### ISSUE TITLE
internal error: binding null type in envBindTypeRef

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#10]
Opened by [henke](https://www.codeplex.com/site/users/view/henke)

In Fsi: 
[Loading X:\logary\src\Logary\WinPerfCounters.fs] 
error FS0192: internal error: binding null type in envBindTypeRef: Generic IKEv1, AuthIP, and IKEv2 

In C:\Program Files (x86)\Microsoft SDKs\F#\3.0\Framework\v4.0\Fsi.exe, Windows 8.1. 
[On this line of code:](https://github.com/logary/logary/blob/723996baa8fad748205dfb1c9203cdf2be7068db/src/Logary/WinPerfCounters.fs#L2654) 

Steps to repro: 
 1) start fsi 
 2) #load "WinPerfCounters.fs"

![screen shot 2014-08-11 at 18 33 19](https://cloud.githubusercontent.com/assets/5175830/5735781/7485c084-9b80-11e4-9ff8-57956f4c4311.png)

>comments
>henke wrote Aug 11, 2014 at 9:36 AM [x] 
>Also, IntelliSense doesn't show the symbols even after changing the commas to underscores.

**Comment by forki** [comment]
Mini-repro:

run fsi with:

    module ``Generic IKEv1, AuthIP, and IKEv2`` =
      [<Literal>]
      let Category = "Generic IKEv1, AuthIP, and IKEv2";;

**Comment by KevinRansom** [comment]
Just testing a fix for this.
