### ISSUE TITLE
F# tooltip errors interfering with tooltip documentation; show both?

### ISSUE THREAD

**Issue by JasonKleban** [Microsoft/visualfsharp#1005]
Yes, I'm doing something wrong - that's why I need to see the documentation for this function so I can fix it or rule it out as the problem.

![documentationhidden](https://cloud.githubusercontent.com/assets/17498172/13673874/0ee2290a-e6a9-11e5-90e3-92b75a6d1589.gif)

I get stuck by this UI glitch all the time.

**Comment by dsyme** [comment]
This can definitely be a problem.

We could do with more details here per CONTRIBUTING.md - an exact repro including code and instructions. We need to be able to know that we've fixed the problem you're actually seeing. Thanks

**Comment by JasonKleban** [comment]
Yes sir.  I don't think I fully understand the circumstances of when this occurs but I'll give it a shot here - probably not very good.

```
/// (Documentation) Use this one for numbers
let generateFunN ( m : int ) = fun i -> m + i

/// (Documentation) Use this one for strings
let generateFunS ( m : string ) = fun s -> m + s

(* This just reverses the params of map to contrive an example 
where the function is based on the 'a of the 'a list instead
of the other way around *)
let mapOver sequence selector = Seq.map selector sequence

let bugged = mapOver [ "a"; "b"; "c" ] (generateFunN 4)       
let  works = mapOver [ "a"; "b"; "c" ] (generateFunS "def")
```

![intellisense behavior](https://cloud.githubusercontent.com/assets/17498172/13707480/dd910bb2-e777-11e5-8b20-38f0b6459c78.gif)

I think the fparsec case I started with has more to do with generics but I reduce that case to this sample.  I tried to make generateFun be generic over anything with (member (+)) but I think I was running into value restriction issues(?)

In the animation there I'd presumably need to read the signature/documentation that generateFunN should be used for numbers and not for strings but I cannot see that because the presumably unhelpful-in-this-case type error is taking precedence.

I'd like to be able to see both, perhaps with the up-down arrows like overloaded signatures typically offer - the error description would just be inserted as the first pane or whatever.

**Comment by dsyme** [comment]
For workarounds - you can also usually press Ctrl-Space on the identifier to get the autocomplete information.

**Comment by dsyme** [comment]
BTW this is how it's always been, I guess I've just got used to it.

**Comment by cloudRoutine** [comment]
We list the errors above the intellisense in Ionide

![](http://i.imgur.com/K93550K.png)

it's quite useful in less trivial cases :smiley:

**Comment by smoothdeveloper** [comment]
This is annoying behaviour in VS when having warning as errors and getting the `symbol is not used` message.

Type information and member documentation should always appear in tooltip if the type checking is done succesfully, it would be great to have this behaviour change in future version of Visual F#.

**Comment by saul** [comment]
Not sure exactly what PR this was fixed in, but here's what current master looks like:
![image](https://cloud.githubusercontent.com/assets/64654/21593959/0bae95a0-d115-11e6-8d6d-a6c72b49d35f.png)

This can be closed now.
