### ISSUE TITLE
Opening files takes about a second or more in large solutions

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1012]
Scenario:
- open several *.fs files in a large solution
- wait while devenv.exe stops consuming CPU
- switch from the active document to another

Result: it takes about 1 second or more with freezing UI thread.

![image](https://cloud.githubusercontent.com/assets/873919/13873279/78789dbe-ed01-11e5-99be-f648e8545126.png)

(purple areas are UI freezes)

![image](https://cloud.githubusercontent.com/assets/873919/13873271/5fc69ba4-ed01-11e5-8c7a-90679470edeb.png)

It spends all the time in a deep recursive `ParseCanonicalName` call. Maybe it's a bug?

**Comment by dsyme** [comment]
Agreed this is broken, and I've noticed this performance problem.  (BTW is that dotTrace above?)

The source code for ParseCanonicalName is in HierarchyNode.cs.  We inherited this code from the C~ project system sample.  It is recursive, and seems to scan along a linked list looking along a linked list and down a tree for a hierarchy item whose Url matches a particular name.  

TO be honest I'm not even sure what the code for ``SelectionElementValueChangedListener.OnElementValueChanged`` is even doing (it's in ``vsintegration\src\FSharp.ProjectSystem.FSharp\Project.fs``.  After finding the matching Hierarchy node based on expensive name comparisons, it then seems to throw all the information away.  I wonder what would change if we just removed the whole ``SelectionElementValueChangedListener`` 


@otawfik-ms @jaredpar Perhaps you might know this?  Or perhaps @vasily-kirichenko and @dungpa you might be able to see what this is about?

**Comment by dsyme** [comment]
Tentative fix here: https://github.com/Microsoft/visualfsharp/pull/1048

**Comment by dsyme** [comment]
@v2m says 

> At glance I would there should be no harm to remove it – I don’t recall any undercover side-effects that will justify this code.

**Comment by dsyme** [comment]
@vasily-kirichenko I tried the fix on VisualFsharp.sln and didn't notice an appreciable difference.  Could you make a repro project?  I'd imagine it depends on project size. We should really add some "big project" tests under ``tests\projects``, perhaps you could add one that contains many small files?

**Comment by vasily-kirichenko** [comment]
@dsyme yes, it was dotTrace in "Timeline" mode (the only mode that brings meaningful results for my taste). 

Yes, this issue is reproduced on a large solution (200 projects, 100 of which are F# ones). No large _projects_ in that solution though, each of them includes up to 10-15 small to middle size files (up to 1000 lines of code, often much less), usually the projects are very small. The notable thing is that the issue is reproduced on _any_ file, regardless of the size of a project or file itself.

I would love to test this fix, but I have always had problems with compiling VFT, actually I've not managed to make it work at all. Is there binaries to try? Should I do the testing in a VM in order to not mess up my current VS + VFT installation?

**Comment by dsyme** [comment]
To trial this fix you should b able to just install the VSIX from the AppVeyor artifacts.  Then test the fix, and uninstall (We have a harder time testing things that invoke the F# compiler from VS or MSBuild builds, but that's not the case here.)

However the build is busted right now, so this PR didn't produce a result, fixing in https://github.com/Microsoft/visualfsharp/pull/1052

**Comment by vasily-kirichenko** [comment]
Do you mean EnableOpenSource.vsix? I installed it and now VS cannot load any F# project and shows the following error dialog:

![image](https://cloud.githubusercontent.com/assets/873919/14408453/541c2bde-fefe-11e5-8330-89d69d012912.png)

**Comment by vasily-kirichenko** [comment]
I cannot find any mentions of any *.VSIX files in any of the guides. I remember there were steps to test VFT VS integration, which included installing EnableOpenSource.vsix.

**Comment by dsyme** [comment]
Yes, I meant EnableOpenSource.vsix from the zip [here](https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/0.0.1.1779/job/fox36022rgr2fd30/artifacts). 

It could you need to run [``src\update.cmd``](https://github.com/Microsoft/visualfsharp/blob/master/src/update.cmd) to turn of strong name checks. ``sn -Vr *,*`` might do the trick, turning them off globally on the machine.

For some reason the instructions about [EnableOpenSource.vsix](https://github.com/Microsoft/visualfsharp/blob/master/DEVGUIDE.md#4-optional-install-the-visual-f-ide-tools) were dropped in a recent integration. I don't understand why. I've added them back in.

**Comment by dsyme** [comment]
I just installed and used that VSIX OK.  Let me know if strong name checking is the problem? Thanks

**Comment by vasily-kirichenko** [comment]
sn -Vl output:

```
C:\WINDOWS\system32>sn -Vl

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

No verification entries registered
```

**Comment by vasily-kirichenko** [comment]
Do I need to build VFT locally before launching https://github.com/Microsoft/visualfsharp/blob/master/src/update.cmd?

**Comment by dsyme** [comment]
I think the only step from ``update.cmd`` you need is to turn off strong name checking.  So 

    sn -Vr *,*

should be enough, or add the entries one by one manually.

**Comment by vasily-kirichenko** [comment]
Wow, it works! Thanks a lot. Will profile it on my large solution soon.

**Comment by vasily-kirichenko** [comment]
Before
![image](https://cloud.githubusercontent.com/assets/873919/14411494/9696f1e8-ff52-11e5-9bf9-7f9a86917153.png)
After
![image](https://cloud.githubusercontent.com/assets/873919/14411486/59b2bc8a-ff52-11e5-8f8b-e2050ca59bbc.png)
Before
![vft_old](https://cloud.githubusercontent.com/assets/873919/14411503/ba9d3e3a-ff52-11e5-826d-235d421adbd9.gif)
After
![vft_new](https://cloud.githubusercontent.com/assets/873919/14411505/c36df2ca-ff52-11e5-8164-3e00ae88df3d.gif)

**Comment by vasily-kirichenko** [comment]
It's a great improvement indeed, but it does not fix slowness of _opening_ files. Look at profiler report, here I open two documents:

![image](https://cloud.githubusercontent.com/assets/873919/14411523/716e26d8-ff53-11e5-9458-00c0154e14f3.png)

Select the second UI freeze:

![image](https://cloud.githubusercontent.com/assets/873919/14411552/182fff46-ff54-11e5-9d17-706ac4b49ec9.png)

Select the top line (Url.ctor):

![image](https://cloud.githubusercontent.com/assets/873919/14411543/dc9cea70-ff53-11e5-8dc8-03c27b058c0f.png)

**Comment by dsyme** [comment]
Hmmm... The call to IsDocumentInProject must be coming from VS, so the only choice here is to implement IsDocumentInProject more efficiently.  Currently it looks like FindChild is doing a linear search. I'm somehow surprised that it's particularly slow because you really have to have a lot of string comparisons to make a linear search noticeable.

I'm not really sure what the best solution is here.  Using a different lookup would mean maintaining some kind of index. Perhaps we could take a look at the Roslyn Project system (which is not open source) or look a the Shared Project System code to see if there have been fixes in this area.  Or we somehow just improve the perf.

**Comment by vasily-kirichenko** [comment]
Closing this VS 2015 issue.
