### ISSUE TITLE
Select all before sending to F# Interactive trims the string

### ISSUE THREAD

**Issue by mrakgr** [Microsoft/visualfsharp#1013]
```
""".
.
.""" |> fun x -> x.Split [|'\n'|]
     |> Array.map (fun x -> x.Length)
     |> printfn "%A"
```
When compiled and or executed in fsi.exe from the command line the above prints `[|2; 2; 1|]`. When sent to F# Interactive from the VS IDE by selecting it, it prints `[|1; 1; 1|]`. It is a bit trivial, but I thought this might be a bug.

**Comment by smoothdeveloper** [comment]
@mkgr is it a case of `\n` vs `\r\n``?

**Comment by mrakgr** [comment]
It might be given that it gets fixed by `TrimRight()`.

**Comment by dsyme** [comment]
Yes, I think this is `\n` vs `\r\n`.  It feels like it is by design in that case.

**Comment by mrakgr** [comment]
Ok, no big deal then.
