### ISSUE TITLE
Set<T> gives weird error on nested loop

### ISSUE THREAD

**Issue by dnallicus** [Microsoft/visualfsharp#1020]
Title:Set<T> gives weird error on nested loop

Description:Set<T> gives weird error on nested loop

Repro Steps:
`let s1 = Set.ofArray [|"1"|]`
`let s2 = Set.ofArray [|"1"|]`
`for x in s1 do`
&nbsp;&nbsp;&nbsp;&nbsp;    `for y in s2 do`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        `System.Console.WriteLine(x)`

Expected:
no exception
Actual:
`error FS0971: Undefined value 'x : string'`
Severity: Minimal

Version: 
Microsoft (R) F# Interactive version 14.0.23413.0
4.4.0 version of FSharp.Core

**Comment by forki** [comment]
I can confirm. This happens in fsi.

The compile error only happens for me in fsi and only when s2 is a set. All is fine if s2 is an array or list. 

All is fine if I compile the code as part of a command line project.

**Comment by forki** [comment]
Just tried with fsi from master and can't reproduce any more. I guess it's fixed.

**Comment by forki** [comment]
https://github.com/Microsoft/visualfsharp/pull/1033 shows this is already fixed

**Comment by panesofglass** [comment]
I think F# 4.1 may have regressed this issue. I just updated and see the same thing happening within a nested loop. I'll try to create a small repro to verify. cc @ctaggart
