### ISSUE TITLE
To the power of -operator (**) notation not accepted

### ISSUE THREAD

**Issue by jesterKing** [Microsoft/visualfsharp#1030]
```
> let Power (a:float) b = (**) a b;;

  let Power (a:float) b = (**) a b;;
  -----------------------------^

stdin(4,30): error FS0003: This value is not a function and cannot be applied
```

It is possible to write ```(**)``` as infix operator, but that makes it impossible to pass the function on as parameter, i.e.
```
let domath (a:float) (b:float) op = op a b
domath 2.0 -2.0 (+)
domath 2.0 -2.0 (-)
domath 2.0 -2.0 (**) // this one will fail
```

In Visual Studio 2015 writing ```let r = (**) 2.0 -2.0``` highlights the ```(**)``` as comment
Also tested with ```Microsoft (R) F# Interactive version 14.0.23413.0```

For now I am circumventing with

```module Utils =  let Power (a:float) b = a ** b```

and passing ```Utils.Power``` as the function onward.

**Comment by rojepp** [comment]
You can get around the conflict with block comment by using spaces:

```fsharp
let Power (a:float) b = ( ** ) a b
 ...
domath 2.0 -2.0 ( ** )
```

**Comment by jesterKing** [comment]
Thanks, didn't try that, but that works.

I still would expect ```(**)``` to work based on the arithmetic operator documentation alone, but now reading doc on code commenting it makes sense.
