### ISSUE TITLE
Build support ignores LogicalName on EmbeddedResource items

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#1050]
When an EmbeddedResource is added to a project, and you manually add a LogicalName entry for an item, the LogicalName entry is ignores
#### Repro steps
1. Compile the project `tests\projects\Sample_VS2012_FSharp_ConsoleApp_net45_with_resource` from http://github.com/fsharp/fsharp
2. Look at the command line flags used and the resource names generated (using ILDASM), particularly for the resources `ResxResourceWithLogicalName` and `NonResxResourceWithLogicalName`
#### Expected behavior

For a C# we get command line flags:
    /resource:NonResxResourceWithLogicalName.txt,The.Explicit.Name.Of.NonResxResourceWithLogicalName 

and resource name:

```
.mresource public The.Explicit.Name.Of.NonResxResourceWithLogicalName
```
#### Actual behavior

For F# on Windows, we get

```
--resource:NonResxResourceWithLogicalName.txt 
```

and

```
.mresource public NonResxResourceWithLogicalName.txt
```
#### Known workarounds

None known, except just not using the feature.
#### Related information

See also two other discrepancies 
- https://github.com/Microsoft/visualfsharp/issues/922
- https://github.com/fsharp/fsharp/issues/562
- .NET Desktop CLR

**Comment by dsyme** [comment]
It is not simple to work out why LogicalName is being ignored.  We could probably add support for once we  work out what's going wrong.  

Browsing the various sources for F# and MSBuild it seems the only substantive place where LogicalName gets mentioned for C# is [here](https://github.com/Microsoft/msbuild/blob/c1459f5cbd36f2c33eafc8f4ff087f6ee84c3640/src/XMakeTasks/CreateManifestResourceName.cs#L216) but that doesn't seem to be a place where the information is actually consumed.  So I don't know how C# processes this item.  Much of this code is common with F# in any case, so it's somewhat surprising that it doesn't just work.

**Comment by nosami** [comment]
I'll take another look at this when I get back home. I managed to figure out how all this stuff worked when I last looked at it.

**Comment by 0x53A** [comment]
Just wanted to note that I hit this when I experimented a bit with a netcore fsproj (new sdk). For now I have worked around it by creating a C# project just to hold the resources ...
