### ISSUE TITLE
Suggestion: add .fsx (and .csx) item template to all projects

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#1056]
F# has been since day one a great story for .NET scripting.

Currently, in a C# project, adding a script file lists those templates:
- CoffeeScript File
- JavaScript File
- JSX File
- TypeScript File
- TypeScript JSX File
- Windows Script Host

![Image](https://cloud.githubusercontent.com/assets/87944/14363234/7529218a-fd03-11e5-86f6-616ae17af404.png)

F# script files should join the party, for any .NET language project type.

**Comment by dsyme** [comment]
This belongs in the roslyn repo if you want to add the F# script type to other language tooling
