### ISSUE TITLE
Visual F# Tools leak memory while reloading solutions

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#106]
Scenario:
◾Disable VFPT in VS if it is installed 
◾Open VFPT solution (https://github.com/fsprojects/VisualFSharpPowerTools), VS occupies ~ 300MB RAM 
◾Repeat the following steps 15 times: (1) Switch to a new git branch (2) Reload the solution (3) Rebuild the solution 
◾VS now occupies ~ 1.7 GB RAM

Context: 
We are hunting down memory leaks in Visual F# Power Tools. It turned out FSharp.Compiler.Service (FCS) leaked memories when Xaml type providers (FsXaml) didn't dispose resources correctly. These bugs have been fixed in FCS and FsXaml. See the discussion at  https://github.com/fsharp/FSharp.Compiler.Service/issues/158. 

After bug fixing, there are still memory leaks. I think Visual F# Tools has the same issue where type providers are in use. We did profile using PerfView without enabling VFPT. Here is a diff of two snapshots where we reload and rebuild solutions twice. 

https://cloud.githubusercontent.com/assets/941060/3277997/c56876ec-f39f-11e3-8042-4840c6cffffd.png 

https://cloud.githubusercontent.com/assets/941060/3278000/13a16d6e-f3a0-11e3-97cd-b994b8086d8e.png 

Configuration:
* Visual Studio 2013 
* Windows 7 
* A recent build of Visual F# Tools 3.1.1

I believe the fix should be similar to that of FCS. Here are relevant commits: 
https://github.com/fsharp/FSharp.Compiler.Service/commit/a325df24d3a1a96524742fe0946407c69b02036e 
https://github.com/fsharp/FSharp.Compiler.Service/commit/4e7c8bca24518fb9c77469fa6715d26b0eca3a63 

Let me know if you need more information.

**Comment by dsyme** [comment]
We should apply the linked fix to VF# Tools.

**Comment by forki** [comment]
> We should apply the linked fix to VF# Tools.

I tried to do this, but there are more commits involved.

**Comment by latkin** [comment]
This was partially addressed by recent fix from @dsyme, but it looks like we still leak a bunch on reload.  I've left it open to keep tracking remaining leaks.

Moving out of VS 2015 milestone, though.

**Comment by dsyme** [comment]
@latkin AFAIK a well written type provider shouldn't leak on reload.  What repro steps should I follow to check this out (I'm ok with this being vNext)

**Comment by latkin** [comment]
Sorry, I was not specific enough.  I trust that the type provider leak in particular is now fixed, but the general problem indicated by the title of the bug ("Visual F# Tools leak memory while reloading solutions") is not.

**Comment by dsyme** [comment]
OK, got it, thanks

**Comment by dsyme** [comment]
Re memory leaks - I noticed another case where the Fsharp.Compiler.Service code is correctly disconnecting a callback when a prjoect is unloaded, see https://github.com/fsharp/FSharp.Compiler.Service/blob/0c37365691e5568adfc357fc915eed645b45481d/src/fsharp/CompileOps.fs#L4093.  Specifically we are missing this commit: https://github.com/fsharp/FSharp.Compiler.Service/commit/4e7c8bca24518fb9c77469fa6715d26b0eca3a63
