### ISSUE TITLE
Fold ILMethodVirtualInfo, MethodBody & MethodCodeKind types of absil/il.fsi into ILMethodDef

### ISSUE THREAD

**Issue by WilliamBerryiii** [Microsoft/visualfsharp#1066]
A review comment, existing in the codebase prior to being added to git repository, made the suggestion to fold the ILMethodVirtualInfo, MethodBody & MethodCodeKind types in the absil/il.fsi file into ILMethodDef.

See: https://github.com/Microsoft/visualfsharp/blob/master/src/absil/il.fsi#L1148

Please update comments in source if this issue is to be closed without moving the noted types.

**Comment by dsyme** [comment]
I deleted the comment via a direct edit, thanks
