### ISSUE TITLE
Review substitute function proposal noted in absil/ilreflect.fs

### ISSUE THREAD

**Issue by WilliamBerryiii** [Microsoft/visualfsharp#1067]
A comment in absil/ilreflect.fs suggests the replacement of the convTypeRefAux function with code proposed in the proceeding comment. See here: https://github.com/Microsoft/visualfsharp/blob/master/src/absil/ilreflect.fs#L339

**Comment by dsyme** [comment]
I think we can close this - the code speaks for itself and something in the future may lead us to action this.  For now leave the code in place - remove the word REVIEW if you like. Thanks
