### ISSUE TITLE
Complete cases for convTypeAux function of absil/ilreflect.fs

### ISSUE THREAD

**Issue by WilliamBerryiii** [Microsoft/visualfsharp#1068]
A review comment in absil/ilreflect.fs makes note of completing the match cases.  See here: 
https://github.com/Microsoft/visualfsharp/blob/master/src/absil/ilreflect.fs#L548

**Comment by dsyme** [comment]
I think we can close this - something in the future may lead us to complete these cases, but we don't need to track this individually  For now leave the comment in place please - remove the word REVIEW if you like. Thanks
