### ISSUE TITLE
Test suite failure in measures/test.fsx - d

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#107]
Originally opened on [CodePlex](https://visualfsharp.codeplex.com/workitem/85) by [ranma42](https://www.codeplex.com/site/users/view/ranma42)

Running:
```fsharp
cd tests/fsharp/core
./run-all.sh
```
The test fails with this message:
...
Running math/measures/test.fsx....
```
-------------------
Failures in math/measures/test.fsx
    FAILED: d
-------------------
```
...
```
FAILURE: math/measures/test.fsx - d
```
The error message is somewhat misleading, because there is no measures dir inside math (it is located in core). The interactive seems to indicate that this failure might be caused by localization:
```fsharp
> (2.0M).ToString();;
val it : string = "2,0"
```
The string corresponding to "2.0M" is "2,0", while the test expects it to be "2.0". 
I am running this in Mono in an Italian locale. Does this test assume an English locale? Or is this a bug of the Mono implementation of Decimal.ToString() ?

**Comment by latkin** [comment]
I've got a fix for this
