### ISSUE TITLE
coreclr\bin\FSharp.Core.dll has TargetFrameworkAttribute "Profile7"

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#1072]
After a ``build coreclr``, the file ``Release\coreclr\bin\FSharp.Core.dll`` contains a TargetFrameworkAttribute mentioning ``Profile7``.  This seems unexpected.

#### Repro steps

Provide the steps required to reproduce the problem

1. ``build coreclr``

2. ``ildasm Release\coreclr\bin\FSharp.Core.dll``

3. Look at the TargetFrameworkAttribute

#### Expected behavior

A DLL with a TargetFrameworkAttribute mentioning something like ``netstandard`` or ``netcore`` or...

#### Actual behavior

A DLL with a TargetFrameworkAttribute mentioning ``Portable7``

```
.custom instance void [System.Runtime]System.Runtime.Versioning.TargetFrameworkAttribute::.ctor(string) = ( 01 00 2A 2E 4E 45 54 50 6F 72 74 61 62 6C 65 2C   // ..*.NETPortable,
                                                                                                              56 65 72 73 69 6F 6E 3D 76 34 2E 35 2C 50 72 6F   // Version=v4.5,Pro
                                                                                                              66 69 6C 65 3D 50 72 6F 66 69 6C 65 37 01 00 54   // file=Profile7..T
                                                                                                              0E 14 46 72 61 6D 65 77 6F 72 6B 44 69 73 70 6C   // ..FrameworkDispl
                                                                                                              61 79 4E 61 6D 65 14 2E 4E 45 54 20 50 6F 72 74   // ayName..NET Port
                                                                                                              61 62 6C 65 20 53 75 62 73 65 74 )                // able Subset

```

#### Related information 

master branch

**Comment by dsyme** [comment]
I think this is the culprit: https://github.com/Microsoft/visualfsharp/blob/master/src/FSharpSource.targets#L233

**Comment by dsyme** [comment]
Notes to self about how this repo builds F# CoreCLR stuff using MSBuild (from looking in FSharp.Source.targets):

* When compiling CoreCLR stuff with MSBuild, we import _both_  ``Microsoft.DotNet.BuildTools\...\Build.Common.Targets`` and ``Microsoft.Portable.FSharp.Targets``.  I could imagine that's risky in the long run and that we need might a standard formula for this.  

```
  <Import  Condition="'$(TargetFramework)'=='coreclr'" Project="$(BuildToolsDir)Build.Common.Targets" />
    ...
        <FSharpTargetsPath>..\Proto\$(protoCLIDir)\bin\Microsoft.Portable.FSharp-proto.Targets</FSharpTargetsPath>
  <Import Condition="'$(ProjectLanguage)' == 'FSharp'" Project="$(FSharpTargetsPath)"/>
```


* In this repo, When compiling CoreCLR stuff with MSBuild, we set these, I'm not sure if it's needed but it feels like typical target files would need to set these or their future equivalents.

```
    <NuGetPackagesPath Condition="'$(NuGetPackagesPath)' == ''">$(FSharpSourcesRoot)\..\packages</NuGetPackagesPath>
    <PackagesDir>$(NuGetPackagesPath)\</PackagesDir>

    <NuGetToolPath Condition="'$(NuGetToolPath)' == ''">$(FSharpSourcesRoot)\..\.nuget\</NuGetToolPath>
    <NuGetConfigCommandLine>-ConfigFile "$(NuGetConfigFile)"</NuGetConfigCommandLine>

    <NugetRestoreCommand>"$(NuGetToolPath)NuGet.exe"</NugetRestoreCommand>
    <NugetRestoreCommand>$(NugetRestoreCommand) install</NugetRestoreCommand>
    <NugetRestoreCommand>$(NugetRestoreCommand) -OutputDirectory "$(NuGetPackagesPath)"</NugetRestoreCommand>
    <NugetRestoreCommand>$(NugetRestoreCommand) -Config "$(NuGetToolPath)NuGet.Config"</NugetRestoreCommand>

    <DnuRestoreCommand>"$(NuGetToolPath)NuGet.exe"</DnuRestoreCommand>
    <DnuRestoreCommand>$(DnuRestoreCommand) restore</DnuRestoreCommand>
    <DnuRestoreCommand>$(DnuRestoreCommand) -OutputDirectory "$(NuGetPackagesPath)"</DnuRestoreCommand>
    <DnuRestoreCommand>$(DnuRestoreCommand) -Config "$(NuGetToolPath)NuGet.Config"</DnuRestoreCommand>
```

There is this funky setting (maybe Paket would like this :) )

    
    <NuGetIngoreLockFile>true</NuGetIngoreLockFile>

**Comment by dsyme** [comment]
I tried these settings in FSHarp.Source.targets and they seem to correct the problem, at least the attribute now looks as @enricosada assures me "dotnet cli" CoreCLR binaries look.  

    
    
    
    
    
    <TargetFrameworkProfile>portable7</TargetFrameworkProfile>                            
    <TargetFrameworkMoniker>.NETStandard,Version=$(TargetFrameworkVersion)</TargetFrameworkMoniker> 
    <TargetFrameworkIdentifier>.NETStandard</TargetFrameworkIdentifier>                           
    <TargetFrameworkMonikerDisplayName>.NET Standard Profile $(TargetFrameworkVersion)</TargetFrameworkMonikerDisplayName>                           
    <ImplicitlyExpandTargetFramework>false</ImplicitlyExpandTargetFramework>           

However I don't know what the TargetFrameworkMonikerDisplayName should be or if it really matters

**Comment by enricosada** [comment]
the .net cli generate this assemblyinfo files (on `dotnet build` )

[dotnet-compile.assemblyinfo.fs](https://github.com/Microsoft/visualfsharp/files/219386/dotnet-compile.assemblyinfo.fs.txt)

```fsharp
[<assembly:System.Runtime.Versioning.TargetFrameworkAttribute(".NETStandard,Version=v1.5")>]
```

[dotnet-compile.assemblyinfo.cs](https://github.com/Microsoft/visualfsharp/files/219391/dotnet-compile.assemblyinfo.cs.txt)

```csharp
[assembly:System.Runtime.Versioning.TargetFrameworkAttribute(".NETStandard,Version=v1.5")]
```

**Comment by enricosada** [comment]
ok, btw added https://github.com/dotnet/netcorecli-fsc/issues/7 to track empty attributes

**Comment by KevinRansom** [comment]
Yeah the profile7 was a nasty hack to get the tooling to work a year ago.  I actually don't know what the right magic is these days but I will chat with Eric and find out.

**Comment by dsyme** [comment]
I checked the latest and this attribute now has the correct value
