### ISSUE TITLE
Remove old .bat files under tests\fsharp

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#1074]
This is a reminder to ourselves that now that https://github.com/Microsoft/visualfsharp/pull/90 is in and coreclr is merged it's time to remove the `*.bat` files under `tests\fsharp` in favour of the `*.fsx` drivers. :stars: :stars: 

@KevinRansom I know you're enabling some coreclr testing via these `*.bat` files. I guess whoever does the removal (probably @enricosada or myself) will just follow the links about what's enabled and make sure that's enabled for CoreCLR too.  Let us know if there's anything specific we need to know, otherwise we can discuss in the removal PR.

**Comment by enricosada** [comment]
yes, let me do that :smile:

**Comment by KevinRansom** [comment]
Well .. if you do please make sure to coreclr smoke tests still work.

**Comment by dsyme** [comment]
@KevinRansom Absolutely!  And maybe we can enable some more :)

**Comment by KevinRansom** [comment]
☺

**Comment by enricosada** [comment]
ok i started, i'll check coreclr for sure

**Comment by dsyme** [comment]
Done
