### ISSUE TITLE
problems with packages.config, and how conservative usage of paket would help

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#1075]
I have been looking a bit at history on this file:

https://github.com/Microsoft/visualfsharp/commits/master/packages.config

In many occurences, changes to this file is associated (disregarding change in code) to changes in project files, because of the way nuget is used and how references are defined in project files.

It seems to me that it causes this kind of problems:
* unnecessary churn
* possible inconsistencies creeping in project files
* have to specify and care about transitive dependencies in a too fine grained way
* unnecessary hindrance when updating dependencies

It is possible to use paket just as a package puller, only paket.dependencies file, without introducing usage of paket.references which is nice but might not fit some use cases (although it can definitely be considered as a later step).

This would bring those advantages:

* packages land in a folder which doesn't change at every change of the version of given dependency
* project files would mostly stay the same (less work on merge, review, no inconsistency if someone miss to commit the project file)
* resolution of transitive dependency instead of listing all the dependencies and managing their versions manually (while still maintaining tight control when it makes sense, definitely possible with paket)

For now this would obviously not handle project.json stuff, but it seems those are already completely disjoint from packages.config (and will generate a lot of churn too, but not the issue here)

I don't think the changes to upgrade maintainers' experience with packages.config would be that hard, mostly:

* add .paket folder with the bootstrapper (and deprecate .nuget)
* add paket.dependencies and paket.lock
* fix project files referencing current nuget packages
* have maintainers all become happy users of paket (really easy to pick-up and helpful in common usecase related to dependencies)

**Comment by dsyme** [comment]
Closing old discussion
