### ISSUE TITLE
Patterns are unreadable in VS dark theme

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/visualfsharp#1076]
Check out https://twitter.com/basarat/status/722277482280267776

![](https://pbs.twimg.com/media/CgXp8NfUAAAU1sK.jpg)

@basarat

**Comment by hmemcpy** [comment]
Hi! I'm not sure it's related, but do you happen to have Visual F# PowerTools installed, and have Depth Colorization enabled?

**Comment by basarat** [comment]
> Visual F# PowerTools installed

nope

**Comment by hmemcpy** [comment]
Is it just the VS dark theme, or are you using any custom one? If so, would you mind exporting it (Tools - Export Settings), and upload the file here?

**Comment by basarat** [comment]
> upload the file here

wouldn't help now as I have it fixed. This is the setting I was after (https://twitter.com/basarat/status/722277482280267776): 

![](https://pbs.twimg.com/media/CgYLishUYAEZNpt.jpg:large)

If this is not the default then it might be specific to me and can be closed :rose:

**Comment by OkayX6** [comment]
This comes in fact from Visual F# Power Tools...

**Comment by basarat** [comment]
> This comes in fact from Visual F# Power Tools...

I didn't install it for VS2015 (which I installed recently) but then again someone setup VS2013 / machine image for me so they might have done it. I'll verify when I get to office today and report back :rose:

**Comment by hmemcpy** [comment]
Maybe this is due to settings synchronization. Maybe the fonts and colors settings got synched, but the extension did not...

**Comment by dungpa** [comment]
@hmemcpy This is an existing bug https://github.com/fsprojects/VisualFSharpPowerTools/issues/1359#issuecomment-211729978. Do you have any idea to fix this?

**Comment by hmemcpy** [comment]
@dungpa not yet :) But I'm fixing another issue, I might as well try my best figuring out this one!

**Comment by basarat** [comment]
The error came back by itself today. And yes I do have visual f# power tools installed. 

![image](https://cloud.githubusercontent.com/assets/874898/14664827/aca56b6a-0711-11e6-913f-0754ac7be7e7.png)

**Comment by hmemcpy** [comment]
Happened to me yesterday as well, when I was playing with the themes... I'd say this is definitely a bug in VFPT.

**Comment by dsyme** [comment]
Closing as this is an issue with Visual F# Power Tools
