### ISSUE TITLE
FSharpProjectPackage Initialization Performance Hit

### ISSUE THREAD

**Issue by OmarTawfik** [Microsoft/visualfsharp#1081]
This bug is for tracking optimization of `FSharpProjectPackage` initialization method. This package is one of the packages being loaded for retrieving editor font and colors and if cache is not present, the package will be loaded in first editor open regardless of editor type.

Traces show the costly operation is getting `GlobalProjectCollection` through MSBuild during package initialize method. If this is not needed for package init or fonts and color, we should defer to the point needed in order to ensure first time an editor is opened is not delayed.

Note package in question is being loaded because it registers a language service and editor is trying to get fonts and colors from all language services. The code will try to load your language service and cast it to `IVsProvideColorableItems`.

If you are not implementing that interface, you can modify your language service registration to `include RequestStockColors = true` so that your package is skipped during this operation.

**Comment by cartermp** [comment]
This is currently being tracked in VSTS and affects the XML editor colorization

**Comment by dsyme** [comment]
@cartermp This has been "Urgency Now" for a while - do we actually have to fix this?

**Comment by cartermp** [comment]
This was fixed in the middle of last week.  Long story short, we broke XML colorization globally in VS for some people if they used the Dark theme.
