### ISSUE TITLE
Build broken since it doesn't find sigdata

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1087]
![image](https://cloud.githubusercontent.com/assets/57396/14672631/554b7840-06f9-11e6-90ca-b267be64fbec.png)

#### Repro steps

* Clone repo
* run build.cmd

#### Related information 

Provide any related information 

* Operating system: Win 10
* Branch: master
* Visual Studio Version 2015 installed

Anyone seen this?

**Comment by KevinRansom** [comment]
Can you check to see if you have an FSharp.Core v4.4.1.0 in the GAC?

We used to place the dll in the GAC, but we did some work to remove all fsharp dll's from the GAC inorder to support the XCopy install for VS it may be possible that you have one in the GAC and the compiler is using that dll.  If you have an fsharp.core.dll in  the GAC and removing it causes your build to work again, then raise an issue because that is a bug.

Kevin

**Comment by KevinRansom** [comment]
Nope ... I just tried to repro this by putting fsharp.core.dll in the GAC and it builds fine.

Can you add /v:diag to this line:

````
%_msbuildexe% %msbuildflags% build-everything.proj /p:Configuration=%BUILD_CONFIG% /v:diag
@if ERRORLEVEL 1 echo Error: '%_msbuildexe% %msbuildflags% build-everything.proj /p:Configuration=%BUILD_CONFIG%' failed && goto :failure
````

and then type:

build > build_log

And attach the log here:

Thanks

Kevin

**Comment by forki** [comment]
sure. 
[build_log.txt](https://github.com/Microsoft/visualfsharp/files/231326/build_log.txt)

**Comment by KevinRansom** [comment]
You have a genuine mystery here:

It looks like the files are copied by the build task to the right spot : down in line 26091
````
09:21:34.750    12>Ziel "CopyToBuiltBin: (Ziel-ID:43)" in Projekt "d:\code\visualfsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj" (Ziel "Compile" ist davon abh„ngig):
                   Hinzugefgte Elemente: BuiltProjectOutputGroupKeyOutput=obj\release\net40\\FSharp.Core.sigdata
                   Hinzugefgte Elemente: BuiltProjectOutputGroupKeyOutput=obj\release\net40\\FSharp.Core.optdata
                   Die Copy-Aufgabe aus der Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a-Assembly wird verwendet.
                   Copy-Aufgabe (Aufgaben-ID: 20)
                     Aufgabenparameter:SourceFiles=obj\release\net40\\FSharp.Core.sigdata (Aufgaben-ID: 20)
                     Aufgabenparameter:DestinationFolder=..\..\..\release\net40\bin\ (Aufgaben-ID: 20)
                     Aufgabenparameter:SkipUnchangedFiles=True (Aufgaben-ID: 20)
                     Die Datei wird von "obj\release\net40\\FSharp.Core.sigdata" in "..\..\..\release\net40\bin\FSharp.Core.sigdata" kopiert. (Aufgaben-ID: 20)
                   Ausfhren der Copy-Aufgabe beendet. (Aufgaben-ID: 20)
                   Copy-Aufgabe (Aufgaben-ID: 21)
                     Aufgabenparameter:SourceFiles=obj\release\net40\\FSharp.Core.optdata (Aufgaben-ID: 21)
                     Aufgabenparameter:DestinationFolder=..\..\..\release\net40\bin\ (Aufgaben-ID: 21)
                     Aufgabenparameter:SkipUnchangedFiles=True (Aufgaben-ID: 21)
                     Die Datei wird von "obj\release\net40\\FSharp.Core.optdata" in "..\..\..\release\net40\bin\FSharp.Core.optdata" kopiert. (Aufgaben-ID: 21)
                   Ausfhren der Copy-Aufgabe beendet. (Aufgaben-ID: 21)

````
And when we build FSharp.LanguageService.dll the build is reading fsharp.core.dll from the right place:
````
-r:d:\code\visualfsharp\release\net40\bin\FSharp.Core.dll
````
And yet almost a minute later the build complains:
````
09:22:31.469    
   15>FSC : error FS1223: FSharp.Core.sigdata not found alongside FSharp.Core [d:\code\visualfsharp\vsintegration\src\FSharp.LanguageService\FSharp.LanguageService.fsproj]
````

So the fsharp.core location it is searching for optdata must be an unexpected location.  I shall change the message to display the location it looked for fsharp.core.sigdata and where it was using fsharp.core.dll, that will make things clearer I think.

**Comment by forki** [comment]
Yes that sounds like a big win for many applications. Missing fsharp.core +
sigdata issues are very hard to debug. So adding more verbose error is a
good idea

**Comment by forki** [comment]
Ok trying to add that output myself

**Comment by forki** [comment]
Ok seems I fucked up. In order to add that additional output I had to rebuild proto compiler.
So I did `git clean -xdf`and rerun build.cmd. Now everything builds fine. I swear I tried that before.

Anyways now it magically builds as expected and I will send a PR which changes the error messages so that future me can debug this better.

**Comment by forki** [comment]
created https://github.com/Microsoft/visualfsharp/pull/1098
