### ISSUE TITLE
Add support for creating and placing files in folders

### ISSUE THREAD

**Issue by kzu** [Microsoft/visualfsharp#1095]
This is a known limitation that is pretty serious for things like [Android projects](http://stackoverflow.com/questions/32556632/how-to-bypass-visual-studios-f-project-folder-limitations-on-xamarin-android/32609700#32609700) which require specific folder structures, but I'm guessing for any app that has more than a handful of files.

A few things that should happen for this support to be first-class:

1 - Enable Add > New Folder command just like any other VS project type (NOTE: this currently DOES show up if you right click on a manually-created folder via the .fsproj!)
2 - When files are added to folder, ensure they are serialized in the right order in the .fsproj (or alternatively [remove that weird limitation](http://stackoverflow.com/questions/32556632/how-to-bypass-visual-studios-f-project-folder-limitations-on-xamarin-android/32609700#32609700)??)

**Comment by saul** [comment]
@KevinRansom Closed by #2692
