### ISSUE TITLE
Build opens flickering command line windows

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1099]
If I run `build.cmd all` on my Windows 10 machine I see command line windows popping up during build. This is a bit annoying since it steals my concentration when I run the full build in background.

I think we discussed this before and saw improvement of this. But somehow this is back. I assume it's related to nunit 3, but I'm not completely sure. /cc @enricosada

**Comment by forki** [comment]
Even more serious: it steals keybord focus from the window that I was working on

**Comment by smoothdeveloper** [comment]
(@forki the same happens in paket integration tests :smile:)

**Comment by forki** [comment]
Nope. Not if you run from Powershell prompt. Which is not possible here
since then all the MSBuild stuff is not working. In paket this is working
because fake detects MSBuild path and does the right thing.

**Comment by dsyme** [comment]
Yes, it would be great to track down which test is doing this.

I think I've sometimes seen forms appear as well. Searching for "Application.Run" reveals these calls:

```
  C:\GitHub\dsyme\visualfsharp\tests\fsharp\core\control\test.fsx(1827):    let form = new System.Windows.Forms.Form()

C:\GitHub\dsyme\visualfsharp\tests\fsharp\regression\656\form.fs(927):do Application.Run(mainForm)
  ```

**Comment by enricosada** [comment]
i tried locally, i see 4-5 times fsc.exe run as shell (cmd windows pop up) in FSharp.Tests.FSharp.dll
you can see what are in the window title.
I'll try to find these, it's strange, because all fsc invocation in tests should use `Commands.fsc` function

**Comment by enricosada** [comment]
probably something inside fsx, like [fsi-shadowcopy/test1.fsx](https://github.com/Microsoft/visualfsharp/blob/8a2e393999f440ea93769a288c37172d98db455a/tests/fsharp/core/fsi-shadowcopy/test1.fsx#L8-L10)

**Comment by enricosada** [comment]
@dsyme i need to run fsharpqa (i am reinstalling perl atm) to check that suite too
