### ISSUE TITLE
ProjectTypeGuids stripped from F# MVC 5 template

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#111]
Originally opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/90) by [riles](https://www.codeplex.com/site/users/view/riles01)

When creating a new F# web project from the F# MVC 5 template, the following ProjectTypeGuids are in the .fsproj:
```
<ProjectTypeGuids>{E53F8FEA-EAE0-44A6-8774-FFD645390401};{349C5851-65DF-11DA-9384-00065B846F21};{F2A71F9B-5D33-465A-A702-920D77279786}</ProjectTypeGuids>
```
From time to time, I find that several of the ProjectTypeGuids are stripped from the project. I've not been able to determine when this happens. It seems as though it may happen only in certain circumstances, but again, I haven't been able to discern a pattern. The remaining ProjectTypeGuids after the others are stripped are the following:
```
<ProjectTypeGuids>{349C5851-65DF-11DA-9384-00065B846F21};{F2A71F9B-5D33-465A-A702-920D77279786}</ProjectTypeGuids>
```
Any ideas? I'd be happy to help resolve the problem. It's a real hindrance for my team. 

Cheers! 
Ryan Riley

>comments
>riles01 wrote Jun 24, 2014 at 7:19 PM [x] 
>By the way, my best guess is that the ProjectTypeGuids are stripped when the project is loaded because when I try to unload, edit, and reload, the Guids are stripped again.
>>KevinRansom wrote Jun 25, 2014 at 12:45 PM [x] 
>>Would it be possible to narrow down the repro a little bit. I took a shot at reproing this by disabling some stuff, and it didn't happen, so I think I will need a better description of the "certain circumstances"
>>Kevin

>>>riles01 wrote Jun 26, 2014 at 11:59 AM [x] 
>>>I should have phrased "certain circumstances" as "unknown circumstances." Case in point: >>>Yesterday, I could never get the context menu to allow me to add a new item. Today, I see the menu. I did restart my VM last night, so potentially that has some impact. Jack Fox has previously told me that it comes and goes, so we really don't know what causes the Add > New Item context menu to show an empty list of items.

**Comment by panesofglass** [comment]
I don't think this is a real issue. Please close. The remaining project GUIDs appear to be sufficient.
