### ISSUE TITLE
Improve error reporting: warning if returning ignore

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#1113]
When beginning with F# (or when exhausted), it can happen to be writing code which mistakenly returns `ignore` such as:

```fsharp
[<Test>] let ``my test`` () =
  // some code

  ignore
```

I think this is in many case unintended and warrants a warning.

`Did you intend to return 'ignore' or to use it to discard previous expression?`

#1103

**Comment by forki** [comment]
What's wrong with it? The fact that we don't ignore anything? And what is
the expected error message?

**Comment by smoothdeveloper** [comment]
@forki, added the error message.

What is wrong is that the function signature in this case turns into `unit -> ('a -> unit)` instead of `unit -> unit`.

Try to put a NUnit test such as this one and to run it, I think I've seen this mistake few times when someone is not used to the pipe operator.

Of course if people think it is a stupid warning we can forget about it :smile:

**Comment by isaacabraham** [comment]
so in other words you meant to return ``()`` or just ``ignore()``?

I guess this is the same as returning a function in any function - is what we're saying is "should we return a warning any time you return a function"? Can't be. Is ``ignore`` a special case though? Would you ever normally want to return it? Maybe not.

**Comment by smoothdeveloper** [comment]
@isaacabraham intent is to just make that happen for `ignore` from `FSharp.Core`, it is OK to return a function otherwise (or to discard the warning if I really want to return ignore).

**Comment by ReedCopsey** [comment]
@smoothdeveloper I wonder if this would be better off as part of [FSharpLint](https://github.com/fsprojects/FSharpLint) instead?

**Comment by forki** [comment]
Yes this one looks too specific to "ignore" - I don't think we can bake that easily into the compiler. I mean there is probably a way, but it feels like this one should go into linter.

**Comment by forki** [comment]
Or maybe it can go into nunit. The runner could complain if it finds tests with wrong signature

**Comment by smoothdeveloper** [comment]
@ReedCopsey  / @forki makes sense, I'll see if I can make a contribution to FSharpLint thanks!
