### ISSUE TITLE
Tests broken on german machine because warning is given in german

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1118]
Our tests are not independent of the language settings of the developer machine.

![image](https://cloud.githubusercontent.com/assets/57396/14808010/09f42a6c-0b82-11e6-9d7c-03b58d1c7bde.png)

#### Repro steps

Use german machine and run `build.cmd all`

#### Actual behaviour

Build is broken with the following changes:

![image](https://cloud.githubusercontent.com/assets/57396/14808182/9cb01ebe-0b83-11e6-8e2b-37c7e5e50f08.png)

![image](https://cloud.githubusercontent.com/assets/57396/14808165/803e6c0e-0b83-11e6-97b7-88d19f84faec.png)

![image](https://cloud.githubusercontent.com/assets/57396/14808141/4f8e13de-0b83-11e6-8be9-390c3dfaf784.png)

![image](https://cloud.githubusercontent.com/assets/57396/14808145/5d520264-0b83-11e6-9bc6-1f86b2e30295.png)

**Comment by smoothdeveloper** [comment]
is there a way to flag them and set the thread culture arbitrarily?

**Comment by enricosada** [comment]
@smoothdeveloper  yes with an internal use fsc argument `LCID` (used by ide), but that add a warning, so change a bit the diff of output.
i added #858 to add an additional  `--preferreduilang` like roslyn to pass `en-US`, so test can pass the language for case sensitive tests (i get same problem with italian)

i think i need to rebase and ask for review

**Comment by forki** [comment]
Maybe we can disable the 4 tests for non-us systems?  Or we remove the part that tests the culture specific message.

**Comment by enricosada** [comment]
the whole test is case sensitive (diff the output of compiler), but we can disable these ( nunit ignore ) on non en-US cultures. I'll send a pr, good idea @forki

**Comment by forki** [comment]
❤️  thanks for making this work.
