### ISSUE TITLE
F#-style optional arguments don't work properly for abstract/virtual methods

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#112]
Originally opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/92) by @latkin
Say we have a class with 2 methods leveraging F# style optional args, otherwise identical except for one being virtual:
```fsharp
type TBase() =
    abstract member Foo : int option -> int
    default this.Foo(?x : int) =
        defaultArg x 100

    member this.Bar(?x : int) =
        defaultArg x 100
```

The non-virtual method works as expected, the virtual one behaves as if it requires an explicit option type, i.e. as if the method were declared this.Foo(x : int option)

```fsharp
let test1 = TBase()
test1.Foo(1)  // fails: This expression was expected to have type int option but here has type int
test1.Foo()   // fails: This expression was expected to have type int option but here has type unit
test1.Bar(1)  // works
test1.Bar()   // works
```
Expected; All of above work.

>comments
>dsyme wrote Jun 27, 2014 at 10:10 AM [x] 
>You declare the abstract signature like this:
abstract member Foo : ?x: int -> int
>So "?x:int" = "x : int option" for the purpose of abstract members and signature checking, but they give different effects at callsites.

>Given this is how things work today, I think it's reasonable to keep this behaviour: with F# members, various attributes like ? optionalness can affect callsite behaviour. 

>>latkin wrote Jun 27, 2014 at 11:09 AM [x] 
>>Ok, that syntax does produce desired/expected behavior.
>>But I would say allowing abstract signature of int option when implementation is optional is very confusing and leads to totally nonintuitive behavior, and should be considered a bug. Is there any realistic scenario where this is the true intent of the developer? Perhaps a warning here would be valuable.

>>The behavior at the callsite is not consistent, either, sometimes it requires an option type, sometimes optional arg:

```fsharp
type TBase() =
    abstract member Foo : int option -> int
    default this.Foo(?x : int) =
        defaultArg x 100

let test1 = TBase()
test1.Foo(None) // <---- TBase call requires option here

type TDerived() =
    inherit TBase() 
    override this.Foo(?x : int) = 
        let newDefault = defaultArg x 0
        base.Foo(newDefault)  // <---- TBase call requires int here
```

**Comment by dsyme** [comment]
@latkin - since there is a language design issue/request here I think this belongs on http://fslang.uservoice.com, and perhaps a request for an F# spec clarification in https://github.com/fsharp/FSharpLangDesign/
