### ISSUE TITLE
Improve error reporting: Accidental use of , instead of ; as record field separator

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#1122]
## What
The following error message is generated from this code snippet:
```fsharp
type Person = { Name : string; Age : int; City : string }
let x = { Name = "Isaac", Age = 21, City = "London" } // , instead of ;
```

``error FS0001: This expression was expected to have type
    string    
but here has type
    'a * 'b * 'c``

## Why
Newcomers to F# syntax (or otherwise!) may accidentally use ``,`` instead of ``;`` as field separators. The error message is not helpful in this case - the inclusion of generics in the message further complicates matters and does not aid the developer with the real problem.

## How
Replace the error message with something like: -

``F# uses ; to separate fields values when creating a record, not , e.g. let x = { Name = "Isaac"; Age = 21 ... }``

**Comment by forki** [comment]
wow this error message is really confusing ;-)

**Comment by forki** [comment]
wow this error message is really confusing ;-)

I mean this should already be a parse error, right? What we report here is an error in the type checker.

**Comment by matthid** [comment]
@forki 
```fsharp
type Person = { Name : string * bool * bool }
let Age = 22
let City = "London"
let x = { Name = "Isaac", Age = 21, City = "London" } // , instead of ;
```

```
>
type Person =
{Name: string * bool * bool;}
val Age : int = 22
val City : string = "London"
val x : Person = {Name = ("Isaac", false, true);}
```

**Comment by forki** [comment]
from chat with @dsyme:

    type X<'T> = { F : 'T };;
    let a = 5;;
    { F = 1, a = 4 };;

    val it : X<int * bool> = {F = (1, false);}

So "1, a = 4" is being treated as an expression of type "int * bool".

This is a valid case ;-)

So the strategy is to special case this in the type checker instead of raising a parser error.

**Comment by forki** [comment]
@matthid yes thanks. @dsyme had similar case at same time. I will try to make it a context sensitive type checker error

**Comment by matthid** [comment]
I think this is realated to https://github.com/Microsoft/visualfsharp/issues/1120 and both are not trivial to improve. But I would love to see an improvement as especially #1120 hit me several times when I started F# and still hits from time to time ;)

**Comment by forki** [comment]
Initial PR in https://github.com/Microsoft/visualfsharp/pull/1171
