### ISSUE TITLE
#nowarn "211" in loaded script files is ignored

### ISSUE THREAD

**Issue by tpetricek** [Microsoft/visualfsharp#1126]
When you have a script with `#I` that points at a non-existing folder, but you also have `#nowarn "211"` to hide the warning, you still get a warning.

To reproduce, create a file, say `C:\temp\nada.fsx` containing

    #nowarn "211"
    #I "totally-non-existing-folder"

And then run the following in F# Interactive:

    Microsoft (R) F# Interactive version 14.0.23020.0
    Copyright (c) Microsoft Corporation. All Rights Reserved.
    For help type #help;;

    > #load @"C:\temp\nada.fsx";;

    [Loading C:\temp\nada.fsx]
    C:\temp\nada.fsx(2,1): warning FS0211: The search directory 
        'C:\temp\totally-non-existing-folder' could not be found
    namespace FSI_0002

Is this supposed to be this way, or is it a bug? /cc @dsyme

**Comment by forki** [comment]
this is fixed in #1239, right? can we close it?

**Comment by dsyme** [comment]
Yes, thanks
