### ISSUE TITLE
Improve error reporting: Wrong cast operator (:?> instead of :>)

### ISSUE THREAD

**Issue by isaksky** [Microsoft/visualfsharp#1127]
Related to #1103 

# What

![image](https://cloud.githubusercontent.com/assets/607986/14874585/4fbd29ca-0cbf-11e6-8638-9ddddd0e3bbb.png)

# Why
This error message is problematic for newcomers, especially ones from C#, because:
1. ```IDictionary<obj,obj>``` *is* compatible with ```Dictionary<obj, obj>```
2. C# only has one cast operator, and this works in C#:
```csharp
public static IDictionary<object, object> TestM() {
    return new Dictionary<object, object>();
}
```

# Possible solution
Before resorting to this error message, check if the left hand side can be statically cast to the type on the right, and if so, use a **"consider using the :> operator"** error message instead.

**Comment by forki** [comment]
first WIP PR: https://github.com/Microsoft/visualfsharp/pull/1149

**Comment by isaacabraham** [comment]
@isaksky Just a thought - C# does have two keywords - ``as`` (which doesn't exist in F# AFAIK) and ``()``. It's more that in C# the "safe upcast" happens implicitly whereas in F# you need to be explicit - although I can't remember if this is only for co/contravariant conversions.

**Comment by isaacabraham** [comment]
In fact here's another whole host of example cases...

```fsharp
type IFoo = abstract member Bar : unit -> unit
type Foo() = interface IFoo with member __.Bar () = ()
        
let Thing : IFoo = Foo() // fails
let Thing2 : IFoo = Foo() :?> IFoo // fails
let Thing3 : #IFoo = Foo() // warning - and for some reason overrides type signature!!
let Thing3 : IFoo = upcast(Foo()) // works!
let Thing4 : IFoo = downcast(Foo()) // doesn't work!
```

**Comment by isaacabraham** [comment]
I propose the error message to say: -

```"The conversion from <type A> to <type B> is a compile-time safe upcast, not a downcast. Considering using the : > (upcast) operator instead of the : ?> (downcast) operator."```

**Comment by forki** [comment]
PR in #1149
