### ISSUE TITLE
Improve error reporting: provide better literal suffix description

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#1129]
## What

```fsharp
let foo = 1up
```

`This is not a valid numeric literal. Sample formats include 4, 0x4, 0b0100, 4L, 4UL, 4u, 4s, 4us, 4y, 4uy, 4.0, 4.0f, 4I`

## Why

It is difficult to remember:
* the valid suffixes
* what exact type they correspond to (despite they are kind of logical, if I made a mistake, better remind me the type as well)
* I was looking for decimal but it isn't there

## How

Bonus point if we instead of 4 we show 42 or the actual value.

`This is not a valid numeric literal. Valid numeric literals include  1, 0x1, 0b0001 (int), 1u (uint32), 1L (int64), 1UL (uint64), 1s (int16), 1y (sbyte), 1ui (byte), 1.0 (float), 1.0f  (float32), 1.0m (decimal), 1I (BigInteger)`

#1103

**Comment by smoothdeveloper** [comment]
note also that `let a = 0m` works but `let a = 0f` doesn't which I think is inconsistent.

**Comment by smoothdeveloper** [comment]
Question: why do `UL` and `L` need  to be uppercased while others are all lowercase only?

**Comment by vasily-kirichenko** [comment]
> Question: why do UL and L need to be uppercased while others are all lowercase only?

About `l` vs `L`, my guess is that's something like `21l` is very hard to read. I'm not sure about `u` vs `U` though.

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko I see, what about the one for BigInteger? `21i` vs `21I` I guess Big Integer = Big I :)

**Comment by forki** [comment]
We should not question the syntax here. That is pretty much fixed. This
should only be about the error messages

**Comment by smoothdeveloper** [comment]
@forki: do you think the proposed error message (check on github itself due to edits) is an enhancement?

**Comment by dsyme** [comment]
Adding the samples is ok, but please keep the style of the original wording where sentences are used, rather than phrases:

    This is not a valid numeric literal. Valid numeric literals include 1, 0x1, 0b0001 (int), 1u (uint32), 1L (int64), 1UL (uint64), 1s (int16), 1y (sbyte), 1ui (byte), 1.0 (float), 1.0f (float32), 1.0m (decimal), 1I (BigInteger)

It's important to say "include" because the numeric literals are extensible through the QZRING feature.

**Comment by smoothdeveloper** [comment]
@dsyme updated, thanks for feedback, maybe you should consider putting some guidelines on #1103 regarding how to word those messages.

I still think the final messages should be created/edited by MS with concern at consistency, comprehensibility and conciseness.

**Comment by forki** [comment]
PR at https://github.com/Microsoft/visualfsharp/pull/1148
Regarding "bonus points": we failed to parse the numeral so we can't say what the "actual value" is here.

**Comment by toburger** [comment]
In the error message the byte literal is wrong: should be 1uy, not 1ui.
