### ISSUE TITLE
Enable VS Gallery to notify user of availability of Visual F# power tools, without having installed them first.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#113]
Opened on [Codeplex](https://visualfsharp.codeplex.com/workitem/94) by @KevinRansom 

This PR will cause visual fsharp tools to activate the Visual Studio Gallery notification mechanism, to notify F# users of the powertools 

https://visualfsharp.codeplex.com/SourceControl/network/forks/dungpa/PowerToolsNotification/contribution/6932 

We want to know if this is desired functionality, and so your votes on this will help determine if we do it. 

We should ensure this is in the next Oob?

>comments
>forki wrote Jul 3, 2014 at 1:15 PM [x] 
>YES!
>>rojepp wrote Jul 3, 2014 at 1:26 PM [x] 
>>Much as I like VFPT, I am not in favour of this idea. The breadcrumbs that already come with VS are just annoying, they never go away. I vote for taking the high road. ;)
>>>dsyme wrote Jul 3, 2014 at 2:42 PM [x] 
>>>I think this is a good idea. It would increase the visibility of the VFPT tools, and spread knowledge about them. Many people using F# in Visual Studio do not know of these tools and continue to believe that F# tooling in Visual Studio is missing key features, when that is no longer the case. This is the best way to bring them to their attention en masse.

>>>Cheers
>>>Don

>>>>KevinRansom wrote Jul 3, 2014 at 2:57 PM [x] 
>>>>Longer term, I want to include the power tools proper in F#, just not right now, first we have to figure out how to do it in such a way that keeps the VFPT team churning out their awesome features, without us slowing them down. Also you can hide an update notification in VS and not see it until the next update arrives.

>>>>Kevin

>>>>>isaaclondon wrote Jul 5, 2014 at 10:37 AM [x] 
>>>>>Hell yes. @KevinRansom agreed re: integration the best way to go in the longer term though.

**Comment by dsyme** [comment]
Feels like this is a feature request belonging in https://visualstudio.uservoice.com/forums/121579-visual-studio/category/30935-languages-f-tools

**Comment by latkin** [comment]
Closing out. Original was open on Codeplex for many months and no new developments here.
