### ISSUE TITLE
Add empty value into the String module

### ISSUE THREAD

**Issue by rexcfnghk** [Microsoft/visualfsharp#1139]
Right now, if I do not want to use the empty string literal `""`, I have to do something like

```fsharp
printfn "%s" System.String.Empty
```
in order to reference the `public static readonly` instance of the empty string in the BCL.

It would be more convenient if I can just do:

```fsharp
// Referencing the F# String module here instead of System.String
printfn "%s" String.empty
```

I would imagine `String.empty` to be an alias to `System.String.Empty` so there should be just a one-line code change:

```fsharp
module String =

    [<CompiledName("Empty")>]
    let empty = ""

    // Other String functions
```

I think this will be useful because we already have similar `empty` values from other modules such as `Seq`, `List`, and `Array`.

This will also make the code more explicit (i.e. convey to others that 'I want an empty string here' instead of 'this can potentially be a typo').

**Comment by enricosada** [comment]
You can do

```fsharp
open System
```

And you can do `String.Empty`

**Comment by rexcfnghk** [comment]
@enricosada I understand I can `open System` and do `String.Empty`, I am just thinking since we also have `Seq.empty<'t>` (same as `Enumerable.Empty<T>` in the BCL), why can't we also include `String.empty` in the F# core library?

**Comment by smoothdeveloper** [comment]
@rexcfnghk changes to F# core library have to be very conservative for plenty of reasons, maybe it is better to define your own library or contribute to one of the extended "core" libraries?

You can put a suggestion on uservoice: https://fslang.uservoice.com/ there are several such suggestions to extend FSharp.Core and some are being implemented.

**Comment by forki** [comment]
What's wrong with opening a namespace? Tools like VFPT can even do that for you. Or you can still use "" which is super concise.

**Comment by rexcfnghk** [comment]
@forki I am not against opening a namespace, I just want to make the `String` module 
- Consistent with the `List`, `Array` modules (i.e. they still have `List.empty`, `Array.empty` despite the fact you can also use the `[]` and `[| |]` literals)
- **Explicit** in conveying the meaning that 'I need an empty string/sequence/list/array here and it's not a typo'

**Comment by enricosada** [comment]
@rexcfnghk enumerable.empty is .net 3.5 . Seq.empty was there before

**Comment by rexcfnghk** [comment]
@smoothdeveloper, a previous PR regarding the addition of [`Map.count`](https://github.com/Microsoft/visualfsharp/pull/1007) and its [RFC](https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1010-add-map-count.md) also shows that there is value to a simple core library addition. Assuming this is only a few lines of code change, won't this be a good addition to make the `String` module more consistent with the `List`/`Array` modules?

**Comment by smoothdeveloper** [comment]
@rexcfnghk I agree there is value to make enhancements to FSharp.Core via RFCs/PRs.

**Comment by enricosada** [comment]
well, i think there are pro/cons :smile: 

@rexcfnghk i think you should close this issue, per [CONTRIBUTING.md](https://github.com/Microsoft/visualfsharp/blob/master/CONTRIBUTING.md#issues): 

> Suggestions for the F# Language and Core library should be added and reviewed at the [F# Language User Voice](https://fslang.uservoice.com/).

put a link there after you added the uservoice suggestion

**Comment by rexcfnghk** [comment]
@enricosada @smoothdeveloper , closing this issue and added the [User Voice link](https://fslang.uservoice.com/forums/245727-f-language/suggestions/13696080-add-empty-value-into-the-string-module)
