### ISSUE TITLE
MissingMethodException when opening solution in VS2015

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1144]
Since yesterday I can't open VisualFSharp.sln anymore in VS2015 Update 2

![image](https://cloud.githubusercontent.com/assets/57396/14980246/a436ec4a-1127-11e6-8722-c3644e1d5cf7.png)

I tried to rebuild the proto compiler and it succeeds from command line, but this still happens

**Comment by forki** [comment]
when I build proto-compiler from 580da22232240847a9ee2a076a80c815959b1457 it still works. so it must be something after that commit

**Comment by forki** [comment]
4819ba9b241e7a29cfe8fff58389e54eea1a9bc9 "Merge pull request #1133 from KevinRansom/crossgen" is the first commit that is broken for me

**Comment by dsyme** [comment]
@forki @KevinRansom  Ah, it seems that when using VisualFSharp.sln, the updated FSharp.Build (or FSharp.Build-proto) is being loaded into VS2015, but without the corresponding update to the VF# IDE bits.  That will make development annoying. 

Not quite sure what to do about this.

**Comment by KevinRansom** [comment]
Yes, that is correct.  I will keep the update only for the coreclr version of fsharp.build not the desktop one.

**Comment by dsyme** [comment]
ok, thanks

**Comment by forki** [comment]
I know we all want to go forward instead of backwards, but can you please revert that merge? I mean the proto compiler build is currently useless and  noone can work on master right now.

**Comment by smoothdeveloper** [comment]
@KevinRansom thanks!

**Comment by smoothdeveloper** [comment]
confirming it works, great :)
