### ISSUE TITLE
fake build script for this repository

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#1156]
This is mostly for discussions and those who want to try out to have a main build script which is platform agnostic rather than maintaining `build.cmd` `build.sh`

This is what I have now, far from completion but it builds the main compiler on my windows machine and tries to follow what I'm reading in `build.cmd`:

https://github.com/smoothdeveloper/buildvisualfsharp/blob/master/fakebuild.fsx

I'll try to make this work on a mac when I have a chance.

I think relying on .fsx script (here made with FAKE) has lots of advantages, one of those is being able to step through the script in a FSI session.

**Comment by KevinRansom** [comment]
@smoothdeveloper 
Thank you for raising this.  This arises from time to time, but is something we have on our radar.

**Comment by smoothdeveloper** [comment]
@KevinRansom I'm just seeing this:

https://github.com/dolly22/fake.dotnet

this might be worth a look to have a crossplatform wrapper to calls to dotnet.exe and installing core clr stuff in our build scripts.

Fake is also coming to .net core: 

https://github.com/fsharp/FAKE/pull/1281

**Comment by smoothdeveloper** [comment]
@KevinRansom, I was chatting on the matter and someone hinted that "not" might not have made it in your comment:

> but is something we have on our radar.

Is it on the radar or not on the radar?

**Comment by dsyme** [comment]
"On the radar" roughly means "aware of the possibility, and could imagine doing it in theory or if things continue to make it more compelling, but no active plan to do it in practice right now".  So it's on the radar.
