### ISSUE TITLE
Improve error reporting: Missing "else" branch for if / elif expression

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#1157]
## What
Related to #1104, but not the same. The following code leads to an especially cryptic error message from the compiler:

```fsharp
let x = 10
let y =
   if x < 10 then "test"
   elif x < 20 then "foo"
```
As if is an expression in F#, you need to provide an ``else`` branch as well. The error message shown below is related to the ``elif`` branch above (but not the ``if`` branch): -

```
error FS0001: This expression was expected to have type
    string    
but here has type
    unit
```

## Why
What's especially confusing about this error (in addition to the points put forward in  #1104) is that the error suggests that the type being returned from this branch is a unit when in fact it is a string. Even worse, if you comment out the elif branch so that you just have the if branch, the types in the error message become inverted!

## How
As per #1104.

**Comment by forki** [comment]
I think I already know why this is reported in wrong order. I *think* I
fixed that by changing order of the equations in that related pr. But
@dsyme said I should be change that back. So we should add more test cases
and then fix the test cases and think really hard if the order is right.

But first things first. I will add tests for this to my other pr. Hopefully
on Monday.

**Comment by KevinRansom** [comment]
@isaacabraham, @forki 

With Steffen's PR It now yields this error:  I think the advice portion is accurate and relevant.

What do you think?

````
> let x = 10
- let y =
-    if x < 10 then "test"
-    elif x < 20 then "foo";;

     elif x < 20 then "foo";;
  ---^^^^^^^^^^^^^^^^^^^^^^
stdin(4,4): error FS0001: The 'if' expression is missing an 'else' branch. The 'then' branch has 
type 'string'. Because 'if' is an expression, and not a statement, add an 'else' branch which 
returns a value of the same type.
>
````

**Comment by isaacabraham** [comment]
It's definitely a big improvement :-) My only question (and this is across all the if / else issues) is what is a "then" branch? Surely it should be the "if" branch as there are several occurrence of "then" within an if / else expression.

**Comment by isaacabraham** [comment]
@forki Just noticed that this only works for simple values. If there's a function in between, it fails e.g.

```fsharp
let foo x = x + 1
let x = if true then (foo 5)
```

gives the error:

`error FS0001: This expression was expected to have type
    'unit'
but here has type
    'int'`

If I remove the `foo` call e.g.

```fsharp
let x = if true then 5
```
Then it works properly:

`error FS0001: The 'if' expression is missing an 'else' branch. The 'then' branch has type 'int'. Because 'if' is an expression, and not a statement, add an 'else' branch which returns a value of the same type.`

Both errors have the same error code which suggests that the compiler understands it's the same error - it's just the it's getting the text from a different place or something?

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/31626956-d8b98226-b2ab-11e7-8dac-f2bccb41edcd.png)

lol it's the `()`

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/31627218-c4d01b48-b2ac-11e7-952c-d57792e3dbf2.png)

function application is not needed
