### ISSUE TITLE
Compiler allows exporting type abbreviations that mention private types

### ISSUE THREAD

**Issue by Porges** [Microsoft/visualfsharp#1158]
(Moved from https://github.com/fsharp/fsharp/issues/572)

The compiler doesn't currently prevent you exporting an alias for a private type, but it probably should. 

#### Repro steps

That is, given this code in an assembly:

```fsharp
module Library
type private Hidden = Hidden of unit
type Exported = Hidden
```

#### Actual behavior

Using this from *another assembly* can produce unexpected results:

```fsharp
// in the consuming executable...
open Library

[<EntryPoint>]
let main argv =
    let x : Exported = Unchecked.defaultof<_>
    printfn "%A" x
    0
```

Giving:

```
Unhandled Exception: System.MethodAccessException:
Attempt by method 'Program.main(System.String[])' to access method
'Microsoft.FSharp.Core.PrintfFormat`5<System.__Canon,System.__Canon,System.__Canon,System.__Canon,System.__Canon>..ctor(System.String)' failed.
```

#### Expected behavior

The desired behaviour would be that a type abbreviation that mentions private types must also be private. This is how functions and "real" types work - neither of these are accepted:

```fsharp
type ExportedRealType = Bad of Hidden
let printExported (_ : Exported) = printfn "How did you get that?"
```

#### Related information 

Provide any related information 

* F#: 4.0 (Core 4.4.0.0)
* Operating system: Windows 10
* .NET Runtime, CoreCLR or Mono Version: 4.5
* Editing Tools: VS2015 Update 2

**Comment by forki** [comment]
fix in https://github.com/Microsoft/visualfsharp/pull/1289
