### ISSUE TITLE
F# compiler generating unnecessary/incorrect closure for inlined function

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#116]
Originally opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/98) by [jackpappas](https://visualfsharp.codeplex.com/workitem/98)

I was looking at the "Language Benchmarks Game" this afternoon to see if any of the F# implementations could be improved. Long story short, I compiled the F# implementation of the 'pidigits' benchmark using an F# compiler I built from source yesterday, and it looks like the compiler is allocating an unnecessary (and unwanted) closure within what is designed to be an optimized loop. 

I've attached a slightly modified / cleaned-up version of the benchmark implementation code so you can reproduce this. 

Comparing the F# code and the IL produced by the compiler, the compiler appears to be creating a closure for the 'prdigit' function instead of inlining it as expected. The function has the type signature "int -> bool", and the single time it's called, the result is assigned to the value "more" (a module-scoped value). The closure generated by the compiler captures the "int" argument, but returns a "unit -> unit" function, which is then immediately called. The other code in the if/else block where 'prdigit' is called -- where the value of 'false' is assigned to "more" if 'prdigit' returned 'true', otherwise the 'compose_r' function is called -- has also been inlined/captured into the closure, which is how the code still manages to produce the correct result.

file attachments
 
* [Program.fs](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visualfsharp&WorkItemId=98&FileAttachmentId=879115)

>comments
>TIHan wrote Oct 8, 2014 at 1:23 AM [x] 
>If you take this piece:
>```fsharp
    // Generate successive digits of PI. 
    let mutable k = 1
    i <- 0
    set_si (&q, 1)
    set_si (&r, 0)
    set_si (&s, 0)
    set_si (&t, 1)
    let mutable more = true
    while more do
        let y = extract 3
        if y = extract 4 then
            if prdigit y then
                more <- false
            else
                compose_r (10, -10 * y, 0, 1)
        else
            compose_l (k, 4 * k + 2, 0, 2 * k + 1)
            k <- k + 1
```
>And wrap it in a function:
>```fsharp
let compute () =
    // Generate successive digits of PI. 
    let mutable k = 1
    i <- 0
    set_si (&q, 1)
    set_si (&r, 0)
    set_si (&s, 0)
    set_si (&t, 1)
    let mutable more = true
    while more do
        let y = extract 3
        if y = extract 4 then
            if prdigit y then
                more <- false
            else
                compose_r (10, -10 * y, 0, 1)
        else
            compose_l (k, 4 * k + 2, 0, 2 * k + 1)
            k <- k + 1
    0
```
prdigit will inline properly.

**Comment by dsyme** [comment]
I think we should close this kind of performance suggestion without a concrete fix proposal plus performance tests.  Or request it be placed on http://fslang.uservoice.com

**Comment by dsyme** [comment]
Closing this as per [CONTRIBUTING.md](https://github.com/Microsoft/visualfsharp/blob/fsharp4/CONTRIBUTING.md) guidelines.

**Comment by dsyme** [comment]
Looked at this more properly, it really shouldn't be creating a closure there.

**Comment by dsyme** [comment]
@jack-pappas This is pretty pathological, but I'll push a fix

* I recommend relying much less on top-level values.  They are likely to be slower than method-local or class-local mutables I think

* The extensive inlining creates a large method body, which gets split.  When the actual main function is made into a function, rather than top-level initialization code, then this doesn't happen.

So basically, writing the code more idiomatically (less use of top level code) will both make the problem go away and help perf I think
