### ISSUE TITLE
Improve error reporting: Let as last line in block

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#1162]
## What
(From @tpetricek). The following code snippet leads to the resulting error message: -
```fsharp
let sum = 0
for x in 0 .. 10 do
    let sum = sum + x
```
```error FS0588: Block following this 'let' is unfinished. Expect an expression.```

## Why
The above error message, whilst factually correct, does not explain to the beginner what this is and why it occurs. There are of course two errors here - one that the user is trying to mutate a value (which should be ignored from this issue as it is covered elsewhere) and the second which is that there is no result from the block.

## How
Suggest: ```Every code block is an expression and must have a result. 'let' is not an expression and cannot be the final code element in a block. Consider returning something explicit from this block.```

**Comment by kurtschelfthout** [comment]
Is this saying that ignore is never an option? I'm not sure that is the case but also I can't come up with a really convincing counter-example so perhaps it is. `ConcurrentDictionary.TryRemove` perhaps? `MethodBase.Invoke` on a void method?

**Comment by isaacabraham** [comment]
@kurtschelfthout not sure I follow. Ignore should be valid - it would just return unit from the block.

**Comment by forki** [comment]
PR in #1164
