### ISSUE TITLE
Build on master is broken on jenkins because VS is missining

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1169]
Master doesn't build right now.

See https://github.com/Microsoft/visualfsharp/pull/1164 and https://github.com/Microsoft/visualfsharp/pull/1149

same failure:

    00:47:44 D:\j\workspace\debug_windows---2f360ea4>if '' == '' echo Error: Could not find an installation of Visual Studio   && goto :failure 
    00:47:44 Error: Could not find an installation of Visual Studio 

Both PR build locally on my machine (apart from expected unit test issues that I'm still trying to fix)

**Comment by forki** [comment]
After looking at my build history I *think* someone changed something on the build agents. This morning I tried to build a commit that worked yesterday (apart from test errors), but it didn't work today.

**Comment by forki** [comment]
The appveyor build is green, so it's really something with jenkins

**Comment by forki** [comment]
@otawfik-ms, @kevinransom any ideas?

**Comment by otawfik-ms** [comment]
@forki yes. I'm merging the changes in #1065 which should bring it back up to green. Pending a small test fix now.

**Comment by forki** [comment]
is it ready?

**Comment by otawfik-ms** [comment]
No. Still fixing the failed tests. Unfortunately, Jenkins machine changes cannot be done in the same PR that is using these changes. I'll link the issue to the opened PR.

**Comment by otawfik-ms** [comment]
Fixed.
