### ISSUE TITLE
Improve error reporting: Recursive async functions

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#1170]
## What
The following code snippet leads to the resulting error message: -
```fsharp
let rec foo() = async { return foo() }
```

```
Type mismatch. Expecting a
    'a    
but given a
    Async<'a>    
The resulting type would be infinite when unifying ''a' and 'Async<'a>'
```

## Why
99/100 times the cause is simply that the developer has forgotten to ```return!``` rather than ```return```. The current error message is confusing, does not explain why the error has occurred and does not present the likely solution.

## How
Suggest a rewording that follows *Error / Explanation / Suggestion* format: -

```
Type mismatch. Expecting a
    'a    
but given a
    Async<'a>
You are attempting to recursively return the result of an asynchronous call which is not awaited. Have you forgotten to use 'return!' instead of 'return' ?
```

Perhaps someone could explain what an infinite type is as well - I have no idea, although I sort of understand why this error occurs... :-) As I don't, the "explanation" bit of this error needs reworking for sure. I know that common parlance is to use "Consider" but in this case it's a guess more than anything. I also don't like use of "await" but am not sure what the correct term is.

**Comment by forki** [comment]
I *assume* the type checker doesn't know concrete computation expression types. It probably knows about generic "return!" but not about the async version. So I guess we need to find wording that does not talk about "async"

**Comment by isaacabraham** [comment]
So I'm not sure the best way to describe the "error" part of this without scaring people. Not do I know the generalized word instead of await. Bind?

**Comment by forki** [comment]
one observation:

![image](https://cloud.githubusercontent.com/assets/57396/15207684/fdc7f284-1827-11e6-8ae7-642c1b200993.png)

we should not put the types in single quotes. I know @KevinRansom just fixed all place to do this consistently (cosistent = good), but it looks really really strange with generic types. @isaacabraham can you please create a new issue for this? We should use different quotes or remove the quotes.

**Comment by forki** [comment]
what about:

![image](https://cloud.githubusercontent.com/assets/57396/15210158/50617a8a-1835-11e6-834f-ab9e5befe394.png)

?

**Comment by forki** [comment]
Initial PR at https://github.com/Microsoft/visualfsharp/pull/1180

**Comment by isaacabraham** [comment]
Perhaps "self referencing type definition" or similar is another way to define this issue?
