### ISSUE TITLE
Compilation error on partial application with classes/interfaces

### ISSUE THREAD

**Issue by JanWosnitza** [Microsoft/visualfsharp#1199]
Compilation error when partial application leaves unapplied class/interface parameters.
This seems to be an error only with unused `let` (e.g. in libraries).

#### Repro Steps
Compile
```
type Class () = do ()
let f (a) (b:Class) = ()
let fPartial = f 10
```

#### Expected
Compilation without errors like this:
```
type Struct = struct end
let f (a) (b:Struct) = ()
let fPartial = f 10
```

#### Actual

The compilation error is:
> error FS0030: Value restriction. The value 'fPartial' has been inferred to have generic type
> &nbsp; &nbsp; val fPartial : ('_a -> unit) when '_a :> Class
> Either make the arguments to 'fPartial' explicit or, if you do not intend for it to be generic, add a type annotation.

It's only an error with **interfaces** and **classes** but not with records, discriminated unions and structs. Additionally if a parameter is given (see workaround 1), a **non generic function is inferred**.

#### Severity
- Confusing while coding as long as the function is not used (see workaround 2).
- Annoying in libraries when functions need an additional pass through parameters, because the function is not used within the library.
- IMHO the additional pass through parameter is less efficient (in compiled code) than passing through all parameters (more cumbersome) or not a single one.

#### Version
- F# 4.0 (FSharp.Core, 4.4.0.0)
- F# Compiler version 14.0.23413.0
- .NET Runtime, Framwork 4.6
- Windows 10
- Visual Studio Community 2015 version 14.0.2513.00 Update 2

#### Workaround

1:
 ```
type Class () = do ()
let f (a) (b:Class) = ()
let fPartial (x) = f 10 x
```
2:
```
type Class () = do ()
let f (a) (b:Class) = ()
let fPartial = f 10
fPartial (Class ())
```

both resulting in ```val fPartial : (Class -> unit)```

**Comment by JanWosnitza** [comment]
@isaacabraham now that I've seen your proposal: Of course, this is a **duplicate** of

> https://github.com/Microsoft/visualfsharp/issues/1161 : Improve error reporting: Partially applied generic value vs function

**Comment by isaacabraham** [comment]
@KevinRansom please close this.
@JanWosnitza no worries. If you want to create more of the error reporting style, can you follow the standard we've adopted for all the others? Details can be found here: https://github.com/Microsoft/visualfsharp/issues/1103

**Comment by JanWosnitza** [comment]
This issue was not meant to improve error reporting, but assuming the compilation error to be a bug. But you mentioned most of my concerns  on your issue, so I think it's alright.

**Comment by forki** [comment]
I think it's not a compiler bug. But I assume @dsyme can cite language spec
to back that claim. ;-)

**Comment by dsyme** [comment]
It's not a compiler bug, just an instance of the value restriction. Classes have subtypes, hence are a source of generic polymorphism, while structs don't.
