### ISSUE TITLE
Debug stepping behavior very poor for loops over arrays

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#12]
Opened by: [latkin](https://www.codeplex.com/site/users/view/latkin)

for loops over list seq and string all exhibit nice, consistent debug stepping behavior, but for loops over arrays don't work well at all. We should correct the debug range assignments here so that this is consistent. 
![19f2qwf](https://cloud.githubusercontent.com/assets/5175830/5735853/20edcc6c-9b82-11e4-8f0b-389d42cf2687.gif)

See example here (VS 2013, "just my code" off, "managed compat mode" disabled) 

 Loops over ranges are also inconsistent, but at least usable, so as a lower priority item we should fix those, too.

**Comment by latkin** [comment]
Removing the VS 2015 milestone on this guy as it would not be approved by shiproom at this point (plus no fix imminent AFAIK).

**Comment by dsyme** [comment]
Fixed by above PR
