### ISSUE TITLE
Non-intuitive behavior with operators starting with character '|'

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#120]
Originally opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/104) by [aqtq314](https://www.codeplex.com/site/users/view/aqtq314)

Given a new operator (|>!)

```fsharp
let inline (|>!) a f = f a; a
```

the following code 

```fsharp
match Some () with
| Some () ->
    true
| None ->
    false
|>! printfn "#### %b"
```

gives

```fsharp
val it : bool = true
```

i.e. the function (printfn "#### %b") is not executed. In fact, the above code is equivalent to

```fsharp
match Some () with
| Some () -> true
| None -> (false |>! printfn "#### %b")
```

If you adjust the indentation slightly, it behaves the way you would expect (note extra space before “false”)

```fsharp
match Some() with
| Some () ->
    true
| None ->
     false
|>! printfn "#### %b"
```

I could not get the issue to repro with the `|>` operator, but it does with a built-in 3-character operator:

```fsharp
match Some() with
| Some () ->
    true, true
| None ->
    false, false    // error: This expression was expected to have type 'a * 'b but here has type bool
||> printfn "#### %b %b"  // error: Type mismatch

match Some() with
| Some () ->
    true, true
| None ->
     false, false    // works with extra space at the beginning
||> printfn "#### %b %b"
```

**Comment by forki** [comment]
@latkin why did you add the suggestion label? This looks like a bug.

**Comment by latkin** [comment]
I'm not convinced this is a bug, seems like perhaps just a weird corner of the standard indentation rules.

**Comment by dsyme** [comment]
Yes, somewhat unfortunately this is "by specification" right now. http://fslang.uservoice.com seems a reasonable place to request an adjustment to this

**Comment by latkin** [comment]
Aha, here is the relevant documentation (per [MSDN](https://msdn.microsoft.com/en-us/library/dd233191.aspx))

> Another exception to the rule that contexts end when a line is not indented as far as a previous line is for infix operators, such as + and |>. Lines that start with infix operators are permitted to begin (1 + oplength) columns before the normal position without triggering an end to the context, where oplength is the number of characters that make up the operator. This causes the first token after the operator to align with the previous line.

I did not know this rule until now.
