### ISSUE TITLE
Autocompletion within object constructors should prioritize object properties higher

### ISSUE THREAD

**Issue by baronfel** [Microsoft/visualfsharp#1204]
Given this short script:

```
type Props() = 
    member val Prop1 = "" with get,set
    member val DateProp = System.DateTime.MinValue with get,set

let newProp = Props()
```

Place the cursor inside the parens and invoke intellisense.  Instead of prioritizing the properties of the type we get an alphabetized list of opened references/members.  This harms usability/discoverability of members and I believe impairs the use of the Object Constructors feature.
#### Repro steps

See above
#### Expected behavior

The autocomplete list would be sorted by a mechanism that allows object properties to float to the top in this scenario only.
#### Actual behavior

Instead I get a very long list of opened members
![image](https://cloud.githubusercontent.com/assets/573979/15367303/13052958-1cee-11e6-9d58-43124e582a06.png)
#### Known workarounds

Know the properties of the object ahead of time and use them without autocompletion.
#### Related information
- OS: Windows 10
- Branch: master
- Runtime: .NET Runtime
- Editing Tools: VS 2015 with VFPT latest

**Comment by isaacabraham** [comment]
The workaround I use is to dot *after* the close brackets and then you get the list there. But agreed, it's a poor situation and should be improved.

**Comment by baronfel** [comment]
I'd love to take a dive into the compiler and work on this.  Is this something that even belongs in this repo, or is it something that should be in FSAC proper?

**Comment by smoothdeveloper** [comment]
@baronfel it belongs to this project:

https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.LanguageService/Intellisense.fs

If you want the same to happen in Ionide/Emacs/Vim, then it will be FSAC, and also the MonoDevelop Plugin, but I don't know if they are affected by the same bug.

**Comment by dsyme** [comment]
@baronfel It would be awesome if we work out how to convince VS to show a "priority" list of completions.  There's messy "Shared Project System" C# code underlying that Intellisense.fs class, but the Visual Studio Python project system uses an updated version of the SPS that might have more advanced visual displays (not just an alphabetical list) - I'm not sure.

**Comment by baronfel** [comment]
I do see where we are able to filter the list a bit up the chain, and where
we sort it in the Fsharp declarations class.  I'll poke around in the
Python tools and see how they do it and try to report back.

**Comment by baronfel** [comment]
Ok, so the Python stuff is pretty easy to follow!

It basically breaks into the Python tools [providing ClassificationTypes](https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/PythonTools/PythonClassifierProvider.cs) to the overall VS ecosystem, and then later on registering a VS Intellisense [CompletionSource](https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/PythonTools/Intellisense/CompletionSource.cs#L59-L65) that [uses these ClassificationTypes](https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs#L1224-L1275) to determine what language construct to return [specialized completions](https://github.com/Microsoft/PTVS/blob/master/Python/Product/PythonTools/PythonTools/Intellisense/DecoratorCompletionAnalysis.cs#L54-L83) for.

These specialized completions just take a span and return some filtered set of completions in a VS Type called CompletionSet, which is a display wrapper around a set of Completions.

So it looks like we'd need to:
* Define a set of classification formats deriving from `Microsoft.VisualStudio.Text.Classification.ClassificationFormatDefinition` and export them.
* Define an `Microsoft.VisualStudio.Text.Classification.IClassifier/Microsoft.VisualStudio.Text.Classification.IClassifierProvider` that classifies a particular token
* Define various completion behaviors for different potential classifiers
* Define an `Microsoft.VisualStudio.Language.Intellisense.ICompletionSource/Microsoft.VisualStudio.Language.Intellisense.ICompletionSourceProvider` that determines the classification of the current span and constructs the completion set based on the above completion behaviors

And Ideally we'd expose these in such a way that FCS/FSAC can consume them as well, so that all editors could share the underlying behaviors.

**Comment by 7sharp9** [comment]
In XS we have dual behaviour where the list can be sorted in inheritance depth order and normal compiler ordering.   The former is quite useful and I often use it.

**Comment by vasily-kirichenko** [comment]
@7sharp9 how would you calculate inheritance depth for a Item having TType available (I mean we have TType on which (dot) completion is executed and an Item which goes to completion list)? What I managed to achieve is only detect than an Item is defined in this TType and prioritize based on that.

**Comment by 7sharp9** [comment]
@vasily-kirichenko  Recursively increment based on parentage back to object.

**Comment by dsyme** [comment]
There has been a lot of work on prioritization since the more to Roslyn.  I'll close this old specific issue
