### ISSUE TITLE
Moving reference assemblies causes compile to fail for .NETCore portable profiles (7, 78, 259)

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#121]
Opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/110) by [latkin](https://www.codeplex.com/site/users/view/latkin)

This repros for new profiles 78, 259, as well as shipped profile 7. 

If all referenced assemblies reside in the same directory, compilation works. 

If you move one of those assemblies to another directory and reference from there, compilation fails, claiming the assembly is not referenced. 

Note - so far I have only reproed for System.Threading.Tasks. This likely does not affect all possible reference assemblies. 

Repro (ZIP file attached):

``` fsharp
// PortableLibrary1.fs
namespace TypeResIssue

module ABC =
    let f n = async { do! Async.Sleep(n) } |> Async.RunSynchronously
```

Build against profile 7, using standard reference assemblies (works):

```
set fscore=%PROGRAMFILES(x86)%\Reference Assemblies\Microsoft\FSharp\.NETCore\3.3.1.0\FSharp.Core.dll
set sysruntime=%PROGRAMFILES(x86)%\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\System.Runtime.dll
set systhread=%PROGRAMFILES(x86)%\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\System.Threading.dll
set systhreadtasks=%PROGRAMFILES(x86)%\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\System.Threading.Tasks.dll
fsc -a --noframework --targetprofile:netcore -r:"%fscore%" -r:"%sysruntime%" -r:"%systhread%" -r:"%systhreadtasks%" PortableLibrary1.fs
```

Now simply move System.Threading.Tasks.dll to the local directory and recompile (fails):

```
xcopy /y "%systhreadtasks%"

fsc -a --noframework --targetprofile:netcore -r:"%fscore%" -r:"%sysruntime%" -r:"%systhread%" -r:"%cd%\System.Threading.Tasks.dll" PortableLibrary1.fs
Error: 
PortableLibrary1.fs(4,27): error FS0074: The type referenced through 'System.Threading.CancellationToken' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks'. 

PortableLibrary1.fs(4,47): error FS0074: The type referenced through 'System.Threading.CancellationToken' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks'.`
```

file attachments
- [repro.zip](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=visualfsharp&WorkItemId=110&FileAttachmentId=881748) 

> comments
> cameron_tachyus wrote Jan 5 at 1:30 PM [x] 
> I get a similar error FS0074 when building for the new Xamarin iOS Unified API. It puts the references in different directories. See https://github.com/fsharp/fsharp/issues/367

**Comment by dsyme** [comment]
Closing this very old issue that seems to be an msbuild issue in any case
