### ISSUE TITLE
Static properties with printfn

### ISSUE THREAD

**Issue by ncave** [Microsoft/visualfsharp#1226]
Side effects and all... probably by design, just not very intuitive.

#### Repro steps
```
let p1 = printfn "1"
let p2 = printfn "2"

[<EntryPoint>]
let main argv = 
    printfn "3"
    p2
    p1
    0
```

#### Expected behavior
```
3
2
1
```

#### Actual behavior
```
1
2
3
```

**Comment by forki** [comment]
This working as expected. 
p2 and p1 are no functions. 

If you change it to let p1() = printfn "1" then it's a function and evaluation will be deferred.

**Comment by ncave** [comment]
Sure, they're compiled to static unit properties that are elided in release, just side effects in debug.
