### ISSUE TITLE
Anonymous function is not inlined anymore when function called by it is marked inline (performance).

### ISSUE THREAD

**Issue by mkoerner** [Microsoft/visualfsharp#1227]
Hi,
I'm observing a counter intuitive behavior of the compiler when marking a function `inline`. I hope this is of interest to the F# compiler team.
#### Issue

Adding the `inline` qualifier to a simple function (here a `static member (+) (lhs,rhs)`) leads to an anonymous function which calls this function not being inlined anymore. At least as far as I can tell from the generated IL code. This leads to a decreased performance of the code with the `inline` present.
#### Repro steps

The file [Program.fs](https://github.com/mkoerner/fsc-inline/blob/master/Program.fs) in this [repository](https://github.com/mkoerner/fsc-inline) should reproduce the problem.
#### Expected behavior

I would expect that marking a function inline in general does not affect the inlining of an anonymous function using it.
#### Related information
- Windows 8.1
- .NET Runtime 4.5.1
- Microsoft (R) F# Compiler version 14.0.23413.0 (Visual Studio 2015)

Regards,
Mathias

**Comment by dsyme** [comment]
> I would expect that marking a function inline in general does not affect the inlining of an anonymous function using it.

@mkoerner While I get what you're saying, I don't think this is a guaranteed expectation.  The anonymous function may be assessed to be larger because of the inlining of the function it is using.  I expect that's what's happening here.  

Ultimately non-forced inlining is a heuristic choice, expecially for anonymous lambdas.  There's no specific guarantee that it will or won't happen.

**Comment by mkoerner** [comment]
@dsyme I see that it can't be/shouldn't be guaranteed. Sorry for formulating it that way.

Given the simplicity of the example, I thought it might be helpful for a compiler developer who knows the relevant parts of the compiler. The effect was very counter-intuitive to me.

**Comment by dsyme** [comment]
@mkoerner I think it's tricky. The actual TAST or IL code for NoOpInline may be quite a bit more than you think - it has to take the address of the input structs to access their properties, for example.  And size is a consideration in inlining, and infact we throw away inlining information for closures above a particular size.

**Comment by mkoerner** [comment]
@dsyme, for numeric code it would be nice to be able to force inlines (of anonymous functions and functions marked as inline) with a flag, even if it produces large assemblies, takes a long time to compile, or leads to an OutOfMemory exception. 

At least that's how I feel, probably because I'm writing a lot of code which is performance sensitive :-) Could such a flag could be a consideration for a future version of the compiler?

**Comment by dsyme** [comment]
@mkoerner I'd prefer to add a mechanism that allows you to explicitly force inlining in more situations.

**Comment by mkoerner** [comment]
@dsyme That would be much better. Do you have a concrete idea in mind? 

I'm wondering if two instead of one "annotation" would be helpful. One for functions that could/should be inlined and one for functions where inlining should be performed inside.

**Comment by dsyme** [comment]
Let's discuss this in http://github.com/fsharp/fslang-suggestions
