### ISSUE TITLE
Should FSharpList`1 be sealed?

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#123]
originally opened at [codeplex](https://visualfsharp.codeplex.com/workitem/119) by [marten_range](https://www.codeplex.com/site/users/view/marten_range)

Inheriting a List<'T> in F# is forbidden:
```fsharp
type MyList() = 
    inherit List<int>()
// Compiler: error FS0945: Cannot inherit a sealed type
```
However creative C# developers can do this:
```csharp
class MyList : FSharpList<int> 
{
    MyList () : base(1, FSharpList<int>.Empty)
    {
    }

    public IEnumerator<int> GetEnumerator ()
    {
        yield break;
    }
}
````
IMHO FSharpList should include the sealed flag to prevent misuse. 

Adding sealed to FSharpList could, I guess, introduce a regression for developers that are overriding FSharpList but I suspect it's a quite rare regression. 

Mårten

>Comments
>dsyme wrote Aug 6, 2014 at 7:25 AM [x] 
>I would be happy for the "Sealed" flag to be added to this type.

>>marten_range wrote Aug 7, 2014 at 12:59 PM [x] 
>>Tried to add the [<Sealed>] attribute. Didn't work so I will need to dig more into how the assembly metadata is generated. Should be a good exercise.

>>marten_range wrote Aug 7, 2014 at 2:44 PM [x] 

>>I think I found a place where sealed can be injected for union cases. Seems to work for types like:
>>```fsharp
type X = | Y |  Z
```
>>However FSharpList1 despise looking like a union to me is generated differently so FSharpList1 don't get tagged sealed.

>>FSharpLìst1 special cases (like TailOrNull and HeadOrDefault) has surprised me before so if anyone has any tips on how to control the code generation for FSharpList1 that would be very interesting to me.

>>Thanks.

**Comment by dsyme** [comment]
Since this affects the compiled form of FSHarp.Core.dll, this is a feature request.  Closing this in favour of the F# Language User Voice tracking entry http://fslang.uservoice.com/forums/245727-f-language/suggestions/7017131-make-f-union-types-like-list-that-have-no-subty
