### ISSUE TITLE
use in Async throws on null

### ISSUE THREAD

**Issue by polytypic** [Microsoft/visualfsharp#1231]
I just noticed the discrepancy demonstrated below:

```fs
$ fsharpi
F# Interactive for F# 4.0 (Open Source Edition)
//...
> Async.RunSynchronously (async { use x = null in return () }) ;;
System.NullReferenceException: Object reference not set to an instance of an object
//...
> use x = (null: System.IDisposable) in () ;;
val it : unit = ()
```

It might make sense to change the `Async.Using` method to better match core language `use` expression semantics.  The fix is trivial `null` check before calling `Dispose`.

**Comment by forki** [comment]
Are you talking about Async.usingA in control.fs?

        /// Implement use/Dispose
        let usingA (r:'T :> IDisposable) f =  
            tryFinallyA (fun () -> r.Dispose()) (callA f r)

If I change it to

        let usingA (r:'T :> IDisposable) f =  
            tryFinallyA (fun () -> if not (isNull r) then r.Dispose()) (callA f r)

then we change the signature. Specifically the type paramter `'T` is now restricted to have null as value.

If I change it to 

        let usingA (r:'T :> IDisposable) f =  
            tryFinallyA (fun () -> if r <> Unchecked.defaultof<'T> then r.Dispose()) (callA f r)

then we restrict `'T` to implement equality.

Both create compile errors.

Any ideas?

**Comment by forki** [comment]
OK,

        /// Implement use/Dispose
        let usingA (r:'T :> IDisposable) f =  
            tryFinallyA (fun () -> if not (Unchecked.equals r Unchecked.defaultof<'T>) then r.Dispose()) (callA f r)

compiles and seems to work.

I'm feeling dirty now and need to take a shower - but after that I will probably send a PR ;-)

**Comment by polytypic** [comment]
Yes, and I noticed the same difficulty after posting the issue.  I used [a C# primitive](https://github.com/Hopac/Hopac/blob/master/Libs/Hopac.Core/Util/Primitive.cs#L8-L10) to work around it.  The C# primitive seems to produce the desired compile outcome on .Net (no code on a struct, simple pointer test on a class). The same CIL code sequence can probably be emitted in F# somehow.

I think the `defaultof<_>` comparison will not work as desired on structs.

**Comment by forki** [comment]
@polytypic can you come up with a minimal struct sample that I can add as additional unit test to verify if it works?

**Comment by eiriktsarpalis** [comment]
If you don't mind the boxing on structs there's also
Object.ReferenceEquals()

**Comment by forki** [comment]
mhm I think we need a primitive like isNull that doesn't restrict the type and does the same as polytypic's C# primitive. That one could also be exposed so that we can use it in other libs.

**Comment by polytypic** [comment]
I just used a Dummy struct like [here](https://github.com/Hopac/Hopac/blob/master/Tests/AdHocTests/JobTests.fs#L11).  You probably also want to test that `Dispose` is actually called (do some side-effect in `Dispose`).

**Comment by forki** [comment]
I just found this little gimmick in prim-types.fs:

    let inline notnullPrim<'T when 'T : not struct>(x:'T) = (# "ldnull cgt.un" x : bool #)"

that's not too bad, right?

**Comment by forki** [comment]
https://github.com/Microsoft/visualfsharp/pull/1233/commits/301c2cc0ae77df1442cb294f202c954ecd48f17b#diff-5470ddaa52d99663f8d391a77ae04f0dR482 might work.

**Comment by forki** [comment]
Ok this is weird.

I created a new function:


![image](https://cloud.githubusercontent.com/assets/57396/15703299/d1095932-27e4-11e6-8779-d0cb85c94074.png)

![image](https://cloud.githubusercontent.com/assets/57396/15703343/0004a656-27e5-11e6-918b-0208948fce7e.png)

**Comment by forki** [comment]
Using ' instead of ^ seems to work, but no idea of IL is correct

**Comment by forki** [comment]
So @dsyme helped me and the PR is ready for review.
