### ISSUE TITLE
Incorrect error being displayed in Visual Studio 2015

### ISSUE THREAD

**Issue by EolAncalimon** [Microsoft/visualfsharp#1242]
#### Repro steps

Set up project with a similar structure to:

https://github.com/EolAncalimon/SampleFakeBuildScripts
#### Expected behavior

Should be valid code
#### Actual behavior

Red squiqqle displays error when no error reported by VSCode
#### Related information

Visual Studio 2015
Windows 7

**Comment by dsyme** [comment]
@EolAncalimon My understanding this has been fixed in the latest tools.
