### ISSUE TITLE
Wrong code generated for "Subscribe" method calls in obscure case

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#125]
Originally opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/123) by [tomasp](https://www.codeplex.com/site/users/view/tomasp)

For more information see [this StackOverflow question](http://stackoverflow.com/questions/25189077/code-gen-error-or-my-misunderstanding/25189621#25189621). 

 I'd say that this is a bug which happens specifically with the Subscribe method of IObservable<T>. Since F# treats events automatically as  IObservable<T> values, it has some special handling for them and it adds Subscribe method. If there is a Subscribe extension declared elsewhere, it clashes and things break. 

The easiest repro I could find is to create a C# project with:

``` csharp
public static class Extensions {
  public static void Subscribe(this IObservable<int> c1, Action<int> f) { 
    f(1);
    f(2);
  }
}
```

And then do exactly what you did:

``` fsharp
let partial() = 
  printfn "called"
  fun n -> ()

let a = new Event<int>()
let o = a.Publish.Subscribe(partial())
111
```

This prints "called" twice, while it should really be called just once.

> comments
> NikonTheThird wrote Aug 7, 2014 at 11:49 AM [x] 
> 
> Hello, here is some code that displays the issue with the Action<'a> delegate:
> 
> ``` fsharp
> open System
> open System.Threading
> 
> let callThrice (action : Action<_>) =
>     for i = 0 to 2 do
>         action.Invoke ()
>         Thread.Sleep 500
> 
> let makeHandler () =
>     let count = ref 0
>     fun () -> printfn "Count: %d" !count
>               incr count
> 
> let try1 () =
>     printfn "try1"
>     let handler = makeHandler ()
>     callThrice (Action<_> handler)
> 
> let try2 () =
>     printfn "try2"
>     callThrice (Action<_> (makeHandler ()))
> 
> try1 ()
> try2 ()
> printfn "Done"
> Console.ReadKey true |> ignore
> ```
> 
> try2 prints only zeros.

**Comment by dsyme** [comment]
Simplified repro all in F#. The delegate creation implied by "partial()" needs to be amortized.  


    module Extend = 
        [<System.Runtime.CompilerServices.ExtensionAttribute>]
        type Extensions() = 
           [<System.Runtime.CompilerServices.ExtensionAttribute>]
           static member Subscribe(this : System.IObservable<int>, f: System.Action<int>)  = 

              f.Invoke(1);
              f.Invoke(2);

    open Extend

    let partial() = 
      printfn "called"
      fun n -> ()

    let a = Event<int>().Publish
    let o = a.Subscribe(partial())

**Comment by dsyme** [comment]
I am going to close this as "Wont Fix".  This is an exceptionally corner-case bug and it is really quite hard to fix.
