### ISSUE TITLE
Array.blit very slow in 64bit programs compared to Buffer.BlockCopy and Array.Copy 

### ISSUE THREAD

**Issue by Ian144** [Microsoft/visualfsharp#1251]
Please provide a succinct description of the issue.

In a 32bit exe Buffer.BlockCopy, Array.Copy and Array.blit run with the times below on my PC when running F# 4.0 (FSharp.Core.dll is 4.40.23413.0)

    BenchmarkDotNet=v0.9.7.0
    OS=Microsoft Windows NT 6.2.9200.0
    Processor=Intel(R) Core(TM) i7-4960HQ CPU 2.60GHz, ProcessorCount=8
    Frequency=2533208 ticks, Resolution=394.7564 ns, Timer=TSC
    HostCLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
    JitModules=clrjit-v4.6.1080.0

    Type=BenchmarkByteArrayCopy  Mode=Throughput

              Method | ArraySize |     Median |    StdDev |
    ---------------- |---------- |----------- |---------- |
     BufferBlockCopy |        32 | 20.7475 ns | 0.2331 ns |
           ArrayBlit |        32 | 45.5956 ns | 0.4286 ns |
           ArrayCopy |        32 | 30.4521 ns | 0.1700 ns |
     BufferBlockCopy |        33 | 20.6930 ns | 0.4244 ns |
           ArrayBlit |        33 | 45.6194 ns | 0.7939 ns |
           ArrayCopy |        33 | 30.4692 ns | 0.1779 ns |
     BufferBlockCopy |       128 | 22.7526 ns | 0.4133 ns |
           ArrayBlit |       128 | 47.4659 ns | 0.6781 ns |
           ArrayCopy |       128 | 32.4409 ns | 0.2617 ns |
     BufferBlockCopy |       129 | 24.2886 ns | 0.3718 ns |
           ArrayBlit |       129 | 47.8088 ns | 0.6581 ns |
           ArrayCopy |       129 | 32.8520 ns | 0.7031 ns |
     BufferBlockCopy |       512 | 26.4369 ns | 2.0953 ns |
           ArrayBlit |       512 | 50.7762 ns | 0.9780 ns |
           ArrayCopy |       512 | 35.9572 ns | 1.2363 ns |
     BufferBlockCopy |       513 | 27.8609 ns | 2.0420 ns |
           ArrayBlit |       513 | 51.8372 ns | 1.4033 ns |
           ArrayCopy |       513 | 36.6213 ns | 2.9354 ns |

    // ***** BenchmarkRunner: End *****

In a 64bit exe Array.blit is very slow compared to the 2 other functions and its own 32bit time

    BenchmarkDotNet=v0.9.7.0
    OS=Microsoft Windows NT 6.2.9200.0
    Processor=Intel(R) Core(TM) i7-4960HQ CPU 2.60GHz, ProcessorCount=8
    Frequency=2533208 ticks, Resolution=394.7564 ns, Timer=TSC
    HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
    JitModules=clrjit-v4.6.1080.0

    Type=BenchmarkByteArrayCopy  Mode=Throughput

              Method | ArraySize |      Median |    StdDev |
    ---------------- |---------- |------------ |---------- |
     BufferBlockCopy |        32 |  19.7775 ns | 0.6260 ns |
           ArrayBlit |        32 | 283.1109 ns | 3.7490 ns |
           ArrayCopy |        32 |  19.3542 ns | 0.8748 ns |
     BufferBlockCopy |        33 |  19.8364 ns | 0.1969 ns |
           ArrayBlit |        33 | 282.3611 ns | 1.9398 ns |
           ArrayCopy |        33 |  19.2031 ns | 0.1164 ns |
     BufferBlockCopy |       128 |  21.7473 ns | 0.7311 ns |
           ArrayBlit |       128 | 291.3455 ns | 3.9101 ns |
           ArrayCopy |       128 |  21.1886 ns | 0.6586 ns |
     BufferBlockCopy |       129 |  22.3929 ns | 1.3163 ns |
           ArrayBlit |       129 | 288.2049 ns | 6.1969 ns |
           ArrayCopy |       129 |  21.5314 ns | 0.8811 ns |
     BufferBlockCopy |       512 |  25.4675 ns | 2.0725 ns |
           ArrayBlit |       512 | 290.6998 ns | 2.3029 ns |
           ArrayCopy |       512 |  24.7855 ns | 1.6994 ns |
     BufferBlockCopy |       513 |  25.7124 ns | 2.1878 ns |
           ArrayBlit |       513 | 288.8875 ns | 2.5716 ns |
           ArrayCopy |       513 |  24.9870 ns | 2.1522 ns |

#### Repro steps

Provide the steps required to reproduce the problem

1.Create an F# console app with the code below
2.Get Benchmarkdotnet from nuget (or paket)
3.Run 32bit and 64bit versions in release mode from the command line

```
type BenchmarkByteArrayCopy () =

    [<Params(32, 33, 128, 129, 512, 513)>]
    member val public ArraySize = 0 with get, set

    member val Src:byte array =  [||] with get, set
    member val Dst:byte array =  [||] with get, set

    [<Setup>]
    member this.SetupArrays () =

        this.Src <- Array.zeroCreate<byte> this.ArraySize
        let rnd = System.Random()
        for ctr = 0 to this.ArraySize - 1 do
            this.Src.[ctr] <- byte (rnd.Next() % 255)
        this.Dst <- Array.zeroCreate<byte> this.ArraySize

    [<Benchmark>]
    member this.BufferBlockCopy () = 
        System.Buffer.BlockCopy( this.Src, 0, this.Dst, 0, this.ArraySize)

    [<Benchmark>]
    member this.ArrayBlit () = 
        Array.blit this.Src 0 this.Dst 0 this.ArraySize

    [<Benchmark>]
    member this.ArrayCopy () = 
        System.Array.Copy( this.Src, 0, this.Dst, 0, this.ArraySize)
        assert (this.Src = this.Dst)

[<EntryPoint>]
let Main args =
    BenchmarkRunner.Run<BenchmarkByteArrayCopy>() |> ignore
    0
```

#### Expected behavior

64bit Array.blit performance is not 6x slower than 32bit.

#### Actual behavior

64bit Array.blit performance is6x slower than 32bit.

#### Known workarounds

use System.Array.Copy or System.Buffer.BlockCopy instead

#### Related information 

    OS=Microsoft Windows NT 6.2.9200.0
    Processor=Intel(R) Core(TM) i7-4960HQ CPU 2.60GHz, ProcessorCount=8
    Frequency=2533208 ticks, Resolution=394.7564 ns, Timer=TSC
    F# 4.0 - FSharp.Core.dll is version 4.40.23413.0

**Comment by rojepp** [comment]
I can reproduce this. It is only slower when `blit` is in an external assembly: 

> BenchmarkDotNet=v0.9.7.0
> OS=Microsoft Windows NT 6.1.7601 Service Pack 1
> Processor=Intel(R) Xeon(R) CPU E5-1650 v3 3.50GHz, ProcessorCount=12
> Frequency=3410136 ticks, Resolution=293.2434 ns, Timer=TSC
> HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE
> JitModules=clrjit-v4.6.1076.0;compatjit-v4.6.1076.0
> 
> Type=BenchmarkByteArrayCopy  Mode=Throughput
> 
>                      Method | ArraySize |        Median |     StdDev |
> --------------------------- |---------- |-------------- |----------- |
>                   ArrayBlit |        32 |   268.0323 ns |  3.1238 ns |
>            MyLocalArrayBlit |        32 |    21.1963 ns |  0.6323 ns |
>         MyExternalArrayBlit |        32 |   268.1077 ns |  2.0329 ns |
>  MyExternalArrayInlinedBlit |        32 |    19.6023 ns |  0.3112 ns |
>                   ArrayBlit |        33 |   271.1886 ns |  2.0877 ns |
>            MyLocalArrayBlit |        33 |    21.2814 ns |  0.3889 ns |
>         MyExternalArrayBlit |        33 |   266.3843 ns |  1.6139 ns |
>  MyExternalArrayInlinedBlit |        33 |    19.7673 ns |  1.1605 ns |
>                   ArrayBlit |       128 |   269.2543 ns |  1.8650 ns |
>            MyLocalArrayBlit |       128 |    23.1813 ns |  0.5487 ns |
>         MyExternalArrayBlit |       128 |   269.8834 ns |  2.6315 ns |
>  MyExternalArrayInlinedBlit |       128 |    21.5356 ns |  0.9052 ns |
>                   ArrayBlit |       129 |   276.4029 ns |  5.4407 ns |
>            MyLocalArrayBlit |       129 |    23.3213 ns |  0.2310 ns |
>         MyExternalArrayBlit |       129 |   269.4831 ns |  1.9089 ns |
>  MyExternalArrayInlinedBlit |       129 |    21.7304 ns |  1.3845 ns |
>                   ArrayBlit |       512 |   272.4070 ns |  2.0908 ns |
>            MyLocalArrayBlit |       512 |    26.2724 ns |  1.9182 ns |
>         MyExternalArrayBlit |       512 |   275.3414 ns |  3.5161 ns |
>  MyExternalArrayInlinedBlit |       512 |    24.6548 ns |  1.2643 ns |
>                   ArrayBlit |       513 |   272.9451 ns |  1.7053 ns |
>            MyLocalArrayBlit |       513 |    26.5051 ns |  1.6400 ns |
>         MyExternalArrayBlit |       513 |   272.1443 ns |  2.3032 ns |
>  MyExternalArrayInlinedBlit |       513 |    25.4807 ns |  1.9037 ns |
>                   ArrayBlit |     70000 | 2,748.9391 ns | 47.1668 ns |
>            MyLocalArrayBlit |     70000 | 2,478.7418 ns | 54.3376 ns |
>         MyExternalArrayBlit |     70000 | 2,748.8373 ns | 61.9645 ns |
>  MyExternalArrayInlinedBlit |     70000 | 2,461.5293 ns | 55.8059 ns |

Simply inlining `blit` fixes this specific issue, but that's surely not the right fix?

**Comment by dsyme** [comment]
@rojepp @Ian144 Could you share your performance testing scripts please?  I'd like to verify that putting an ``inline`` on the Array.blit function fixes this

I don't understand why inlining would help here specifically - but looking at the above it seems it does. Perhaps the JIT treats this as a special intrinsic in certain circumstances, but not for generic code.

**Comment by dsyme** [comment]
@rojepp @Ian144   I've pushed a possible fix for this issue

**Comment by Ian144** [comment]
Hi Don

My script is listed in the issue, I've copied it below.

thanks, Ian


1. Create an F# console app with the code below
2. Reference Benchmarkdotnet from nuget (or paket)
3. Run 32bit and 64bit versions in release mode from the command line

type BenchmarkByteArrayCopy () =

    [<Params(32, 33, 128, 129, 512, 513)>]
    member val public ArraySize = 0 with get, set

    member val Src:byte array =  [||] with get, set
    member val Dst:byte array =  [||] with get, set

    [<Setup>]
    member this.SetupArrays () =

        this.Src <- Array.zeroCreate<byte> this.ArraySize
        let rnd = System.Random()
        for ctr = 0 to this.ArraySize - 1 do
            this.Src.[ctr] <- byte (rnd.Next() % 255)
        this.Dst <- Array.zeroCreate<byte> this.ArraySize

    [<Benchmark>]
    member this.BufferBlockCopy () =
        System.Buffer.BlockCopy( this.Src, 0, this.Dst, 0, this.ArraySize)

    [<Benchmark>]
    member this.ArrayBlit () =
        Array.blit this.Src 0 this.Dst 0 this.ArraySize

    [<Benchmark>]
    member this.ArrayCopy () =
        System.Array.Copy( this.Src, 0, this.Dst, 0, this.ArraySize)
        assert (this.Src = this.Dst)

[<EntryPoint>]
let Main args =
    BenchmarkRunner.Run<BenchmarkByteArrayCopy>() |> ignore






On 08/07/2016 14:39, Don Syme wrote:

@rojepp<https://github.com/rojepp> @Ian144<https://github.com/Ian144> Could you share your performance testing scripts please? I'd like to verify that putting an inline on the Array.blit function fixes this

I don't understand why inlining would help here specifically - but looking at the above it seems it does. Perhaps the JIT treats this as a special intrinsic in certain circumstances, but not for generic code.

**Comment by dsyme** [comment]
Merged the PR above, hence closing this.
