### ISSUE TITLE
Cannot define a type with a same name of module after the module

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#126]
Originally opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/124) by [trek42](https://www.codeplex.com/site/users/view/trek42)
I can do this:
```fsharp
type A = ...

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module A = ...
```
but if I put type A after module A, like this:
```fsharp
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
module A = ...

type A = ...
```
I get a compile error "duplicate definition of type or module (FS0037)". 

https://stackoverflow.com/questions/24684918/module-and-class-with-same-name gives a workaround, but it doesn't work if type A is a record. There seems to be no way to define a record type after a module that has the same name. (I do find this is potentially useful as it allows me to simulate nested types -- I can put the detailed types in module A, and use it as a field in record type A). 

 Is this a compiler bug or a specified behavior? Is there any workaround? 

 thanks!

**Comment by dsyme** [comment]
Fixed by https://github.com/Microsoft/visualfsharp/pull/1319
