### ISSUE TITLE
__SOURCE_DIRECTORY__ not considered valid static type provider parameter

### ISSUE THREAD

**Issue by OkayX6** [Microsoft/visualfsharp#1265]
``__SOURCE_DIRECTORY__`` is not considered as a literal when used in a static type provider parameter.

#### Repro steps

In:

1. An F# console application
2. Add FSharp.Data package

Write this code:

```fsharp
open FSharp.Data

type Sample = JsonProvider<"Sample.json", ResolutionFolder=__SOURCE_DIRECTORY__>
```

#### Expected behavior

It should compile.

#### Actual behavior

![image](https://cloud.githubusercontent.com/assets/1169339/16087732/581062a0-3324-11e6-9962-c2b82613a808.png)

#### Known workarounds

Use ``const (...)``

    type Sample = JsonProvider<"Sample.json", ResolutionFolder= const (__SOURCE_DIRECTORY__)>

Or define a literal above and reuse it:

![image](https://cloud.githubusercontent.com/assets/1169339/16087847/cadd7250-3324-11e6-8a1f-0dc1f22aa086.png)

#### Related information 

Provide any related information 

* Windows 10 Pro
* F# 4.0
* .NET 4.6
* Visual Studio Enterprise 2015

**Comment by dsyme** [comment]
Thanks for the report.  You can also use ``const (...)``

    type Sample = JsonProvider<"Sample.json", ResolutionFolder= const (__SOURCE_DIRECTORY__)>

**Comment by dsyme** [comment]
Fixed by https://github.com/Microsoft/visualfsharp/pull/1317

**Comment by reed-adams** [comment]
This appears to be un-fixed in a recent release of VS.  We have been using this in our projects since February and today one of the developers contacted me about the build suddenly not working after they did a VS update.  Currently using VS 16.10.4, net5.0.  The const workaround still works around.

![image](https://user-images.githubusercontent.com/2051727/127237945-5ee5c952-f126-4651-8913-d00ce141ecd6.png)

**Comment by vzarytovskii** [comment]
> This appears to be un-fixed in a recent release of VS.  We have been using this in our projects since February and today one of the developers contacted me about the build suddenly not working after they did a VS update.  Currently using VS 16.10.4, net5.0.  The const workaround still works around.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/2051727/127237945-5ee5c952-f126-4651-8913-d00ce141ecd6.png)

Was fixed in https://github.com/dotnet/fsharp/issues/11610

Should be in latest VS and SDK.
