### ISSUE TITLE
Compiler allows invalid uses of byref in interface methods

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#127]
Originally opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/127) by [kvb](https://www.codeplex.com/site/users/view/kvb)

The compiler is way too lax in checking the types of signature elements for byref types. For instance, this compiles, but fails peverify:
```fsharp
type I =
    abstract M : List<byref<'s>> -> unit

type T =
    interface I with
        member this.M(l) = ()
```

**Comment by dsyme** [comment]
Closing in favour of master bug https://github.com/Microsoft/visualfsharp/issues/862
