### ISSUE TITLE
Default script references for .NET Core

### ISSUE THREAD

**Issue by ncave** [Microsoft/visualfsharp#1272]
@KevinRansom To resolve issues with incorrect script assembly resolution in `FSharpChecker.GetProjectOptionsFromScript` and `FSharpChecker.ParseAndCheckProject`, please consider adding .NET Core-specific assembly references for scripts, and/or switching to useMonoResolution instead of MSBuild for script assembly resolution on netcore.

See [#588](https://github.com/fsharp/FSharp.Compiler.Service/pull/588), [#589](https://github.com/fsharp/FSharp.Compiler.Service/pull/589) and [this](https://github.com/fsharp/FSharp.Compiler.Service/pull/589#issuecomment-227305575) in [FSharp.Compiler.Service](https://github.com/fsharp/FSharp.Compiler.Service) for one possible implementation (that can definitely be improved upon).

**Comment by dsyme** [comment]
@ncave I believe this is dealt with by https://github.com/Microsoft/visualfsharp/pull/1316/.  System.Xml.Linq is not included in the default reference list though.  I'll close this issue since 1316 is tracking a different bug.
