### ISSUE TITLE
Where is main.

### ISSUE THREAD

**Issue by gdennie** [Microsoft/visualfsharp#1282]
Since GitHub organizes code modules alphabetically and thinks it wise to decorate folder and file items with their last commit message, the structure of the source code is invisible. In particular, the code entry point is not obvious. Even the viewing of file content is constrained by an artificial narrowing of the view width. Just frustrating. (for some reason my version of fsc.exe seems to be searching for FSharp.Core 4.0 in the GAC and failing)

**Comment by brodyberg** [comment]
Is this a question/issue for the f# compiler? Is this a comment about ... github?

**Comment by gdennie** [comment]
It is an issue with FSharp within the failings of GitHub. It needs to compensate in some way. For instance, the Fsc project refers to "fscmain.fs", however, such a file was not found by a GitHub repository search. I think the source should be a description rather than an intricate puzzle.

**Comment by brodyberg** [comment]
I find the file immediately using the GitHub find file feature

<img width="621" alt="screen shot 2016-06-23 at 11 30 18 pm" src="https://cloud.githubusercontent.com/assets/151955/16329920/98a43194-399a-11e6-9101-fd61983a7005.png">

**Comment by gdennie** [comment]
I wasn't as lucky. I was surprise though, seeing as how it is clearly stated in the project file. Unfortunately, I don't have any specifics for restructuring at the moment. Perhaps additional directories...

**Comment by gdennie** [comment]
I wasn't as lucky. I was surprise though, seeing as how it is clearly stated in the project file. Unfortunately, I don't have any specifics for restructuring at the moment. Perhaps additional directories...

**Comment by cartermp** [comment]
> however, such a file was not found by a GitHub repository search

GitHub search is, unfortunately, not very "smart" right now.  @brodyberg's suggestion about using the file finder for search is your best bet for things like this.  If you want to understand the topographical organization of the codebase, your best bet is to clone and open in VS.

**Comment by cloudRoutine** [comment]
https://fsharp.github.io/2015/09/29/fsharp-compiler-guide.html

**Comment by gdennie** [comment]
Structure visibility and accessibility might be good hypertext based project. :)

**Comment by dsyme** [comment]
Please use the template in ISSUE_TEMPLATE.md when reporting bugs.  I'll close this since it doesn't appear to fit that format.
