### ISSUE TITLE
Make F# compiler and interactive part of default .NET Framework distribution

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#1284]
On Microsoft Windows operating system, .NET Framework is installed by default, this comes with C# compiler as well as other compilers and tools related to .NET Framework.

I believe having fsc.exe and fsi.exe part of that distribution is necessary to make F# scripting a viable option for scripting on windows operating system, with same level of support than batch, javascript, vbscript and powershell which all work out of the box.

Strangely F# is missing to the party and I think it is important to get this fixed.

**Comment by cloudRoutine** [comment]
If this would limit the rate at which new versions of FSharp.Core, Fsi, and Fsc could be released it doesn't seem worthwhile.

**Comment by smoothdeveloper** [comment]
@cloudRoutine, I don't see how it would limit the rate, there are still releases of independent SDK for .NET tools, Windows and F# and what I'm describing doesn't imply this should stop nor that other release scheme should not be studied.

I'm mainly looking at having .fsx (or just compiling F# code) being viable out of box on Windows, and eventually have that default install hotfixed / updated with normal operating system updates.

**Comment by smoothdeveloper** [comment]
I'm not even saying the tools should be in PATH, just that they come by default with OS, whatever release is most recent when OS is released.

**Comment by KevinRansom** [comment]
I'm afraid we will not be adding fsc/fsi and fsharp.core.dll to the desktop .net framework install.  Roslyn and the latest C# and VB are not part of the default .net install.  The latest msbuild bits (since about 2008) are not in it either.

Developers who need F# should be able to get it easily, there is not much benefit in installing it on every single client OS.

Kevin
