### ISSUE TITLE
Unexpected NullReferenceException on dotnet core test runner

### ISSUE THREAD

**Issue by duckmatt** [Microsoft/visualfsharp#1288]
In certain scenarios values can unexpectedly be null (even for values of types which cannot be null) when running `dotnet test` on an F# project

#### Repro steps

Create a dotnet core app from the [two files in here](https://gist.github.com/duckmatt/3c689807b79ccb6c329b8d4b5b709540) and run:

    dotnet restore
    dotnet test

#### Expected behavior

Expected single passing test

#### Actual behavior

    1) Error : Program+TestFoo+TestFoo.Foo
    System.NullReferenceException : Object reference not set to an instance of an object.
       at Program.TestFoo.TestFoo.Foo()

#### Known workarounds

* This only happens if the test file is the last file in the project
* Turn the module level value into a function e.g. `let config = { Hello = "Test" }` to `let config () = { Hello = "Test" }`

#### Related information 

Only tested so far on nunit test runner:

    NUnit .NET Core Runner 3.4.0
    Copyright (C) 2016 Charlie Poole
    Runtime Environment
        OS Platform: Windows
        OS Version: 10.0.10586
            Runtime: win10-x64

Test runs as expected under nunit test runner on .NET framework

**Comment by forki** [comment]
is this a compiler issue or dotnet cli issue?
/cc @davkean @enricosada

**Comment by duckmatt** [comment]
Sorry, the issue was emitting an entry point which was mangling the last test file, without it the tests run as expected under xunit and nunit

**Comment by cartermp** [comment]
FYI: there will be documentation on this that will "ship" with the .NET Core runtime/libraries RTM on Monday.
