### ISSUE TITLE
#nowarn codes undocumented for vs 2012/ vs 2013

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#129]
Originally posted on [Codeplex](https://visualfsharp.codeplex.com/workitem/137) by [citykid](https://www.codeplex.com/site/users/view/citykid)

@latkin commented:
Weird - they are doc'ed in the [VS 2010 version](http://msdn.microsoft.com/en-us/library/vstudio/dd233195(v=vs.100).aspx) of MSDN, but missing from the [2012](http://msdn.microsoft.com/en-us/library/vstudio/dd233195(v=vs.110).aspx) and [2013](http://msdn.microsoft.com/en-us/library/vstudio/dd233195(v=vs.120).aspx) versions of the page.

**Comment by KevinRansom** [comment]
Assigned to Bill.

**Comment by billchi-ms** [comment]
Submitted fix, thanks for catching that!  I can't say when it will appear on MSDN due to our machinery's pub schedule over the next few weeks.

**Comment by KevinRansom** [comment]
Fixed:  https://msdn.microsoft.com/en-US/library/3c8fc5c0-5b3e-4096-9772-68fd3b7c7a11(v=vs.140).aspx

vs 2014 is not yet the default page, so you will need to follow the link for now.
