### ISSUE TITLE
Augmented members considered incorrect even though all conditions are satisfied

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#1293]
From https://github.com/fsharp/fsharp/issues/581

I want to compile such a piece of code

``` F#
namespace Models

type ElementList = LineElement ImmutableList

type LeadingLine =
    { Elements : ElementList
      InputEnding : Ending
      OutputEnding : Ending }

namespace Models.Operations

open Models

module LeadinLine =

    let insertElement line index element =
        { line with Elements = line.Elements.Insert(index, element) }

    let removeElement line element =
        { line with Elements = line.Elements.Remove(element) }

    let replaceElement line replacableElement replacementElement =
        { line with Elements = line.Elements.Replace(replacableElement, replacementElement) }

    let containsElement line element =
        line.Elements.Contains(element)

namespace Models

open Models.Operations.LeadinLine

type LeadingLine with
    member line.Contains = containsElement line
    member line.Insert = insertElement line
    member line.Remove = removeElement line
    member line.Replace = replaceElement line
```

And all the conditions are satisfied: same file, same namespace.
#### Expected behavior

Successful compilation
#### Actual behavior

`error FS0644: Namespaces cannot contain extension members except in the same file and namespace where the type is defined. Consider using a module to hold declarations of extension members.`
#### Related information
- Windows 10 Pro 14372
- PCL Profile259
- Visual Studio 2015 Enterprise Update 2
- Severity: I can't achieve my goal

**Comment by forki** [comment]
can you please make the sample self-contained?

![image](https://cloud.githubusercontent.com/assets/57396/16420820/1b68d7c2-3d53-11e6-8a63-4ff19498f127.png)

**Comment by dsyme** [comment]
The problem here is the error message ``error FS0644: Namespaces cannot contain extension members except in the same file and namespace where the type is defined. Consider using a module to hold declarations of extension members.``

should be 

``error FS0644: Namespaces cannot contain extension members except in the same file and namespace declaration group where the type is defined. Consider using a module to hold declarations of extension members.``

**Comment by dsyme** [comment]
@xperiandri If you'd like to add a suggestion to remove this restriction, please use http://fslang.uservoice.com, thanks

**Comment by xperiandri** [comment]
@dsyme, I run out of votes.
The number of votes available is too small!

**Comment by xperiandri** [comment]
@forki, use FSharp.Collections.Immutable

The content of NuGet.config for solution
``` XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NuGet v3" value="https://api.nuget.org/v3/index.json" />
    <add key="fsharp-collections-immutable" value="https://www.myget.org/F/fsharp-collections-immutable/api/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by xperiandri** [comment]
`Ending` does not matter, just remove it

**Comment by xperiandri** [comment]
@dsyme, so the primary approach is to implement members and then implement a module with functions that use that members. Is it correct?
I thought that functional first means having modules with functions and then attaching them to types. But without ability to implement interface in augmentation or override in augmentation it is impossible.

**Comment by dsyme** [comment]
@xperiandri You can do it either way.  You just can't currently split the module implementation into a separate namespace.

> I thought that functional first means having modules with functions and then attaching them to types.

"Functional-first" means using functional programming as your first technique to solve problems and express data manipulations. But it doesn't exclude object type design - it just places it in its proper place.  

In any case, the above code looks perfect to be a single immutable type (class or record) with associated members.  In this case I don't see any value in the "Operations" namespace and module.

**Comment by xperiandri** [comment]
The major issue is that augmentations are very limited in usage.
From my point of view augmentations are like partial classes in C#. They have to serve 2 goals:
1. Ability to split written code from generated code
2. Ability to define a primary point of view. Like you do with UML diagrams or EDMX diagrams where the diagram must show a primary point of view, or scenario, or reveal the intent or a problem using 7±2 entities so that consumer can instantly realize what is described.

In my case the primary point of view is data model.
``` F#
type LeadingLine =
    { Elements : ElementList
      InputEnding : Ending
      OutputEnding : Ending }

    static member Empty =
        { Elements = ElementList.Empty
          InputEnding = Ending.OpeningFrame
          OutputEnding = Ending.OpeningFrame }

    interface IImmutableList<LineElement>
    interface System.Collections.IEnumerable
```
And operations on that class are secondary.
``` F#
type LeadingLine with
    member line.Contains (element : #LineElement) = line.Elements.Contains(element)
    member line.FindAll = line.Elements.FindAll
    member line.FindAllParts id = line.FindAll(Predicate(checkElementById (=) id))
    member line.RemoveAllParts id = line.Elements.RemoveAll(Predicate(checkElementById (=) id))
    // IImmutableList
    member line.Clear() = { line with Elements = line.Elements.Clear() }
    member line.IndexOf element = line.Elements.IndexOf element
    member line.Insert(index, element) = { line with Elements = line.Elements.Insert(index, element) }
    member line.Remove element =
        { line with Elements = line.Elements.Remove(element) }
    member line.RemoveAll(predicate) = { line with Elements = line.Elements.RemoveAll(predicate) }
    member line.RemoveAt(index) = { line with Elements = line.Elements.RemoveAt(index) }
    member line.Replace(replacable, replacement) =
        { line with Elements = line.Elements.Replace(replacable, replacement) }
    // IReadOnlyList
    member line.Item with get(index) = line.Elements.[index]
    // IReadOnlyCollection
    member line.Count = line.Elements.Count
    interface IImmutableList<LineElement> with
        member line.Add item = { line with Elements = line.Elements.Add item } :> _
        member line.AddRange items = { line with Elements = line.Elements.AddRange items } :> _
        member line.Clear() = line.Clear() :> _
        member line.IndexOf(item, index, count, comparer) =
            line.Elements.IndexOf(item, index, count, comparer)
        member line.Insert(index, item) = line.Insert(index, item) :> _
        member line.InsertRange(index, items) =
            { line with Elements = line.Elements.InsertRange(index, items) } :> _
        member line.LastIndexOf(item, index, count, comparer) =
            line.Elements.LastIndexOf(item, index, count, comparer)
        member line.Remove(item, comparer) =
            { line with Elements = line.Elements.Remove(item, comparer) } :> _
        member line.RemoveAll(predicate) = line.RemoveAll(predicate) :> _
        member line.RemoveAt(index) = line.RemoveAt(index) :> _
        member line.RemoveRange(index : int, count : int) =
            { line with Elements = line.Elements.RemoveRange(index, count) } :> IImmutableList<_>
        member line.RemoveRange(items : LineElement seq, comparer) =
            { line with Elements = line.Elements.RemoveRange(items, comparer) } :> IImmutableList<_>
        member line.Replace(replacaple, replacement, comparer) =
            { line with Elements = line.Elements.Replace(replacaple, replacement, comparer) } :> _
        member line.SetItem(index, item) =
            { line with Elements = line.Elements.SetItem(index, item) } :> _
        member line.Item with get(index) = line.[index]
        member line.Count = line.Count
        member line.GetEnumerator() = line.Elements.GetEnumerator() :> _
    interface System.Collections.IEnumerable with
        member line.GetEnumerator() = line.Elements.GetEnumerator() :> _
```
I would better put them into absolutely separate file. Or at leas just leave class members but put interface members away.

So I wonder why interface implementations in augmentations are deprecated?

**Comment by dsyme** [comment]
Fixed the error message.  Anything else here would be a language suggestion (please open an fslang-suggestion issue if you'd like it tracked)
