### ISSUE TITLE
Microsoft's ApiPort.exe reports FSharp.Core.dll to be only 95.78% compatible with .NET 4.6.2

### ISSUE THREAD

**Issue by Thorium** [Microsoft/visualfsharp#1304]
I ran Microsoft's ApiPort.exe report to two dlls, FSharp.Core.dll and FSharp.Data.SQLProvider (which has no dependencies but FSharp.Core) and even though they are created with .NET 4.5.1 the Microsoft compatibility checker claims they are not compatible.

Also running on .NET 4.6.2 gave same errors.
Here is the results: http://thorium.kapsi.fi/copy.html

Microsoft/dotnet-apiport#304

**Comment by eriawan** [comment]
@Thorium 

Based on reply from @terrajobst on the your [dotnet-apiport issue 304](https://github.com/Microsoft/dotnet-apiport/issues/304) this is an issue of ApiPort, not FSharp.Core,

We should isolate this as ApiPort issue based on the reply from the dotnet team, not FSharp.Core issue. I suggest we close this issue.

cc @cartermp @KevinRansom @dsyme
