### ISSUE TITLE
Wrong SRTP constraints inferred

### ISSUE THREAD

**Issue by gmpl** [Microsoft/visualfsharp#1306]
Long time ago I was trying to define generic constants, something like the existing GenericZero and GenericOne, but involving a method constraint of a typar and a specific type since we can't simulate static member outside the F# compiler.
But writing those signatures were not possible because of [this limitation](https://fslang.uservoice.com/forums/245727-f-language/suggestions/7887270-allow-all-inferrable-srtp-constraints-to-be-writte) the only solution I found was involving a phantom type:

    type M() =
        static member ($) (x:string, M) = ""
        static member ($) (x:int   , M) = 0
        static member ($) (x:float , M) = 0.0

    let inline empty< ^R, ^M when (^R or ^M) : (static member ($) : ^R * M ->  ^R) and ^M :> M> =
        let m = M()
        ((^R or ^M) : (static member ($): ^R * M -> ^R ) (Unchecked.defaultof<'R>, m))

    let a :int    = empty<  _ , M >
    let b :string = empty<  _ , M >

But now that there is a [PR which solves that issue](https://github.com/Microsoft/visualfsharp/pull/1278) I tried again using that version and found that in fact that limitation was hiding a bug in the type inference.

#### Repro steps

. Download the [fixed F# compiler ](https://github.com/Microsoft/visualfsharp/pull/1278) 
. type build
. open it with Visual Studio
. Set FSIANYCPU as Start Project
. Press F5
. Paste this code:

    type M() =
        static member ($) (x:string, M) = ""
        static member ($) (x:int   , M) = 0
        static member ($) (x:float , M) = 0.0

    let inline empty< ^R when ( ^R or  M) : (static member ( $ ) :  ^R *  M ->  ^R)> =        
        let m = M()
        Unchecked.defaultof< ^R> $ m: ^R

#### Expected behavior

    val inline empty< ^R when ( ^R or  M) : (static member ( $ ) :  ^R * M ->  ^R) > :
       ^R when ( ^R or  M) : (static member ( $ ) :  ^R * M ->  ^R)

#### Actual behavior

It fails to compile with this error:

          Unchecked.defaultof< ^R> $ (m:M) : ^R;;
      ----^^^^^^^^^^^^^^^^^^^^^^^^
    stdin(155,5): error FS0001: A type parameter is missing a constraint 'when ( ^R or  ^_arg2) : (static member ( $ ) :  ^R *  ^_arg2 ->  ^R)'

#### Known workarounds

No workaround found apart from the phantom type solution above mentioned which is very ugly.

#### Related information 

Branch: 

* Branch https://github.com/Microsoft/visualfsharp/pull/1278

BTW: why in cases like this (even without the fix) the compiler complains about a missing constraint instead of inferring it for you as it does normally?

**Comment by dsyme** [comment]
Interesting - nice repro, thanks.  Will need to look into it more.

**Comment by dsyme** [comment]
@gmpl I have updated the fix for 1278 with a fix for this problem too

**Comment by gmpl** [comment]
@dsyme  Cool, thanks so much.
I tried the code, it compiles but now when I try to use the generic constant I get this error:

    stdin(9,15): error FS0001: None of the types 'int, M' support the operator '$'
    > let (a:int) = empty<M> ;;

      let (a:int) = empty<M> ;;
      --------------^^^^^^^^

But M supports the operator $

**Comment by dsyme** [comment]
@gmpl Could you add a full repro for that?  In the original repro code above, ``empty`` takes two type parameters.

**Comment by gmpl** [comment]
@dsyme Sorry, I was testing only the repro, but now the full code should be:

    type M() =
        static member ($) (x:string, M) = ""
        static member ($) (x:int   , M) = 0
        static member ($) (x:float , M) = 0.0

    let inline empty< ^R when ( ^R or  M) : (static member ( $ ) :  ^R *  M ->  ^R)> =        
        let m = M()
        Unchecked.defaultof< ^R> $ m: ^R

    let (a:int) = empty
    let (a:string) = empty

and this works !!!

Are you going to include this fix in the next F# release?

**Comment by dsyme** [comment]
@gmpl I imagine it will be integrated along with all the other fixes in the pipe

**Comment by gmpl** [comment]
@dsyme That will be a really cool feature. Thanks.

I tried now to create an alias for the generic constant, but:

    > let inline x = empty ;;

      let inline x = empty ;;
      -----------^

    stdin(41,12): error FS0832: Only functions may be marked 'inline'

I guess this is by-design.
Then using explicit type arguments:

    > let inline x< ^T> = empty< ^T> ;;
      let inline x< ^T> = empty< ^T> ;;
      --------------------^^^^^

    stdin(45,21): error FS0001: A type parameter is missing a constraint 'when ( ^T or M) : (static member ( $ ) :  ^T * M ->  ^T)'

and this is because when the type parameter is explicit the constraint should also be explicit, so if you write the whole signature it will work:

    let inline x< ^T when ( ^T or M) : (static member ($) :  ^T * M ->  ^T)> = empty< ^T>

But regarding the first case I think you said once that you might consider removing that limitation in the future. Do you think it should be allowed? I don't see anything wrong with that.

**Comment by dsyme** [comment]
You mean ``let inline x = empty``?  I don't think we would add a feature to infer something to be a type function (executed as a method call) without explicit annotations - the change in semantics by adding``inline`` is just too great.

**Comment by gmpl** [comment]
@dsyme I see your point, for me it's clear what's happening but I agree that for someone else might be confusing. I have some alternative ideas which may be a better compromise but I think is better to use the user voice for that ;)

**Comment by dsyme** [comment]
Fixed by the above PR
