### ISSUE TITLE
Fix memory leak in Async.AwaitWaitHandle

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#131]
From [Codeplex](https://visualfsharp.codeplex.com/workitem/139) opened by [Pepeiborra](https://www.codeplex.com/site/users/view/Pepeiborra)

The details and a simple fix are available at GitHub: 
https://github.com/fsharp/fsharp/pull/333

**Comment by latkin** [comment]
This user declined to submit a CLA, so we could not accept the fix. If someone else wants to pick it up, feel free.

**Comment by forki** [comment]
I will take a look
