### ISSUE TITLE
Right-clicking within editor window of VS 2015 opens FSI

### ISSUE THREAD

**Issue by jmsul** [Microsoft/visualfsharp#1313]
#### Description

In Visual Studio 2015 and '15' Preview 2, right-clicking within the text editor window for any reason opens the FSI window. This should not happen. VS 2013 had the proper behavior: one needed to right-click and select "Execute in F# Interactive" from the context menu in order to activate the FSI window.

This seems to be an unresolved bug. The only other references to this issue I've been able to find:
[http://stackoverflow.com/a/33506763](url)
[http://stackoverflow.com/q/33143719](url)

I can't tell if this is universal behavior or a problem with certain installations. AFAIK, it happens across installs, across machines, with both the ISO and online installer.
#### Repro steps

Have FSI window closed. Simply perform a single right-click within the text editor of a *.fsx or *.fs file. Alternatively, hit the menu key on the keyboard when cursor is within the editor.

This is a very annoying problem when you are trying to copy or paste or do anything else with the context menu. 
#### Expected behavior

The only thing that should happen is that the context menu should appear. FSI window should not activate until selecting it from the context menu.
#### Actual behavior

The FSI window will pop into view, disrupting whatever you were doing. The window has to be wrangled with constantly. 
#### Known workarounds

Use VS 2013 instead. 
#### Related information
- Visual Studio 2015 Update 3, Visual Studio '15' Preview 2
- Visual F# 4.0 and 4.1
- Moderate severity. Very disruptive.

**Comment by dungpa** [comment]
This has been fixed in https://github.com/Microsoft/visualfsharp/issues/1983. The fix should be available in VS 2017 RC3.
