### ISSUE TITLE
Source code anchors are wrong sometimes

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#132]
Originally opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/148) by [xionghuaidong ](https://www.codeplex.com/site/users/view/xionghuaidong)

I'm trying to learn F#. I found it interesting, but the following bug is quite annoying. 

Sometimes, when multiple errors happen in F# Interactive, source code anchors in error messages are wrong. They point to the source code of some previous error. See the following screenshot. 
Image 

My F# is part of Microsoft Visual Studio Professional 2013 English Version 12.0.30723.00 Update 3, and my operating system is Windows 8.1 Professional Simplified Chinese version.

file attachments

image001.pngI'm trying to learn F#. I found it interesting, but the following bug is quite annoying. 

 Sometimes, when multiple errors happen in F# Interactive, source code anchors in error messages are wrong. They point to the source code of some previous error. See the following screenshot. 
Image 

My F# is part of Microsoft Visual Studio Professional 2013 English Version 12.0.30723.00 Update 3, and my operating system is Windows 8.1 Professional Simplified Chinese version.

![image001](https://cloud.githubusercontent.com/assets/5175830/5911393/fbe0d660-a579-11e4-91ef-8ec4ec4f2973.png)

> comments
> brodyberg wrote Oct 10, 2014 at 11:51 AM [x] 
> That is indeed odd. I see that if I continue incrementing FSI will continue to report the error as with 2F: 
> stdin(1,1): error FS1156: This is not a valid numeric literal. Sample formats include 4, 0x4, 0b0100, 4L, 4UL, 4u, 4s, 4us, 4y, 4uy, 4.0, 4.0f, 4I.
> 2F;;
> 2F;;
>  ^^
> 
> stdin(2,1): error FS1156: This is not a valid numeric literal. Sample formats include 4, 0x4, 0b0100, 4L, 4UL, 4u, 4s, 4us, 4y, 4uy, 4.0, 4.0f, 4I.
> 
> 3F;;
> 
> 2F;;
>  ^^
> 
> stdin(2,1): error FS1156: This is not a valid numeric literal. Sample formats include 4, 0x4, 0b0100, 4L, 4UL, 4u, 4s, 4us, 4y, 4uy, 4.0, 4.0f, 4I.
> 
> 4F;;
> 
> 2F;;
>  ^^
> 
> stdin(2,1): error FS1156: This is not a valid numeric literal. Sample formats include 4, 0x4, 0b0100, 4L, 4UL, 4u, 4s, 4us, 4y, 4uy, 4.0, 4.0f, 4I.
> 
> 5F;;
> 
> 2F;;
>  ^^
> 
> stdin(2,1): error FS1156: This is not a valid numeric literal. Sample formats include 4, 0x4, 0b0100, 4L, 4UL, 4u, 4s, 4us, 4y, 4uy, 4.0, 4.0f, 4I.
> 
> What's even more interesting is this: 
> 
> { "foo" };;
> 
> 2F;;
>  ^^^^^^^^^

**Comment by latkin** [comment]
(my quick repro investigation, from earlier internal mail)

This does appear to be very annoying… for a certain batch of lexing errors, the reported range from LexBuffer simply does not increment for each new line.

Result is that error messages and “console squiggles” are now permanently (for the rest of the session) out of alignment with the culprit code that gets printed

```
Microsoft (R) F# Interactive version (private)
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> 1F ;;

  1F ;;
  ^^

stdin(1,1): error FS1156: This is not a valid numeric literal. Sample formats include 4, 0x4, 0b0100, 4L, 4UL, 4u, 4s, 4
us, 4y, 4uy, 4.0, 4.0f, 4I.
> 99999B ;;

  99999B ;;
  ^^^^^^

stdin(2,1): error FS1156: This is not a valid numeric literal. Sample formats include 4, 0x4, 0b0100, 4L, 4UL, 4u, 4s, 4
us, 4y, 4uy, 4.0, 4.0f, 4I.
> --2 ;;

  99999B ;;
  --^

stdin(2,3): error FS1208: Invalid prefix operator
> let x = 20 ;;

val x : int = 20

> x.NoSuchMember ;;

  let x = 20 ;;
  --^^^^^^^^^^^^

stdin(4,3): error FS0039: The field, constructor or member 'NoSuchMember' is not defined
```

**Comment by enricosada** [comment]
i'll try to fix this one

**Comment by enricosada** [comment]
minimal repro:

```

> gg;;

  gg;;
  ^^

stdin(1,1): error FS0039: The value or constructor 'gg' is not defined
> 1F;;

  1F;;
  ^^

stdin(2,1): error FS1156: This is not a valid numeric literal. Sample formats in
clude 4, 0x4, 0b0100, 4L, 4UL, 4u, 4s, 4us, 4y, 4uy, 4.0, 4.0f, 4I.
> hh;;

  1F;;
  ^^

stdin(2,1): error FS0039: The value or constructor 'hh' is not defined
>
```

now every other evaluation has an invalid -1 line offset.
The offset is cumulative (evaluate 2F add another -1 offset)

The error doesn't occur if the lex error is the first of the session

```
> 1F;;

  1F;;
  ^^

stdin(1,1): error FS1156: This is not a valid numeric literal. Sample formats in
clude 4, 0x4, 0b0100, 4L, 4UL, 4u, 4s, 4us, 4y, 4uy, 4.0, 4.0f, 4I.
> hh;;

  hh;;
  ^^

stdin(2,1): error FS0039: The value or constructor 'hh' is not defined
> gg;;

  gg;;
  ^^

stdin(3,1): error FS0039: The value or constructor 'gg' is not defined
```

**Comment by xionghuaidong** [comment]
Pity! This bug is not fixed in VS2015!

**Comment by dsyme** [comment]
I'm closing this - it's a really minor cosmetic bug to do with numeric literal forms.
