### ISSUE TITLE
Set.contains is quite slow

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#133]
Originally opened on [Codeplex](https://visualfsharp.codeplex.com/workitem/152) by [CraigStuntz](https://www.codeplex.com/site/users/view/CraigStuntz) @CraigStuntz

Set.contains is 50 times slower than HashSet<T>.Contains() for a case where the set is fairly small. An optimized set based on a dense array is 100 times faster. 

I have a test application which compares various methods of testing whether an enum is within a certain set of possible values here: 
https://github.com/CraigStuntz/Enum-Set-Contains-Performance-Test 

I know that Set and HashSet have different use cases and performance goals, but it might be worth looking into whether the performance of contains can be improved. 

>comments
>marten_range wrote Oct 16, 2014 at 1:30 PM [x] 
>I looked into and from my experimenting this seems to have more to do with the GenericComparer used by F# Set is slow for enumerations. For integers there are special cases that are fast. 

>A fix for this would probably involve optimizing the GenericComparer for enumerations types.
>>latkin wrote Oct 19, 2014 at 11:42 AM [x] 
Don's recent PR made significant improvements to generic comparison, and does appear to make a big difference here (F# set is now ~3.2x faster for optimized) . However F# set is still slow compared to other options for this particular test.

>>If someone wants to dig into this that would be great, but I don't think this is a super high priority.
HashSet:                  17.8 ms
F# set:                    177.7 ms
C#:                            48.5 ms
C# (int input):            1.35 ms
F# (generic enum):   24.1 ms
F# (IConvertible):     54.3 ms
F# (int input):            1.35 ms

**Comment by dsyme** [comment]
Closing this as it's a performance suggestion without a corresponding concrete improvement.  (We definitely need performance improvements, but issues need to be more concrete, per the CONTRIBUTING.md guidelines)
