### ISSUE TITLE
Is there a repo of markdown files for the tryfsharp learn website?

### ISSUE THREAD

**Issue by rogersachan** [Microsoft/visualfsharp#1331]
I'm trying to push for a merge of said lessons into the dotnet/training-tutorials but I've had to do nearly all of this manually. If there were to be an changes to the website these would not sync, and complicate  efforts to keep documentation in line. It would be better if we could add said tutorials via a submodule.

Thanks,
Roger

**Comment by rogersachan** [comment]
I'll be making it manually either way for the [dotnet/training-tutorials](https://github.com/dotnet/training-tutorials) repo. You can check my progress at [rogersachan/training-tutorials](https://github.com/rogersachan/training-tutorials).

**Comment by brodyberg** [comment]
Maybe @cartermp knows the answers to these questions.

**Comment by cartermp** [comment]
Whoa!  I missed this issue.

Unfortunately, there is no repo of markdown files for the tryfsharp website content that I know of.  @rogersachan, your work would be the first one.

I think this work is *awesome* and it's totally in line with what we ultimately want to do in the tutorials section of the [tutorials section of the website](https://www.microsoft.com/net/learn).  Thanks a lot, @rogersachan!

**Comment by dsyme** [comment]
Closing old discussion
