### ISSUE TITLE
Protected Internal members are not visible in F# with InternalsVisibleTo

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#1332]
`protected internal` in C# means famorassem, e.g. the visibility is the superset of protected and internal.

#### Repro steps

Class in C#:

```C#
namespace A
{
    public class Class1
    {
        protected static int Protected;
        internal static int Internal;
        protected internal static int ProtectedInternal;
        public static int Public;
    }
}
```

I added this to the AssemblyInfo.cs

```C#
[assembly: InternalsVisibleTo("B")]
[assembly: InternalsVisibleTo("C")]
```

I then added two additional projects, B (C#) and C (F#).

__C#__
![image](https://cloud.githubusercontent.com/assets/4236651/16672159/87547164-44a4-11e6-920a-2449e215ff45.png)

__F#__
![image](https://cloud.githubusercontent.com/assets/4236651/16672164/97ab2fa8-44a4-11e6-9c71-3229b19a52f5.png)
(The internal member is visible, so InternalsVisibleTo works in general)

#### Expected behavior

I would have expected the member ProtectedInternal to be visible.

#### Actual behavior

Only Internal (and public ofc.) is visible

Please not that this is notjust a tooling issue - when I try to compile the project, I get this error message:

`A.Class1.ProtectedInternal <- 5`

> error FS1097: The struct or class field 'ProtectedInternal' is not accessible from this code location

#### Known workarounds

I need to modify the C# project and make the member either only internal, so that InternalsVisibleTo works, or make it public.

#### Related information 

Provide any related information 

![image](https://cloud.githubusercontent.com/assets/4236651/16672216/e924e0c2-44a4-11e6-994a-11d96d0a633b.png)

**Comment by dsyme** [comment]
Fix linked above, thanks for the excellent bug report

**Comment by 0x53A** [comment]
@dsyme damn, that was fast, thanks!

There is also one other visibility in IL, famANDassembly, e.g. it can only be accessed by sub-types in the same assembly (and by subtypes in other assemblies, if you use InternalsVisibleTo

AFAIK it is not yet possible to generate this via any language, but C# had wanted to implement it for C#6 (not sure if it was post poned to C#7 or completeley scraped), and there is always the possibility to muck with IL manually...

I modified an assembly with DnSpy:

![image](https://cloud.githubusercontent.com/assets/4236651/16690759/b92284f8-4529-11e6-8473-fd56f07fb351.png)

The member is invisible outside the subtype
![image](https://cloud.githubusercontent.com/assets/4236651/16690743/a9f6cb42-4529-11e6-852e-dc3dbe0d23c2.png)

The member is visible inside the subtype
![image](https://cloud.githubusercontent.com/assets/4236651/16690729/99d5cc54-4529-11e6-92f9-349724ea52b1.png)

In F#, the FamAndAssembly member is NOT visible, but funnily, the ProtectedInternal member is visible in the subtype.

![image](https://cloud.githubusercontent.com/assets/4236651/16690798/eaa2f472-4529-11e6-8c3b-03b2ecb8d590.png)

This was tested with the same version ( so without your fix).


Attached is the modified assembly (A.dll) 
[A.zip](https://github.com/Microsoft/visualfsharp/files/354454/A.zip)

**Comment by ReedCopsey** [comment]
On Fri, Jul 8, 2016 at 7:39 AM, Lukas Rieger <notifications@github.com>
wrote:

> famANDassembly


Note that you can generate types/methods with this access in C++/CLI (it's
the `public protected:` modifier).

**Comment by dsyme** [comment]
I'll close this - please open a separate issue for the one above
