### ISSUE TITLE
Improve error message for FS3022

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#134]
Originally at [CodePlex](https://visualfsharp.codeplex.com/workitem/155) by [slace](https://www.codeplex.com/site/users/view/slace)

I recently hit  FS3022 when working on a  Type Provider. It was solved by  moving a let binding, but this wasn't obvious from the error message, it was pointed out via twitter. 

Something to better convey that that was the problem would make it easier to resolve.

**Comment by forki** [comment]
I wonder what the original code looked like. 
We currently have no test for FS3022 and I'd like to add one.

**Comment by dsyme** [comment]
Search for "InvalidInvokerExpression", which reveals a test very similar to this case which can used as a basis 

C:\GitHub\dsyme\visualfsharp\tests\fsharp\typeProviders\negTests\provider.fsx

            |   _, [||] when mb.Name = "get_InvalidInvokerExpression" ->
                    Quotations.Expr.WhileLoop(Quotations.Expr.Value(true), Quotations.Expr.Value((), typeof<unit>))

I suggest the error message change to something like "Unsupported constant type '%s'. Quotations provided by type providers can only contain simple constants. You may need to move a value declared outside a provided quotation literal to be a 'let' binding inside the qutoation literal."
