### ISSUE TITLE
Cannot evaluate expression because the code of the current method is optimized

### ISSUE THREAD

**Issue by gmpl** [Microsoft/visualfsharp#1343]
When trying to debug the compiler all I get when I look into 99% of the values is "Cannot evaluate expression because the code of the current method is optimized."

I tried [removing all the optimization flags](https://fsharp.github.io/2015/09/29/fsharp-compiler-guide.html#how-to-debug-optimized-assembly-for-generated-code) but no luck.

Could you please explain how to avoid this and consider adding it to the devguide?

Otherwise, is there a way to pretty-print the <code>csenv</code> in the Constraint Solver?

**Comment by dsyme** [comment]
@gmpl I'd like to get to the bottom of this too.  I've been using the Debug build and have not _always_ been seeing this, but yes, it does happen.  

For example I have been seeing timeouts when displaying the properties of some TAST objects which then seem to cascade to this problem.

An accurate step-by-step repro that we can focus on and solve together might be needed.  If you have time could you please write one? Include your various debug settings (e.g. Just My Code, Show Raw Structure of Obejcts etc.)

**Comment by gmpl** [comment]
Thanks @dsyme , I didn't know it was a known issue.
So here's the details:

Visual Studio Professional 2015 version 14.0.25.123.00 Update 2

Steps to reproduce:

. Checkout the latest version
. Build
. Set FSIANYCPU as default project
. Set a breakpoint, somewhere in the ContraintSolver.fs 
. Hit F5

All this with a fresh visual studio installation with the default options, so I think it should be easy to reproduce.
Then tried unchecking "Enable Just my Code" but still the same results.
Tried enabling "Show Raw Structure of Objects" and it gets a bit better, but still many values not showing with that message.
Apart from that, each time I press F10 to step it takes around 1 minute to come back.

**Comment by dsyme** [comment]
@gmpl thanks :) Could you specify an exact location for the breakpoint please? 

Also is it really 1min, or just "a long time". 

Does changing to legacy debug engine help. 

Also does debugging via a new instance of VS started using "devenv /debugexe path\to\fsiAnuCpu.exe" help with stepping perf? If so that might indicate memory usage of devenc.exe is a problem. 

Thanks

**Comment by gmpl** [comment]
@dsyme I'm trying now setting a breakpoint in the first line of the function <code>solveTypMeetsTyparConstraints</code>.
It is really 1 minute more or less, I tried changing to legacy and have the impression that it's a bit better at startup but still very slow.

Tried also via the new instance but it doesn't help.

Here are some screenshots:
![screenshot1](https://cloud.githubusercontent.com/assets/1261319/16792631/70f0dbe0-48ca-11e6-9e73-26c2535c99f4.jpg)

Have a look at these values here

![screenshot2](https://cloud.githubusercontent.com/assets/1261319/16792633/71122002-48ca-11e6-9f64-4dd4095ce81c.jpg)

And these are now my Debug Settings

![screenshot3](https://cloud.githubusercontent.com/assets/1261319/16792632/710fe53a-48ca-11e6-920f-f67e32ca7ee4.jpg)

**Comment by gmpl** [comment]
@dsyme Just tried restarting the computer so the first thing I do when it comes back is to open the solution and hit F5 and now the step time seems to be normal.
I will try to work with only one instance of Visual Studio open, but still have the problem of the values as shown on my screenshots.

**Comment by gmpl** [comment]
@dsyme OK, 5th time I press F5 in that debug session that started well and it already slowed down again.

**Comment by dsyme** [comment]
@gmpl Thanks for the specific repro steps, and the updated info.

**Comment by dsyme** [comment]
@gmpl I recall what the problem is now.  The ``update.cmd`` step of the build (run by ``build.cmd``) installs an NGEN image.  Previously this was not a debug image, so optimized code was being run.  

I believe this problem is fixed in the latest master branch, since commit 425a1c5. See https://github.com/Microsoft/visualfsharp/blob/master/src/update.cmd#L90 which adds the debug flag when ``build.cmd debug`` is used.

Please check that your ``build.cmd debug`` is running ``ngen`` with the flag.

I'm not sure about the slowdown you're reporting though, that doesn't sound like something under the control of F#

**Comment by dsyme** [comment]
@gimpl I just hit F5 loads of times at the TryD breakpoint (with debug NGEN images loaded) and performance was OK.   I tried with both ``fsc.exe`` and ``fsianycpu.exe``

**Comment by Thorium** [comment]
Also check that your pdb files are in place. I have seen this problems when the code I'm trying to debug has no pdb files for whatever reason.

**Comment by gmpl** [comment]
@dsyme I can confirm now that with the current version the issue is solved. It works out-of-the-box without having to change any settings.
Thanks.

**Comment by dsyme** [comment]
@gmpl Great, thanks for checking
