### ISSUE TITLE
.fsx intellisense problems on location of FSharp.Core files not accompanied by optdata

### ISSUE THREAD

**Issue by eiriktsarpalis** [Microsoft/visualfsharp#1352]
This is a problem I often come across when script debugging projects that have "copy local:true" set on their FSharp.Core dependencies. This will cause a copy of FSharp.Core.dll and FSharp.Core.xml to placed in the build output directory, without however also providing a copy of FSharp.Core.optdata and FSharp.Core.sigdata. This results in some interesting problems, particularly when using the `#I` directive in scripts:
![issue1](https://cloud.githubusercontent.com/assets/2813363/16871669/e84b8cc2-4a90-11e6-996b-ce138f4b20fa.png)
![issue2](https://cloud.githubusercontent.com/assets/2813363/16871672/ed2edd0c-4a90-11e6-92f7-811c14e5d393.png)
In some cases, though I couldn't reproduce while writing this issue, an error message will pop up stating 

> error FS1225: File 'C:\Users\eirik\Development\mbrace\MBrace.Core\bin\FSharp.Core.optdata' not found alongside FSharp.Core"

Incidentally, I also get the same error message when trying to host fsi using FSCS. 

Making the problem go away is simple: just delete FSharp.Core.dll from the bin folder.

So the question here is why are not the sigdata and optdata files copied along with FSharp.Core.dll? Is it an msbuild limitation? Or is there a different reason?

This issue is also tangentially related to paket, because it often reverts my setting of "copy local:false" back to true. @forki what do you think?

**Comment by forki** [comment]
regarding the paket part: did you set the copy local settings in paket.references? http://fsprojects.github.io/Paket/references-files.html#copy_local-settings

**Comment by eiriktsarpalis** [comment]
@forki thanks, that should work :+1:

**Comment by forki** [comment]
ok. so we're back to the problem with sigdata and optdata. 
TBH I think FSharp.Core should always been drawn from the nuget package. 
Copy-local:false might work for you here, but I think the correct way would be to copy sigdata and optdata as well (or to somehow get rid of it ;-) )

So what can we do? 
* Changing MSBuild to learn about FSharp.Core: out-of-scope and probably unrealistic
* Getting rid of sigdata and optdata: if that would be easy then I assume @dsyme would already done it
* Changing Paket to learn about optdata and sigdata: If someone comes up with MSBuild tags that copy sigdata and optdata then we could let Paket emit these

**Comment by cloudRoutine** [comment]
Couldn't they be included as [content files in the Nuspec](http://docs.nuget.org/Create/Nuspec-Reference#contentfiles-with-visual-studio-2015-update-1-and-later) that have `copyToOutput` and `flatten` set to `true` ?
@forki  does paket account for & handle these settings properly?

**Comment by forki** [comment]
yes content files are handled. That might work.

**Comment by eiriktsarpalis** [comment]
@dsyme am I right to assume that sigdata and optdata were separated from the main dll out of size concerns? They account for a third (~1 MB) of the total size.
![issue1](https://cloud.githubusercontent.com/assets/2813363/16873593/f8f0e91c-4a9c-11e6-9c8d-aae0ed216a74.png)
Other F# assemblies have metadata embedded in the dll. Given the aforementioned drawbacks, would it make sense to reconsider this split?

**Comment by cloudRoutine** [comment]
@eiriktsarpalis  I've never had sigdata & opdata issues when using FSharp.Core from nuget with a `standalone` compilation. The size of the dlls and exes produced this way is a common complaint, so that may not be the best solution.

**Comment by forki** [comment]
yeah I guess the resulting exe is fine as well since AFAIK sigdata and optdata are only used during compilation. So here we have the issue that tooling is confused at design time.

**Comment by eiriktsarpalis** [comment]
@cloudRoutine sigdata and optdata are required for applications that somehow host the F# compiler post-build. Hence the failure of fsi and fscs.

**Comment by dsyme** [comment]
@eiriktsarpalis It would be great to list a specific step-by-step repro to see what we can do about it, thanks.  Ideally compile-time fsc/fsi should never resolve to an FSharp.Core that doesn't have these files alongside, and in general should really ignore ``#I`` paths for this particular assembly.

**Comment by eiriktsarpalis** [comment]
@dsyme Reproduction is pretty straightforward:

1. Create a new F# class library project with some types.
2. Make sure that copy local is set to "true" for FSharp.Core, which is the default settings.
3. In an F# script file, write `#I @"bin\Debug"` then "#r" to the particular dll.
4. Fix the intellisense errors by deleting FSharp.Core.dll in build output folder.

**Comment by dsyme** [comment]
@eiriktsarpalis Thanks

**Comment by dsyme** [comment]
Should be addressed fundamentally by #1953
