### ISSUE TITLE
FSI ignores Errors in #loaded scripts

### ISSUE THREAD

**Issue by matthid** [Microsoft/visualfsharp#1393]
After reporting https://github.com/Microsoft/visualfsharp/issues/1392 I figured I'd try to reproduce https://github.com/fsharp/FSharp.Compiler.Service/issues/586 again without using FSharp.Compiler.Service. And lo and behold here is how it works (or should I say fails):
#### Repro steps

`test.fsx`

``` fsharp
#load "other.fsx"

Other.func()
```

and

`other.fsx`

```
let func = (fun () ->
    printfn "This shouldn't work"
) )
```
1. open `fsi`
2. `#load test.fsx`
#### Expected behavior

```
other.fsx(3,3): error FS0010: Unexpected symbol ')' in implementation file
```
#### Actual behavior

```
> #load "test.fsx";;
[Loading C:\PROJ\visualfsharp.issues\loadWithError\other.fsx
 Loading C:\PROJ\visualfsharp.issues\loadWithError\test.fsx]
This shouldn't work

namespace FSI_0003
  val func : unit -> unit


namespace FSI_0003
```
#### Known workarounds

No known workaround
#### Related information
- F# 4.0 (Microsoft (R) F# Interactive version 14.0.23413.0)
- Windows 10
- VS 2015

`fsi.exe test.fsx` works ie errors out as expected. That's why I initially assumed it would be an FSharp.Compiler.Service only bug. see https://github.com/fsharp/FSharp.Compiler.Service/issues/586

**Comment by dsyme** [comment]
Fixed
