### ISSUE TITLE
Consider to use CLAHub

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#14]
I know it's a lawers question, but CLAHub would make things much easier than the current process. 
https://www.clahub.com/

**Comment by KevinRansom** [comment]
I’m sure that it would, and I will forward the suggestion to our legal folks.

Thanks for the heads up

Kevin

**Comment by ctaggart** [comment]
There is also a `Microsoft Contribution License Agreements` bot. See its activity:
https://github.com/msftclas?tab=activity

**Comment by KevinRansom** [comment]
I chatted with our legal guys.  There are good reasons for managing CLA's the way we do now.  They tell me the process will get more straightforward than it currently is over time.

Closing
