### ISSUE TITLE
Bug in byref-return checking: passing local struct address should not be permitted

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#1401]
This is a bug in ref-return safety checking, a missing error for negative test case https://github.com/Microsoft/visualfsharp/pull/1367/files#diff-59ae1d2137d6b7479475f5d1287557d9L13

For most cases of returning byrefs we correctly report an error, e,g

```
let negTest5() = 
    let mutable x = 0
    let addr = &x
    &addr

```

But not for this case: 
#### Repro steps

Compile this code:

``` fsharp

module Test

[<Struct>]
type Struct(initial:int) = 
    let mutable x = initial
    member __.AddrX = &x
    member __.IncrX() = x <- x + 1

let negTest7() = 
    let mutable iterator = Struct(0)
    iterator.AddrX

```
#### Expected behavior

We expect an error to be reported
#### Actual behavior

No error is reported

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/20627428/3a4b4e70-b320-11e6-8f69-85e41fd09bb5.png)

nice one ;-)

**Comment by dsyme** [comment]
Closing in favour of the bucket bug https://github.com/Microsoft/visualfsharp/issues/862
