### ISSUE TITLE
Visual Studio Update 3 removes "F# Script File" template

### ISSUE THREAD

**Issue by tpetricek** [Microsoft/visualfsharp#1404]
After installing VS Update 3, I can no longer create F# Script files in the "New File" dialog:

![boo](https://cloud.githubusercontent.com/assets/485413/17364542/a8cbf112-5978-11e6-8b24-dfeccd7ac6df.PNG)

On the plus side, Update 3 removes that horrible yellow smiley face for sending feedback.
#### Repro steps

I have Windows 8.1 Pro (on Surface Pro 3). All I did is to install Update 3 for Visual Studio. I guess this does not happen for everyone, but I do not [seem to be the only one](https://www.reddit.com/r/fsharp/comments/4h7zu5/add_f_script_file_missing_from_visual_studio_2015/).
#### Attempted workarounds

I tried running  some magic commands from the admin command prompt, but it did not help:

```
devenv /setup
devenv /installvstemplates
devenv /resetuserdata
```

I also tried running VS installer to remove "Visual F#" (so that I can reinstall it), but this does not do anything - it does not remove F# (I can still open F# projects and next time I run the installer, F# is checked as installed).

**Comment by KevinRansom** [comment]
I will see if I can repro this.

**Comment by eriawan** [comment]
@tpetricek , @KevinRansom 
On my machine, opening File -> New and click the Script, I have this:

![image](https://cloud.githubusercontent.com/assets/8773147/17577837/74429790-5fac-11e6-85a8-751c1dcd66e2.png)

My machine is using both VS 2015 Enterprise Update 3 (locally) and VS 2015 Community Update 3 on VM. 
Maybe you need to install this Update 3 fix: https://msdn.microsoft.com/en-us/library/mt752379.aspx

Let me know if this help or not :blush:

**Comment by xperiandri** [comment]
Template is available on my environment too. Not deleted

**Comment by ploeh** [comment]
FWIW I _still have_ the F# script template, but I'm on Windows 10 x64, if that makes a difference. VS version info:

> Microsoft Visual Studio Professional 2015
> Version 14.0.25431.01 Update 3
> Microsoft .NET Framework
> Version 4.6.01586
>
> Installed Version: Professional

**Comment by herrerapedro** [comment]
I have the same issue - uninstalled Visual Studio 2013 and installed 2015.

> Microsoft Visual Studio Enterprise 2015
> Version 14.0.25431.01 Update 3
> Microsoft .NET Framework
> Version 4.6.01055
> 
> Installed Version: Enterprise

**Comment by KevinRansom** [comment]
Please re-open if this still repros for you.  I have not succeeded in reproing this.
