### ISSUE TITLE
Installing latest master build in VS 2015

### ISSUE THREAD

**Issue by slav** [Microsoft/visualfsharp#1406]
I can download the latest artifacts from CI build here: http://dotnet-ci.cloudapp.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part1_windows_nt/lastSuccessfulBuild/artifact/

Is there an easy way to install them in a way for VS 2015 (with F# 4.0 installed), to where it would pickup the new fsc compiler for compiling F# projects?

**Comment by dsyme** [comment]
@slav As I understand it there is not.  The setup changes required for Visual Studio vNext have been integrated.  This means the CI VSIX can't be installed into VS2015.

@otawfik-ms might be able to confirm

**Comment by otawfik-ms** [comment]
@slav master branch is updated to dependencies on Visual Studio 15.
https://www.visualstudio.com/en-us/downloads/visual-studio-next-downloads-vs.aspx

Is there a specific scenario you've in mind?

**Comment by slav** [comment]
@otawfik-ms I just wanted to try new features, especially new struct records, etc. I'm writing code in VS 2015 that can benefit from structs and right now it's old fashioned way of doing it. I was thinking while I'm working on the code to try new, upcoming features.

**Comment by otawfik-ms** [comment]
@slav For that, you just need the new compiler, not VS integration. To do that, you can install VS 15, which will put F# 4.1 under `[Program Files]\Microsoft SDKs\F#\4.1`, and then update your project files to reference the targets there instead of the VS 2015 ones (which will point to F# 4.0).
Let me know if that helps.

**Comment by slav** [comment]
@otawfik-ms - if I would just download artifacts of the last CI build (http://dotnet-ci.cloudapp.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part1_windows_nt/lastSuccessfulBuild/artifact/release/net40/bin/) and point project at the target from it, things should work. Right?

**Comment by slav** [comment]
Also, a follow up question, any way to get VS 2015 to use FSI from new location?

**Comment by otawfik-ms** [comment]
@slav I don't see a reason why not, although it is not a supported scenario AFAIK. It would be interesting to try out :) let me know if you run into problems.

**Comment by slav** [comment]
I've tried to replace 4.0 with 4.1 in "C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0" and in "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\FSharp" for build targets

I also installed assemblies into GAC (not all, those F# that are already there for F# 4.0).

So, build VS would try to use fsi and targets from 4.1.

On build I'm getting error ```2>C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Microsoft.FSharp.Targets(155,9): error MSB6004: The specified task executable location "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\fsc.exe" is invalid."```

On trying to launch FSI in VS (which I need for REPL development) getting the following error:
```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'fsi, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.AppDomain.ExecuteAssemblyByName(AssemblyName assemblyName, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(AssemblyName assemblyName, String[] args)
   at Microsoft.FSharp.Compiler.Interactive.Shell.MainMain(String[] argv) in D:\j\workspace\release_ci_pa---b45f7c2b\src\fsharp\fsi\fsi.fs:line 2520
```

**Comment by otawfik-ms** [comment]
F# 4.1 is not in the GAC anymore. You don't need to place the 4.1 binaries there. What happens if you try to run fsc.exe from command line? This should work.
I believe hacking FSI 4.1 into VS 2015 would be much harder. The new FSI would be built to load vNext components, which it won't find.

**Comment by slav** [comment]
@otawfik-ms - I'm sure running from cmd line will work, but that kinda kills the point.

Are you saying when F# 4.1 is released VS 2015 won't be supported?

**Comment by otawfik-ms** [comment]
Yes. F# 4.1 won't be backward compatible with VS 2015.
But you should be able to use both at the same time:
VS 2015 -> F# 4.0
VS next -> F# 4.1

**Comment by slav** [comment]
But VS 15 might not be released this fall? Or at least it wasn't confirmed AFAIK. And I've read that F# 4.1 is coming out in fall?

**Comment by otawfik-ms** [comment]
F# 4.1 will be released with VS 15. You can try it out starting with the next upcoming VS preview (4).

**Comment by slav** [comment]
Gotcha. Thank you for clarifying.
