### ISSUE TITLE
Allow Wiki page editing

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#1417]
Sometimes the information on the pages is incomplete or could include more information to make it easier for people to use, case in point - [The Using CI Builds Wiki Page](https://github.com/Microsoft/visualfsharp/wiki/Using-CI-Builds)

![](http://i.imgur.com/b7av3M6.png)

which could be improved to -

------------------------------------------

### Installing CI Builds of the Visual F# IDE Tools

To install the Visual F# IDE Tools from Release.zip, first run [`sn.exe` (Strong Name Tool)](https://msdn.microsoft.com/en-us/library/k5b5tt23(v=vs.110).aspx) from 
the [developer command prompt](https://msdn.microsoft.com/en-us/library/ms229859%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) 

```
sn -Vr *,*
```

to turn of strong name checking on your machine, and then run 

```
Release\net40\bin\EnableOpenSource.vsix
```

to run `sn.exe` from the standard command prompt you can locate it at 

```
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\
```
------------------------------------

But if you don't want to open access to allow wiki editing you can copy the md from this issue.

**Comment by KevinRansom** [comment]
Yes ... I agree ...

**Comment by KevinRansom** [comment]
Wiki is now editable.
