### ISSUE TITLE
array.Length pattern in array.fs causes bounds checking / perf problems

### ISSUE THREAD

**Issue by jackmott** [Microsoft/visualfsharp#1419]
It is a common pattern in the array.fs functions to do something like this:

``` F#
let len = array.Length
for i = 0 to len-1 do
   //etc
```

I have tested and found that this causes performance issues, probably related to the JIT not identifying that bounds checking is unnecessary. As well, the compiled IL is odd. The C# view of the for loop in `Array.rev` for instance:

``` C#
int num = len - 1;
        if (num >= i)
        {
            do
            {
                res[len - i - 1] = array[i];
                i++;
            }
            while (i != num + 1);
        }
```

If you refactor the for loop to read `for i = 0 to array.Length-1 do` you get much more sensible compilation, again the C# view from ILSpy:

``` C#
for (int i = 0; i < array.Length; i++)
        {
```

Assuming there is no other good reason for this pattern, it should be possible to mechanically go through and replace this pattern and improve the performance of  many of the core lib functions.

**Comment by forki** [comment]
1) I think mechanically replacement is a easy and good fix - compiler/unit tests/property based tests are in place as safety net. Please send a PR ;-)
2) real fix would be to optimize generated IL ;-)

**Comment by jackmott** [comment]
PR on the way.
For the real fix - a for x downto 0 loop doesn't compile properly either way.
So if/when someone works on that, they should address downto as well.

**Comment by asik** [comment]
The JIT eliminates bounds checking for the equivalent IL of this, specifically:
```
for i in 0 to array.Length - 1 do
    array.[i]
```
Very picky about that, anything slightly different gets bounds checking, including backwards loops. Only way to be sure is to inspect the assembly code (make sure to disable "Suppress JIT optimizations module load"), if you see a branch and call before each array access that's bounds checking.

**Comment by russellhadley** [comment]
Before merging in the change to the lib let us take a peek at the JIT and see if we can get this case.  @JosephTremoulet, you were just looking at bounds checks, can you take a look at this case?

**Comment by KevinRansom** [comment]
@russellhadley .  Will do ... thanks mate.


Kevin

**Comment by jackmott** [comment]
@russellhadley If, while you are in there, you could get backward iterations eliding the bounds check in the JIT that would be great!

**Comment by saul** [comment]
Looks like this PR was merged - can this be closed now? @cartermp

**Comment by jackmott** [comment]
fine by be
