### ISSUE TITLE
Array.averageBy calls Seq.averageBy

### ISSUE THREAD

**Issue by jackmott** [Microsoft/visualfsharp#1432]
Is there a reason for this?

### Current:

```F#
        let inline averageBy f (array:_[]) = 
            checkNonNull "array" array
            Seq.averageBy f array
```

### 8 times Faster
```F#
let inline averageBy2 f (array:_[]) =              
            checkNonNull "array" array
            if array.Length = 0 then invalidArg "array" ""
            let mutable acc = LanguagePrimitives.GenericZero< (^T) >
            for i = 0 to array.Length - 1 do
                acc <- Checked.(+) acc (f array.[i])
            LanguagePrimitives.DivideByInt< (^T) > acc array.Length
```

**Comment by KevinRansom** [comment]
No there is not a good reason for that.  Since the argument is an array, using that fact to gain a performance improvement is clearly a good thing.

**Comment by jackmott** [comment]
It looks like #886 was trying to get this exact change committed but something was wrong, and he hasn't chimed in since Jan. I can submit a new PR for it. Assuming that checks out you could close #886

**Comment by jackmott** [comment]
I think I see the difficulty, getting the surface area test to pass! I'm on it though.

**Comment by jackmott** [comment]
For some reason changing that averageBy to not call Seq, causes line 2142 ofr SurfaceArea.net40.fs to disappear:

`Microsoft.FSharp.Core.FSharpOption`1[T]: Microsoft.FSharp.Core.FSharpOption`1[T] op_Implicit(T)`

Which causes the surface area test to fail.
I don't understand why so am hesitant to just delete that line from SurfaceArea.net40.fs.

**Comment by jackmott** [comment]
closing this, can move any discussion to the #1437
