### ISSUE TITLE
Questions Regarding 'Microsoft.FSharp.Targets' Path Resolution

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#1435]
### The Issue

I'm a bit confused about the manner in which the FSharp MSBuild targets are resolved in the project file templates. 

I'll use the [Library Project Template](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/ProjectTemplates/LibraryProject/Template/Library.fsproj#L60-L72) as an example

``` xml
<Choose>
    <When Condition="'$(VisualStudioVersion)' == '11.0'">
        <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">
            <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
        </PropertyGroup>
    </When>
    <Otherwise>
        <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')">
            <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
        </PropertyGroup>
    </Otherwise>
</Choose>
<Import Project="$(FSharpTargetsPath)" />
```

Let's say I'm building with Visual Studio 2015, that's going to take me to this `.targets` file

``` xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">  
  <Import Project="$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\4.0\Framework\v4.0\Microsoft.FSharp.Targets" />  
</Project>
```

But what if I change my `<TargetFSharpCoreVersion>` property to `4.3.1.0`?  
In that case is there a reason that the F# 4.0 targets should be used instead of the
targets located at 

```
C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.targets
```

Projects created with these templates are inevitably going to end up on machines that don't have Visual Studio installed and a reliance on the `$(VisualStudioVersion)` property seems like an invitation for confusing build errors.  This layer of indirection seems unnecessary if in the end we're always going to end up back at the F# SDK installation.
### An Alternative Approach

I think a better way to resolve the path to `Microsoft.FSharp.Targets` is

``` xml
<Choose>
    <When Condition="$(TargetFSharpCoreVersion) &gt;= 4.3.0.0 AND $(TargetFSharpCoreVersion) &lt; 4.3.1.0 ">
        <PropertyGroup>
            <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
        </PropertyGroup>
    </When>
    <When Condition="$(TargetFSharpCoreVersion) &gt;= 4.3.1.0 AND $(TargetFSharpCoreVersion) &lt; 4.4.0.0 ">
        <PropertyGroup>
            <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
        </PropertyGroup>
    </When>
    <When Condition="$(TargetFSharpCoreVersion) &gt;= 4.4.0.0 AND $(TargetFSharpCoreVersion) &lt; 4.4.1.0 ">
        <PropertyGroup>
            <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\4.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
        </PropertyGroup>
    </When>
    <Otherwise>
        <PropertyGroup>
            <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\4.1\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
        </PropertyGroup>
    </Otherwise>
</Choose>
<Import Project="$(FSharpTargetsPath)" Condition="Exists('$(FSharpTargetsPath)')" />
```
### In Practice

I decided to test this out in VS 2015 with an edited `fsproj` from the `ConsoleApplication` template to see if it would work the way I expected.

With project settings of  

![](http://i.imgur.com/Nz40ynF.png)

The MSBuild output shows it was evaluated correctly to 

```
1>Target "CoreCompile" in file "C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.Targets" from project "C:\Users\jared\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.fsproj" (target "Compile" depends on it):
1>  Building target "CoreCompile" completely.
```

With project settings of   

![](http://i.imgur.com/Rl8bXzr.png)

The MSBuild output shows it was evaluated correctly to

```
1>Target "CoreCompile" in file "C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Microsoft.FSharp.Targets" from project "C:\Users\jared\Documents\Visual Studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.fsproj" (target "Compile" depends on it):
1>  Building target "CoreCompile" completely.
```

If you guys are amenable to this change I'll gladly update all of the templates to use it instead of the current approach.
### Other Notes -
- If the default `<TargetFSharpCoreVersion>` in the template is `4.4.0.0` should the `<MinimumVisualStudioVersion>` really be `11`?  I thought only VS2015 and newer could use F# 4.0  
- If these templates are meant to be released with VS 15 & F# 4.1 shouldn't the default `<TargetFSharpCoreVersion>` be `4.4.1.0`?

**Comment by KevinRansom** [comment]
I doubt if any of this is going to last much longer.  Moving forward the compiler tools are likely to be nuget or paket deployed rather than installed with VS .

What we have now works fine for the current VS round tripping scenarios.  We will eventually get around to new simpler templates with a reduced need for pre-installed files.

So I would say that since it isn't currently broken, and is likely to be redesigned over the next year or so.  I would prefer to do nothing right now.

As an FYI ... I do need to figure out what templates should look like for building with the coreclr version of the F# compiler.  Which is where we will likely scout out decent approaches.  I assume you have bee looking at this for Ionide?  For sure I would imagine you would prefer not to have preinstall requirements for projects within Ionide.

If you would like to get involved with an effort to improve our templates and targets.  Please let me know.

Kevin

**Comment by Krzysztof-Cieslak** [comment]
> Moving forward the compiler tools are likely to be nuget or paket deployed rather than installed with VS .

Does it mean that F# `targets` file will be also distributed with NuGet? 

> I assume you have bee looking at this for Ionide? For sure I would imagine you would prefer not to have preinstall requirements for projects within Ionide.

Not having any "global" requirements would be definitely perfect from our point of view, right now (since we are using FCS' ProjectCracker) Ionide requires several things installed globally (MsBuild [either installed by VS or by standalone distribution], and F# [again, VS or standalone])

**Comment by cloudRoutine** [comment]
I definitely would like to get involved :smile: 

The issues with the templates and the resolving the targets path has been a constant source of frustration for the devs and users of Ionide and Fable (the Fable compiler is used to build Ionide).  This is primarily due to issues with the implementation of the `FSharp.Compiler.Service.ProjectCracker` which fails to evaluate valid `fsproj` properly. 

That's what the real issue is, the current project files that most people end up using end up being impossible for the `FSharp.Compiler.Service` to use effectively unless one or more versions of the MSBuild tools and one or more versions of Visual Studio are installed depending on what's broken about the ProjectCracker on that particular day.  Since I rely on the `FSharp.Compiler.Service` for projects beyond Ionide and Fable, and the next version of VisualFSharpPowertools (FSharp.Editing) is being designed to work solely dependent on FCS getting to a point where FCS will work reliably as long as the F# SDK is installed would be ideal.

This seems broken to me :arrow_down: 

> But what if I change my <TargetFSharpCoreVersion> property to 4.3.1.0?
> 
> In that case is there a reason that the F# 4.0 targets should be used instead of the
> targets located at
> 
> C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.targets
