### ISSUE TITLE
Improve Error Reporting : Return Offending Arguments with Error Messages (Parameterized Errors)

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#1438]
A pervasive issue throughout FSharp.Core is that when a function receives an argument that's invalid or violates a constraint the error message says what went wrong, but not **_how_** it went wrong.

For an example, let's look at `Array.map3` 

``` fsharp
> Array.map3 mapfn arr1 arr2 arr3;;
System.ArgumentException: The arrays have different lengths.
   at Microsoft.FSharp.Collections.ArrayModule.Map3[T1,T2,T3,TResult](FSharpFunc`2 mapping, T1[] array1, T2[] array2, T3[] array3)
   at <StartupCode$FSI_0005>.$FSI_0005.main@()
```

Is the length of only one of the arrays different from the other two? If so which array is it? Are the lengths of all the arrays different? What is the degree of difference  between these lengths? 

This is all important information to quickly diagnose the source of the error, and we **_have_** this information, so let's stop hiding it.

A better error message would be -

``` fsharp
> Array.map3 mapfn arr1 arr2 arr3;;
System.ArgumentException: The arrays have different lengths.
array1.Length = 45, array2.Length = 1, array3.Length = 44
   at Microsoft.FSharp.Collections.ArrayModule.Map3[T1,T2,T3,TResult](FSharpFunc`2 mapping, T1[] array1, T2[] array2, T3[] array3)
   at <StartupCode$FSI_0005>.$FSI_0005.main@()
```

By exposing the values that caused the failure it becomes easy to see when an off by one error has occurred, when a sequence hasn't been truncated properly, when an earlier function call did not produce the result you expected it to, and a wide variety of other unexpected execution results. It might not seem as valuable with the trivial example of a single function call in the REPL, but when you have a long pipeline of functions the more informative error feedback makes it easier to hone in on the bug.

Unfortunately we can't implement a better `invalidArg` like 

``` fsharp
let inline invalidArgf (arg:string) fmt =
    let error msg = raise (new System.ArgumentException(msg,arg))    
    Printf.ksprintf error fmt
```

``` fsharp
invalidArgf "array2" "%s\narray1.Length = %i, array2.Length = %i " "arraysHadDifferentLengths" array1.Length array2.Length
```

 Since `Printf` hasn't been defined in `FSharp.Core` at the earliest points we'd want to start using it (all of the collections modules)

`String.Format` could provide an alternative 

``` fsharp
let inline invalidArgFmt (arg:string) fmt argArray =    
    let msg = String.Format(fmt,argArray)
    raise (new System.ArgumentException(msg,arg))
```

``` fsharp
invalidArgFmt "array2" "{0}\narray1.Length = {1}, array2.Length = {2} " [|"arraysHadDifferentLengths";array1.Length; array2.Length|]
```

Or if someone else has a better (and more type safe) approach please suggest it.
### Local.fs
- [x] `List.init` - [return invalid count](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L469)
- [x] `List.takeFreshConsTail` - [return the amount of elements it fell short](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L479)
- [x] `List.take` - [return invalid count](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L486)
- [x] `List.take` - [change to invalid arg, list can't be empty](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L489)
- [x] `List.splitAtFreshConsTail` - [return the amount of elements it fell short](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L501)
- [x] `List.splitAt` - [return invalid index](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L508) 
- [x] `List.splitAt` - [return the amount of elements it fell short](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L512) 
- [x] `List.window` - [return invalid windowsize](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L675)
- [x] `List.chunkBySize` - [return invalid chunksize](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L701)
- [x] `List.splitInto` - [return invalid count](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L727)
- [x] `List.zipToFreshConsTail` - [return which list is shorter](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L748)
- [x] `List.zip` - [return which list is shorter](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L760)
- [x] `List.zip3ToFreshConsTail` - [return which list is shorter](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L773)
- [x] `List.zip3` - [return which list is shorter](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L786)
- [x] `Array.Sort` - [return difference in number of keys vs values](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L861)
- [x] `Array.Sort` - [return difference in number of keys vs values #2](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L871)
- [x] `Array.Init` - [return invalid count](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/local.fs#L893)

@KevinRansom 
@forki 
@isaacabraham

**Comment by liboz** [comment]
At least for map2/map3/mapi2, one slight problem with your example is that the length of a List or Seq could be a very costly operation, which could make printing out the Length in the error message slow down the system. So maybe an error message like this would better:

```
List.map3 mapfn list1 list2 list3;;
System.ArgumentException: The lists had different lengths.
list2 has fewer elements than list1 and list3.
   at Microsoft.FSharp.Collections.ListModule.map3aux[a,b,c,d](FSharpFunc`4 f, FSharpList`1 list1, FSharpList`1 list2, FSharpList`1 list3, FSharpList`1 acc)
   at Microsoft.FSharp.Collections.ListModule.Map3[T1,T2,T3,TResult](FSharpFunc`2 mapping, FSharpList`1 list1, FSharpList`1 list2, FSharpList`1 list3)
   at <StartupCode$FSI_0022>.$FSI_0022.main@()
```

**Comment by cloudRoutine** [comment]
I wouldn't say that was a problem with my example per say, but your point is well taken. I specifically picked that array example because it fits within the kinds of cases I want to address, ones where the additional error information is already present. I don't think we should do a bunch of extra work of a potentially expensive and indeterminate amount for the sake of an error message.  If you're suggesting that we should give less information in all contexts due to the ones where it'd be expensive to give a higher level of specificity, I don't think we should do that. But if you mean that error messages should be tailored to the context I wholeheartedly agree.

```fsharp
[<CompiledName("FoldBack2")>]
let rec foldBack2<'T1,'T2,'State> f (list1:'T1 list) (list2:'T2 list) (acc:'State) = 
    match list1,list2 with 
    | [],[] -> acc
    | h1::rest1, k1::rest2 -> 
        let f = OptimizedClosures.FSharpFunc<_,_,_,_>.Adapt(f)
        match rest1, rest2 with 
        | [],[] -> f.Invoke(h1,k1,acc)
        | [h2],[k2] -> f.Invoke(h1,k1,f.Invoke(h2,k2,acc))
        | [h2;h3],[k2;k3] -> f.Invoke(h1,k1,f.Invoke(h2,k2,f.Invoke(h3,k3,acc)))
        | [h2;h3;h4],[k2;k3;k4] -> f.Invoke(h1,k1,f.Invoke(h2,k2,f.Invoke(h3,k3,f.Invoke(h4,k4,acc))))
        | _ -> foldBack2UsingArrays f list1 list2 acc
    | _ -> invalidArg "list2" (SR.GetString(SR.listsHadDifferentLengths))
```
^ We don't need to evaluate the difference in the lengths between the two lists but we could at least say which one was longer.

```fsharp
let foldBack2UsingArrays (f:OptimizedClosures.FSharpFunc<_,_,_,_>) list1 list2 acc = 
    let arr1 = toArray list1
    let arr2 = toArray list2
    let n1 = arr1.Length
    let n2 = arr2.Length
    if n1 <> n2 then invalidArg "list2" (SR.GetString(SR.listsHadDifferentLengths));
    let mutable res = acc
    for i = n1 - 1 downto 0 do
        res <- f.Invoke(arr1.[i],arr2.[i],res)
    res
```
^ we have the lengths so lets return them

```fsharp
[<CompiledName("Skip")>]
let skip count list =
    if count <= 0 then list else
    let rec loop i lst =
        match lst with
        | _ when i = 0 -> lst
        | _::t -> loop (i-1) t
        | [] -> invalidArg "count" (SR.GetString(SR.outOfRange))
    loop count list       
```
^ we can return how much the `count` exceeds the length of the list

```fsharp
[<CompiledName("ExactlyOne")>]
let exactlyOne (source : list<_>) =
    match source with
    | [x] -> x
    | []  -> invalidArg "source" LanguagePrimitives.ErrorStrings.InputSequenceEmptyString            
    | _   -> invalidArg "source" (SR.GetString(SR.inputSequenceTooLong))
```
^ this is fine, how much longer it is than 1 is too expensive and not as useful as the extra error information that could be provided in the other examples.

@liboz  I hope this clarifies my intentions and position on how to approach this.

**Comment by KevinRansom** [comment]
As a principle it’s okay to do extra work on the error path, not on the main path.  So if the extra work improves the error message and it’s only done after the error has been discovered than it’s justified to do it.

Kevin

**Comment by forki** [comment]
can this be closed?

**Comment by dsyme** [comment]
@forki Yes, thanks
