### ISSUE TITLE
Private Type with Non-private static member op_Multiply not multipliable

### ISSUE THREAD

**Issue by JanWosnitza** [Microsoft/visualfsharp#1443]
I would expect the following code to compile:

    type private MyType =
        | Something
        with

        static member op_Multiply( a:MyType, b:MyType ) = Something

    let func () =
        let x = MyType.op_Multiply( Something, Something )
        let y = Something * Something
        0

but the compiler says on line `let y = Something * Something`:
> The member or object constructor 'op_Multiply' is not public. Private members may only be accessed from within the declaring type. Protected members may only be accessed from an extending type and cannot be accessed from inner lambda expressions.

I do understand, that this is due to the global implementation of `(*)`. But actually I would expect this to work flawlessly since all the code is inlined and `MyType.op_Multiply` is callable within the given scope.

I don't know if this is a bug or a feature ;)

* Windows 10
* .NET Framework 4.6
* F# 4.0 (FSharp.Core, 4.4.0.0)
* Visual Studio Community 2015

**Comment by JanWosnitza** [comment]
At least the error-message isn't helpful.

**Comment by dsyme** [comment]
See this too: https://fslang.uservoice.com/forums/245727-f-language/suggestions/5695277-allow-the-addition-of-operators-in-type-extensions

**Comment by dsyme** [comment]
I'll close this as it is covered by the User Voice request
