### ISSUE TITLE
Improve Error Reporting: Field suggestions not shown consistently

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#1445]
Related to #1102.

Given the following code snippet: 
```fsharp
type Person = { Name : string; }

let x = { Person.Names = "Isaac" }
let y : Person = { Names = "Isaac" }
let z = { Names = "Isaac" }
```

The first error message reads: -

```error FS0039: The field, constructor or member 'Names' is not defined```

yet the remaining two give suggestions for replacement fields. I would expect the first two to give identical error messages.

**Comment by isaacabraham** [comment]
CC: @forki

**Comment by forki** [comment]
I think I get this working:

![image](https://cloud.githubusercontent.com/assets/57396/17699206/c1e2934e-63bf-11e6-8f16-1ef408def6d6.png)

**Comment by forki** [comment]
see https://github.com/Microsoft/visualfsharp/pull/1448

**Comment by cloudRoutine** [comment]
could the message be - `The field, constructor or member 'Names' is not defined for type 'Person'`?

**Comment by forki** [comment]
sure that would only require like a million fixes in tests ;-)

that said: go for it - send a WIP PR and fix everything

**Comment by isaacabraham** [comment]
@forki @KevinRansom was this merged in and released? I've just tested in Ionide and it's still happening.

**Comment by forki** [comment]
In ionide? I think that's not the test vehicle.

**Comment by isaacabraham** [comment]
OK - but that shows all other compiler errors relating to this.
