### ISSUE TITLE
Improve Error Reporting: Type suggestions not shown consistently

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#1446]
Related to #1102

The following code snippet shows that different error messages are shown depending on how to express the value. The first one shows a simple error message; the second one shows suggestions on valid types.

```fsharp
let data = System.Collections.Generic.Lst()
let dataTwo : System.Collections.Generic.Lst = ResizeArray()
```

CC: @forki

**Comment by forki** [comment]
see https://github.com/Microsoft/visualfsharp/pull/1449
