### ISSUE TITLE
Can't debug fsi anymore

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1447]
I tried to debug fsi like I always did (describe at http://www.navision-blog.de/blog/2016/04/25/make-failure-great-again-a-small-journey-into-the-f-compiler/) and now see:

![image](https://cloud.githubusercontent.com/assets/57396/17698715/e825058a-63bc-11e6-8ac2-77d76146a43c.png)

Did something change recently?

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/17734166/d12f41a6-647a-11e6-96ee-33630c5ae2de.png)

this is what I see for debug symbol load info. 

    PDB does not match image.

**Comment by AviAvni** [comment]
@forki I'm getting this to after I build the compiler

**Comment by forki** [comment]
Ok then I'm relieved and something is really messed up.

Am 17.08.2016 3:15 nachm. schrieb "Avi Avni" <notifications@github.com>:

**Comment by forki** [comment]
@kevinransom is this related to latest changes to portable pdbs?

**Comment by KevinRansom** [comment]
I changed the debugtype to portable pdbs for the OSS build when I checked in some cleanup.  I will change it back.   Or you can set the debugger type to coreclr in the VS doing the debugging.

For now set the DebugType to full here: https://github.com/Microsoft/visualfsharp/blob/master/src/FSharpSource.Settings.targets#L28

**Comment by KevinRansom** [comment]
@forki , hey mate does this work for you now?

**Comment by AviAvni** [comment]
Thank @KevinRansom it help now I can debug the compiler

**Comment by forki** [comment]
thanks. it's working again.
