### ISSUE TITLE
Improve Error Reporting: Incorrect error message on 'if' expression

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#1450]
Related to #1102. The following code snippet leads to a misleading error message:

```fsharp
type Person = { Name : string; }

let x =
    if 5 > 10 then { Name = "Isaac" }
```
The error is: ```error FS1129: The type 'unit' does not contain a field 'Name'```

**Comment by isaacabraham** [comment]
cc:@forki

**Comment by forki** [comment]
What do you mean with "misleading"? I think the compiler is right.

**Comment by forki** [comment]
That said which error message would you expect here?

**Comment by isaacabraham** [comment]
I wouldn't expect the following to lead to a different error message: -

```fsharp
let x =
    if 5 > 10 then { Person.Name = "Isaac" }
```

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/17702269/8c7f27cc-63cd-11e6-8f32-57456b647ceb.png)

what do you mean?

**Comment by isaacabraham** [comment]
OK - I was going off Ionide, which shows the following: -

![untitled](https://cloud.githubusercontent.com/assets/1781813/17702381/f3763d12-63cd-11e6-9156-45bffe8391fe.png)

**Comment by forki** [comment]
/cc @Krzysztof-Cieslak

I assume it's not the final version in FCS/Ionide?

**Comment by isaacabraham** [comment]
I suggest we close this issue - using the "real" compiler should be sufficient to confirm that this is a non-issue, but it'd be good to know why this is occurring.

**Comment by forki** [comment]
ok maybe it's giving multiple errors, let me check that

**Comment by forki** [comment]
also we should find a repro for "The typ 'unit' does not contain a field" that should never be thrown

**Comment by forki** [comment]
nope. only one error thrown. I vote to close this.

**Comment by forki** [comment]
It's still weird. Why is the other one already working?

**Comment by isaacabraham** [comment]
I can confirm that this is gone in Ionide.
