### ISSUE TITLE
Latest Master does not build

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#1455]
Running `build.cmd` in Administrator mode gives the following error on the latest master (81bdd76): -

``` cmd
Build FAILED.

       "C:\Users\Isaac\Source\Repos\visualfsharp\build-everything.proj" (default target) (1) ->
       "C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\fsharp-vsintegration-vsix-build.proj" (Build ta
       rget) (10) ->
       "C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\Vsix\VisualFSharpFull\VisualFSharpFull.csproj"
       (Build target) (15) ->
       "C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.f
       sproj" (default target) (27) ->
       (ResolveAssemblyReferences target) ->
         C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3
       245: Could not resolve this reference. Could not locate the assembly "Microsoft.VisualStudio.Shell.Fram
       ework". Check to make sure the assembly exists on disk. If this reference is required by your code, you
        may get compilation errors. [C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\src\FSharp.Project
       System.FSharp\ProjectSystem.fsproj]


       "C:\Users\Isaac\Source\Repos\visualfsharp\build-everything.proj" (default target) (1) ->
       "C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\fsharp-vsintegration-vsix-build.proj" (Build ta
       rget) (10) ->
       "C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\Vsix\VisualFSharpFull\VisualFSharpFull.csproj"
       (Build target) (15) ->
       "C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.f
       sproj" (default target) (27) ->
       (MergeCtoResource target) ->
         C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\VSSDK\Microsoft.VsSDK.targets(874,5): war
       ning VSSDK1011: obj\release\net40\MenusAndCommands.cto has no valid Resource. [C:\Users\Isaac\Source\Re
       pos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj]
         C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\VSSDK\Microsoft.VsSDK.targets(874,5): war
       ning VSSDK1011: obj\release\net40\fsiCommands.cto has no valid Resource. [C:\Users\Isaac\Source\Repos\v
       isualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj]


       "C:\Users\Isaac\Source\Repos\visualfsharp\build-everything.proj" (default target) (1) ->
       "C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\fsharp-vsintegration-vsix-build.proj" (Build ta
       rget) (10) ->
       "C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\Vsix\VisualFSharpFull\VisualFSharpFull.csproj"
       (Build target) (15) ->
       "C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.f
       sproj" (default target) (27) ->
       (CoreCompile target) ->
         FSC : error FS0193: Could not find file 'C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\src\F
       Sharp.ProjectSystem.FSharp\obj\release\net40\ProjectResources.rc.res'. [C:\Users\Isaac\Source\Repos\vis
       ualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj]

    3 Warning(s)
    1 Error(s)

Time Elapsed 00:02:13.00
```

**Comment by KevinRansom** [comment]
@isaacabraham,  you wake up and this is the first thing you do in the morning?  That is plum crazy mate :-)

I'm guessing you are building with VS2014 rather than VS2015?

**Comment by KevinRansom** [comment]
@isaacabraham 

For now delete this line in your local repro.  
https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.ProjectSystem.FSharp/ProjectSystem.fsproj#L99

I will try to get a slightly better fix.  but it is the middle of the night here, and I am off work for the next couple of days.  Although I am of course still working and will submit a PR shortl.  I also messed up debugging with this PR.

I also owe @forki a fix for his debugging change.  

The reason for the change is that VS crefactored some of their implementation assemblies for Dev 15 Preview 4, I didn't really take into account developers building the UI with old versions of VS ... which was kind of careless of me.  orry about that.

**Comment by isaacabraham** [comment]
@KevinRansom it's the only real chance I have to try out non-work stuff :-) I'm using VS2015 btw.

Thanks for the tip though, I'll give that a go.

You do of course realise that by helping me out here this might mean more PRs for you to review ;-)

**Comment by KevinRansom** [comment]
That sounds like a small price to pay.  And certainly one I am eager to pay.

**Comment by KevinRansom** [comment]
@isaacabraham if you get a chance could you sync and rebuild master.  I would like to confirm the problem is cured.

Thanks.

Kevin

**Comment by isaacabraham** [comment]
Afraid not. Did a pull, clean and rebuild: -

```cmd
 "C:\Users\Isaac\Source\Repos\visualfsharp\build-everything.proj" (default target) (1) ->
       "C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\fsharp-vsintegration-vsix-build.proj" (Build ta
       rget) (12) ->
       "C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\Vsix\VisualFSharpFull\VisualFSharpFull.csproj"
       (Build target) (14) ->
       "C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.f
       sproj" (default target) (24) ->
       (CoreCompile target) ->
         FSC : error FS0193: Could not find file 'C:\Users\Isaac\Source\Repos\visualfsharp\vsintegration\src\F
       Sharp.ProjectSystem.FSharp\obj\release\net40\ProjectResources.rc.res'. [C:\Users\Isaac\Source\Repos\vis
       ualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj]
```

**Comment by KevinRansom** [comment]
I think that's due to an inability to build the res file.
Do you have C++ installed, it's c++ that installs the rc compiler.

Also you need the windows sdk installed:  https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk

**Comment by isaacabraham** [comment]
No, I don't have C++ installed. Why would I :-) And why do we need the Windows 10 SDK to built the F# compiler?

**Comment by forki** [comment]
We should add such tools to the repo.

**Comment by KevinRansom** [comment]
No ... they should be on nuget.  Also we should probably not use windows specific tools, but that's a different can of worms.

Kevin

**Comment by forki** [comment]
On nuget would be better. But we can only change one Microsoft product at a
time.

Am 22.08.2016 6:53 nachm. schrieb "Kevin Ransom (msft)" <
notifications@github.com>:

**Comment by KevinRansom** [comment]
Well we are trying …

**Comment by isaacabraham** [comment]
OK what's the upshot here - I need to install C++ and Windows 10 SDK or there's plans afoot to remove this? If the former - is this C++ for VS or just some redist?

**Comment by KevinRansom** [comment]
rc --- the resource compiler is an old native tool that ships with c++.  And we need that for the build.  It should really be in a nuget package or part of the standard SDK download I suppose.
