### ISSUE TITLE
Generic 2D Array not working in C#

### ISSUE THREAD

**Issue by janni2** [Microsoft/visualfsharp#1458]
Hi,

Im trying to build a F# library with mathematical capabilities for a C# program without using MathNet-Libraries. Implementing a custom number system worked more or less beside some unnecessary F#-restrictions. First idea was, to build a module and say things like:
let Sin x = sin x where under C# you get "sin<'T>(x)" and under F# the constraint "needs a _static_ member Sin x". Anything logic so far. But when playing a bit more, I found out, that "let tanh x = sinh x / cosh x doesnt work correctly anymore, because C# now enforces 3 type parameters, which can be solved by constraints in F#. But then suddenly the "/" operator doesnt work anymore. So "(/) 'T*'T -> 'T" cannot be resolved. 

I thought, well my fault but when I tried to use the F# Library "FsAlg" for matrix calcution under C#, this just leads to crashes _on C# side_ and works really fine at the F# side. I spent two weeks to find a workaround and now I'm using interfaces up and down-casts under F# to bind my operators at compile time like "x.Abs().Inverse().Sin()" ... which is pretty ugly because F# enforces explicite casts, so the code looks like "(a :> interface).doSomething(b :> interface) :?> actualclass

I think the observation is correct, because on Vector operations it worked well - also for C#. Indeed the named library has warnings, that F# expects a constraint like 'T \* ? -> 'T, but the Library tries to enforce to stay at one type. So the code is not "super" generic, but that's fine, because we want it that way.
#### Repro steps
1. clone https://github.com/gbaydin/FsAlg
2. create C# command line programm with reference to the library and with a code similar to this
   `using System;
   using System.Collections.Generic;
   using System.Linq;
   using System.Text;
   using System.Threading.Tasks;
   using FsAlg.Generic;

namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {
            var raw = new float[2, 2];
            for (var i = 0; i < 2; i++) for (var j = 0; j < 2; j++) { raw[i, j] = (float) (i \* i) + 1f / ((float)j + 1f); }
            var matrix = Matrix.ofArray2D(raw);
            Console.WriteLine(matrix.GetLUDecomposition());  
        }
    }
}`
1. run it -> "NotSupportedException was unhandled" at "toggle <- -toggle" where toggle contains the value "1.0" with type float as you can see in the debugger / watch variable. When uncommenting toggle, it crashes at the next "basic operation". In opposite to that crashing behaviour the folder "docs" of the library contains a lot of F# samples, that "just work" even in F# Interactive console, as they are.
#### Expected behavior

When a type (DU) has a constraint like >> 'T : (static member (~-) : 'T -> 'T) <<, I would expect that I can use this operator in a member function like >> member inline m.GetLUDecomposition() <<
Because once instanciated, the type T of a class should be immutable for that object.

Probably the point is, that "operators" do not work under "certain circumstances" in C#
#### Actual behavior

"NotSupportedException" ... it's even unclear, WHAT actually is "not supported" and why
#### Known workarounds

a) when generic matrices are necessary -> writing an interface INumeric, where Matrix<INumeric> implements things like "element.Negate()" similar what the old F# Powertools did, this works completely without any Exception, but is really ugly to implement. At least it could be encapsulated in sofar, that at C# side you can write "A*B" again, and implement implicite conversions FROM double[,] to INumeric[,]

b) using MathNet.Numerics obviously. They implemented matrices for each single type like double, float, complex, which is not a "generic" solution, for example, when I want to introduce a 4th type like "symbolics" (Parameters or Constants for example), I would be enforced to repeat the same code probably with 5% change.
#### Related information
- Operating system: Windows 10
- Branch current release (F# 4.0, FSharp.Core 4.4.4.0, .NET Framework 4.5) also older releases
- Editing Tools : Visual Studio 2015 Community

**Comment by dsyme** [comment]
This behavior is expected: you are using an F# ``inline`` function from C# https://github.com/gbaydin/FsAlg/blob/master/src/FsAlg/Matrix.fs#L167

C# doesn't support inlining of functions with static constraints like this, so at runtime gives NotSupportedException

**Comment by dsyme** [comment]
Perhaps add a User Voice request to mark such functions as Obsolete (or something like that) to the C# user

**Comment by janni2** [comment]
Could you give an example of how to get
let tanh x = sinh x / cosh x 
working in C# with or without any constraints or "inline" keywords, so that you can apply the function to "real" AND "complex" values? Because that was initially the idea, to replace the underlying types if necessary.
