### ISSUE TITLE
Azure Web Deploy Publish Broken on First Attempt

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#146]
Originally opened on [codeplex](https://visualfsharp.codeplex.com/workitem/156) by [riles01](https://www.codeplex.com/site/users/view/riles01)

I just cleared out my old pubxml files and re-authenticated in order to re-publish an F# web application. When I first tried to publish, I received the old error, "Object reference not set to an instance of an object." that always appeared prior to the 3.1.2 Visual F# Tools release. A subsequent attempt to publish worked fine. I was able to reproduce this by deleting the .pubxml, signing out, signing in, and attempting to publish again.

**Comment by dsyme** [comment]
I believe I've seen this too.  It made me think the feature didn't work.

**Comment by cartermp** [comment]
I suspect this old bug is not relevant anymore:

* Publish for .NET Core SDK-based projects works
* There is no official F# web app template that is _not_ .NET Core SDK-based
* These old-style projects are likely incredibly small in number, especially since .NET Core supports F#

I vote to close.
