### ISSUE TITLE
Highlight matching delimiters (braces, quotes) when pointed at with cursor

### ISSUE THREAD

**Issue by slav** [Microsoft/visualfsharp#1481]
### Description

Highlight matching delimiters when cursor is pointing at the delimiter. Braces are not as important in F# as in other languages, but still are used frequently (lambda functions, computation expressions, etc). VS 2015 has native braces highlight in C#, C++ and VB.

### Repro steps

Open a brace '(' and close a brace ')'.

### Expected behavior

When you move cursor to either brace, it and the matching brace should highlight.

### Actual behavior

When you point cursor at either brace there's no highlight.

### Related information 

* Visual Studio 15
* F# 4.0
* Latest Visual F# Power Tools
* Viasfora (for rainbow brackets)

**Comment by forki** [comment]
this works already in VS2013 with VFPT enabled!? /cc @vasily-kirichenko @dungpa

**Comment by vasily-kirichenko** [comment]
Yes, it's worked since VS2013.

**Comment by slav** [comment]
Doesn't seem to work in my copy of VS2015. I've tried to reinstall F# and do VS repair. Tried to disable all plugins. Everything else related to F# seems to works fine.

Tested and parenthesis get highlighted in supported files (C++, C#, etc)

Any suggestions on what else I could try to do?

**Comment by slav** [comment]
Just to update, on typing closing brace, matching brace is highlighting. But, if afterwards I move cursor to the brace, matching brace doesn't get highlighted.

**Comment by slav** [comment]
And, it seems to be related to VsVim plugin. When disabled braces are matching. Strange.
