### ISSUE TITLE
Is there a vm available to start immediately hacking on the compiler, if not can there be one?

### ISSUE THREAD

**Issue by 7sharp9** [Microsoft/visualfsharp#1482]
Its fairly difficult to contribute to compiler development unless you have a working Windows system set up in exactly the right way.  The only alternative is working with merges across from `Microsoft/visualfsharp` to the `fsharp/fsharp` repo and waiting for the planets to align in exactly the right way with a silver spoon in your right hand and a large cup of coffee.  

The best way to make it easier for anyone to contribute is to have a nicely baked VM all ready to go.
#### Repro steps

Provide the steps required to reproduce the problem
1. Try and contribute to the compiler when you are not a Windows user.
#### Expected behavior

Easy to develop new features for the compiler even if you don't use Windows.
#### Actual behavior

Not easy to develop new features for the compiler unless you use Windows.  Even then some people report problems.
#### Known workarounds

Sulk, troll on twitter.

**Comment by forki** [comment]
It would need Win10, VS2015, git 
what else?

**Comment by neoeinstein** [comment]
What about preparing something like a `Vagrantfile` that would allow easy provisioning of such a system?

**Comment by AviAvni** [comment]
Perl

**Comment by 7sharp9** [comment]
A list of stuff to install, a script or a pre made vm, in reverse order of desire.

**Comment by slang25** [comment]
How about using packer, and outputting a vagrant box:
https://www.packer.io/intro/getting-started/vagrant.html
Very much like this:
https://github.com/jen20/packer-windows-netdev
but with newer VS and all the relevant things we get in the AppVeyor image, i.e. the readme dependency list.
I know getting the compiler to build for the first time was a struggle for me, and for @isaacabraham, so there's a lot of value in this.
I'd love help out with this, but seriously doubting I'm gonna have time in the next few weeks.

**Comment by OkayX6** [comment]
Would giving you access to a VM on Windows Azure be enough?

**Comment by neoeinstein** [comment]
I'd strongly prefer a reliable provisioning script that could be checked in and versioned rather than a black box that no one else knows how it got built.

**Comment by forki** [comment]
sure. a script that generates a VM that I can simply download and start

**Comment by 7sharp9** [comment]
@OkayX6 Azure VM would be preferable for me.

**Comment by OkayX6** [comment]
@7sharp9 should we close this issue? :)
