### ISSUE TITLE
VS 15 Can't Load Xml.Linq Reference

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#1483]
VS 15 is on the left, VS 2015 on the right
![](http://i.imgur.com/PrQzPkm.png)

This is the exact same solution file

Zip of the repo 
[xmllinqfail.zip](https://github.com/Microsoft/visualfsharp/files/435173/xmllinqfail.zip)

**Comment by dsyme** [comment]
@OmarTawfik @brettfo @KevinRansom Any idea if this is still an issue, and/or does it deserve the "Urgency Now" label?  I presume not?

**Comment by vasily-kirichenko** [comment]
Current master:

![image](https://cloud.githubusercontent.com/assets/873919/20859693/b39d9b6e-b976-11e6-86bf-8606df675868.png)

So I think this issue can be closed.
