### ISSUE TITLE
Internal serialization of Async<_>

### ISSUE THREAD

**Issue by Thorium** [Microsoft/visualfsharp#1486]
I have used async a lot as currently F# is still mainly backend server language and those servers benefit of async. But there is an usability issue.

If you serialize current Async<_> item, e.g. save it to memory IDictionary<_,_> it won't warn you but it will fail at runtime producing unexpected result.

However current .NET "standard way" of Task<_> (the corresponding C# implementation) works.
http://fssnip.net/sA

Besides that, most of Microsoft .NET tools like WCF, SignalR, unit tests, etc. work with Taks<_>. Now, these kind of APIs like SignalR or WCF don't actually serialize the Task-object, they just await it and serialize the result. So you can use F# Async<_> with them like this:

``` fsharp
member __.MyThing () =
    async {
        let! itm = doThings()
        //...
    } |> Async.StartAsTask
```

But this is very error prone:
- If you forget `|> Async.StartAsTask` this will compile and server will return Async<_> object to client which can't handle it and fails mysteriously with no descriptions.
- If this throws exception and you have some more processing, server may fail to run StartAsTask even if it's there and again Async<_> is going to the wire.

Could we do something about this?
Could the Async be serialized as a Task internally automatically?

**Comment by dsyme** [comment]
Closing this inactive discussion
