### ISSUE TITLE
A method with the same name as DU counstructor

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#1488]
Why can't I create a static method with the same name as discriminated union constructor or static method generated from it?

Neither this

``` F#
type ElementDimensions =
    | Inherited of Length : Dimension
    | TypeSizeDimensions of TypeSize : TypeSize * Length : Dimension
    | CustomDimensions of Profile : Profile * Lenght : Dimension
    static member NewCustomDimensions (width, height, length) =
        CustomDimensions(Profile(width, height), length)
```

Nor this does work

``` F#
    static member CustomDimensions (width, height, length) =
        CustomDimensions(Profile(width, height), length)
```

And I wonder why because the number of parameters is different!
#### Expected behavior

If the list of parameters of DU constructor and the static method with the same name is different, it compiles well.
#### Actual behavior

error FS0023: The member 'NewCustomDimensions' can not be defined because the name 'NewCustomDimensions' clashes with the compiled form of the union case 'CustomDimensions' in this type or module
### Known Workarounds

``` F#
[<AutoOpen>]
[<CompilationRepresentation (CompilationRepresentationFlags.ModuleSuffix)>]
module Element =

    open System
    open System.Collections.Immutable
    open FSharp.Collections.Immutable
    open Microsoft.FSharp.Data.UnitSystems.SI.UnitSymbols

    let CustomDimensions (width, height, length) =
        CustomDimensions(Profile(width, height), length)
```

But it does not work for other .NET languages. I cannot expose an overload for DU case constructor method.
#### Related information
- Windows 10 Pro 14393
- .NET Portable Profile259
- Visual Studio 2015 Enterprise Update 3

**Comment by forki** [comment]
As described in the original post I don't think there is a easy fix if we don't want to override the compiler generated method.

**Comment by forki** [comment]
Original post at https://github.com/fsharp/fsharp/issues/604

**Comment by xperiandri** [comment]
I don't want to override it.
I just want to provide an overload for it.

**Comment by xperiandri** [comment]
Basically what I want is an ability to declare a few constructors for a single DU case.

**Comment by KevinRansom** [comment]
@xperiandri 
I think a user voice suggestion is the right place for this discussion

**Comment by xperiandri** [comment]
@KevinRansom, INCREASE the amount of votes there!
10 votes is too little to provide any suggestion!!!!!

**Comment by smoothdeveloper** [comment]
Actually suggestions moved out of user voice: https://github.com/fsharp/fslang-suggestions you can 👍 on all the suggestions you like without restriction.
