### ISSUE TITLE
Indentation Bug in Generic Type Parameters

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#1494]
This is valid 
```fsharp
open System

    module Z =
        type Alpha< ^b, ^a 
    when ^     a    :  (member Name:string)
and    ^a:        (member Zip
   : ^b when
^b : struct   )
and             ^a
:                 (static member(+)
    :    'a * 'a 
-> 'a 
) 
         > () = 
            member inline __.X = ()
        with  
        static member inline Y = ()
```

This gives an indentation warning on the `(` before `static`

```fsharp
type TypeWithALongName< ^a 
    when ^a:(static member(+):'a * 'a -> 'a )
    and  ^a:(static member(-):'a * 'a -> 'a )            
    and  ^a:(static member(*):'a * 'a -> 'a )            
    and  ^a:(static member(/):'a * 'a -> 'a )            
    > =
    static member inline X = ()
```

It seems like there should be no warning on the latter and the former should be cause for multiple compiler errors

The F# 4.0 Spec states
> The F# language uses simplified, indentation-aware syntactic constructs known as lightweight
syntax. The lines of the sample program in the previous section form a sequence of declarations and
are aligned on the same column. 

So generics don't count?

**Comment by dsyme** [comment]
@cloudRoutine It's correct that there are no specific indentation-aware rules applied while processing generic argument lists - i.e. no new indentation contexts are opened by any of the tokens/constructs.  So this is by design

**Comment by cloudRoutine** [comment]
then it seems like this is an oversight or flaw in the design
¯\\\_(ツ)\_/¯

**Comment by dsyme** [comment]
@cloudRoutine Yes, it is a bit of a flaw.

We thought about adding this in F# 2.0, but the cost for implementing the indentation aware syntax here is quite high, and the need is relatively rare.  

We would probably add named collections of constraints before we would add this.

So perhaps record it as a language suggestion at http://fslang.uservoice.com (that's the site for now  :) )

**Comment by abelbraaksma** [comment]
If this is by design, then why would you receive an indentation warning? Doesn't that mean it allows "free style" syntax between `<` and `>`?

**Comment by dsyme** [comment]
@abelbraaksma It's by design that no new indentation contexts are pushed in that region.

It's also by design that violations of existing (already-pushed) indentation contexts give the warnings

**Comment by abelbraaksma** [comment]
Aha. Tx. Got it now (I think).
