### ISSUE TITLE
VS 15 preview 4 crashes when I try to open project properties dialog

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1495]

**Comment by cartermp** [comment]
@vasily-kirichenko Which workload did you select?

**Comment by vasily-kirichenko** [comment]
Workload?..

**Comment by cartermp** [comment]
One of these:

<img width="450" alt="screen shot 2016-09-02 at 9 06 34 am" src="https://cloud.githubusercontent.com/assets/6309070/18210278/a6b1def6-70ec-11e6-93c8-e8622c135896.png">

I'll try and repro today when I'm at my office, but after installing the Data Science workload I was able to retarget an F# project through the Property Pages.  However I hadn't tried doing that in any other Workload.

**Comment by dsyme** [comment]
@OmarTawfik @brettfo @KevinRansom Any idea if this is still an issue, and/or does it deserve the "Urgency Now" label?  I presume not?

**Comment by KevinRansom** [comment]
It works for me with the latest preview build, so it must have been fixed.

If it still fails please re-open with a detailed repro

Thanks

Kevin

![proppages](https://cloud.githubusercontent.com/assets/5175830/20276664/0fbe3ea0-aa52-11e6-80c7-af3f204b2293.png)
