### ISSUE TITLE
random reflected field order

### ISSUE THREAD

**Issue by sgtz** [Microsoft/visualfsharp#1497]
The reflected field order is unexpected but deterministic (see example). If you assume you've got an unordered sequence of (tag,value) pairs, the impact is zero in terms of correctness. The point is that this is disconcerting for exploratory programming purposes. This as a place that could avail of the _sensible defaults_ principle.

... it's just better to be logical and consistent across the board.

Hint: in the example below, the values appear to be grouped by type and reversed within each group.

Take a simple vector -- I'd like to see this represented as (x,y,z), instead of (z,y,x). This goes for all types really, but in the vector case, there may be domain-specific situations where meaning that can be derived visually by the reader that'll be obscured otherwise.

End-points are not the only thing that matter, the in-between stage is also important -- take packet analysis in something like WireShark for example. Wouldn't you like the output to visually match what you are seeing in the interactive IDE / REPL. Yes, there are defensive workarounds available, but, it's much nicer not to be thinking at this level from the word go. Protobuf field ordering attributes come to mind as one way forward, but, again, it's nicer not to need these, and especially not in the early code-first stages. 

Side effects: 
1. decreased readability
2. may lead to author thinking they've got a piece of recursion wrong
3. unexpected order in downstream systems
4. it can be really strange for any kind of pub-sub round-tripping. 

More serious side effects:
1. if ordering changed between versions of .net, this could lead to order sensitive serializers like FsPickler breaking. In a distributed system this may pop up if the deployment of .dlls is staggered for some reason. In the strict IPC scenario that FsPickler is created for, this might not be a concern. 
#### Repro steps (.fsx ready)

```

open System.Reflection

type MixedValues(x : float, y : float, fname : string, lname : string, someVal : int, someOtherValue : int) =
  member prop.DX = x
  member prop.DY = y
  member prop.FName = fname
  member prop.LName = lname
  member prop.SomeVal = someVal
  member prop.SomeOtherValue = someOtherValue

let allMembers =
    BindingFlags.NonPublic ||| BindingFlags.Public |||
        BindingFlags.Instance ||| BindingFlags.Static |||
            BindingFlags.FlattenHierarchy

let ty = typeof<MixedValues>
let fields = ty.GetFields(allMembers)
              |> Array.map(fun pinf->pinf.Name)
```

Results in:

```
val fields : string [] =
  [|"y"; "x"; "someVal"; "someOtherValue"; "lname"; "fname"|]
```

Steps to reproduce the problem
1. copy the above into a .fsx file
2. run it
3. note your field ordering in the _fields_ value
#### Expected behavior

Take a simple vector -- I'd like to see this represented as (x,y,z), instead of (z,y,x). This goes for all types really, but in the vector case, there may be meaning that can be derived visually by the reader that'll be obscured.
#### Actual behavior

the values appear to be grouped by type and reversed within each group.
#### Known workarounds

You could add a sort in whatever code you are working on. However, programmers often group things for business domain reasons as a preference.
#### Related information

Provide any related information 

F# 4.0
Framework 4.6.1
.NET Runtime
Visual Studio

Severity: low

**Comment by cloudRoutine** [comment]
> if ordering changed between versions of .net, this could lead to order sensitive serializers like FsPickler breaking.  

@sgtz this is the exact issue I ran into trying to use FsPickler for IPC between processes running on different .net framework versions

**Comment by davisnw** [comment]
Type.GetFields does not guarantee an ordering, and it has long been documented that your code must _not_ rely on the order in which fields (or properties) are returned.

To me this does not appear to be an F# issue at all, nor a bug, but the expected behavior from the core of .NET.

If you want a specific order, you must order the fields after getting them based on  your own criteria.

From https://msdn.microsoft.com/en-us/library/ch9714z3(v=vs.110).aspx?cs-save-lang=1&cs-lang=fsharp#code-snippet-1
> The GetFields method does not return fields in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which fields are returned, because that order varies.

From https://msdn.microsoft.com/en-us/library/aky14axb(v=vs.110).aspx
> The GetProperties method does not return properties in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which properties are returned, because that order varies.

**Comment by sgtz** [comment]
@cloudRoutine: thanks for mentioning this. I did wonder if this would pop up. 

@davisnw: it's easy to think of a good reason for having a consistent default. I can't think of a good reason to support the current state of play. The first side effect is "the need to order the fields based on your own criteria." The property decoration scheme becomes the default for a disciplined programmer. The default is less readable code. Taking this to an extreme, then the default is engineer-first, rather than solve a problem first. 

Going back to the vector example, field order is important to the casual observer. Your observer may not be a programmer, but a mathematician, or a business expert. In fact, they may be the people who also write the original code. Kids are learning robotics in primary school these days. Programming is not purely the domain of professional programmers anymore.

Is there a way to raise a bug against the original spec?

What should a sensible default look like if we bake this into the respective compilers -- a static private member variable -- an array or string?

The current state of play seems to favour low-level considerations. I love protobuffs, but perhaps with the compiler-as-a-service philosophy, we should be looking beyond hinting the packet level alongside the code. Sure, get extra disciplined for multi-year efforts and define this yourself, but there exists a class of problem-solving that doesn't need this. Exploratory programming

**Comment by KevinRansom** [comment]
@cloudRoutine 
We will not bake in an arbitrary order.  Any sorting cost cpu cycles, and so if you need sorting, add it yourself.

Kevin

**Comment by sgtz** [comment]
@KevinRansom: the order is not arbitrary in this case, but that which the programmer works with + defines. It's a simple one-to-one mapping with an existing mental schema. It's useful meta. It's best not to throw it away.

An idea to come out of this is just to remember what the order was in a static list/array as a short-cut to framework authors to use if they want to. Otherwise, there are no shortcuts other than compiler-as-a-service / properties / parsing / some other manual mapping. In short, the alternatives are more verbose + manual + error prone.

I can't see that this would cost any CPU cycles because it is opt-in. Once the FsPickler combinators are ordered, no extra CPU cycles are lost there either. The compiler would do a minimal amount of additional work to store the extra meta -- one int16 per field / property / method / function.

What do you think? Am I missing anything?

**Comment by KevinRansom** [comment]
I'm sure that one could have fspickler add the extra metadata or sorting, but there is not much that the compiler can do to fix Type.GetTypes().

Kevin

**Comment by sgtz** [comment]
@KevinRansom: "there is not much that the compiler can do to fix Type.GetTypes()". 

Agreed. This "wouldn't it be good if" has morphed into a work-around. Let's not question the original rationale for unordered anymore. Here's a quick plan so that we can get back to discussing the merits of the idea:
1. generate SyntacticAST as per normal
2. walk type members. Note the order of these.
3. add a branch to each type's AST detailing the naturalOrder (a simple static member field / property, perhaps accessible via an interface)
4. emit IL as per normal
5. add a switch to fsc.exe --forgetNaturalMemberOrder:false (ie. it's on by default)

A simple alphabetical sort could solve this in FsPickler, and I'll submit that change at some point as an interim, but should we take the quick fix route, lets be clear that we are passing on the chance to add extra predicatability / debugability by default.

For me keeping the intuitive link back to the origninal source code is just as important as the potential cross-platform / cross-version issue this randomness represents.

**Comment by dsyme** [comment]
Closing old discussion
