### ISSUE TITLE
mutable struct behaviour --- is this expected :

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1499]
@dsyme 
````
let mutable struct (x,y) as p = struct (1,2);;

val mutable p : struct (int * int) = (1, 2)
val mutable y : int = 2
val mutable x : int = 1

> printfn "%A %A" x y;;
1 2
val it : unit = ()
> p <- struct (3,4);;
val it : unit = ()
> printfn "%A %A" x y;;
1 2
val it : unit = ()
>
````

Should x,y not have been updated to 3 and 4 or am I missing something?

Thanks

Kevin

**Comment by smoothdeveloper** [comment]
This has been topic for long discussions in roslyn/c# https://github.com/dotnet/roslyn/issues/10429.

In the sample you provide I'd assume `p` is mutable but not the individual parts, if you want mutable tuple, maybe you can use `ValueTuple` directly (albeit without nice syntax)?

**Comment by KevinRansom** [comment]
This behavior is matched by ref tuples so I suppose it is "by design".
