### ISSUE TITLE
Misaligned methods are either successfully compiled, or reported with unrelated messages

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#1504]
#### Repro steps

Provide the steps required to reproduce the problem

Take this code:
![image](https://cloud.githubusercontent.com/assets/4236651/18087466/a583ed78-6eb5-11e6-9ec1-8cd3dc77d25a.png)
#### Expected behavior

It should complain at the declaration of `test 2`.
#### Actual behavior

It compiles without errors or warnings.

---
## Case 2

Now, this case isn't actually that bad. What had me and a colleague stumped for some time was the behaviour, when you add a loop to the method:

![image](https://cloud.githubusercontent.com/assets/4236651/18087546/137097dc-6eb6-11e6-9e75-75c6c994c6ac.png)

If I remove two spaces each from the method declaration, it compiles.

In our more complex example, there was an error `this value is not a function and can not be applied` in the middle of the method, but if you copied the whole code block into another method, it compiled. Removing the block also made the method compile.
#### Version

![image](https://cloud.githubusercontent.com/assets/4236651/18087611/588744f6-6eb6-11e6-9784-c37e8656fe95.png)
#### Code

```
module Tests

open System.IO
open System.Xml.Linq
open System
open System.Xml
open System.Security.Cryptography
open Xunit



type FSharpTests() =
    [<Fact>]
    member __.``test 1``() =
        ()

      [<Fact>]  
      member __.``test 2``() =
        let folder = Path.Combine(__SOURCE_DIRECTORY__, @"..\..\Data")
        let paths = [| Path.Combine(folder,  "1")
                       Path.Combine(folder, "2") |]
        ignore paths.Length
//        for x in paths do ()
//        ()
```

**Comment by dsyme** [comment]
Closing in favour of language tracking suggestion https://github.com/fsharp/fslang-suggestions/issues/585
