### ISSUE TITLE
Provided reference to union case type not recognized

### ISSUE THREAD

**Issue by Jand42** [Microsoft/visualfsharp#1509]
Whenever a type provider emits code that uses a generated subclass of a union type, F# compiler fails to resolve it.

See https://github.com/Jand42/TP-error

Error: `The module/namespace 'Microsoft.FSharp.Core.FSharpChoice`2' from compilation unit 'FSharp.Core' did not contain the namespace, module or type 'Choice1Of2'`

Tested with VS2015 and VS15 Preview 4 (updated to FSharp.Core 4.1).

**Comment by dsyme** [comment]
@Jand42 This is more or less expected - provided union types are not supported, nor are subtypes of union types supported in the F# language.
