### ISSUE TITLE
Compiler generating invalid code.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#152]
Originally opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/165) by [eriktsarpalis](https://www.codeplex.com/site/users/view/eiriktsarpalis)

Here is a minimal reproduction example: 
https://gist.github.com/eiriktsarpalis/ec4a108444a91c0e7e8f 

And here is the code generated, as shown in ILSpy 
https://gist.github.com/eiriktsarpalis/197499e416227f7f91ff#file-generated-cs-L45 
For further reference, here is a screenshot of what happens when trying to evaluate in fsi: 

https://twitter.com/eiriktsarpalis/status/527528870699089920 

The issue seems to go away when I add an explicit annotation to the Bar argument in the Foo constructor. Not sure whether this is a typecheck or codegen issue, type checker does complain if I change create into an explicit member method.

**Comment by dsyme** [comment]
This code now gives an error when compiled, so marking this as fixed.  I'm not certain when the fix was made - it was sometime in F# 4.1 timeframe
