### ISSUE TITLE
Values with ' are not visible in VS debugger

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1521]
If I have a value called `args'` (which is happening a lot in the compiler itself) then VS 2015 debugger doesn't show the value. If I rename to `newArgs` then it works.

**Comment by dsyme** [comment]
I think this is might be because the C# expression evaluator is being used.  Or a naive parser for scraping the word/name from the source text

**Comment by dsyme** [comment]
Closing as covered by https://github.com/Microsoft/visualfsharp/issues/2544
