### ISSUE TITLE
Operator precedence table in MSDN is wrong

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#153]
opened at [codeplex](https://visualfsharp.codeplex.com/workitem/166) by[nodakai](https://www.codeplex.com/site/users/view/nodakai)

MSDN states
&&& , |||, ^^^, ~~~, <<<, >>>

should come between ^ op and < op, >op, =, |op, &op but it disagrees with the F# 3.1 language spec (draft.) 

http://stackoverflow.com/questions/26630784/f-operator-precedence

**Comment by dsyme** [comment]
Appropriate info has been provided to Bill Chiles, the MSDN docs contact for the VF# Team

**Comment by billchi-ms** [comment]
Submitted a fix with Don's spoon feeding.  I can't say when this will publish to MSDN due to our pub sched the next few weeks.

**Comment by dsyme** [comment]
Please fix this issue at https://github.com/Microsoft/visualfsharpdocs
