### ISSUE TITLE
can't run fsi.exe after installing Visual F# Tools 4.0 RTM on new machine

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#1535]
After installing the RTM package, running fsi.exe gives:

> error FS0193: Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0,Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

#### Repro steps

1. download https://www.microsoft.com/en-us/download/details.aspx?id=48179
2. install the package
3. cd "c:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0"
4. see error message

#### Expected behavior

Either running FSI session or during install, abort install with message with a link to preliminary requirement download.

#### Actual behavior

> error FS0193: Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0,Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

#### Known workarounds

Install https://www.visualstudio.com/downloads/download-visual-studio-vs#d-build-tools ms build tools.

#### Related information 

* Windows Server 2012

**Comment by isaacabraham** [comment]
This caught me out some time ago too with one of my devs. Clean machine, installed code and F#4 but still needed to install some MSBuild tools as well.

**Comment by smoothdeveloper** [comment]
Updated ticket description with link to msbuild tools which solves the issue.

Should future versions of setup abort and point to that location / mention "Microsoft Build Tools VERSIONNUMBER is a pre-requisite, please install it first"?

**Comment by dsyme** [comment]
@KevinRansom @cartermp @OmarTawfik Any updates on this?

**Comment by dsyme** [comment]
I think the question is whether the instructions at http://fsharp.org/use/windows are up-to-date.  Could you make sure the above dependency is documented there please?

**Comment by KevinRansom** [comment]
This is fixed in the next preview release.
