### ISSUE TITLE
fsc fails with StackOverflowException on a file with > 485 let bindings

### ISSUE THREAD

**Issue by estokes** [Microsoft/visualfsharp#1536]
Please provide a succinct description of the issue.

C:\Users\Eric>"C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\fsc.exe" -o:obj\Debug\Test.dll -g --debug:full --noframework --define:DEBUG --define:TRACE --optimize- -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v2.0\2.3.0.0\FSharp.Core.dll" -r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\mscorlib.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\System.Core.dll" -r:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll --target:library --nowarn:00052 --warn:5 --warnaserror:76 --vserrors --LCID:1033 --utf8output --fullpaths --flaterrors --highentropyva- --sqmsessionguid:d9b14b80-365b-425e-811d-066cf3c283cb Test.fs
Microsoft (R) F# Compiler version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

Process is terminated due to StackOverflowException.

#### Related information 

I generated a test case with the following function, but I will also attach the generated file
[Test.zip](https://github.com/Microsoft/visualfsharp/files/473504/Test.zip)

    let testlet path i =
        let head =
            [|"module TestCase"
              "open System"
              ""|]
        let binds = [|0..i-1|] |> Array.map (fun i -> sprintf "let x%d = \"%d\"" i i)
        System.IO.File.Delete(path)
        System.IO.File.WriteAllLines(path, Array.append head binds)

Provide any related information 

* Operating system

Windows 10 build 14393.105

**Comment by estokes** [comment]
Note, this issue may be related to #851, I wasn't sure, and I had it boiled down to a simple example, so I filed a new bug. I apologize if I've created noise.

**Comment by smoothdeveloper** [comment]
@estokes could you confirm that the issue doesn't happen if you compile in RELEASE mode instead of DEBUG?

In #851 according to last information there, it is related to the diasymreader component which I assume is outside of this repository, not sure if owner of this component could fix it for new release.

**Comment by estokes** [comment]
Confirmed. It does not happen when not compiling debug code.

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/18540482/425ee22c-7b1f-11e6-8e3d-7f73d8ba01f8.png)

it's happening in pdbCloseMethod in ilwritepdb.fs - will try to send your repro as unit test

**Comment by forki** [comment]
see https://github.com/Microsoft/visualfsharp/pull/1537

**Comment by dsyme** [comment]
AFAIK we have existing tests like this, I don't understand why CI isn't catching this problem. 

So we both need to fix this and check our CI test coverage

**Comment by forki** [comment]
@dsyme  see #1537 I tried to reprocude in the normal fsharpQA test suite, but seems I don't get that to go red. I also proposed a "fix"
