### ISSUE TITLE
Allow type annotations at the top level in fsi

### ISSUE THREAD

**Issue by Tarmil** [Microsoft/visualfsharp#1538]
Currently, using a type annotation at the top level in fsi results in a syntax error:

```fsharp
> 1 : int;;

  1 : int;;
  --^

stdin(1,3): error FS0010: Unexpected symbol ':' in interaction. Expected incomplete structured construct at or before this point, ';', ';;' or other token.
```

The workaround is to wrap the whole expression in parentheses, but I don't believe there's any reason for it to be necessary. It has misled some people into thinking they need to use another syntax instead ([like this person who tried to use `:?>`](https://www.reddit.com/r/fsharp/comments/52g9vr/how_to_solve_value_restriction_error/)).

(I'm submitting this here rather than on uservoice because I feel like it's more a parsing bug than a new feature really.)

**Comment by dsyme** [comment]
It's been like this since the start of time, so at this stage this is best considered "by design". Please submit to uservoice to track as a design change request, thanks.

**Comment by Tarmil** [comment]
[Ok, done.](https://fslang.uservoice.com/forums/245727-f-language/suggestions/16126906-allow-type-annotations-at-the-top-level-in-fsi)

**Comment by dsyme** [comment]
thanks
