### ISSUE TITLE
Unable to complete pattern match in function argument definition

### ISSUE THREAD

**Issue by SimonGustavsson** [Microsoft/visualfsharp#1539]
Hi there!

(I'm not very experienced with F#, so pardon my ignorance.)
I've been reading a lot of Haskell lately and thought the argument matching was kinda cool.
So I took to my F# project and tried the following:
````fsharp
let foo 1 = true
let foo _ = false
````

This fails to compile, as you'd expect(?) "Duplicate definition of 'foo'".
However, if you leave out the second definition of `foo`, you end up with a compiler warning about incomplete pattern match. There doesn't seem to be any way of completing this pattern match using this syntax.

I am aware a more idiomatic F# way would be
````fsharp
let foo = function | 1 -> true | _ -> false
````

or
````fsharp
let foo x = match x with | 1 -> true | _ -> false
````

I've been searching through the spec and the internet, but I have not been able to find a definite answer
as to whether this type of matching is supposed to be supported, or whether it's a "flaw" in the grammar.

Any help would be appreciated

Thank you

**Comment by forki** [comment]
only 

    let foo = function | 1 -> true | _ -> false

and

    let foo x = match x with | 1 -> true | _ -> false

are supported.

**Comment by cartermp** [comment]
I think that this warning is misleading:

```
Incomplete pattern matches on this expression. For example, the value '0' may indicate a case not covered by the pattern(s).
```

Since @forki is right, only the `function ...` and `match x with ...` forms are supported.  Idiomatic Haskell pattern matching isn't, but the warning could easily be interpreted as "you didn't do this style of pattern matching correctly".

**Comment by SimonGustavsson** [comment]
@cartermp I agree, I think a warning that is more specific to this case would be nice. I imagine it'd help people coming from other functional languages a bit.

Would someone be able to give a definite answer as to how this syntax is even valid in the first place?
I mean despite the warning, it compiles and runs. Guess I just don't like loose ends and just need to know!
