### ISSUE TITLE
CompilationRepresentationFlags.UseNullAsTrueValue silently ignored for recursive union types

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#154]
Opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/167) by [kurt2001](https://www.codeplex.com/site/users/view/kurt2001)

```fsharp
[<CompilationRepresentation(CompilationRepresentationFlags.UseNullAsTrueValue)>] 
type Test = A | B of Test 

box A = null // false
```

**Comment by dsyme** [comment]
I don't repro this - in F# interactive I get ``true`` for ``box A = null``

**Comment by latkin** [comment]
No repro for me either, even back to F# 3.0
