### ISSUE TITLE
Slighly suboptimal error messages when inheriting from non-existent type

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#1548]
This was tested using latest master.
#### Repro steps

Compile Project A:

```
module B
type PublicType() =
    member x.Y() = ()
type private PrivateType() =
    member x.Y() = ()
```

Try to compile Project B:

```
type E() =
    inherit B.Type()
    member x.Y() = ()
```
#### Actual behavior

Provide a description of the actual behaviour observed. 
![image](https://cloud.githubusercontent.com/assets/4236651/18615973/aea2919a-7db3-11e6-8409-12423b1572ca.png)

1) The error message is printed thrice.
2) Instead of a linebreak, some symbol is printed (maybe related to the new conhost in W10?)
3) The new heuristic offers all types, even ones that are not visible (PrivateType) (cc @forki)
#### Related information
- Operating system Windows 10
- Branch master

**Comment by forki** [comment]
@DebugKing something for the train ride? ;-)

Am 18.09.2016 15:25 schrieb "Lukas Rieger" <notifications@github.com>:

**Comment by forki** [comment]
repro at https://github.com/Microsoft/visualfsharp/pull/1552

**Comment by forki** [comment]
this can be closed.

**Comment by 0x53A** [comment]
The error message is still printed three times:

21>Program.fs(68,21): error FS0039: The type 'Type' is not defined in 'B'.
21>Program.fs(68,21): error FS0039: The type 'Type' is not defined in 'B'.
21>Program.fs(68,21): error FS0039: The type 'Type' is not defined in 'B'.

I don't get any suggestions at all for Type now (which is ok, because of the difference in size), but I get a suggestion for PublicType if I type PublicTyp. So that is good.

This is when building from VS
