### ISSUE TITLE
Could not find the full path of reference ‘System.ValueTuple’ after creating F# ConsoleApplication template

### ISSUE THREAD

**Issue by joelverhagen** [Microsoft/visualfsharp#1558]
_Copied from https://github.com/NuGet/Home/issues/3486._

**Repro Steps:**
1.	New a project (F# ConsoleApplication template).
2.	Expand ‘References’ node in Solution Explorer.
3.	Right-click ‘System.ValueTuple’ and look at the full path of it in ‘Properties’.

**Expected Result:**
There is no yellow warning icon on the reference and the full path is not empty.

**Actual Result:**
There is a yellow warning icon on the reference and the full path is empty as below screenshot.
![systemvaluetuple](https://cloud.githubusercontent.com/assets/20632625/18704195/9b5b26e6-801b-11e6-912f-6744be7bd48a.png)
**Note:**
1.	It found on Dev15 Preview 25719.02 (NuGet 3.6.0-Beta1-1821).
2.	It repro on Dev15 Preview 25719.02 + NuGet 3.6.0-xprivate-2004.
3.	It doesn’t repro on Dev14 Microupdate3.5 25431.01 (NuGet 3.4.4.1321).
4.	It doesn’t repro on Dev14 U3 25425.01 (NuGet 3.4.4.1321).
5.	It doesn’t repro on Dev14 U3 25425.01 + NuGet 3.5.0-RTM-1846.

**Comment by joelverhagen** [comment]
This problem resolves itself after first build, since NuGet detects a restore is required during the VS on-build event.

I spoke to @KevinRansom offline about this. My thought here is that the F# templates can use the template wizard to install the `System.ValueTuple` package. Details here:
https://docs.nuget.org/ndocs/visual-studio-extensibility/visual-studio-templates

This will mean that the `packages` folder is populated after File > New Project has completed.

**Comment by dsyme** [comment]
@KevinRansom Any ideas on this?

**Comment by dsyme** [comment]
@KevinRansom Perhaps the template needn't reference System.ValueTuple by default?

**Comment by KevinRansom** [comment]
Yes, I will fix it in a future set of templates, for now, restore nugget packages for the solution and all will be well.

**Comment by cartermp** [comment]
Just verified today - when you attempt to build for the first time on dev15, it'll restore packages and everything works.
