### ISSUE TITLE
FSProj: Can't use variables in Import declaration

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#1559]
#### Repro steps

We use common project files which are imported into each csproj/fsproj.

All our projects include two files:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(SolutionDir)..\Other\Build\TimCSDefaultSettings.proj" />
  <Import Project="$(SolutionDir)..\Other\Build\TimCSLibDefaultSettings.proj" />
```
#### Expected behavior

This should work the same in both csproj / fsproj
#### Actual behavior

In csproj, it works.
In fsproj, I get
![image](https://cloud.githubusercontent.com/assets/4236651/18745046/09896de4-80c1-11e6-8ac8-6909deb43bf3.png)
It seems to ignore the `$(SolutionDir)` and instead goes one level up from the project directory.
#### Known workarounds

I can hardcode the full relative path:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\..\Other\Build\TimCSDefaultSettings.proj" />
  <Import Project="..\..\Other\Build\TimCSExeDefaultSettings.proj" />
```

This works great if the project directory structure is flat, but if some projects are in different levels of subdirectories, then the import declaration is different between projects, which is suboptimal.
#### Related information
- VS 2015 Update 3

**Comment by KevinRansom** [comment]
@0x53A 

This doesn't repro for me.  I have a solution with two projects.
````
The path to the solution file is: C:\Users\kevinr\source\repos\ConsoleApplication41\ConsoleApplication41.sln
The path to the F# project file is:   C:\Users\kevinr\source\repos\ConsoleApplication41\ConsoleApplication41\ConsoleApplication41.fsproj
The path to the C# project file is:   C:\Users\kevinr\source\repos\ConsoleApplication41\ConsoleApp1\ConsoleApp1.csproj

The path to timsproj is: C:\Users\kevinr\source\other\Build\TimCSDefaultSettings.proj
````
If I delete the $(SolutionDir) from the project the project fails to load, indicating that it is actually used.

I'm using a preview build 15.6, but that shouldn't make a difference.
Does this help?
Kevin


The F# project file looks like:
````
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(SolutionDir)..\..\Other\Build\TimCSDefaultSettings.proj" />
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
````

The C# project file is: C:\Users\kevinr\source\repos\ConsoleApplication41\ConsoleApp1\ConsoleApp1.csproj

The C# project file looks like:
````
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(SolutionDir)..\..\Other\Build\TimCSDefaultSettings.proj" />
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
````

Both projects have successfully loaded: 
![image](https://user-images.githubusercontent.com/5175830/36824092-825f986a-1cb5-11e8-959f-eba8e1daa211.png)

**Comment by 0x53A** [comment]
I can still reproduce it with the latest preview.

I have no clue why your repro doesn't fail, I would expect it to.

Can you please try this project (https://github.com/0x53A/fs-variables-in-proj-file)?


```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(SolutionDir)x.proj"/>
```

![image](https://user-images.githubusercontent.com/4236651/36844754-3d24a66a-1d54-11e8-8b54-3945193a9e22.png)


```
---------------------------
Microsoft Visual Studio
---------------------------
The imported project "C:\Users\lr\Source\Repos\Library2\Library2\x.proj" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\lr\Source\Repos\Library2\Library2\Library2.fsproj
---------------------------
OK   
---------------------------
```
