### ISSUE TITLE
failwithf doesn't really work inside of async

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1569]
let f x  =
      async {
        try
          
          return 24
        with
        | exn -> failwithf "test %s" x
      }

![image](https://cloud.githubusercontent.com/assets/57396/18904069/9c5e2660-855c-11e6-95d4-fe79b5760291.png)

## Workaround

    let f x  =
      async {
        try
          
          return 24
        with
        | exn -> failwithf "test %s" x
                 return 0
      }

**Comment by dsyme** [comment]
This is by design though a better error message may make sense. ``failwithf`` is being used as a statement of type ``unit``.  The normal formulation is

    return! failwith "abc"

likewise for ``failwithf``

**Comment by forki** [comment]
Nice. Is this documented somewhere?

**Comment by dsyme** [comment]
@forki Not specifically.  Perhaps add it to the docs.microsoft.com page for F# async, or for ``failwith``, or both?
