### ISSUE TITLE
should not allow Framework 4 / F# 3.1 combination in project properties.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#157]
opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/171) by[Gautier](https://www.codeplex.com/site/users/view/Gauthier)

In a F# project properties, I can select Target Framework .NET 4.0 and at the same time pick F# 3.1 for F# runtime. 

It seems this combination is actually not working on machine having only .NET 4 installed, the assembly is compiled with a TargetFrameworkAttribute pointing to .NET 4.5 

The project properties dialog should forbid this combination.

>comments
>Gauthier wrote Nov 20, 2014 at 12:30 PM [x] 
>Actually, with VS2013 when you create a project picking framework 4, it sets the f# runtime on the wrong version by default.

>latkin wrote Nov 26, 2014 at 9:41 AM [x] 
>Good catch, yes we have not been careful about this.

**Comment by latkin** [comment]
I am keen to have this looked at and carefully sorted out.  We have been kind of casual about this in the past, would be good to have accurate target framework -> FSharp.Core version mappings in the UI.
