### ISSUE TITLE
Named/labeled tuple fields raise compile error when used with parentheses

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#1571]
I believe that labeled tuple fields were introduced in F# 3.1., but when used with parentheses around the type definition, they fail to compile.

## Repro steps

The following, normal tuples, work:

    type Y = Msg of string * string
    type X = Msg of (string * string)

But when labeled, the parenthesed version raises an error:

    // compiles successfully
    type Y = Msg of sender:string * Recip: string
    
    // fails with one or another error, see below
    type X = Msg of (sender:string * Recip: string)

## Expected behavior

It should just compile, the parens are superfluous and if the tuple without labels but with parens succeeds, it should behave the same with labels, I presume.

## Actual behavior

I have seen this raising either:

> error FS0010: Unexpected symbol ':' in type definition. Expected ',' or other token.

Or:

> Anonymous type variables are not permitted in this declaration

The second one shows up in the error log of VS2015, but not in the build log. It also shows when hovering over the statement. The first error is shown in the (textual) build log. In some projects, I didn't see the second error appear.

I don't know why I see different errors reported, but I'd guess there shouldn't be an error at all.

## Known workarounds

Remove the parens.

## Related information 

I could repro this within VS2015, with F# 4.0. I haven't tried other versions.

**Comment by 0x53A** [comment]
I think what was added in F# 3.1 was labeled DU fields, not labeled tuple fields.
Afaik you can't use labeled tuple fields anywhere except in DUs.

So the compiling case contains a DU with multiple named fields (not a tuple!) and the other case contains a DU with one field (which itself could be named) where that field itself contains a tuple.

**Comment by dsyme** [comment]
@0x53A is correct, so this is by design

**Comment by abelbraaksma** [comment]
Ah, now it makes sense. I never realized that it was the DU I am labeling, instead of the contained tuple. Then the difference in syntax makes sense.

Thanks.
