### ISSUE TITLE
VS debugger doesn't show variable inspector on variables named with a '

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#1584]
Using Visual Studio Professional 2015, I can't inspect `kv'` in that debugging session:

![image](https://cloud.githubusercontent.com/assets/87944/19174645/30c60d02-8be5-11e6-8970-9662a5282ed2.png)

The variable appears in locals pane.

**Comment by dsyme** [comment]
Duplicate of https://github.com/Microsoft/visualfsharp/issues/1521
