### ISSUE TITLE
C# compiler supports embedding sourcelink info in Portable pdb files.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1585]
From the latest: roslyn oss compiler build:

/sourcelink:<file>            Source link info to embed into Portable PDB.

The debugger team are currently implementing support to fetch sourcelink (ed) source code files.

We should enable this for F#.

**Comment by Korporal** [comment]
@KevinRansom - I cannot find any documentation about this new /sourcelink option, can you possibly shed some light?
