### ISSUE TITLE
Smart indent stops working for F# projects after installing Visual Studio Update 3

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#1588]
If you have _Smart Indent_ enabled in Visual Studio Tools > Options > Text Editor > F# > Tabs > Smart Indent, then it stops working after you install Update 3 of Visual Studio 2015.
### Repro steps

To reproduce, enable Smart Indent for any F# project in a Visual Studio 2015 Update 3 installation:
- Open VS2015 with any F# project
- Go to Tools > Options > Text Editor
- Select F#, then Tabs
- Select _Smart Indent_
- Click OK
- Type some code, indented, and hit enter
### Expected behavior

In any indented code block, you'd expect the cursor to either indent further (smart indent), or to stay at the same indentation level, after you hit Enter at any line.

```
module Test =
    let foo x =
        match x with
        ^ this is the expected position after hitting Enter on prev. line
```
### Actual behavior

The cursor _always_ returns to the beginning of the line, requiring you to hit tab multiple times to get to the correct position:

```
module Test =
    let foo x =
        match x with
^ actual position after hitting Enter on prev. line
```
### Known workarounds

Switching back to _Block Indent_ solves the problem (but obviously disables _Smart Indent_, though I can't remember how "smart" indenting was in F# prior to this issue arising, it is one of those conveniences you grow so accustomed to that you don't know it is even there, only to miss it when it is gone).
### Related information

Happened after installing Update 3 on VS 2015. Using F# 4.0.

**Comment by dsyme** [comment]
Closing as this is VS2015 and there has been a lot of change since this reported

**Comment by abelbraaksma** [comment]
I don't see much difference between smart indent and block indent, but I agree, this ought to be closed, as it is fixed beyond expectations, it works much better now in VS2017.
