### ISSUE TITLE
Types don't colorize at declaration

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1603]
1. Install latest master of F# and Roslyn in a single hive.
2. Create a Console App.
3. Enter the following:

``` fsharp
// Learn more about F# at http://fsharp.org
// See the 'F# Tutorial' project for more help.

type BST<'T> =
    | Empty
    | Node of 'T * BST<'T> * BST<'T>

let rec flip (tree: BST<'T>) =
    match tree with
    | Empty -> tree
    | Node(x, left, right) -> Node(x, flip right, flip left)

[<EntryPoint>]
let main argv = 
    printfn "%A" argv
    0 // return an integer exit code
```

Note that `BST<'T>` isn't colorized at the first declaration, but is colorized in subsequent uses.

![fs-roslyn-no-color-first-declar](https://cloud.githubusercontent.com/assets/6309070/19293513/d9fd7642-8fd9-11e6-8bcc-443ecceb0d70.PNG)

**Comment by brettfo** [comment]
Also, generic parameters don't colorize, either.

``` F#
let x = new HashSet<SomeType>()
//                  ^^^^^^^^ this isn't colorized

let y = new HashSet<int>()
//                  ^^^ neither is this
```

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/1841

**Comment by dsyme** [comment]
@vasily-kirichenko Thank you for this fix
