### ISSUE TITLE
Debugger does not show variables with names ending with quotation char

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#161]
opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/175) by [antofik](https://www.codeplex.com/site/users/view/antofik)

Debugger does not show variables with names ending with ' character. 
Suppose I have following code:

``` fhsarp
let x = 1
let x' = x + 1
```

If I try to see value of x' with hover, you'll get nothing. Using QuickWatch will result in error message "New line in constant".

> comments
> latkin wrote Nov 26, 2014 at 4:04 PM [x] 
> Yes, I can repro this, even on VS 2015. The x' variable does appear properly in the "locals" window, at least.
> We will follow up with debugger team and see if there is something simple we can do here to make this work better.

**Comment by mrange** [comment]
This is somewhat irritating as append ' is a quite common pattern.

**Comment by dsyme** [comment]
Closing as covered by more general issue #2544
