### ISSUE TITLE
Error FS0832: Only functions may be marked 'inline' is not thrown on static members that are not functions

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#1617]
A static member that is marked inline and is not a function but a field is accepted as an inline function and does not throw FS0832. This may well be a feature and not a bug, in that this gets compiled into a `get()` member which itself is a function. However, I do find it odd that this distinction exists, hence raising this bug.

Conversely, if a static member does not get compiled into a static global accessor field as a let-binding does, then inlining does make sense, or changing this to into no-inlining-allowed and functioning similar to let-bindings would make sense performance wise.

### Repro steps

To repro, see this code:

```
type Foo =
    | Bar
    static member inline Test = function Bar -> true    // no FS0832, but expected
    static member inline Other = 2                      // no FS0832, but expected
    static member inline Fun = fun _ -> 12              // no FS0832, but expected

module FooMod =
    let inline Test = function Bar -> true  // FS0832
    let inline Other = 2                    // FS0832
    let inline Fun = fun _ -> 12            // FS0832
```

### Expected behavior

The expected behavior is that the static members would also throw this error. However, that is not the case, which leaves one wondering whether the inlining is ignored or actually takes place on member references.

### Actual behavior

Error FS0832 is not thrown on static members.

Conversely, it may be nice to allow inlining on let-bindings that are values and not functions as well. It would simply work as a literal, except that this would have the odd side-effect that inlining a value and using it will typically be slower: it will be evaluated each time instead of only once (unless for the odd case where lookup is slower than immediate in terms of CPU registers and cache).

### Known workarounds

No workaround exists, or is necessary. It may well be considered a feature, unless the inlining does not take place, in which case it _should_ raise an error.

### Related information 

Behavior seen with VS2015 (no updates) and VS2015 Update 3, using F# 4.0.

**Comment by dsyme** [comment]
Yes, this is by design - the static property members are shorthand for ``get()`` functions.

**Comment by abelbraaksma** [comment]
Fair enough, albeit somewhat surprising. Thanks.
