### ISSUE TITLE
FSI won't run in Dev15 Preview 5

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#1622]
The F# Interactive Tool window is stuck in a failure loop where it prompts to hit enter to restart and immediately fails again.

![](http://i.imgur.com/cMUW0Fp.png)
#### Repro steps

Provide the steps required to reproduce the problem

1. Uninstall Visual F# Tools from **Dev15 Preview 5** Extension Manager
2. Install **VisualFSharpFull.vsix** from the [artifacts of release_ci_part1_windows_nt #243](http://dotnet-ci.cloudapp.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part1_windows_nt/243/artifact/)  
(the last successful build at the time of issue posting)
3. Open FSI tool window in **Dev15 Preview 5**

#### Expected behavior

FSI launches without immediately crashing

#### Actual behavior

FSI launches and immediately crashes

#### Known workarounds

[Install a build from before the visualfsharp/Roslyn branch merge](https://ci.appveyor.com/project/KevinRansom/visualfsharp-3dtit/build/0.0.1.1398/job/kkkdb0yalg5c190w/artifacts)

![](http://i.imgur.com/XdeOHMh.png)

_side note - VFPT works with this build_

#### Related information 

* Operating system - Windows 10 Pro 10.0.14393 Build 14393
* Branch - visualfsharp/master
* Editing Tools - Dev15 Preview 5

**Comment by dsyme** [comment]
I presume this is fixed now in master?
