### ISSUE TITLE
F# Language Settings missing from Text Editor Section of the Options Menu in Dev15 Preview 5

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#1623]
The text editor section of the Options menu is missing an entry for the F# language to set line numbers, virtual space, etc. It does have an entry for "FSharpInteractive" which doesn't seem appropriate for a tool window, I don't know if those settings do anything due to #1622 

![](http://i.imgur.com/KtoE4fo.png)
#### Repro steps

Provide the steps required to reproduce the problem
1. Uninstall Visual F# Tools from **Dev15 Preview 5** Extension Manager
2. Install **VisualFSharpFull.vsix** from the [artifacts of release_ci_part1_windows_nt #243](http://dotnet-ci.cloudapp.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part1_windows_nt/243/artifact/)  
   (the last successful build at the time of issue posting)
3. Open Options menu
#### Expected behavior

A listing for F#
#### Actual behavior

No listing for F#
#### Known workarounds

[Install a build from before the  visualfsharp/Roslyn branch](https://ci.appveyor.com/project/KevinRansom/visualfsharp-3dtit/build/0.0.1.1398/job/kkkdb0yalg5c190w/artifacts)

![](http://i.imgur.com/qlMfHMC.png)

_side note - VFPT works with this build_
#### Related information
- Operating system - Windows 10 Pro 10.0.14393 Build 14393
- Branch - visualfsharp/master
- Editing Tools - Dev15 Preview 5

**Comment by dsyme** [comment]
@cloudRoutine  @cartermp Was this fixed?

**Comment by cartermp** [comment]
Looks fixed to me on RC3 + VSIX:

![fixed](https://cloud.githubusercontent.com/assets/6309070/22563884/43a5e1e0-e937-11e6-9340-024f71a27de2.PNG)
