### ISSUE TITLE
Object expressions from base type with signature file don't compile

### ISSUE THREAD

**Issue by manofstick** [Microsoft/visualfsharp#1630]
The following works fine:

fsi file:

    module DelayedDouble

    type IDelay<'a> =
        abstract F : unit -> 'a

    val inline double : source:^T -> IDelay< ^T> when ^T : (static member ( + ) : ^T * ^T -> ^T) 

fs file:

    module DelayedDouble

    type IDelay<'a> =
        abstract F : unit -> 'a

    let inline double (value: ^a) : IDelay< ^a> =
        { new IDelay< ^a> with
              member x.F(): ^a = 
                  Checked.(+) value value }

But if we try to use a base class rather than an interface as in the following case:

fsi file:

    module DelayedDouble

    [<AbstractClass>]
    type Delay<'a> =
        abstract F : unit -> 'a

    val inline double : source:^T -> Delay< ^T> when ^T : (static member ( + ) : ^T * ^T -> ^T) 

fs file:

    module DelayedDouble
    
    [<AbstractClass>]
    type Delay<'a>() =
        abstract F : unit -> 'a

    let inline double (value: ^a) : Delay< ^a> =
        { new Delay< ^a>() with
              override x.F(): ^a = 
                  Checked.(+) value value }

The we get the following error:

    error FS1113: The value 'double' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible

If we remove the signature file then it functions as expected.

**Comment by dsyme** [comment]
@manofstick I'm pretty sure that's because the constructor for the abstract base type is hidden by the signature file

**Comment by dsyme** [comment]
Will close as by design , please reopen if needed

**Comment by manofstick** [comment]
Ahh yes, changing the signature to

    module DelayedDouble

    [<AbstractClass>]
    type Delay<'a> =
        new : unit -> Delay<'a>
        abstract F : unit -> 'a

    val inline double : source:^T -> Delay< ^T> when ^T : (static member ( + ) : ^T * ^T -> ^T) 

does work. Thanks!

Maybe nicer error message would be helpful (i.e. saying what is non-public...)

**Comment by isaacabraham** [comment]
Put a new task into the improved error issue :)
