### ISSUE TITLE
Enable Send/Execute/Debug in Interactive with Roslyn Integration

### ISSUE THREAD

**Issue by OmarTawfik** [Microsoft/visualfsharp#1633]
Implementation and verification of the following features:
- Execute in Interactive.
- Send to Interactive (Alt-Enter).
- Debug in Interactive.

**Comment by JoshVarty** [comment]
Just wanted to note that there's a conflict with the Alt-Enter keybinding for users with the Visual C# 2005 keybindings set. It maps Alt-Enter to View.Quick Actions. (The light bulb)

![image](https://cloud.githubusercontent.com/assets/1249087/20448173/93b73b9c-ad97-11e6-947d-2b65da36d580.png)

I'm going to try to figure out how to make sure Alt-Enter still maps to Send to Interactive within the context of F# files.

**Comment by dsyme** [comment]
@vladima @OmarTawfik @cartermp @brettfo  This is really crucial.  Please chime in if you're working on an implementation of this or have ideas on what to do. It's probably easy to wire up

**Comment by cartermp** [comment]
This is in the top set of issues @brettfo is tackling; however, we are in Escrow for vs2017 RC2 starting Monday.  There will be one last period on Monday morning PST for changes to make it into RC2, but the bar is likely to be high.  We can try to make a case for getting this (and recent fixes) in, provided there is an implementation checked in a ready for insertion at that point.

**Comment by dsyme** [comment]
@cartermp Thanks.  Yes, I do think the recent fixes need to go in, the tools are pretty much unusable without these fixes.

**Comment by dsyme** [comment]
This code as in ViewFilter.cs in FSharp.LanguageService.Base, which is no longer being used
```
            else if (guidCmdGroup == Microsoft.VisualStudio.VSConstants.VsStd11)
            {
                if (nCmdId == (uint)Microsoft.VisualStudio.VSConstants.VSStd11CmdID.ExecuteSelectionInInteractive)
                {
                    Interactive.Hooks.OnMLSend(GetProjectSystemPackage(), Interactive.FsiEditorSendAction.ExecuteSelection, null, null);
                    return true;
                }
                else if (nCmdId == (uint)Microsoft.VisualStudio.VSConstants.VSStd11CmdID.ExecuteLineInInteractive)
                {
                    Interactive.Hooks.OnMLSend(GetProjectSystemPackage(), Interactive.FsiEditorSendAction.ExecuteLine, null, null);
                    return true;
                }
            }
            else if (guidCmdGroup == guidInteractive)
            {
                if (nCmdId == cmdIDDebugSelection)
                {
                    Interactive.Hooks.OnMLSend(GetProjectSystemPackage(), Interactive.FsiEditorSendAction.DebugSelection, null, null);
                    return true;
                }
            }
```

**Comment by dsyme** [comment]
Also this in C:\GitHub\dsyme\visualfsharp\vsintegration\src\FSharp.VS.FSI\fsiSessionToolWindow.fs - I suppose this is being run since it is in ``OnToolWindowCreated``
```
            addCommand Guids.guidInteractiveCommands Guids.cmdIDSessionInterrupt onInterrupt     None
            addCommand Guids.guidInteractiveCommands Guids.cmdIDSessionRestart   onRestart       None
            addCommand Guids.guidFsiConsoleCmdSet Guids.cmdIDAttachDebugger      onAttachDebugger  None
            addCommand Guids.guidFsiConsoleCmdSet Guids.cmdIDDetachDebugger      onDetachDebugger  None
            
            addCommand Guids.guidInteractiveShell Guids.cmdIDSendSelection       onMLSendSelection   None
            addCommand Guids.guidInteractiveShell Guids.cmdIDSendLine            onMLSendLine        None

            addCommand Guids.guidInteractive Guids.cmdIDDebugSelection           onMLDebugSelection  None
```

**Comment by dsyme** [comment]
TBH I think it's just a matter of wiring up the stuff in this comment https://github.com/Microsoft/visualfsharp/issues/1633#issuecomment-263349069
