### ISSUE TITLE
Type extensions should not need generic type constraints, or throw a more descriptive FS0957

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#1635]
If you extend a type that has a generic type constraint on one or more of its generic type parameters, you will receive a (not very helpful) error message, like:

> FS0957: The declared type parameters for this type extension do not match the declared type parameters on the original type 'Map<\_,\_>'
### Repro steps

A simple example of getting this error is:

```
// seems valid enough (here extending the F# Map type)
type Map<'U, 'V> with
    static member merge map1 map2 = Map.fold (fun acc key value -> Map.add key value acc) map1 map2
```
### Expected behavior

I don't think this error should be raised, the constraints can be inferred from the original type and it is impossible to have two type names with the same generic type parameters, but different constraints.

If the error _must_ be raised, I suggest a different, or improved error message, something like:

> FS0957: One or more of the declared type parameters for this type extension have a missing or wrong type constraint not matching the original type constraints on 'Map<\_,\_>'
### Actual behavior

An error is raised as mentioned above.
### Known workarounds

Add the type constraint is the only logical workaround, but I think it oughtn't be necessary. With more complex type constraints (like member constraints) this can even be a real pain to get right.
### Related information

Tested and seen with VS2015, Update 3, F# 4.0.

**Comment by forki** [comment]
I created https://github.com/Microsoft/visualfsharp/pull/1835 which would fix this.

**Comment by dsyme** [comment]
@forki I've submitted https://github.com/Microsoft/visualfsharp/pull/3248 to improve the error message rather than change the language design

**Comment by dsyme** [comment]
Merged
