### ISSUE TITLE
The F# compiler ignores `MethodImplOptions.AggressiveInlining` flag

### ISSUE THREAD

**Issue by FrankNiemeyer** [Microsoft/visualfsharp#1637]
The F# compiler ignores the `System.Runtime.CompilerServices.MethodImplAttribute` applied to methods/functions if the `MethodImplOptions.AggressiveInlining` flag is set and consequently doesn't emit the required IL metadata ("aggressiveinlining" method flag = 0x0100).
#### Descriptive Example

For example, compiling the following F# code

``` fsharp
[<MethodImpl(MethodImplOptions.AggressiveInlining)>]
let inc x = x + 1
```

yields the following IL

```
.method public static int32  inc(int32 x) cil managed
{
    .maxstack  8
    IL_0000:  nop
    IL_0001:  ldarg.0
    IL_0002:  ldc.i4.1
    IL_0003:  add
    IL_0004:  ret
}
```

In contrast, the C# compiler translates

``` csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static int Inc(int x) => x + 1;
```

to

```
.method public hidebysig static int32  Inc(int32 x) cil managed aggressiveinlining
{     
    .maxstack  8
    IL_0000:  ldarg.0
    IL_0001:  ldc.i4.1
    IL_0002:  add
    IL_0003:  ret
}
```

generating the required `aggressiveinling` flag.
#### Further Experiments

The same behavior can be observed for `MethodImplOptions.AggressiveInlining` flags applied to methods or static methods of class types. Strangely enough, if applied to indexer `get`/`set` methods, the F# compiler doesn't ignore the attribute, but treats it like a custom attribute ([instead of a pseudo custom attribute](http://weblog.ikvm.net/2008/11/25/PseudoCustomAttributes.aspx)). For instance,

``` fsharp
type Dummy =
    member self.Item
        with [<MethodImpl(MethodImplOptions.AggressiveInlining)>] get x = x + 1
```

becomes

```
.method public hidebysig specialname instance int32 get_Item(int32 x) cil managed
{
    .custom instance void [mscorlib]System.Runtime.CompilerServices.MethodImplAttribute::.ctor(valuetype [mscorlib]System.Runtime.CompilerServices.MethodImplOptions) = ( 01 00 00 01 00 00 00 00 ) 
    .maxstack  8
    IL_0000:  nop
    IL_0001:  ldarg.1
    IL_0002:  ldc.i4.1
    IL_0003:  add
    IL_0004:  ret
}
```
#### Known workarounds

None.
#### Related information

According to @kvb, `PreserveSig`, `Synchronized`, and `NoInlining` flags seem to be respected by the compiler, see [this StackOverflow question](http://stackoverflow.com/questions/40104687/applying-methodimploptions-aggressiveinlining-to-f-functions).

Test environment:
- Windows 10 Pro Build (14393.321)
- .NET 4.6
- F# 4.0
- VisualStudio 2015

**Comment by kbattocchi** [comment]
It might be beneficial to review the other pseudo-custom attributes (see e.g. the list [here](http://weblog.ikvm.net/2008/11/25/PseudoCustomAttributes.aspx)) in addition to `MethodImpl` to verify that there aren't other important pieces of metadata being inadvertently dropped.

**Comment by buybackoff** [comment]
Is this still the case for the latest F# shipped with VS2017?

**Comment by forki** [comment]
AFAIK nobody has fixed this

**Comment by forki** [comment]
I tried to find it in ECMA 335 but it's not there!?

**Comment by forki** [comment]
WIP in https://github.com/Microsoft/visualfsharp/pull/3154

**Comment by forki** [comment]
mhm I just tried C#:

![image](https://cloud.githubusercontent.com/assets/57396/26578395/055b1162-4530-11e7-9b66-bd62bcfd4cc0.png)

**Comment by forki** [comment]
ok that was an issue with DotPeek. ILSpy is showing:

![image](https://cloud.githubusercontent.com/assets/57396/26579239/477ef916-4533-11e7-9cee-d7ffc5d15381.png)

**Comment by forki** [comment]
btw: it looks like noinlining is not respected as well.

**Comment by buybackoff** [comment]
I have created a simple workaround for this - just to [rewrite](https://github.com/Spreads/Spreads/blob/master/tools/ILSub/Program.cs#L207-L227) IL after build and repack it with ilasm. It was simpler than #3154 for me. Such trick was used in corefxlab in the very early implementation of the `S.R.CS.Unsafe` package. All code is in [this commit](https://github.com/Spreads/Spreads/commit/e05817cc0087f09bcc96727643096734c9efefa9). 


To add the attribute, one should add a custom attribute [`RewriteAIL`](https://github.com/Spreads/Spreads/blob/master/src/Spreads.Core/Utils/ILSub.cs#L24) next to `MethodImpl(MethodImplOptions.AggressiveInlining)` like [here](https://github.com/Spreads/Spreads/blob/master/src/Spreads.Collections/Collections/SortedMap.fs#L1623). Then after build a [command](https://github.com/Spreads/Spreads/blob/master/tools/re_write_il.cmd) started from a command line 
disassembles a dll to IL, adds the `aggressiveinlining` attribute and repacks the modified IL code into a signed dll.

Tools and samples are in [this folder](https://github.com/Spreads/Spreads/tree/master/tools).

I couldn't integrate it with build automatically, but after manually calling rewrite scripts as admin the command `[dotnet pack](https://github.com/Spreads/Spreads/blob/master/nuget/step3.bat)` with `--no-build` works fine.

This gives small but stable c.5% performance improvement for the hottest method in the library.
![image](https://user-images.githubusercontent.com/489852/27466140-2324eef2-57e1-11e7-8bde-86a1e2b2fddf.png)

**Comment by dsyme** [comment]
@buybackoff The fix https://github.com/Microsoft/visualfsharp/issues/3154 is now ready

**Comment by buybackoff** [comment]
@dsyme Thanks a lot! When it will be available? Several percents are not a game changer but they are real and free 😄

**Comment by dsyme** [comment]
@buybackoff probably not until Visual Studio 2017 Update 4, unless you're using some other packaging of the F# compiler.  Maybe Visual Studio 2017 Update 3 but that depends on what the Microsoft ship people decide.

**Comment by dsyme** [comment]
Merged
