### ISSUE TITLE
F# interactive is not given focus in VS 2015

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#164]
opened at[codeplex](https://visualfsharp.codeplex.com/workitem/182) by [latkin](https://www.codeplex.com/site/users/view/latkin)

In VS 2013 and earlier, sending code to F# Interactive causes that tool window to 
* Activate if it wasn't open at all before 
* Get focus and become visible if it was currently a "hidden" tool window (e.g. "Error List" was the visible tab)

In VS 2015 preview, the second behavior is not working. Code is correctly sent/evaluated, but the user needs to manually click on the tab in order for F# interactive to become visible.

**Comment by latkin** [comment]
This seems to work now, though I don't recall doing anything to change the behavior.  Would be interested to know if anyone else can repro.

**Comment by KevinRansom** [comment]
I'm closing this not repro, the behavior in 2013 and 2015 seem to be the same for me.
