### ISSUE TITLE
.fsx file not colourized with latest bits.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1642]
Observe:

![untitled](https://cloud.githubusercontent.com/assets/5175830/19535438/7f337058-95fc-11e6-944f-9fc6b70d4b4f.png)

**Comment by OmarTawfik** [comment]
Are you sure it is not a duplicate of #1590?

**Comment by OmarTawfik** [comment]
@KevinRansom  The fix is not inserted into VS yet. To test it, you've to F5 the vsix locally.

**Comment by KevinRansom** [comment]
Sweet ... Thanks
