### ISSUE TITLE
Illogical error message when asking using Seq.item 0 on an Empty Seq

### ISSUE THREAD

**Issue by liboz** [Microsoft/visualfsharp#1644]
@cloudRoutine 
#### Repro steps

Build master and then open FSI and type
`Seq.item 0 (Array.zeroCreate<int> 0)`
#### Expected behavior

The error message should say `seq was short by 1 element`.
#### Actual behavior

The error message is `seq was short by 0 elements`, which makes no sense since that should mean the sequence had enough elements.
#### Known workarounds

None

**Comment by forki** [comment]
see https://github.com/Microsoft/visualfsharp/pull/1818
