### ISSUE TITLE
F# PortableProfile 78 and 259. Apps that use BigInt are not portable to coreclr and they should be.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1658]
Because profile 78, 259 contain an implemention of BigInt and coreclr has a BigInt implementation from System.Numerics.

I think we need a repro case and a type forward in the coreclr assembly.

Discovered because I was trying to upgrade to fscheck and specified the profile259 version of the portable lib.

Kevin

**Comment by dsyme** [comment]
The big integer support in FSharp.Core is such a millstone for us.  We really should have just avoided having any mention of BigInteger in FSharp.Core at all and somehow had the support just be completely separate.

If there was a way we could cut that connection (e.g. deprecate the System.Numerics reference in FSharp.Core itself, and have no BigInteger support in Profile 259 and 78, but have everything work correctly if you can reference System. Numerics in .NET Core, .NET Standard or .NET Framework) then perhaps we should follow that path now.  I'd be happy with a story where BigInteger just doesn't work in Profile 78 or 259.

Even if we don't do that it feels like worrying about this glitch with Profile78/259 is not worth it, and we should just say ".NET Standard is coming, if you want cross-platform components that use BigInteger then use that"?

**Comment by KevinRansom** [comment]
BigInt is not really a problem, we can easily TypeForwardTo to System.Runtime.Numerics and all will be well.  Right now, I just need to understand if there is a good reason we don’t allow the “TypeForwardedToAttribute”.  I can’t think of a reason why it’s not supported.

We also need the type forward in Desktop, Windows Profile 7 and I think profile 47.

Anyway it’s not any sort of real problem … just a compatibility detail that’s just come to light.

Kevin

**Comment by KevinRansom** [comment]
Fixed.
