### ISSUE TITLE
F# compiler doesn't support authoring TypeForwardedTo attribute

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1660]

**Comment by dsyme** [comment]
Adjusted the title to say that this is about authoring TypeForwardedTo attributes in F# code (F# does support reading the compiled .NET form of theses from the ExportedTypes tables of .NET assemblies).

**Comment by KevinRansom** [comment]
I liked the original title.

**Comment by dsyme** [comment]
:)

**Comment by KevinRansom** [comment]
Resolved the issue:  
F# does not support authoring of TypeForwarding Attributes.  However, the issue was to enable type forwarding from Fsharp.Core.dll version of BigInteger to the System.Runtime.Numerics version.

See:     https://github.com/Microsoft/visualfsharp/pull/1675
