### ISSUE TITLE
Error from git when running build.cmd as admin

### ISSUE THREAD

**Issue by peter-campora** [Microsoft/visualfsharp#1664]
Running build.cmd fails with the errors listed in the Repro steps section.
#### Repro steps

I'm running cmd/powershell as an admin in the visualfsharp-master directory, and when I try to build the fsharp compiler, I get the errors:
"C:\PathTo\visualfsharp-master\src\fsharp-proto-build.proj" (default target) (1) ->
"C:\PathTo\visualfsharp-master\src\fsharp\FSharp.Build-proto\FSharp.Build-proto.fsproj" (Build target) (2) ->
(GenerateSourceLink target) ->
  C:\PathTo\visualfsharp-master\src\FSharpSource.targets(552,5): error MSB3073: The command "git config --get remote.origin.url" exited with code 1. [C:\PathTo\visualfsharp-master\src\fsharp\FSharp.Build-proto\FSharp.Build-proto.fsproj]

"C:\PathTo\visualfsharp-master\src\fsharp-proto-build.proj" (default target) (1) ->
"C:\PathTo\visualfsharp-master\src\fsharp\FSharp.Compiler-proto\FSharp.Compiler-proto.fsproj" (Build target) (3) ->
  C:\PathTo\visualfsharp-master\src\FSharpSource.targets(552,5): error MSB3073: The command "git config --get remote.origin.url" exited with code 1. [C:\PathTo\visualfsharp-master\src\fsharp\FSharp.Compiler-proto\FSharp.Compiler-proto.fsproj]"

I also see a, "ERROR: The system was unable to find the specified registry key or value.".

Git is installed, and my internet is working.
#### Expected behavior

A successful build of the compiler
#### Actual behavior

I get two "error MSB3073: The command "git config --get remote.origin.url" exited with code 1." errors.
#### Known workarounds

Provide a description of any known workarounds.
#### Related information

Provide any related information 
- Operating system - Windows 10
- Branch - visualfsharp
- .NET Runtime, CoreCLR or Mono Version - .NET 4.6
- Editing Tools (e.g. Visual Studio Version) - VS Enterprise 2015
  Git is installed, as is msbuild and Strawberry Perl

**Comment by dsyme** [comment]
@peter-campora I believe this is now fixed, could you try again?  Or can you check you can run ``git config --get remote.origin.url`` please?

**Comment by peter-campora** [comment]
Yes @dsyme , I don't have any issues with git in the build file anymore, but I do have a new issue with use of fsi.exe in C:\PathTo\visualfsharp\src\scripts\fssrgen.targets(27,5): 

I'm repairing Visual Studio 15 and I'm going to make sure all of the other software is correctly installed before filing a new ticket.

On another (off topic) note, is writing a script file to interact with a built compiler infeasible (I was able to successfully build the open source code base on a fedora machine)? I basically want to instantiate some research ideas that will use the FSharp constraint solver. So I'm trying to just add a script file and load the necessary dll's and source files to just work with the type system, but I've run into some puzzling errors. I just want to make a script to quickly test out the skeleton of the algorithm, for a paper.

Thanks,
Peter Campora

**Comment by dsyme** [comment]
> On another (off topic) note, is writing a script file to interact with a built compiler infeasible (I was able to successfully build the open source code base on a fedora machine)? 

It might be better to do this in a fork of the FSHarp.Compiler.Service project (basically the same as this repo but building the compiler as a DLL).  The tests show how to use the component. You can gradually then make more things public, strip off signature files etc. according to your hacking needs
