### ISSUE TITLE
Searching for "F#" yields no results

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1671]
https://docs.microsoft.com/en-us/search/index?search=F%23

The above query yields no results.  I remember it working before, so I think this is a regression.

**Comment by atifaziz** [comment]
So much for being a citizen of [first-class](https://docs.microsoft.com/en-us/search/index?search=C%23). :wink:

PS Sorry for the poor humour and while I'd choose F# over C# any given day, I just couldn't resist.

**Comment by cartermp** [comment]
Being addressed by the team.  Closing!
