### ISSUE TITLE
Context menu in prerel branch for .fsx file does not have a Send to interactive option

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1676]
Context menu in prerel branch for .fsx file does not have a Send to interactive option

<img width="1440" alt="screen shot 2016-10-27 at 9 32 01 pm" src="https://cloud.githubusercontent.com/assets/5175830/19795158/1c7ff39e-9c8e-11e6-9412-bca5890f8eb8.png">

**Comment by OmarTawfik** [comment]
@KevinRansom  I think it is a duplicate of #1633?

**Comment by KevinRansom** [comment]
So it is.

**Comment by KevinRansom** [comment]
yep
