### ISSUE TITLE
Refactor/delete old language service code

### ISSUE THREAD

**Issue by OmarTawfik** [Microsoft/visualfsharp#1679]
With the merge of the Roslyn branch, the following projects can be refactored/deleted from the codebase:
- FSharp.LanguageService
- FSharp.LanguageService.Base

Along with all tests that reference them in VisualFSharpTests project.

**Comment by OmarTawfik** [comment]
@brettfo I'm creating this work item to track that work. I'm suspecting it will be a series of PRs to complete, but it is not blocking feature work.

**Comment by dsyme** [comment]
Note we will want to keep tests until their logical equivalent has been transferred to  the new LS too. There are a lot of critical test assets in there :)

**Comment by OmarTawfik** [comment]
@dsyme yes. That's what was actually more time consuming than implementing the new language service. Porting tests and tweaking issues there.

**Comment by cartermp** [comment]
I'm going to close this out:

* Migrating all the unit tests is unlikely to happen given how expensive and time consuming that effort would be
* This code is dead in the actual product. No code path touches it now, for any reason

Given this, I think things are fine enough to close.
