### ISSUE TITLE
Use github tags instead of close pr/issue

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#168]
Instead of closing a pull request if not meets some criteria for contributions, tag it with `needs-something`

A pull request can be easy updated ( need only to push to branch )
Also i  can see the open pull requests in all github [is:pr author:jack-pappas is:open](https://github.com/search?utf8=✓&q=is%3Apr+author%3Ajack-pappas+is%3Aopen&type=Issues&ref=searchresults), easier to track all todo

Reopen a closed pr is more work from contributor (make easy to contribute) and easier to forget

like:
* `needs-performance-test` #58 #59 #61 #62
* `needs-cla-signed` 
* `needs-test` #63
* `needs-issue` #63

With lot of issue/pr is easier to triage with tags and search

some other good tags `needs-doc` , `needs-speclet`, `needs-api-compatibility` maybe :smile:

**Comment by dsyme** [comment]
That's an interesting idea.  Though from experience having PRs hanging around is quite a burden on the repo maintainers (and for visualfsharp the time of the maintainers is a critical resource).  I'd rather just get to the point where people routinely only submit PRs that mean the requirements.

**Comment by latkin** [comment]
I like the idea of adding tags like `needs-spec` or `needs-test`, but I'd still prefer to close.  Luckily, it is just as easy to search for closed, tagged PRs as open, tagged PRs :).

We don't want a bunch of PRs and issues left open indefinitely when they don't even meet the minbar for contributions.

**Comment by forki** [comment]
Closing is much easier for maintainers, that's for sure. But don't forget we want to build a strong community and therefor it's important for people to get involved and also to make mistakes. Closing a pull request is always a bit disappointing to the person who sent the PR. 

From this point of view PRs should not be closed instantly because of formal reasons. That's often way to hard for newcomers. Instead we should help them to get the thing accepted. This doesn't mean that the Visual F# team has to guide every newcomer. I'm pretty sure that people who already have a couple of accepted PRs can help here.

**Comment by dsyme** [comment]
Yes, giving people lots of help is really important.

**Comment by dungpa** [comment]
Perhaps give a window (a few hours, 1-2 days, etc.) before closing a PR and mention it in the contributing guidelines. That gives enough time for a submitter to response and fix mistakes. 

Imagine a newcomer submitting a PR with goodwill. It's not a good experience if your first PR gets closed right away.

**Comment by latkin** [comment]
![image](https://cloud.githubusercontent.com/assets/5943573/5946157/818d3e56-a6e8-11e4-9e0f-3c721cb1b721.png)

Juuuust kidding :) Yes, of course whatever we do we still want to be helpful and polite, and not discouraging to those eager to contribute. I think allowing some reasonable buffer time makes sense.

**Comment by forki** [comment]
YES! Gifs are the magic to make github projects successful ;-)

**Comment by dungpa** [comment]
Yep, more magic gifs please.

**Comment by enricosada** [comment]
I think status closed it usually mean end of discussion, open can be further discussed and improved.

If a pr need the performance test, maybe the code is ok to review. If the pr is open, there are more :eyes: to review it waiting of tests from the author

For sure a pr must be closed after some time ( maybe after a ping comment to author )
An open pr for a week is not uncommon, people write on spare time ( i do ), is not a race to close issues quickly but better code and discussion
Btw for that reason i dont like the  badge issuestats, pretty much useless, github pulse is way better

Meanwhile the tags are nice to have, to quickly triage the status of a pr

:+1: for gifs

**Comment by dsyme** [comment]
I agree that leaving things open for at least a week seems reasonable.
