### ISSUE TITLE
How to see all git history for VS integration part?

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1683]
The git history of this repository started 2 years ago. I'd like to see how this file https://github.com/Microsoft/visualfsharp/blame/master/vsintegration/src/FSharp.ProjectSystem.Base/Project/ProjectConfig.cs, for example, has been evolved. 

@dsyme I think you wrote somewhere (on Twitter or in some github repository) that it's possible to get older history. Can you help with it please?

**Comment by KevinRansom** [comment]
There is no public older history for the vs tools.  The compiler was.first open.sourced on codeplex.so there may be some extra compiler history there.

**Comment by dsyme** [comment]
http://visualfsharp.codeplex.com and the code drops at https://fsharppowerpack.codeplex.com/ are the best we have
