### ISSUE TITLE
FSI text often shows as white-on-almost-white, hard to read

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#1684]
Quite often I end up with FSI looking like the following (and this is **not me selecting the text!**):

![White on white](http://i.imgur.com/EvjbNXE.png)

Once it happens, resetting FSI is not a solution (it will look as above). FSI works, but it is very hard to read. After restarting Visual Studio, it works as normal.

Typing text in FSI has the text itself covered in the same white-on-white look.

I am unsure what causes it, but it happens quite often. I'm reporting it for the off-chance that others have seen this too, and/or can point me in the direction for debugging this, as I would like to get to the bottom of it (it starts to be rather annoying).

Using VS 2015 Update 3 with F# 4.0. 

It happens with FSI in Debug or Release mode.

Today I have restarted and retried an exact same set of steps, and sometimes it happened, sometimes it didn't (only to happen a few hours later anyway). Not having a good repro is not very handy, I know, but I welcome any ideas on how to debug this.

**Comment by cartermp** [comment]
I cannot repro this, so I'm going to bump this to VS 2017 Updates.

**Comment by cartermp** [comment]
@abelbraaksma Have you been able to repro this with the VS 2017 RTM bits?

**Comment by cartermp** [comment]
Closing this, since (a) haven't noticed white-on-white highlighting when it's in focus, and (b) I doubt that highlighting color is something we control.

**Comment by abelbraaksma** [comment]
> @abelbraaksma Have you been able to repro this with the VS 2017 RTM bits?

Actually, I have not seen it since the latest update of VS2015, and I haven't seen it in VS2017 P4 yet. So I'm thinking it got somewhere fixed down the line. 

That is not to say that it won't happen again, it might, since it only happened occasionally and in particular when copy/pasting or sending-to FSI large chunks of code.
