### ISSUE TITLE
Upgrading FSCheck to 2.5.0 or 2.6.2 causes fsharp.core.unittests to not complete

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1691]
@forki 

Do you know anything about fscheck, I have tried several times to update it to a newer version.  But When I do fsharp.core.unittests hangs, or at least fails to complete in a reasonable time.

**Comment by KevinRansom** [comment]
It just finished:  7158 seconds ---- that's almost 2 hours

Run Settings
    RuntimeFramework: V4.0
    WorkDirectory: c:\kevinransom\visualfsharp\release\net40\bin
    Verbose: True
    NumberOfTestWorkers: 4

Test Run Summary
    Overall result: Failed
   Tests run: 5317, Passed: 5316, Errors: 1, Failures: 0, Inconclusive: 0
     Not run: 0, Invalid: 0, Ignored: 0, Explicit: 0, Skipped: 0
  Start time: 2016-11-01 00:35:56Z
    End time: 2016-11-01 03:16:28Z
    Duration: 7158.638 seconds

**Comment by forki** [comment]
I think we need to ask @kurtschelfthout about what changed in fscheck

**Comment by kurtschelfthout** [comment]
See https://github.com/fscheck/FsCheck/issues/326

**Comment by kurtschelfthout** [comment]
I'm looking at his. How long does it usually take?

**Comment by dsyme** [comment]
Thanks @kurtschelfthout  and @KevinRansom for doing this
