### ISSUE TITLE
User-defined Module name gets colorized as blue when used to qualify a computation expression name

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1697]
0. Using the Roslyn editor on dev15prerel with .NET Desktop installed
1. Clone [FSharpx.Extras](https://github.com/fsprojects/FSharpx.Extras)
2. Change build targets of projects if they don't load, I just changed them to .NET Framework 4.6.1 and everything was fine
3. Run paket.bootstrapper and then paket restore
4. Open `Lens.fs` and go to line 58, noting that `State.state` is colorized blue, as if it were a keyword.

![fs-wrong-color-type](https://cloud.githubusercontent.com/assets/6309070/19977729/dc76df8c-a1b1-11e6-8ead-f2b0eeb27d23.PNG)

However, the module `State` is user-defined:

![fs-wrong-color-type-module](https://cloud.githubusercontent.com/assets/6309070/19977740/e4b7303e-a1b1-11e6-99d2-e98e7a296338.PNG)

I'm not actually sure what the expected behavior here should be.  Should the module be colorized at all as, say, teal?  Should the name of the user-defined computation expression be colorized?  cc @dsyme @Pilchie

**Comment by forki** [comment]
please make sure that `state` (the one in lower case keeps be highlighted as keyword.

**Comment by OmarTawfik** [comment]
@cartermp I wonder if that repros in Preview 5 (before rolsyn). No colorization logic was changed with RC?

**Comment by cartermp** [comment]
@OmarTawfik I can try tomorrow, but this does have your type colorization work (`'T` and `'State` are colorized in the second screenshot).

**Comment by cartermp** [comment]
@OmarTawfik There's no coloring on dev14 Update 3:

![fs-dev14-no-color](https://cloud.githubusercontent.com/assets/6309070/20021052/6f72fd54-a291-11e6-8fa9-2d595ac3d116.PNG)

**Comment by vasily-kirichenko** [comment]
In VS 2017 RC with VFPT installed it looks OK:

![image](https://cloud.githubusercontent.com/assets/873919/20462716/a756d294-af35-11e6-8a6d-8e49a604da15.png)

**Comment by brettfo** [comment]
Fixed by #2036.
