### ISSUE TITLE
Go to Definition indicates that VB is the language, not F#

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1698]
This is using dev15prerel branch, with the same repro/setup steps as #1697 

![fs-wrong-color-type-module](https://cloud.githubusercontent.com/assets/6309070/19977993/ace089f2-a1b2-11e6-98e4-cb6a212359a8.PNG)

**Comment by OmarTawfik** [comment]
@CyrusNajmabadi is this something configurable from our side? where does roslyn get the icons from?

**Comment by CyrusNajmabadi** [comment]
We're probably just falling back to VB if the language isn't C#.  Whoops.   :)

**Comment by CyrusNajmabadi** [comment]
Code is here: C:\GitHub\roslyn-internal\Open\src\VisualStudio\Core\Def\Implementation\Library\FindResults\TreeItems\DefinitionTreeItem.cs

**Comment by OmarTawfik** [comment]
Thanks @CyrusNajmabadi. I filed https://github.com/dotnet/roslyn/issues/15178 to track this.
@cartermp wrong link in the description?

**Comment by cartermp** [comment]
Good catch @OmarTawfik, fixing.

**Comment by cartermp** [comment]
Closing this for now, since F# should not be returning more than one result.
