### ISSUE TITLE
Seq.item fails compilation with "This construct is deprecated. please use Seq.item"

### ISSUE THREAD

**Issue by Andrea** [Microsoft/visualfsharp#170]
Verified this bug on both latest pre-release and previous one

![Seq.item](https://cloud.githubusercontent.com/assets/3103/5946566/b72467b0-a72e-11e4-9827-e3c2e1b89945.png)

Same error occurs for Seq.nth.

The implementation of Seq.item doesn't seem to be available in Seq. However according to [this](https://visualfsharp.codeplex.com/wikipage?title=Status) it looks like it should 

I am testing a little bit more will update this issue when I know more

**Comment by forki** [comment]
could you please try to come up with a mini-repro?

**Comment by latkin** [comment]
This was originally opened as https://github.com/fsharp/fsharp/issues/375

Just a trivial mistake.
>Whoops.  Can you please open this at https://github.com/Microsoft/visualfsharp/ ?

>`item` should be replacing `nth`, it is a mistake that `item` got marked Obsolete. See [here](https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/ListSeqArrayAdditions.md)

>Culprit [here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/FSharp.Core/seq.fsi#L570)

>BTW I would not think this is an error, just a warning. Do you have "warnings as errors" enabled?

**Comment by mexx** [comment]
Sorry, my bad, it was introduced in https://github.com/Microsoft/visualfsharp/commit/f028ee4a27b8e0d03b03d3e85caf6a94d8a350a9
