### ISSUE TITLE
Improve error reporting: suggest using `in` instead of mistaken `=`

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#1711]
# what

when writing for loop

```fsharp
for i = 0 .. 100 do
    ()
```

FSI yields

> Unexpected symbol '..' in expression

# why

I made a mistake using `=` instead of `in`

# how

I'd like the compiler to show me how to fix:

> Unexpected symbol '..' in expression, were you intending to use for x in y .. z do?

Related #1430

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/20866294/936d3566-ba2a-11e6-8cab-92c1693cd9d2.png)

**Comment by forki** [comment]
PR at https://github.com/Microsoft/visualfsharp/pull/1934
