### ISSUE TITLE
Implicit module suffix is not added to rec modules

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1720]
This code compiles OK:

```fsharp
type R = R
module R = begin end
```

This does not:

```fsharp
type R = R
module rec R = begin end
```
```
Error	 Duplicate definition of type, exception or module 'R'	ConsoleApplication3	C:\Users\kot\documents\visual studio 15\Projects\ConsoleApplication3\ConsoleApplication3\Program.fs	14	
```
![image](https://cloud.githubusercontent.com/assets/873919/20067194/3f813cc8-a525-11e6-8b47-0686a16c27c6.png)

VS 15 Preview 5

**Comment by forki** [comment]
I think this should definitely be revisited before the release.  I assume no. 1 user of the rec module feature will be fable. And I think this could bring serious trouble

**Comment by dsyme** [comment]
I'm not sure what the issue is yet, I'll take a look.  Note that you can use this formulation, indeed this would likely be more normal.

```fsharp

namespace rec Whatever // or "namespace rec global" or "module rec Whatever"

type R = A | B

module R = begin end
```
