### ISSUE TITLE
FS0084 During clean build

### ISSUE THREAD

**Issue by destroyhimmyrobots** [Microsoft/visualfsharp#1739]
Assemblies fail to load when running `.\build.cmd`. Seems similar to #1100.

#### Repro steps

Provide the steps required to reproduce the problem

1. Clone `Microsoft/visualfsharp`
2. `.\build.cmd proto` (this should be added to the build steps documentation, since it does not seem to run from step #3).
3. `.\build.cmd`
2. Open solution in VS Enterprise vNext
3. Type `F7` to build

#### Expected behavior

The build is successful.

#### Actual behavior

A number of errors occur: [full build log](https://github.com/Microsoft/visualfsharp/files/588370/vfs-log.txt)

**Comment by dsyme** [comment]
@destroyhimmyrobots This should be fixed by #1732, please give it a try.  

You now open ``FSharp.sln`` if you are only interested in the F# compiler rather than the Visual F# IDE Tools.

As far as I can see ``build.cmd proto`` shouldn't be necessary if you do a ``build.cmd``

**Comment by dsyme** [comment]
Closing as I believe this is fixed, please verify

**Comment by destroyhimmyrobots** [comment]
@dsyme confirmed! Thank you for the swift patch.
