### ISSUE TITLE
Migrate internal localization strings to use the Multilingual App Toolkit (MAP).

### ISSUE THREAD

**Issue by brettfo** [Microsoft/visualfsharp#1745]
This will enable us to remove our internal mirror of this repo that exists only to house the proprietary localization work.

[Multilingual App Toolkit](https://developer.microsoft.com/en-us/windows/develop/multilingual-app-toolkit).

**Comment by dsyme** [comment]
@brettfo @cartermp Please add a milestone?  Just trying to gauge the severity of this

**Comment by cartermp** [comment]
Personally I don't think it's too severe (hence the vFuture [side note: I couldn't click the right thing to save my life...]), but if @brettfo has the time to address this as a part of making setup awesome, then that's always great.

**Comment by brettfo** [comment]
I'm OK with leaving this in vFuture for now, but I would like to start working on this as soon as VS2017 RTM ships, because this makes a lot of internal infrastructure and process go away and is a prerequisite to batch-signing our binaries which will bring our fully signed build down from 3 hours to 1.5.

**Comment by cartermp** [comment]
Hmm, in that case I'll just move it to VS 2017 Updates.  We can always just adjust it later.

**Comment by dsyme** [comment]
> because this makes a lot of internal infrastructure and process go away 
> and is a prerequisite to batch-signing our binaries which will bring our 
> fully signed build down from 3 hours to 1.5.

That would be a huge win!  Any complexity reduction we can do will pay off in the long term

**Comment by cartermp** [comment]
@brettfo can this be closed?
