### ISSUE TITLE
Warning FS0082 in tests net40-fsharp causes errors in optimize\tests_optimize.fs

### ISSUE THREAD

**Issue by destroyhimmyrobots** [Microsoft/visualfsharp#1746]
On an Intel x64 machine, a warning related to a mismatch between the architecture of some DLLs and the "project being build" appears during the testing phase of `.\build.cmd`. It seems reasonable to have the build script use the current machine's architecture by default, if that is at all related to this issue.

For example, this error appears for `System.Data.dll` `System.Web.dll` and `mscorlib.dll`:

    There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "mscorlib.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. (Code=MSB3270)";

As a consequence, tests that depend on output generated by (what appear to be) generated test programs fail. For example, here's the contents of the files `effects.HasEffect.output.test.bsl` and `effects.HasEffect.output.test.txt`, affected by the `FS0082` error:

    PS C:\Users\s\Source\github.com\microsoft\fsharp\visualfsharp\tests\fsharp\optimize\analyses> head .\effects.HasEffect.output.test.bsl
    function constantUnit at line 5 causes no side effects
    function constantInteger at line 6 causes no side effects
    function constantValue at line 7 causes no side effects
    function fieldLookup1 at line 8 causes side effects or may not terminate
    function libraryCall1 at line 9 causes side effects or may not terminate
    function libraryCall2 at line 10 causes side effects or may not terminate
    function constantData1 at line 11 causes no side effects
    function constantData2 at line 12 causes no side effects
    function constantTuple1 at line 13 causes no side effects
    function constantTuple2 at line 14 causes no side effects

    PS C:\Users\s\Source\github.com\microsoft\fsharp\visualfsharp\tests\fsharp\optimize\analyses> head .\effects.HasEffect.output.test.txt

    warning FS0082: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "mscorlib.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. (Code=MSB3270)

#### Repro steps

Provide the steps required to reproduce the problem

1. Clone VF#
2. `.\build.cmd`
3. `.\build.cmd test`

#### Expected behavior

The tests pass.

#### Actual behavior

The tests display architecture warnings for several DLLs: [partial test log](https://github.com/Microsoft/visualfsharp/files/593853/vfs-log-82.txt).

#### Attempted workaround

Adding an x64 platform to the solution and then running the following does not change the test output.

    .\build.cmd clean
    .\build.cmd
    .\build.cmd test

#### Related information 

The default settings of `FSharp.sln` appear to use x86 as the default architecture. Here's a screenshot, which has the same values for `Debug`, `Proto` and `Release`:

![vfs-confmgr](https://cloud.githubusercontent.com/assets/4496122/20336679/2bc8b71c-ab9a-11e6-9bff-4a48ad96a9e3.png)

**Comment by dsyme** [comment]
I've never seen this problem, and I work on an x64 platform all the time. 

I think we can close it because no one else has reported the problem.

@destroyhimmyrobots please reopen if you see this again?

thanks
