### ISSUE TITLE
Go to definition works in a strange way

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1752]
VS 2017 RC:

![image](https://cloud.githubusercontent.com/assets/873919/20362586/33f27d70-ac4d-11e6-9ff4-f7e16a1f9a21.png)

F12 does not jump to the definition, but shows the definition location in a tool window.

**Comment by dsyme** [comment]
@OmarTawfik @brettfo Can you take a look please? thanks

**Comment by dsyme** [comment]
@vladima Any pointers on this?  If you review our GotoDefinition code you might spot the mistake? https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/GoToDefinitionService.fs

**Comment by vladima** [comment]
I think that code of `TryGotoDefinition` in `FSharpGoToDefinitionService` should be something like this:

```F#
        member this.TryGoToDefinition(document: Document, position: int, cancellationToken: CancellationToken) =
            let definitionTask = this.FindDefinitionsAsyncAux(document, position, cancellationToken)
            
            // REVIEW: document this use of a blocking wait on the cancellation token, explaining why it is ok
            definitionTask.Wait(cancellationToken)
            
            if definitionTask.Status = TaskStatus.RanToCompletion && definitionTask.Result.Any() then
                let navigableItem = definitionTask.Result.First() // F# API provides only one INavigableItem
                let workspace = document.Project.Solution.Workspace
                let navigationService = workspace.Services.GetService<IDocumentNavigationService>()
                navigationService.TryNavigateToSpan(workspace, navigableItem.Document.Id, navigableItem.SourceSpan)
            else
                false
```

Reasoning: if GotoDef returns one result then it should try to jump to a discovered location. If it returns multiple results then it should use `presenters` to render items so user can choose whatever he needs. Given that per comment F# API always returns only one item then we should always navigate to definition and get rid of presenters.

**Comment by dsyme** [comment]
Thanks so much @vladima that works perfectly

Fix ready at https://github.com/Microsoft/visualfsharp/pull/1836
