### ISSUE TITLE
Open an .fs file in Dev 15 RC and it is not colourized

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1756]
F# colourization works great when editing a file that is part of an F# project, but a loose .fs file does not get colourized.

Expected VS editor to edit loose F# files with full colorization etc ...

![untitled](https://cloud.githubusercontent.com/assets/5175830/20372226/7536eaac-ac1e-11e6-88d3-82372d7a5cac.png)

**Comment by dsyme** [comment]
@brettfo I've fixed this here: https://github.com/Microsoft/visualfsharp/pull/1819
