### ISSUE TITLE
Type Providers are broken in the editor, even though they will execute just fine.

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1758]
1. Install VS 2017 RC1 Community on a clean machine.
2. Install .NET Desktop workload.
3. Install the FSharp.Data package.
4. Enter the following code in the editor:

```fsharp
open FSharp.Data

type JsonContext = JsonProvider<""" { "name":"John", "age":94 } """>

let json = JsonContext.Parse(""" { "name":"John", "age":94 } """)

[<EntryPoint>]
let main argv = 
    printfn "Age: %d.  Name: %s" json.Age json.Name
    printfn "%A" argv
    0 // return an integer exit code

```

Expected: No red squiggles and IntelliSense when "dotting" into `json`.

Actual:

![tp-appears-broken](https://cloud.githubusercontent.com/assets/6309070/20375261/ec3ef234-ac32-11e6-8336-ef22f56f2d7d.PNG)

**Comment by dsyme** [comment]
I had thought this might be a binding redirect problem for FSHarp.Core but it looks like it isn't, as this appears OK in my ``C:\Users\dsyme\AppData\Local\Microsoft\VisualStudio\15.0_7c5620b7FSharpDev\devenv.exe.config``


```
			<dependentAssembly>
				<assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
				<bindingRedirect oldVersion="2.0.0.0-4.4.0.0" newVersion="4.4.1.0"/>
			</dependentAssembly>

```
