### ISSUE TITLE
Build Cannot Copy License File

### ISSUE THREAD

**Issue by destroyhimmyrobots** [Microsoft/visualfsharp#1759]
Running `.\build.cmd all` attempts to copy `License.txt` from `VisualFSharpOpenSource.csproj` to an incorrect path name.

The relevant lines in `VisualFSharpOpenSource.csproj` appear to be https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/Vsix/VisualFSharpOpenSource/VisualFSharpOpenSource.csproj#L80:

    <Content Include="$(FSharpSourcesRoot)\..\License.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>

For some reason, the *absolute path* to the license `C:\dev\src\github.com\microsoft\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\..\..\..\src\..\` is included in the destination path to which the license is to be copied.

#### Repro steps

1. Clone
2. `.\build.cmd all`

#### Actual behavior

    "C:\dev\src\github.com\microsoft\visualfsharp\build-everything.proj" (default target) (1) ->
    "C:\dev\src\github.com\microsoft\visualfsharp\vsintegration\fsharp-vsintegration-vsix-build.proj" (Build target) (34) ->
    "C:\dev\src\github.com\microsoft\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj" (Build target) (38) ->
    (DeployVsixExtensionFiles target) ->
    C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(654,5): error MSB3021: Unable to copy file "C:\dev\src\github
    .com\microsoft\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\..\..\..\src\..\License.txt" to "C:\Users\s\AppData\Local\Microsoft\VisualStudio\15.0_1a0d62d2FSharpDev\Extensions\Micr
    osoft.VisualFSharpTools\Visual F# Tools\15.4.1.9055\C:\dev\src\github.com\microsoft\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\..\..\..\src\..\\License.txt". The given path's fo
    rmat is not supported. [C:\dev\src\github.com\microsoft\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]

**Comment by cloudRoutine** [comment]
I ran into this too

![](http://i.imgur.com/PeccNt1.png)

![](http://i.imgur.com/CXk2pBI.png)

**Comment by destroyhimmyrobots** [comment]
`git pull` seems to have fixed this for me.
