### ISSUE TITLE
F# Source File has a duplicate in Add New Item

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1762]
See this tweet: https://twitter.com/Bizmonger/status/799276211151183872

I haven't been able to repro on my own machine.

**Comment by cartermp** [comment]
Closing this for now, since I haven't been able to reproduce this in a month.

**Comment by vdanche** [comment]
@cartermp we still can repro on VS 17.10 preview 2.
the related bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1364213
