### ISSUE TITLE
"Preview selected item" does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1763]
VS 2017 RC:

![image](https://cloud.githubusercontent.com/assets/873919/20400655/a727b008-ad06-11e6-89da-c8be96d4d776.png)

Single clicking on files in Solution Explorer should open them on "preview" panel. It works in VS 2015 and it does work for C# files in VS 2017 RC:

![1](https://cloud.githubusercontent.com/assets/873919/20400778/2e680806-ad07-11e6-8890-56a65600e690.gif)

**Comment by cartermp** [comment]
@KevinRansom @Pilchie is preview behavior something that `fsproj` handles, or is it a VS thing?

**Comment by vasily-kirichenko** [comment]
It affects the behavior of "Go to all" ("Navigate to" previously): 

![1](https://cloud.githubusercontent.com/assets/873919/20401328/71e84c9c-ad09-11e6-89ec-29b18ebb90d4.gif)

**Comment by Pilchie** [comment]
I believe the solution explorer infrastructure handles it, but content types/file extensions can opt-in/opt-out of it.  Looks like F# is no longer opting into it since the switch?

**Comment by saul** [comment]
@Pilchie I can't seem to find anything in the Roslyn code besides this (and some stub/interface implementations):
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/NavigateTo/VisualStudioNavigateToPreviewService.cs,f8d5dff8e6168697

Do you have any idea if there's something missing VS-side in the Solution Explorer for this? Specifically it looks like in the SolutionExplorerShim there's a property on BaseItem named CanPreview.

**Comment by Pilchie** [comment]
I believe there is some property on the content type registration that indicates whether it supports previewing or not.  @jasonmalinowski or @dpoeschl, do you know what it is?

**Comment by dpoeschl** [comment]
@MTBandolier - I was referred to you for this question. How do we get documents of the F# content type to show in the preview tab when single clicked in solution explorer? I looked to see how we're doing it for C#/VB, but I haven't been able to figure it out. If you're not the right person to ask, do you know who might be?

**Comment by saul** [comment]
@dpoeschl, @Pilchie - any update on this? @MTBandolier doesn't appear active on GH whatsoever so I wouldn't wait for a reply from him here.

**Comment by dpoeschl** [comment]
@saul Thanks for mentioning it. I've sent him an email directly now. One of us will update this thread when we have some sort of answer.

**Comment by dpoeschl** [comment]
Some comments from Jeff:

Previewing in Solution Explorer is controlled by the registration of the editor that owns the file type.  Check out this post:  https://social.msdn.microsoft.com/Forums/en-US/dea6c30a-dc1f-45da-9f0f-5e7f0ded4ce4/cannot-get-custom-editor-to-use-the-provisional-tab?forum=vsx

/cc: @saul @KevinRansom @brettfo @Pilchie

**Comment by saul** [comment]
I've tried:

```c#
    [ProvideEditorFactory(typeof(FSharpEditorFactory), 101, CommonPhysicalViewAttributes=(int)__VSPHYSICALVIEWATTRIBUTES.PVA_SupportsPreview)]
```

To no avail :(

**Comment by MTBandolier** [comment]
You can enable some logging that will give you more information about the previewing process:

### Enable Tracing
1.	Close all instances of VS
2.	Start regedit
3.	Select the HKLM node
4.	File > Load Hive….  Locate privateregistry.bin under %LocalAppData%\Microsoft\VisualStudio for the instance of VS that you want to inspect.
5.	You’ll be prompted for a key name.  Pick something like “junk”.
6.	Navigate to HKLM\junk\Software\Microsoft\VisualStudio\{regroot}\General.  _{regroot}_ is the node that doesn’t have the “_Config” or “_Remote” suffix.
7.	Add a REG_DWORD value named “TraceProvisionalViewingInfo” and give it a value of 1.
8.	Select HKLM\junk
9.	File > Unload Hive

### Try to Preview Your File
1.	Start one instance of VS (the debugger)
2.	Start another instance of VS (the debuggee)
3.	In the debugger, click Debug > Attach to Process and attach to the debuggee.  Select the “Native” and “Managed (v4.6, v4.5, and v4.0)” code types.
4.	Once the debugger is fully attached, try previewing your file in the debuggee.  You should see tracing information similar to this in the debugger’s Output window:

```
GetProvisionalViewingStatusForFile: %UserProfile%\Documents\Visual Studio 2017\Projects\WpfApp1\WpfApp1\MainWindow.xaml
    logview = LOGVIEWID_Primary
    editor  = {32CC8DFA-2D70-49B2-94CD-22D57349B778} (Automatic Editor Selector (XML)) delegates to
              {F11ACC28-31D1-4C80-A34B-F4E09D3D753C} (XAML Designer)
    size    = 501
    maxsize = 2097152
    status  = enabled, slow
GetProvisionalViewingStatusForFile: %UserProfile%\Documents\Visual Studio 2017\Projects\WpfApp1\WpfApp1\MainWindow.xaml.cs
    logview = LOGVIEWID_Primary
    editor  = {A6C744A8-0E4A-4FC6-886A-064283054674} (CSharp Editor)
    size    = 659
    maxsize = 2097152
    status  = enabled
```

In Solution Explorer, you should see previews of files whose status is “enabled”, but not “disabled” or “enabled, slow.”

### Disable Tracing
Follow the steps in “Enable Tracing” and remove the “TraceProvisionalViewingInfo” value (or set it to 0).

**Comment by saul** [comment]
Thanks @MTBandolier - that's helping to trace the issue. Here is some output after attempting to preview two files:
```
GetProvisionalViewingStatusForFile: C:\Code\visualfsharp\src\fsharp\FSharp.Build\Fsc.fs
    logview = LOGVIEWID_Primary
    editor  = {4EB7CCB7-4336-4FFD-B12B-396E9FD079A9} ((null))
    size    = 25161
    maxsize = 2097152
    status  = disabled
GetProvisionalViewingStatusForFile: C:\Code\visualfsharp\src\fsharp\FSharp.Build\Fsc.fsi
    logview = LOGVIEWID_Primary
    editor  = {4EB7CCB7-4336-4FFD-B12B-396E9FD079A9} ((null))
    size    = 3509
    maxsize = 2097152
    status  = disabled
```

Any ideas @dpoeschl / @Pilchie?

**Comment by vasily-kirichenko** [comment]
OK, I've found why previewing was not supported, see this PR https://github.com/Microsoft/visualfsharp/pull/2417 for further discussion.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2417
