### ISSUE TITLE
There is no "Execute / Debug in interactive" commands

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1764]
VS 2015:

![image](https://cloud.githubusercontent.com/assets/873919/20401591/80524930-ad0a-11e6-8c66-766db602a164.png)

VS 2017 RC:

![image](https://cloud.githubusercontent.com/assets/873919/20401638/ab76099e-ad0a-11e6-9d3e-c45c202944c7.png)

**Comment by cartermp** [comment]
Closing as duplicate of #1633
