### ISSUE TITLE
Method Overloads are not propagating in IntelliSense

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1765]
In VS RC1 with F# installed, type the following in a console app:

```fsharp
open System

[<EntryPoint>]
let main argv = 
    Console.WriteLine(
    0 // return an integer exit code
```

Note that the overloads for `WiteLine` do not show up in IntelliSense:

![no-method-overloads](https://cloud.githubusercontent.com/assets/6309070/20402500/d389a96c-acb1-11e6-8ce9-9a2439f817c0.PNG)

**Comment by dsyme** [comment]
Seems the same as #1766
