### ISSUE TITLE
Cannot find the request resource: '300' after closing Add File dialog

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1768]
1. Create an F# console app.
2. Right-click > Add File.
3. Close the dialog.

![resource-300](https://cloud.githubusercontent.com/assets/6309070/20404107/55abdd4c-acb8-11e6-9700-28ff21fa4246.PNG)

**Comment by cartermp** [comment]
@KevinRansom @Pilchie is this something we control with fsproj, or is it part of VS?

**Comment by KevinRansom** [comment]
That's a bug and we should investigate and fix it.
