### ISSUE TITLE
Adding a new file to existing project crashes VS

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1769]
1. Create an F# console app
2. Right Click > Add File
3. Wait for a few seconds.

VS will crash and restart.

**Comment by vasily-kirichenko** [comment]
I can reproduce it reliably in VS 2017 RC.

**Comment by cartermp** [comment]
Note @brettfo there is another bug is VSTS about renaming a file and having it crash.  That might be related to this.
