### ISSUE TITLE
Perhaps ... we should allow scripts to be signed so that an OS Administrator can lock down the machine.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1774]
Java script and Powershell have a notion of signed scripts that can be run in a locked-down mode.  For security conscious individuals fsi gives the possibility of downloading the scripting engine and scripts, giving access to a wide range of functionality that an administrator may want to disable.

**Comment by dsyme** [comment]
Closing suggestion - please add to fslang suggestions?
