### ISSUE TITLE
Incorrect resolution when consuming extension method overloads with optional parameters

### ISSUE THREAD

**Issue by neoeinstein** [Microsoft/visualfsharp#1777]
In Serilog, sink configuration often uses two overloads, one which has only optional parameters, and one which takes a formatter and the same set of optional parameters. The second overload cannot be resolved in F#. In Serilog's case, it effectively means that you cannot use a non-default formatter for any sink.

```csharp
public static LoggerConfiguration Console(
    this LoggerSinkConfiguration sinkConfiguration,
    LogEventLevel restrictedToMinimumLevel = LevelAlias.Minimum,
    string outputTemplate = DefaultConsoleOutputTemplate,
    IFormatProvider formatProvider = null,
    LoggingLevelSwitch levelSwitch = null,
    LogEventLevel? standardErrorFromLevel = null)

public static LoggerConfiguration Console(
    this LoggerSinkConfiguration sinkConfiguration,
    ITextFormatter formatter,
    LogEventLevel restrictedToMinimumLevel = LevelAlias.Minimum,
    LoggingLevelSwitch levelSwitch = null,
    LogEventLevel? standardErrorFromLevel = null)
```

#### Repro steps

```fsharp
#r "Serilog.dll"
#r "Serilog.Sinks.Console.dll"

open Serilog
open Serilog.Formatting.Json

let lc = LoggerConfiguration().WriteTo.Console(JsonFormatter())
```

#### Expected behavior

That this compiles and resolves to the second overload.

#### Actual behavior

Compilation Error:

```
error FS0001: This expression was expected to have type
    Events.LogEventLevel
but here has type
    JsonFormatter
``` 

#### Known workarounds

None

#### Related information 

Tested with F# 4.0 on the .NET Framework and the alpha F# 4.1 compiler on .NET Core 1.0.
Serilog: 2.0.0
Serilog.Sinks.Console: 2.0.0

**Comment by kurtschelfthout** [comment]
Are you sure you are not just confused with Serilog versions? I think the overload with formatter was only added in Serilog 2.1.0, and the code works with that version.

**Comment by dsyme** [comment]
@neoeinstein Can you verify that this overload exists in the version you mention please? thank you

**Comment by neoeinstein** [comment]
@kurtschelfthout You are correct. I was at first attempting to use the LiterateConsole, which has the overload in source, but the versions released so far do not have the overload. I was able to find the overload in the Console sink, and when I referenced 2.1.0 of `Serilog.Sinks.Console`, the compiler was able to bind correctly.

I'm closing this issue.
