### ISSUE TITLE
Add release notes to the repo

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#178]
Do you think it would be a good idea to commit the release notes directly into the repo? We use markdown for this in all projectscaffold-like projects and I really like it. See https://github.com/fsprojects/Paket/blob/master/RELEASE_NOTES.md

**Comment by latkin** [comment]
Like this? https://github.com/Microsoft/visualfsharp/blob/fsharp4/changelist.txt We could convert it to markdown I suppose (I think it's already pretty close, just saved as .txt)

**Comment by forki** [comment]
![blind](https://cloud.githubusercontent.com/assets/57396/5973039/b1e9f4d2-a863-11e4-9168-d3a5cbd3514d.gif)

sorry I forgot about this one.

But converting to markdown and adding links to the issues would be nice addition.
