### ISSUE TITLE
Cannot build VSIX

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1782]
VS 2017 RC, current master:
> $ build.cmd vs
......
CreateVsixContainer:
  Creating VSIX Container...
  Creating the package with the following compression level. "Normal".
  VisualFSharpOpenSource -> D:\github\visualfsharp\release\net40\bin\VisualFSharpOpenSource.vsix
D:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(602,5): error M SB4018: The "GetExtensionsPath" task failed unexpectedly.\r [D:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource \VisualFSharpOpenSource.csproj]
D:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(602,5): error M SB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Settings.15.0, Version=15.0. 0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. \r [D:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
D:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(602,5): error M SB4018: File name: 'Microsoft.VisualStudio.Settings.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' \r [D:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
D:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(602,5): error M SB4018:    at Microsoft.VsSDK.Build.Tasks.GetExtensionsPath.Execute()\r [D:\github\visualfsharp\vsintegration\Vsix\VisualFSha rpOpenSource\VisualFSharpOpenSource.csproj]
D:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(602,5): error M SB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r [D:\github\vis ualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
D:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(602,5): error M SB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()\r [D:\github\visualfsharp\vsinteg ration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
D:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(602,5): error M SB4018: \r [D:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
D:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(602,5): error M SB4018: WRN: Assembly binding logging is turned OFF.\r [D:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\Visu alFSharpOpenSource.csproj]
D:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(602,5): error M SB4018: To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to  1.\r [D:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
D:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(602,5): error M SB4018: Note: There is some performance penalty associated with assembly bind failure logging.\r [D:\github\visualfsharp\vsin tegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
D:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(602,5): error M SB4018: To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r [D:\github\visualfs harp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
D:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(602,5): error M SB4018:  [D:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
Done Building Project "D:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj" (Build  target(s)) -- FAILED.
```

**Comment by KevinRansom** [comment]
Hi, 
when you installed VS2017 RC which options did you specify?
These are the options II select
* .Net desktop development                 + .Net Framework 4.6.2 development tools
* Desktop development with C++        + Windows 10 SDK (10.0.1439.0)
* Visual Studio extension development

Kevin

**Comment by KevinRansom** [comment]
vsix build requires VS 2017 RC and VSSDK to build.  I added a check for this to the build.cmd file.

Kevin

**Comment by vasily-kirichenko** [comment]
Same error on current master :(

**Comment by vasily-kirichenko** [comment]
Fixed in RC2.
