### ISSUE TITLE
"Comment Selection" command does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1785]
VS 2017 RC.

![1](https://cloud.githubusercontent.com/assets/873919/20462405/53b9bb26-af2e-11e6-8b1f-220789c906fe.gif)

**Comment by dsyme** [comment]
I tried to fix this by using the following but I got a "component composition" error

I can't find any documentation for MEF component composition and all these attributes.  Anyone know what I'm doing wrong?

```
[<ExportCommandHandler("BlockCommentEditingCommandHandler", FSharpCommonConstants.FSharpContentTypeName)>]
[<Order(After = PredefinedCommandHandlerNames.Completion)>]
type internal BlockCommentEditingCommandHandler [<ImportingConstructor>] (undoHistoryRegistry: ITextUndoHistoryRegistry, editorOperationsFactoryService: IEditorOperationsFactoryService) =
    inherit AbstractBlockCommentEditingCommandHandler(undoHistoryRegistry, editorOperationsFactoryService)

    override __.GetExteriorTextForNextLine(_caretPosition:SnapshotPoint) = "//"
```

**Comment by vasily-kirichenko** [comment]
@dsyme looks exactly the same as http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp.EditorFeatures/BlockCommentEditing/BlockCommentEditingCommandHandler.cs
I will try to reproduce your error.

**Comment by vasily-kirichenko** [comment]
I did this change https://github.com/vasily-kirichenko/visualfsharp/commit/bec14f695ea038cfd572ba4aeea0b857b42cfea9

No errors, but it does not work (however, it does not show 
![image](https://cloud.githubusercontent.com/assets/873919/20607456/7a591d54-b289-11e6-8e59-a428146932d3.png)
as before).

**Comment by vladima** [comment]
in TypeScript instead of deriving from `AbstractBlockCommentEditingCommandHandler` we expose implementation of [ICommentUncommentService](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/CommentSelection/ICommentUncommentService.cs,834c1b6b76ee2b11)  which looks roughly like this:

```f#
open Microsoft.CodeAnalysis.Editor.Implementation.CommentSelection

[<Shared>]
[<ExportLanguageService(typeof<ICommentUncommentService>, FSharpCommonConstants.FSharpLanguageName)>]
type CommentUncommentService() =
    interface ICommentUncommentService with
        member this.SingleLineCommentString = "//"
        member this.SupportsBlockComment = true
        member this.BlockCommentStartString = "(*"
        member this.BlockCommentEndString = "*)"
        member this.Format(document, _changes, _cancellationToken) = document
```

**Comment by vasily-kirichenko** [comment]
@vladima I've tested your code, it works! :) 👍
