### ISSUE TITLE
.NET Framework 4.5.2 is the default for new F# projects in VS 2017

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1787]
![image](https://cloud.githubusercontent.com/assets/873919/20462466/7d868b0e-af2f-11e6-87f0-8daffc049605.png)

Even though more recent versions are installed:

![image](https://cloud.githubusercontent.com/assets/873919/20462471/9a35279c-af2f-11e6-8f19-7937ad134ddb.png)

**Comment by forki** [comment]
Is that good or bad? What do you think it should be?

**Comment by vasily-kirichenko** [comment]
It should select the most recent version. I cannot reproduce it anymore. It seems to depend on target versions set in current solution's projects. Closing it.

**Comment by Pilchie** [comment]
On a fresh machine it still picks 4.5.2 (though I think we plan to update to 4.6.1 based on the number of deployments out there).

After that, it remembers the last choice and re-applies that.
