### ISSUE TITLE
Can't debug FSI in VS2015 anymore

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1788]
* Clone lastest master
* run build.cmd in VS2015 developer promt in admin mode
* open VS2015
* Right click on FSIAnyCPU and start debug.

![image](https://cloud.githubusercontent.com/assets/57396/20462592/446619dc-af22-11e6-986b-a8d0be49b458.png)

**Comment by dsyme** [comment]
@forki I think you need to do ``build debug``
