### ISSUE TITLE
Squiggles color for warnings has changes from blue to green in VS 2017

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1789]
![image](https://cloud.githubusercontent.com/assets/873919/20462819/82e2e68a-af37-11e6-8c44-b0da1bd351fc.png)

Maybe it's not a bug and it's consistent with the rest of VS now?

**Comment by KevinRansom** [comment]
@vasily-kirichenko 
C# uses green.

![untitled](https://cloud.githubusercontent.com/assets/5175830/20465850/27631660-af1c-11e6-9e59-bc58399494c9.png)

Kevin
