### ISSUE TITLE
.NetCore on Linux (Mint 18/Ubuntu 16.04) fails to compile just created F# project

### ISSUE THREAD

**Issue by palutz** [Microsoft/visualfsharp#1791]
Hi,
trying to play a bit with F# and .NetCore (1.1). I've read F# is supported so I was trying it but with no luck.
This is my system:

> $ cat /proc/version
> Linux version 4.4.0-36-generic (buildd@lcy01-01) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016

and 

> $ dotnet --version
> 1.0.0-preview2-1-003177

I create my new app like this:

1. Create the F# project
> $ dotnet new -l F#
2. Restore
> $ dotnet restore
> log  : Restoring packages for /home/palutz/Project/fsharp/core1/project.json...
> log  : Restoring packages for tool 'dotnet-compile-fsc' in /home/palutz/Project/fsharp/core1/project.json...
> log  : Writing lock file to disk. Path: /home/palutz/Project/fsharp/core1/project.lock.json
> log  : /home/palutz/Project/fsharp/core1/project.json
> log  : Restore completed in 2090ms.
> 

but when I try to run it (without any modification, just to see the classic "Hello World") I got this:
3. Compile and Run
> $ dotnet run
> Project core1 (.NETCoreApp,Version=v1.1) will be compiled because expected outputs are missing
> Compiling core1 for .NETCoreApp,Version=v1.1
> The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
>   - Check application dependencies and target a framework version installed at:
>       /usr/share/dotnet/shared/Microsoft.NETCore.App
>   - The following versions are installed:
>       1.1.0
>   - Alternatively, install the framework version '1.0.0'.
> /usr/share/dotnet/dotnet compile-fsc @/home/palutz/Project/fsharp/core1/obj/Debug/netcoreapp1.1/dotnet-compile.rsp returned Exit Code 131
> 
> Compilation failed.
>     0 Warning(s)
>     0 Error(s)
> 
> Time elapsed 00:00:00.3389032
> 

Any suggestion how to solve this?

Thanks.

#### Expected behavior

I was expecting a simple compilation and the classic "Hello World" output

#### Actual behavior

look at the point 3)

#### Known workarounds
....

#### Related information 

Provide any related information 

* Operating system
Linux Mint 18 (Ubuntu 16.04)
Linux version 4.4.0-36-generic (buildd@lcy01-01) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016
* .NET Runtime, CoreCLR or Mono Version
Brand new, just installed, .Net core 1.1
1.0.0-preview2-1-003177
* Editing Tools (e.g. Visual Studio Version)
Vs Code (and Vim :) )
* Links to F# RFCs or entries on http://fslang.uservoice.com
* Links to performance testing scripts
* Indications of severity

**Comment by palutz** [comment]
Just a couple more tests:
- same problem in Mac OsX 10.10
- same problem in Windows Linux subsystem (Windows 10 64bit, Linux version 3.4.0-Microsoft (Microsoft@Microsoft.com) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Wed Dec 31 14:42:53 PST 2014)

Instead works on WIndows 10 (same version of all the other systems: 1.0.0-preview2-1-003177 ).

**Comment by KevinRansom** [comment]
@enricosada 
Hey buddy, I think this is using you dotnet.exe integration stuff.

Kevin

**Comment by PatrickMcDonald** [comment]
I just tried this on macOS 10.12.1 and the fresh project compiled for me

```
MBA: ~/Projects/dotnet                                                                                          ▸▸▸▸▸▹▹▹▹▹
 → mkdir hellofs

MBA: ~/Projects/dotnet                                                                                          ▸▸▸▸▸▹▹▹▹▹
 → cd hellofs 

MBA: ~/Projects/dotnet/hellofs                                                                                  ▸▸▸▸▸▹▹▹▹▹
 → dotnet --version
1.0.0-preview2-1-003177

MBA: ~/Projects/dotnet/hellofs                                                                                  ▸▸▸▸▸▹▹▹▹▹
 → dotnet new -l F#

Welcome to .NET Core!
---------------------
Learn more about .NET Core @ https://aka.ms/dotnet-docs. Use dotnet --help to see available commands or go to https://aka.ms/dotnet-cli-docs.
Telemetry
--------------
The .NET Core tools collect usage data in order to improve your experience. The data is anonymous and does not include commandline arguments. The data is collected by Microsoft and shared with the community.
You can opt out of telemetry by setting a DOTNET_CLI_TELEMETRY_OPTOUT environment variable to 1 using your favorite shell.
You can read more about .NET Core tools telemetry @ https://aka.ms/dotnet-cli-telemetry.
Configuring...
-------------------
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 3158 ms
Expanding 100% 8372 ms
Created new F# project in /Users/Patrick/Projects/dotnet/hellofs.

MBA: ~/Projects/dotnet/hellofs                                                                                  ▸▸▸▸▸▹▹▹▹▹
 → dotnet restore
log  : Restoring packages for /Users/Patrick/Projects/dotnet/hellofs/project.json...
log  : Installing Microsoft.FSharp.Core.netcore 1.0.0-alpha-160629.
log  : Restoring packages for tool 'dotnet-compile-fsc' in /Users/Patrick/Projects/dotnet/hellofs/project.json...
log  : Installing NuGet.Configuration 3.5.0-beta2-1484.
log  : Installing NuGet.Protocol.Core.Types 3.5.0-beta2-1484.
log  : Installing NuGet.Protocol.Core.v3 3.5.0-beta2-1484.
log  : Installing NuGet.Repositories 3.5.0-beta2-1484.
log  : Installing NuGet.LibraryModel 3.5.0-beta2-1484.
log  : Installing NuGet.Packaging.Core.Types 3.5.0-beta2-1484.
log  : Installing System.Globalization 4.0.0.
log  : Installing dotnet-compile-fsc 1.0.0-preview2-020000.
log  : Installing Microsoft.DotNet.Compiler.Common 1.0.0-preview2-003121.
log  : Installing Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121.
log  : Installing Microsoft.DotNet.Cli.Utils 1.0.0-preview2-003121.
log  : Installing NuGet.DependencyResolver.Core 3.5.0-beta2-1484.
log  : Installing Microsoft.FSharp.Compiler.netcore 1.0.0-alpha-160629.
log  : Installing Newtonsoft.Json 6.0.4.
log  : Installing Microsoft.DotNet.Files 1.0.0-preview2-003121.
log  : Installing NuGet.RuntimeModel 3.5.0-beta2-1484.
log  : Installing Microsoft.Extensions.DependencyModel 1.0.0.
log  : Installing System.Runtime.Serialization.Primitives 4.1.1.
log  : Installing NuGet.Packaging.Core 3.5.0-beta2-1484.
log  : Installing NuGet.Packaging 3.5.0-beta2-1484.
log  : Installing Newtonsoft.Json 9.0.1.
log  : Installing NuGet.Common 3.5.0-beta2-1484.
log  : Installing NuGet.Versioning 3.5.0-beta2-1484.
log  : Installing Microsoft.DotNet.InternalAbstractions 1.0.0.
log  : Installing Microsoft.DiaSymReader.PortablePdb 1.1.0.
log  : Installing System.Reflection.Metadata 1.4.1-beta-24227-04.
log  : Installing NuGet.Frameworks 3.5.0-beta2-1484.
log  : Installing NuGet.ProjectModel 3.5.0-beta2-1484.
log  : Installing Microsoft.DiaSymReader 1.0.8.
log  : Installing System.Diagnostics.TraceSource 4.0.0.
log  : Writing lock file to disk. Path: /Users/Patrick/Projects/dotnet/hellofs/project.lock.json
log  : /Users/Patrick/Projects/dotnet/hellofs/project.json
log  : Restore completed in 21274ms.

MBA: ~/Projects/dotnet/hellofs                                                                                  ▸▸▸▸▸▹▹▹▹▹
 → dotnet run
Project hellofs (.NETCoreApp,Version=v1.1) will be compiled because expected outputs are missing
Compiling hellofs for .NETCoreApp,Version=v1.1

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:06.5901725
 

Hello World!
```

**Comment by enricosada** [comment]
@KevinRansom yes, i am tracking that in https://github.com/dotnet/netcorecli-fsc/issues/42 , i'll fix it tomorrow, already tried locally the fix (no changes in templates needed 😄 )

**Comment by palutz** [comment]
@enricosada thanks. Looking forward to it. I close it.

**Comment by jpmoraez** [comment]
@PatrickMcDonald I've followed the same steps on a Mac 10.12.1 (.net 1.0.0-preview2-1-003177) and got this issue :/

**Comment by enricosada** [comment]
yes, doesnt work yet.  
@jpmoraez i'll update dotnet/netcorecli-fsc#42 when fix is ready.

**Comment by PatrickMcDonald** [comment]
@jpmoraez I think maybe mine worked because I had also installed .NET Core 1.0.1
