### ISSUE TITLE
Make F#'s Alt-Enter keybinding local to F# files only

### ISSUE THREAD

**Issue by JoshVarty** [Microsoft/visualfsharp#1797]
Currently F# registers it's Alt-Enter keybinding in the context of all text editors regardless of the language. From [source](https://github.com/Microsoft/visualfsharp/blob/6afc4f9776a5dba903ca6b11965a206fb8bc23d8/vsintegration/src/FSharp.VS.FSI/fsiCommands.vsct#L220-L225):

```XML
<!-- ALT-ENTER is used for the SendToInteractive command.
         ALT-ENTER is globally bound to Diagram.Property.
         Here we bind it in the Editor context of the standard TextEditor.
         Ideally, we would bind it for F# only editor.
    -->
<KeyBinding guid ="guidVSStd11" id ="cmdidExecuteSelectionInInteractive" editor="GUID_TextEditorFactory" key1="VK_RETURN" mod1="Alt"  />
```

This has worked so long as no other language services were interested in this key combination. However now C++ and C# are interested in using this keybinding. In Visual Studio 2017 RC, F#'s keybinding is being overriden by users who have the Visual C# or Visual C++ profiles selected in 
`Tools > Options > Environment > Keyboard`.

We can solve this by declaring an F# [`EditorFactory`](https://msdn.microsoft.com/en-us/library/bb166453.aspx) that is called every time an F# file (.fs or .fsx) is opened in Visual Studio. At this point, the editor factory would set the keybindings and they would appropriately live only in the context of F# files.

If this is OK with you guys, I will implement it and submit a PR after I've tested against various filetypes.

**Comment by cartermp** [comment]
I think that's a great idea.

**Comment by JoshVarty** [comment]
I have a candidate PR for this but I'm unable to confirm that it works until #1633 is solved.

**Comment by KevinRansom** [comment]
@JoshVarty @cartermp We have #1633 fixed now in this repo.

**Comment by JoshVarty** [comment]
Awesome, I'll test and try to submit a PR to fix this during the week.

**Comment by JoshVarty** [comment]
I've implemented this but it doesn't appear to have solved the issue. I've reached out to some members who worked on the shell at some point to figure out a workaround.

**Comment by onionhammer** [comment]
Honestly, ALT+ENTER seems to work only some of the time now. It keeps getting unbound on my environment. Now when I re-bind it manually it fails to work altogether

**Comment by dsyme** [comment]
@onionhammer Could you open a new issue on that please, preferably with specific repro steps for that problem?  Thanks

**Comment by onionhammer** [comment]
@dsyme Sorry, I was using the wrong keybinding command. I deleted my comment.

**Comment by dsyme** [comment]
@onionhammer :) fat finger! :)
