### ISSUE TITLE
[From VSTS] hash function produces same value for (0.0, 2.0) and (2.0, 0.0)

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1799]
This was originally reported in internal VSTS, but I decided to try it out.  Screens below are with Mono/VsCode/Ionide.

<img width="242" alt="screen shot 2016-11-21 at 9 47 03 pm" src="https://cloud.githubusercontent.com/assets/6309070/20512416/18c9421e-b034-11e6-8ac5-43655a698953.png">

Compared with `hash (0.0, 1.0)` and `hash (1.0, 0.0)`:

<img width="262" alt="screen shot 2016-11-21 at 9 48 10 pm" src="https://cloud.githubusercontent.com/assets/6309070/20512457/4c7a24f2-b034-11e6-822f-72227e6e7dba.png">

Is this a bug?  It feels unexpected that we'd have a collision for something as "simple" as `(2.0, 0.0)` and `(0.0, 2.0)`.

**Comment by colinbull** [comment]
Same in VS 2015

![image](https://cloud.githubusercontent.com/assets/585546/20515053/9aa7c974-b087-11e6-8f64-f7f4ed5ab60a.png)

**Comment by forki** [comment]
Hash collisions always look like a bug. But they do happen. Usually it
should not be a problem.
There is this interesting debugging rule: if you set your program to return
0 for every hash function call then it should still work.

So actually I think it's nice that we now know a concrete collision. This
allows us to write tests against our hash based collections to see if
collisions are handled correctly.

Am 22.11.2016 8:46 vorm. schrieb "Colin" <notifications@github.com>:

**Comment by dsyme** [comment]
This is not an F# choice, it's a decision made long ago in the design of System.Tuple in the BCL.  It's a known problem but we've asked them not to churn the hash codes for reasons of stability.

(As an aside, hashing floating point numbers is nearly always a bad idea, though the collisions can no doubt happen with other values too)

**Comment by isaacabraham** [comment]
Will strict tuples and reference tuples support structural equality and / or will hashing algorithm differ between them?

**Comment by dsyme** [comment]
@isaacabraham AFAIK the decision was to make them precisely the same, so you could  switch between them seamessly, and advanced compilers could even choose representations.

**Comment by isaacabraham** [comment]
Good - that was my hope. I has visions of converting between them and getting spurious results.
