### ISSUE TITLE
[VS 2017 RC] Go To Implementation shouldn't appear if the capability doesn't exist

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1800]
Today in VS 15 RC, right-click shows Go to Implementation.  However, there is no ability to go to an implementation.  We shouldn't show this in the context menu until it's actually implemented.

**Comment by dungpa** [comment]
I have been looking at this issue. When the F# language service is initialized, it calls `base.SetUpNewTextView` which binds a Roslyn command filter to the current text view. This command filter register all kinds of menu items supported by Roslyn including Go To Implementation. However, it doesn't provide any extension point to override whether users can disable some of the features it supports.

I also tried to disable the menu item manually through FsiCommandFilter (added recently), but it didn't work because these MEF-exported command filters have lower priorities than the one provided by the language service.

Is there any good way to do this without rewriting Language Service command filters (to replace `base.SetupNewTextView` call)? /cc @brettfo @cartermp

**Comment by cartermp** [comment]
@dungpa I have no idea.  @OmarTawfik would you know more?

**Comment by OmarTawfik** [comment]
@CyrusNajmabadi is this something we can disable through an option?

**Comment by CyrusNajmabadi** [comment]
No.  But it should be trivial to add support for this.  We'd just need a new option, and we'd need to fix up: 

https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/GoToDefinition/GoToDefinitionCommandHandler.cs

to check for it.

**Comment by dungpa** [comment]
@CyrusNajmabadi It seems too ad-hoc to add one-off settings in that manner. What we need is the flexibility to disable a bunch of features (e.g. Go To Implementation, Formatting Document, Formatting Selection, etc)

Is this possible to make those `Query*` methods in AbstractOleCommandTarget class overridable? There is a related comment at  http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/AbstractOleCommandTarget.Query.cs,26

**Comment by CyrusNajmabadi** [comment]
> It seems too ad-hoc to add one-off settings in that manner. 

It's not.  It's the standard Roslyn way for languages to control things when they want different behaviors from other languages.  We do this in many places today already.  The places we haven't done this are those where we haven't had the need so far.  When teh need arises though, we add the option.

> Is this possible to make those Query* methods in AbstractOleCommandTarget class overridable? There is a related comment at

I am against doing that.  The OleCommandTarget stuff is effectively an internal implementation detail.  It's also something that is extremely brittle.  I don't want *anyone* messing with how we build command handler chains as that could lead to some incredibly hard to undrestand scenarios.

**Comment by CyrusNajmabadi** [comment]
> What we need is the flexibility to disable a bunch of selected features (e.g. Go To Implementation, Formatting Document, Formatting Selection, etc)

For the formatting guys, you can export "IEditorFormattingService" and return ```false``` for methods like:

```
        bool SupportsFormatDocument { get; }
        bool SupportsFormatSelection { get; }
        bool SupportsFormatOnPaste { get; }
        bool SupportsFormatOnReturn { get; }
```

**Comment by dungpa** [comment]
@CyrusNajmabadi Thanks for answering. We should add a Roslyn option and fix up GoToDefinitionCommandHandler as you suggested. Do you need me to open an issue on Roslyn repo?

**Comment by CyrusNajmabadi** [comment]
Sure.

**Comment by dungpa** [comment]
Here you go https://github.com/dotnet/roslyn/issues/15958

**Comment by cartermp** [comment]
Closing this, as it should be addressed in RC3.
