### ISSUE TITLE
[VS 2017 RC - From VSTS] F# Interactive broken in vs2015 after install VS 2017 RC

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1801]
**The following is copied verbatim from a VSTS bug:**

I already had VS 2015 Community installed which was working fine. I installed VS 2017 RC today. Now, when I use FSharp Interactive within Visual Studio 2015 OR I execute fsi.exe from the Visual Studio 2015 Developer Command Prompt I get the following:

```
Microsoft (R) F# Interactive version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> 
Session termination detected. Press Enter to restart.


unknown(1,1): error FS1223: FSharp.Core.sigdata not found alongside FSharp.Core


unknown(1,1): error FS0229: Error opening binary file 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\FSharp.Core\v4.0_4.4.0.0__b03f5f7f11d50a3a\FSharp.Core.dll': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+StopProcessing' was thrown.


unknown(1,1): error FS3160: Problem reading assembly 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+StopProcessing' was thrown.
```

However, I can run FSharp Interactive either from Visual Studio 2017 RC or from the Visual Studio 2017 RC Developer Command Prompt.

**Comment by graydo64** [comment]
I don't think #1820 is a duplicate of this issue as indicated.  #1820 is about F# interactive being broken in VS2017RC (see my [original post](https://developercommunity.visualstudio.com/content/problem/2754/fsharp-interactive-broken-in-visual-studio-2015-af.html)) but this issue is that installing VS2017RC breaks F# interactive in VS2015.  I can run F# interactive in VS2017RC.

**Comment by dutts** [comment]
I agree @graydo64. I have no problems with Interactive mode in my 2015 install, just 2017RC

**Comment by cartermp** [comment]
@KevinRansom @brettfo Is this something we can take a look at?

**Comment by jaromey** [comment]
I have this same problem too. I uninstalled VS 2017 RC and it still didn't work. I unistalled F# and reinstalled it. Still doesn't work. I also have no intellisense.

**Comment by ivanbenko** [comment]
experienced the same problem, it seems like assembly FSharp.Core 4.0 has been removed from the GAC with VS2017. so, as workaround, installing it to GAC or just copying to fsi.exe folder  helped me.

**Comment by sblom** [comment]
As a workaround, I did a Repair on Visual Studio 2015 from Add/Remove Programs, and FSI is all better.

**Comment by cartermp** [comment]
Closing this for now, as I don't think we really have the bandwidth the fix this given .NET Core and other pushes.  Since there is a workable solution by repairing the VS 2015 install, this is a less severe issue for us.  FSharp.Core as a whole is moving GAC-less and eventually it will just be a package we pull in via the package cache which comes with VS.  This is a breaking change, but for the better because it will solve the always-nagging issues related to loading these different assemblies.
