### ISSUE TITLE
"full" or "portable" debug symbol generation causes problems with InternalsVisibleTo 

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#1804]
The ``debug`` version of the CoreCLR compiler doesn't start correctly because InternalsVisibleTo attributes are not being respected when ``fsc.exe`` refers to ``FSharp.Compiler.dll``.

It appears this has something to do with debug symbol generation.   AFAICS the difference between the ``debug`` and ``release`` versions is in this set of flags:

Debug:

```
 --debug:portable
  --sourcelink:obj\debug\coreclr\source_link.json
 --delaysign+
  --keyfile:C:\GitHub\dsyme\visualfsharp\src\fsharp\FSharp.Compiler\..\..\fsharp\msft.pubkey
```

Release
```
  --debug:pdbonly
 --delaysign+
  --keyfile:C:\GitHub\dsyme\visualfsharp\src\fsharp\fsi\..\..\fsharp\msft.pubkey
```

When I manually changed the CoreCLR Debug compilation to use ``--debug:pdbonly`` then things worked OK.   It does *not* work with ``--debug:full``.  

This says to me that using ``--debug:portable`` and ``--debug:full`` are messing with the identity or signing of the assembly being produced.

#### Repro steps

```
build net40 coreclr debug

tests\testbin\debug\coreclr\fsc\win7-x64\CoreRun.exe tests\testbin\debug\coreclr\fsc\win7-x64\fsc.exe 
```

#### Expected behavior

Runs ok

#### Actual behavior

```
Unhandled Exception: System.MethodAccessException: Attempt by method 'Microsoft.FSharp.Compiler.CommandLineMain.main(System.String[])' to access method 'Microsoft.FSharp.Compiler.ErrorLogger+BuildPhase.get_Parameter()' failed.
   at Microsoft.FSharp.Compiler.CommandLineMain.main(String[] argv)
```
.

**Comment by KevinRansom** [comment]
No its a coreclr problem.  For.some reason.internals visible doesnt work correctly when we build for.debug.

**Comment by KevinRansom** [comment]
Third party apps should be fine.its.nust the.debug fsharp.compiler that has a problem.

**Comment by dsyme** [comment]
@KevinRansom Is this still an issue?  I presume not?

**Comment by dsyme** [comment]
Closing as this appears fixed
