### ISSUE TITLE
Built locally VFT does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1811]
Today's VS 2017 RC release
```
Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.25920.0 D15REL
```
* Uninstall VFT VSIX 
* build VisualFSharp.sln with msbuild
* Install VisualFSharpFull.vsix (all other ones fail to install)
* Open a F# solution

Results:

* *.fs files do not colorized and no features work
* *.fsx files colorized completely properly
* build command does not work: nothing is happening, build process is in "in progress" state forever.

**Comment by dsyme** [comment]
@vasily-kirichenko I've been able to build and install VisualFSharpFull.vsix correctly.  I'm using a command line install/uninstall

    VSIXInstaller.exe  /a /u:"VisualFSharp"
    VSIXInstaller.exe /a  debug\net40\bin\VisualFSharpFull.vsix

.fs files outside of projects are not colorized.  That's a known bug (need to search for ID)

**Comment by vasily-kirichenko** [comment]
@dsyme .fs files which belong to projects weren't colorized either. I'll try to install with vsixinstaller.exe later today. Thanks!

**Comment by vasily-kirichenko** [comment]
If I install Debug VSIX, nothing works, except .fsx files colorizing.
If I install Release VSIX, everything works, except .fsx files - it says it cannot find FSharp.Core.dll 4.1.1.0

**Comment by vasily-kirichenko** [comment]
The way it works for me (as @dsyme added into DEVGUIDE.MD recently): set VisualFSharpOpenSource.vsix as startup project and hit `Ctrl+F5` (`F5` does not work for me, experimental instance crashes on start), then I can attach to it manually and debug.

**Comment by dsyme** [comment]
@vasily-kirichenko Good to know.  (F5 is working for me)
