### ISSUE TITLE
Feature: keyword completion

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1839]
Current master:

![image](https://cloud.githubusercontent.com/assets/873919/20631772/9eeb8a88-b349-11e6-89d7-89ddc2d22132.png)

**Comment by cartermp** [comment]
Just to verify, the expectation is the `true` is in the completion set?  IMO it should also be at the top.

**Comment by vasily-kirichenko** [comment]
Yes, `true`.

**Comment by vasily-kirichenko** [comment]
C# editor has a dedicated Completion Provider for keywords, http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis.CSharp.Features/Completion/CompletionProviders/KeywordCompletionProvider.cs

@dsyme where can I get full keyword list? If it's not accessible anywhere in the codebase, I can port this one https://github.com/ionide/FsAutoComplete/blob/master/src/FsAutoComplete.Core/KeywordList.fs (which already has nice "xml docs" for each keyword and is used in Xamarin and FSAC for autocomplete and tooltips). It can be used to filter out types-that-are-also-keywords (like `int`) to fix https://github.com/Microsoft/visualfsharp/issues/1809 (however, filtering by string names is a bit hacky I think and will not work for qualified names. Could you suggest anything better?)

**Comment by dsyme** [comment]
@vasily-kirichenko There's a keyword list at ``Microsoft.FSharp.Compiler.Lexhelp.Keywords\keywordNames``

**Comment by cloudRoutine** [comment]
```fsharp
__LINE__
__SOURCE_DIRECTORY__
__SOURCE_FILE__
```
should be included too

**Comment by dsyme** [comment]
My impression is that this has been completed?  @vasily-kirichenko @cloudRoutine  What about __LINE__ etc.?  I don't see them in the autocomplete lists

**Comment by vasily-kirichenko** [comment]
Yes, those keywords are not added yet,

**Comment by vasily-kirichenko** [comment]
Keyword completion was implemented long time ago.
