### ISSUE TITLE
Feature request: Zooming Disabled in FSI Tool Window

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#1840]
I noticed that [zooming is intentionally disabled for the FSI tool window](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.VS.FSI/fsiSessionToolWindow.fs#L102-L107) and I'm hoping this decision will be reconsidered. At the very least for the sake of presentations where the lack of zoom makes FSI in VS useless.  When the zoom has been increased for the source code to make it legible to viewers but REPL stays at a minuscule inscrutable level the validity of this zoom lock decision comes into question.

#### Repro steps

1. Try to zoom the FSI window
2. Fail

#### Expected behavior

Zoom works with CTRL+SCROLL UP/SCROLL DOWN

#### Actual behavior

No Zoom

#### Known workarounds

Change monitor resolution

#### Related information 

Provide any related information 

* Operating system Win10
* Branch master
* .NET Runtime
* Editing Tools VS2015, VS2017

**Comment by forki** [comment]
Urgs what's the intention to disable zoom?

Am 25.11.2016 6:04 nachm. schrieb "Jared Hester" <notifications@github.com>:

**Comment by KevinRansom** [comment]
We can certainly consider zoom.

**Comment by forki** [comment]
My question was: why was it disabled? What's the intention? Maybe it was just copied over from a sample? 

Also @cloudRoutine please send PR which enables it again?

**Comment by dsyme** [comment]
@forki I have no idea, any reasoning behind this is lost in time

**Comment by KevinRansom** [comment]
I'm sure it wasn't deliberately disabled.

**Comment by cartermp** [comment]
Fixed by #1914
