### ISSUE TITLE
Please add an equivalent to Microsoft.Net.Compilers

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#1843]
### Feature Request:

Please add a Nuget Package, which, when added to a F# project, replaces the system F# compiler with the F# compiler contained in the package.

Something similar exists for C# / VB in the form of [Microsoft.Net.Compilers](https://www.nuget.org/packages/Microsoft.Net.Compilers/).

### Reasoning:
Where I work (and I doubt I am alone in this), many buildservers still only run __VS2013__! With MNC, I am able to use all the latest and greatest C#6 and C#7 features, regardless of what is installed on the buildserver. If a developer opens the solution with VS2013. he/she will get a lot of red squigglies at design time, but the project builds and is debuggable.

But I won't be able to use F# vNext until maybe in half a year or a year, and even then only on buildservers targeting our main branch. (We have yearly versioned branches, with 3 parallel versions being developed, and buildservers targeting [vLatest-n] are not updated.)

This would also reduce the friction on the community adapting F#vLatest. AFAIK currently most F# projects would need to wait until all contributors AND all CI systems (e.g. Appveyor) update to VS15, until F#4.1 is usable. With this package, contributors may get syntax errors at worst, but the project is still compilable everywhere.

**Comment by dsyme** [comment]
@0x53A There is FSharp.Compiler.Tools, published from githunb.com/fsharp/fsharp.  This doesn't completely replace the compilers without setting the FscToolPath property in your project file.  You would also need to NGen the FSharp.Compiler.dll to get acceptable performance. But you may be able to extend the package so it does these things automatically.

**Comment by 0x53A** [comment]
I am now using FSharp.Compiler.Tools in all our projects, so that they can be built even on a build server without VS2017.

Thank you @dsyme.
