### ISSUE TITLE
I can haz 4 CI parts pleazse 

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#1844]
Today we have 2 CI parts which allow us to have "faster" builds. Can we try to split it up again?

**Comment by dsyme** [comment]
I suppose so.  It's diminishing returns because each one has a base of 10-15 minutes to build Proto and Net40.  But 3-4 parts would help (Though not for AppVeyor which is serial).

**Comment by dsyme** [comment]
@forki I'll close this for inactivity. But feel free just to try submitting a built.cmd with 4 parts instead of 3.  It's hard to get the split exactly right though
