### ISSUE TITLE
Strange autocomplete suggestion

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1846]
![image](https://cloud.githubusercontent.com/assets/873919/20639101/4d3aa49e-b3cb-11e6-9c94-3088ab73c1cc.png)

**Comment by forki** [comment]
Wow what even is this thing?

**Comment by dsyme** [comment]
@forki @vasily-kirichenko Yeah I know, it's odd.  I saw them yesterday too

**Comment by 0x53A** [comment]
They are generated by roslyn for lambdas, etc. AFAIK these classes are internal, so either the visibility filter does not work, or you have a InternalsVisibleTo?

**Comment by dsyme** [comment]
@0x53A It's odd as I'm sure we have a filter in place.  We don't have an IVT into Roslyn AFAIK

**Comment by 0x53A** [comment]
@dsyme you must have an IVT, the whole class is internal:

http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CommonCompletionItem.cs,02f200b007a2f8e7,references

**Comment by dsyme** [comment]
@0x53A Oh, the power :) OK, closing this for now.  I mean, from one perspective we shouldn't show these I suppose.  But internal is internal, and we can see internals.

**Comment by Pilchie** [comment]
They should have  attributes on them (`CompilerGenerated`?) that you might be able to filter on.  Roslyn's symbol model has [`ISymbol.CanBeReferencedByName`](http://source.roslyn.io/#Microsoft.CodeAnalysis/Symbols/ISymbol.cs,0921be50519eedc4) as well for things that appear in the symbol API but aren't mentionable.
