### ISSUE TITLE
What is the purpose of:  FSharp-4.0.30603.0

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#185]
We have 3 lkgs in our lkg folder

FSharp-2.0.50726.900
FSharp-4.0.30319.1
FSharp-4.0.30603.0
sentinel

FSharpSource.Settings.target is configured to use 4.0.30319.1
    <LkgVersion>4.0.30319.1</LkgVersion>

To be clear .... 4.0.30603.0 will not compile FSharp.Compiler-proto.fsproj because of resource id collisions, which amazingly the previous lkg is quite relaxed about.

Additionally the FSharp-4.0.30603.0\ appears to be dependent on a non-existent runtime.  When I run fsc.exe I get this dialog:

![untitled](https://cloud.githubusercontent.com/assets/5175830/5985742/7e5c297c-a89b-11e4-9252-1482790f9681.png)

I propose we delete it from the tree, it seems to be nothing but clutter, unless someone understands it's divine purpose.

Thanks

Kevin

**Comment by dsyme** [comment]
agreed!

**Comment by dsyme** [comment]
Closing - fix by @KevinRansom above
