### ISSUE TITLE
VS2017 RC - Crash when editing 

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#1850]
I hit a crash when typing ``..`` here:

![capture5](https://cloud.githubusercontent.com/assets/7204669/20640981/9cd44f54-b3e5-11e6-98df-0f885d55b324.PNG)

I didn't capture more informationas yet.

**Comment by cartermp** [comment]
Adding urgency-now label, since crashes are pri0.  cc @brettfo

**Comment by dsyme** [comment]
@cartermp Thanks.  Note I haven't got a repeatable repro for this yet.

**Comment by vladima** [comment]
Can you check if you have any relevant entries in Event Log `eventvwr`? Like errors with the source `.NET Runtime`

**Comment by dsyme** [comment]
Closing as I haven't seen this again
