### ISSUE TITLE
VS2017 RC - Glitch - Wrong colorization?

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1854]
![image](https://cloud.githubusercontent.com/assets/873919/20642974/18bbcf50-b42e-11e6-8de9-04612ef17ef3.png)

**Comment by cartermp** [comment]
I'm seeing this as well.

**Comment by vasily-kirichenko** [comment]
Fixed long ago, was related to optional arguments.
