### ISSUE TITLE
VS2017 RC - Project-wide analysis should not be enabled

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#1856]
VS2017 RC currently enabled project-wide analysis based on ParseAndCheckProject and shows red-squiggly errors based on the results

See vsintegration\src\FSharp.Editor\ProjectDiagnosticAnalyzer.fs

This is wrong, because this method checks using saved files on-disk, not the current contents of buffers.  This results in erratic, persistent red-squiggly errors being shown in half-edited unsaved files in the IDE.

We should just disable this feature for now

**Comment by vasily-kirichenko** [comment]
I'm trying to port virtual file system we use in VFPT https://github.com/vasily-kirichenko/visualfsharp/commit/5185d7668ede2cc4b968c3c47a98d84bb1a2d9bb

It tracks open documents and pass to file system dirty buffers content.

I'm stuck on fitting it to MEF as `LanguageServer` has FSharpChecker as static field.

**Comment by vasily-kirichenko** [comment]
OK, it seems to work, but `ParseAndCheckProject` does not call FileSystem :(

**Comment by dsyme** [comment]
@vasily-kirichenko Can you share your branch?

We may have to delay looking at this until F# 4.2, though it would be great to get a prototype done

**Comment by vasily-kirichenko** [comment]
@dsyme what do you mean by sharing the branch? I've created a PR from it, do it whatever you want with it.

**Comment by dsyme** [comment]
yes that's what I meant, thanks

**Comment by dsyme** [comment]
Mistakenly auto-closed
