### ISSUE TITLE
F# is broken on .NET Core 1.1

### ISSUE THREAD

**Issue by rogersachan** [Microsoft/visualfsharp#1857]
#### Repro steps

Provide the steps required to reproduce the problem

1. Install .NET Core latest version

2. `dotnet new -t f#`

3. `dotnet restore`

4. `dotnet run`

#### Expected behavior

Compiles and `Hello World!`
#### Actual behavior

Errors with

```
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.
```
#### Known workarounds

Install .NET Core LTS

#### Related information 

```
PS /home/ubuntu/workspace/learn/test> dotnet run                                                                                                                                                                                                     
Project test (.NETCoreApp,Version=v1.1) will be compiled because expected outputs are missing
Compiling test for .NETCoreApp,Version=v1.1
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.
/usr/share/dotnet/dotnet compile-fsc @/home/ubuntu/workspace/learn/test/obj/Debug/netcoreapp1.1/dotnet-compile.rsp returned Exit Code 131

Compilation failed.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.4445729
```
See dotnet/cli#4787
* Operating system
Any
* Branch
* .NET Runtime, CoreCLR or Mono Version
.NET Core 1.1
* Editing Tools (e.g. Visual Studio Version)
* Links to F# RFCs or entries on http://fslang.uservoice.com
* Links to performance testing scripts
* Indications of severity
Prevents usage of F# on .NET Core

**Comment by enricosada** [comment]
it's an issue with sdk integration (`dotnet-compile-fsc`) not directly the compiler afaik.

tracking it in https://github.com/dotnet/netcorecli-fsc/issues/42

**Comment by KevinRansom** [comment]
per enricosada, is is with sdk.
