### ISSUE TITLE
Error message suggests strange types

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1863]
![image](https://cloud.githubusercontent.com/assets/873919/20648991/f2f4412e-b4c5-11e6-8ccd-6b08ee7a1263.png)

In particular, I don't see how `Byte` can fit here.

/cc @forki

**Comment by forki** [comment]
It suggests the correct type as first thing. I think it's ok

**Comment by forki** [comment]
I would love DayeTimeKind expected to be on second position. But I assume we would need a different distance function for that. Also we could filter better so that Byte and Double would be eliminated. Do you have a heuristic in mind?

**Comment by forki** [comment]
I remember @Rickasaurus proposed to use Jaro-Winkler Distance instead of Damerau-Levenstein edit distance. Quick google search showed Rick already blogged an implementation: http://richardminerich.com/2011/09/record-linkage-algorithms-in-f-jaro-winkler-distance-part-1/

So I copied it and tested on our sample:

![image](https://cloud.githubusercontent.com/assets/57396/20672873/16e6954c-b583-11e6-890a-485c03efd773.png)

Pretty neat. @Rickasaurus are you interested in contributing the algorithm? I would take care about the rest,

**Comment by forki** [comment]
see https://github.com/Microsoft/visualfsharp/pull/1876

**Comment by nosami** [comment]
<img width="438" alt="screen shot 2016-11-28 at 16 03 22" src="https://cloud.githubusercontent.com/assets/667194/20675478/514c32b8-b584-11e6-92e1-a56db0af4951.png">

First time I've seen this - awesome!

**Comment by forki** [comment]
@nosami one day we want that to provide quickfixes ;-)

**Comment by Rickasaurus** [comment]
Sure, just grab it. In practice we double down on the first two letters even harder by doubling up the winkler coefficient, but I'm not completely sure you'd want to do that here.

**Comment by forki** [comment]
@rickasaurus unfortunatly this is not so easy with this repo. CLA, lawyers and stuff. But I would prepare https://github.com/Microsoft/visualfsharp/pull/1876 - so that in the end you would just need to resent the PR with your CLA. Deal? And thanks for helping

**Comment by Rickasaurus** [comment]
If that's the case I'll need to check with the higher ups at my company who will certainly say yes to the submission, but I'm not sure about the CLA. We'll probably need our lawyers to look at it.

**Comment by forki** [comment]
ok. if that's going to be a problem then just let me know. I'm pretty sure I can google that algorithm and implement it myself if that's really needed. But of course I'd like to credit your work here.

**Comment by Rickasaurus** [comment]
Sure, where can I find the CLA? I'll send it today.

**Comment by forki** [comment]
I think the process starts by sending a PR. Then a bot will send you a link
a checks everything. So I suggest you just send a cosmetical Pull request
like removing unnecessary semicolon somewhere. Sorry for that ;-)

Am 28.11.2016 17:46 schrieb "Rick Minerich" <notifications@github.com>:

**Comment by cartermp** [comment]
@Rickasaurus when you make a PR a bot should comment and give you the info to sign the CLA - it uses GitHub authentication and after you've signed it, it'll mark the PR as already-signed and you'll be good to go from then.  You can also look at it here: https://cla.microsoft.com/cladoc/microsoft-contribution-license-agreement.pdf

It's quite straightforward and only requires a few things like ~~your soul~~ that you have permission to make contributions by your employer if you're doing it for your employer, among

**Comment by Rickasaurus** [comment]
Thanks for the link. I sent an email to our CEO about it. I'll come back when I know more.

**Comment by Rickasaurus** [comment]
I've been given the go ahead to contribute this as Bayard Rock work. If I submit as myself will the proper corporate CLA be given?

**Comment by cartermp** [comment]
cc @martinwoodward to answer this question.  I *suspect* there's no issue, but Martin could clarify.

**Comment by martinwoodward** [comment]
So section 4 of the CLA is the important bit. Basically, if the PR is made in the course of your work for an employer or your employer has intellectual property rights in the PR, you must have got permissions from them before signing the agreement.  How you get permission varies from company to company - but if you are happy that they are happy for this to be contributed then you can sign your CLA and you are saying that you are allowed to contribute the IP as open source.  Hope that makes sense - but please make sure you have taken a look at Section 4 before signing.

**Comment by Rickasaurus** [comment]
Thanks Martin. We've already had our lawyer look at it and I have the go ahead from our CEO.

**Comment by martinwoodward** [comment]
Fantastic news - thanks for doing that. Sounds like you'll be good to go. ✨

**Comment by Rickasaurus** [comment]
So what's the next step?

**Comment by cartermp** [comment]
@Rickasaurus In this case, all you gotta do is make your first PR.  A bot will ask you to sign the CLA (logged in with credentials), and that'll be that.  If you've already signed, it'll mark the PR with the `cla-already-signed` label, and from then on it's just code review time.

**Comment by forki** [comment]
You might as well wait one or two days and I have the test ready so that
you can submit the real fix. I'll let you know. And thanks.

Am 28.11.2016 11:50 nachm. schrieb "Phillip Carter" <
notifications@github.com>:

@Rickasaurus <https://github.com/Rickasaurus> In this case, all you gotta
do is make your first PR. A bot will ask you to sign the CLA (logged in
with credentials), and that'll be that. If you've already signed, it'll
mark the PR with the cla-already-signed label, and from then on it's just
code review time.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/issues/1863#issuecomment-263420331>,
or mute the thread

**Comment by forki** [comment]
@Rickasaurus Ok I think https://github.com/Microsoft/visualfsharp/pull/1876 will be green now. So you could just resubmit 6b48059 as a new PR. I will then close mine in favour of yours.

**Comment by forki** [comment]
@nosami: https://twitter.com/k_cieslak/status/803738567214329860 your move ;-)
