### ISSUE TITLE
Build test: Couldn't find CORSDK, when running with latest framework

### ISSUE THREAD

**Issue by nelak** [Microsoft/visualfsharp#1864]
Running build test with the latest framework throws: couldn't find CORSDK

#### Repro steps

Clean install of windows and clean install of VS2017 RC
Run: build test

#### Expected behavior

Test should run

#### Actual behavior

![image](https://cloud.githubusercontent.com/assets/254502/20649886/ff8c72bc-b4a7-11e6-837d-4033a527ac89.png)

#### Known workarounds

Modifying [test-framework.fs](https://github.com/Microsoft/visualfsharp/blob/2f5851a1db3749dcf561e9d1f6afe72f27490a4a/tests/fsharp/test-framework.fs#L156) to include these entries:
```
regQueryREG_SOFTWARE @"SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools" "InstallationFolder"
regQueryREG_SOFTWARE @"SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\NETFXSDK\4.6.2\WinSDK-NetFx40Tools" "InstallationFolder"
```
will make the tests run again.

#### Related information 
None of the following registry keys are matched when running tests with the latest frameworks:

- Software\Microsoft\Microsoft SDKs\NETFXSDK\4.6\WinSDK-NetFx40Tools
- Software\Microsoft\Microsoft SDKs\Windows\v8.1A\WinSDK-NetFx40Tools
- Software\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx40Tools
- Software\Microsoft\Microsoft SDKs\Windows\v7.1\WinSDK-NetFx40Tools
- Software\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-NetFx40Tools

**Comment by nelak** [comment]
Let me know if adding those keys is the correct approach and I'll create a PR with the changes

**Comment by dsyme** [comment]
Sure add these please
