### ISSUE TITLE
Signature file definitions don't effect type inference

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#1870]
When a function's types are specified in a signature file and the parameters for that function in the corresponding implementation file do not have their types specified the parameters are inferred to be generic.

#### Repro steps

1. create impl and sig files

**Example01.fsi**
```fsharp
module FCS.Example01

val fn001 : int -> string -> unit
```

**Example01.fs**
```fsharp
module FCS.Example01

let fn001 num txt = ()
```
2. see error & 
![](http://i.imgur.com/WYKy2zZ.png)

#### Expected behavior

`num` inferred to be `int` and `txt` inferred to be `string`

#### Actual behavior

`num` inferred to be `'a` and `txt` inferred to be `'b`

#### Known workarounds

specify the types in the implementation file

#### Related information 

Provide any related information 
* F# 4.0
* Operating system win10
* .NET Runtime, CoreCLR or Mono Version .net 4.5

**Comment by dsyme** [comment]
This is by design. Please submit to fslang-suggestions?
