### ISSUE TITLE
Formatting prevents Compiler from finding corresponding implementation for a signature file

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#1871]
When the `namespace` and `module` formatting in a `.fsi` and `.fs` file don't match the compiler thinks the implementation doesn't exist.

#### Repro steps

Provide the steps required to reproduce the problem

1. Define `.fs` and `.fsi` files 

**Example01.fsi**
```fsharp
namespace FCS
module Example01 =
    val fn001 : string -> unit
```

**Example01.fs**
```fsharp
module FCS.Example01

let fn001 (txt:string) = ()
```

2. Build project
3. See error in build output & signature file

```
error FS0240: The signature file 'Example01' does not have a corresponding implementation file. 
If an implementation file exists then check the 'module' and 'namespace' declarations 
in the signature and implementation files match.
```
![](http://i.imgur.com/bYBf2Sn.png)

despite 

![](http://i.imgur.com/8EDeQQo.png)

![](http://i.imgur.com/CUpFpZY.png)

#### Expected behavior

Compiler should recognize the module despite the different formatting

#### Actual behavior

Compiler error

#### Known workarounds

Use the same formatting in both the sig and impl
```fsharp
module FCS.Example01
``` 

in both or 

```fsharp
namespace FCS
module Example01 =
```

in both

#### Related information 

F# 4.0
* Operating system Win10
* .NET 4.5
* VS 2015

**Comment by dsyme** [comment]
@cloudRoutine THis is going back a long way, but the current behavior is intended, as you can see from the error message ``If an implementation file exists then check the 'module' and 'namespace' declarations 
in the signature and implementation files match.``

**Comment by cloudRoutine** [comment]
If `FCS` is the namespace in both examples and `Example01` is the module inside the namespace `FCS` in both examples, I'd argue that the declarations match semantically.

**Comment by dsyme** [comment]
@cloudRoutine I know.  It might be as imple fix, perhaps poke around at the QualNameOfFile stuff, which is what gives a file its identity when finding signature files for implementation files and vice-versa.  It's not based purely on the file name - the question is whether there is any good reason for that

**Comment by dsyme** [comment]
@cloudRoutine This is by-design, so I will close this.  However as mentioned we would be open to a language addition that adjusts to the behavior that you expect.
