### ISSUE TITLE
Implement Output Channel for F# Language Service

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#1874]
@KevinRansom  In VFPT we have an output channel that we can enable in "diagnostic mode" to pump information onto while working on new features and fixing bugs. I think it'd be really useful for the F# vsintegration to have something similar. Even if it only works in debug mode and doesn't get shipped as part of the release.

![](http://i.imgur.com/ke5ZrLE.png)

@vasily-kirichenko or I could implement this

**Comment by dsyme** [comment]
Yes please

**Comment by Pilchie** [comment]
Yes - I've done the same thing in Roslyn for Lightweight Solution Load [here](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/ProjectSystem/VisualStudioProjectTracker_IVsSolutionLoadEvents.cs,cb868bc5e9437be6,references).

**Comment by KevinRansom** [comment]
@cloudRoutine 
This sounds like an excellent notion.

**Comment by dsyme** [comment]
Fixed
