### ISSUE TITLE
Compiler sometimes fails to build projects in VisualFSharp.sln 

### ISSUE THREAD

**Issue by JoshVarty** [Microsoft/visualfsharp#1879]
Occasionally when working with `VisualFSharp.sln` I get to a state where Visual Studio is unable to build any projects in the solution.

The only error message shown in output is:
```
FSharp.Compiler -> C:\Users\jovarty\Documents\GitHub\visualfsharp\Debug\net40\bin\FSharp.Compiler.dll
Unhandled Exception:Operation is not valid due to the current state of the object.
========== Rebuild All: 5 succeeded, 19 failed, 0 skipped ==========
```

I've seen this issue on two different machines and @cloudRoutine mentioned that he has seen it as well while working with this solution.

I can still build all projects using `msbuild` from the Visual Studio 2017 RC Command Prompt with no problems.

#### Repro

I do not have a repro beyond "Make changes to the solution and build projects". If I discover a reliable repro I'll add it to the issue here.

#### Known workarounds

@cloudRoutine suggested that I clean my /.vs directory, reset to an earlier commit and if that fails then to repair Visual Studio.

#### Related information 

Provide any related information 

* Operating system: Windows 10
* Branch: master
* Editing Tools: Visual Studio 2017 RC (15.0.25920.0)

**Comment by dsyme** [comment]
Error is "Unhandled Exception:Operation is not valid due to the current state of the object."

Would be good to work this one out

**Comment by cartermp** [comment]
I haven't noticed this.  @JoshVarty @cloudRoutine have you noticed this behavior recently?

**Comment by JoshVarty** [comment]
Not since the first week I first reported it.

**Comment by cartermp** [comment]
Okay.  I'll close this for now.  We can re-open if it comes back again.
