### ISSUE TITLE
Protocompiler does not build

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1880]
1. Grab latest master (up until [this commit](https://github.com/Microsoft/visualfsharp/commit/c22aaa22d3752c32a1b8694e35cd1d449243ade6))
2. Using vs2017 RC 1, make sure you have .NET Desktop with F# checked, C++ Desktop, and VS Extensibility Workloads installed
3. open VS Developer command prompt in admin mode
4. run `build.cmd vs`

```
Build FAILED.

"C:\Users\Phillip Carter\repos\visualfsharp\src\fsharp-proto-build.proj" (default target) (1) ->
"C:\Users\Phillip Carter\repos\visualfsharp\src\fsharp\FSharp.Compiler-proto\FSharp.Compiler-proto.fsproj" (Build targe
t) (3) ->
(CallFsLex target) ->
  C:\Users\Phillip Carter\repos\visualfsharp\packages\FsLexYacc.7.0.1\build\FsLexYacc.targets(34,3): error MSB3073: The
 command "C:\Users\Phillip Carter\repos\visualfsharp\src\fsharp\FSharp.Compiler-proto\..\..\..\packages\FsLexYacc.7.0.1
\build\fslex.exe  -o "pplex.fs" --unicode --lexlib Internal.Utilities.Text.Lexing ..\pplex.fsl" exited with code 9009.
[C:\Users\Phillip Carter\repos\visualfsharp\src\fsharp\FSharp.Compiler-proto\FSharp.Compiler-proto.fsproj]
```

Code 9009 is file not found, and I noticed that `pplex.fsl` does not exist on my machine.

**Comment by JoshVarty** [comment]
From: http://stackoverflow.com/questions/1351830/what-does-exited-with-code-9009-mean-during-this-build

It may be because your path has a space in it. Perhaps try in a different location.

**Comment by cartermp** [comment]
Thanks @JoshVarty, that seemed to work.  I'll create a PR to add a note to the DEVGUIDE that the path cannot have a space in it.

**Comment by forki** [comment]
How about fixing that thing that checks the path to accept spaces?

Am 29.11.2016 2:03 vorm. schrieb "Phillip Carter" <notifications@github.com
>:

Closed #1880 <https://github.com/Microsoft/visualfsharp/issues/1880>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/issues/1880#event-874541348>,
or mute
the thread

**Comment by cartermp** [comment]
@forki Not familiar with the build scripts, but it seems to just be invoking msbuild on the project: https://github.com/Microsoft/visualfsharp/blob/master/build.cmd#L488

Quick google search suggests using `\\` to specify paths, otherwise msbuild won't accept the path.  Not sure what a good solution here is for the build script, but I'm inclined to think that it would involve a string replace up top and percolating the replaced path string throughout the script.

**Comment by forki** [comment]
Didn't @dsyme just fix it? Or was this another thing?

Am 29.11.2016 6:45 nachm. schrieb "Phillip Carter" <notifications@github.com

**Comment by cartermp** [comment]
yup looks like it
