### ISSUE TITLE
MsBuild causing blocking on UI thread in a variety of situations

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#1884]
Switching between build configurations and trying to build the solution while there are errors in a source file are consistently locking up VS where it's faster to kill the process and restart than to wait for the thread to unblock.

I ran a trace just on switching between debug and release in VS 2017

![](http://i.imgur.com/veTj6HD.png)

^ that's a 3.8 min block on the UI thread

Please provide a succinct description of the issue.

#### Repro steps

**Configuration Blocking**

1. Switch Build Configurations

**Build Blocking**

1.  introduce errors in `.\vsintegration\src\FSharp.LanguageService\XmlDocumentation.fs`
2. try to build

#### Expected behavior

VS 2017 doesn't lock

#### Actual behavior

UI Locks that last for several minutes.

#### Known workarounds

Kill Process and Restart

#### Related information 

Provide any related information 

* Operating system - Win 10
* Branch - master
* .NET Runtime
* Visual Studio Version 2017

**Comment by vasily-kirichenko** [comment]
Yes, this issue is terribly annoying. TBH, it's here since VS 2012, maybe earlier.

**Comment by dsyme** [comment]
@cloudRoutine Any chance you could see if you could grab some relevant call stacks?

**Comment by saul** [comment]
This was resolved in #2133 - this can be closed.
