### ISSUE TITLE
Support Locals and Parameters in Completion and IntelliSense Filtering

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1886]
In C# projects, you can do this:

![locals](https://cloud.githubusercontent.com/assets/6309070/20699251/34675ff6-b5bb-11e6-98fd-9cd2b6792270.PNG)

This would be quite useful for F#, as there are numerous situations where you explicitly give something a name and use it some way, like passing to a function, such as this:

```fsharp
type BST<'T> =
    | Empty
    | Node of value:'T * left:BST<'T> * right:BST<'T>

let rec flip t = 
    match t with
    | Empty -> t
    | Node(x, left, right) -> Node(x, flip right, flip left)
//                                          ^^          ^^
//                        These would be suggested to me by IntelliSense
//                        after typing "r" and "l", respectively.
```

**Comment by vasily-kirichenko** [comment]
VS 2015:

![image](https://cloud.githubusercontent.com/assets/873919/20709273/57461262-b645-11e6-85d1-6329d8d9fb4a.png)

**Comment by forki** [comment]
so label should be changed to regression

**Comment by cloudRoutine** [comment]
this isn't a feature that consistently works in 2015 and it definitely doesn't work in all the contexts that it should

**Comment by vasily-kirichenko** [comment]
@cloudRoutine I think concrete samples should be added.

**Comment by cartermp** [comment]
So this may actually be a bug, not a feature request:

![locals-current](https://cloud.githubusercontent.com/assets/6309070/20717971/226783c0-b60c-11e6-9d6e-81c4881c3a40.PNG)

`right` is definitely not a constant, but it's being classified as such.  My expectation would be that this would be classified under Locals and Parameters like what I showed in the C# screenshot.  cc @OmarTawfik @Pilchie @brettfo

**Comment by dsyme** [comment]
We were just using the Constant glyph incorrectly. 

There is still an unfortunate choice between the (overly object-oriented) Roslyn view of the world and the F# view.  For F#, we call all of these "values"

- module-defined values 
- class-defined values
- parameters
- values from pattern matching including let-bound values

We call these "functions" (though they can be used as values so the user might think of them as values)

- module-defined functions 
- locally-defined functions 
- class-defined functions 

With https://github.com/Microsoft/visualfsharp/pull/1892 we use
* Glyph.Method for all of the latter
* Glyph.Constant for all of the former that are ``[<LiteralValue>]``
* Glyph.Local for all of the former that are non-function-typed
* Glyph.Method for all of the former that are function-typed




Anyway with the change we use the type

**Comment by cartermp** [comment]
@dsyme It seems to me that we might want to consider defining new glyph types to account for the F# worldview for post-RTM.  Should I start a discussion?
