### ISSUE TITLE
ngen is not found in appveyor script

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#189]
While looking at the log for an appveyor run, I noticed that ngen is't being found:
See the bold snippet below.

108Time Elapsed 00:10:32.55
109 
**110C:\projects\visualfsharp-radou>ngen install lib\proto\fsc-proto.exe**
**111 'ngen' is not recognized as an internal or external command,**
**112 operable program or batch file.**
113 
114C:\projects\visualfsharp-radou>"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" src/fsharp-library-build.proj /p:UseNugetPackages=true  
115Microsoft (R) Build Engine version 12.0.31101.0

**Comment by dsyme** [comment]
Fixed by direct commit (tested on my mahine, let's double check appveyor goes through https://github.com/Microsoft/visualfsharp/commit/1f7f85a97fa3696216203580577a242852966c97)

**Comment by dsyme** [comment]
Fixed via https://github.com/Microsoft/visualfsharp/commit/1f7f85a97fa3696216203580577a242852966c97
