### ISSUE TITLE
Do not show empty parameter XML Doc in signature helper

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1893]
![image](https://cloud.githubusercontent.com/assets/873919/20724743/73cb59fc-b680-11e6-9cae-ecce38ca2ec7.png)

**Comment by vasily-kirichenko** [comment]
I think the doc comment just does not exists, so it's better to not show "filename:" at all.

**Comment by dsyme** [comment]
I'm not certain we have control over this.  All we give is this:

                      let doc = [| TaggedText(TextTags.Text, paramDoc);  |] 

Perhaps

    filename: <no documentation>

would be half palatable

**Comment by cartermp** [comment]
@dsyme @vasily-kirichenko Here's what it looks like with that change (words are different, happy to have it just say "no documentation"):

![no-doc-stuff](https://cloud.githubusercontent.com/assets/6309070/20727089/f3f1ef0a-b62c-11e6-8785-3f5848c42504.PNG)

Would that be PR-worthy, or should we reach out to folks who own this and try to get a change on their end?

**Comment by vasily-kirichenko** [comment]
@cartermp how c# editor handle this?

**Comment by cartermp** [comment]
@vasily-kirichenko No parameters are shown for C#.

![no-doc-csharp](https://cloud.githubusercontent.com/assets/6309070/20727749/9e94dc72-b62f-11e6-868e-4b18d0240d01.PNG)

**Comment by Pilchie** [comment]
> `let doc = [| TaggedText(TextTags.Text, paramDoc);  |] `

I think that if you created an *empty* array if `paramDoc` is null or empty instead of creating an array with an element with null/empty text, then this would work as expected.

**Comment by cartermp** [comment]
Looks like passing an empty array leaves a newline in there:

![no-doc-stuff-empty-arr](https://cloud.githubusercontent.com/assets/6309070/20730259/4033c28c-b63a-11e6-9dee-95a9697d01c1.PNG)

It also behaves the same if I pass in `[| TaggedText(TextTags.Text, ""); |]`.

**Comment by Pilchie** [comment]
Strange - Roslyn doesn't do anything special here - http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/SignatureHelp/SignatureHelpParameter.cs,5750a926612a5093,references, and looking at the editor code it collapses that part if there is no text.

No chance that you just have a trailing newline on the end of "Does some stuff" there?

**Comment by cartermp** [comment]
Ah, culprit here: https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/SignatureHelp.fs#L168

We always append newline - just need to change that to only append if there are parameter docs.

**Comment by cartermp** [comment]
Okay, so there's a deeper problem here - invoking [`XmlDocumentation.BuildMethodOverloadTipText`](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/SignatureHelp.fs#L158) will [parse out the parameters as well](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.LanguageService/XmlDocumentation.fs#L257), leading to a funky tooltip:

![no-doc-original](https://cloud.githubusercontent.com/assets/6309070/20732775/16ec5816-b645-11e6-84bf-ecd997f3c967.PNG)

This is using the latest master up until here: https://github.com/Microsoft/visualfsharp/commit/3851f9d72cb21b69a646e8da6836fc297f423f47

So unfortunately, I don't this will be as simple as just only appending a newline if there are parameter docs.
