### ISSUE TITLE
Alt-f12 doesn't invoke Peek Definition

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1894]
Right-click -> Peek Definition works for types within the same project, but hitting alt+f12 does nothing.

**Comment by Pilchie** [comment]
When is Alt+Enter ever bound to Peek Definition?

**Comment by cartermp** [comment]
Whoops, mistyped - what I meant was alt+f12.

**Comment by vasily-kirichenko** [comment]
We have this functionality implemented in VFPT https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharp.Editing.VisualStudio.v2015/PeekDefinition.fs

I can try to port it, but not right now since I failed to build VFT behind a proxy.

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it on master. `Alt+F12` works for symbols defined in current project.

**Comment by vasily-kirichenko** [comment]
It also works cross projects:

![image](https://cloud.githubusercontent.com/assets/873919/20860044/08ec9198-b980-11e6-87a9-47375f26d48f.png)

**Comment by cartermp** [comment]
Interesting...I'll take a look again this afternoon.

**Comment by cartermp** [comment]
Hmm.  Maybe it's my keyboard/keybindings, since alt+f12 also fails on C# projects for me.
