### ISSUE TITLE
Create new project error: Unable to find version '4.3.0' of package 'System.ValueTuple'

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1901]
VS 2017 RC + VisualFSharpOpenSource.vsix built from current master:

![image](https://cloud.githubusercontent.com/assets/873919/20763915/252e7aa0-b73d-11e6-899e-cb85043c1e9b.png)

As a result, the project is created and opened in VS, but has broken System.ValueTuple reference:

![image](https://cloud.githubusercontent.com/assets/873919/20764014/84ff66c4-b73d-11e6-8dd3-98c3955e3474.png)

**Comment by cartermp** [comment]
cc @KevinRansom

**Comment by dsyme** [comment]
I saw this too when creating a new tutorial project

**Comment by rojepp** [comment]
This seems to work in RC2, probably got fixed in packaging.

**Comment by cartermp** [comment]
Closing, as I can confirm @rojepp's experience.
