### ISSUE TITLE
Assert when using F# project dialog

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#1908]
Got this assert when clicking on the Build tab of the project dialog for FSharp.Editor in VisualFSharp.sln when using a debug build of the VIsual F# IDE Tools

![capture11](https://cloud.githubusercontent.com/assets/7204669/20803141/15225a60-b7e6-11e6-98c1-f45c2981fec1.PNG)

**Comment by saul** [comment]
Duplicate of #2123 @cartermp

**Comment by cartermp** [comment]
Closing in favor of #2123.  Thanks @saul
