### ISSUE TITLE
Suggestions for mispelled values are not applied against simple values.

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#1909]
The following code provides a valid suggestion: -
```fsharp
type Foo = { Name : string }
let bar = { Nam = "Isaac" }
```

However the following does not: -

```fsharp
let name = "Isaac"
let fullName = nam + " Abraham"
```

I would like the compiler to apply the same suggestions whenever any symbols cannot be identified.

**Comment by isaacabraham** [comment]
cc: @forki

**Comment by forki** [comment]
I'm on it

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/20810771/641c1c26-b80b-11e6-983e-8d9b0e94e070.png)

**Comment by forki** [comment]
^^ this is without jaro-winkler...

**Comment by forki** [comment]
see https://github.com/Microsoft/visualfsharp/pull/1911

**Comment by isaacabraham** [comment]
Wicked. Nice one.

**Comment by forki** [comment]
We could filter even better if we would have type information, but hey I think it's still progress
