### ISSUE TITLE
Debugger tooltips do not work on large solutions

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1915]
1. Open VisualFSharp.sln.
2. Set VisualFSharpOpenSource project as the startup one.
3. Press `F5`.
4. If you lucky, a new VS experimental instance opens, if not press `Ctrl+F5`, then attach to it with the debugger.
5. Hover over any symbol in a F# source file.
6. After ~2 seconds delay the following dialog opens:

![image](https://cloud.githubusercontent.com/assets/873919/20764244/65278e84-b73e-11e6-8d0d-0c385ce92e7e.png)

7. This dialog does not disappear, no tooltip appear either until you move the mouse somewhere else.

This bug does not relate to QuickInfo, it's called in debug mode (for unknown reason, BTW), but commenting it out entirely does not help. So I think the problem is purely in `ILanguageDebugInfoService.GetDataTipInfoAsync` method.

**Comment by cartermp** [comment]
Opening a hive is consistent for me, but I'm noticing this with regularity.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/1926
