### ISSUE TITLE
Visual F# appears without "RC" suffix in VS about dialog

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1917]
![image](https://cloud.githubusercontent.com/assets/873919/20830840/74212d36-b893-11e6-9230-8abef4ecacd1.png)

**Comment by forki** [comment]
that's because this stuff is already really RTMish ;-)

**Comment by cartermp** [comment]
@brettfo Is this a setup thing?

**Comment by dsyme** [comment]
I don't think it's worth fixing this.  We'll only forget to unfix it when RTM comes.

**Comment by cartermp** [comment]
Marking for now, but I definitely wouldn't prioritize this unless we've been _not_ following a proper setup procedure.

**Comment by KevinRansom** [comment]
There is no automagic procedure ... there used to be but now.  We don't share branding ... so no procedure,
Won't-fixing.
Kevin
