### ISSUE TITLE
"Could not copy "...RegisterFsharpPackage.pkgdef" warnings if built inside VS

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1922]
> 21>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4241,5): warning MSB3026: Could not copy "E:\github\visualfsharp\vsintegration\Vsix\RegisterFsharpPackage.pkgdef" to "E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpWeb\..\..\..\src\..\Debug\net40\bin\RegisterFsharpPackage.pkgdef". Beginning retry 1 in 1000ms. The process cannot access the file 'E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpWeb\..\..\..\src\..\Debug\net40\bin\RegisterFsharpPackage.pkgdef' because it is being used by another process.
21>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4241,5): warning MSB3026: Could not copy "E:\github\visualfsharp\vsintegration\Vsix\RegisterFsharpPackage.pkgdef" to "E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpWeb\..\..\..\src\..\Debug\net40\bin\RegisterFsharpPackage.pkgdef". Beginning retry 2 in 1000ms. The process cannot access the file 'E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpWeb\..\..\..\src\..\Debug\net40\bin\RegisterFsharpPackage.pkgdef' because it is being used by another process.
20>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4241,5): warning MSB3026: Could not copy "E:\github\visualfsharp\vsintegration\Vsix\RegisterFsharpPackage.pkgdef" to "E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpFull\..\..\..\src\..\Debug\net40\bin\RegisterFsharpPackage.pkgdef". Beginning retry 1 in 1000ms. The process cannot access the file 'E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpFull\..\..\..\src\..\Debug\net40\bin\RegisterFsharpPackage.pkgdef' because it is being used by another process.
19>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4241,5): warning MSB3026: Could not copy "E:\github\visualfsharp\vsintegration\Vsix\RegisterFsharpPackage.pkgdef" to "E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpDesktop\..\..\..\src\..\Debug\net40\bin\RegisterFsharpPackage.pkgdef". Beginning retry 1 in 1000ms. The process cannot access the file 'E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpDesktop\..\..\..\src\..\Debug\net40\bin\RegisterFsharpPackage.pkgdef' because it is being used by another process.
19>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4241,5): warning MSB3026: Could not copy "E:\github\visualfsharp\vsintegration\Vsix\RegisterFsharpPackage.pkgdef" to "E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpDesktop\..\..\..\src\..\Debug\net40\bin\RegisterFsharpPackage.pkgdef". Beginning retry 2 in 1000ms. The process cannot access the file 'E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpDesktop\..\..\..\src\..\Debug\net40\bin\RegisterFsharpPackage.pkgdef' because it is being used by another process.

**Comment by cartermp** [comment]
@vasily-kirichenko have you been bale to repro this lately?

**Comment by dsyme** [comment]
We can close this old issue I believe
