### ISSUE TITLE
Transitive VisualFSharpOpenSource.vsix build error 

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1923]
> 15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018: The "CreateZipPackage" task failed unexpectedly.
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018: System.ObjectDisposedException: Store must be open for this operation.
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Packaging.PackagingUtilities.SafeIsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, ReliableIsolatedStorageFileFolder folder)
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Packaging.PackagingUtilities.CreateUserScopedIsolatedStorageFileStreamWithRandomName(Int32 retryCount, String& fileName)
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Packaging.SparseMemoryStream.EnsureIsolatedStoreStream()
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Packaging.SparseMemoryStream.SwitchModeIfNecessary()
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Packaging.SparseMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Zip.ZipIOFileItemStream.Write(Byte[] buffer, Int32 offset, Int32 count)
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Zip.ProgressiveCrcCalculatingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at Microsoft.VsSDK.Build.Tasks.CreateZipPackage.CopyStream(Stream source, Stream target)
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at Microsoft.VsSDK.Build.Tasks.CreateZipPackage.Execute()
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
15>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Build: 14 succeeded, 1 failed, 13 up-to-date, 0 skipped ==========

**Comment by cartermp** [comment]
@vasily-kirichenko Have you been able to repro this recently?

**Comment by vasily-kirichenko** [comment]
Since number of packages reduced to two, it appears rarely, but it's not gone.

**Comment by dsyme** [comment]
@vasily-kirichenko Still seeing this?

**Comment by vasily-kirichenko** [comment]
Not exactly this one, but building from within VS fails time to time.

**Comment by vasily-kirichenko** [comment]
RC3, building within VS:
> 50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018: The "CreateZipPackage" task failed unexpectedly.
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018: System.IO.IsolatedStorage.IsolatedStorageException: Unable to delete file.
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at System.IO.IsolatedStorage.IsolatedStorageFile.DeleteFile(String file)
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at MS.Internal.IO.Packaging.PackagingUtilities.DeleteIsolatedStorageFile(String fileName)
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at MS.Internal.IO.Packaging.PackagingUtilities.SafeIsolatedStorageFileStream.Dispose(Boolean disposing)
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at System.IO.Stream.Close()
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at MS.Internal.IO.Packaging.SparseMemoryStream.Dispose(Boolean disposing)
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at System.IO.Stream.Close()
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at MS.Internal.IO.Zip.ZipIOFileItemStream.Save()
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at MS.Internal.IO.Zip.ZipIOLocalFileBlock.Save()
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at MS.Internal.IO.Zip.ZipIOBlockManager.SaveContainer(Boolean closingFlag)
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at MS.Internal.IO.Zip.ZipIOBlockManager.SaveStream(ZipIOLocalFileBlock blockRequestingFlush, Boolean closingFlag)
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Dispose(Boolean disposing)
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at System.IO.Stream.Close()
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at System.IO.Packaging.PackagePart.Close()
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at System.IO.Packaging.Package.DoClose(PackagePart p)
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at System.IO.Packaging.Package.DoOperationOnEachPart(PartOperation operation)
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at System.IO.Packaging.Package.System.IDisposable.Dispose()
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at Microsoft.VsSDK.Build.Tasks.CreateZipPackage.Execute()
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
50>E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(590,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
51>------ Build started: Project: VisualFSharp.Unittests, Configuration: Debug Any CPU ------

**Comment by dsyme** [comment]
Fixed ages ago
