### ISSUE TITLE
Error does not disappear after fixing the code

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1925]
Current master:

![1](https://cloud.githubusercontent.com/assets/873919/20858046/44ab834e-b94c-11e6-8832-36969890a08b.gif)

**Comment by abelbraaksma** [comment]
FWIW, this also happens in VS2015 w/ F# 4.0 latest edition/fixes. I often close/reopen a file to make errors and warnings disappear. It happens most often when:

0. Pasting large parts of code
0. Uncommenting (or commenting: coloring, incl. red curlies, stays, does not turn green) code
0. Opening a solution (this actually happens *always*, any project-reference will appear as non-existing, always need to rebuild whole solution before I start working)
0. Fast typing, esp. within builders (when you stop fast-typing, the error curly remains)

Usually, the solution to all this is to just build it.

Not trying to hijack your issue or anything ;), just saying it may be the resurfacing of an existing bug that has gotten more prominent with recent changes somehow.

**Comment by dsyme** [comment]
@vasily-kirichenko Aside - just saw this

![capture14](https://cloud.githubusercontent.com/assets/7204669/20975884/b9eff99c-bc98-11e6-92b5-649b0c724127.PNG)

**Comment by vasily-kirichenko** [comment]
@dsyme I think it's ok?

**Comment by dsyme** [comment]
@vasily-kirichenko But it just appeared in the errors dialog while typing.  We don't want to see that do we?

**Comment by vasily-kirichenko** [comment]
Ah, then something went wrong :( Yeah, it should be investigated.

**Comment by vasily-kirichenko** [comment]
I found this line https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/CommonHelpers.fs#L120

I think we should just check if the token has been cancelled and break the loop in the normal way.

**Comment by vasily-kirichenko** [comment]
It might be the cause of this bug I think.

**Comment by dsyme** [comment]
@vasily-kirichenko It feels like it's valid to throw if cancellation is requested. And we should always be swallowing OperationCancelledException when we start our asyncs?

Or we should be making this code ``async {  .. }``?

**Comment by vasily-kirichenko** [comment]
As it's always called from other asyncs, then it should work, yes. I'm still not sure that our exception catching logic in `CommonRoslynHelpers.StartAsTask` is valid. I'd be more happy if we removed it entirely.

**Comment by dsyme** [comment]
@vasily-kirichenko I think we should always be explicitly throwing away cancellation exceptions at that point

**Comment by dsyme** [comment]
BTW I'm seeing this all the time, do you see this
```
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018: The "CreateZipPackage" task failed unexpectedly.
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018: System.ObjectDisposedException: Store must be open for this operation.
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Packaging.PackagingUtilities.SafeIsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, ReliableIsolatedStorageFileFolder folder)
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Packaging.PackagingUtilities.CreateUserScopedIsolatedStorageFileStreamWithRandomName(Int32 retryCount, String& fileName)
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Packaging.SparseMemoryStream.EnsureIsolatedStoreStream()
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Packaging.SparseMemoryStream.SwitchModeIfNecessary()
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Packaging.SparseMemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Zip.ZipIOFileItemStream.Write(Byte[] buffer, Int32 offset, Int32 count)
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Zip.ProgressiveCrcCalculatingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at Microsoft.VsSDK.Build.Tasks.CreateZipPackage.CopyStream(Stream source, Stream target)
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at Microsoft.VsSDK.Build.Tasks.CreateZipPackage.Execute()
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
15>C:\GitHub\dsyme\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25907-RC2\tools\vssdk\Microsoft.VsSDK.targets(573,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Build: 14 succeeded, 1 failed, 13 up-to-date, 0 skipped ==========
```

**Comment by vasily-kirichenko** [comment]
@dsyme Yes I see this, but not always. I'm not sure but I think it's happening when several VSIX-es are built in parallel. However, restarting VS usually helps, so...

**Comment by dsyme** [comment]
Fix to the original issue in this thread is here: https://github.com/Microsoft/visualfsharp/pull/1963

**Comment by cartermp** [comment]
@vasily-kirichenko I can't repro this anymore.  I think it's fixed.  Can you verify?

**Comment by vasily-kirichenko** [comment]
@cartermp I cannot reproduce it either.
