### ISSUE TITLE
internal error : the list had different lengths. Parameter name xs2

### ISSUE THREAD

**Issue by robsiera** [Microsoft/visualfsharp#1935]
I'm new to F#, but based on information I found on StackOverflow I thought it might be useful to mention this compile error I can't get rid of.

"internal error : the list had different lengths. Parameter name xs2"

#### Repro steps

Try compiling this project  https://github.com/robsiera/Fsharp-SignalR in Visual Studio 2015
That will trigger the error.

The project is currently using the latest nuget F# pre-release. But even that didn't solve the problem.

**Comment by forki** [comment]
IMHO this is not a compiler bug.

I assume it fails at

    let definedClientHubTypes =
        List.zip (typeInfo |> List.map (fun (n,_) -> n)) clientTypeInfo
        |> List.map makeClientHubType

in SignalRProvider.fs. 

Please report this to the author of tje SignalRProvider

**Comment by robsiera** [comment]
Thx @forki for having a look at it. 
But the error message is a compiler error message right? If so, then who/what is responsible (who's concern is it) for making sure that developers know what is going on. I mean, even you have to 'assume' where it fails. Can't we get rid of that kind of uncertainty?

**Comment by forki** [comment]
No it's not. It's thrown by the zip function inside of the type provider constructor. This is "user code" that happens to be run at compile time. Yeah type providers are weird. 

The message itself comes from fsharp.core and you can reproduce this easily if you zip two lists with unequal lengths in fsi. So the author of the type provider needs to make sure both lists are of equal length. If the author can't ensure that he should throw a detailed error message which gives a better error. As I said this is all "user code" and not coming from the compiler itself.

**Comment by robsiera** [comment]
Ok, case closed.

But for future reference (it was very hard to find any information on this error) allow me to give my personal conclusion

Due to the fact that the error is raised in the context of a Type Provider, one needs to debug that Provider in order to gather more information on the error raised.
So it is just a matter of getting the Type Provider debugging to work. Which seems easier said than done. I tried following 3 different tutorials.
* https://docs.microsoft.com/en-us/dotnet/articles/fsharp/tutorials/type-providers/creating-a-type-provider
* https://sergeytihon.wordpress.com/tag/type-providers/
* http://blog.ctaggart.com/2014/07/debugging-into-f-type-provider-source.html

**Comment by forki** [comment]
yes definetly a super complicated issue and needs much more love. I fully aggree

**Comment by matthid** [comment]
One could argue that the bug is the bad error message produced by the compiler. Maybe the compiler should write the full error info somewhere...

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/20883127/c32cae70-bae4-11e6-99a1-218477d5d3f6.png)

**Comment by matthid** [comment]
ok not that bad :)

**Comment by forki** [comment]
That's what I got ootb in VS2013. I mean it could clearly be  improved, but it's already pointing in the right direction. 

But the xs2 part of the zip error message is really not helpful

**Comment by dsyme** [comment]
We should just give a partial stack trace on type provider errors.  That would help enormously.
