### ISSUE TITLE
False positives for extern methods with --warnon:1182

### ISSUE THREAD

**Issue by jack-pappas** [Microsoft/visualfsharp#1937]
In F# 4.0 (I haven't tried to repro in 4.1), specifying the ``--warnon:1182`` compiler flag results in false positive warnings for the parameters of ``extern`` methods -- by definition, such methods don't have a body so the compiler probably shouldn't be warning about unused parameters. Another way of looking at this -- there's no way to "use" the parameters of an ``extern`` method in such a way to satisfy this check and get rid of the warning.

#### Repro steps

Compile the following example code while invoking the compiler with the ``--warnon:1182`` flag:

```fsharp
namespace WarnOn1182ExternRepro

open System.Runtime.InteropServices

type DWORD = uint32

module NativeMethods =
    [<DllImport("kernel32.dll", CallingConvention = CallingConvention.Winapi)>]
    extern [<MarshalAs(UnmanagedType.Bool)>] bool Beep (DWORD dwFreq, DWORD dwDuration)
```

#### Expected behavior

The compiler shouldn't issue warnings for unused parameters in ``extern`` methods.

#### Actual behavior

The compiler issues warnings for unused parameters in ``extern`` methods.

#### Known workarounds

There aren't any workarounds, aside from disabling the warning (either by not using ``--warnon:1182``, or by disabling the warning for a specific file with ``#nowarn "1182"``.

#### Related information 

* Windows 10 Pro x64
* Visual Studio 2015 Update 3
* .NET 4.6.2

**Comment by forki** [comment]
Duplicate of #485?

**Comment by jack-pappas** [comment]
@forki Yes, you're correct. I'll close this one and follow that issue instead.

**Comment by forki** [comment]
if you are interested you can try to pick up #1861
