### ISSUE TITLE
Functions with a byref parameter like Int64.TryParse act inconsistent when overloaded w.r.t. type inference and type resolution

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#1940]
This issue [was raised on StackOverflow previously](http://stackoverflow.com/questions/40845386/type-extensions-wont-compile-and-or-exhibit-strange-compile-time-behavior) and while it still awaits an answer there, I think it may be a bug, or should at least be considered as one:

Overriding `Int64.TryParse` incorrectly resolves to itself, leading to incorrect type inference.

For the following examples, consider this exists:

    type Option<'T> with
        /// Creates an Option from a .NET byref result, (true, res) -> Some res, otherwise None
        static member ofByRef (success, result) =
            match success with
            | true -> Some result
            | _ -> None

## Repro steps

The main issue is explained with this example:

    type Int64 with
        static member TryParse s = (Int64.TryParse >> Option.ofByRef) s   // won't compile, type error

Compare it with this:

    type Int64 with
        static member TryParse = Int64.TryParse >> Option.ofByRef   // compiles, but cannot be used

    // call it raises type error
    let test1 = 
        Int64.TryParse "42"
        |> Option.map ((*) 2L) 

## Expected behavior

Both should compile fine.

## Actual behavior

The first example above shows that `Int64.TryParse` is considered to be of generic type. However, the rules (iirc) state that if there's a conflict between a type extension and an actual method, it should resolve to the actual method. This doesn't happen, in fact, it appears to recursively resolve to oneself.

Surprisingly, I don't see a workaround for this (i.e., using `global.System.Int64.TryParse` seems to have no effect).

The second example infers (when hovered over) to be of the correct type (i.e. `string -> int64 option`), but when you call it, it won't be used, even though its signature is different from the original (different number of arguments).

## Known workarounds

Surprisingly, if you redefine `Int64.TryParse` by assigning it to a let-binding as `let parseInt = Int64.TryParse` and then use that instead, it compiles just fine:

    let tparse = Int64.TryParse
    type Int64 with
        static member TryParse s = (tparse >> Option.ofByRef) s  // no error anymore

The second issue above can be worked around by using `Int64.get_TryParse() "42"` to call the function. This is hardly intuitive and I doubt it ought to be necessary.

## Related information

Tested with most recent versions of F# 4.0, VS2015.

**Comment by dsyme** [comment]
I've checked that this is not a regression.

The extension method is being preferred over the treat-the-byref-return-as-a-tuple.  We should look closely at the existing spec for that case.

Given that this behaviour has been around some time, we would probably have to use an RFC to change it, should we decide that it's not by-design.

**Comment by dsyme** [comment]
Needs RFC/suggestion
