### ISSUE TITLE
[VS 2017 RC] Go to Definition and Navigation is very slow in a large file

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1941]
1. Go to src/fsharp/vs/service.fs
2. Place caret on `GetDeclarationLocation` at line 1941.
3. Invoke Go to Definition.

![nav-to-def-slow 1](https://cloud.githubusercontent.com/assets/6309070/20873672/db881c60-ba5e-11e6-949b-3d34b61c7e67.gif)

**Comment by vasily-kirichenko** [comment]
It's expectable if the project is not type checked yet. If it is, then it's a bug. However I found the new Go to definition much slower than what we had in VS 2015. May it be the case that it performed some more smart cacheing?

**Comment by abelbraaksma** [comment]
This not only happens in the newest 4.1 branch.

In VS2015, esp. when a project is not (completely) compilable and is fairly large (100k LOC) then GoToDefinition can take up to a minute or so, and if you meanwhile continue typing, at some point you'll get a popup saying "No definition found" (not sure of the the text).

If the definition is in another project (linked as project reference), GoToDefinition sometimes works, sometimes doesn't. I just tried it again in VS2015 (solution with 12 F# projects). F12 on a method in project X works (after 20 sec), but same method used in project Y doesn't. Both X and Y are part of the same solution and linked as project reference.

I use F12 (GoToDefinition) a lot, but have learned to live with its perks. But if someone is going to have a stab at making it more resilient I'd welcome that a lot.

**Comment by cartermp** [comment]
@abelbraaksma Yes, I've marked it as `Urgency-Soon`, because I believe GoToDefinition to be one of the top items we need to do very well if we want to match "experience parity" with C#/VB.  I think the perf is definitely worth investigating.

At the very least, we'll need to make it aware of other projects for vs2017 - right now, it only works within the same project, which is a regression (even if it was spotty at times in the past).

**Comment by cartermp** [comment]
@vasily-kirichenko I noticed that after _quite_ a long while, it would be pretty fast.  Perhaps that's the typechecking.  I hope it's not, though, because otherwise we likely would not be able to speed up what I observed.

**Comment by dsyme** [comment]
@cartermp Using a "debug" install of those tools it is likely ~40 seconds before GTD is ready in service.fs.  Using a release build should be ~25 seconds

**Comment by cartermp** [comment]
@dsyme I see.  IIRC I'm using a release build - I'll test it out again and see if I can get decent estimates on the time it takes.  After a while (presumably when everything is typechecked), it's basically instant.

**Comment by abelbraaksma** [comment]
This delay also happens on my project when it is just compiled. I notice a first-time long delay (sometimes > 60s). After that, everything in the linked project seems to be direct. Reopening the project will show red squiggles everywhere (though sometimes F12 works regardless), even though there are no errors. After rebuild and all the linked projects look "normal" again, there's still the first time delay.

After some editing, the delay sometimes comes back (but right now I can't repro that, may be Upd 3 fixed this).

First-time delay seems per-project (i.e. assembly), not per class, and irrespective whether it was just compiled. When the project is not compilable, F12 seems to work on types + members, but not on extension members.

2nd and later times are still slow compared to C# (near instant). On my system it takes about 1-2s, sometimes 2-5s. I only checked self-built projects, as I find F12 with disassembled or reflected types rather useless (albeit better than nothing).

**Comment by abelbraaksma** [comment]
Just a suggestion: could we fix this perhaps by using a timer callback? I.e, suppose it takes longer than 2s, or suppose the type system is still working in the background, show a message in the status bar: "Go to member not yet available, please wait until background type checking is completed.".

I think this will be frustrating, but less frustrating than thinking it doesn't work, you continue your editing work and after a minute the cursor jumps to whatever it was on when you hit F12 a minute ago. Happens to me quite often...

**Comment by dsyme** [comment]
@abelbraaksma Could you edit your comments above to indicate if the observations are with VS2015 , VS2017RC or VS2017(master) please?   Thanks

**Comment by abelbraaksma** [comment]
@dsyme , done. Sorry, thought it was clear from the context. It's all VS2015, Upd 3, F# 4.0, I've edited the comments.

**Comment by dsyme** [comment]
@abelbraaksma I think the GTD implementation has changed sufficiently that we will only be able to investigate reports that reproduce using VS2017RC (master). 

It's likely this will still reproduce there  - could you check please?

**Comment by abelbraaksma** [comment]
@dsyme, that may take some time as I haven't downloaded it yet and I may need to set up a VM so as not to potentially taint my development environment (not sure if the VS2017RC can be installed side-by-side with VS2015 risk-free). But I'll try it out.

**Comment by cartermp** [comment]
Closing, as this has been made much better with recent performance improvements to FCS.  It's also really a symptom of classification taking a long time in FCS, particularly for files in VisualFSharp.sln.

**Comment by abelbraaksma** [comment]
> @dsyme, that may take some time as I haven't downloaded it yet 
I have meanwhile done so and the "go to declaration" functionality has much improved in the new VS2017, it is fast and most of the time accurate (but not so with same-named DU's, but that's a new issue).
