### ISSUE TITLE
Saving a script file under a different name results in loss of colorization

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#1944]
Saving a script file under a different name results in loss of colorization

#### Repro steps

Provide the steps required to reproduce the problem

1. Take script1.fsx containing some F# code.  Observe its colors

2. Save it as script2.fsx. Observe its colors

#### Expected behavior

Colorized in both cases

#### Actual behavior

Colorized only prior to the save-as operation

#### Known workarounds

close/open the file

**Comment by dsyme** [comment]
We should test similar scenarios in projects as well (e.g. adding/deleting/renaming files in projects)

**Comment by cartermp** [comment]
I can't repro this on master from up until here: https://github.com/Microsoft/visualfsharp/commit/4b8aafd809b9232213f73fc0942ac13a55b63db6

However I did notice that there is no rename ability for files.  Neither right-click nor double-click work:

![no-rename-file](https://cloud.githubusercontent.com/assets/6309070/20889895/a26e165e-bab9-11e6-91c9-979f3232833b.PNG)

**Comment by rojepp** [comment]
@cartermp That's because the file in your screenshot is in a 'folder'. That is also why 'Move Up'/'Move Down' are greyed out. All these work in project root folder.

**Comment by rojepp** [comment]
Can't repro either, using VisualFSharpOpenSource from a few days ago.

**Comment by cartermp** [comment]
Got it to repro:

![loss-colorization](https://cloud.githubusercontent.com/assets/6309070/21325545/b665938a-c5db-11e6-9af7-47b9f4670076.PNG)

It looks like reserved keywords aren't getting colorized, but type information is.

**Comment by cartermp** [comment]
Looks like [`IEditorClassificationService.AddSyntacticClassificationsAsync`](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Classification/ColorizationService.fs#L42) isn't invoked on a rename, as per @brettfo's suspicions.

**Comment by saul** [comment]
I didn't even need to rename the file. I added the file to an existing project, pasted the code, saved it and then I suffered the same discolouration as above.

**Comment by cartermp** [comment]
@Pilchie @brettfo Is this something we can address from the Roslyn side?  Syntactic Classification isn't called for script files under certain circumstances.

**Comment by Pilchie** [comment]
This would happen if the `ITextSnapshot` doesn't correspond to a `Document` that is part of the `Workspace`.  I don't think this a Roslyn issue.

**Comment by majocha** [comment]
Simple repro is to rename a script file in Solution Explorer.

Cause of this bug is that we currently don't handle script file renaming. Roslyn exports a `MiscellaneousFilesWorkspace` which tracks renaming scripts by implementing `IVsRunningDocTableEvents2` but we don't use it.

**Comment by saul** [comment]
The reason this is happening is because in FSharpLanguageService we're listening on Workspace.DocumentClosed. This is fired when the script file is renamed, and so we remove the single-file project. DocumentOpened is never fired again and neither is SetupNewTextView (what we use to setup single file projects).

@Pilchie do you know what the proper way to setup single-file projects is? What event should we be listening to that will fire when a document is renamed?

**Comment by saul** [comment]
@majoca We can't use MiscellaneousFileWorkspace until https://github.com/dotnet/roslyn/pull/17263 is made available. See https://github.com/dotnet/roslyn/pull/17263#issuecomment-297010447

**Comment by dsyme** [comment]
I can confirm that this does **not** appear to be fixed by #3025

**Comment by cdutcher** [comment]
Is there any eta or plan for this fix?

**Comment by cartermp** [comment]
Not at the moment, no.

**Comment by saul** [comment]
Shame - I fixed this is #2909.

**Comment by cartermp** [comment]
I’m actually keen on getting that PR worked on, or at least chunks pulled out and merged. But we sinply lack the bandwidth right now due to .NET Core platform and tooling bringup.

**Comment by saul** [comment]
I’ll pull out the fix for this issue now and take a stab at using the MiscellaneousFilesWorkspace - that’s the proper fix (but we couldn’t use it back then)

**Comment by cartermp** [comment]
@saul Awesome! Just in terms of timeframe, VS 15.6 release is unlikely to take a fix like this since we're nearly locked down, but 15.7 is still quite open.

**Comment by cartermp** [comment]
Just as an update, renaming a `.fs` file to a `.fsx` triggers this issue, forcing a re-open of the document.

Now that we depend on updated Roslyn and editor binaries, we could probably fix this a lot easier than before.

**Comment by cartermp** [comment]
Closing as fixed. Note that we're also in the process of letting Roslyn effectively handle this all for us with a proper workspace here: https://github.com/dotnet/roslyn/pull/31134
