### ISSUE TITLE
Question: Should "EnableOpenSource.vsix" contain these dlls?

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#195]
When I open debug\net40\bin\EnableOpenSource.vsix as a ZIP file (after renaming it), it seems to contain a whole bunch of System.* and Microsoft.* DLLs.  Is this expected?

![capture](https://cloud.githubusercontent.com/assets/7204669/5993557/26ea7a34-aa23-11e4-957c-f140da57bf51.JPG)

**Comment by dungpa** [comment]
I think these files shouldn't be there. However, they do no harm except increasing the size of the output vsix.

**Comment by latkin** [comment]
@KevinRansom are these expected to be packaged?

**Comment by KevinRansom** [comment]
The VSIX and debugging scenario is the next thing on my list to work through.  I will see what I can do to exclue the VS dependencies.

**Comment by KevinRansom** [comment]
This was fixed with : https://github.com/Microsoft/visualfsharp/pull/186

![debugging](https://cloud.githubusercontent.com/assets/5175830/6094521/fb730416-aee1-11e4-999b-f194168bbe8e.jpg)

**Comment by KevinRansom** [comment]
Dll's are still there.

**Comment by KevinRansom** [comment]
Fix merged
