### ISSUE TITLE
More consistent and more simple syntax

### ISSUE THREAD

**Issue by 21c-HK** [Microsoft/visualfsharp#1952]
Inspired by the recent syntax discussion in the thread "How to drive F# Adoption - Part 4" (#1339), I created this thread that is dedicated to discussions on making the F# syntax more consistent and more simple. I had difficulty naming this thread, because I did not want to simply name it "Improve syntax" since this thread **should not be about (more or less arbitrary) syntax changes** like "_Can't we replace this keyword/operator/bracket with that keyword/operator/bracket?_". Instead, this thread **should be geared towards (more or less objective) consistency and simplification of the syntax** like "_There is the following unnecessary syntactic inconsistency, which might be confusing to F# users and/or complicate the F# compiler_".  

The suggestion to make the F# syntax more consistent and more simple is in line with a few desirable factors of suggestions listed in [fslang-suggestions](https://github.com/fsharp/fslang-suggestions):
> - education/learning paths and simplicity
> - does this give multiple ways to achieve the same thing
> - design coherence
> - "less is more" design considerations

I give a few examples at the bottom to make clear what I mean. I (or you) might post these examples as individual issues on [fslang-suggestions](https://github.com/fsharp/fslang-suggestions) if other people agree that these would be worthwhile changes. I am aware that "_we simplified the syntax and compiler_" is not as sexy or impressive as "_wow, look at this new feature_", but it would be a worthwhile long-term investment that would help F# adoption since it would reduce the learning costs of every F# user.

Note that I chose to post here first instead of [fslang-suggestions](https://github.com/fsharp/fslang-suggestions), because that repository seems to be for individual suggestions while I thought that it might be a good idea to gather a few inconsistencies first to see if we can find a common themes like verbose vs. lightweight below before posting individual suggestions.

**I would like to suggest that if there are two syntactic ways to do _exactly_ the same thing (see below for examples), then we should decide on one of them to be the only way and officially deprecate the other.** Ideally, a future version of F# would not longer support the deprecated syntax and all references to it would be removed from the official documentation. I imagine that this would simplify the compiler considerably and improve the learning experience of F#.

## Examples of inconsistent syntax ##

1. The option between verbose syntax and lightweight syntax is a clear example of two ways of expressing *exactly the same thing* that might be extremely confusing to a beginner. Especially when reading F# code on various blog posts or projects where you encounter both lightweight syntax and verbose syntax (e.g. older projects or blog posts). Tooltips and F# interactive in Visual Studio 2015 and earlier always display verbose syntax. It essentially forces to the reader to have to know both syntaxes! Then there are also a few cases where there is no equivalent lightweight syntax. While there is lightweight syntax for defining interfaces with at least one member, verbose syntax must be used to define an empty interface (e.g. marker interface) and empty class (e.g. non-constructable type) because there is no lightweight equivalent. On the other hand, there is only (lightweight) syntax for defining abstract classes, which require an attribute (`AbstractClassAttribute`) but there is no attribute for interfaces or classes, which could be used to define an empty interface or empty class.

So syntax consistency could be improved by deprecating verbose syntax and adding equivalent consistent lightweight syntax where required via attributes for interfaces and classes similar to the existing attributes for struct and abstract class.

2. There are two ways of expressing type parameters. E.g. `a' option` (OCaml style) vs. `Option<'a>` (.NET style).

3. Structs are declared and used differently from records. E.g. Struct declaration requires `val` for fields and constructor can only be defined with `new`-keyword, but cannot be pattern matched like other structural types and have a default constructor that is accessible from F#. This issue will fortunately be fixed with the upcoming "struct records", so I consider this a feature that leads to more consistent and more simple syntax.

4. Too many type aliases. E.g. `List = list`, `Option = option`, `float = double`, `float32 = single` seem interchangeable, but they are not. For example, units of measure do not work on these type aliases (i.e. need to use `float32` instead of `single`). I also once had an issue where `List` was somehow different from `list`, but I cannot recall the details. Since the type aliases are probably going to stay, we need to ensure that types and type alias are truly interchangeable.

5. I find it really strange that you can use `^` and `'` for statically resolved type parameters in explicit member constraints interchangeably most of the time (but not always), because the F# compiler will automatically infer/translate `'` to be `^`. It gets confusing when the F# compiler requires an additional space before the first type parameter when you use `^`, but not when you use `'`. Here is a code example:

``` F#
// does not compile because of missing space after <
type GenericClass<^type_parameter when ... >(value : ^type_parameter) ... 
// compiles because of additional space after <
type GenericClass< ^type_parameter when ... >(value : ^type_parameter) ... 
// interprets ' as ^ and compiles despite missing space after < 
type GenericClass<'type_parameter when ... >(value : ^type_parameter) ... 
```

6. Inconsistent allowance of `with`-keyword depending on indentation. I don't recall the details because I have gotten used to a certain style. I will update this issue with a concrete example when I encounter this again.

7. It does not matter whether statically resolved type parameters of explicit member constraints are tupled or curried at declaration, but the compiler only resolves the member when it is tupled in the member implementation. I will update this issue with a concrete example another time.

These were just a few examples from the top of my head. All these examples boil down to **one too many syntactic ways to do exactly the same thing**.

**Comment by dsyme** [comment]
Per CONTRIBUTING.md, please move to http://github.com/fsharp/fslang-suggestions, and garner discussions and votes there, thanks

**Comment by jeroldhaas** [comment]
@dsyme for the sake of high signal, shouldn't discussion occur elsewhere and per-item requests be placed at fslang-suggestions, or prefer discussion there? Please clarify.

**Comment by dsyme** [comment]
This repo is generally for engineering, though some other discussions initiated by Microsoft happen here occasionally. Language design is discussed in fslang-suggestions (for suggestions) and fslang-design (for approved RFCs). In fslang-suggestions I suppose you'll likely get further if you break thing up into individual, independent items. 

I suppose a wholesale language syntax revision may be best explained via a lengthy blog analysis and compatible parser implementation.

**Comment by jeroldhaas** [comment]
@21c-hk can you copypasta the issue here to fslang-suggestions as perhaps an overview issue to reference for individual issues (pending great @dsyme approval ;) )?

**Comment by 21c-HK** [comment]
Whatever @dsyme thinks is best. I was not sure where to post this since this is intended to be a discussion first that is not tied to individual suggestions per se. My examples were just intended to inspire others to post more inconsistencies, not necessarily suggestions that would need to be posted in fslang-suggestions. I wanted to gather feedback first and see how big of a problem this actually is, but I suppose there may be other inconsistencies that other people have encountered.

It may even make sense to have discussions regarding language design in a completely separate (new) repository (e.g. fslang-discussion) if the F# team likes to keep separate repositories like fslang-suggestions and fslang-design for greater focus.

**Comment by 21c-HK** [comment]
What is the final word on this @dsyme? Should I keep the thread here (in which case you can just reopen the issue), should I move it to fs-lang-suggestions, or move it somewhere else?

**Comment by KevinRansom** [comment]
Move it to fslang .... language design happens there ... and this is a language design issue.

**Comment by 21c-HK** [comment]
Done.
