### ISSUE TITLE
Cannot build FSharp.sln from commandline with MSBuild

### ISSUE THREAD

**Issue by JoshVarty** [Microsoft/visualfsharp#1954]
I'm having trouble building `FSharp.sln` using MSBuild on Windows. When I follow the instruction at [DEVGUIDE.md](https://github.com/Microsoft/visualfsharp/blob/master/DEVGUIDE.md#f-compiler-windows) I receive the following errors when using `msbuild FSharp.sln`

```
C:\Users\jovarty\Documents\GitHub\visualfsharp [master ≡]> msbuild .\FSharp.sln
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 12/6/2016 1:19:15 PM.

C:\Users\jovarty\Documents\GitHub\visualfsharp\FSharp.sln(248): Solution file error MSB5023: Error parsing the nested project section in solution file. A project with the GUID "{BF5C6
D92-D053-4216-9C42-B62F5F5C5E91}" is listed as being nested under project "{CFE3259A-2D30-4EB0-80D5-E8B5F3D01449}", but does not exist in the solution.

Build FAILED.

  C:\Users\jovarty\Documents\GitHub\visualfsharp\FSharp.sln(248): Solution file error MSB5023: Error parsing the nested project section in solution file. A project with the GUID "{BF5
C6D92-D053-4216-9C42-B62F5F5C5E91}" is listed as being nested under project "{CFE3259A-2D30-4EB0-80D5-E8B5F3D01449}", but does not exist in the solution.

    0 Warning(s)
    1 Error(s)
```

Please provide a succinct description of the issue.

#### Repro steps

1. Clone visualfsharp repo

2. Run `build.cmd`

3. Run `msbuild FSharp.sln`

#### Expected behavior

The solution and its projects compile properly.

#### Actual behavior

I receive the above errors regarding missing projects.

**Comment by JoshVarty** [comment]
I performed a quick sanity check and confirmed I still see this issue when I use MSBuild v 15.1.371.0 (The version that ships with VS2017 RC)

**Comment by KevinRansom** [comment]
Install:
Dev15 rc2

Select:
C++/Managed Languages and VSIX workloads


Open A VS 2017 Command Window as admin
Cd root of the repo
Build all


Should do it.

**Comment by JoshVarty** [comment]
I installed the C++ workload as I hadn't previously had it installed but I am still getting this error.

The GUID `BF5C6D92-D053-4216-9C42-B62F5F5C5E91` is only found in [`FSharp.sln`](https://github.com/Microsoft/visualfsharp/blob/12213cea55748f05d95b005032839e10501cfba2/FSharp.sln) and I can't tell what it's supposed to refer to.

The GUID `CFE3259A-2D30-4EB0-80D5-E8B5F3D01449` is found in both [`FSharp.sln`](https://github.com/Microsoft/visualfsharp/blob/12213cea55748f05d95b005032839e10501cfba2/FSharp.sln) and [`VisualFSharp.sln`](https://github.com/Microsoft/visualfsharp/blob/12213cea55748f05d95b005032839e10501cfba2/VisualFSharp.sln). It apparently points to `"Tests"` as indicated in:

```
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Tests", "Tests", "{CFE3259A-2D30-4EB0-80D5-E8B5F3D01449}"
EndProject
```

So just to confirm, you're actually able to build `FSharp.sln` using the Developer Command Prompt?

**Comment by KevinRansom** [comment]
Use build all.

fsharp.sln is an artifact that Don uses probably for source colouring and intellisense. I have no idea if it builds or not.

visualfsharp.sln should build the compiler and ide tooling but is not a tool I regularly use

build net40   to build the desktop compiler
build coreclr to build the coreclr compiler
build proto to build the proto compiler
build vs to be the vs addins
build all to build everything including the installers


Kevin

**Comment by JoshVarty** [comment]
Thanks Kevin, I'll use `build all` for now. Going forward I think we should either:

1. Fix `FSharp.sln` and make it buildable.
2. Remove `FSharp.sln`.
3. At least update the documentation so it doesn't tell people to run `msbuild FSharp.sln`

Maybe @dsyme can clarify the purpose of `FSharp.sln` and it'll make it easier to understand how to go forward here.

**Comment by KevinRansom** [comment]
Sounds like a plan.

**Comment by dsyme** [comment]
Please leave FSharp.sln and lets somehow make sure it compiles.  Set up another CI if necessary, or reuse the non-VS one.

Many people coming to this repo are uninterested in the Visual F# IDE tools, or lack the experience and knowledge to understand them. For them, FSharp.sln is a much, much simpler entry point to contributing.  It will also eventually open in Xamarin Studio and elsewhere to allow cross-platform development of the compiler (though not yet CoreCLR).  

It's also what we tell people to open in the main compiler section of DEVGUIDE.md.
