### ISSUE TITLE
Inline functions can't invoke members of module-private types

### ISSUE THREAD

**Issue by kbattocchi** [Microsoft/visualfsharp#1956]
In the below code, the compiler wrongly indicates that the method to be inlined (here, `X::op_Addition`) is inaccessible, but this is not accurate since the calling code is also in the same module.  Manually inlining the call works fine.

    module Repro =
      type private X() =
        static member (+)(_:X,_:X) = 0

      let i = X() + X()

#### Expected behavior

No error.

#### Actual behavior

> error FS0043: The member or object constructor 'op_Addition' is not public. Private members may only be accessed from within the declaring type. Protected members may only be accessed from an extending type and cannot be accessed from inner lambda expressions.

#### Known workarounds

Manually inline the method.

**Comment by dsyme** [comment]
There is a language suggestion open for this somewhere.

**Comment by kbattocchi** [comment]
@dsyme if this is really not considered a bug it would be nice to at least make the error message more accurate - `op_Addition` is public and so the rest of the message is wrong (as is plainly obvious since inlining the code by hand works fine).

**Comment by dsyme** [comment]
> op_Addition is public

I believe it's computed as private because it's in a private type? (in F#, private types can't have public members)

**Comment by kbattocchi** [comment]
But then why can I call it explicitly from elsewhere in the module?  That is, if it were truly private in the .NET sense, this wouldn't work:

    module Okay =
        type private X() =
            static member (+)(_:X,_:X) = 0

        let i = X.op_Addition(X(), X())

The error message makes it seem as though this won't work, but it will.

**Comment by dsyme** [comment]
"private" on a type means "private to the enclosing namespace declaration group or module".

So this gives an error:

```
module Okay =
    type private X() =
        static member (+)(_:X,_:X) = 0

open Okay
let i = X.op_Addition(X(), X())```

**Comment by kbattocchi** [comment]
Right, I get that (it's why I think this behavior is a bug).  My point is that in my initial repro the inlining would occur _within the same module_ as the type definition (and so would be fine, as my latter version of the `Okay` module shows).  However the compiler doesn't allow it and the error message states:

> The member or object constructor 'op_Addition' is not public. Private members may only be accessed from within the declaring type. Protected members may only be accessed from an extending type and cannot be accessed from inner lambda expressions.

This is clearly not true: `op_Addition` _can_ be used outside of the declaring type `X` as long as it's used in the module where `X` is defined, which is all I was trying to achieve anyway.

**Comment by dsyme** [comment]
@kbattocchi Yes, you're right, the error message is poor

However right now all solutions to statically resolved calls must currently be public.  There's an open language suggestion to lift that limitation, in which case this code would indeed compile.

**Comment by abelbraaksma** [comment]
@sdsyme, I've been going over [all issues that mention 'inline'](https://github.com/fsharp/fslang-suggestions/search?q=inline&type=Issues&utf8=✓) but can't find an (open or closed) issue that directly or indirectly addresses this.

Just saying, perhaps we need a new language suggestion for this one.

**Comment by dsyme** [comment]
@abelbraaksma @kbattocchi This is the one https://github.com/fsharp/fslang-suggestions/issues/230
