### ISSUE TITLE
Fully qualified names are not resolved from within their namespace, and namespaces are unknown in the file in which they are defined

### ISSUE THREAD

**Issue by kurtschelfthout** [Microsoft/visualfsharp#1957]
Referring to a type using a fully qualified name (e.g. `NS.MyType`) from within a file in the same namespace (e.g. `NS`) does not work, even if `global` is prefixed (e.g. `global.NS.MyType`). 

In addition, if the namespace isn't defined in a preceding file, the namespace itself is not known from within the file.

#### Repro steps

Here's a project: [Library1.zip](https://github.com/Microsoft/visualfsharp/files/636314/Library1.zip)

In an empty project add the following:

```fsharp
namespace Library1

type AType() = class end

module AModule =
    type AType() = class end

module SO =

    //works
    let t0 = AType()
    //works
    let t1 = AModule.AType()

    //The namespace or module 'Library1' is not defined
    let t2 = Library1.AType()
    //The namespace or module 'Library1' is not defined
    let t3 = global.Library1.AType()
```

Then add another file containing just:

    namespace Library1

before the file above. Now F# knows about the namespace, but can't resolve the type:

```fsharp
    //The value, constructor, namespace or type 'AType' is not defined
    let t2 = Library1.AType()
    //The value, constructor, namespace or type 'AType' is not defined
    let t3 = global.Library1.AType()
```

#### Expected behavior

All these names should resolve as normal.

#### Actual behavior

The names are not resolved.

#### Known workarounds

Don't use the fully qualified name.

#### Related information 

VS 2015, F# 4.0 on windows.

Probably not a big deal by itself, but can produce confusing behavior/error messages down the line, see e.g. here: http://stackoverflow.com/questions/40997380/how-to-pass-a-type-as-a-an-an-attribute-parameter-using-f-syntax/40998066?noredirect=1#40997380

**Comment by forki** [comment]
can you please upload a project as zip with the repro? would like to take a look at this.

**Comment by kurtschelfthout** [comment]
@forki done.

**Comment by forki** [comment]
urgs that looks pretty serious. Put a BType in the first file and that type get's resolved correctly.
So it looks the resolver is only taking the first file into consideration.
Or to be more concrete it is only taking types from namespaces in files that were already processed.

**Comment by forki** [comment]
if you put `namespace Library2` just before the `module SO =` line, then the resolver will find the AType in Library1. So I assume it's not in name env until the namespace is fully processed.

**Comment by dsyme** [comment]
> Or to be more concrete it is only taking types from namespaces in files that were already processed.

This seems to be by design? You can't recursively refer to the contents of the namespace declaration group until it has been processed, unless you use ``namespace rec``.

**Comment by forki** [comment]
yeah didn't find a way to make it work. gave up

**Comment by kurtschelfthout** [comment]
> This seems to be by design? You can't recursively refer to the contents of the namespace declaration group until it has been processed, unless you use namespace rec.

I think that explains technically why defining the namespace first in a separate file allows you to reference  it (though it still feels weird). 

But why can we refer to `AType` unqualified, but not using the fully qualified name?

**Comment by dsyme** [comment]
> But why can we refer to AType unqualified, but not using the fully qualified name?

Which specific lines do you mean? thanks

**Comment by abelbraaksma** [comment]
> This seems to be by design?

If this is by design, I think we should fix the design. I have been bitten more than once by this (the SO question was raised by me not realizing this limitation in attributes), but if that's not a good argument (I know, it isn't), it simply isn't consistent and defies all we know about namespaces.

The self-reference module-limitation makes some sense: a module can appear only once anyway and you may consider it a visual aid to see unprefixed names to be either global, autoopen or from the current module.

But that argument doesn't fly with namespaces. A namespace is not resolved fully in the first file it appears in. And besides, when you hover over any type you see its FQN, but even if you type it over literally (which is what I did) it will still give you a type error. Also, you could argue it's common knowledge for .NET programmers that you can always access a type by either its short name (if it is in scope by a "using" or "open") or its fully qualified name (FQN).

I doubt this is hard to fix (either by the tokenizer or by virtually inserting an empty namespace file before the current new namespace) and could potentially resolve a lot of questionable headbanging situations.

**Comment by dsyme** [comment]
@abelbraaksma I sympathise with this POV.  Please open an fslang suggestion and link here.  

It's surprisingly hard to fix this without introducing a lot more mutability to internal compiler data structures.

**Comment by forki** [comment]
From what I already know the AType can be found in the name resolution environment. But only as local unqualified name. So whenever we put it there we should also put it into the other qualified maps. But I didn't find that place. And I look quite a while in debugger.

**Comment by kurtschelfthout** [comment]
>>But why can we refer to AType unqualified, but not using the fully qualified name?

>Which specific lines do you mean? thanks

May be moot by now, but just to close the loop:

    //works
    let t0 = AType()
    
    // 'AType` is not defined (if Library1 is defined in different file) or `Library1` is not defined (if not)
    let t2 = Library1.AType()

**Comment by cartermp** [comment]
Based on @dsyme comment, can this be remade into a language suggestion in https://github.com/fsharp/fslang-suggestions
