### ISSUE TITLE
[ VS2017 RC ] Parse errors not going away when the code is fixed

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#1961]
VS2017 RC master 

Parse errors are not going away when the code is fixed

#### Repro steps

Provide the steps required to reproduce the problem

1. Start with this in a script:

![capture13a](https://cloud.githubusercontent.com/assets/7204669/20973034/f413e124-bc8e-11e6-9536-ded7afcd4fda.PNG)

2. Edit to this:

![capture13b](https://cloud.githubusercontent.com/assets/7204669/20973041/f999e1a2-bc8e-11e6-9373-2bbed7963aef.PNG)

#### Expected behavior

The error should no longer show at the end of the script

#### Actual behavior

The error is still there

#### Known workarounds

It's very problematic as the wrong red squigglies end up all over your script

**Comment by vasily-kirichenko** [comment]
Isn't it duplicates https://github.com/Microsoft/visualfsharp/issues/1925?

**Comment by dsyme** [comment]
@vasily-kirichenko Yes it is.  I'm looking at it now.
