### ISSUE TITLE
QuickInfo doesn't truncate members on Async<'T> when code is invalid

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1973]
Using latest master, in any function, type the following invalid code:

`let foo = Async<int>`

Then hover over `Async`.

**Expected:** A typical `Async` hover with the members truncated, but with the error message at the bottom.

**Actual:**

![async-huge](https://cloud.githubusercontent.com/assets/6309070/21038818/b76a2a76-bd8d-11e6-9088-845adfa935c3.PNG)

I've been trying to reproduce this in a more general case, but so far only `Async` seems to be the culprit.

Although this is a bit left field, it could be harmful for people first learning the language getting blasted by the IDE for typing stuff incorrectly.

**Comment by dungpa** [comment]
What do you expect to see?

**Comment by cartermp** [comment]
Updated

**Comment by cartermp** [comment]
This was fixed in #2070.
