### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1974]
#### Repro steps

1. Open `VisualFSharp.sln`
2. Open `service.fs` file
3. Wait for semantic colorization to appear
4. Look at `devenv.exe` private set size, it's about 2GB

![image](https://cloud.githubusercontent.com/assets/873919/21042759/8a5b8f12-be04-11e6-82b6-ea411432e528.png)

#### Expected behavior

Never consume more than 2GB, preferably less than that.

#### Actual behavior

Features like Document Highlight and Inline Rename take up to 20 seconds to complete, even without any changes in files. One of CPU cores is loaded at 100%. Occasional UI freezes (supposedly due to blocking GC).

#### Known workarounds

Do not open any files in large projects.

#### Related information 

* master branch

**Comment by forki** [comment]
Lol I like that workaround.

Am 09.12.2016 09:49 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
I've noticed that we have `keepAllBackgroundResolutions` parameter set to `true` (default) here https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/LanguageService.fs#L51. Is it intentionally?

**Comment by cartermp** [comment]
Yeah, `service.fs` is really difficult to work in right now.

@dsyme would you know more?

**Comment by dsyme** [comment]
Yes, looking at https://github.com/fsprojects/VisualFSharpPowerTools/issues/848 it seems that keepAlBackgroundResolutions should be false
