### ISSUE TITLE
`Document.Solution.Projects` contains current project only

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1975]
For this solution:

![image](https://cloud.githubusercontent.com/assets/873919/21046114/2031b14c-be14-11e6-9ec8-ec51a69b4b7e.png)

`Solution.Projects` collection contains current project only:

![image](https://cloud.githubusercontent.com/assets/873919/21046160/5287dee6-be14-11e6-9fa4-08b93c0122ff.png)

It blocks implementing solution wide refactorings like Inline Rename.

**Comment by vasily-kirichenko** [comment]
Aha! it turns out a project appears in `Solution.Projects` collection as any file that belongs to it is opened:

![image](https://cloud.githubusercontent.com/assets/873919/21046285/03fabea0-be15-11e6-920b-4772a3bf88bc.png)

**Comment by vasily-kirichenko** [comment]
C# has this interface http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.CSharp/ProjectSystemShim/Interop/ICSharpProjectHost.cs,836c27d8580b5238 implemented in its language service http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.CSharp/LanguageService/CSharpLanguageService_ICSharpProjectHost.cs,19 but it's unclear who and when calls this method.

**Comment by vasily-kirichenko** [comment]
It affects Go to definition, too.

1. Open `VisualFSharp.sln`
2. Open `DocumentDisagnosticAnalyzer.fs`
3. Try to Go to definition on `FSharpErrorInfo`
4. It does not work:

![image](https://cloud.githubusercontent.com/assets/873919/21058211/01c71b4a-be4e-11e6-9569-9f35aaba3a7d.png)

5. Open `IncrementalBuild.fsi`
6. Wait until semantic colorization appears (or don't wait and go right to the next step, but in this case "navigating to..." dialog will appear)
7. Close it.
8. Repeat step 3.
9. It works:

![1](https://cloud.githubusercontent.com/assets/873919/21058367/a74e9124-be4e-11e6-9507-47f67f11a9bd.gif)

In my opinion this is the most harmful bug at the moment.

**Comment by vasily-kirichenko** [comment]
As I understand, projects are added to `Solution` here https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/LanguageService.fs#L230 which is called only when a document is being opened, see `SetupNewTextView` here https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/LanguageService.fs#L297. 

So what we need is to call `SetupProjectFile` for each project in a solution when it's loading.

**Comment by cartermp** [comment]
@vasily-kirichenko Great analysis.  I agree, this is a high-priority thing that needs to be fixed.

**Comment by OmarTawfik** [comment]
@vasily-kirichenko @cartermp I believe this is because of F# lacking complete integration with Roslyn project system. The project system would need to update the Roslyn work space with other projects in the solution.

**Comment by vasily-kirichenko** [comment]
@OmarTawfik Yes, I understand all projects should be "registered" in `Solution`, but I have no idea _when_ and _who_ can do this. Any pointers?

**Comment by dungpa** [comment]
@vasily-kirichenko I sent this PR https://github.com/Microsoft/visualfsharp/pull/1990. Hope it could help to find a viable solution.

**Comment by OmarTawfik** [comment]
@vasily-kirichenko this is part of integrating F# into CPS (see #1193 for more info).
Perhaps @KevinRansom or @cartermp would have more insight on this.

**Comment by vasily-kirichenko** [comment]
We should fix it in ~~hacky~~ any way that works because Find All References / Inline Rename and Navigate To do not work properly. Navigate To is especially useless, because it must search in all projects in solution.

**Comment by dungpa** [comment]
@vasily-kirichenko I plan to send a PR during the weekend. If you figure it out before then, go ahead.

**Comment by vasily-kirichenko** [comment]
@dungpa Great. I will inform you if I do anything with this.

**Comment by cartermp** [comment]
Tagging for RTM, since it's definitely an important improvement.
