### ISSUE TITLE
Build Action: None still shows syntax errors and coloring

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#1977]
If you change the _Build Action_ of an F# file inside Visual Studio to `None`, and you open it, it will still show syntax errors and the Error List will still show errors.

Comparing this to other languages, i.e. C#, they don't show the errors. In fact, I think it makes sense that if the Build Action is `None` it should not even be parsed (though admittedly, the syntax coloring is useful, albeit confusing: it suggests it is build, a dimmed color would make more sense).

## Repro steps

Create a solution with an `*.fs` file that contains errors. Change the _Build Action_ to `None`, open the file in Visual Studio.

## Expected behavior

No errors are shown.

## Actual behavior

Errors are shown.

## Known workarounds

Ignore the errors (you can build, when you build the errors don't show up in the build log, but this is confusing).

## Related information 

Tested this with VS2015 Update 3, but it was apparent on earlier versions of F# and VS. Tested this with `devenv.exe /SafeMode`.

For the C# comparison, some syntax errors are caught regardless, like a missing semicolon, but incorrect identifiers, duplicate definitions, non-existing usings, invalid operators etc won't show any error. I think the C# parser does too much here, it shouldn't show any error (build action _None_ means _None_), but that is outside the scope of this forum.

_(Aside: I use the `Build Action: None` a lot as a quick way of removing files from the build, if removing from the build but keeping them makes more sense than removing them completely. This is simply because the F# build is quite slow esp. when files contain a lot of inlining or static member constraints. When not needed, excluding them can save seconds, even minutes during builds.)_

_(Another reason for using this if you have two versions of one source, where depending on build settings you need one of them and you flip the build action from `None` with MSBuild conditionals.)_

**Comment by dsyme** [comment]
This is by design, we have always shown errors in out-of-project files

**Comment by abelbraaksma** [comment]
@dsyme, while I can live with your resolution, there seems to have been a change in how this is handled since the latest update of VS2017 with Preview 6.

Maybe this should then be a bug, but I like how it is now, as when I open a file that has action other than Compile, it clearly indicates that now by removing the syntax coloring completely and the squigglies have disappeared too. I think this is a good new direction the VS team took: 

![image](https://user-images.githubusercontent.com/16015770/28698246-5968fe1e-7342-11e7-9d40-812c83d5ad74.png)
