### ISSUE TITLE
QuickInfo tooltips should line wrap

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1979]
On latest master, hover over a type with a very long sentence in its information, such as `Async.FromBeginEnd`.

**Expected:** Long summaries like this are line wrapped to ~100 chars or so.

**Actual:**

<img width="1677" alt="screen shot 2016-12-09 at 10 03 50 am" src="https://cloud.githubusercontent.com/assets/6309070/21059447/59622d06-bdf7-11e6-804b-58fc10b4732d.png">

**Comment by vasily-kirichenko** [comment]
Does it look better?

![image](https://cloud.githubusercontent.com/assets/873919/21059853/81ac10d4-be55-11e6-9c5f-aa5cb5540b09.png)

**Comment by cartermp** [comment]
@vasily-kirichenko  Hmmm.  I think it should still be shorter in width, but I'm seeing that C# does basically the same thing that you've got in your screenshot.  I think that's fine for now.

**Comment by vasily-kirichenko** [comment]
We can set any width for QuickInfo (but not for errors). This is what it looks like for width = 400 on 4K screen:

![image](https://cloud.githubusercontent.com/assets/873919/21060849/aca98988-be5a-11e6-981a-67b5d3efa07d.png)

**Comment by cartermp** [comment]
Yeah, I think the wrapped text like that can actually be worse.  We'll probably have to re-evaluate tooltips for F# post-vs2017, but I think your PR which does the line wraps is good for vs2017.

Might be able to play around with width to see if we can shorten it to a point where no signatures wrap, but I wouldn't prioritize that.

**Comment by abelbraaksma** [comment]
> Expected: Long summaries like this are line wrapped to ~100 chars or so.

@cartermp, this is not just on the _latest master_. On VS2015, Update 3, with F# 4.0 (and, iirc also for older VS and older Updates), function summaries on one line are not linewrapped. For my own function library I added `<para>`, but this is obviously the wrong approach (as I need to remove them when creating online references).

Here it is on VS2015, Update 3, F# 4.0

![Ugly tooltip](http://i.imgur.com/X1WNBbo.png)

If this is somewhere configurable (however hidden it may be), that would be awesome. You can never predict what font sizes and window sizes other programmers are accustomed to.

I'd assume this won't be back-ported into the VS2015 branch of things?

_(note 1: I thought I reported this previously, but couldn't find it back, big deja-vu feeling here)_
_(note 2: It may seem like a small bug, but it really makes using F# "feel" more mature, I think it is a two-thumbs-up improvement)_
_(note 3: C# has the same issue, iirc, but I've no problem in getting "better" than C# in editing experience)_

**Comment by cartermp** [comment]
@abelbraaksma Yeah, I think configurability is something we could investigate, and hopefully push further downstream so that C#/VB can benefit as well.

> I'd assume this won't be back-ported into the VS2015 branch of things?

I don't think so, no.  The mechanism behind tooltips is powered by Roslyn infrastructure that we only support in F# for vs2017 and onward.  That's the plan for now, anyways.

**Comment by abelbraaksma** [comment]
I can live with that, we can't keep living in the past anyways (I dread that I still have to maintain some projects in VS2010..., but that's totally OT here)

**Comment by cartermp** [comment]
In my previous job I had to modify a web app in vs2005 🙂.  Took a few days to get it to compile...
