### ISSUE TITLE
Indentation falls back to column 0 after second line break

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#1980]
In latest master, type the following:

```fsharp
let getStringAsync(str: string) = async { return str }

let fooAsync() = async {
    let! str1 = getStringAsync "hello"    
}
```
Now, hit enter.  Notice that the cursor is at the same column as the above `let!` binding,  column 5:

```fsharp
let getStringAsync(str: string) = async { return str }

let fooAsync() = async {
    let! str1 = getStringAsync "hello"    
//  |  <--- cursor is here
}
```

Now, hit enter again:

**Expected:** Cursor is on a new line, and still on column 5.

**Actual:** Cursor is at column 1.

<img width="414" alt="screen shot 2016-12-09 at 11 00 36 am" src="https://cloud.githubusercontent.com/assets/6309070/21060903/c0a7ddb0-bdfe-11e6-8a8a-ae2bc1364f53.png">

**Comment by vasily-kirichenko** [comment]
Yes, it's an annoying bug.

**Comment by cartermp** [comment]
@abelbraaksma Thanks for pointing that out!  We should definitely address that if it's feasible for this release.
