### ISSUE TITLE
Should we update Microsoft.CodeAnalysis.XXX packages to RC?

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1982]
For example https://www.nuget.org/packages/Microsoft.CodeAnalysis.Features/2.0.0-rc

We use beta-6 at the moment. RC has breaking changes (namespace renamed, API changed, etc.)

**Comment by cartermp** [comment]
I think we should, yes, but I'll let @KevinRansom or @Pilchie make the call here.

**Comment by Pilchie** [comment]
@vasily-kirichenko Do we depend on any of those breaking changes?  If so, then we definitely need to update, or we'll end up with TypeLoadException/MissingMethodException.

If not, we should do so as soon as it is convenient.

**Comment by vasily-kirichenko** [comment]
@Pilchie I'm not sure if we depend on any of API breaking changes, it's easier to just update to RC and fix errors if any.
I've updated to RC in `find-all-references` branch and everything works OK, so I don't think we will have problems with it.

**Comment by Pilchie** [comment]
We should be publishing the RC2 packages shortly, and we should probably update to those.

**Comment by vasily-kirichenko** [comment]
Done.
