### ISSUE TITLE
Build errors are not shown in Error List window

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#1988]
Current master:

![1](https://cloud.githubusercontent.com/assets/873919/21079219/0d8516c2-bf9c-11e6-8b98-e03b404182fc.gif)

**Comment by forki** [comment]
yes this looks like a regression to VS2015

**Comment by dungpa** [comment]
@vasily-kirichenko @forki Does anyone have any hint? I think the integration between FSC errors  and VS error list goes wrong, but I have no idea where.

**Comment by vasily-kirichenko** [comment]
@dungpa I'm aware about two points where errors are reported to Roslyn: https://github.com/Microsoft/visualfsharp/tree/master/vsintegration/src/FSharp.Editor/Diagnostics

**Comment by dungpa** [comment]
I don't think that is it. The error comes from MSBuild, it should be related to https://github.com/Microsoft/visualfsharp/blob/baebacb434a084853c57023750695279ae61898c/vsintegration/src/FSharp.ProjectSystem.Base/Project/IDEBuildLogger.cs

**Comment by forki** [comment]
Sorry I have no idea

Am 16.12.2016 8:36 nachm. schrieb "Anh-Dung Phan" <notifications@github.com
