### ISSUE TITLE
F# code in Visual Studio 2015 has Keep Tabs = true

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#199]
I installed Visual Studio 2015 CTP5 without any particular change of settings. F# code seems to have Keep Tabs = ``true`` by default.  This should be ``false``

![capture](https://cloud.githubusercontent.com/assets/7204669/5994396/b7bd3aee-aa3f-11e4-8144-c69aa57549c0.JPG)

**Comment by dsyme** [comment]
It would be good if someone could verify if this not just some quirk of my machine

**Comment by dungpa** [comment]
My installation shows "Insert spaces" as the default option.

**Comment by dsyme** [comment]
Well, that's strange.  I can't imagine why mine would be showing "TABs"....

**Comment by rojepp** [comment]
@dsyme Could it be that it inherited from 'All languages' when updating?

**Comment by enricosada** [comment]
i tried using a new azure vm (the vs 2015 ctp from gallery), is ok for me ( `insert spaces` )

The default of `All Languages` is not set

**Comment by dsyme** [comment]
I'll close this for now since no one else can repro. But let's keep an eye on this - there must be some logical explanation for how I got the Tabs setting on my machine.

**Comment by enricosada** [comment]
@latkin reopen this one so?
If you have ideas about how to procede. There is an vs installation log?

**Comment by enricosada** [comment]
@latkin can you reopen this one pls? the other is a duplicate, but i have this issue in my installation (VS2015 RC see #413 )

Also the c# file configuration is the same, with insert tabulation instead of space

**Comment by latkin** [comment]
I do see this in clean test installs, as well.

Weird because in the settings file for the General profile (which I think is inherited by the F# profile) there is explicit config for F# language to use spaces, not tabs.  I will try to poke around a bit, that config is part of closed VS platform code.

**Comment by enricosada** [comment]
@latkin Take a look at c# page too. Default is tabs there instead of spaces ( wrong )

Maybe you can also raise the priority because is really bad. New file, write write and doesnt work. 
Is difficult to understand is a tabs vs spaces problem. For new user is really difficult

**Comment by jcansdale** [comment]
Does the F# compiler treat a single tab as being equal to a space?

**Comment by enricosada** [comment]
Tabs are compile time error
