### ISSUE TITLE
Document preview doesn't work for F# documents

### ISSUE THREAD

**Issue by rojepp** [Microsoft/visualfsharp#1993]
In latest master, Arrow up/down in Solution Explorer. Note that moving to a C# file opens it in the editor, in preview mode. This doesn't happen for F# files.

![arrow](https://cloud.githubusercontent.com/assets/445888/21083377/3f352a42-bfef-11e6-840f-6105e48eaf58.gif)

#### Expected behavior

Preview should open

#### Actual behavior

Nothing happens

**Comment by cartermp** [comment]
Closing as duplicate of #1763.
