### ISSUE TITLE
F# .NET Core in Visual Studio status

### ISSUE THREAD

**Issue by Biarity** [Microsoft/visualfsharp#1994]
Is there a plan to add F# .NET Core support to Visual Studio so enable scaffolding .NET Core projects like C# (without using the CLI)?

Sorry if this is the wrong place to ask this, feel free to redirect me as you wish. I've had a look at [this page](https://github.com/Microsoft/visualfsharp/wiki/F%23-for-CoreCLR---Status)  but it's still unclear to me if that's the Visual Studio F# effort.

**Comment by cartermp** [comment]
@Biarity Yep!  We're still holding off on shipping templates in VS because the .NET Core SDK is still in preview, but we plan on having templates for .NET Standard and .NET Core.

**Comment by Biarity** [comment]
IMO that's the final step needed for a truly cross-platform F#. Thanks for efforts!

**Comment by xperiandri** [comment]
@cartermp, please ship F# project templates for analyzers and refactorings so that community could quickly implement missing features like:
- add enum member
- add DU member
- extract into function
etc.
