### ISSUE TITLE
Support for Structure Guide Lines

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#1997]
F# is a language for whom indent guides are super useful.  Roslyn provides support for indent guildes we should enable indent guides for F#.

**Comment by forki** [comment]
Wtf is that?

Am 12.12.2016 8:26 nachm. schrieb "Kevin Ransom (msft)" <
notifications@github.com>:

**Comment by cloudRoutine** [comment]
![](http://i.imgur.com/73GpCMK.png)

![](http://i.imgur.com/dPMNVkG.png)

[Indent Guides](https://marketplace.visualstudio.com/items?itemName=SteveDowerMSFT.IndentGuides)

**Comment by vasily-kirichenko** [comment]
we have logic that calculates positions of indent guides, it's a bit buggy but worth to port I think.

**Comment by rojepp** [comment]
From the screens, it seems it doesn't follow the source code structure, but rather fixed at whatever VS is set to (4).

**Comment by Pilchie** [comment]
Tagging @cyrusnajmabadi - can you point to the Roslyn APIs needed to implement this for F#?

**Comment by cloudRoutine** [comment]
@vasily-kirichenko i'm not sure it's worth porting, I think we could make a better version using the same UAST traversal we use for outlining. `DepthParser.fs` is just a worse version of it, they're fundamentally looking for the same range information before they do their own sets of filters and transformations on them.

**Comment by vasily-kirichenko** [comment]
I suspect it's a single "structure" roslyn service, providing which automagically enables both outlining and the guides.

**Comment by CyrusNajmabadi** [comment]
Yes.  Roslyn uses a single service to enable all these scenarios.  You need to provide your own implementation of "BlockStructureService" to make this work.  

Let me know if you need any more info.

**Comment by KevinRansom** [comment]
fixed
