### ISSUE TITLE
Label F# PCL projects such that it's obvious which ones support Xamarin

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#2]
Some of the F# PCL libraries support profiles 78 and 259 (support for consumption by Xamarin projects) but this isn't obvious when looking at the project descriptions when looking at them in visual studio. Someone developing a platform independent library intending to support Xamarin has no way of knowing these profiles will do what they want. I had to ask in a chat room in order to find out. Some sort of indication that these projects support profiles 78 and 259 would vastly improve discoverability.

comments
>KevinRansom wrote Jan 2 at 10:49 AM [x] 
>I agree we should do something to make this clearer, after all Android and IOS programming are >very important use cases these days. Also the Visual Studio 2015 previews ship with a breadcrumb >to download the Xamarin VS add-in.
>
 >What do others think ?
>
> Kevin

>>latkin wrote Jan 5 at 9:12 AM [x] 
>>I agree it would be helpful to include the profile number in the project description. We could just >>add "(profile 259)" or similar at the end.

>>>mydogisbox wrote Jan 5 at 9:43 AM [x] 
>>>Is there some way to make it more obvious than just the profile number? Unless someone is >>>familiar >with the meaning of profile numbers (I'm not), then they're just going to go off of the list >>>of supported >platforms which imply that it won't be consumable by Xamarin projects.

>>>>latkin wrote Jan 5 at 10:09 AM [x] 
>>>>We have no control over how or if Xamarin chooses to use various portable profiles. They might >>>>add/drop/modify support for how these map to iOS or Android. And Xamarin is not, generally >>>>speaking, the only consumer of these libraries. So I think we should just stick to the facts.

>>>>>mydogisbox wrote Jan 5 at 10:39 AM [x] 
>>>>>Ah, I didn't think of that. I guess that would be on Xamarin's end to publish which profiles they >>>>>support then.

**Comment by latkin** [comment]
@KevinRansom you have a string change prepped, correct?

**Comment by KevinRansom** [comment]
it's fixed.with [commit e3c08a19](https://github.com/Microsoft/visualfsharp/commit/e3c08a19fce08ebcb0c0f40291599e5b9112492e#diff-2dc200944822198fedeedefac4cab86b)
