### ISSUE TITLE
Publish "F# Tools For Visual Studio 2015 Preview" releases on GitHub releases

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#20]
https://twitter.com/Codecutterman/status/555772302692872192 shows that previews are still published  on Codeplex. One day this should move to Github. Very low prio - just as reminder ;-)

**Comment by KevinRansom** [comment]
I pushed it there because it is not clear to me where to publish binaries on Github, but that is undoubtedly due to how new I am to it.

Can you drop me a line, letting me know what you think is the best way to go about this.

Thanks

Kevin

**Comment by forki** [comment]
This is how we do it in ProjectScaffold like projects:

Github has a "releases" page: See https://github.com/fsprojects/Paket/releases for Paket
For Visual F# this would be: https://github.com/Microsoft/visualfsharp/releases

Releases can be edited manually via the UI or via the [Github HTTP API](https://developer.github.com/v3/repos/releases/).
Usually a release corresponds to a git tag (that you have to push before). I'm not completely sure if you can do releases without tags.

You will probably start to edit these manually, but later after applying #15 you might want to look at https://github.com/fsprojects/Paket/blob/master/build.fsx#L286 to see how FAKE can help here.
In ProjectScaffold-like projects we have a release.cmd which does everything in one click. This includes build, test, docs and release to github.

More docs about this can be found at http://fsprojects.github.io/ProjectScaffold/release-process.html
