### ISSUE TITLE
MSBuild: F# copies too many assemblies, even if CopyLocal=false

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#2005]
I was investigating why a bunch of unexpected assemblies were copied to our build output. It turns out there is a slight difference in how C# and F# treat assemblies where CopyLocal is set to false.

### Repro steps

(I have attached a full solution at the end.)

There are two assemblies (not projects) **CSharpA** and **CSharpB** where **CSharpB** references **CSharpA** . Both assemblies are in a directory dep.

I have a solution with 3 projects:

**CSharpC**: C# lib which references **CSharpB** with CopyLocal=false
**CSharpCopyLocalTest**: C# Exe which references **CSharpB** with CopyLocal=false and has a project reference to **CSharpC** with CopyLocal=true.
**FSharpCopyLocalTest**: F# exe which references **CSharpB** with CopyLocal=false and has a project reference to **CSharpC** with CopyLocal=true.

### Expected behavior

When I build the C# project, the output directory contains

![image](https://cloud.githubusercontent.com/assets/4236651/21165914/935d8042-c1a2-11e6-9b98-15feaf900a96.png)

### Actual behavior

When I build the F# project, the output directory contains
![image](https://cloud.githubusercontent.com/assets/4236651/21165938/b439d194-c1a2-11e6-9947-6037575c9a77.png)

Note how it contains CSharpA, but not CSharpB (I would have expected neither), so the issue seems to be when it calculates the closure of all referenced assemblies.

#### Notes

It does not copy CSharpA if I remove the reference to CSharpB and keep the reference to CSharpC.
It also does not copy CSharpA if I remove the project reference to CSharpC.

Also, when taking a look at the detailed log (building from command line):
![image](https://cloud.githubusercontent.com/assets/4236651/21166221/6b0ac076-c1a4-11e6-8d88-477827774f94.png)
It copies CSharpA from the directory dep.

### Known workarounds

I can either ignore them, or remove them manually from the build output after compile. But in my real case, a rather large number of DLLs is additionally copied, and I don't know (without hardcoding a list somewhere) which DLLs should be removed and which should be kept.

### Related information 

Provide any related information 

* Operating system: Win 10
* Branch: VS2015 Update 3
* Indications of severity: a bit annoying, currently this causes our setup to be ~50 MB larger than it could be.

[FSharpCopyLocalTest.zip](https://github.com/Microsoft/visualfsharp/files/650583/FSharpCopyLocalTest.zip)

**Comment by dsyme** [comment]
I don't know anything in F# that could possibly be causing this. It must surely be an MSBuild issue

**Comment by 0x53A** [comment]
Since there is a difference between C# and F#, it's probably down to something in FSharp.targets, but it is such a corner case that I personally don't really care.

**Comment by dsyme** [comment]
Yeah, I know the F# targets files well and I don't think it's anything there.  And the C# ones are impossible to read
