### ISSUE TITLE
Cannot build VisualFSharp solution

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2006]
RC2, current master. It's the same error @forki encountered in https://github.com/Microsoft/visualfsharp/pull/1996

> "E:\github\visualfsharp\build-everything.proj" (default target) (1) ->
"E:\github\visualfsharp\vsintegration\fsharp-vsintegration-vsix-build.proj" (Build target) (34) ->
"E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj" (Build target) (38) ->
(GetVsixDeploymentPath target) ->
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(612,5): error MSB4018: The "Get ExtensionsPath" task failed unexpectedly.\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(612,5): error MSB4018: System.IO. FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Settings.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken =b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFS harpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(612,5): error MSB4018: File name: 'Microsoft.VisualStudio.Settings.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'\r [E:\github\visualfsharp\vsintegra tion\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(612,5): error MSB4018: at Micr osoft.VsSDK.Build.Tasks.GetExtensionsPath.Execute()\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource. csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(612,5): error MSB4018: at Micr osoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r [E:\github\visualfsharp\vsintegration\Vsix\VisualF SharpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(612,5): error MSB4018: at Micr osoft.Build.BackEnd.TaskBuilder.d__26.MoveNext()\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\V isualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(612,5): error MSB4018: \r [E:\git hub\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(612,5): error MSB4018: WRN: Assem bly binding logging is turned OFF.\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(612,5): error MSB4018: To enable
assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.\r [E:\github\visualfsharp\vsinte gration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(612,5): error MSB4018: Note: Ther e is some performance penalty associated with assembly bind failure logging.\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSourc e\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(612,5): error MSB4018: To turn th is feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharp OpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.25929-RC2\tools\vssdk\Microsoft.VsSDK.targets(612,5): error MSB4018: [E:\githu b\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]

**Comment by vasily-kirichenko** [comment]
Solved:
1. `build.cmd vs` - failed as above.
2. Open `VisualFSharp.sln` in VS 2017 RC2.
3. Build it - failed.
4. Restart VS.
5. Open `VisualFSharp.sln`
6. Build it - success.

**Comment by cartermp** [comment]
@vasily-kirichenko In the pastI run `build vs` and then `msbuild VisualFSharp.sln` before `.\VisualFSharp.sln` and it always worked.  Does that work for you in RC2?  I haven't had the chance to build the bits yet

**Comment by brettfo** [comment]
It looks like there was an issue restoring NuGet packages.  `Microsoft.VisualStudio.Settings.15.0` is specified in `vsintegration\packages.config` which is restored in [`build.cmd`](https://github.com/Microsoft/visualfsharp/blob/master/build.cmd#L462) which is dependent on the `%BUILD_VS%` variable being set to `'1'` which happens [here](https://github.com/Microsoft/visualfsharp/blob/master/build.cmd#L149).

Does your `packages` directory contain `Microsoft.VisualStudio.Settings.15.0`?  If you manually run NuGet restore on `vsintegration\packages.config` does it show up?

**Comment by vasily-kirichenko** [comment]
I'm on current master now, the issue is still here. `packages` folder:

![image](https://cloud.githubusercontent.com/assets/873919/21223194/f992fff6-c2d6-11e6-9bf2-de796e2d9cd1.png)

the assembly is actually there:

![image](https://cloud.githubusercontent.com/assets/873919/21223207/0eb1e65e-c2d7-11e6-9cd4-c98cdc90a034.png)

### Try remove all untracked files with `git clean -d -f -q`, then run `build.cmd vs` ###
