### ISSUE TITLE
VS RC2 uses newer Microsoft.CodeAnalysis.XXX assemblies than available via NuGet packages

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2009]
Modules loaded by VS 2017 RC2:

![image](https://cloud.githubusercontent.com/assets/873919/21180720/5b1ada68-c20b-11e6-8066-004f7d787473.png)

Version available via RC nuget packages:

![image](https://cloud.githubusercontent.com/assets/873919/21180749/75961cf4-c20b-11e6-9e11-b69fcbd0a413.png)

As a result, Navigate To does not work:

![image](https://cloud.githubusercontent.com/assets/873919/21180770/88708cb0-c20b-11e6-98e2-24ee5fd6d432.png)

see https://github.com/Microsoft/visualfsharp/pull/1958#issuecomment-267010118

**Comment by cartermp** [comment]
@Pilchie Is it possible to publish another prerelease of Microsoft.CodeAnalysis that matches what RC2 uses?

**Comment by Pilchie** [comment]
I believe the RC2 packages were published this morning.

**Comment by vasily-kirichenko** [comment]
@Pilchie Yes, they were. Thanks!

**Comment by vasily-kirichenko** [comment]
Hm. I updated my branch to use RC2 packages, but it has not helped. Same error :(

**Comment by vasily-kirichenko** [comment]
The versions of assemblies that loads VS and ones from the packages are same.

**Comment by Pilchie** [comment]
Is it *exactly* the same error?  That's odd, since that looks like the F# binary is missing a method.

**Comment by vasily-kirichenko** [comment]
Yes, exactly the same error. I've clean the working dir and rebuilding everything, maybe some assemblies were not updated.

**Comment by vasily-kirichenko** [comment]
Yes, I was right. I even cannot build FSharp.Editor - assemblies lay in different directories now.

**Comment by vasily-kirichenko** [comment]
@cartermp @KevinRansom maybe you guys could update the packages the right way? I'm not sure I'm doing it properly.

**Comment by Pilchie** [comment]
Tagging @brettfo too.  Can you take a look here?

**Comment by brettfo** [comment]
I've just created #2013.

**Comment by vasily-kirichenko** [comment]
The problem is gone, thanks.
