### ISSUE TITLE
FS1125 The instantiation of the generic type 'x' is missing and can't be inferred ..., should not be thrown if type is inferred correctly

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#2014]
The warning from the title is thrown with the following example, but I don't think it is necessary to throw as the type is properly inferred and the code can be run. The warning suggests smoke without fire...

## Repro steps

Copy this code in the code editor and you should see the warning squiggles (please don't blame the silly example, I came to this after cutting away a lot of code):

```
type XData2<'T, 'U> = {
        CreateString : 'T -> string
        RunStr : string -> 'U
    } with

    static member SetCreate xp xd = { xd with CreateString = xp }
    static member SetRunStr run xd = { xd with RunStr = run }

module XData2 =
    let empty() =
        {
            CreateString = fun _ -> String.Empty
            RunStr = fun _ -> Unchecked.defaultof<_>
        }

    let tempting =

        empty()
        |> XData2.SetCreate (fun i -> sprintf "this is it: %i" i)  // FS1125
        |> XData2.SetRunStr (fun s -> printfn "%s" s)   // FS1125
```

## Expected behavior

Warning FS1125 should not be thrown.

## Actual behavior

The following warning is thrown. And not once, but for all occurrences of `SetCreate` and `SetRunStr`.

> warning FS1125: The instantiation of the generic type 'XData2' is missing and can't be inferred from the arguments or return type of this member. Consider providing a type instantiation when accessing this type, e.g. 'XData2<\_,\_>'.

### Related behavior

When you run this in REPL, you don't see the above warning, but you get a different warning, on a different line (the `static member` lines).

> warning FS0667: The field labels and expected type of this record expression or pattern do not uniquely determine a corresponding record type

## Known workarounds

Workaround is to add type annotations, but apart from being tedious, it seems unnecessary, the compiler does a fine job (or I'm missing something, but it runs just fine).

## Related information 

I used VS2015, Update 3, F# 4.0 to create the repro.

I would understand if this is "by design", but I'd like you to consider to drop this warning if it is superfluous. I mean, it should be a warning if it actually creates some dangerous code.

_(BTW, this warning itself has surprisingly little coverage on the internet)_

**Comment by dsyme** [comment]
The correct warning is to make sure the generic parameters actually get referenced in the static member:

```
    static member SetCreate xp (xd: XData2<'T, 'U>) = { xd with CreateString = xp }
    static member SetRunStr run (xd: XData2<'T, 'U>) = { xd with RunStr = run }
```

**Comment by abelbraaksma** [comment]
@dsyme, if it is "by design", then we should probably fix the error text. It says _"it can't be inferred"_, while clearly it can:

>> The instantiation of the generic type 'XData2' is missing and can't be inferred from the arguments or return type of this member

In the example above, the generic type is inferred properly, but the warning says the opposite. Proposal for other warning text could be:

> "The instantiation of the generic type 'XData2' is missing and there was not enough information to infer it with certainty. The type is inferred to be 'XData2'. Add a type annotation to remove this warning."

(hmm, clunky, but something along those lines perhaps?)

**Comment by haf** [comment]
How do I make this warning disappear? The code compiles, works and is correctly inferred and I can't add any more type annotations AFAIK

<img width="1185" alt="screen shot 2017-03-28 at 17 12 47" src="https://cloud.githubusercontent.com/assets/193115/24412829/d54a9fce-13d9-11e7-948e-4e936e3032f7.png">
