### ISSUE TITLE
Build status links in readme.md are broken

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2016]
![image](https://cloud.githubusercontent.com/assets/873919/21218293/0af2df2a-c2c1-11e6-8d9c-62d8f0937ff4.png)

![image](https://cloud.githubusercontent.com/assets/873919/21218309/182aece6-c2c1-11e6-9648-7ff2a3946ab0.png)

**Comment by forki** [comment]
yeah I can't remember when I saw this working

**Comment by vasily-kirichenko** [comment]
fixed in https://github.com/Microsoft/visualfsharp/pull/2017
