### ISSUE TITLE
Error window is faster than squigglies

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2019]
![vs](https://cloud.githubusercontent.com/assets/57396/21230063/06661b5c-c2e4-11e6-8152-7ef03b226abd.gif)

/cc @vasily-kirichenko

**Comment by cartermp** [comment]
This seems like it *could* be related to #1808, or that diagnostic analysis is not kicked off or happening fast enough.

See this comment in @dsyme's PR: https://github.com/Microsoft/visualfsharp/pull/1906#issue-192887878

From the PR:
> Perhaps we could eventually let the Roslyn one drive the whole show.

Handing that job off to Roslyn may end up being faster than FCS.  The discussion in #1808 goes into that a bit.

**Comment by dsyme** [comment]
Closing in favour of https://github.com/Microsoft/visualfsharp/issues/3000
