### ISSUE TITLE
Visual Studio 2017 RC hangs on closing VF# solution

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2022]
Nearly every time I close the VF# solution (sln from this repo here) in VS2017 RC the VS hangs forever on unloading project 50 from 64.

![image](https://cloud.githubusercontent.com/assets/57396/21237123/f119da62-c2fd-11e6-9635-44c2d83cb471.png)

Same happens when switching branches.

**Comment by cartermp** [comment]
I haven't encountered this before - neither on my desktop nor my laptop.  Do you have similar behavior in other F# projects with a fair amount of .fsprojs?

**Comment by forki** [comment]
No. I only tried with this solution and it's always project 50.
Unfortunately it doesn't say which project that is.

Am 16.12.2016 06:56 schrieb "Phillip Carter" <notifications@github.com>:

**Comment by cartermp** [comment]
@forki have you noticed this lately?  I still haven't encountered it.

**Comment by forki** [comment]
Yes still there

**Comment by cartermp** [comment]
FYI I was able to repro this on a VM.  It's inconsistent (could never repro it on my desktop nor my laptop after multiple installations), but now that we have a VM with this repro-ing we can try and get a fix.  Unfortunately we're going to have to punt this one for now, but we're calling it out as a known regression ...and thus it has a high priority for us to fix.

**Comment by cartermp** [comment]
Just an update: I've been seeing this pretty consistently now with RC3 + VSIX installed.  Not sure how that "helped" by making it more common, but at least it's something we can pin down pretty reliably.

**Comment by vasily-kirichenko** [comment]
Yes, I see it now on RC3. This is what dotTrace shows:

![image](https://cloud.githubusercontent.com/assets/873919/22617033/a366ef8a-eacb-11e6-847e-ed084a96f39b.png)

Leaving alone the huge portion on native code, `Microsoft.CodeAnalysis.Workspace.OnDocumentContextUpdated` is actively doing something in a background thread. I'm not sure if it's our issue or Roslyn's. Note that VS loads one CPU code _forever_.

**Comment by vasily-kirichenko** [comment]
![image](https://cloud.githubusercontent.com/assets/873919/22617231/91bb3f02-ead0-11e6-95b8-cf86caf1d43d.png)

**Comment by vasily-kirichenko** [comment]
Looks like Roslyn is waiting `SemaphoreSlim` here http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Workspace_Editor.cs,347 
This semaphore can be locked in any of 34 places where it's used :(

@Pilchie @CyrusNajmabadi any ideas how to investigate it further?

**Comment by CyrusNajmabadi** [comment]
Is this just a dupe of https://github.com/dotnet/roslyn/issues/14479  ?   If so, @dpoeschl has submitted a fix here: https://github.com/dotnet/roslyn/pull/16889

**Comment by vasily-kirichenko** [comment]
@CyrusNajmabadi yes, looks like it's the same bug. And it looks like the fix is going to RTM?

**Comment by CyrusNajmabadi** [comment]
Yup.  The fix is going into RTM.

**Comment by forki** [comment]
Cool. Would have been a real paint point otherwise. Thanks
