### ISSUE TITLE
Please give merge rights to someone in europe

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2027]
In the last couple of weeks we often have red builds because of merge errors.
This blocks us - please consider to give merge rights (only restricted to build fixes) to one of the community members.

I suggest @vasily-kirichenko

**Comment by vasily-kirichenko** [comment]
I think it should be someone from Microsoft, but yes, 9-11 hours time shift between Redmond and us in Europe is a huge pain.

**Comment by KevinRansom** [comment]
Don can merge
