### ISSUE TITLE
Errors in multiple project.lock.json files

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2030]
Current master:

![image](https://cloud.githubusercontent.com/assets/873919/21277098/b0a641a8-c3e5-11e6-8f98-0c34d87ce59c.png)

However, the solution builds OK both with `build.cmd vs` and in VS.

**Comment by KevinRansom** [comment]
They are going to go away as soon as we get a tooling update.

**Comment by KevinRansom** [comment]
the files ... not the errors

**Comment by vasily-kirichenko** [comment]
I see. So we can close this?

**Comment by cartermp** [comment]
Yup.  project.json is phased out and unsupported at release.
