### ISSUE TITLE
Preprocessor derectives colored in grey 

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2040]
![image](https://cloud.githubusercontent.com/assets/873919/21292270/f020ba40-c50f-11e6-8de2-d7795c764adf.png)

**Comment by dungpa** [comment]
It seems deliberate to be consistent with Roslyn's C# integration.

But it feels weird since we are used to seeing them as keywords.

**Comment by vasily-kirichenko** [comment]
Ah, if it's consistent with c# editor, then it's ok.
