### ISSUE TITLE
Auto-completing attributes adds 'Attribute' suffix

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2041]
When auto-completing attribute names, the 'Attribute' suffix is automatically added, but is against .NET conventions.

#### Repro steps

1. Start writing an attribute above a function (e.g., `[<AutoOp`)

2. Notice that the autocompletion list suggests `AutoOpenAttribute` (and will type this when you accept the suggestion)

#### Expected behavior

Autocompletion should recognise that the caret is within an attribute specifier, and so should drop the Attribute suffix. So the suggestion should be `AutoOpen` instead of `AutoOpenAttribute`.

#### Actual behavior

Autocompletion suggests `AutoOpenAttribute`.

#### Known workarounds

Hit enter, then remove the `Attribute` suffix.

**Comment by cartermp** [comment]
Agreed, this should follow the .NET convention.

**Comment by cartermp** [comment]
This appears to be back.  I noticed it for quite some time, but I'm not sure why I never bothered to re-open this...

Anyways, here is what it's like in 15.5 RTW when typing a new attribute:

![attr-1](https://user-images.githubusercontent.com/6309070/33743559-31eaa1de-db62-11e7-883d-8aa6b0bb2528.PNG)

If `[<>]` is present, the `Attribute` suffix is gone as expected:

![attr-2](https://user-images.githubusercontent.com/6309070/33743567-3d27bba4-db62-11e7-94f9-0da752379002.PNG)

**Comment by cartermp** [comment]
Never mind, I couldn't see the gif in the PR that added this - there is no completion context for attributes when we're at `[<` (debugging it shows `null`). I don't think that's different from  when #2095 was added.

**Comment by forki** [comment]
Can you please reopen. I would like it to be fixed eventually

Am 08.12.2017 00:44 schrieb "Phillip Carter" <notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
It can be fixed only parsing source string manually (or maybe using the lexer, however I doubt). It's _hacky_.

**Comment by realvictorprm** [comment]
I would prefer to have general competition, auto adding the other hand side so `[<` is completed to `[<SomeAttributeName>]` or just adding the braces.

@vasily-kirichenko I think the Hacky way is OK here. I can't think of any great problems. Sure it would be nice to have information from the lexer about our current context.

**Comment by cartermp** [comment]
I'd really rather not introduce hacks (and I suspect @vasily-kirichenko wouldn't either), especially since this is really just a symptom of a larger problem with the parser. #4049 is the beginnings of brace completion, and it could be modified to complete the `>]`. No idea if that solves this problem or not, since it's not implemented yet.

**Comment by vasily-kirichenko** [comment]
@cartermp I don't think anybody will touch the parser. I'm sure @dsyme did his best to make it as good as possible. There is at least one similar hack in getting completion context, so adding another one is not a big deal.

**Comment by vasily-kirichenko** [comment]
This is the existing hack https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/ServiceUntypedParse.fs#L1265-L1275

**Comment by realvictorprm** [comment]
We or me can try the hacky solution while we think about how to solve it in a clean way. 
I really prefer nice and solid solution too @cartermp :-)

**Comment by dsyme** [comment]
TBH I'm OK with the hacky solution to this.  

Adding parsing recovery for incomplete things like ``[<Abc`` and ``[<Abc(`` is worthwhile, but does need real care.  Hence a quick-fix hack solution is ok
