### ISSUE TITLE
VS2015 sluggish with many F# editor tabs open and stalls long when closing all

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#2044]
I've hit this issue over the years quite often and it has seemed that with each version of F# and Visual Studio it improved. Both C# and F# seem to suffer from memory and, more importantly, CPU issues when many editor tabs are open.

I'm about to test this with VS2017, but thought about reporting it anyway in case VS2015 is still on the radar. It is understandable that Visual Studio becomes slower with more tabs open (assuming each of them take a certain amount of continuous CPU and memory resources). But it goes on until typing and cursor movement becomes sluggish.

Once you decide to close all tabs it becomes more responsive (but this trick only works a few times until you have to restart VS to have it perform responsively again).

Closing all tabs (or all but current) with single click can stall VS for up to a minute, while it is totally unresponsive. Most of the time it returns to normal operation though.

#### Repro steps

The only way to repro this, I think, is to work for a longer time with a single project or solution and to get more and more tabs open. By 10 or 20 editor tabs open, all F# source, it starts to exhibit this behavior.

#### Expected behavior

While some resource-eating can be expected, I don't expect it to get to the point where typing gets slow. Comparing with C# projects, this seems to happen way sooner (with C# I see it after opening over 100 editor tabs of C# source and ASP.NET, the latter seemingly being the cause).

#### Actual behavior

Each tab takes an amount of memory and CPU. The CPU amount appears to be constant and after some time, it rises to 100% CPU on (presumably) a single thread. I notice this in the CPU monitor, because it doesn't get above 4%, and I have two hexacore CPUs with total 12 cores, 24 with hyperthreading. This is the typical max percentage for a single thread.

This behavior can be seen with minimal memory usage (on this project around 1.4GB after startup). When it exhibits itself with around 3.2GB or more memory usage (after some time of intense working with VS) it is usually a sign that VS is about to crash or simply disappear (killed without messagebox).

#### Known workarounds

Restart Visual Studio 2015.

#### Related information 

I know the focus is on VS2017 and I will try it out there too. But I didn't see this behavior reported yet and I thought it should be, if not only for those people that experience the same behavior.

Feel free to close this with no action. 

If VS has an option to use multiple threads for the editor (or if it does, then I wonder what causes this behavior, it may be the syntax checker service or something). Maybe there's a way I can pinpoint the actual service/thread that causes this, but I'll need help to find out how to identify it.

* OS: Windows 7
* F# 4.0
* .NET 4.6
* Visual Studio 2015 Update 3
* Performance issue seen on 48GB memory, 3.2Ghz dual CPU hexacore Xeon CPU machine. During monitoring there was enough free CPU, free memory and free temp-directory (ramdisk) available.

**Comment by cartermp** [comment]
@abelbraaksma This is a good report, thanks.  I'll tag this with the performance label.  We haven't begin planning what we want to focus on post-vs2017 yet, but this combined with other issues makes me think that a tooling "performance epic" may be high on the list of things to do.

**Comment by abelbraaksma** [comment]
> This is the typical max percentage for a single thread.

I should have said: or multiple threads that wait on or block each other in tandem. Using SysInternal's process monitor shows that more than one thread is definitely active, but the CPU doesn't manage to spread the threads. This either means that one thread is doing the heavy lifting and makes VS sluggish, or multiple threads are just waiting on one another.

@cartermp, thanks for your quick response and to acknowledge it is potentially helpful :).

**Comment by fierval** [comment]
I have the same issue in the VS2017 Enterprise, Productivity PowerTools installed. Several open F# windows bog down the IDE, progressively making it less and less usable until it stops responding after some trivial command (e.g.: Close All Documents). I have a solution with 25 projects, mostly F#. Had roll back to VS 2015.

**Comment by vasily-kirichenko** [comment]
@fierval Do you use latest nightly or RTM?

**Comment by fierval** [comment]
@vasily-kirichenko  RTM. Also, using type providers (CSV) relatively heavily.

**Comment by vasily-kirichenko** [comment]
RTM has major performance (and other) bugs. Install the nightly build, please. Instructions are here https://blogs.msdn.microsoft.com/dotnet/2017/03/14/announcing-nightly-releases-for-the-visual-f-tools/ (it's as simple as adding an extra extensions feed and install VFT via it).

**Comment by fierval** [comment]
@vasily-kirichenko Cool. Done, thanks.

**Comment by dsyme** [comment]
Closing old issue

**Comment by abelbraaksma** [comment]
Maybe an old issue, but it was never fixed in any of the updates of VS2015.

Only since VS2017 Preview 6 from 2 days ago, this seems to be sufficiently fixed. While the VS2017 issue (sudden, high, continuous CPU usage after some time working with the IDE) was not the same as this original report, and the sluggishness for sure is still happening in my most up-to-date VS2015, since it is now solved in the most recent Preview, I agree we should put it to rest, I doubt much fixes will, or should come around for VS2015 now.
