### ISSUE TITLE
Tuple types colorized slightly wrong in signature help

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2045]
![image](https://cloud.githubusercontent.com/assets/873919/21294451/cf52559c-c54d-11e6-83af-011b8bfba27c.png)

/cc @dungpa

**Comment by dungpa** [comment]
I'm aware of this.

I hope @vladima will send a PR for https://github.com/Microsoft/visualfsharp/compare/master...vladima:vladima/classification soon.

Once that is in, this kind of error is very easy to fix.

**Comment by vasily-kirichenko** [comment]
@dungpa wow! We are gonna get great coloring info. Can it be used for "normal" code colorization or for quick info / signature help only? Anyways, what a time to be alive :)

**Comment by cartermp** [comment]
That is indeed great coloring info.  All the way down into the depths of the language service.  If it could be used for semantic colorization then that would be great (provided it's faster, which I bet it is).

**Comment by dungpa** [comment]
This has been fixed after https://github.com/Microsoft/visualfsharp/pull/2070 was merged.
