### ISSUE TITLE
Huge pause with high CPU load before VFT solution is started building

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2046]
1. Open VisualFSharp.sln
2. Build it

What I see: ~30 seconds pause before output window starts to show anything. dotTrance shows the following picture:

![image](https://cloud.githubusercontent.com/assets/873919/21294737/4e517268-c555-11e6-8e45-984e1ba2d961.png)

**Comment by vasily-kirichenko** [comment]
OK, it's this msbuild invoke:

https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.ProjectSystem.FSharp/Project.fs#L1282-L1292

And I suspect it's because of huge number of references .NET Core introduces. 

What I _don't understand_ is why we recompute the references each time? What about caching them and invalidate when a project changes?

**Comment by vasily-kirichenko** [comment]
Bad news ;)

![image](https://cloud.githubusercontent.com/assets/873919/21294957/ea44ea2e-c55a-11e6-84bb-490aa7630464.png)

**Comment by cartermp** [comment]
I have noticed this as well.  It seems like it sometimes gets out of hand and can take longer after a few hours of f5 debugging.

**Comment by saul** [comment]
I'm not sure why ComputeSourcesAndFlags is even being called here. Take a look at:
https://github.com/Microsoft/visualfsharp/blob/6afc4f9776a5dba903ca6b11965a206fb8bc23d8/vsintegration/src/FSharp.ProjectSystem.Base/Project/ProjectNode.cs#L3222-L3225

It looks like every single MSBuild action results in re-calculating sources and flags. It feels like this is happening way too often - if we're doing this already at project load, configuration change, file add/remove and more - why do we have to do it at every MSBuild action? Not to mention doing a compilation of the project already updated sources and flags! I'm tempted to remove this extra call.

I'll have a tinker in a couple of days to try and figure out how often this is called. I've got a sneaking suspicion that this function is being called way more often than necessary, and it's a CPU hog and is freezing the UI thread. At a bare minimum I want to use IWaitIndicator to show a progress bar while this is happening.

**Comment by vasily-kirichenko** [comment]
It's completely fixed in https://github.com/Microsoft/visualfsharp/pull/2133
