### ISSUE TITLE
Move Up/Down context menu not available on folders, but Alt-Up/Down works

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#2050]
Move Up / Down is not available in the context menu when a folder is selected, however the functionality is there, so there seems no reason for removing it from the context menu.

## Repro steps

Rightclick on a folder in the solution explorer:

![image](https://cloud.githubusercontent.com/assets/16015770/21295683/d7c34404-c55a-11e6-888d-0431976887f1.png)

## Expected behavior

The options Move Up / Move Down should be available, similar to when you select a file:

![image](https://cloud.githubusercontent.com/assets/16015770/21295704/37cc9c1a-c55b-11e6-9dcd-04e486ce578e.png)

## Actual behavior

Move Up / Move Down are not available.

## Known workarounds

Use the Alt + Up Arrow or Alt + Down Arrow key combinations.

## Related information 

The same applies to the functionality of Add Below, Add Above context menus.

* Visual Studio 2015, Update 3

**Comment by saul** [comment]
It looks like this is because QueryStatusOnNode is never being called on FSharpFolderNode with a command group of `VSProjectConstants.guidFSharpProjectCmdSet`. It is called with this command group on FSharpFileNode. I'm not sure where these commands get registered but I imagine this is the issue.

**Comment by cartermp** [comment]
Tagging this for VS Updates; although it seems like a small enough change that we may be able to get it in for release.

**Comment by JoshVarty** [comment]
I'll try to take a look at this. No guarantees though as I don't know much about the solution explorer APIs.

**Comment by JoshVarty** [comment]
Interestingly, it looks like it no longer shows up at all as of [`15.4.1.17031702`](https://dotnet.myget.org/feed/fsharp/package/vsix/VisualFSharp/15.4.1.17031702) 

![image](https://cloud.githubusercontent.com/assets/1249087/24065387/b6d47f0c-0b27-11e7-8f26-63dc5267754d.png)

**Comment by saul** [comment]
@joshvarty that's the problem :) it may only work on folders and not files. There is a ticket but I'm on mobile so I'm struggling to find it!

**Comment by cartermp** [comment]
@JoshVarty Shows up for me on `15.4.1.17031702`.  The options are greyed out, though.

**Comment by abelbraaksma** [comment]
Excellent work on this! The folder-support in VS2017, and adding/removing items from a folder, or moving them inside a folder or to/from a folder, including the much-anticipated copy/paste now all seem totally stable (it used to cripple the project file).
