### ISSUE TITLE
Remove unneeded VSIX projects

### ISSUE THREAD

**Issue by JoshVarty** [Microsoft/visualfsharp#2065]
Currently there are four VSIX projects:

 - VisualFSharpDesktop
 - VisualFSharpFull
 - VisualFSharpOpenSource
 - VisualFSharpWeb

It looks to me like some of these were in place to support Visual Studio SKUs that are no longer around. Can we remove any of them? 

So far as I can tell:
 - VisualFSharpDesktop targets the Express SKU (does this still exist?)
 - VisualFSharpFull targets Community, Professional and Enterprise
 - VisualFSharpOpenSource targets Community, Professional and Enterprise
 - VisualFSharpWeb targets the Web Developer Express SKU (does this still exist?)

I've reached out to the shell team to get a list of VS2017 SKUs. Can we remove any projects for SKUs that no longer exist? 

Also: Is there a difference between VisualFSharpFull and VisualFSharpOpenSource? If not, can we remove one of these projects?

**Comment by JoshVarty** [comment]
The difference between Full and OpenSource `.csproj` files appears to be:

1. Full specifies `<DeployExtension>false</DeployExtension>`
2. OpenSource comments out the following:

```XML
<Content Include="$(FSharpSourcesRoot)\..\packages\System.ValueTuple.4.3.0\System.ValueTuple.4.3.0.nupkg">		    <Content Include="$(FSharpSourcesRoot)\..\packages\System.ValueTuple.4.3.0\System.ValueTuple.4.3.0.nupkg">
  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>		      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  <Link>packages\System.ValueTuple.4.3.0.nupkg</Link>		      <Link>packages\System.ValueTuple.4.3.0.nupkg</Link>
  <IncludeInVSIX>true</IncludeInVSIX>		      <IncludeInVSIX>true</IncludeInVSIX>
</Content>
```

**Comment by cartermp** [comment]
cc @KevinRansom 

Personally I see no reason to keep the ones that target Express SKUs, since those have been deprecated since VS Community.

**Comment by KevinRansom** [comment]
@cartermp Can we see if we can get an official word about the Express Skus?

**Comment by cartermp** [comment]
Sending email

**Comment by cartermp** [comment]
Okay, got some official word - although Express isn't deprecated we're doing as little work as possible to support Express SKUs so we can move people who use it to either Community or Pro (depending on their organization).  We don't advertise it anymore and push any new people towards Community and Pro.

Given that nobody is tied to VS at all if they need a version of the F# compiler with bugs fixed, I think it's safe for us to cut support and remove those.  I don't have any data on hand that suggests we have companies using VS Express who are expecting support and bug fixes for the Express SKU.  We're also not shipping any such improvements to Express SKUs for F# 4.1.

**Comment by saul** [comment]
This can be closed as it's now on master.

**Comment by KevinRansom** [comment]
Fixed
