### ISSUE TITLE
Unrelated suggestions in error message

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2066]
![image](https://cloud.githubusercontent.com/assets/873919/21380872/289587ce-c769-11e6-9776-3e759b2bf69f.png)

While `Math` looks legible, all the other suggestions are completely unrelated. 

/cc @forki

**Comment by forki** [comment]
The problem here is that none of the namespaces is related and the real suggestion would be to open System.IO. Maybe that's some for 4.2 cycle

**Comment by forki** [comment]
That said I think I will send a PR that checks if the similarity of a suggestion is above a certain threshold. That should filter things better.

**Comment by vasily-kirichenko** [comment]
Yes, I think it's a good idea.

**Comment by saul** [comment]
This can be closed as #2068 and #2175 have been merged.
