### ISSUE TITLE
Discussion: F# Roslyn analyzers

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2076]
@KevinRansom proposed in https://github.com/Microsoft/visualfsharp/pull/2068 to use roslyn analyzers for suggestions instead of throwing detailed error messages.

Open questions;

1) Is it technically possible to do?
2) Can we generate quick fixes from analyzers? /cc @vasily-kirichenko 
3) Can ionide use this information in VS Code and still generate it's quick fixes / cc @Krzysztof-Cieslak
4) What about fsi.exe - can we still suggest from there?
5) What about Xamarin Studio? Would analyzers work there? /cc @nosami

**Comment by nosami** [comment]
Roslyn analyzers would work fine in Xamarin Studio. When I built this 
![cookingwithgas](https://cloud.githubusercontent.com/assets/667194/21425046/90cc9960-c83e-11e6-97d9-7a15277e36ce.gif)
, I had to fight against the current implementation for C# which used Roslyn CodeFixes.


I would especially like to see FCS generate the list of TextChanges for each potential CodeFix. Right now fixes would entail parsing information passed through the compiler error message and acting on that. 

A Text Change is just { startPos; endPos; newText } and can represent text to be removed, added or changed.

I don't think Roslyn analyzers would work in the fsi scenario - I'm not sure what use case you are thinking of.

**Comment by forki** [comment]
In the fsi we usually just type and do most of the typos since we don't
have autocomplete. For this error message with suggestions is useful.

Am 22.12.2016 13:06 schrieb "Jason Imison" <notifications@github.com>:

**Comment by nosami** [comment]
I think that error messages are a separate concern. 

The compiler would generate messages like it does today and can maybe include suggestions.

The analyzers act upon specific error IDs and can produce multiple fixes per error. The text generated by the analyzers would/should be different than the error message.
The Analzer messages would contain the text messages (and the corresponding TextChanges) that appear in the QuickFix context menu.

**Comment by nosami** [comment]
I just noticed that the current fixes _are_ represented as Roslyn CodeFixes with TextChanges. I guess I need to make this work in Xamarin Studio.

I think I also muddied the difference between Analyzers and CodeFixes. I think Analyzers work across the whole document / solution in the background.

**Comment by Krzysztof-Cieslak** [comment]
Ionide has access only to FCS. So we should be able to support anything that's part of it.

And 👍 for having structured CodeFixes (TextChange) returned from FCS (as part of returned errors, I guess) - it would be much nicer than manual parsing of error messages.

**Comment by vasily-kirichenko** [comment]
@Krzysztof-Cieslak I think the way to go is to move F# to Roslyn project system, which (I hope) would enable analyzers automatically.

**Comment by cartermp** [comment]
I'm not sure moving to the roslyn project system will enable them automatically, but it does move us in the right direction for sure.

I think it's also important to call out the difference between diagnostic analyzers and code fixes versus the consumption of Analyzers written which depend on `ISymbol` and other Roslyn APIs.  Unfortunately, unless we move to Roslyn models, we'll sort of be on our own island Analyzer-wise.  But I don't want that to distract from diagnostic analyzers being a great choice for handling errors in tooling.

Is there a flag in the compiler where we could keep the text-base suggestions for naked `fsc` usage, but use diagnostic analyzers wherever there's IDE tooling?
