### ISSUE TITLE
Add "generate XML Doc comment" feature

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2078]
@CyrusNajmabadi could you please point me what code in C# editor inserts XML Doc comment when user types triple slash `///` above a symbol, like this:

![image](https://cloud.githubusercontent.com/assets/873919/21426837/2e38b12a-c862-11e6-942d-acf1cbbf4200.png)

I wonder if it's a standard feature we could reuse.

**Comment by dungpa** [comment]
If there is no entry point, probably I will port the VFPT's XML Doc comment feature as is.

**Comment by vasily-kirichenko** [comment]
@dungpa actually I tried and stuck on getting dirty text since no Document available.

**Comment by cartermp** [comment]
@vasily-kirichenko For C#, the handler appears to be here: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/CSharp/DocumentationComments/DocumentationCommentCommandHandler.cs#L22

And much of the shared logic is here: https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Core/Implementation/DocumentationComments/AbstractDocumentationCommentCommandHandler.cs

**Comment by CyrusNajmabadi** [comment]
Note: those types are fine for seeing the general approach we took. However, they're very VB specific (using syntax trees and symbols), so they're unlikely to be usable by you guys directly

**Comment by vasily-kirichenko** [comment]
@dungpa go for it if you like.
