### ISSUE TITLE
ArgumentOutOfRange Exception thrown when clicking at end of document

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2079]
(Yes, some of these repro steps aren't related, but this is what I had when I got the exception)

1. `f5` a new hive of the latest master
2. Create an F# console app.
3. Create a C# class library.

In the C# class library, type the following code:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    public class TheClass
    {
        public static string TheMessage(string name) => $"Hey there, {name}";
    }
}
```

In the F# console app, type the following code:

```fsharp
// Learn more about F# at http://fsharp.org
// See the 'F# Tutorial' project for more help.

open ClassLibrary1

let getTheName name = TheClass.TheMessage(name)


[<EntryPoint>]
let main argv = 
    printfn "%s" (getTheName "Phillip")
    0 // return an integer exit code
```

Now, click the end of the F# document:

![exception-end-of-file](https://cloud.githubusercontent.com/assets/6309070/21434829/56c2aab0-c82b-11e6-8bc1-b832d6a1f4c8.PNG)

**Comment by cartermp** [comment]
cc @vasily-kirichenko this seems to have been called from Document Highlight Service

**Comment by cartermp** [comment]
Cause is here: https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Common/CommonHelpers.fs#L343

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2090

**Comment by cartermp** [comment]
Great!

**Comment by cartermp** [comment]
Closing, since I can't repro this after @vasily-kirichenko's fix.
