### ISSUE TITLE
Assertion Failed when writing code with a dependency on C# class library in Debug mode

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2080]
1. `f5` a new hive of the latest master
2. Create an F# console app.
3. Create a C# class library.

In the C# class library, type the following code:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClassLibrary1
{
    public class TheClass
    {
        public static string TheMessage(string name) => $"Hey there, {name}";
    }
}
```

In the F# console app, type the following code (note that the line with `TheClass` is not finished typing):

```fsharp
// Learn more about F# at http://fsharp.org
// See the 'F# Tutorial' project for more help.

open ClassLibrary1

let getTheName name = TheClass

[<EntryPoint>]
let main argv = 
    printfn "%s" (getTheName "Phillip")
    0 // return an integer exit code
```

Assertions fail at what seems to be the error logger at this point:

![assertion-failed](https://cloud.githubusercontent.com/assets/6309070/21435073/89ee09d8-c82c-11e6-9436-b0af3a546a48.PNG)

![assertion-failed-0](https://cloud.githubusercontent.com/assets/6309070/21435155/03f62ddc-c82d-11e6-8b3b-e58727043f4a.PNG)

![assertion-failed-1](https://cloud.githubusercontent.com/assets/6309070/21435129/d5042a06-c82c-11e6-89a7-323bef7d7501.PNG)

**Comment by vasily-kirichenko** [comment]
that's from Add Open feature, see my comment in the PR.

**Comment by cartermp** [comment]
I see.  Is there a way to fix that?  Not critical anymore, but still pretty annoying when testing things out in a debug hive.

**Comment by vasily-kirichenko** [comment]
Yes, it makes testing in Debug mode (and, of course, debugging) next to impossible. It's deep in call stack, somewhere in `infos.fs`, if I'm right. It's inconvenient that the Assertion cannot be muted. I tried to replace ErrorLogger with no-op one for the time the code fixer gathering Entities, but it did not help.
