### ISSUE TITLE
What version of Microsoft.CodeAnalysis packages we should use for VS 2017 RTM?

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2089]
There are `2.0.0-rc3-xxx` and `2.1.0-beta1-xxx` packages on https://dotnet.myget.org/feed/roslyn (for example, https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.Features)

If VS 2017 RTM will use RC3 packages, then I think we should update to the freshest `rc3`.

**Comment by Pilchie** [comment]
Stay with the `2.0` line - the `2.1` packages are from the `post-dev15` branch of Roslyn and won't be shipping in RTM.

**Comment by vasily-kirichenko** [comment]
@Pilchie thanks.
