### ISSUE TITLE
Brace Highlighting Should Activate at more positions

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#2092]
I marked out the columns where brace matching activates and where it does not
`o` means it activates on the following col,  `x` means it doesn't i.e.

![](http://i.imgur.com/cA6Ac4X.png)
![](http://i.imgur.com/c8RKCs9.png)
```fsharp
(*          ox          xo        *)
    let a1 = [ 0 .. 100  ]
(*          oxx          xox        *)
    let a2 = [| 0 .. 100  |]
(*          oxx    xox        *)
    let a3 = <@ 0   @>
(*          oxxx     xoxx        *)
    let a4 = <@@  0   @@>
(*          ox     xo        *)
    let a6 = (  ()  )
(* oxx                  xox     *)
    [<ReflectedDefinition>]
    let a7 = 70
(*              ox        xo     *)
    let a8 = seq { yield() }
(*     oxx   xxo         *)
    let (| A9 |) = ()
```

I think brace matching should activate on either side of the brace and at all positions inside of the brace for multi column braces

It doesn't activate at all for - 
- `(*` `*)`
- `begin` `end`
- `struct` `end`
- `class` `end`
- `interface` `end`
- `<` `>` for generics

[ vs2017 rc2 with latest tools built from master ]

**Comment by vasily-kirichenko** [comment]
+500 for this.

**Comment by saul** [comment]
With my latest PR (#3313), we're returning the correct braces to Roslyn. However, Roslyn explicitly ignores them. See http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/BraceMatching/BraceHighlightingViewTaggerProvider.cs,3ee09e525b0037c8

```c#
/// Given code like   ()^()  (where ^ is the caret position), returns the two pairs of
/// matching braces on the left and the right of the position.  Note: a brace matching
/// pair is only returned if the position is on the left-side of hte start brace, or the
/// right side of end brace.  So, for example, if you have (^()), then only the inner 
/// braces are returned as the position is not on the right-side of the outer braces.
/// 
/// This function also works for multi-character braces i.e.  ([  ])   In this case,
/// the rule is that the position has to be on the left side of the start brace, or 
/// inside the start brace (but not at the end).  So,    ^([   ])  will return this
/// as a brace match, as will  (^[    ]).  But   ([^   ])  will not.
/// 
/// The same goes for the braces on the the left of the caret.  i.e.:   ([   ])^
/// will return the braces on the left, as will   ([   ]^).  But   ([   ^]) will not.
```

You need to raise the issue with Roslyn, as they explicitly do not allow what you're asking (I agree it's counterintuitive).
