### ISSUE TITLE
Compiler error msg fix

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#21]
mmjb submitted this via CodePlex

Error message uses 'attributes' too many times.
"This type uses an invalid mix of the attributes 'NoEquality', 'ReferenceEquality', 'StructuralEquality', 'NoComparison' and 'StructuralComparison' attributes"

Should be:
"This type uses an invalid mix of the attributes 'NoEquality', 'ReferenceEquality', 'StructuralEquality', 'NoComparison' and 'StructuralComparison'"

**Comment by latkin** [comment]
Already fixed (by you!) https://github.com/Microsoft/visualfsharp/commit/3ccdcea0950a1040e87e4b6d1afa2dcce91fb45d

**Comment by KevinRansom** [comment]
The fix and the report came from mmjb.  I just pressed the delete char.
