### ISSUE TITLE
Invalid namspace is suggested

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2108]
![image](https://cloud.githubusercontent.com/assets/57396/21481475/3ff3aed4-cb68-11e6-9c78-eaa00dc095c9.png)

/cc @vasily-kirichenko

**Comment by forki** [comment]
not really sure what's happening here, but it doesn't look correct ;-)

**Comment by vasily-kirichenko** [comment]
I've stared at it for some time and haven't got what's happening here either. What do you expect it to do (or not to do)?

**Comment by cartermp** [comment]
@vasily-kirichenko Looks like @forki is trying to use this: https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/PackageResolver.fs#L77

Which is in `Paket.PackageResolver`, but the IDE is suggesting `PackageResolveer.Paket.PackageResolver`.  Looks like the correct namespace is getting appended here.

**Comment by forki** [comment]
Yep I think it's suggesting the current namespace.

Am 26.12.2016 17:27 schrieb "Phillip Carter" <notifications@github.com>:

**Comment by forki** [comment]
@Krzysztof-Cieslak do you see the same thing happening in ionide?

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2102
