### ISSUE TITLE
"Edit project file" does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2110]
![1](https://cloud.githubusercontent.com/assets/873919/21483749/b50d9e70-cb98-11e6-967c-5a76cf5c1454.gif)

**Comment by cartermp** [comment]
Yes, I noticed this the other day as well (Christmas time and traveling, forgot to log the bug).  Definitely needs to get fixed.

**Comment by saul** [comment]
I can't reproduce this on master or RC2, on the VisualFSharp solution at least. Do you have a minimal repro?

**Comment by vasily-kirichenko** [comment]
Isn't the screencast a minimal repro?

**Comment by saul** [comment]
Sorry, I meant to ask whether you could reproduce it every time on the same solutions and whether you couldn't edit any project across all solutions

**Comment by vasily-kirichenko** [comment]
Yes, I can reproduce it on FSharp.Editor project in VisualFSharp.sln on current master, also on a hello world console project. I ran it under debugger and no exceptions were caught.

**Comment by cartermp** [comment]
I can still reproduce this.

**Comment by cartermp** [comment]
@KevinRansom @brettfo This one is critical to get in for RTM

**Comment by saul** [comment]
@cartermp has anyone had a chance to look at this? This seems urgent and considering how broken folder support is, will be something that is used often.

**Comment by vasily-kirichenko** [comment]
It works on original RC2, without the hotfix that was published on the day after RC2 release.

**Comment by cartermp** [comment]
I can no longer repro this on RC3 + VSIX.  Tried it on FSharpPlus like in the GIF above, and it seems to work.  @vasily-kirichenko can you no longer repro this either, or are you still seeing it on RC3?

**Comment by vasily-kirichenko** [comment]
Yes, I cannot reproduce it on RC3.
