### ISSUE TITLE
FSComp.txt and FSStrings.resx should be merged

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2118]
It's always annoying to search in both to find a concrete error string.

**Comment by forki** [comment]
Also all Code fixes depend on these two files and the translations (which are not OSS yet)

**Comment by forki** [comment]
@cartermp + @kevinransom can one of you please comment on the implications for translation. I personally would like to merge the FSStrings.resx into FSComp.txt since I find it much easier to work with. But that's personal taste. We can probably also do it the other way around.

**Comment by cartermp** [comment]
I support a change like this - seems like an obvious improvement.  I'm not sure if we do anything special for localization - @brettfo can speak more to that - but from a translation side of things, one file is also easier to deal with.

**Comment by KevinRansom** [comment]
Yeah it's irritating fscomp.txt should go away.  But it's going to have to wait until we have OSS'd the localization tools.  Otherwise we will have to muck about with the current localization scripts which are going away.  The ETA for OSs localization is 2 to 3 months.

**Comment by forki** [comment]
FSComp.txt is such a nice thing. Sad that you say this one should go. ;-)

Anyways having only one will be much better in the future

Am 30.12.2016 18:46 schrieb "Kevin Ransom (msft)" <notifications@github.com

**Comment by dsyme** [comment]
Seems better to keep FSComp.txt since it is more type safe: after being processed by FsSrGen it uses printf-style type checking to make sure all format holes are filled in when strings are used.  Is there a specific reason to go back to the resx?

**Comment by KevinRansom** [comment]
Sure but VS has tooling for rest files.

**Comment by forki** [comment]
Yeah which is the annoying part ;-)

Am 01.01.2017 9:34 nachm. schrieb "Kevin Ransom (msft)" <
notifications@github.com>:

**Comment by smoothdeveloper** [comment]
Curious when is the last time resx editor has been improved in VS? VS2005?

It seems the text file is a bit more "roots" solution but has some advantages (printf style type checking) and doesn't require VS for basic edits.

**Comment by forki** [comment]
Tbh the resx editor is really annoying so that I always end up opening then
resx in a text editor.

Am 02.01.2017 07:33 schrieb "Gauthier Segay" <notifications@github.com>:

**Comment by dsyme** [comment]
Like others I can't stand the VS tooling for resx and just edit by hand. And the type safety of FSComp.txt buys a considerable amount of peace-of-mind.

**Comment by dsyme** [comment]
I'm closing - agreed this is an annoyance, and something we could improve, but not something we need to track with an issue
