### ISSUE TITLE
Compiler's bug: Field initialization order of record

### ISSUE THREAD

**Issue by u1roh** [Microsoft/visualfsharp#212]
# Description
Maybe I've found a F# compiler's bug, which is demonstrated in .NET Fiddle. https://dotnetfiddle.net/pLFzQE 
I expected that each field initialization of record is evaluated in order, but it isn't.
I checked a spec document of F# 3.0 out, and I found "6.9.11 Evaluating Record Expressions" says
that "Each expression e1 … en is evaluated in order". So, I'm afraid this behavior below is a compiler's bug. 

# Repro Steps
```fsharp
type Foo = {
  A : int
  B : int
  C : int
}

let _ =
  { A = let _ = printfn "1" in 0
    C = let _ = printfn "2" in 0
    B = let _ = printfn "3" in 0 }
```

# Expected/Actual
I expected the above program prints:
1
2
3

but, actually:
2
1
3

# Version
F# 3.0 (FSharp.Core, 4.3.0.0), .NET Framework 4.5

**Comment by latkin** [comment]
This repros in F# 4.0.

Worth noting that the "A C B" order is the *only* permutation that results in out-of-order initialization.

**Comment by forki** [comment]
I think only the new tests are useful. the fix itself was not correct.
