### ISSUE TITLE
Find all references raises Assert dialog on some external symbols

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2140]
![image](https://cloud.githubusercontent.com/assets/873919/21576874/121cad96-cf53-11e6-9f39-02acb83ca353.png)

In the following code this error is raised only on `FileStream`, `FileMode` and `Append`:

```fsharp
module M

open System

let xy = new System.IO.FileStream("", IO.FileMode.Append)
let z: System.IDisposable = null

let _ = { new System.IDisposable with
              member this.Dispose(): unit = 
                  raise (System.NotImplementedException()) }
```

I've examined the spans we return to Roslyn and they look good. No idea what's happening here.

**Comment by dsyme** [comment]
How bad is this - if you ignore the assert (e.g. release builds) does anything catastrophic happen?

**Comment by vasily-kirichenko** [comment]
@dsyme No the assertion in Release configuration, it just says "no references found for ...". So it's not as critical.

**Comment by cartermp** [comment]
We'll definitely want to be able to find references to those symbols.  Not a disaster if it doesn't work for release, but it should definitely get addressed.

**Comment by vasily-kirichenko** [comment]
The assertion dialog fixed in https://github.com/Microsoft/visualfsharp/pull/2167 (it does not find usages of external and provided symbols though).

**Comment by vasily-kirichenko** [comment]
Completely fixed in https://github.com/Microsoft/visualfsharp/pull/2167
