### ISSUE TITLE
Duplicated errors in tooltip

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2141]
![image](https://cloud.githubusercontent.com/assets/873919/21576984/c206de9c-cf59-11e6-9771-65ef59fc9a1e.png)

Current master.

**Comment by vasily-kirichenko** [comment]
This is another issue that the one we fixed earlier. This time parse errors themselves are duplicated:

![image](https://cloud.githubusercontent.com/assets/873919/21577001/ba0b675c-cf5a-11e6-9d75-4fa5357eda2a.png)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2142

**Comment by dsyme** [comment]
I suppose we should keep this open until the PR is merged
