### ISSUE TITLE
Find All References does not work on dirty documents

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2143]
![1](https://cloud.githubusercontent.com/assets/873919/21577044/38376e80-cf5d-11e6-9f6a-a618b9d7eef6.gif)

For the following code:

```fsharp
let private xxx = 1
let y = xxx
let z = xxx
```

The text we pass to FCS looks good:

![image](https://cloud.githubusercontent.com/assets/873919/21577092/41c13182-cf5f-11e6-8994-958e8d3cfc06.png)

but it returns two symbol uses instead on three:

![image](https://cloud.githubusercontent.com/assets/873919/21577100/8906d416-cf5f-11e6-8ca5-253733940bf4.png)

At the same time the same FCS method returns three symbol uses in Document Highlight service:

![image](https://cloud.githubusercontent.com/assets/873919/21577111/e2fdb14c-cf5f-11e6-9484-67e4394aa20b.png)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2144

**Comment by dsyme** [comment]
Great find and fix.  Again leaving open until PR is merged
