### ISSUE TITLE
Find All References missing usages

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2145]
Find All References seems to be missing references to many symbols.

Note how in the first screenshot, Find All References is missing symbols that are known to the highlights service.

#### Repro steps

1. Select a symbol
2. Use Find All References

#### Expected behavior

All references to a symbol are shown.

#### Actual behavior

![refs](https://cloud.githubusercontent.com/assets/64654/21577243/1986ef4e-cf4c-11e6-8144-3668aff9662f.png)

![find results](https://cloud.githubusercontent.com/assets/64654/21577244/1c184e7e-cf4c-11e6-8a3e-55e7e0b02044.png)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2139

However, Workspace does not aware of all projects in solution, see https://github.com/Microsoft/visualfsharp/issues/1975, a project is added to Workspace when a file belonging to it is opened.

**Comment by cartermp** [comment]
Closing this, as #1975 does capture the issue of cross-project problems.
