### ISSUE TITLE
Range of SynExpr.App inconsistent when funcExpr is an operator

### ISSUE THREAD

**Issue by duckmatt** [Microsoft/visualfsharp#2149]
The range of `SynExpr.App` is inconsistent when an operator is the `funcExpr` - values applied to an infix operator in prefix fashion e.g. `let x = (*) 4 5`. `(*)` behaves as expected, but other operators such as `(+)` do not have the first left paren included in the range of the SynExpr.App

#### Repro steps

Function application expression: `(+) 2`, SynExpr.App's range: `+) 2`
Function application expression: `(*) 2`, SynExpr.App's range: `(*) 2`

#### Expected behavior

Expected range of the expression `(+) 2` to cover: `(+) 2`

#### Actual behavior

*not as expected*: expression: `(+) 2`, range of function application covers: `+) 2`, range of identifier covers (no surrounding parens in ast): `+`

![image](https://cloud.githubusercontent.com/assets/3247369/21598199/12462c1c-d150-11e6-8de2-686fce7c2f10.png)

*as expected*: expression: `(*) 2`, range of function application covers: `(*) 2`, range of identifier covers (no surrounding parens in ast): `(*)`

![image](https://cloud.githubusercontent.com/assets/3247369/21598234/e754636a-d150-11e6-81b9-d34ba3cf5300.png)

*as expected*: expression: `(foo) 2`, range of function application covers: `(foo) 2`, range of paren covers: `(foo)`, of identifier covers: `foo`

![image](https://cloud.githubusercontent.com/assets/3247369/21598220/7ef62d30-d150-11e6-8d1c-5c3d6aa49308.png)

#### Known workarounds

Tooling using the range of SynExpr.App can require extra handling logic around operators other than `(*)` as a workaround

#### Possible fix

[Including the parentheses inside of the range of the identifier](https://github.com/duckmatt/visualfsharp/commit/5261ff6c9460356eb56b1a2c275ae142bb46e2fb). What are your thoughts?

#### Related information 

* **severity: low**
* OS: Windows 10
* currently have only tested via: FSharp.Compiler.Service v8.0
* .NET Framework 4.5

**Comment by KevinRansom** [comment]
@dsyme comments?  Is this a uservoice suggestion or a bug?

Thanks

Kevin

**Comment by smoothdeveloper** [comment]
I think it would be a relevant issue for https://github.com/fsharp/FSharp.Compiler.Service.

@KevinRansom User Voice has been demoted, we should head to https://github.com/fsharp/fslang-suggestions instead but this doesn't sound like a "F# end user" feature.

**Comment by dsyme** [comment]
Tracking as an FCS bug https://github.com/fsharp/FSharp.Compiler.Service/issues/783
