### ISSUE TITLE
Signature help does not show secondary constructor parameter types

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2153]
For this type https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/Symbols.fs#L1131-L1132

```fsharp
and FSharpMemberOrFunctionOrValue(cenv, d:FSharpMemberOrValData, item) = 
...
    new (cenv, vref) = FSharpMemberFunctionOrValue(cenv, V vref, Item.Value vref)
    new (cenv, minfo) =  FSharpMemberFunctionOrValue(cenv, M minfo, Item.MethodGroup(minfo.LogicalName, [minfo], None))
...
```
signature help does not show parameter type names, it shows parameter names, colored as types:

![1](https://cloud.githubusercontent.com/assets/873919/21618537/6c8e53aa-d1fc-11e6-90aa-70e64f3c9d57.gif)

**Comment by cartermp** [comment]
I can repro this on the bits that shipped with RC2 as well.  Good find!

**Comment by cartermp** [comment]
I couldn't get VisualFSharp.sln to build in a debug hive, so Signature Help wouldn't work there.  I tried a [quick repro with some fake types](https://gist.github.com/cartermp/881b18a408f4ba37c1c7ce54e67710a7), but it showed Signature Help info correctly.  Seems like there's something else going on when it's got everything in scope 😕

**Comment by cartermp** [comment]
Bumping the severity down for this, since I get expected behavior on my own types that follow this kind of pattern:

![sig-overload-no-repro](https://cloud.githubusercontent.com/assets/6309070/21629252/853cc592-d1db-11e6-8dc1-6d466a9b45b4.gif)

**Comment by vasily-kirichenko** [comment]
@cartermp that symbols.fs has .fsi counterpart, could you try add one for your sample project and see what will happen?

**Comment by cartermp** [comment]
Same result:

![sig-overload-no-repro-2](https://cloud.githubusercontent.com/assets/6309070/21689695/009f1f3c-d326-11e6-8938-7a8f5a6caab0.gif)

**Comment by rojepp** [comment]
Is it because of the mutually recursive types?

**Comment by dungpa** [comment]
I think this is by design.

The signature files here don't provide name arguments for constructors, so only type names are displayed in quick info: https://github.com/Microsoft/visualfsharp/blob/43dc89177e2a9981054dfe05026d172214cac8a1/src/fsharp/vs/Symbols.fsi#L603-L604

**Comment by cartermp** [comment]
@dungpa You may be right.  Got it to repro with the below code.

C.fsi:
```fsharp
namespace CLib

/// C class.  It does C things.
type [<Class>] C =
    /// Displays the string, int, and float.
    member Display: string

    internal new: string * int -> C
    internal new: string * float -> C
```

C.fs:
```fsharp
namespace CLib

type C(s: string, i: int, f: float) =
    new (s, i) = C(s, i, 0.0)
    new (s, f) = C(s, 0, f)

    member this.Display = sprintf "The string i: %s and the int is: %d and the float is: %f" s i f
```

![sig-no-names](https://cloud.githubusercontent.com/assets/6309070/21690859/0ae1c094-d32b-11e6-902c-a3eb795891d8.PNG)

However, I'm not sure that this is the best design, since the tuples do have their elements named.  Eliding those names feels strange.

**Comment by cartermp** [comment]
Tagging as VS Updates.  Not a bug, but you could argue that it's unexpected behavior.
