### ISSUE TITLE
[From VSTS] Type Providers do not seem to work

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2154]
The following is copied from our internal bug tracker from VS Feedback:

> When trying to use FSharp.Data, I get the following error by the compiler:
>
>Error FS3033 The type provider 'ProviderImplementation.CsvProvider' reported an error in the context of provided type 'FSharp.Data.CsvProvider,Sample="C:\\Users\\me\\Downloads\\data.csv",InferRows="10000"', member 'GetSample'. The error: Specified method is not supported. 

I'll try and repro this on my machine.

**Comment by vasily-kirichenko** [comment]
I've just tested current master with the latest FSharp.Data CVS TP and it work both in IDE and at runtime.

**Comment by cartermp** [comment]
Yeah, I can't seem to get this same error.  I'll keep it open for now to see if anyone can repro, but if not, I'll close this in a week or two.
