### ISSUE TITLE
Very wrong type provider usage syntax highlighting

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2155]
![image](https://cloud.githubusercontent.com/assets/873919/21619556/3d436d9c-d201-11e6-8dcd-635b177c9a0e.png)

![image](https://cloud.githubusercontent.com/assets/873919/21619769/30e1ce9e-d202-11e6-999e-17e883d7448d.png)

it works ok on single line TP:

![image](https://cloud.githubusercontent.com/assets/873919/21619738/110acbc0-d202-11e6-9b22-d2907b9d61da.png)

**Comment by cartermp** [comment]
Yikes.  Good find.

**Comment by cartermp** [comment]
Looks like this is a regression based on @vladima's PR.  On vanilla RC2 it works fine:

![tp-classification-old](https://cloud.githubusercontent.com/assets/6309070/21630147/65378f9a-d1e3-11e6-8565-eb65f50dfce0.gif)

**Comment by vladima** [comment]
I'd be surprised given than my changes update only quick info, signature help and completion. This looks like an issue with lexical - the state from the previous line is not propagated to the next line

**Comment by cartermp** [comment]
Hmmm.  @vasily-kirichenko could this be from when you did some refactoring and fixes to lexing logic?

**Comment by vasily-kirichenko** [comment]
Maybe. When I debugged the lexer cache, the "lex sate at start of line" and "lex state at end of line" (int) were always 32769. I have no idea what they are and how they should work though :(

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2158

**Comment by cartermp** [comment]
Nice.
