### ISSUE TITLE
Wrong XML doc indentation in quick info and signature help

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2159]
![image](https://cloud.githubusercontent.com/assets/873919/21642707/44806364-d295-11e6-9df9-1d8735c25334.png)

![image](https://cloud.githubusercontent.com/assets/873919/21642727/5b27e600-d295-11e6-807f-fe60743d8999.png)

The XML doc in source code for that method looks good https://github.com/dotnet/roslyn/blob/614299ff83da9959fa07131c6d0ffbc58873b6ae/src/Compilers/Core/Portable/Text/TextLineCollection.cs#L31-L35

I cannot reproduce it by copy-pasting the comment:

![image](https://cloud.githubusercontent.com/assets/873919/21642855/2e3cc7c2-d296-11e6-8b0b-ab80606603c2.png)

**Comment by cartermp** [comment]
Strange.  Does it indent if you copy-paste that only a member within a class?

**Comment by vasily-kirichenko** [comment]
@cartermp It's formatted ok even being copied to a class.

**Comment by cartermp** [comment]
Huh.  Definitely strange.  cc @vladima

**Comment by vasily-kirichenko** [comment]
Another catch:

![image](https://cloud.githubusercontent.com/assets/873919/21727928/b422591e-d454-11e6-8098-f138c15995e0.png)

I tried to find where the XML Doc text is transformed to `TaggedText` and failed. Maybe a fix may be as simple as adding `Trim` to each element?

**Comment by cartermp** [comment]
@vasily-kirichenko Perhaps it's when this is called? https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.LanguageService/XmlDocumentation.fs#L71

I'm not able to debug ATM

**Comment by cartermp** [comment]
Tagging this for VS Updates, since it's not a critical bug.  I'll defer to @KevinRansom on if a fix for this (if submitted in the next week or two) will make it in or not.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2177
