### ISSUE TITLE
VS FSI does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2160]
1. Ctrl+F5 current master.
2. Open FSI window in the experimental VS instance.

Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> 

unknown(1,1): error FS1225: File 'C:\USERS\VASKI\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D2A776E5FSHARPDEV\EXTENSIONS\MICROSOFT.VISUALFSHARPTOOLS\VISUAL F# TOOLS\15.4.1.9055\FSharp.Core.optdata' not found alongside FSharp.Core. File expected in C:\USERS\VASKI\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D2A776E5FSHARPDEV\EXTENSIONS\MICROSOFT.VISUALFSHARPTOOLS\VISUAL F# TOOLS\15.4.1.9055\FSharp.Core.optdata.

unknown(1,1): error FS0229: Error opening binary file 'C:\USERS\VASKI\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D2A776E5FSHARPDEV\EXTENSIONS\MICROSOFT.VISUALFSHARPTOOLS\VISUAL F# TOOLS\15.4.1.9055\FSharp.Core.dll': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+StopProcessingExn' was thrown.

unknown(1,1): error FS3160: Problem reading assembly 'C:\USERS\VASKI\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D2A776E5FSHARPDEV\EXTENSIONS\MICROSOFT.VISUALFSHARPTOOLS\VISUAL F# TOOLS\15.4.1.9055\FSharp.Core.dll': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+StopProcessingExn' was thrown.
Session termination detected. Press Enter to restart.

**Comment by vasily-kirichenko** [comment]
It may be related to https://github.com/Microsoft/visualfsharp/issues/2098

**Comment by rojepp** [comment]
*sigh* at those optdata/sigdata files.. Wasn't it decided they should be baked in? Can't seem to find that discussion now.

**Comment by majocha** [comment]
I do have #2098 on core projects but FSI seems to work fine both in exp instance and with VisualFSharpOpenSource.vsix installed.

**Comment by vasily-kirichenko** [comment]
@majocha have you ever run `build.cmd vs` to the end successfully?

**Comment by majocha** [comment]
@vasily-kirichenko yes, with some warnings. I just did a `git pull`, `build.cmd`, `build.cmd vs` and installed the vsix.

**Comment by vasily-kirichenko** [comment]
It still does not work in the exp instance. .optdata and .sigdata are missed:

![image](https://cloud.githubusercontent.com/assets/873919/21646718/57142cd2-d2a8-11e6-8ff6-b86e6639d0b3.png)

**Comment by vasily-kirichenko** [comment]
Yes, if I copy those two files manually to ^^^, it works.

**Comment by majocha** [comment]
I tried deleting the experimental instance folder from appdata\local just now and FSI still starts fine on a fresh instance.

**Comment by cartermp** [comment]
@KevinRansom @brettfo We should take a look at this and get it fixed for release.

**Comment by vasily-kirichenko** [comment]
It's still reproduced on current master.

**Comment by dsyme** [comment]
@vasily-kirichenko Is this now working for you?

**Comment by dsyme** [comment]
Given the original bug report was about optdata/sigdata, I will close this.
