### ISSUE TITLE
Minor tweak to Symbol not found error suggestions

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#2169]
@forki 

I got this error today:

````
 c:\kevinransom\visualfsharp\tests\fsharp\test-framework.fs(58,12): error FS0039: The namespace or module 'Commands' is not defined. Maybe you want one of the following:   CommonExtensions   CodeDom   ComparisonIdentity   Compression   ComponentModel [c:\kevinransom\visualfsharp\tests\fsharp\FSharp.Tests.FSharpSuite.fsproj]
````
What's interesting is that Commands was used inside the Commands module.  Which is not legal ... so perhaps the Symbol not found error code should suggest removing 'Command' if it discovers the callsite is inside the Command module?

**Comment by forki** [comment]
How can I reproduce this?

**Comment by forki** [comment]
Mhm after reading again I think I now understand. This is indeed an interesting case and kind of related to general open namespace suggestions.

**Comment by dsyme** [comment]
I think this can be closed, it doesn't seem to be being actioned and is not major
