### ISSUE TITLE
Block structure strangeness with getters and setters

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2190]
![memberblockstructure](https://cloud.githubusercontent.com/assets/64654/21746256/48831b66-d536-11e6-8ce5-7f29db841dce.gif)

It appears that the block structure service is creating a block for the whole member at the same line as the block for the getter. Furthermore the guideline seems to be off (not sure where that's coming from).

The GIF above demonstrates the issue:

* The first click collapses the getter AND whole member
* The second click expands the whole member
* The third click expands the getter

When this issue is fixed I think it would be a good idea to write some new/expand the existing unit tests for the block structure service - it seems like something that would be simple to test.

**Comment by vasily-kirichenko** [comment]
How should it behave? I'm ok to remove collapsing and guidelines for getter and setter altogether.

**Comment by vasily-kirichenko** [comment]
@saul the ported code was named "outlining" in VFPT and we had a good bunch of tests for it, see https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/tests/FSharp.Editing.Tests/OutliningTests.fs I think we should port them, adjusting to the fact that new code returns two kinds of ranges (for guidelines and for collapsible blocks).

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2195
