### ISSUE TITLE
Unexpected block structure guideline with multiple cases on a pattern match

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2191]
Minimal reproduction:

```f#
match x with
| _ // removing this line fixes the issue
| _ ->
    ()
```

![image](https://cloud.githubusercontent.com/assets/64654/21746297/b38604e0-d537-11e6-9593-e8dd32ebaef6.png)

Current master

**Comment by saul** [comment]
This looks like it's a duplicate of #2115.

**Comment by cartermp** [comment]
Yep, let's use that issue to track "block structure looks weird" bugs for now.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2195
