### ISSUE TITLE
Types are not highlighted in FSI

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2193]
Current master

![image](https://cloud.githubusercontent.com/assets/873919/21748789/08ed0d68-d59f-11e6-8dcd-c0d5f27570e7.png)

**Comment by saul** [comment]
I've got a simple fix for this - it's because structs aren't being mapped to a particular colour.

**Comment by saul** [comment]
It works for me:
![image](https://cloud.githubusercontent.com/assets/64654/21749301/0b61f6c2-d594-11e6-8c3e-13d4ae4b96b1.png)

I'm just about to submit a PR.
