### ISSUE TITLE
Unreadable color for keywords in FSI

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2194]
![image](https://cloud.githubusercontent.com/assets/873919/21748804/814b1066-d59f-11e6-906c-2b47065b7332.png)

**Comment by saul** [comment]
I suggested this in the PR (make them green) but Kevin thought they were fine as is. To be fair, the Windows console colour defaults are dire - quite a few of them are unreadable on black as is. It's easy enough to tweak the colour setting  of the console though.

**Comment by forki** [comment]
yes please try to add better defaults

**Comment by vasily-kirichenko** [comment]
I already suggested to steal VS Dark theme colors (but they should be made a bit brighter because the Dark theme uses not completely black background, but very dark gray).

**Comment by vasily-kirichenko** [comment]
This blue color reminds me the same color in ssh bash on windows :) Crazy stuff I must say.

**Comment by saul** [comment]
The VS Dark scheme colours are the same (blue for keywords). The console is limited to 16 colours.

**Comment by vasily-kirichenko** [comment]
Maybe look at other REPLs, line OCaml's?

**Comment by saul** [comment]
OCaml doesn't have colours in its REPL:
![image](https://cloud.githubusercontent.com/assets/64654/21749109/d24c157a-d58e-11e6-8205-05006a4db1f2.png)

**Comment by vasily-kirichenko** [comment]
yeah, there is no better color among the standard 16 :( Is it possible to change the colors as FSI starts?

**Comment by saul** [comment]
I'm of the opinion that the users should change their console colours. All other terminal emulators except Windows Command Prompt provide sane colour defaults (i.e. where blue is clear to read on black) - all other REPLs that use colour have this same issue.

**Comment by vasily-kirichenko** [comment]
What about white color for keywords 

![image](https://cloud.githubusercontent.com/assets/873919/21749196/c616a5ec-d5aa-11e6-8e61-d7f8d48ecb7c.png)

BTW, reference types ^^^ are not highlighted either.

**Comment by vasily-kirichenko** [comment]
And I suggest these colors for strings and numerics

![image](https://cloud.githubusercontent.com/assets/873919/21749229/c7afce78-d5ab-11e6-979b-7a55bf3d754d.png)

**Comment by saul** [comment]
At the end of the day colours are very subjective. I just copied VS's defaults, and we all agreed that the colours should be customisable (see #2179). I agree that those colours work better as defaults on the default Windows Command Prompt, but they do not match VS's colours which could lead to confusion.

**Comment by forki** [comment]
it's not important whether we match default colors if we provide a good default.
I think it's super important to make the default look ok - I personally don't want to customize such things

**Comment by saul** [comment]
With that colour scheme @vasily-kirichenko - you'd have to do a check to see if the console background is white, and if so use a different set of colours (white on white for keywords and yellow on white for strings would have terrible contrast).

**Comment by saul** [comment]
Feel free to submit a PR by the way - the colours that you posted on the other issue seem reasonable and work across many different colour schemes.

Here's a comparison of Windows, Mac, Ubuntu:
https://imgur.com/a/q0zUA

**Comment by slang25** [comment]
The latest PR is much better, this looks awesome =) Although prior to Windows 10 Anniversary Update you only have 16 a color palette to play with, you are able to map the standard 16 to whatever colors you want, so you could use this technique to replicate the VS dark theme (ala Colorful.Consul: https://github.com/tomakita/Colorful.Console/blob/master/src/Colorful.Console/ColorMapper.cs). The downside is you are overriding default mappings / terminal color theme. Maybe with a command line parameter + VS setting to control between standard color palette, our custom palette, and colors off.

Another option is to use the 24-bit color support added to Windows 10 Anniversary Update which uses ANSI color support (virtual terminal sequences), this would work cross-plat too (as would the previous suggestion of remapping the 16 palette ). I can see 2 big problems with this 1. You'd need to detect the support of this on windows, and you can only do it by platform, no way to actually interrogate the terminal (for code, see libuv: https://github.com/libuv/libuv/pull/889#issuecomment-226617598). 2. We don't need a palette greater than 16! So this idea is pointless.

Again, great work, the last few months of PRs have got me very excited for the VS 2017 release, many thanks to all!

**Comment by saul** [comment]
Completed in #2196. @slang25 do you mind adding your comment to the FSI colour customisation issue?

**Comment by saul** [comment]
@vasily-kirichenko please close as it's been fixed in #2196
