### ISSUE TITLE
Puzzling error message in case of wrong indentation inside computation expression

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2201]
![image](https://cloud.githubusercontent.com/assets/873919/21752490/31ffd3c0-d5ea-11e6-9965-7c16a33c7b69.png)

**Comment by dsyme** [comment]
@isaacabraham Please add to your error message tracker? Thanks

**Comment by isaacabraham** [comment]
I assume that the error is caused by the extra space indentation and should be something more like that? This is a general problem that can occur in many, many places.

**Comment by dsyme** [comment]
@isaacabraham Yes :)
