### ISSUE TITLE
"Prefix unused value with underscore" code fix should not appear on double ticked names

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2207]
![image](https://cloud.githubusercontent.com/assets/873919/21768646/c60bfd54-d68b-11e6-9f3b-9850575474ab.png)

**Comment by forki** [comment]
Lol

**Comment by forki** [comment]
Speaking more generally: we should filter suggestions that lead to invalid identifiers.

**Comment by vasily-kirichenko** [comment]
I don't think it's a good strategy, it would hide bugs in suggestions.

**Comment by forki** [comment]
I'm fine with handling these incrementally whenever we see one appearing

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2424
