### ISSUE TITLE
Completion is broken for double backticked names

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2211]
They did not appear at all. After fixing it, they do appear (without backticks, which is OK I think):

![image](https://cloud.githubusercontent.com/assets/873919/21777227/03321df8-d6af-11e6-8a6c-e7fdba1bcf3d.png)

back <Enter> does not add backtickes:

![image](https://cloud.githubusercontent.com/assets/873919/21777273/31c35ac4-d6af-11e6-8281-cc6cc8373734.png)

Same for TPs:

![1](https://cloud.githubusercontent.com/assets/873919/21777315/58951f98-d6af-11e6-8138-0b3999d0f307.gif)

These screenshots are on this PR https://github.com/Microsoft/visualfsharp/pull/2212

**Comment by vasily-kirichenko** [comment]
@dsyme @vladima could you comment on this? How it worked in pre-Roslyn era?

**Comment by vasily-kirichenko** [comment]
Any why space is among characters which allowed in operator here https://github.com/Microsoft/visualfsharp/blob/ed948abaec8e2723c4fcafbde969a1071a4d72b1/src/fsharp/PrettyNaming.fs#L117?

**Comment by vasily-kirichenko** [comment]
I think we should use this http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionItemRules.cs,54 to amend backticks-free long ident on commit (<Enter>). Or maybe not. Ideas?

**Comment by vasily-kirichenko** [comment]
No, the rules are for completely different stuff. I'm out of ideas. 

@Pilchie help. What we basically need is to show identifiers like 
```fsharp
``long ident``
```
without the backticks in the completion list, but insert them _with_ backticks into document when completion is committed. I cannot find anything useful in `CompletionItem` type.

**Comment by vasily-kirichenko** [comment]
Oh, it seems I've found the right place http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionProvider.cs,54

**Comment by Pilchie** [comment]
@cyrusnajmabadi and/or @rchande can answer the question above if you still need it.

**Comment by CyrusNajmabadi** [comment]
Your scenario is totally supported.  Basically, you can store whatever data you want on a CompletionItem (like the text you'd like to insert).  Then you implement CompletionService.GetChangeAsync to grab and insert that text if it is available.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2212

**Comment by saul** [comment]
@vasily-kirichenko if this is fixed can it be closed? :)
