### ISSUE TITLE
Wrong suggestion

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2214]
![image](https://cloud.githubusercontent.com/assets/873919/21797252/14b8bb16-d71f-11e6-856a-a7cc043fe942.png)

Here it should not suggest anything because module `N` is in scope.

**Comment by forki** [comment]
Mhm this is interesting. Here the compiler is emitting 2 different errors. First the FS0039 for module N and then FS0599 ("Missing qualification after .") at the .

Tbh I think the FS00039 itself is not correct and the suggestion is just an aftereffect.

**Comment by saul** [comment]
@vasily-kirichenko can this be closed now that #2218 is merged?

**Comment by vasily-kirichenko** [comment]
I confirm the bug has been fixed.
