### ISSUE TITLE
Suggestions do not work properly for double backticked identifiers

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2217]
1. No suggestions for normal double backticked identifiers.
2. Wrong suggestion for generated property (wrong title, no preview):

![image](https://cloud.githubusercontent.com/assets/873919/21802737/fd4d5900-d737-11e6-9a0e-ae0f9e5800f2.png)

**Comment by forki** [comment]
fixed with #2218
