### ISSUE TITLE
Cannot open F# source files in VFT solution, except FCS project

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2227]
1. build.cmd vs on current master
2. Install VisualFSharpOpenSource.vsix
3. open VisualFSharp.sln
4. Try to open any file from FSharp.Editor project

![1](https://cloud.githubusercontent.com/assets/873919/21862454/51c1be96-d84a-11e6-933a-8376625e01ac.gif)

**Comment by cartermp** [comment]
I can't repro this since I cannot install VisualFSharpOpenSource.vsix 😞

**Comment by vasily-kirichenko** [comment]
I reinstalled the VSIX and the bug gone. No idea what it was.
