### ISSUE TITLE
Breakpoint Resolution on if/else expression resolves to last else clause when on same line

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2229]
![bp-resolve-end](https://cloud.githubusercontent.com/assets/6309070/21871146/187a3922-d815-11e6-9b30-580c7943ca90.gif)

When I set that breakpoint and call the code, and `s1` is equal to "hello", the breakpoint never hits.

#### Expected behavior

Resolves to `let! res1`.  When it's a return expression, it resolves to the predicate.

#### Actual behavior

Always resolves to last sub-expression.

#### Known workarounds

Split the code up to multiple lines.

**Comment by smoothdeveloper** [comment]
The behaviour in 2015:

```fsharp
if id < 0 then None else Some(getDeviceById id)
^-------------^    ^----^
```
resolves to if predicate

```fsharp
if id < 0 then None else Some(getDeviceById id)
               ^--^
```
resolves to None expression

```fsharp
if id < 0 then None else Some(getDeviceById id)
                         ^--------------------^
```
 resolves to the else expression

**Comment by cartermp** [comment]
This is a regression of behavior @smoothdeveloper describes due to the changes made in #1918.

Basically, #1918 made it so you can set a breakpoint in many more places than before via clicking, but the result is that in single-line `if..then..else` cases like this, the list of ranges that are yielded will contain all three expressions - the predicate, the `then` expression, and the `else` expression.  Because the code simply takes the last item in that list, it always resolves to the `else` expression.

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper I don't understand your samples. Could you shoot a gif?

**Comment by vasily-kirichenko** [comment]
More importantly, what the _right_ behavior should be?

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko here is a screen capture
![ifbreakpoint](https://cloud.githubusercontent.com/assets/87944/21881603/797c9b08-d8a5-11e6-927b-92d89b488e91.gif)

To me that is the right behaviour and consistent with other languages.

**Comment by forki** [comment]
For me this is still broken on master and alsways selects the last part:

![debug](https://cloud.githubusercontent.com/assets/57396/21889570/e97e34ce-d8c9-11e6-9163-e082ab7aa3c4.gif)
1

**Comment by forki** [comment]
This is how it worked in VS2015:

![debug](https://cloud.githubusercontent.com/assets/57396/21889647/4ce8af1c-d8ca-11e6-8e15-2fa26757680d.gif)

so this is a regression

**Comment by vasily-kirichenko** [comment]
@forki what's happening if you click on the margin to set the breakpoint?

**Comment by forki** [comment]
VS 2015:

![debug1](https://cloud.githubusercontent.com/assets/57396/21889850/3d0871f8-d8cb-11e6-914d-fe0d10e414da.gif)

VS2017 RC (on master):

![debug2](https://cloud.githubusercontent.com/assets/57396/21889871/5bb4eb4a-d8cb-11e6-955a-6087d6cc3c74.gif)

so same bug.
