### ISSUE TITLE
f9 breakpoints on if expressions on the same line don't resolve correctly.

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2230]
As reported by @smoothdeveloper:

When setting a breakpoint with f9 on a single-line `if` expression, it will always resolve to the last sub-expression.

The behavior in 2015:

```fsharp
if id < 0 then None else Some(getDeviceById id)
^-------------^    ^----^
```
resolves to if predicate

```fsharp
if id < 0 then None else Some(getDeviceById id)
               ^--^
```
resolves to None expression

```fsharp
if id < 0 then None else Some(getDeviceById id)
                         ^--------------------^
```
resolves to the else expression

**Comment by KevinRansom** [comment]
Symbol type: full, pdbonly or portable?

**Comment by cartermp** [comment]
@KevinRansom not sure, but this is in a debug hive.

**Comment by KevinRansom** [comment]
Almost certainly full then.
