### ISSUE TITLE
Autocompletion for double backtick unions doesn't work

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2231]
![union](https://cloud.githubusercontent.com/assets/57396/21881640/69e37a84-d8a7-11e6-933b-822908fecb05.gif)

/cc @vasily-kirichenko

**Comment by vasily-kirichenko** [comment]
What about types in general?

**Comment by forki** [comment]
![union](https://cloud.githubusercontent.com/assets/57396/21881872/5c173ad4-d8a8-11e6-9e25-b9a9d996231b.gif)

same thing

**Comment by forki** [comment]
also squigglies:

![image](https://cloud.githubusercontent.com/assets/57396/21881901/805f14a2-d8a8-11e6-9288-d3ec93b5a716.png)

**Comment by forki** [comment]
and since ranges are incorrect, we get wrong suggestion as result:

![image](https://cloud.githubusercontent.com/assets/57396/21881938/a46f5dd4-d8a8-11e6-81e0-7cb5f5cd5118.png)

**Comment by forki** [comment]
added a test: https://github.com/Microsoft/visualfsharp/pull/2233

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2235
