### ISSUE TITLE
Rename should automatically handle double backticks

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2232]
![union](https://cloud.githubusercontent.com/assets/57396/21882229/da75f342-d8a9-11e6-9987-0ce139cf6697.gif)

/cc @vasily-kirichenko

**Comment by vasily-kirichenko** [comment]
Should it remove existing backticks if the identifier does not need them anymore?

**Comment by forki** [comment]
yes sure!

**Comment by forki** [comment]
![union](https://cloud.githubusercontent.com/assets/57396/21882304/28bd0752-d8aa-11e6-800b-7159fd6afee9.gif)

**Comment by vasily-kirichenko** [comment]
Roslyn does support amending new symbol name, but it's apparently broken, see https://github.com/dotnet/roslyn/issues/16460

**Comment by vasily-kirichenko** [comment]
WIP PR implementing it https://github.com/Microsoft/visualfsharp/pull/2236

**Comment by dsyme** [comment]
Fix upstream
