### ISSUE TITLE
Compiler errors are duplicated

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2241]
As requested by @KevinRansom in the comment on #2142.

Compiler errors appear duplicated, resulting in us needing to HashSet them in FSharpDocumentDiagnosticAnalyzer.GetDiagnostics.

**Comment by dsyme** [comment]
@saul We need a repro for this please

**Comment by dsyme** [comment]
To be honest there are many cases where errors and warnings are duplicated.  Enough things are multi-pass in analyzing types that it's very difficult to stop.  Probably the best thing is to HashSet the errors as they come out of fsc.exe

**Comment by saul** [comment]
@dsyme I don't have a repro - you're best asking @vasily-kirichenko. I only created this ticket as Kevin requested it in the attached PR.

**Comment by dsyme** [comment]
OK.  I think I'll close this as the current behavior is not a huge problem
