### ISSUE TITLE
Normalize F# file/assembly/package versions

### ISSUE THREAD

**Issue by brettfo** [Microsoft/visualfsharp#2252]
This is a longer-lead item to make F# versions more like Roslyn versions, which also embed the build number and commit hash into their binaries.

**Comment by dsyme** [comment]
@brettfo Milestone/severity?

**Comment by cartermp** [comment]
@brettfo is this still valid to be open now that we embed the build and commit hash?

**Comment by brettfo** [comment]
I think we can call this complete.
