### ISSUE TITLE
Static vs. nonstatic method conflicts are not properly reported

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2255]
If we access a non-static property in static way, then the compiler shows corresponding error.
This should be similar for methods.

![image](https://cloud.githubusercontent.com/assets/57396/21954713/bfb07e54-da59-11e6-846c-622b187f4023.png)

**Comment by vasily-kirichenko** [comment]
Looks like an easy fixable having that `NameResolution.fs` stuff explored? :)

**Comment by forki** [comment]
seems harder than I expected. This is raised on method overload resolution deep in ConstraintSolver

**Comment by forki** [comment]
OK I think I found something

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/21954917/7cf30e78-da5f-11e6-9f68-e56015957a74.png)

**Comment by forki** [comment]
fix in #2256

btw the opposite case already worked as well:

![image](https://cloud.githubusercontent.com/assets/57396/21954965/e5fb574e-da60-11e6-83b3-3e0d77fd9a3d.png)
