### ISSUE TITLE
PR #2093  broke Json.NET

### ISSUE THREAD

**Issue by majocha** [Microsoft/visualfsharp#2257]
commit 13b0ba050d450ca09a3e461d6355e490a273fca9 introduced a change that breaks Json.NET deserialization of lists.

#### Repro steps
add `Microsoft.FSharpLu.Json` from NuGet

execute:

```fsharp
#r "Newtonsoft.Json"
#r "Microsoft.FSharpLu.Json"
open Microsoft.FSharpLu.Json
let u: int list = [1; 2; 3] |> Compact.serialize |> Compact.deserialize
```

#### Expected behavior
`val u : int list = [1; 2; 3]`

#### Actual behavior

"Newtonsoft.Json.JsonSerializationException: Cannot create and populate list type Microsoft.FSharp.Collections.FSharpList`1[System.Int32]. Path '', line 1, position 1."

#### Related information 
master branch
net40

Can't say anything about severity. Newtonsoft.Json is quite a popular library, for sure.

edit to add repro directly using Newtonsoft.Json
```fsharp
#r "Newtonsoft.Json"

open Newtonsoft.Json

[1; 2; 3] 
|> JsonConvert.SerializeObject 
|> JsonConvert.DeserializeObject<int list>
```

**Comment by smoothdeveloper** [comment]
@majocha it might be worth to track a bug on https://github.com/Microsoft/fsharplu I doubt we can say it is a compiler bug if some library breaks because a type exposes a new interface.

**Comment by forki** [comment]
does it also break direct serialization in json.net? TBH 13b0ba0 seems absolutely harmless

**Comment by majocha** [comment]
@forki, unfortunately it does. 
Json.net assumes F# list doesn't implement IReadOnlyCollection
[link](https://github.com/JamesNK/Newtonsoft.Json/blob/b8e60c773bfbd765b9131694a01569e067b37d99/Src/Newtonsoft.Json/Serialization/JsonArrayContract.cs#L181)

**Comment by forki** [comment]
ok. then we should log that with JSON.NET and ask @fgreinacher and @JamesNK

**Comment by majocha** [comment]
I'm not sure if the moment is right. If this change makes it into RC3 there will be simpler way to repro and test for it.

**Comment by forki** [comment]
afaik this is merged in RTM branch

**Comment by vasily-kirichenko** [comment]
I doubt there will be RC3 at all.

**Comment by JamesNK** [comment]
How come `FSharpList`1` doesn't have a constructor that takes an `IEnumerable`1`? If it had one then it would automatically work with Json.NET

**Comment by dsyme** [comment]
@JamesNK Yeah, I'm sorry about this.  FSharpList is just a bit odd-looking from the C# perspective and doesn't have the usual shape for a collection.  As @cartermp says this is because it happens to be defined as an F# discriminated union.  

@JamesNK Can you fix this in Json.NET?

@cartermp  @KevinRansom It's a real shame that adding IReadOnlyCollection has busted something so fundamental - it's a lesson to me that it's not necessarily worth changing anything in FSharp.Core, and not so late in the development cycle

**Comment by fgreinacher** [comment]
https://github.com/JamesNK/Newtonsoft.Json/pull/1181 has the fix for Json.NET.

**Comment by fgreinacher** [comment]
Important question: When will F# 4.1 be released? I think @JamesNK wants to release the next Json.NET version after VS 2017 is out.

**Comment by cartermp** [comment]
@fgreinacher F# 4.1 will ship alongside VS 2017 (although you can use it in production today due to the Go-live license in vs2017 RC, and it's available in Ionide for VSCode).

**Comment by cartermp** [comment]
@dsyme Agreed regarding the development cycle.  We should honor a cutoff date.

**Comment by liboz** [comment]
Sorry about causing this. I didn't expect adding that interface to cause any issues really. Is there anything that can be done in the future to stop issues like this from happening other than having a cutoff date?

**Comment by KevinRansom** [comment]
@liboz

This is a good change that we would have taken for FSharp.Core it improves F# interop with C#.  It demonstrates, however, why we are resistant to last minute changes, the dotnet eco-system is huge and destabilizing that is always risky.

The issue with json.net and fsharplist has been found and fixed, so the preview process worked well ... if somewhat uncomfortably for all involved.

Kevin

**Comment by JamesNK** [comment]
Fix is merged in Json.NET

I'll probably do a new pre-release version on NuGet sometime soon so this is available for people who use the latest version of FSharp.Core. The next non-prerelease version of Json.NET will come out after VS2017.

**Comment by dsyme** [comment]
Closing as this has been dealt with

**Comment by dsyme** [comment]
Fix is in Json.NET 9.0.2-beta and later

https://www.nuget.org/packages/Newtonsoft.Json/9.0.2-beta2
