### ISSUE TITLE
Issue with CLIMutable record optimization

### ISSUE THREAD

**Issue by miegir** [Microsoft/visualfsharp#2262]
When compiled with optimization (in Release build), the compiler inlines record field access. In general it is good idea, but not with CLIMutable records.

#### Repro steps

Run the following code:
```F#
[<CLIMutable>]
type Args = 
    { Name : string }

module Updater = 
    open System.Reflection
    
    let update args = 
        // update args.Name through reflection
        args.GetType().InvokeMember("Name", BindingFlags.SetProperty, null, args, [| "Test" |]) |> ignore

module Actor = 
    open System
    
    let act name = 
        let args = { Name = name }
        Updater.update args
        Console.WriteLine(args.Name)

[<EntryPoint>]
let main argv = 
    Actor.act "Hello"
    0 // return an integer result code
```

#### Expected behavior

The program outputs "Test" in both Debug and Release builds. The compiler should not optimize access to CLIMutable record fields.

#### Actual behavior

The program outputs "Test" in Debug build, but "Hello" in Release build. In the release `act` method, access to args.Name is optimized to directly use the name parameter. This optimization does not consider that ars is CLIMutable record and can be therefore changed externally.

#### Known workarounds

The workaround is to mark the args variable mutable:
```F#
let mutable args = { Name = name }
```
But it is not so obvious to detect this issue and find that workaround, especially as the issue occurs only in Release builds and mutability of the args variable is not required in F# code here.

#### Related information 

* Operating system: Windows 10
* Branch: F# 4.0 RTM
* .NET Runtime: 4.0
* Editing Tools: Visual Studio 2015 Update 3

**Comment by vasily-kirichenko** [comment]
I think the related code is over here https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/Optimizer.fs#L2938

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2263

**Comment by saul** [comment]
@miegir / @cartermp can this be closed now that the fix has been merged?
