### ISSUE TITLE
Wrong error "type is not structurally comparable" if some fields of a record definition are unresolvable

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2268]
![image](https://cloud.githubusercontent.com/assets/873919/21985524/2e453874-dc0c-11e6-8d9c-f7a1665ec368.png)

![image](https://cloud.githubusercontent.com/assets/873919/21985537/3b56d3ba-dc0c-11e6-94e0-5bd13946b4db.png)

**Comment by dsyme** [comment]
There is a systematic issue in the compiler where we return ``obj`` as the type in error recovery.  IIRC normally this is an "error" type variable solved to equal ``obj``.  By more systematically checking for is-erroneous-type-variable then I think it's possible to remove errors like this.

We could alternatively have an explicit "error" type though that might cause as many problems as it solves (and, with the error flag on a solved type variable, we already effectively have this information, we're just not using it)/

**Comment by dsyme** [comment]
@isaacabraham Could you please add this to the "improved error reporting" bug tracker? thanks

**Comment by vasily-kirichenko** [comment]
Duplication of https://github.com/Microsoft/visualfsharp/issues/777
