### ISSUE TITLE
Outlining and Structure Guidelines do not work with a global namespace

### ISSUE THREAD

**Issue by dhwed** [Microsoft/visualfsharp#2274]
Note that the expand/collapse boxes and the dashed vertical lines disappear when the namespace is global.

![42d5e1d0-dbee-11e6-9990-8bfc84cb77cf 1](https://cloud.githubusercontent.com/assets/10184638/21996302/39d76760-dbef-11e6-81f8-a20eaa992aaa.png)

**Comment by smoothdeveloper** [comment]
I know in C# `global::` allows to disambiguate names that are meant to be fully qualified, in F# the same syntax is `global.` and can clash with namespace named the same.

In F#, is there a way to disambiguate a namespace named `global` from the keyword?

**Comment by dhwed** [comment]
A namespace that is named 'global' would be declared like this: ```namespace ``global`` ```.

To use it, you would have to either ```open ``global`` ``` or call ``` ``global``.Whatever()```

Note that `namespace global` is not declaring a namespace named 'global', it is simply the equivalent of not using a namespace block at all in C#.

**Comment by forki** [comment]
see https://github.com/Microsoft/visualfsharp/pull/2278
