### ISSUE TITLE
Updated: Announcement for VS2017 RC3

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2276]
**Update:**

RC3 has shipped.  To install the _proper_ F# tools on RC3, see these instructions: https://github.com/Microsoft/visualfsharp/releases/tag/Visual-Studio-2017-RC3

These changes are already in the RTM release of Visual Studio 2017.

**Original post below:**

Hey folks,
 
The latest VS2017 RC3 will not include updates to the F# tools over RC2. This is due to a mistake on our part, causing us to miss the update window for the new bits. We had significant improvements made by the community in the past weeks that therefore won’t be included in RC3, although all these changes will be in the final product.
 
To use the updated F# tools in VS2017 RC3, we will be providing a separate signed VSIX that you can install. To anyone who hasn't been following GitHub closely, these bits fix multiple bugs and introduce many new features. The bits included in this VISX have already been inserted into the release build for VS 2017, so they will be available when VS 2017 ships.
 
We sincerely apologize about this, and we have taken steps to make sure that this does not happen again.
 
We hope that you will install the VSIX and keep providing feedback. We’re very grateful for your involvement in helping us bring F# tooling up in VS 2017, and we’re devoted to continually working with you to make the Visual Studio experience for F# amazing.
 
Sincerely,
The Visual F# Team

**Comment by smoothdeveloper** [comment]
@cartermp what is the cut-point of things that will ship for RTM?

**Comment by KevinRansom** [comment]
@smoothdeveloper 

We will let you know what is in RTM when we are able, these decisions are not solely in our hands, there is a huge VS team with differing sets of priorities and assessments of risks.  At the absolute minimum everything that is in the rc3 branch right now will be in.

Kevin

**Comment by saul** [comment]
That's a shame - will details as to how to install this VSIX be in the VS release notes? Slightly concerned that all of the changes made since RC2 won't be tested as heavily as those in the previous RCs and it's going straight to RTM with less testing.

**Comment by cartermp** [comment]
@saul We're still deciding where best to place instructions for installation.  Unfortunately, yes, this does mean that those bits are going to have less people hammering on them.

**Comment by smoothdeveloper** [comment]
@cartermp the anouncement (when RC3 and vsix download links are set) should be sent to the F# open source mailing list.

**Comment by vasily-kirichenko** [comment]
Please, test the VSIX internally before making it available for download. I mean, after installing on top of RC2:

* it replaces the compiler in ...sdsk\f#\4.1\... (the Open source vsix does not do it)
* VisualFSharp.sln can be loaded and all the features work on all projects, without having to unload fsharp.core

**Comment by forki** [comment]
I have no words. Honestly wtf is happening in Redmond? Where is the last minute rush to make the F# bits in VS 2017 a success? There is basically no visible activity from the Visual F# team at all any more. Very few bug reports and no fixes at all. I always thought you are doing all the important invisible work that is needed to get best integration (things like having F# ticked by default). 

But now this? I begin to wonder if there exists a VF# team at all. This feels extremely bad, especially if you are like vasily and myself and basically devoted all of your time to fix things after first RC. 

I'm super sad right now.

**Comment by isaacabraham** [comment]
Disappointing, embarrassing, frustrating. I only feel sympathy for everyone that bust a nut over the past few weeks to get stuff fixed only for it to miss the last RC.

**Comment by dungpa** [comment]
This is so sad. What can we do to ensure usable RTM for Visual F#?

**Comment by forki** [comment]
since RC2 stopped working (see https://github.com/Microsoft/visualfsharp/issues/2286) and RC3 is not available - do we now a new window for putting in our stuff? ;-)

**Comment by OnurGumus** [comment]
Please sign and spread the word:
https://www.change.org/p/microsoft-make-visual-f-a-true-first-class-net-language-with-proper-tooling-and-uwp-support

**Comment by Krzysztof-Cieslak** [comment]
Instead of signing it, contribute to OSS project. 

Nothing good will happen, as long as we are stuck in "MSFT needs to do everything for us" mentality. 

And you can target UWP without any problems... With Fable + ReactNative

**Comment by OnurGumus** [comment]
@Krzysztof-Cieslak, No you are incorrect.  No body said "MSFT needs to do everything for us" here. Of course contributing is definitely a good way to help. However, Especially with UWP support, please be aware of the fact it is not OSS, and not contributable by anyone else besides Microsoft. Also, the core part of visual studio,and many tools from Visual Studio are not open source.  

I certainly believe people who work on Visual F# from Microsoft side are doing fantastic job. But they are certainly outnumbered. 

So there is a serious management problem here from the Microsoft side. The person / people / team who decides how much resource should be used for Visual F# project is apparently  making a mistake, under-estimating the demand and the work load of the current team.

The goal of this campaign to make higher management of Microsoft to be aware of this management problem here so that a more serious effort will be put this project from their side including the fixes like UWP and other closed source tooling. It is NOT about attracting more developers.

**Comment by wastaz** [comment]
If it had been the C# tools, can anyone really say with a straight face that this could have happened?

I'm speechless. :(

**Comment by vasily-kirichenko** [comment]
> I certainly believe people who work on Visual F# from Microsoft side are doing fantastic job.

Hm. I'm afraid there is not such thing as "VFT team" at Microsoft at all. What I've seen for last month were 1 or 2 part-time developers spending about 1-2 hours per week on VFT.

**Comment by AngelMunoz** [comment]
I agree With @Krzysztof-Cieslak most of the good F# stuff I've seen recently has been made by the open source community and given that VF# remains a some sort of second player instead a first class citizen waiting for MSFT to do stuff is a waste of time,  this kind of mistakes proves that either wrong management or no interest at all,  clearly the priority is not F# neither is one of them.

**Comment by misterspeedy** [comment]
Has the VSIX mentioned been made available yet? There are people out here (including me) who are preparing materials for VS launch and therefore need the final version.  Thanks!

**Comment by Andrew-Webb** [comment]
It's a weird catch-22 position.  The more the open source community does for F#, the more MS management will rely on it to do so.  I've been confused and frustrated by MS's dithering about F# for years.  Frankly it's put me off a bit, even though I love the language.

I think MS is a deeply divided house on this issue.  Also: they have to consider very carefully where to deploy their resources, which aren't limitless.  I also think that management regard F# as too high up on the blub scale for them and their (perceived) target audience of C# and VB developers.  Operator-heavy F# source code can look very intimidating.

Recently, I've been finding that it's much more fun and rewarding to work in an environment (the PureScript language + libraries + tools) that is just OSS community - more or less - and there is no confused relationship with the mighty corporate giant.  Everyone knows where they stand.

**Comment by cartermp** [comment]
@misterspeedy No, the VSIX isn't available yet.  VS2017 RC3 hasn't shipped yet, so such a VSIX would likely fail to install on any version of VS2017 you have right now.

**Comment by misterspeedy** [comment]
@cartermp I'm confused.  The install I have right now says it's RC3 - is there a distinction between "available for download" and shipped?
<img width="299" alt="capture" src="https://cloud.githubusercontent.com/assets/800686/22282478/9e48b99c-e2d4-11e6-8329-cdadd9ed3f44.PNG">

**Comment by OnurGumus** [comment]
Today I was filling a survey sent by Microsoft about getting some feedback from windows insiders. It's in Turkish and asking which programming languages I use for development. It might give you another clue about Microsoft's stance on F#:

![fsharp](https://cloud.githubusercontent.com/assets/4114592/22286484/fda05792-e2f7-11e6-9f7a-c53f96cc1be0.png)

**Comment by smoothdeveloper** [comment]
The same thing at jetbrains (with better layout):

![image](https://cloud.githubusercontent.com/assets/87944/22288307/a118f6a6-e2f6-11e6-8827-bc4dbde056f9.png)

**Comment by forki** [comment]
Lol that one is good to reinforce @jetbrain's bias against F# ;-)

**Comment by cartermp** [comment]
@misterspeedy I've asked about what you're seeing (no response yet).  I know for a fact that today is *not* the day that RC.3 goes out, so I'm not sure why you're seeing that in the installer.  Just as a quick check, if you open up the installer and select .NET Desktop Development, what do the checkboxes on the side look like?

**Comment by misterspeedy** [comment]
@cartermp Thanks for following up. Installer screenshot attached.

<img width="929" alt="installer" src="https://cloud.githubusercontent.com/assets/800686/22331290/990698fc-e3c2-11e6-9f14-c7badc29a065.PNG">

**Comment by misterspeedy** [comment]
@cartermp ...and here's how it shows in my start  menu.

<img width="298" alt="startmenu" src="https://cloud.githubusercontent.com/assets/800686/22331306/b06b2120-e3c2-11e6-8de0-1561994cb0ac.png">

**Comment by misterspeedy** [comment]
@cartermp ...by the way I downloaded and first ran the installer on 19th Jan.

**Comment by cartermp** [comment]
@misterspeedy It looks like that's still a previous RC.  Perhaps there was a small bug which named a download RC3, which is likely the source of this confusion.

**Comment by cartermp** [comment]
FYI: RC3 has officially been released, and the instructions and downloads are here: https://github.com/Microsoft/visualfsharp/releases/tag/Visual-Studio-2017-RC3

**Comment by kit-i2o** [comment]
@cartermp Thanks Phillip. ;-)

**Comment by OnurGumus** [comment]
Sorry but where are the instructions ? How do we install this ?

**Comment by vasily-kirichenko** [comment]
@OnurGumus they removed the instructions because RC3 was unpublished due to a critical bug.

**Comment by forki** [comment]
Everything was taken down because VS RC 3 was taken down. Now the rc is back online but the vf# stuff is not. We have to wait until @cartermp wakes up

**Comment by vasily-kirichenko** [comment]
@forki it would be very polite if he give his phone number to us, just in case :)

**Comment by cartermp** [comment]
@forki I don't think the RC is back online - the release available in the installer is 15.0.26020.0, which is an RC2 release.  There are some comments stating the same thing: https://blogs.msdn.microsoft.com/visualstudio/2017/01/26/update-to-visual-studio-2017-release-candidate/#comments

I've sent out mail to clarify if RC3 is available or not today.

**Comment by majocha** [comment]
RC3 is back online. Installing 15.0.26127.0 right now.

**Comment by cartermp** [comment]
RC3 is indeed back online!  Instructions are here: https://github.com/Microsoft/visualfsharp/releases/tag/Visual-Studio-2017-RC3

**Comment by petertiedemann** [comment]
How do i verify that the new tooling installed correctly? Is this the new version?:

![image](https://cloud.githubusercontent.com/assets/1265354/22394728/4610357e-e528-11e6-850b-1a8648ceca34.png)

**Comment by JohnCSimon** [comment]
I'm seeing 15.4.1.17012301 in the uninstall dialog, I'm running the latest VS 2017 RC3

I do a file->NewProject-> F# Tutorial
I close out of VS by clicking file->close solution and it hangs VS. Anyone else seeing this?
![Uploading 2017-01-27 22_13_54-Tutorial2 - Microsoft Visual Studio.png…]()

**Comment by cartermp** [comment]
@petertiedemann After installing the VSIX my version is 15.4.1.17012301.  You can test a few features to verify, though:

* Find all References
* F1 on a type or keyword
* Colorization in hovers and IntelliSense

All of the above should be working.  There will be a more complete list of the features added when VS is at RTM.

@JohnCSimon This is a known issue: #2022.  Key bit is [here](https://github.com/Microsoft/visualfsharp/issues/2022#issuecomment-273943221) it's an inconsistent issue and difficult to peg down a repro.  We're going to be looking into it in a future update.  I'm not aware of a workaround, save for a reinstall of the tools.

**Comment by petertiedemann** [comment]
@cartermp 
The things you mention works, but renaming a symbol fails:

![image](https://cloud.githubusercontent.com/assets/1265354/22395076/e324c712-e532-11e6-8ff7-1e036f40a736.png)

**Comment by cartermp** [comment]
@petertiedemann Yup - also a known issue: #2328.  We've had to disable it temporarily, hence the dialog.  It's unlikely that we'll be able to fix a reference issue + re-enable the feature in time for RTM...we're currently working on spinning a new build with updated Roslyn references to see if we can get the feature re-enabled without issue.  If it doesn't make the cut, it will be available very soon after vs2017.

**Comment by petertiedemann** [comment]
@cartermp Ah ok, did look at #2328, but saw that the error dialog was different.

Anyway, i guess i will stick with 2015 for now.

**Comment by vasily-kirichenko** [comment]
@cartermp would you just republish Full vsix as Inline Rename and suggestions fixed?

**Comment by cartermp** [comment]
@vasily-kirichenko Yep, when we can generate a build we can republish the VSIX (and MSI as needed).

**Comment by OnurGumus** [comment]
Wow, hovering feature is fantastic and it was much needed for functional programming. Works great! Thank you.

**Comment by forki** [comment]
"hovering feature"?

Am 28.01.2017 20:57 schrieb "Onur Gumus" <notifications@github.com>:

**Comment by OnurGumus** [comment]
@forki, When I mouse over an identifier or a type, the tooltip appears to be in colors and more detailed. This is a new feature in 2017, if I am not mistaken.

**Comment by cartermp** [comment]
@OnurGumus This is a new feature, yes.  Good work done by @vladima, with further improvements made by @vasily-kirichenko.

**Comment by cartermp** [comment]
Closing as we're nearing RTM and have already released RC4 which has all of these features.
