### ISSUE TITLE
RC2 has stopped working

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2286]
![image](https://cloud.githubusercontent.com/assets/873919/22055792/f0297e66-dd6d-11e6-8a0b-c3e61249ccce.png)

**Comment by forki** [comment]
running VS Installer and upgrading all the things didn't work for me. License still expired ;-(

**Comment by vasily-kirichenko** [comment]
I think it's because RC3 is being (slowly) released right now. Veeery slooowly...

**Comment by forki** [comment]
there should be some explict order in these things - other than the one that is used  ;-)

**Comment by vasily-kirichenko** [comment]
Just pray it includes VFT RC2. Chances are we will find RC there. Or won't find anything at all. Who knows...

**Comment by forki** [comment]
ok installer always installs 15.0.26020.0 - what now?

**Comment by vasily-kirichenko** [comment]
I think they've turned off RC2, but have not publish RC3 yet. Very safe choice so to say.

**Comment by StefanKoell** [comment]
Testing nowadays is overrated...

**Comment by cartermp** [comment]
This is a bug in VS platform.  I've reached out for more information, but this isn't something we can control.

**Comment by forki** [comment]
this should not be closed without a proper public issue where we can point people to.

**Comment by cartermp** [comment]
Good point.  I'll leave it open until the license issue gets resolved.

**Comment by forki** [comment]
someone pressed a button and it seems to work again.
so we can file this under "living in wrong timezone"
