### ISSUE TITLE
Discussion, ways to enhance compile time of compiler in development?

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2293]
I don't know if some of you are acquainted with Resharper Build (https://blog.jetbrains.com/dotnet/2015/10/15/introducing-resharper-build/), it has a "Public API surface monitoring" which could provide quick gain in development feedback loop, this saves me lots of time any day.

My thinking is that FSharp.Compiler project has a cohesive set of subfolders, and each could be a separate project with normal project dependencies; right now changing anything in that project incurs recompile of the whole project.

With Resharper Build, it could mean just compiling a single folder, even if the folder is at the top of the project, as long as no public symbol which is depended upon has changed, even in such case, it would only recompile the other projects that actually depend on those symbols and not all of them.

I'd prefer F# to have fine grained incremental compilation but this is probably not going to come overnight, but it feels this work around could be quite effective and save time to developers who don't compile on fastest machines available.

**Comment by dsyme** [comment]
Closing this as it's an inactive discussion
