### ISSUE TITLE
Deprecate Dictionary.ofList in illib.fs

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2297]
This function is very slow, it is convenient, but forces to allocated lists and tuples just to populate a dictionary.

It is also a place where the infamous `List.length` is called.

Calling Dictionary.Add in place at usage site seems to be close to 10 times faster (I've taken the size of all calls, loading a project in FSI to check), this might add few lines of code at the call sites but is the only way I've found to get the good performance.

The function is called 9 times in the code:

* absil\illib.fs
* absil\il.fs
* absil\ilmorph.fs
* absil\ilbinary.fs
* fsharp\TcGlobals.fs
* fsharp\MethodCalls.fs
* fsharp\IlxGen.fs

I'll prepare a codebase discarding it's usage.

**Comment by smoothdeveloper** [comment]
@dsyme could you comment on usage in `betterTyconRefMap` (https://github.com/Microsoft/visualfsharp/blob/f3b72d6f3cb44460c81acc8b5eadb63c9dea27a5/src/fsharp/TcGlobals.fs#L679) I think this one is just executed once and won't impact much, is it right?

**Comment by smoothdeveloper** [comment]
it doesn't amount to any visible difference to replace the implementation AFAICS.

**Comment by dsyme** [comment]
@smoothdeveloper Yes it's fine to remove this

**Comment by smoothdeveloper** [comment]
I've submitted the PR (#2301), there seems to be no gain, but I somehow feel safer than having this helper being used in places it could be a bad choice.

The `prependInstrsToCode` is the place I suspect had the most wastage (identified with my other PR #2296 with non-optimal Array.append²) because we generate a list and pairs for thousands of IL instructions just to populate a dictionary, better to initialize dict at good size and do a for loop in this case.

I wish .net framework had a constructor with `Seq<KVP<K,V>>` (or value tuple?) but this doesn't exist somehow.

**Comment by dsyme** [comment]
@smoothdeveloper I'm closing this as I don't think this particular change needs to be tracked by a bug - if we get perf improvements in a PR then we will accept it
