### ISSUE TITLE
Enabling --times output in Visual Studio

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2299]
#### Repro steps

* Add --times to other flags
* disable warning as errors (or remove the warning)

#### Expected behavior

in the output window, I can see the times output

#### Actual behavior

the output window remains unaffected

#### Known workarounds

None

#### Related information 

* win 10
* master
* .net 4.5
* vs 2015

**Comment by dsyme** [comment]
This isn't particularly expected behavior - we don't guarantee to display extraneous compiler output

**Comment by smoothdeveloper** [comment]
@dsyme, intuition tells me the output panel should print the same things that are sent to console standard output.

What would be the negative aspect of having `--times` (which is added manually and explicitly, never on by default) reported in the output window and also what would need to be changed if this was required?

**Comment by dsyme** [comment]
> What would be the negative aspect of having --times (which is added manually and explicitly, never on by default) reported in the output window 

None, it would be good

> what would need to be changed if this was required?

I'm afraid I don't know.  MSBuild confuses me - I don't understand why this isn't the default

**Comment by smoothdeveloper** [comment]
:smile:  it sounds like you would have written this issue instead of me.

I'm thinking, despite MSBuild confuses you, you might have better access than me to specialists working on it and integration with VS to try to clear that?

I understand `--times` is not for wide consumption by end users, but it is an important tool for someone approaching the compiler trying to get inside of it.

That task for an outsider is daunting on many grounds and smoothing the way is best way to enable more people to contribute, share ideas etc.

**Comment by smoothdeveloper** [comment]
Side question, what would enable to have similar switch in FSI which reports for each evaluation?

I've found that FSI can be leveraged for quickly test things after recompiling the compiler, I can load a project with a bunch of `#load` and it (generally) doesn't come with host of issues about framework assemblies, running commands or IDE with new bits, and it works readily on each platform we have FSI.

**Comment by dsyme** [comment]
> Side question, what would enable to have similar switch in FSI which reports for each evaluation?

Just follow through the implementation, I think it is not too hard and mostly just a matter of enabling the switch in the FSI flag set

**Comment by dsyme** [comment]
Actually it already exists:
```
C:\GitHub\fsharp\FSharp.Compiler.Service>fsi --times


warning FS0075: The command-line option 'times' is for test purposes only

Microsoft (R) F# Interactive version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> TIME:  0.3 Delta:  0.0 Mem:  66 G0:   0 G1:  0 G2:  0 [Optimizations]
TIME:  0.4 Delta:  0.0 Mem:  67 G0:   0 G1:  0 G2:  0 [Ending Optimizations]
TIME:  0.4 Delta:  0.0 Mem:  67 G0:   0 G1:  0 G2:  0 [TAST -> ILX]
TIME:  0.4 Delta:  0.0 Mem:  67 G0:   0 G1:  0 G2:  0 [Linking]
TIME:  0.4 Delta:  0.0 Mem:  68 G0:   0 G1:  0 G2:  0 [ILX -> IL (Unions)]
TIME:  0.4 Delta:  0.0 Mem:  68 G0:   0 G1:  0 G2:  0 [ILX -> IL (Funcs)]
TIME:  0.4 Delta:  0.0 Mem:  69 G0:   0 G1:  0 G2:  0 [Assembly refs Normalised]

TIME:  0.4 Delta:  0.0 Mem:  70 G0:   0 G1:  0 G2:  0 [Reflection.Emit]
- 1+1;;
TIME:  0.5 Delta:  0.2 Mem:  72 G0:   1 G1:  1 G2:  0 [Run Bindings]
TIME:  0.5 Delta:  0.0 Mem:  72 G0:   0 G1:  0 G2:  0 [Optimizations]
TIME:  0.6 Delta:  0.0 Mem:  72 G0:   0 G1:  0 G2:  0 [Ending Optimizations]
TIME:  0.6 Delta:  0.0 Mem:  72 G0:   0 G1:  0 G2:  0 [TAST -> ILX]
TIME:  0.6 Delta:  0.0 Mem:  72 G0:   0 G1:  0 G2:  0 [Linking]
TIME:  0.6 Delta:  0.0 Mem:  72 G0:   0 G1:  0 G2:  0 [ILX -> IL (Unions)]
TIME:  0.6 Delta:  0.0 Mem:  72 G0:   0 G1:  0 G2:  0 [ILX -> IL (Funcs)]
TIME:  0.6 Delta:  0.0 Mem:  72 G0:   0 G1:  0 G2:  0 [Assembly refs Normalised]

TIME:  0.6 Delta:  0.0 Mem:  72 G0:   0 G1:  0 G2:  0 [Reflection.Emit]
val it : int = 2
> 1+1;;
TIME:  0.6 Delta:  0.0 Mem:  73 G0:   0 G1:  0 G2:  0 [Run Bindings]
TIME:  0.6 Delta:  0.0 Mem:  73 G0:   0 G1:  0 G2:  0 [Optimizations]
TIME:  0.6 Delta:  0.0 Mem:  73 G0:   0 G1:  0 G2:  0 [Ending Optimizations]
TIME:  0.6 Delta:  0.0 Mem:  73 G0:   0 G1:  0 G2:  0 [TAST -> ILX]
TIME:  0.6 Delta:  0.0 Mem:  73 G0:   1 G1:  0 G2:  0 [Linking]
TIME:  0.6 Delta:  0.0 Mem:  73 G0:   1 G1:  0 G2:  0 [ILX -> IL (Unions)]
TIME:  0.6 Delta:  0.0 Mem:  73 G0:   0 G1:  0 G2:  0 [ILX -> IL (Funcs)]
TIME:  0.6 Delta:  0.0 Mem:  73 G0:   0 G1:  0 G2:  0 [Assembly refs Normalised]

TIME:  0.6 Delta:  0.0 Mem:  73 G0:   0 G1:  0 G2:  0 [Reflection.Emit]
val it : int = 2
>
```

**Comment by smoothdeveloper** [comment]
Thanks, I'll give it another try!

**Comment by smoothdeveloper** [comment]
`--times` with FSI works very nicely, outputs at each evaluation.

**Comment by dsyme** [comment]
Closing old discussion

**Comment by smoothdeveloper** [comment]
To show it in Visual Studio, setting _Detailed_ in the highlighted drop down:

![image](https://user-images.githubusercontent.com/87944/71701998-49ec7400-2dcd-11ea-8741-dc2ed21b269c.png)

In Rider, check Console and pick Low (maybe a less verbose configuration exists):

![image](https://user-images.githubusercontent.com/87944/72028445-d04bfe80-3282-11ea-969d-456a89233320.png)
