### ISSUE TITLE
Operator token unrecognized when right-hand side is on new line

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2306]
Open this file in Nu: https://github.com/bryanedds/Nu/blob/master/Nu/Nu/World.fs#L39

Try to over over the operator with its right-hand argument on a new line:

![op-not-recognized](https://cloud.githubusercontent.com/assets/6309070/22140410/2dc51d32-dea1-11e6-9b0c-926eb6bd178f.gif)

**Comment by vasily-kirichenko** [comment]
Try to reproduce it on https://github.com/Microsoft/visualfsharp/pull/2298

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2298
