### ISSUE TITLE
suspicious repeated calls to MemberConstraintSolutionOfMethInfo in ConstraintSolver.ResolveOverloading

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2310]
I'm looking at `ConstraintSolver.ResolveOverloading` and it seems in certain condition, we would repeat calls to MemberConstraintSolutionOfMethInfo for each candidate method, it means called twice instead of just once per candidate, this is happening in this match:

https://github.com/Microsoft/visualfsharp/blob/f8103bb6f1ae8858029cf89cbda0e25ccd49666c/src/fsharp/ConstraintSolver.fs#L2161-L2179

In the second part, that expression looks it would be the same as in the first match case:

```fsharp
let cxsln = Option.map (fun traitInfo -> (traitInfo, MemberConstraintSolutionOfMethInfo csenv.SolverState m candidate.Method candidate.CalledTyArgs)) cx
```

Does that look suspicious / potentially hurting performance?

Should we generate cxsln for each candidate and then match on that which will avoid repeating those calls?

**Comment by dsyme** [comment]
I believe ``MemberConstraintSolutionOfMethInfo`` is fast in comparison to everything else that's being done there (and cxsln will often be None)

**Comment by smoothdeveloper** [comment]
@dsyme correct, that call seems to be very cheap (00:00:00.0000004) so it won't save much, preparing those in advance reduced call count from 434 to 287 when compiling Prime project.

There are other calls which would look to be repeated:
* MustUnifyInsideUndo
* TypesMustSubsumeOrConvertInsideUndo

we also issue similar looking code here:

https://github.com/Microsoft/visualfsharp/blob/f8103bb6f1ae8858029cf89cbda0e25ccd49666c/src/fsharp/ConstraintSolver.fs#L2211-L2226

I've noticed we have a mutable member `ExtraCxs` in ConstraintSolverState, although in some calls taking ConstraintSolverState we only access other readonly fields, since this code is difficult to comprehend in terms of side effect, it might be worth to pass only field used to distinguish what is going to alter `ExtraCxs` might help understand impact of reorganizing this code.

**Comment by smoothdeveloper** [comment]
@dsyme do you know if MustUnifyInsideUndo and TypesMustSubsumeOrConvertInsideUndo are worth looking at? thing is they take the trace object as parameter, so it is mutating it, I'm unsure it can be changed easily.

**Comment by dsyme** [comment]
@smoothdeveloper Have you got the outputs of a profiling tool showing what is expensive?

**Comment by smoothdeveloper** [comment]
@dsyme I'm going to setup dottrace, thanks

**Comment by smoothdeveloper** [comment]
![image](https://cloud.githubusercontent.com/assets/87944/22174839/473abe28-dfe8-11e6-8c1d-e80b068e7857.png)

ConstraintSolver barely register when compiling Prime.

**Comment by dsyme** [comment]
@smoothdeveloper Please link the source code and the steps for acquiring traces, so others can get these figures.  Also please indicate if these are inclusive (includes called code) times or exclusive (does not include called code) times

**Comment by dsyme** [comment]
@smoothdeveloper You will also want to profile on a long compilation I think.  I expect the above is dominated by cracking the binaries mscorlib.dll etc.

**Comment by smoothdeveloper** [comment]
@dsyme the trace was inclusive I believe.

I'm not sure how to go about testing long compilating, I'd like to run the profiler while compiling the compiler itself but that seems like a tricky endeavour.

My current process is:
* in VS2015, open a vanilla F# project and use http://fsprojects.github.io/VisualFSharpPowerTools/generatereferences.html
* compile the compiler (build.bat net40)
* in dottrace, run FsiAnyCpu.exe passing the generated "load-project.fsx" as argument

this cuts the headache of getting proper compiler invocation command line, I don't know how I could do that while compiling the compiler (because you can't compile F# with normal compiler, you need proto AFAIU).

I could try that FSharpPlus library but this is not representative of idiomatic F# codebase.

For future traces, I'll point to the revision of the compiler and the code I'm compiling so other can have a look at those.

**Comment by smoothdeveloper** [comment]
>  I expect the above is dominated by cracking the binaries mscorlib.dll etc.

In most F# project in the wild, I expect the F# code to be rather bland, but to have a fair share of dependencies, I'll try to check on projects with significant amount of dependencies but not so much code what time is spent .

I've noticed that F# tend to need dependencies eagerly, e.g. when opening a namespace even if some types that require deps aren't referenced, in some case I've faced, that forced me to add transitive dependencies to the project despite those wouldn't be used in any of the symbol I was actually dealing with; is there a way to optimize that to be more lazy and also not force the dependencies if we don't actually use the types?

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper use FSharp.Compiler.Service as a project to compile.

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko good idea, although I'm getting this from FSI:

> SimulatedMSBuildReferenceResolver.fs(4,1): error FS0076: This directive may only be used in F# script files (extensions .fsx or .fsscript). Either remove the directive, move this code to a script file or delimit the directive with '#if INTERACTIVE'/'#endif'.

I'm going to try to remove those last files from the test compile.
