### ISSUE TITLE
Visual F# installed but no MS Build Tools: error message is too cryptic

### ISSUE THREAD

**Issue by lilred** [Microsoft/visualfsharp#2313]
#### Repro steps

From a clean install of Windows - in particular, without Visual Studio installed:
1. Install Visual F# Tools 4.0
2. Open cmd in the F# folder, run fsi.exe
3. Witness a cryptic error message. ("could not load file or assembly...")
4. ???
5. Eventually figure out that you need to install Microsoft Build Tools 2015.

#### Expected behavior

The error message should suggest installing Microsoft Build Tools 2015.

#### Actual behavior

The error message does not suggest installing Microsoft Build Tools 2015.

#### Known workarounds

Ask a professor, IT person, or friendly F# guru for help.

#### Related information 

This is an issue because we're teaching a class using F#, and glossing over this part of the installation steps is a common failure mode. We get a ton of questions from students that are resolved this way.

**Comment by smoothdeveloper** [comment]
@lilred thanks for the error report, could you post the exact message?

http://fsharp.org/use/windows/ (which is linked from http://ionide.io/) does list msbuild tools 2015 as a requirement (as well as the windows SDK which is not required).

I think for most students under windows, installing the community edition of Visual Studio is a great way to go and it will install all the prerequisistes.

Great choice to pick F# as a language to teach students.

**Comment by lilred** [comment]
I don't have a machine handy with the exact message, I'll update as soon as I do.

>http://fsharp.org/use/windows/ (which is linked from http://ionide.io/) does list msbuild tools 2015 as a requirement (as well as the windows SDK which is not required).

It does! ...unfortunately, the students seem to skip right over it. One solution would be to reword that page, but documentation-crafting is an exquisite art which I do not master.

>I think for most students under windows, installing the community edition of Visual Studio is a great way to go and it will install all the prerequisistes.

We're trying to steer students clear of Visual Studio; students run a variety of OSes, but we'd like to only support one editor, so it's Visual Studio Code for everyone.

**Comment by smoothdeveloper** [comment]
I've faced the issue and I think what needs to be kept track of is that the F# Tools installer should check pre-requisite and point to download pages for those.

After installing F# tools succesfully, there should never be an error for missing anything else when just running FSI and FSC.

**Comment by cartermp** [comment]
I think there are two good things here which can be done:

1. Error message when failing to a load an assembly from MSBuild.  Not sure how easy it is to tell this.
2. Prompting to install MSBuild in the F# Tools installer if it's not found, or bundling the MSBuild tools with the installer.

Unfortunately, this issue is a consequence of sitting atop .NET Framework and not using Visual Studio as the installation vehicle.  Consequentially, this is one of the big motivations of .NET Core.  Although the tooling isn't there yet for .NET Core yet, it really is the future of how you acquire the runtime, compilers, and SDK in a uniform way across any OS.

Improvements could be made in documentation, but as @lilred pointed out, people tend to gloss over instructions unless they're really short and *really* obvious.  We've done studies which show this as well.  The best way forward is a clean, simple install that installs all the dependencies it needs, and helpful error messages (if possible) if that install somehow goes wonky or something gets bypassed.  That said:

> We're trying to steer students clear of Visual Studio; students run a variety of OSes, but we'd like to only support one editor, so it's Visual Studio Code for everyone.

I'm interested in a bit more background here.  How much overhead is it to support more than one editor?  Is this for a more traditional class, or is it a bit more "real world" in the sense that people are building projects with tools they may see in the industry?

**Comment by isaacabraham** [comment]
Can confirm this happened to me with a colleague - installer vscode, visual f# tools but didn't work - needed to find the msbuild tools to work.

**Comment by lilred** [comment]
>I'm interested in a bit more background here. How much overhead is it to support more than one editor?

Just supporting one is a hard enough sell. Plus, VS Community is a more polished, more first-class solution, and if we supported it we could be accused of favoring users of Microsoft products. (I pushed pretty hard for the switch to F#, and I've also interned at Microsoft, so this could look like a conflict of interest.)

>Is this for a more traditional class, or is it a bit more "real world" in the sense that people are building projects with tools they may see in the industry?

Traditional class. "Coding in the small", functional programming, all that good stuff. We just switched last year from Standard ML, which wasn't really conducive to project work. I could see this changing in the future.

_________________________

Returning to the question at hand:

* How would you check to see if an assembly is available in the most generic possible matter?
* Where in the Visual F# installer code would a check for/download of MS Build Tools 2015 go?

**Comment by vasily-kirichenko** [comment]
@lilred I'm afraid there's no installer anymore. Visual F# Tools will be shipped as VSIX (VS extension) installer only.

**Comment by lilred** [comment]
Does this mean that it's going to be impossible to install F# on Windows without installing Visual Studio?

**Comment by forki** [comment]
That is a really good question and I guess we still need an installer. @cartermp can you please comment on that?

**Comment by vasily-kirichenko** [comment]
@7sharp9 asked for installer for MacOS as well.

**Comment by cartermp** [comment]
I agree that we need a standalone installer for F# in the interim.  @KevinRansom can speak more towards how easy bundling up a standalone F# 4.1 installer is.  As for macOS, doesn't F# come with the Mono install?  At least I've never *not* had F# when installing Mono.

**Comment by smoothdeveloper** [comment]
The exact error message is the following
```
C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0>fsi

Microsoft (R) F# Interactive version 14.0.23020.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

>

error FS0193: Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0>fsc

error FS0193: Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

Before installing .NET framework, trying to install displays this message:

![image](https://cloud.githubusercontent.com/assets/87944/22222569/b17de712-e1b7-11e6-8d7b-96fcfb5dcf4c.png)

**Comment by KevinRansom** [comment]
@cartermp  @vasily-kirichenko 

We have an MSI for installing the Visual F# compiler and FSI for the Windows desktop. We will publish it on MSDN when VS is RTW.
- It won't install the VS tools.  It will not be the mechanism for installing msbuild.
The msbuild oob installer is the tool for that.
- It won't install the VS editor experience. 

As for the mac and unix.  The dotnet/cli and the dotnet/cli-fcs is the mechanism for those platforms.

Is that sufficient, or is something else required?

Kevin

**Comment by forki** [comment]
dotnet/cli is not for standard .NET framework/mono, right? So that can't be the only way!?

**Comment by vasily-kirichenko** [comment]
I think linux users would appreciate an apk much more, preferably available via official feeds (or whatever it's called, I mean it should be as simple as `apt-get/yum install fsharp`)

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko I think this is the resort of each distribution to package what they see fit, we can encourage them to package fsharp but can't force anything.

To make it more likely, the repository would need a simple build process such as

```
./configure
make
```
or 
```
automake
make
```

Inspired from what the mono repository has. I think until dotnet core gets packaged, or we have a compile to native and bootstrapped way to build this repository, fsharp will still depend either on mono or dotnet core.

I know freebsd has a standalone fsharp package but it is version 3 of compiler AFAIR.

**Comment by cartermp** [comment]
@vasily-kirichenko I can't speak for Mono, but the .NET CLI is packaged up in the "native" way for each linux distro.

**Comment by autisticvegan** [comment]
@KevinRansom 
Now that VS has been released, where can we find the F# Compiler / FSI stand-alone?

**Comment by cartermp** [comment]
@autisticvegan We're working on getting it into the Microsoft Download Center.  Should be available soon.

**Comment by dsyme** [comment]
@autisticvegan @cartermp You can also use the FSharp.Compiler.Tools nuget package, which bundles a Mono-ready version of the F# 4.1 compiler and F# Interactive.  It's not an official Microsoft thing.

**Comment by harrisonmeister** [comment]
Is there any update as to the timelines on getting the F# 4.1 compiler / stand-alone tools into the MS download center?

**Comment by vasily-kirichenko** [comment]
@harrisonmeister what about using https://www.nuget.org/packages/FSharp.Compiler.Tools/?

**Comment by harrisonmeister** [comment]
@vasily-kirichenko  - would this require me to change any fsproj files to locate the targets files correctly? I've tested with msbuild 15 and this was (one of) the issues. I'm happy to make the fsproj changes if needed!

**Comment by cartermp** [comment]
Ack, sorry!  It's been difficult to get it into the download center and I admit that I forgot about it last week.  I've made a note to myself to talk to the right people next week to get it in there.

(I'm not in Redmond this week, hence needing to do it next week)

**Comment by harrisonmeister** [comment]
@cartermp - no problems whatsoever, we are running msbuild 14 for now, so no mega rush, was just curious :)

**Comment by dsyme** [comment]
FSharp.Compiler.Tools is available, seems like a good resolution here

**Comment by lilred** [comment]
What's the recommended approach to install FSharp.Compiler.Tools without Visual Studio?

**Comment by harrisonmeister** [comment]
Will the compiler tools be able to be installed without visual studio on a build server?

**Comment by JarnoNijboer** [comment]
FSharp.Compiler.Tools is available as a package on Nuget. When you install this package into your project, the compiler from the nuget package will be used instead of the one that is installed on e.g. your buildserver.

**Comment by dsyme** [comment]
@JarnoNijboer is correct.  You need to adjust your reference to Microsoft.FSharp.targets in your project files to point to the Microsoft.FSHarp.targets in the nuget package.  If using the compiler a lot you may also want to run ``ngen install ...\fsc.exe``

**Comment by lilred** [comment]
If I just want to install the compiler without creating a project, is there a way?

**Comment by dsyme** [comment]
@lilred Getting the FSharp.Compiler.Tools nuget package is the easiest way. Then run tools\fsc.exe
