### ISSUE TITLE
Constraint solver bug when the inlined caller function for the static method is inside it

### ISSUE THREAD

**Issue by mrakgr** [Microsoft/visualfsharp#2314]
The offending code fragment can be seen at the top of this [SO question](http://stackoverflow.com/questions/41807147/how-to-resolve-the-strange-type-error-in-a-recursive-map-with-statically-resolve). According to Gustavo, it should work and it certainly seems that way, but the constraint solver gets confused. It can be worked around by pulling the inline function out of the static method, which I had not known at the time because I thought it would not work on extension methods.

**Comment by mrakgr** [comment]
Here is a minimal repro:
```
type CudaScalar<'t> = CudaScalar of name: string with
    member t.Name = t |> fun (CudaScalar name) -> name

type ArgsPrinter = ArgsPrinter with
    static member inline PrintArg(_: ArgsPrinter, t: CudaScalar<float32>) = sprintf "float %s" t.Name

    static member inline PrintArg(_: ArgsPrinter, (x1, x2)) = 
        let inline print_arg x = 
            let inline call (tok : ^T) = ((^T or ^in_) : (static member PrintArg: ArgsPrinter * ^in_ -> string) tok, x)
            call ArgsPrinter
        [|print_arg x1;print_arg x2|] |> String.concat ", "

    static member inline PrintArg(_: ArgsPrinter, (x1, x2, x3)) = 
        let inline print_arg x = 
            let inline call (tok : ^T) = ((^T or ^in_) : (static member PrintArg: ArgsPrinter * ^in_ -> string) tok, x)
            call ArgsPrinter
        [|print_arg x1;print_arg x2;print_arg x3|] |> String.concat ", "
```

Here is working version:
```
type CudaScalar<'t> = CudaScalar of name: string with
    member t.Name = t |> fun (CudaScalar name) -> name

type ArgsPrinter = ArgsPrinter

let inline print_arg x = 
    let inline call (tok : ^T) = ((^T or ^in_) : (static member PrintArg: ArgsPrinter * ^in_ -> string) tok, x)
    call ArgsPrinter

type ArgsPrinter with
    static member inline PrintArg(_: ArgsPrinter, t: CudaScalar<float32>) = sprintf "float %s" t.Name
    static member inline PrintArg(_: ArgsPrinter, (x1, x2)) = 
        [|print_arg x1;print_arg x2|] |> String.concat ", "
    static member inline PrintArg(_: ArgsPrinter, (x1, x2, x3)) = 
        [|print_arg x1;print_arg x2;print_arg x3|] |> String.concat ", "
```
An even more minimal repro is possible, but then the code does not make sense:
```
type ArgsPrinter = ArgsPrinter with
    static member inline PrintArg(_: ArgsPrinter, (x1, x2)) = 
        let inline print_arg x = 
            let inline call (tok : ^T) = ((^T or ^in_) : (static member PrintArg: ArgsPrinter * ^in_ -> string) tok, x)
            call ArgsPrinter
        [|print_arg x1;print_arg x2|] |> String.concat ", "
    static member inline PrintArg(_: ArgsPrinter, (x1, x2, x3)) = 
        let inline print_arg x = 
            let inline call (tok : ^T) = ((^T or ^in_) : (static member PrintArg: ArgsPrinter * ^in_ -> string) tok, x)
            call ArgsPrinter
        [|print_arg x1;print_arg x2;print_arg x3|] |> String.concat ", "
```

**Comment by mrakgr** [comment]
Related to this issue is my [second question](http://stackoverflow.com/questions/41813454/how-to-resolve-the-strange-type-error-in-a-recursive-map-with-statically-resolve) on SO. In there Gustavo managed to make it work by reordering some statements that should not make a difference, but after that in my edit, I added some fields and the thing broke again with the same error as in the first post.

I do not think F# can imitate the finally tagless style at present, not until these compiler bugs are fixed.

**Comment by dsyme** [comment]
I think this is by design.  It is the case that more generalization can happen for top-level functions than if those functions are defined in expressions - F# tries hard to avoid that but there are definitely cases where it can happen.  I believe this is one such case.

**Comment by mrakgr** [comment]
I expected this would be a bug rather than by design, but it did feel like I am abusing the function inlining mechanism to do things it was not made for. This adventure of trying to plug a Cuda DSL into F# in the end forced me to go out and study type theory so I can do it for the ground up rather than force the language to fit into the mold. That will take a while.

That having said, having advanced polymorphism type features would have been really helpful for this particular use case and you have my vote for adding them into the language.
