### ISSUE TITLE
Unhandled exception RC2 when clicking on F# Interactive window

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2318]
> System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component. at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo) at Microsoft.VisualStudio.Package.Colorizer.GetLineInfo(IVsTextLines buffer, Int32 line, IVsTextColorState colorState) at Microsoft.VisualStudio.Package.Source.GetWordExtent(Int32 line, Int32 idx, WORDEXTFLAGS flags, Int32& startIdx, Int32& endIdx) at Microsoft.VisualStudio.Package.ViewFilter.GetWordExtent(Int32 line, Int32 index, UInt32 flags, TextSpan[] span) at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.GetWordExtent(Int32 iLine, Int32 iCol, UInt32 dwFlags, TextSpan[] pSpan) at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.TryGetQuickInfoFromDebugger(IQuickInfoSession session, TextSpan[] dataBufferTextSpan, String& tipText) at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan& applicableToSpan) at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate() at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start() at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e) at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()

**Comment by cartermp** [comment]
I'll see if I can repro this on my build at home.

**Comment by majocha** [comment]
It happens on hover.
Repro steps in my case:

Open fresh Visual Studio instance, open F# interactive, hover mouse over any text in the interactive for a moment.

**Comment by smoothdeveloper** [comment]
![vs2017fsi](https://cloud.githubusercontent.com/assets/87944/22310395/f500f4aa-e303-11e6-9781-7d49413dd828.gif)

**Comment by KevinRansom** [comment]
@vasily-kirichenko 

I just tested this on a build from a recent RTM branch ...  and it works fine for me.

Is this using the addon VSIX or just out of the box rc2?

**Comment by smoothdeveloper** [comment]
When I remove the last vsix (that I built from master), then it works.

Is it a signing thing? Should that stuff be hardened to not crash Visual Studio?

**Comment by majocha** [comment]
@smoothdeveloper I think your crash is another issue. The exception @vasily-kirichenko got doesn't kill Visual Studio.
@KevinRansom it occurs with VisualFSharpOpenSource.vsix built from master installed on RC2, exception is being logged 
with source _Editor or Editor Extension_

**Comment by KevinRansom** [comment]
@majocha 
Thanks for the heads up.  I almost had a heart attack when I saw this, I thought it was in the product.

**Comment by majocha** [comment]
The same bug exists in RC3 (with RC3 vsix installed acc. to the instructions).

**Comment by vasily-kirichenko** [comment]
An uncaught exception is thrown on RC4 + current master OS vsix:

> System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.&#x000D;&#x000A;   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   at Microsoft.VisualStudio.Package.Colorizer.GetLineInfo(IVsTextLines buffer, Int32 line, IVsTextColorState colorState)&#x000D;&#x000A;   at Microsoft.VisualStudio.Package.Source.GetWordExtent(Int32 line, Int32 idx, WORDEXTFLAGS flags, Int32&amp; startIdx, Int32&amp; endIdx)&#x000D;&#x000A;   at Microsoft.VisualStudio.Package.ViewFilter.GetWordExtent(Int32 line, Int32 index, UInt32 flags, TextSpan[] span)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.GetWordExtent(Int32 iLine, Int32 iCol, UInt32 dwFlags, TextSpan[] pSpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.TryGetQuickInfoFromDebugger(IQuickInfoSession session, TextSpan[] dataBufferTextSpan, String&amp; tipText)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan&amp; applicableToSpan)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2423
