### ISSUE TITLE
F1 does not work on master

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2319]
1. F1 on `Async.StartChild`
2. It goes to `https://msdn.microsoft.com/ru-ru/library/dd831853(v=vs.140).aspx?appId=Dev15IDEF1&l=EN-US&k=k(Microsoft.FSharp.Control.FSharpAsync.StartChild)%3bk(SolutionItemsProject)%3bk(DevLang-FSharp)&rd=true`, which shows:

![image](https://cloud.githubusercontent.com/assets/873919/22306978/5d46b70e-e352-11e6-8586-88393b709da1.png)

**Comment by cartermp** [comment]
Sounds like the language service grabs the correct token, but the redirect on MSDN which handles it seems to fail.  I'll see if I can chat with someone who owns this area.

**Comment by dsyme** [comment]
@cartermp Ping - any update on this?

**Comment by cartermp** [comment]
Sent email just now.

**Comment by cartermp** [comment]
Okay, so it seems like a bit of a strange issue:

1. Some articles do not have the metadata defined  to be recognized by the service.  That can be fixed, though it may take a while before everything works properly.  We're also migrating the F# Reference material, so we may just wait until it's on the new system before we go changing stuff.

2. It *does* work for [articles without metadata](https://github.com/dotnet/docs/blob/master/docs/fsharp/language-reference/keyword-reference.md), depending on the article.  See below:

![f1-works](https://cloud.githubusercontent.com/assets/6309070/23922941/c1794a0e-08c1-11e7-9be8-078a818a9642.gif)

**Comment by vasily-kirichenko** [comment]
It works ok on master.
