### ISSUE TITLE
FCS caches does not work when a file opens

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2324]
1. Open FCS solution
2. Open `service.fs`
3. Wait until colorization appears
4. Close the file
5. Reopen it
6. It takes equally long time for colorization and even structure to appear

The same behavior is observed when another file, even small one, is opened after the first one is fully checked. Looks like https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/service.fs#L2413 checks all files laying prior to the current every time (however, I've not looked at it closely yet).

**Comment by dsyme** [comment]
>  Looks like https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/service.fs#L2413 checks all files laying prior to the current every time (however, I've not looked at it closely yet).

This fetches the results cached by the IncrementalBuilder (i.e. the background build process).  I believe we have quite a lot of tests checking that re-checking doesn't happen (counting the number of checks).

That's not to say there isn't some kind of bug.  For the repro steps above I would expect considerably less time on second opening, as long as the project itself has not been closed.

**Comment by vasily-kirichenko** [comment]
I've investigated it. Create a hello world app, open a file, wait for coloring, close it, reopen. 
It turns out, this https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/service.fs#L2530 returns `None`, digging into it shows this path: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/IncrementalBuild.fs#L1704 => https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/IncrementalBuild.fs#L840 => https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/IncrementalBuild.fs#L413

I know nothing about this vectors stuff. @dsyme any ideas what's going wrong?

**Comment by vasily-kirichenko** [comment]
It looks like `GetCheckResultsBeforeFileInProject` does not return cached background check result _for any just opened file_. It means that everything up to a opening file is rechecked (in one fat Reactor op, but it's a different issue). 

I think it's a huge bug.

**Comment by vasily-kirichenko** [comment]
Fixed. 
1. `LanguageService.SetupProjectFile` is called every time a file is opening https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Common/LanguageService.fs#L298
2. It unconditionally called `UpdateProjectInfo` https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Common/LanguageService.fs#L307
3. The latter, in turn, called `Checker.InvalidateConfiguration` https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Common/LanguageService.fs#L117
4. It recreated `IncrementalBuilder` https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/service.fs#L2716 and replaced the old one.

I'm surprised anything worked at all :(

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2395

**Comment by cartermp** [comment]
Moving to VS Updates now 😄
