### ISSUE TITLE
Breakpoint Resolution falls back to enclosing scope in nested expressions when clicking in margin

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2325]
This is with RC3 + the VSIX installed.

1. Clone https://github.com/bryanedds/Nu
2. Build it
3. Open `AssetGraph.fs` and go to line 139 under the `buildAssets5` function.
4. Set a breakpoint there by clicking in the margin.

**Expected:** Breakpoint set at line 139, `let inputFileSubpath = asset.FilePath`.

**Actual:** Breakpoint is set at the top of the `for..do` loop.

![bp-set-loop](https://cloud.githubusercontent.com/assets/6309070/22361205/6098038a-e40c-11e6-8d25-c5eb57436644.gif)

Note that it also fails inside any block inside the `match` expressions inside of a lambda in `loadAssetsFromPackageDescriptor4`.

**Comment by cartermp** [comment]
Note: I don't think this is a regression.  In fact, in the current bits breakpoint resolution is improved in many cases.

**Comment by forki** [comment]
fixed with #2815

**Comment by saul** [comment]
@cartermp @KevinRansom this can be closed now :_
