### ISSUE TITLE
[RC3] "go to type / symbol / etc" does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2326]
1. `Ctrl+1, T` - nothing.
2. Execute "go to type" menu - nothing.
3. Same on C# files.

![1](https://cloud.githubusercontent.com/assets/873919/22361730/9a795282-e46d-11e6-868b-489c5c476aa5.gif)

**Comment by cartermp** [comment]
@vasily-kirichenko What settings do you have for vs2015 and vs 2017?  I finally got vs2015 Update 3 + vs2017 RC3 (with VSIX) installed and can't repro this problem.

**Comment by vasily-kirichenko** [comment]
You must be logged in with same account in both VSs and synchronization must be turned on (it is by default).

**Comment by cartermp** [comment]
@vasily-kirichenko Do you think we should close this for now since you don't seem to see it?

**Comment by vasily-kirichenko** [comment]
Yes, I don't reproduce it anymore.

**Comment by cartermp** [comment]
Good to know.  Hopefully it doesn't come back again...
