### ISSUE TITLE
[RC3] Inline Rename crashes with MissingMethodException

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2328]
This is what happens if Inline Rename is enabled:

![image](https://cloud.githubusercontent.com/assets/873919/22380890/467cf2d4-e4d0-11e6-9274-76a5a56b0295.png)

@Pilchie any ideas? I updated Roslyn packages to the latest available 2.0.0-rc4-61327-05. VS loads slightly older ones:

![image](https://cloud.githubusercontent.com/assets/873919/22380996/bc6b3d20-e4d0-11e6-9ade-3d6324a8bdc9.png)

**Comment by vasily-kirichenko** [comment]
OK, I tried all 2.0.0-rc4-61324-XX packages available on https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis and no one contained exactly same binaries as RC3 loads from `c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\ManagedLanguages\VBCSharp\LanguageServices\` (I've compared SHA-1 hashes).

**Comment by vasily-kirichenko** [comment]
Updating System.Immutable.Collections package to 1.3.1, which is loaded by RC3 has not helped either.

**Comment by vasily-kirichenko** [comment]
I'm out of ideas.

**Comment by cartermp** [comment]
@KevinRansom didn't you say that this was caused by an issue with a System.Collections.Immutable version number?

**Comment by KevinRansom** [comment]
Yes ... it looks that way.  We need to ensure that we are using the exact same version as the RTM bits.  I seem to recall that Roslyn may have rolled back a change for RC3 ... and we probably didn't.  We will have to drill in to see if this issue repro's on RTM.  if it does we will need to figure out what to do.

**Comment by cartermp** [comment]
cc @jasonmalinowski for FYI

**Comment by jasonmalinowski** [comment]
This is a breaking change that Roslyn did in roslyn/commit@806a804bd18c19f39b98871be07241398f6ab7d0. We rolled it back because it broke TypeScript. Upgrading to newer packages and updating code accordingly should be sufficient to unblock this.

**Comment by jasonmalinowski** [comment]
And yes, the exception is confusing: "missing method" in this case means it can't find the property getter that is matching by return type, since the return type got changed.

**Comment by vasily-kirichenko** [comment]
As I already wrote, updating System.Immutable.Collections had not helped. Anyone, try it again, maybe I'm doing something wrong.

**Comment by cartermp** [comment]
@vasily-kirichenko It may require us generating a build with internal bits to get Roslyn references "right".  @KevinRansom is looking into doing this over the weekend to see if we can get something working by next week.  If we can get a successful build _with no regressions from RC3 + VSIX_, then we'll try to make a case to get this in for RTM...such a change would be subject to review in our shiproom.

**Comment by vasily-kirichenko** [comment]
@cartermp Interesting thing's just happened: I was on my `fix-quick-info` branch and Inline Rename worked OK on RC3 (Ctrl+F5). However, on `vs2017-rtm` branch it's crashed.

**Comment by vasily-kirichenko** [comment]
The difference is this:

![image](https://cloud.githubusercontent.com/assets/873919/22395157/86fbe5d8-e546-11e6-87a3-4506a956f251.png)

**Comment by vasily-kirichenko** [comment]
And of course these

![image](https://cloud.githubusercontent.com/assets/873919/22395160/a1d040fc-e546-11e6-9db1-cd1882e03700.png)

**Comment by vasily-kirichenko** [comment]
I'm just very surprised that it works with rc2 Roslyn packages, but does not with the latest rc3.

**Comment by KevinRansom** [comment]
It was explained to me like this ...

* In November Roslyn made an API breaking change.
* F# built against the updated (with breaking change) APIs
* In January the breaking change was rolled back in the RC3 branch.
* We didn't discover that because of the same reason we had to ship the update MSI and VSIX
 separately.

Over the weekend I will update the references to the correct set, re-enable the feature, and hopefully get the change approved for RTM ... however there really is no guarantee of that.

I hope this helps with understanding what has happened.

**Comment by vasily-kirichenko** [comment]
> It may require us generating a build with internal bits to get Roslyn references "right".

Maybe create a sub repository containing proper roslyn binaries, that you at msft could grab directly, no nuget involved, as I suspect do TS and Python teams? I doubt anybody would against it, because the binaries are already published via that myget feed (the problem is that there are no exactly same versions as VS uses).

**Comment by KevinRansom** [comment]
Everything we need should be published on myget.  Roslyn has daily builds pushed to myget.  Anyway -I'm not too worried that we can get it sorted now we know what the issue is.

**Comment by cartermp** [comment]
Because changing Roslyn references to the correct version breaks Find All References, this is going to go into a microupdate for VS 2017.  We're too deep into the RTM stabilization period to get the changes needed to un-break Inline Rename, address the issue in Find All References, and test again for ensuring there are no regressions.

**Comment by vasily-kirichenko** [comment]
Fixed in master.
