### ISSUE TITLE
[RC3] Code Fixes do not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2329]
I attached to a VS instance and don't see any exceptions, like missing methods, etc. Absolutely no idea what's happening. Code Fixes work OK in C# editor.

**Comment by cartermp** [comment]
Yup, I think the bit that ultimately connects to the "initiate a code fix suggestion" is disabled somehow...you can see the Simplifier Analyzer actually working by dimming/graying tokens which can be simplified.

**Comment by vasily-kirichenko** [comment]
Maybe update VS packages? There's 15.0.26105-RC3 version.

**Comment by saul** [comment]
I can't find it for the life of me, but there was a PR on the Roslyn project that disabled Code Fixes for F# - I brought this up at the time it was merged but it looks like it was completely ignored.

I believe the PR disabled "Go to implementation" if there wasn't an implementation of it in the language service. I'll keep trying to find the PR...

**Comment by saul** [comment]
See dotnet/roslyn#15961

We need to add the FSharp content type to src/EditorFeatures/Core/Implementation/Suggestions/SuggestedActionsSourceProvider.cs in Roslyn

**Comment by cartermp** [comment]
Thanks, @saul!  Looks like that change it getting taken to our shiproom, so if it's approved then I'll change the milestone here and close this out.

**Comment by saul** [comment]
@cartermp it's been approved and merged 👍
