### ISSUE TITLE
VFPT-like enhanced syntax highlighting

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2334]
The Visual F# Power Tools used to feature enhanced syntax highlighting, that highlighted syntax such as functions, mutable variables/ref cells, modules, etc. I find this really useful and it makes F# looks like a first class language in VS.

I'm not sure whether there's an issue already to track porting VFPT features over from the extension to this repository, but it's a shame that we're losing some features in VS 2017 for F# as VFPT won't be supported.

**Comment by cartermp** [comment]
I thought @vasily-kirichenko had VFPT building on vs2017?  I'd certainly support the extended syntax highlighting, although I'm also of a mind that it's the sort of thing that's perfect for a power tools-like extension; offering even more great functionality on top of a good base of in-box features.

**Comment by saul** [comment]
I'm sure it does work on 2017 but I thought the features of VPFT were being migrated to the official extension? Also I don't following the logic as to why extended syntax highlighting shouldn't be in the main extension - it has a minuscule performance cost and is really useful for users.

F#'s out-of-the-box syntax highlighting is barely better than a basic grammar that can be written up in a few lines (keywords, strings, comments).

**Comment by smoothdeveloper** [comment]
Syntax higlighting in VS2017 is way better than it was in vanilla VS2015, but I do miss the mutable bindings being in a different colors and probably few other things.

It would be great to bring at least the mutable colorization IMHO.

The problem with having a next version of VFPT is also that it incurs having two times the FCS codebase instanciated, which means twice the objects in cache (AFAIU), it also seems that from development perspective, although VF# solution is bulkier, it helps to have FCS codebase at hand for easy stepping etc. @vasily-kirichenko was saying to me it is preferable to contribute features to this repository.

**Comment by cartermp** [comment]
Ah, yes that would be untenable.  I think it's a good feature, just not something that I would prioritize over getting "IDE feature parity" with C#/VB and proper settings in place to toggle and customize features.  I'd happily accept the PR, though.

**Comment by KevinRansom** [comment]
@smoothdeveloper 
We would welcome a PR to add that feature, and any others that improved the experience of F# developers using the Visual F# tools.

Kevin

**Comment by smoothdeveloper** [comment]
Yes a PR is good to fix what is missing.

On the question of enabling 3rd part VS extensions, I don't know what are the road blocks to avoid adding dependency on FCS in 3rd part VS extension, but I'm guessing removing `internal` in few places in the language service bits and shipping a nuget package for it would be the way to go; can we have some feedback from people who know better on that matter?

**Comment by KevinRansom** [comment]
We made a good deal of internal Compiler Service stuff public at the beginning of this release.  If there are still API's that are internal that need to be made public then make a PR or a proposal to change them to public and we can have a discussion.

**Comment by vasily-kirichenko** [comment]
I don't think I'd like to resurrect VFPT. I just don't see the point. About two FCS instances, it'd not be the case because FSharpChecker is already exposed as MEF service and we would very easily use it in VFPT, but again, I don't think it's a good idea to have VFPT at all.

**Comment by saul** [comment]
@vasily-kirichenko has started this work in #2341

**Comment by smoothdeveloper** [comment]
@KevinRansom thanks

> If there are still API's that are internal that need to be made public then make a PR or a proposal to change them to public and we can have a discussion.

Right now I'm porting some VFPT code which uses FCS, it wants to expose `range` which is defined as internal in this repository, this forces me to start defining more things as internal or to redesign the code.

I think whatever is public in FCS currently should be made public in FSharp.Compiler assembly (or only in FSharp.Compiler.LanguageService if we want to add #if but what is the point?). As there is nobody right now which going to depend on FSharp.Compiler or FSharp.Compiler.LanguageService, I'd be for aligning with FCS codebase if that makes sense.

@dsyme do you have opinion on how to handle those cases?

**Comment by cartermp** [comment]
Tagging #2348 for tracking purposes.  @saul do you feel that this issue has been thoroughly addressed?

**Comment by saul** [comment]
Yes @cartermp - I'm under the impression that the VFPT code was ported over directly.

I believe there's still an outstanding issue that @vasily-kirichenko commented on the PR:
"About the commented code in service.fs, it's an attempt to determine if vref is of type Ref`1. I asked @dsyme for help, but he's not answered."

**Comment by dsyme** [comment]
@saul Do you have a link for the specific piece of code? thanks

**Comment by dsyme** [comment]
I'll close this since the main work has been done

@vasily-kirichenko To tell if something is a ref cell, use this:

    val isRefCellTy   : TcGlobals -> TType -> bool

**Comment by vasily-kirichenko** [comment]
It's implemented long time ago.
