### ISSUE TITLE
Keyboard shortcut for Quick Launch doesn't work in RTW

### ISSUE THREAD

**Issue by majocha** [Microsoft/visualfsharp#2335]
Keyboard shortcut for Quick Launch (by default ctrl-Q) doesn't work when F# editor window has focus.
It works OK in other windows like FSI or C# editor.
Changing the shortcut to something else in settings doesn't help.

#### Repro steps

Open .fs or .fsx file

Press Ctrl-Q

#### Expected behavior

Quick Launch has focus

#### Actual behavior

Nothing happens

#### Known workarounds

Click the Quick Launch box.

#### Related information 

Visual Studio 2017 Enterprise RC3 with released F# vsix installed according to instructions.

**Comment by saul** [comment]
@Pilchie do you have any idea what may be causing this?

**Comment by Pilchie** [comment]
I'm not sure - it looks like F#'s `IOleCommandTarget` is returning that the command isn't supported for F# somewhere, but I'm not sure where.

**Comment by majocha** [comment]
Closing as it's fixed.
