### ISSUE TITLE
Add file system completion for #r and #load directives in scripts

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2343]
We could just port http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.InteractiveEditorFeatures/Completion/FileSystem/LoadDirectiveCompletionProvider.cs and http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.InteractiveEditorFeatures/Completion/FileSystem/ReferenceDirectiveCompletionProvider.cs

**Comment by vasily-kirichenko** [comment]
It's turned out we need Roslyn's `Microsoft.CodeAnalysis.Scripting` assembly to add `FSharp.Editor` to it's internals visible to list, see https://github.com/dotnet/roslyn/issues/16823

**Comment by smoothdeveloper** [comment]
Haven't looked in details but there are minor adjustments we would need to make in their code:

```csharp
private static readonly Regex s_directiveRegex = new Regex(@"#load\s+(""[^""]*""?)", RegexOptions.Compiled);
```

in F#, it support the @ verbatim string so that regex needs to be updated to account for that.

It is a great idea to bring that feature to .fsx :+1:
