### ISSUE TITLE
Discussion: Memory usage by language service related to assembly references

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2345]
I made some comments on that issue pertaining to memory usage of language service:

https://github.com/Microsoft/visualfsharp/pull/2312#issuecomment-274806501

I was pointed to https://fsharp.github.io/2015/09/29/fsharp-compiler-guide.html#compiler-memory-usage by @vasily-kirichenko.

I'm adding this more detailled report:

![image](https://cloud.githubusercontent.com/assets/87944/22436258/ac6ad638-e723-11e6-96bf-4a480c6de893.png)

The total memory used there for assembly references (about 140mb) roughly matches the size of assemblies on disk, those assemblies do contain a large section of resource embedded (like bitmap, etc.).

I wonder if we have a chance to optimize that usage, C#/VB projects don't take as much memory and in the case of the solution I was using while taking memory dump, they even have more assembly references in the projects.

Are there quick gains that could be made? those would benefit usage of F# in projects using assembly references.

Is there a way down the road to have the memory shared with C#/VB projects which also need to load up assembly references to get relevant meta data?

**Comment by dsyme** [comment]
Closing as we've done a fair bit of memory work.  More may be needed but we should identify specific scenarios and do new logging
