### ISSUE TITLE
Publish Signed OOB VSIX on regular cadence on GitHub

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2355]
@brettfo has done a lot of internal work to get our builds in order so that we can produce a signed VSIX for vs2017 quite easily.  I propose a regular cadence (~1 week or so) to publish a signed VSIX of the latest master which builds successfully, so that folks can get the latest and greatest tooling.

What this does mean is that the VSIX may not be nearly as well-tested, and from time-to-time may introduce a breaking change or regression.  The assumption is that if you decide to install this VSIX, you're opting into that less-tested path.  Problems in that area will be addressed of course, but in general, the most stable tools will be the ones that ship directly with VS.

I'm happy to put myself on the hook for uploading such a VSIX, making sure installation instructions are correct, and being the person you can yell at if something breaks because you installed it.

**Comment by vasily-kirichenko** [comment]
This is just great.

**Comment by Pilchie** [comment]
Alternatively to posting directly on github, we could upload to myget (similar to the Roslyn vsixes at https://dotnet.myget.org/gallery/roslyn

**Comment by cartermp** [comment]
@Pilchie I think that's an even better idea.  @brettfo any estimate on how much work would be needed to upload signed builds to MyGet?

**Comment by brettfo** [comment]
I have no idea, but @jmarolf might; I seem to remember him doing something with regular updates for the Roslyn VSIXs.

**Comment by cartermp** [comment]
As an update, we got the info about how to get our builds out into a MyGet feed.  We're doing this.

**Comment by cartermp** [comment]
CLOSIN'

https://blogs.msdn.microsoft.com/dotnet/2017/03/14/announcing-nightly-releases-for-the-visual-f-tools/
