### ISSUE TITLE
Cannot `build vs` from master

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2361]
`build.cmd vs`

> "E:\github\visualfsharp\build-everything.proj" (default target) (1) ->
"E:\github\visualfsharp\vsintegration\fsharp-vsintegration-vsix-build.proj" (Build target) (34) ->
"E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj" (Build target) (36) ->
(GetVsixDeploymentPath target) ->
  E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error MSB4018: The "Get ExtensionsPath" task failed unexpectedly.\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error MSB4018: System.IO. FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Settings.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken =b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFS harpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error MSB4018: File name:  'Microsoft.VisualStudio.Settings.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'\r [E:\github\visualfsharp\vsintegra tion\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error MSB4018:    at Micr osoft.VsSDK.Build.Tasks.GetExtensionsPath.Execute()\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource. csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error MSB4018:    at Micr osoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r [E:\github\visualfsharp\vsintegration\Vsix\VisualF SharpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error MSB4018:    at Micr osoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\V isualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error MSB4018: \r [E:\git hub\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error MSB4018: WRN: Assem bly binding logging is turned OFF.\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error MSB4018: To enable
assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.\r [E:\github\visualfsharp\vsinte gration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error MSB4018: Note: Ther e is some performance penalty associated with assembly bind failure logging.\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSourc e\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error MSB4018: To turn th is feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharp OpenSource\VisualFSharpOpenSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error MSB4018:  [E:\githu b\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]

**Comment by majocha** [comment]
I can't reproduce it on a fresh clone.

**Comment by vasily-kirichenko** [comment]
The failing msbuild task is from `Microsoft.VsSDK.Build.Tasks` assembly, which depends on `Microsoft.VisualStudio.Settings.15`:

![image](https://cloud.githubusercontent.com/assets/873919/22585810/b6226602-ea0a-11e6-8c27-690afd178dfa.png)

and the latter is not in GAC on my machine.

**Comment by vasily-kirichenko** [comment]
Copied `c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VSSDK\VisualStudioIntegration\Common\Assemblies\v4.0\` to `e:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\`. New error:
```
"E:\github\visualfsharp\build-everything.proj" (default target) (1) ->
"E:\github\visualfsharp\vsintegration\fsharp-vsintegration-vsix-build.proj" (Build target) (34) ->
"E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj" (Build target) (36) ->
(GetVsixDeploymentPath target) ->
  E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error VSSDK1077: Unabl e to locate the extensions directory. "Value cannot be null.\r [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpO penSource.csproj]
E:\github\visualfsharp\packages\Microsoft.VSSDK.BuildTools.15.0.26124-RC3\tools\vssdk\Microsoft.VsSDK.targets(621,5): error VSSDK1077: Paramet er name: path1". [E:\github\visualfsharp\vsintegration\Vsix\VisualFSharpOpenSource\VisualFSharpOpenSource.csproj]

    4 Warning(s)
    1 Error(s)
```

**Comment by majocha** [comment]
Microsoft.VsSDK.Build.Tasks that ends up in packages folder on my machine is version 15.0.26124.5 modified 25.01.2017 17:56, if it's of any help.

**Comment by vasily-kirichenko** [comment]
Same. It goes from here https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/packages.config#L19

**Comment by vasily-kirichenko** [comment]
Just removed and reinstalled VS, clean working dir - same error.

**Comment by vasily-kirichenko** [comment]
But this is not a huge problem. Huge problem is this one: https://github.com/dotnet/roslyn/issues/16900

**Comment by majocha** [comment]
@vasily-kirichenko I know it's a desperate measure, but have you tried deleting/renaming the whole AppData\Local\Microsoft\VisualStudio directory?

**Comment by vasily-kirichenko** [comment]
@majocha same :(

**Comment by vasily-kirichenko** [comment]
A workaround: reinstall / reset windows, then install RC3.
