### ISSUE TITLE
F# does not seem to work with Visual Studio 2017 RC3 26127.3

### ISSUE THREAD

**Issue by chaotic-butter** [Microsoft/visualfsharp#2362]
#### Repro steps

Uncertain. Perhaps the installation of RC3 26127.3. The original installation of RC3 worked with the steps provided.

#### Expected behavior

Support for F# projects in Visual Studio 2017 RC3 26127.3
 
#### Actual behavior

F# projects will not load and going to Tools -> Options -> F# Tools has the following: _An error occurred loading this property page_

#### Related information 

_Attempted Fixes_: Repair option in installer, refollow instructions from step 3 on. Uninstall/reinstall refollow instructions. All failed.

_Activity.xml error_:

>LegacySitePackage failed for package [FSharpProjectPackage]Source: 'FSharp.ProjectSystem.FSharp' Description: Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

>System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.LanguageServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
> File name: 'Microsoft.VisualStudio.LanguageServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' at Microsoft.VisualStudio.FSharp.ProjectSystem.FSharpProjectPackage.Initialize() at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)

* Windows 10
* Visual Studio 2017 RC3 Release
* .NET 4.6

**Comment by cartermp** [comment]
Interesting.  I'm running 26127.3 on my machine and having no problems.  I know you said that you followed the installation instructions, but did you perhaps not install a .NET workload (.NET Desktop, ASP.NET)?  `Microsoft.VisualStudio.LanguageServices` failing to load sounds like a different issue which is then affecting F#.  cc @brettfo

**Comment by KevinRansom** [comment]
@chaotic-butter 
@cartermp 

Okay, I just reproed this on a clean VM.

As Phillip suggests this happens when VS is installed without first selecting the .Net Desktop Development workload.  It should be noted that the instructions for this are quite specific, because installing the VF# tools this way is not a supported scenario.  We have these instructions because we made a mistake inserting our code into the RC3 release.

So ... to fix your install ... 
rerun vs setup and select the .Net Desktop Development workload
once it has completed installation everything should work as expected 
(it takes quite a long time, with the progress on zero %)

I hope this helps.

**Comment by brettfo** [comment]
To piggy-back on @KevinRansom's comment, in the next update we've fixed this so it _is_ possible to install just F# (without the .NET Desktop workload) and get the appropriate dependencies.

**Comment by ctaggart** [comment]
Thanks for the detailed installation notes. I screwed them up the first time too. Visual Studio 2017 RC3 comes with the extension: Visual F# Tools 15.4.1.0. The version installed from GitHub using those instructions is 15.4.1.17012301.

![image](https://cloud.githubusercontent.com/assets/80104/22613449/06a4a3a0-ea3e-11e6-8b93-ec32c1c35451.png)

**Comment by chaotic-butter** [comment]
Thank you all, installing the .NET Desktop workload did in fact clear the problem. I was installing just the F# component originally.

**Comment by cartermp** [comment]
Updated [the RC3 instructions](https://github.com/Microsoft/visualfsharp/releases/tag/Visual-Studio-2017-RC3) to remove the bit about selecting F# from Individual Components.

**Comment by ctaggart** [comment]
Thought about creating another issue, but didn't. What is the status for supporting the update msbuild project files.  The notes in https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-rc3 seem to indicate that it doesn't work. When I create a project and run it with `dotnet` it works.
```
dotnet new -l fsharp
dotnet restore
dotnet run
```

I then try to open it in Visual Studio 2017 RC3 with all of this installed and I get this error:

```
---------------------------
Microsoft Visual Studio
---------------------------
The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\FSharp.NET.Sdk\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\camer\fs\testA\testA.fsproj
---------------------------
OK   
---------------------------
```

Where testA.fsproj is:
```
<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <Version>1.0.0-alpha</Version>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.NET.Sdk" Version="1.0.0-beta-*" PrivateAssets="All" />
    <PackageReference Include="Microsoft.FSharp.Core.netcore" Version="1.0.0-alpha-161023" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-compile-fsc">
      <Version>1.0.0-preview2-020000</Version>
    </DotNetCliToolReference>
  </ItemGroup>

</Project>
```

Thoughts? Hacks? Work-a-rounds?

Should I copy some files from the SDK there?
C:\dotnet\dotnet-dev-win-x64.1.0.0-rc3-004530\sdk\1.0.0-rc3-004530\Sdks\FSharp.NET.Sdk\Sdk

**Comment by ctaggart** [comment]
I tried out the hack by copying the missing files with:
``` ps
mkdir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\FSharp.NET.Sdk"
cp -r C:\dotnet\dotnet-dev-win-x64.1.0.0-rc3-004530\sdk\1.0.0-rc3-004530\Sdks\FSharp.NET.Sdk\Sdk "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\FSharp.NET.Sdk\"
```

But then Visual Studio 2017 RC3 can't find the targeting pack for `.NETCoreApp,Version=v1.0` and I can't see how to install that. Does it not come with Community Edition?

![image](https://cloud.githubusercontent.com/assets/80104/22614632/663132f0-ea4a-11e6-8d01-d1560d4f19d8.png)

I know I'm missing something. :-)

**Comment by cartermp** [comment]
@ctaggart Looks like encountering two problems:

1. Lack of F# project system support for the .NET Core SDK and the new MSBuild.  This is a priority 0 issue we're addressing and targeting for a VS2017 microupdate.
2. Lack of the .NET Core SDK on your machine via your installation.

The latter can be addressed right now - there should be a checkbox for .NET Core support in the .NET Desktop workload.  Otherwise, you could install either the ASP.NET workload or the .NET Core/Docker workload.  Either way, it should get you the correct bits.  It's all available on the Community edition.

The former is something that you unfortunately can't address right now.  Just to clarify on the scenario, that means that the .NET CLI will ship with the ability to generate F# projects which cannot be opened in Visual Studio 2017 at this time.

**Comment by ctaggart** [comment]
Thanks @cartermp, looking forward to that microupdate!

**Comment by jpierson** [comment]
@cartermp by "Visual Studio 2017" I'm assuming you mean *Visual Studio 2017 RC3* and that the final release of _Visual Studio 2017_ will indeed include support for opening F# projects created through the .NET CLI tool. Is this correct?

**Comment by cartermp** [comment]
@jpierson No, unfortunately this means that the release of VS 2017 will lack the ability to open an F# project created by the .NET CLI tool.  There is work we need to do in our project system to support the new flavor of MSBuild it uses, which will debut in release form for the first time in the release of VS 2017.

**Comment by jpierson** [comment]
@cartermp that's unfortunate but thanks for making this clear. Where can I follow along for the progress of addressing the project file compatibility? I'm curious how or whether F# projects will be able to leverage the improved wildcard support for source files given the F# compiler's single-pass design.

**Comment by cartermp** [comment]
@jpierson We don't have a tracking issue yet, but we'll create one soon.  It's a top priority issue for us.  In terms of wildcards, we won't be able to use those (or file globbing support).  File order will still have to exist in the project file.

**Comment by curdincaspar** [comment]
@cartermp Any idea when this could be done? It's really frustrating to work with the old and new format side by side. The new C# projects don't understand the old F# format and VS doesn't know the new format.

**Comment by cartermp** [comment]
@curdincaspar See #2461 for the tracking bug for what you've mentioned.  Referencing an F# .NET Framework project from the new C# projects works just fine, but the inverse is not true.  We're targeting the first update of VS 2017.

**Comment by dsyme** [comment]
Closing old RC3 issue

**Comment by biosek** [comment]
I still have this problem...
![](http://i.imgur.com/VPWSnMY.png)
When I try to hack it by copying 
`c:\Program Files\dotnet\sdk\1.0.3\Sdks\FSharp.NET.Sdk\` into 
`c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\`
after trying to open the project I get...
![](http://i.imgur.com/DyhHhAZ.png)

Was that `micro update` already issued? Or is it still in the workings? Thanks

**Comment by cartermp** [comment]
You're experiencing a different issue.  You're attempting to load a .NET Core project (likely created from the CLI?) into VS.  Our project system doesn't support that yet.  We have support in the new dotnet project system (dotnet/project-system on github), which is the one which supports those kinds of projects.  Release date is expected to be July, though there will be some previews available earlier.

**Comment by cartermp** [comment]
Phew, not on mobile anymore.  Much easier to link.  @biosek if you're interesting in tracking it, [here](https://github.com/dotnet/project-system/issues?q=is%3Aopen+is%3Aissue+label%3AArea-F%23) is the link.  You'll notice Milestones say "15.3".  That means the 3rd update of Visual Studio 2017 (and 15 is the technical version of Visual Studio).  3rd update is supposed to be out around July.

**Comment by hasanOryx** [comment]
I've same problem at MS VS for MAC, while trying making iOS app, with C# it is fine, but with F# it is not working.
