### ISSUE TITLE
Active pattern tooltip has incorrect type signature

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2367]
The tooltip for active patterns has regressed in master since RC2 (probably when we colourised the tooltips but I'm not entirely sure):

## Master
![image](https://cloud.githubusercontent.com/assets/64654/22612771/c3378b5a-ea6a-11e6-8c61-8d6662a8ea64.png)

## RC2
![image](https://cloud.githubusercontent.com/assets/64654/22612813/f81354f8-ea6a-11e6-993b-c5c0f2bbf58a.png)

**Comment by vasily-kirichenko** [comment]
Looks good to me.

**Comment by cartermp** [comment]
I think this is an interesting mix of regression and (IMO) improvement.  The `s:string -> int option` and Fulle name bits are missing which is a regression, but I do prefer `active pattern Integer: unit` in the QuickInfo.  Perhaps the following is what's needed?

```
<glyph> active pattern Integer: unit -> s:string -> int option

Full name: Validation.( |Integer|_| )
```

Thoughts?

**Comment by saul** [comment]
I think it *is* a regression. I don't have one to hand, but I'm pretty sure in VS 2015 this would show as an "active pattern recognizer" with the signature of "string -> int option".

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2809
