### ISSUE TITLE
"Failed to retrieve msbuild property ProjectGuid form the project file" error

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2370]
1. Open any file from FSharp.Editor - OK
2. Open service.fs from FSharp.LanguageService.Compiler:

![image](https://cloud.githubusercontent.com/assets/873919/22618677/f0bdbd72-eaf3-11e6-8ed1-143bf57b62ea.png)

3. Close it, reopen. Same error.

**Comment by cartermp** [comment]
Is this on RC3 + VSIX or latest master?

**Comment by vasily-kirichenko** [comment]
RC3 + VSIX.

**Comment by cartermp** [comment]
Hmm.  I can't repro this on my machine, although for some reason I'm also unable to load certain projects because it thinks I need the ASP.NET workload.  Creating issue...

**Comment by cartermp** [comment]
So to clarify, I'm unable to build: FSharp.LanguageService.Base, ProjectSystem.Base, FSharp.PropertiesPages

Which aren't F# so it makes be believe that there's a setup issue on my machine.  That said, I still can't repro your issue:

![cant-repro](https://cloud.githubusercontent.com/assets/6309070/22620661/6d2e91a8-eac5-11e6-8c49-382c2622ddb1.PNG)

**Comment by bentayloruk** [comment]
I have just encountered this issue.  RC3 + VSIX.  Screenshot and VS version details below.

Can I help figure it out?  It's basically a brand new project, although I don't recall if I created pre or post VSIX install.

<details>
<summary>Click to expand my Visual Studio About "Copy Info" details</summary>
Microsoft Visual Studio Professional 2017 RC
Version 15.0.26127.3 D15SVC
Microsoft .NET Framework
Version 4.6.01590

Installed Version: Professional

Visual Basic 2017 RC   00369-50000-00000-AA747
Microsoft Visual Basic 2017 RC

Visual C# 2017 RC   00369-50000-00000-AA747
Microsoft Visual C# 2017 RC

Visual F# 4.1   00369-50000-00000-AA747
Microsoft Visual F# 4.1

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GhostDoc   5.4.16325.0
GhostDoc automatically generates XML documentation comments.

JetBrains ReSharper Ultimate 2016.3.2    Build 107.0.20170126.120331
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

Markdown Editor   1.10.186
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

VsVim   2.1.1.0
VsVim is a Vim emulator for Visual Studio
</details>

<hr/>

**Error Screenshot**

![image](https://cloud.githubusercontent.com/assets/189409/22825969/e08ce23c-ef87-11e6-9426-67e12d22522f.png)

**Comment by vasily-kirichenko** [comment]
@bentayloruk I think it makes no sense to test RC3 anymore.

**Comment by bentayloruk** [comment]
Ah, OK.  How come?  Is there a later VSIX or is it build your own time?

**Comment by vasily-kirichenko** [comment]
Just update VS, it's now RC4, no need for manually installed VSIX

**Comment by bentayloruk** [comment]
Doh! Thanks. 😊

**Comment by cartermp** [comment]
I actually noticed this on Parallels + the [Nu project](https://github.com/bryanedds/Nu) yesterday.  I'm not sure if it was just some pain related to using a project not built in VS2017 or not, but based on the above it does sound like there's a bug somewhere.

**Comment by BentTranberg** [comment]
I got this error dialog when trying to open fs files in any kind of F# project in a solution with the fresh release version of VS 2017. The files opened in spite of the error dialog.
.NET Framework 4.5.2, F# 4.0 (4.4.0.0).

After restarting VS the problem disappeared, but another problem with missing or superfluous entries in the Error List pane appeared instead. Not sure if it's related.

**Comment by cartermp** [comment]
@BentTranberg Could you create a separate issue about the superfluous entries?  If you have a minimized repro + screenshots that would be superb.

**Comment by BentTranberg** [comment]
I did, but I doubt it's related. Here: https://github.com/Microsoft/visualfsharp/issues/2548
