### ISSUE TITLE
Cannot install VisualFSharpOpenSource.vsix on RC4

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2374]
> 05-Feb-17 16:42:11 - Microsoft VSIX Installer
05-Feb-17 16:42:11 - -------------------------------------------
05-Feb-17 16:42:11 - vsixinstaller.exe version:
05-Feb-17 16:42:11 - 15.0.26127.3 built by: D15SVC
05-Feb-17 16:42:11 - -------------------------------------------
05-Feb-17 16:42:11 - Command line parameters:
05-Feb-17 16:42:11 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe,E:\github\visualfsharp\release\net40\bin\VisualFSharpOpenSource.vsix
05-Feb-17 16:42:11 - -------------------------------------------
05-Feb-17 16:42:11 - Microsoft VSIX Installer
05-Feb-17 16:42:11 - -------------------------------------------
05-Feb-17 16:42:12 - Initializing Install...
05-Feb-17 16:42:12 - Extension Details...
05-Feb-17 16:42:12 - 	Identifier         : VisualFSharp
05-Feb-17 16:42:12 - 	Name               : Visual F# Tools
05-Feb-17 16:42:12 - 	Author             : Microsoft.VisualFSharpTools
05-Feb-17 16:42:12 - 	Version            : 42.42.42.42
05-Feb-17 16:42:12 - 	Description        : Deploy Visual F# Tools templates to Visual Studio
05-Feb-17 16:42:12 - 	Locale             : en-US
05-Feb-17 16:42:12 - 	MoreInfoURL        : 
05-Feb-17 16:42:12 - 	InstalledByMSI     : False
05-Feb-17 16:42:12 - 	SupportedFrameworkVersionRange : [4.6,)
05-Feb-17 16:42:12 - 
05-Feb-17 16:42:12 - 	SignatureState     : Unsigned
05-Feb-17 16:42:12 - 	Supported Products : 
05-Feb-17 16:42:12 - 		Microsoft.VisualStudio.Pro
05-Feb-17 16:42:12 - 			Version : [15.0]
05-Feb-17 16:42:12 - 
05-Feb-17 16:42:12 - 	References         : 
05-Feb-17 16:42:12 - 	Prerequisites      : 
05-Feb-17 16:42:12 - 		-------------------------------------------------------
05-Feb-17 16:42:12 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
05-Feb-17 16:42:12 - 		Name         : Visual Studio core editor
05-Feb-17 16:42:12 - 		Version      : [15.0,16.0)
05-Feb-17 16:42:12 - 
05-Feb-17 16:42:12 - Signature Details...
05-Feb-17 16:42:12 - 	Extension is not signed.
05-Feb-17 16:42:12 - 
05-Feb-17 16:42:12 - Searching for applicable products...
05-Feb-17 16:42:12 - Found installed product - Global Location
05-Feb-17 16:42:12 - Found installed product - Visual Studio Enterprise 2017 RC
05-Feb-17 16:42:12 - PKGDEF Information: Looking for master PkgDef file, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\master.pkgdef

05-Feb-17 16:42:12 - PKGDEF Information: Creating PkgDefCacheNonVolatile
05-Feb-17 16:42:12 - PKGDEF Information: Double-checking master pkgdef file
05-Feb-17 16:42:12 - PKGDEF Information: PkgDefManagement initialized
05-Feb-17 16:42:12 - PKGDEF Information: RootFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

05-Feb-17 16:42:12 - PKGDEF Information: ShellFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\

05-Feb-17 16:42:12 - PKGDEF Information: PkgDefSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.admin.pkgdef

05-Feb-17 16:42:12 - PKGDEF Information: ImageManifestSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions;C:\Users\vaski\AppData\Local\Microsoft\VisualStudio\15.0_183b437f\Extensions

05-Feb-17 16:42:12 - PKGDEF Information: ApplicationExtensionsFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions

05-Feb-17 16:42:12 - PKGDEF Information: "ZeroImpact" = dword:0, "MergeRegistry" = dword:3
05-Feb-17 16:42:12 - PKGDEF Information: PkgDefCache flags, PKGDEF: 7005
05-Feb-17 16:42:12 - PKGDEF Information: PkgDefManagement startup complete
05-Feb-17 16:42:13 - The extension will be upgraded from version 15.4.1.17012301.
05-Feb-17 16:42:35 - The following target products have been selected...
05-Feb-17 16:42:35 - 	Visual Studio Enterprise 2017 RC
05-Feb-17 16:42:35 - 
05-Feb-17 16:42:35 - Beginning to install extension to Visual Studio Enterprise 2017 RC...
05-Feb-17 16:42:35 - Upgrading 'Visual F# Tools', version 15.4.1.17012301 to version 42.42.42.42.
05-Feb-17 16:42:52 - Install Error : System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by majocha** [comment]
Yep, it's like this since 0a38f47bb28e8dda6d3e6a68a32c33d44923f8dc, I think.
Workaround (not really) for now is to directly use `devenv /rootsuffix FSharpDev`

**Comment by cartermp** [comment]
cc @brettfo

**Comment by cloudRoutine** [comment]
I'm getting the exact same error message as @vasily-kirichenko when I try to install the `VisualFSharpOpenSource.visx`

**Comment by brettfo** [comment]
What happens when you F5 (or Ctrl F5) the VisualFSharpOpenSource project from VisualFSharp.sln?  I think that does some different type of install, but I'm not totally sure how it works.  Could you modify VisualFSharpOpenSource to deploy to the root hive instead of FSharpDev and Ctrl F5 to get it installed?

**Comment by vasily-kirichenko** [comment]
Ctrl+F5 work fine. F5 has never ever worked for me, an exp VS instance trying to start and crashes. Every single time.

**Comment by vasily-kirichenko** [comment]
> ould you modify VisualFSharpOpenSource to deploy to the root hive instead of FSharpDev and Ctrl F5 to get it installed?

Oh... interesting (and very hacky) idea...

**Comment by majocha** [comment]
Dropping vsix content directly into the folder worked for me. Visual Studio crashed on first run but after a restart started working fine.

**Comment by vasily-kirichenko** [comment]
@majocha Dropped the content. VS crashes on loading VFT solution. Reverted the content - crashes. Gonna restore VS...

**Comment by vasily-kirichenko** [comment]
Removing / adding VFT has not helped :) The whole extension thing is so fragile.

**Comment by vasily-kirichenko** [comment]
Thanks god VS restore has made the magic.

**Comment by vasily-kirichenko** [comment]
So, currently I strongly doubt _anybody_ test current master because - how?

**Comment by vasily-kirichenko** [comment]
BTW, I would prefer the Full VSIX to be installable, in the same way as RC3 signed one is. I tried and it says that the extension is already installed. Is it because my VSIX is unsigned?

**Comment by smoothdeveloper** [comment]
> So, currently I strongly doubt anybody test current master because - how?

I don't test master, roughly since I faced #2351 and seeing other conversations along same type of issue running the vsix project.

If there are updated, consistent and not too long steps that we have to make it work, I'll resume some light testing of master (and attempt to contribute small feature).

**Comment by majocha** [comment]
@vasily-kirichenko 
Hmm... It definitely should work.
Can you see FSharp assemblies listed when you do `sn -Vl`?

**Comment by majocha** [comment]
@smoothdeveloper 
After today's RC update I managed to "install" from current master with following steps:

- in VisualFSharpOpenSource project properties check `Copy VSIX content to the following location:`
- enter `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp` as location, backup that folder first just in case
- close VS and run `build vs`
-restart VS
if FSharp package fails to load you may have to run `src\update release` to skip strong name verification.

**Comment by smoothdeveloper** [comment]
@majocha thanks for your help, I seem to be able to run VisualFsharp.sln after updating to latest RC!

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper RC3 is good, it works OK so far. Have you installed the OpenSource VSIX on it?

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko I haven't yet installed the opensource vsix, I was able to run master branch and debug into it, I'll do more testing with changing the code and running it.

**Comment by vasily-kirichenko** [comment]
Tried on RC4, same error:
> 08-Feb-17 15:03:53 - Beginning to install extension to Visual Studio Enterprise 2017 RC...
08-Feb-17 15:03:53 - Upgrading 'Visual F# Tools', version 15.4.1.17020301 to version 42.42.42.42.
08-Feb-17 15:03:54 - Install Error : System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by vasily-kirichenko** [comment]
@brettfo 
> What happens when you F5 (or Ctrl F5) the VisualFSharpOpenSource project from VisualFSharp.sln? I think that does some different type of install, but I'm not totally sure how it works. Could you modify VisualFSharpOpenSource to deploy to the root hive instead of FSharpDev and Ctrl F5 to get it installed?

Just tried Ctrl+F5. No errors, but OS VSIX is not actually installed into FSharpDev instance. So, we cannot even test anything :(

**Comment by brettfo** [comment]
@vasily-kirichenko: Can you try a clean install of VS?  I just tried this locally and I'm appropriately getting 42.42.42.42 installed at `%localappdata%\Microsoft\VisualStudio\15.0_39d5e2fbFSharpDev\Extensions\Microsoft.VisualFSharpTools\Visual F# Tools\42.42.42.42` and it's also appearing under Tools -> Extensions and Updates.

**Comment by vasily-kirichenko** [comment]
Fixed in master.
