### ISSUE TITLE
Cannot test VFT at all

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2386]
In addition to https://github.com/Microsoft/visualfsharp/issues/2374 (cannot install the vsix into the main hive), it's now not possible to test in in FSharpDev instance, either, see https://github.com/Microsoft/visualfsharp/issues/2374#issuecomment-278318303

**Comment by majocha** [comment]
F5 Seems to work, at least after deleting *FSharpDev folder ![przechwytywanie](https://cloud.githubusercontent.com/assets/1760221/22738770/14543cf8-ee09-11e6-9f8f-7aba6ce41a55.PNG)
Next I changed the version number to check if the vsix gets redeployed on rebuild:

![43](https://cloud.githubusercontent.com/assets/1760221/22739267/396383c6-ee0b-11e6-9911-35eed19d85a1.PNG)

**Comment by vasily-kirichenko** [comment]
@majocha oh, yeah, after deleting FSharpDev folders F5 works (yes, F5!)
