### ISSUE TITLE
"Find all references" returns 3 identical results for an attribute

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2387]
![image](https://cloud.githubusercontent.com/assets/873919/22739758/26d2a666-ee1e-11e6-9096-e0cff9ced8e2.png)

![image](https://cloud.githubusercontent.com/assets/873919/22739787/46d50db4-ee1e-11e6-9ddf-5abcd10609fd.png)

**Comment by cartermp** [comment]
Repro'd on my machine as well.  Good catch!

**Comment by vasily-kirichenko** [comment]
FCS returns three `FSharpSymbolUse` which have different `ItemOccurrence`s (Use, UseInAttribute, UseInType). We don't care about the occurrence type here, so we can distinct by symbol use range.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2396
