### ISSUE TITLE
tooltip on open declarations are faulty

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2393]
With VS2017 RC4 I have this in a .fsx file:

```fsharp
open System.Collections
open System.Windows.Forms
```

when I hover on `Collections`, it shows `Microsfot.FSharp.Collections`, when I hover on `Windows` or `Forms` it doesn't show anything.

**Comment by vasily-kirichenko** [comment]
This is fixed in master long ago.

**Comment by cartermp** [comment]
Yup, looks like I missed #2298

**Comment by smoothdeveloper** [comment]
I confirm running master doesn't reproduce this.
