### ISSUE TITLE
how to open the project created by dotnet cli

### ISSUE THREAD

**Issue by Huqin-China** [Microsoft/visualfsharp#2394]
i use the dotnet core cli tools create a f# library,
when open it through vs2017 rc3 ,it alert me that some error about Fsharp.net.sdk?
what can i do to edit the project use vs2017rc3

**Comment by vasily-kirichenko** [comment]
It's not supported yet.

**Comment by forki** [comment]
The only thing you can do is to use Visual Studio Code together with the ionide plugin. This is working for me like a charme. As @vasily-kirichenko said Visual Studio is not working in this scenario and unfortunately there is noone trying to implement it yet.

**Comment by vasily-kirichenko** [comment]
Unfortunately? No one working on it ==============> no one _really_ wants it.

**Comment by forki** [comment]
>> no one really wants it.

This is already a real show-stopper for us. We happily use the dotnet core stuff in production and since it's only working in Ionide we can't use VS any more. Yes this is a recent development and you could argue I should try to put in VS, but to be tbh I really think MS should do it. All this company-wide push for coreclr and then we can't use it in VS - that's really weird.

**Comment by vasily-kirichenko** [comment]
@forki we both know that MS is not gonna do anything.

**Comment by isaacabraham** [comment]
Maybe they can prove you wrong and show you that they care more about the platform than you feel :-)

**Comment by vasily-kirichenko** [comment]
@isaacabraham That's the plan.

**Comment by forki** [comment]
I mean given that dotnet core was the most important thing in F# 4.1 it's really a bummer that we can't actually use it in VS. So much work rendered completely useless.

**Comment by Huqin-China** [comment]
thanks all,i won't move on dotnet core platform until it's strong enough,my entire math core are written by f#
