### ISSUE TITLE
Support compilation and running unit tests on 64 bit Windows

### ISSUE THREAD

**Issue by xepaul** [Microsoft/visualfsharp#24]
I'm not sure if its just me but I had issues running tests on 64 windows.
It would be good to fix this or at least put notes in the Dev and Test guides.

**Comment by KevinRansom** [comment]
Which branch?
What were the issues?


Thanks

Kevin

**Comment by forki** [comment]
I have 64bit Windows and tests run fine on current fsharp4 branch. But during the development of my nameof I broke the proto-compiler and saw really strange results. I recommend you clean every from your repo (git clean - xdf) and try from the beginning.

**Comment by xepaul** [comment]
Ahh ok thanks. I had issues running the BuildTestTools.cmd with complains from ILComparerfsproj on the fsharp4 branch

**Comment by latkin** [comment]
@KevinRansom and I and many others are using x64 and aren't having trouble. Any other info you can provide? Can you try full clean + rebuild?

**Comment by dsyme** [comment]
64-bit works for me
