### ISSUE TITLE
Simplify name kicks in on slicing syntax for strings and arrays

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2405]
On RC4 and the following code:

```fsharp
[<EntryPoint>]
let main argv = 
    let arr = [|1;2;3;4;5|]
    let lst = [1;2;3;4;5]
    let str = "bananas"

    ignore <| arr.[1..arr.Length-1]
    ignore <| lst.[2..4]
    ignore <| str.[0..3]

    0 // return an integer exit code
```

**Expected:** I'm not prompted for any lightbulbs

**Actual:** I'm prompted to simplify the name for `arr` and `str` (but not `lst`):

![simplify-bug](https://cloud.githubusercontent.com/assets/6309070/22835718/92409344-ef6e-11e6-9f44-9dcf6392ad58.gif)

**Comment by vasily-kirichenko** [comment]
I turned it off in master long time ago. It is too expensive. Maybe we return to it some time in the future.

**Comment by cartermp** [comment]
Yeah, I'd love to see it in there eventually.  Definitely gives the feeling that the IDE is more "alive".

**Comment by vasily-kirichenko** [comment]
I think we could revert it if a user setting were added.

**Comment by dsyme** [comment]
Closing since the feature is turned off
