### ISSUE TITLE
Colorization Discrepancies between settings, source, and tooltips 

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#2410]
For C# everything matches 

![](http://i.imgur.com/edYjNIg.png)

For F#.......not so much

![](http://i.imgur.com/9nkCUUB.png)

### Issues in the Source Coloring -

- [x] Classes are colored as modules instead of using their own color
- [x] Interfaces are colored as modules instead of using their own color
- [x] Structs are colored as modules instead of using their own color
- [x] Generics/Type Parameters are colored as modules instead of using their own color
- [x] In Generics `'` is not colored the same as the rest of the parameter name
- [x] Some punctuation is not colored
- [x] Some punctuation is colored incorrectly as operators
- [x] Fully Qualified Union Cases aren't colored
- [x] Fully Qualified Enum Cases aren't colored
- [x] Function fields on records are not highlighted as functions - fixed #2722

![](https://cloud.githubusercontent.com/assets/64654/24425040/8dde2324-13fa-11e7-88d0-7e355b8be45c.png)

### Issues in the Tooltip Coloring -
- [ ] `<-` is colored as punctuation instead of as a keyword
- [ ] Interfaces and Classes are colored as structs in the body of the signature instead of using their respective colors
- [x] `[]` is colored as punctuation instead of as a Class
- [ ] Methods/members are not colored
- [ ] Enum cases are listed as fields in tooltips on right side of pattern match
- [ ] Enum cases don't have a construct name

**Comment by vasily-kirichenko** [comment]
Quick info uses TaggedText, as far as I know, we cannot add new tags. TBH, I don't understand the way Roslyn matches, say, TextTag.Enum and enum classification to get the proper color.

About not respecting colors for modules, struct, etc in the editor, we just pass Roslyn classification type names here https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Classification/ClassificationDefinitions.fs#L28. If it does not work, we should investigate why. I don't think it's a major bug though.

**Comment by majocha** [comment]
Looks like custom tags would be possible if we implemented our own `IDeferredQuickInfoContent` for use here:
[https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/QuickInfo/QuickInfoProvider.fs#L78](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/QuickInfo/QuickInfoProvider.fs#L78)

**Comment by cloudRoutine** [comment]
Cases are now being colored for DUs but not for Enums

![](http://i.imgur.com/kH52s7a.png)

Enum cases don't have a construct name

![](http://i.imgur.com/aVeXqsy.png)

![](http://i.imgur.com/42DUGCs.png)

Enum cases are listed as fields in tooltips on right side of pattern match 

![](http://i.imgur.com/YC2M983.png)


built off of master @ 331dde6aa9e37930eed1bdf2dd81f8da8ac53790

**Comment by cloudRoutine** [comment]
Not sure what's going on in `lex.fs`

![](http://i.imgur.com/TS9BXBz.png)

built off of master @ 331dde6aa9e37930eed1bdf2dd81f8da8ac53790

**Comment by vasily-kirichenko** [comment]
Your color theme is so strange that I barely see any colorization issues there, sorry. Draw arrows with text like "this thing should be colored with green".

**Comment by cloudRoutine** [comment]
in `lex.fs` there are many things going wrong in the colorization, e.g. the color changes mid identifier

![](http://i.imgur.com/tdGErrS.png)

Qualified enum cases are not being colored

![](http://i.imgur.com/CAJ6Pco.png)

You can click on the imgs to open them at full resolution in a new tab

**Comment by cartermp** [comment]
@cloudRoutine Could you split off another issue for the structured guidelines problem?  Thanks!

Interesting how colorization in `lex.fs` is so off with your settings.  Either way, good finds.

**Comment by cloudRoutine** [comment]
@cartermp what do you mean? I already made one
https://github.com/Microsoft/visualfsharp/issues/2431

**Comment by cartermp** [comment]
I'm stupid

**Comment by vasily-kirichenko** [comment]
The glitches are from my perf optimization PR, I'm sure. We can either revert it or investigate what's wrong. Could anybody review it? https://github.com/Microsoft/visualfsharp/pull/2402/files

**Comment by saul** [comment]
@cloudRoutine #2722 also fixed enum case colouring

**Comment by smoothdeveloper** [comment]
@cloudroutine:

>  the color changes mid identifier

it looks like a +1 / -1 thing on line number for this case, look how "trimBoth length" matches the color expected on above line.

**Comment by saul** [comment]
@cloudRoutine @smoothdeveloper - notice the `# 3` directive - I think everything's shifted by 2 lines.

**Comment by dsyme** [comment]
@cloudRoutine Can we close this or should we complete every item mentioned above?

**Comment by dsyme** [comment]
Closing as the major issues have been fixed

**Comment by cartermp** [comment]
Also worth noting that source and tooltips are more aligned now in terms of coloring and tagging. And tooltips also structure classes/structs/interfaces consistently regardless of if it's F#-defined or .NET defined
