### ISSUE TITLE
strange / inconsistent behaviour property setter in constructor call

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2412]
#### Repro steps

I'm using the environment set for #2411 but adding this code to the .fsx:

```fsharp
open Eto.Forms
let textBoxColumn (index: int) header = new GridColumn(HeaderText = header, DataCell = new TextBoxCell index)
```

Note: I don't know if there are restrictions in property setter in the context of such call, it would be good to have explicit error message if this is the case (I was initially confused by the message), but maybe this highlights a class of issues.

#### Expected behavior

I expect the DataCell property to be assigned the same as if I was passing `new TextBoxCell(index)` (with parens)

#### Actual behavior

> error FS0010: Unexpected symbol ')' in expression

#### Known workarounds

Write the call to TextBoxCell constructor with parens

#### Related information 

* Win 7 pro 64bit
* VS2017 RC4

**Comment by smoothdeveloper** [comment]
I'm trying to figure out if this is per the spec, the relevant section would be 

> 14.4 Method Application Resolution
> Resolves post-hoc property assignments.
> If arg is a binary expression of the form name=expr, it is a named actual argument.

I don't see any restriction on expr, it might be worth to expand the spec on restrictions which apply there.

I'm facing similar issue where I need to wrap the expression after `name=` in parens.

```fsharp
[<System.Flags>]
type Flags =
| Foo = 1
| Bar = 2
| Baz = 4

type Boo() =
  member val Val = Flags.Foo with get,set

let b = Boo(Val = Flags.Foo ||| Flags.Bar)
```

> The member or object constructor 'Boo' takes 0 argument(s) but is here given 1. The required signature is 'new : unit -> Boo'.

**Comment by dsyme** [comment]
This is the mistake:
```
new TextBoxCell index
```

Just use
```
new TextBoxCell(index)
```
or
```
TextBoxCell index
```

**Comment by smoothdeveloper** [comment]
@dsyme right, I see that it is an invalid expression on it's own.

Regarding that other case I'm showing in second comment, is there something I'm missing in the spec? syntactically the expression doesn't look ambiguous as there are no `,` or `=` involved, the resolution looks faulty.

**Comment by dsyme** [comment]
> Regarding that other case I'm showing in second comment,

I think that's to do with the relative precedence of `|||` and `=`
