### ISSUE TITLE
project.json files give annoying errors when compiling master in VS2017 RC

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2425]
![image](https://cloud.githubusercontent.com/assets/57396/22882307/b6a5da9a-f1ea-11e6-951b-5f2752b3b14e.png)

anybody seen this?

**Comment by vasily-kirichenko** [comment]
Yes, these error have been for long time. They don't prevent compilation to finish though.

**Comment by forki** [comment]
so who is going to fix that?

**Comment by cartermp** [comment]
Warnings will probably just be part of a cleanup, but the `project.json` stuff involves us upgrading to the new MSBuild and upgrading our build systems.  It won't be immediate (like, today), but it's one of the first prerequisites to getting MSBuild 15 projects loading in our project system, so it's thus a top priority for us.

**Comment by Huqin-China** [comment]
“D:\ProgrammingWorks\visualfsharp\VisualFsharp.sln”(默认目标 defualt target) (1) ->
“D:\ProgrammingWorks\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj”(默认目标) (12) ->
(CoreCompile 目标) ->
  FSC : error FS0193: <未能找到文件can't find file>“D:\ProgrammingWorks\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\obj\Debug\n
et40\ProjectResources.rc.res”。 [D:\ProgrammingWorks\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectS
ystem.fsproj]


“D:\ProgrammingWorks\visualfsharp\VisualFsharp.sln”(默认目标defualt target) (1) ->
“D:\ProgrammingWorks\visualfsharp\vsintegration\tests\unittests\Resources.MockTypeProviders\DefinitionLocationAttribute
WithSpaceInTheType\DefinitionLocationAttributeWithSpaceInTheType.csproj”(默认目标defualt target) (19) ->
(CopyFilesToOutputDirectory 目标) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targe
ts(3979,5): error MSB3021: 无法将文件<can not copy  file>“obj\Debug\net40\DefinitionLocationAttributeWithSpaceInTheType.dll”复制到“D:\ProgrammingWo
rks\visualfsharp\vsintegration\tests\unittests\Resources.MockTypeProviders\DefinitionLocationAttributeWithSpaceInTheTyp
e\..\..\..\..\..\src\..\Debug\net40\bin\UnitTestsResources\MockTypeProviders\DefinitionLocationAttributeWithSpaceInTheT
ype.dll”。指定的路径或文件名太长，或者两者都太长。完全限定文件名必须少于 260 个字符，并且目录名必须少于 248 个字符<filename or path,or both are too long ,fullname must less than 260char,and directory name must less than 248 char>。 [D:\ProgrammingWorks\visualfsharp\vsintegration\tes
ts\unittests\Resources.MockTypeProviders\DefinitionLocationAttributeWithSpaceInTheType\DefinitionLocationAttributeWithS
paceInTheType.csproj]

**Comment by vasily-kirichenko** [comment]
@Huqin-China go to ProjectSystem project and remove `ProjectResources.rc.res`. It should make compiler happy. I encounter this issue on one of my machines on Preview 5 (only).

**Comment by dsyme** [comment]
Closing as I think this is an old issue now?

**Comment by cartermp** [comment]
May be worthwhile to keep it open since we haven't moved away from project.json yet, but it doesn't actually inhibit you from working in the solution.  The errors are a bit of a red herring

**Comment by dsyme** [comment]
ok, thanks

**Comment by cartermp** [comment]
These errors don't show up anymore. We still need to move away from project.json, but that's a separate issue.
