### ISSUE TITLE
"build.cmd vs" won't build on master for VS2017 RC

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2427]
1) run "build.cmd vs" in admin VS developer prompt:

![image](https://cloud.githubusercontent.com/assets/57396/22886718/5c81b8f8-f1ff-11e6-95f7-9f0f3beb7419.png)

    Unerwarteter Fehler bei der GetExtensionsPath-Aufgabe

"Unexpected error at GetExtensionsPath task"

**Comment by majocha** [comment]
Does it matter that it's a 2015 command prompt?

**Comment by forki** [comment]
good catch!
