### ISSUE TITLE
Missing constructor arguments at base constructor call site

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2434]
![image](https://cloud.githubusercontent.com/assets/873919/22921018/ffa2afe8-f2a8-11e6-9562-12b6356549cc.png)

**Comment by vasily-kirichenko** [comment]
I've investigated it a bit. It chooses a proper `NameResolutionEnv`, but it does not contains primary constructors arguments. @dsyme how is it possible? I thought type checker uses the same nameres environment...

**Comment by dsyme** [comment]
>  It chooses the proper NameResolutionEnv

@vasily-kirichenko when you say "proper" how do you mean - proper by range or ...?

**Comment by dsyme** [comment]
@vasily-kirichenko It may be the use of ``AddLocalValuePrimitive`` (no call to ``CallEnvSink``) instead of ``AddLocalVal`` in this code:

```
                            let envInstance = match incrClassCtorLhs.InstanceCtorSafeThisValOpt with Some v -> AddLocalVal cenv.tcSink scopem v envInstance | None -> envInstance
                            let envInstance = List.foldBack AddLocalValPrimitive incrClassCtorLhs.InstanceCtorArgs envInstance 
                            let envNonRec   = match incrClassCtorLhs.InstanceCtorSafeThisValOpt with Some v -> AddLocalVal cenv.tcSink scopem v envNonRec | None -> envNonRec
                            let envNonRec   = List.foldBack AddLocalValPrimitive incrClassCtorLhs.InstanceCtorArgs envNonRec
```

(Really there should only be one call to ``CallEnvSink`` after everything has been added, but simpest fix may be just to change to ``AddLocalVal``)

**Comment by vasily-kirichenko** [comment]
@dsyme I replaced `AddLocalValuePrimitive` with `AddLocalVal`, now it goes to this:

![image](https://cloud.githubusercontent.com/assets/873919/22966605/faa18520-f373-11e6-8777-226f4f5ccc9b.png)

but `MemberInfo` is `None`, so it's not added to `eUnqualifiedItems`, which prevents appearing it in completion list. 

![image](https://cloud.githubusercontent.com/assets/873919/22966689/63a21170-f374-11e6-8543-e1598e7b4a36.png)
![image](https://cloud.githubusercontent.com/assets/873919/22966696/6cfd412c-f374-11e6-9d76-15ab9297e630.png)

**Comment by vasily-kirichenko** [comment]
Completion works strangely in class body. 

Ctrl+Space after `let x =` (no "ba" yet), then type "ba":

![image](https://cloud.githubusercontent.com/assets/873919/22966939/5fca19d4-f375-11e6-8cde-989cf567bca8.png)

Ctrl+Space after `let x = ba`:

![image](https://cloud.githubusercontent.com/assets/873919/22966986/928bf28e-f375-11e6-8991-6685de6f2f76.png)

However, this trick does not work inside parens in `inherit Base1( )`:

![image](https://cloud.githubusercontent.com/assets/873919/22967021/bcf93ec8-f375-11e6-9d74-c7ce70e1c5b4.png)

**Comment by vasily-kirichenko** [comment]
https://github.com/Microsoft/visualfsharp/pull/2439

**Comment by vasily-kirichenko** [comment]
Ranges of selected `NameResolutionEnv` for each case

![image](https://cloud.githubusercontent.com/assets/873919/22970482/62e5d92e-f383-11e6-9c87-04e21c26eca3.png)

![image](https://cloud.githubusercontent.com/assets/873919/22970551/9f0a3c60-f383-11e6-8bd8-2f23f24e2034.png)

![image](https://cloud.githubusercontent.com/assets/873919/22970606/c8e9e850-f383-11e6-9ff8-76725579f6a0.png)

**Comment by vasily-kirichenko** [comment]
Too hard to fix, too minor issue.
