### ISSUE TITLE
Red marker on global variable in code that compiles

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2446]
* clone https://github.com/fsprojects/Paket
* run build.cmd

open in VS2017 RC with latest (master) vsix and see `verbose` is in red:

![image](https://cloud.githubusercontent.com/assets/57396/23015752/4a4613b4-f434-11e6-8874-9bb5c58bc02e.png)

Interestingly Crtl+F12 works and goes to definition

![image](https://cloud.githubusercontent.com/assets/57396/23015827/9224d828-f434-11e6-8913-887bcaf12df2.png)

**Comment by vasily-kirichenko** [comment]
It's mutable, that's why it's red :)

**Comment by vasily-kirichenko** [comment]
Please suggest a better color if you have one in mind.

**Comment by forki** [comment]
ohhh. i thought it's broken. would never assume that this is a feature.

Mhm that color should really be changed.

**Comment by vasily-kirichenko** [comment]
Yeah. It's really hard to choose a good one. Dark red is just the same as used for strings, for example. If the font is bold, then text moves to the right and left as you type. And so on.

**Comment by nosami** [comment]
Xamarin Studio default mutable  colour
<img width="829" alt="screen shot 2017-02-16 at 09 58 46" src="https://cloud.githubusercontent.com/assets/667194/23016486/916d9ccc-f42e-11e6-8970-9b1babf7f30b.png">

**Comment by vasily-kirichenko** [comment]
What about white theme? It's quite easy to find a lot of good colors for dark theme.

**Comment by TWith2Sugars** [comment]
if it was a garish colour (Mangenta for example) it would definitely put me off from using mutable.

**Comment by nosami** [comment]
<img width="835" alt="screen shot 2017-02-16 at 10 00 59" src="https://cloud.githubusercontent.com/assets/667194/23016582/e2a35640-f42e-11e6-8a36-694a92400980.png">


Me and Dave both wanted red, but Miguel was dead set against it :)

**Comment by vasily-kirichenko** [comment]
What's RGB of it?

**Comment by nosami** [comment]
Dark theme is #ffd21c, Light theme is #a08000

**Comment by vasily-kirichenko** [comment]
we cannot provide defaults for dark theme, so the light one is fine :)

**Comment by ErikSchierboom** [comment]
Perhaps orange is a good suggestion? Is implies a warning (and thus possible danger), but does not imply immediate lethal danger.

**Comment by mariusschulz** [comment]
It's probably too drastic, but what about giving a different background color to mutable variables?

**Comment by nosami** [comment]
Dave made Xamarin Studio switch foreground and background colours for a while... looked pretty good everywhere

**Comment by majocha** [comment]
@vasily-kirichenko 
> we cannot provide defaults for dark theme, so the light one is fine :)
I was thinking if maybe writing two ready sets of color themes into the settings store during installation would work. We could have nice custom themes out of the box.

**Comment by vasily-kirichenko** [comment]
@majocha Please, do it if you know how :)

**Comment by majocha** [comment]
@vasily-kirichenko I have no idea TBH, I would have to investigate this. You probably tried it already?

**Comment by vasily-kirichenko** [comment]
@majocha No, I've not. What we had in VFPT is a set of colors hard coded in C# source.

**Comment by majocha** [comment]
@vasily-kirichenko I'll try to tinker with this. If only color settings are accessible programmatically we could check if they exists and otherwise write some defaults for all themes either on install or first run of the package.

**Comment by voronoipotato** [comment]
Hot pink

**Comment by vasily-kirichenko** [comment]
@voronoipotato like this?

![image](https://cloud.githubusercontent.com/assets/873919/23022139/627b8e88-f460-11e6-9168-4af727ee2708.png)

**Comment by vasily-kirichenko** [comment]
@nosami #A08000

![image](https://cloud.githubusercontent.com/assets/873919/23022191/a270a2d0-f460-11e6-9f66-c5d1ca7e8be3.png)

**Comment by vasily-kirichenko** [comment]
I think I like #A08000 more.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2448

**Comment by voronoipotato** [comment]
Haha fair enough, it's a little less offensive on the eyes, while still quite visible :). 👍

**Comment by majocha** [comment]
I've managed to get the theme manager to build and work so far. What's not cool is that it overwrites user's customizations on every theme change.

**Comment by majocha** [comment]
@vasily-kirichenko I've revived the theme changer [https://github.com/Microsoft/visualfsharp/pull/2450](https://github.com/Microsoft/visualfsharp/pull/2450)
It's a Frankenstein's monster now but seems to work :)

**Comment by majocha** [comment]
Fixed with #2450

**Comment by vasily-kirichenko** [comment]
@nosami point me please at the code which grays out unused open statements (don't tell me you've ported it from VFPT!)

**Comment by cartermp** [comment]
@vasily-kirichenko Should be in here: https://github.com/mono/monodevelop/blob/master/main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs

**Comment by vasily-kirichenko** [comment]
@cartermp yeah, that's it. It contains quite a lot of interaction with MD editor, so it cannot be copy-pasted as is. I'll try.
