### ISSUE TITLE
float function uses invariant culture

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#2449]
It surprised me to find out that float uses the Invariant Culture rather than Current Culture (particularly for working with strings).

This wasn't what we expected. All of our team thought that `float` was simply an alias for `Double.Parse`.

I'm sure there's a reason why this is though.

#### Repro steps

```fsharp
System.Threading.Thread.CurrentThread.CurrentCulture <- System.Globalization.CultureInfo "de-DE"
let x = Double.Parse "80,0" // works
let y = float "80,0" // pop
```

#### Known workarounds

Make sure you use `System.Double.Parse` for parsing strings.

**Comment by vasily-kirichenko** [comment]
The function is here https://github.com/vasily-kirichenko/visualfsharp/blob/fsharp4/src/fsharp/FSharp.Core/prim-types.fs#L4356

**Comment by isaacabraham** [comment]
In retrospect, maybe I have a little hasty in raising this. The XML comment clearly states it's invariant culture. Closing.

**Comment by dsyme** [comment]
@isaacabraham There may be an opportunity for a module of operators (in FSharp.Core or a community library) that uses CurrentCulture.  

You'd need to do the full set of Checked and normal operators etc.

**Comment by isaacabraham** [comment]
Mmmmm. I can imagine one day someone then asking for the same for CurrentUICulture as well ;-)
