### ISSUE TITLE
Navigation (Go To... ) in mixed solution doesn't include F# results

### ISSUE THREAD

**Issue by majocha** [Microsoft/visualfsharp#2468]
Unless we open some F# file first, navigation in mixed solution doesn't include F# results, only C# ( or VB)

#### Repro steps

1. Open VisualFSharp.sln without any F# files pre-opened.

2. Go To Symbol (Ctrl-1, Ctrl-S)

2. start typing for example "roslynhelp"

#### Expected behavior

CommonRoslynHelpers is found

#### Actual behavior

Some C# and VB symbols show up briefly but nothing from F# files is found.

#### Known workarounds

Open some F# file to "jumpstart" FSharpLanguageService

#### Related information 

master on current RC of VS2017

**Comment by vasily-kirichenko** [comment]
It's expected :) First file is triggering all F# project registration in Roslyn.

**Comment by majocha** [comment]
I think I got it to work a little bit better but it needs some testing.

**Comment by majocha** [comment]
OK my internet is abysmal today, but I managed to push it. Seems to work, but I'm new to this codebase, I hope I didn't miss something obvious.
