### ISSUE TITLE
Enrich syntax highlighting with rainbow braces

### ISSUE THREAD

**Issue by financial-engineer** [Microsoft/visualfsharp#2471]
#### New feature suggestion

Dear developers!
Please add rainbow braces to F# syntax highlighting.
Rainbow braces are colorization of braces {}, square brackets [], square and angle brackets [< >] for attributes, angle brackets < > for generic type parameters, and parenthesis (), so language users visually see the corresponding matching brace. As braces are enclosed inside one another, the color changes, so the depth of the expression can be easily seen by language users.

#### Expected behavior
Just like in C# code given below:
![rainbowbraces](https://cloud.githubusercontent.com/assets/1476239/22148769/b9cd99cc-df18-11e6-8292-7f1399b0aa20.png)

**Comment by smoothdeveloper** [comment]
Is that something that needs to be taken care in F# tooling itself?

I know I use rainbow-delimiters in emacs and it works out of box for any language.

I'd see this more suited to a separate VS extension or something in the text editor control itself.

**Comment by financial-engineer** [comment]
@smoothdeveloper 
I work in Visual Studio (not in emacs), and I found no VS extension that 
1) worked correctly with F# code, 
2) did not crash while trying to highlight braces in F# code. 
I believe the support of rainbow braces in F# tooling can greatly improve coding experience for new and existing F# language users.

**Comment by cartermp** [comment]
Personally I think it would be cool, but I think it would have to be preceded by proper settings for IDE features, since I think such a feature would have to be turned off by default.

**Comment by smoothdeveloper** [comment]
@financial-engineer curious how do you get it to do that in C#? 

To be clear, I'd be happy to have that in VS, but not only for F# was my message, I'd like this implemented at a lower level in text editor handling / visible in "all languages" options.

Better editor support of brace matching (like those colors) and for example things like light formatting (like putting spaces and handling indentation when I press return after a construct such as if or for) would sure be good for users.

**Comment by KevinRansom** [comment]
@cartermp I am feeling quit old ... I had to look up rainbow delimiters on the web, to figure out what was being discussed.  In my head I imagined a multi-hued Brace character ....

It seems like a decent idea it would certainly need a switch.

Whenever I get confused about brace matching I like to copy the offending code to notepad and manually indent each level of brace so that it is perfectly clear to me what is intended.   So ... what I would like is a ode formatter that would be able to do that for me

My contribution to the bikeshed design:-)

**Comment by cloudRoutine** [comment]
viasfora does this - http://viasfora.com/

![](http://i.imgur.com/O2dLp40.png)

**Comment by financial-engineer** [comment]
@cloudRoutine 
viasfora does not colorize braces in F# code in my VS 2015, and it crashes, I do not know why. So, I asked for new feature.
OK, I'll wait for an official release of VS 2017 and install it along with viasfora.

**Comment by vasily-kirichenko** [comment]
@financial-engineer don't think VS 2017 RTM will be any different from RC4. It's better to try RC4 now and report bugs.

**Comment by smoothdeveloper** [comment]
This is color-scheme I ported from my emacs pasted into Viasfora settings:
```
#C071E1
#8371E1
#719BE1
#71DDE1
#71E19B
#8EE171
#D8E171
#E1A071
#E17471
```

![image](https://cloud.githubusercontent.com/assets/87944/23334132/00f85052-fb99-11e6-8209-220f8cf9612a.png)

![image](https://cloud.githubusercontent.com/assets/87944/23334137/1c4b9daa-fb99-11e6-87d1-1a340edc71c9.png)

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper I don't think many people interested how it looks in a dark theme.

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko those colors work well on both themes I think.

**Comment by smoothdeveloper** [comment]
![image](https://cloud.githubusercontent.com/assets/87944/23334294/dca2f2d6-fb9b-11e6-9ab2-fb74aacd3c12.png)

the yellow might need tweaking, and if needed, darken all of them.

**Comment by KevinRansom** [comment]
Dang that is colorful.  It would be worth using a dark them just to get that much color on screen :-)

**Comment by dsyme** [comment]
Closing - feature suggestion best tracked on user voice or elsewhere (also viasfora shoud just add F# support?)

**Comment by charlesroddie** [comment]
viasfora has F# support now
