### ISSUE TITLE
Add Open Codefix does not work for operators

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2473]
Using RC4, enter the following in an F# script file:

```fsharp
module MyOps =
    let (>.>) x f = f(x)

let bananas xs =
    xs >.> List.map (fun x -> "bananas")
```

**Expected:** Lightbulb comes up, offering to `open MyOps`.

**Actual:** No lightbulb.

Note that this affects libraries such as Suave, where you need to open the `Suave.Operators` namespace to compose routes, and it's not always obvious to people that this is the case.

**Comment by cartermp** [comment]
I can get it to trigger by adding `FS0043` to the list of `fixableDiagnosticIds`.  Looks like this:

![codefix-maybe-work](https://cloud.githubusercontent.com/assets/6309070/23236775/6870ebae-f90f-11e6-8940-c90ca87e07cf.PNG)

The latter option actually causes the code to fail to compile because it's treated just as a regular function call.  That suggestion could get filtered in this case, I guess.

@vasily-kirichenko any concerns about recognizing `FS0043`?

**Comment by vasily-kirichenko** [comment]
@cartermp looks like a good fix.
