### ISSUE TITLE
Please support CoClassAttribute

### ISSUE THREAD

**Issue by sayurin** [Microsoft/visualfsharp#248]
F# doesn't support System.Runtime.InteropServices.CoClassAttribute.
At C#,
```C#
[Guid("AC4A48F4-590E-4FEF-807B-1CE30011866C")]
class CoClass {}

[ComImport, Guid("4862688B-AC55-42CA-A71F-B80C082CCA31"), CoClass(typeof(CoClass))]
interface Interface {}

var i = new Interface();
```
last line is compiled as
```C#
var i = (Interface)new CoClass();
```
But F#,
```F#
let i = Interface ()        // FS0804
let i = CoClass () :?> Interface    // FS0193
let i = CoClass() |> box :?> Interface    // ok
```
F# compiler should support CoClassAttribute like C# compiler.

**Comment by KevinRansom** [comment]
I'm not inclined to support this.  The C# support is an idiosyncratic corner of the language, I doubt if the current language designers would approve this feature if it was being proposed today.

We could consider improving the error message to notice the CoClassAttribute on the interface and suggest new of the coclass instead.

**Comment by KevinRansom** [comment]
There seems to be no great appetite for this so I am closing this issue.
