### ISSUE TITLE
"Unexpected null" when trying to rename

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2484]
![image](https://cloud.githubusercontent.com/assets/57396/23308599/fbcdcb72-faab-11e6-90ce-6b765a5ea263.png)

**Comment by vasily-kirichenko** [comment]
Could you attach, pause and look at call stack?

**Comment by forki** [comment]
tried. no idea how to get the call stack

**Comment by vasily-kirichenko** [comment]
open "Debug -> Parallel Stacks", find the relevant one (which ends with something like "show dialog")

**Comment by forki** [comment]
shit can't reproduce anymore.
