### ISSUE TITLE
Visual Studio 2013 tab file print file.fs - Error Index was outside bounds of the array.

### ISSUE THREAD

**Issue by Art** [Microsoft/visualfsharp#249]
Visual Studio 2013 tab file print file.fs - Error " Index was outside bounds of the array. "

Print works fine if I select a program.cs file. 

This error has been around for some time. I just finally got fed up with it.
So if anyone has the secret sauce, please share.
If it's not a cock pit error, please if possible fix.

And please check that F# 4.0 and VS '15 work and play and print together.

![2-17-2015 4-32-26 pm](https://cloud.githubusercontent.com/assets/18847/6241110/e8d8ca96-b6cc-11e4-98c9-2d87d5debc8f.jpg)

**Comment by latkin** [comment]
This is actually one of the very first bugs that was fixed for VS 2015.  Fix was done last June, and hit the open repo in September when the fsharp4 git branch finally got going. See commit [ae51ca7](https://github.com/Microsoft/visualfsharp/commit/ae51ca7a422e8867ade374a#diff-b933613d7e072820c8fd25f782ee9b6b).

At the time we didn't think it affected VS 2013. I don't repro in 2013 right now (running VS 2013 Update 2, maybe it repros with update 3 or 4?).  Do you know when it started occurring?

**Comment by rojepp** [comment]
I can not reproduce in F# 3.1.2 on VS 2013 update 4. @Art What versions are you using?

**Comment by KevinRansom** [comment]
Visual studio 3.1.2 can be downloaded from here: 

[https://visualstudiogallery.msdn.microsoft.com/06b5edaf-9557-4987-b64e-f1722b015e86?SRC=Home](https://visualstudiogallery.msdn.microsoft.com/06b5edaf-9557-4987-b64e-f1722b015e86?SRC=Home)

**Comment by KevinRansom** [comment]
Sorry pressed the wrong button.

**Comment by enricosada** [comment]
i cannot repro 

    Microsoft Visual Studio Premium 2013
    Version 12.0.31101.00 Update 4
    Microsoft .NET Framework
    Version 4.5.50938

    Installed Version: Premium

    Visual F# 2013   06191-004-0456024-02977
    Microsoft Visual F# 2013

**Comment by latkin** [comment]
Ok, given that this does not seem to have reliable VS 2013 repro, and it's definitely fixed in 2015, I think it's safe to close out.
