### ISSUE TITLE
Send to Interactive not bound to Alt+Enter in german VS2017

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2490]
I installed german VS2017 + master vsix.

Alt+Enter is not bound to "Interaktiv ausführen"

**Comment by vasily-kirichenko** [comment]
I confirm it does not bound in English either.

**Comment by cartermp** [comment]
Looks like this one wasn't tracked yet.  Thanks @forki

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/23474989/2cdb1bc6-feb6-11e6-92ac-bea577790d3d.png)

weird it shows as configured corrently after install, but doesn't work

**Comment by forki** [comment]
or maybe it's because it's bound to "FSharpEditorFactor" - whatever that means

**Comment by smoothdeveloper** [comment]
FSharpEditorFactory is a place somewhere in Russia.

**Comment by forki** [comment]
Ok so you're saying vaskir is slacking and not responding to my alt+enter
commands? VASKIR! Wake up buddy.

Am 01.03.2017 10:10 nachm. schrieb "Gauthier Segay" <
notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
I think @dungpa is the only person who touched commands handling. PHAN, we need you!

**Comment by dungpa** [comment]
The FSharpEditorFactory is introduced in https://github.com/Microsoft/visualfsharp/pull/2029.
There is a relevant comment:

> Note: This also requires a change to the Alt+Enter bindings in Visual Studio. So the fix won't be apparent until the next update to Visual Studio 2017 RC.

@JoshVarty Is this related? Has the mentioned Visual Studio change been available in any RC yet?

**Comment by forki** [comment]
so there is a chance this magically works in RTM?

**Comment by KevinRansom** [comment]
Alt+enter works for me with the RTM candidate on my desktop.

1.  open a .fsx file
2.  type in some code
3.  highlight and use alt+enter to send it to FSI works

Kevin




.

**Comment by JoshVarty** [comment]
@vasily-kirichenko and @forki What versions of VS are you using? (In `Help` >`About`)

Did this command work for you recently and stop? Or has it simply not been working at all?

I re-enabled it some time ago, but I'm not sure how the F# changes have flowed through to VS.

**Comment by forki** [comment]
I'm on rc4. It always worked in VS 2015. It did not work in rc4 when I
first tried.

After binding manually to global workspace it worked.

Am 03.03.2017 3:43 vorm. schrieb "Josh Varty" <notifications@github.com>:

**Comment by JoshVarty** [comment]
Can you show me what exists in the drop down when you reset to default commands and press Alt+Enter in the shortcutkey box?

For example, here's mine:

![image](https://cloud.githubusercontent.com/assets/1249087/23543616/cd54d6c2-ffa7-11e6-8baf-56fd853b03cd.png)

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/23543792/201f5eee-fff4-11e6-86df-0bbd18d4b62d.png)

^^ it's the same. Just translated.

**Comment by JoshVarty** [comment]
In the "Shortcut currently used by:" dropdown as well? And in the same order?

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/23544011/4603dd50-fff5-11e6-8044-4b69359e16c2.png)

mhm order looks reversed!?

**Comment by forki** [comment]
(btw: I'm only using german in order to ind more bugs - I would never do that during production times ;-) )

**Comment by JoshVarty** [comment]
On second thought I was wrong about order being important (it's just alphabetical).

It looks like everything is registered correctly so I'm not sure what's wrong exactly. Tomorrow I'll let up a VM with German language and see if I can repro. Thanks for your help! :)

**Comment by forki** [comment]
@JoshVarty it's not germa language related. @vasily-kirichenko had the same in english

**Comment by forki** [comment]
I think the issue is with FSharpEditorFactory being not configured in my build. @KevinRansom said his newer build works.

**Comment by JoshVarty** [comment]
@vasily-kirichenko Do you use the English version of Windows as well?

It's just concerning to me that my RC4 bits work and yours do not. I'll just run some sanity checks on fresh machines tomorrow. 

It would be a shame if my only PR to the F# repo broke such a critical feature. 😩

**Comment by majocha** [comment]
English Windows here with English VS2017 RC4 and I can repro this, too.

**Comment by majocha** [comment]
Maybe naïve question, but looking at `fsiCommands.vsct` it seems someone tried to make it work with UIContexts:
[https://github.com/Microsoft/visualfsharp/blob/389f04f326a55d58111f2ca1b627b8736c3f0561/vsintegration/src/FSharp.VS.FSI/fsiCommands.vsct#L196](https://github.com/Microsoft/visualfsharp/blob/389f04f326a55d58111f2ca1b627b8736c3f0561/vsintegration/src/FSharp.VS.FSI/fsiCommands.vsct#L196)

There also seems to be an attempt to use custom UIContext. Custom guid defined here, that is never, nowhere used:
[https://github.com/Microsoft/visualfsharp/blob/389f04f326a55d58111f2ca1b627b8736c3f0561/vsintegration/src/FSharp.VS.FSI/fsiCommands.vsct#L256](https://github.com/Microsoft/visualfsharp/blob/389f04f326a55d58111f2ca1b627b8736c3f0561/vsintegration/src/FSharp.VS.FSI/fsiCommands.vsct#L256)

Wouldn't a rule based approach work reliably for us: [Use Rule-based UI Context for Visual Studio Extensions](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions) ? Or is there some gotcha here?

**Comment by JoshVarty** [comment]
That's certainly worth exploring. If the comment there is correct and it's not working then we should probably remove it entirely for the sake of clarity.

I'm in the process of setting of my VMs (one with RC4, one with RTW).

In the meantime @cartermp do the [rules for installing RC3](https://github.com/Microsoft/visualfsharp/releases/tag/Visual-Studio-2017-RC3) also apply to RC4? Or were the changes integrated into VS in time for RC4?

**Comment by cartermp** [comment]
@JoshVarty Nope, changes were integrated for RC4.  No extra instructions necessary.

**Comment by JoshVarty** [comment]
For `15.0.0-RC.4+26206.0 (Community)` taken from `public facing download` Alt+Enter works.

For `15.0.0+26228.0` taken from internal RTW branch: Alt+Enter works.

Both were VS Community Installations with a .NET Workload with the F# language support option checked.

For people using VS 2017 seeing this bug: Was RC4 your first download of 2017? If not, could you try running "`devenv /Setup` from Developer Command Prompt for VS 2017 RC? 

It's kind of a shot in the dark, but since I edited the `.pkgdef` it's possible these changes haven't flowed through to your registry and the F# editor factory isn't being used to create your editors.

@forki You mentioned you installed the master VSIX. Did it work before this?

@majocha @vasily-kirichenko Did you guys also install the master VSIX? Or were you just using vanilla installations?

**Comment by forki** [comment]
I did not test before installing the master vsix.

Am 04.03.2017 12:57 vorm. schrieb "Josh Varty" <notifications@github.com>:

**Comment by majocha** [comment]
@JoshVarty I have this issue both on master and RC4 on different machines. I'm quite sure I fully reinstalled Visual Studio 2017 a few times since December.

**Comment by majocha** [comment]
A breakpoint placed in `CreateEditorInstance` is never hit when opening F# files in editor. Looks like `FSharpEditorFactory` is being constructed (constructor does get invoked) but is never used. 
I have a suspicion it doesn't register properly for some reason. It shows up in keyboard settings (because MPF picks it up?) but is never used as `EditorFactory` for F#.

**Comment by majocha** [comment]
@JoshVarty "Save dump..." doesn't work for me. Disabled.

**Comment by Pilchie** [comment]
@majocha You'll need to invoke Debug->Break All in between.  Attaching leaves the debuggee in a running state.

**Comment by majocha** [comment]
@JoshVarty  [MiniDump](https://1drv.ms/f/s!AqAFaCPTjg4mj-9QARTbdos_DQAmXg)
Only in name. It's quite huge, unfortunately.

**Comment by JoshVarty** [comment]
I can repro this with the following steps:

1. Install RTM with F# tools
2. Observe that Alt+Enter works
3. Uninstall the F# tools with `VSIXInstaller.exe /uninstall:VisualFSharp`
4. Install latest master `.vsix` from https://ci2.dot.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part1_windows_nt/lastSuccessfulBuild/artifact/release/net40/bin/VisualFSharpOpenSource.vsix
5. Observe that Alt+Enter no longer works.

Unfortunately, I'm having a ton of trouble building the F# repo, so it's going to take me some time to figure out exactly what's going wrong here.

I suspect it's something to do with an incorrect `.pkgdef` or something.

**Comment by vasily-kirichenko** [comment]
I think it's `Editor.QuickActions` binding hide our 'send to interactive`. After removing it everything is ok. I suspect they added `Alt+Enter` for quick actions in RTW. I've no idea how to fight it.

**Comment by JoshVarty** [comment]
The reason we had to introduce the `FSharpEditorFactory` was because of the `Editor.QuickActions` command, but that's not the root cause here.

The issue is that our command bound to the `FSharpEditorFactory`. But for some reason when you uninstall the main VSIX and re-install `FSharpOpenSource.vsix` the `FSharpEditorFactory` is no longer being used to create our F# editors, the standard editor factory is. This means that our command isn't active.

It's going to take me at least another day (maybe more) to trace through the old `msenv.dll` and figure out what's going on. 

In the meantime: Does anyone know the differences between the `VisualFSharpFull.vsix` (I confirmed this is what VS installs) and `VisualFSharpOpenSource.vsix` (What we recommend you install for latest master)?

I had a brief look but nothing stood out to me. (`.pkgdef`'s were identical, `.vsixmanifest`s looked normal).

**Comment by cartermp** [comment]
@JoshVarty `VisualFSharpFull.vsix` is indeed what VS installs, and it's what we build internally for a release.  `VisualFSharpOpenSource.vsix` is for OSS developers to install locally on their machines.

**Comment by JoshVarty** [comment]
I'm still unsure *why* we need two different DLLs and what the differences between them are.

**Comment by JoshVarty** [comment]
I've made some progress.

When F# wants to open a file (eg. clicking an item in Solution Explorer) it calls [`IVsUIShellOpenDocument.OpenStandardEditor()`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsuishellopendocument.openstandardeditor.aspx). F# makes this call [here](https://github.com/Microsoft/visualfsharp/blob/e28fcd7a39c463b388a94d66a7e114580e669a6f/vsintegration/src/FSharp.ProjectSystem.Base/Project/FileDocumentManager.cs#L185) and [here](https://github.com/Microsoft/visualfsharp/blob/e28fcd7a39c463b388a94d66a7e114580e669a6f/vsintegration/src/FSharp.ProjectSystem.Base/Project/FileDocumentManager.cs#L204).

One of the parameters here is `rguidLogicalView` which takes its value from the [`LogicalView`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.logicalview.aspx) enumeration. 

- When F# passes in `Primary {00000000-0000-0000-0000-000000000000}` the F# Editor Factory is chosen.
- When F# passes in `Text {7651A703-06E5-11D1-8EBD-00A0C90F26EA}` the Source Code (Text) Editor Factory is chosen and Alt+Enter does not work.

I've confirmed that if I force the GUID to be `Primary {00000000-0000-0000-0000-000000000000}` then the F# Editor Factory is used and Alt+Enter works properly.

I believe the GUID is being chosen here: 
https://github.com/Microsoft/visualfsharp/blob/e28fcd7a39c463b388a94d66a7e114580e669a6f/vsintegration/src/FSharp.ProjectSystem.FSharp/Project.fs#L2173 and was added in #2417.

@vasily-kirichenko  What's the criteria for `IsFormSubType`?

**Comment by JoshVarty** [comment]
Looking through the shell code, there is an explicit check in `GetProvisionalViewingStatus` to see whether or not we're using an external (custom) editor factory. If so, it says preview is disabled. Presumably this is to avoid loading designers and stuff (eg. for .xaml files) while you're scrolling through the menu.

I believe that this should be achievable by looking at the physical view attributes on the editor factory to determine whether they support preview or not. For example, our [editor factory says that it does](https://github.com/Microsoft/visualfsharp/blob/e28fcd7a39c463b388a94d66a7e114580e669a6f/vsintegration/src/FSharp.ProjectSystem.Base/Project/FSharpEditorFactory.cs#L20).

I'll bring this to the shell team and see what they say.

In the meantime we have to choose:
1. Do we enable preview but disabled Alt+Enter
2. Do we disable preview to enable Alt+Enter

**Comment by dsyme** [comment]
Great, that's a relief to have this fixed :)
