### ISSUE TITLE
Send to Interactive not working in debug hive

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2491]
#### Repro steps

1) build from master
2) open VF# in debug hive
3) open any fsx file
4) mark code and send to interactive

Crashes with meesage that FSharp.Core.optdata was not found alongside

**Comment by vasily-kirichenko** [comment]
Yes, it's a known issue for about 2 months.

**Comment by cartermp** [comment]
Looks like this one wasn't tracked yet.  Thanks @forki

**Comment by forki** [comment]
Microsoft (R) F# Interactive version 4.1
    Copyright (c) Microsoft Corporation. All Rights Reserved.
    
    For help type #help;;
    
    > 
    unknown(1,1): error FS1225: File 'C:\USERS\STEFFEN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D10313E7FSHARPDEV\EXTENSIONS\MICROSOFT.VISUALFSHARPTOOLS\VISUAL F# TOOLS\42.42.42.42\FSharp.Core.optdata' not found alongside FSharp.Core. File expected in C:\USERS\STEFFEN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D10313E7FSHARPDEV\EXTENSIONS\MICROSOFT.VISUALFSHARPTOOLS\VISUAL F# TOOLS\42.42.42.42\FSharp.Core.optdata.
    
    
    unknown(1,1): error FS0229: Error opening binary file 'C:\USERS\STEFFEN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D10313E7FSHARPDEV\EXTENSIONS\MICROSOFT.VISUALFSHARPTOOLS\VISUAL F# TOOLS\42.42.42.42\FSharp.Core.dll': Eine Ausnahme vom Typ "Microsoft.FSharp.Compiler.ErrorLogger+StopProcessingExn" wurde ausgelöst.
    
    
    unknown(1,1): error FS3160: Problem reading assembly 'C:\USERS\STEFFEN\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D10313E7FSHARPDEV\EXTENSIONS\MICROSOFT.VISUALFSHARPTOOLS\VISUAL F# TOOLS\42.42.42.42\FSharp.Core.dll': Eine Ausnahme vom Typ "Microsoft.FSharp.Compiler.ErrorLogger+StopProcessingExn" wurde ausgelöst.
    
    Session termination detected. Press Enter to restart.

^^ happens as soon as you open a fsx file and try to evaluate

**Comment by vasily-kirichenko** [comment]
Duplicate https://github.com/Microsoft/visualfsharp/issues/2160

**Comment by cartermp** [comment]
Closing due to dupe, thanks @vasily-kirichenko

**Comment by forki** [comment]
wished it would be closed as fixed...
