### ISSUE TITLE
can't add account to VS 2017 community RC4

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2492]
I can't sign-in in VS2017

![image](https://cloud.githubusercontent.com/assets/87944/23332772/818c553e-fb7f-11e6-9539-21c1e298356e.png)

![image](https://cloud.githubusercontent.com/assets/87944/23332764/5acd5a74-fb7f-11e6-8fb8-97f8095aef23.png)

I've checked the contents of Microsoft.Developer.IdentityService.dll.config as documented in several places describing same issue:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <!-- JsonRPC users newtonsoft json 6, we want to make sure everyone is using the same version. -->
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral"/>
        <bindingRedirect oldVersion="4.5.0.0-8.0.0.0" newVersion="8.0.0.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <system.net>
    <!-- Use the default proxy (by default) and use the users integrated credentials if the proxy requires authentication -->
    <defaultProxy useDefaultCredentials="true" />
  </system.net>
</configuration>
```

I've tried repair as well as uninstall / install.

The only way to run VS2017 is to change my system date but this obviously has many other side effects.

**Comment by cartermp** [comment]
@smoothdeveloper Are you behind a proxy?

**Comment by smoothdeveloper** [comment]
@cartermp no, plain internet connection. This doesn't happen on another machine on same connection.

I'd like this not to be a hardfailure for community edition, I can understand the concern of having user logged in in normal circumstances, but why make it blocking in community edition?

**Comment by cartermp** [comment]
Since this is a VS Platform issue, could you log the bug [here](https://connect.microsoft.com/VisualStudio/Feedback)?  Unfortunately we can't do anything here since it's a VS Platform issue.  Closing on that note.

**Comment by smoothdeveloper** [comment]
@cartermp understood. Alas, I can't post a comment on connect, I can both sign out and sign in on that page:

![image](https://cloud.githubusercontent.com/assets/87944/23333944/187279e6-fb95-11e6-827c-69d19e45f017.png)

**Comment by cartermp** [comment]
Hmmm.  Could you try [this link instead](https://developercommunity.visualstudio.com/content/problem/7675/cant-sign-into-accounts.html?childToView=17494)?  Sorry you're having this issue...it seems like it's been hit by quite a few people though, so hopefully it's just a point-in-time problem with the RC.

**Comment by smoothdeveloper** [comment]
Still facing the issue with RTW, although I finally found a work around, in my internet explorer option, I've disabled the security stuff:

![image](https://cloud.githubusercontent.com/assets/87944/23689032/47adabe2-03b8-11e7-9ee1-45e65c584dce.png)

I'd recommend Microsoft to not couple that signin dialog to internet explorer component, instead open system browser and allow user to sign-in on a page which will give a code that can be pasted back into Visual Studio.
