### ISSUE TITLE
Find References shows duplicates

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2494]
Basically everywhere in VF# solution "Find references" shows duplicates. I assume this is because the files are shared between multiple projects. But don't knw for sure.

![image](https://cloud.githubusercontent.com/assets/57396/23341154/8037f18e-fc42-11e6-829d-f189fba2ecc9.png)

**Comment by vasily-kirichenko** [comment]
Yes, I've seen this.

**Comment by cartermp** [comment]
Have you seen this in other projects where we don't share files between projects?  I wonder how common such a thing is outside of the VF# solution.

**Comment by forki** [comment]
Pretty common in my projects.

Am 26.02.2017 19:53 schrieb "Phillip Carter" <notifications@github.com>:

**Comment by saul** [comment]
Would it be difficult to hash set the results before we pass them as results to Roslyn?

**Comment by smoothdeveloper** [comment]
@saul, @vasily-kirichenko had a similar fix #2396 for attributes, it was due to FCS giving several time the same symbol with different ItemOccurence.

**Comment by Pilchie** [comment]
I think @cyrusnajmabadi was interested in fixing the shared files duplicates in Roslyn, but I don't know at what layer.

**Comment by vasily-kirichenko** [comment]
> Would it be difficult to hash set the results before we pass them as results to Roslyn?

we do: https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Navigation/FindUsagesService.fs#L121

**Comment by vasily-kirichenko** [comment]
This one is tough. If a file belong to several projects, we (properly) get all definition locations (project + document + range), but `FSharpSymbolUse` does not contain project / assembly where a referenced symbol is defined, so we cannot match our definitions' projects with usages' projects.

@dsyme Do I understand right that it's impossible to get where a symbol defined (project / assembly)?

**Comment by dsyme** [comment]
> @dsyme Do I understand right that it's impossible to get where a symbol defined (project / assembly)?

There is the ``Assembly`` property on ``FSharpSymbol`` - but do you need more than this?  thanks

**Comment by vasily-kirichenko** [comment]
@dsyme thanks! It should work.

**Comment by cartermp** [comment]
This no longer reproduces as per the original issue:
![image](https://user-images.githubusercontent.com/6309070/45845422-eaeb1480-bcd9-11e8-983d-ab902a963258.png)

**Comment by smoothdeveloper** [comment]
I'm seeing this in VS2019, doing "Find All References" on https://github.com/fsprojects/FSharp.Data.SqlClient/blob/b78ff715285bf753e9d2c0cb31d8e811cb9fab23/src/SqlClient.DesignTime/QuotationsFactory.fs#L14

![image](https://user-images.githubusercontent.com/87944/56059845-ffe0d100-5d19-11e9-95e2-e9a3bdc3d945.png)

The issue could be related to multi target projects or usage of linked files in more than a single project.

**Comment by cartermp** [comment]
There may be an issue related to linked files + multi-TFM, but you should see results for each TFM in the window as per how the IDE handles multi-TFM today.

**Comment by cartermp** [comment]
Can you file a new issue with repro steps so we can see if anything is unexpected?

**Comment by smoothdeveloper** [comment]
I think those steps should do:

* clone https://github.com/fsprojects/FSharp.Data.SqlClient
* run build.cmd
* open SqlClient.sln then, "Find All References" : https://github.com/fsprojects/FSharp.Data.SqlClient/blob/b78ff715285bf753e9d2c0cb31d8e811cb9fab23/src/SqlClient.DesignTime/QuotationsFactory.fs#L14

It looks like the same issue as this one and I didn't want to make a duplicate, probably another edge case that needs to be addresed around where @vasily-kirichenko did initial fix.
