### ISSUE TITLE
Publish fsc for .net core runtime 1.1

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#2502]
From dotnet sdk team feedback, the .net core 1.0 is not avaiabile in all os supported by .net core sdk (for example ubuntu 16.10) ref https://github.com/dotnet/netcorecli-fsc/issues/76

In these os just .net core 1.1 is supported.

From https://github.com/dotnet/netcorecli-fsc/issues/76#issuecomment-281485936 probably the netcore 1.1 will be the reccomended runtime for all os in rtm too.

The `Microsoft.Fsharp.Compiler.netcore` is using [Microsoft.NETCore.Platforms/1.0.1](https://www.nuget.org/packages/Microsoft.NETCore.Platforms/1.0.1), but should use 1.1.0.
And be  another parallel package versions probably, because deps.

So can be added into `FSharp.Compiler.Tools` later (i'll fix choose based on installed runtimes in `FSharp.Core.Sdk` targets )

NOTE i need just fsc published, not the package itself, ref fsharp/fsharp repo packaging

**Comment by cartermp** [comment]
cc @KevinRansom - looks like we need to update the compiler package.  Personally I'm fine with .NET Core 1.1 being the recommended target for apps.  The LTS/Current split isn't quite so strong now, especially with .NET Core 2.0 on the horizon.

**Comment by dsyme** [comment]
This has been done
