### ISSUE TITLE
Hover information not shown with empty documentation

### ISSUE THREAD

**Issue by realvictorprm** [Microsoft/visualfsharp#2506]
No hover information about a variable is shown if the documentation for the var is empty.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create a new variable with empty comment / documentation above
`///`
`///`
`///`
`let somevar = 1`

2. Hover with the mouse over the var

#### Expected behavior

All information which is available should be shown, e.g. type information. 

#### Actual behavior

Nothing is shown on hover.

#### Known workarounds

Not making empty comments.

#### Related information 

* VS 2017 Community with experimental Visual F Sharp tools extension (Latest, state 28th February 2017)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2507

**Comment by realvictorprm** [comment]
As @vasily-kirichenko told with the pull request this should be solved.

**Comment by cartermp** [comment]
Tagging for tracking purposes.
