### ISSUE TITLE
Wrong open namespace suggestion in case of FS0043

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2511]
![image](https://cloud.githubusercontent.com/assets/873919/23457834/92b29afe-fe8a-11e6-9c22-115d5576d80f.png)

@cartermp it looks like it's been introduced by your last PR.

**Comment by cartermp** [comment]
Repro'd.  Good catch, thanks!

**Comment by cartermp** [comment]
My only idea is to special case FSharp.Core in the CreateEntity function in ServiceAssemblyContext.  I can try that out this evening.

**Comment by smoothdeveloper** [comment]
Is it related to `[<AutoOpen>]`?

**Comment by cartermp** [comment]
@smoothdeveloper Doesn't seem like it.  Code like this:

```fsharp
[<AutoOpen>]
module Foo =
    let (>.>) x y = x + y

[<EntryPoint>]
let main argv =
    let y = 2 >.> 12.

    0 // return an integer exit code
```
won't trigger a lightbulb.  In @vasily-kirichenko's repro, FSharp.Core is actually pulled up from `tryFindInsertionContext`.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2515
