### ISSUE TITLE
Install path of Windows F# SDK implies framework 4.0

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2513]
I was looking at files / assemblies in `C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0`

It seems assemblies are compiled with framework 4.5:

> [assembly: TargetFramework(".NETFramework,Version=v4.5", FrameworkDisplayName = ".NET Framework 4.5")]

Should the SDK folder indicate that?

**Comment by cartermp** [comment]
I think this is because it's guaranteed to work .NET Framework 4.0 or higher, but @KevinRansom could provide more info/prove that I'm wrong here.

**Comment by dsyme** [comment]
@cartermp That's correct, the ``4.0`` in this path is basically meaningless these days, just one of those things
