### ISSUE TITLE
MSDN F# documentation missing?!?

### ISSUE THREAD

**Issue by rmunn** [Microsoft/visualfsharp#2519]
This may or may not be the right repository to report this; if it's not, please let me know where this report should go.

Suddenly, none of the MSDN links to F# documentation seem to work. If I go to https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/lists the article is there, but its link to the List module at MSDN (https://msdn.microsoft.com/library/a2264ba3-2d45-40dd-9040-4f7aa2ad9788, which redirects to https://msdn.microsoft.com/visualfsharpdocs/conceptual/collections.list-module-%5bfsharp%5d) gives a 404. Same applies for every other MSDN F# link I've tried so far.

**Comment by cartermp** [comment]
Looks like something went down - I know it was up, since I was looking at the `NativePtr` page just this afternoon.  I'll reach out to see what's up.

**Comment by cartermp** [comment]
Bug is filed in the internal system and it will be addressed.  I'll keep this issue open until it's back up again.

**Comment by rmunn** [comment]
Still down, at least for me, as of 17:20 GMT on Friday 2017-03-03.

**Comment by cartermp** [comment]
@rmunn What about now?  Just got someone to republish.  It may take a little bit of time.

**Comment by rmunn** [comment]
Looks like everything's back up now; closing the issue since it's been resolved.
