### ISSUE TITLE
Type check in scripts ignores #r placement

### ISSUE THREAD

**Issue by majocha** [Microsoft/visualfsharp#2522]
Not very common case, I know, but IDE should show some error here:
![przechwytywanie](https://cloud.githubusercontent.com/assets/1760221/23551190/6299a1d2-0015-11e7-97da-86e5dbd87aee.PNG)

**Comment by vasily-kirichenko** [comment]
It's a feature ;)

**Comment by dsyme** [comment]
Yes, this is by-design.  The language service analyzes scripts with a whole-file view, as if they are executed all-at-once.  It's just how it is, we don't attempt to scope the referenced assemblies, it would just be really hard to do that.
