### ISSUE TITLE
"Go to declaration" on public methods/fields should jump to the signature file

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2527]
Right-clicking on a type, function or value that is public on a module/namespace and selecting "Go to declaration" should jump to the proper line in the signature file.

I also think that clicking "Go to definition" should always jump to the definition in the .fs file. It seems in 2015 half of the time it jumps to the signature file (this is quite painful). This has been fixed in 2017 already.

#### Repro steps

Feature request, not a bug

#### Expected behavior

Clicking "Go to declaration" should jump to the signature file.

#### Actual behavior

Does nothing.

#### Known workarounds

Open the fsi file manually.

#### Related information 

VS 2017 master.

**Comment by vasily-kirichenko** [comment]
In 2017 we've fixed the annoying previous behavior when F12 jumped to fsi file.

**Comment by saul** [comment]
Thank god for that - thanks. In which case, ignore that part of my ticket!

**Comment by cloudRoutine** [comment]
I've been thinking it'd be useful to have the goto functionality split up as -

- **GotoSignature** : 
jumps to the signature file, especially useful when the function or type is documented in the `.fsi`

- **GotoDeclaration** : 
jumps to the point where the identifier was bound/created

- **GotoDefinition** : 
jumps to the definition of the identifier's type or pulls up a metadata signature view like in VFPT or goes to the corresponding instantiation of an interface (no more writing out inferred types just for the jump!)

- **GotoImplementation** :
jumps from an abstract class to the classes inherit/derived from it, or jumps from the definition of an interface to its instantiations

**Comment by majocha** [comment]
I don't have "go to declaration"? Never saw it with F# files. Only "definition" and "implementation". F12 still sometimes takes me to .fsi which is quite annoying.

**Comment by cloudRoutine** [comment]
@majocha they currently don't exist. These would be new features/services to implement

**Comment by saul** [comment]
@cloudRoutine I'm not sure I agree on the name of Go to definition. I think more suitable names would be:

* **GotoDeclaration** (jump to the place where an identified is declared - fsi files come before fs files)
jumps to the signature file, especially useful when the function or type is documented in the .fsi

* **GotoDeclaration**
jumps to the point where the identifier was bound/created

* **GotoTypeDefinition** (jump to where the type is defined)
jumps to the definition of the identifier's type or pulls up a metadata signature view like in VFPT or goes to the corresponding instantiation of an interface (no more writing out inferred types just for the jump!)

* **GotoImplementation**
jumps from an abstract class to the classes inherit/derived from it, or jumps from the definition of an interface to its instantiations

**Comment by saul** [comment]
This is now essentially fixed - just hit F12 again to go to the signature file 👍
