### ISSUE TITLE
Fix Jenkins builds for OSX/macOS

### ISSUE THREAD

**Issue by jack-pappas** [Microsoft/visualfsharp#2533]
The Jenkins CI builds for OSX / macOS are still broken. After Don's changes in #2442, I have no problems building ``master`` on macOS + Mono 4.6.x -- I can run ``./build.sh net40`` or ``./build.sh net40 ci`` with no problems. However, @KevinRansom enabled the OSX CI builds again in e44ee28, found they still didn't work, and disabled them again in 490b9e1.

There was some additional discussion about this previously in #2134. @mmitche said the Jenkins images have Mono installed now, so I can't think of what could be causing the OSX builds to fail there. @KevinRansom do you remember why they failed? I looked in Jenkins for a log from the failed build, but I couldn't find anything (the mac builds don't even appear in the list of build configurations).

**Comment by mmitche** [comment]
@jack-pappas We can take a look at one of these machines to verify that mono is installed correctly.

**Comment by jack-pappas** [comment]
@mmitche Have you had a chance to look at these machines?

**Comment by cartermp** [comment]
I think this issue is likely to be out of date. We've since made sweeping changes to our infrastructure and CI to the point where this may not be relevant.
