### ISSUE TITLE
Slow initial IDE performance, when Loading FSharp.Core project.

### ISSUE THREAD

**Issue by OnurGumus** [Microsoft/visualfsharp#2538]
When I open a project like FSharp.Core in VisualFSharp with VS 2017 RC3, the CPU peaks quite for a while. Here are the perfview traces:

![screenshot 13](https://cloud.githubusercontent.com/assets/4114592/23613867/b5016dbc-0289-11e7-8e65-66e468ea50be.png)

![screenshot 14](https://cloud.githubusercontent.com/assets/4114592/23613868/b68c901c-0289-11e7-88df-1d86093ad365.png)

Perhaps for these bottlenecks, using BCL Imperative collections should be considered instead of the FSharp immutable ones.

**Comment by vasily-kirichenko** [comment]
It's typechecking. It's OK.

**Comment by OnurGumus** [comment]
@vasily-kirichenko but can't this type checking be done more efficiently?

**Comment by vasily-kirichenko** [comment]
No.

**Comment by KevinRansom** [comment]
@OnurGumus ... 
perhaps ... however ... no one has come up with a more performant approach so far.  And it has been slooooow for a very long time.

**Comment by cartermp** [comment]
@OnurGumus While I'm sure typechecking could be made more efficient if someone were to look at it in-depth for a very long time, it's a very significant effort.

**Comment by OnurGumus** [comment]
Maybe I am naïve but , isn't using imperative collections will help immediately? Sure you guys thought about it, just curious why not?

**Comment by vasily-kirichenko** [comment]
@OnurGumus In short, to obtain info to make all the features work (syntax highlighting, find usages, rename, etc, etc.) we need to compile the whole project. Measure how much it takes to compile your project. That should match that initial pause you are talking about.

**Comment by cartermp** [comment]
IIRC @vasily-kirichenko did profile using `Dictionary<'T, 'U>` in some language service code and didn't see any performance gains.  That doesn't mean using different collection types in typechecking *wouldn't* be an improvement, but this requires detailed profiling to identify why behavior is the way it is.  Surely there are some heavy data structures which could be trimmed as well, but as with collection types this would have to be profiled effectively.  This is before any of the significant cost involved of swapping out an immutable structure with a mutable one, which could violate any assumptions we have about immutability in the codebase.  In short, not a simple task.

**Comment by vasily-kirichenko** [comment]
The things are not that simple. We cannot replace Map with Dictionary in name resolution environment, for example because it means cloning (copying) _a lot_ of dictionaries (currently all maps share common tree parts, (very) naturally).

**Comment by dsyme** [comment]
@vasily-kirichenko It's certainly true that we've always done the background type checking of projects

However I don't understand why ``IsRelativeNameResolvable`` would be on the background checking path - it's not part of the normal process of type checking, and seems more related to some new IDE feature such as finding suggestions for opening namespaces?  So it could be that this perf view trace indicates an unoptimized path in the language service implementation of a new IDE feature

I just want to check that we're not labeling CPU usage as "doing type checking" when we're really doing something new?

thanks
don

**Comment by vasily-kirichenko** [comment]
@dsyme it must be (now disabled) Simplify name analyzer.

**Comment by dsyme** [comment]
@vasily-kirichenko Got it, thanks

**Comment by vasily-kirichenko** [comment]
@dsyme or it may be Roslyn's all files background analyzing, which we turned off in master. It took ~20 minutes one core 100% loaded after a singe change on VFT solution.

**Comment by vasily-kirichenko** [comment]
...and RTW is released with this enabled...

**Comment by dsyme** [comment]
> @dsyme or it may be Roslyn's all files background analyzing, which we turned off in master. It took ~20 minutes one core 100% loaded after a singe change on VFT solution.

I think the presence of ``IsRelativeNameResolvable`` in the trace indicates it's an IDE feature

**Comment by vasily-kirichenko** [comment]
Ah, yes, sorry. Then it's Simplify name analyzer for sure.

**Comment by OnurGumus** [comment]
Just in case I am adding the traces and preview itself as a zip file.
https://1drv.ms/u/s!AsiXNzy93_kOnY1KiLsoVT5BukxaMA

**Comment by dsyme** [comment]
Closing since the "Simplify name analyzer" is disabled by default, and we believe this is what's responsible
