### ISSUE TITLE
Vs2017 fails to open any F# projects from latest master VSIX from CI

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [Microsoft/visualfsharp#2542]
#### Repro steps

Provide the steps required to reproduce the problem

1. Instal VS 2017
2. Install F# from the link https://ci2.dot.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part1_windows_nt_prtest/lastSuccessfulBuild/artifact/release/net40/bin/VisualFSharpOpenSource.vsix
3. File -> New Project -> F# -> .Net Framework 4.5.2 -> Console Application
#### Expected behavior

FSharp creates a project/solution, and it opens

#### Actual behavior

Warning dialog, The 'FSharpProjectPackage' did not load correctly
in ActivityLog.xml:

> CreateInstance failed for package [FSharpProjectPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;file:///C:\Users\User\AppData\Local\Microsoft\VisualStudio\15.0_539ba969\Extensions\fqq25zot.lxo\FSharp.ProjectSystem.FSharp.dll&apos; or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)&#x000D;&#x000A;System.IO.FileLoadException: Could not load file or assembly &apos;file:///C:\Users\User\AppData\Local\Microsoft\VisualStudio\15.0_539ba969\Extensions\fqq25zot.lxo\FSharp.ProjectSystem.FSharp.dll&apos; or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)&#x000D;&#x000A;File name: &apos;file:///C:\Users\User\AppData\Local\Microsoft\VisualStudio\15.0_539ba969\Extensions\fqq25zot.lxo\FSharp.ProjectSystem.FSharp.dll&apos; ---&gt; System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)&#x000D;&#x000A;The Zone of the assembly that failed was:&#x000D;&#x000A;MyComputer&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)&#x000D;&#x000A;The Zone of the assembly that failed was:&#x000D;&#x000A;MyComputer

#### Known workarounds

no known workaround, besides opening up VS 2015

#### Related information 

* Windows10
* ?? Branch of what?
* .Net 4.5.2
* Editing Tools (e.g. Visual Studio Version)
* unable to open/create anything F# on VS 2017.
* tell it to try to compile an existing solution from VS 2015 and it seems to work as expected even with the projects unloaded and unable to load

**Comment by vasily-kirichenko** [comment]
@cartermp I don't think VisualFSharpOpenSource.vsix has ever worked without building it locally, because after installing it uses a compiler (at least) located in <vft repository root>\release\net40\bin>.

**Comment by ImaginaryDevelopment** [comment]
I guess this tweet isn't accurate then or I'm using it wrong: https://twitter.com/sergey_tihon/status/839179852192366592
uninstalled F# via extension & updates. which also removed F# language support from VS2017. reinstalled from the vs2017 installer, still the same error continues.

**Comment by 0x53A** [comment]
you probably need to disable strong name verification, ref https://github.com/Microsoft/visualfsharp/wiki/Using-CI-Builds

> To install the Visual F# IDE Tools from Jenkins, first run sn.exe (Strong Name Tool) from the Visual Studio developer command prompt to turn off strong name checking on your machine:
> 
> sn -Vr *,*

**Comment by ImaginaryDevelopment** [comment]
I need to disable that even if I uninstalled, and let VS2017 put back in
the RTM version it came with?

**Comment by cartermp** [comment]
@ImaginaryDevelopment Just to confirm that @0x53A is correct here.  You need to run the Strong Name Hijack tool to use CI builds.

We're very close to having nightly signed VSIXs available so that the strongname hijack isn't necessary.

**Comment by ImaginaryDevelopment** [comment]
@cartermp  does this apply to a fresh vs2017 installation? I uninstalled the CI build

**Comment by 0x53A** [comment]
@ImaginaryDevelopment no, my comment was regarding the initial post. That is relatively clear from the error message: 

> Could not load file or assembly  [...] Strong name validation failed.

If it still doesn't work after reinstall by the VS setup, then that is a different (and in my opinion critical) bug.

**Comment by cartermp** [comment]
@ImaginaryDevelopment No, there's no need to run that tool to use what ships in VS 2017.

**Comment by ImaginaryDevelopment** [comment]
ok, I have Microsoft.VisualFSharpTools Version 42.42.42.42 installed is that the right shipped with VS2017 version? it still says 

> CreateInstance failed for package [FSharpProjectPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;file:///C:\Users\User\AppData\Local\Microsoft\VisualStudio\15.0_539ba969\Extensions\fqq25zot.lxo\FSharp.ProjectSystem.FSharp.dll&apos; or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)&#x000D;&#x000A;System.IO.FileLoadException: Could not load file or assembly &apos;file:///C:\Users\User\AppData\Local\Microsoft\VisualStudio\15.0_539ba969\Extensions\fqq25zot.lxo\FSharp.ProjectSystem.FSharp.dll&apos; or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)&#x000D;&#x000A;File name: &apos;file:///C:\Users\User\AppData\Local\Microsoft\VisualStudio\15.0_539ba969\Extensions\fqq25zot.lxo\FSharp.ProjectSystem.FSharp.dll&apos; ---&gt; System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)&#x000D;&#x000A;The Zone of the assembly that failed was:&#x000D;&#x000A;MyComputer&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)&#x000D;&#x000A;The Zone of the assembly that failed was:&#x000D;&#x000A;MyComputer

**Comment by cartermp** [comment]
@ImaginaryDevelopment No, it looks like the VSIX you still have is the latest built from master.  If you uninstall and then reinstall F# from the Visual Studio Installer it should give you the signed bits shipped with VS 2017.

**Comment by ImaginaryDevelopment** [comment]
uninstall/reinstall via the VS installer, and it still says `42.42.42.42`

**Comment by majocha** [comment]
Try `vsixinstaller /u:VisualFSharp`

**Comment by ImaginaryDevelopment** [comment]
deleted the folder that had the F# stuff in it from `C:\Users\User\AppData\Local\Microsoft\VisualStudio\15.0_539ba969\Extensions\fqq25zot.lxo\`
and now running a repair.

**Comment by rmTizi** [comment]
Did the shipped version worked for anyone here ? I had to reinstall the CI version for the tools to even load.

**Comment by cartermp** [comment]
@rmTizi Just to confirm, are you saying that F# projects would not load with VS 2017 RTM and the "F# language support" installed?

**Comment by ImaginaryDevelopment** [comment]
I must have followed the tweet's instructions first.
after repair, then telling the vs installer to install F#, a new project works, and my legacy projects load, trying to see next what's going on with building, might not be related.

**Comment by rmTizi** [comment]
@cartermp I had the "F# support" installed, I managed to create a new project (didn't even tried to load my existing project since I use core), but no tooling feature was available (syntax coloring, intellisense...) overall it looked like a similar issue to this: https://twitter.com/sergey_tihon/status/839179852192366592 so I reinstalled the CI build and then the tooling worked.

**Comment by majocha** [comment]
For me VS updated to RTM with the master vsix intact and working.
I just tested and it has to be uninstalled from command prompt. Doing so, I'm left with RTM F# still installed and working fine (but no so well as master).

**Comment by cartermp** [comment]
@rmTizi Did you install "F# language support" individually, or did you install it as a part of a .NET Workload (e.g., .NET Desktop Development, ASP.NET and Web Development)?

Looking to diagnose the issue here.  If you installed it individually, then I think I know what's wrong.

**Comment by rmTizi** [comment]
@cartermp In the end I used the Desktop workload with a few individual features, but I _did_ spent a few minutes on the setup screen checking and unchecking various workloads and features to see what was linked with what, so maybe that messed up something indeed. Is there any log file I could provide you to help ?

**Comment by ImaginaryDevelopment** [comment]
so building in vs2017, or even opening in vs2017, it loads up quite a few errors in the error list window. but building succeeds, and I haven't seen any issues with intellisense in the places there aren't errors showing in the window.

**Comment by ImaginaryDevelopment** [comment]
is it time for me to close my issue? or stay open for others that are still commenting?

**Comment by cartermp** [comment]
@rmTizi Hmmm, you definitely shouldn't have had those issues, even if you spent time customizing the install.  The bits the .NET Desktop workload pulls down by default are sufficient for F#.  I'm a bit stumped as to why you've seen this.  If you have the time, could you try installing it on another machine?  We haven't come across this issue before.

@ImaginaryDevelopment It's okay to leave it open.  Since this link is live on Twitter, other people with similar issues have a place to go.  I'll close it after there's inactivity for a while.

**Comment by ImaginaryDevelopment** [comment]
@cartermp what should I do about the errors that come up and just sit in the error window, even though everything builds and runs?

**Comment by cartermp** [comment]
@ImaginaryDevelopment If you could create another issue, preferably with screenshots, that would be super helpful.  We can track what's going on in that issue.

**Comment by dsyme** [comment]
I'll close this now as it's been inactive for a while and there isn't a specific repro
