### ISSUE TITLE
Cannot uninstall VisualFSharp from command line after VS2017 Enterprise Install

### ISSUE THREAD

**Issue by jonschoning** [Microsoft/visualfsharp#2543]
Cannot uninstall VisualFSharp from command line after VS2017 Enterprise Install

* Operating system - Windows 7 Enterprise

#### Repro steps

Provide the steps required to reproduce the problem

1. Open Visual Studio 2017 Tools Command Prompt (administrator)

2. Execute `VSIXInstaller.exe /uninstall:VisualFSharp`

#### Expected behavior

uninstall:VisualFSharp uninstalls

#### Actual behavior

Uninstallation Falied

VSIX Log: https://gist.github.com/jonschoning/cab9fae6a3c7407e1c2850cbf6b45ae1

**Comment by AviAvni** [comment]
I have the same problem

**Comment by majocha** [comment]
There is no need to uninstall if you are trying to install the newer build. It will install on top of RTM without problems. Just don't forget about the strong name hijack, because it's not signed.

**Comment by cartermp** [comment]
The VSIXInstaller issue is, unfortunately, not something we control.  It's a VS Setup engine thing, I think.

**Comment by majocha** [comment]
I think we need clear instructions how to install latest build on top of RTM. Looks like a lot of people try.

**Comment by cartermp** [comment]
Yeah, unfortunately we're chasing down one last bug in getting a signed VSIX installed.  With that in place, it's pretty simple:

1. Uninstall F# from VS installer
2. Uninstall F# 4.1 SDK MSI
3. Reinstall F# from VS Installer

And then you're back at whatever shipped in that version of VS 2017.  We'll post another blog post update, and have updated instructions on how to get the signed nightly builds once we work out the issue we're dealing with.

**Comment by jonschoning** [comment]
https://blogs.msdn.microsoft.com/dotnet/2017/03/14/announcing-nightly-releases-for-the-visual-f-tools/ appears to solve this
