### ISSUE TITLE
Cannot uninstall VF# VSIX via VSIXInstaller command line for VS2017 RTM

### ISSUE THREAD

**Issue by bentayloruk** [Microsoft/visualfsharp#2549]
I just tried to uninstall the Visual F# VSIX for VS2017 RTM, as per the [instructions here](https://github.com/Microsoft/visualfsharp/wiki/Using-CI-Builds) and it fails with `System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.`

This seems similar to #2374, #2152 and #1999.  

I tried as admin and non-admin, with the following command line:

`"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VSIXInstaller.exe" /uninstall:VisualFSharp`

Tail of the error log:

```
08/03/2017 13:31:59 - The following target products have been selected...
08/03/2017 13:31:59 - 	Visual Studio Professional 2017
08/03/2017 13:31:59 - 
08/03/2017 13:32:00 - Uninstalling 'Visual F# Tools', version 15.4.1.17022502.
08/03/2017 13:32:04 - System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.InstallProgressPage.UninstallVsix(String vsixId, SupportedVSSKU targetSku, IProgress`1 progress)
```

<details>
<summary>Full error log</summary>
08/03/2017 13:31:58 - Microsoft VSIX Installer
08/03/2017 13:31:58 - -------------------------------------------
08/03/2017 13:31:58 - vsixinstaller.exe version:
08/03/2017 13:31:58 - 15.0.26228.0 built by: D15REL
08/03/2017 13:31:58 - -------------------------------------------
08/03/2017 13:31:58 - Command line parameters:
08/03/2017 13:31:58 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VSIXInstaller.exe,/uninstall:VisualFSharp
08/03/2017 13:31:58 - -------------------------------------------
08/03/2017 13:31:58 - Microsoft VSIX Installer
08/03/2017 13:31:58 - -------------------------------------------
08/03/2017 13:31:58 - PKGDEF Information: Looking for master PkgDef file, Path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.PkgDef

08/03/2017 13:31:58 - PKGDEF Information: Creating PkgDefCacheNonVolatile
08/03/2017 13:31:58 - PKGDEF Information: Double-checking master pkgdef file
08/03/2017 13:31:58 - PKGDEF Information: PkgDefManagement initialized
08/03/2017 13:31:58 - PKGDEF Information: RootFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\

08/03/2017 13:31:58 - PKGDEF Information: ShellFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\

08/03/2017 13:31:58 - PKGDEF Information: PkgDefSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.admin.pkgdef

08/03/2017 13:31:58 - PKGDEF Information: ImageManifestSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions;C:\Users\Ben Taylor\AppData\Local\Microsoft\VisualStudio\14.0\Extensions

08/03/2017 13:31:58 - PKGDEF Information: ApplicationExtensionsFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions

08/03/2017 13:31:58 - PKGDEF Information: "ZeroImpact" = dword:0, "MergeRegistry" = dword:1
08/03/2017 13:31:58 - PKGDEF Information: User extensions enabled by setting, Path: HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0\ExtensionManager\EnableAdminExtensions

08/03/2017 13:31:58 - PKGDEF Information: PkgDefCache flags, PKGDEF: 5001
08/03/2017 13:31:58 - PKGDEF Information: PkgDefManagement startup complete
08/03/2017 13:31:59 - PKGDEF Information: Looking for master PkgDef file, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\master.pkgdef

08/03/2017 13:31:59 - PKGDEF Information: Creating PkgDefCacheNonVolatile
08/03/2017 13:31:59 - PKGDEF Information: Double-checking master pkgdef file
08/03/2017 13:31:59 - PKGDEF Information: PkgDefManagement initialized
08/03/2017 13:31:59 - PKGDEF Information: RootFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\

08/03/2017 13:31:59 - PKGDEF Information: ShellFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\

08/03/2017 13:31:59 - PKGDEF Information: PkgDefSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.admin.pkgdef

08/03/2017 13:31:59 - PKGDEF Information: ImageManifestSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions;C:\Users\Ben Taylor\AppData\Local\Microsoft\VisualStudio\15.0_9e74e205\Extensions

08/03/2017 13:31:59 - PKGDEF Information: ApplicationExtensionsFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions

08/03/2017 13:31:59 - PKGDEF Information: "ZeroImpact" = dword:0, "MergeRegistry" = dword:3
08/03/2017 13:31:59 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
08/03/2017 13:31:59 - PKGDEF Information: User extensions enabled by setting, Path: HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\15.0_9e74e205\ExtensionManager\EnableAdminExtensions

08/03/2017 13:31:59 - PKGDEF Information: PkgDefCache flags, PKGDEF: 7001
08/03/2017 13:31:59 - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
08/03/2017 13:31:59 - PKGDEF Information: PkgDefManagement startup complete
08/03/2017 13:31:59 - Initializing Uninstall...
08/03/2017 13:31:59 - Extension Details...
08/03/2017 13:31:59 - 	Identifier         : VisualFSharp
08/03/2017 13:31:59 - 	Name               : Visual F# Tools
08/03/2017 13:31:59 - 	Author             : Microsoft.VisualFSharpTools
08/03/2017 13:31:59 - 	Version            : 15.4.1.17022502
08/03/2017 13:31:59 - 	Description        : Deploy Visual F# Tools templates to Visual Studio
08/03/2017 13:31:59 - 	Locale             : en-US
08/03/2017 13:31:59 - 	MoreInfoURL        : 
08/03/2017 13:31:59 - 	InstalledByMSI     : False
08/03/2017 13:31:59 - 	SupportedFrameworkVersionRange : [4.6,)
08/03/2017 13:31:59 - 
08/03/2017 13:31:59 - 	Supported Products : 
08/03/2017 13:31:59 - 		Microsoft.VisualStudio.Pro
08/03/2017 13:31:59 - 			Version : [15.0]
08/03/2017 13:31:59 - 
08/03/2017 13:31:59 - 	References         : 
08/03/2017 13:31:59 - 	Prerequisites      : 
08/03/2017 13:31:59 - 		-------------------------------------------------------
08/03/2017 13:31:59 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
08/03/2017 13:31:59 - 		Name         : Visual Studio core editor
08/03/2017 13:31:59 - 		Version      : [15.0,16.0)
08/03/2017 13:31:59 - 
08/03/2017 13:31:59 - 
08/03/2017 13:31:59 - The following target products have been selected...
08/03/2017 13:31:59 - 	Visual Studio Professional 2017
08/03/2017 13:31:59 - 
08/03/2017 13:32:00 - Uninstalling 'Visual F# Tools', version 15.4.1.17022502.
08/03/2017 13:32:04 - System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.InstallProgressPage.UninstallVsix(String vsixId, SupportedVSSKU targetSku, IProgress`1 progress)

</details>

**Comment by vasily-kirichenko** [comment]
I think you should not uninstall the stock VFT. Just install the OSS one above it.

**Comment by bentayloruk** [comment]
OK.  Does the open source version sit alongside the VFT?  I must admit, I'm a bit confused.  Is it me being a bit dense?  The instructions don't seem to make a distinction.

**Comment by KevinRansom** [comment]
Visual F# is a component that ships in the box, vs does not allow the vsixinstaller /u or the command to uninstall this type of command at this time.  

To uninstall F# use the tools/Extensions and updates menu or the VS setup program found in 
:  Program Files (x86)\Microsoft Visual Studio\Installer

vsixinstaller can be used to install and uninstall the vsix built from the OSS codebase.

**Comment by bentayloruk** [comment]
Thanks @KevinRansom and @vasily-kirichenko, that makes sense.

Do you think it be helpful if I updated the wiki instructions to make this clear?  It makes total sense now I see the difference, but could be confusing for other newbies.  I'm assuming you can't/shouldn't have them both installed at the same time?

**Comment by KevinRansom** [comment]
Yes ... that would be great.

**Comment by bentayloruk** [comment]
OK, will do.
