### ISSUE TITLE
VS2017 / no F# project template, although F# language support is installed

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2551]
#### Repro steps

* install VS2017 RTW
* check those options in screenshot bellow
* on first launch, choose c++ preferences (I have suspicion this creates problem with project template hierarchy)
* file / new / project...

![image](https://cloud.githubusercontent.com/assets/87944/23709981/7621821a-041b-11e7-9af9-5c6b0b19111b.png)

#### Expected behavior

There is a Visual F# section somewhere in the template hierarchy

#### Actual behavior

I don't see Visual F# project template anywhere:

![image](https://cloud.githubusercontent.com/assets/87944/23710166/0c2aee54-041c-11e7-9a80-167831e313a7.png)

#### Known workarounds

create project some other way

#### Related information 

* Win7 64 pro
* I'm updating from RC4 where I had opensource VF# tools installed (don't think it is relevant)

**Comment by KevinRansom** [comment]
1.  I was able to successfully select c++ settings.

2.  From the command line can you try 
````
vsixinstaller /uninstall:VisualFSharp
````
to uninstall the VisualFSharpOSS package, just in case there is some interaction.  You will be able to reinstall the OSS VSix again after.

**Comment by smoothdeveloper** [comment]
@KevinRansom I've done a full uninstall / reinstall (i've added back open source VSIX before retesting) and now I see the proper templates:

![image](https://cloud.githubusercontent.com/assets/87944/23758319/b33b5184-04e9-11e7-828b-a205626c58ba.png)

Depending if you could reproduce it or else, please let me know if we want to close this.

**Comment by cartermp** [comment]
I reinstalled yesterday and didn't run into this issue.  Closing for now - hopefully it was just some one-off fluke.

**Comment by stgaup** [comment]
Hi, I have the same problem. Today when I was going to create a new F# Library project, the templates were nowhere to be found. I did install WebSharper, but I am not sure if that was the reason. When I run 
`vsixinstaller /uninstall:VisualFSharp`
I get an error and in the log I find this:
```
29.06.2017 10.17.30 - Uninstalling 'Visual F# Tools', version 15.4.1.17051001.
29.06.2017 10.17.38 - System.InvalidOperationException: The VSIX's catalog does not include a 'Component' which is required for install/uninstall.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineUnInstall(IInstalledExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.UninstallInternal(IInstalledExtension extension, Boolean forceDelete, Version targetedVSVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.Uninstall(IInstalledExtension extension, Version targetedVSVersion)
   at VSIXInstaller.InstallProgressPage.UninstallVsix(String vsixId, SupportedVSSKU targetSku, IProgress`1 progress)
```

**Comment by stgaup** [comment]
Running...

> vsixinstaller.exe "C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.FSharp.VSIX.Full.Core,version=15.4.1.17051001\VisualFSharpFull.vsix"

Just says it's already installed.

**Comment by giuliohome** [comment]
No F# templates on Visual Studio 2017 even if I selected F# support. I also tried to install WebSharper 4 vsix (don't know if it is related).
Shoild I open another issue or this is fine here?
Version 15.5.2 Community

**Comment by cartermp** [comment]
@giuliohome Which F# templates are you looking for? There are two components starting in 15.5:

* F# language support
* F# desktop support

The first one brings the F# compiler SDK, .NET Core and .NET Standard templates, F# Interactive, etc. The second one brings the same .NET Framework-based templates which have always been there. Do you have both selected?

**Comment by giuliohome** [comment]
@cartermp thank you.
I'm not sure about F# desktop support. 
Maybe I missed it. I will check within tomorrow and let you know. 
Thanks again.

**Comment by giuliohome** [comment]
I've added "F# desktop support" but my problem remains. I must have done something wrong which corrupted the templates. I will run the repair installation now. Thanks for your support in the meantime.

**Comment by giuliohome** [comment]
I confirm that everything is ok after the installation repair (my fault, sorry).
