### ISSUE TITLE
Settings reset in VS2017 break colors in Dark theme

### ISSUE THREAD

**Issue by sergey-tihon** [Microsoft/visualfsharp#2555]
In `VS2017` all `functions`, `members` and `properties` are colored in `black` on `dark` background by default.

<img width="477" alt="screen shot 2017-03-08 at 10 19 58 pm" src="https://cloud.githubusercontent.com/assets/1197905/23719700/7603dbac-044d-11e7-894f-75effca18c95.png">

I have this issue since `VFPT` and I have tried to reset all VS settings to default values for all `collection of settings` (Strange that we do not have F# settings collection yet.)
<img width="553" alt="screen shot 2017-03-08 at 10 18 19 pm" src="https://cloud.githubusercontent.com/assets/1197905/23719623/2d1f9af2-044d-11e7-9d86-fa9c91edb1c7.png">

#### Expected behavior

F# should look nice and readable on all 3 themes supported by VS

#### Actual behavior

Default colors are very strange

<img width="628" alt="screen shot 2017-03-08 at 10 08 28 pm" src="https://cloud.githubusercontent.com/assets/1197905/23719334/03df0eee-044c-11e7-92f3-d6511980584c.png">
<img width="627" alt="screen shot 2017-03-08 at 10 08 41 pm" src="https://cloud.githubusercontent.com/assets/1197905/23719351/12466914-044c-11e7-8854-927e3ba8ce3e.png">

#### Known workarounds

Manually modify colors for `F# Functions / Methods` and `F# Properties` for `Text editor`.

#### Related information 

* Operating system - Win 10 Enterprise 
* Branch - [Manually installed VisualF# Tools](https://twitter.com/k_cieslak/status/839176318403104769)
* Editing Tools (e.g. Visual Studio Version) - VS2017

//cc @vasily-kirichenko Could you please change theme to the `Dark` and share the colors that you see in settings for `F# Functions` & `F# Properties`? Thx

**Comment by saul** [comment]
I believe this was been fixed in #2450. But considering you're on master, that's a bummer.

cc @majocha to take a look at this.

**Comment by sergey-tihon** [comment]
I did repeat all steps from [this manual](https://github.com/Microsoft/visualfsharp/wiki/Using-CI-Builds) only again just now (with current master) and it seems that it works for me now...

Let's assume it's magic

**Comment by sergey-tihon** [comment]
Just for history:

`Visual F# Tools` reinstall helped me after `VS` settings reset.
Maybe `Visual F# Tools` calculate colors on 1st run? That's why settings reset did not help me...

**Comment by majocha** [comment]
@sergey-tihon you are right there's a bug right now. Resetting the colors will break the dark mode :( I'll try to think about a solution.

**Comment by sergey-tihon** [comment]
Thank you @majocha, so I reopen this issue to keep tracking.

**Comment by majocha** [comment]
I must find a consistent repro, though. I've seen it once and now it's gone.

**Comment by sergey-tihon** [comment]
@majocha Do you know any reason why we do not have `Visual F#` settings collections with all F# related setting the hat we can `import`/`export`/`reset` independently? Like `C#`, `VB`, `C++` & `JS` do?

<img width="553" alt="screen shot 2017-03-08 at 10 18 19 pm" src="https://cloud.githubusercontent.com/assets/1197905/23719623/2d1f9af2-044d-11e7-9d86-fa9c91edb1c7.png">

**Comment by majocha** [comment]
@sergey-tihon I suspect it's because as for now there are no F# option pages apart from F# Interactive which is done in an _interesting_ way. I tried to make an option page leveraging Roslyn but it seems we're blocked by some old dependencies that need to be updated first to make it work.

**Comment by majocha** [comment]
I think I got a repro for the color problem. I'll think how to deal with it best.
Looks like something changed in the Fonts and Colors handling in Visual Studio RTM :(

**Comment by majocha** [comment]
OK, simple repro for the record:
1. Install master
2. Set fonts & colors to default
3. Change theme from light to dark (or from dark to light)

The reason for this bug is that Visual Studio stores formats registered with `EditorFormatDefinition` and uses this stored versions. After that it does instantiate FormatDefinitions at each run but doesn't use the styles set in their constructors anymore. There is a simple fix for this that I will post soon.
