### ISSUE TITLE
Unable to build VisualFSharp repository

### ISSUE THREAD

**Issue by JoshVarty** [Microsoft/visualfsharp#2556]
#### Repro steps

1. Install Visual Studio with (.NET Workload + F# Tools) and (Visual Studio Extensibility Workload)
2. Clone the VisualFSharp repository (master)
3. `build.cmd` succeeds
4. `build.cmd vs` and `msbuild vsintegration\Vsix\VisualFSharpOpenSource` fail with:

```
"C:\git\visualfsharp\build-everything.proj" (default target) (1) ->
"C:\git\visualfsharp\vsintegration\fsharp-vsintegration-src-build.proj" (Build target) (10) ->
"C:\git\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj" (Build target) (17) ->
(CoreCompile target) ->
  FSC : error FS0193: Could not find file 'C:\git\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\obj\release\net40\ProjectResources.rc.res'. [C:\git\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\ProjectSystem.fsproj]
```
5.  Building `VisualFSharpOpenSource.csproj` within Visual Studio gives me:

![image](https://cloud.githubusercontent.com/assets/1249087/23721521/eada390a-03f6-11e7-9486-0eb0eda26352.png)

Relevant Output:

```
16>FSC: error FS0193: Could not find file 'C:\git\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\obj\Debug\net40\ProjectResources.rc.res'.
16>Done building project "ProjectSystem.fsproj" -- FAILED.
16>
16>Build FAILED.
17>------ Build started: Project: VisualFSharpOpenSource, Configuration: Debug Any CPU ------
17>CSC : warning CS1668: Invalid search path 'C:\Program Files (x86)\Windows Kits\10\Lib\10.0.14393.0\um\x64' specified in 'LIB environment variable' -- 'directory does not exist'
17>CSC : warning CS1668: Invalid search path 'C:\Program Files (x86)\Windows Kits\10\Lib\10.0.14393.0\ucrt\x64' specified in 'LIB environment variable' -- 'directory does not exist'
17>CSC : error CS0006: Metadata file 'C:\git\visualfsharp\Debug\net40\bin\FSharp.ProjectSystem.FSharp.dll' could not be found
========== Build: 14 succeeded, 3 failed, 11 up-to-date, 0 skipped ==========
```

Do I need to install any other workloads or run any commands not specified in the [DEVGUIDE](https://github.com/JoshVarty/visualfsharp/blob/master/DEVGUIDE.md)?

**Comment by JoshVarty** [comment]
This problem (with the resource) is mentioned in the comments of an existing issue here: https://github.com/Microsoft/visualfsharp/issues/2425#issuecomment-279650229

If I follow the advice there and remove

```
<RCResourceFile>ProjectResources.rc</RCResourceFile>
```

Then I can build from command line, but cannot build from Visual Studio.

What is this resource file? Is it needed? Can we remove it so the repository builds properly for contributors?

**Comment by cartermp** [comment]
cc @brettfo 

@JoshVarty No, you shouldn't need any other workloads or special bits.  I'm not sure how this could have gone wrong.  Could you back up to a previous commit in the repo?  I was able to build master as of a few days ago, so something must have happened in between now and then.

**Comment by KevinRansom** [comment]
@JoshVarty  I always install.  Dotnet workload + F#, C++ and VS Extensions.

**Comment by JoshVarty** [comment]
I haven't been able to build once since investigating #2490

The comment that recommends removing `ProjectResources.rc` is ~23 days old so that's a reasonable lower bound on how long this has affected people.

It's strange that you're able to build without issues.

**Comment by JoshVarty** [comment]
@KevinRansom I don't have C++ installed so I'll give that a shot now.

**Comment by KevinRansom** [comment]
Well C++ brings in the Windows SDK which is a pre-req for the vf tools repo.

**Comment by JoshVarty** [comment]
This was the issue: You must have the Windows Desktop C++ workload installed. 

I'll prepare a PR for the DEVGUIDE to update this information now.

Thanks everyone for your speedy help! :)

**Comment by KevinRansom** [comment]
@JoshVarty 

You must have a Windows SDK ... the C++ workload is one of the two workloads with it as an option.  .NetNative being the other one.  Frankly I consider the desktop workload not having it as an option is a bug, but  I suppose not every desktop developer needs the SDK.

**Comment by JoshVarty** [comment]
Ah yes, I see you can get it from Universal Windows Platform Development workload as well.

That is kind of strange that .NET Desktop Development doesn't have list it as an optional component...

**Comment by cartermp** [comment]
I *swear* I've built this without the WinSDK but it may have just been on my machine already for some reason.

**Comment by smoothdeveloper** [comment]
The SDK is 2.5gb, can we clarify if that `<RCResourceFile>ProjectResources.rc</RCResourceFile>` can be replaced by some other mechanism (AFAICS it is to register 4 icon types in solution explorer)?

Is that done the same way in C#/VB.NET editors?

**Comment by smoothdeveloper** [comment]
For VS vNext, can we get the C++/Windows SDK team to modularize their tooling? the RC resource compiler ought to be a standalone package (if it can be made smaller).

**Comment by KevinRansom** [comment]
@smoothdeveloper there is nothing really stopping us from making our own rc nuget package.  everything can be improved it just takes time and effort :-)

**Comment by smoothdeveloper** [comment]
For what is worth, I have `rc.exe` in my path (embeded in another development environment).

In ProjectSystem.fsproj we have this

```xml
  <Target Name="BeforeBuild">
    <Exec Command="&quot;$(ProgramFiles)\Windows Kits\8.1\bin\x86\rc.exe&quot; /fo $(IntermediateOutputPath)$(RCResourceFile).res $(RCResourceFile)" Condition="Exists('$(ProgramFiles)\Windows Kits\8.1\bin\x86\rc.exe')" />
    <Exec Command="&quot;$(ProgramFiles)\Windows Kits\10\bin\x86\rc.exe&quot; /fo $(IntermediateOutputPath)$(RCResourceFile).res $(RCResourceFile)" Condition="Exists('$(ProgramFiles)\Windows Kits\10\bin\x86\rc.exe')" />
  </Target>
```

Maybe we could just add rc.exe in the repository and tweak that project file to fallback to it instead?
