### ISSUE TITLE
inline rename issue with _prefixed symbols

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2563]
![renameissue](https://cloud.githubusercontent.com/assets/87944/23738700/d8cefab2-049a-11e7-8721-769f466d20e6.gif)

**Comment by vasily-kirichenko** [comment]
FCS does not return symbol uses for ignored symbols.

**Comment by smoothdeveloper** [comment]
What will break when FCS will return those symbols?

Maybe we logged that issue, but the fact we have code fix to prefix unused name with _ and that when you start using those it is recommended to rename those, it seems to be important to handle this case well.

**Comment by vasily-kirichenko** [comment]
I think ignored symbols are just erased completely on some very early stage. 

@dsyme please, shed light on this topic :)

**Comment by vasily-kirichenko** [comment]
@dsyme 

for 

```fsharp
module File7

let foo = 1

let _ = foo
```

We have captured name resolution for `foo` definition:

![image](https://cloud.githubusercontent.com/assets/873919/23764151/871376da-050d-11e7-8cf2-b1e8d0c17b17.png)

But for 

```fsharp
module File7

let _foo = 1

let _ = _foo
```

we don't

![image](https://cloud.githubusercontent.com/assets/873919/23764232/df5694d0-050d-11e7-959f-380ffdcfb322.png)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2568
