### ISSUE TITLE
String.concat casts to an array before concatenating

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2569]
In String.concat, the elements to concatenate are first passed through Seq.toArray, see:
https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/string.fs#L23

String.Join has an overload of IEnumerable<string>, so why are we casting it to an array first? I did some benchmarks for my PR https://github.com/Microsoft/visualfsharp/pull/2558#issuecomment-285490560 and noticed that String.concat is really slow with large sequences. Using String.Join is significantly faster, and I it's because we're doing Seq.toArray first.

@dsyme do you have any comments as to why we convert the sequence to an array first? I wonder if the String.Join overload was added after this function was written.

**Comment by majocha** [comment]
Good catch, wasn't String.Join overload added in .Net 4.0?

**Comment by saul** [comment]
Looks that way: https://msdn.microsoft.com/en-us/library/dd783876(v=vs.110).aspx

.NET Framework
Available since 4.0

So we should be able to use it in FSharp.Core :)
