### ISSUE TITLE
Suggestions delimited by empty lines in VS FSI 

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2572]
![image](https://cloud.githubusercontent.com/assets/873919/23786545/b9d5313c-057e-11e7-931e-803355145c31.png)

I don't think it's good. @forki any ideas?

**Comment by forki** [comment]
I think we need to understand where errors are reported. There is already a
switch for one line option. But this looks like an issue with fsi
formatting new lines as 2 linebreaks

Am 10.03.2017 08:46 schrieb "Vasily Kirichenko" <notifications@github.com>:
