### ISSUE TITLE
Move to AsyncPackage

### ISSUE THREAD

**Issue by JoshVarty** [Microsoft/visualfsharp#2578]
Occasionally while using `VisualStudioOpenSource.vsix` I receive notifications indicating that F# Tools are slowing down solution load:

![image](https://cloud.githubusercontent.com/assets/1249087/23808531/0abb8c2c-057f-11e7-8c86-b7a9eb0101ab.png)

In the performance manager: 

![image](https://cloud.githubusercontent.com/assets/1249087/23808542/1a80d91e-057f-11e7-9e7e-0257d734625d.png)

This notification is from a VM so I don't expect this to be typical performance, but it's still something we could improve.

I believe this can be mitigated by using an `AsyncPackage` instead of `Package` to load F# tools.

For more see: 
- [How to: Use AsyncPackage to Load VSPackages in the Background](https://msdn.microsoft.com/en-us/library/mt750288.aspx) 
- [How to: Provide an Asynchronous Visual Studio Service](https://msdn.microsoft.com/en-us/library/mt709265.aspx)

**Comment by cartermp** [comment]
👍

**Comment by cartermp** [comment]
cc @brettfo

**Comment by cloudRoutine** [comment]
@JoshVarty won't that require a reimplementation of the `AbstractPackage` and `AbstractLanguageService` on top of `AsyncPackage` instead of `Package`?  It might be easier just to profile and attack the bottlenecks

**Comment by JoshVarty** [comment]
Yeah it might not work since we're using the Roslyn base classes here, but I'm not very familiar with them so I can't say one way or the other.

Profiling might be a better option here.

**Comment by cartermp** [comment]
Closing this in favor of our issue tracking the consumption of Roslyn work
