### ISSUE TITLE
VS2017: No QuickInfo when debugging

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2584]
In VS2017, while using the debugger, there is no type information in F# code when I hover any of the symbols.

-------------------
(@cartermp edit: repro)

1. Create new Console app project.
2. Replace the code with the following, then debug it:

```fsharp
[<EntryPoint>]
let main argv = 
    let x = 1
    printfn "%d" x
    0 // return an integer exit code
```

**Expected:** When hovering over `printfn`, I can see its type signature.
**Actual:** Nothing is displayed when it is hovered.

**Comment by vasily-kirichenko** [comment]
Yes, I saw it once in RTW. It's gone after VS restart.

**Comment by KevinRansom** [comment]
I see this, did you have something else in mind?

<img width="1090" alt="screen shot 2017-03-11 at 12 02 37 pm" src="https://cloud.githubusercontent.com/assets/5175830/23825641/fb464ce4-0652-11e7-961e-dec714292431.png">

**Comment by smoothdeveloper** [comment]
@KevinRansom yes (sorry should have made screenshot)

![image](https://cloud.githubusercontent.com/assets/87944/23825982/31d3b40e-0694-11e7-9968-f505eee629b8.png)

**Comment by smoothdeveloper** [comment]
To clarify, when I hover a function, I'd like to see the signature, right now it shows nothing.

I understand that for variables, the debug inspector tooltip is good enough.

**Comment by vasily-kirichenko** [comment]
Is it how it works in C# editor?

**Comment by smoothdeveloper** [comment]
I'll check, but in C# editor I don't have choice other than having full method signatures in the code :)

I think the infobar will help if it can be ported from VFPT.

**Comment by saul** [comment]
The case is the same for C# - this is an IDE issue.

**Comment by cartermp** [comment]
Closing in favor of https://github.com/dotnet/roslyn/issues/4243

Since this isn't something we control
