### ISSUE TITLE
Renaming files in folders causes strange UI display

### ISSUE THREAD

**Issue by dungpa** [Microsoft/visualfsharp#259]
First we have two files inside a folder:
![image](https://cloud.githubusercontent.com/assets/941060/6312874/e22a33e4-b9bd-11e4-81db-eb95b8e4a4c2.png)

After renaming `File94.fs` to `File95.fs`, `File95.fs` moves on top (even on top of References nodes):

![image](https://cloud.githubusercontent.com/assets/941060/6312879/257581c6-b9be-11e4-9b51-8b50d8c9a1da.png)

It's a UI bug since the project is in good state. Reopening the project fixes the display.

See this in both VF# 3.1.2 and VF# 4.0.0.

**Comment by dungpa** [comment]
It's an annoying bug and it manifests in Folder organization feature in VFPT.

I gave a try at fixing it but didn't find a way.
@KevinRansom @latkin @vladima Could you guys give some pointers to investigate further? Thanks.

**Comment by dungpa** [comment]
I did some investigation. `RenameFileNode` at https://github.com/Microsoft/visualfsharp/blob/584093c6bcac8f4e67d1d2d588138be32e76310d/vsintegration/src/vs/FsPkgs/FSharp.Project/FS/Project.fs#L2527-L2562 looks fishy. Any ideas?

**Comment by enricosada** [comment]
hey @dungpa you know other bugs like this one? with node moved in another folders?

**Comment by dungpa** [comment]
@enricosada I recalled another similar bug. See the last sentences at http://fsprojects.github.io/VisualFSharpPowerTools/folderorganization.html#Limitations.

> Renaming a folder using standard F2 shortcut (inplace editing) is buggy due to issues inside F# project system. 

Here is a long repro https://github.com/fsprojects/VisualFSharpPowerTools/pull/313#issuecomment-39660694.

I can't seem to narrow down to a smaller repro. Could you have a quick look? Thanks.

**Comment by enricosada** [comment]
@dungpa i'll try a *quick* look, i think is renaming the physical directory into `f1` before the file, but fix depend on how messy is the code.
i really want to fix the project system but is easier not one bug at a time, the code need a refactor, see my other pr on fix already rendered folders bug. 

Maybe we need to summarize all the bugs on project system (not language service) and lacking features on a issue/wiki for status and roadmap. There are good example like pytools/nodejstools. 
i'll write a post/issue/wiki with my ideas, i'll ping you and @vasily-kirichenko and @fsprojects/visualfsharppowertools for feedback ( create a team in the organization :smile:  )

As @KevinRansom said, for Dev14 is too late for major refactoring, but maybe we can start work for next iteration

**Comment by enricosada** [comment]
yes the directory is renamed before the file, i'll check the code

**Comment by dungpa** [comment]
@enricosada Great. Do you happen to find a smaller repro?
