### ISSUE TITLE
EntityRef.get_Stamp() raises exception

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2591]
1. Ctrl+F5 in debug configuration
2. Open FSharp.Configuration solution
3. Open YamlProvider.fs

![image](https://cloud.githubusercontent.com/assets/873919/23829744/fcc9cc5e-070a-11e7-919e-8edd6c040962.png)

another one

![image](https://cloud.githubusercontent.com/assets/873919/23829748/148ebf34-070b-11e7-8244-021a87079689.png)

**Comment by dsyme** [comment]
Stepp back a bit, the overall aim hould be to make [GetSemanticClassification](https://github.com/Microsoft/visualfsharp/blob/4a43f48a8bfa6bc514a5824c9d16b298b9296675/src/fsharp/vs/service.fs#L1500) be tolerant of missing assembly references.  

One sure way to fix this is to put a ``protect`` around the processing of each individual ``resolution`` https://github.com/Microsoft/visualfsharp/blob/4a43f48a8bfa6bc514a5824c9d16b298b9296675/src/fsharp/vs/service.fs#L1215 and default to some empty value if something fails.


Another more local way is to make GetImmediateInterfacesOfType more tolerant of missing assembly references and simply don't return the interfaces if dereferencing is not possible - it tolerates some [on this path](https://github.com/Microsoft/visualfsharp/blob/8da728657e3380f5971f67c6a33c677c3211df72/src/fsharp/infos.fs#L138) through ``CanImportILType`` but not on the other branch of the ``else``.   You could put a [``protectAssemblyExploration``](https://github.com/Microsoft/visualfsharp/blob/40e95b223887fda83e121373c5753cb3b2390d49/src/fsharp/vs/ServiceDeclarations.fs#L541) call for example.

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it on current master.
