### ISSUE TITLE
module rec causes compilation error

### ISSUE THREAD

**Issue by tldrlol** [Microsoft/visualfsharp#2593]
Environment: VS2017 community, Windows 10, F# 4.1 Console Application with warning level set to 5

The following snippet (pasted verbatim into `Program.fs`) fails to compile. As the comment suggests, removing the `rec` keyword makes this a compiling program that prints `10` as expected.

```f#
// removing `rec` makes this compile
module rec Identity

type IdentityBuilder() =
  member inline __.Return(a: 'a): 'a = a

let identity = IdentityBuilder()

identity { return 10 } |> printfn "%d"
```

Errors don't appear in the "Error List" window. The build Output window however lists the following:

```
1>C:\Users\dk\Documents\Visual Studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\Program.fs(9,12): warning FS0021: This recursive use will be checked for initialization-soundness at runtime. This warning is usually harmless, and may be suppressed by using '#nowarn "21"' or '--nowarn:21'.
1>C:\Users\dk\Documents\Visual Studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\Program.fs(9,12): warning FS0040: This and other recursive references to the object(s) being defined will be checked for initialization-soundness at runtime through the use of a delayed reference. This is because you are defining one or more recursive objects, rather than recursive functions. This warning may be suppressed by using '#nowarn "40"' or '--nowarn:40'.
1>C:\Users\dk\Documents\Visual Studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\Program.fs(9,12): error FS1114: The value 'Identity.IdentityBuilder.Return' was marked inline but was not bound in the optimization environment
1>C:\Users\dk\Documents\Visual Studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\Program.fs(5,20): error FS1113: The value 'Return' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
1>C:\Users\dk\Documents\Visual Studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\Program.fs(9,12): warning FS1116: A value marked as 'inline' has an unexpected value
1>C:\Users\dk\Documents\Visual Studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\Program.fs(9,12): error FS1118: Failed to inline the value 'Return' marked 'inline', perhaps because a recursive value was marked 'inline'
1>Done building project "ConsoleApplication1.fsproj" -- FAILED.
```

**Comment by dsyme** [comment]
I think it's best to consider this "by design". For better or worse this counts as a use-before-definition w.r.t. "inline".  Just remove the "inline" or put the test code in another file.

**Comment by tldrlol** [comment]
Would it at all be possible to receive more explanation of why that is?

In particular, how it is that a seemingly unrelated keyword `rec` describing a module introduces a compilation error?

**Comment by drvink** [comment]
@tldrlol Basically, use of `inline` in any recursive binding construct (`let rec ... and ...`, `class`, and as of F# 4.1, `module rec` and `namespace rec`) imposes ordering requirements. This works:

```fsharp
let rec inline plus x y = x + y
(* val plus : x:'a -> y:'b -> 'c (requires member ( + )) *)
and hoop = plus "a" "b"
(* val hoop : string *)
and hober = plus 1 2
(* val hober : int *)
```

This doesn't:

```fsharp
let rec zzz = plus 1 2
(* Warning: FS0040: This and other recursive references to the object(s) being defined will be checked for initialization-soundness at runtime through the use of a delayed reference. This is because you are defining one or more recursive objects, rather than recursive functions. This warning may be suppressed by using '#nowarn "40"' or '--nowarn:40'. *)
and abc = plus "a" "b"
(*             ^^^ ^^^
This expression was expected to have type
    'int'    
but here has type
    'string' *)
and inline plus x y = x + y
(* val plus : x:int -> y:int -> int *)
```

[F# RFC FS-1009 - Allow mutually referential types and modules over larger scopes within files](https://github.com/fsharp/fslang-design/blob/master/FSharp-4.1/FS-1009-mutually-referential-types-and-modules-single-scope.md) says:
> [This proposal] doesn't make declarations independent of ordering: both type inference and initialization are still order-specific

#596 has a more baffling example of `inline` ordering issues. #1565 has some simpler examples and also gives a general rule by which to understand exactly how the ordering requirement behaves and how to not get bit by it.

Better diagnostics on this would certainly be nicer, though I'm not sure what sort of message could begin to easily explain this in a few short sentences. I also get the feeling that detecting the issue (i.e. making the compiler smart enough to know when to issue such a diagnostic) would be non-trivial, given the cascade of different, subtly-related messages it currently causes, but that's purely a guess.

**Comment by abelbraaksma** [comment]
> #1565 has some simpler examples and also gives a general rule by which to understand exactly how the ordering requirement behaves and how to not get bitten by it.

Yes, and there's been some update now for some more insights. Actually, @drvink, the only reason `rec inline` works in your code above is because it is not self-recursive. 

But you've given me a good example why you still need `rec inline` even though in most cases it is redundant, or causes spurious errors upon compiling: using `rec` here is required because of `and`.

However, whenever you try one of these, it will fail, regardless of the `rec` in the definition. So the `rec ... and` is redundant:

* Make any recursive function self-referring (direct recursion)
* Make the functions mutually referring (mutual recursion)
* Change the order where an earlier binding refers to a later one

Only the last in that list gives a more useful warning, and after compiling will give an error:

> warning FS0040: This and other recursive references to the object(s) being defined will be checked for initialization-soundness at runtime through the use of a delayed reference. This is because you are defining one or more recursive objects, rather than recursive functions. This warning may be suppressed by using '#nowarn "40"' or '--nowarn:40'.
