### ISSUE TITLE
Eliminate the effervescence of windows in FSharpQA tests when using hosted compiler

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#26]
For those who are actually running all of the tests, current defaults for the FSharpQA suite are to use parallel execution + hosted compiler server.  This results is a new compiler server console popping up and dying away every few seconds, which is rather disruptive if you are trying to do other work.

It's a simple change to make those windows hidden, just update constant in [runall.pl](https://github.com/Microsoft/visualfsharp/blob/fsharp4/tests/fsharpqa/testenv/bin/runall.pl#L3869) to `CREATE_NO_WINDOW`.

Hosted compiler was initially very unreliable, so it was nice to be able to see the output. But it seems sturdy enough now, I think I will change the behavior to something less disruptive.

**Comment by brodyberg** [comment]
Thanks Lincoln

**Comment by dsyme** [comment]
Thanks for this info. BTW I think it would make sense to make CREATE_NO_WINDOW the default.

**Comment by latkin** [comment]
Ok I will make that change today

**Comment by dsyme** [comment]
Thanks @latkin !
