### ISSUE TITLE
100% CPU load

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2602]
![image](https://cloud.githubusercontent.com/assets/873919/23870672/423bd56a-0838-11e7-8ac1-c9ed98c4784d.png)

![image](https://cloud.githubusercontent.com/assets/873919/23870692/55afc69c-0838-11e7-8fa4-b593cb831325.png)

![image](https://cloud.githubusercontent.com/assets/873919/23870732/7e8974c8-0838-11e7-8915-e91dbd96e71b.png)

![image](https://cloud.githubusercontent.com/assets/873919/23870772/a5939724-0838-11e7-9487-23d86a494c62.png)

**Comment by vasily-kirichenko** [comment]
@dsyme it's my, relatively new (post RTW) code:
```fsharp
 member x.IsDisposableType =
        if isUnresolved() then false else
        let ty = generalizedTyconRef entity
        Infos.ExistsHeadTypeInEntireHierarchy cenv.g cenv.amap range0 ty cenv.g.tcref_System_IDisposable
```

Please, help.

**Comment by cartermp** [comment]
@vasily-kirichenko Which PR was that?

**Comment by vasily-kirichenko** [comment]
@cartermp https://github.com/Microsoft/visualfsharp/pull/2488

**Comment by cartermp** [comment]
Thanks!  Is this on VisualFSharp.sln?  If so, which file?

Interesting that this is happening.  For some reason the [loop](https://github.com/Microsoft/visualfsharp/blob/8da728657e3380f5971f67c6a33c677c3211df72/src/fsharp/infos.fs#L105) within a [loop](https://github.com/Microsoft/visualfsharp/blob/8da728657e3380f5971f67c6a33c677c3211df72/src/fsharp/infos.fs#L161) is just slamming the dictionary in [`CanImportILType`](https://github.com/Microsoft/visualfsharp/blob/8da728657e3380f5971f67c6a33c677c3211df72/src/fsharp/infos.fs#L43).  Maybe there's a way to filter down what to look for prior to that?

**Comment by vasily-kirichenko** [comment]
@cartermp many files were opened at that time :( One thing I can think about is trying to call `IsDisposableType` for `IDisposable` itself.

**Comment by dsyme** [comment]
Either a quadratic (or worse) algorithm or a concurrency problem accessing that dictionary?

**Comment by vasily-kirichenko** [comment]
I don't see this bug anymore.
