### ISSUE TITLE
Exception thrown when sending code to F# Interactive

### ISSUE THREAD

**Issue by CodEFouR** [Microsoft/visualfsharp#2608]
When sending the code to the F# Interactive, I always came across the exception below:

![default](https://cloud.githubusercontent.com/assets/594939/23884033/4a1eca18-08a5-11e7-9dd4-f909cc02b4e2.png)

Don't know what triggers this and how to reproduce the issue, but it seems that the issue appears first time sending the code to interactive. The execution of the sent code is not impacted. And it doesn't happen immediately after sending the code, rather it happens after a while like when I scroll the code. The log file in the picture above shows the following:

```
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.   at 
System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo) at 
Microsoft.VisualStudio.Package.Colorizer.GetLineInfo(IVsTextLines buffer, Int32 line, IVsTextColorState colorState) at 
Microsoft.VisualStudio.Package.Source.GetWordExtent(Int32 line, Int32 idx, WORDEXTFLAGS flags, Int32 startIdx, Int32 endIdx  at 
Microsoft.VisualStudio.Package.ViewFilter.GetWordExtent(Int32 line, Int32 index, UInt32 flags, TextSpan[] span) at 
Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.GetWordExtent(Int32 iLine, Int32 iCol, UInt32 dwFlags, TextSpan[] pSpan)at 
Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.TryGetQuickInfoFromDebugger(IQuickInfoSession session, TextSpan[] dataBufferTextSpan, String tipText)   at 
Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan applicableToSpan) at 
Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()  at 
Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()   at 
Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e)  at 
Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()
```
OS: Windows 10 with latest update
VS 2017 Community Edition

**Comment by vasily-kirichenko** [comment]
It's fixed long time ago. Use latest VisualFSharpOpenSource.vsix

**Comment by CodEFouR** [comment]
I'm running the latest VS2017:
![default](https://cloud.githubusercontent.com/assets/594939/23887362/6876954c-08bc-11e7-8167-baf910265483.png)
![1](https://cloud.githubusercontent.com/assets/594939/23887363/68794850-08bc-11e7-802c-982b90525362.png)

**Comment by CodEFouR** [comment]
Ah sorry I didn't check out VisualFSharpOpenSource.vsix in my last post. I got it and will give it a try. Thank you.

**Comment by dsyme** [comment]
Closing as already fixed in master
