### ISSUE TITLE
Struct Records cannot be stored in Nullable

### ISSUE THREAD

**Issue by neildanson** [Microsoft/visualfsharp#2609]
Given the point of using Struct Records/union is to reduce allocations, I think using heap allocated Option to box in this case is sub-optimal. Nullable should work, but gives compiler error.

#### Repro steps

```fsharp
[<Struct>]
type Point = { X: float; Y: float }
let pt = { X = 1.0; Y = 2.0 }
let n = System.Nullable(pt)
```
also 

```fsharp
[<Struct>]
type Point = 
| Point of float * float
let pt = Point(1.0, 2.0)
let n = System.Nullable(pt)
```

#### Expected behavior

Code builds, and Point can be used in a `Nullable<'t>`

#### Actual behavior
`Error	FS0001	The type 'Point' is not compatible with the type 'System.ValueType'`

#### Known workarounds
Use "old" struct format.

#### Related information 

* Operating system - Windows 10
* .NET Runtime, CoreCLR or Mono Version - .NET 4.6.2
* Editing Tools (e.g. Visual Studio Version) - VS 2017 RTM

**Comment by dsyme** [comment]
Changed title - the problem is that the F# compiler doesn't consider struct records and unions to be subtypes of System.ValueType.  This was missed in the RFCs for these language features.

**Comment by vasily-kirichenko** [comment]
I think we have a number of serious bugs here:

![image](https://cloud.githubusercontent.com/assets/873919/25313634/f2ba37f2-283a-11e7-95c2-48763245709d.png)

**Comment by dsyme** [comment]
@vasily-kirichenko OK, thanks.  Probably the same underlying cause(s).

**Comment by thinkbeforecoding** [comment]
It also surfaces with dealing with MemoryMappedFiles and MemoryViewAccessor.
When using a view: MemoryViewAccessor, doing:
view.Read<StructRec>(0L)
emit the same error message:
The type 'StructRec' is not compatible with the type 'ValueType'.

After analyzing a bit the issue, in F#, declaring a function:
let f<'a when 'a : struct>() = ...

the function works with Struct Records, and display a constraint "<'a (requires value type)>"
whereas framework functions as MemoryViewAccessor.Read have a constraint "<'T (requires default constructor and value type and 'T :> ValueType )"

Maybe simplifying constraint generation when reading assembly metadata to 'requires value type' would solve the problem ?

**Comment by thinkbeforecoding** [comment]
@dsyme the PR #3208 fixes it by returning a ValueType base type for both struct records and struct unions.

**Comment by dsyme** [comment]
@thinkbeforecoding Super, thanks!

**Comment by thinkbeforecoding** [comment]
Btw the fix also return System.Enum base type for F# enums...

**Comment by dsyme** [comment]
fixed, thanks
