### ISSUE TITLE
No IntelliSense after re-opening multi-project solution on VS reload

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2611]
If you create a solution where one project references another, close VS, then re-open that solution, you will not get IntelliSense in VS 2017 RTW.

#### Repro steps

1. Create a new Class Library with the following (template) code:

```fsharp
namespace Library1

type Class1() = 
    member this.X = "F#"
```

2. Create a new Console App with the following:

```fsharp
open Library1

[<EntryPoint>]
let main argv = 
    Class1().X |> ignore
    0 // return an integer exit code
```

3. Close VS.
4. Open VS with the solution you just created.

#### Expected behavior

IntelliSense and type colorization all works, as before.

#### Actual behavior

No IntelliSense, type colorization, etc.

#### Known workarounds

Modify the project file, causing projects to reload.  IntelliSense shows up again.

#### Related information 

This may be fixed in the latest nightly, but I'm not positive until I can get that build on my machine.

**Comment by vasily-kirichenko** [comment]
Another repro: open any file in FsharpProject project in vft solution - nothing works. Go to project settings dialog, change (wrong) project type from console app to library - everything works.

**Comment by majocha** [comment]
For me the result on RTW is 
<img width="828" alt="2017-03-15" src="https://cloud.githubusercontent.com/assets/1760221/23957424/9d0acee8-099f-11e7-9086-2b42308a3190.png">
but on master everything works fine.
<img width="767" alt="2017-03-15 2" src="https://cloud.githubusercontent.com/assets/1760221/23957756/71f40278-09a0-11e7-8e9b-cd4dc9f54a87.png">

**Comment by vasily-kirichenko** [comment]
Why file bugs found in RTW at all? It's tremendously outdated.

**Comment by cartermp** [comment]
@vasily-kirichenko People provide feedback through VS, which eventually turns into a TFS bug that finds its way to us.  Any way we can convert that to GitHub, point people towards it, and verify with a larger audience, the better.  It also helps in tracking what issues are (or were), and for which release.

**Comment by cartermp** [comment]
Confirmed that this is fixed in the latest nightly.  Yay!

**Comment by fierval** [comment]
Issue is back in 15.1, latest nightly: 15.4.1.17040601. Workaround works.

**Comment by kaftand** [comment]
> Issue is back in 15.1, latest nightly: 15.4.1.17040601. Workaround works.

Has this since been resolved? I am experiencing the same issue now (Version 15.9.8)

**Comment by cartermp** [comment]
@kaftand This was fixed a long time ago. Can you file a new issue with a repro please?

**Comment by kaftand** [comment]
I appreciate your quick response. It turns out the issue was a stupid mistake on my part :/ apologies for wasting your time.

**Comment by cartermp** [comment]
No worries!
