### ISSUE TITLE
Visual Studio 2017 Crash when executing code in FSI

### ISSUE THREAD

**Issue by gusty** [Microsoft/visualfsharp#2613]
This is hard to reproduce but from time to time I'm getting:

 - Exceptions displayed like this:

![image](https://cloud.githubusercontent.com/assets/1261319/23941656/ed955b66-0969-11e7-912d-5932df8b51d8.png)

(the file is attached)

 - Visual Studio crashes, and then it restarts. This happens when sending code to the fsi window.

#### Repro steps

Unfortunately I can't find steps to reproduce it at the moment.

#### Expected behavior

No exceptions, no crashes.

#### Actual behavior

Exceptions, crashes.

#### Known workarounds

None

#### Related information 

* Operating system: Windows 10 Pro N
* Branch: Visual Studio 2017 26228.9
* .NET  Version: 4.6.01055
* Editing Tools (e.g. Visual Studio Version): 2017
* Links to F# RFCs or entries on http://fslang.uservoice.com: N/A
* Links to performance testing scripts: [ActivityLog.zip](https://github.com/Microsoft/visualfsharp/files/843964/ActivityLog.zip)
* Indications of severity: Medium to High

**Comment by vasily-kirichenko** [comment]
This is fixed in master.
