### ISSUE TITLE
Loading two scripts with same name from different folders doesn't work in fsi

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2614]
![image](https://cloud.githubusercontent.com/assets/57396/23946846/60baace2-097c-11e7-8161-b61150897e40.png)

[fileload.zip](https://github.com/Microsoft/visualfsharp/files/844321/fileload.zip)

The issue is QualFileNameOfFilename in CompileOps.fs doesn't look at the file path and therefor generates two implicit module names with same name.

**Comment by smoothdeveloper** [comment]
thinking the modules should be combined if possible, or the name of subsequent scripts altered (to not be a breaking change).

**Comment by dsyme** [comment]
@forki  It seems reasonable for QualFileNameOfFilename to either include the file path  in some way, or a stable hash of the file path

**Comment by smoothdeveloper** [comment]
@dsyme is that going to change the implicit name given of the module?

**Comment by dsyme** [comment]
@smoothdeveloper Yes, the change should be made with that in mind. e.g. only add the hash if there is a clash with an existing file in the compilation. (I think anything else would be a breaking change)

**Comment by smoothdeveloper** [comment]
Right, I had this in mind (when I stated "name of subsequent scripts altered" I meant to write module names).

Although I'm wondering if there aren't messy problems down the road by doing so, opening the same script in different places will bring the implicit module stuff under different names which could be a problem.

I guess it is a problem with work around (open the right module or don't do stupid things), we still need to find a graceful handling for naming to not have breaking changes in future nor have to open module such as `Script1{some_guid_or_hash}`.

Maybe finding the first part which is distinct from previously imported module given absolute path from the files, in this case it would be `F2.Script1`, can we list few suggestions?

**Comment by KevinRansom** [comment]
@dsyme @smoothdeveloper 

perhaps extend #load to allow a developer to specify the module name instead of inferring it.  Then the packagemanager (or developer)  can specify whatever name it likes, and the default behavior remains unchanged and so no breaking change.

Kevin

**Comment by smoothdeveloper** [comment]
That's a possibility although I don't see any breaking change in having better automatic naming happening, because currently FSI doesn't accept that situation (I'm surprised I never faced it so far).

Even when we specify a name, there is still going to be room for clash AFAIU, right?

**Comment by cartermp** [comment]
This seems to work with fsharpi and mono.

`one/Script1.fsx`:
```fsharp
let db x = x * 2
```

`two/Script1.fsx`:
```fsharp
let sq = x * x
```

`Script.fsx`:
```fsharp
#load "one/Script1.fsx"
#load "two/Script1.fsx"

open Script1

printfn "Double of 2: %d\nSquare of 2: %d" (db 2) (sq 2)
```

Then run `fsharpi Script1.fsx`:

<img width="280" alt="screen shot 2017-03-15 at 9 59 55 am" src="https://cloud.githubusercontent.com/assets/6309070/23960810/32629546-0966-11e7-88a4-0c2c190f39ca.png">

**Comment by forki** [comment]
Yeah I have a suspicion that we regressed here

Am 15.03.2017 18:00 schrieb "Phillip Carter" <notifications@github.com>:

**Comment by smoothdeveloper** [comment]
It works from FSI but the problem is in VS, same problem exists in VS2015.

**Comment by KevinRansom** [comment]
@forki, @smoothdeveloper, @dsyme, @cartermp 
Is someone working on this, or should I take a look at it?

**Comment by forki** [comment]
I looked at it, but tbh I am already preparing next vacation ;-)

**Comment by KevinRansom** [comment]
I would prefer not to duplicate work, so I can take a look if no one else is.

**Comment by forki** [comment]
yeah what I was trying to say was. I'm not working on it.

**Comment by smoothdeveloper** [comment]
@KevinRansom not working on it, tried to get us thinking about what we want instead of current behaviour and intend to work on other smallish bugs in the IDE I logged recently.

**Comment by KevinRansom** [comment]
Okay ... I will add to the list of things to get on with ...

**Comment by dsyme** [comment]
@forki Am I right that this has been fixed?

**Comment by forki** [comment]
Did not test again

**Comment by dsyme** [comment]
@forki I checked, it is fixed, thanks
