### ISSUE TITLE
Intellisense list is sorted very wrongly

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2618]
Not-after-dot completion sorted very wrongly:

![image](https://cloud.githubusercontent.com/assets/873919/23965016/a84cfdbc-09c7-11e7-88b1-a760906b6c15.png)

It's fixed in https://github.com/Microsoft/visualfsharp/pull/2594 (not entirely, but almost). Does it make sense to make a separate PR?

**Comment by KevinRansom** [comment]
@vasily-kirichenko I just pulled #2594.  So feel free to submit any fixes you think are needed.

**Comment by JoshVarty** [comment]
Out of curiosity: What's the ideal order in your view? 

C# uses alphabetical, but I've heard some people want "more intelligent" sorting.

**Comment by vasily-kirichenko** [comment]
@JoshVarty R# like.

**Comment by smoothdeveloper** [comment]
@JoshVarty one thing R# does is having a MRU of committed completions, and in general you want locals/parameters before the rest.

**Comment by AmadeusW** [comment]
I'm working on a new Intellisense API specification for VS. I'm interested in what are the desired sorting mechanisms. We are now open for suggestions, and so far we've heard of sorting by

* Camel case match (this will be performed by VS on each keystroke, before other sorts)
---
* Scope distance (locals before class members before rest)
* Recently used
* Suggested name (when language service proposes a new variable name)
* Lastly, alphabetical

Language services will be able to implement some, all or more than the above items, in any order. We would like to encourage language services to adopt a standard and predictable way of ordering for consistent UX across languages.

**Comment by vasily-kirichenko** [comment]
We implemented the following order in F# editor:

For completion after dot:

* Recently used (but not extension methods)
* Own (defined in the type before dot) properties
* Inherited properties
* Own fields
* Inherited fields
* Own methods
* Inherited methods
* Own events
* Inherited events
* Everything else
* Extension methods

Then alphabetically Inside each group.

About completion which does not involve a concrete type or module (strictly not after dot sense F# does not allow accessing members inside class via implicit `this` reference), we are not sure yet. Currently it shows fields (including enum fields) first, then everything else.

**Comment by smoothdeveloper** [comment]
@AmadeusW please also consider looking beyond sorting for Intellisense API revisions:

* making the list resizeable (when I use APIs with hundreds of members, I really need a bigger list)
* having more info in the list: R# shows namespaces for members in the list that aren't in scope (it will open the namespace for you if you commit the completion), and it also put the type signature of the elements aligned to the right
* having extensible way of displaying icons (not just a hardcoded enum, but possibility to add overlays to the icons)
* having ways to use different text and background styling for items in the list
* having a default implementation for the MRU behaviour switchable and configurable in the API
* better way to show overloads (see pictures bellow)

R#:
![image](https://cloud.githubusercontent.com/assets/87944/24016232/a702e9ca-0a8b-11e7-8826-434a1a2d176b.png)

VS:

![image](https://cloud.githubusercontent.com/assets/87944/24016269/c99e34bc-0a8b-11e7-8b39-3bfdb95ccd55.png)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2594
