### ISSUE TITLE
Wishlist: better debugger display for List, Set, Map

### ISSUE THREAD

**Issue by vivainio** [Microsoft/visualfsharp#2619]
Currently, you get a good overview of data structure contents for Array (i.e. actual items in a flat list).

List, Set and Map should provide a similar overview. Instead, you need to click through the internal data structure to see the contents.

**Comment by forki** [comment]
You need to activate "use old C#/VB debugger visualizers" or something like that in VS options. Then it works like in VS 2015. Unfortunately there is no way to reactivate that for VF#. It's a bit fucked up situation

**Comment by vivainio** [comment]
I tried that, and it worked.

For posteriority, it's here:

Tools => Options => Debugging => General => "Use the legacy C# and VB expression evaluators".

My immediate problem is solved with this one, but I'll leave the ticket open in case we get around to getting a "non legacy" solution for this as well, eventually.

**Comment by forki** [comment]
I think it's a duplicate since I raised exactly the same thing couple of weeks ago. It's just unfortunate that MS did not activate that thing again...

**Comment by smoothdeveloper** [comment]
#2184

**Comment by vivainio** [comment]
Closed as duplicate of #2184

**Comment by cartermp** [comment]
Just to chime in, support for all three means support for an F# Expression Evaluator.  That's a very nontrivial bit of work that we've got as a high priority internally, but won't be able to get to until at least when the project system work is finished.

**Comment by dsyme** [comment]
> The legacy C# EE that we used to use calls into List's DebugView member, which effectively ToArray'd the list and returned that array. The current C# EE that we use could be modified in a similar way as a temporary stopgap.

I consider this a bug in the current C# EE? It should always have continued to support DebugView on any F# (or Visual Basic or whatever) objects.  That is I don't understand why the existing DebugView's don't just work with the new C# EE

**Comment by cartermp** [comment]
@tmat, would you know more about this?

**Comment by tmat** [comment]
@cartermp Can you point me to the nupkg and assembly in it that defines the types in question?

**Comment by cartermp** [comment]
@tmat Code is here: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/prim-types.fs#L3512

The assembly is FSharp.Core.dll (not distributed via nupkg in vs2017) - we ship versions 4.4.1.0, 4.4.0.0, 4.3.1.0, and 4.3.0.0 which each define the type.  We ship a nupkg for .NET Core [here](https://www.nuget.org/packages/Microsoft.FSharp.Core.netcore/1.0.0-rc-170316-0).

The only regression here is in Lists, though we do define debugview types for [Maps](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/map.fs#L634) and [Sets](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/set.fs#L753), so I suppose it's just as easy to support them as it is to re-enable Lists.
