### ISSUE TITLE
Align openfsharp and visualfsharp

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#262]
Sorry for this list dump, maybe a wiki page is better? i need some feedback about that

I do not want to merge the two repo ( as @dsyme wrote before the open and visualfsharp repositories have different purposes ) but align the code where possibile is good for maintainability

I'd like to discuss (before starting to send pr :smile: ) what can/should be aligned, not import blindly code. 
As i understand the current teams (@dsyme + ? for openfsharp and @latkin + @KevinRansom for visualfsharp ) can give some quick hints (yes/no/need discussion) and leave the next step as `up-for-grabs`

Some are easy (like encoding) and require only a choice. 
Some required only a bit of coordination from the two teams (like the msbuild stuff)
Some are new features or required for cross-platform , which may or may not be useful

I have done a file compare on `src` directory, from fsharp/fsharp#385 to 72185167566e7b7ac85f396a40258ebe35a10c19 (visualfsharp master branch) and the major differences are:

- [conflicts](#conflicts) : different implementation, same line conflict usually
- [open -> visual](#openfsharp---visualfsharp), does not exist in visualfsharp
- [visual -> open](#visualfsharp---openfsharp), exists only in visualfsharp

My idea is to create a wiki page with this list ( roadmap and link to the questions maybe ) and document the known differences (at least the preprocessor directives )

As usual a long post, sry

CONFLICTS
=========

The implementation differs in the two repositories

- [ ] copyright hardcoded inside assembly attributes like `AssemblyCompany`, `AssemblyCopyright`, `AssemblyProduct` in `src/assemblyinfo/*`
- [ ] define `SILVERLIGHT_COMPILER_FSHARP_CORE` vs `FX_NO_CUSTOMATTRIBUTEDATA` (same code inside)
- [x] surface area tests: not the surface, the multiline `\r\n` trim implementation
- [ ] directory `lkg` vs `lib`
- [ ] directory `.nuget` vs `FSharp.Core.Nuget.nuget`

#### Encodings

same text, different file encoding only 
how to: use UTF-8

- [x] .resx file encoding (UTF8-BOM vs UTF8)
- [x]  app.config file encoding (UTF8-BOM vs UTF8) 
- [x]  AppManifest.xml file encoding (UTF8-BOM vs System) 
- [x]  .xaml file encoding (UTF8-BOM vs System) 

#### Infrastructure

- [ ] msbuild property `FSharpSourcesRoot`

	`<FSharpSourcesRoot>..\..</FSharpSourcesRoot>` 
	vs
	`<FSharpSourcesRoot>$(MSBuildProjectDirectory)\..\..</FSharpSourcesRoot>`

- [ ] msbuild `ProjectReference` of `FSharp.Core`

	`<ProjectReference Include="$(FSharpSourcesRoot)\fsharp\FSharp.Core\FSharp.Core.fsproj">` 
	vs 
	`<ProjectReference Include="..\FSharp.Core\FSharp.Core.fsproj">`

- [ ] msbuild `Reference` of `FSharp.Core`

	```xml
	<Reference Include="$(FSCoreLKGPath)" />
	``` 
	vs
	```xml
	<Reference Include="FSharp.Core">
	  <HintPath>$(FSharpSourcesRoot)\..\lib\bootstrap\4.0\FSharp.Core.dll</HintPath>
	  <Private>True</Private>
	</Reference>
	```
- [ ] msbuild version 12 vs 4.0
- [ ] import of lkg FsLexYacc etc

	```xml
	<Import Project="$(FSharpSourcesRoot)\..\lkg\FSharp-$(LkgVersion)\bin\FSharp.PowerPack.targets" />
	```
	vs
	```xml
	<Import Project="$(LkgPath)\FsLexYacc.targets" />
	```

OPENFSHARP -> VISUALFSHARP
==========================

- [ ] the `if runningOnMono` with same code of visualfsharp for else
- [ ] the ISymWrapper.dll is missing
- [ ] the [manifest resource name]
- [ ] the `SecurityRulesAttribute` not enabled (with `CROSS_PLATFORM_COMPILER` define)
- [ ] fsi console, type are internal not public
- [x] feature `fsc --gccerrors`, fsc ErrorStyle.GccErrors
- [x] feature ``fsc --exename``, TcConfigBuilder.exename
- [ ] hide items with ObsoleteAttribute in intellisense list
- [ ] reference resolution

#### Defines

- [ ] `CROSS_PLATFORM_COMPILER`
- [ ] `FX_NO_BIGINT_CULTURE_PARSE`
- [ ] `FX_NO_TASK`
- [ ] `EXTRAS_FOR_SILVERLIGHT_COMPILER`
- [ ] `WSDL`
- [ ] `EXTENSIONTYPING`
- [ ] `INCREMENTAL_BUILD_OPTION`
- [ ] `TYPE_PROVIDER_SECURITY`
- [ ] `FSHARP_SERVER_PROGRESS` (fsc)
- [ ] `FX_ATLEAST_45_COMPILER_LOCATION`

#### infrastructure

- [ ] makefile build
- [ ] xbuild workarounds
- [ ] monodevelop configuration helpers

	```xml
	<!-- MonoDevelop likes these here to recognise the configurations -->
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' " />
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' " />
	```

[manifest resource name]: https://github.com/fsharp/fsharp/blob/259e855b69140995056c1f74d58a26b7071ccae5/src/fsharp/FSharp.Build/CreateFSharpManifestResourceName.fs#L20-L38

VISUALFSHARP -> OPENFSHARP
==========================

- [ ] msbuild property `TargetFrameworkVersion`
- [ ] msbuild ProjectReference property `<Private>True</Private>`
- [ ] define `SILVERLIGHT`
- [ ] feature DisplayEnv.showHiddenMembers
- [ ] msbuild conditional for net20: `<ItemGroup Condition=" '$(TargetFramework)' == 'net20'`

**Comment by enricosada** [comment]
`--gccerrors` and `--exename` with #587

**Comment by dsyme** [comment]
Closing old discussion
