### ISSUE TITLE
an refresh of Microsoft.FSharp.*.netcore on nuget.org

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#2625]
@KevinRansom Is possibile to have a new release of package [Microsoft.FSharp.Compiler.netcore](https://www.nuget.org/packages/Microsoft.FSharp.Compiler.netcore) on nuget.org? Maybe fsharp.core too, if needed.
Atm version is `1.0.0-rc-170122`.  /cc @cartermp

To get fsc args (https://github.com/fsharp/FSharp.Compiler.Service/issues/707) required by FSAC  (https://github.com/fsharp/FSharp.Compiler.Service/issues/705), i added new properties of the msbuild Fsc task with https://github.com/Microsoft/visualfsharp/pull/2523 . That's why i need the new package, for an updated `FSharp.Build.dll`

Now that the works is done for FSAC (and can be tried in https://github.com/ionide/FsAutoComplete/pull/53 with vscode), i'd like to use official MS package and refresh downstream (so `FSharp.Compiler.Tools`, `FSharp.NET.Sdk` ) so is possibile to use it in FSAC /cc @dsyme

**Comment by KevinRansom** [comment]
Done Version="1.0.0-rc-170316-0"... it's just indexing

https://www.nuget.org/packages/Microsoft.FSharp.Compiler.netcore/1.0.0-rc-170316-0
https://www.nuget.org/packages/Microsoft.FSharp.Core.netcore/1.0.0-rc-170316-0

**Comment by enricosada** [comment]
Awesome, thx a lot @KevinRansom . i'll try update fsharp packages now 👍 and some test, after that i'll close it

**Comment by enricosada** [comment]
All ok for now! published as [FSharp.Compiler.Tools/4.1.1](https://www.nuget.org/packages/FSharp.Compiler.Tools/4.1.1), 

@KevinRansom @cartermp thx a lot! Just adding a gif on why i am so happy about it

clean repo -> open code -> `dotnet restore` -> intellisense! -> F5 -> debug!

![rec-vscode-102](https://cloud.githubusercontent.com/assets/147243/24065781/e986501a-0b6d-11e7-9564-db9c68002f30.gif)
