### ISSUE TITLE
Double-clicking error in error list on dirty file duplicates tab

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2626]
Looks like #2417 didn't catch this.

#### Repro steps

1. Create a new Class Library.

2. Make it fail to compile (I typed `asdfa` somewhere)

3. Double-click the error in the Error List window.

#### Expected behavior

Takes me to the line with the error

#### Actual behavior

takes me to the line with the error **and** opens a duplicate tab of the file.

![duplicate-tab](https://cloud.githubusercontent.com/assets/6309070/24007632/6bcb6a6c-0a2c-11e7-8c2f-59c38e990bcf.PNG)

#### Known workarounds

None.

#### Related information 

Using the [first nightly](https://dotnet.myget.org/feed/fsharp/package/vsix/VisualFSharp) released on 2017-15-03.

**Comment by vasily-kirichenko** [comment]
It caught. Looks like https://github.com/Microsoft/visualfsharp/pull/2606 bring back duplication. 

Find usages - click on a symbol in the result window => duplicated tab
GoToAll - find a symbol - go to it => duplicated tab
F12 on a symbol definition => duplicated tab

@JoshVarty are you sure your PR don't yield duplicated tabs?

**Comment by JoshVarty** [comment]
Which version number? `15.4.1.17031503`?

**Comment by JoshVarty** [comment]
So I tried to repro this and got some weird behavior:

- If I start Visual Studio and previously opened documents are open, I can repro this behavior.
- If I close the documents and then re-open them, I can no longer repro this behavior.

@cartermp @vasily-kirichenko Can you repro this behavior once you close your open tabs?

**Comment by cartermp** [comment]
@JoshVarty This was with 15.4.1.17031602, but I cannot reproduce this anymore with 15.4.1.17031603.

**Comment by cartermp** [comment]
Neither do Go to Definition, nor Find all References.  I can't seem to repro it on VisualFSharp.sln, either.  I'll close this for now.

**Comment by JoshVarty** [comment]
I'd actually leave it open because I can repro it reliably via:

1. Install any nightly build
2. Open a `.fs` file in a solution.
3. Close VS
4. Uninstall the F# tools
5. Install a different nightly build.
6. Open your original solution. (Visual Studio will automatically open the previous `.fs` file.
7. Introduce the error your mentioned above
8. Click the error list and observe a duplicate tab is opened.

I'll investigate and fix this issue since many people will be using the nightly builds and will therefore run into this daily.

**Comment by cartermp** [comment]
Sounds good.

**Comment by JoshVarty** [comment]
Ah, there's an issue with `VisualFSharp.15.4.1.17031503.vsix`.
It does not have the `.pkgdef` changes.

`VisualFSharp.15.4.1.17031503.vsix`. was generated at Wed, 15 Mar 2017 15:42:57 GMT
My PR was merged on Thurs, 16 Mar 2017 2:51:00 GMT

So it's likely just an issue with the PR not being present in that copy.

**Comment by JoshVarty** [comment]
Actually upon further review (and failing to repro this by switching between versions that include #2606) I don't think this will be a problem going forward.

It's likely you had tabs open from previous installs of the Visual F# Tools. These tabs were created with the `Source (Text) Editor Factory`. When Visual Studio restarts, it always opens tabs with the same editor factory they were opened with previously. (If you still have these tabs open, you can confirm that Alt+Enter does not work in one of them, but does work in the other).

Going forward (`15.4.1.17031601` onward) all editors will be created with the F# Editor Factory.

We can close if @vasily-kirichenko can confirm:

1. He's on `15.4.1.17031601` or later
2. Closing the tabs and re-opening stops this behavior

**Comment by vasily-kirichenko** [comment]
@JoshVarty I confirm that if I close all previously opened tabs, than duplicated tabs don't appear anymore. Thanks!
