### ISSUE TITLE
Used `open` colored as unused

### ISSUE THREAD

**Issue by sergey-tihon** [Microsoft/visualfsharp#2627]
Incorrect coloring of used `open` statements.

#### Repro steps

Paste following code samples in `VS2017`

```fsharp
module A =
    open System

module B =
    open System

    let queries =
        System.IO.File.ReadAllLines(__SOURCE_DIRECTORY__ + "file.txt")
        |> Array.filter (String.IsNullOrWhiteSpace >> not)
```

#### Expected behavior

`open System` in `Module A` is unused
`open System` in `Module B` is used

#### Actual behavior

<img width="703" alt="screen shot 2017-03-16 at 8 16 04 pm" src="https://cloud.githubusercontent.com/assets/1197905/24009247/7110fb14-0a85-11e7-8e87-e82fae7dceff.png">

#### Known workarounds

No

#### Related information 

* Windows 10
* Nightly build for VS2017 - 15.4.1.17031503
* Indications of severity - Low

**Comment by cartermp** [comment]
Tagging this for VS 2017 updates for now, though I may move it from that milestone in the future since it's fairly low-priority

**Comment by sergey-tihon** [comment]
Thanks @cartermp, sure. When do you use label:"Up for Grabs" ?

**Comment by cartermp** [comment]
Good question.  I suppose that's always implicitly up - though I suspect @vasily-kirichenko would need to be involved (certainly for a code review) since he wrote this part of the tools.

**Comment by KevinRansom** [comment]
The milestone thing, is really for when Don, Phillip, Brett or Me will look at it.  If a member of the community wants to fix it, we will incorporate their fix when it is ready, not when it's milestone is achieved.

We don't have a good strategy for up-for grabs, mainly because there seems to be a notion that up-for grabs are somehow 'entry level bug fixes' good for beginners as it were.  Obviously most of our bug fixes are challenging even for developers super familiar with our codebase.

So up for grabs is not something we do a lot of.  Effectively every issue is always up for grabs.

Does that help?

Kevin

**Comment by vasily-kirichenko** [comment]
I'm not sure it's a bug. Either of `open System` can be considered as unused because we can remove either of them and the code will compile.

**Comment by vasily-kirichenko** [comment]
IDEA considers nearest import statement as "used" though:

![image](https://cloud.githubusercontent.com/assets/873919/25305971/61bb615c-278d-11e7-9fbb-ce78dd0a71a1.png)

I don't see the rationale in this logic still.

**Comment by 0x53A** [comment]
The first open is scoped to Module A:

![image](https://cloud.githubusercontent.com/assets/4236651/25306018/ef5c477c-2785-11e7-8fcc-cd8aa89ecff8.png)

If I move the first open to the global scope, then it works better:

![image](https://cloud.githubusercontent.com/assets/4236651/25306026/17cce37e-2786-11e7-8597-8dffd024be9b.png)

And imo that is correct, it should prefer outer opens.

**Comment by vasily-kirichenko** [comment]
ah! sorry, i'm stupid :(

**Comment by vasily-kirichenko** [comment]
Currently we don't correlate scope were a namespace or module is opened with symbol uses' scope. So fixing this bug requires rewriting the feature. I think we can live with it for now.

**Comment by dsyme** [comment]
Closing per discussion above
