### ISSUE TITLE
Nightly VSIX failed to install

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2629]
1. The first nightly build installed, everything works
2. Notification come
3. Update
4. Installer fails saying the extension is already installed
5. Open VS, it says VFT package failed to load

![image](https://cloud.githubusercontent.com/assets/873919/24009986/9645806a-0a87-11e7-9355-63dcb8efad72.png)

![image](https://cloud.githubusercontent.com/assets/873919/24009886/4ded1eea-0a87-11e7-97e9-a31d234ed238.png)

**Comment by cartermp** [comment]
@brettfo Is looking at this right now.  The current workaround is to uninstall it first, then install the update.  He's working with the extensions team in VS right now to see what's up.

**Comment by jack-pappas** [comment]
For comparison, I was able to install just fine. The first time I brought up VS after installing the nightly, VS crashed. I restarted and everything has been fine since then.

**Comment by JoshVarty** [comment]
I saw this behavior today as well. After installing I ran `devenv /updateConfiguration` from a developer command prompt and it seemed to get things working properly again.

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it anymore.
