### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#263]
About [.NET Core], is someone trying to port f# to [coreclr] and [corefx] ? 

Is this the repo or is fsharp/fsharp ?

Sry if it is an useless issue, but i think is good to track this because is important

ref [uservoice]

[.net Core]: https://github.com/dotnet/core
[coreclr]: https://github.com/dotnet/coreclr
[corefx]: https://github.com/dotnet/corefx
[uservoice]: http://fslang.uservoice.com/forums/245727-f-language/suggestions/6803533-support-net-core-and-coreclr

**Comment by KevinRansom** [comment]
Clearly this is something that is a priority for the .Net framework, Clr and Managed Languages teams will be a priority for us.  We are in the process of finalizing how F# will fit into this new cross platform open source world.  We will be updating our roadmap for F# and that will include information on coreclr and asp vnext support.

Right now the very best thing the community can focus on is fixing F# bugs for VS 2015.
