### ISSUE TITLE
Ctrl+; keybinding (search solution explorer) doesn't trigger with F# files are in focus

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2630]
#### Repro steps

1. Create a new F# project.

2. Click in the editor on an F# project.

3. Press `Ctrl+;` keybinding.

#### Expected behavior

Focus is brought into the Solution Explorer search bar.

#### Actual behavior

Nothing happens.  Doesn't appear broken on C# or XAML.

![search-solution-fails](https://cloud.githubusercontent.com/assets/6309070/24013713/8c6f868c-0a3f-11e7-96d1-ca6040b3d55c.gif)

#### Known workarounds

None.

#### Related information 

Latest F# nightly.

**Comment by saul** [comment]
This is also an issue with Ctrl+Q (and Alt+Enter?). Was it not fixed in #2606?

**Comment by vasily-kirichenko** [comment]
`Alt+'`, `Ctrl+;`, `Ctrl+Q` do not for me on latest nightly. `Alt+Enter` works, but I set the binding manually yesterday (and for `Alt+'` as well, it's stopped working).

**Comment by cartermp** [comment]
Seems like something serious has regressed and we're swallowing common keybindings.  I have no idea what could be causing this, and lack context on anything which could have changed on the VS side of things.  @JoshVarty would you know more?

**Comment by JoshVarty** [comment]
On `15.4.1.17031702` I can repro for `Ctrl+;` and `Ctrl+Q`. (Both global commands)

`Alt+Enter` and `Alt+'` work for me. For these two ensure you've installed `15.4.1.17031601` or later.

I'll investigate why global commands seem to be swallowed.

**Comment by JoshVarty** [comment]
Interestingly not all global commands are affected. `Ctr+'` (`Team.TeamExplorerSearch`) and `Ctr+,` (`Edit.GoToAll`) work fine.

Also there has been a relevant issued opened at Roslyn here: https://github.com/Microsoft/visualfsharp/issues/2335

**Comment by JoshVarty** [comment]
More info:

**Chord**: `Ctr+Q`
`pguidCmdGroup` : `{d63db1f0-404e-4b21-9648-ca8d99245ec3}`
`commandId` : `18`
CommandName: [`VSStd11CmdID.GlobalSearch`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.vsconstants.vsstd11cmdid.aspx)

**Chord**: `Alt+'`
`pguidCmdGroup` : `{d63db1f0-404e-4b21-9648-ca8d99245ec3}`
`commandId` : `20`
CommandName [`VSStd11CmdID.SolutionExplorerSearch`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.vsconstants.vsstd11cmdid.aspx)

Both commands are routed through [here](https://github.com/dotnet/roslyn/blob/84bc7eea2e05e9d9d7e1b53c2a107c0ac9857a72/src/VisualStudio/Core/Def/Implementation/AbstractOleCommandTarget.Execute.cs#L72) for both F# and C#. This suggests that there aren't any problems with Roslyn's `AbstractOleCommandTarget`.

Next I'll look at the editor chain of `IOleCommandTargets` to figure out where this command should end up and why it's not making it there.

**Comment by majocha** [comment]
Commenting out the export here 
[https://github.com/Microsoft/visualfsharp/blob/30cd23e6f70b7688c034e2c1ea5eef9eed9b2be4/vsintegration/src/FSharp.Editor/Commands/FsiCommandService.fs#L76](https://github.com/Microsoft/visualfsharp/blob/30cd23e6f70b7688c034e2c1ea5eef9eed9b2be4/vsintegration/src/FSharp.Editor/Commands/FsiCommandService.fs#L76)

fixes `Ctrl-Q` and `Ctrl-;`

**Comment by JoshVarty** [comment]
I believe the problem lies here: https://github.com/Microsoft/visualfsharp/blob/30cd23e6f70b7688c034e2c1ea5eef9eed9b2be4/vsintegration/src/FSharp.Editor/Commands/FsiCommandService.fs#L39-L44

I haven't written F# much but I believe this is always returning `VSConstants.S_OK` so the command is never routed back to the shell where it would be properly handled. Returning `VSConstants.S_OK` essentially says "I have handled the command".

I think you want something like:
```
if nCmdId = uint32 VSConstants.VSStd11CmdID.ExecuteSelectionInInteractive then
    Hooks.OnMLSend projectSystemPackage.Value FsiEditorSendAction.ExecuteSelection null null
    VSConstants.S_OK
elif nCmdId = uint32 VSConstants.VSStd11CmdID.ExecuteLineInInteractive then
    Hooks.OnMLSend projectSystemPackage.Value FsiEditorSendAction.ExecuteLine null null
    VSConstants.S_OK
OleConstants.OLECMDERR_E_NOTSUPPORTED
```

**Comment by JoshVarty** [comment]
@majocha I believe that should fix these keybindings but probably breaks `Alt+Enter` and `Alt+'`

**Comment by majocha** [comment]
Yes, it's just indication of the problem. I think the logic in the ifs ladder is a bit wrong and it returns S_OK where it shouldn't, swallowing some commands.

**Comment by majocha** [comment]
Probably we should rewrite it all using Roslyn helpers...

**Comment by JoshVarty** [comment]
It should be alright for now. I'm actually (in my normal work) redesigning commanding within the editor so Roslyn, F# etc. don't need to use this `IOleCommandTarget` at all. I'm hoping that should simplify things for all language services.

**Comment by majocha** [comment]
```F#
    interface IOleCommandTarget with
        member x.Exec (pguidCmdGroup, nCmdId, nCmdexecopt, pvaIn, pvaOut) =
            if pguidCmdGroup = VSConstants.VsStd11 && nCmdId = uint32 VSConstants.VSStd11CmdID.ExecuteSelectionInInteractive then
                do Hooks.OnMLSend projectSystemPackage.Value FsiEditorSendAction.ExecuteSelection null null
                VSConstants.S_OK
            elif pguidCmdGroup = VSConstants.VsStd11 && nCmdId = uint32 VSConstants.VSStd11CmdID.ExecuteLineInInteractive then
                do Hooks.OnMLSend projectSystemPackage.Value FsiEditorSendAction.ExecuteLine null null
                VSConstants.S_OK
            elif pguidCmdGroup = Guids.guidInteractive && nCmdId = uint32 Guids.cmdIDDebugSelection then
                do Hooks.OnMLSend projectSystemPackage.Value FsiEditorSendAction.DebugSelection null null
                VSConstants.S_OK
            elif not (isNull nextTarget) then
                nextTarget.Exec(&pguidCmdGroup, nCmdId, nCmdexecopt, pvaIn, pvaOut)
            else
                VSConstants.E_FAIL
```
should work...

**Comment by JoshVarty** [comment]
Out of curiosity, do I need the `do` keyword on `Hooks.OnMLSend projectSystemPackage.Value FsiEditorSendAction.ExecuteLine null null`?

It seems work without it, but I don't know what it does.

**Comment by majocha** [comment]
No,, it's optional. I used it to indicate what doesn't return a value.

**Comment by saul** [comment]
@majocha while you're looking at this stuff, do you mind taking a look at why the "Move up" and "Move down" context menu commands on folders (I think?) in the solution explorer. I imagine it's exactly the same bug that you're seeing here. 

Great work by the way :)

**Comment by JoshVarty** [comment]
@saul It's probably unrelated since the solution explorer handles commands independently from the editor. Solution folders have been a constant source of pain and introduce a class of problems of their own. :(

**Comment by majocha** [comment]
Yes, from debugging it seems FSharpFolderNode is never being queried for any FSharpProjectCmdSet commands.
