### ISSUE TITLE
using debug VSIX on VisualFSharp.sln: Assert failed in unused opens

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2632]
using debug VSIX from master (minus #2612), loading CompileOps.fs and waiting for type check to complete in the solution:

![image](https://cloud.githubusercontent.com/assets/87944/24023236/24472288-0aab-11e7-8146-fab394cab42e.png)

**Comment by smoothdeveloper** [comment]
another one when opening the script from #2610 but there is no clear part in stack trace:

![image](https://cloud.githubusercontent.com/assets/87944/24024025/81103108-0ab0-11e7-8a4a-a27bf6d2cbad.png)

**Comment by dsyme** [comment]
Should be fixed by https://github.com/Microsoft/visualfsharp/issues/2632
