### ISSUE TITLE
Referencing a VS 2017 created C# Portable Class Library shows a warning in the reference icon.

### ISSUE THREAD

**Issue by OnurGumus** [Microsoft/visualfsharp#2636]
**Repro steps from VS 2017**:

1. Create a Class Library (Portable) C# project and accept the default targets.
2. Create an F# Console Application Targeting .NET 4.6.2
3. Attempt to add a reference to the portable project from the F# Console App.

**Expected behavior**

It adds the reference without any warnings.

**Actual behavior**

It adds the reference but with a warning icon:

![image](https://cloud.githubusercontent.com/assets/4114592/24045643/6f1c9de2-0b28-11e7-91b8-00c048f1cc8d.png)

**Known workarounds**

None.

**Related information**

Running on VS 2017 RTM with nightly F#.
Note that besides this warning sign, everything seems to work correctly. You can use the reference and compile the code just fine.

**Comment by OnurGumus** [comment]
Also note that these new portables is somewhat different than the portables created in VS 2015. In VS 2015's portables we did not have project.json. Also old portables target profiles like Profile111. These new ones  are rather different in their respective project files.

**Comment by cartermp** [comment]
Closing this out - PCLs are deprecated (including the project.json variants which were meant to act as a stopgap measure for various issues with xproj), and starting with 15.6 you can reference .NET Standard projects from .NET Framework.
