### ISSUE TITLE
ASP.NET 5 (vNext) Support

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#264]
About [ASP.NET 5 (vNext)] running on the full .NET Framework.

there are some feature who are needed for it, like:

- [Assembly Neutral Interfaces]
- In memory compilation and pdb

is this the repo or is fsharp/fsharp or [vNext repo] ?

Sry if it is an useless issue, but i think is good to track this because is important

ref [uservoice]

[ASP.NET 5 (vNext)]: http://www.asp.net/vnext
[vNext repo]: https://github.com/aspnet/home
[Assembly Neutral Interfaces]: https://github.com/aspnet/Home/wiki/Assembly-Neutral-Interfaces
[uservoice]: http://fslang.uservoice.com/forums/245727-f-language/suggestions/6717137-allow-for-completely-in-memory-compilation

**Comment by KevinRansom** [comment]
Clearly this is something that is a priority for the ASP, .Net framework, Clr and Managed Languages teams and will be a priority for us.  We are in the process of finalizing how F# will fit into this new cross platform open source world.  We will be updating our roadmap for F# and that will include information on coreclr and asp vnext support.

Right now the very best thing the community can focus on is fixing F# bugs for VS 2015.

**Comment by enricosada** [comment]
@KevinRansom good to know!

/cc @panesofglass

> how F# will fit into this new cross platform open source world

No offense meant, but this sound really marketing speak :smile:

**Comment by panesofglass** [comment]
That's unfortunate. As someone who is using F# primarily as a web platform, I see this as very important. @enricosada, you can see current state of F# support for vNext at https://github.com/YoloDev/YoloDev.FSharp.AspNet.

**Comment by dbettin** [comment]
"We are in the process of finalizing how F# will fit into this new cross platform open source world."  Isn't  this something that should be "finalized" in the open?

I find support for both .Net Core and  Asp.Net 5 hugely important for F# and its growth.  They are people waiting to help out on this front.  Fixing bugs and moving F# into the next generation is not  a zero-sum game.

**Comment by forki** [comment]
I think this is mainly a communication issue. Some twitter comments by members of the ASP.NET raised serious concerns about the future. I'm sure this will all work out somehow and smart people are thinking about solutions, but the communication about this is really bad.

**Comment by enricosada** [comment]
I think I wrote badly my comment, the /cc was not about the marketing speak ( i was joking about it) and was not an attack to @KevinRansom or the team. I need more newline :smile: 

I was curious about the roadmap, and how i can help. 
I know if i try to do something on .netcore and vNext now is pretty useless, if is going to be replaced by a microsoft implementation, so better focus on other visualfsharp issues. 
If in progress i'd like to help try it and send feeback (more on netcore than vNext)

Maybe an high level roadmap can help. 
Netcore and vNext are open question, last time (winrt, xaml, wpf, mvc, azure) the other side was closed source, now is not and is doing a really good job about explain the vision and engage community for new features. Btw you too @KevinRansom and @latkin  ! 

I read time ago in the @davidfowl blog about vNext plugin status and @YoloDev work, the compiler issues and todo, and i think some people want to help (but maybe they dont have much interest now in the f# tools visual studio extension or fsi)

**Comment by dsyme** [comment]
Is it possible for someone in the community to take the @YoloDev work and iterate on it?  Those kinds of experiments are always useful. 

(FWIW I don't think either this repo or fsharp/fsharp are technically the right place to do this, though it's ok to chat about it here :) )
