### ISSUE TITLE
Editor does not replace tabs with spaces

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2642]
![1](https://cloud.githubusercontent.com/assets/873919/24051177/5634a634-0b42-11e7-9204-f3d998dba299.gif)

**Comment by cartermp** [comment]
Works just fine for me on nightly `15.4.1.17031702`:

![f1-works](https://cloud.githubusercontent.com/assets/6309070/24051823/9df56fc8-0af0-11e7-9fea-6e56939ac295.gif)

**Comment by vasily-kirichenko** [comment]
This setting was switched by itself 

![image](https://cloud.githubusercontent.com/assets/873919/24052041/2e067aa4-0b45-11e7-810c-7bd85142ea58.png)

No idea how it's possible :(

**Comment by dsyme** [comment]
I saw that once too (not recently)
