### ISSUE TITLE
Marshaling multi-case struct unions causes run-time errors

### ISSUE THREAD

**Issue by pblasucci** [Microsoft/visualfsharp#2647]
An otherwise valid and working struct union will cause run-time errors when used with functions on the `System.Runtime.InteropServices.Marshal` type. (Note: I didn't test ever possible function on the `Marshal` type).

#### Repro steps

1. Define a small struct union
    ``` fsharp
    [<Struct>]
    type Msg = 
      | One of name :string
      | Two of key :int

    [<Struct>]
    type Msg2 = 
      { name :string
        key :int
        tag :int }
    ```

2. Instantiate and use with `Marshal` functions
    ``` fsharp
    open System.Runtime.InteropServices
    let msg = Two 42
    let size = Marshal.SizeOf(msg)  // <<< will fail

    let msg2 = { name = null; key = 42; tag=1 }
    let size = Marshal.SizeOf(msg2)  

    // ... alternately ...
    let buffer = Marshal.AllocHGlobal(64) // HACK: just assumed a much larger size
    Marshal.StructureToPtr<Msg>(msg, buffer, false) // <<< will fail

#### Expected behavior

`Marshal.SizeOf()` correctly reports size _and_ `Marshal.StructureToPtr()` correctly moves bytes. In other words, the same behavior which occurs when using an explicit struct.
 
#### Actual behavior

Functions on the `Marshal` type raise run-time exceptions.

#### Known workarounds

None.

#### Related information 

Provide any related information 

* Windows 10
* FSharp.Core 4.1 (from Nuget)
* .NET Runtime v 4.6.2
* Visual Studio 2017 (with nightly release of F# Tooling: 15.4.1.17031702)

**Comment by pblasucci** [comment]
FWIW, I am _not_ seeing this behavior with struct records. They work as one would expect.

**Comment by dsyme** [comment]
> 1. Define a small struct union

In your repro code you don't put ``[<Struct>]`` - I assume you did that in practice? thanks

**Comment by pblasucci** [comment]
Whoops! My bad.  :-(

Yes. The actual code _did_ apply the `[<Struct>]` attribute. I've update the repo steps accordingly.

Sorry for any confusion.

**Comment by dsyme** [comment]
@pblasucci The underlying reason for this is that the struct union type is not marked "sequential"

The bigger picture is that multi-case struct unions currently use a set of fields which are the union of all the different cases, plus a tag. This is obviously non-optimal in many cases, and in the future we may change this to use actual .NET IL union types that use overlapping fields, or which share fields between different cases. For this reason I don't think we want to use "Sequential" layout or encourage marshaling for struct unions at this time? Single case struct unions may be a different story though, clearly they should be sequential and marshalable.

**Comment by pblasucci** [comment]
Thanks, @dsyme. This actually makes a lot of sense. Maybe this is just a documentation issue?

**Comment by cartermp** [comment]
@pblasucci I'm tracking work (which I'm currently doing) here: https://github.com/dotnet/docs/issues/1677

Would love to get your input on this area if you think it's worth documenting.

**Comment by pblasucci** [comment]
I'm going to close this since it's really a documentation issue and being track by @cartermp
