### ISSUE TITLE
Inlining struct static methods in debug mode will result TypeLoadException during the execution (based on the generated IL, the struct will be wrapped in System.Tuple`N)

### ISSUE THREAD

**Issue by zpodlovics** [Microsoft/visualfsharp#2661]
#### Please provide a succinct description of the issue:

Inlining struct static methods in debug mode will result  System.TypeLoadException : The generic type 'System.Tuple`2' was used with an invalid instantiation in assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Based on the generated IL that the struct for some reason the struct wrapped to System.Tuple when it use the static inline method in debug mode.

#### Repro steps

1. fsc -a test.fs

2. peverify test.exe

test.fs contains:
```fsharp
module Tests

open System

[<NoEquality; NoComparison>]
[<Struct>]
type StructInt32 =
    val mutable Value: int32
    new(value) = { Value = value }
    static member Write(value, x: StructInt32 byref) =
        x.Value <- value;
    static member inline InlineWrite(value, x: StructInt32 byref) =
        x.Value <- value;

let initialValue = 2
let newValue = 3

let ``StaticWriteResultANewValue`` () =
    let mutable v = StructInt32(initialValue);
    StructInt32.Write(newValue, &v);
    let result = v.Value
    (newValue, result)

let ``StaticInlineWriteResultANewValue`` () =
    let mutable v = StructInt32(initialValue);
    StructInt32.InlineWrite(newValue, &v);
    let result = v.Value
    (newValue, result)

Error Message:
 System.TypeLoadException : The generic type 'System.Tuple`2' was used with an invalid instantiation in assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.

```

#### Expected behavior

No runtime error. Successful unit tests.

#### Actual behavior

Exception when compiled and executed in debug mode:

System.TypeLoadException : The generic type 'System.Tuple`2' was used with an invalid instantiation in assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.

#### Known workarounds

1. Compile and Execute in Release mode, OR
2. Use a curried `let` function instead of a static member method

**Comment by dsyme** [comment]
I checked:  this repros with both F# 4.0 and 4.1

Changing to use a curried ``let`` function works
```
let inline InlineWrite value (x: StructInt32 byref) =
        x.Value <- value;
```

**Comment by dsyme** [comment]
fixed by PR above
