### ISSUE TITLE
Syntax highlighting fails when using for...to inside a computation expression

### ISSUE THREAD

**Issue by dhwed** [Microsoft/visualfsharp#2680]
If you use a `for...to` expression inside of a computation expression, the syntax highlighting is wrong:

![image](https://cloud.githubusercontent.com/assets/10184638/24215596/46160cac-0f07-11e7-893b-9345e18eda5d.png)

I'm using VS 2017 RTM with the VisualFSharpOpenSource.vsix compiled from master.

Here's the code from the screenshot:
```fsharp
module SyntaxHighlightingBug =
    let list1 = [ for x in [0;1] do yield x ]
    let list2 = [ for x = 0 to 1 do yield x ]
    let list3 = [ for x = 0 to 1 do yield x.ToString() ]
    let list4 =
        [ for x = 0 to 1 do // comment
            let x = x // comment
            yield x // comment
        ]
    let list5 =
        [ for x = 0 to 1 do // comment
            let x = x.ToString() // comment
            yield x // comment
        ]
```

**Comment by vasily-kirichenko** [comment]
I can reproduce it on master

![image](https://cloud.githubusercontent.com/assets/873919/24217157/f3c6ffb2-0f4f-11e7-966e-9ceaee5d6582.png)

@dsyme I'm really puzzled with this. Any tips what could go wrong?

**Comment by cloudRoutine** [comment]
@vasily-kirichenko 
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ExtensibilityTools

![](http://i.imgur.com/YR1FJlU.png)
adds this toolbar on the bottom 

it lets you see the classifiers so that leads me to believe it's the semantic colorization function that's acting up

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2681
