### ISSUE TITLE
OptionalAttribute and DefaultParameterValueAttribute is not output to signature file by --sig option

### ISSUE THREAD

**Issue by hafuu** [Microsoft/visualfsharp#2684]
#### Repro steps

1. Compile following code with `--sig` option and generate signature file.
```
namespace Library1
open System.Runtime.InteropServices
type A() =
  member this.M([<Optional; DefaultParameterValue("")>]x: string) = ()
```

#### Expected behavior

`OptionalAttribute` and `DefaultParameterValueAttribute` is output to signature file.

#### Actual behavior

`OptionalAttribute` and `DefaultParameterValueAttribute` is not output.

```
namespace Library1
  type A =
    class
      new : unit -> A
      member M : x:string -> unit
    end
```

#### Known workarounds

none

#### Related information 

Windows 10, F# 4.1, Visual Studio 2017

**Comment by dsyme** [comment]
Covering problems with the ``--sig`` option by the single bug https://github.com/Microsoft/visualfsharp/issues/393
