### ISSUE TITLE
When "module rec" is used, a file that can not be compiled is output by --sig option

### ISSUE THREAD

**Issue by hafuu** [Microsoft/visualfsharp#2685]
#### Repro steps

1. Compile following code with `--sig` option and generate signature file.
```
module rec Library1

[<Struct>]
type A = A of B

[<Struct>]
type B = B
```

2. Add the generated signature file to project.

#### Expected behavior

It generates the compilable signature.

#### Actual behavior

A compile error occurs: Unexpected keyword 'and' in signature file.

```
module Library1
[<StructAttribute ()>]
type A = | A of B
[<StructAttribute ()>]
and B = | B
```

#### Known workarounds

Edit the generated signature file manually as follows:

1. replace `and` to `type` for `type B`
2. add `rec` keyword after `module` keyword

```
module rec Library1
[<StructAttribute ()>]
type A = | A of B
[<StructAttribute ()>]
type B = | B
```

#### Related information 
Windows, Visual Studio 2017, F# 4.1

**Comment by FunctionalFirst** [comment]
Isn't the issue that `[<StructAttribute>]` is in the wrong position? It should be after `and`.

**Comment by dsyme** [comment]
Covering problems with the --sig option by the single bug #393
