### ISSUE TITLE
Numbers with underscores cause compilation error sometimes

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2701]
![image](https://cloud.githubusercontent.com/assets/873919/24330474/a06d700a-1227-11e7-9936-dbff82df38cf.png)

I cannot reproduce it with code like:
```fsharp
[1..5] |> List.mapi (fun i n -> sprintf "%06d" (n + 1_000_000));;
```

**Comment by forki** [comment]
Ok I can repro on master.

**Comment by forki** [comment]
fix in https://github.com/Microsoft/visualfsharp/pull/2702
