### ISSUE TITLE
Better style for Quick Info links 

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2703]
I find style used for links on Quick Info tooltips is a bit heavyweight:

![1](https://cloud.githubusercontent.com/assets/873919/24333669/cebae7a2-1264-11e7-893e-fc07e0b2d487.gif)

I've found this XAML to customize links http://www.java2s.com/Tutorial/CSharp/0470__Windows-Presentation-Foundation/TextBlockUnderlinedecorationwithdashes.htm:

```xml
<StackPanel>
      <TextBlock FontSize="24" Width="180" VerticalAlignment="Center">
        The lazy dog
        <TextBlock.TextDecorations>
          <TextDecoration Location="Underline" 
            PenThicknessUnit="FontRecommended">
            <TextDecoration.Pen>
              <Pen Brush="Red" Thickness="1">
                <Pen.DashStyle>
                  <DashStyle Dashes="5"/>
                </Pen.DashStyle>
              </Pen>
            </TextDecoration.Pen>
          </TextDecoration>
        </TextBlock.TextDecorations>
      </TextBlock>
  </StackPanel>
```
I have no idea how to port it to our code though.

**Comment by majocha** [comment]
We should probably upgrade the current code to XAML. Styling in imperative code one can quickly go crazy :)

I just figured out how to load XAML :sweat_smile: so I'll try to refactor it ASAP into proper controls.

**Comment by saul** [comment]
I think a pen offset of 1px and an opacity of ~60/70% will make it feel a lot lighter.

**Comment by cloudRoutine** [comment]
@majocha let's also build a custom options page to allow more tooltip customization 
 
- scale with editor
- max dimensions
- enable scrolling
- which kinds of information to include (assembly, exceptions, etc)
- hide on mouse move
- show original typeinfo for alias
- full typeinfo on parameters 
- collapse overloads

I'm sure there are other useful parameters that I've left out.

**Comment by majocha** [comment]
I like @saul 's idea very much. We could go even lower with opacity but leave underline always on for discoverability.
With PenOffset 1 and A set to 0x64:
<img width="1065" alt="2017-03-27" src="https://cloud.githubusercontent.com/assets/1760221/24351282/680a656a-12e5-11e7-92f0-0731943b14d8.png">
<img width="998" alt="2017-03-27 1" src="https://cloud.githubusercontent.com/assets/1760221/24351284/69f8099a-12e5-11e7-95a2-ed376f44313c.png">

**Comment by vasily-kirichenko** [comment]
@majocha looks great :) PR?

**Comment by majocha** [comment]
@vasily-kirichenko will do a PR to @cloudRoutine' s one in a few hours when I'm back at my PC.

**Comment by majocha** [comment]
Code is here:
[https://github.com/cloudRoutine/visualfsharp/pull/2/commits/b21a41aae63c25f2a6edb4ad3e648b06c6f62c2e](https://github.com/cloudRoutine/visualfsharp/pull/2/commits/b21a41aae63c25f2a6edb4ad3e648b06c6f62c2e)

**Comment by majocha** [comment]
I've been thinking about copying some tried and tested code from [FsXaml](https://github.com/fsprojects/FsXaml). Namely the [utilities](https://github.com/fsprojects/FsXaml/blob/master/src/FsXaml.Wpf/Utilities.fs) to load XAML from resources. It would be useful in loading markup for options pages and also with Quick Info.
@ReedCopsey would you be OK with this?

/cc @vasily-kirichenko for opinion/advice

**Comment by vasily-kirichenko** [comment]
@majocha do whatever you want if it simplify the XAML related code. I know close to nothing about this stuff.

**Comment by saul** [comment]
@majocha is there a reason why we can't just take a NuGet reference on FsXaml?

**Comment by majocha** [comment]
@saul I'm not sure. We can't use it as intended, because of the type provider IIUC.

**Comment by vasily-kirichenko** [comment]
Yes, we should not use FsXaml because it would conflict with its newer versions being used in users' projects. We learned this in VFPT.

**Comment by smoothdeveloper** [comment]
@saul one reason I know of is that when VS loads a type provider in the process, it becomes impossible to have that same type provider (but another version) handled in your project. @ReedCopsey faced that issue and was forced to push updates to VFPT for that reason on each new release of FsXaml.

I think this could call for starting to use paket and file dependencies (we can commit the file as well to face situation where original file disappear).

**Comment by vasily-kirichenko** [comment]
The style is ok and customizable now. Closing it.
