### ISSUE TITLE
FSharp.Core that used in the proto compiler

### ISSUE THREAD

**Issue by AviAvni** [Microsoft/visualfsharp#2704]
When investigating the bug https://github.com/Microsoft/visualfsharp/pull/2702
I found that the proto compiler use FSharp.Core 4.4.0
from the lkg https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Compiler-proto/FSharp.Compiler-proto.fsproj#L449
The problem is that changes to FSharp.Core not affect the build of this repository until someone update the lkg
It's means some performance that done not affect the build
And maybe some more problems

**Comment by dsyme** [comment]
It's correct to use the lkg. The proto compiler is built by the lkg and should run with its fsharp.core.

**Comment by forki** [comment]
ok can we change it to update the lkg then?
