### ISSUE TITLE
Limit "Go to all" results to improve performance

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2710]
"Go to all" currently causes a UI freeze of around 10 seconds on my machine when I try to search for something broad like "a". Even if I have a particularly narrow search, the freeze is still very noticeable.

I originally thought this was because we were doing an async as RunSyncronously, but it turns out 99.9% of the time is spent in WPF UpdateLayout. I assume this is because we're returning a huge number of results - it makes more sense if we 'cap' the number of results we return to the top 50 or so.

I'm not sure if this is a Roslyn bug or something we can fix on the F# side.

#### Repro steps

1. Open VisualFSharp.sln
2. Go to all > Search "a"
3. See the UI freeze

#### Expected behavior

No UI freeze

#### Actual behavior

UI is frozen for many seconds

#### Related information

![image](https://cloud.githubusercontent.com/assets/64654/24376804/1e1f8f48-1335-11e7-9ae2-cb0a8368c74e.png)

**Comment by cloudRoutine** [comment]
we could also batch collect the results in the background and throttle the publishing

**Comment by majocha** [comment]
I tried to do this with a sizeable C# solution (Roslyn). Much worse freeze.

**Comment by cloudRoutine** [comment]
How did you implement it?

**Comment by majocha** [comment]
Miscommunication :) I tried `Ctrl-T`
Looking at the interface of `INavigateToSearchService` it only allows for per-project granularity. We can't do anything on our side. Returning not all results would be incorrect. It's simply not optimized in Visual Studio.

**Comment by majocha** [comment]
One idea that comes to mind:
Don't use fuzzy matching for one char search pattern.

Another:
For single letter return only results that start with it.

**Comment by saul** [comment]
@majocha are you saying the problem also exists in large C# solutions?

**Comment by majocha** [comment]
@saul it surely seems so.

**Comment by vasily-kirichenko** [comment]
We returned empty list on single-character filter in VFPT. We could do the same here. Agree?

**Comment by majocha** [comment]
@vasily-kirichenko and what if I'm looking for a single letter identifier :)?

**Comment by vasily-kirichenko** [comment]
OK, we can return exact match for single char.

**Comment by cartermp** [comment]
Exact match for single char seems like a good approach.

**Comment by saul** [comment]
I'm going to raise an issue with Roslyn as well as it's more of a fundamental issue with rendering a huge amount of results.

**Comment by vasily-kirichenko** [comment]
https://github.com/Microsoft/visualfsharp/pull/2716 However, it works OK on my machines. No blazing fast, but definitely usable.

**Comment by saul** [comment]
Closing as this is definitely a platform problem and not an F# issue. See https://github.com/dotnet/roslyn/issues/18253

@vasily-kirichenko you may as well close your PR.
