### ISSUE TITLE
Accessibility and Mutable Highlights

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2714]
**Note:**  This is a tracking issue for accessibility, but there is no action to take at this time.

I spoke with @dpoeschl about accessibility requirements for default colorization in the Blue Theme for VS.  This is the theme which has requirements in this area.  Colorization for mutables does not fall within the required contrast ratio.  Same with other colors we use.  That said, Roslyn also uses default colors which fall short of these requirements.  We'll be hearing back about this in the future, at which point I'll take one of the following actions:

1. Close this issue and forget about it.  That means it won't be a problem.
2. Add this issue to the VS Updates milestone.  We'll have to pick a default color (or colors) which meet accessibility requirements for the contrast ratio in the Blue Theme for VS.

**Comment by vasily-kirichenko** [comment]
I don't even understand what it's all about.

**Comment by cartermp** [comment]
@vasily-kirichenko Compliance.  A 4.5:1 (or higher) contrast ratio is the bar for accessibility requirements on colors for VS Blue Theme.  Mutables in Blue Theme are at 3:1.  We're below that for other colors as well.  So is Roslyn, though, and because we share some colors there may not end up being any action we have to table.

**Comment by dpoeschl** [comment]
We are still in the process of deciding whether classification colors in particular need to satisfy this 4.5:1 requirement.

**Comment by majocha** [comment]
Currently we don't have separate theme for Blue vs Light. Both use the same set of colors. Personally I'm all for making mutables red again :)

**Comment by vasily-kirichenko** [comment]
@majocha red makes errors hard to see, same for dark orange.

**Comment by cartermp** [comment]
Looks like we'll have to update the color here.  What we choose will also have to work under light/dark themes and Windows High Contrast White/Black modes.  I'll get a designer to give us a set of colors to choose from.
