### ISSUE TITLE
Structure/ServiceUntypedParse convergence

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2715]
We currently have ServiceUntypedParse for traversing UASTs.  It was not sufficient for support Structured Guidelines, so @cloudRoutine built [`Structure.fs`](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Structure/Structure.fs).  There are similar goals here.  It could also be the case that Structure solves some problems in existing code in ServiceUntypedParse. Perhaps it's worth seeing what some convergence here would look like.  Surely, any way to push functionality in Structure benefits FCS as a whole, which helps more than just VS.

**Comment by dsyme** [comment]
You're correct that this is the right plan. We need to take a pass over quite a bit of recently added FCS surface area

I'll close this since it's really a general issue about improving the FCS api, we won't track everything separately for that
