### ISSUE TITLE
'do' within a match case causes incorrect indent guidelines

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2717]
![image](https://cloud.githubusercontent.com/assets/64654/24424753/a643bc40-13f9-11e7-970e-ab0afdd8089d.png)

`do` seems to break indent guides within match case blocks

cc @vasily-kirichenko if you point me in the right direction I'm willing to try and fix this myself 👍

**Comment by smoothdeveloper** [comment]
@saul you might look at https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Structure/Structure.fs 
@cloudRoutine surely knows better to help you with more accurate details.

**Comment by cloudRoutine** [comment]
@saul the parsing to identify the ranges for outlining happens in https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Structure/Structure.fs

**Comment by saul** [comment]
Thanks guys - will take a look now. I was searching for "indent" and "guide" which wasn't helping...

**Comment by cloudRoutine** [comment]
the problem is that not all syntax constructs are represented in the UAST and sometimes the ranges provided by the UAST are wrong. 

iirc the `do` doesn't show up in certain contexts

**Comment by cloudRoutine** [comment]
@saul you can close this issue, i added this case to https://github.com/Microsoft/visualfsharp/issues/2431

**Comment by saul** [comment]
Duplicate of #2431
