### ISSUE TITLE
Fields are not shown as being part of their encapsulating type in 'Go to'

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2719]
![image](https://cloud.githubusercontent.com/assets/64654/24425193/2c3681ce-13fb-11e7-953e-e2685177eb18.png)

I'm expecting the red boxed "namespace Library1" to read "type MyRecord".

P.S. apologies for the influx of reports - I spend my day using the F# nightlies at work and take note of all the issues I'm finding.

**Comment by cartermp** [comment]
@saul 👍 on the reports.  More folks using it with day-to-day projects the better!
