### ISSUE TITLE
AutoComplete - Keywords appearing in completion list during '.' completion

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#2723]
![](http://i.imgur.com/sIJepDp.png)

![](http://i.imgur.com/7eU4vGs.png)

They should not be appearing in this completion context

cc @vasily-kirichenko

**Comment by vasily-kirichenko** [comment]
It was fixed some time ago. I cannot reproduce it on master. @cartermp close this please.
