### ISSUE TITLE
can't type "match / with" properly if there is a function with "with"

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2731]
Using nightly 15.4.1.17032701, having this code:

```fsharp
let inline endsWith text x = (^a:(member EndsWith:string->bool)x, text) 
```

I can't type `match x with` without `with` being changed to `endsWith`, the workaround is to type ESC before ENTER

**Comment by 0x53A** [comment]
similar with ``for x in y do``, if you instantly press enter after ``do``, it will complete to ``double``, but if you wait a little bit, it will keep the ``do``.

**Comment by dsyme** [comment]
That needs to be fixed :)

**Comment by vasily-kirichenko** [comment]
![1](https://cloud.githubusercontent.com/assets/873919/24470856/0432701a-14c9-11e7-8874-2cd629b3bd0f.gif)

**Comment by vasily-kirichenko** [comment]
About `do`, it's the old good dreadful range operator, which spreads from `f` in `for` to `do` and father. So we detect completion context as `Some RangeOperator`. We don't return keywords into completion list if context <> `None`, so the result.

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko somehow this is what I have (what tool do you use instead of licecap to get the completion captured properly?):

![vswith](https://cloud.githubusercontent.com/assets/87944/24475926/d7fa9f5a-14d1-11e7-90f9-c650acf25377.gif)

**Comment by vasily-kirichenko** [comment]
licecap only. so you press Enter at the end?

**Comment by smoothdeveloper** [comment]
Yes enter, sometimes even before the list pops up.

**Comment by vasily-kirichenko** [comment]
Are keywords and "xxx (open yyy)" stuff in the list?

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko no, not sure why it is not there. Do you suspect my VF# tools aren't the one we expect?

I checked again and it is  15.4.1.17032701:

![image](https://cloud.githubusercontent.com/assets/87944/24505747/562e95fa-155b-11e7-9dc9-bdc386b4b2cd.png)

**Comment by vasily-kirichenko** [comment]
yes, they are outdated. Nightly is broken March, 27.

**Comment by cartermp** [comment]
We've got a broken build right now (not in CI, but internally) preventing a nightly from going out.  @KevinRansom is getting it fixed.

**Comment by dsyme** [comment]
Closing as this has been fixed
