### ISSUE TITLE
Type Provider / Intellisense UX Improvement

### ISSUE THREAD

**Issue by xenocons** [Microsoft/visualfsharp#2747]
When certain references go missing from a project, unhelpful UX can occur in the form of missing or hidden error messages. I am not sure if this belongs in visualfsharp or FSharp.Data, I have a feeling that it may be really a limitation in how type providers work, but there might be some smoothness that can be hacked into the VS UX to make things easier.

#### Repro
1. Create a new solution, add 2 F# class library projects.
2. Add FSharp.Data (via nuget) to both.
3. In first project (Library1):
````
namespace Library1
module TypeTestFast = 
    open FSharp.Data
    type TestData = XmlProvider<"<xml><data>abc</data></xml>",InferTypesFromValues=false,Global=true>
    let f (x : TestData.Xml) = x.Data
````
4. In second project (Library2), add first project(Library1) as a reference. Then:
````
module Test = 
    let f (x: Library1.TypeTestFast.TestData.Xml) = x.Data
````

So far, everything works. Note all the types in VS are complete and pretty, with no errors.

Now delete System.Xml.Linq from second project (Library2). Observe the strange behaviours:
- In the below, the error message is unhelpful, one would expect to see the actual type signature to be where an error occurs:
![image](https://cloud.githubusercontent.com/assets/3858449/24538426/da771bfa-1634-11e7-947a-c46ec5c0a612.png)
- Hovering over the parameter yields strange results too, even though there is no type signature error, somehow the type is inferred to be `'a`:
![image](https://cloud.githubusercontent.com/assets/3858449/24538462/0e4d9a08-1635-11e7-907a-edcebc589722.png)
- Navigating back to the type signature and trying to trigger intellisense on `TestData` pops up a list:
![image](https://cloud.githubusercontent.com/assets/3858449/24538495/359b1b1c-1635-11e7-8d5f-643f0f347244.png)
- To which you need to scroll to the very top to notice the `<Note>`:
![image](https://cloud.githubusercontent.com/assets/3858449/24538511/4e98fbb6-1635-11e7-8cfd-3470231ce416.png)

#### Expected behavior

Ideally, if there is an unresolved reference detected during the process of intellisense completion, it should be raised on the type signature, and noted with a red squiggly underline.

#### Related information 

Windows, .NET 4.6, VS2017 with F# nightly myfeed.

**Comment by vasily-kirichenko** [comment]
The bug on the last screenshot is fixed in https://github.com/Microsoft/visualfsharp/pull/2755

**Comment by vasily-kirichenko** [comment]
The bug on the third screenshot (keywords in the list after dot) is fixed in https://github.com/Microsoft/visualfsharp/pull/2762

**Comment by dsyme** [comment]
Closing as a the main parts of this have been addressed as mentioned above
