### ISSUE TITLE
Redundant pattern detection fails for simple duplicates cases when active pattern used

### ISSUE THREAD

**Issue by chillitom** [Microsoft/visualfsharp#2754]
Presence of active patterns disables the detection of simple duplicates cases.

```fsharp
        type Foo = A | B | C

        let good = function
            | A -> ()
            | B -> ()
            | B -> () // Squiggly with warning "This rule will never be matched"
            | _ -> ()
            | _ -> () // Squiggly with warning "This rule will never be matched"

        let (|IsA|_|) x = if x = A then Some () else None

        let bad = function            
            | IsA -> ()
            | B -> ()
            | B -> () // no warning
            | _ -> ()
            | _ -> () // no warning
```
When active patterns are present checking whether a match is exhaustive clearly becomes difficult/impossible but duplicate cases can still be detected.

**Comment by dsyme** [comment]
I've labelled it as a feature request.  There has always been some limitations in redundancy checking for APs, we knew that when we implemented them

**Comment by dsyme** [comment]
This is a language suggestion, closing to track by https://github.com/fsharp/fslang-suggestions/issues/586
