### ISSUE TITLE
Can't access full definition of types outside solution

### ISSUE THREAD

**Issue by breyed** [Microsoft/visualfsharp#2757]
Using the nightly build, if I hover over a type defined outside the solution (such as a .NET Framework type), F# nicely shows the type's definition as F# code in the tooltip. It reasonably truncates the view so that the tooltip doesn't get too big.

However, I can't view the definition standalone (useful for seeing all of it and for searching):
* Go To Definition shows the error, "Cannot navigate to the symbol under the caret".
* Peek Definition does nothing.
* Go To Implementation does nothing.

The "does nothing" behaviors in particular make me wonder if this is a nightly build regression. In any case, it's not a good user experience.

**Comment by cartermp** [comment]
@breyed Go to Definition / Peek / Implementation doesn't work for anything other that F# items in your solution.  Cross-C#/VB or .NET Framework metadata is currently unsupported.  #2658 is the work to address the latter.  The former is still a prototype that @saul is working on.

Long story short, it's a lot of work that still needs to be implemented.

**Comment by breyed** [comment]
Thanks for letting me know. I saw #2658 but wasn't sure. It seems sooooo close, since all the info is right there in a tooltip. Just need to break it out of its straitjacket.

**Comment by breyed** [comment]
An alternative would be a View in Object Browser feature, which Go To Definition could fall back to for symbols outside the solution. I'm surprised that Object Browser gets so little love in terms of the IDE navigating into it. It's not so good at searching within type, but otherwise, it's very efficient for learning about an API.

**Comment by cartermp** [comment]
Unfortunately, that likely won't be possible.  I don't think there's a direct way to connect to object browser and find the correct symbol.  That would likely be more work than what #2658 does.

**Comment by breyed** [comment]
The command ClassViewContextMenus.ClassViewProjectReference.ViewinObjectBrowser purports to navigate into the Object Browser, albeit only for a symbol in the solution. So it seems like there's a way. However, it doesn't appear to work, so maybe it's functionality that was dropped at some point. I just reported the following as a problem in VS feedback (not sure how to get a link).

> ClassViewContextMenus.ClassViewProjectReference.ViewinObjectBrowser does nothing

> If you bind a keyboard shortcut to ClassViewContextMenus.ClassViewProjectReference.ViewinObjectBrowser, try as you might, nothing you select in Class View, be it a project, namespace, class, method, etc., does anything when you press the shortcut key.
