### ISSUE TITLE
Block structure incorrect when using proportional font

### ISSUE THREAD

**Issue by breyed** [Microsoft/visualfsharp#2760]
When the F# text editor uses a proportional font, the block structure shows extra lines, sometimes in addition to, sometimes in place of, the desired lines.

#### Repro steps

1. Set the Text Editor font to Calibri.

2. Create an F# file with this code:

```
module test
open System

let x =
    if 3 = 4 then
        5
    else
        6

```

#### Expected behavior

Two block structure vertical lines, like you get if you're using Consolas.

#### Actual behavior

A third, middle block structure line between the two standard ones. Before the `let` line, only this middle line appears.

#### Known workarounds

Use a non-proportional font and buy a wider monitor. :-)

#### Related information 

[Readability data](http://ux.stackexchange.com/q/48753/79277)

**Comment by vasily-kirichenko** [comment]
we don't control the guide lines rendering. Please, report this bug to the Roslyn repository https://github.com/dotnet/roslyn/issues

**Comment by breyed** [comment]
Created dotnet/roslyn#18365
