### ISSUE TITLE
Feedback on the F# Tutorial Project + some minor issues

### ISSUE THREAD

**Issue by CameronAavik** [Microsoft/visualfsharp#2761]
Hello, I decided to play around with F# and noticed the tutorial project so I thought I would go through it. I've had no previous experience with F# but do know a bit about functional programming.

The tutorial [can be found here](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/ProjectTemplates/TutorialProject/Template/Tutorial.fsx)

Here is a list of all the errors/inconsistencies/suggestions

* [45-46](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/ProjectTemplates/TutorialProject/Template/Tutorial.fsx#L45-L46): The description given for modules actually made me more confused about what modules are. The way it is described made me think it was like C# classes, but then you see on line 68 that it actually runs code too. I'm still kind of confused about what they are. I think modules should be better explained here. The ability to place code in the module I don't think is even explained in the linked docs either
* [91](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/ProjectTemplates/TutorialProject/Template/Tutorial.fsx#L91): This makes it sound like `=` is only used for equality, when it is also used in `let` statements and `module` declarations
* [111-112](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/ProjectTemplates/TutorialProject/Template/Tutorial.fsx#L111-L112): This comment should have been made back in the Immutability tutorial when they use `%d` for the first time
* [119](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/ProjectTemplates/TutorialProject/Template/Tutorial.fsx#L119): This uses the 2nd sample function, not the 1st
* [133](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/ProjectTemplates/TutorialProject/Template/Tutorial.fsx#L133): This uses the 3rd sample function, not the 2nd
* [212](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/ProjectTemplates/TutorialProject/Template/Tutorial.fsx#L212): This notation with specifying type with `let` is not mentioned earlier in the tutorial. As well, that `(int*int)` is the notation for the type of a pair that has two ints has not been mentioned yet.
* [333](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/ProjectTemplates/TutorialProject/Template/Tutorial.fsx#L333): This was probably meant to say 2017 and not 2012?
* [742](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/ProjectTemplates/TutorialProject/Template/Tutorial.fsx#L742): Unintended open System?
* [969](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/ProjectTemplates/TutorialProject/Template/Tutorial.fsx#L969): this sentence being printed doesn't make sense. Same as line 979

That's all the issues I had with it. Apart from that, I believe the tutorial taught me enough to get started writing F#.

**Comment by forki** [comment]
Hi, could you please try to send a pull request with your feedback
incorporated. That would be super helpful. Thanks

Am 01.04.2017 09:33 schrieb "Cameron Aavik" <notifications@github.com>:

**Comment by CameronAavik** [comment]
Sure thing.

**Comment by forki** [comment]
Thanks!
