### ISSUE TITLE
Inconsistent indentation rules for `do yield` and `->`.

### ISSUE THREAD

**Issue by nikonthethird** [Microsoft/visualfsharp#2764]
The rules for indentation are different for the expressions `[for a in b do yield { record }]` and `[for a in b -> { record }]`.

#### Repro steps

```fsharp
type A = { A : Unit }
let values = Seq.empty<A>

let doYield = [
    for value in values do yield {
        A = () // OK.
    }
]

let arrow = [
    for value in values -> {
        A = () // Possibly incorrect indentation.
    }
]
```

#### Expected behavior

Both variants should be valid according to the indentation rules.

#### Actual behavior

The sequence expression `doYield` is valid.
The sequence expression `arrow` shows a "possibly incorrect indentation" warning. 

#### Known workarounds

Placing the parenthesis on the next line works.

```fsharp
let arrow = [
    for value in values ->
    {
        A = ()
    }
]
```

#### Related information 

* Windows 10
* Visual Studio 2017
* Using the [nightly tools](https://blogs.msdn.microsoft.com/dotnet/2017/03/14/announcing-nightly-releases-for-the-visual-f-tools/)

**Comment by dsyme** [comment]
@nikonthethird Per CONTRIBUTING.md, please submit to http://github.com/fsharp/fslang-suggestions,thanks
