### ISSUE TITLE
Cannot debug VFT inself anymore - FSharp.Editor has no PDB file

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2771]
* git cleanup
* deleted `c:\Users\me\AppData\Local\Microsoft\VisualStudio\15.0_183b437fFSharpDev` 
* deleted `c:\Users\me\AppData\Roaming\Microsoft\VisualStudio\15.0_183b437fFSharpDev`
* `build vs`
* build VFT solution inside VS
* Ctrl+F5
* attached to the exp instance
* tried to set a breakpoint in several places in FSharp.Editor and FSharp.Language.Service

![image](https://cloud.githubusercontent.com/assets/873919/24585569/ca120d20-1796-11e7-8ced-abfd46cb9cca.png)

**Comment by forki** [comment]
Yes I noticed that as well. Since very recently I can't debug the compiler.
Usually I do:
* git clean -xdf
* build debug
* open vs
* set Fsc as startup project
* F5

I thought I messed up my settings, but since you see something similar...

Am 02.04.2017 10:26 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
wow :((

**Comment by forki** [comment]
Ok so we should investigate if older commits still work. If so we probably
find the one using bisect

Am 02.04.2017 10:30 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
I think the big diff was switching to more nuget VS packages instead of GAC deps.

**Comment by forki** [comment]
Sigh. 
I think @cloudRoutine said something about nuget packages messing up his editor support yesterday. Why is this shit never working? 
OK so what now? Can you reset before that and confirm it broke us?

**Comment by vasily-kirichenko** [comment]
![image](https://cloud.githubusercontent.com/assets/873919/24585794/70a2566e-179b-11e7-8199-10123f7258f2.png)

**Comment by vasily-kirichenko** [comment]
I'm completely stuck on working on VFT at the moment :(

**Comment by cloudRoutine** [comment]
![](http://i.imgur.com/UDmHhkj.png)
![](http://i.imgur.com/40ig3WJ.png)
![](http://i.imgur.com/hjtqrYc.png)

tried adding 
```xml
<IncludeDebugSymbolsInVSIXContainer>true</IncludeDebugSymbolsInVSIXContainer>
  <IncludeDebugSymbolsInLocalVSIXDeployment>true</IncludeDebugSymbolsInLocalVSIXDeployment>
```
to `visualfsharpopensource.csproj`, only seemed to make symbols load faster

after disabling just my code in debug settings

![](http://i.imgur.com/lS7w1xP.png)

Changing the setting suggested in the image below made no difference

![](http://i.imgur.com/CKPK7QY.png)

**Comment by cloudRoutine** [comment]
After trying to set a breakpoint crashed VS

I was able to set some breakpoints that came up as invalid while loading the experimental instance once it was actually running

![](http://i.imgur.com/6NeKDWb.png)

**Comment by vasily-kirichenko** [comment]
I looked at what FSharp.Editor.dll is actually loaded and there no *.pdb in that folder at all:

![image](https://cloud.githubusercontent.com/assets/873919/24588462/2309a0c0-17d1-11e7-85af-fd041aace0b9.png)

**Comment by vasily-kirichenko** [comment]
I've copied *.pdb manually, it's not helped.

**Comment by vasily-kirichenko** [comment]
`'devenv.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\USERS\VASKI\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_183B437FFSHARPDEV\EXTENSIONS\MICROSOFT.VISUALFSHARPTOOLS\VISUAL F# TOOLS\42.42.42.42\FSharp.Editor.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.`

Why the hell it's optimized??

**Comment by sergey-tihon** [comment]
not sure if it is related, but after update to latest nightly, VS2017 asked to install some VS updates ...
After installation I cannot open solutions with F# projects and I found that `VFT` extension is disables

I can do anything about it for now...
<img width="691" alt="vft-disabled" src="https://cloud.githubusercontent.com/assets/1197905/24588701/63cd95b2-17d6-11e7-9dbe-61de5fcb4433.png">

**Comment by cartermp** [comment]
@sergey-tihon Can you run VSIXInstaller to remove the nightly and load F# projects after that? (It should be using the vs2017 RTW version of the tools).

**Comment by cloudRoutine** [comment]
cc @ctaggart

**Comment by cloudRoutine** [comment]
switching back to my `navigable-improvements` branch/PR and the problem disappears

![](http://i.imgur.com/aKPFtnl.png)

so the problem should be within 
https://github.com/cloudRoutine/visualfsharp/compare/navigable-improvements...cloudRoutine:master

**Comment by 0x53A** [comment]
The following fixed it for me: https://github.com/0x53A/visualfsharp/commit/3e11e0bdf804ada5ae91c6b03e07ecffb4cd586c
![image](https://cloud.githubusercontent.com/assets/4236651/24589555/abf14644-17dc-11e7-92f0-d865d5479eea.png)

My money is on disabling optimizations, but I am not 100% sure yet.

**Comment by majocha** [comment]
Thanks @0x53A !  It started to work with your fix, but only after another git clean.

**Comment by 0x53A** [comment]
@majocha you don't need to clean, but you need to change anything in any file, because the up-to-date check doesn't check the ``FSharpSource.Settings.targets``, and so doesn't rebuild by default. I always just added/removed one space in FSharp.Editor when testing this.

**Comment by forki** [comment]
clean is often needed if you want to rebuild proto or when nuget fucked up again.

**Comment by forki** [comment]
This is really really painful

**Comment by majocha** [comment]
Yeah, I'm totally blocked again. Breakpoints fail to bind.

**Comment by cartermp** [comment]
cc @KevinRansom @brettfo - this has to be resolved quickly.

**Comment by vasily-kirichenko** [comment]
Fixed in master.
