### ISSUE TITLE
Queue diagnostics

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2774]
I sometimes find whilst debugging that things like semantic colourisation, structure guidelines or even syntax colourisation can take a while to show. While I'm waiting what's going through my mind is "what the hell is taking so long?"

Currently there is no visibility as to what's going on in the background - I'm absolutely sure that something *must* be happening that's causing the FCS to churn - but I've no idea what. It would be really useful if we had a debug-only output window, such as "FCS" that showed debug output like:

> Added 'Semantic Colourisation' to queue at 21:12:45
> ...
> Processing 'Semantic Colourisation' in queue...
> 'Semantic Colourisation' complete. Queuing for 4 seconds, running for 1 second.

At least this would help us diagnose what's taking so long/what's holding up the queue. I've no idea how to even start tackling this - I'm happy to do it myself but I just don't know where to look.

Any opinions would be appreciated :)

**Comment by cloudRoutine** [comment]
@saul that's what https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Common/Logging.fs is for.  

it's pretty simple to add additional functions that only run in debug mode

**Comment by vasily-kirichenko** [comment]
See https://github.com/dotnet/roslyn/issues/18376

7 SECONDS delay (!) Please, add more noise to that issue to make it fixed sooner.

**Comment by cloudRoutine** [comment]
If you added a message pump to the reactor in addition to the existing traces then all of those messages could be subscribed to by the current output pane, or there could be an additional pane dedicated to writing timestamped reactor messages. 

I find the debug output pane far too cluttered to be useful most of the time and the reactor messages get lost in the chaff. 

In VFPT we had a diagnostic mode toggle setting to enable these logging features.

**Comment by cloudRoutine** [comment]
It'd probably be useful to mix in rosyln workspace event notification messages, (doc opened, closed, command called, etc) with the F# language service specific logging to get the full picture of what's going on.

**Comment by dsyme** [comment]
Closing old discussion
