### ISSUE TITLE
Rename doesn't work for generic types

### ISSUE THREAD

**Issue by buybackoff** [Microsoft/visualfsharp#2779]
Renaming generic types doesn't work. E.g. for original code

```
type MyGenericType<'T1,'T2>() =
  member this.Foo = "Bar"

[<EntryPoint>]
let main argv = 
  let myInstance = new MyGenericType<int,int>()
  printfn "%A" argv
  0 
```

when I press F2, the line with `let myInstance...` becomes `let myInstance = new MyGenericTypeMyGenericType()` even before renaming, and after renaming to `MyRenamedGenericType` the result is:

```
type MyRenamedGenericType<'T1,'T2>() =
  member this.Foo = "Bar"

[<EntryPoint>]
let main argv = 
  let myInstance = new MyRenamedGenericTypeMyRenamedGenericType()
  printfn "%A" argv
  0 
```
I.e. all usages of the type duplicate the new type name and erase generic types.

VisualFSharp version 15.4.1.17040101

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2955

![1](https://cloud.githubusercontent.com/assets/873919/25557830/91e50bf4-2d22-11e7-8179-6974e61fcfd8.gif)
