### ISSUE TITLE
NullReferenceException when trying to add some COM references

### ISSUE THREAD

**Issue by Regent** [Microsoft/visualfsharp#278]
When I try adding 'Microsoft Windows Installer Object Library' as a COM reference to my F# project it fails with "Object reference not set to an instance of an object":
![image](https://cloud.githubusercontent.com/assets/220614/6411273/cf3f0cb8-be6e-11e4-9556-c8e6c46b2e8e.png)

Well, when I try doing that for a C# project if fails too, although with a different error:
![image](https://cloud.githubusercontent.com/assets/220614/6411308/16aa466c-be6f-11e4-8bb3-a99fdc65a216.png)

However for a C# I can "Browse..." to a DLL directly by "C:\Windows\System32\msi.dll" and this adds COM reference just fine, but for F# this approach still fails with the same NullReferenceException.

**Comment by enricosada** [comment]
i can repro

the line is [ComReferenceNode.cs#L370](https://github.com/Microsoft/visualfsharp/blob/9c53f727c48b2b0fa773db9b98a93525d0acdbbc/vsintegration/src/vs/FsPkgs/FSharp.Project/Common.Source.CSharp/Project/ComReferenceNode.cs#L370)

the lcid used ( `0` ) to [find the key](https://github.com/Microsoft/visualfsharp/blob/9c53f727c48b2b0fa773db9b98a93525d0acdbbc/vsintegration/src/vs/FsPkgs/FSharp.Project/Common.Source.CSharp/Project/ComReferenceNode.cs#L368) target an invalid regedit key

invalid with lcid 0
HKEY_CLASSES_ROOT\TypeLib\{000C1092-0000-0000-C000-000000000046}\1.0\0\win32

valid on my machine (ldic 409) and valid `C:\Windows\system32\msi.dll` path
HKEY_CLASSES_ROOT\TypeLib\{000C1092-0000-0000-C000-000000000046}\1.0\409\win32

i am debugging this one

**Comment by enricosada** [comment]
ok, fixed. i'll add a pr soon

**Comment by dungpa** [comment]
Should this one be closed?

**Comment by latkin** [comment]
Yep, thanks
