### ISSUE TITLE
NUnit 3 Test Adapter cannot find any tests anymore

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2786]
1. Build VFT
2. Open test explorer
3.

![image](https://cloud.githubusercontent.com/assets/873919/24623471/2c2e9706-18b1-11e7-95bb-5e9b199b2c4b.png)

It started a couple of days ago or so.

**Comment by jack-pappas** [comment]
Is this specific to F# projects? Can you reproduce the failure to find tests if you try to use the NUnit 3 test adapter to run tests from a C# project?

**Comment by forki** [comment]
I saw the same thing here. I assume a bad commit (maybe nuget package changes) broke this.

**Comment by vasily-kirichenko** [comment]
I still can reproduce it - no tests in Test Explorer.

**Comment by cloudRoutine** [comment]
A few days ago I ran into this, iirc the problem was caused by emitting pdb debug symbols, once I changed the output type the test runner started working again.

**Comment by vasily-kirichenko** [comment]
@cloudRoutine where is this output type changed? In project settings?

**Comment by 0x53A** [comment]
I think you can either switch to debug (which uses full pdbs), or edit the targets file to also use full in release.

Afaik this is caused by an old mono.cecil version, which can't handle portable pdbs yet: https://github.com/nunit/nunit-vs-adapter/issues/145

**Comment by vasily-kirichenko** [comment]
I'm on Debug.

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it on current master.

**Comment by dsyme** [comment]
@vasily-kirichenko Thanks you for checking and closing out these old issues.
