### ISSUE TITLE
Revert status bar changes implemented in #2683

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2787]
Can we revert the status bar changes implemented in #2683? I understand that there are good intentions, but personally I think we should try to stick to standard VS behaviours as much as possible. I don't think it's unreasonable to think that many people using F# are in a mixed C#/F# codebase, and having distinct results for the same action (missing definition dialog in this instance) is more confusing than clarifying.

I'd just like to add that I'm really appreciative of the changes that @cloudRoutine implemented in that PR, I use the tooltips very often and it makes going back to VS 2015 even more painful. Keep it up guys :)

**Comment by cartermp** [comment]
I agree - we should be loud and obvious about failure rather than not.

**Comment by KevinRansom** [comment]
@cloudRoutine would you send a PR stripping out the status bar changes at issue, it would probably be preferable to reverting the whole PR. then have a discussion about the best way to incorporate those improvements.

Kevin

**Comment by cloudRoutine** [comment]
there's no reason to take all of them out, first of all it doesn't disable the dialog box in all instances, second a few lines need to be changed to make it appear more often than it already does

**Comment by saul** [comment]
@cloudRoutine sure, I can't speak for the rest of the guys but I'm happy with "Searching for symbol..." and the like. I just think the dialog box, as annoying as it is, at least makes failure obvious. 9pt text in the bottom left of my 30" screen is practically unnoticeable :(

**Comment by vasily-kirichenko** [comment]
Originally we use the localized message from Roslyn resources.

**Comment by cloudRoutine** [comment]
https://github.com/Microsoft/visualfsharp/pull/2791

**Comment by vasily-kirichenko** [comment]
@cartermp Can we close it now?
