### ISSUE TITLE
No syntax highlighting in document

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2788]
![image](https://cloud.githubusercontent.com/assets/64654/24626349/ee534eca-18a8-11e7-887d-99839bb024ee.png)

Not sure what's going on here - this isn't the first time this has happened to me and I can't find a reliable repro.

Note that when I do Ctrl+G to jump to a line, I get a "First open a text file to go to a line" message. That may be telling as to what's going on here.

However the document is still a 'primary document' role as mentioned in the status bar.

Any ideas would be great.

**Comment by cloudRoutine** [comment]
This has been happening to me as well

![](http://i.imgur.com/bGwgGue.png)

in my case i know it's due to nuget detritus

![](http://i.imgur.com/giodAj8.png)

because once I delete these files and reload the project

![](http://i.imgur.com/4cAea0j.png)

**Comment by cartermp** [comment]
Is this with the latest nightly?

**Comment by cloudRoutine** [comment]
i don't use the nightlies, I build my own tools straight off of master

**Comment by vasily-kirichenko** [comment]
I've not seen this for about two weeks at least.

**Comment by cartermp** [comment]
I've not seen this either.  @cloudRoutine or @saul please ping this if you see it again so I can re-open.

**Comment by saul** [comment]
This is still happening - can it be re-opened? Thankfully it's happened in my debug instance so I've been able to set some breakpoints:

![image](https://cloud.githubusercontent.com/assets/64654/25563281/7564aaac-2d90-11e7-9ab9-52d8e94134f4.png)

Open for minutes - nothing. Closing/re-opening the file does nothing. It looks like nothing on IEditorClassificationService is being called (for example AddSyntacticClassificationsAsync).

**Comment by realvictorprm** [comment]
@Saul I can report this error too, during my Code Lens tests this happened a couple of time's too

**Comment by dsyme** [comment]
We need a reliable repro for this.  I'll close it until we have one - but please reopen immediately you find one, or indeed if you see the problem again and can grab a screenshot

**Comment by matthid** [comment]
I experienced this problem as well after updating everything to latest (nightly F#, latest VS2017).
Restarting VS and reloading projects as well as re-opening `.fs` files did not help.
It disappeared immediately after I changed the solution configuration to "Debug" instead of "Release" the solution I experienced this was `Paket.sln`.
