### ISSUE TITLE
Extended F# syntax coloring and color settings are missing

### ISSUE THREAD

**Issue by bchavez** [Microsoft/visualfsharp#2794]
Extended F# syntax colorization and color settings are missing.

@vasily-kirichenko says of [`VisualFSharpPowerTools`](https://github.com/fsprojects/VisualFSharpPowerTools/issues/1498#issuecomment-283611548):
> This project is not actively maintained anymore, everything has been ported to Visual F# Tools and is available in VS 2017.

Please see below.

### Repro steps

1. Step A : Install Visual Studio 2017 with F# language support

![vs_installershell_92](https://cloud.githubusercontent.com/assets/478118/24672741/b07d65fe-192a-11e7-9d62-f7f04bfabfb9.png)

### Expected behavior

![devenv_90](https://cloud.githubusercontent.com/assets/478118/24675078/b6bb46b8-1932-11e7-9f69-cc2b7419976d.png)

![devenv_95](https://cloud.githubusercontent.com/assets/478118/24675082/bcf167ba-1932-11e7-9350-e8eddccdbf77.png)

### Actual behavior

![devenv_91](https://cloud.githubusercontent.com/assets/478118/24675087/c1582cc6-1932-11e7-8e77-2b6b1e9210ae.png)

![devenv_96](https://cloud.githubusercontent.com/assets/478118/24675090/c4e8eee8-1932-11e7-8720-0d28089f513c.png)

### Known workarounds

None, except going back to Visual Studio 2015.

------

### Related information 

* Operating system
     **Windows 7 64-bit**
* Branch
     **No idea**
* .NET Runtime, CoreCLR or Mono Version
     **Visual Studio 2017**
![vs_installershell_93](https://cloud.githubusercontent.com/assets/478118/24672834/0460e484-192b-11e7-86a3-15fb78a8f227.png)

* Editing Tools (e.g. Visual Studio Version)
(snipped for brevity)
```
Microsoft Visual Studio Community 2017
Version 15.0.26228.12 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01590

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA337
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA337
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA337
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA337
Microsoft Visual F# 4.1

ASP.NET and Web Tools 2017   15.0.30223.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
For additional information, visit https://www.asp.net/

JetBrains ReSharper Ultimate 2017.1    Build 108.0.20170402.75312
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Merq   1.1.13-alpha (2f64b6d)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
```

* Indications of severity
    ***Severe, must fix, blocking.*** because I hate looking at code that looks like it's from notepad. :smiley: 
* Likely cause
    Possibly due to underpaid, understaffed, F# team developers under the direction of overly demanding devdiv 'ship it now' PMs at Microsoft.

Pls fix. Thanks.

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**

**Comment by vasily-kirichenko** [comment]
1. Install nightly Visual F# Tools, instructions here (very easy) https://blogs.msdn.microsoft.com/dotnet/2017/03/14/announcing-nightly-releases-for-the-visual-f-tools/
2. Use these color settings

![image](https://cloud.githubusercontent.com/assets/873919/24675876/67ce77d0-1989-11e7-84d9-135ea29e8770.png)

**and these**

![image](https://cloud.githubusercontent.com/assets/873919/24675894/7b9a75d4-1989-11e7-93a7-1876702d098c.png)

(use "User types - Enums" to set color for discriminated unions).

**Comment by bchavez** [comment]
Ahh thank you so much @vasily-kirichenko ! (and I noticed rename works again too!). Happiness has been restored. I hope Microsoft is paying you handsomely for all this F# goodness. :+1: 

Thank you again, I very much appreciate your help!

Have a wonderful day!
Brian

![devenv_97](https://cloud.githubusercontent.com/assets/478118/24676825/68773226-1939-11e7-9346-26a1bb5fcf5c.png)

:cloud: :sunny: **[Bassnectar - Chasing Heaven - Into the Sun](https://www.youtube.com/watch?v=a2BAia075lE)**

**Comment by vasily-kirichenko** [comment]
:)
