### ISSUE TITLE
Debugging ranges all messed up

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#2804]
I don't really know what's up, but my favourite debugging technique for the F# compiler now seems to be messed up.  I believe it's because the PDB files being generated by the compiler are now wrong somehow

Normally I do this:

    devenv /debugexe Debug\net40\bin\fsc.exe test.fs

If I then put some breakpoints in Optimizer.fs I expect to hit them, e.g. in OptimizeLambda and OptimizeImplFileInternal.

But now the line numbers for stack frames shown by both VS2015 and VS2017 are wrong. For example, in the screen shot below the hover tip claims that OptimizeLambda is on line 3168 of Optimizer.fs.  But that's nowhere neat the actual source range of that function

![image](https://cloud.githubusercontent.com/assets/7204669/24717256/c35796a4-1a29-11e7-8a8f-53c1bdb521b3.png)

This means none off the following work correctly

* Setting breakpoints (setting a breakpoint in most places in Optimzier.fs now normally fails to bind)
* double-click source navigation up and down the call stack no longer works

Maybe it's related to some of the other issues with debugging reported recently, e.g. the portable debug format

**Comment by forki** [comment]
We're all cheering to get https://github.com/Microsoft/visualfsharp/pull/2773 in

**Comment by KevinRansom** [comment]
@dsyme we are now using portable pdbs rather than desktop pdb's.  There may still be some issues because we haven't really been dogfooding them.

**Comment by dsyme** [comment]
I confirmed that moving to "full" makes this problem go away. Closing in favour of https://github.com/Microsoft/visualfsharp/pull/2773

**Comment by vasily-kirichenko** [comment]
@dsyme use https://github.com/Microsoft/visualfsharp/pull/2773. Without it VFT isn't debuggable at all.
