### ISSUE TITLE
Better breakpoint support when clicking (works fine with F9)

### ISSUE THREAD

**Issue by OnurGumus** [Microsoft/visualfsharp#2814]
It is not possible to fine put fine grained breakpoints by clicking but only with F9.

#### Repro steps

Provide the steps required to reproduce the problem

1. Suppose we have the below code:

```
[<EntryPoint>]
let main argv = 
    let x = 1
    
    let z =
        match x with
        | 1 ->  x
        | _ ->  x + 1
    
    printfn "%A" (z)
    0 // return an integer exit code
```

2. We try to click to left hand side of visual studio to line starting `| 1 -> x` . Visual studio puts the breakpoint to the match statement. 

3. However if we click to `x` then hit F9 then a proper breakpoint inserted.

#### Expected behavior

The breakpoint should be put the relevant line.

#### Actual behavior

The breakpoint is put to the nearest match statement.

#### Known workarounds

Manual mouse click and hit F9 puts the breakpoint to the desired location.
#### Related information 

VS 2017 RTM (all latest updates installed), F# tools nightly.

**Comment by OnurGumus** [comment]
It might be a dup for https://github.com/Microsoft/visualfsharp/issues/2325 not entirely sure though.

**Comment by forki** [comment]
I'm taking a look

**Comment by forki** [comment]
I can repro

**Comment by cartermp** [comment]
It's sort of a dup but might not technically be a dup, even if overall it's still the same problem.  Breakpoint resolution is kinda janky with clicking.  This is something I want to look at soon.  @forki and @vasily-kirichenko have made improvements here before, too.

**Comment by forki** [comment]
https://github.com/Microsoft/visualfsharp/pull/2815 you are welcome
