### ISSUE TITLE
Cannot load certain projects generated via Ionide in VS 2017

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2819]
Ensure you have VS 2017 installed with F#.

1. Clone the following: https://github.com/thinkbeforecoding/UnoFSharpX
2. Run `build.cmd` (there is an error)
3. Attempt to load one of the projects.

#### Expected behavior

Project loads.

#### Actual behavior

<img width="334" alt="screen shot 2017-04-07 at 5 00 01 pm" src="https://cloud.githubusercontent.com/assets/6309070/24808502/de35c834-1bb3-11e7-8ad2-06d789b3f9c7.png">

Also, note the following error if you run `build.cmd` or the FAKE script, you get the following error:

```
  1) Building S:\Downloads\UnoFSharpX-master\UnoFSharpX-master\Uno.Tests\Uno.Tests.fsproj failed with exitcode 1.
  2) MSB4057: S:\Downloads\UnoFSharpX-master\UnoFSharpX-master\Uno\Uno.fsproj(0,0): The target "GetTargetFrameworkProperties" does not exist in the project.
```

#### Known workarounds

None.

#### Related information 

* VS 2017
* F# Tools: 15.4.1.17032302 (it's a nightly)
* On Parallels, though this repros on "regular" Windows as well

**Comment by thinkbeforecoding** [comment]
After investigation, on my system, I have the VisualStudioVersion environment variable set to '14.0', and it builds using C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe

When I set the env variable to '15.0' it runs C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe and fails with
    1>C:\Development\UnoFSharpX\Uno.Tests\Uno.Tests.fsproj : error MSB4057: The target "Build" doesn't exist in the project.

**Comment by vasily-kirichenko** [comment]
@cartermp Isn't it a ionide but?..

**Comment by cartermp** [comment]
@vasily-kirichenko Likely not.  If you create an F# 4.1 project in VS 2017 and attempt to build it with msbuild 14, it will fail as well.  Seems like we might have a setup authoring issue?

**Comment by cloudRoutine** [comment]
i've run into this issue lots of times, there are a few different ways to address it. Setting a default visual studio version in the fsproj sometimes fixes it, but it doesn't always seem to work. 
```xml
  <PropertyGroup>
    <VisualStudioVersion Condition=" '$(VisualStudioVersion)' == '' ">14.0</VisualStudioVersion>
    <MinimumVisualStudioVersion Condition="'$(MinimumVisualStudioVersion)' == ''">11</MinimumVisualStudioVersion>
  </PropertyGroup>
```

the other is to add something like this to the `build.fsx`

```fsharp
let msbuild14 = ProgramFilesX86</>"MSBuild"</>"14.0"</>"Bin"</>"MSBuild.exe"

if isWindows && fileExists msbuild14 then 
     setEnvironVar "MSBUILD"  msbuild14
```

**Comment by cartermp** [comment]
cc @brettfo @KevinRansom

**Comment by dsyme** [comment]
This is a bug in the Ionide templates. This:

```
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\4.1\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
```

should be 
```
        <FSharpTargetsPath>$(MSBuildProgramFiles32)\Microsoft SDKs\F#\4.1\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
```

or
```
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
```

**Comment by dsyme** [comment]
Closing as this was a hand-created project file with a bad targets path
