### ISSUE TITLE
Add New Item to Visual F# project has an incorrect tree structure

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#282]
Decription:
When adding an item to an F# project the Item selector displays an incorrect tree structure Picture below.

The tree is:
Visual F# Items
      Code
      Visual F# Items
             Code
             Data
             General  

Clearly the first Visual F# Items and code are incorrect.

Repro:
1.   Start VS2015
2.  Add new F# Library Project
3.  In solution explorer window select Add new item

![bug](https://cloud.githubusercontent.com/assets/5175830/6428526/4d1332a4-bf5a-11e4-981e-90e6fe935cd9.jpg)

Note:    I am confident the fix will not be in the open part of the codebase, reporting here to avoid dupes.

Twitter: @codecutterman

**Comment by latkin** [comment]
I do not repro using an internal VS drop from last week, or with VS 2015 preview.  Does anyone else see this?

**Comment by latkin** [comment]
Does not repro for me with fresh install of VS 2015 CTP6 + latest F# package.

Per our hallway convo - I wonder if this is due to EnableOpenSource installation/development on your box? Maybe a tree path got horked while you were debugging that guy.

**Comment by KevinRansom** [comment]
I agree it was likely a configuration issue

**Comment by bentayloruk** [comment]
I have just had the same issue with VS 2015 RC.  It is wrong in 2015 RC and correct in 2013.  As the following images demonstrate.  Is there anything I can do to help figure this out, or is it likely I've done something rogue! :smile: 

## VS 2015 RC
![screen shot 2015-05-07 at 10 02 23](https://cloud.githubusercontent.com/assets/189409/7511950/01115d5a-f4a1-11e4-963e-dadca62300e8.png)

## VS 2013
![screen shot 2015-05-07 at 10 05 49](https://cloud.githubusercontent.com/assets/189409/7511954/06f5b6e4-f4a1-11e4-98cb-987ce72db6cf.png)

**Comment by PatrickMcDonald** [comment]
Here's what my 2013 dialog looks like if that helps (So just the extra `Code` node from Kevin's screenshot is different):

![image](https://cloud.githubusercontent.com/assets/1562597/7512417/bd56fba2-f4a4-11e4-9555-73a650a5b1a4.png)

**Comment by isaacabraham** [comment]
Bizarre, I just checked and have the same SQL stuff showing in the Visual F# Items bit (if you drill down, it's located in Data).

I did upgrade from CTP4 or 5 to the RC - maybe this is something left over from then.

**Comment by latkin** [comment]
Yeah I am actually seeing this now, too, after installing RC.

**Comment by latkin** [comment]
This bug just won't go away... 

Right now, F# "new item" dialog looks correct with the default set of extensions that come with VS.  However there appears to be some VS platform issue (or maybe setup bug on our side) whereby installing/uninstalling other extensions can cause our root node to disappear.

I have confirmation from our team and the VS platform team that it's too late to make further changes for this, so we will live with it for now.  I have a lead on a proper fix, will look at that for vNext.
