### ISSUE TITLE
Same namespace cross project(C#,F#) will cause error.

### ISSUE THREAD

**Issue by Huqin-China** [Microsoft/visualfsharp#2822]
### Fix description
Not intellisense bug.
It's caused by what's title said;
see below
![fsharpbug](https://cloud.githubusercontent.com/assets/15418465/24830616/67e7275e-1cbc-11e7-90ea-4ebe324eb23c.PNG)

Provide any related information 
f# core  4.4.1
VFPT Nightly 2017040601
Target .Net 4.5

**Comment by dsyme** [comment]
I think we need a much more minimal repro for this, in an empty or minimal project?

**Comment by Huqin-China** [comment]
### More Situation
"." competionprovider also report the same error for  System.Collections.ImmutableDictionary  type.

**Comment by Huqin-China** [comment]
@dsyme Yes，i create new project,and  intellisense in this project looks good.

**Comment by Huqin-China** [comment]
[https://git.oschina.net/RenewableEnergy/REDKit.git](url)

branch feature/core重构->REDKit.Core.Fsharp

i can't debug asyncmaybe method  ViualFsharp.sln

cc @vasily-kirichenko ,pls

**Comment by forki** [comment]
Is it fixed?

**Comment by Huqin-China** [comment]
@forki ,i find what cause this problem,but i can't sure it should be called an bug.

1. create REDKit.Core Lib use c#,
2. create REDKit.Core.Fsharp lib then reference REDKit.Core C# lib
3. Use the same root namespace the both project like REDKit.Core. Create some type in c# lib under root namespace,then create fs file in f# project
4. in fs  file  create new module or type under REDKit.Core(root) namespace ,then these types or modules will show that missing"system.drawing.dll",intellisense report error,and project compilation will fail.
5. when new type or module in f# project are not under REDKit.Core namespace,it will be ok,Like change this project's root namespace to "REDKit.Core.Fsharp"

Maybe f# treat this types or modules are  extending  the C# lib, is it designed like this or bug?
this issue should be close when it's not a bug.

**Comment by Huqin-China** [comment]
# 3004 solved this,Close Now
