### ISSUE TITLE
Internal error in fsharpi - referencing a facade DLL

### ISSUE THREAD

**Issue by haf** [Microsoft/visualfsharp#2823]
Trying to run tests with Mono.Cecil as a reference throws 'internal error'

#### Repro steps

Run this file in `fsharpi` on OS X on mono 4.8.0 https://github.com/logary/RingBuffer/commit/a3282d70f06d32f799b91baca65745ad98b07468#diff-879359970577bc1dba6b3bc3fc59e6d2 after doing a `paket restore`. It triggers the issue on this line: `Tests.runTests defaultConfig tests`:

```
> Tests.runTests defaultConfig tests
- ;;
Binding session to '/usr/local/Cellar/mono/4.8.0.495/lib/mono/4.5-api/Mono.Cecil.dll'...

error FS0193: internal error:

Binding session to '/usr/local/Cellar/mono/4.8.0.495/lib/mono/4.5-api/Mono.Cecil.dll'...

error FS0193: internal error:

Stopped due to error
```

#### Expected behavior

Not to throw internal error.

#### Actual behavior

Throws internal error.

#### Known workarounds

Remove Mono.Cecil as a dep from Expecto?

#### Related information 

Provide any related information 

* Operating system: OS X 10.11.6
* .NET Runtime, CoreCLR or Mono Version, Mono JIT compiler version 4.8.0 (Stable 4.8.0.495/e4a3cf3 Wed Mar  1 08:20:42 GMT 2017)
* Editing Tools (e.g. Visual Studio Version): vscode
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
* Indications of severity: major since it throws internal error without a way to remedy

**Comment by dsyme** [comment]
The problem appears to be that the ``4.5-api`` DLL is being used.  I don't know why this is used in preference to the explicitly referenced DLL, I wouldn't expect that to be the case.

    Binding session to '/usr/local/Cellar/mono/4.8.0.495/lib/mono/4.5-api/Mono.Cecil.dll'...

**Comment by dsyme** [comment]
@haf If you get a chance to check with latest "fsharp" master from fsharp/fsharp (or latest tag) that would be great, I expect the bug has been fixed there (by preferring the `4.5` copy of Mono.Cecil)

**Comment by dsyme** [comment]
Proposed fix: https://github.com/Microsoft/visualfsharp/pull/2949

**Comment by dsyme** [comment]
I can verify this is now fixed

![image](https://cloud.githubusercontent.com/assets/7204669/25552257/aa7ef8f0-2c8c-11e7-8dbb-4d700b1e3c4b.png)
