### ISSUE TITLE
Faulty coloring of numbers in comprehensions with a step

### ISSUE THREAD

**Issue by kerams** [Microsoft/visualfsharp#2825]
When using list/seq/array comprehensions with a step, the final number is either partly or entirely miscolored.

#### Repro steps

![untitled](https://cloud.githubusercontent.com/assets/5063478/24836731/f70c010e-1d23-11e7-9394-c484daff2b3f.png)

#### Expected behavior

All numbers should have the same color.

#### Related information 

Visual F# Tools version 15.4.1.17040601
.NET 4.6.2

**Comment by kerams** [comment]
The closing brace in `test3` is grey too by the looks of it.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2826
