### ISSUE TITLE
Add option to place open statements at the namespace level

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2827]
At present, refactorings that add open statements open them at the module level. I personally prefer to place open statements at the namespace level, but this isn't an option in the F# tools.

It would be great if we could have an option where this could be specified. I'm happy to have 'place at module level' as the default :) At the minute 'add open' is pretty useless to me as I have to manually cut/paste the line somewhere else.

**Comment by vasily-kirichenko** [comment]
Yeah, I thought about it. It's easy to implement after https://github.com/Microsoft/visualfsharp/pull/2805 is merged.

**Comment by cartermp** [comment]
I'd like this as well.  Personally I think it makes sense as the top option (assuming two options, where one is to `Add open` and the next is `Add open (module level)`).

**Comment by cartermp** [comment]
Thinking about this some more, this may be a bit of work.  We have to account for any `#if` defines, and add it appropriately.  From what I understand, Roslyn has a fair bit of logic in determining where to place it at the top.  We may want to port that code over.

**Comment by cartermp** [comment]
Looks like it may depend on the Semantic Model API, so we'd be on our own on how to determine the proper location at the top :/

**Comment by saul** [comment]
It already puts it at the top if you're not in a module so there's already some code that does does this (somewhere :p)

**Comment by vasily-kirichenko** [comment]
Implemented in https://github.com/Microsoft/visualfsharp/pull/2875

**Comment by vasily-kirichenko** [comment]
@cartermp Can we close this now?
