### ISSUE TITLE
Creat new project in debug mode will fail because properties miss some value

### ISSUE THREAD

**Issue by Huqin-China** [Microsoft/visualfsharp#2831]
Please provide a succinct description of the issue.

#### Repro steps

1. Lastest Master branch,luanch visualfsharpopensource

2. Create new project using F#

#### Expected behavior

No error;

#### Actual behavior

debug report error,because {Microsoft.VisualStudio.FSharp.ProjectSystem.Automation.OAProperties.Properties} miss {TargetPlatformIdentifier}

there is a (if check) in source code ,when this  expression can't find {TargetPlatformIdentifier} property ,project will throw a argument exception
`            
if (index is string)
            {
                string indexAsString = (string)index;
                if (this.properties.ContainsKey(indexAsString))
                {
                    return (EnvDTE.Property)this.properties[indexAsString];
                }
            }
`

#### Known workarounds

No idea

#### Related information 

vs15.1 preview latest
Lastest Master branch

**Comment by cartermp** [comment]
This isn't something I've been able to reproduce for quite a long time.  @Huqin-China, please re-open if you are still seeing this on 15.3.5 or higher.
