### ISSUE TITLE
Wrong completions for "member val x = 0 with get,"

### ISSUE THREAD

**Issue by vivainio** [Microsoft/visualfsharp#2835]
#### Repro steps

Type in code:

```fsharp
type Foo() = 
    member val a = 12 with get
```

If you enter "," after the completion tooltip shows, code gets expanded to:

```fsharp
type Foo() = 
    member val a = 12 with Array.get,
```

The completion tooltip is shown here:

![image](https://cloud.githubusercontent.com/assets/557579/24927407/97ab76a0-1f07-11e7-8ff0-6e7c41e7a0ad.png)

#### Expected behavior

When pressing ",", it should just leave "get" there as it's legal syntax. Current workaround is wait for the tooltip, dismiss it with ESC and then type in the ","

**Comment by vasily-kirichenko** [comment]
I'm sure there is no AST available for such incomplete code. In such case we have no choice but suggest all unqualified symbols. We could use the lexer to try to parse such code on ourselves, but it's complex and error prone.

**Comment by vivainio** [comment]
The word I typed ("get") is already available in the suggested completions (as shown in the screenshot), it's just not the first completion. The problem is in the UI flow - if I typed something and press "," (not tab or whatever), it should be satisfied with that completion and leave the code as is.

**Comment by sergey-tihon** [comment]
@vivainio and seems that fix is similar. If @vasily-kirichenko does not mind to add `,` to `noCommitOnSpaceRules` you could PR that fix your case.

**Comment by vasily-kirichenko** [comment]
I think it should commit on Enter and Tab only.
