### ISSUE TITLE
Enable tests for mono

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2846]
According to @7sharp9 we currently have a version that compiles on mono and even fsharpi works on mono. This is really nice and we should make sure we keep it like this. 
We should enable at least a handful of tests on mono. Ideally we strive to run all fsc and fsi tests - but let's start small.

**Comment by dsyme** [comment]
@forki Yes, that would be great. There is now pretty much total alignment of core code between fsharp/fsharp and Microsoft/visualfsharp, with a couple of very minor exceptions.

fsharp/fsharp includes some testing - a variant of the "fsharp" suite is compiled through "fsharpi" - see run-all.fsx.  That is one approach we could adopt - although it'a bit kludgy it does have some advantages in really stressing Mono's reflection emit.  Alternatively we could just try running the fsharp suite itself, but skipping calls to things like ``peverify`` and other tools not available on Mono.

**Comment by dsyme** [comment]
I'll close this and track it as part of https://github.com/Microsoft/visualfsharp/issues/2854
