### ISSUE TITLE
Object reference not set to instance of an object from Generate References for F# Interactive using Fsharp.Org MVC 5 templates 

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#286]
Description:

After creating an MVC 5 project from the fsharp.org template, selecting Generate References for F# 
Interactive yields a modal dialog with Object reference not set to instance and creates and creates the load-references.fsx file.
Do it a second time, it yields the error dialog as before and creates the load-project.fsx file
Do it a third time and no error appears.

Repro:
1.  Download and install F# MVC templates from VS Gallery
2.  Create a new MVC 5 F# Project
3.  Unload the project and reload it
4.  On the solution explorer for the project select Generate References for F# Interactive
5.  Observe a dialog with the text : "Object reference not set to instance of an object "
6.  Repeat step 4. observe the error again
7.  Repeat step 4. observe no further errors

Expected:
References to be correctly created.

TwitterID:  @codecutterman

**Comment by rojepp** [comment]
'Generate References for F# Interactive' is a VFPT command. Care to report the bug [there](https://github.com/fsprojects/VisualFSharpPowerTools)?

**Comment by latkin** [comment]
Closing per @rojepp
