### ISSUE TITLE
Incorrect code comment for revAcc function in FSharp.Core/local.fs

### ISSUE THREAD

**Issue by Treit** [Microsoft/visualfsharp#2864]
The following comment on line 412 of FSharp.Core/local.fs implies the following revAcc function uses mutation. However, the implementation does not use mutation so the comment appears to be incorrect.

        412     // optimized mutation-based implementation. This code is only valid in fslib, where mutation of private 
        413     // tail cons cells is permitted in carefully written library code. 
        414     let rec revAcc xs acc =  
        415         match xs with  
        416         | [] -> acc 
        417         | h::t -> revAcc t (h::acc) 
        418 
 
        419     let rev xs =  
        420         match xs with  
        421         | [] -> xs 
        422         | [_] -> xs 
        423         | h1::h2::t -> revAcc t [h2;h1] 

The incorrect comment should be removed or updated.

**Comment by forki** [comment]
Can you please send a pull request with a fix? Thanks

**Comment by dsyme** [comment]
Fixed by direct commit in https://github.com/Microsoft/visualfsharp/commit/e69a774973a79b3d605c7f623b3dc612d8e067b0
