### ISSUE TITLE
VS2017: completion icon issue for items in non opened namespaces

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#2866]
When listing items which are not in scope, it seems the icon used (and impacts filtering as well) doesn't follow the type of symbols, at least for symbols defined in C# assembly:

![image](https://cloud.githubusercontent.com/assets/87944/25072455/e1496a72-22ce-11e7-8eb3-67dd61332a75.png)

[ClassLibrary1.zip](https://github.com/Microsoft/visualfsharp/files/924399/ClassLibrary1.zip)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2896

**Comment by smoothdeveloper** [comment]
Thanks!

**Comment by vasily-kirichenko** [comment]
@cartermp Can we close it now?
