### ISSUE TITLE
F# options missing from Fonts and Colors

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2869]
In the latest nightly release (15.4.1.17041402), the F# options are missing from Fonts and Colors. It looks like the mutable variables are still highlighted as before, but functions are not, see:

![image](https://cloud.githubusercontent.com/assets/64654/25099417/13eb7b66-23a4-11e7-9de6-7ba5ba3b7c58.png)

Not sure when this was broken, or what could have caused it.

**Comment by cartermp** [comment]
@saul Interesting.  I've got them in 15.4.1.17041701 (latest today).
<img width="493" alt="screen shot 2017-04-17 at 12 48 46 pm" src="https://cloud.githubusercontent.com/assets/6309070/25102206/3ec7b864-236c-11e7-9530-8b28f5a8145a.png">

**Comment by vasily-kirichenko** [comment]
The settings are there on current master.

**Comment by cartermp** [comment]
Closing for now, as I've not seen this missing in nightlies either.  Perhaps it was a bad build.
