### ISSUE TITLE
Set Targetframework for MVC 5 project to .Net 2.0 project no longer loads

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#287]
The project properties page allows the selection of .Net framework 2.0 for MVC projects.  Once this has happened the projects can not be loaded by VS. To correct the problem requires a manual edit of the project file to set the target framework.

Repro:
1.  Download F# MVC 5 add on from vs gallery
2.  Create an F# MVC 5 project
3.  Open the Project properties dialog
4.  Set Target Platform to .Net 2.0
5.  Select Apply
6.  Observe that the project is now unloaded and can't be reloaded.

Portable projects don't have this issue because they have specific target frameworks.  We should ensure that this 

TwitterId: @codecutterman

**Comment by dsyme** [comment]
This is really old and MVC 5 is old. Let's close this.
