### ISSUE TITLE
pr to wiki

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#288]
i added some doc about vs development

the changes are on `update_doc_1` topic branch of my [forked wiki repo](https://github.com/enricosada/visualfsharp.wiki.git)

you can see the changes on [my published wiki fork](https://github.com/enricosada/visualfsharp/wiki)

- removed nunit from required software (is downloaded from nuget)
- add visualfsharp logo to Home
- add visual F# tools dev guide

btw, since this repo does not use collaborators, maybe make the public the wiki (removing collaborators only restriction) can help people to write docs? 
The wiki is a git repo, it's easy to revert errors

**Comment by latkin** [comment]
Looks nice. I've pushed your changes to wiki on this repo.
