### ISSUE TITLE
Show expression evaluation result next to it in a adornment layer

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2882]
Like this: 

https://twitter.com/markwoodhall/status/854444009665810432

**Comment by cartermp** [comment]
This seems like an Alive-style thing - ping @JoshVarty if there's any context here.  However, even as an ephemeral comment, I think this would be great.

**Comment by JoshVarty** [comment]
Yeah [Alive](https://www.youtube.com/watch?v=PZni_54s0o4) was pretty similar, but for C#. We're still doing research into how Alive might fit into future versions of Visual Studio.

I always thought the idea might be better applied to F#.

**Comment by vasily-kirichenko** [comment]
@JoshVarty is Alive open source? I don't think I like the slider for loop evaluating though. And I'm sure it complicates things a lot. Just showing each expression result next to it is totally enough.

**Comment by vasily-kirichenko** [comment]
> Code Connect is joining Microsoft!
28 Jun 2016
We started Code Connect to build tools that help developers be as productive as they can be. Over the course of the last two years we built and shipped Code Connect, Source Browser and Alive.

> At Microsoft we will continue full-time development on Alive and we’ll be exploring different ways in which we can integrate Alive more closely with Visual Studio. Stay tuned for more information on this in the coming months.

So it was almost a year ago. Is it available (for C# at least) in VS?

**Comment by vasily-kirichenko** [comment]
Won't be implemented, closing it to reduce number of issues.
