### ISSUE TITLE
kprintf broken on 64 bit

### ISSUE THREAD

**Issue by blumu** [Microsoft/visualfsharp#2885]
#### Repro steps
Minimal repro obtained with @mgreisen:
- Create a new project
- Replace the main function with the following code
- In project settings unselect "Prefer 32 bit"
- Build, run and observe crash
```fsharp
// Will crash when compiled for 64bit (Remove Prefer 32 bit in the project settings)
let guid1 = System.Guid.NewGuid()
let guid2 = System.Guid.NewGuid()
[<EntryPoint>]
let main _ =

    // If you take this `aux` function out of main, it does not repro anymore!
    let aux f = Printf.kprintf id f

    let x = aux "%A-%A-%s-%s" guid1 guid2 "Foo" "Foo2"
    let y = Printf.kprintf id "%A-%A-%s-%s" guid1 guid2 "Foo" "Foo2"

    System.Console.WriteLine(x)
    System.Console.WriteLine(y)

    if x <> y then
        failwith "What's going on, F#?"
    0
```
#### Expected behavior

Program should not crash (`x` and `y` should be equal)

#### Actual behavior

Program crashes: in `y`, `guid1` gets expanded twice (instead of `guid1` and `guid2`).

#### Known workarounds

- Build the project with "Prefer 32bit" option enabled.
- Use different format specifiers: 
    * replace %A by %s
    * remove the last %s specifier and parameter
    * add an extra %s and associated parameter
- Inline the `aux` function
- Define `aux` function as a top-level function

#### Related information 
* Operating system: Win 10, Win 2008 R2
* Branch: Official build of F# 4.1
* .NET Runtime: 4.5.2

**Comment by 0x53A** [comment]
I can repro, but only with optimizations enabled. In debug configuration it works as expected.

**Comment by dsyme** [comment]
This must be a JIT64 bug? Perhaps with an obscure brand of tailcall?

**Comment by 0x53A** [comment]
Tailcalls are disabled in both assemblies, the only difference is the debuggable flag.

**Comment by dsyme** [comment]
> Tailcalls are disabled in both assemblies, the only difference is the debuggable flag.

OK, then really must be a JIT bug.  We should open a bug in the relevant CLR repo (not sure which it is).  Would also be worth checking if RyuJIT on/offf makes a difference

**Comment by 0x53A** [comment]
It must somehow be related to large >=12 byte structs:

```F#

// 16 byte
// this fails
//let guid1 = struct (1,2,3,4)
//let guid2 = struct (5,6,7,8)

// 16 byte
// this also fails
//let guid1 = System.Guid.NewGuid()
//let guid2 = System.Guid.NewGuid()

// 4 byte
// this passes
//let guid1 = 1
//let guid2 = 2

// 8 byte
// this passes
let guid1 = struct (1,2)
let guid2 = struct (5,6)

// 12 byte
// this fails
//let guid1 = struct (1,2,3)
//let guid2 = struct (5,6,7)

```

**Comment by 0x53A** [comment]
Since no one else volunteered I have created https://github.com/dotnet/coreclr/issues/11090, please chime in if you have anything to add.

**Comment by dsyme** [comment]
@0x53A Thanks!

**Comment by dsyme** [comment]
Closing since the external bug is closed, see the link for resolution and availability of fix
