### ISSUE TITLE
The current netcore "release" is missing GetUnionFields

### ISSUE THREAD

**Issue by matthid** [Microsoft/visualfsharp#2890]
Please provide a succinct description of the issue.
`error FS0039: The field, constructor or member 'GetUnionFields' is not defined.`

#### Repro steps

Try to use `Microsoft.FSharp.Reflection.FSharpValue.GetUnionFields` on dotnetcore and try to compile.

#### Expected behavior

Compilation works.

#### Actual behavior

Compilation fails.

#### Known workarounds

Use https://gist.github.com/cloudRoutine/3884b1ac325bbd5553f9 provided by @cloudRoutine or see what Argu is doing https://github.com/fsprojects/Argu/blob/96d61e1f5253c5c025d5bafa720a5fc8ed7b2110/src/Argu/PreCompute.fs
Or don't use reflection.

#### Related information 

Provide any related information 

* Windows 10
* Using FSharp.Core 4.1.12 nuget package
```
$ dotnet --info
.NET Command Line Tools (1.0.2)

Product Information:
 Version:            1.0.2
 Commit SHA-1 hash:  54743c8b7b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.2
```

**Comment by dsyme** [comment]
Did you open ``FSharp.Reflection``?

There's a replacement extension member in 
```
[<AutoOpen>]
module FSharpReflectionExtensions =
...
```

**Comment by matthid** [comment]
The code was explicitly using the fully qualified member from above and broke. Did dot try to open anything to be honest. I had no idea ;)

**Comment by matthid** [comment]
@dsyme So this is an intended breaking change in the API? Why?

**Comment by dsyme** [comment]
@matthid I'll reopen while we work out the answer to that.

**Comment by dsyme** [comment]
Looking through the code ``Microsoft.FSharp.Reflection.FSharpValue.GetUnionFields`` should be available for .NET Core.  eg this from Cvisualfsharp\src\fsharp\FSharp.Core.Unittests\SurfaceArea.coreclr.fs

    Microsoft.FSharp.Reflection.FSharpValue: System.Tuple`2[Microsoft.FSharp.Reflection.UnionCaseInfo,System.Object[]] GetUnionFields(System.Object, System.Type, Microsoft.FSharp.Core.FSharpOption`1[System.Reflection.BindingFlags])

Could you take a look again? thanks

**Comment by matthid** [comment]
1. Download https://www.nuget.org/packages/FSharp.Core
2. Open the /lib/netstandard1.6/FSharp.Core.dll
3. 
![grafik](https://cloud.githubusercontent.com/assets/1866463/25924879/7320257a-35e5-11e7-9ddc-3cfdab6718d1.png)

It's definitely there but not usable.

**Comment by dsyme** [comment]
Looks  like it was fixed here: https://github.com/Microsoft/visualfsharp/commit/a2bb40f7017de0bb43a79823edaf0c9abce431c6#diff-96d63f77df4761df66a8645a91bd8683

**Comment by matthid** [comment]
Perfect. So they will be in the next nuget package? I'm happy with that :)

**Comment by dsyme** [comment]
Yes, I just recompiled from master and they are public
