### ISSUE TITLE
No link for a navigable symbol

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2895]
![image](https://cloud.githubusercontent.com/assets/873919/25275789/b11dff78-269f-11e7-8aa2-1faf95bf169a.png)

F12 works for it.

**Comment by majocha** [comment]
Yes, I noticed it sporadically fails now. Not sure but I think rebuilding solution fixes it (?)
![image](https://cloud.githubusercontent.com/assets/1760221/25275974/3e10b8ce-2698-11e7-9744-5714a09f7a1b.png)

The logic for creating links is fairly simple. If there is no valid range pointing to a symbol at the time tooltip is created, there is no link. Yet I think it worked reliably before(?) I must catch it in the act to debug it. :(

**Comment by vasily-kirichenko** [comment]
Cannot reproduce it on current master

![image](https://cloud.githubusercontent.com/assets/873919/25778694/55c26f12-330e-11e7-8cb0-d37c527ab147.png)
