### ISSUE TITLE
Open script from a folder does not work for the first time

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2897]
1. Open a _folder_ that contains any fsx files
2. Double click on any script file

![image](https://cloud.githubusercontent.com/assets/873919/25278607/6e347f90-26ac-11e7-983c-9381092077db.png)

It turns out it's reproduced for any type of file (ps1 for instance). 

@Pilchie where should I report this bug?

**Comment by cartermp** [comment]
cc @brettfo who was looking at a bug related to this

**Comment by cartermp** [comment]
Evidently this has been fixed, and should be in for 15.2.

**Comment by smoothdeveloper** [comment]
@cartermp can you clarify? I'm seeing it in nightly, is it outside of visualfsharp?

**Comment by cartermp** [comment]
VS editor fix.  Not F#.

**Comment by smoothdeveloper** [comment]
Got it, thanks!
