### ISSUE TITLE
(Same) Problem after installing FSharp_Bundle on 2 different machines

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#29]
Opened by: hmemcpy  on codeplex
Hello, 

I noticed I had an update for FSharp Tools in my VS2013, so I downloaded and installed it. 
After that, I could no longer compile ANY F# projects - even creating a new console app/library would fail compilation with the following: 

![tempaetbbjl](https://cloud.githubusercontent.com/assets/5175830/5790479/648c8c40-9e4f-11e4-89a0-0f1249e18088.png)

Same exact thing happened on my other machine also running VS2013 Update 4 - after installing the latest F# tools and rebooting the machine, I had the same exact problem! 

I changed the version of FSharp.Core (under references) to 4.3.0.0 instead of 4.3.1.0, and the problem went away! 

What am I doing wrong? 

Please let me know if you need additional information.

> comments

> KevinRansom wrote Dec 4, 2014 at 10:23 AM [x] 

> Did you install VS 2014 preview 3 or 4 on your machine. We had a bug where we were placing the wrong Fsharp.core.dll in the 4.3.1.0 reference and that unfortunately broke VS 2013. Because of the way setup works it wasn't even repairable. The work around was to copy the correct 4.3.1.0 dll into the references directory.

> The thread is here:  https://visualfsharp.codeplex.com/workitem/154 could you check to see if this was the same issue for you?

>> latkin wrote Dec 4, 2014 at 10:25 AM [x] 
>> I changed the version of FSharp.Core (under references) to 4.3.0.0 instead of 4.31.1.0, and the problem went away! 

>> Do you mean 4.3.1.0, not 4.31.1.0?

>> Errors like that will occur when for whatever reason the compilation ends up referencing FSharp.Core out of the GAC, rather than from proper place in %programfiles%\Reference Assemblies...

>> Curious, does the same issue occur if you do command-line build with msbuild? If so, you can try to get more info by running msbuild /verbosity:Detailed, and it will dump out the reference resolution logic as it goes. That might point to where the failure is.

**Comment by latkin** [comment]
Has anyone else experienced this?

There was the confirmed issue in an earlier preview where wrong version of FSharp.Core was dropped at 4.3.1.0, but recent previews and builds should work fine.

**Comment by KevinRansom** [comment]
I'm going to close this out, because of no action for 2 months, 3 months if you exclude the port to GH and lincolns follow up.
