### ISSUE TITLE
Amending source code does not show up in referencing projects

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#290]
If you have two F# projects in VS, where project B references project A, and amend the code in the project A, it won't automatically show up in project B. You have to manually re-build project A before project B "sees" e.g. the amended function signatures.

This is not the same behaviour of e.g. C# projects where it updates without a rebuild occurring.

**Comment by dsyme** [comment]
This is one of the issues that could be addressed by bringing some of the FSharp.Compiler.Service functionality into the Visual F# Tools.  The FCS incremental checker keeps results from a solution-wide graph of projects, rather than one-project-at-a-time.

**Comment by latkin** [comment]
This falls into the "feature request" bucket, it's not intended to work at this point. Agree it would be very nice to have.

**Comment by dsyme** [comment]
This has been implemented when we brought the VFPT work over
