### ISSUE TITLE
F12 Go to definition not working for signature files in referenced project.

### ISSUE THREAD

**Issue by majocha** [Microsoft/visualfsharp#2904]
Latest nightly
![f12](https://cloud.githubusercontent.com/assets/1760221/25317546/ed48f020-287a-11e7-85b2-9aafdacab359.gif)

This is probably related to #2902.

**Comment by dsyme** [comment]
I can't repro this - could you reopen with exact repro steps please and sample project? thanks

**Comment by majocha** [comment]
I can't reproduce this outside of VIsualFSharp.sln.
