### ISSUE TITLE
Make Statically Resolved Type Parameters work with other .NET languages

### ISSUE THREAD

**Issue by panesofglass** [Microsoft/visualfsharp#2906]
I attempted to use F#'s statically resolved type parameters to facilitate types declared in other projects, including C# projects. It appears that these only work with types declared in F#, even though the types should be equivalent. I would love to see or help make this work across languages.

As this is a compile-time step, I suspect this will not be possible without some sort of common integration with other language compilers. However, as I don't know much about the mechanism, I thought I would ask.

#### Repro steps

Provide the steps required to reproduce the problem

1. Define a function in F# using statically resolved type parameters.
2. Attempt to define a class in C# and use it with the function defined in F#.
3. Observe that the application compiles successfully.
4. Run the program and discover the F# function fails with an `InvalidOperationException`.

I have a sample solution [here](https://github.com/panesofglass/AssemblyNeutralInterfaces).

#### Expected behavior

Type defined in C# both compiles and runs with the F# function.

#### Actual behavior

The application compiles but fails at runtime.

#### Known workarounds

Workaround is to use an F# library to interact with the library providing the function using statically resolved type parameters.

#### Related information 

Provide any related information 

* Operating system Windows 10
* Branch F# 4.1
* .NET Runtime, CoreCLR or Mono Version 4.6.2
* Editing Tools (e.g. Visual Studio Version) Visual Studio 2017
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
* Links to performance testing scripts
* Indications of severity

**Comment by cartermp** [comment]
I think this is a good candidate for a [language suggestion](https://github.com/fsharp/fslang-suggestions), as AFAIK SRTPs aren't intended to be consumed, thus this would be closed "by design".  That said, I definitely would support such a change if it were possible to do so without requiring changes to the C# and VB.NET compilers.

**Comment by vasily-kirichenko** [comment]
No way a inline function that uses SRTP will ever work being called from any other compiler but F#. All the magic is done by F# compiler.

**Comment by 0x53A** [comment]
The maximum that would be possible is to pre-specialize the function for a limited number of generics.

E.g. if you have 

```F#
[<Specialize(typeof<int>)>]
[<Specialize(typeof<double>)>]
let inline x y = x + y
```

then you could call it with either int or double from C#, but all other types would still blow up.

**Comment by dsyme** [comment]
@panesofglass Per CONTRIBUTING.md, please open a language design suggestion on this please - thanks! I did approve one suggestion today, so it sometimes happens :)
