### ISSUE TITLE
FSharpFunc => Action/Func implicit conversion

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2907]
It's super annoying that F# functions are not converted automatically to `Action`/`Func` when passed to methods:

![image](https://cloud.githubusercontent.com/assets/873919/25339225/9024b196-290a-11e7-859d-1c5d3cb74baf.png)

So we have to write ugly code like this `Action<_> (printfn "%s")` or like this `fun x -> printfn "%s" x`

**Comment by matthid** [comment]
This adds some corner cases and imlicit typing to the language. Maybe another way would be to have an operator for this, which converts to `Action`/`Func` as needed? And a special error message could show or advice that operator?

**Comment by vasily-kirichenko** [comment]
@matthid the compiler already converts lambdas to `Action`/`Func` and it's caused no problems so far, so why not to do the same for any value of type `FSharpFunc`?

**Comment by matthid** [comment]
@vasily-kirichenko But from a users perspective that's not an implicit conversion, instead the user is writing an action or func in that case (I guess that's a philosophical question). Maybe @dsyme can share his opinion on this.

**Comment by isaacabraham** [comment]
@matthid I had the same idea re: improve error reporting with guidance on how to convert (perhaps not even operators, just a few utility funcs added to FSharp.Core?)

**Comment by smoothdeveloper** [comment]
@vasily-kirichenko consider adding some elements to #2503

**Comment by smoothdeveloper** [comment]
IMHO this is a problem with delegates altogether, not only `Action` `Func`.

**Comment by matthid** [comment]
Thanks @smoothdeveloper after https://github.com/fsharp/fslang-suggestions/issues/248#issuecomment-273176935 I kind of changed my mind. Maybe we need it to just work :)

**Comment by dsyme** [comment]
@matthid @vasily-kirichenko @smoothdeveloper Yes, this is a glitch (my fault, sorry...) that should be fixed.  I've marked https://github.com/fsharp/fslang-suggestions/issues/248 as approved in principle

Next steps would be to dig into the "single overload" path of method overload resolution and understand why it differs from the "multiple overload" path.

**Comment by dsyme** [comment]
Closing as this is an approved RFC, we just need to implement this
