### ISSUE TITLE
Outlining: top level node collapses entire file

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2908]
![1](https://cloud.githubusercontent.com/assets/873919/25340840/9c03d1ae-290f-11e7-8286-2f89d800fb0d.gif)

**Comment by cartermp** [comment]
Thought I had seen this reported in one of the other issues for Structured Guidelines, but I can't find find it.

**Comment by smoothdeveloper** [comment]
@cartermp maybe this one: #2392

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2915
