### ISSUE TITLE
Replace Unused suggestion causes code to not compile

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2912]
This is in `QuickInfoProvider.fs`.

![replace-underscore-bug](https://cloud.githubusercontent.com/assets/6309070/25368208/b5f38404-292f-11e7-9e3f-93ed684f8557.gif)

Though one could argue whether or not this is the responsibility of the code fix, generally code fixes should not suggest something which won't compile.

**Comment by vasily-kirichenko** [comment]
Yeah, it's a corner case. I think we have two definition locations for same symbol here.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2914
