### ISSUE TITLE
All features stop working on opened script files after project reloading

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2916]
![1](https://cloud.githubusercontent.com/assets/873919/25384132/cc5c2136-29c7-11e7-8db8-a246486b0d98.gif)

**Comment by saul** [comment]
Think this is related to #1944 - I'm working on a fix now

**Comment by dsyme** [comment]
I believe this is fixed by https://github.com/Microsoft/visualfsharp/pull/3025, at least for the cases I've been looking at

There may be additional cases such as renames and others not covered by that, where we need to listen to RDT

**Comment by vasily-kirichenko** [comment]
I confirm it's fixed in #3025. Thanks!

**Comment by dsyme** [comment]
Fixed by https://github.com/Microsoft/visualfsharp/pull/3025
