### ISSUE TITLE
System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-Editor>.$Views' threw an exception.

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2918]
1. Load a solution so that a script auto opens. 
2. Unhandled error dialog pops up, no features work.
3. The log contains the following:

> System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-Editor>.$Views' threw an exception. ---> System.InvalidOperationException: The 'ResourceAssembly' property of the 'Application' type cannot be changed after it has been set. at System.Windows.Application.set_ResourceAssembly(Assembly value) at <StartupCode$FSharp-Editor>.$Views..cctor() --- End of inner exception stack trace --- at Microsoft.VisualStudio.FSharp.Editor.SessionHandling.Microsoft-VisualStudio-Language-Intellisense-IQuickInfoSourceProvider-TryCreateQuickInfoSource@33.Microsoft-VisualStudio-Language-Intellisense-IQuickInfoSource-AugmentQuickInfoSession(IQuickInfoSession session, IList`1 quickInfoContent, ITrackingSpan& applicableToSpan) at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate() at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start() at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e) at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()

It's not reproduced 100% of time.

**Comment by majocha** [comment]
@vasily-kirichenko Well, this sucks as it shouldn't happen and also I can't reproduce it. Could you please try if #2920 makes things better?

**Comment by dsyme** [comment]
closing since #2920 has been merged
