### ISSUE TITLE
Navbar steals keyboard focus from pre-opened editor.

### ISSUE THREAD

**Issue by majocha** [Microsoft/visualfsharp#2921]
#### Repro steps:

Open solution with some .fs (not .fsx) file pre-opened in editor.

Try arrow keys, tab and backspace in the opened editor.

Navbar reacts instead of the editor.

Latest master and nightly.

**Comment by dsyme** [comment]
This really needs to be fixed - I noticed it a lot today

Anyone know which PRs caused this?

**Comment by dsyme** [comment]
@majocha Do you know what might have caused this?  I have no idea. thanks

**Comment by majocha** [comment]
@dsyme for me it just went away but I missed the precise moment it got fixed. Do you still see this bug?

**Comment by dsyme** [comment]
@majocha I thought I saw it last night.  But it's true - it seemed to happen for a while but not anywhere near as often now.

**Comment by dsyme** [comment]
I'll close until we see it come back
