### ISSUE TITLE
When running "dotnet test", some values are not able to get correctly.

### ISSUE THREAD

**Issue by yukitos** [Microsoft/visualfsharp#2925]
Originally reported by @pocketberserker.

@pocketberserker and I know that the current version of F# doesn't fully support .net core, but we'd report this to be fixed until RTMed.

#### Repro steps

1. Download repro code from below and extract on a directory
   https://github.com/pocketberserker/FSharpNETCoreSandbox/tree/load-assembly-in-test

2. cd to `Test` subfolder, run `dotnet restore` and `dotnet test`

3. Output some text including below:
   ````text
   module: int value, 1
   module: string value, string
   module: record, null
   module: struct record, {V = 0;}
   static property: record, {V = 1;}
   static property: struct record, {V = 1;}
   ````

   In each line, left side of comma indicates the name of the value defined in `Test/Tests.fs` and right side is its value.

#### Expected behavior

* Record value named `module: record` is not `null` and is an instance of `Foo`.

* Struct record value named `module: struct record` keeps its member's value: `1`.

#### Actual behavior

* `module: record` is `null`.
* `module: struct record` doesn't keep its member's value.

#### Known workarounds

We don't have any workarounds.

#### Related information 

Related code to output these values can be found here:
https://github.com/pocketberserker/FSharpNETCoreSandbox/blob/load-assembly-in-test/TestAdapter/TestAdapter.cs#L27-L47

* Operating system : Windows 10 (10.0.14393)
* .NET Runtime, CoreCLR or Mono Version : 1.0.0

**Comment by dsyme** [comment]
@enricosada What do you make of this one? thanks

**Comment by enricosada** [comment]
That because test are exe not lib. 
See https://github.com/dotnet/netcorecli-fsc/issues/79#issuecomment-282092726

Workaround is to add an empty main ( ser reference issues)

If fixed, but require a new release of dotnet cli because is in the templates

**Comment by enricosada** [comment]
@yukitos see reference issue for workaround (add an empty main)

This can be closed, will Ben fixed with next release

**Comment by dsyme** [comment]
thanks @enricosada !

**Comment by yukitos** [comment]
Good to hear that. thanks @enricosada !
