### ISSUE TITLE
Bundle partial `FSharp.NET.Sdk`

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#2928]
the new fsproj templates (msbuild 15 and .net core sdk) need a partial `FSharp.NET.Sdk` bundled in msbuild Sdks directory, like .net core sdk (dotnet/cli) is doing now.

It also need to be updated for https://github.com/dotnet/project-system/issues/1857 , work is tracked in https://github.com/dotnet/netcorecli-fsc/issues/106

/cc @brettfo @KevinRansom 

# Workaround

- locate `dotnet.exe`
- copy `sdk\1.0.1\Sdks\FSharp.NET.Sdk` subdirectory into `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\FSharp.NET.Sdk\`

**Comment by cloudRoutine** [comment]
This is how the VSIX can be configured to install the sdk components into the correct directory
https://docs.microsoft.com/en-us/visualstudio/extensibility/set-install-root

**Comment by enricosada** [comment]
To add some context, atm it need to be bundled this specific nuget packages, and just `Sdk` dir.

- bundle `FSharp.NET.Sdk` version `1.0.0-beta-040011`
- just the `Sdk` directory, not the others

like [dotnet cli does](https://github.com/dotnet/cli/blob/85ca206d84633d658d7363894c4ea9d59e515c1a/build/BundledSdks.props#L8), dotnet/cli bundle only `Sdk` dir too

I'll publish a package version with just the `Sdk` dir, ready to bundle, ref https://github.com/dotnet/netcorecli-fsc/issues/56 in next 1.0.4 release.
