### ISSUE TITLE
Partial application should have "closure" for mutable parameter

### ISSUE THREAD

**Issue by LincolnYang1** [Microsoft/visualfsharp#2930]
it seems partial application doesn't have "closure", if I use mutable variable as parameter to build partial application, it seems it will make a copy of this parameter and as "immutable".  this is very misleading sometime, especial if not use partial application, just add full parameter, in case below just add b it will have a big different behavior

#### Repro steps

let add a b = a + b
let mutable mutVal1 = 1

// case 1. partial application
let addMutVal1_partial = add mutVal1

printf "mutVal1 = 1, mutVal1+100=%d" (addMutVal1_partial 100)
mutVal1 <- 1000

printf "it should equals to 1001, but partial application doesn't use 'closure' to capture in runtime \r\n" 
printf "mutVal1 = 1000, mutVal1+100=%d" (addMutVal1_partial 100)

// case 2. no partial application, correct behavior
printf "\r\n  no partial application, correct behavior\r\n"
mutVal1 <- 1
let addMutVal1_no_partial b = add mutVal1 b

printf "mutVal1 = 1, mutVal1+100=%d" (addMutVal1_no_partial 100)
mutVal1 <- 1000
printf "mutVal1 = 1000, mutVal1+100=%d" (addMutVal1_no_partial 100)

#### Expected behavior

if partial application take mutable variable as parameter, it should have "closure" to capture the changed value in run time. otherwise it will cause confusion  

#### Actual behavior

partial application will make a "immutable" copy from mutable variable. 

#### Known workarounds

do not build partial application with mutable parameter

#### Related information 

Provide any related information 

* Windows 7
* Branch
* .NET Runtime 4.6
* VS2015 
* https://github.com/fsharp/fslang-suggestions/issues/565

**Comment by dsyme** [comment]
@LincolnYang1 This is by design
