### ISSUE TITLE
Incorrect Code can be simplified message

### ISSUE THREAD

**Issue by daz10000** [Microsoft/visualfsharp#2931]
Visual F# in 2017 is frequently suggesting these kinds of simplifcation in x.[ ] type constructs where x is a string.    In the case shown here, it would break the code by removing the identifier into which we are indexing.

![image](https://cloud.githubusercontent.com/assets/6342645/25448516/8c52acda-2a6d-11e7-84df-85adc454789d.png)

#### Related information 

Provide any related information 

* Win10
* .NET Runtime, CoreCLR or Mono Version  4.6.1
* Editing Tools (e.g. Visual Studio Version) VS2017 pro  Version 15.1 26403.7
* Visual F# 4.1 
* Indications of severity  : easy to avoid by not taking suggestion

**Comment by vasily-kirichenko** [comment]
@daz10000 It's fixed long time ago, use https://blogs.msdn.microsoft.com/dotnet/2017/03/14/announcing-nightly-releases-for-the-visual-f-tools/ please.

**Comment by daz10000** [comment]
Much appreciated.  You guys rock.  I figured something this obvious would have been cleaned out.  Pity they don't do product updates more frequently!
