### ISSUE TITLE
Breakpoint Resolution fails in if block

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#2934]
TODO - getting repro zip, but:

The gist of this is setting a breakpoint [here](https://github.com/cartermp/15.2-E2E/blob/master/E2E.Core/PigLatin.fs#L9).

Expected: Line 9 has a breakpoint set.
Actual: Line 11 is where the breakpoint is set.

**Comment by forki** [comment]
Will take a look.

**Comment by cartermp** [comment]
I can get the zipped project tomorrow if you can't repro it yourself.  It's behind corpnet resources and I'll need to snag it from a VPN on my desktop.  This is from an internal testing thing where I snuck some F# in there, so it was a new user.

**Comment by forki** [comment]
![bp](https://cloud.githubusercontent.com/assets/57396/25518740/412c2234-2bf5-11e7-822b-14b309387c8b.gif)

can't repro on master

**Comment by cartermp** [comment]
Let me see if I can reproduce it on the internal build used.  It's behind master, though I don't think any improvements to breakpoint resolution were made between that build and master.

**Comment by forki** [comment]
Maybe you need to be a bit more specific about where and how you tried to
set it

Am 28.04.2017 3:41 nachm. schrieb "Phillip Carter" <notifications@github.com

**Comment by cartermp** [comment]
This is from an internal bug report.  Reported as failing for both clicking and f9 on line 9.

**Comment by forki** [comment]
Mhm as screencast shows I can't repro

Am 28.04.2017 3:47 nachm. schrieb "Phillip Carter" <notifications@github.com
