### ISSUE TITLE
Remove ReferenceEquals of Tuple from ConstraintSolver

### ISSUE THREAD

**Issue by manofstick** [Microsoft/visualfsharp#2936]
[ConstraintSolver.fs](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/ConstraintSolver.fs#L2365-L2374) uses ReferenceEquals (via the === function) on a Tuple which is dubious.

#2923 commented on this functionality, and it was noted that it is actually undefined behaviour, so it should be removed. I will probably do this at some stage (but if anyone else feels like it, go for it!), and this Issue is just to act as a reminder.

**Comment by dsyme** [comment]
fixed
