### ISSUE TITLE
ship FSharp.Core.pdb files

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/visualfsharp#294]
Please include `FSharp.Core.pdb` files in the `FSharp.Bundle.exe` distributions.

**Comment by KevinRansom** [comment]
I believe they should be published to the Microsoft public symbol server.  At least for the VS2013, VS 2012.  I think we may have forgotten to do that for the two Out of band releases.  If they are not then we should figure out how to do so.

Details:  https://msdn.microsoft.com/en-us/library/b8ttk8zy(v=vs.90).aspx

Thanks

Kevin

**Comment by ctaggart** [comment]
They should be included with all the builds. Symbol servers are not a good idea, especially the Microsoft public symbol servers that tend to strip information from the pdb files. If the pdb files get source indexed, then users will be able to debug into FSharp.Core and see the exact source. If Power Tools adds support https://github.com/fsprojects/VisualFSharpPowerTools/issues/201 then it will be possible to F12 into the source at design time.

Take an additional step and making F# more open source. Provide users the ability to see the source on demand. Including the pdb files with the builds is an easy first step.

**Comment by enricosada** [comment]
:+1: for @ctaggart source index, is great

**Comment by KevinRansom** [comment]
I don't think the symbol servers strip the information.  I think we just build and post stripped symbols for some products.  Shipping symbols.with product just bloats the size of the deployment and they are rarely used by anyone.  Symbol and source servers are the right solution for that.

**Comment by ctaggart** [comment]
GitHub can be the *source* server. Source indexed .pdb files would get more eyes on the F# source code and make it much easier to contribute back. Every build can include its own symbols. The symbols never get lost. Including the .pdb files will make the distribution bigger. You have options:

1. include the .pdb in `FSharp_Bundle.exe`
2. create a separate distribution for includes the .pdb files, something `FSharp_Bundle_with_Symbols.exe`
3. create a separate distribution for just the .pdb files, something like `FSharp_Bundle_Symbols.zip`.

Option 1 is my favorite. Would it make the 27.8 MB download twice as big? It is totally worth it.

**Comment by KevinRansom** [comment]
We are currently struggling with the need to reduce the size of installers not increase them.  The preview builds we post are intended to be the exact installers that we use for Oob and Visual Studio Releases.  It is not our plan to increase their size without a corresponding increase in functionality.  We do not expect the majority of F# developers to have the need to debug our libraries or tools.

To debug Visual F# with debugging symbols you will need to rebuild the open source codebase and either patch the VS or debug using the enableopensource project in deployment.sln.

**Comment by baronfel** [comment]
It would be killer to have this feature.  The biggest stumbling block I get when introducing C# devs to F# is that they lose the simple f12 to view source workflow that they are used to.  They view this as a symbol of immature tooling, and then tune out the rest of the benefits of the language.  Showing tooling on par with the other .Net languages is a critical aspect of evangelizing F#.

**Comment by ctaggart** [comment]
Are there .pdb files available for the RC that I can test?

**Comment by latkin** [comment]
@ctaggart - no AFAIK symbols aren't available anywhere public.  Maybe we can find them on an internal build share and distribute them, will need to check.

**Comment by ctaggart** [comment]
I'd really love to be able to include source indexed .pdb files with the `FSharp.Core` published on NuGet. Users would like to try out the RC or another preview build on NuGet https://github.com/fsharp/fsharp/issues/429, so now would be a good time. In order for the pdb files to be source indexed, I just need to know the git commit for the build and it must have been compiled with the `.fs` line endings set as `lf` since you have a `.gitattributes` http://ctaggart.github.io/SourceLink/how-it-works.html#Line-Endings.

**Comment by latkin** [comment]
@ctaggart I don't think there is a particular reason for us not to redist the PDBs.  The Roslyn people are also trying to figure out a practical way to do this, too.

In internal TFS source control that produces official builds, everything has CR/LF.  We can't change that now, though for future we could look into it.

**Comment by ctaggart** [comment]
I released a new version of SourceLink.exe yesterday that allows you to automates switching those files to `LF` before the build if you can't adjust the Git `core.autocrlf` setting before the clone. It can be used to change the line endings before the compile and also do the source indexing after the compile. I tried it out on this project and it works great.

SourceLink.exe can be installed/copied however you want and is available on Chocolatey and NuGet galleries. Here I unset the `core.autocrlf` settings as part of the test. It sadly defaults to behaving like 'true'.
```
choco install SourceLink --version 0.6.1 -y --force
git config --global --unset core.autocrlf
git config --system --unset core.autocrlf
git clone https://github.com/Microsoft/visualfsharp.git --depth 1
cd .\visualfsharp
SourceLink.exe linefeed -pr .\src\fsharp\FSharp.Core\FSharp.Core.fsproj
.\appveyor-build.cmd
Show-Tree Release -ShowLeaf
SourceLink.exe index -pr .\src\fsharp\FSharp.Core\FSharp.Core.fsproj -pp Configuration Release -u 'https://raw.githubusercontent.com/Microsoft/visualfsharp/{0}/%var2%'
```

After it is source indexed, you can have it download and `check` all of the file checksums against what is pdb.
![image](https://cloud.githubusercontent.com/assets/80104/8470869/9f12bb7c-2046-11e5-95da-a37e26a992f0.png)

Any/all of the pdb files can be indexed this way. It will allow developers to get the exact code on demand while debugging and sometimes when hitting F12 during design time if they have the Visual F# Power Tools installed.

**Comment by dsyme** [comment]
closing old discussion

**Comment by ctaggart** [comment]
@dsyme Why was this closed? Was it decided not to ship FSharp.Core.pdb files or did you find a way to actually ship them?

**Comment by dsyme** [comment]
Only because it was marked discussion and stale.  I'll reopen it as a feature suggestion.

**Comment by jdh30** [comment]
"We do not expect the majority of F# developers to have the need to debug our libraries or tools."
At least in VS2015, exceptions thrown during the computation of global constants makes the debugger look for FSharp.Core.pdb, i.e. ordinary developer errors can require the debugging of your libraries.
![image](https://cloud.githubusercontent.com/assets/3476054/26525649/ee044050-4355-11e7-94c7-210fd9a57395.png)

**Comment by KevinRansom** [comment]
@jdh30 
We will be embedding portable PDBs in dlls shipped via nugget.  The windows pdbs for shipped FSharp dll are deployed to a symbol server.

**Comment by enricosada** [comment]
@KevinRansom afaik this is now done with `FSharp.Core` 4.2.x packages, so this can be closed?

**Comment by KevinRansom** [comment]
Can we leave it around for a while.  I want to revisit everything we do about pdbs, including generating portables by default and converting them to windows pdb on windows builds.

**Comment by ctaggart** [comment]
The pdb files are still missing from the current FSharp.Core 4.2.3.

```
C:\Users\camer\.nuget\packages\fsharp.core> tree /f
└───4.2.3
    │   fsharp.core.4.2.3.nupkg
    │   fsharp.core.4.2.3.nupkg.sha512
    │   fsharp.core.nuspec
    │
    └───lib
        ├───net45
        │       FSharp.Core.dll
        │       FSharp.Core.optdata
        │       FSharp.Core.sigdata
        │       FSharp.Core.xml
        │
        └───netstandard1.6
                FSharp.Core.dll
                FSharp.Core.optdata
                FSharp.Core.sigdata
                FSharp.Core.xml
```

If you are using `dotnet pack`, you can enable the pdb files to be included with this msbuild property:
```
  <PropertyGroup>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
</PropertyGroup>
```
That is what I did for SourceLink 2.7
https://github.com/ctaggart/SourceLink/blob/master/SourceLink.Create.CommandLine/SourceLink.Create.CommandLine.props

**Comment by ctaggart** [comment]
Microsoft has decided to ship their source linked pdb files using to their symbol server. Please do the same. https://github.com/aspnet/Universe/issues/850

Everyone else outside of Microsoft, it is [recommended by Microsoft](https://github.com/aspnet/Universe/issues/131#issuecomment-363269268) to put the source linked PDBs in the nuget packages.

**Comment by danyx23** [comment]
I just ran into this as well, would be great to have pdb files available for fsharp.core!

**Comment by 7sharp9** [comment]
Same, its painful to debug FSharp.Core if you need to without anything like this.

**Comment by ctaggart** [comment]
Did the [FSharp.Core 4.5.0](https://www.nuget.org/packages/FSharp.Core/4.5.0) pdb files get published somewhere internally such as the [prodcon symbol server](https://github.com/aspnet/Universe/issues/850)?

**Comment by KevinRansom** [comment]
The desktop symbol files should have been published to the Microsoft Public Symbol server.  We do not yet build and publish nuget, portable pdb packages.  We should certainly do so.

Something else to look into …  yay!!!!

**Comment by ctaggart** [comment]
This is technically done. The pdb files that match the dll's in the 4.5.2 nupkg are on the Microsoft Symbol Servers.

![image](https://user-images.githubusercontent.com/80104/45857856-919dd800-bd0f-11e8-98b9-4bfec94e2c9a.png)

![image](https://user-images.githubusercontent.com/80104/45857872-a8442f00-bd0f-11e8-82d5-feb42dff6454.png)

![image](https://user-images.githubusercontent.com/80104/45857903-bf831c80-bd0f-11e8-9a52-05b9771887ec.png)

For me, it download the symbol to:
C:\Users\taggac\AppData\Local\Temp\SymbolCache\FSharp.Core.pdb\0A868D34CF4743D0B21CC9DF656936A71\FSharp.Core.pdb

Now you just need to:
1. enable SourceLink so that the source can be loaded
2. switch it over to portable pdb so that it can be used from non-Windows

Progress! I'll open up separate issues.
