### ISSUE TITLE
Context Menu for F# Project System has some unlocalized strings.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#295]
Description:  Title has the details.

1.  Install a non English language version of Visual Studio.
2,  Create a new F# project
3.  Right click on the Project System
4. Look at the context menu and notice the English language words.

__Project System Context Menu__
![localizationprojectsystem](https://cloud.githubusercontent.com/assets/5175830/6473870/23517594-c1b1-11e4-94c2-ca6c40662bf5.png)

__Send file to fsi not localized__
![localizationprojectsystem3](https://cloud.githubusercontent.com/assets/5175830/6474098/cf8e27ca-c1b2-11e4-9e1a-d90cd2099f39.png)

__F# interactive tool window caption is not localized__
![localizationprojectsystem2](https://cloud.githubusercontent.com/assets/5175830/6474062/95a6b310-c1b2-11e4-9f2c-f230a4818175.png)

__Send References to FSI is not localized__
![send references](https://cloud.githubusercontent.com/assets/5175830/6474168/6b9e8a2e-c1b3-11e4-948f-86ce34aa74e6.jpg)

Expected correct localizations

**Comment by enricosada** [comment]
an easy `up-for-grabs`

**Comment by KevinRansom** [comment]
Funnily enough @enricosada, it was not not an easy up for grabs because localization is mostly handled as part of the internal codebase.  It required updates to our internal build infrastructure and a minor mod to the open source codebase.  Anyway it's fixed now and checked in internally.

**Comment by enricosada** [comment]
@KevinRansom an info, where are the localized resource files? in the internal build? 
i do not see the translated resource files in the repo
