### ISSUE TITLE
Fix up-for-grabs.net url

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#296]
The Visual F# Tools on http://up-for-grabs.net target the old codeplex repo instead of this github repo

**Comment by PatrickMcDonald** [comment]
Created pull request: dahlbyk/up-for-grabs.net#174

**Comment by enricosada** [comment]
ouch, i was thinking project owner needed to do something. thx @PatrickMcDonald

**Comment by PatrickMcDonald** [comment]
Maybe they do :) We'll see what  happens

**Comment by latkin** [comment]
Yeah, also discussed here https://github.com/dahlbyk/up-for-grabs.net/issues/154#issuecomment-77162916
