### ISSUE TITLE
Autocomplete appears when typing type argument names

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#2961]
Type the following (and wait for intellisense to appear):

```f#
type Foo<'S
```

You'll notice that intellisense is suggesting names to complete with - it shouldn't be suggesting anything at this point.

**Comment by saul** [comment]
I think this has been the case this @vasily-kirichenko's #2644 PR was merged

**Comment by vasily-kirichenko** [comment]
Check parse AST for that code. If there is no meaningful one, we cannot do anything with it (we could use the lexer though, but it's too hacky).

**Comment by saul** [comment]
This has been significantly interfering with my ability to code this week, I'm using generics everywhere and this is making it even more painful than it needs to be.

@vasily-kirichenko can you point me in the right direction for the code that needs to be changed here?

**Comment by vasily-kirichenko** [comment]
@saul You can make https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/ServiceUntypedParse.fs#L930 return `CompletionContext.Invalid` if we are at type parameters or add a new case into it and handle it in https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/service.fs#L783

**Comment by vasily-kirichenko** [comment]
But I suspect there's no AST in code like `type My<|`
