### ISSUE TITLE
Quick Info throws exceptions

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2966]
On current master I always get the following

![image](https://cloud.githubusercontent.com/assets/873919/25565709/2bb7334e-2dd5-11e7-9790-d02462ae16c9.png)

**Comment by majocha** [comment]
@vasily-kirichenko sorry for this, clearly my previous attempt didn't work. I'm not sure but I suspect you have another extension that also sets Application.ResourceAssembly. I must find a better way for locating resources in a installed vsix.

**Comment by vasily-kirichenko** [comment]
@majocha yes, we reuse the resources for Code Lens. We'd like to reuse it very very much :)

**Comment by majocha** [comment]
@vasily-kirichenko Done, this time for good :)
I think, the code that loads the styles can be freely put into a module and reused now.
