### ISSUE TITLE
Assert(s) during fsharpqa: "no compiler phase..."

### ISSUE THREAD

**Issue by brodyberg** [Microsoft/visualfsharp#297]
Steps
* Install Windows 8.1 or Threshold preview (on MSDN downloads)
* Clone repo
* Switch to fsharp4
* All build steps (except visual studio stuff)
* Ngen step
* Build test tools step
* runTests.cmd debug fsharpqa

Observed: 

I see multiple abort/retry/ignore dialogs with stacks that say: "Compile error seen with no phase to attribute it to..." 

[Full exception](http://imgur.com/4QUCXKi) screenshot. 

Expected: 

This type of window isn't mentioned in the test docs, and with no changes I am surprised it is happening. Is this expected? Typically an assert dialog like this seems like a pretty serious issue. I've seen this on multiple machines. Am I doing something wrong?

I would expect there to be no assert dialogs during testing and for the tests to pass without incident from a clone.

**Comment by latkin** [comment]
There are a various bogus asserts which cause core and IDE tests to fail/hang.  I don't bother running full tests against debug builds due to this (and because it's super slow).  You might get fewer asserts if you run without using the hosted compiler (remove/comment [this line](https://github.com/Microsoft/visualfsharp/blob/fsharp4/tests/RunTests.cmd#L39)).

It would be great if someone went though and systematically removed the bogus asserts.  That's not a small job, though.

**Comment by brodyberg** [comment]
The hard part would be removing all and only bogus asserts correct? You aren't saying blow away all asserts I imagine.

**Comment by latkin** [comment]
Right.  If an assert captures a truly "this should be impossible" kind of situation that's good. Unfortunately I think there are a few that fail in legitimate error cases and cause noise.

**Comment by brodyberg** [comment]
I think this is doable - I feel like I get plenty of asserts, but not an overwhelming number. Let me see about capturing them and then moving to the next part, which is, as you said, identifying which are bogus. I'll try to make a list of bogus/not bogus, have you review and then we can move on from there with specific disabling.

**Comment by brodyberg** [comment]
I think the problem is perhaps this, in ErrorLogger.fs:369, which causes uses of errorR in tastOps.fs to throw the "Compile error with no phase" assert which I think is definitely distracting and possible inaccurate. 

    let errorR  exn = CompileThreadStatic.ErrorLogger.ErrorR exn

I am going to track the use of errorR into tastOps and see what I get.

**Comment by brodyberg** [comment]
errorR is called in about a dozen places in tastOps.fs. What I am going to do is figure out why some tests come through errorR in BuildPhase.DefaultPhase and if that matters.

**Comment by dsyme** [comment]
closing this old issue
