### ISSUE TITLE
Wrong completion for property initializers within constructor call

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#2973]
1. Normal ctor argument (OK)

![image](https://cloud.githubusercontent.com/assets/873919/25610440/dbdaae5c-2f2b-11e7-91c8-a5fce460eb27.png)

2. Writable property (Fail)

![image](https://cloud.githubusercontent.com/assets/873919/25610509/310e2462-2f2c-11e7-9776-e0d73514041a.png)

3. No properties is there is a space between ctor name and open paren:

![image](https://cloud.githubusercontent.com/assets/873919/25610801/4bcbeaf4-2f2d-11e7-850e-8712e0aace8e.png)

**Comment by vasily-kirichenko** [comment]
@dsyme any ideas where those property names suffixed with `@` may come?

**Comment by 0x53A** [comment]
The backing fields of Records are postfixed with @, and the symbol of the completion item is a field, not a property, afaik, so that would match.

**Comment by dsyme** [comment]
I believe something should be filtering for IsCompilerGenerated (I would need to double check though)

**Comment by vasily-kirichenko** [comment]
I checked the Item, it has IsCompilerGenerated = false. I also expected all properties in the debugger and have not found any which can be used to filter the item out (except by the suffix itself in xxxName props, but it's silly)

**Comment by dsyme** [comment]
> I checked the Item, it has IsCompilerGenerated = false. I also expected all properties in the debugger and have not found any which can be used to filter the item out (except by the suffix itself in xxxName props, but it's silly)

Ah ok. AFAIK it should really be IsCompilerGenerated=true.

**Comment by vasily-kirichenko** [comment]
#3 is fixed in https://github.com/Microsoft/visualfsharp/pull/2981

**Comment by vasily-kirichenko** [comment]
@dsyme I tried to find how to fix `IsCompilerGenerated` flag for auto properties. Binding is generated in TypeCheckes.fs, 15832 (GitHub is unable to show this file in a whole, so I cannot make a link to the line), search for line
```fsharp
[(SynMemberDefn.LetBindings ([binding], isStatic, false, mWholeAutoProp))]
```
I tried to add a field to `LenBinding`, but I've no idea how to pass it through all stages to `Val` and further to `ValRef`.

**Comment by dsyme** [comment]
@vasily-kirichenko Yes, this line is always false for all syntactic let bindings:

        let compgen = false

That flag makes its way to ``TcPatBindingName``.  I think the thing to do is to change this:

```
and TcPatBindingName cenv env id ty isMemberThis vis1 topValData (inlineFlag,declaredTypars,argAttribs,isMutable,vis2,compgen) (names,takenNames:Set<string>) = 
    let vis = if Option.isSome vis1 then vis1 else vis2
    if takenNames.Contains id.idText then errorR (VarBoundTwice id)
    let baseOrThis = if isMemberThis then MemberThisVal else NormalVal
```
to
```
and TcPatBindingName cenv env id ty isMemberThis vis1 topValData (inlineFlag,declaredTypars,argAttribs,isMutable,vis2,compgen) (names,takenNames:Set<string>) = 
    if Option.isSome vis1 then vis1 else vis2
    let vis = if Option.isSome vis1 then vis1 else vis2
    if takenNames.Contains id.idText then errorR (VarBoundTwice id)
    let compgen = compgen || IsCompilerGeneratedName id.idText
    let baseOrThis = if isMemberThis then MemberThisVal else NormalVal
```

**Comment by vasily-kirichenko** [comment]
@dsyme thanks, it works https://github.com/Microsoft/visualfsharp/pull/2991

**Comment by vasily-kirichenko** [comment]
The fix makes read-only properties appear at constructor argument list site. I cannot fix it, so I closed the PR and don't care about this bug anymore, closing it.

**Comment by realvictorprm** [comment]
I ran into this problem with the code lens so this needs to be fixed.
Going to have a look into this stuff.

Either someone reopens the issue or I'm going to create a new one specifically for this one
