### ISSUE TITLE
Gitter chat 

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#2975]
Since noone from the Visual F# team hangs out on gitter we should remove the link from the readme. Maybe we switch it against slack link

**Comment by dsyme** [comment]
(It would be good if someone with pull permissions could hang out in the chat rooms - but for me personally my digital life is already flooded with notifications, and I find it really hard to hang out on slack or gitter - github is already a form of chat room for me)

**Comment by forki** [comment]
1) yes Visual F# team should be present in "blessed" chat room (not everyone all the time, bu in principle)
2) the linked room is basically abandoned from the main contributors here. we as a community seem to be elsewhere ("everyone" seems to be on slack"). my request is more to point people to where we actually are.

**Comment by dsyme** [comment]
> my request is more to point people to where we actually are.

OK, please submit PR?

> yes Visual F# team should be present in "blessed" chat room (not everyone all the time, bu in principle)

Nah :) The use of chat rooms in this repo is is something that some contributors happen to like, but please there should be no attendance requirement or expectation on the part of on maintainers.  (I personally don't use chat rooms - I dislike the synchronous nature of the communication, the notification noise and the lack of solid record of discussions in an organized, issue-by-issue way.)

Also, adding one regular maintainer won't particularly solve anything fundamentally because different contributors have different knowledge.  If something needs to be brought to the attention of a maintainer, it should be in a github issue.

**Comment by forki** [comment]
The VF# team is represented on the slack channel by @cartermp. And he does a great job on communicating things over there. So there is no issue at all. 
I just wanted to ask if we want to bless the very very informal slack channel before I send the PR.

**Comment by dsyme** [comment]
> The VF# team is represented on the slack channel by @cartermp. And he does a great job on communicating things over there. So there is no issue at all. 

OK, super.  So it's how @cartermp works - which is great - but is not a permanent expectation on the maintainers :)


> I just wanted to ask if we want to bless the very very informal slack channel before I send the PR.

Fine my be

Aside: I think it's better to talk in terms of roles than affiliations, i.e. "maintainer" not "Microsoft employee" of "Visual F# team member".  We should try to be using standard open source terminology which AFAICS is role-based.  Different contributors play different roles.  Using that terminology, @KevinRansom, @cartermp, @brettfo and myself are all maintainers on this repo.

**Comment by forki** [comment]
I don't think these roles apply for MS repos, but that's another topic. Here I just want evaluate if we want to point people to slack or just delete the gitter link.

**Comment by cartermp** [comment]
I'd be fine with putting in the FSSF slack link.  Even if much of the conversation about tools is actually in the fpchat slack, I'm all for getting more people into the FSSF slack.

**Comment by forki** [comment]
Yeah that one is an option as well. It's not the same amount of chatter on
this one but it's considered more "civilized". I'll send a pull request

Am 02.05.2017 2:51 nachm. schrieb "Phillip Carter" <notifications@github.com
>:

I'd be fine with putting in the FSSF slack link. Even if much of the
conversation about tools is actually in the fpchat slack, I'm all for
getting more people into the FSSF slack.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/issues/2975#issuecomment-298626276>,
or mute the thread
