### ISSUE TITLE
Build error: The module/namespace 'Microsoft.FSharp.Core' from compilation unit 'FSharp.Core' did not contain the namespace, module or type 'string' 

### ISSUE THREAD

**Issue by chillitom** [Microsoft/visualfsharp#2977]
Receive the following error whilst trying to build the F# compiler as detailed in DEVGUIDE.md.

`build.cmd`

`FSC : error FS0193: The module/namespace 'Microsoft.FSharp.Core' from compilation unit 'FSharp.Core' did not contain the namespace, module or type 'string' [C:\Projects\visualfsharp\src\fsharp\FSharp.Core\FSharp.Core.fsproj]`

Log of the build output when run as normal user and again as a user with admin perms.

[build.admin.txt](https://github.com/Microsoft/visualfsharp/files/970199/build.admin.txt)
[build.txt](https://github.com/Microsoft/visualfsharp/files/970200/build.txt)

* Operating system - Win7
* Branch - master
* .NET Runtime, CoreCLR or Mono Version: 4.6.1
* Editing Tools (e.g. Visual Studio Version) VS2017

**Comment by forki** [comment]
@chillitom can you please try:

* git clean -xdf
* build.cmd debug

**Comment by chillitom** [comment]
Seems like something was holding a handle open to FSharp.Build-proto.dll causing it to fail to rebuild, unfortunately I didn't manage to see what it was.
