### ISSUE TITLE
QuickInfo is often not working 

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#2999]
For my local install of "master" QuickInfo is not working in many situations

#### Repro steps

1. Take the following code in ``a.fsx``

```
let y = 1

type AlarmStatus =
    | NoData

let v = y
```

2. Hover over "NoData" or "AlarmStatus" or "y" on the last line

#### Expected behavior

QuickInfo is shown

#### Actual behavior

Nothing is shown.  Compare with hovering over "let y" or "let v" (which are only included to show uick info is working in some situations)

#### Known workarounds

None

**Comment by majocha** [comment]
![qi](https://cloud.githubusercontent.com/assets/1760221/25781273/effa65fc-3337-11e7-8ce5-d00cb38cdc73.gif)
@dsyme it should work.
Nothing comes to my mind but maybe try a rebuild. I do a `git clean -fdx` and rebuild when things behave oddly and sometimes it helps...

**Comment by dsyme** [comment]
Thanks - I'll close and retry tomorrow

**Comment by dsyme** [comment]
This repros for me if no solution has been opened.  The bug is here:

```fsharp
    member __.RelativePath (range: range) =
        let targetUri = Uri(range.FileName)
        Uri(solution.FilePath).MakeRelativeUri(targetUri).ToString()
        |> Uri.UnescapeDataString
```

Here ``solution.FilePath`` is null.  Oh for option types...
