### ISSUE TITLE
Struct Union Fails to Compile

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#3003]
@dsyme there's still a simple case where struct unions fail to compile

```fsharp
    type [<Struct>] Failure = A | B 
```

![](http://i.imgur.com/o9onwHw.png)

This is the repro repo that's setup to use the compiler tools to build

[struct-union-failure.zip](https://github.com/Microsoft/visualfsharp/files/984919/struct-union-failure.zip)

Built using `FSharp.Compiler.Tools (4.1.17)`

Please provide a succinct description of the issue.

#### Repro steps

1. open repro sln
2. build sln

**Comment by dsyme** [comment]
@cloudRoutine It took a while but see https://github.com/Microsoft/visualfsharp/issues/3274 for the fix
