### ISSUE TITLE
NullReferenceException during loading VFT solution

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3005]
![image](https://cloud.githubusercontent.com/assets/873919/25842833/0fa38f42-34ae-11e7-9a55-84ca6bfa15af.png)

Where `referencedProjectGuid` = `{1c5c163c-37ea-4a3c-8ccc-0d34b74bf8ef}`

**Comment by dsyme** [comment]
I think this is fixed by this part of @saul's work https://github.com/Microsoft/visualfsharp/pull/2909/files#diff-6c1f1c169f25637ae2a051ba57b20d4eR876

**Comment by dsyme** [comment]
I copied @saul's fix into #3010
