### ISSUE TITLE
GoTo Line has a pause after hitting "return" (due to colorization?)

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#3011]
#### Repro steps

1. Take a large file
2. Use "Go to Line" (Ctrl-G) then type a number then hit return

#### Expected behavior

Goes to the line very fast, then colorizes

#### Actual behavior

Takes a while, I think it is colorizing the file.  (Is it waiting for a semantic colorization?  Or just slowly doing syntax colorization)

#### Known workarounds

Be patient and just wait

**Comment by vasily-kirichenko** [comment]
I'm afraid we don't control this.

**Comment by dsyme** [comment]
Yeah I was wondering.  Maybe it is just incentive for us to make the appropriate colorizer faster, or submit a roslyn bug to delay colorization

**Comment by majocha** [comment]
I think something's not right on our side. For comparison open ProjectNode.cs in ProjectSystem.Base. Over 6k lines and go to line is instantaneous.

**Comment by vasily-kirichenko** [comment]
The only thing I can think is syntactic colorization, which is synchronous in Roslyn (for a reason I don't fully understand, something like "we made `AddSyntacticClassificationsAsync` async, but call in synchronously from UI thread because we expect it to be super fast, because it's just tokenizing after all). The problem is that we need to tokenize all lines above current one in order to keep proper lexer state, so, when you jump to line #10000 from line #1, 10K line are tokenized, which is fast, but not lighting fast.

(that's how I see it, maybe I'm wrong)

**Comment by majocha** [comment]
I suspect it's the UI of that go to popup that blocks and stutters for some reason. Try making large jumps around the code by right clicking scrollbar and selecting "scroll here" and it's always snappy.

**Comment by vasily-kirichenko** [comment]
My VFT is broken, see the latest issue. Cannot test.

**Comment by dsyme** [comment]
> The only thing I can think is syntactic colorization..

I think it must be that.  If you go to the last line of a large file, it's slow. Then back to the top, and try again to the last line, and its fast.  That strongly seems to indicate colorization.

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it on TypeChecker.fs. It jumps to any line instantly.

**Comment by vasily-kirichenko** [comment]
I reproduced it on tast.fs, it took about 2-3 seconds _each time_ I went to line #5000. dotTrace shows this:

![image](https://cloud.githubusercontent.com/assets/873919/25891720/c217818e-357a-11e7-9c9c-2031b740dc54.png)

After about a minute this stopped happening and it jumped instantly (no CPU load were for all that time).

**Comment by dsyme** [comment]
@vasily-kirichenko I can't see anything specific on the dotTrace info - can you?  Thanks

**Comment by vasily-kirichenko** [comment]
That's the problem :)

**Comment by cartermp** [comment]
cc @Pilchie

**Comment by dsyme** [comment]
I tried again and the pause seems much reduced now in large files.  This is an old issue so closing
