### ISSUE TITLE
Rename FSharp.Editor --> VisualFSharp.Editor etc.

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#3015]
I suggest that at some opportune moment we rename all the components of the Visual F# IDE Tools as follows:

    FSharp.Editor --> VisualFSharp.Editor
    FSharp.LanguageService --> VisualFSharp.LanguageService

and so on.  Perhaps adding the "Microsoft" prefix, I don't mind.

This will make it much clearer what is "core F#" and what is the Visual F# IDE tools.  (From a broad F# naming perspective  assemblies like FSHarp.Editor are clearly misnamed)

**Comment by vasily-kirichenko** [comment]
Roslyn IVT should be updated accordingly.

**Comment by dsyme** [comment]
@vasily-kirichenko  Good point :)

**Comment by KevinRansom** [comment]
@dsyme I would rather not have to coordinate a change in IVT with roslyn, as well as muck with deployment and whatever else is necessary, stuff always breaks and there is always a bug tail.  Can we just leave well enough alone ... please?

**Comment by smoothdeveloper** [comment]
@KevinRansom / @dsyme what is the problem for asking the Roslyn team to add the IVT with the new names without removing old ones?

This way we can wait for next round before renaming our projects / assemblies.

We shouldn't close issues which are geared toward making this repository more coherent, even if we can't act on those right now.

**Comment by KevinRansom** [comment]
So is this a high value change ?  does it change/add/remove any functionality? does it simplify deployment or tooling?  if the answer is no ... why risk the bugs?

Stuff breaks here all of the time because we rely on internals why would we do something that would for a while at least make things more likely to break?

**Comment by dsyme** [comment]
I think there is high value in this change, but there's absolutely no rush to do it.   Let's do this eventually, once the IVT disappears.

**Comment by KevinRansom** [comment]
Yes please ...

**Comment by cartermp** [comment]
@dsyme Should this be tracked in #2854 instead?

**Comment by cartermp** [comment]
Closing to track in #2854 instead
