### ISSUE TITLE
Missing intellisense in "ProjectSystem" in OSS VSIX release

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3019]
1. Build and install OSS VSIX from current master.
2. Open VFT solution.
3. No features work, except syntactic colorization:

![image](https://cloud.githubusercontent.com/assets/873919/25872998/66c5fdca-3515-11e7-9086-ae5b23a42ffd.png)

**Comment by majocha** [comment]
I just reinstalled from master and cannot reproduce this.
It's odd that colorization works but structure doesn't.

**Comment by dsyme** [comment]
Working for me in "Symbols.fs".  Semantic colors took about 20s appear because it's towards the end of the large compiler project

**Comment by vasily-kirichenko** [comment]
Hmm. I see no CPU load, so no chance anything will appear after some time. Did you guys run `git cleanup -dfx` before build?

**Comment by majocha** [comment]
Not long ago probably, but not this time. I wonder if it could be a problem with some components being wrong or stale (no idea if it's even possible, but colorization and structure and so on are separate exports) maybe, just maybe this could help:
[https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache)

**Comment by vasily-kirichenko** [comment]
Just rebuilt from fresh master, same thing:

![image](https://cloud.githubusercontent.com/assets/873919/25889561/ccdc0020-3572-11e7-9cc5-71b332eeb7c1.png)

**Comment by vasily-kirichenko** [comment]
@majocha that extension has not helped either.

**Comment by vasily-kirichenko** [comment]
Solved: it wants FSharp.Core.dll from the debug folder, so I had to build it first, then reopened VS. However, nothing still works on ProjectSystem project.

**Comment by dsyme** [comment]
@vasily-kirichenko I'll reopen until we iron out ProjectSystem.

**Comment by dsyme** [comment]
Covered by https://github.com/Microsoft/visualfsharp/issues/2970#issuecomment-300421077
