### ISSUE TITLE
Seal FSharpFunc / FSharpTypeFunc implementers to benefit from devirt 🎉

### ISSUE THREAD

**Issue by NinoFloris** [Microsoft/visualfsharp#3020]
As Andy Ayers has started the herculean task https://github.com/dotnet/coreclr/issues/9908 to get to full CLR devirt he has already merged the first pieces.

Specifically interesting is https://github.com/dotnet/coreclr/pull/9230 which is about devirtualizing calls when the runtimetype at the callsite can be determined exactly (newobj) or if the runtimetype is a sealed subtype / the called method is sealed. 

The compiler currently outputs FSharpFunc / FSharpTypeFunc (among others) classes without sealing them while I know of no reason it could not seal those.

This would bring F# function invocation performance up quite a notch (as a non virtual call they'll subsequently become inlining targets as well) and has widespread positive performance impact I presume.

**Comment by dsyme** [comment]
We should do this (and should always have done it)

See https://github.com/Microsoft/visualfsharp/compare/master...dsyme:clo?expand=1 for what I think is the implementation.  Can someone take this and update any necessary tests?

**Comment by vasily-kirichenko** [comment]
@dsyme https://github.com/Microsoft/visualfsharp/pull/3031

**Comment by vasily-kirichenko** [comment]
It's implemented in https://github.com/Microsoft/visualfsharp/pull/3031, @cartermp close this issue please.

**Comment by cartermp** [comment]
👍

**Comment by NinoFloris** [comment]
Thanks all

**Comment by dsyme** [comment]
> Did we actually test the performance impact of this?

No (on CLRs as available at the time we would have expected no change)
