### ISSUE TITLE
F# code specific markers (*F# ... F#*) are ignored in latest release of F# 4.1

### ISSUE THREAD

**Issue by blumu** [Microsoft/visualfsharp#3021]
The markers used to indicate F# specific code. This breaks compatibility scenario for FsLex and OcamlLex.

#### Repro steps
With F# 4.0
```
C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe

Microsoft (R) F# Interactive version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.
For help type #help;;

> (*F# printfn "hello" F#*);;
hello
val it : unit = ()
```

With latest version of F# 4.1 (VS 15.2 26430.4)
```
"C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\Fsi.exe"

Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> (*F# printfn "hello" F#*);;
>
```

#### Expected behavior

The code within the  `(*F#` and `F#*)` markers should be executed.

#### Actual behavior

The code within the  `(*F#` and `F#*)` is interpreted as a comment by the compiler.

#### Known workarounds

None

#### Related information 

Provide any related information 

* Operating system Windows 10
* Branch: official release (VS with 5/10/2017 update)
* VS 15.2 26430.4

**Comment by KevinRansom** [comment]
@WilliamBerryiii 
We removed those pre-processor pieces a while back.  We weren't aware of any dependence on them.  We dropped both (*F# and (*OCAML *).  

There is a proper pre-processor in F# now, and that's really how these should be done.

**Comment by blumu** [comment]
@KevinRansom Since `(*OCAML *)` was removed I am not sure how the F# pre-processor would help here. Is the F# preprocessor compatible with OCaml preprocessor? For instance could you tell me how I should rewrite the following lexer code (.mll) so that it can be compiled with _both_ OCaml and F# like it used to? 
```fsharp
(*IF-OCAML*)
let incr_linenum lexbuf =
  let pos = lexbuf.Lexing.lex_curr_p in
    lexbuf.Lexing.lex_curr_p <- {
      pos with
        Lexing.pos_lnum = pos.Lexing.pos_lnum + 1;
        Lexing.pos_bol = pos.Lexing.pos_cnum;
    }
;;
(*ENDIF-OCAML*)

(*F#
let incr_linenum (lexbuf : lexbuf) = lexbuf.EndPos <- lexbuf.EndPos.NextLine
F#*)
```

**Comment by KevinRansom** [comment]
@Don Syme<mailto:Don.Syme@microsoft.com>

No good deed goes unpunished … William Blum has been bitten by us removing the (*OCaml and (*F# removal … should we put it back or is there a work around?

Kevin

**Comment by dsyme** [comment]
@KevinRansom I suppose we can put it back.  We should have strongly deprecated for a version before removing it

> There is a proper pre-processor in F# now, and that's really how these should be done.

@blumu is correct that the feature is designed to allow a special kind of compat that can't be achieved with the F# ``#if``

**Comment by KevinRansom** [comment]
@dsyme I will put it back.

**Comment by blumu** [comment]
Thanks @KevinRansom @dsyme 
By the way, although this change was made a while back, it only made it in today's release of Visual Studio 15.2 Build 26430.4. The bug does not repro on Visual Studio 15.1 Build 26403.7.
