### ISSUE TITLE
Quick Info tooltips are too wide

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3028]
It's just not usable sometimes

![image](https://cloud.githubusercontent.com/assets/873919/25937635/239485f0-3635-11e7-983c-731028d0d0c3.png)

@majocha Do I understand right that we have to reimplement the tooltip control to be able to set it's width? What about splitting XML Doc into line of fixed length, like 1/2 of screen width?

**Comment by majocha** [comment]
@vasily-kirichenko yes, this looks horrible.
Reimplementing the tooltip is not much work. Docs can go into separate TextBlock; I think we can set a max width for it, so only the docs would wrap and reflow but not the rest of the text. I'll make a PR later today.

**Comment by vasily-kirichenko** [comment]
> so only the docs would wrap and reflow but not the rest of the text

Could you elaborate? Do I understand right that long function signatures will still make tooltips super wide? (I'm not saying it's bad, just asking)

**Comment by majocha** [comment]
@vasily-kirichenko I think formatting code-like stuff to sensible width should be done separately, like in Xamarin example that you posted.

As initial attempt we can just wrap the docs to make them more readable even if the whole tooltip is wide because of long signatures.

**Comment by cartermp** [comment]
Related: #1979

Finding a way to wrap these sensibly would be great.  Lots of good F# libraries have significant summary text which can get out of control with the current system.
