### ISSUE TITLE
Enter on completion after '.' doesn't commit; enters newline

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3032]
#### Repro steps

Provide the steps required to reproduce the problem

1. Enter the following code in VS.

```fsharp
module M =
    let f1 () = ()

[<EntryPoint>]
let main argv = 
    M.
    0
```

2. Invoke completion on module `M`, see `f1` in the completion list, and hit enter.

#### Expected behavior

Completion for `M.f1`.

#### Actual behavior

New line is committed instead.

#### Known workarounds

Use Tab for everything instead.

#### Related information 

VS 15.2.  Not fixed with nightlies.

**Comment by vasily-kirichenko** [comment]
Hmm. I'm 100% sure Enter always work in prior VS releases.

**Comment by cartermp** [comment]
Yeah, it also worked in 15.0 and 15.1 with latest nightlies.  So this is clearly a regression from 15.2 integration somehow.

Just for reference, we're currently also working on a regression in the 15.3 branch (due to a Roslyn internal API change).  I'll spend time next week to go through these regressions (I haven't found others yet) and see if they also exist in 15.3.  Haven't had the time due to //Build though.

**Comment by vasily-kirichenko** [comment]
You need to select an item to commit it by Enter, it's same as in C# editor:

![1](https://cloud.githubusercontent.com/assets/873919/26005029/6d53a0ac-3740-11e7-943c-7a3af667263e.gif)

**Comment by dsyme** [comment]
@vasily-kirichenko What if there is only one entry in the list? (just double checking)

**Comment by vasily-kirichenko** [comment]
@dsyme same

![1](https://cloud.githubusercontent.com/assets/873919/26013930/22bdd06c-3763-11e7-82b3-5fc53827722f.gif)

**Comment by dsyme** [comment]
@vasily-kirichenko OK, so sounds like this is reasonable expected behaviour (even if changed) and can be closed?

**Comment by cartermp** [comment]
Hmmmm.  I'm not so sure.  I need to test this on 15.1 again.  I don't ever recall this behavior, and was immediately bit by it because my muscle memory was to use enter.

**Comment by cartermp** [comment]
Thought about it; I'll close for now since C# exhibits this behavior.  If people complain, I'll certainly open this back up.
