### ISSUE TITLE
[From VSTS] IVSLanguageDebugInfo::ValidateBreakpointLocation returns incorrect span, breakpoint is set in wrong place

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3035]
1. clone https://github.com/cartermp/15.2-E2E
2. Open in visual studio and F5
3. Type 'banana' in the textbox and click 'Generate!' button
4. Open PigLatin.fs in Visual Studio
5. Set a breakpoint on line 16 by clicking the gutter

**Expected:** Breakpoint is set on Line 16.

**Actual:** Breakpoint is set on line 13.

**Additional Info:** 
The breakpoint can successfully be set on line 16 if the cursor is placed after column 13 and the shortcut key 'f9' is used to set the breakpoint.
The root cause of this issue is that `IVSLanguageDebugInfo::ValidateBreakpointLocation` is returning the wrong span when given line 16, column 0. It returns the span from lines 13 to 16 rather than the span on line 16.

**Comment by dsyme** [comment]
I checked this and it is working OK in master.  After clicking in the gutter:

![image](https://user-images.githubusercontent.com/7204669/27674570-37f2b3e8-5c9e-11e7-95fa-2df4fa2eaba1.png)
