### ISSUE TITLE
Update System.ValueTuple NuGet package reference to version 4.3.1 in templates

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3037]
1. Create a new Console / Library project
2. Open package manager
3. It suggest to pdate System.ValueTuple package to version 4.3.1

![image](https://cloud.githubusercontent.com/assets/873919/25986267/c7dfe100-36f7-11e7-970d-e7b07bdd762c.png)

**Comment by cartermp** [comment]
@KevinRansom What was your plan around System.ValueTuple for Update 3 in VS setup?  Just update here, or would we change our approach based on #2983?

**Comment by KevinRansom** [comment]
I just proposed and then closed a PR to update it to 4.3.1.  It appears that there is an issue with ValueTuple on mono and so I will in fact need to update to 4.4-preview.

**Comment by dsyme** [comment]
@KevinRansom In that case we probably shouldn't update at all until everything is ready. I don't think we should be using a preview package in default templates etc.

**Comment by KevinRansom** [comment]
@dsyme 
Well ... let me grok the real issue, it seems as if the preview may be our only valid choice ... and it is up on nuget already, so referencing it from templates is probably okay.  Frankly I'm miffed that they keep messing the type.  IMO they should leave have left it alone at the first released version, and they are probably getting tired of me keep repeating it.

**Comment by dsyme** [comment]
What's invalid about the current version? thx

**Comment by KevinRansom** [comment]
@dsyme 
Trying to get to the bottom of it.

**Comment by KevinRansom** [comment]
Well, it seems as if mono treats the svt dll a bit wierdly.  It's banned, the mono devs are doing some fixes.  However, apparently the mono build of fsc.exe has svt disabled in some way.

**Comment by dsyme** [comment]
This has been done
