### ISSUE TITLE
Visual Studio question

### ISSUE THREAD

**Issue by nojaf** [Microsoft/visualfsharp#3039]
Does the new Visual Studio 15.3 preview support F# project generated from the dotnet cli?

#### Repro steps

Provide the steps required to reproduce the problem

1. dotnet new console -l F#

2. Open fsproj in VS 2017

#### Expected behavior

I can build and run the project.

#### Actual behavior

![Crash](https://i.imgur.com/nk2BTzp.png)

#### Related information 

Provide any related information 

* Operating system: Windows 7, Windows 10 Creators
* .NET Runtime, CoreCLR or Mono Version: 
```
PS C:\temp\vs17test> dotnet --info                
.NET Command Line Tools (1.0.4)                   
                                                  
Product Information:                              
 Version:            1.0.4                        
 Commit SHA-1 hash:  af1e6684fd                   
                                                  
Runtime Environment:                              
 OS Name:     Windows                             
 OS Version:  6.1.7601                            
 OS Platform: Windows                             
 RID:         win7-x64                            
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4   
```
* Editing Tools (e.g. Visual Studio Version): Visual Studio Comunnity 207 (15.2 Release)

**Comment by vasily-kirichenko** [comment]
It does not. What's more, nobody is working / is going to work on it.

**Comment by forki** [comment]
@vasily-kirichenko and the only community guy that was working on dotnet cli for F# was let's say "disappointed" by MS...

**Comment by vasily-kirichenko** [comment]
This task has had "super high" priority for several months, btw.

**Comment by nojaf** [comment]
Ouch, this is sad news.

**Comment by dsyme** [comment]
@nojaf The work is in progress, though like most things it is taking longer than we would hope/

@vasily-kirichenko @forki Your comments on this thread were not accurate - please repost them if you wish. I just found it unfair to say "no one is going to work on it" when people are actually working on it.

Specifically, [there](https://github.com/Microsoft/visualfsharp/pull/3029) [have](https://github.com/Microsoft/visualfsharp/pull/3027) [been](https://github.com/Microsoft/visualfsharp/pull/3023) [several](https://github.com/Microsoft/visualfsharp/pull/3018) [PRs](https://github.com/Microsoft/visualfsharp/pull/2993) to this repo recently to help add F# support to the .NET SDK, a pre-requisite for this work.  The [RFC](https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1032-fsharp-in-dotnet-sdk.md) explains why this is being done the way it is.  I understand that this takes a different technical direction, but the RFCs discuss the pros and cons. Personally I'm excited to see F# in the Microsoft.NET.Sdk directly and although this is taking time to come through the pipe, it is the right way to do things long term.

The work to update the project system is being done largely in [the Roslyn Project SYstem repo](https://github.com/dotnet/project-system). That repo is now even named "C#, F# and Visual Basic project system".  Again, the work is taking its time to come through the pipe.  But personally I will be thrilled to pieces to get the VS Project System implementation out of this repo and into a place where deep experts in that area conregate, and where the work is aligned with C# project system work.  

Either way, again I think its unfair to say "no one is working on it" - people are working on it, and if we want to help, we can go to those repos and help.  Here are some specific issue to help on:

* https://github.com/dotnet/project-system/issues/1854
* https://github.com/dotnet/project-system/issues/1853
* https://github.com/dotnet/project-system/issues/219
* https://github.com/dotnet/project-system/issues/1855
* https://github.com/dotnet/project-system/issues/1875

**Comment by cartermp** [comment]
Thanks, @dsyme.  Was going to say roughly the same thing, but you got to it first (I just woke up 😄 ).  To add, the work in the .NET Core SDK to support F# has been approved for Update 3 Preview 2.  So you can expect it to "light up" at that time, @nojaf.  Quite a few other features and improvements are going to show up at Preview 2 as well, so this isn't a super last-minute push where everything else is awaiting F#.  We're still targeting the full release of VS 2017 Update 3.

**Comment by nojaf** [comment]
Thanks @dsyme and @cartermp for the clarification. Perhaps the [blogpost](https://blogs.msdn.microsoft.com/visualstudio/2017/05/10/update-to-visual-studio-2017-and-next-preview/) on the new preview could have mentioned this.

**Comment by cartermp** [comment]
@nojaf The approval came after the final draft of the blog post was written.  I can have it updated, but that may not be until later today or this weekend.  We're all still 100% booked up with the //Build conference this week, myself included.

**Comment by nojaf** [comment]
@cartermp that explains. I totally understand that things must be quite hectic with //build going on. 
The utmost respect for everything you folks do. I'll patiently wait for Update 3.

**Comment by cartermp** [comment]
Tracked!  Thanks, @nojaf.

<img width="469" alt="screen shot 2017-05-12 at 6 42 05 am" src="https://cloud.githubusercontent.com/assets/6309070/26000526/2860bcc6-36de-11e7-9c99-83495c9d095a.png">
