### ISSUE TITLE
Line numbers are not enabled as default

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#304]
Please enable line numbers as a default for the F# editor.

I know someone will tell me this is a feature request and don't belong here, but then CodeLens (for me one of the most annoying features ever) is also enabled in VS as a default.

**Comment by latkin** [comment]
Are they enabled by default for C#, C++, etc?

**Comment by forki** [comment]
Same bug.

**Comment by forki** [comment]
Let's change this default for whole VS. It's just wrong. (regardless of CodeLens)

**Comment by forki** [comment]
The first thing I do (and probably everyone who is doing pair programming or reading compil

**Comment by enricosada** [comment]
:+1 for line numbers active, is a sane default

**Comment by dnauck** [comment]
+1

**Comment by veikkoeeva** [comment]
+1

**Comment by latkin** [comment]
Also +1 from me

**Comment by latkin** [comment]
Config that controls this is not part of our repo, it's part of internal general VS settings controlling the various "profiles."  We certainly can't change the VS default for all file types unilaterally, but we could change it for F# and encourage Roslyn, Typescript, etc to do the same.

**Comment by bentayloruk** [comment]
+1

**Comment by latkin** [comment]
Found an old UserVoice here http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/3273933-enable-line-numbers-by-default. Votes there would be useful.
