### ISSUE TITLE
Build failure on clean machine

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#3041]
I'm not sure why but I'm getting a build failure on a clean machine:

    build vs

gives

![image](https://cloud.githubusercontent.com/assets/7204669/26000919/8c43901c-3722-11e7-9c9e-27047823cdef.png)

**Comment by majocha** [comment]
#2556 had the same error

**Comment by vasily-kirichenko** [comment]
I saw it 5 months ago https://github.com/Microsoft/visualfsharp/issues/1916, nobody even took a look.

**Comment by dsyme** [comment]
Yes, I installed prerequisites properly and this solved the problem.  Would be simpler to get ``rc.exe`` from a nuget package though

**Comment by dsyme** [comment]
Here's the relevant re-requisite: https://github.com/Microsoft/visualfsharp/blob/master/DEVGUIDE.md#developing-the-visual-f-ide-tools-windows-only

**Comment by KevinRansom** [comment]
That rc requirement is silly, I keep trying to get the c++ team to give us a simple nuget package for link, rc and those kind of tools, but that seems to be to radical.

**Comment by dsyme** [comment]
Yes - was tempted to just check in the tool.  I had to download 3GB of C++ tools at home just to get it :/
