### ISSUE TITLE
We use outdated Roslyn packages

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3042]
VS 15.2 uses 2.2.0-beta1, we use 2.0.0-rc5

![image](https://cloud.githubusercontent.com/assets/873919/26004546/df5ad492-373e-11e7-8908-c0d51f3618cc.png)

![image](https://cloud.githubusercontent.com/assets/873919/26004622/1b2f0060-373f-11e7-8c70-05edf7b95a37.png)

@brettfo to what NuGet packages version we should update?

**Comment by vasily-kirichenko** [comment]
Maybe someone should keep an eye on it, always? Is it possible to get to know what Roslyn binaries are gonna be shipped with next VS update?

**Comment by dsyme** [comment]
Yes, second time this has happened.

**Comment by Pilchie** [comment]
@brettfo and @KevinRansom were talking about writing a bot that tries updating to the latest nightly builds on Roslyn's myget every day, and updating if CI passes.

**Comment by brettfo** [comment]
What @Pilchie said.

In the short term, though, there is a Roslyn change coming soon that will require us to update to 2.3.0-beta bits and I'll be doing that work likely next week.

**Comment by dsyme** [comment]
I'll close this as a duplicate of https://github.com/Microsoft/visualfsharp/issues/3067 since it is the same underlying issue
