### ISSUE TITLE
.NET portability analyzer is not aware of FSharp.Core

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3046]
.NET portability analyzer http://vsixgallery.com/extension/55d15546-28ca-40dc-af23-dfa503e9c5fe/ is not aware of FSharp.Core:

![image](https://cloud.githubusercontent.com/assets/873919/26023876/dcb3689a-37ce-11e7-8590-ff75bcfd6a4b.png)

[ApiPortAnalysis.xlsx](https://github.com/Microsoft/visualfsharp/files/998443/ApiPortAnalysis.xlsx)

I think we should fix it since there are people that do need it:

![image](https://cloud.githubusercontent.com/assets/873919/26023891/0f6ba3b0-37cf-11e7-919b-3ae77e4d12b9.png)

**Comment by dsyme** [comment]
Is this an open source tool?

**Comment by vasily-kirichenko** [comment]
@dsyme yes https://github.com/microsoft/dotnet-apiport/

**Comment by dsyme** [comment]
So do we know if  this is a bug for that repo?  Or is it some fault in the attributes we generate for FSharp.Core?  Thanks!

**Comment by 0x53A** [comment]
I think it is a current limitation of the tool - it seems to only compare the assembly against what's in-box, which FSharp.Core is not. See https://github.com/Microsoft/dotnet-apiport/issues/400

**Comment by cartermp** [comment]
@0x53A Good find.  I replied to that thread.  If this is true, it seems like ApiPort is misleading for F# developers.

**Comment by enricosada** [comment]
See https://github.com/Microsoft/dotnet-apiport/issues/304

**Comment by conniey** [comment]
This should be fixed now, we updated the catalog to include most of the MSFT packages on NuGet.  Can you try rerunning your analysis against `.NET Standard` and/or `.NET Standard + Platform Extensions`?

![image](https://cloud.githubusercontent.com/assets/10136526/26808830/8de829d2-4a14-11e7-8cf5-1babe7fdeca9.png)

**Comment by xkrt** [comment]
@conniey for .NET Standard [+ Platform Extensions] report was improved, but what about .NET FW 4.6.2 for example? This is expected?

![screenshot-1](https://cloud.githubusercontent.com/assets/428187/26814879/60cdc68c-4a91-11e7-816d-225ec1bfb99d.png)

**Comment by chlowell** [comment]
Yes, the Framework targets still represent only what's in-box.

**Comment by dsyme** [comment]
The external issue has now been resolved
