### ISSUE TITLE
Tooltips don't show field types

### ISSUE THREAD

**Issue by asik** [Microsoft/visualfsharp#3058]
If one hovers over a field, only the name is displayed in the tooltip:

![image](https://cloud.githubusercontent.com/assets/1631157/26083032/463d1814-39a1-11e7-9101-dd4c69f54da1.png)

For properties this works correctly:

![image](https://cloud.githubusercontent.com/assets/1631157/26083053/62aa75a0-39a1-11e7-9265-c24adb5bde0d.png)

**Comment by vasily-kirichenko** [comment]
Year, it's always been this way. Super annoying.

**Comment by dsyme** [comment]
I'll label it as a bug since it's easy to fix.  The fix would go here: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/symbols/SymbolHelpers.fs#L1065
