### ISSUE TITLE
Go to Definition sometimes opens a temporary window for the same file

### ISSUE THREAD

**Issue by Tarmil** [Microsoft/visualfsharp#3059]
Here's a screen grab:

![754658ef-8ccc-4c6e-9a93-5868e8c2b5a5](https://cloud.githubusercontent.com/assets/921395/26096324/165c7240-3a21-11e7-889a-3bdfd6e06d0d.gif)

The definition is in the same file, but F12 still opens a new window to show it instead of just moving the cursor.

#### Repro steps

1. Put the cursor on a call to a function defined in the same file

2. Press F12

#### Expected behavior

The cursor moves within the window to the definition.

#### Actual behavior

A temporary window is opened with the same file contents and the cursor at the definition.

#### Known workarounds

None, but I've seen the correct behavior happen. Right now I have 2 solutions open, one with the correct behavior one with the wrong behavior; I haven't been able to figure out in what conditions either case happens.

#### Related information 

VS 2017, VFT Nightly 15.4.1.17051601 (but also happens with the pre-installed VFT)

**Comment by dsyme** [comment]
@Tarmil We will need a reliable step-by-step repro for this, I haven't been able to repro it

Please reopen if you get an exact repro
