### ISSUE TITLE
XML Doc it not shown on Quick Info tooltip for symbols defined in mscorlib.dll

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3072]
![1](https://cloud.githubusercontent.com/assets/873919/26168991/d3179ec2-3b44-11e7-9cdd-01a173be23bb.gif)

**Comment by dsyme** [comment]
Odd - what's your project file reference to mscorlib?  I'm seeing the docs in VisualFSharp.sln

**Comment by dsyme** [comment]
I'm seeing xmldocs on a new library proejct

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it on current master. Closing.
