### ISSUE TITLE
Create command line parser for new project system work.

### ISSUE THREAD

**Issue by brettfo** [Microsoft/visualfsharp#3074]
Implement a command line parser that can be used by [`FSharpParseBuildOptions.cs`](https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.FSharp/ProjectSystem/LanguageServices/FSharpParseBuildOptions.cs) in the project system repo.

**Comment by dsyme** [comment]
@brettfo We should add an FSharpCHecker entry point for this.  See https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/service.fs#L2561 for what the implementing code would feel like. Once you've populated the tcConfigB with information you can read off what you need

Can FSHarpParseBuildOptions.cs call into FSharp.LanguageService.Compiler?

**Comment by dsyme** [comment]
@brettfo It would be really good to reuse the existing compiler command line parser for this

**Comment by dsyme** [comment]
This has already been completed in the project system code
