### ISSUE TITLE
Duplicate entries for values / function names in IntelliSense auto-complete

### ISSUE THREAD

**Issue by xdaDaveShaw** [Microsoft/visualfsharp#3076]
#### Repro steps
Using this code:
```F#
let foo = 1
let fool = 2
let foob = 3

[<EntryPoint>]
let main argv = 
    printfn "%A" foo
    0 // return an integer exit code
```
1. Place you cursor at the end of `printfn "%A" foo` 
2. Press Ctrl+Space (or just delete `foo` and retype it).

#### Expected behavior

Only see the following (+ anything else usually shown)
- `foo`
- `foob`
- `fool`

#### Actual behavior

![image](https://cloud.githubusercontent.com/assets/2511715/26178142/9dbca73a-3b54-11e7-86dc-6efc05041711.png)

See 
- `foo`
- `foob`
- `fool`
- `foo`
- `foob`
- `fool`

#### Known workarounds

Ignore the duplicates, could be hard depending on how things are named.

#### Related information 

* Windows 10 x64 1607
* VS2017 (15.2) + 17051701 nightly

Does not happen in VS2015:
![image](https://cloud.githubusercontent.com/assets/2511715/26178100/7c276466-3b54-11e7-921c-8867a8a5d267.png)

Or Ionide:
![image](https://cloud.githubusercontent.com/assets/2511715/26178162/b275d868-3b54-11e7-972e-a972ca16435c.png)

**Comment by dsyme** [comment]
@vasily-kirichenko Any ideas on this? Just wondering if you had a hunch

**Comment by vasily-kirichenko** [comment]
@dsyme yes, the duplicates are from "all entities" https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Completion/CompletionProvider.fs#L105, it calls https://github.com/Microsoft/visualfsharp/blob/de67934a8c64f57ee18356f4d94a1edc2df7fdca/src/fsharp/symbols/Symbols.fs#L2127 for current project and all referenced projects / assemblies.

Duplicates are filtered here https://github.com/Microsoft/visualfsharp/blob/de67934a8c64f57ee18356f4d94a1edc2df7fdca/src/fsharp/symbols/SymbolHelpers.fs#L818 with `ItemDisplayPartialEquality`. For all "external" (gotten by `signature.Entities`) entities item = `Item.UnqualifiedType` (no idea why), so I added these bits https://github.com/Microsoft/visualfsharp/blob/de67934a8c64f57ee18356f4d94a1edc2df7fdca/src/fsharp/symbols/SymbolHelpers.fs#L755-L759 to make it work. Must be it fails on the sample in this issue.

**Comment by dsyme** [comment]
Ah I see, Yes, we need to improve the duplicate filtering there
