### ISSUE TITLE
Cannot navigate to a symbol defined in FCS from FSharp.Editor

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3083]
![image](https://cloud.githubusercontent.com/assets/873919/26216636/789cb97c-3c0d-11e7-80a0-d023fee8f61a.png)

**Comment by majocha** [comment]
Seems to be broken for quite some time now #2904 on master.

I just checked that it works fine on current released version.

**Comment by realvictorprm** [comment]
@cartermp I think this is solved too.

**Comment by cartermp** [comment]
Yep, can confirm that this works on today's nightly.
