### ISSUE TITLE
An implementation of the file or module 'ServiceDeclarationLists' has already been given

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3084]
![image](https://cloud.githubusercontent.com/assets/873919/26216834/2fed1220-3c0e-11e7-96a6-cba80d4733aa.png)

**Comment by majocha** [comment]
I can reproduce on current nightly. It takes some for this error to show.

**Comment by dsyme** [comment]
There are duplicate entries for this file in the .fsproj file.  I'm not sure why it only affects the IDE and not the build though

**Comment by dsyme** [comment]
Fixed in recent commits for FSHarp.Compiler.Private
