### ISSUE TITLE
Cannot debug VFT

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3085]
![image](https://cloud.githubusercontent.com/assets/873919/26216909/6cbab068-3c0e-11e7-964f-f960e19f10fe.png)

**Comment by KevinRansom** [comment]
@vasily-kirichenko portable library symbols or full desktop PDB's?

**Comment by majocha** [comment]
I quickly tested on current nightly. Debug configutration. It works, at least when placing the breakpoint in service.fs after starting debugging. Breakpoint gets hit ok.

**Comment by dsyme** [comment]
@vasily-kirichenko Still a problem?

**Comment by vasily-kirichenko** [comment]
no
