### ISSUE TITLE
IntelliSense suggesting when completing a range

### ISSUE THREAD

**Issue by xdaDaveShaw** [Microsoft/visualfsharp#3086]
When typing an range IntelliSense is kicking in after `..` and suggesting functions that match the end number.

#### Repro steps

Provide the steps required to reproduce the problem

1. Paste the following `let a = ResizeArray<_>([1`
2. Type `..10])` to complete the range `1..10`

#### Expected behavior

- No IntelliSense suggestions.
- Text appears as `let a = ResizeArray<_>([1..10])`

#### Actual behavior

- IntelliSense appears as you type in `10` and suggests `log10` function which is accepted when you press `]`
- Text appears as `let a = ResizeArray<_>([1..log10])` and requires you to go back and remove `log`.

![image](https://cloud.githubusercontent.com/assets/2511715/26223139/bc9115a4-3c14-11e7-9f6d-6c078829c307.png)

#### Known workarounds

Edit the incorrect auto-completion.

#### Related information 

Provide any related information 

* Windows 10 x64 1607
* VS2017 (15.2) + 17051701 nightly

Probably quite low severity, if you enter the range with spaces around `..` (`1 .. 10`) it doesn't happen.

**Comment by vasily-kirichenko** [comment]
It cannot be fixed because we don't have ast for such code. Add ]) end the bed and it should work as expected.

**Comment by xdaDaveShaw** [comment]
Would it be possible to not have any auto-complete suggestions appear after `..`? This is how Ionide works.

**Comment by vasily-kirichenko** [comment]
@xdaDaveShaw why? The user could like to write `for i in 1..aLongNamedVariable.fromAnother.Namespace - 1` and completion after `..` is totally OK.

**Comment by saul** [comment]
@vasily-kirichenko I think the fix here is to not commit autocomplete on `]`

**Comment by dsyme** [comment]
@saul That sounds good

**Comment by vasily-kirichenko** [comment]
I think we should not commit on any character but Enter and Tab.

**Comment by Pilchie** [comment]
@vasily-kirichenko VS supports "Suggestion mode" completion, where there is an extra field at the top, and commit of the "soft selected" item only happens with tab, or after an explicit selection in the window.

In C# you can toggle into that mode with this toolbar button:

![image](https://user-images.githubusercontent.com/312835/27452570-e0991674-5747-11e7-91ca-ca5eba6e3db4.png)

Not sure if F# got that for free from Roslyn or not, but that's an option.  (Unfortunately the setting isn't sticky across VS restarts).

**Comment by cartermp** [comment]
This is fixed.

Typing:

```fsharp
let a = [1..10
```

Shows no completion, as expected.
