### ISSUE TITLE
Wrong enum field colorization if it contains dots

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3087]
![image](https://cloud.githubusercontent.com/assets/873919/26238826/6753a0f6-3c83-11e7-9443-9f41d0e47aea.png)

**Comment by dsyme** [comment]
:) Nice find

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/3102

**Comment by vasily-kirichenko** [comment]
Thanks for closing it after #3102 was merged.

**Comment by dsyme** [comment]
@vasily-kirichenko Thanks for closing
