### ISSUE TITLE
nullref when StructuredFormatDisplay has bogus property name on portable profile

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#309]
As mentioned at https://github.com/Microsoft/visualfsharp/pull/251#issuecomment-81905576

If one provides a bogus property name to `StructuredFormatDisplay`, a reasonable error is expected.  On portable profiles we instead get a nullref error message.

```
test cenwoiwe12: expected 
    '<StructuredFormatDisplay exception: Method 'Test+CheckDisplayAttributes12+Foo.Val{Hello' not found.>' but produced 
    '<StructuredFormatDisplay exception: Object reference not set to an instance of an object.>'
```

Culprit is [these lines](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/utils/sformat.fs#L756-L757) I believe. If first reflection call returns null, second line will nullref.  We should be checking for that and throwing a better error.

**Comment by latkin** [comment]
Marking up for grabs as the fix is very small.

Testing is a bit tricky due to need for portable -- suggestion when doing private validation is to strip down the core\portable test code to include only the `printf` tests, then run from there.  I can provide more details as needed.

**Comment by latkin** [comment]
ping on up-for-grabs

**Comment by dsyme** [comment]
Because this involves a corner case in portable profiles only, and .NET Standard is the new new, I think we can close this.
