### ISSUE TITLE
Exceptions declared using "exception" have no coloring

### ISSUE THREAD

**Issue by asik** [Microsoft/visualfsharp#3093]
Exceptions declared using the "exception" keyword have no syntax coloring in the text editor. They do in tooltips though.
Exceptions declared using "type" are fine.

![image](https://cloud.githubusercontent.com/assets/1631157/26272179/677e5262-3ce0-11e7-8f4c-21dc5982419d.png)

Visual FSharp Tools 15.4.1.17051001.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/3102

**Comment by realvictorprm** [comment]
@cartermp can we close this?
