### ISSUE TITLE
"Microsoft.FSharp" namespace considered unused if "Microsoft" is removed

### ISSUE THREAD

**Issue by asik** [Microsoft/visualfsharp#3095]
Writing "Microsoft" is optional in namespaces beginning with "Microsoft.FSharp". However, this seems to confuse the unused namespace finder:

![image](https://cloud.githubusercontent.com/assets/1631157/26272516/7f968e84-3ce8-11e7-8e36-af47cf6441e7.png)

In this case, the namespace should not be flagged as unused, as removing it will cause the code not to compile.

Visual FSharp Tools 15.4.1.17051001.

**Comment by vasily-kirichenko** [comment]
I believe I fixed this already :(

**Comment by BentTranberg** [comment]
Is this an effect of bug #3347 / #3306 ?

**Comment by cartermp** [comment]
I believe this has been fixed - I cannot reproduce it anymore in 15.6 Preview 5:

![works](https://user-images.githubusercontent.com/6309070/36354532-cfce895e-148a-11e8-8da6-7dc235fd94a4.gif)
