### ISSUE TITLE
Add this repository to https://github.com/showcases/programming-languages

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3096]
There is fsharp/fsharp repo there, but it's almost dead (however, it has more stars then this repo, so...)

**Comment by cartermp** [comment]
Good call.  I'll see who I can contact to make it happen.

**Comment by cartermp** [comment]
I contacted GitHub.  Will close this when it's updated.

**Comment by cartermp** [comment]
Completed!  https://github.com/showcases/programming-languages
