### ISSUE TITLE
Allow ParseFileInProject be called from outside Reactor

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3107]
Currently (very fast) parsing jobs have to wait in Reactor queue for (slow) type check jobs. This results with a situation when you open a file in project and it's started to check (and all files above it, if it's the first time a file in the project is touched), blocking any `ParseFileInProject` until it's finished. It means no structure guidelines, no nav bar for long time (I know Rider guys are also struggling with it). As I understand, parsing is performed under reactor because it gets `IncrementalBulider` for project to get `TcConfig`, project source file list and dependency list from it, see https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/vs/service.fs#L2278-L2285 

Is it possible allow parsing outside Reactor?

**Comment by dsyme** [comment]
@vasily-kirichenko Yes and no.

For ``ParseOneFile`` it should be possible to remove the CompilationThread requirement, see this comment:
```
          // This function requires the compilation thread because we install error handlers, whose callbacks must
          // be invoked on the compilation thread, no other reason known to date.
          // We should check whether those are "real" reasons - we could for example make collecting errors thread safe.
          RequireCompilationThread ctok 
```

The error loggers can actually be installed on any thread and contrary to what the comment says . AFAIK the same logger is not being used in multiple parsing calls, so it should be safe.

However prior to calling ``ParseOneFile`` we need to do this:
```
            let! builderOpt,creationErrors,decrement = getOrCreateBuilderAndKeepAlive (ctok, options, userOpName)
```
which does require the compilation thread.  This is basically creating a project builder just to get the TcConfig configuration (conditional defines and any other settings relevant to parsing).  Roslyn separates out compilation options relevant to parsing - the F# compiler implementation currently does not.

**Comment by dsyme** [comment]
Note that I believe #3063 would address many of these "long wait for language service features to become active on startup" problems.  Perhaps you can try it out.
