### ISSUE TITLE
FSC and FSI usage text and code comments inaccurate regarding debug defaults

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#311]
Both FSI and FSC print the following usage info for the `--debug` flag:

```
                - CODE GENERATION -
--debug[+|-]                   Emit debug information (Short form: -g)
--debug:{full|pdbonly}         Specify debugging type: full, pdbonly. ('full' is the default and enables attaching a
                               debugger to a running program).
```
It says `full` is the default debug setting.  However this is not true, either in FSC or in FSI.

(note that `-g` ==  `--debug+` == `--debug:full`)

-----

In FSC the [relevant code](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/fsc.fs#L322-L325) reads:

```fsharp
    // Preset: --optimize+ -g --tailcalls+ (see 4505)
    SetOptimizeSwitch tcConfigB On
    SetDebugSwitch    tcConfigB None Off
    SetTailcallSwitch tcConfigB On 
```
The call to `SetDebugSwitch` is actually equivalent to `--debug-`, so both the usage text and the comment are incorrect.

-----
In FSI the [relevant code](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/fsi/fsi.fs#L2147-L2150) reads:

```fsharp
    // Preset: --optimize+ -g --tailcalls+ (see 4505)
    do SetOptimizeSwitch tcConfigB On
    do SetDebugSwitch    tcConfigB (Some "pdbonly") On
    do SetTailcallSwitch tcConfigB On  
```
The call to `SetDebugSwitch` is actually equivalent to `--debug:pdbonly`, so both the usage text and the comment are incorrect

-----

We should either
- Modify the true defaults so they match the documentation/comments
- Modify the documentation/comments so they match the true defaults

**Comment by KevinRansom** [comment]
I believe we need to modify the documentation/comments to match the behavior.

**Comment by jwood803** [comment]
I *think* I have this updated. Is it ok to have the PR created to double check the changes while the CLA is in process?

**Comment by latkin** [comment]
@jwood803 sure, that's fine to get it started before the CLA is done

**Comment by jwood803** [comment]
Awesome! I'll submit it later tonight.

-----Original Message-----

**Comment by latkin** [comment]
To be clear, here's what I'd prefer to see.

**Old usage:**
```
--debug[+|-]                   Emit debug information (Short form: -g)
--debug:{full|pdbonly}         Specify debugging type: full, pdbonly. ('full' is the default and enables attaching a
                               debugger to a running program).
```

**Proposed usage:**
```
--debug[+|-|:full|:pdbonly]    Emit debug information (Short form: -g)
                               -g, --debug, --debug+, --debug:full : full debug information
                               --debug:pdbonly                     : limited debug information
                               --debug-                            : no debug information (default)
```

I'd certainly be open to suggestions on how else to make this more clear.

**Comment by matthid** [comment]
The [msdn](https://msdn.microsoft.com/en-us/library/dd233172.aspx) suggests that `-g[+|-|:full|:pdbonly]` should work as well. This just hit me [here](https://github.com/fsharp/FAKE/pull/1080#issuecomment-172480111)

**Comment by dsyme** [comment]
Fixed by above PR
