### ISSUE TITLE
Value types colored as reference types

### ISSUE THREAD

**Issue by asik** [Microsoft/visualfsharp#3110]
Value types have their own color setting in the IDE (User Types - Structures). Let's make them Fuschia just to make it super obvious. There are a few cases where they are colored as reference types:

1) When they have a unit of measure, they are colored as reference types both in the text editor and tooltips:
![image](https://cloud.githubusercontent.com/assets/1631157/26416651/adf7b006-4084-11e7-9a83-79c8c6c9c2ad.png)

2) FSharp aliases of value types appear correctly in the editor, but it's all mixed up in tooltips:
![image](https://cloud.githubusercontent.com/assets/1631157/26416713/d4dc2e04-4084-11e7-9cf4-d289dfe9645b.png)

**Comment by dsyme** [comment]
We've discussed this sort of thing before - the general principle is that F# tries to de-emphasize difference between things, and emphasizing difference via the color scheme needs to be done very cautiously

F# programmers will very often want to focus on domain semantics not incidental representational details.  Consider for example the common trick of wrapping a reference type in a single-field value type to give it a different name and semantics. OK, it's a struct type, but that is not what the F# programmer needs to be constantly reminded of, nor is it even operationally relevant

**Comment by asik** [comment]
Well, the option is there in Visual Studio, and right now it's sometimes honored and sometimes not honored by F#. So at least it should be made consistent, either by always honoring it or never honoring it.

Personally I'd vote to support it. It's basically off by default since by default value types have the same color; those who want to be reminded of that difference can, by changing the font color. It's a nice option for someone doing anything very GC-sensitive like systems programming, game development, etc. With a bit more love for value types, F# can be a great language for that as well. Also there's traction in .NET to make working explicitely with memory easier (Span<T>/Memory<T>, C# has added ref returns, ref readonly is next), so generally speaking it would be great if F# supported that well. I don't think it takes away anything from the language for anyone else.
