### ISSUE TITLE
Getting entities by compiled paths

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#3114]
I'm trying to add a member to `FSharpAssemblySignature` to get an `FSharpEntity` by its compiled path like ``["MyNamespace"; "MyModule"; "MyCompiledName`2"]``.

I'm using [`mtyp.AllEntitiesByCompiledAndLogicalMangledNames`](https://github.com/fsharp/FSharp.Compiler.Service/blob/master/src/fsharp/tast.fs#L1651-L1660) in ModuleOrNamespaceType to get it recursively. However, using this approach I found that this cache doesn't contain entities that are hidden by a signature file.

Is there a more efficient way to get an entity or this approach is OK? If there's a way to get it fast using a string like ``"MyNamespace.MyModule+MyCompiledName`2"`` it would be helpful.
Could someone assist me in getting hidden entities, please?

I'd like to open PRs adding few APIs in FCS, but found this repo to be more active lately so opened an issue here first.

**Comment by auduchinok** [comment]
Sure, I'll move it to FCS.
But due to the repos merging I'm not sure when FCS packages are going to start being published from this repo. Do I get it right that I should I submit a PR here while opening an issue in FCS?

**Comment by dsyme** [comment]
> But due to the repos merging I'm not sure when FCS packages are going to start being published from this repo. 

Yeah I know.  The merge is kind of half-complete - and we may still continue to build packages from fsharp/FSharp.Compiler.Service for a fair while 

> Do I get it right that I should submit a PR here while opening an issue in FCS?

Yes, thanks.
