### ISSUE TITLE
Internal error involving quotation of struct tuple

### ISSUE THREAD

**Issue by stephen-swensen** [Microsoft/visualfsharp#3118]
The following quotation (involving struct tuple)

```
let actual = struct (0,0)
let code = 
    <@ match actual with
       | struct (0,0) -> true
       | _ -> false @>
```
Produces the following error

> Error FS0073 internal error: Unexpected expression shape

Meanwhile, the following quotation (involving struct DU)

```
let actual: Result<string, string> = Ok "foo"
printfn "%A" 
    <@ match actual with
       | Ok _ -> true
       | Error _ -> false @>
```
Produces the following output

> IfThenElse (UnionCaseTest (AddressOf (ValueWithName (Ok "foo", actual)), Error),
>         Value (false), Value (true))

So it compiles without error, but I am unsure if `AddressOf` makes sense here.

Visual F# 4.1

**Comment by forki** [comment]
WIP see https://github.com/Microsoft/visualfsharp/pull/3125
