### ISSUE TITLE
Make FSharp.Core.Operators.raise inline

### ISSUE THREAD

**Issue by miegir** [Microsoft/visualfsharp#3121]
If `raise` will be inlined, tools such as unit test coverage analyzer in Visual Studio will not mark `raise` calls as partially covered. Methods that use it, such as `nullArg`, will also benefit from this. Is there a reason whiy `raise` is not inlined? I can redefine these operators myself, but it requires inline assembly and therefore that annoying red squiggles in Visual Studio.

**Comment by saul** [comment]
@dsyme this can be closed now that the PR is merged

**Comment by zpodlovics** [comment]
This is a subissue comment related to #3476

Perhaps I am a bit late for the party, but could you please reconsider the exception inlining in the light of the following performance issues (or consider to do compiler generated thow only non-inlining methods when raise/nullarg/failwith/etc are used):

Do not inline methods that never return: https://github.com/dotnet/coreclr/pull/6103
RyuJIT should not inline throw only methods: https://github.com/dotnet/coreclr/issues/1270

Take a look at what Kestrel (.NET Core HTTP Server) done:
https://github.com/aspnet/KestrelHttpServer/commit/6b161f51d49ab87180fda4c16b3c8a10da6761bb
