### ISSUE TITLE
All projects in VFT solution escaped their folders

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3122]
![image](https://cloud.githubusercontent.com/assets/873919/26487456/4068d63e-4208-11e7-8f39-ea2df44717bb.png)

**Comment by cartermp** [comment]
cc @brettfo Any idea what could have caused this?

**Comment by realvictorprm** [comment]
Any reproduction @vasily-kirichenko?
I updated my CodeLens to the latest master and only experienced improvements!

**Comment by cartermp** [comment]
Yeah this is still an issue on latest nightlies

**Comment by cartermp** [comment]
I'll be honest, I'm not even sure what we're doing in the solution file.  These files are horrendous and map guids to guids.  It doesn't *appear* anything which could have caused this was changed in that file.

**Comment by dsyme** [comment]
Fixed.  @vasily-kirichenko  thanks for reporting this
