### ISSUE TITLE
Nightly build 15.4.1.17052601 won't open any projects

### ISSUE THREAD

**Issue by piaste** [Microsoft/visualfsharp#3133]
Updated to nightly 15.4.1.17052601 from the previous nightly and Visual Studio will now refuse to open any F# project:

![devenv_2017-05-26_17-32-41](https://cloud.githubusercontent.com/assets/12280683/26501320/8b19650a-4239-11e7-9e46-a5adf9e3569f.png)

![chrome_2017-05-26_17-38-22](https://cloud.githubusercontent.com/assets/12280683/26501507/26c19842-423a-11e7-9ace-06b5af3fb501.png)

Creating a new basic template results in:

![devenv_2017-05-26_17-33-56](https://cloud.githubusercontent.com/assets/12280683/26501321/8b1abea0-4239-11e7-8b88-fc73ab46d0b1.png)

This seems to be strictly a VS issue with .fsproj files; FSI, Ionide and Rider work as normal.

I've tried uninstalling both the nightly extension and the VS language support component, then rebooting, then reinstalling the extension, without effect.

#### Related information 

* Operating system: Windows 10 v1703
* .NET Runtime, CoreCLR or Mono Version: NETFX 47
* Indications of severity: High?

**Comment by cartermp** [comment]
cc @brettfo

**Comment by brettfo** [comment]
Good catch, this is my bad.

The issue is that `Microsoft.VisualStudio.LanguageServices, Version=2.3.0.0` could not be loaded.  I've been developing locally with an internal 15.3 build and this obviously won't work for anybody else.

I'm testing the revert of #3062 locally (on the publically released VS :smile:) and once that's done I'll spin up another build.

ETA: 6 hours from now (official builds take a long time).

**Comment by realvictorprm** [comment]
Ah thanks @brettfo had a beginner today which struggled with exactly this issue!

**Comment by brettfo** [comment]
As a temporary workaround you could:

1.  Disable the nightly F# feed from within VS.
2.  Remove the bad F# build from a developer command prompt: `VSIXInstaller.exe /uninstall:VisualFSharp`.
3.  (optional) If you still want newer bits, manually install the last good package from [here](https://dotnet.myget.org/F/fsharp/vsix/VisualFSharp-15.4.1.17051701.vsix).

**Comment by realvictorprm** [comment]
I'm sharing the workaround for those who are facing the issue. Thanks for posting @brettfo

**Comment by brettfo** [comment]
I've also deleted the bad build from the package source, but you'll still have to manually remove any existing installs and it may take a few minutes for the bad one to actually get unlisted.
