### ISSUE TITLE
#nowarn “2003” doesn't disable FS2003

### ISSUE THREAD

**Issue by curtnichols** [Microsoft/visualfsharp#3139]
The repro code, below, compiled in a fresh console project in VS2017 (v15.2), fails to suppress the FS2003 warning (which the `#nowarn` directive should suppress). I'm targeting F# 4.1 (FSharp.Core 4.4.1.0).

We compile with "warnings as errors," so this is a strong issue. This is to be used in generated code, so `#nowarn` is far preferable to editing every F# project.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create an F# console project with VS2017.

2. Replace the program code with the code below.

3. Build
```
    open System.Reflection

    #nowarn "2003"
    [<assembly: AssemblyInformationalVersion("13.3.1.74-g5224f3b")>]

    do() // necessary for the assembly attribute

    [<EntryPoint>]
    let main argv = 0
```
#### Expected behavior

No FS2003 warning should be generated.

#### Actual behavior

An FS2003 warning was generated.

`FSC: warning FS2003: An System.Reflection.AssemblyInformationalVersionAttribute specified version '13.3.1.74-g5224f3b', but this value is invalid and has been ignored`

#### Known workarounds

Hand edit all your VS F# projects to ignore the warning in the project properties page. (Ew.)

#### Related information 

All testing was on .NET Framework 4.5 and 4.6.2 on Windows 10. Reproduces with both F# 4.0 and 4.1.

* Problem reproduced on VS 2017 15.2 26430.4.
* Problem reproduced on VS 2017 15.2 26430.6.
* Problem reproduced on VS 2015 14.0.25431.01 Update 3.

Also brought up on https://stackoverflow.com/q/44187146/83202

**Comment by realvictorprm** [comment]
@cartermp Any ideas?

**Comment by cartermp** [comment]
I can repro, though I'm not sure what the root cause is here.

**Comment by dsyme** [comment]
Yeah, it's a compiler issue.  The version information is checked before the scope pragma filters are in place

**Comment by matthid** [comment]
Interestingly I cannot reproduce with the above code and a standalone `fsc file.fs` call. Instead it only reproduces when another version attribute is given:

Reproduces via `fsc file.fs`:

```fsharp
namespace System
open System.Reflection

#nowarn "2003"
[<assembly: AssemblyVersionAttribute("5.0.0")>]
[<assembly: AssemblyInformationalVersion("5.0.0-beta024")>]
do ()
```

Seems like `AssemblyInformationalVersion` has been whitelisted somewhere already but not properly.
