### ISSUE TITLE
Quick Watch shows wrong value on variables with same name

### ISSUE THREAD

**Issue by Dolfik1** [Microsoft/visualfsharp#3141]
Quick Watch shows wrong value on variables with same name 

#### Repro steps

Provide the steps required to reproduce the problem

1. Paste the following:
```fsharp
let testNullA x =
    let x = // quick watch 1
        if isNull(x) then printf "value is null" // quick watch 2
        else 
            printf "value is not null" // breakpoint 1
    ()

let testNullB x =
    let x = // quick watch 3
        if isNull(x) then null // quick watch 4
        else 
            null // breakpoint 2
    ()

[<EntryPoint>]
let main argv = 
    testNullA "123"
    testNullB "123"
    0
```

2. Set breakpoints on line with `// breakpoint 1` and `// breakpoint 2` comments.
3. Start debug
4. Quick watch `x` on lines with `// quick watch n` comment

#### Expected behavior

`quick watch 1: x = null`
`quick watch 2: x = "123"`
`quick watch 3: x = null`
`quick watch 4: x = "123"`

#### Actual behavior

`quick watch 1: x = "123"`
`quick watch 2: x = "123"`
`quick watch 3: x = null`
`quick watch 4: x = null`

#### Known workarounds

Use different names of variables. For example:
```fsharp
let testNullA x =
    let a = // quick watch 1
        if isNull(x) then printf "value is null" // quick watch 2
        else 
            printf "value is not null" // breakpoint 1
    ()
```

#### Related information 

Bug reproduced in Visual Studio 2017 with Visual F# Tools Extension 15.4.17051701 and Visual Studio Code with Ionide extension 2.25.13

**Comment by dsyme** [comment]
I suspect that this is an off-by-one issue in emitting the range information for local variable names in the debug info.  I'm not sure though.  

So it might be very easy to fix, particularly if some tools are available for dumping the debug information produced

**Comment by dsyme** [comment]
Fixed
