### ISSUE TITLE
Inconsistent error message for incompatible return type in nested if / else

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#3146]
This code correctly does not compile. However, the error messages across both branches in the inner if / else are not consistent: -

```fsharp
let x = 1
if x = 1 then true
else
    if x = 2 then "A" // The expression was expected to have type 'bool' but here has type 'string'
    else "B" // All branches of an 'if' expression must have the same return type. This expression was expected to have type 'bool' but here has type 'string'.
```

I would have expected both errors to be the same, using second version (the F#4.1 improved error message).

cc: @forki

**Comment by forki** [comment]
This is very hard to do since you don't know how deep this goes.

**Comment by forki** [comment]
fsi only reports the first one:

![image](https://cloud.githubusercontent.com/assets/57396/26554255/7c723e52-448f-11e7-96d0-a1ec81feccee.png)

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/26554868/b34b8638-4492-11e7-976b-ff079654c558.png)


would this help?

**Comment by forki** [comment]
WIP: https://github.com/Microsoft/visualfsharp/pull/3150

**Comment by isaacabraham** [comment]
Would it be possible to use the same error messages in both places? I'm not really sure what "context type requirements" would mean to a newbie either.

**Comment by forki** [comment]
No we can't use the same error message. It's different reasons.

Am 30.05.2017 9:28 vorm. schrieb "Isaac Abraham" <notifications@github.com>:

**Comment by isaacabraham** [comment]
What are the different reasons? It's an expression that needs to give consistent results; one half returns bool and the other half returns some non-bool. Yes, it trickles down but why is it any different?

**Comment by forki** [comment]
Seems I found a way:

![image](https://cloud.githubusercontent.com/assets/57396/26580425/6850447e-4538-11e7-9007-08a6e1e41b36.png)

**Comment by forki** [comment]
as you can see in https://github.com/Microsoft/visualfsharp/pull/3150/commits/e2b9efdea043a172f219125c1e4ee79168cf7300 this evaluates the current context and passes the Else info down if we are already in else branch.
