### ISSUE TITLE
Links are highlighted inside excluded and commented code

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3155]
![image](https://cloud.githubusercontent.com/assets/873919/26574971/207689a8-452c-11e7-8d78-c8d9785c6563.png)

**Comment by cartermp** [comment]
@Pilchie Is this something which comes from Roslyn, or is this an editor thing?

**Comment by Pilchie** [comment]
It's the editor, and there is an option for it Tools\Options.   See https://github.com/dotnet/roslyn/issues/17108 for some more context.

**Comment by cartermp** [comment]
Hmmm.  I'm not sure what we could do here for F#, then.  I suppose it's a bit annoying, but at least there's a setting to turn it off.  @vasily-kirichenko any thoughts?

**Comment by realvictorprm** [comment]
How are the text effects applied? If it's in roslyn then we might be able to change it.

**Comment by Pilchie** [comment]
It is not in Roslyn, it's directly in the editor.  It's a feature of the editor, with it's own option.  Why do you want to turn it off?

You *can* control it through the mechanism described in dotnet/roslyn#17108, but I'm not sure why you want to circumvent it.

**Comment by cartermp** [comment]
Closing for now, as this isn't a bug.  @vasily-kirichenko please feel free to re-open as a feature request for what @Pilchie was decribing.
