### ISSUE TITLE
Can't open any F# project settings anymore

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#3168]
With VF# tools from master I can't open any F# project settings anymore. I always see:

![image](https://cloud.githubusercontent.com/assets/57396/26673427/2b1265fc-46bd-11e7-9d13-4d7ae1605433.png)

**Comment by vasily-kirichenko** [comment]
:1st_place_medal:

**Comment by forki** [comment]
@vasily-kirichenko Do you see same?

**Comment by vasily-kirichenko** [comment]
I don't use VS.

**Comment by forki** [comment]
good for you. since couple of days I have a million crashes.

**Comment by vasily-kirichenko** [comment]
I think we should take a pause in using VS 2017 for a year or two to let the guys some time to fix it.

**Comment by forki** [comment]
OMG I'm debugging this shit and now I'm in VB code:

![image](https://cloud.githubusercontent.com/assets/57396/26674395/a24978e2-46c0-11e7-87ce-6d8d95082a3a.png)

**Comment by vasily-kirichenko** [comment]
:))))))))))))) be strong.

**Comment by forki** [comment]
I "fixed" it https://github.com/Microsoft/visualfsharp/pull/3169
Tbh I have no idea why we cast to a type and then check that this type implements a certain interface - which it obviously doesn'T

**Comment by forki** [comment]
reinstalled VS. error gone. /shrug

**Comment by realvictorprm** [comment]
@forki Does data in %appdata% remain after deinstallation?
