### ISSUE TITLE
[Question] Type solver fails with simple destructuring

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#3175]
I would like to request a second a pair of eyes on this build failure. Basically I think it is a compiler error, but when I reduce it, then it compiles without any issues.

This is the reduced code that compiles OK (tested in FSI):

```F#

open System

[<System.Diagnostics.DebuggerDisplay("{ToString()}")>]
[<CustomEquality;CustomComparison>]
type PackageName =
| PackageName of string * string

    member this.GetCompareString() =
        match this with
        | PackageName(_,id) -> id

    override this.ToString() = 
        match this with
        | PackageName(name,_) -> name

    override this.Equals(that) = 
        match that with
        | :? PackageName as that -> this.GetCompareString() = that.GetCompareString()
        | _ -> false

    override this.GetHashCode() = hash (this.GetCompareString())

    interface System.IComparable with
       member this.CompareTo that = 
          match that with 
          | :? PackageName as that -> StringComparer.Ordinal.Compare(this.GetCompareString(), that.GetCompareString())
          | _ -> invalidArg "that" "cannot compare value of different types"

let GetTargetsFiles(targetFolder, (pkg : PackageName)) =
    let (PackageName(packageName, packageId)) = pkg
    0;;

```

The relevant part is the destructuring in the second-last line (``let (PackageName(packageName, packageId)) = pkg``). 

BUT the exact same code failed to build with the error below in a commit in Paket: https://github.com/fsprojects/Paket/pull/2388/commits/9f3ec77df0a8ec3a25ad789ce283e71ba063f534#diff-f10ae9a29f6d89affe032f7f01071cc0R642

``  InstallProcess.fs(167, 65): [FS0072] Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
  NuGetV2.fs(642, 22): [FS0001] This expression was expected to have type    'PackageName'    but here has type    ''a * 'b'``

## Workaround: https://github.com/fsprojects/Paket/pull/2388/commits/b9eb886f08ba83b0d58e70cd9f57f4a53b8c7c18

**Comment by dsyme** [comment]
@0x53A I can't explain the paket build failure and error message - I looked around the code and perhaps there is some reason for it.  

Could you reopen with exact repro instructions please and a minimized bug report? Thanks.. :)

**Comment by 0x53A** [comment]
> Could you reopen with exact repro instructions please and a minimized bug report? Thanks.. :)

I will try again to reduce it, but the error disappears relatively fast.

To reproduce it, clone the paket repository and checkout commit 9f3ec77df0a8ec3a25ad789ce283e71ba063f534.

Then either run build.cmd, or just open in the editor of your choice and build.

**Comment by 0x53A** [comment]
Well, seems I didn't really try last time, now I managed to reduce it =).

```F#
type PackageName =
| PackageName of string * string

type PackageFilter =
| PackageName of PackageName
| PackageFilter of string
    
let GetTargetsFiles(targetFolder, (pkg : PackageName)) =
    let (PackageName(packageName, packageId)) = pkg
    []
```

I'm no longer sure if this is really a bug or by design - the issue is that two different unions have a case with the same name.

**Comment by dsyme** [comment]
Yes, this is by design.  There is no overloading of union case names.
