### ISSUE TITLE
Struct tuple versions of functions like Map.ofList

### ISSUE THREAD

**Issue by NinoFloris** [Microsoft/visualfsharp#3179]
Just to give this a spot in the issue list I was wondering if struct tuples would get some deeper integration into the F# BCL.

Currently most of the cases just deal with reference tuples and converting struct tuples into ref tuples negates all of the gains :/
Concerning for instance (but probably not including all):
```
Map.of(List|Array|Seq)
Map.to(List|Array|Seq)
```

Would be interesting to look through the BCL for more cases

**Comment by dsyme** [comment]
@NinoFloris Please add a suggest to http://github.com/fsharp/fslang-suggestions.  Also I think it would be very important to give performance comparisons (also against inlined versions of the ref-tuple features)

**Comment by dsyme** [comment]
(Closing as this should first be tracked at fslang-suggestions)

**Comment by NinoFloris** [comment]
Ah alright, sorry for posting in the wrong location. Still hard to find the right repo without pointers, thanks!
