### ISSUE TITLE
Remove F# portable library templates.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#3185]
C# and VB have already deprecated the creation of new portable libraries in Visual Studio, we propose that Visual F# does the same.

The Scenarios for portable are now to be achieved through the use of the netstandard libraries.  Following implementation of this proposal it will no longer be possible to use the VS tooling to create new projects targeting portable libraries; existing projects will still be loadable, editable and debug-able using VS.

The current portable libraries will be frozen with the current API set and will continue to ship with Visual F# for the Windows desktop deployments for the time being.  They are also available using the FSharp.Core nuget package at: https://www.nuget.org/packages/FSharp.Core/  versions: 4.1.*.

If you have any questions or comments, let me know what you have in mind.

Thanks

Kevin

/cc: @cartermp @dsyme @brettfo

**Comment by dsyme** [comment]
done
