### ISSUE TITLE
Projects with target runtime 3.0 don't show up correctly on the VS project dialog

### ISSUE THREAD

**Issue by ovatsus** [Microsoft/visualfsharp#319]
F# Data still targets runtime of 3.0, but that option doesn't show up on the Target F# runtime dropdown in the Application tab of project properties. Only 3.1 and 4.0 appear as options:

![image](https://cloud.githubusercontent.com/assets/738761/6765386/c53544f8-cfd5-11e4-8d9c-7468a480e96b.png)

**Comment by latkin** [comment]
4.3.0.0 targets 4.0 framework, you have 4.5 framework selected. Does it become an option if you target framework 4.0?

**Comment by ovatsus** [comment]
Yes, If I change the target framework to 4.0, only 4.3.0.0 appears. But It's perfectly legal to have a project targeting .NET 4.5 and still use FSharp.Core 4.3.0.0. .NET 4.0 is the min version. On VS 2013 this combination was allowed, so many projects might have that combination.

**Comment by latkin** [comment]
I see, that makes sense.  @KevinRansom what do you think, should we add 4.3.0.0 back to the framework 4.0 node?

**Comment by KevinRansom** [comment]
Yes I will update it, to add that back.
