### ISSUE TITLE
Order of items in fsproj files change for no good reason

### ISSUE THREAD

**Issue by BentTranberg** [Microsoft/visualfsharp#3202]
I created a new F# library, then commited that. Then i added the FSharp.Data.SqlClient type provider from NuGet to the library. Then I wanted to see what changes were made. This is the diff of the library's fsproj file.

![changemessy](https://user-images.githubusercontent.com/15068882/27068424-5b2f9fc8-5010-11e7-98d6-18a7fdd02ebb.jpg)

It looks like some XML tags have been moved around for no good reason. If I move the tags manually, I get this.

![changeactual](https://user-images.githubusercontent.com/15068882/27068475-920baba4-5010-11e7-95bc-e17c86e400b6.jpg)

I assume that the order of the tags is not important in this case, so that the tags didn't really need to be moved.

(I edited the left side, but should have edited the right side, but never mind that. I think you get my point anyway.)

In my opinion tools should not move stuff around like this, and I bet there are lots of developers that would agree, because it makes it difficult to follow the change history of the project. I would appreciate a fix of this.

I understand this issue perhaps isn't related to this tool, but I don't know how to find out. Which tool can be blamed for moving the tags around in this particular case?

* .NET Framework 4.5.2
* F# 4.0 (4.4.0.0)
* Visual Studio 2015 and 2017 (15.0.26430.4)
* Visual F# Nightly 15.4.1.17060901 in VS 2017
* Severity: Low. Only a nuisance.

**Comment by vasily-kirichenko** [comment]
Just use Paket.

**Comment by dsyme** [comment]
I'll close this as won't fix - the project system code is responsible for project file adjustments is either (a) out of this project or (b) due to be replaced by the roslyn project system and (c) not worth the risk given that this is not a functionality bug, and is just an inconvenience.

**Comment by forki** [comment]
If I understood @cartermp correctly then "new roslyn project system" will only work for the MSBuild 15 projects. So we should actually really fix stuff like that and reconsider the choice

**Comment by cartermp** [comment]
@forki Initially yes, but it's also the replacement project system for all managed languages moving forward.  Since this is a minor issue, I think it's fine to wontfix it given that (although we'd obviously take a PR).  Coincidentally, F# will probably be easier to completely move over to the new project system because it's 100% managed, whereas C#/VB have lots of very old native code in there.
