### ISSUE TITLE
Compiler resolves overload incorrectly with reverse pipeline, but correctly with parenthetical expression

### ISSUE THREAD

**Issue by aggieben** [Microsoft/visualfsharp#3209]
While writing an `async` expression, I found that the `Async.AwaitTask : task:Task.Tasks -> Async<unit>` overload is not resolved by the compiler when a reverse pipeline operator is used, but instead the compiler resolves the `Tasks.Task<'a> -> Async<'a>` overload and fails to build the file because of the type mismatch.

For instance:

```fsharp
let task = async {
        do! Async.AwaitTask (socket.ConnectAsync(Uri(""), CancellationToken.None)) // works fine

        do! Async.AwaitTask <| socket.ConnectAsync(Uri(""), CancellationToken.None) // breaks build
    }
```

Error:
`Program.fs(13,32): error FS0001: The type 'Tasks.Task' is not compatible with the type 'Tasks.Task<'a>`

#### Repro steps

Provide the steps required to reproduce the problem

1. dotnet new console -lang f#

2. write `async` block like the one above

#### Expected behavior

Compiler correctly resolves the type-matched overload.

#### Actual behavior

Compiler incorrectly resolves the type-mismatched overload, but only when the function is applied with a reverse pipeline operator.

#### Known workarounds

Use a parenthetical expression to compose the expressions instead of a reverse pipeline operator.

#### Related information 

Provide any related information 

```
✔ ~/proj/scratch/async-await-task-repro 
15:05 $ dotnet --info
.NET Command Line Tools (2.0.0-preview2-006391)

Product Information:
 Version:            2.0.0-preview2-006391
 Commit SHA-1 hash:  ef5d4b47c3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview2-006391/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

✔ ~/proj/scratch/async-await-task-repro 
23:34 $ mono --version
Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Wed May 31 14:47:04 BST 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
✔ ~/proj/scratch/async-await-task-repro 
23:34 $ 

```

See attached repro project.
[async-await-task-repro.tar.gz](https://github.com/Microsoft/visualfsharp/files/1073442/async-await-task-repro.tar.gz)

**Comment by saul** [comment]
Do you know if this worked in F# 4.0?

**Comment by dsyme** [comment]
@aggieben Yes, this would only be considered a bug if behaviour had changed. Otherwise it is likely per-spec

**Comment by aggieben** [comment]
@dsyme Could you point out where the spec indicates this behavior?  I searched for it in an effort to answer this question for myself, but didn't find anything direct that indicated any difference between the two syntaxes.  Granted, I'm still new to F♯ and may have missed something direct because it wasn't obvious to me.

@saul I guess not - I tried it in LinqPad (which afaict uses F# 4.0) and got the same result.

**Comment by realvictorprm** [comment]
If the specs tell something different I would wonder why. The syntax looks fine to me...

**Comment by dsyme** [comment]
Start at section 6.4 of http://fsharp.org/specs/language-spec/4.0/FSharpSpec-4.0-latest.pdf and follow it through.

Basically if you use
```
    x.OverloadedMethod(arg1,arg2)
```
then the types of ``args`` will be taken into account to help resolve the overloading.  If you use
```
    x.OverloadedMethod
```
then the overload resolution method will be different, based on resolving ``(fun y -> x.OverloadedMethod(y))`` unless other type information is available based on a left-to-right analysis about the number of arguments.

**Comment by realvictorprm** [comment]
thanks for resolving this.
