### ISSUE TITLE
Regression on the fix for #50

### ISSUE THREAD

**Issue by ovatsus** [Microsoft/visualfsharp#321]
I'm still seeing the _Print member. Either I dind't test it properly last time or the behavior has regressed

Repro:

Go to XmlProvider.fsx in F# Data (https://github.com/fsharp/FSharp.Data/blob/master/docs/content/library/XmlProvider.fsx#L276) 

and add the `type t = OutputXml.OrderLine`  line:

![image](https://cloud.githubusercontent.com/assets/738761/6769677/a1eb0d5c-d09d-11e4-89aa-d8b56f9a86a9.png)

**Comment by ovatsus** [comment]
#50 
/cc @forki

**Comment by latkin** [comment]
It seems to only still be a problem in provided types.  And FWIW the member is not present in intellisense, only the tooltip.

This seems like a weird scenario - is the provided type inheriting from a record type?

**Comment by ovatsus** [comment]
Yes, the provided type inherits from a record type: https://github.com/fsharp/FSharp.Data/blob/master/src/Xml/XmlRuntime.fs#L61

The original bug was never about IntelliSense, was always about the tooltip

**Comment by latkin** [comment]
Is the `_Print` guy also implemented directly by the provided type, or does it only come along as part of the base type? From quick tests it doesn't look like base class members are normally shown at all in the tooltip for sub types.

Record types are supposed to be sealed I thought, I'm surprised you are permitted to inherit from them.  Maybe this is a bug that it's allowed at all?

**Comment by ovatsus** [comment]
It only comes from base type. This is not real inheritance, though, it's the base type for an erased type.

**Comment by latkin** [comment]
I see the issue, provided types are [routed to a different function](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/NicePrint.fs#L1507) that was not updated with the original fix.  I'm testing a fix now.
