### ISSUE TITLE
Useful stale type check information is thrown out

### ISSUE THREAD

**Issue by moloneymb** [Microsoft/visualfsharp#3210]
Changes made to a type that result in a failure to type check will mean that type check information will not appear. 

Previously you could work on a member of a type and would access to the (stale but still useful) parameter information of the other members of the type. 

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A

```
type Foo() as this =
    member this.Bar(a:string,b:string) = a + b
```

2. Step B

Type out the middle line to invoke parameter completion

```fsharp
type Foo() as this =
   do this.Bar( 
   member this.Bar(a:string,b:string) = a + b
```

#### Expected behavior
As you type out the line and hit open paren, as well as ',' the parameter completions should drop down and list the parameter type information
#### Actual behavior
There is no parameter completion
#### Known workarounds
None

#### Related information 
* It's pretty annoying not having it
* Still doesn't work on Version 5.4
* Apparently there is an option to enable "use stale" but I'm unable to try it as my Tools -> Options -> F# Tools -> IntelliSense property page throws an error

**Comment by saul** [comment]
+1 to this, cc @dsyme and @vasily-kirichenko 

Also please can you raise a separate issue for "Tools -> Options -> F# Tools -> IntelliSense". Thanks

**Comment by moloneymb** [comment]
Sure I can do that

**Comment by cartermp** [comment]
For 15.3.5:

1. Signature Help is show after typing `(`,
2. Signature Help is _not_ shown after typing `,` afterwards.

**Comment by cartermp** [comment]
This issue no longer repros as of 15.8.6:

<img width="379" alt="screen shot 2018-10-08 at 22 26 51" src="https://user-images.githubusercontent.com/6309070/46648287-5857cb80-cb49-11e8-933e-4958c918ae77.png">
<img width="371" alt="screen shot 2018-10-08 at 22 27 01" src="https://user-images.githubusercontent.com/6309070/46648292-5b52bc00-cb49-11e8-9dde-533463fdc00e.png">
<img width="369" alt="screen shot 2018-10-08 at 22 27 10" src="https://user-images.githubusercontent.com/6309070/46648294-5db51600-cb49-11e8-8359-f0978f38bd74.png">

We fall back to stale data appropriately (tunable with settings), and I believe the work to do automatic brace completion has helped this (among other) IntelliSense issues by providing the parser with more information.
