### ISSUE TITLE
Duplicate entries in error list and Intellisense - VS2017

### ISSUE THREAD

**Issue by NatElkins** [Microsoft/visualfsharp#3211]
When using VS2017, there will be duplicate errors in the error list and in the Intellisense tooltip.  Also, once the error is resolved, only one of the errors will disappear; the other will remain.

#### Repro steps

1. Clone Paket https://github.com/fsprojects/Paket
2. Run build.cmd
3. Open in VS2017 with VF# installed.
4. Reload the two unloaded projects, Paket.Core and Paket (you may not be able to load them if you don't run build.cmd first).
5. Open up a random *.fs file.  In my case, I opened up GitHandling.fs.
6. Create an error.  I suggest just commenting out a random bit of code, like so:
![image](https://user-images.githubusercontent.com/1795462/27187879-5f7327e8-51ba-11e7-9d79-6ca6adc41f63.png)
7. Build using Ctrl-Shift-B.  Look at the error list.
8. Resolve the error, and build again.  Look at the error list.

#### Expected behavior

There should be only one entry in the error list for the error you've created.  Also, once the error is resolved the error should be removed from the error list.

#### Actual behavior

The error is duplicated in the error list.
![image](https://user-images.githubusercontent.com/1795462/27187979-abac42a2-51ba-11e7-967d-c46cf381031f.png)

and also in the Intellisense tooltip

![intellisense-issue](https://user-images.githubusercontent.com/1795462/27188208-6ee4c988-51bb-11e7-897c-c0ee2c4ce807.gif)

If I resolve the error, only one of the errors in the error list is removed rather than both.

#### Known workarounds

Build the project/solution to get rid of the remaining error.

#### Related information 

Windows 10
VS2017 Enterprise
VF#T 15.4.1.17061403
master branch of Paket

**Comment by saul** [comment]
Already fixed in https://github.com/Microsoft/visualfsharp/pull/3071

**Comment by dsyme** [comment]
Closing as addressed/tracked by #3071
