### ISSUE TITLE
Operator precedence with dynamic (?) operator

### ISSUE THREAD

**Issue by ptrelford** [Microsoft/visualfsharp#3214]
#### Repro steps

Create a console project in Visual Studio 2017 (with the F# nightly build installed), and add the following code:

```
type json =
    | Number of float
    | Object of (string * json) list
    // ...
    static member (?) (this:json,name:string) = 
        match this with
        | Object xs -> xs |> List.find (fst >> (=) name) |> snd
        | _ -> invalidOp "Expecting object"
    member this.AsNumber() =
        match this with
        | Number n -> n
        | _ -> invalidOp "Expecting number"

let x = json.Object ["One",Number 1.0;"Two",Number 2.0;"Three",Number 3.0]
let one = x?One.AsNumber() // This works in all FSI & VS2015 and below
let one' = (x?One).AsNumber() // Parens required for compilation in VS2017
```

Build the project

#### Expected behavior

The code should compile as it does in VS2015, VS2013, VS2012, ....

#### Actual behavior

error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.

#### Known workarounds

1) Don't use VS2017
2) LISPify your code with extra parentheses to get it to build with VS2017.

#### Related information 

* Operating system Windows 10 Pro
* Visual Studio 2017 with F# Nightly Build

**Comment by dsyme** [comment]
@ptrelford BTW the duplicate bug is this one: https://github.com/Microsoft/visualfsharp/issues/2416.  Please reopen if you can confirm that this is not fixed, thanks

**Comment by ptrelford** [comment]
@dsyme I ran dir fsc.exe /s - the latest fsc.exe I have installed on my machine is dated 23/02/2017 and in folder C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\
What are the recommended steps to get the latest fsc.exe with the fix?

**Comment by dsyme** [comment]
> @dsyme I ran dir fsc.exe /s - the latest fsc.exe I have installed on my machine is dated 23/02/2017 and in folder C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0. What are the recommended steps to get the latest fsc.exe with the fix?

I'm not totally sure, but my understanding is that the nightly package installs the ``fsc.exe in the same place as a manual install of the built extension.  This is a very, very obscure location, on my machine it is

    C:\Users\dsyme\AppData\Local\Microsoft\VisualStudio\15.0_80d64992\Extensions\0xjx03ws.2mz

I might be wrong about that for the nightlies though.

Anyway, if all you want to do is validate the fix, then either dig out this location or build the master yourself and use ``Release\net40\bin\fsc.exe``

AFAIK there isn't a great solution right now to make the ``fsc.exe`` from a nightly build the default ``fsc.exe`` when working with your projects in Visual Studio.  Perhaps @brettfo  and @cartermp know more though

**Comment by ptrelford** [comment]
I have a similar folder C:\Users\p.trelford\AppData\Local\Microsoft\VisualStudio\15.0_95a66079\Extensions\l55uj42h.kzt with fsi.exe, FSharp.Editor, etc. but no fsc.exe which I guess is why "dir" didn't pick it up.

**Comment by ptrelford** [comment]
OK, I now have a workaround for getting the latest fsc.exe using the instructions on the F# Foundation site: http://fsharp.org/use/windows/

Follow Option 4 / Option B: Standalone installations / Item 4 - [Install the free F# 4.1 Compiler SDK from Microsoft](http://download.microsoft.com/download/F/3/D/F3D6045E-4040-4058-ADAD-2698F1793CBC/Microsoft.FSharp.SDK.Core.msi) which installs the latest fsc.exe in the expected location, i.e. C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0

**Comment by dsyme** [comment]
> I have a similar folder C:\Users\p.trelford\AppData\Local\Microsoft\VisualStudio\15.0_95a66079\Extensions\l55uj42h.kzt with fsi.exe, FSharp.Editor, etc. but no fsc.exe which I guess is why "dir" didn't pick it up.

Urgh, yes, you are right

Thanks for the other details!

**Comment by dsyme** [comment]
> Follow Option 4 / Option B: Standalone installations / Item 4 - Install the free F# 4.1 Compiler SDK from Microsoft which installs the latest fsc.exe in the expected location, i.e. C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0

Can I ask - what did you have installed before this?  Thanks.  I would have assumed your install of Visual Studio 2017 had this?  Or did installing this mean that the nightly install also updated this component?

**Comment by ptrelford** [comment]
I had VS2017 that I installed around May 2017, which I then added the F# nightly builds to. 
The version of fsc.exe I had on my machine prior to installing the F# 4.1 Compiler SDK was dated 23/02/2017. Installing the F# 4.1 Compiler SDK appeared to overwrite the fsc.exe installed with VS2017 with a newer version.

**Comment by kunjee17** [comment]
Faced similar kind of issue for CSV type provider. Have to fallback to 4.0 compilation by modifying fsproj file. 
@ptrelford can you share gist how you set to compile with 4.1. Because I tried to point it out but didn't work for me. Same CSV Provider issue. 

If compilation can be done from project it self then it would be great and make things much easier.

**Comment by ptrelford** [comment]
@kunjee17 I think we might have had different issues.
I had an old (buggy) version of the F# 4.1 compiler which I overwrote with a newer less buggy version.

**Comment by kunjee17** [comment]
@ptrelford Mine is totally buggy. Means not working at all. Anyways thanks for reply.
