### ISSUE TITLE
Type aliases to TPs have incomplete tooltips

### ISSUE THREAD

**Issue by ovatsus** [Microsoft/visualfsharp#322]
With mouse cursor on OrderLine:

![image](https://cloud.githubusercontent.com/assets/738761/6769677/a1eb0d5c-d09d-11e4-89aa-d8b56f9a86a9.png)

With mouse cursor on t:

![image](https://cloud.githubusercontent.com/assets/738761/6769782/5daa0dd4-d0a0-11e4-817b-1edeff4568b5.png)

Is this intentional or a bug?

**Comment by latkin** [comment]
I'm guessing this is intentional - the tooltip for a type alias just points you back to the original type.  It's not TP-specific, either, same thing for standard types:

![image](https://cloud.githubusercontent.com/assets/5943573/6785422/ae34f4c4-d142-11e4-84a1-4c7e9b4e04c4.png)

**Comment by ovatsus** [comment]
Especially for TPs the tooltip becomes not very useful then, is this something that could be accepted as a minor item or it would have to go through uservoice? I could have a shot at sending a PR to improve this

**Comment by dsyme** [comment]
I think you can go ahead and propose an improvement.  Showing 

    type t = ABBREVIATION
           = EVENTUAL TYPE AFTER REMOVING ABBREVIATIONS

may be reasonable.

**Comment by ovatsus** [comment]
Created the user voice here: https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/7367956-improve-tooltips-for-type-aliases

**Comment by dsyme** [comment]
Closing this old suggestion
