### ISSUE TITLE
can't type "match / with" properly if there is a function with "with" (again)

### ISSUE THREAD

**Issue by mattmccutchen-microsoft** [Microsoft/visualfsharp#3220]
I'm seeing the same problem as #2731: when I type `match ... with` and press Enter, `with` gets replaced by an identifier in scope that contains `with`, in my case `withSkippedString` from FParsec.  I don't know if this is a real bug or something broken in my environment.

#### Repro steps

1. Create a F# console application.
2. Add the FParsec NuGet package.
3. At the top of Program.fs, add: `open FParsec`
4. As the first line of `main`, type `match argv with` and press Enter.

#### Expected behavior

A newline is inserted.

#### Actual behavior

`with` is changed to `withSkippedString` is inserted and no newline is inserted.

#### Known workarounds

Press Escape before pressing Enter.

#### Related information 

* Operating system: Windows 10 Enterprise, Version 1703, OS Build 15063.413

The relevant parts of the info from the "About Microsoft Visual Studio" dialog:
```
Microsoft Visual Studio Enterprise 2017 
Version 15.2 (26430.13) Release
VisualStudio.15.Release/15.2.0+26430.13
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise

Visual F# 4.1   00369-90050-01272-AA637
Microsoft Visual F# 4.1
```

**Comment by saul** [comment]
@mattmccutchen-microsoft I can't repro this anymore. Are you using the latest nightly?

**Comment by dsyme** [comment]
I don't repro this either.  I believe there was a fix in this area, so we can close

**Comment by mattmccutchen-microsoft** [comment]
I just saw this since I had the emails going to the wrong mailbox.  I upgraded to the current signed nightly build of the F# tools (15.4.1.17063001) and the problem no longer occurs.  Hopefully I don't run into any other problems using this nightly build until the next release.
