### ISSUE TITLE
FSharpType.IsUnion problem

### ISSUE THREAD

**Issue by Qubitus** [Microsoft/visualfsharp#3225]
I have the following code which gives different results when upgrading FSharp.Core:

F#:
```
type Side = 
  | Left
  | Right
```

C#:
`FSharpType.IsUnion(typeof(Side), FSharpOption<BindingFlags>.None)`

FSharp.Core 4.0.0.1 NuGet: returns **true**
FSharp.Core 4.2.1.0 NuGet: returns **false**

**Comment by dsyme** [comment]
@Qubitus There's something odd about this

Running master:
```
type Side =
  | Left
  | Right

> FSharp.Reflection.FSharpType.IsUnion(typeof<Side>, ?bindingFlags=None);;
val it : bool = true
```

**Comment by dsyme** [comment]
@Qubitus I don't repro this with an F#/C# solution, 

See this zip:

https://1drv.ms/u/s!Aq5gXOPBI5HdirhPo8sp6HqtMp6-8w

**Comment by vasily-kirichenko** [comment]
I have this issue as well:
```
  2017-06-21 01::18:43.266 System.ArgumentException: Type 'FSI_0001+MachineRole' is not an F# union type.
  2017-06-21 01::18:43.266 Parameter name: unionType
  2017-06-21 01::18:43.266    at Microsoft.FSharp.Reflection.Impl.checkUnionType(Type unionType, BindingFlags bindingFlags)
  2017-06-21 01::18:43.266    at Microsoft.FSharp.Reflection.FSharpType.GetUnionCases(Type unionType, FSharpOption`1 bindingFlags)
  2017-06-21 01::18:43.266    at ...\parseUnionCase[a](String name) in 
```
The code:
(in a compiled dll):
```fsharp
let parseUnionCase<'a> name = 
    FSharpType.GetUnionCases typeof<'a>
    |> Seq.tryFind (fun uc -> String.Compare (uc.Name, name, true) = 0)
    |> Option.map (fun uc -> FSharpValue.MakeUnion (uc, [||]) :?> 'a)
```
(in a script)
```fsharp
type MachineRole =
    | Logger
    | Statistics

parseUnionCase<MachineRole> "Logger"

**Comment by Qubitus** [comment]
@dsyne I've tried to reproduce this behavior in a new test solution, however without result.

I've tried writing a test application from scratch and even importing the original dll's containing the unions.
Each time I got the correct result, but within my original solution I was still experiencing this bug when using a version above 4.0.0.1 of the FSharp.Core NuGet package.

I've now added the following binding redirect within the web.config, which fixes my issue for the later versions of FSharp.Core.

**Comment by dsyme** [comment]
> I've now added the following binding redirect within the web.config, which fixes my issue for the later versions of FSharp.Core:

I see, it seems likely that you were somehow binding to multiple copies of FSHarp.Core

Are you using [AutoGenerateBindingRedirects](https://fsharp.github.io/2015/04/18/fsharp-core-notes.html#use-autogeneratebindingredirectstrue-in-applications)?

**Comment by Qubitus** [comment]
@dsyme Yes, I am using AutoGenerateBindingRedirects.

I'm glad I was able to 'fix' my issue, however I keep wondering why I would get an incorrect return value...

**Comment by dsyme** [comment]
@vasily-kirichenko Could you post a full repro for that please?  Also check my attempt to make a repro if you get the chance

**Comment by dsyme** [comment]
@vasily-kirichenko For your case, using VS2017 fsi.exe:

```
C:\GitHub\misc\enumissueinvs2017>type a.fs
module M
open System
open FSharp.Reflection

let parseUnionCase<'a> name =
    FSharpType.GetUnionCases typeof<'a>
    |> Seq.tryFind (fun uc -> String.Compare (uc.Name, name, true) = 0)
    |> Option.map (fun uc -> FSharpValue.MakeUnion (uc, [||]) :?> 'a)

C:\GitHub\misc\enumissueinvs2017>type b.fsx
#r "a.dll"

open M

type MachineRole =
    | Logger
    | Statistics

C:\GitHub\misc\enumissueinvs2017>fsi < b.fsx

Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

>
--> Referenced 'C:\GitHub\misc\enumissueinvs2017\a.dll' (file may be locked by F# Interactive process)

type MachineRole =
  | Logger
  | Statistics
val it : MachineRole option = Some Logger

```

**Comment by vasily-kirichenko** [comment]
I used FSharp.Core 4.4.1.0 with F# 4.0 (VS 2015). May it cause that behavior? I've downgraded to 4.4.0.0 and it works now. If FSharp.Core 4.4.1.0+ must not be used with F# compiler 4.0, we should document it and make very visible.

**Comment by dsyme** [comment]
> I used FSharp.Core 4.4.1.0 with F# 4.0 (VS 2015). May it cause that behavior? 

I'm not aware of a technical reason why that combination would cause that behaviour, but will try to repro it

**Comment by dsyme** [comment]
@vasily-kirichenko @Qubitus I still can't repro this even when using the F# 4.0 compiler (I was using the one that comes with Visual Studio 2015)

1>------ Rebuild All started: Project: Library4, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning 1>	C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\fsc.exe -o:obj\Debug\Library4.dll -g --debug:full --noframework --define:DEBUG --define:TRACE --doc:bin\Debug\Library4.XML --optimize- --tailcalls- -r:C:\Users\dsyme\Downloads\Library4\Library4\packages\FSharp.Core.4.2.1\lib\net45\FSharp.Core.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\mscorlib.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Numerics.dll" --target:library --warn:3 --warnaserror:76 --vserrors --LCID:1033 --utf8output --fullpaths --flaterrors --subsystemversion:6.00 --highentropyva+ --sqmsessionguid:952d1cd6-a19e-420b-8a0e-d42193e6e33f "C:\Users\dsyme\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.fs" AssemblyInfo.fs Library1.fs 
1>	Library4 -> C:\Users\dsyme\Downloads\Library4\Library4\Library4\bin\Debug\Library4.dll
2>------ Rebuild All started: Project: ConsoleApp1, Configuration: Debug Any CPU ------
2>  ConsoleApp1 -> C:\Users\dsyme\Downloads\Library4\Library4\ConsoleApp1\bin\Debug\ConsoleApp1.exe
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Comment by dsyme** [comment]
I'll close this as we don't have a repro using F# 4.1
