### ISSUE TITLE
Optimization error in Set's Intersection, Except

### ISSUE THREAD

**Issue by GregRos** [Microsoft/visualfsharp#324]
It appears that whatever algorithm you use for Intersection, you don't check which is the larger set before you apply it, giving different performance depending on which of the two sets is the larger. I discovered this while benchmarking some collections against FSharp.Set. Union seems unaffected.

I ran 1000 iterations of the set-theoretic operations with one set containing 10,000 elements while the other containing 1 element, 20 times and then averaged out. The benchmarking was very careful and there was practically no noise. I ran it several times to confirm and got very similar results.

![Results](https://cloud.githubusercontent.com/assets/1788329/6773102/da4cd758-d114-11e4-9f9d-ce0206f14566.png)

The operation marked `Except` is `Set.difference`. Ignore the operation called `Difference`. `Set.difference` is slow because of this: (https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/FSharp.Core/set.fs)

```
    let rec diffAux comparer m acc = 
        match m with 
        | SetNode(k,l,r,_) -> diffAux comparer l (diffAux comparer r (remove comparer k acc))
        | SetOne(k) -> remove comparer k acc
        | SetEmpty -> acc    
```

It doesn't check if `acc` is empty

Also submitted here: https://github.com/fsharp/fsharp/issues/398

**Comment by dsyme** [comment]
Fixed by the above PR
