### ISSUE TITLE
Some info is missing in PartialAssemblySignature when signature file exists

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#3259]
Here're several cases which may be connected:
* Consider a type with attributes declared in `*.fs` and `*.fsi` files. After type-checking the `*.fs` file and getting its partial assembly signature, the type contains attributes from the signature file only. When getting the same type via `GetAllUsesOfAllSymbolsInFile`, all attributes are shown.
* When type-checking a signature file, its partial assembly signature doesn't contain types defined in this file (but contains files defined in previous files in the project).
* When symbols are hidden by a signature file they do not appear in `PartialAssemblySignature`.

**Comment by dsyme** [comment]
@auduchinok Could you put this issue in http://github.com/fsharp/FSharp.Compiler.Service please? We're still tracking FCS issues there

**Comment by dsyme** [comment]
@auduchinok Add a tracking link here too please when you've opened the new issue, thanks!

**Comment by auduchinok** [comment]
The issue on FCS repo: https://github.com/fsharp/FSharp.Compiler.Service/issues/784.
