### ISSUE TITLE
Warning for return type of statement in while loop should only indicate the last line

### ISSUE THREAD

**Issue by jpalmer** [Microsoft/visualfsharp#326]
Using the following as test.fs:

```
while true do
    printfn "unneeded"
    true
```

will produce the following error:

```
(2,5): warning FS0020: This expression should have type 'unit' but has type 'bool' ....
```

However, the error is actually on line 3 with the `true`.  This was tested with a build from git of the mono version, but I believe these sorts of bugs go here.

**Comment by forki** [comment]
I can reproduce with VS2013.

![image](https://cloud.githubusercontent.com/assets/57396/6800320/94b191c0-d21d-11e4-9381-a93f022d2643.png)

As you can see the squiggly is also on line 2.

Interestingly if you comment out the printfn line it seems to report line 3:

![image](https://cloud.githubusercontent.com/assets/57396/6800314/7f31900c-d21d-11e4-8ede-24c6203f8009.png)

**Comment by jpalmer** [comment]
I suspect the problem is that the compiler is treating the entire inner part of the while loop as an expression rather than each individual line.  This explains why the squiggly line covers both lines.

**Comment by forki** [comment]
yup:

![image](https://cloud.githubusercontent.com/assets/57396/6800385/33be2c88-d21e-11e4-82ee-239b47b5fa8c.png)

**Comment by forki** [comment]
better repo case for fsi (for reasons):

    let mutable x = 0
    while x < 1 do
        printfn "unneeded"
        x <- x + 1
        true

**Comment by forki** [comment]
tbf I'm not even sure if this should compile at all. but I guess it would be breaking a lot if we change this

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/20641359/7e98fee8-b3f6-11e6-80a9-7dbb1f7f8321.png)

I fixed it, but the fix requires #1115 - so I will just amend it there.

**Comment by forki** [comment]
ec3c13e is the fix.

**Comment by isaacabraham** [comment]
@forki Can I close this in #1103?

**Comment by forki** [comment]
I think it's not merged yet
