### ISSUE TITLE
15.3 preview 3: dependency conflicts

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3261]
1. dotnet new console -n xxx -lang F#
2. dotnet restore
3. open the project in VS
4. result

![image](https://user-images.githubusercontent.com/873919/27575492-b133f88e-5b22-11e7-9829-c29fed4edc6d.png)

**Comment by dsyme** [comment]
Please reopen in https://github.com/dotnet/project-system/

**Comment by enricosada** [comment]
cannot repro after fix https://github.com/dotnet/sdk/pull/1372

**Comment by cartermp** [comment]
Yes, this is now fixed.  You can get things to show up with this CLI/SDK install combo: https://github.com/dotnet/cli/tree/release/2.0.0

That is, the following should work if you install:

* 15.3 Preview 3
* The above linked CLI
