### ISSUE TITLE
15.3 preview 3: debugging .NET Core 2.0 preview 2 projects does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3262]
![image](https://user-images.githubusercontent.com/873919/27578954-736188bc-5b2e-11e7-9a3c-3d0e9dad3a02.png)

**Comment by enricosada** [comment]
can you try use this nuget.config?

https://github.com/fsharp/FsAutoComplete/blob/master/test/FsAutoComplete.IntegrationTests/DotNetSdk2.0/sample1/nuget.config

sdk 2.0 project require .net core 2.0 runtime, and that's preview atm, the nuget.config add the .net core dev nuget feed. that's normal atm for .net core `2.0.0-preview2` (`preview1` instead is on nuget.org already)

**Comment by forki** [comment]
(can it work with paket?)

**Comment by cartermp** [comment]
@vasily-kirichenko Is this with the .NET Core 2.0 SDK (with .NET Core 2.0 Preview 1) installed?

**Comment by enricosada** [comment]
i can repro.

- `<TargetFramework>netcoreapp2.0</TargetFramework>` same error.

- `<TargetFramework>net462</TargetFramework>` or `net47 works

**Comment by enricosada** [comment]
fixed by https://github.com/dotnet/sdk/pull/1372

**Comment by cartermp** [comment]
Yes, this is now fixed.  You can get things to show up with this CLI/SDK install combo: https://github.com/dotnet/cli/tree/release/2.0.0

That is, the following should work if you install:

* 15.3 Preview 3
* The above linked CLI
