### ISSUE TITLE
15.3 preview 3: Solution Explorer does not show proper icons for F# source files

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3264]
![image](https://user-images.githubusercontent.com/873919/27579026-c09f0b04-5b2e-11e7-8e55-8aa08ba2525c.png)

**Comment by saul** [comment]
Are they defined as <Compile> in the project file?

**Comment by enricosada** [comment]
cannot repro, icons are ok for me.

![image](https://user-images.githubusercontent.com/147243/27592261-544436a2-5b54-11e7-883c-dea71787f2f6.png)

**Comment by cartermp** [comment]
I'm observing proper icons both with and without the correct SDK install.  Please re-open if you see it again.

**Comment by Pilchie** [comment]
I think @srivatsn fixed an issue here in the project system repo today.  Not sure why it works for some people and not others though.
