### ISSUE TITLE
15.3 preview 3: adding source files via Solution Explorer results with a new ItemGroup in project file

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3265]
![image](https://user-images.githubusercontent.com/873919/27579103-084a9252-5b2f-11e7-8286-52152d59a435.png)

**Comment by saul** [comment]
It's weird that adding source files also adds them as <None> instead of <Compile>

**Comment by enricosada** [comment]
@davkean @srivatsn any clue?

**Comment by srivatsn** [comment]
The SDK has a glob for None and that's picking up the fs files. @brettfo fixed this recently (https://github.com/Microsoft/visualfsharp/pull/3212) by making the SDK set `<EnableDefaultNoneItems>false</EnableDefaultNoneItems>` for F# but I guess that change hasn't made it into this build.

**Comment by dsyme** [comment]
@srivatsn Is the workaround to add 

    <EnableDefaultNoneItems>false</EnableDefaultNoneItems> 

explicitly to the project file?

**Comment by srivatsn** [comment]
Yes that should work.

**Comment by srivatsn** [comment]
Also looking at the screenshot, the project doesn't have the dependencies node (and a bunch of other stuff is likely broken) - that needs this fix in the SDK - https://github.com/dotnet/sdk/pull/1350. i.e you need the latest 2.0 SDK to make that work

**Comment by cartermp** [comment]
Closing this out as the issue is fixed.  Should be available in preview 4.

**Comment by dsyme** [comment]
@cartermp @srivatsn Great to know!

**Comment by cartermp** [comment]
Re-opening until we have clarity for Preview 4 - @brettfo can you confirm when this change is inserted into VS?

**Comment by cartermp** [comment]
Confirming that this is fixed and inserted.
