### ISSUE TITLE
"Find All References" in VS 2015 not working

### ISSUE THREAD

**Issue by amazingant** [Microsoft/visualfsharp#327]
In the context menu on any token in an F# source file and selecting the `Find All References` tool, I'm currently being told `Can't find a symbol under cursor. Please make sure that the code is typechecked.` in VS's status bar. The code compiles fine with one warning (incomplete pattern matches on a WIP), so the message itself seems inaccurate, but I'm also finding that many things that should be colored by the syntax highlighter aren't.

Current repro steps for me are to open Visual Studio, open an F# project, right-click any token, and select `Find All References`. This happens to me even with the default `Console Application` project by trying to find references to the `printfn` use on line 6. Odd point of note is that this does not happen in F# script files, which also appear syntax highlighted normally.

This is happening to me with Visual Studio 2015 CTP 6 and whatever F# compiler/core version came with it. I'll attempt to repro in a fresh VM and see if it still happens, and of course the easiest way to avoid this is to do a text-based search or to just not use VS 2015 ;)

**Comment by forki** [comment]
are you referring to "Find all references" from http://fsprojects.github.io/VisualFSharpPowerTools/?
AFAIK "Visual F#" (this project here which is shipped directly with VS) doesn't come with "Find all references" support.

/cc @vasily-kirichenko @dungpa

**Comment by dungpa** [comment]
@amazingant I don't know why it happened but the issue went away when I install latest Visual F# Preview on top of VS 2015 CTP 6. Could you give it a try?

**Comment by latkin** [comment]
Per @forki's comment, Visual F# does not implement Find All References or extended syntax highlighting, those both come from the Visual F# Power Tools extensions. Please log an issue there https://github.com/fsprojects/VisualFSharpPowerTools/issues

**Comment by amazingant** [comment]
@forki Yes, it looks like I am. Sometimes I forget that so many Visual Studio things don't exist for F# without the Power Tools extension.

@dungpa That fixed it for me as well. Rather than opening another issue over in the Power Tools extension repo I'll just consider this a result of using the most recently outdated version of F#.

**Comment by amazingant** [comment]
@dungpa Just finished lunch and installed on my dev machine, looks like that fixed the syntax highlighting too! Double thank-you!

**Comment by dungpa** [comment]
You're welcome. Glad that it worked.
