### ISSUE TITLE
Fsc msbuild task does not seem to provide a way to set the preferred UI language on .NET Core

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/visualfsharp#3272]
I'm working on https://github.com/dotnet/cli/issues/4988 which will allow customizing the CLI's UI language to something other than the system default. I have the override flowing to csc.exe and vbc.exe, but cannot find a way to pass the language through to fsc.exe via the msbuild targets on .NET Core.

As far as I can tell:
*  The compiler has two switches for this `--preferreduilang:<string>` and `--LCID:<n>`
 * Only -`-preferreduilang` actually works on .NET Core
 * Only  `--lcid` can be passed via the MSBuild task and target as `$(LCID)`

If that's right, then we need one of two things:
* Wire $(PreferredUILang) to the the Fsc task invocation (matches roslyn)
* Make $(LCID) work on .NET Core

If that's not right, what am I missing and how should I be changing the UI language via an msbuild property on .NET Core?

@KevinRansom

**Comment by dsyme** [comment]
Sounds right to me

**Comment by nguerrera** [comment]
@dsyme Which of two solutions would you favour?

**Comment by dsyme** [comment]
This one: 

> Wire $(PreferredUILang) to the the Fsc task invocation (matches roslyn)

**Comment by dsyme** [comment]
@nguerrera The alignment with C# flags is important

**Comment by KevinRansom** [comment]
I can take care of that.

**Comment by nguerrera** [comment]
Great, then the CLI change I'm making will just light up for fsc once that happens.
