### ISSUE TITLE
Build Events page is broken for CPS projects

### ISSUE THREAD

**Issue by srivatsn** [Microsoft/visualfsharp#3277]
This [line](https://github.com/Microsoft/visualfsharp/blob/6afc4f9776a5dba903ca6b11965a206fb8bc23d8/vsintegration/src/FSharp.ProjectSystem.PropertyPages/PropertyPages/BuildEventsPropPage.vb#L215) needs to be fixed - when the RunPostBuildEvent property is not set, the old PS returned a special missing value where CPS returns an empty string. That code needs to account for the empty string.

**Comment by dsyme** [comment]
@srivatsn Can you submit a PR?  Or even just paste what the line should be below
