### ISSUE TITLE
15.3 preview 3: error highlighting updates in 5-6 seconds

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3278]
Everything is updated with a huge delay, especially error squiggles. Such a feedback is completely useless while you typing code:

![1](https://user-images.githubusercontent.com/873919/27685019-1cb7abf6-5cd5-11e7-9aad-bf859c2232d7.gif)

Can the Roslyn team just provide two simple options: 

* `DoNotMakeAnyArtificialDelays: bool`
* `RunAllInternalAnalyzersInParallel: bool`

?

I understand that they've made a research and honestly trust that such a behavior is great, but it does not work for F#.

**Comment by vasily-kirichenko** [comment]
yeah, everything is so awful, that I cannot use it at all. Back to VS 2015.

**Comment by dsyme** [comment]
@vasily-kirichenko I believe that 15.3 preview 3 doesn't contain the fixes. Use the nightly

**Comment by dsyme** [comment]
I'm seeing < 1sec red squiglly update on master.

**Comment by dsyme** [comment]
(Note I don't know if nightly can be used with 15.3, I'm using it with 15.2)

**Comment by dsyme** [comment]
@vasily-kirichenko Relevant fixes were https://github.com/Microsoft/visualfsharp/pull/3238 and #3270 

I'll close this since it is fixed.  For production coding I'd use 15.2 + nightly today

**Comment by vasily-kirichenko** [comment]
Nightly VSIX + 15.3 preview 3: 3-4 seconds. Still slow. If you think it's fast enough, ok.

**Comment by vasily-kirichenko** [comment]
This is how it should work:

![1](https://user-images.githubusercontent.com/873919/27693761-fbfb6074-5cf2-11e7-82e7-195d2f622b63.gif)

**Comment by dsyme** [comment]
> If you think it's fast enough, ok.

3-4 seconds is not fast enough - with 15.2 I am seeing < 1 second.

**Comment by dsyme** [comment]
@vasily-kirichenko Do you have a 15.2 install available?

**Comment by vasily-kirichenko** [comment]
Yes. Just installed the nighties:

![image](https://user-images.githubusercontent.com/873919/27695298-2220e9aa-5cf7-11e7-947f-a62db87962e2.png)

1. Open folder
2. Select any folder
3. Create a script file
4. Put the following code into it

```fsharp
[<AllowNullLiteral>]
type Test = class end

let _: Test = null
let _: Test = null
let _: Test = null
let _: Test = null
let _: Test = null
let _: Test = null
let _: Test = null
let _: Test = null
let _: Test = null
let _: Test = null
```

5. Close it, then reopen since otherwise nothing works
6. Result

![1](https://user-images.githubusercontent.com/873919/27695441-8f8d6112-5cf7-11e7-82fd-2df33162d3aa.gif)

**Comment by vasily-kirichenko** [comment]
My machine is pretty fast (i7 4GHz).

**Comment by vasily-kirichenko** [comment]
VS Code is also slow (only ~2 times faster than VS), Atom is fast:

![1](https://user-images.githubusercontent.com/873919/27697054-e4b4bb14-5cfb-11e7-9af5-3e944c88026e.gif)

So the problem in VS, not in FCS.

**Comment by dsyme** [comment]
Looking at your screenshot https://github.com/Microsoft/visualfsharp/issues/3278#issuecomment-312000055 it seems between 2-3.5 seconds.

**Comment by cartermp** [comment]
I see ~2 seconds on my machine, but it's clear that that ~2 seconds is taken up mostly by the artificial delay.

**Comment by dsyme** [comment]
There's another usability factor here we should keep an eye on, which is timing consistency

User studies of various things have shown that variable response time (say 1s - 10s) can be even less productive than a fixed, consistent response time well above the average of the variable response time.  People basically get used to a particular response time and are productive if it is consistent (and will be even more productive if it is even faster).

TBH I think our response times are pretty inconsistent, though when working only within one file they are probably fairly ok

**Comment by vasily-kirichenko** [comment]
Today's release Rider beta:

![1](https://user-images.githubusercontent.com/873919/27700769-4d2a74c6-5d07-11e7-8cdb-644343c4f8e8.gif)

**Comment by saul** [comment]
It's clearly an artificial delay - the fact that the semantic highlighting changes quickly shows that we're parsing fast enough. I believe @CyrusNajmabadi knows about these delays and can probably affect some change into how much of a delay we have on our error squiggles. Also IIRC I think one of the other Roslyn devs said that we shouldn't be using document analyzers for our error reporting anyway? I was under the impression only F# does it that way.

**Comment by vasily-kirichenko** [comment]
@saul what we should use then?

**Comment by saul** [comment]
I'm not sure - I can't remember exactly what was suggested. Let me check my emails

**Comment by dsyme** [comment]
Please don't leave these discussions about delays to guesswork.  The exact timings of FCS activities involved can now be seen in traces like this: https://github.com/Microsoft/visualfsharp/issues/3094#issuecomment-310230014.  They now include a lot of causal information, so it's very easy to see the pauses.

Just connect a debugger to devenv.exe, capture a trace of logging for an activity, paste it in a gist, analyze it,

**Comment by dsyme** [comment]
Also, please make sure you're using master on 15.2.  (It's possible the Roslyn-related timings have changed in 15.3, but we don't have a good way of running master reliably on 15.3 yet)

**Comment by dsyme** [comment]
@vasily-kirichenko Are you still seeing these long times?  I'd like to close this as the update times on my machine are fast (at least, when all else is working :) )

**Comment by vasily-kirichenko** [comment]
Yes, it seems working fast on small files, on large ones it's constrained by FCS.

**Comment by dsyme** [comment]
@vasily-kirichenko Super, thanks for checking

**Comment by vasily-kirichenko** [comment]
Sorry, I was wrong, it still takes about 4-5 seconds to update:

![1](https://user-images.githubusercontent.com/873919/29712410-602c39b6-89a2-11e7-84ac-af83d34d34de.gif)

This file belongs to a really tiny project (3 source files, 200 lines of code), which is a part of a large solution (> 100 F# project).

On a hello world project (and a solution that contains this project only), it works about twice as fast:

![1](https://user-images.githubusercontent.com/873919/29712528-f0d901d8-89a2-11e7-9c36-82b6b29239d4.gif)

Compare to Rider:

![image](https://user-images.githubusercontent.com/873919/29712567-3369d360-89a3-11e7-97f4-9608ececa14e.png)

IMHO this is how it should work.

**Comment by saul** [comment]
@vasily-kirichenko  It's worth trying setting `highPriority=true` here and seeing if it makes a difference:

https://github.com/Microsoft/visualfsharp/blob/86fcbe34761a820be6e906370e26e342d5252c89/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L70

**Comment by dsyme** [comment]
@saul I think we've looked into it and it doesn't make much difference

@vasily-kirichenko I measure 3.0-4.5 seconds from your screen shot.  

I'm not sure of Rider's approach to using FCS, but it's possible their approach may not be entirely sustainable, or may have other tradeoffs.  But I agree it's very nice and immediate for these samples.

**Comment by vasily-kirichenko** [comment]
I've tried `highPriority=true`, no difference.

**Comment by vasily-kirichenko** [comment]
Errors highlighting apparently works ok, I'm closing it.

**Comment by saul** [comment]
Can we re-open this please? It hasn’t been resolved

**Comment by vasily-kirichenko** [comment]
@saul Still not resolved?

**Comment by cartermp** [comment]
With 15.7.x the consistency issue should be resolved, now that the error diagnostics analyzer is always run first. I see consistent 1-2 seconds, which although it could be improved, is at least consistent unlike before.

**Comment by dsyme** [comment]
@cartermp OK, I think this should be closed then

**Comment by cartermp** [comment]
Closing (since I apparently never bothered to do that...)
