### ISSUE TITLE
Nightly VSIX throws exception being installed in 15.3 preview 3

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3280]
1. Open a file
2. Type a character
3. Result:

> System.TypeInitializationException: The type initializer for 'Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionProvider' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$FSharp-Editor>.$CompletionProvider' threw an exception. ---> System.MissingMethodException: Method not found: 'Microsoft.CodeAnalysis.Completion.CompletionItem Microsoft.CodeAnalysis.Completion.CommonCompletionItem.Create(System.String, System.Nullable`1<Microsoft.CodeAnalysis.Glyph>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.SymbolDisplayPart>, System.String, System.String, System.Nullable`1<Int32>, Boolean, Boolean, System.Collections.Immutable.ImmutableDictionary`2<System.String,System.String>, System.Collections.Immutable.ImmutableArray`1<System.String>, Microsoft.CodeAnalysis.Completion.CompletionItemRules)'. at <StartupCode$FSharp-Editor>.$CompletionProvider.-cctor@49-1.Invoke(Int32 n, Tuple`2 tupledArg) at Microsoft.FSharp.Primitives.Basics.List.mapi[T,TResult](FSharpFunc`2 f, FSharpList`1 x) at Microsoft.FSharp.Collections.ListModule.MapIndexed[T,TResult](FSharpFunc`2 mapping, FSharpList`1 list) at <StartupCode$FSharp-Editor>.$CompletionProvider..cctor() --- End of inner exception stack trace --- at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionProvider..cctor() --- End of inner exception stack trace --- at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionProvider..ctor(Workspace workspace, SVsServiceProvider serviceProvider, FSharpCheckerProvider checkerProvider, ProjectInfoManager projectInfoManager, AssemblyContentProvider assemblyContentProvider) at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionService..ctor(Workspace workspace, SVsServiceProvider serviceProvider, FSharpCheckerProvider checkerProvider, ProjectInfoManager projectInfoManager, AssemblyContentProvider assemblyContentProvider) at Microsoft.VisualStudio.FSharp.Editor.FSharpCompletionServiceFactory.Microsoft-CodeAnalysis-Host-Mef-ILanguageServiceFactory-CreateLanguageService(HostLanguageServices hostLanguageServices) at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.<>c__DisplayClass4_0.<.ctor>b__1() at System.Lazy`1.CreateValue() at System.Lazy`1.LazyInitValue() at System.Lazy`1.get_Value() at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.GetService[TLanguageService]() at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.GetCompletionService() at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.ExecuteCommandWorker[TCommandArgs](TCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.CommandHandlers.AbstractCompletionCommandHandler.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1() at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteReturnOrTypeCommand(CommandArgs args, Action nextHandler, CancellationToken cancellationToken) at Microsoft.CodeAnalysis.Editor.Implementation.Formatting.FormatCommandHandler.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1() at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.HandlePossibleTypingCommand(CommandArgs args, Action nextHandler, Action`1 actionIfInsideActiveSpan) at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.RenameCommandHandler.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.<>c__DisplayClass6_1`1.<ExecuteHandlers>b__1() at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.SignatureHelp.Controller.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.CommandHandlers.SignatureHelpCommandHandler.ExecuteCommandWorker[TCommandArgs](TCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.CommandHandlers.SignatureHelpCommandHandler.Microsoft.CodeAnalysis.Editor.ICommandHandler<Microsoft.CodeAnalysis.Editor.Commands.TypeCharCommandArgs>.ExecuteCommand(TypeCharCommandArgs args, Action nextHandler) at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.ExecuteHandlers[T](IList`1 commandHandlers, T args, Action lastHandler) at Microsoft.CodeAnalysis.Editor.Implementation.Commands.CommandHandlerService.Microsoft.CodeAnalysis.Editor.ICommandHandlerService.Execute[T](IContentType contentType, T args, Action lastHandler) at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteTypeCharacter(IntPtr pvaIn, ITextBuffer subjectBuffer, IContentType contentType, Action executeNextCommandTarget) at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.ExecuteVisualStudio2000(Guid& pguidCmdGroup, UInt32 commandId, UInt32 executeInformation, IntPtr pvaIn, IntPtr pvaOut, ITextBuffer subjectBuffer, IContentType contentType) at Microsoft.VisualStudio.LanguageServices.Implementation.AbstractOleCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 commandId, UInt32 executeInformation, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.CommandChainNode.InnerExec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.SendCommand(Guid cmdGroup, UInt32 cmdID, Object inParam) at Microsoft.VisualStudio.Editor.Implementation.VsKeyboardFilter.TextInput(TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

**Comment by dsyme** [comment]
The nightly doesn't work in 15.3 preview.  @bretfo's advice we

* If using 15.2, then use nightlies or compile master
* If using 15.3 previews, compile and use the vs2017-rtm branch

**Comment by cartermp** [comment]
Yeah, unfortunately this is a WONTFIX right now, because:

(a) The VS infrastructure would need to support the notion of nightly "channels".  This is something the VS platform team was in the early stages of designing when we first announced nightlies, but I'm not sure what the current status is.  I can find out.

(b) Our own build would have to be updated to support said "channels".  We'd also have to manually cherry-pick fixes over from the 15.3 branch over to the 15.2 branch.  I'm also not sure if previous updates are considered supported when a new one is released.  I suppose I should find that one out.
