### ISSUE TITLE
[Question] FS0072: Type inference fails between Task and Task<'T>

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#3281]
ref https://github.com/rspeele/TaskBuilder.fs/issues/2

use this ``task`` builder: https://github.com/rspeele/TaskBuilder.fs/blob/6aa7ef6e47caf9f0af56413c4bb6d256763ffbaf/TaskBuilder.fs

and this F# code consuming the builder:

```F#
open System.Threading.Tasks
open FSharp.Control.Tasks.ContextSensitive

type X() =
    member this.Num = 0

let xTask : Task<X> = task { return X() }

let badTask =
    task {
        let! x = xTask
        return x.Num + 1
        //      ^ FS0072: Lookup on object of indeterminate type based on
        //        information prior to this program point.
    }
``` 

This caused the author the remove direct support for Task, and requires the user to wrap a non generic ``Task`` with a helper (``unitTask``), see https://github.com/rspeele/TaskBuilder.fs/commit/eeb42e52fce7d082dae1d25f2b297f9849b16f4b.

I can still reproduce this issue with the latest nightly. Do you think the type inference could be improved to support this? Or is there maybe a workaround that could be applied to the ce-builder, so that the ``Task<'T>`` overload is prioritized?

**Comment by dsyme** [comment]
@0x53A This is either a language suggestion or a stackoverflow question 

There is a hack to prioritize overloads by making them extension methods, see https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/Query.fsi#L349 for an example.  However it may not help with an interaction with type inference like this

**Comment by 0x53A** [comment]
For me FS72 is never clear between bug-fixing and language suggestion (e.g. https://github.com/Microsoft/visualfsharp/issues/3170).

It would actually expect the above code snippet to compile, and my first reaction was that this must be a bug, but I'm sure you can find a quote in the spec which says this is by design. =)

Your tip with the extension methods seems to work, I will try to create a PR against the repo.

Thank you!

Should I close this and create a new issue at fs-lang-suggestions, or keep this open?

**Comment by dsyme** [comment]
> Should I close this and create a new issue at fs-lang-suggestions, or keep this open?

Close and open a suggestion issue

**Comment by dsyme** [comment]
@0x53A You are correct that https://github.com/Microsoft/visualfsharp/pull/3173 should really have had an RFC though it was the most borderline of these cases I know of.  If you could create one that would be great.
