### ISSUE TITLE
visualfsharp crashes on Visual Studio load (similar to #2917)

### ISSUE THREAD

**Issue by daz10000** [Microsoft/visualfsharp#3287]
I am subscribed to the nightly updates and VS2017 stopped loading suddenly (not necessarily related to the nightly update) with the error message (shown from activity log below).   Oddly uninstalling F# language support doesn't seem to remove the Visual F#tools, but leaves it disabled.  I've tried uninstalling the extension or trying to install the nightly update which is now available and both fail to perturb it.  Have tried uninstalling F# language support and reinstalling and visual studio remains in the same state.  I tried the solution mentioned in issue 2917 but the component cache folder doesn't seem to be present on my machine.

![fsharpinstallpage](https://user-images.githubusercontent.com/6342645/27720659-9eb235d8-5d0f-11e7-9040-7e8852646203.png)

I've included the log at the time of crash in case it's useful.  I have had this happen a couple of times over the last few months.  Last time I repaired VS2017 which fixed the problem but basically blew everything away.   The only other major plugin I run is VsVim

```
  <entry>
    <record>486</record>
    <time>2017/06/30 03:24:19.929</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [FSharpPackage]Source: &apos;Microsoft.VisualStudio.Composition&apos; Description: Expected 1 export(s) with contract name &quot;Microsoft.VisualStudio.FSharp.Editor.SettingsPersistence+ISettings&quot; but found 0 after applying applicable constraints.&#x000D;&#x000A;Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name &quot;Microsoft.VisualStudio.FSharp.Editor.SettingsPersistence+ISettings&quot; but found 0 after applying applicable constraints.&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()&#x000D;&#x000A;   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()&#x000D;&#x000A;   at Microsoft.VisualStudio.FSharp.Editor.FSharpPackage.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>
    <guid>{871D2A70-12A2-4E42-9440-425DD92A4116}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
```

#### Related information 

Provide any related information 

* Operating system  win10
* Branch  nightly
* .NET Runtime, CoreCLR or Mono Version  4.6.1 and lower versions installed
* Editing Tools (e.g. VS2017 pro )
* Indications of severity - effectively cripples all in editor support for F# until I reinstall visual studio

**Comment by Huqin-China** [comment]
+1
Provide any related information

Operating system win10
Branch nightly 20170630
Editing Tools (e.g. VS2017 15.2 latest )

**Comment by dsyme** [comment]
This is the error listed above.  Please, we need an MEF expert to look at this @srivatsn @brettfo @Pilchie 

    <description>LegacySitePackage failed for package [FSharpPackage]Source: &apos;
Microsoft.VisualStudio.Composition&apos; 
Description: Expected 1 export(s) with contract name &quot;
Microsoft.VisualStudio.FSharp.Editor.SettingsPersistence+ISettings&quot; but found 0 after applying applicable constraints.&#x000D;&#x000A;Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name &quot;
Microsoft.VisualStudio.FSharp.Editor.SettingsPersistence+ISettings&quot; but found 0 after applying applicable constraints.&#x000D;&#x000A;   
at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)&#x000D;&#x000A;   
at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)&#x000D;&#x000A;   
at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)&#x000D;&#x000A;   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)&#x000D;&#x000A;   
at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()&#x000D;&#x000A;   
at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()&#x000D;&#x000A;   
at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()&#x000D;&#x000A;   at Microsoft.VisualStudio.FSharp.Editor.FSharpPackage.Initialize()&#x000D;&#x000A;   
at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>

**Comment by Pilchie** [comment]
It sounds like the nightly is in a strange, half-installed state.  I would try getting rid of it manually to get back to a clean state:

1. Open `%LocalAppData%\Microsoft\VisualStudio\15.0_xxxxx\Extensions` and either delete it all, or find the directory that contains the F# nightly extension.
2. Delete `%LocalAppData%\Microsoft\VisualStudio\15.0_xxxxx\devenv.exe.config`
3. Delete `%LocalAppData%\Microrost\VisualStudio\15.0_xxxxx\ComponentModelCache`
4. Start a VS Command prompt and run `devenv /updateconfiguration`
5. Run VS and verify that things work as expected.
6. [Optional] Install the nightly again.

**Comment by daz10000** [comment]
Thanks! - when I first went in I couldn't find the extensions folder.   I ended up doing a repair on VS and it now starts up correctly (lost all my other extensions and settings but it's functional).  I've subscribed to the nightly updates again so let's see what happens.  Will keep the info above in case it happens again.

**Comment by dsyme** [comment]
I'll close, please reopen if it happens again

**Comment by pkanavos** [comment]
Time to reopen this. 

Got the same after installing Visual Studio 2017 15.5 Preview 2 and checking on the `F# Package`. I *didn't* use the nightly build, just the package displayed in the VS Installer

Now I get the typical Visual Studio error dialog box :

```
---------------------------
Microsoft Visual Studio
---------------------------
The 'FSharpPackage' package did not load correctly.
```

And ActivityLog.xml contains : 

```
LegacySitePackage failed for package [FSharpPackage]Source: &apos;Microsoft.VisualStudio.Composition&apos; Description: Expected 1 export(s) with contract name &quot;Microsoft.VisualStudio.FSharp.Editor.SettingsPersistence+ISettings&quot; but found 0 after applying applicable constraints.
Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name &quot;Microsoft.VisualStudio.FSharp.Editor.SettingsPersistence+ISettings&quot; but found 0 after applying applicable constraints.
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName)
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]()
   at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
   at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
   at Microsoft.VisualStudio.FSharp.Editor.FSharpPackage.Initialize()
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)
```
F# projects load and build, but the editor is almost unusable. The Enter key doesn't work, syntax colouring doesn't work. 

I'll try to remove the package

**Comment by reijerh** [comment]
Had the exact same problem this week (VS2017 15.4.5) with the latest F# Tools nightly. I think the problem 
 was triggered by updating VS to the latest version.

I've attached the `ActivityLog.xml`.

[ActivityLog.txt](https://github.com/Microsoft/visualfsharp/files/1530939/ActivityLog.txt)

**Comment by cartermp** [comment]
@reijerh Now that 15.5 is released, you should use any nightly build atop that (should you continue to use nightlies).  They won't work for any previous version.

**Comment by reijerh** [comment]
Alright, the 15.5 update just became available it seems here, nice.

(BTW I was able to get it in a working state using these instructions: https://github.com/Microsoft/visualfsharp/issues/3287#issuecomment-312515611 )
