### ISSUE TITLE
Strange compile error with generic abstract members returning unit

### ISSUE THREAD

**Issue by saul** [Microsoft/visualfsharp#3289]
When I have a generic interface (of `unit`) where one of the members returns this generic type, the compiler believes that I have not implemented the correct type when implementing:

```f#
type Crate = abstract member Apply : CrateEvaluator<'ret> -> 'ret
and CrateEvaluator<'ret> = abstract member Eval : unit -> 'ret

let foo () : unit =
    let leafCrate = { new Crate with member __.Apply e = e.Eval () }
    leafCrate.Apply { new CrateEvaluator<_> with
        member __.Eval () = ()
    }
```

Errors:
```
(6,27) At least one override did not correctly implement its corresponding abstract member
(7,19) The member 'Eval : unit -> unit' does not have the correct type to override the corresponding abstract method.
```

You can work around this by using a strong unit type:

```f#
type Crate = abstract member Apply : CrateEvaluator<'ret> -> 'ret
and CrateEvaluator<'ret> = abstract member Eval : unit -> 'ret

type Unit = Unit

let foo () : unit =
    let leafCrate = { new Crate with member __.Apply e = e.Eval () }
    leafCrate.Apply { new CrateEvaluator<_> with
        member __.Eval () = Unit
    }
    |> ignore
```

I'm wondering what's special about `unit` that is causing the compiler to think that the abstract member hasn't been implemented? I'm hoping this is a simple fix 😄

**Comment by dsyme** [comment]
See https://github.com/fsharp/fslang-suggestions/issues/25.  Not a simple fix, sorry

**Comment by dsyme** [comment]
Closing as this is covered by the language suggestion

**Comment by saul** [comment]
Thanks Don - I didn't think to search the language suggestions for an already reported issue. How much effort do you think this would take to fix?

**Comment by dsyme** [comment]
@saul Answered on the thread: https://github.com/fsharp/fslang-suggestions/issues/25#issuecomment-312252103
