### ISSUE TITLE
Lack of pattern matching warning when capturing only with &

### ISSUE THREAD

**Issue by simoncowen88** [Microsoft/visualfsharp#3296]
The use of _only_ `&` in a pattern match causes a warning (FS0026) to fail to be produced.

#### Repro steps
    type T = | A | B

    // no captures => warns about unmatchable case
    let stupidMatch a b =
        match a,b with
        | A, B
        | A, A
        | B, A -> printfn "A"
        | A, B -> printfn "B" // warning FS0026: This rule will never be matched
        | _, _    -> printfn "C"

    // '&' captures only => no warning
    let stupidMatchWithCapture a b =
        match a,b with
        | A & v, B
        | A & v, A
        | B & v, A -> printfn "A"
        | A,     B -> printfn "B" // no warning
        | _,     _ -> printfn "C"

    // introducing an 'as' capture => warns about unmatchable case again
    let stupidMatchWithCaptureAndAs a b =
        match a,b with
        | A as v, B
        | A & v, A
        | B & v, A -> printfn "A"
        | A,     B -> printfn "B" // warning FS0026: This rule will never be matched
        | _,     _ -> printfn "C"

Print statements are mostly just there for ability to sanity-check behaviour at run time.

#### Expected behavior

In `stupidMatchWithCapture` we expect to see a warning FS0026 for case `| A,B -> printfn "B"`

#### Actual behavior

No warning is produced

#### Known workarounds

Always using an `as` capture somewhere in the match, uncertain if this covers all cases though.

**Comment by simoncowen88** [comment]
I'm uncertain if this is the same issue, or related to, issue #3294

**Comment by chillitom** [comment]
Seems like it might be related to this: https://github.com/Microsoft/visualfsharp/issues/2754 and in turn this https://github.com/fsharp/fslang-suggestions/issues/586

**Comment by dsyme** [comment]
Since ``&`` is involved I'm pretty sure that #3294 is the same issue

BTW my impression is that ``&`` is rarely used, and of the places where it is used, the cases also covered by ``as`` are most of those

**Comment by cartermp** [comment]
Closing as per #3294 duplicate
