### ISSUE TITLE
Warning FS0073: internal error: Typar not found during XmlDoc generation

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#33]
[from fsbugs]  Ported from [Codeplex](http://visualfsharp.codeplex.com/workitem/5)

Simplified repro of root cause:

```fsharp
let rec foo< > c = bar c
and bar c = 0
```

changing the order of lines 1 and 2 fixes the problem 

Original repro:
```
 C:\Users\latkin\Desktop\FSharp.DataFrame-typar-error\FSharp.DataFrame-typar-error\src\Frame.fs(251,28): warning FS0073: internal error: Typar not found during XmlDoc generation
```

```fsharp
/// [category:Series operations]
member frame.SeriesApply<'T>(strict, f:Func<Series<'TRowKey, 'T>, ISeries<_>>) = 
    frame.Columns
    |> Series.mapValues (fun os ->
        match os.TryAs<'T>(strict) with
        | OptionalValue.Present s -> f.Invoke s
        | _ -> os :> ISeries<_>)
    |> Frame<'TRowKey, 'TColumnKey>.FromColumnsNonGeneric
```

**Comment by forki** [comment]
I think the code sample is not correctly displayed

**Comment by latkin** [comment]
Updated with what I believe is proper formatting (though the original repro is probably not useful given the greatly simplified repro), and a link back to original codeplex bug.

**Comment by forki** [comment]
The foo function still looks strange. Is it really a space between the angle brackets?

**Comment by latkin** [comment]
The code is not properly formed, but it does repro the bug.  Repro also occurs with more fully-formed code:

```fsharp
let rec foo<'t> c = bar c
and bar c = 0
```

**Comment by latkin** [comment]
Oddly enough, the workaround compiles successfully, even with the (I would think) invalid code `< >`:

```fsharp
let rec bar c = 0
and foo< > c = bar c
```

**Comment by vladima** [comment]
@forki, `foo< >` stands for type application with an empty list of type parameters (6.4 Basic application expressions)

**Comment by dsyme** [comment]
@latkin Hmm... I labelled this as fix ready in May - did the typar check PR fixed this and I just forgot to reference the issue?

**Comment by latkin** [comment]
With current codebase, repro here https://github.com/Microsoft/visualfsharp/issues/33#issuecomment-70894927 now fails with `test.fs(1,9): error FS3188: Type inference caused an inference type variable to escape its scope. Consider adding type annotations to make your code less generic.`

That's better than an ICE but it still doesn't compile.

**Comment by dsyme** [comment]
That's a sufficient resolution. In that case we can close this.
