### ISSUE TITLE
Can't build ci_part3 locally

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#3301]
* clone project
* run `build.cmd ci-part3`

![image](https://user-images.githubusercontent.com/57396/27819515-f41b615a-609a-11e7-98c2-39a5be298815.png)

**Comment by forki** [comment]
I also like the `\r` ;-)

**Comment by enricosada** [comment]
Deps of dev build of dotnet cli like preview3 arent on nuget.org ( `2.0.0-preview2` is there, maybe easier to use that to avoid dev pkgs?) and these need a  .net core dev feed.

adding this feed should fix it ( ref [cli](https://github.com/dotnet/cli/blob/master/NuGet.Config#L7) )

```xml
<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
```

Saved a `nuget.dev.config` and passed to `dotnet restore` make it less fragile. add as `nuget.config` directly (so picked automatically) is more risky, but depends on what deps you want to use (really dev os just current preview)

**Comment by dsyme** [comment]
Closing old issue
