### ISSUE TITLE
Known differences in behaviour for the  F# compiler when running on .NET Core v. .NET Framework 

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#3311]
cc @ncave 

This is to document the known differences in behaviour and spec  for the  F# compiler and FSharp.Compiler.Service.dll when running on .NET Core v. .NET Framework. Apart from the first they are generally inconsequential or even unreachable in normal use.

The F# compiler is run on .NET Core when using the .NET SDK 2.0

### Major differences

* Type providers are not yet supported when any of fsc.exe, fsi.exe, fsiAnyCpu.exe, FSharp.Compiler.Service.dll are run using .NET Core , see  #2406 and workaround #3303 

### Minor differences

* The .NET Framework fsc,exe allows small, incomplete argument sets where a set of default references are assumed, e.g. ``fsc.exe a.fs``.  Likewise, you can compile scripts and the same set of references is used ``fsc.exe script.fsc``.  This mode of use of ``fsc.exe`` is not really supported yet for .NET Core - the expectation is that ``msbuild`` or ``dotnet build`` will pass ``--noframework`` and a full set of references.    If you try to directly invoke .NET Core ``fsc.exe`` without a complete set of args you will either get no useful references or an invalid set of references.

* Similarly, the .NET Framework fsi.exe can be started with just ``fsi.exe``, and a default set of references is assumed.  Again, the .NET Core fsi.exe is not really yet designed for this mode of use, and a full set of references must be given

* Similarly, the .NET Framework FSharp.Compiler.Serice.dll can analyze scripts and get the project options from them, and can compile using incomplete option sets.  In this case, this mode of use is possible for the .NET Core FSharp.Compiler.Service.dll, see the examples tests in the FCS repository added by @ncave 

Other minor differences will be documented here over time, and we may update this issue to reflect latest reality

**Comment by enricosada** [comment]
@dsyme is not better as wiki page doc in https://github.com/Microsoft/visualfsharp/wiki ?

**Comment by dsyme** [comment]
Closing old discussion
