### ISSUE TITLE
Intellisense/Autocomplete is messing with case of parameter names

### ISSUE THREAD

**Issue by BentTranberg** [Microsoft/visualfsharp#3312]
I will use this source to explain the behaviour.

    type DemoReportParameters() =
        inherit ReportParameters()
        member val Date: DateTime = DateTime.MinValue with get, set
        member val Text: string = "" with get, set
        member val Index: int = 0 with get, set
        member val Number: float = 0.0 with get, set

    let demoReportParameters date text index number = DemoReportParameters(Date=date, Text=text, Index=index, Number=number)

When typing the arguments in the constructor, the parameter names, or property names - whatever they are - will automatically be lowercased when the corresponding equal sign is typed. I end up with e.g. "date=date", and will have to go over these and correct them.

The behavior is not consistent, but is usually there. If you don't see it, try typing slower.

Annoying, and slows me down a bit, but otherwise not a problem.

VS 2017  15.2 (26430.14), Visual F# Nightly 15.4.1.17070601

**Comment by saul** [comment]
This is another example of us needing to only commit IntelliSense on enter and not = (and others)
