### ISSUE TITLE
Duplicated warnings

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3314]
https://github.com/Horusiath/Akkling/blob/master/src/Akkling/ActorRefs.fs#L209

![image](https://user-images.githubusercontent.com/873919/27983178-d640e6ec-63be-11e7-9576-e70c7bd64dcd.png)

**Comment by NatElkins** [comment]
This is fixed with https://github.com/Microsoft/visualfsharp/pull/3071 .  I had made a similar issue which was closed (https://github.com/Microsoft/visualfsharp/issues/3211).

**Comment by cartermp** [comment]
Closing as dupe of #3047
