### ISSUE TITLE
Index was outside the bounds of the array when adding a reference in Android

### ISSUE THREAD

**Issue by joj** [Microsoft/visualfsharp#3318]
When trying to add a reference in an Android project the dialog is not shown and the I get an Index was outside the bounds of the array dialog instead. The problem is in this line: https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.ProjectSystem.FSharp/Project.fs#L1015. The path on android projects is empty, so len is 0 and len-1 is outside the bounds of the array (anything would be, really). The fix is simply to check for len > 0 there. I'll send a PR. Screencast showing the issue: https://www.screencast.com/t/M1WK4Wl9y1P

#### Repro steps

Provide the steps required to reproduce the problem

1. Create Fsharp Android Blank App Project
2. Right click on References Option
3. Error dialog is shown

#### Expected behavior

The expected behavior is to get the Add Reference dialog, properly populated with Android references..

#### Actual behavior

The actual behavior is the error dialog, as seen in the screencast. 

#### Known workarounds

The possible workaround is to add the references on text, editing the fsproj directly. It's not a nice workaround :)

#### Related information 

Provide any related information 

* Windows 10
* master
* Current Stable Android version
* Visual Studio 2017 latest stable (and internal builds), with current master of F#.
* This is a very high severity for Android, as no references can be added (other than probably nugets)

**Comment by andybrackley** [comment]
Hi, I'm currently running into this issue in VS2017 Pro ( Version 15.3.5 ), Visual F# 4.1, Xamarin 4.7.9.45.
It seems as though this was fixed and closed sometime ago, do you know when this fix will be available?  

Thanks

**Comment by cartermp** [comment]
This fix should be in for 15.4.
