### ISSUE TITLE
`[<ProjectionParameter>] ` on `for`'s sequence parameter ignored?

### ISSUE THREAD

**Issue by Gitgiddy** [Microsoft/visualfsharp#332]
This is a work in progress, so the code as a whole doesn't make sense, but I am just trying to determine whether one aspect of it is a flaw in the way F# desugars computational expressions.

In this example code below `ce1` and `ce2` are not valid - I THINK because `[<ProjectionParameter>]` is being ignored rather than the normal behavior of it being understood it to mean `(fun _d -> _d.As)` as happens with `where` and as `ce3` behaves.  `ce4`, which also doesn't work, shows that it isn't just because it is the first statement in the CE.

The total goal involves getting my `ce1` and `ce2` to have a same type, but I'm not there yet - I'm starting on just getting them to take the same type *as input*.

    module example

    open System

    type CapturedFor<'D, 'T, 'S> = { over : ('D -> 'T seq); expr : ('T -> 'S) }
    type CapturedYield<'S> = { value : 'S }

    type A = { ID : int; Name : string }
    type B = { ID : int; Name : string }
    type Domain =
        abstract member As : A seq
        abstract member Bs : B seq

    type CommandBuilder () =
        member __.For ([<ProjectionParameter>] seq : (Domain -> 'T seq), expr : ('T -> 'S)) = { CapturedFor.over = seq; expr = expr }
        member __.Yield (x : 'S) = { CapturedYield.value = x }

    let stuff (d : Domain) =
        let command = new CommandBuilder()

        let ce1 =
            command {
                for a in d.As do
                yield true
            }

        let ce2 =
            command {
                for b in d.Bs do
                yield false
            }

        let ce3 =
            command {
                for a in (fun f -> f.As) do
                yield false
            }

        let ce4 =
            command {
                let x = d
                for a in x.As do
                yield false
            }

        ignore

**Comment by latkin** [comment]
`[<ProjectionParameter>]` only applies to custom operations (designated with `[<CustomOperation>]`), it is not intended to be used on parameters of standard operations.

**Comment by MrAndMrsK** [comment]
If we can redefine a standard operator's implementation, and if it is the implementation that takes the attribute, then for consistency shouldn't it be honored?

**Comment by latkin** [comment]
Certainly it's understandable that one might expect it to carry over, but as it stands the current behavior is per spec (section 6.3.10, emphasis mine)

> `ProjectionParameterAttribute` indicates that, when a **custom operation** is used in a computation 
expression, a parameter is automatically parameterized by the variable space of the computation 
expression

If you'd like to see the computation expression support expanded to cover this, please open a suggestion at http://fslang.uservoice.com/

**Comment by Gitgiddy** [comment]
OK, I added this as a feature request too.  For clarity, here is a much better illustration:

    type Domain = interface end
    type Projection<'R> = 
        abstract member source : Table<'R>
    and Table<'R> = inherit Projection<'R>
    and Table<'R, 'K> = 
        inherit Table<('R * 'K)>
        abstract member row : 'R
        abstract member key : 'K

    type proj<'R> = Projection<'R>
    type table<'R> = Table<'R>

    type Engine<'D> when 'D :> Domain = 
        abstract member from: 'R table * ('R proj -> 'U) -> 'U
        abstract member where: ('R -> bool) * 'R proj -> 'R proj
        abstract member any: ('R -> bool) * 'R proj -> bool
        abstract member select: ('R -> 'S) * 'R proj -> 'S proj

    type A = { ID : int; Name : string }
    type B = { ID2 : int; Name2 : string }
    type MyDomain =
        inherit Domain
        abstract member As : A table
        abstract member Bs : B table

    type CommandBuilder<'D> when 'D :> Domain () =
        // [<CustomOperation("for")>]  **no effect (?)** 
        member __.For ([<ProjectionParameter>] over : ('D -> 'R table), expr : ('R proj -> _)) =       // [<ProjectionParameter>] is ignored
            (fun (engine : Engine<'D>, domain : 'D) -> engine.from(over(domain), expr))
        member __.Yield x = x

        [<CustomOperation("select")>]
        member __.Select (over : (Engine<'D> * 'D -> 'R proj), [<ProjectionParameter>] mapping : ('R -> _)) = 
            (fun (engine : Engine<'D>, domain : 'D) -> engine.select(mapping, over(engine, domain)))

        [<CustomOperation("where", MaintainsVariableSpace = true)>]
        member __.Where (over : (Engine<'D> * 'D -> 'R proj), [<ProjectionParameter>] byPredicate : ('R -> bool)) = 
            (fun (engine : Engine<'D>, domain : 'D) -> engine.where(byPredicate, over(engine, domain)))

        [<CustomOperation("any", MaintainsVariableSpace = true)>]
        member __.Any (over : (Engine<'D> * 'D -> 'R proj), [<ProjectionParameter>] byPredicate : ('R -> bool)) = 
            (fun (engine : Engine<'D>, domain : 'D) -> engine.any(byPredicate, over(engine, domain)))

        member __.Quote() = ()
        member __.Run(q) = q

    let command = new CommandBuilder<MyDomain>()

    let invariant1 =
        command {
            for a in (fun _d -> _d.As) do  // should be `for a in d.As do`
            any (a.Name = "disallowed value")
        }

    let invariant2 =
        command {
            for b in (fun _d -> _d.Bs) do  // should be `for a in d.Bs do`
            any (b.Name2 = "disallowed value")
        }

    let domainInvariants = [ invariant1; invariant2 ]

**Comment by Gitgiddy** [comment]
OK, I added this as a feature request too. I updated the original post with a much better code sample illustrating the issue.
