### ISSUE TITLE
Ctrl+F doesn't show search results in visible screen

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#3320]
Please provide a succinct description of the issue.

* clone https://github.com/fsprojects/Paket
* ctrl+f for tryGetAllVersionsFromNugetODataWithFilter`

#### Expected behavior

Search results are shown on screen

#### Actual behavior

![image](https://user-images.githubusercontent.com/57396/28057751-52b2f17a-6621-11e7-836c-976b9bc42e65.png)

The line is found but hidden behind the navigation bar so that you need to scroll up. This is really really annoying since it breaks the worflow when searching for things.

#### Known workarounds

scroll up

#### Related information 

Provide any related information 

VS 2017.3 Preview

**Comment by Pilchie** [comment]
@olegtk @JoshVarty - editor issue, right?

**Comment by olegtk** [comment]
@forki, can you please clarify the repro steps, down to details like initial position in the file and whether you type "tryGetAllVersionsFromNugetODataWithFilter" in QuickFind or paste it. Thanks!

**Comment by forki** [comment]
@olegtk it happens all the time.

do the following:

* install F# support (you need the navigation bar)
* clone paket (as above)
* go to RELEASE_NOTES.md in VS
* press Ctrl+F (search in solution)
* paste `tryGetAllVersionsFromNugetODataWithFilter`
* hit the search arrow

VS will find something in `NuGetV2.fs` but you can't see it on the screen since it's behind navigation bar.

**Comment by olegtk** [comment]
Hard to say off hand if it's editor or F#, but we would need to take a first look to determine that. Please file an internal bug for the editor team, @Pilchie.

**Comment by Pilchie** [comment]
Filed https://devdiv.visualstudio.com/DevDiv/_workitems/edit/463409.

**Comment by cartermp** [comment]
This bug was run through VS editor validation in 15.7 and could not be reproduced. @forki please do ping if you see this again.
