### ISSUE TITLE
Error MSB6006: "fsc-proto.exe" exited with code -1073741819.

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3331]
1. Build and install OOS VSIX from https://github.com/Microsoft/visualfsharp/pull/3328
2. Check out https://github.com/Microsoft/visualfsharp/pull/3330
3. Try to build it in VS
4. Result

> E:\github\visualfsharp\Proto\net40\bin\Microsoft.FSharp-proto.targets(224,9): error MSB6006: "fsc-proto.exe" exited with code -1073741819.

**Comment by dsyme** [comment]
Every time?

**Comment by vasily-kirichenko** [comment]
Yes. Then I `git clean -dfx`, `build vs`, `build vs debug` and it stops crashing.  However, I did just the same sequence of commands this morning, so it's not related to super outdated proto compiler. However, I don't know how to reproduce this, it can be closed.

**Comment by dsyme** [comment]
[google](https://www.google.co.uk/search?q=1073741819&rlz=1C1CHBF_en-GBGB744GB744&oq=1073741819&aqs=chrome..69i57j69i61.1863j0j7&sourceid=chrome&ie=UTF-8) mostly says "file system error"...

**Comment by vasily-kirichenko** [comment]
I was wrong, it crashes again. I cannot build VFT at all.

**Comment by vasily-kirichenko** [comment]
hmm

**Comment by vasily-kirichenko** [comment]
It seems to relate to the anti-virus software, solved.
