### ISSUE TITLE
Solution Explorer does not show any content of a .NET Core 2 preview 2 project 

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3333]
```
> dotnet --version
2.0.0-preview2-006502

dotnet new console -n Core1 -lang f#
```
![image](https://user-images.githubusercontent.com/873919/28223647-ef22e08c-68d4-11e7-8b0f-51bd930bbbf5.png)

**Comment by vasily-kirichenko** [comment]
After installing Core 2 preview 3 it loaded the project, but sdks are broken:

![image](https://user-images.githubusercontent.com/873919/28224087-7eb306ea-68d6-11e7-8a1e-17a165246f80.png)

**Comment by cartermp** [comment]
Closing as expected for .NET Core 2.0 Preview 2

I created an issue for the SDK here for your latter screen: https://github.com/dotnet/sdk/issues/1413
