### ISSUE TITLE
Self-built VSIX installs across all VS installs

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3336]
This will result in some inconsistencies, as this VSIX will appear to work fine with 15.2, but will exhibit issues in 15.3, even though those issues have been fixed.  See: https://github.com/Microsoft/visualfsharp/issues/3334

**Comment by realvictorprm** [comment]
@Cartermp anything we can do?

**Comment by cartermp** [comment]
Not sure.  @brettfo would know more.

**Comment by KevinRansom** [comment]
The source.extension.vsixmanifest allows target and pre-req specification.

https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/Vsix/VisualFSharpOpenSource/Source.extension.vsixmanifest

````
  <Installation Experimental="true">
    <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[15.0]" />
  </Installation>
...
  <Prerequisites>
    <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.0,16.0)" DisplayName="Visual Studio core editor" />
  </Prerequisites>
````

We could update these to : 
````
  <Installation Experimental="true">
    <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[15.3]" />
  </Installation>
...
  <Prerequisites>
    <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.3,16.0)" DisplayName="Visual Studio core editor" />
  </Prerequisites>
````

I expect that would work.  @cartermp if you or someone could try it out.

I don't know whether the inconsisties are more irritating than requiring an update for OSS vs ide developers.  I welcome feedback on that.

Kevin

**Comment by cartermp** [comment]
I don't think we'll ever get to this. It's incredibly rare to have two point-releases of the same VS version installed on the same machine. What's far more likely is someone running the Preview and Release channels, and a VSIX built from one toolset will only ever install into the VS that it was built from:

* Using the VS developer command prompt (GA) will install a VSIX into that GA VS only
* Using the VS developer command prompt (Preview) will install a VSIX into the Preview VS only
