### ISSUE TITLE
Error Tooltips are too wide

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3338]
I think we discussed this problem before, I cannot find an issue or PR though. 

I believe this is unacceptable: 

![image](https://user-images.githubusercontent.com/873919/28241680-be9d8d72-69a1-11e7-963a-edb518e75f17.png)

**Comment by vasily-kirichenko** [comment]
@majocha I think you had ideas or even a prototype that format tooltip text so that it's not wider that some predefined value. Didn't you?

**Comment by vasily-kirichenko** [comment]
Rider formats it better:

![image](https://user-images.githubusercontent.com/873919/28241725-6a307f1e-69a2-11e7-9539-7074013a4702.png)

**Comment by majocha** [comment]
@vasily-kirichenko I believe the fix I did some time ago is already merged to master, maybe it didn't make it to Preview.

**Comment by vasily-kirichenko** [comment]
XML Doc comments are formatted properly in both 15.2 + nightly and 15.3 preview 4:

![image](https://user-images.githubusercontent.com/873919/28241913-3e3fe5b6-69a7-11e7-88ff-21ce58635e59.png)

But the error message are not in either.

**Comment by majocha** [comment]
@vasily-kirichenko Now I remember better. I think we have no control over error messages formatting.

The IDE constructs the tooltip by stacking content elements provided by various services. We can format only what we provide and the error message part is created by Visual Studio. I see no straightforward way around this ( would inserting linebreaks into the error message do? ) and frankly this should be handled by the platform.

**Comment by cartermp** [comment]
@Pilchie Is this something that can be done in Roslyn perhaps?

**Comment by Pilchie** [comment]
This is actually one of Roslyn's oldest unaddressed issues :( https://github.com/dotnet/roslyn/issues/5.  Though, that issue isn't specific to errors.  I wonder if we could do something better with just plain error message wrapping.

@cyrusnajmabadi, @rchande, any ideas?

**Comment by realvictorprm** [comment]
can we do something about this @Pilchie ?

**Comment by Pilchie** [comment]
@realvictorprm - you can submit a PR to Roslyn to address it...

**Comment by realvictorprm** [comment]
Thanks @pilchie. Sounded like it's something problematic which can't be addressed that fast.

**Comment by vasily-kirichenko** [comment]
@realvictorprm so you have tried and failed or how you have come to the conclusion that it's problematic to make a PR to the Roslyn repo?

**Comment by cartermp** [comment]
Closing this in favor of https://github.com/dotnet/roslyn/issues/5, at least unless we can find a way to control this ourselves
