### ISSUE TITLE
Type providers are not resolved when using FSharp.Core 4.1.17 and FCS

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#3342]
I'm trying to use FCS built from this repo and can't get some type providers working with FSharp.Core 4.1.17 (net45) loaded at runtime. Getting FS3005 warning ("Referenced assembly '%s' has assembly level attribute '%s' but no public type provider classes were found") and unresolved symbol errors. When using 4.4.0.0 from GAC type providers work properly. 
<img width="281" alt="screen shot 2017-07-17 at 16 16 47" src="https://user-images.githubusercontent.com/3923587/28269621-63484168-6b0b-11e7-9b68-dc08844f3b4d.png">

**Comment by auduchinok** [comment]
Got it working with FSharp.Core 4.1.17 targeting net40. Previously tried 4.1.17 targeting net45 and the build from visualfsharp repo (built in fcs task).

**Comment by dsyme** [comment]
@auduchinok Could you add a step-by-step repro please? thanks

**Comment by auduchinok** [comment]
@dsyme I'd like to provide a repro but I cannot reproduce it anymore. Currently I'm using FSharp.Core 4.1.18 (net45) with FCS from master and it seems to work fine in projects I had came across to this problem.
I'm closing the issue and will reopen in case it reproduced again.

**Comment by auduchinok** [comment]
I previously tried it using `bindingRedirect` to FSharp.Core 4.1.0.0, but using it in runtime is not feasible in our case, so I'm trying to reference the version we're shipping.
I can reproduce this bug when changing the FSharp.Core reference in FCS project like this: 
```
<Reference Include="FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
  <HintPath>..\packages\FSharp.Core.4.1.18\lib\net45\FSharp.Core.dll</HintPath>
  <Private>false</Private>
</Reference>
```

**Comment by dsyme** [comment]
@auduchinok I think we need a step-by-step repro for this.  Which tool is ultimately executing FSharp.Compiler.Service.dll?  (e.g. fsc.exe, fsi.exe, devenv.exe, ...)  All such tools need a binding redirect to the latest FSharp.Core.dll if they are to load type providers

**Comment by auduchinok** [comment]
@dsyme Thank you for the tip about redirecting, we've managed to use a binding redirect to FSharp.Core that we ship for the tool executing FSharp.Compiler.Service.dll (JetBrains.ReSharper.Host64.exe).
