### ISSUE TITLE
VS2017 doesn't save project check cache size unless user clicks off of textbox

### ISSUE THREAD

**Issue by NatElkins** [Microsoft/visualfsharp#3351]
#### Repro steps

1. Open up VS2017 with VF#T 15.4.1.17071806
2. Open up Tools -> Options -> Text Editor -> F# -> Performance
3. Change project check cache size, and then without changing focus click the OK button.
4. Open up Tools -> Options -> Text Editor -> F# -> Performance
5. See that the project check cache size is unchanged.

![project_check_cache_size](https://user-images.githubusercontent.com/1795462/28375434-798b4eaa-6c75-11e7-971c-0a9505a9ea27.gif)

#### Expected behavior

It should save the value.

#### Actual behavior

It doesn't save the value.

#### Known workarounds

Move focus from the textbox before clicking OK.

#### Related information 

This doesn't happen on other boxes under the same option tree.  For example, in Text Editor -> F# -> Tabs, you can keep focus on Tab Size and click OK and the change will be saved.

VS2017 15.2 (26430.16) Release
VF#T 15.4.1.17071806

**Comment by JohanLarsson** [comment]
Weird, the `TextBox` should lose focus when the button is clicked. Binding with `UpdateSourceTrigger=PropertyChanged` is one solution but it will mess a bit with validation.

**Comment by vasily-kirichenko** [comment]
Fixed via https://github.com/Microsoft/visualfsharp/pull/3353
