### ISSUE TITLE
ngen failed to compile FSharp.Compiler.Private.dll

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3355]
> Error compiling ...\packages\FSharp.Compiler.Tools\tools\FSharp.Compiler.Private.dll: Invalid access to memory location. (Exception from HRESULT: 0x800703E6)
1>Uninstalling assembly e:\hg\klsrl.core\packages\FSharp.Compiler.Tools\tools\FSharp.Compiler.Private.dll because of an error during compilation: Invalid access to memory location. (Exception from HRESULT: 0x800703E6)
Invalid access to memory location. (Exception from HRESULT: 0x800703E6)

**Comment by dsyme** [comment]
Repeatable?

**Comment by vasily-kirichenko** [comment]
Yes.

**Comment by vasily-kirichenko** [comment]
I'll try at home, maybe it's the antivirus again.

**Comment by vasily-kirichenko** [comment]
Everything is OK at home.
