### ISSUE TITLE
Consider using a "git flow release model"

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#3368]
https://github.com/Microsoft/visualfsharp/pull/3367 shows that the current release of FSharp.Core contains a regression, but it's hard to proof that since it's already fixed in master.

If there would be a hotfix branch then we could send a PR against that branch and CI would actually check the right merge.

Adding a hotfix branch would also make it easier for maintainers to release a hotfix with just the commits that are needed.

**Comment by dsyme** [comment]
@forki I can create this for you, but what would the head of "hotfix" be?  Also,  perhaps a better branch name would be "FSharp.Core 4.2.1" - we aren't going to prepare a specific hotfix for this, since the next release of FSharp.Core nuget package can push the fix

**Comment by forki** [comment]
> FSharp.Core 4.2.1

that's more a git tag for me.

What I'm looking for is a branch that always points to the the last release (+ very few hotfix PRs on top) and which ready for release in case of emergency.

**Comment by dsyme** [comment]
@forki OK.  I think that tag would be different for various outputs of this repo, i.e.
* the F# compiler
* the FSharp.Core nuget package
* the Visual F# Tools
* the FSharp.Compiler.Service package (eventually)

I suppose we could have branches "latest-fsharp-core-package" etc. that you can push PRs to for the purposes of testing. I suspect they would not be kept up-to-date, but you could always push a PR to bring them up-to-date.  I don't think releases would get made from them, but that's not my call

We could equally just have a few branches "test1", "test2" etc. which would serve much the same purpose of allowing you to activate CI, which is what you really want I think?

**Comment by dsyme** [comment]
@forki If you're brave you could probably just create a PR with a massive number of commits to a branch such as https://github.com/Microsoft/visualfsharp/tree/vs2017-rtm, bringing it up to the base you want, and adding the testing code which you want to prove fails?

**Comment by forki** [comment]
we already showed that it fails (locally and with paket in real world scenario).

this is more a question if we want to move over to something like git flow release model.

**Comment by dsyme** [comment]
> this is more a question if we want to move over to something like git flow release model.

I think this would only apply to the "FSharp.Core" nuget package output of this repo, since all the other outputs are pushed out via other release channels.

However I'm pretty sure that over time the production of that package will be changed to be more in line with other Microsoft processes, rather than using some specific process here

**Comment by dsyme** [comment]
Closing old discussion
