### ISSUE TITLE
Error highlighting is not updated until project build is started

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3371]
![1](https://user-images.githubusercontent.com/873919/28536632-e8c812be-70b0-11e7-9f90-ce64c4c518ee.gif)

**Comment by dsyme** [comment]
@vasily-kirichenko I've not seen this problem, at least not like this

What is your "Error List" setting - show errors from "Build", "Intellisense" or "Build + Intellisense"?

Also is this 15.2 + master?

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it anymore. It's 15.2 + master, Error List mode is "Intellisense". The error squiggle updates quite fast.

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it on 15.3 preview 5 + VFT nightly preview either.
