### ISSUE TITLE
[From VSTS] Preview 4 will crash if loading F# and C# .NET Core projects where the F# project references a C# project

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3373]
1. Download this repro solution: [9140-crashproblemsimplesolution.zip](https://github.com/Microsoft/visualfsharp/files/1170746/9140-crashproblemsimplesolution.zip)
2. Open it in VS 2017 Update 3 preview 4

**Expected:** No crash.
**Actual:** VS will crash.

**Workaround:** There is none.

Note: the above C# projects do set `IOperation` to true and use the preview FXCop analyzer.  That does seem unrelated, as commenting out either will still cause a crash.

**Comment by cartermp** [comment]
Not sure if this is related to the root cause of #3260 or not.

**Comment by Pilchie** [comment]
@jasonmalinowski just fixed this.  See https://github.com/dotnet/roslyn/pull/21035 and https://github.com/dotnet/roslyn/pull/21023

**Comment by Pilchie** [comment]
Not the root cause of #3260.

**Comment by cartermp** [comment]
Awesome.  Thanks!
