### ISSUE TITLE
Find All References does not work across projects

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3381]
![image](https://user-images.githubusercontent.com/873919/28580375-f8bb2820-7167-11e7-9fa4-fb985b0825af.png)

**Comment by cartermp** [comment]
I think this is a dupe of #3033 unless something is different.

**Comment by vasily-kirichenko** [comment]
Same on 15.3 preview 5 + VFT nightly preview.
