### ISSUE TITLE
FSharp.sln from master does not load correctly: Unrecognized Guid format.

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#3393]
git checkout 5573f6f8005add122df07b8daa0fe2fe41b02da8
git clean -x -d -f
build debug
open FSharp.sln

![image](https://user-images.githubusercontent.com/4236651/28670526-6d234464-72d9-11e7-9693-6094e213f195.png)

![image](https://user-images.githubusercontent.com/4236651/28670538-80454b0a-72d9-11e7-952b-d61f6a1c81ea.png)

__Edit: same issue in VS15.2__

**Comment by KevinRansom** [comment]
Hmm that's weird because it has been working for me, I guess we are going to have to ship my laptop to every F# user, perhaps a signup sheet :-)

**Comment by saul** [comment]
This is also happening for me on a fresh checkout (on two separate machines). I can't build the VSIX in VS because of this.

**Comment by dsyme** [comment]
@saul ``FSharp.sln`` is not used in building the VSIX, only ``VisualFSharp.sln`` is

**Comment by saul** [comment]
I am using `VisualFSharp.sln` - that project is in there and is required to build.

**Comment by dsyme** [comment]
@saul Odd - I'm not getting this "Unrecognized Guid format"

**Comment by dsyme** [comment]
@saul Actually, yes I am.  Just for that one project (FSharp.Compiler.Interactive.Settings.dll)
