### ISSUE TITLE
WarningsNotAsErrors tag in project file is not implemented

### ISSUE THREAD

**Issue by pmbanka** [Microsoft/visualfsharp#3395]
Scenario: I want to treat all warnings as errors EXCEPT some specific ones. This is possible in when calling F# compiler directly (https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-options), but there is no way to specify this option in fsproj file.

Note that it is possible in C#: https://stackoverflow.com/a/468166/1108916

I found that there is `WarningsAsErrors` setting, but `WarningsNotAsErrors` is missing: https://github.com/Microsoft/visualfsharp/blob/f6049d54d464874559765ced35276978656a5e52/src/fsharp/FSharp.Build/Fsc.fsi#L62 this is probably where it should be implemented.

The option is also missing from the VS UI.

Apologies if this is not a correct place to report this.

**Comment by KevinRansom** [comment]
@on banks agreed, this would be a food addition to that build task.

**Comment by kasper3** [comment]
I sent a pull request for it. Please review. Thanks!
