### ISSUE TITLE
The editor does not honor/render <para> anymore in XML doc comments

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3396]
Not a big bug of sorts, but a pity to all my neatly formatted comments...

In VS2015, `<para>` is honored:

![image](https://user-images.githubusercontent.com/16015770/28686039-31e786c2-730a-11e7-86f4-86b7316de781.png)

In VS2017, up until P6, it is not:

![image](https://user-images.githubusercontent.com/16015770/28686057-41ae642c-730a-11e7-8e27-20d962fe745f.png)

Seen with F# 4.4.0.0 and with F# 4.4.1.0.

**Comment by cartermp** [comment]
Closing in favor of #3213
