### ISSUE TITLE
F# code windows partially locked up for editing after reopening the project in Visual Studio 2017

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3397]
I was hesitant reporting this, as I was certain it'd be caused by some extension or plugin. However, after disabling everything that could be disabled, restarting etc, the issue persisted.

If the first file that is remembered from a solution is an F# code file, cursor keys, backspace keys and others don't work. 

### Repro steps

**It happens always, on every project open**, since Visual Studio 2017 Preview 4 through Preview 6. To repro:

* Open an F# solution
* Make sure to close Visual Studio with the editor open on an F# code file (*.fs)
* Close / reopen Visual Studio with this project
* Result: many editor or cursor keys don't work.

It doesn't matter whether you open your solution through folder view, direct open, through the open menu.

Note that sometimes the lockup behavior is not immediate, but after a couple of keystrokes.

### Expected behavior

All normal keys, like cursor keys and backspace, should just work.

### Actual behavior

I noticed at least the following strange behavior:

* Up, Down, Right, Left keys do nothing
* Backspace key does nothing
* Clicking in the file on a different location, or changing focus to a different editor and back, has no effect
* Only the first opened file has this problem, other open tabs work normally (though sometimes, after a while, these also locked up)
* Delete key sometimes works, sometimes doesn't
* C# code windows do not exhibit this behavior
* Hitting Home or End brings you to the first or last tab, instead end/begin of line (which suggests the focus is wrong, but clicking around doesn't change this)

Letter and digit keys work normally. Only way to delete text is by selecting and then rightclicking it.

### Known workarounds

Close all files and reopen them. If you close only one file, the locking-up behavior propagates to the next.

### Related information 

* OS: Windows 7, latest service packs and fixes
* Visual Studio 2017, Preview 4, Preview 5 and Preview 6 (at least)
* Using Roslyn, old .NET versions, newest versions does not make a difference
* Tested with both F# 4.4.0.0 and F# 4.4.1.0
* Same project opened in Visual Studio 2015 behaves normally

PS: if this is not the right place for reporting this, I'll be happy to move the issue to another repo.

**Comment by vasily-kirichenko** [comment]
https://github.com/Microsoft/visualfsharp/issues/3267

**Comment by cartermp** [comment]
Closing in favor of #3267.  We're currently working on this.

**Comment by abelbraaksma** [comment]
Thanks, @cartermp, @vasily-kirichenko, I searched, but apparently did a poor job at it. I was most afraid it was one of those "it happens only with me" scenarios, good to know it got your attention already 💯 .

**Comment by abelbraaksma** [comment]
For others googling and getting here: this bug was resolved, since 15.3.1.0 Preview 1 it doesn't seem to appear anymore (though a few users seem to have seen a variant of the same bug, see related thread #3267).
