### ISSUE TITLE
Error in pass2 for type FSharp.DataFrame.FSharpFrameExtensions, error: duplicate entry 'Frame`2.GroupRowsBy' in method table

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#34]
[from fsbugs] 

Simplified repro:

```fsharp
type Frame = 
  class 
  end
module X =
  type Frame with
    member frame.GroupRowsBy(key) = ()
    member frame.GroupRowsBy(key) = ()
```
Issue: Signatures in extrinsic type extensions are not validated for uniqueness.

**Comment by KevinRansom** [comment]
Hey Don ... is there any progress on this or should I assign this back to unassigned, so that someone else can take a crack at it?

**Comment by dsyme** [comment]
I've cleared the assignee....
