### ISSUE TITLE
"an item with the same key has already been opened" is shown when opening an F# project in Visual Studio 2017

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3411]
Whenever you open an F# source file from an F# project in Visual Studio 2017 for the first time, and sometimes later again, you will get a static dialog popup with:

> an item with the same key has already been opened

![image](https://user-images.githubusercontent.com/16015770/28882000-2ebfa6a6-77aa-11e7-897b-76b94ff39150.png)

### Repro steps

Not sure, but I wasn't the first to notice (see for instance this comment: https://github.com/Microsoft/visualfsharp/issues/3267#issuecomment-311551337). But this warrants its own issue, as it keeps happening with most recent previews.

I have one project where it reproduces after I remove all NuGet packages from disk, but only for one project in the solution, in this case one using UnQuote, which compiled previously, but in the editor and from MsBuild command prompt, it didn't load the library at all.

Not sure the one has to do with the other. I see the duplicate-key popup happen on any project, whether or not it was saved through Visual Studio 2017 before or not. The only common denominator seems to be that:

* It happens whenever you open a source file for the first time on that computer with that version of VS2017
* It happens with F# projects only 
* It seems to happen occasionally after the first time, or after removing all NuGet packages (but again, this may not be related)

### Expected behavior

No error dialogbox.

### Actual behavior

The error as shown above.

### Known workarounds

I don't know of any workarounds (apart from clicking the messagebox away, you can continue working).

### Related information 

* Seen on Windows 10 Creative Ed and Windows 7 latest SP
* Visual Studio, at least since Preview 3 through Preview 7 (15.3.0 Preview 7.0)
* F# 4.0, 4.1 (or internally, version craziness: Core dlls having 4.4.0.0 or 4.4.1.0)

**Comment by cartermp** [comment]
This should be fixed here: https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L465

The only way to test this out at the moment is to use a self-built install of the Visual F# tools in VS 2017 Update 3.  You can do that by following the instructions in `DevGuide.md` to get prerequisites, then running `build vs release`.  If you run the VISX under `bin/release/net40`, then it will replace your current F# tools with the latest master.  I'll re-open this if you can still reproduce it.

**Comment by abelbraaksma** [comment]
@cartermp: I haven't seen this for a while now (probably since 15.3 Preview 6 or so) and I for sure haven't seen it with 15.3.1.0 Preview 1 and today's nightly, so I consider this confirmed fixed unless it resurfaces.

**Comment by cartermp** [comment]
@abelbraaksma Good to hear!
