### ISSUE TITLE
Could not enable GCServer for F# Interactive 

### ISSUE THREAD

**Issue by CodEFouR** [Microsoft/visualfsharp#3414]
Changing fsi.exe.config and fsiAnyCPU.exe.config to enable GCServer doesn't work for F# Interactive in VS2017 with Visual F# Tools night build.

To reproduce:

1. Open fsi.exe.config and fsiAnyCPU.exe.config (with admin) and add the following
```
    <gcConcurrent enabled="true" />
    <gcServer enabled="true" />
```
2. Open VS2017 and open F# Interactive, and verify:
```
System.Runtime.GCSettings.IsServerGC;;
```
3. The result is `false` no matter how fsi.exe.config and fsiAnyCPU.exe.config is changed.  
However open fsi.exe in command line, it shows true for GCServer.

#### Expected behavior

GCServer should be enabled.

#### Actual behavior
GCServer is not enabled.

#### Known workarounds

No workaround found.

#### Related information 

* Windows 10 with Creators Update
* .NET Framework 4.6 and F# 4.1
* Visual Studio 2017 Profession with Visual F# Tools nightly build

**Comment by dsyme** [comment]
> Changing fsi.exe.config and fsiAnyCPU.exe.config to enable GCServer doesn't work for F# Interactive in VS2017 with Visual F# Tools night build.


Which fsi.exe.config are you changing?  If you are running the nightly build, then AFAIK Visual F# tools run the fsi.exe from under a path something like

    C:\Users\dsyme\AppData\Local\Microsoft\VisualStudio\15.0_088a6328\Extensions\faqeurj5.za1

**Comment by CodEFouR** [comment]
I didn't know that's the one. Thanks a lot I confirm it works.
