### ISSUE TITLE
FS0193 error when specifying sequential struct layout of a type

### ISSUE THREAD

**Issue by kasperhj** [Microsoft/visualfsharp#342]
While translating some C# code into F# I noticed some unexpected behavior with structlayout.

Having
```
type MyType =
    struct
        val a: int
    end
```
is fine, but having
```
open System.Runtime.InteropServices
[<type:StructLayout(LayoutKind.Sequential, Pack=1)>]
type LayoutType =
    struct
        val a: int
    end
```
results in an error:
> error FS0193: internal error: Could not load type 'LayoutType' from assembly 'FSI-ASSEMBLY,  Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because field 'a@' was not given an explicit  offset.

Setting `Pack=0` and everything is fine.

I tried this out in VS2013 and VS2015 CTP 6, and the results are identical.

/@kasperhj

**Comment by KevinRansom** [comment]
I can repro this too.  According to : https://msdn.microsoft.com/en-us/library/vstudio/system.runtime.interopservices.structlayoutattribute.pack(v=vs.100).aspx

1 is a valid value for pack, 
setting it to 1 or any other non zero that I tried for that matter results in:  
```
error FS0193: internal error: Could not load type 'LayoutType' from assembly 'FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because field 'a@' was not given an explicit offset.
```

**Comment by asik** [comment]
Yes I had noticed this a while ago: http://stackoverflow.com/questions/24587684/structlayout-limitation-in-f-interactive
