### ISSUE TITLE
No tooltip / symbol highlighting / etc. for operators that ends with dot

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3424]

**Comment by cartermp** [comment]
Furthermore, completion will invoke on the `.`:

![custom-operator-ends-with-dot-completion](https://user-images.githubusercontent.com/6309070/29082897-dcc4a6dc-7c1b-11e7-8a9a-d714b7782bb9.PNG)

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it in 15.7.2

![image](https://user-images.githubusercontent.com/873919/40783095-15580112-64ea-11e8-8493-eb39a9eeab02.png)
