### ISSUE TITLE
Printf env finalizers

### ISSUE THREAD

**Issue by ncave** [Microsoft/visualfsharp#3432]
Perhaps (and most probably) I'm missing something here, but why is [env.Finalize()](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/printf.fs#L228) called directly instead of through IDisposable and use statement (like [this](https://blogs.msdn.microsoft.com/mcsuksoldev/2011/06/05/f-class-library-template/))? Seems to contradict [this guideline](https://msdn.microsoft.com/en-us/library/system.object.finalize%28v=vs.110%29.aspx#Notes):

> Every implementation of Finalize in a derived type must call its base type's implementation of Finalize. This is the only case in which application code is allowed to call Finalize.

**Comment by KevinRansom** [comment]
Probably because the type is generated by the compiler, it didn't need all of that fancy dispose pattern implemented, so @v2m  made the call that simplest was best, and perhaps easier to generate.

That's just a theory of course.

**Comment by vladima** [comment]
this is a case of bad choice of the name :) - `Finalize` here is not related to finalizer

**Comment by dsyme** [comment]
Yep, best to rename that one :)
