### ISSUE TITLE
Wrong error highlighting in scripts

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3438]
![image](https://user-images.githubusercontent.com/873919/29328738-3f6245a2-81fc-11e7-8a5f-278bfc36d3e0.png)

That's a script in a new console application targeting .NET 4.7.

**Comment by vasily-kirichenko** [comment]
![1](https://user-images.githubusercontent.com/873919/29328833-879dd976-81fc-11e7-8098-239d4ddcb7e5.gif)

**Comment by cartermp** [comment]
I can't repro this on 15.4.1.17081501:

![no-repro](https://user-images.githubusercontent.com/6309070/29331463-5ab0801c-81b1-11e7-8a3c-e35ebdc05d1c.PNG)

**Comment by cartermp** [comment]
I can repro this after typing gibberish in the path, pasting the script code, then re-typing the proper path:

![repro-sorta](https://user-images.githubusercontent.com/6309070/29332877-721f4238-81b6-11e7-9013-c636de10ca3c.PNG)


Could this be related to #1944 or #1808?

**Comment by dsyme** [comment]
Yes, it could be related to #1808.

**Comment by dsyme** [comment]
I'm trying to repro this, but can't do it yet.   @vasily-kirichenko or @cartermp could you write out step-by-step repro steps for me please?

There _is_ a variation of https://github.com/Microsoft/visualfsharp/issues/1808 via these steps:

1. Create a script with ``#r "nada.dll"`` and some code, where that file doesn't exist. Red-squigglies appear
2. Create the DLL in the background.  

Expected: The red-squigglies should disappear automatically, without any movement of the mouse or editing of the file or anything else that triggers an FCS request about the script. At least that's what happened in VS2010-15.

Actual: the red-squigglies hang around until you actually interact with the script, e.g. a mouse hover. 

It may be that we can register the proper metadata dependencies for the Roslyn Project for the script (though I'm not sure we actually create one of those yet).  And then Roslyn's re-analysis thread will look after reanalyzing when the files appear/disappear.  

@Pilchie a question - do you know if Roslyn is "reactive" in this way, listening to changes in the referenced DLL files and re-scheduling error analysis of the files?  Or is our language service responsible for listening to changes in those files?

**Comment by cartermp** [comment]
I believe that this is indeed that variation.  What I encountered was exactly what you described there.
