### ISSUE TITLE
FSharp.Core packaged incorrectly

### ISSUE THREAD

**Issue by matthid** [Microsoft/visualfsharp#3451]
See https://github.com/fsharp/fsharp/issues/741
and https://github.com/fsprojects/Paket/issues/2378

Basically FSharp.Core needs an empty dependency group for net45.

/cc @enricosada

**Comment by cartermp** [comment]
Is this for FSharp.Core 4.1.x?  @KevinRansom was telling me the other day that he wanted to push an update to that package because of the net47 issue.

**Comment by matthid** [comment]
Yes there was an issue with `System.ValueType` that has been resolved (well depends on how you look at it). But it basically is still not correct. Let me explain how NuGet works:

Consider you have a project for net47. NuGet [tells us](http://nugettoolsdev.azurewebsites.net/4.3.0-preview4/get-nearest-framework?project=net47&package=netstandard16%0D%0Anet45) that from the two binaries (net45 and netstandard16) it will pick the net45 one.
However from the metadata it will add the netstandard16 dependencies (as it is the best matching dependency group).

To synchronize, `FSharp.Core` needs an "emtpy" dependency group for net45.

In general a NuGet package should have a dependency group for each contained binary with the correct dependencies for the given binary (=framework in most cases).


The problem is that NuGet and paket will add all the dependencies for netstandard16 while they are not required. The only reason this wasn't noticed as of yet is because netstandard16 is not compatible with <net461.

This brings us back to the discussion about netstandard20 and the reason why @enricosada and myself are telling you we need to include a netstandard20 binary into the package (with an appropriate dependency group obviously). Technically you can use netstandard16 for everything, but the user-experience is much better when you can get rid of all the netstandard packages.
Please re-consider this decision and don't let us write an RCF for this.

**Comment by dsyme** [comment]
@matthid Could you submit a PR(s) for the change(s) you want? The FSharp.Core authoring is fully open source

**Comment by dsyme** [comment]
Specifically https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core.nuget/FSharp.Core.4.2.xxx.nuspec

**Comment by matthid** [comment]
https://github.com/Microsoft/visualfsharp/pull/3452

**Comment by matthid** [comment]
See also https://github.com/Microsoft/visualfsharp/pull/3454. Obviously I'm not investing any time in rewriting the build system (the batch scripts) as it probably wouldn't get accepted anyway.

**Comment by dsyme** [comment]
@matthid I'll close this since #3452 has been accepted - thanks!
