### ISSUE TITLE
Triple slash comments (xml comments) on modules also take the lines from before previous statement

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3457]
If you have an `open` statement  (or essentially any statement that is not a declaration or let binding) that is preceded by XML documentation comments or simple syntax triple-slash comments, it will become part of the documentation of the next `module`  (or `type`, `let`  etc) declaration:

From the Tutorial project:

![image](https://user-images.githubusercontent.com/16015770/29432692-d5f6cece-839c-11e7-8810-f19a6db8b7c2.png)

## Repro steps

Create a new Tutorial project, open Tutorial.fsx. Or copy this:

```
/// This is a pipe!
open System

/// This is not a pipe!
module Test =
    ()
```

Or copy this:

```
module Test =

    /// Hello world
    15 = 2 |> ignore

    /// Let there be X
    let x = 12

    ()
```

## Expected behavior

It should look like this:

![image](https://user-images.githubusercontent.com/16015770/29432883-7cd2c3ce-839d-11e7-8188-9ed203d87012.png)

Or this (2nd example):

![image](https://user-images.githubusercontent.com/16015770/29433167-6280490a-839e-11e7-82c4-103e977bf6f1.png)

## Actual behavior

But it looks like this;

![image](https://user-images.githubusercontent.com/16015770/29432776-2662cc8c-839d-11e7-8c06-4445b29e9f8d.png)

Or this (2nd example):

![image](https://user-images.githubusercontent.com/16015770/29433072-1ba737d2-839e-11e7-9a5c-5ad9e87169eb.png)

## Known workarounds

Don't use triple-slash comments before statements.

## Related information 

I would understand this to be considered low prio, though essentially the triple-slash documentation parser should really only take into account what precedes directly before the declaration. A statement should cancel that parsing out.

This becomes more apparent if you create documentation from your sources. The Tutorial project template is therefore a good example how this should *not* work, and would compile into erroneous documentation.

Seen on: 
* Visual Studio 2015 Upd 3
* Visual Studio 2017, until at least Preview 17.1

**Comment by matthid** [comment]
I'm not sure but we might even (miss-)use this "feature" in FSharp.Formatting. Maybe @tpetricek can recall if this is true.

If this is true a fix for this probably should contain a way to retrieve comments from namespaces. Otherwise I'm positive that this needs to be fixed :)

**Comment by abelbraaksma** [comment]
@matthid, I really think this is a bug, as you can see from the first screenshot, it also spans between double-slash and triple-slash comments. A double-slash comment should break the triple-slash documentation, I'd say (and I believe I have seen in other parts of my code that a double-slash stops the processing, but that may have been in an earlier version of VS or F#).

More importantly (and I failed to mention that above), when you need to switch to the more versatile XML comments, this "feature" (if considered so) can lead to potentially hard to find documentation bugs, because it will take the last XML comment it finds looking backward from the current declaration:

![image](https://user-images.githubusercontent.com/16015770/29434423-3a2e0e92-83a3-11e7-88ea-b8d137ff0d01.png)

**Comment by cartermp** [comment]
Yeah, this definitely seems like a bug, and it's the same in VS 2017 as well.

**Comment by matthid** [comment]
> @matthid, I really think this is a bug, as you can see from the first screenshot, it also spans between double-slash and triple-slash comments. 

Yep I'm definitely not arguing against it. It is a bug and needs to be fixed. Was just pointing out that this might break "FSharp.Formatting" (or not that's why I asked @tpetricek if he can recall).

**Comment by matthid** [comment]
Additionally I'd love to see that XML docs get some love again ;)

**Comment by dsyme** [comment]
Thanks for the simple and clear repro steps
