### ISSUE TITLE
QuickInfo not triggered for everything in VF#

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3459]
15.3 RTW.

So far, it seems like anything in FSharp.Core or methods in `FSharpCheckFileResults` don't show:

![no-hover-1](https://user-images.githubusercontent.com/6309070/29439193-e3e41b08-8370-11e7-9f95-c7c4c044c1d6.gif)

I can't reproduce this in Paket.sln.

**Comment by majocha** [comment]
![image](https://user-images.githubusercontent.com/1760221/29489105-1d9b79a0-8519-11e7-80bf-93950efe983d.png)
Works for me. It just initially takes much longer to get QI for those symbols than the local ones.
Try `Ctrl-K,I ` on a symbol just after opening the solution and just wait for it. QuickInfo will show up eventually.

**Comment by abelbraaksma** [comment]
> It just initially takes much longer to get QI for those symbols than the local ones.
I've seen this behavior too, but sometimes "much longer" can be as long as an hour or so, which is unworkable (possibly only for big projects, I have not checked it, and sometimes it is fast, sometimes slow, I can't seem to pinpoint this to a particular situation).

**Comment by cartermp** [comment]
@majocha Interesting.  I suppose this will have to be profiled, but it doesn't seem to make much sense to me given that other stuff that's about the same level of "depth" does trigger QuickInfo.  I don't recall this being a problem in the 15.2 timeframe, but that's not really concrete.

**Comment by abelbraaksma** [comment]
> Is this something you might be able to share with a reduced reproduction?

@cartermp: that'll be difficult. Whenever I try to repro performance-related issues in a small-enough prj, they always disappear. I see it in my current F# project mainly, for which some solution files have 10+ projects and each prj some 50k+ lines. Very good for testing performance, I'm sure, but I can't share the whole project unless in a private conversation (and NDA). And even then, it doesn't happen always.

If you can give me pointers of something I can log, or debug into, I might try that the next time this happens (today I saw delays only up to several minutes, not that long compared to some earlier experiences).

Interestingly: after a recompile I often see the XML (or simple `///`) comments disappear from QuickInfo tips, only to reappear much later, or not at all, or to reappear after reopening the solution.

**Comment by dsyme** [comment]
@abelbraaksma I'd encourage you to create an artificial massive solution that also demonstrates the problem - see for example the ones under tests\projects\stress.  Having a range of such solutions in our test suite is invaluable, even for manual testing.

**Comment by cartermp** [comment]
I cannot reproduce this on 15.3.3 + Nightlies.  Although there's still an issue here, the specific issue of not getting QuickInfo for the things mentioned above is no longer the case anymore (and on the same machine).
