### ISSUE TITLE
Go to Definition via f12 or menu fails, but QuickInfo Go to Definition does not

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3460]
15.3 RTW, Paket.sln.

These are symbols in the same project.

![gtd-fails](https://user-images.githubusercontent.com/6309070/29439285-8979b44c-8371-11e7-97ff-5304b5c2f99a.gif)

**Comment by cartermp** [comment]
Interestingly, it works in a debug hive...

**Comment by cartermp** [comment]
I cannot reproduce this anymore with 15.3.3 + Nightlies.

**Comment by abelbraaksma** [comment]
This may be related: #3544 (and still open).

**Comment by cartermp** [comment]
I'm not sure it is - #3544 looks like we're not accounting for mutually referential types correctly.  This was an outright failure for any symbol.

**Comment by abelbraaksma** [comment]
@cartermp, ok, other bug then, tx ;).
