### ISSUE TITLE
Error highlighting does not update at all

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3466]
![1](https://user-images.githubusercontent.com/873919/29467167-254df49c-8448-11e7-88be-b9203362809b.gif)

![image](https://user-images.githubusercontent.com/873919/29467189-34b8e450-8448-11e7-9df4-5be8e4841144.png)

**Comment by dsyme** [comment]
Are you showing errors from "Build", "Intellisense" or "Build + Intellisense"?

thx

**Comment by vasily-kirichenko** [comment]
"Build + Intellisense".

**Comment by dsyme** [comment]
@vasily-kirichenko Had you done a build?

**Comment by vasily-kirichenko** [comment]
Yes, I did a build from within VS.

I confirm it's fixed in master 👍

**Comment by dsyme** [comment]
Fabuloso
