### ISSUE TITLE
Debugger does not show value of an argument if its name is different in signature and impl files

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3467]
![1](https://user-images.githubusercontent.com/873919/29469391-af90bc68-8450-11e7-9a54-510a8c75d6f2.gif)

**Comment by dsyme** [comment]
Hmmm.  the signature uses name "lineText" and that has been used in the IL

We should give a warning when signature name doesn't match implementation name

**Comment by dsyme** [comment]
https://github.com/Microsoft/visualfsharp/blob/ba6dff806dcd47177a3b8547d55d317ca5471089/src/fsharp/vs/service.fsi#L147

**Comment by vasily-kirichenko** [comment]
Wow! Interesting. 👍 for warning.

**Comment by dsyme** [comment]
Closing as the warning implemented in the above PR and issue #3539 covers this
