### ISSUE TITLE
Implicit class constructor with a single obj argument could be called without argument which will pass null as argument

### ISSUE THREAD

**Issue by zpodlovics** [Microsoft/visualfsharp#347]
Hi,

As far as I know the FSharp type checker should not allow calling the (implicit) class constructor without properly typed arguments. However implicit class constructor with a single obj argument could be called without argument which will pass null as argument.

```
[<Class>]
type T1(obj1: obj) =
  let obj1=obj1
  member this.Obj1
    with get() = obj1
 
let x1 = T1(new System.Object())
let x2 = T1()
 
printfn "x1.Obj1: %A" x1.Obj1
printfn "x2.Obj1: %A" x2.Obj1
```

The example are available at:
https://gist.github.com/zpodlovics/16d92f05f7e1c7376369

Executing the code will print the following result:
```
x1.Obj1: System.Object
x2.Obj1: <null>
```

I have checked the generated IL, and it seems that on x2 case the constructor will called with null as argument (IL_000f:  ldnull).

```
	IL_0000:  newobj instance void object::'.ctor'()
	IL_0005:  newobj instance void class Fsharpclassconstobjargcheck/T1::'.ctor'(object)
	IL_000a:  stsfld class Fsharpclassconstobjargcheck/T1 '<StartupCode$fsharpclassconstobjargcheck>.$Fsharpclassconstobjargcheck'::x1@7
	IL_000f:  ldnull 
	IL_0010:  newobj instance void class Fsharpclassconstobjargcheck/T1::'.ctor'(object)
	IL_0015:  stsfld class Fsharpclassconstobjargcheck/T1 '<StartupCode$fsharpclassconstobjargcheck>.$Fsharpclassconstobjargcheck'::x2@8

```

System environment: x86_64, Ubuntu 14.04, Mono 3.12.1 (from source based on tpokorra repo), F# 3.1.1.31 (from source).

Update: It seems that the explicit class constructors with single obj arg has the same problem.

Is this a bug or the expected way of working? In my opinion in this case FSharp should propagate nulls only if it passed explicitly as an argument.

Thanks for your help,
Zoltan

**Comment by latkin** [comment]
This is by design.  You are calling the constructor with 1 argument, the value of which is `unit`, and `unit` is always represented as `null`.

It does look a bit weird, however this behavior is specifically described in the language spec (§ 14.4, emphasis mine):

> If ... `M` has only one candidate method, which accepts only one required argument, **ignore the decomposition of `arg` to tuple form. Instead, `arg` itself is the only named actual argument.** 

So in the special case that there is only 1 overload to consider, and the signature requires exactly 1 argument, the callsite arg(s) is just slotted directly in, without the typical de-tupling.

So this satisfies the special case and is legal:

```fsharp
type T1(p1:obj) =
  class
  // new (p1:obj, p2:obj) = T1(p1)
  end

let x = T1()  // p1 is unit/null
let y = T1(1, 2, 3, 4)  // p1 is the tuple 1,2,3,4
```
but if a second overload is introduced, we are no longer covered by the special case, and the last lines are now an error:

```fsharp
type T1(p1:obj) =
  class
  new (p1:obj, p2:obj) = T1(p1)
  end

// error FS0505: The member or object constructor 'T1' does not take 0 argument(s). An overload was found taking 1 arguments.
let x = T1()
// error FS0505: The member or object constructor 'T1' does not take 4 argument(s). An overload was found taking 1 arguments.
let y = T1(1, 2, 3, 4)  // p1 is the tuple 1,2,3,4
```
