### ISSUE TITLE
Access modifier "internal" breaks custom operator +

### ISSUE THREAD

**Issue by fjoppe** [Microsoft/visualfsharp#3470]
I've created a piece of code. In an effort to provide clean access to my library, I was restricting access with signature files, and the access modifier "internal".

I discovered that applying "internal" to a module, or record type, broke custom operators for addition and subtraction. Those operators are provided in a mini DSL, and my code depends heavily on them. I'd like to avoid to convert these to normal functions.

#### Repro steps

I've isolated the issue in this code fragment (note I've seen this issue with + and - operators):

```fsharp
module internalBreaksOperator

type A = 
    { txt : string }
    with
        static member (+) (a:A, b: A) = {txt = "Plus"} 

type B()=
    member this.addit() = {txt = "1"} + {txt = "2"}
```

If I apply access moifier "internal" to one of:
* module
* type A
* (+) operator in type A

then using the + operator in B.addit breaks and does not compile anymore. I've seen this behavior when type "B" is in the same file, or in a different file. I've only seen/tested this in a .fs source, not in an .fsx file

When the "internal" modifier is applied, in VS2015 (not VS2017!), the "+" in B.addit gets red curly's. If you then select that +, and follow it with F12, you'll go to ``module Microsoft.FSharp.Core.Operators``, where the cursor is set at an inline (+) operator, with a signature that does not comply, to what is needed in the code above.

#### Expected behavior

I'd expect adding the "internal" modifier would only hide the module/type/method to become invisible for foreign dlls and executables.

#### Actual behavior

Somehow, the custom (+) operator is hidden for code close in scope (while having enough accesibiity and complying signature), and a non-relevant public implementation of (+) is preferred with non-compliant signature, which causes this to break.

#### Known workarounds

I haven't worked around this. The only thing I can think of is, put all project code in one file and then use exclusively signature files for hiding; I don't like this idea.. 

#### Related information 

* Windows 10
* Visual Studio 2015 and VS2017 (15.3)

**Comment by dsyme** [comment]
This is a known issue - see language suggestion https://github.com/fsharp/fslang-suggestions/issues/230

**Comment by dsyme** [comment]
Closing as tracked by language suggestion
