### ISSUE TITLE
arr.[..a]  != arr.[0..a]    and    arr.[a..(arr.Length-1)] != arr.[a..]

### ISSUE THREAD

**Issue by syeerzy** [Microsoft/visualfsharp#3474]
#### Repro steps

```fsharp
let arr = [1;2;3;4]
arr.[0..2] // [1;2;3;]   === arr.[..2]
arr.[0..1] // [1;2] === arr.[..1]
arr.[0..0] // [1] === arr.[..0]
arr.[0..-1] // []  ~~~~~~~~~   arr.[..(-1)] fail to an execaption.

arr.[1..3] // [2;3;4] === arr.[1..]
arr.[2..3] // [3;4] === arr.[2..]
arr.[3..3] // [4] === arr.[3..]
arr.[4..3] // []  ~~~~~~~~~  arr.[4..] fail to an execaption.
```

#### Expected behavior

i think the `arr.[..a]`  and the `arr.[0..a]` should has  same behavior.  both fail , or both return an empty slice.

#### Actual behavior

`arr.[0..a]`  return `[]`  and `arr.[..a]` goes to an execaption.

#### source in FSharp.Core 

    let sliceTake n l =
            if n < 0 then outOfRange()  //  <----- here should be []
            match l with
            | [] -> outOfRange()
            | x::xs ->
          // ..............
           match lst with
                | _ when i = 0 -> lst
                | _::t -> loop (i-1) t
                | [] -> outOfRange()  //  <----- here should be []
            loop n l

or : 

       member l.GetSlice(startIndex: int option, endIndex: int option ) = 
            match (startIndex, endIndex) with
            | None, None -> l
            | Some(i), None -> PrivateListHelpers.sliceSkip i l
            | None, Some(j) -> PrivateListHelpers.sliceTake j l
            | Some(i), Some(j) ->
                if i > j then [] else    // <---- change [] to outOfRange()
                PrivateListHelpers.sliceTake (j-i) (PrivateListHelpers.sliceSkip i l)

**Comment by dsyme** [comment]
@syeerzy I believe this has been noticed before. As I understand it there is no specific plan to change it because of compatibility concerns.  If you would like to progress it, then feel free to submit a trial PR fixing the issue and we can assess from there (it will need an RFC, but a PR is an excellent way to make sure we've got the issues covered, assessed perf impact etc.)

**Comment by dsyme** [comment]
@syeerzy OK, I see the PR here, thanks.  We'll take a look and assess the impact on existing tests https://github.com/Microsoft/visualfsharp/pull/3475

**Comment by charlesroddie** [comment]
I posted [an issue](https://github.com/Microsoft/visualfsharp/issues/2643) a while ago but was lazy about getting round to doing an RFC. The changes look ok to me. I will get round to it now.

For PR I expect you will also need to change https://github.com/Microsoft/visualfsharp/blob/master/tests/fsharp/core/array/test.fsx

These are the problematic ones that I can see, which should give empty structures rather than fail:
```
test "slice1928" (try s1.[7..] |> ignore; false with _ -> true)
test "slice1919" (try s1.[.. -1] |> ignore; false with _ -> true)

test "bslice1928" (try s1.[7..] |> ignore; false with _ -> true)
test "bslice1919" (try s1.[.. -1] |> ignore; false with _ -> true)

test "aslice1928" (try s1.[7..] |> ignore; false with _ -> true)
test "aslice1919" (try s1.[.. -1] |> ignore; false with _ -> true)

test "a2slice1942" (try m1.[1, 10..] |> ignore; false with _ -> true)
test "a2slice1943" (try m1.[10.., 1] |> ignore; false with _ -> true)
test "a2slice1944" (try m1.[1, .. -1] |> ignore; false with _ -> true)
test "a2slice1945" (try m1.[.. -1, 1] |> ignore; false with _ -> true)

test "a3slice1933" (try m1.[*,*,7..] |> ignore; false with _ -> true)
test "a3slice1934" (try m1.[*,*,.. -1] |> ignore; false with _ -> true)
test "a3slice1935" (try m1.[*,3..,*] |> ignore; false with _ -> true)
test "a3slice1936" (try m1.[*,.. -1,*] |> ignore; false with _ -> true)
test "a3slice1937" (try m1.[3..,*,*] |> ignore; false with _ -> true)
test "a3slice1938" (try m1.[.. -1,*,*] |> ignore; false with _ -> true)

test "a4slice1931" (try m1.[*,*,*,7..] |> ignore; false with _ -> true)
test "a4slice1932" (try m1.[*,*,*,.. -1] |> ignore; false with _ -> true)
test "a4slice1933" (try m1.[*,*,3..,*] |> ignore; false with _ -> true)
test "a4slice1934" (try m1.[*,*,.. -1,*] |> ignore; false with _ -> true)
test "a4slice1935" (try m1.[*,3..,*,*] |> ignore; false with _ -> true)
test "a4slice1936" (try m1.[*,.. -1,*,*] |> ignore; false with _ -> true)
test "a4slice1937" (try m1.[3..,*,*,*] |> ignore; false with _ -> true)
test "a4slice1938" (try m1.[.. -1,*,*,*] |> ignore; false with _ -> true)
```

**Comment by charlesroddie** [comment]
@dsyme What is the next step, language suggestion or draft RFC?

**Comment by dsyme** [comment]
@charlesroddie An RFC - on a quick glance I support changing the exception into an empty return, but we can do full discussion in the RFC

**Comment by dsyme** [comment]
@charlesroddie Thanks!

**Comment by dsyme** [comment]
@syeerzy I'll close this in favour of #2643, please work with @charlesroddie on the RFC

**Comment by charlesroddie** [comment]
RFC PR done
