### ISSUE TITLE
Error building project with a type provider NuGet reference

### ISSUE THREAD

**Issue by sjuberman** [Microsoft/visualfsharp#3477]
`dotnet build` fails when building a F# project that contains a type provider NuGet reference even if the full .Net framework is targeted.

#### Repro steps

1. Create a new F# console project using the dotnet command line
2. Change TargetFramework to `net462`
3. Add a NuGet reference to some type provider (In my case SwaggerProvider, also tested FSharp.Data)
4. Run `dotnet restore` and `dotnet build`

Zip with repro:
[TypeProviderTest.zip](https://github.com/Microsoft/visualfsharp/files/1238646/TypeProviderTest.zip)

#### Expected behavior

Project should build without errors

#### Actual behavior

Build fails with error: `error MSB6006: "RunFsc.cmd" exited with code -1073741571`

#### Known workarounds

No known workarounds

#### Related information 

* OS: Windows 10
* dotnet SDK version: 2.0.0

**Comment by forki** [comment]
can you please upload a zip with the repro? This will make it easier to reproduce locally.

**Comment by sjuberman** [comment]
@forki Done. Added to the main issue.

**Comment by dsyme** [comment]
@sjuberman This is a known issue, see #3303
