### ISSUE TITLE
Intellisense documentation message for "ref"

### ISSUE THREAD

**Issue by CHBen** [Microsoft/visualfsharp#3494]
#### Repro steps

Using Visual Studio 2017, partially type in "ref", and look at Intellisense

![ref partial](https://user-images.githubusercontent.com/29471423/29650786-a72f4084-88cf-11e7-8b4a-5da34e58ec5f.png)

#### Expected behavior

I think [:=] is for setting, and [!] is for getting the value.

Suggested sentence:
"Use the functions [!] and [:=] to get and set values of this type."

#### Actual behavior

Actual sentence:
"Use the functions [:=] and [!] to get and set values of this type."

#### Known workarounds

Change the symbol [:=] and [!] on this page:

https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Core/prim-types.fsi

A suitable task for a beginner contributor. I would like to try contributing. Thanks.

P.S. As mentioned in this stackoverflow question, it is suggested to use "mutable" instead of "ref", but I would still like the chance to contribute.
https://stackoverflow.com/questions/3221200/f-let-mutable-vs-ref

**Comment by cartermp** [comment]
@CHBen Absolutely feel free to contribute this fix!
