### ISSUE TITLE
VS hangs forever on solution loading, high CPU load

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3495]
1. Create a new console project in VS/Rider/etc.
2. Open VFT master.
3. Ctrl+F5
4. Open the console project it the exp instance.

![image](https://user-images.githubusercontent.com/873919/29660019-c227fbc6-88c8-11e7-9732-5d01e9f26d90.png)

**Comment by majocha** [comment]
Release vsix built from current master hangs on solution load, too.

**Comment by vasily-kirichenko** [comment]
I blame the recent work on MailboxProcessor. @dsyme can it be related?

**Comment by dsyme** [comment]
Yes, see #3498 .  It's also bad code in LanguageService.fs

**Comment by matthid** [comment]
Ah, so the nightlies are always using the latest `FSharp.Core` code, didn't even realize that, good to know.

**Comment by vasily-kirichenko** [comment]
It's fixed in https://github.com/Microsoft/visualfsharp/pull/3498
