### ISSUE TITLE
Renaming linked file results in error dialog

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#350]
If you have a linked file in an F# project, you can attempt to rename the file in solution explorer:

![image](https://cloud.githubusercontent.com/assets/5943573/7055137/13139f34-ddf6-11e4-9078-9e65ca63700f.png)

However you get an error dialog when you try it:

![image](https://cloud.githubusercontent.com/assets/5943573/7055143/230d4be2-ddf6-11e4-99fe-b200aa0d8322.png)

FWIW C# prohibits rename on linked files entirely.  This seems reasonable, as it's not clear what "renaming" even means with respect to linked files (change the name of the link? or the file itself?).  So IMO fix would be to just mark this field a read-only.

![image](https://cloud.githubusercontent.com/assets/5943573/7055177/5fc521ae-ddf6-11e4-8f06-6f5a35798234.png)

**Comment by enricosada** [comment]
Linked file are used more in f# than c#. We can help:

- rename the physical file if file name = label
- If different we rename the link label only

I know is more work but not too much. 
But maybe two different behavior are too confusing. 

Another approach, easier:

Rename label and show a dialog asking to rename the physical file too

**Comment by latkin** [comment]
I think disabling the broken rename scenario is the cheap and correct thing to do for now (i.e. for VS 2015 if someone sends a PR).

Personally I don't see this particular issue as worth spending time building out as a feature... It opens up a lot of corner cases and behaviors that need to be tested and supported for all eternity, for fairly small value.  There are more useful and impactful ways to contribute to the VS tools :-)

**Comment by enricosada** [comment]
readonly is also the current behaviour (F2 or double click) for linked items
