### ISSUE TITLE
Microsoft.FSharp.Compiler should not depend on Microsoft.NETCore.Platforms

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/visualfsharp#3504]
.nuspec has this. 

```
      <group targetFramework=".NETStandard1.6">
        <dependency id="Microsoft.NETCore.Platforms" version="1.0.1" />
```

It is causing a conflict in a runtime update in the CLI, and talking to @eerhardt, you shouldn't be referencing this at all.

**Comment by nguerrera** [comment]
@KevinRansom

**Comment by KevinRansom** [comment]
Okay .. I will make that change.

**Comment by eerhardt** [comment]
@ericstj and @weshaggard - for awareness.  It's my understanding that libraries outside of the shared framework shouldn't need to depend on `Microsoft.NETCore.Platforms`.

@KevinRansom - do you know why this dependency was added originally?

**Comment by ericstj** [comment]
> It's my understanding that libraries outside of the shared framework shouldn't need to depend on Microsoft.NETCore.Platforms.

Why not?  If they use RIDs and install on a framework other than .NETCoreApp what would bring in the RID graph?

**Comment by eerhardt** [comment]
> If they use RIDs and install on a framework other than .NETCoreApp what would bring in the RID graph?

Should the `framework other than .NETCoreApp` bring in the RID graph?  Or the application itself decide?

In the case that drew @nguerrera's attention, the dotnet/cli was getting downgrade warnings for Microsoft.NETCore.Platforms from `1.1.0` to `1.0.1`.  It seemed unnecessary for the FSharp.Compiler to be referencing NETCore.Platforms at all.

I guess there may be cases, but it seems a fringe/edge case.

**Comment by nguerrera** [comment]
The only reason I had a conflict is because in our upgrade to 2.1, we got to a place where we had TFM=netcoreapp2.0, but package=Microsoft.NETCore.App,2.1.0-*. Once I bumped the TFM to 2.1 as well, then I naturally got a "nearer" Microsoft.NETCore.Platforms with a better version. So, maybe this should just be left alone. 

With that said, I still don't understand the scenario for .NETStandard library to pull in Microsoft.NETCore.Platforms.

**Comment by KevinRansom** [comment]
It was originally added way back in the day, so that I could discover and copy all of the files necessary to run the tests.  This was way before publish ...

**Comment by ericstj** [comment]
Downgrade warnings can only happen on a package subgraph.  So if FSharp.Compiler was getting downgrade warnings it was referencing a lower version of the package than one of its dependencies.  In which case it has nothing to do with the referencing the package or not: they just need to make sure to consistently update dependencies.

>  I still don't understand the scenario for .NETStandard library to pull in Microsoft.NETCore.Platforms.

If the library has a folder inside it like `runtimes/win/lib/netstandard1.4` then it needs to tell the project what `win` means.  That information is contained in Microsoft.NETCore.Platforms.

**Comment by KevinRansom** [comment]
Closing this, it seems that the current nuspec is good.
