### ISSUE TITLE
Valid pattern match fails to compile 

### ISSUE THREAD

**Issue by bikalgurung** [Microsoft/visualfsharp#3516]
The following pattern matching expression fails. I am not sure if this is a valid error. 

#### Repro steps
```
type Token = 
  | T_Exclamation
  | T_Question
  | T_String of string
  | T_Lparen
  | T_Rparen
  | T_Eof
  | T_Empty    

let compare (x:Token) (y:Token) =  
  match x, y with
  | N_Session, N_Session -> 0
  | _,_ -> 1

```
#### Error 
error FS0038: 'N_Session' is bound twice in this pattern

#### Related information 
* Windows 10
* .NET Runtime,
*  Visual Studio Version 2017, 15.3.2

**Comment by AviAvni** [comment]
You don't have the case N_session so it's treated as variable and you can't use the same car name in one pattern more then one

**Comment by bikalgurung** [comment]
@AviAvni .. Indeed. you are correct. I will close this issue.
