### ISSUE TITLE
Intellisense for unused parameters/values just says "The value is unused"

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#3518]
This is a rather contrived example, but consider these two images:

In the first one, I'm holding the mouse pointer over `x`:
![correct](https://user-images.githubusercontent.com/7766733/29818475-c7745af0-8cbc-11e7-9a1d-a29fd0cc4409.PNG)

In the second one, I'm holding the mouse pointer over `y`:
![wrong](https://user-images.githubusercontent.com/7766733/29818476-c79e9928-8cbc-11e7-92c3-c57a8e094311.PNG)

I'd expect Intellisense to show me type info also in the second example (together with the existing "unused" message). As it is now, I have to write a dummy usage (e.g. `let y' = y`) in order to get the type info on mouseover.

I'm using VS 15.3.2. In case it's relevant, the project in question is targeting PCL profile 259 and F# 4.1 (3.259.41.0). Let me know if you need more info.

**Comment by NatElkins** [comment]
Interesting, I see different behavior.  In the project I tried this example in I have the `--warnon:1182` flag added (warn on unused variables), and I see the following:

![unused](https://user-images.githubusercontent.com/1795462/29829857-85ec5b4a-8cae-11e7-8396-d11871643896.gif)

You can see the message duplicated for unused variables (although the type is present).  When I remove the flag, this is what I see:

![unused2](https://user-images.githubusercontent.com/1795462/29829907-a5740cce-8cae-11e7-9a18-a11f022fa39e.gif)

That appears to be the behavior you're looking for.

I'm using the VF# nightlies (15.4.1.17082301) and VS 15.3.2.  I'd try upgrading to the most recent VF# nightly build and checking to see if that fixes things.

**Comment by cmeeren** [comment]
I have no idea how to do that and what that would mean for my development process. Is it safe? Is it easy to go back? Does it work with PCL (I'm stuck with old yucky PCLs for the moment due to needing to support UWP), or doesn't VF# have anything to do with such things?

**Comment by NatElkins** [comment]
It's easy to install and easy to go back.  This blog post shows to to install VF# nightly builds and how to go back: https://blogs.msdn.microsoft.com/dotnet/2017/03/14/announcing-nightly-releases-for-the-visual-f-tools/

**Comment by cartermp** [comment]
Just to confirm @NatElkins's statements, it is easy to install, safe, and easy to go back.  There are also other improvements in the nightlies right now that you may be interested in taking.

**Comment by saul** [comment]
I’m on the nightlies and I also see this.

**Comment by cmeeren** [comment]
Just installed the nightlies and I still see this.

**Comment by vasily-kirichenko** [comment]
That's not a tooltip, that's a quick action (note the lightbulb), which I believe replaces normal tooltip. 

Can you guys reproduce it on C# code?

**Comment by cmeeren** [comment]
I don't get any "unused warning" at all in C# without ReSharper.

Without R#:

![nors](https://user-images.githubusercontent.com/7766733/29910515-87d1db74-8e2a-11e7-9abe-ead8730ceb37.PNG)

With R#:

![rs](https://user-images.githubusercontent.com/7766733/29910519-8b31f7e0-8e2a-11e7-9764-d0cca11326c6.PNG)

**Comment by realvictorprm** [comment]
Looks like an additional tool tip

Am 31.08.2017 08:58 schrieb "Christer van der Meeren" <
notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
@cmeeren I think it's not related to a specific warning (unused var). I believe a quick fix tooltip always hides a normal one (which shows signature, xml docs and errors (if any)).

**Comment by cmeeren** [comment]
I see. What can I do about it, then?

**Comment by forki** [comment]
Probably report it to VS

Am 31.08.2017 09:37 schrieb "Christer van der Meeren" <
notifications@github.com>:

I see. What can I do about it, then?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/issues/3518#issuecomment-326215690>,
or mute the thread

**Comment by vasily-kirichenko** [comment]
@cmeeren if it is reproduced on c# code in any form, report it to https://github.com/dotnet/roslyn

**Comment by cmeeren** [comment]
@vasily-kirichenko as shown in the picture [above](#issuecomment-326207942), it does not seem to be a problem when using C#.

**Comment by vasily-kirichenko** [comment]
@cmeeren 

![image](https://user-images.githubusercontent.com/873919/29915767-7cbebbce-8e45-11e7-8eb4-671be81cdbd8.png)

![image](https://user-images.githubusercontent.com/873919/29915779-851fcc7c-8e45-11e7-8c2a-d748ca554090.png)

on the second screenshot the signature is not shown, only the quick fix is, so it's indeed a Roslyn issue, not Visual F# Tools one (however, I'm pretty sure they will try to persuade you that it's the way it should work, based on an extensive user UI experience research they've made :) )

**Comment by cmeeren** [comment]
Are you saying there's no point in filing it? Also, what about the [comment](#issuecomment-325705546) by @NatElkins where it seems to be working?

**Comment by vasily-kirichenko** [comment]
You can try to file it, of course. It seems not a big issue in C# because of the limited type inference, so there is not need to see signatures in such quick fix tooltips as they are already presented in the code itself most of the time.

About @NatElkins 's comment, I cannot reproduce it:

![image](https://user-images.githubusercontent.com/873919/29916550-c4e78730-8e47-11e7-9a5b-157e29c6c0bc.png)

No idea why it works for him.

**Comment by cartermp** [comment]
@cmeeren Please do file an issue on Roslyn and reference this issue there.  Since it's not an F#-controlled thing (as far as we know), that would be a good place.

**Comment by sharwell** [comment]
@cmeeren @vasily-kirichenko I tested this just now in C# and found the following. I'm using Visual Studio 2017 (15.3.3).

![image](https://user-images.githubusercontent.com/1408396/30062367-85309f2e-9210-11e7-8de5-31b3db04cff2.png)

**Comment by vasily-kirichenko** [comment]
![1](https://user-images.githubusercontent.com/873919/30062928-8f4e7608-9255-11e7-9590-47b5d81b0a52.gif)

**Comment by cmeeren** [comment]
@vasily-kirichenko, I'm puzzled by the fact that you seem to experience the correct behavior as you show in your latest comment. Have I missed any VS settings that could control this? Do you have any idea why we see different tooltips? (I don't even see the lightbulb button, though <kbd>Ctrl</kbd>+<kbd>.</kbd> works.)


(Using VS 15.4.4 and latest nightly of F#, and this is still an issue for me.)

**Comment by vasily-kirichenko** [comment]
@cmeeren have you turned off ReSharper (if you have it)? If you have, then I have no idea why it does not work for you. I've not touched any VS settings.

**Comment by cmeeren** [comment]
I noticed I don't even have any F# templates installed. Following https://github.com/Microsoft/visualfsharp/issues/3056, I'll try to repair my VS installation.

**Comment by vasily-kirichenko** [comment]
Templates were missed in several releases, install the latest nightly.

**Comment by cmeeren** [comment]
Nope, still nothing (except Xamarin F# templates). Attempting repair.

**Comment by cmeeren** [comment]
Repairing VS brought back the templates. I have now discovered that the bug is caused by the presence of ReSharper.

If ReSharper is enabled (even if it's suspended), I get the bug. If I disable the ReSharper plugin and restart, everything seems to work fine. This thus seems to be a duplicate of #3056.

**Comment by cmeeren** [comment]
And by the way, templates are still missing from latest nightly (15.4.1.17111702).
