### ISSUE TITLE
Assembly reference is not created when a type is used in attribute only

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#3522]
When types from an assembly are only used in attributes, a reference to the assembly isn't created.
A minimal repro: [AttrReference.zip](https://github.com/Microsoft/visualfsharp/files/1263134/AttrReference.zip)

```fsharp
namespace AttrRef

type AttrAttribute(t: System.Type) = class end

[<Attr(typeof<System.IO.File>)>]
type Class() = class end
```
Expected behavior: example output assembly has a reference to `System.IO.FileSystem`.
Actual behavior: no reference.
Workaround: using the `File` type anywhere else in the code creates the reference.

**Comment by dsyme** [comment]
@auduchinok Nice find :)  Thanks
