### ISSUE TITLE
Display signatures in CodeLens above functions

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#3529]
It would greatly help my development experience if the signature of functions appeared above their definition, like in VS Code (perhaps using CodeLens?).

**Comment by realvictorprm** [comment]
Hey look into #2967 that's my PR for Code Lens. It's unfortunately currently blocked. We need to wait till Microsoft opens their API.

Also this is a duplicate I think.

**Comment by cmeeren** [comment]
Great, thanks. I searched for "signature", but found no relevant issues from the first few search result pages.

Not holding my breath, though - it's been requested [for a long time](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/5743423-provide-an-open-api-to-allow-us-to-extend-code-len)...

**Comment by cmeeren** [comment]
Wait, why is it blocked again? From the GIFs it seems it's working great, even though the CodeLens API is not open.

**Comment by realvictorprm** [comment]
Haha thanks :smile:
Well it's problematic. It's difficult to achieve, I've developed I think 4 different caching systems in combination with the UI system. The last two caching system didn't work well but would prove best caching capabilities. If I choose an older version with worse caching I can get it working again.

**Comment by realvictorprm** [comment]
@cartermp told me that movement happens @cmeeren

**Comment by cmeeren** [comment]
Would it be possible to offer a current implementation as a default-off option that users can turn on? Because IMHO this is certainly THE single most significant feature that would drastically improve my F# dev experience. I find myself mouseover-ing absolutely everything all the time to check signatures while I code.

**Comment by cmeeren** [comment]
My point being, I would gladly sacrifice some UI responsiveness for signatures.

**Comment by realvictorprm** [comment]
I can update my old versions. However be aware of that it doesn't work well with duplicates!

**Comment by cmeeren** [comment]
What do you mean by duplicates, and how could I get this functionality?

**Comment by realvictorprm** [comment]
I'll answer you later. Currently in a meeting :smile Ping me in at least 2 hours

**Comment by realvictorprm** [comment]
Can I find you on the FSSF slack @cmeeren?

**Comment by cmeeren** [comment]
Sorry, I'm not on slack.

**Comment by vasily-kirichenko** [comment]
I'm for merging the feature PR, off by default. Code lens is quite tricky to implement in a bug free and fast way, look at Ionide, for example (I cannot test VS for Mac implementation though (no a Mac around), but it may make a sense to see how it's done there (if it's OSS, which might be not the case)).

**Comment by realvictorprm** [comment]
@cmeeren let us talk over gitter, https://gitter.im/Microsoft/visualfsharp

**Comment by cmeeren** [comment]
Decided to join FSSF on slack, see you there. :)

**Comment by cartermp** [comment]
Closing as dupe of #2364
