### ISSUE TITLE
Signature tooltip is not shown if there is an error at the same position

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3547]
![image](https://user-images.githubusercontent.com/873919/29998146-a07f204c-902c-11e7-9eac-26fed93b22b7.png)

I'm pretty sure it used to show both signature and errors in same tooltip.

**Comment by dsyme** [comment]
Step by step repro please?

**Comment by vasily-kirichenko** [comment]
1. Hover the mouse over an error.
2. Tooltip showing the error appear.
3. Tooltip containing symbol info does not appear.

**Comment by dsyme** [comment]
ok - I don't see this

![image](https://user-images.githubusercontent.com/7204669/30035109-7eacd694-919e-11e7-9ce0-8f7a20797963.png)

**Comment by dsyme** [comment]
I seem to recall people already reported this, would be good to know what circumstances cause it

**Comment by majocha** [comment]
Slow or not working QuickInfo #3459 would manifest like this when there is also an error.

**Comment by cartermp** [comment]
I can repro this.  Picked a psuedorandom match expression in `service.fs`:

![repro](https://user-images.githubusercontent.com/6309070/30192023-988b0c4a-93f9-11e7-9a80-6f8072bde9a7.gif)

Notice that I get QuickInfo for the `Some` and `None` case, but nothing for the `checkResults` token.

**Comment by dsyme** [comment]
@cartermp That's by design - the ``checkResults`` was never analyzed, and no type information or name resolution was performed for it

**Comment by cartermp** [comment]
I see.  Could that also be what @vasily-kirichenko was seeing as well?

**Comment by saul** [comment]
Looks like this is caused by ReSharper. When ReSharper is disabled, quickinfo shows for variables even when there are errors.

**Comment by saul** [comment]
Can we re-open this please? It hasn’t been resolved

**Comment by cartermp** [comment]
Closing this out as the root cause is that in #3056 (which I've renamed
