### ISSUE TITLE
msbuild + fsharp + mono 5.2.0.215 (clickety) -> non-IL or abstract method

### ISSUE THREAD

**Issue by haf** [Microsoft/visualfsharp#3552]
Build an F# project on Mono 5.2.0.215, with a command such as:

```
msbuild /verbosity:detailed /property:Configuration=Release MyProject.fsproj
```

This causes a lot of output like below:

```
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
  non-IL or abstract method with non-zero RVA
```

Expected behaviour: fixed on latest mono.
OS: macOS 10.12.
Severity: after being assured this has no effect; minimal severity since it only shows up in detailed verbosity.

**Comment by dsyme** [comment]
That line of code went with tag 4.1.25 from http://github.com/fsharp/fsharp.  

@nosami - could you check which tag we're using?

**Comment by nosami** [comment]
fsharp 4.1.25 is in the 5.4 and 5.6 series.

Mono 5.2 series is using 4.0.1.20

**Comment by dsyme** [comment]
@nosami OK, thanks

Any chance we could hotfix the 5.2 series to use tag ``4.0.1.20.1`` tag.   I just pushed that  with that one line removed?

**Comment by nosami** [comment]
I can create a Mono 5.2 build with F# 4.0.1.20.1 - that's the easy part :)

The more difficult part is getting it authorised and through QA etc - I'll see what I can do.

**Comment by dsyme** [comment]
Well, it's only one line :)

**Comment by nosami** [comment]
I can probably get a Mono build published somewhere, even if it's not part of an official tag.

**Comment by nosami** [comment]
Eek... I made a mistake... Mono 5.2 is on F# 4.1.9 - No idea where I got 4.0.1.20 from.

I can apply the patch myself to our build.

**Comment by dsyme** [comment]
ok, thanks!

**Comment by dsyme** [comment]
@nosami I'm actually glad to here that - 4.0.1.20 was old :)

**Comment by nosami** [comment]
OK. Here's Mono 5.2.1.5 https://dl.xamarin.com/uploads/cx2x4qs22hs/MonoFramework-MDK-5.2.1.5.macos10.xamarin.universal.pkg containing the fix.
