### ISSUE TITLE
Duplicated Find All References results on .NET Core 2.0 project

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3556]
![image](https://user-images.githubusercontent.com/873919/30110888-6ad0f16a-9314-11e7-86c0-03f958d2dd2e.png)

**Comment by vasily-kirichenko** [comment]
I'm pretty sure Microsoft claimed it's in charge of fixing any bugs in code provided by the community. If it's not the case, it's better to remove or disable all the Roslyn-based features in order to not confuse users.

**Comment by Pilchie** [comment]
@vasily-kirichenko is the project targeting multiple frameworks?  If so, I think this is likely https://github.com/dotnet/roslyn/issues/16587.

**Comment by cartermp** [comment]
I cannot repro this on a .NET Core 2.0 project after #3564 in the 15.5 build.

![no-repro](https://user-images.githubusercontent.com/6309070/30305513-2573c9ea-9728-11e7-8f86-5322d12fe345.PNG)

Tagging this with the `needs-repro` label so that it's easier to find once Preview 1 ships.
