### ISSUE TITLE
Duplicate Find All References results after a closed and re-opened .NET Core 2.0 project

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3557]
1. Clone and build this project: https://github.com/fable-compiler/fable-suave-scaffold
2. Open ClientServer.sln.
3. Observe that things work.
4. Add a new file that defines the following:

```fsharp
    type private MaybeBuilder() = 
        member x.Bind(v, f) = Option.bind f v
        member x.Return(v) = Some v
        member x.Zero() = Some ()
        member x.Combine(v, f:unit -> _) = Option.bind f v
        member x.Delay(f : unit -> 'T) = f
        member x.Run(f) = f()
        member x.While(cond, f) =
            if cond() then x.Bind(f(), fun _ -> x.While(cond, f)) 
            else x.Zero()

    let private maybe = MaybeBuilder()

    let testFxn =
        let ret = 
            maybe {
                let! x = Some 1
                let! y = Some 2
                return x + y
            }
        ret
```

4. Close ClientServer.sln.
5. Re-open it.
6. Find All References on a `maybe`.

You will see duplicate results in the Find All References window.

**Old issue:**
![image](https://user-images.githubusercontent.com/873919/30110945-9660b1da-9314-11e7-8dca-65b0f3f3a86b.png)

**Comment by cartermp** [comment]
I cannot repro this on a .NET Core 2.0 project after #3564 in the 15.5 build.

![no-repro](https://user-images.githubusercontent.com/6309070/30305619-b04543be-9728-11e7-86a0-91fd2bccd714.PNG)

**Comment by cartermp** [comment]
Interestingly enough, this does repro after I close and reopen the solution.

**Comment by cartermp** [comment]
This no longer reproduces. I believe all issues with duplicates have long been resolved.
