### ISSUE TITLE
Rename does not work on .NET Core 2.0 project

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3558]
![image](https://user-images.githubusercontent.com/873919/30111014-cdb3ac00-9314-11e7-9430-9546bd3636a1.png)

**Comment by cartermp** [comment]
I cannot repro this on a .NET Core 2.0 project after #3564 in the 15.5 build.

![no-repro](https://user-images.githubusercontent.com/6309070/30305658-f02f4060-9728-11e7-9267-8ff9bb867f0a.PNG)
