### ISSUE TITLE
Nothing works on a reopened .NET Core project 

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3559]
1. Open a .NET Core 2.0 project
2. Everything works
3. Create new full framework project
4. Everything works
5. Reopen the first project
6. Nothing works:

![image](https://user-images.githubusercontent.com/873919/30111140-42c6798c-9315-11e7-9741-071f349ec6ab.png)

7. Reopen the second (full .net) project
8. Everything works
9. Reopen the Core project
10. Nothing works
11. Restart VS
12. Nothing works

I have no idea how it worked initially :(

**Comment by 7sharp9** [comment]
`maybe` is a local file, not extcore?

**Comment by vasily-kirichenko** [comment]
Yes, it's defined right in the `Program.fs`

**Comment by vasily-kirichenko** [comment]
Actually I cannot get anything working on that Core 2 project anymore. Rider works fine on it.

**Comment by cartermp** [comment]
I cannot repro this after #3564.  However, #3557 does repro afterwards.
