### ISSUE TITLE
fsi.exe from dotnet core 2.0 not working on Window 7

### ISSUE THREAD

**Issue by nojaf** [Microsoft/visualfsharp#3560]
#### Repro steps

Provide the steps required to reproduce the problem

1. Go to install location of dotnet core on Windows

2. Execute fsi.exe from command line.

#### Expected behavior

Repl starts as described on [docs]( https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/fsharp-interactive/)

#### Actual behavior

![image](https://user-images.githubusercontent.com/2621499/30159543-3b2c46ca-93c9-11e7-8313-ffb4478398f2.png)

#### Related information 

Provide any related information 

* Operating system: Windows 7
* .NET Runtime, CoreCLR or Mono Version: 2.0

How can I use `fsi` installed with dotnet core?

**Comment by dsyme** [comment]
@nojaf It is not yet available, see https://github.com/Microsoft/visualfsharp/issues/2407

Closing as duplicate
