### ISSUE TITLE
Editor + Dotnet ProjectSystem ---- When opening a project with a .fs initially opened.  the .fs is opened as a StandAloneFile.  Roslyn has yet to open a project. 

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#3569]
When opening a dotnet sdk project.  SetupNewTextView is called before the project is loaded.

This causes it to be loaded as a Standalone project thus intellisense, file ordering and references are broken.

Probably ...
   Need to figure out how Roslyn deals with this !!!!!

**Comment by cartermp** [comment]
Is this something you'll be addressing in #3564?

**Comment by KevinRansom** [comment]
fixed with:  https://github.com/Microsoft/visualfsharp/pull/3564
