### ISSUE TITLE
VisualFSharp project --- is super slow to display Cyan Type info

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#3570]
When loading a large solution, time to get to full build is slow.

**Comment by cartermp** [comment]
The title and body of this issue differ.  Are you referring to semantic colorization being slow on VF#, or the time to build the solution?

**Comment by dsyme** [comment]
Repro steps would be helpful :)

However I believe Kevin is referring to the fact that when in-memory cross-project references are enabled (the default) and you're working in FSharp.Editor, then it takes ages to show Cyan because it goes and does a full typecheck on all dependent projects first.

If in-memory cross-project references are disabled, and a build has been done, then it is faster.

**Comment by abelbraaksma** [comment]
@dsyme, I think that is exactly what @KevinRansom means. Though I think it is also related to editing a large project and finding that it gets annoyingly slow very quickly (to the point where even typing a simple comment ends up at about a character a second!). It often takes less than a half hour of editing for this to happen. Waiting it out and continuing does not give back performance (once slow, it stays slow until restart).

I have been trying to find the culprit by attaching a profiler when this happens and I have seen a lot of thread-wait cycles, but I have yet to manage to find the actual thread I should be monitoring for this, I mean, I am not sure the thread-waits are the culprit (or how to effectively profile to begin with). I'm willing to do more research, but may need some help. I can also give a datadump of the profile session if that helps anyone with more knowledge of the processes involved.

I also noticed that it seems to be a single thread spinning, it is not that multiple threads end up using all available processing power.

**Comment by cartermp** [comment]
There are two things at work here:

1. Semantic classification basically requires typechecking the world for large solutions in files where many types from many places are used (e.g., FSharp.Editor).
2. The workspace event which tells us to invoke semantic classification isn't instantaneous, so there is a delay before our chunky operation can happen.

@KevinRansom was looking into the idea of immediately kicking off semantic classification upon file open against a known TFM and the default set of references for that type. This will still result in things like types from P2P references not being colored until the workspace computes projects and fires off the event, but it should make the editor "feel" faster for numerous cases.

**Comment by dsyme** [comment]
Closing this old issue
