### ISSUE TITLE
Editor + Dotnet ProjectSystem ---- Project References don't work.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#3571]
With a dotnet sdk solution, project with project references do not work properly.

**Comment by cartermp** [comment]
I think we should be more specific here: I highly doubt that everything will fail once the language service is made aware of the P2P reference.  But that appears to be the issue right now.

Is this something you'll be addressing in #3564?

**Comment by cartermp** [comment]
Fixed by #3777
