### ISSUE TITLE
Continuous high CPU, Team Explorer flashing when opening FSharp solution from Github

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3573]
VS2017 15.4.0 P2 + latest nightlies FSharp.

When opening a new copy through Git (Team Explorer > Clone) then opening FSharp.sln (which will partially fail, needs to be build from cmd line first), the Team Explorer will start flashing and VS2017 and MSBuild go nuts:

**Flashing Team Explorer**

![flashingteamexplorer_fsharpsln](https://user-images.githubusercontent.com/16015770/30389070-270a5b80-98b2-11e7-863c-a3933c20e659.gif)

** High CPU**

![image](https://user-images.githubusercontent.com/16015770/30389150-5dc8fe2e-98b2-11e7-8a8a-5bd0148fed82.png)

### Repro steps

1. Open Team Explorer, select Git Clone, enter VisualFSharp Git repo
2. Open FSharp.sln
3. Go back to Team Explorer
4. Behavior as shown

### Expected behavior

No flashing expected. The high CPU is perhaps expected, not sure.

### Actual behavior

Flashing as in the video. High CPU for about 1-2 min (I didn't keep track). Then the CPU stopped and the flashing stopped.

### Known workarounds

Wait it out.

### Related information 

VS 2017 v15.4.0 Preview 2 on Windows 7, all updates installed.

Not sure this is "normal" or "expected" behavior. Not sure this is related to the F# repo, or a VS2017 bug. And I haven't tested this in older VS's or RTM's.

**Comment by vasily-kirichenko** [comment]
I don't think it's related to VFT. BTW, why do you use Team Explorer? I find the UI and performance equally terrible. The best VCS UI/integration I've ever seen is the Rider's (IDEA) one.

**Comment by abelbraaksma** [comment]
@vasily-kirichenko, thanks for chiming in :). I didn't quite think it through, and on any other project I stay away from Team Explorer. But I figured, this is an MS prj by MS people (and a lot of volunteers), so let's stick to the toolchain they offer. It somehow seemed to make sense.

I just saw that this may be a known issue with VS20xx, because NCrunch (I am basically trying to run the unit tests with it) reports a warning on using Git with VS, in essence it says: **don't use Git in VS!**:

> The Microsoft Git Provider has been detected as resident in the VS IDE, and this solution is part of a large git repository containing many entries.
> 
> The MS Git Provider has a performance issue that causes it to constantly re-scan the entire repository when file system changes are detected anywhere underneath the repository root or in nested directories.  This problem exists regardless of how Git is configured with .gitignore files, and is responsible for high CPU consumption in the IDE on solutions with large Git repositories.
> 
> Because NCrunch often updates files within its own cache directory (_NCrunch_SOLUTIONNAME), it can act as a continuous trigger for this performance problem.
> 
> If you are not actively using the Microsoft Git Provider, it is strongly recommended that you remove it from your system.  It is possible to disable this extension through Visual Studio's 'Tools->Options-Source Control' setting, but the extension very often re-enables itself silently at a later date.  To permanently remove this extension, see https://stackoverflow.com/questions/22459959/how-do-you-remove-microsoft-git-provider#23512676

**Comment by vasily-kirichenko** [comment]
wow. Sorry if I was advertising Rider too aggressively, I just love its VCS integration too much :)

**Comment by dsyme** [comment]
> wow. Sorry if I was advertising Rider too aggressively, I just love its VCS integration too much :)

It's definitely ok to talk about other F# IDEs and their merits in this repo - partly because it's not just the Visual F# IDE tools - it's also the repo of the F# compiler and compiler service, which form part of these IDEs. And partly because it's interesting and helpful to learn what other IDEs do.

**Comment by abelbraaksma** [comment]
> wow. Sorry if I was advertising Rider too aggressively, I just love its VCS integration too much :)

@vasily-kirichenko: not to me the comment I wrote was about Git-integration of VS, not Rider. I don't think I have used Rider yet, unless unconsciously perhaps. So your comment came as an eye-opener to me :).

**Comment by abelbraaksma** [comment]
>  But I figured, this is an MS prj by MS people (and a lot of volunteers), so let's stick to the toolchain they offer. It somehow seemed to make sense.

@vasily-kirichenko, rereading my own comment it looks rather derisive, it wasn't meant that way, my apologies. I'm just starting out getting test coverage working and I figured, let's stick to the defaults given by the instructions in DEVGUIDE.md, before getting more adventurous and trying it with other tools. 

Certainly, I didn't mean to suggest this project may only be used with MS tools, on the contrary ;), your input is very valuable to me.

**Comment by abelbraaksma** [comment]
Btw, I think I ought to close this thread, as this is an issue caused by the GIT provider or Visual Studio and has nothing to do with Visual F# tools.
