### ISSUE TITLE
Record fields are wrongly resolved on unrelated symbols

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3574]
![image](https://user-images.githubusercontent.com/873919/30392069-53e8fee2-98c4-11e7-896c-774312265d61.png)

same in Rider

![image](https://user-images.githubusercontent.com/873919/30392080-604ffae6-98c4-11e7-87f1-9ed515c5db4c.png)

I think it's quite a huge bug.

Find references "works" as well

![image](https://user-images.githubusercontent.com/873919/30392184-b95e0f38-98c4-11e7-9d06-64ccdad8d7eb.png)

**Comment by vasily-kirichenko** [comment]
It's not in completion list though 

![image](https://user-images.githubusercontent.com/873919/30392244-df74ce3c-98c4-11e7-9f07-74e820c64679.png)

**Comment by vasily-kirichenko** [comment]
The error message is quite interesting, it does not say that `x` does not have `Foo` property/method, it says it's not a `MyRec`

![image](https://user-images.githubusercontent.com/873919/30392325-2b373bfc-98c5-11e7-96e9-1414fc7b5991.png)

which is misleading for my taste.

**Comment by cartermp** [comment]
@vasily-kirichenko could you split out the compiler error message into a separate issue?  Just want to split that out from the clear bug in the language service.

**Comment by dsyme** [comment]
@vasily-kirichenko I agree the compiler shouldn't really be performing that resolution if a non-record nominal type is already known for ``x``.

**Comment by dsyme** [comment]
@cartermp The nit is more in the compiler than the language service - the compiler has resolved the record label, and then decided that on a subsequent check that the types don't add up.  

So it's related to the error message and is the same nit.
