### ISSUE TITLE
Wrong compiler error when a record field is used after dot on a variable of unrelated type

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3576]
![image](https://user-images.githubusercontent.com/873919/30392069-53e8fee2-98c4-11e7-896c-774312265d61.png)

The error message is quite interesting, it does not say that `x` does not have `Foo` property/method, it says it's not a `MyRec`

![image](https://user-images.githubusercontent.com/873919/30392325-2b373bfc-98c5-11e7-96e9-1414fc7b5991.png)

which is misleading for my taste.

**Comment by abelbraaksma** [comment]
FWIW, this is not a regression (and you don't claim it is, I know), I checked your code with VS2015, F# 4.0 and it raises basically the same error:

![image](https://user-images.githubusercontent.com/16015770/30405309-5c60e48c-98eb-11e7-99d1-6bd4d7834f0f.png)

I agree though that improvement would be nice. I have seen that error a bunch of times, esp in Record-type hungry solutions.

Wouldn't the simplest solution be to say something similar to the default error when the method/property/field is not known? I mean, I would actually expect something like the following:

![image](https://user-images.githubusercontent.com/16015770/30405367-b04c287c-98eb-11e7-877f-2809499fc13d.png)

Cause, if you take the logic of the above error, then _any_ method/property/field that is used in _any_ type in scope could show that error.

**Comment by dsyme** [comment]
The relevant code is here: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/NameResolution.fs#L3127

The "record field" case should be adjusted so that it only kicks in if the type ``typ`` is a variable type or record type (something like ``not (isNominalTy typ) || isRecordTy ...``)

**Comment by vasily-kirichenko** [comment]
I confirm this is fixed in 15.7.2 

![image](https://user-images.githubusercontent.com/873919/40783532-5dd881cc-64eb-11e8-956f-9c72f4990d57.png)
