### ISSUE TITLE
VerifyArea test fails on master for FSharpOption.IsNone and IsSome, unclear cause

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3586]
I'm not sure this is a bug or anything, but on my system (Win7, VS2017 15.4) running the VerifyArea test fails with the following error:

> Assembly: FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
> Expected and actual surface area don't match. To see the delta, run:
>     windiff C:\Users\Abel\AppData\Local\NCrunch\15476\7\src\fsharp\FSharp.Core.Unittests\SurfaceArea.net40.fs C:\Users\Abel\AppData\Local\NCrunch\15476\7\Debug\net40\bin\CoreUnit_net40_Xml.xml
> 
> Unexpectedly missing (expected, not actual):
>     Microsoft.FSharp.Core.FSharpOption`1[T]: Boolean IsNone
>     Microsoft.FSharp.Core.FSharpOption`1[T]: Boolean IsSome
> 
> Unexpectedly present (actual, not expected):
>     Microsoft.FSharp.Core.FSharpOption`1[T]: Boolean IsNone [Microsoft.FSharp.Core.FSharpOption`1[T]]
>     Microsoft.FSharp.Core.FSharpOption`1[T]: Boolean IsSome [Microsoft.FSharp.Core.FSharpOption`1[T]]
> 
>    at FSharp.Core.Unittests.LibraryTestFx.SurfaceArea.verify(String expected, String platform, String fileName) in D:\Projects\OpenSource\VisualFSharp\src\fsharp\FSharp.Core.Unittests\LibraryTestFx.fs:line 178
>    at FSharp.Core.Unittests.SurfaceArea.SurfaceAreaTest.VerifyArea() in D:\Projects\OpenSource\VisualFSharp\src\fsharp\FSharp.Core.Unittests\SurfaceArea.net40.fs:line 3534

I'm reporting this because I'm not sure where to look for a cause. I.,e., is it possible that the function signature inference fails because of possible differences in system configuration? I'd assume it shouldn't fail, and I think that master is only merged when there aren't any Unit Test errors (right?), which suggests this may be caused by a difference in system configuration.

As per the DEVGUIDE.md and TESTGUIDE.md, I compile and run the tests in x86 mode using standard NUnit v3 runners in an x86 host process. I tried x64 mode, but this had the same result.

(this was one of the findings after starting investigating test coverage, see #3579)

**Comment by dsyme** [comment]
Could you look into why the test failure isn't failing CI?

**Comment by abelbraaksma** [comment]
@dsyme: I don't understand your question? I assume you mean the CI process run here, and then I assume that the mentioned error is simply not reported, unless of course the test is ignored. The latter seems doubtful, considering this checks the whole surface area.

I can check logs, but no idea where/how/what? Sorry, bit of a learning curve here...

**Comment by dsyme** [comment]
Here's what I tried 

1. Looking at build.cmd, the FSharp.Core unit tests are run in ``ci_part2`` https://github.com/Microsoft/visualfsharp/blob/master/build.cmd#L248

2. Clicking on this on the front page of the repo:

![image](https://user-images.githubusercontent.com/7204669/30454615-cd03da42-9994-11e7-8b6b-84919a5b356e.png)

4. takes us to https://ci2.dot.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part2_windows_nt/

4. Clicking on build 612 takes us to https://ci2.dot.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part2_windows_nt/612/

5. Looking at the plain text console log doesn't show any mention of VerifyArea

6.  Looking at the "Build Artefacts" reveals the output log core unit log in the "TestResults" directory. However the log for the unit tests strangely  doesn't make any mention of `VerifyArea` or `SurfaceArea` https://ci2.dot.net/job/Microsoft_visualfsharp/job/master/job/release_ci_part2_windows_nt/612/artifact/tests/TestResults/test-net40-coreunit-output.log doesn't reveal an

**Comment by abelbraaksma** [comment]
@dsyme, tx for showing the steps. I've tried to locate any of the `FSharp.Core.UnitTests` I am seeing when running it locally and wondering now whether I am running the right things. I tried to find some tests in the different builds, but can't find `SurfaceAreaTest` either, nor `MakeTypeType`, `TypeForwarding` of `JaroWinklerTest`.

I'm missing a browsable interface that simple shows a report test-by-test, but perhaps Jenkins (I've never worked with that) doesn't provide one. I use TeamCity, where I get a browsable report for each test (and the log as a fallback as well). Anyway, I shouldn't complain about Jenkins, just need to get used to it I guess.

**Comment by dsyme** [comment]
> I tried to find some tests in the different builds, but can't find SurfaceAreaTest either, nor MakeTupleType, TypeForwarding of JaroWinklerTest.

I think the test is being executed on CI. Here's the execution of the unit tests in the CI log

```
"D:\j\workspace\release_ci_pa---94d249b3\packages\NUnit.Console.3.0.0\tools\nunit3-console.exe" --verbose --framework:V4.0 --result:"D:\j\workspace\release_ci_pa---94d249b3\tests\TestResults\test-net40-coreunit-results.xml;format=nunit3" --output:"D:\j\workspace\release_ci_pa---94d249b3\tests\TestResults\test-net40-coreunit-output.log"  --err:"D:\j\workspace\release_ci_pa---94d249b3\tests\TestResults\test-net40-coreunit-errors.log"  --work:"D:\j\workspace\release_ci_pa---94d249b3\release\net40\bin" "D:\j\workspace\release_ci_pa---94d249b3\release\net40\bin\FSharp.Core.Unittests.dll" 
NUnit Console Runner 3.0.5797 
Copyright (C) 2015 Charlie Poole

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.14393.0
  CLR Version: 4.0.30319.42000

Test Files
    D:\j\workspace\release_ci_pa---94d249b3\release\net40\bin\FSharp.Core.Unittests.dll

Agent process 6176 starting
Running under version 4.0.30319.42000, Net 4.5
Agent process 6176 exiting

Tests Not Run

1) Explicit : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Collections.CollectionModulesConsistency.unfold is consistent full

2) Explicit : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Control.AsyncModule.Async.AwaitWaitHandle does not leak memory

3) Explicit : FSharp.Core.Unittests.FSharp_Core.Microsoft_FSharp_Control.AsyncModule.Async.Choice specification test

Run Settings
    RuntimeFramework: V4.0
    WorkDirectory: D:\j\workspace\release_ci_pa---94d249b3\release\net40\bin
    Verbose: True
    NumberOfTestWorkers: 4

Test Run Summary
    Overall result: Passed
   Tests run: 5336, Passed: 5336, Errors: 0, Failures: 0, Inconclusive: 0
     Not run: 3, Invalid: 0, Ignored: 0, Explicit: 3, Skipped: 0
  Start time: 2017-09-14 08:58:33Z
    End time: 2017-09-14 09:05:46Z
    Duration: 433.217 seconds
```

Here's an entry from the XML (not the "output log")
```
<test-suite id="0-6409" duration="431.973069" end-time="2017-09-14 09:05:45Z" start-time="2017-09-14 08:58:33Z" asserts="0" skipped="0" inconclusive="0" failed="0" passed="1" total="1" result="Passed" testcasecount="1" runstate="Runnable" fullname="FSharp.Core.Unittests.SurfaceArea" name="SurfaceArea" type="TestSuite">
<test-suite id="0-6181" duration="0.168959" end-time="2017-09-14 09:05:45Z" start-time="2017-09-14 09:05:45Z" asserts="0" skipped="0" inconclusive="0" failed="0" passed="1" total="1" result="Passed" testcasecount="1" runstate="Runnable" fullname="FSharp.Core.Unittests.SurfaceArea.SurfaceAreaTest" name="SurfaceAreaTest" type="TestFixture" classname="FSharp.Core.Unittests.SurfaceArea.SurfaceAreaTest">
<test-case id="0-6182" duration="0.165406" end-time="2017-09-14 09:05:45Z" start-time="2017-09-14 09:05:45Z" asserts="0" result="Passed" runstate="Runnable" fullname="FSharp.Core.Unittests.SurfaceArea.SurfaceAreaTest.VerifyArea" name="VerifyArea" classname="FSharp.Core.Unittests.SurfaceArea.SurfaceAreaTest" seed="1350782031" methodname="VerifyArea">
<reason>
<message>
<![CDATA[

]]>
</message>
</reason>
</test-case>
</test-suite>
```

**Comment by dsyme** [comment]
``MakeTupleType`` and ``TypeForwarding`` are also in that XML file. I presume the JaroWinkler one is in the FSharp.Compiler.UnitTests.dll log (a separate run of unit tests)

**Comment by dsyme** [comment]
I still don't understand what's causing these differences on your machine though
```
> Unexpectedly missing (expected, not actual):
>     Microsoft.FSharp.Core.FSharpOption`1[T]: Boolean IsNone
>     Microsoft.FSharp.Core.FSharpOption`1[T]: Boolean IsSome
> 
> Unexpectedly present (actual, not expected):
>     Microsoft.FSharp.Core.FSharpOption`1[T]: Boolean IsNone [Microsoft.FSharp.Core.FSharpOption`1[T]]
>     Microsoft.FSharp.Core.FSharpOption`1[T]: Boolean IsSome [Microsoft.FSharp.Core.FSharpOption`1[T]]
```

**Comment by abelbraaksma** [comment]
@dsyme, I was typing a response yesterday while my computer spontaneously restarted (this has happened a few times since recent installs of VS2017 previews and/or F# nightlies, and seem to happen only when running a lot of tests at once, but I have not yet determined a clear correlation, nothing in the event logs).

My response was essentially that I found the source. NCrunch adds instrumentation data to the methods/functions etc for getting coverage and timing information. For this particular function, it seems to have the effect that the signature of the function changes. I don't know why that is, but I guess that should be send as a report to NCrunch itself (unless of course I find that the cause is in the compiler).

Removing the instrumentation shows that the test runs successfully. I will close this bug report and reopen only if the cause is reproducibly related to the F# toolchain.
