### ISSUE TITLE
Uploading images to Github seems to be disallowed / blocked by amazonaws.com, response 503 "slow down"?

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3588]
This is rather weird and I hope I can close this soon again. But it seems like uploading resources to this repo has been blocked, at least for me. Each time I Ctrl-V an image I receive the message:

> Something went really wrong, and we can’t process that file. Try again.

Using select-file-then-upload gives the same error. I can see the following in the console, which may or may not be related:

> Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> api.github.com/_private/browser/stats Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> 2github-production-user-asset-6210df.s3.amazonaws.com/ Failed to load resource: the server responded with a status of 503 (Slow Down)
> new:1 XMLHttpRequest cannot load https://github-production-user-asset-6210df.s3.amazonaws.com/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://github.com' is therefore not allowed access. The response had HTTP status code 503.

With my limited understanding of AmazonAWS I would interpret this as if some denial-of-service protection has come into place (notice the "503 Slow Down" message).

I know, probably totally unrelated to this repo, but I didn't see anyone report on it, so if it's just me who's blocked I'll close this soon.

**Comment by dsyme** [comment]
![image](https://user-images.githubusercontent.com/7204669/30453915-72d1d652-9992-11e7-99cc-41cdefc8bbd8.png)

**Comment by abelbraaksma** [comment]
I just managed to upload again as well, probably a glitch. Nice kitten! :100:
