### ISSUE TITLE
[.NET Framework Projects] IDE is confused about the last file to compile

### ISSUE THREAD

**Issue by majocha** [Microsoft/visualfsharp#3596]
Current master
![image](https://user-images.githubusercontent.com/1760221/30511617-7716a890-9add-11e7-89c8-44fb8312a8f5.png)

It builds and runs OK. The false error is only in the IDE.

Repro:

Create a solution with [two or more console app projects](https://github.com/majocha/Repro3596).

**Comment by vasily-kirichenko** [comment]
.net core? this is expected

**Comment by majocha** [comment]
Not dotnet core, .Net Framework 4.6.1
I've noticed this in Gjallarhorn WPF sample projects at first.

**Comment by dsyme** [comment]
@KevinRansom @cartermp Something is quite busted on master, I think it is to do with cases where source files in projects get interpreted as if they are single file projects

![image](https://user-images.githubusercontent.com/7204669/30512135-ea203a8e-9adf-11e7-96e3-ae81075b98ba.png)

**Comment by majocha** [comment]
@KevinRansom I think I have some idea what's going on.

https://github.com/Microsoft/visualfsharp/blob/6c6de72d154a550732dd1ce818f64ad75fee843c/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L414-L417

This event with `ProjectAdded` args fires during solution load, and it can fire well before `SetupProjectFile` or `SyncProject` had a chance to run for a given project. Execution goes here https://github.com/Microsoft/visualfsharp/blob/6c6de72d154a550732dd1ce818f64ad75fee843c/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L163-L170
and, I guess, things break because InvalidateConfiguration is being called for a project that is not set up?

Commenting out this line
https://github.com/Microsoft/visualfsharp/blob/6c6de72d154a550732dd1ce818f64ad75fee843c/vsintegration/src/FSharp.Editor/LanguageService/LanguageService.fs#L416

fixes this issue and the other one (#3545) but I'm not sure what it breaks in return. I don't fully understand why it is needed.

**Comment by dsyme** [comment]
> and, I guess, things break because InvalidateConfiguration is being called for a project that is not set up?

Yes, that sounds like the problem

AFAIK the line is only needed for new-style .NET SDK project files (where a Roslyn project already exists).  SetupProjectFile is needed for old-style project files.  We need to somehow do the right thing here for old-style projects

**Comment by KevinRansom** [comment]
Hmmm looks like I broke something.  On it.

**Comment by cartermp** [comment]
cc @Pilchie for FYI

**Comment by dsyme** [comment]
Fixed by #3603 - thanks for resolving this @KevinRansom
