### ISSUE TITLE
No XML Doc in tooltips

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3615]
![1](https://user-images.githubusercontent.com/873919/30657804-6a59957e-9e41-11e7-8363-6d2a498397fa.gif)

**Comment by vasily-kirichenko** [comment]
It seems to reproduce for symbols defined in `mscorlib.dll` only. This is the root cause:

![image](https://user-images.githubusercontent.com/873919/30659568-d7dc1f0e-9e46-11e7-96d3-ac2b480a1605.png)

(`GetMemberIndexOfAssembly` returns `None` here)

If I understand correctly, it searches for `mscorlib.xml` file, but it does not exists:

![image](https://user-images.githubusercontent.com/873919/30659678-3b711aa6-9e47-11e7-84b9-b2fe89cd94e7.png)

I suspect there was a special logic to get XML docs from those symbols, which is broken.

**Comment by vasily-kirichenko** [comment]
Aha. `c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\` looks different:

![image](https://user-images.githubusercontent.com/873919/30659835-bc9f05d4-9e47-11e7-9d64-2a2c479807bd.png)

there _is_ the xml file, but it contains a redirect (yep there is such thing...):

```xml
<?xml version="1.0" encoding="utf-8"?>
<doc redirect="%PROGRAMFILESDIR%Reference Assemblies\Microsoft\Framework\.NETFramework\v4.X\mscorlib.xml" />
```
And we finally can find the full xml file there:

![image](https://user-images.githubusercontent.com/873919/30659930-00e4d9d0-9e48-11e7-9fa1-f09b6e71bb9a.png)

What's interesting, 4.7 contains full xml files right in its folder:

![image](https://user-images.githubusercontent.com/873919/30659975-1cd793ee-9e48-11e7-92ff-ca43514523dc.png)

**Comment by vasily-kirichenko** [comment]
And yes, switching to 4.6.1 or 4.7 fixes the tooltip:

![image](https://user-images.githubusercontent.com/873919/30660075-5a789658-9e48-11e7-9c10-74f62035e4f3.png)

So the problem is that 4.6.2 does not contain xml files. Is it my local problem or a general one with this specific version?

**Comment by cartermp** [comment]
Closing this since it's not an F# or F# setup thing - though I would argue that this sort of violates the principle of least surprise that you can create net462 projects, but can't get XML intellisense.

**Comment by vasily-kirichenko** [comment]
I think VFT should warn users some way, because absent XML docs on majority of symbols feels like a huge bug.

**Comment by vasily-kirichenko** [comment]
OK, C# editor works exactly the same.

**Comment by forki** [comment]
Works exactly the same = doesn't work

Am 20.09.2017 20:52 schrieb "Vasily Kirichenko" <notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
I think we should show a warning right in the tooltip if we cannot find a xml doc for framework assemblies, like "to get xml doc please install .net 4.x.x targeting pack (link)".
