### ISSUE TITLE
VS2017 15.4.0 P2 + current nightlies chokes on compiler-specific syntax for ILASM like `(#...#)`

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3618]
I don't know if I'm the only one seeing this, but since Visual Studio 15.4.0 P2 came out, and (at least) since nightly build 15.4.1.17091801, possibly earlier, constructs with compiler-only syntax, like `(#...#)` for ILASM generates errors in the editor.

These errors didn't use to be there (unless you were trying to use these outside this particular project).

I started seeing them after making a few local adjustments (in the tests, so not related, I assume). Building the whole project, also from within VS, is fine, it's just that the editor seems confused. 

I.e., in `prim-types.fsi`:

![image](https://user-images.githubusercontent.com/16015770/30670784-fe057316-9e63-11e7-8c62-ee563617256f.png)

or `prim-types-prelude.fsi`, this error is usually only shown if you use this construct in a normal project:

![image](https://user-images.githubusercontent.com/16015770/30670816-2d3219a0-9e64-11e7-819d-d0e2ba60870c.png)

Just wondering if this is possibly a local issue and whether I should delve deeper or whether other devs out there have the same and have some thoughts.

Rebuidling everything from scratch, clean checkout doesn't seem to have a discernible effect.

**Comment by abelbraaksma** [comment]
@dsyme, @KevinRansom , did you commit anything to fix this? Saturday this was still a problem. With the master of this morning (or at least, the current one), this seems to be fixed. It looks "normal" again:

![image](https://user-images.githubusercontent.com/16015770/30836592-75180d52-a25f-11e7-9b53-38383768cd89.png)

**Comment by vasily-kirichenko** [comment]
maybe error highlighting is broken?

**Comment by cartermp** [comment]
@abelbraaksma I don't think we fixed this over the weekend or today.  If you restart VS, does it still result in no errors?

**Comment by abelbraaksma** [comment]
@cartermp, I also installed VS 2017 15.4.0 P3. But several merges were done of fixes that date back further than this weekend. Another thing that I noticed on my own system is that, while I did run the `VSIXInstaller`, I did not to a `update-vsintegration.cmd`. While I believe this only updates the local SDK installation, perhaps this is of influence somehow?

Did anybody else notice the original error, or has it only been seen as in the last screenshot (where it seems fixed)?

Note that I checked this almost daily, just to be certain it wasn't a local fluke.

**Comment by dsyme** [comment]
@abelbraaksma I'm going to close this - it must have been some kind of glitch for you

**Comment by abelbraaksma** [comment]
@dsyme, it is repeatable with the code of the master branch at the time. But since it's not happening anymore (and it's useless to check historical commits), it's either fixed by accident, or whatever else. Either way, closing is a good thing ;)
