### ISSUE TITLE
FSharp.Core project is broken

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3621]
![image](https://user-images.githubusercontent.com/873919/30755678-432c41f0-9fd0-11e7-826f-7f21110de41d.png)

**Comment by vasily-kirichenko** [comment]
@brettfo it would be great if you tried to load the solution into VS before merging.

**Comment by vasily-kirichenko** [comment]
@brettfo sorry, but it's master after all...

**Comment by brettfo** [comment]
No need to apologize, I broke it when it should never have been broken.
