### ISSUE TITLE
F# compiler option --nowarn does not accept alphanumeric warning codes

### ISSUE THREAD

**Issue by mishra14** [Microsoft/visualfsharp#3626]
_From @mishra14 on September 21, 2017 20:1_

Stemming from: https://github.com/NuGet/Home/issues/5913

It seems that F# compiler option [--nowarn](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-options) only accepts integers. Which seems fine based on the description on the docs page. 

But the docs also state that the option is equivalent to C# compiler option [/nowarn](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/nowarn-compiler-option). But the C# compiler option accepts alpha-numeric codes like /nowarn:CS0219

```
F:\validation\test\addpkg>csc Program.cs /nowarn:NU1603;CS0219
Microsoft (R) Visual C# Compiler version 2.4.0.62025 (a0507c1e)
Copyright (C) Microsoft Corporation. All rights reserved.


F:\validation\test\addpkg>
```

IMO, either the two should be equivalent or maybe the docs should not state them as equivalent.

Please let me know, if this is not the right place for it or it needs to be in [fslang-suggestions](https://github.com/fsharp/fslang-suggestions).

_Copied from original issue: fsharp/fsharp#785_

**Comment by mishra14** [comment]
_From @forki on September 22, 2017 5:43_

I tink it should be posted in https://github.com/Microsoft/visualfsharp
/cc @cartermp

**Comment by mishra14** [comment]
_From @cartermp on September 22, 2017 16:11_

Yep, @mishra14 can you repost this on visualfsharp?  Thanks!

**Comment by KevinRansom** [comment]
Seems like a reasonable suggestions, just out of curiosity:  what does the 
    /nowarn:NU1603;  is that a C# compiler error message?

**Comment by KevinRansom** [comment]
@mishra14, @forki 

Okay ...

so we won't validate the alpha chars, and we will only warn for fsxxxx numbers.  And I guess we will need to make sure that we keep the arguments as passed and pass them through the compilation ...

Does that sound like what we need?.

**Comment by mishra14** [comment]
@KevinRansom: NUxxxx warnings are NuGet related warnings which were recently added. 

Your description seems about right. The same warning codes should be acceptable in `--nowarn` and `--warnaserror`.

**Comment by KevinRansom** [comment]
@mishra14 @forki 
**Yeah ... C#** is broken, so I will not make this change in the compiler.  I will fix the issue in the targets file or build task, I will just strip out values our compiler doesn't understand we don't understand..

**The C# bug:**
````
namespace ConsoleApp10 {
    class Program {
        static void Main(string[] args) {
            int x = 7;
        }
    }
}
```'
**csc Program.cs**
````
Microsoft (R) Visual C# Compiler version 2.3.2.62019 (b7354608)
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(13,17): warning CS0219: The variable 'x' is assigned but its value is never used
````
**csc Program.cs /nowarn:0219**
````
Microsoft (R) Visual C# Compiler version 2.3.2.62019 (b7354608)
Copyright (C) Microsoft Corporation. All rights reserved.

````
now this:
**csc Program.cs /nowarn:cs0219**
Microsoft (R) Visual C# Compiler version 2.3.2.62019 (b7354608)
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(13,17): warning CS0219: The variable 'x' is assigned but its value is never used
````








**Yeah ... C#** is broken, so I will not make this change in the compiler.  I will fix the issue in the targets file or build task, I will just strip out values our compiler doesn't understand we don't understand..

**The C# bug:**
````
namespace ConsoleApp10 {
    class Program {
        static void Main(string[] args) {
            int x = 7;
        }
    }
}
```'
**csc Program.cs**
````
Microsoft (R) Visual C# Compiler version 2.3.2.62019 (b7354608)
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(13,17): warning CS0219: The variable 'x' is assigned but its value is never used
````
**csc Program.cs /nowarn:0219**
````
Microsoft (R) Visual C# Compiler version 2.3.2.62019 (b7354608)
Copyright (C) Microsoft Corporation. All rights reserved.

````
now this:
**csc Program.cs /nowarn:cs0219**
Microsoft (R) Visual C# Compiler version 2.3.2.62019 (b7354608)
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(13,17): warning CS0219: The variable 'x' is assigned but its value is never used
````
C# ignores any non numeric value including cs0219.  It is a C# bug, and it is very likely it won't get fixed.

**Comment by mishra14** [comment]
@KevinRansom Thanks for the detailed response. 

I have one correction - /nowarn:CS0219 works as expected - 

F:\validation\test\addpkg>csc Program.cs  /nowarn:CS0219
Microsoft (R) Visual C# Compiler version 2.4.0.62025 (a0507c1e)
Copyright (C) Microsoft Corporation. All rights reserved.


```
F:\validation\test\addpkg>csc Program.cs  /nowarn:CS0219
Microsoft (R) Visual C# Compiler version 2.4.0.62025 (a0507c1e)
Copyright (C) Microsoft Corporation. All rights reserved.


F:\validation\test\addpkg>csc Program.cs  /nowarn:cs0219
Microsoft (R) Visual C# Compiler version 2.4.0.62025 (a0507c1e)
Copyright (C) Microsoft Corporation. All rights reserved.

Program.cs(9,17): warning CS0219: The variable 'x' is assigned but its value is never used

F:\validation\test\addpkg>
```

Note that it is case sensitive, so `cs0219` is not the same as `CS0219`.

**Comment by forki** [comment]
I just wished nuget would not mess with compiler flags. But it seems it's
too late. Again...

Am 23.09.2017 01:51 schrieb "Ankit Mishra" <notifications@github.com>:

**Comment by KevinRansom** [comment]
@forki ... it's 6 of one, half a dozen of the other.

Clearly that C# doesn't validate arguments is a bug ... however ... it is convenient that no UI is needed to add the nugget nowarn setting in VS because they can re-use the nowarnings field in the compiler settings.

So I can see it both ways ... anyway ... it is no big deal

**Comment by forki** [comment]
It's convenient and wrong.

Am 23.09.2017 05:07 schrieb "Kevin Ransom (msft)" <notifications@github.com

**Comment by Pilchie** [comment]
For reference, the C# compiler does this because it runs analyzers (which have their own custom error prefixes) and emits the diagnostics from analyzers, and allows suppression with `/nowarn` and `#pragma warning disable`.

**Comment by Pilchie** [comment]
I.e., it's not so much for other exes in the build like NuGet, etc, as it is for other analyzers running within csc.exe.
