### ISSUE TITLE
Nightlies down for now

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3628]
As you're likely aware, we produce signed nightly binaries that go through the VS update channel.

There haven't been any nightlies this week, despite changes going in.  This is due to outages in our infrastructure, which have been affected by the recent natural disasters.  We'll close this issue once things are back to a good state.

**Comment by ylibrach** [comment]
@cartermp would it be possible to get a nightly posted manually for now, at something like a once-a-week cadence? The current nightlies have a pretty big IDE issue with regards to loss of syntax highlighting and intellisense.

**Comment by Pilchie** [comment]
Unfortunately not - our entire ability to produce signed binaries is blocked, because the infrastructure for it is in Puerto Rico, and they have more important things to deal with right now.

However, you can manually download and install an older version of a nightly from the myget feed at https://dotnet.myget.org/feed/fsharp/package/vsix/VisualFSharp

**Comment by forki** [comment]
wow.

**Comment by realvictorprm** [comment]
Now I'm surprised too. I'm sorry for the people there.

**Comment by ylibrach** [comment]
@Pilchie understood. Based on the fact that the infrastructure is in Puerto Rico, and that Puerto Rico is likely facing months before things start getting back to normal, are we to assume that there will be no new nightlies for at least several more weeks?

**Comment by Pilchie** [comment]
@ylibrach We're not sure yet.  Microsoft as a whole has signing facilities in a few other locations world-wide, but the Visual Studio org normally runs through Puerto Rico.  People are looking at failover to other facilities, but they are also near capacity.  I don't expect it to be weeks/months before we get *any* signed builds again, but we might not get automatic nightly signed builds for a while, we might only get one-off builds for a while.  We'll keep you updated as we learn more.

**Comment by realvictorprm** [comment]
@ylibrach Even if you don't get nightlies this way you can still build Visual F# yourself and install it :)

@Pilchie I'm currently unsure whether we described how to do such clean so people don't face version problems (so far I see in my dev environment the resulting version of the tools would be 42.42.42.42?)

**Comment by piaste** [comment]
> Even if you don't get nightlies this way you can still build Visual F# yourself and install it :)

A less drastic solution is to [download the CI builds](https://github.com/Microsoft/visualfsharp/wiki/Using-CI-Builds) :)

**Comment by chillitom** [comment]
Any update?

**Comment by cartermp** [comment]
No update right now.

**Comment by vasily-kirichenko** [comment]
I got a couple of new nightlies Oct, 17 and Oct, 18 (approx).

**Comment by KevinRansom** [comment]
The signing pipeline is back online ... so the nightlies are flowing again :-)

**Comment by realvictorprm** [comment]
Great, thanks for the update!

**Comment by cartermp** [comment]
It appears that the signing which nightlies use (not "full signing") is up.  Closing this out.

**Comment by Bananas-Are-Yellow** [comment]
It still shows a latest nightly build of September 18 for me:

![image](https://user-images.githubusercontent.com/5648989/31854096-0d4e7ada-b68c-11e7-83b3-d1d1db23923f.png)

**Comment by cartermp** [comment]
@Bananas-Are-Yellow There's a small problem in master preventing the nightly for master going out, but the channel itself can now deliver them again.
