### ISSUE TITLE
rec inline function failed to compile, but the editor does not show any errors

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3634]
```fsharp
module M =
    let rec inline foo x = 
        if System.DateTime.Now.Ticks % 2L = 0L then
            foo x

[<EntryPoint>]
let main _ = 
    0
```
compilation errors:
```
1>Program.fs(4,13): error FS1114: The value 'Program.M.foo' was marked inline but was not bound in the optimization environment
1>Program.fs(2,20): error FS1113: The value 'foo' was marked inline but its implementation makes use of an internal or private function which is not sufficiently accessible
1>Program.fs(4,13): warning FS1116: A value marked as 'inline' has an unexpected value
1>Program.fs(4,13): error FS1118: Failed to inline the value 'foo' marked 'inline', perhaps because a recursive value was marked 'inline'
1>Done building project "ConsoleApplication5.fsproj" -- FAILED.
```

![image](https://user-images.githubusercontent.com/873919/30775560-b2b018ac-a09e-11e7-86b4-798497981404.png)

**Comment by abelbraaksma** [comment]
Possibly related: #1565, which I incorrectly closed a while back. it contains other examples that cause the same errors you mention here, which are not shown in the editor. 

My (not so educated) guess is, these inline functions can only really be resolved when compiling in full and whatever is used by IntelliSense is not so rigorous.

**Comment by dsyme** [comment]
This is a known issue - you just have to run the compiler to discover these errors.  

Running the optimization phase (which prepares optimization info) in the IDE developer loop is too expensive

**Comment by forki** [comment]
But the combination of keywords is not really useful right? We could warn.
