### ISSUE TITLE
Can we update NUnit from version 3.5 to 3.8?

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3640]
The used NUnit version is **about 2 years old**, version 3.5.0. We currently are at 3.8.0. 

I tried to fix it by changing this in `FSharpSource.targets` to see the effect on the tests, but it didn't seem to change the used NUnit in the output dir, so I guess there is not a "single point" where this is currently configured.

```xml
<NUnitVersion>3.8.0</NUnitVersion>
<NUnitFullVersion>3.8.0.0</NUnitFullVersion>
```

![image](https://user-images.githubusercontent.com/16015770/30791287-d4265ed8-a1b1-11e7-8490-63f292afd6c3.png)

**Comment by dsyme** [comment]
@abelbraaksma Is there anything specific we gain by updating?  I don't mind updating just historically I've found NUnit versions a bit of a PITA to update and just end up sticking to the same version if there's nothing specifically wrong with it

**Comment by PatrickMcDonald** [comment]
@abelbraaksma  It looks like these commits were used to last update to 3.5: https://github.com/Microsoft/visualfsharp/commit/db5aec23dfbc71d1dbec3aee0ef98af28a90f869 https://github.com/Microsoft/visualfsharp/commit/1f6b0f75c73fb6e485a304560b062013167744c2

**Comment by abelbraaksma** [comment]
@PatrickMcDonald, thanks. @dsyme, I still have "hanging" tests. They appear to hang on creation or invocation and this seems to be caused by the test driver or by the test framework. To exclude that it is caused by a bug in NUnit, I would like to update.

Besides, I believe that several features have been added that may be useful, like `MaxTime`, `Combinatorial`. Some existed earlier, but were buggy, it's more stable now.

**Comment by dsyme** [comment]
OK, thanks

> I've no problem doing this. Just need to know about procedure. If a PR would "in principle" be accepted, I wouldn't mind doing the work.

Yes, it would be accepted once all CI is green.  A lot of engineering improvements fall in this category :)

**Comment by dsyme** [comment]
I'm closing this since there's nothing specific driving the need for this

**Comment by abelbraaksma** [comment]
I forgot about this one, but I agree to close it for now. Though it wouldn't be a bad idea to keep external references up-to-date, including NUnit, as bugs in those libraries are getting resolved which may make our work easier too.
