### ISSUE TITLE
When building in VS2017 Preview, focus switches to a different source file

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3644]
VS 2017 15.4 Preview 2: when you compile (Ctrl-Shift-B) then after a few seconds the editor suddenly switches to a different source file. This is rather annoying but doesn't happen always. Not sure it is a VS bug or an F# bug.

Not a true repro yet, but I see this happening at least sometimes when I open a solution that previously had tabs open. Then hit Ctrl-Shift-B and focus changes to a different file. Ctrl-Tab brings you back to the original file. The selection seems random.

**Comment by cartermp** [comment]
I've no idea what could cause this.  @Pilchie, any ideas?

**Comment by Pilchie** [comment]
No.  That's very odd indeed.

**Comment by cartermp** [comment]
Closing this out as I've not seen it happen yet. Hopefully this was just a fluke! @abelbraaksma please ping if you still see this with the latest (15.5.6) or preview.

**Comment by abelbraaksma** [comment]
There was another report with a full repro where this happened always in a specific scenario (I can't recall the bug number, but it was resolved and with it, perhaps this too). 

So, this can indeed be closed, I haven't seen it happen anymore in ages (up to 15.6.3 and Previews), thanks @cartermp for reminding me to tend to my bugs ;).
