### ISSUE TITLE
TypeLoadException raised when starting fsi from Visual Studio

### ISSUE THREAD

**Issue by SvetlanaZj** [Microsoft/visualfsharp#3649]
After installing nuget package 4.1.23 and pointing Visual Studio to the installation folder, there is a TypeLoadException. Visual Studio starts fsi.exe as follows:

"%FSharpInstallDir%\fsi.exe" --fsi-server-output-codepage:65001 --fsi-server-input-codepage:65001 --fsi-server-lcid:1033 --fsi-server:FSIChannel_5160_912619280_1750851008  --optimize

The output is: 

Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

SERVER-PROMPT>
Exception raised when starting remoting server.
System.TypeLoadException: Access is denied: 'Microsoft.FSharp.Compiler.Server.Shared.FSharpInteractiveServer'.
   at Sample.Microsoft.FSharp.Compiler.Interactive.Main.StartServer(FsiEvaluationSession fsiSession, String fsiServerName)
   at Microsoft.FSharp.Compiler.Interactive.Shell.SpawnInteractiveServer@2376.Invoke(Unit unitVar0)

The same can be reproduced from a Command prompt without using Visual Studio. Just run the same command in a Command prompt window and the same exception occurs.

The originally installed version of F# that came with Visual Studio does not show this error and just returns with the SERVER-PROMPT>

**Comment by dsyme** [comment]
@SvetlanaZj Could you give exact step-by-step repro steps please?  For example

- which nuget package
- What do you mean by "pointing Visual Studio to the installation folder"
- which version of Visual Studio are you using?  Which version of the Visual F# Tools do you have - the default install or a nightly?

**Comment by SvetlanaZj** [comment]
Hi Don,

Sure, with pleasure. Thought it was clear, but then I assume you have not been able to reproduce the problem.

Here is a detailed step by step.

Precondition:

a) I have Visual Studio 2010 Pro with standard F# 2.0 which came with the installation. It was an expensive purchase but it is still adequate for my purposes, except when I wanted to start more seriously with F#. Of course, all updates and hotfixes are applied. The NuGet Package Manager is installed from the Visual Studio Gallery, version 2.8....

b) My computer is using Windows 7 Ultimate with all updates applied and all .net releases available up to today but starting from .net 2.0. There is no more installation of .net 1.1

Steps:

1) I installed the package ""fsharp.compiler.tools.4.1.23.nupkg" using the nuget package manager in Visual Studio as per the instructions. The install is on a project basis and for the project I was using. The project was correctly modified by the install.

2) I verified that the project was copiling correctly with the new F# version. The project was OK and everything works just fine as it should. No observations.

3) Next, I need to explain what but also why I am doing this step. I want to use fsi and also fsc in this package also in Visual Studio 2010 for all projects. In addition, I want to use the new fsi.exe also in the F# Interactive window. It is not convenient to download and install a copy of the nuget package for each project. In addition the IDE and F# interactive window still are working with F# 2.0. Moreover, I am using software restriction policies that do not allow execution in non-standard directories for non-priviliged users. This protects me from most - if not all - ransomware and other malware,

I know very well that there is no official way to install a newer compiler version for Visual Studio 2010. But both fsc.exe and fsi.exe in the package tools subdirectory can be used in a command window and work correctly as expected independently of the project in Visual Studio. All required assemblies are installed in the GAC and the native images are all there as well after the installation of the package.

I also know that the newer Visual Studio versions have better support and are more up to date but I am not ready to switch yet and I am not so impressed with the license models for the new Visual Studio versions. So I stick with VS2010 for the time.

F# is largely independent already and technically, I could not find any reason why it would not work with VS2010. So I copied the entire pachage directory (with the build, buildCrossTargeting and tools folders) to a permanent directtory (C:\Program Files\Microsoft F#\v4.1).

4) I modified the F# registry key used by VS2010 (HKLM\SOFTWARE\Microsoft\FSharp\2.0\Runtime\v4.0) to point to this directory (@="c:\\Program Files\\Microsoft F#\\v4.1\\tools") and updated the version number HKLM\SOFTWARE\Microsoft\FSharp\2.0\Runtime\v4.0\Install\InstallSuccess="4.4.1.0"

5) I modified the .fspproj file in the VS project to import the project from this new permanent folder where the tools are installed. Only the second line, the Import ... line was changed to:

 <Import Project="$(MSBuildExtensionsPath32)\..\Microsoft F#\v4.1\build\FSharp.Compiler.Tools.props" Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft F#\v4.1\build\FSharp.Compiler.Tools.props')" />
I verified that project was built correctly. Build, debug and run were all OK.

5) I opened a command shell window, added a PATH to C:\Program Files\Microsoft F#\v4.1\tools and then started the fsc compiler manually on a test project. Everything worked just fine.

6) In the same command window I started fsi.exe. The interpreter works fine. Absolutely no issues. I tested many F#4.0 additions and I checked which assemblies were loaded in the windows debugger (WinDbg). No observations. All assembly bindings in the fsi.exe process are correct in as far as I can understand.

7) I tesed VS2010 editor. It is accepting the F#4.0 syntax correctly and any new project (with modified template as in step 5) runs fine with F#4.0.

8) I started the F# interactive window in VS2010. It starts up fine, shows the initial prompt:

Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

>
but shortly after that:

Exception raised when starting remoting server.
System.TypeLoadException: Access is denied: 'Microsoft.FSharp.Compiler.Server.Shared.FSharpInteractiveServer'.
   at Sample.Microsoft.FSharp.Compiler.Interactive.Main.StartServer(FsiEvaluationSession fsiSession, String fsiServerName)
   at Microsoft.FSharp.Compiler.Interactive.Shell.SpawnInteractiveServer@2376.Invoke(Unit<mailto:Microsoft.FSharp.Compiler.Interactive.Shell.SpawnInteractiveServer@2376.Invoke(Unit> unitVar0)

I ignored the exception. the F# Interactive windows works fine. No issues found. Also copy from the IDE editor with <ALT>ENTER works fine. the F# Interactive window accepts and correctly responds to all input. I tried many code snippets from the F# 4.0 Language reference manual with <ALT>ENTER copy from the IDE editor. The F# Interactive windows correctly processes all code snippets with F#4.0 syntax and addtitions. Apart from the exception, I cannot see any issue.

9) I know the exception has nothing to do with Visual Studio, so I checked the command line that is used by Visual Studio to start the fsi process. This is:

"c:\Program Files\Microsoft F#\v4.1\fsi.exe" --fsi-server-output-codepage:65001 --fsi-server-input-codepage:65001 --fsi-server-lcid:1033 --fsi-server:FSIChannel_5160_912619280_1750851008  --optimize

10) In a command shell window I enter exactly this command. fsi starts and shows:

Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

SERVER-PROMPT>

and after a short delay:

Exception raised when starting remoting server.
System.TypeLoadException: Access is denied: 'Microsoft.FSharp.Compiler.Server.Shared.FSharpInteractiveServer'.
   at Sample.Microsoft.FSharp.Compiler.Interactive.Main.StartServer(FsiEvaluationSession fsiSession, String fsiServerName)
   at Microsoft.FSharp.Compiler.Interactive.Shell.SpawnInteractiveServer@2376.Invoke(Unit<mailto:Microsoft.FSharp.Compiler.Interactive.Shell.SpawnInteractiveServer@2376.Invoke(Unit> unitVar0)

11) I ran the same command but without the --fsi-server:FSIChannel switch. That is:

"c:\Program Files\Microsoft F#\v4.1\fsi.exe" --fsi-server-output-codepage:65001 --fsi-server-input-codepage:65001 --fsi-server-lcid:1033  --optimize

The result is that fsi starts up correctly:

Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

>
No exceptions raised.

Conclusion:

There is no functional problem that I can find at the moment except the exception. There should not be one and I cannot understand the consequences. But to me it proves that VS2010 is not the culprit. I also believe that the installation that I made works fine in principle.

Hence I raised the issue because I believe it is something in the fsi code that has to do with the fsi-server setup. I prefer not to guess further at this point but I believe it can be fixed. There does not seem to be a compelling reason why it could not work with VS2010 in the way that I described.

I would much appreciate your feedback and please do not hesitate if you need further info or if I can be helpful in any way.

I am happy to see the advances in the F# project and commitment of all involved !

Best regards,
Svetlana









----- Original Message -----

**Comment by dsyme** [comment]
@SvetlanaZj Thanks for the details.  Modifying a VS2010 install is an unsupported scenario - indeed TBH I think there are multiple such things happening here

**Comment by KevinRansom** [comment]
@SvetlanaZj you should try VS2017 community edition or VSCode with Ionide.  They are both quite nice.

**Comment by vasily-kirichenko** [comment]
Try VS Code. If it's too simplistic for your needs, try JetBrains Rider. I suggest to forget about VS 2017 - it's buggy and slow as hell and it's not getting better from update to update. If you truly need VS, try VS 2015 + Visual F# Power Tools addin, this combination is stable and works quite good.

**Comment by SvetlanaZj** [comment]
Thanks everyone for all your comments. Indeed I fear to use VS2017 since it has become an enormous download and installation for just about everything. So many things need to be loaded, I cannot even keep an overview of all that is offered and needed. I much prefer slim and efficient tools only for the purpose I need. I will have a look at your suggestions. Thanks for replying to me.

**Comment by vasily-kirichenko** [comment]
If you love slim tools, you will love VS Code for sure :)

**Comment by forki** [comment]
@SvetlanaZj Visual Studio Code and Ionide (http://ionide.io/) is a really great alternative to get the latest compiler goodies and also have a nice dev environment that is "free". I really like it and now spend most of my F# development in it. Also @Krzysztof-Cieslak is a very helpful maintainer
