### ISSUE TITLE
Debug in F# Interactive crashes VS2015 on FAKE script

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#365]
repro for me on Win 8.1 and VS 2015 CTP6 + latest F# from releases page:

clone https://github.com/fsprojects/Paket

set breakpoint in build.fsx and try to debug in F# Interactive:

![image](https://cloud.githubusercontent.com/assets/57396/7141562/bd1e90b6-e2d2-11e4-9224-e49d3e2a72af.png)

results in VS crash:

![image](https://cloud.githubusercontent.com/assets/57396/7141545/979caa62-e2d2-11e4-9b8c-f15402cf94be.png)

**Comment by latkin** [comment]
Same issue as https://github.com/Microsoft/visualfsharp/issues/291. Root cause is Roslyn bug, which has since been fixed, but which you don't get with the F# pre-releases.  It will work in next CTP.
