### ISSUE TITLE
Running tests with VS2017's test tools

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3655]
This is in part more of a question than a bug report. Has anybody ever tried running tests with Visual Studio's test tools?

If I try to run them (i.e. the `FSharp.Core.UnitTest` project), it says there are zero tests. It seems like it tries to find tests in the source, perhaps it doesn't understand F#, or Visual Studio's own test runner doesn't understand NUnit tests to begin with?

Just wondering. I usually use NCrunch (and still working on getting a solid configuration, which isn't trivial for a certain class of tests), but I wanted to do some comparisons with other test runners.

**Comment by dsyme** [comment]
@abelbraaksma Have you installed the VS test runner for NUnit?

**Comment by cartermp** [comment]
Closing old discussion, as after you do:

1. NUnit test runner
2. Solution build

You can use the test tools. I also group tests into playlists so that it's easier to handle.

**Comment by abelbraaksma** [comment]
@cartermp, I agree, while it would be nice if VS could somehow hint at this, the feature "an sich" works.
