### ISSUE TITLE
Units of measure code compiles, but throws FatalExecutionEngineError at runtime when compiled with Optimize=false

### ISSUE THREAD

**Issue by mjmckp** [Microsoft/visualfsharp#366]
The following code compiles fine.
```
open System

[<Measure>]
type foo

let works (xs: float<'u> []) flag =
    let inner = let zero = LanguagePrimitives.FloatWithMeasure 0. in fun x -> if flag then zero else x
    Array.map inner xs

let fails (xs: float<'u> []) flag =
    let inner = let zero = 0.<_> in fun x -> if flag then zero else x
    Array.map inner xs

[<EntryPoint>]
let main _ = 

    works [|1.<foo>|] true |> ignore
    
    fails [|1.<foo>|] true |> ignore

    0
```

However, when compiled and run with Optimize=false (note: the error does not occur with Optimize=true), the call to 'works' works fine, but the call to 'fails' (which differs only by using LanguagePrimitives.FloatWithMeasure 0. instead of 0.<_>) throws the following exception:

```
FatalExecutionEngineError occurred
Message: Managed Debugging Assistant 'FatalExecutionEngineError' has detected a problem in 'C:\dev\BugReport\bin\Release\BugReport.exe'.
Additional information: The runtime has encountered a fatal error. The address of the error was at 0x71a6a2b6, on thread 0x19748. The error code is 0xc0000005. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.
``

**Comment by yukitos** [comment]
I can repro on VS2013 F# 3.1 (Fsharp.Core, 4.3.1.0) only when compiling Debug configuration.

**Comment by yukitos** [comment]
I think that I can found simpler repro code:

````fsharp
open System

let ok () =
    let inner =
        let zero = 0.<_>
        zero
    inner

let ng () =
    let inner =
        let zero = 0.<_>
        fun x -> zero
    inner 0

[<EntryPoint>]
let main _ = 
    
    ok() |> ignore

    ng() |> ignore
    
    0
````

In this code, the line `fun x-> zero` inside `ng` function throws FatalExecutionEngineError exception.

**Comment by latkin** [comment]
I think this is the same as http://visualfsharp.codeplex.com/workitem/61.  It has been fixed in F# 4.0, which will be shipping with VS 2015.  I can repro in VS 2013/F# 3.1 but it works ok (and the assembly passes PEVerify) with VS 2015/F# 4.0 CTP.

Is it possible for you to move to F# 4.0?

**Comment by rojepp** [comment]
Johanns workaround in that original bug seems to work here too, simply inlining the function makes the app work:

```
let inline ng () =
    let inner =
        let zero = 0.<_>
        fun x -> zero
    inner 0
```

**Comment by yukitos** [comment]
Thank you for the info, @latkin and @rojepp .
It works fine for me :+1:

**Comment by mjmckp** [comment]
Ok, thanks a lot all!
