### ISSUE TITLE
Suggestion to close or update item in Visual Studio UserVoice about refactoring and renaming support

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3667]
I believe that this (providing moderate refactoring support, and implementing Power Tools) has been done and been completed. Considering the amount of votes and how Google brings you to that UserVoice issue, perhaps someone could change the status on that ticket, perhaps with someone "officially" summarizing some of the amazing things that have been added so far (rename of folders, drag/drop, rename of members, unions, classes, etc etc).

See: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/2213611-provide-refactoring-support-for-f-code

**Comment by Pilchie** [comment]
Thanks - @cartermp can you take care of this?

**Comment by cartermp** [comment]
Yep, I'll get to this next week.

**Comment by cartermp** [comment]
Done.

**Comment by abelbraaksma** [comment]
Great @cartermp, looks good 👍 :)

**Comment by cartermp** [comment]
I've been cleaning house a bit in there as well.
