### ISSUE TITLE
Possible overloads errors ranges are trimmed

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#3685]
When getting type check errors, possible overloads are shown as errors with trimmed ranges. What is the purpose of the trimming?
For me it looks like a bug as related errors should have the same range as the main one. Disabling trimming in code below makes producing correct error ranges.

https://github.com/Microsoft/visualfsharp/blob/841dc2c9b1d541b0f71dd0ce4102dc0c2090c29d/src/fsharp/symbols/SymbolHelpers.fs#L64-L70

https://github.com/Microsoft/visualfsharp/blob/841dc2c9b1d541b0f71dd0ce4102dc0c2090c29d/src/fsharp/symbols/SymbolHelpers.fs#L183-L187

https://github.com/Microsoft/visualfsharp/blob/841dc2c9b1d541b0f71dd0ce4102dc0c2090c29d/src/fsharp/symbols/SymbolHelpers.fs#L191-L194

Example code with trimmed errors for String constructor overloads:
```fsharp
module Say =
    let hello name =
        System.String(123) |> ignore 
```

**Comment by dsyme** [comment]
It was probably to stop the "PossibleOverload" error being chosen as the one to show in a mouse-hover error text

**Comment by auduchinok** [comment]
I'd like to improve it on the FCS side. I see two ways to do it:
* simplify overloads error messages and merge related errors into the main one
* make FCS return proper ranges so it would be up to clients what to do with them (a field telling that error is related may be added)

Is there any other cases besides possible overloads/constraints where related errors are produced?

**Comment by dsyme** [comment]
> Is there any other cases besides possible overloads/constraints where related errors are produced?

I don't think so but check the code.  However I think it's a useful concept in general and rolling into one error message would be hard

> make FCS return proper ranges so it would be up to clients what to do with them (a field telling that error is related may be added)
> remove mentions of Error List window (as errors may be presented differently in editors/IDEs)

I agree with these two - letting the IDE choose how to handle things should be an option.
