### ISSUE TITLE
Referencing a type provider requires IReflectableType (when running compiler with .NET Core)

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#3701]
See https://github.com/Microsoft/visualfsharp/pull/3658#issuecomment-334773415

Basically, when the F# compiler runs on .NET CoreApp 2.0 it effectively requires that all System.Type have an implementation of IReflectableTYpe.  But we have no reasonable way to implement that interface. That requirement seems to be coming from uses of GetTypeInfo in FSharp.Core.dll (though hopefully not anywhere else)

Specifically, if we enable ``netcoreapp2.0`` as a test target here: https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/132/files#diff-ac663ab43267f2bdb3a22e804b6c9af6R4 then tests fail

![image](https://user-images.githubusercontent.com/7204669/31283908-e7a4cd36-aaae-11e7-8097-884d5ff937f2.png)

**Comment by dsyme** [comment]
It is possible that the fix is to avoid the use of GetTypeInfo in FSHarp.Core.  

If so, that will almost certainly require making a .NET Standard 2.0 version of FSharp.Core (since AFAIK GetTypeInfo is a legacy thing from .NET Standard 1.x)

**Comment by KevinRansom** [comment]
@dsyme it's urgency soon.  It's not a regression, this has never worked on coreclr, it's a missing feature.

**Comment by dsyme** [comment]
This has been fixed via recent work in the Type Provider SDK https://github.com/fsprojects/FSharp.TypeProviders.SDK/
