### ISSUE TITLE
[From VSTS] Semantic highlighting is off for precision formatting

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3703]
![format-bad](https://user-images.githubusercontent.com/6309070/31303834-83e2de44-aac9-11e7-8f69-3d5f654db830.PNG)

Note that the first line loses the teal coloring for `%.`.  This seems to be caused when `.` is encountered.

**Comment by abelbraaksma** [comment]
> This seems to be caused when . is encountered.

True, but at any level, i.e., `%1.5f` also colors incorrectly.
