### ISSUE TITLE
Error highlighting takes 12 seconds to update

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3707]
![1](https://user-images.githubusercontent.com/873919/31309313-d50dcafe-ab8c-11e7-8f80-ff53f1a5a97a.gif)

**Comment by vasily-kirichenko** [comment]
Ionide is able to do the same job in about 3 seconds:

![1](https://user-images.githubusercontent.com/873919/31309468-5f674c50-ab8f-11e7-9118-ab7a002198d5.gif)

**Comment by vasily-kirichenko** [comment]
Rider is even faster:

![1](https://user-images.githubusercontent.com/873919/31309675-e7e4e940-ab92-11e7-86b8-b3024c04f1ed.gif)

**Comment by vasily-kirichenko** [comment]
CPU is hardly loaded at all:

![1](https://user-images.githubusercontent.com/873919/31309833-8d078836-ab95-11e7-88d7-ea57bc5d4ebe.gif)

**Comment by dsyme** [comment]
Yeah, it's not CPU perf. It's sure to be a combination of Roslyn choices, ordering of analyzers, ordering of which files are updated, and other delays.   

You might also want to check if turning off in-memory project references makes a difference

**Comment by vasily-kirichenko** [comment]
12 seconds was with this settings:

![image](https://user-images.githubusercontent.com/873919/31310478-c026cec8-aba1-11e7-925b-d364562a2645.png)

**Comment by vasily-kirichenko** [comment]
OK, switching off Simplify Name analyzer makes error highlighting work as fast as Ionide (~3 seconds).

@dsyme I'm afraid you added some `Async.Sleep`s in the analyzer loop, it may cause this behavior (no CPU load, long delay).

**Comment by vasily-kirichenko** [comment]
https://github.com/Microsoft/visualfsharp/pull/3708

**Comment by vasily-kirichenko** [comment]
I think it's clear now that Simplify Name analyzer is executed _before_ document diagnostics analyzer.

**Comment by dsyme** [comment]
Yes. Note that SimplifyName is off by default, see this:
```
            { // We have this off by default, disable until we work out how to make this low priority 
              // See https://github.com/Microsoft/visualfsharp/pull/3238#issue-237699595
              SimplifyName = false 
```

**Comment by dsyme** [comment]
@vasily-kirichenko My understanding is that removing the delays doesn't solve this problem, since my understanding is that the SimplifyName analysis process can take considerable time (it makes many FCS requests) - at least adding a few seconds.  Fundamentally we need Roslyn to support high-priority analyzers

**Comment by saul** [comment]
@dsyme how does C#/VB inform the IDE of IntelliSense errors? I've always thought we're not using the correct mechanism.

**Comment by dsyme** [comment]
@saul I don't the details. I assume we're using the right mechanism considering we're sitting on top of Roslyn

**Comment by dsyme** [comment]
Since SImplifyName is off by default I'm going to close this
