### ISSUE TITLE
Wrong completion items for location

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#3709]
https://github.com/YaccConstructor/YaccConstructor/blob/67b6a137f8fc1d4d116316e15fd497227fc32c5a/src/RIGLRGenerator/RIGLRGenerator.fs#L23
When trigger completion inside `Split` identifier, FCS gives members from Array type instead of string.

**Comment by vasily-kirichenko** [comment]
No bug:
```fsharp
let args = ""
let args1 = args.Split([|' '|])
```

Bug:
```fsharp
let args = ""
let args = args.Split([|' '|])
```
Looks like it uses the type of resulting `args` instead of the string `args` if the names are equal.
