### ISSUE TITLE
Completion commits on brackets and pipes

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3717]
Typing the following:

```fsharp
let xs = [1..10
```

Will bring up `log10` in completion (which is perfectly fine).  However, Typing `]` to finish to expression will commit `log10` instead of `10`.  Same with `|` if this were an array.  This can be annoying if you're doing data sciency/heavily numeric tasks.

**Comment by vasily-kirichenko** [comment]
I think it works as expected, because you may want to type, say, [1..log10 x |> int]

**Comment by vasily-kirichenko** [comment]
Ah, you are talking about committing, not auto popping up. You are right.
