### ISSUE TITLE
Send to FSI / send line to FSI commands is not presented in settings, the latter does not work

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3724]
![image](https://user-images.githubusercontent.com/873919/31379495-165a9d4e-adb7-11e7-81b1-d7f21ed12e2f.png)

**Comment by isaacabraham** [comment]
Funnily enough I just came up against this this morning. It's `EditorContextMenus.CodeWindow.ExecutiveInInteractive` now.

**Comment by vasily-kirichenko** [comment]
Thanks! :)
