### ISSUE TITLE
VS 15.4 and still having no F# features from time to time

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#3730]
![image](https://user-images.githubusercontent.com/57396/31444112-883e51dc-ae9b-11e7-8221-583642887c62.png)

@KevinRansom I fear the "no F# support" bug is not fixed

**Comment by 0x53A** [comment]
dupe https://github.com/Microsoft/visualfsharp/issues/3222

**Comment by forki** [comment]
Sorry I thought it was claimed as fixed. Anyway it's still in 15.4 happening

**Comment by 0x53A** [comment]
Well, the more people make noise, the better...

**Comment by forki** [comment]
I'm telling @cartermp at least every week. since the first time I saw it ;-)

**Comment by 0x53A** [comment]
``¯\_(ツ)_/¯``

**Comment by forki** [comment]
Exactly

Am 11.10.2017 16:55 schrieb "Lukas Rieger" <notifications@github.com>:
