### ISSUE TITLE
No way to add a new file to correct position in VS 15.5

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#3740]
#### Repro steps

1. git clone https://github.com/SAFE-Stack/SAFE-BookStore.git
1. open solution
1. Try to add a file to src/Server/Server.fsproj to a specific location

#### Expected behavior

* Right click on any file allows you to add a new file above or below

#### Actual behavior

Only folder and project nodes allow to add new files. And they are always added to the top of the childs of that node.

#### Known workarounds

Add a file to the project and edit fsproj manually

**Comment by cartermp** [comment]
Closing in favor of https://github.com/dotnet/project-system/issues/2887
