### ISSUE TITLE
Recursive functions defined inside computation expressions fail after installing VS 15.5 preview 1

### ISSUE THREAD

**Issue by dhwed** [Microsoft/visualfsharp#3743]
After installing VS 15.5 preview 1, this fails:

```fsharp
[<EntryPoint>]
let main argv =
    let factorials =
        [ for x in 0..10 do
            let rec factorial x =
                match x with
                | 0 -> 1
                | x -> x * factorial(x - 1)
            yield factorial x
        ]

    for f in factorials do printf "%i" f
    
    0 // return an integer exit code
```

![image](https://user-images.githubusercontent.com/10184638/31523333-658ababc-af78-11e7-8b63-444ee066aef2.png)

This happens even in VS 15.4 now.

**Comment by dsyme** [comment]
@dhwed Oh wow, that's a regression. The culprit will be https://github.com/Microsoft/visualfsharp/pull/3536

**Comment by dsyme** [comment]
@cartermp I'll start on these regressions tomorrow (particularly this one)

**Comment by dsyme** [comment]
Workaround 1 - in this case compiling in "Release" mode makes NRE go away

Workaround 2 - lift the ``let rec`` out of the list/array/sequence expression, adding any captured variables as arguments

**Comment by dsyme** [comment]
Fixed by undoing the fix, When we fix the fix it will all be fixed
