### ISSUE TITLE
Quoted function name clashes with DU Pattern ID

### ISSUE THREAD

**Issue by xenocons** [Microsoft/visualfsharp#375]
Hello,

I am not sure if this is a bug, or an issue localised to me, or perhaps it is meant to be this way (or I am just doing something stupid).

```
    let ``TEST`` = id

    type XXXX = 
        | A
        | TEST
    
    let lookup = function   
        | A -> Some id
        | TEST -> Some ``TEST``
```

On the last line, the error is: error FS0001: This expression was expected to have type
    'a -> 'a    
but here has type
    XXXX    

I would have expected this to compile, but it seems that the DU XXXX is overriding the function \`\`TEST\`\`, is this normal and expected?
Edit: tried to update function name

**Comment by enricosada** [comment]
moved from fsharp/fsharp/issues/402 ( so is linked :smile: )

**Comment by enricosada** [comment]
i think the binding remove the backticks

```fsharp
> let ``TEST`` = id;;

val TEST : ('a -> 'a)
```

both are valid

```fsharp
> TEST;;
val it : ('a -> 'a) = <fun:clo@4-1>
> ``TEST``;;
val it : ('a -> 'a) = <fun:clo@5-2>
```

but inside DU are not

**Comment by xenocons** [comment]
@enricosada thank you.

I think if this is a language use case then a warning should be added that advises that something with the same name is already bound? This would be consistent then with how double binding errors are surfaced to the user.

**Comment by enricosada** [comment]
@xenocons i think is a bug, but depends on fsharp spec ( /cc @dsyme ) if identfier ``TEST`` = TEST 

The error is ok, like if you write without backticks

```fsharp
 let lookup = function   
        | A -> Some id
        | TEST -> Some TEST
```
this is an error because ``A -> (a -> a) option`` and ``TEST -> XXXX option``

But **with backticks** the compiler should infer the correct binding

I think the compiler search the identifier without backticks, like my test with fsi

**Comment by latkin** [comment]
There is no difference between a backticked identifier and a "regular" identifier, all that matters are the characters within.  Once the identifier has been parsed, the backtick information is essentially thrown away, AFAIK.

So the provided code is equivalent to

```fsharp
    let TEST = id

    type XXXX = 
        | A
        | TEST

    let lookup = function   
        | A -> Some id
        | TEST -> Some TEST
```

Which follows normal shadowing rules and gives an error as expected.  Note that it works the other way, too - you can consume non-backticked guys even if you add backticks:

```fsharp
let dude = 42
let sweet = ``dude`` + 10
```

**Comment by enricosada** [comment]
make sense :smile: 

> spec
>>
```
regexp ident-text = ident-start-char ident-char*
token ident =
  | ident-text  	For example, myName1
  | `` ( [^'`' '\n' '\r' '\t'] | '`' [^ '`' '\n' '\r' '\t'] )+ `` 
               		For example, ``value.with odd#name``
```
>>Any sequence of characters that is enclosed in double-backtick marks (\`\` \`\`), excluding newlines, tabs, and double-backtick pairs themselves, is treated as an identifier. Note that when an identifier is used for the name of a types, union type case, module, or namespace, the following characters are not allowed even inside double-backtick marks:
‘.', '+', '$', '&', '[', ']', '/', '\\', '*', '\"', '`'

>identifier
>>A sequence of characters that is enclosed in \`\` \`\` double-backtick marks, excluding newlines, tabs, and double-backtick pairs themselves.

i read the spec, but didn't understood \`TEST\` = TEST

**Comment by latkin** [comment]
Thanks for the relevant spec passage @enricosada. I guess the key bit is "excluding ... double-backtick pairs themselves".
