### ISSUE TITLE
Build_CI2 times out from time to time

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#3764]
This makes CI unreliable

**Comment by cartermp** [comment]
Closing this for now, as it I haven't seen this happen after a few rounds of updates to CI

**Comment by PatrickMcDonald** [comment]
Thus is still happening as of last week

https://github.com/Microsoft/visualfsharp/pull/4038

**Comment by cartermp** [comment]
We can reopen this if it reliably times out. More often than not, the issue is environmental and out of our control.
