### ISSUE TITLE
Broken FSharp.Compiler.Private project file

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3768]
https://github.com/Microsoft/visualfsharp/commit/80b8c9e1b72e72cc9793133941b2396ed20d91b8#diff-7716f59c2f64afbb5bd4b2ac20ebdc8dR51 results with this:

![image](https://user-images.githubusercontent.com/873919/31720836-5a9fe8c8-b420-11e7-9418-c1aeca44163e.png)

/cc @brettfo

**Comment by vasily-kirichenko** [comment]
And

![image](https://user-images.githubusercontent.com/873919/31721238-84609710-b421-11e7-86ab-69947b3dd347.png)

Everything builds successfully, it just looks weird in VS.

**Comment by cartermp** [comment]
cc @brettfo @KevinRansom
