### ISSUE TITLE
Find All References does not work on any but local symbols

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3774]
Open VFT solution.
Open `InlineRenameService.fs`
Execute "find all references" on any non-local symbol, like "Solution", "Document", "FSharpChecker", etc.
Result: no references found.

**Comment by cartermp** [comment]
Seems to work now.

![image](https://user-images.githubusercontent.com/6309070/36221273-6e7807ea-1172-11e8-934e-9fd3cfa0d084.png)

![image](https://user-images.githubusercontent.com/6309070/36221300-86f44946-1172-11e8-98d3-b1bf32ac7f36.png)

![image](https://user-images.githubusercontent.com/6309070/36221446-fcd2cc6e-1172-11e8-899d-5615a2497cdb.png)
