### ISSUE TITLE
Nothing works in VisualFSharp.Unittests project

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3779]
![image](https://user-images.githubusercontent.com/873919/31786438-293991f2-b511-11e7-9698-f9224003470a.png)

**Comment by vasily-kirichenko** [comment]
On latest nightly (October, 17th).

**Comment by vasily-kirichenko** [comment]
It seems it works on the project from what the first file is opened. On all other projects ^^^.

**Comment by cartermp** [comment]
The project has language service lightup on the 15.5 release. Closing.
