### ISSUE TITLE
[15.5 Preview 2] VS may crash when opening F# .NET Core/Standard templates

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3802]
**Note:** The severity of this is low given that this is a preview and we already have a fix.  The fix will be in the next update to 15.5.

1. Install VS 2017 15.5 **Preview 2**.
2. Install the .NET Core development workload **only**.
3. Open VS and create a new F# + .NET Core SDK-based project.

Observe that VS may crash, depending on your machine.  It is a race condition.  We've already authored a fix and can verify that it does not reproduce there.  To get that fix, will need to subscribe to the new "F# Preview Nightly" feed here: https://dotnet.myget.org/F/fsharp-preview/vsix

To clarify, this nightly release channel is **only** for when you are using a **Preview** version of Visual Studio.  It is not intended to be used with a mainline release of VS 2017.  Note that the fix in this channel will get #3799 to reproduce, but it unblocks this specific issue.

**Comment by KevinRansom** [comment]
This has been resolved in the latest previews.  Closing
