### ISSUE TITLE
NetSDK Project--- errors list contains erroneous err

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#3813]
repro:
__In VS:__
1.  Create new dotnet console app
2.  Add netstandard class library project
3.  Set reference from console app to netstandard classlibrary
4.  add line similar to:  ClassLibrary1.Say.hello "Hello"
5.  Select ErrorList observe error message

__Desktop projects work as expected__

Expected no errors in error list.

![image](https://user-images.githubusercontent.com/5175830/31969708-761484de-b8ca-11e7-82ac-de811fc50db3.png)

**Comment by Xiu-Li** [comment]
Tested on latest d15.6/27222.00, this issue **still repro**.

**Comment by Xiu-Li** [comment]
@cartermp @KevinRansom 
The bug is closed, should the issue be fixed? But I can still repro it on latest d15.6 build.

**Comment by cartermp** [comment]
@Xiu-Li It seems this was accidentally closed and duped to #3952.
