### ISSUE TITLE
Performance analysis of the language service

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3820]
This is a tracking issue.

We will be doing significant performance analysis of the language service, then act on those investigations.  This will be a long-term effort, and this issue will be updated with findings as the work is done.  It will link out to more specific issues as they are created.

**Comment by dsyme** [comment]
Closing old issue

**Comment by abelbraaksma** [comment]
This thread looks a bit as if there was no action taken, but I think that's not true, I'm history I can see many commits relating to language service and performance. Just to say that this issue wasn't closed with no action, the opposite is true ;)
