### ISSUE TITLE
IDE seems to have trouble with AspNetCore library

### ISSUE THREAD

**Issue by lambdakris** [Microsoft/visualfsharp#3822]
I am not sure how much support VS 2017 Version 15.4.1 has for .NET Core F# projects but I figured I'd log this just in case, since it seems to work for most .NET Core libraries but is stumbling on ASP.NET Core for some reason. The problem is that the IDE reports that "The namespace 'AspNetCore' is not defined" even though all of the other .NET Core libraries open without a problem.

#### Repro steps

Provide the steps required to reproduce the problem

1. Create project 
```
dotnet new web -lang f# -o HelloWeb
```

2. Manually restore packages for posterity
```
cd HelloWeb
dotnet restore
```

3. Open project in Visual Studio 2017

4. Open Program.fs file and notice the error "The namespace 'AspNetCore' is not defined"

#### Expected behavior

I would expect that the ASP.NET Core library would open like any other .NET Core library

#### Actual behavior

I find that the ASP.NET Core library does not open like all the other .NET Core libraries (of course, I have not tried ALL the other .NET Core libraries, but I have tried Newtonsoft.Json and IdentityServer4, and those open fine)

#### Known workarounds

None that I can think of...use VS Code I guess...

#### Related information 

Windows 10 1709
VS 2017 Community Version 15.4.1
.NET Core 2.0

**Comment by cartermp** [comment]
@lambdakris There's no support for these project types in 15.4.1, but we are targeting that support in 15.5.  Using Preview 2 bits, your scenario works:

```
mkdir Test && cd Testy
dotnet new sln
dotnet new web -lang F# -o Testy
dotnet sln add Testy/Testy.fsproj
.\Testy.sln
```

...wait for VS project system to compute references, etc.

Open `Program.fs`, wait for semantic colors to kick in:

![helloweb-works](https://user-images.githubusercontent.com/6309070/32030200-49e2079e-b9ae-11e7-9e20-2ce27f037309.PNG)
