### ISSUE TITLE
NetSDK project references to C# not working

### ISSUE THREAD

**Issue by dhwed** [Microsoft/visualfsharp#3829]
I'm testing a NetSDK F# project that has a reference to a NetSDK C# project, both targeting .NET Framework  4.6.1.  Builds work fine, but the tooling (Intellisense, Go To Definition, etc..) is not working.

I'm using VS 15.5 preview 2 with a vsix compiled from 4c19c4297229fd63e61344afaf6b25630379cf3e.

![image](https://user-images.githubusercontent.com/10184638/32060872-adb4f8f8-ba35-11e7-8a28-6eba1365e31f.png)

Here's the error:

Error	FS3160 Problem reading assembly 'D:\Code\Refs\CSharpLib\bin\Debug\net461\CSharpLib.dll': Build was not evaluated, expected the results to be ready after 'Eval' (`GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 1007; Id 1008; Id 1009; Id 1010; Id 1011|], Id 1013,
 false, None)`).

**Comment by cartermp** [comment]
That error is the same as #3798, but not on VisualFSharp.sln.  I wonder if it's related to #3813 as well, though the `Build was not evaluated, expected the results to be ready after 'Eval' ` message makes me believe that it's not.

**Comment by dhwed** [comment]
@KevinRansom I'm not quite sure that I'm testing this correctly, but I applied your changes from #3833 to my C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\Microsoft.FSharp.Targets file and I am still having this issue with C# references.

**Comment by KevinRansom** [comment]
@dhwed I will look at this over the weekend.  This pretty much needs to work.

**Comment by KevinRansom** [comment]
@dhwed 

Thanks for the report, I have an inkling what it might be, more like a theory I suppose.

Since the C# project is a project, I tell the F# compiler service about the project reference, however, since it is not an F# project the compiler service is clueless about what is inside.

Kevin

**Comment by KevinRansom** [comment]
@dhwed 
so ... here is a PR for part of this:  https://github.com/Microsoft/visualfsharp/pull/3858

The current desktop project system for F# works in this scenario when the referenced project is already built and there is an assembly to read metadata from.  This PR enables this.

Roslyn apparently has a mechanism based on "Metadata Projects" which will allow a project to reference a project that is not yet built and collect it's metadata ... I currently don't know how this magic all works, but I guess I am going to be learning it over the next short while :-)

Once we have figured out how to plumb that into the FCS it should be possible to reference a C# or VB project that is not yet built and have intelli-sense and the other groovy stuff working for it.

Kevin

**Comment by dhwed** [comment]
This is working great; thanks.

We now finally have `<PackageReference>`s and a fast up-to-date checker for F# in VS.
