### ISSUE TITLE
Class with [<AllowNullLiteral(false)>] barred from inheriting from normal non-nullable class

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#383]
Super minor, but might as well log it. Up for grabs.

I would think this code should be legal

```fsharp
type A() = class end

[<AllowNullLiteral(false)>]
type B() = inherit A() // error FS0935: Types with the 'AllowNullLiteral' attribute may only inherit from or implement types which also allow the use of the null literal
```

The check makes sense, but fails to consider the case when the attribute explicitly *disallows* nulls. I made the same mistake in #376.

Fix is to change `hasAllowNullLiteralAttr` in tc.fs to actually check the value of the attribute, something like `TryFindTyconRefBoolAttribute cenv.g m cenv.g.attrib_AllowNullLiteralAttribute thisTyconRef = Some(true)`.  [That is around line 13985 of tc.fs, unfortunately GH won't render that many lines so I can't link directly to it :sob:]

**Comment by mexx** [comment]
@latkin I want to look into it, can you point me the right place where a test for this case should be placed?

**Comment by mexx** [comment]
I've found some tests covering `AllowNullLiteralAttribute`:
 * in `test-hw.fsx`, the positive ones
 * in `neg16.fs`, the negative ones
 * in `E_AllowNullLiteral02.fs`, as well positive as negative ones

**Comment by latkin** [comment]
Adding some cases to `tests\fsharp\typecheck\sigs\neg16.fs` seems like the right place, maybe also add to one of the `pos*.fs` guys for non-error cases.
