### ISSUE TITLE
suggest: Tuple Field Metadata

### ISSUE THREAD

**Issue by greatim** [Microsoft/visualfsharp#3830]
https://github.com/fsharp/fslang-design/blob/master/FSharp-4.1/FS-1006-struct-tuples.md,
in the section **Possible Extension: Tuple Field Metadata**
> e.g.

>`let f () = struct (x=1,y=1)`

It's hard to  distinguish if 'x=1' is a bool or a int named 'x' .

I suggest to add the metadata into the signature of function.
e.g.
`let f(): struct(x: int * y: int) = struct(1, 1)`

**Comment by cartermp** [comment]
This seems like it would be best to have this issue here: https://github.com/fsharp/fslang-suggestions/issues

Could you create a corresponding issue there?  Thanks!
