### ISSUE TITLE
No new item templates

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3837]
15.4 + nightly from Oct, 17.

Click on a source file in a project, choose "add below -> new item".

Result:

![image](https://user-images.githubusercontent.com/873919/32092815-b5f8f23a-bb02-11e7-89be-001cd283af65.png)

**Comment by KevinRansom** [comment]
Thanks, for this.  We had to refactor the installer when adding the dotnet templates, I think I probably refactored a bit too hard.  The Item templates should always be installed with VisualFSharp.

**Comment by KevinRansom** [comment]
Should appear in next nightly

**Comment by vasily-kirichenko** [comment]
There are no templates in 15.5 preview 2.

Is it expected?

**Comment by cartermp** [comment]
Yes, this is to be expected.  #3840 has this fixed and should be in one of the next previews.
