### ISSUE TITLE
Smart indent and auto-deindent doesn't work on VSIX built from master

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3848]
![indent-deindent-no-worky](https://user-images.githubusercontent.com/6309070/32199742-2c820330-bd8b-11e7-9098-90a2c0042d89.gif)

**Comment by saul** [comment]
How is that possible? There are tests that assert it works. What's your indent style set to?

**Comment by cartermp** [comment]
🤦‍♂️ it looks like my editor was changed to Block instead of Smart.  Which is so strange, considering that it's been set to Smart for _ages_ across countless uninstall/reinstall of the tools for months.
