### ISSUE TITLE
Nightly breaks VS installation

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3852]
1. Try to update the nightly.
2. It fails with something like "this addin is already installed into this SKU"
3. Launch VS
4. Result

![image](https://user-images.githubusercontent.com/873919/32213154-2e6e61ca-be2b-11e7-9a05-0ce7ad6df648.png)

**Comment by cartermp** [comment]
@brettfo @KevinRansom could this be due to recent changes to pull in 15.5/15.6 changes into master?

**Comment by vasily-kirichenko** [comment]
What's strange is that Ctrl+F5 on master works on 15.4.1

**Comment by vasily-kirichenko** [comment]
So it's something with the nightly VSIX (which is not the same as OSS VSIX I think).

**Comment by KevinRansom** [comment]
On it.

**Comment by brettfo** [comment]
Neither @KevinRansom nor I are seeing this failure.  @vasily-kirichenko can you send us your ActivityLog.xml?  If you prefer you can email it directly to me (my email address is on my profile.)

On a related note we did see that project templates are gone, and that's to be expected because we recently re-factored out a `VisualFSharpTemplate` package that has them.  We're working now on publishing that VSIX to unblock project creation for nightly users.

**Comment by rojepp** [comment]
I have this problem too. Two errors in ActivityLog: 

> Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.VisualStudio.CodeSense, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
          C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\EXTENSIONS\HOEK2K44.0U3\Microsoft.VisualStudio.ApplicationInsights.dll

and 

> LegacySitePackage failed for package [FSharpPackage]Source: 'Microsoft.VisualStudio.Composition' Description: Expected 1 export(s) with contract name "Microsoft.VisualStudio.FSharp.Editor.SettingsPersistence+ISettings" but found 0 after applying applicable constraints. Microsoft.VisualStudio.Composition.CompositionFailedException: Expected 1 export(s) with contract name "Microsoft.VisualStudio.FSharp.Editor.SettingsPersistence+ISettings" but found 0 after applying applicable constraints. at Microsoft.VisualStudio.Composition.ExportProvider.GetExports(ImportDefinition importDefinition) at Microsoft.VisualStudio.Composition.ExportProvider.GetExports[T,TMetadataView](String contractName, ImportCardinality cardinality) at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T,TMetadataView](String contractName) at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T](String contractName) at Microsoft.VisualStudio.Composition.ExportProvider.GetExport[T]() at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]() at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]() at Microsoft.VisualStudio.FSharp.Editor.FSharpPackage.Initialize() at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)

[ActivityLog.xml.zip](https://github.com/Microsoft/visualfsharp/files/1434044/ActivityLog.xml.zip)

**Comment by cartermp** [comment]
Closing this for now, as this may have just been a bad nightly
