### ISSUE TITLE
With .NET Core SDK-based projects, Go to Implementation invokes Find All References (and in a weird way)

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3853]
1. Create a new F# Standard Library
2. Right click on the usage of `name` to open the context menu and choose 'Go to Implementaiton'

**Expected:** It goes to the definition of the `argv` symbol.

**Actual:**

![go-to-impl-bug](https://user-images.githubusercontent.com/6309070/32248398-d415d10a-be42-11e7-8a75-4cf08d38d3ca.PNG)

**Comment by vasily-kirichenko** [comment]
Isn't this the standard VS behavior if we return more than one definition

**Comment by cartermp** [comment]
On 15.5 Preview 2, it goes to definition on `argv` with .NET Framework projects.

Although I'd argue that it doesn't really make sense for it to do anything given that we don't implement Go to Implementation in F#.

**Comment by ylibrach** [comment]
It seems that this is "fixed" and that Go To Implementation now performs the same function as Go To Declaration. However, this is obviously still not the desired behavior and serves no real purpose. Is there any update to having Go To Implementation work correctly within Visual Studio?
