### ISSUE TITLE
Remaining work for F# 4.0

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#386]
We are at the tail end of the Visual F# 4.0 development cycle, but there is still work to be done.  Below, I've shared the remaining test/lockdown items that need to be completed as we approach the finish line.

Some of this needs to be done using internal tools or resources, but much of it would benefit from help by the community.  I've tried to make it clear where we would love help.

As this work gets done, I'll try to keep the check boxes up to date so we can see progress :-)

------

- [x] Finish up remaining small features
	- Complete, final feature work has been merged
- [x] Bug fixing
	- Bug fixes and low-risk performance improvements will continue to be welcome until the very end
	- There are still [up for grabs issues](https://github.com/Microsoft/visualfsharp/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22up+for+grabs%22) available!
	- *Action*:
		- [x] Fix bugs: **everybody**
- [x] Focused test pass at downlevel F# targeting
	- We have historically found downlevel F# targeting to be a high-risk scenario:
		- Using vCurrent compiler to interact with vPrevious runtime
			- Consuming libraries built with F# 3.1- from F# 4.0
			- Using F# 4.0 to create libraries targeting F# 3.1-
		- Using vPrevious compiler to consume output of vCurrent compiler
			- Using F# 3.1- to reference libraries built in F# 4.0
    - Lots of runtime and compiler changes for 4.0 => particularly high risk
    - *Action*:
	    - [x] Test your libraries and apps in cross-targeting situations: **everybody**
	    - [x] Coverage via test automation: @latkin
- [x] Fix up internal IDE tests
	- We have decent IDE scenario tests that are still closed-source
	- They have bit-rotted somewhat during F# 4.0 development
	- *Action*:
		- [x] Get the test up and running again: @latkin
		- [ ] Add any appropriate new tests: @latkin
- [x] Final all-up test pass
	- Run-through of all test automation on top OSes: Win7, Win8.1, Win10
	- Spot check of various key end-to-end scenarios
		- Project upgrade/round-trip
		- Express SKUs
		- Type provider dialog
	- *Action*:
		- [x] Test automation on supported OSes: @latkin
		- [x] Trying out end-to-end scenario: **everybody**
- [x] Check-offs for internal release criteria
	- Lots of Microsoft-internal tools and release criteria that need to be tracked and handled
		- Localization
		- Security
		- Accessibility
		- etc
    - *Action*:
	    - [x] Track these: @KevinRansom
	    - [x] Follow up with fixes/mitigations: @KevinRansom

**Comment by theoy** [comment]
Nice writeup, Lincoln :+1: :smile:.

Definitely looking forward to wrapping up the first release of F# 4!
