### ISSUE TITLE
Wrong "Open declaration can be removed" when type is in AutoOpen-ed module

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#3862]
`File1.fs`:

```f#
namespace Test1

module NotAutoOpened =

  type Foo =
    | Bar
    | Baz

[<AutoOpen>]
module AutoOpened =

  type Latin =
    | Lorem
    | Ipsum
```

`File2.fs`:

```f#
namespace Test2

module Test =
  
  open Test1.NotAutoOpened

  let foo = Bar

module Test_AutoOpened =

  open Test1

  let latin = Lorem
  ```

`open Test1.NotAutoOpened` in module `Test` works fine, but `open Test1` in module `Test_AutoOpened` gives a false "Open declaration can be removed":

![image](https://user-images.githubusercontent.com/7766733/32315070-ef80592e-bfaa-11e7-8753-37ddccdc0797.png)

VS 15.4.2, running a VF# branch based on https://github.com/realvictorprm/visualfsharp/tree/codelens.

**Comment by vasily-kirichenko** [comment]
Fixed on master I believe. Add a test into https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/tests/unittests/UnusedOpensTests.fs to be sure.

**Comment by cmeeren** [comment]
Can't figure out exactly how those tests work. Can someone else add the test?

**Comment by vasily-kirichenko** [comment]
for example,

[<Test>]
let ``unused open declaration in top level module``() =
    """
module TopModule
open System
open System.IO
let _ = DateTime.Now
"""
    => [ 4, (5, 14) ]

checks that it should detect single unused open on line 4 (lines starts from 2 here), from column 5 to column 14 ("System.IO").

**Comment by cmeeren** [comment]
> lines starts from 2 here

Ah, that clears things up a bit.

**Comment by cmeeren** [comment]
I can confirm this is *not* fixed in the latest nightly.

**Comment by vasily-kirichenko** [comment]
Minimal repro:

```fsharp
namespace Ns

module M1 =
    [<AutoOpen>]
    module AutoOpened =
        type T() = class end

module M2 =
    open M1
    let _ = T()
```

![image](https://user-images.githubusercontent.com/873919/32688310-485fa0fa-c6df-11e7-8d2a-b3f9d7ec162c.png)

It does not reproduce if a value is used instead of a type (`T`).

**Comment by vasily-kirichenko** [comment]
I cannot reproduce it on current master. 
@cmeeren could you recheck?

**Comment by vasily-kirichenko** [comment]
Added a test https://github.com/Microsoft/visualfsharp/pull/3930

**Comment by cmeeren** [comment]
Unable to reproduce on latest nightly, so I guess it is fixed after all. :)
