### ISSUE TITLE
Incorrect lines with portable PDBs

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#3868]
There is something incorrect with portable PDB line numbers (or the debugger consuming them)

Here’s the sort of problem I’m seeing.  I add this explicit Break()
![a](https://user-images.githubusercontent.com/7204669/32343556-c8a9610a-bffb-11e7-8446-143a6b5fe41e.png)

 

And the break gets shown as here:

 
![b](https://user-images.githubusercontent.com/7204669/32343558-cb0ff72e-bffb-11e7-9cbf-e02aa06d0611.png)

So there is something messed up with how we are emitting line numbers for portable PDB

I don’t yet have a small repro yet though it’s 100% in ProvidedTypes.fs from the TPSDK

![image](https://user-images.githubusercontent.com/7204669/32343581-deead520-bffb-11e7-932d-c22e24d8f817.png)

**Comment by dsyme** [comment]
This is code compiled using the F# compiler that got installed as part of 15.3.0 - so perhaps there was a bug fix since then
```
  C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\fsc.exe -o:obj\Debug\netstandard2.0\ComboProvider.dll
  -g
  --debug:portable
```

**Comment by KevinRansom** [comment]
@dsyme I expect I can repro something like this with the compiler dll too.  

I will take a look.

**Comment by dsyme** [comment]
I think this was a problem with 15.3 that must have been fixed.  I've moved all my machines to 15.4 and haven't been seeing the problem.  Will reopen if I see it again
