### ISSUE TITLE
Preview Selected Item does not work on .NET Core projects

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3869]
15.5 preview 2

![1](https://user-images.githubusercontent.com/873919/32343771-bb634104-c015-11e7-82da-f5321e3dcbdf.gif)

**Comment by cartermp** [comment]
Can repro

**Comment by vasily-kirichenko** [comment]
It does work on old-style full framework projects though.

**Comment by cartermp** [comment]
This now works:

![works](https://user-images.githubusercontent.com/6309070/36221785-125d04c2-1174-11e8-9921-40c399f2213d.gif)
