### ISSUE TITLE
Support coreclr

### ISSUE THREAD

**Issue by Alxandr** [Microsoft/visualfsharp#387]
Please support compiling against and on the coreclr to further both xplat and dnx support.

**Comment by enricosada** [comment]
hi @Alxandr (nice work on asp.net vNext btw :smile: ) 

see #263

**Comment by Alxandr** [comment]
@enricosada I was told on twitter by @visualfsharp to go make a discussion here though ^^

**Comment by enricosada** [comment]
ah ok, nice :smile:

**Comment by forki** [comment]
seems there is something going on at https://github.com/Microsoft/visualfsharp/pull/499

**Comment by kevinrood** [comment]
thanks @forki

**Comment by Alxandr** [comment]
So, there is a new "target" we can build against which is `dotnet`. It's not a compile target (it's a nuget thing), but a reference target (stuff like `System.IO` are nuget packages). I think work could realistically start on getting the fsharp compiler to run on dotnet core, and compile against it.

**Comment by dsyme** [comment]
in progress

**Comment by lilred** [comment]
Maybe leave this issue open until .NET Core support is released? <3
