### ISSUE TITLE
No intellisense for members of some types

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3872]
15.5. preview 2

It works for namespaces

![image](https://user-images.githubusercontent.com/873919/32344354-a85b90d2-c017-11e7-87e8-f8640449d77b.png)

But it does not work for member for `Tcp` type here

![1](https://user-images.githubusercontent.com/873919/32344535-3da1c0d0-c018-11e7-8123-fc2cf65e2a90.gif)

**Comment by cartermp** [comment]
@vasily-kirichenko Is this a .NET Core/Standard project, or a .NET Framework project?

**Comment by vasily-kirichenko** [comment]
It's .NET Framework project. It's Akkling.

**Comment by dsyme** [comment]
@vasily-kirichenko Is it ok if the module you're defining is not also called ``Tcp``?

**Comment by cartermp** [comment]
The akkling code is rather strange...perhaps I don't understand the style or what's even going on here.  `Tcp` is a function, but it's showing as a type when I hover over it:

![fxn](https://user-images.githubusercontent.com/6309070/32913956-ccbbf28a-cac8-11e7-82f1-f644bff31523.PNG)

And the code is using `Tcp` to quality the name of the member type that it contains.  I can reproduce the bug, but I'm a bit confused about why this code would work in the first place...

**Comment by cartermp** [comment]
I don't think any meaningful completion could be provided for `Tcp` as you show in your GIF.  Someone could be referring to either function value `Tcp` or the class `Tcp` from the Akka.IO assembly.

**Comment by vasily-kirichenko** [comment]
OK, it's corner case, closing it.
