### ISSUE TITLE
Find all References shows weird duplicates with .NET Core/.NET Standard projects

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3873]
Using this project: https://github.com/cartermp/giraffesample

![duplicates](https://user-images.githubusercontent.com/6309070/32344681-ebb11fda-bfc4-11e7-8307-86291b051a42.PNG)

**Comment by cartermp** [comment]
![refs](https://user-images.githubusercontent.com/6309070/32694661-abc4f044-c6fa-11e7-9e66-b808e4f0ac84.PNG)

**Comment by vasily-kirichenko** [comment]
For this project

![image](https://user-images.githubusercontent.com/873919/32696751-83bf5a16-c791-11e7-939c-897707b27b6e.png)

`Solution.GetDocumentIdsWithFilePath` returns two different `Document`s

![image](https://user-images.githubusercontent.com/873919/32696758-b2369602-c791-11e7-9b75-086daecf85d1.png)

So it seems there is a bug in the way we interact with CPS.

**Comment by vasily-kirichenko** [comment]
The solution contains two copies of the project:

![image](https://user-images.githubusercontent.com/873919/32696784-2417bd8c-c792-11e7-97eb-4ce7a58f60c9.png)

**Comment by cartermp** [comment]
Bumping this up to Urgency-Now because it basically renders Inline Rename and Find All References as nonsense if you invoke them on a symbol with a lot of uses in a document.  I imagine that this hurts perf as well.

**Comment by Pilchie** [comment]
Is the project multi-targeting to multiple TFMs?  If so, this is by design as far as Roslyn is concerned. It creates a `Project` for each TFM so that it can do differential IntelliSense, etc.

**Comment by cartermp** [comment]
In the case of my solution, it's not multi-TFM.

**Comment by cartermp** [comment]
This seems to be due to the project getting into a weird state...

New console app --> write some code --> use it --> find refs --> things are fine

Close console app --> re-open project --> add an async CE --> use it --> find refs --> observe duplicates

Very weird.

**Comment by cmeeren** [comment]
I too experience this all over my codebase and have for a while. No idea what causes it.

Will it be fixed soon? It's had "Urgency-Now" for two months...

**Comment by cmeeren** [comment]
I actually experience two kinds of duplicates:

![image](https://user-images.githubusercontent.com/7766733/35144123-e63f2ac0-fd03-11e7-83d4-712f991943a8.png)

**Comment by cartermp** [comment]
This seems to have been fixed by subsequent updates to the .NET SDK integration. I have not observed this for some time in our own codebase, and the reproduction codebase also no longer demonstrates the issue.
