### ISSUE TITLE
Non localized strings in F# solution explorer context menu

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#3877]
Repro:
1.   Install French or German or indeed any other language pack.
2.   Create a new F# project
3.   In solution explorer right click on the program.fs file
4.   Observe the very english language options Add Above, Add Below, Move Up, Move Down

See below:
![image](https://user-images.githubusercontent.com/5175830/32356761-b4360d74-bff4-11e7-8efd-03fbd7143b16.png)

Expect menu options to be displayed correctly translated.

**Comment by lukaschal** [comment]
Localized in a xlf file:

https://github.com/Microsoft/visualfsharp/blob/c6a5a98694f9372067960fae6364d77dfc8cc70a/vsintegration/src/FSharp.ProjectSystem.FSharp/xlf/MenusAndCommands.vsct.de.xlf

Repro on Ploc build (vsuvctools 27308.4000).

![fsharp](https://user-images.githubusercontent.com/18324331/34777162-5e1349ea-f611-11e7-979d-c23e3ea0398e.png)

**Comment by lukaschal** [comment]
Not repro on Dev16.

**Comment by KevinRansom** [comment]
Thanks for checking this out @lukaschal 


Kevin
