### ISSUE TITLE
Content items in up-to-date check causes rebuilds

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#388]
The content files cause useless build

**repro**

- create a new Library project
- add a new Text File (`Copy to Output Dir` = `Do not copy`) 
- build -> build success
- build -> up to date
- change content of Text File
- build -> build success
- build -> build success ( :exclamation:  expected up to date )

Same if with `Copy to Output Dir` = `Copy if newer`

**Comment by latkin** [comment]
As explained in #374, this is by design, and matches how C# up-to-date check works.  This will only affect workflows where Content items are being modified much more frequently than code files.  That's not a very common use-case.
