### ISSUE TITLE
Error sugestions are too expensive

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3882]
Opening any file from Logic folder in this repository takes long time to syntax highlighting and structure to appear. Profiling pointed at the type suggestion algorithm:

![image](https://user-images.githubusercontent.com/873919/32387411-6dfc4404-c0d5-11e7-87d4-3e166000a856.png)

(it was Rider, but it does not matter)

**Comment by vasily-kirichenko** [comment]
It seem that replacing `Set` with `HashSet` would make it a lot faster.

**Comment by vasily-kirichenko** [comment]
Even better, it would be great if suggestions were opt-out by a compiler command line argument (and would be off by default). Frankly, I haven't found them useful at all and I never look at them.

**Comment by dsyme** [comment]
@vasily-kirichenko Is this opening the file without a solution?  i.e. so there are lots and lots of errors?

**Comment by vasily-kirichenko** [comment]
It's opening files in VisualFSharp solution. I don't know why there are a lot of errors in Rider, I think it does not matter. The suggestion algorithm should not slow down compilation and tooling.

**Comment by vasily-kirichenko** [comment]
I mean it's a nice feature, at least for some users, but it should be optional, like analyzers.

**Comment by forki** [comment]
I think they should be automatically disabled if we have more than let's say 5 errors. Because then they become slow and definitely the issue is somewhere else.
Using a hash set is a good idea as well.

**Comment by vasily-kirichenko** [comment]
@forki Done https://github.com/Microsoft/visualfsharp/pull/3883

**Comment by forki** [comment]
Very good. For the other idea I wonder if we can keep track how many suggestions we already had. Maybe some new field in the name resolution environment. But currently No time unfortunately
