### ISSUE TITLE
improve optional warning message when accessing property on mutable struct: strange warning FS0052 

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#389]
from [so](http://stackoverflow.com/questions/13753312/warning-produced-by-f-value-has-been-copied-to-ensure-the-original-is-not-muta)

``` fsharp
let warning () =
    System.DateTime.Now.Ticks

let ok () =
    let now = System.DateTime.Now
    now.Ticks
```

the `System.DateTime.Now.Ticks` raise a warning (warning level 5):

```
Library1.fs(4,14): warning FS0052: The value has been copied to ensure the original is not mutated by this operation
```

instead the function `ok` does not.

the decompiled code is the same

```
.method public static int64  ok() cil managed
{
  // Code size       15 (0xf)
  .maxstack  3
  .locals init ([0] valuetype [mscorlib]System.DateTime now)
  IL_0000:  nop
  IL_0001:  call       valuetype [mscorlib]System.DateTime [mscorlib]System.DateTime::get_Now()
  IL_0006:  stloc.0
  IL_0007:  ldloca.s   now
  IL_0009:  call       instance int64 [mscorlib]System.DateTime::get_Ticks()
  IL_000e:  ret
} // end of method Test::ok



.method public static int64  warning() cil managed
{
  // Code size       15 (0xf)
  .maxstack  3
  .locals init ([0] valuetype [mscorlib]System.DateTime V_0)
  IL_0000:  nop
  IL_0001:  call       valuetype [mscorlib]System.DateTime [mscorlib]System.DateTime::get_Now()
  IL_0006:  stloc.0
  IL_0007:  ldloca.s   V_0
  IL_0009:  call       instance int64 [mscorlib]System.DateTime::get_Ticks()
  IL_000e:  ret
} // end of method Test::warning

```

**Comment by dsyme** [comment]
This is really by design.  In the first example the creation of a local for the property access is implicit, in the second the local is already explicit. But either way, that warning is really more like a hint than a true warning - which is why it is level 5.

**Comment by enricosada** [comment]
yes, but i dont understand anyway.

The return of `DateTime.Now` is a struct. The `Ticks` does not mutate the property, because is already copied (return value). Cannot mutate the property with Ticks.

Or this warning meaning is `DateTime.Now property return a value (struct). The `Ticks` property change the this value not the original `Now` property instance` ?

maybe the warning message can be improved. Or i didn't understood the problem

sorry to bother you @dsyme  :smile:

**Comment by dsyme** [comment]
How about if the error message could be improved, e.g.

    "The value has been copied to ensure the original is not mutated by this operation or because the copy is implicit when returning a struct from a member"

**Comment by forki** [comment]
this should be closed. the warning has already be changed to:

    The value has been copied to ensure the original is not mutated by this operation or because the copy is implicit when returning a struct from a member and another member is then accessed

**Comment by dsyme** [comment]
Thanks
