### ISSUE TITLE
An option to always emit attribute symbols in Symbols API

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#3890]
We inspect symbol attributes when looking for tests or doing some analysis. Some attributes we're particularly interested in are erased in compiled code due to use of `ConditionalAttribute` and these attributes aren't emitted in Symbols API either.
Example of such attributes include `NotNull`, `CanBeNull`, `UsedImplicitly` from [`JetBrains.Annotations`](https://www.nuget.org/packages/JetBrains.Annotations) package. Ignoring the use of `ConditionalAttribute` in TypeChecker.fs helps in our case, makes it emit these attributes.

I'd like to add an option to always emit such attributes by ignoring condition. Would `FSharpProjectOptions` be a suitable place for it? It would require to pass a bool to `TcConfigBuilder`, `TcConfig` and then through type check calls.
Another option is to make it always emit such attributes by adding `COMPILER_PUBLIC_API` condition directive to the code below so all attributes would be available for analysis by clients. Also, another property for checking whether an attribute is actually emitted may be added to FSharpAttribute type.
https://github.com/Microsoft/visualfsharp/blob/fefae464c7fb4f15d5b0a19b2e8bfff123a692ca/src/fsharp/TypeChecker.fs#L10528-L10532

**Comment by dsyme** [comment]
@auduchinok I'm fine with you adding this. A hidden command-line flag may be easiest to reduce plumbing, though I'm don't mind too much either way

It's possible some other things should come under this, i.e. the flag should be a general "view the elaborated source before erasure" flag

**Comment by auduchinok** [comment]
@dsyme Could you advice a name suitable for the general flag, please?

**Comment by abelbraaksma** [comment]
Doesn't this cause problems with the CLI? I remember that the `ConditionalAttribute` is required to result in erasing an entire method (provided the constitutional is false), meaning it can't even appear in the assembly. If that requirement is still valid, doesn't it conflict with your solution?

**Comment by auduchinok** [comment]
@abelbraaksma It makes any difference only when analysing code in FCS, not when compiling code.
