### ISSUE TITLE
Current master does not work on 15.4

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3900]
1. 15.4.2 installed, no any 15.5 previews and have never been on this machine.
2. Load VFT solution, master branch
3. F5
4. Create a console project in the exp instance
5. Result

![image](https://user-images.githubusercontent.com/873919/32491338-6696a93a-c3c7-11e7-8e82-c000ee2d19b9.png)

Even keyboard does not work properly - arrow keys, Del and Backspace do not work.

**Comment by dsyme** [comment]
Ouch.  I was about to install master on my machine too.

@cartermp  @brettfo @KevinRansom  Any ideas on what we need to do to get master valid for 15.4 development?  I presume it's been the recent update to Roslyn dependencies? How can we address this in the future?

**Comment by KevinRansom** [comment]
Probably when I updated dependencies yesterday.

**Comment by KevinRansom** [comment]
Just online with dell, my laptop has a motherboard issue.  Then I will try to revert the change.

**Comment by vasily-kirichenko** [comment]
@dsyme I find 15.5 pre 3 is good and faster than 15.4, so maybe it's worth to just switch to it.

**Comment by KevinRansom** [comment]
Lol ... and side by side.

**Comment by dsyme** [comment]
> @dsyme I find 15.5 pre 3 is good and faster than 15.4, so maybe it's worth to just switch to it.

AFAIU our policy is that ``master`` and ``vs2017-rtm`` require latest public non-prerelease Visual Studio 2017, and that currently we don't have a specific established technique to allow development with prereleases (though we obviously need one)

I'm fine with solving this via having multiple branches (``master`` and ``vs-latest-prerelease`` or something, or just ``master`` and ``release``) or whatever, but I'd just like that we have a policy and stick to it.

**Comment by cmeeren** [comment]
I experience this too. Had to uninstall the nightlies.
