### ISSUE TITLE
Autocomplete inside `'`, typing `E`, and commit on enclosing `'`

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3901]
15.5 P3:

![completion-on-dash](https://user-images.githubusercontent.com/6309070/32504061-bcea85ec-c393-11e7-815f-9ed61ed1c2c3.gif)

Expectation:

* No autocompletion when inside of a `'` and typing `E`
* No commit on `'` (although this shouldn't ever be hit in this context)

Whether or not it should complete is a different story.  Given this:

```fsharp
let value = 12
let value' = 13
```

It's valid to commit on `'`.  Though I don't think it really matters, because the `'` is going to be at the end of the identifier anyways.

**Comment by dsyme** [comment]
@cartermp I suppose that if anything it should offer the names of all generic type variables ``'T``

**Comment by cartermp** [comment]
Agreed - though I think this sort of thing should be spec'd out (i.e., I need to turn #2432 into an RFC).  For the time being, just making sure it's quiet is better than the status quo.  Unless it's easy to restrict this to generic types we have symbols for and in the correct context.

**Comment by vasily-kirichenko** [comment]
I think my PR (fixed the @jdh30 problem with double dots etc.) has fixed this as well.

**Comment by cartermp** [comment]
Just tried it in P3 in a script file.  Using this sln:  https://github.com//cartermp/15.x-e2e

**Comment by vasily-kirichenko** [comment]
![image](https://user-images.githubusercontent.com/873919/32508324-fe60c614-c3fa-11e7-80e6-f28a67398282.png)

No, sorry :)

**Comment by vasily-kirichenko** [comment]
![1](https://user-images.githubusercontent.com/873919/32508389-37f0e0da-c3fb-11e7-99e8-2770e545fa14.gif)

**Comment by vasily-kirichenko** [comment]
This is on vanilla 15.5 pre 3

**Comment by cartermp** [comment]
What if you type `E` after `'`?

**Comment by vasily-kirichenko** [comment]
Reproduced.

**Comment by cartermp** [comment]
Updated repro steps - I can now see that they were a bit confusing 😄
