### ISSUE TITLE
Remove redundant `.resx` files when updated `dotnet` ships.

### ISSUE THREAD

**Issue by brettfo** [Microsoft/visualfsharp#3905]
PR #3904 required that some `.resx` files be added to the `src/buildfromsource/` directory.  When a new dotnet sdk is shipped that has changes #3577 and #3607, then the `.resx` files (and their accompanying `.fs` files) should be removed.

**Comment by dsyme** [comment]
+100

**Comment by cartermp** [comment]
@brettfo Does this still need to be open?

**Comment by brettfo** [comment]
There are still some we need to keep around for the proto build and buildfromsource, so it should stay open a bit longer.

**Comment by TD5** [comment]
Does resolving this issue remove the need to manually copy any files at all across to `src\buildfromsource\FSharp.Compiler.Private\` (as per [DEVGUIDE.md](https://github.com/Microsoft/visualfsharp/blob/master/DEVGUIDE.md#updating-fscompfs))?

**Comment by brettfo** [comment]
Yes, once this is resolved that manual copy step will go away.  It should be handled by my changes in #5842.

**Comment by cartermp** [comment]
Closing this as we no longer have this directory in our source build.

**Comment by cartermp** [comment]
Closing this as we no longer have this directory in our source build.
