### ISSUE TITLE
.NET Core app misses FSharp.Core.dll

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3918]
1. Create a .NET Core console app.
2. `dotnet publish -c Release --self-contained -r win-x64`
3. Copy `bin\Release\netcoreapp2.0\win-x64` folder to a clean machine which does not have any .NET Core installed.
4. Run the app
```
...\win-x64>App.exe
Error:
  An assembly specified in the application dependencies manifest (App.deps.json) was not found:
    package: 'FSharp.Core', version: '4.2.3'
    path: 'lib/netstandard1.6/FSharp.Core.dll'
```

**Comment by vasily-kirichenko** [comment]
It turns out it does not work having .NET Core runtime installed:

1. Create a .NET Core console app.
2. `dotnet build -c Release`
3. Copy `bin\Release\netcoreapp2.0` folder to a machine having .NET Core 2.0 runtime installed.
4. `dotnet App.dll`
5. Same error as above.

**Comment by KevinRansom** [comment]
@vasily-kirichenko 
Hmm interesting!!!  ... want me to look at it? or are you happy to track down the magic to make it work?

**Comment by vasily-kirichenko** [comment]
No, I know close to nothing about .NET Core, so go for it :)

**Comment by KevinRansom** [comment]
Me too … but I guess I get paid to endure it.

**Comment by KevinRansom** [comment]
It looks to me like it works fine:  
It's just that step 3 should copy files from:  bin\Release\netcoreapp2.0\win-x64\publish

**Comment by vasily-kirichenko** [comment]
Aha, it works being run from `publish` folder. OK. What about running it via `dotnet App.dll`? Is this scenario is supported at all? I mean `dotnet build` produces these files:
```
└───Release
    └───netcoreapp2.0
            app.deps.json
            app.dll
            app.pdb
            app.runtimeconfig.dev.json
            app.runtimeconfig.json
```
Which is not sufficient to deploy.

**Comment by KevinRansom** [comment]
dotnet publish -c Release --self-contained -r osx.10.11-x64
is for the scenario, where there is no shared components.  So you deploy the published directory and rely on nothing else.

dotnet publish -c Release -r osx.10.11-x32
Needs a preinstalled dotnet on the system published to.

then you can use 
    dotnet "path to published.exe"

To run the app.

**Comment by vasily-kirichenko** [comment]
OK, thanks.
