### ISSUE TITLE
Some namespace symbols are not present in GetAllUsesOfAllSymbolsInFile()

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#3919]
```fsharp
open System
open System.IO
```
I'd like to add these namespaces symbols to this API.

**Comment by dsyme** [comment]
@auduchinok Yes - It's odd they aren't present, they should be

**Comment by vasily-kirichenko** [comment]
Recently I added NotifyOpenNamespace (I’m not remember the name precisely) into the sink and it brings modules to all sysmbol uses, but not namespaces. I’m not sure why.

**Comment by vasily-kirichenko** [comment]
Yes, master returns symbol uses. 

For code:
```fsharp
open System
open System.IO

[<EntryPoint>]
let main argv = 
    0
```

![image](https://user-images.githubusercontent.com/873919/32671033-db15a676-c656-11e7-9a0f-9d39abdf5ad0.png)

But it returns a symbol use for `System` in the first open and for `IO` in the seconds one (but not for `System` in the second one).

**Comment by vasily-kirichenko** [comment]
This is completely fixed https://github.com/Microsoft/visualfsharp/issues/3919
