### ISSUE TITLE
Target Framework for F# Project  does not allow the specification of desktop frameworks

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#3926]
I think this is a project system issue, but I want to record it here.  So we can push on it.

![image](https://user-images.githubusercontent.com/5175830/32684758-ce464d9e-c63b-11e7-98a3-3c8bdbea17f7.png)

Also the Target F# core version is grayed out, which is fine I suppose.  Not sure what to do with it ... needs thought.

I have tons of targeting packs installed with this VS:

![image](https://user-images.githubusercontent.com/5175830/32684984-55d92022-c63e-11e7-87cd-bc20893272b7.png)

**Comment by cartermp** [comment]
I'm going to close this since it's not an issue that we control in the tools. It's already tracked there by this bug: https://github.com/dotnet/project-system/issues/3024
