### ISSUE TITLE
dotnet cli test templates work when targeting .NET Core but fail when targeting .NET Standard and .NET Framework

### ISSUE THREAD

**Issue by lambdakris** [Microsoft/visualfsharp#3931]
The dotnet cli test project templates work when targeting .NET Core but fail when targeting .NET Standard and .NET Framework

I am opening this issue here instead of in the templating or cli repos because I'm unsure as to whether it is just a simple template issue or something more fundamental. Also, it reminds me of, and may have some relation to, https://github.com/xunit/xunit/issues/1221 and https://github.com/dotnet/netcorecli-fsc/issues/79, but what I'm questioning here is whether it should be working differently for .NET Core, .NET Framework, and especially .NET Standard.

#### Repro steps

1. Create a test project 
```
dotnet new mstest -o Testy -lang f#
```

2. Open Testy.fsproj and change TargetFramework to .NET Standard
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>
...
```
3. Run cli test tool
```
dotnet test
```
4. Observe error the following error about invalid module declaration for project type
```
C:\Users\lambdakris\Code\Example\special\Testy\Program.fs(1,1): error FS0222: Files in libraries or multiple-file applications must begin with a namespace or module declaration. When using a module declaration at the start of a file the '=' sign is not allowed. If this is a top-level module, consider removing the = to resolve this error. [C:\Users\lambdakris\Code\Example\special\Testy\Testy.fsproj]
```
5. Attempt to fix issue by making the suggested changes to Program.fs
```
namespace Testy

module Program =
    [<EntryPoint>]
    let main _ = 0
```
6. Run cli test tool
```
dotnet test
```
7. Observe the following error about EntryPointAttribute needing to be last (which it certainly appears to be)
```
C:\Users\lambdakris\Code\Example\special\Testy\Program.fs(5,9): error FS0433: A function labeled with the 'EntryPointAttribute' attribute must be the last declaration in the last file in the compilation sequence. [C:\Users\lambdakris\Code\Example\special\Testy\Testy.fsproj]
```

#### Expected behavior

A test project created using the dotnet cli test templates should work regardless of what framework is being targeted

#### Actual behavior

A test project created using the dotnet cli test templates only works when targeting .NET Core

#### Known workarounds

I suppose that the work-around, which probably suggest something about the issue, is to use old style proj files.

#### Related information 

* Windows 10 1709
* .NET Core 2.0, .NET Framework 4.7.1
* Visual Studio Code, Visual Studio 2017 (is installed but was not used)

**Comment by cartermp** [comment]
Although the error message is confusing, this is by design for both MSTest and xUnit.  Test projects are console apps on .NET Core, and the `dotnet test` command is what executes the code.  Any change to support .NET Standard for test projects is outside the scope of F# support on .NET Core.
