### ISSUE TITLE
Completion is available inside bindings idents

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#3936]
When invoking code completion inside complete binding ident that is not pattern:
<img width="360" alt="screen shot 2017-11-13 at 15 39 46" src="https://user-images.githubusercontent.com/3923587/32726231-471f4ba4-c889-11e7-99a4-0367a7edb503.png">
When binding is incomplete completion context is invalid as desired.
<img width="177" alt="screen shot 2017-11-13 at 15 40 03" src="https://user-images.githubusercontent.com/3923587/32726206-3013ccc8-c889-11e7-931d-6a40be92cea9.png">

In some situations completion is not available inside binding idents, e.g. in parameter definitions:
<img width="214" alt="screen shot 2017-11-13 at 15 47 23" src="https://user-images.githubusercontent.com/3923587/32726433-127bef28-c88a-11e7-9a0f-ce285f8fef83.png">

**Comment by vasily-kirichenko** [comment]
Fixed via https://github.com/Microsoft/visualfsharp/pull/5083
