### ISSUE TITLE
Symbols API: provide a way to check if a field name was generated

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#3938]
We need to check if a field name was generated (e.g. Item, Item2 in union cases, Data0, Data1 in exceptions) for symbols in source code.
This [commit](https://github.com/JetBrains/visualfsharp/commit/11e1b1066c3a8adf811d130f13160bee8df6bfd4) adds it, however not for fields defined in compiled assemblies. There're some other APIs we'd like to add and need for symbols defined in source code only as well. Should these APIs be generalized for IL types before opening PRs? (If yes, should info about field names be added to metadata?) Should they be added as is with a comment that it is for source-defined symbols only? Another option would be to add such APIs to a separate module.

**Comment by dsyme** [comment]
@auduchinok I think for now just add the API and add to the comment that it is only for source-defined symbols.
