### ISSUE TITLE
Quick Actions shortcut not working in VS2015 RC

### ISSUE THREAD

**Issue by hyh** [Microsoft/visualfsharp#394]
In VS2013, Quick Actions menu can be accessed via Ctrl + . shortcut. This is not working in VS2015. (I can still click the tooltip, only the shortcut is broken)
![image](https://cloud.githubusercontent.com/assets/650551/7409236/35842990-ef57-11e4-8826-8a77cb4229d3.png)

The shortcut is working in C# project though.
![image](https://cloud.githubusercontent.com/assets/650551/7409567/ef77be8c-ef59-11e4-8c0f-0ae3691911fa.png)

**Comment by forki** [comment]
@dungpa @vasily-kirichenko isn't that a VisualFSharpPowerTools feature?
http://fsprojects.github.io/VisualFSharpPowerTools/resolveunopenednamespaces.html

**Comment by hyh** [comment]
Ah, you are right.
Moving this issue to fsprojects/VisualFSharpPowerTools#962
