### ISSUE TITLE
Extended completion should contain extension and static members

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3948]

**Comment by ingted** [comment]
1>Z:\GoogleDrive_anighost\FsPickler\src\FsPickler\Combinators\Tuple.fs(338,40): error FS0039: The field, constructor or member 'Item2' is not defined.
1>Z:\GoogleDrive_anighost\FsPickler\src\FsPickler\Combinators\Tuple.fs(339,40): error FS0039: The field, constructor or member 'Item3' is not defined.
1>Z:\GoogleDrive_anighost\FsPickler\src\FsPickler\Combinators\Tuple.fs(340,40): error FS0039: The field, constructor or member 'Item4' is not defined.
1>Z:\GoogleDrive_anighost\FsPickler\src\FsPickler\Combinators\Tuple.fs(341,40): error FS0039: The field, constructor or member 'Item5' is not defined.
1>Z:\GoogleDrive_anighost\FsPickler\src\FsPickler\Combinators\Tuple.fs(342,40): error FS0039: The field, constructor or member 'Item6' is not defined.
1>Z:\GoogleDrive_anighost\FsPickler\src\FsPickler\Combinators\Tuple.fs(343,40): error FS0039: The field, constructor or member 'Item7' is not defined.
1>Z:\GoogleDrive_anighost\FsPickler\src\FsPickler\Combinators\Tuple.fs(344,42): error FS0039: The field, constructor or member 'Rest' is not defined.

**Comment by ingted** [comment]
System.Tuple variable could not just directly get each item by .Item.
It requires "variable.ToValueTuple().ItemX" to get item

**Comment by ingted** [comment]
And got a lot of errors when compiling projects:
Error	FS0756	'new' may only be used with named types

**Comment by vasily-kirichenko** [comment]
@ingted wrong issue?...

**Comment by ingted** [comment]
I think it is. Because my projects with extension method invocation are failed to build after upgrading to VS 15.4.

**Comment by ingted** [comment]
VS is unable to recognize extension method's return values...

**Comment by vasily-kirichenko** [comment]
@ingted how these problems are related to this issue?

**Comment by ingted** [comment]
When I use Visual FSharp project, extension method doesn't work with intelligence...
If this is not related, I will delete my comments.

**Comment by vasily-kirichenko** [comment]
Could you provide a minimal repro?

**Comment by ingted** [comment]
Just upgrade VS from 15.2 to 15.4 and start a new FSharp Project.

In source code,

let a = new Tuple<int, int> (1,2)
let b = a.Item1

This could be built in 15.2 but not in 15.4.


On Thu, Nov 16, 2017 at 5:55 PM, Vasily Kirichenko <notifications@github.com

**Comment by cartermp** [comment]
@ingted The issue you're referring to isn't related to this issue. #3729 is the demonstration of breaking `.ItemX` properties from System.Tuples coming directly from F# code.  In this case, you should change your code to use F# tuple syntax rather than the `.ItemX` properties:

```fsharp
let (a, b) = Tuple.Create(1, 2)
```

**Comment by ingted** [comment]
Thanks so much, should I delete the previous comments (sorry about that I didn't google the correct post)?
