### ISSUE TITLE
Bug in UnusedOpens analyzer when one module is nested inside an AutoOpen'ed module

### ISSUE THREAD

**Issue by nosami** [Microsoft/visualfsharp#3950]
I noticed this bug when converting VS for Mac over to use the new `UnusedOpens.getUnusedOpens` API in FCS.

```fs
            namespace module1namespace
            [<AutoOpen>]
            module module1 =
                module module2 =
                    let x = 1
            namespace consumernamespace
            open module1namespace
            module module3 =
                let y = module2.x
```

```fs
open module1namespace
```
should be flagged as unneeded

**Comment by auduchinok** [comment]
@nosami Should it? These namespaces aren't nested and the compiler shows an error if `open ...` is removed.
` Library.fs(8, 13): [FS0039] The value, namespace, type or module 'module2' is not defined. Maybe you want one of the following:   <Module>`

**Comment by nosami** [comment]
Hmm... no errors for me here on OSX.

<img width="587" alt="screen shot 2017-11-15 at 15 17 24" src="https://user-images.githubusercontent.com/667194/32843642-26b14724-ca18-11e7-9902-78eb9c45ac00.png">

**Comment by nosami** [comment]
Hang on ... you're right. It fails if `module1namespace` is removed. I must have had a bogus unit test. Thanks!

**Comment by vasily-kirichenko** [comment]
It would be great if you added this sample as a test (there are about 60 tests already).

**Comment by nosami** [comment]
@vasily-kirichenko: sure, will do

**Comment by nosami** [comment]
@vasily-kirichenko: nice work on the new API btw... switching over to this new code has removed a few bugs that I had in my implementation.

**Comment by vasily-kirichenko** [comment]
@nosami Thanks. This impl has no known bugs :) However, it's slow on large files (~2 seconds on common files, 40 seconds on `TypeChecker.fs`), so if you cannot run this analyzer completely independently from any other ones, you should not have it turned on by default.
