### ISSUE TITLE
.NET Core SDK projects with P2P or NuGet references will see phantom errors in Error List

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3952]
#### Repro steps

1. Create a new .NET Core Console App.
2. Create a new .NET Standard class library and add a reference to it from the console app.
3. Type `Say` in the `Program.fs` file in the Console App.

#### Expected behavior

No errors.

#### Actual behavior

IntelliSense all works (yay!), but the Error List says that the symols I'm using aren't defined:

![err](https://user-images.githubusercontent.com/6309070/32850903-6126b3f6-c9e8-11e7-8eb6-817c44cf480f.PNG)

#### Known workarounds

Close and re-open `Program.fs`.

#### Related information 

* VS 15.5 Preview 4

**Comment by cartermp** [comment]
Note that this will also be the case if you have a P2P reference in an existing project that you open.  As in the case of the original issue, you just need to close and reopen your files and then the errors in the error list will go away.

**Comment by Xiu-Li** [comment]
Repro on latest d15.7/27508.00. 
Not repro on latest d15.7stg/27508.3006.

**Comment by Xiu-Li** [comment]
**Not Repro** on latest **d15.7/27512.00**.

**Comment by cartermp** [comment]
@KevinRansom and I chatted and he believes this is fixed with #4328, which came in too close for 15.6 but made it into 15.7. Given that this has not reproduced on the 15.7 build where we've had an insertion, he appears correct. I'll close this out and re-open if it reproduced again.
