### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#3960]
![image](https://user-images.githubusercontent.com/873919/32911746-1b61d6ca-cb1e-11e7-8131-0fbea86dbfbb.png)

Rider does not even show XML doc and signature:

![image](https://user-images.githubusercontent.com/873919/32911713-fc901b62-cb1d-11e7-8ccd-2ef03cb0794f.png)

/cc @auduchinok

**Comment by cartermp** [comment]
Should the error message by the same as if you did `let _ = System`?

```The value or constructor 'System' is not defined.```

I'm not sure what triggers the additional items in the error message.

**Comment by vasily-kirichenko** [comment]
I'm not sure what an ideal error message should be in this case, the current one is not that bad.
