### ISSUE TITLE
No project templates in latest nightly

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#3978]
Project templates are missing from latest nightly (15.4.1.17111702). Here's the result of searching for "f#" in my New Project dialog - only Xamarin templates are found:

![image](https://user-images.githubusercontent.com/7766733/33017101-570be1cc-cdf1-11e7-98d3-1d77fcb40253.png)

**Comment by cartermp** [comment]
I think something in our recent pushes to master wiped them out for 15.4 installations - I can repro this on VS 15.4.  @brettfo @KevinRansom any ideas?

**Comment by Pilchie** [comment]
We split them into a different vsix (to be in different workloads), so nightlies are replacing a vsix that contains them with one that doesn't.  May need to tweak dogfooding instructions to include a set of vsixes to install, or make a nested hierarchical vsix. 

(The latter tends to hit some bugs in auto-update though).

**Comment by cartermp** [comment]
Weird that it would happen now, though.  #3720 was merged into master more than a month ago, so I would have expected a bug like this to be reported a lot earlier than now.

**Comment by KevinRansom** [comment]
NIghtlies will not have templates until dev VS2017.5 is released.

**Comment by cartermp** [comment]
By-designing this, then. Bit of a shame, but given that we're fairly close to the 15.5 release + nightlies aren't officially supported it's not the end of the world
