### ISSUE TITLE
Bring back (limited) support for Alt+' "send line to interactive"

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#398]
In #260, support for "send line to F# interactive" was removed, in favor of modifying "send selection to F# interative" to have smarter behavior.  In particular, we didn't just remove the UI menu item, we stopped handling the VS command altogether.

I'm seeing some feedback that people liked "send line to interactive" and are missing it now.  Since we don't handle the command at all any more, they cannot add a custom keybinding even if they try.

I propose we:

- Add back the handling of the raw "send line" VS command (for sure)
- Add back the default keyboard shortcut `Alt+'`  (maybe... thoughts?)
- Continue to leave it out of the editor context menu

**Comment by isaacabraham** [comment]
@latkin: I'm confused. I've got VS2015 RC installed. If I do Alt + Enter, without selecting anything, it sends the line to FSI (as per #260). If I highlight some text, it'll send just that text.

Are you referring to menu items? In which I case, I don't have "send selection to F# interactive" (or "send line to F# Interactive" for that matter) - all I have is Execute In F# Interactive (which is the same as Alt + Enter).

What exactly are people losing out on?

**Comment by latkin** [comment]
@isaacabraham Most users don't follow the conversation in this repo, so how are they supposed to know that `Alt+Enter` now accommodates "execute line" behavior?  If I was an `Alt+'` user, and I move to VS 2015:

- My keystrokes don't work any more
- The "execute line" menu item is gone
- It doesn't even work to manually add a shortcut to `VSStd11CmdID.ExecuteLineInInteractive`

That's not a great experience.

**Comment by isaacabraham** [comment]
@latkin I had no idea that there was even an ```Alt+'``` option to execute the current line! My behaviour in the past was always ```shift``` -> ```down arrow``` -> ```alt + enter```.  So yes, if someone used ```Alt + '``` I can imagine confusion.

Perhaps just add a secondary mapping for ```Alt + '``` onto the new smart send line?

Or just bring the old one back - then you have two features (and keyboard shortcuts) to do essentially the same thing?

**Comment by latkin** [comment]
Fixed with https://github.com/Microsoft/visualfsharp/commit/0cb505c9c12bca80c5ae90065d9cea9390761823
