### ISSUE TITLE
Bug of automatic focus change in editor of VS2017 is back

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3980]
Not present in VS2017 RTM (15.4.4), but present in at least latest Pro Preview (15.5.5). I remember this bug was around and was fixed. Now it is back.

### Repro steps

1. Open an existing solution with multiple editor tabs open. Before last close, focus is not on the left-most tab.
2. Clear solution
3. Build solution
4. Tab jumps to left-most one automatically (without any user action)

### Expected behavior

The open tab with current focus should remain in focus.

### Actual behavior

As described, focus is changed without user action.

### Known workarounds

Don't use preview edition.

### Related information 

Seen on:

* Microsoft Visual Studio Professional 2017 Preview, version 15.5..0 Preview 4.0
* Active .NET framework (from About-screen): .NET 4.7.02558.

It may happen with other usage scenarios, as we saw with the previous occurrence of this bug. I am wondering, is it possible to add a UI-test for this so that it doesn't pop back up? It was a lot of effort last time around to fix this, I hope it isn't the same cause (which I can't remember).

**Comment by dsyme** [comment]
Sounds nasty, can anyone repro?

**Comment by abelbraaksma** [comment]
@dsyme, I made a little screengrab to show what goes on, in case it helps. It turns out, it happens _always_ on any project I have, provided it is cleaned, or the changes are significant (i.e., it doesn't happen when only a single file is out-of-date).

It happens occasionally "out of the blue", but I can consistently repro it with any solution I have when it fires up. This is one example (it takes a moment to start, it's a rather large solution file):

![vs2017_prev_jumps_to_other_tab](https://user-images.githubusercontent.com/16015770/33103994-10d10558-cf26-11e7-9a41-745bbfdaea1e.gif)

**Comment by cartermp** [comment]
@abelbraaksma Do you see this happen with any C# or VB solution, or is this just with F# files?

**Comment by cartermp** [comment]
@abelbraaksma Since I couldn't reproduce this I'll close, but please ping for re-open if you see it again.
