### ISSUE TITLE
The "dict" debugger visualizer is useless

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#3981]
![grafik](https://user-images.githubusercontent.com/4236651/33022588-fbdc9a84-ce05-11e7-87f9-c5f9a35af8c4.png)

![grafik](https://user-images.githubusercontent.com/4236651/33022596-08d56c02-ce06-11e7-93fe-50ff36b3b686.png)

**Comment by vasily-kirichenko** [comment]
Turning on this setting

![image](https://user-images.githubusercontent.com/873919/33037251-f42c755c-ce41-11e7-9ca7-4a9e92b478d2.png)

makes it more usable

![image](https://user-images.githubusercontent.com/873919/33037220-dcd245c6-ce41-11e7-9761-d9db825dacff.png)

**Comment by vasily-kirichenko** [comment]
However

![image](https://user-images.githubusercontent.com/873919/33037278-15b24260-ce42-11e7-94d7-9aa059154fed.png)

@KevinRansom @TIHan We should think about providing "modern" (whatever it means) visualizers for lists, dicts and maps.

**Comment by cartermp** [comment]
Lists, arrays, and maps use the same visualization behavior in the legacy EE thanks to @saul:

![works](https://user-images.githubusercontent.com/6309070/33037622-001c8d9e-cde7-11e7-9dad-5ab3268373ba.gif)

Is the suggestion that the underlying `IDictionary` be `ToArray`'d?  Today it shows it as the underlying IEnumerable, which you must enumerate.

**Comment by 0x53A** [comment]
__Note:__ I am using the latest VS preview WITHOUT nightlies, so some of this may already be fixed.

------

ah, right, there was that switch ...
If I enable the legacy EE, I get empty "Autos" / "Locals", and trying to manually add something to the watch:
![grafik](https://user-images.githubusercontent.com/4236651/33040092-505cbb82-ce3a-11e7-9e68-596a8313fe9f.png)

![grafik](https://user-images.githubusercontent.com/4236651/33040005-175db8c2-ce3a-11e7-8b29-f2beb0a7b0a1.png)

--------------

If I also enable managed compatibility mode, then I get
![grafik](https://user-images.githubusercontent.com/4236651/33040151-7b6a84b2-ce3a-11e7-8064-5eebd972dea6.png)

![grafik](https://user-images.githubusercontent.com/4236651/33040129-6fa474c6-ce3a-11e7-9aa7-c57b36b92dbf.png)

(Which is probably because this is a new-sdk console app, so portable-pdb).

----------

IF I then also disable portable-pdb I see this:
![grafik](https://user-images.githubusercontent.com/4236651/33040421-50d6e8c0-ce3b-11e7-887c-35e3d3f5e09a.png)

So there is no way to drill into ``Keys``, but I can drill into ``Values``.


----------
----------

Compare this with C#:

![grafik](https://user-images.githubusercontent.com/4236651/33040637-f2d198e6-ce3b-11e7-82c9-14633e803abd.png)

I see the total count at the top, instead of the type which I don't care about.

If I open it, I see ToString for each key/value combination, and can drill down.

**Comment by saul** [comment]
Looking at the code, we just don't have a debug visualizer for the result of 'dict'. Will take a look at adding this an put in a PR.

**Comment by 0x53A** [comment]
Should I create a separate issue for the following, or is this already on your radar?

1) Legacy EE only works in combination with Managed Compat Mode (otherwise I get "Internal error in the expression evaluator")
2) Managed Compat Mode does NOT work in combination with portable-pdb

==> portable-pdb and sane debugging are exclusive

**Comment by cartermp** [comment]
The legacy EE is very unlikely to change in the future, nor do I suspect we'll be doing much work in portable PDB generation to ensure it works with an EE that will be discontinued.  With @saul's PR (if you can confirm it works), what else is missing such that it's "sane"?

**Comment by KevinRansom** [comment]
The Legacy EE is deprecated.  We need to build an F# EE it's a piece of work, and is on the backlog.  In the meantime we leverage C#'s EE.

**Comment by 0x53A** [comment]
Ah, apologies.

I was under the mistaken impression that the ``List``, ``Set``, ``Map`` (and so on) visualizers also only worked with legacy EE.

After actually testing it, it works really good with new EE and portable-pdb. 👍 

The only really minor thing I noticed is that it writes the type of the key as ``System.__Canon {string}`` instead of just ``string``.

![grafik](https://user-images.githubusercontent.com/4236651/33134587-6b1fe16c-cfa0-11e7-86f7-a0344d370225.png)
