### ISSUE TITLE
Regression from VS2015 -> VS2017 for compiling matches against enums, now throws FS3191

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#3985]
I needed to test old code and rolled back some local version, only to find out that it didn't compile anymore (even though my logging showed it did, at the time).  Then I tried with VS2015 (instead of 2017) and it compiled just fine.

Reason: pattern matching against enums cannot take a variable anymore.

### Repro steps

This may illustrate the issue:

```f#
module TestFS3191 =
    type MyEnum = 
        | Value1 = 1
        | Value2 = 2
        | Value3 = 3

    let testEnum =
        let foo = MyEnum.Value1

        match foo with
        | MyEnum.Value1 foo -> foo   // error in VS2017, no error in VS2015
        | MyEnum.Value2 foo -> foo
        | MyEnum.Value3 foo -> foo
```

### Expected behavior

What compiles in VS2015 should compile in VS2017. Note that in both cases, code is F# 4.0. Changing it to 4.1, still raises the error though.

### Actual behavior

Raises (in VS2017):

> error FS3191: This literal pattern does not take arguments

### Known workarounds

Update the code. Presumable, the coder wanted `as foo`, or didn't intend to use `foo` in that location in the first place and it got there. I noticed that it gets ignored by the compiler. If you try this:

```f#
        match foo with
        | MyEnum.Value1 a-> a   // error on second "a", it says it isn't defined
```

This, clearly, seems wrong, and may have been fixed, but introduced a (albeit small) backwards compatibility issue with existing code becoming non-compilable based on syntax alone.

### Related information 

Erroneous behavior seen in VS2017 RTM and Preview editions. Not related to version of F#, it throws the error by FSC regardless of targeted 4.0 or 4.1 version.

**Comment by dsyme** [comment]
This was a bug fix. The code should ne er have been accepted. We could have made it a warning but chose to just make the fix instead. Given the time that has passed I'd imagine we'll leave it like it is now.

**Comment by abelbraaksma** [comment]
@dsyme, I'm ok with that, if it was for good reason. But normally if the choice is _breaking change_ vs _non-breaking-change_, the latter is taken. For some reason not in this case. 

I'm not sure the code is illegal, I guess that's how you define enum-matching expressions. Though I see little use in that syntax, I didn't even know I had it until this error came around.

We should somewhere keep a list of breaking changes. That can (for instance) be on a dedicated place, like in the wiki or on the fsharp.org site. I searched for this error, but didn't find anything (but I may not have sought very deep). Perhaps this bug report helps other people migrating their code ;).

**Comment by cartermp** [comment]
I'll close this out with the tag.  Perhaps a list of these things could be produced and maintained, but the core problem:

* There are bugs in the compiler (any compiler, really) which result in behavior, which is often unknown to us, that people can depend upon
* These bugs may or may not get fixed over time
* Fixing of such bugs will break people

Isn't really solvable unless we decide to freeze the F# compiler ... but we won't be doing that.

**Comment by dsyme** [comment]
Perhaps we could document this sort of thing post-hoc with a very brief
RFC doc in the fsharp 4.1 folder of fslang-design, basically nothing but
a link here.

**Comment by abelbraaksma** [comment]
@cartermp: yes, to all your points, and I understand the necessity. Ideally I would like to add it to the documentation. I.e., if we change a hypothetical construct `do a` and we disallow that, but previously ignored it, we should write a line in the documentation on `do`, like "before version X `do a` was allowed, after version X it raises an error".

Obviously this would only work if:

* We recognize that we introduce a backward compat issue when we fix a bug
* We document it timely, before knowledge fades (though even just tagging + comment would already be very helpful and somebody else could take it on later)

**Comment by dsyme** [comment]
See https://github.com/Microsoft/visualfsharp/issues/3985 where I added an "RFC" for F# 4.1to document this fix
