### ISSUE TITLE
Extended completion isn't triggered inside attributes

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#3990]

**Comment by vasily-kirichenko** [comment]
Ah... There is a special context for attributes, so we should pass "all entities" there the same way as we do for "default" context.

**Comment by vasily-kirichenko** [comment]
This is fixed in https://github.com/Microsoft/visualfsharp/pull/5028

**Comment by cartermp** [comment]
Thanks for the ping @vasily-kirichenko
