### ISSUE TITLE
Implement IReadOnlyDictionary for dict

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#3999]
The return value of `dict` is a readonly view of the underlying dictionary, so it should implement `IReadonlyDictionary<'TKey, 'TValue>`.

**Comment by dsyme** [comment]
+1

**Comment by dsyme** [comment]
@cartermp We should check that all IReadOnly* are implemented wherever possible in FSharp.Core.  We held off doing that for too long.

**Comment by cartermp** [comment]
Created suggestion here: https://github.com/fsharp/fslang-suggestions/issues/624

Happy to fill out the RFC as well.

**Comment by dsyme** [comment]
@cartermp Super, marked as approved :)

**Comment by manofstick** [comment]
How about wrapping in a type which contains the collection of interfaces so that it advertises what it has rather than requiring a blind cast?

    type Dict<'key, 'value> =
        interface IDictionary<'key, 'value>
        interface IReadOnlyDictionary<'key, 'value>

    let dict : seq<'key*'value> -> Dict<'key, 'value>

Hmmm, probably no good because it is an API change, but something to mull over...

**Comment by cartermp** [comment]
Closing in favor of the RFC and language proposal
