### ISSUE TITLE
Existing F# projects won't open if only VS2015 is installed

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#4]
Opened on codeplex by ovastus:
Existing F# projects won't open if only VS2015 is installed

These 2 conditions present on most projects will fail if only VS2015 is installed:
```xml
<PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">`
     <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
     </PropertyGroup>
     <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.Targets')">
     <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.1\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
</PropertyGroup>
```

The workaround is simple, install the F# 3.1 bundle, but for a new user trying the language for the first time this can be a blocker. This sort of thing never happens in C#, but whenever there is a new F# version we always bump into these kinds of problems :( 
Could the installer maybe bundle F# 3.0 and 3.1 together with 4.0?

>comments
>latkin wrote Jan 5 at 9:06 AM [x] 

>Those conditions are not present in the standard project templates included in VS. Where are you >getting that config from?

>The standard project imports the targets file like so:

  >```xml
<Choose>
    <When Condition="'$(VisualStudioVersion)' == '11.0'">
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </Otherwise>
  </Choose>
  <Import Project="$(FSharpTargetsPath)" />
```
There is a backcompat check for 3.0 that points directly at the targets file, but everything since then (3.1+) has been picked up by a shim file that's dropped to C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v%VSVERSION%\FSharp. It's this file that actually points to the real targets file. You automatically get the latest targets file when you open in the latest VS.

**Comment by latkin** [comment]
Per my codeplex comment, would be interested to know if anyone else has encounted this behavior, or has project files that resemble the original from @ovatsus

**Comment by ovatsus** [comment]
I got this on FSharp.Data project. I think the .fsprojs were manually modified because for a while mono didn't support <Choose>, I forgot about that when I posted this issue on codeplex.

Will a fsproj from VS2012 that didn't have thise <Choose>, open correctly on VS2015, both directly or after first upgrader to VS2013?

**Comment by jaredpar** [comment]
This is the trick that I use to get my F# projects to open in any version of Visual Studio including 2015:

``` xml
  <Choose>
    <When Condition="'$(VisualStudioVersion)' == '' or '$(VisualStudioVersion)' == '9.0'">
      <PropertyGroup>
        <FSharpTargetsPath>$(ProgramFiles)\Microsoft F#\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <When Condition="'$(VisualStudioVersion)' == '11.0' or '$(VisualStudioVersion)' == '10.0'">
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </Otherwise>
  </Choose>
  <Import Project="$(FSharpTargetsPath)" />
```

Source: https://github.com/jaredpar/VsVim/blob/fixes-dev14/Src/VimCore/VimCore.fsproj#L38

**Comment by latkin** [comment]
Nice @jaredpar, looks close to the current default, but with 10.0 and 9.0 support. (9.0? F# wasn't even in VS in 9.0...)

**Comment by tpetricek** [comment]
Yeah... most F# projects on GitHub that had early Travis CI support don't use `<Choose>` because that used to fail on Mono (see [for example this](https://github.com/BlueMountainCapital/FSharpRProvider/blob/master/src/RProvider/RProvider.fsproj#L48)). If this is now supported in Mono, we should probably fix all projects to use the standard format.

**Comment by jaredpar** [comment]
Not sure why the 9.0 support is there. Wonder if that was from the pre-RTM
days before the version number flipped.  This file dates back that far so
it's possible.

On Thursday, January 15, 2015, Lincoln Atkinson <notifications@github.com>
wrote:

> Nice @jaredpar <https://github.com/jaredpar>, looks close to the current
> default, but with 10.0 and 9.0 support. (9.0? F# wasn't even in VS in
> 9.0...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/visualfsharp/issues/4#issuecomment-70196925>
> .
>


-- 
Jared Parsons
http://blog.paranoidcoding.com/
http://twitter.com/jaredpar

**Comment by latkin** [comment]
@ovatsus not exactly a full back-compat test pass, but I just created a default VS 2012 project, and it opened fine in VS 2015 straight away.  The upgrade adds the version-agnostic stuff mentioned above. The project system code that detects and converts "11.0-era" projects to current style is still in place.

**Comment by PatrickMcDonald** [comment]
From memory, didn't F# 1.0 install into Visual Studio 2008?  It just wasn't installed ___with___ VS until 2010
