### ISSUE TITLE
F# NetSDK projects don't allow source file preview

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#4006]
If you select a C# source file in a C# project the IDE previews the source file.

F# NetSDK projects don't support this.

**Comment by cartermp** [comment]
Note that the preview pane _does_ show for Go to Definition:
![gtf](https://user-images.githubusercontent.com/6309070/33155657-2f2a5726-cfa7-11e7-9575-855cc4429bc0.PNG)
So it's likely that a little thing isn't wired up correctly.  Do we know if we control this?

**Comment by KevinRansom** [comment]
I'm sure it's our fault somehow.

**Comment by vasily-kirichenko** [comment]
https://github.com/Microsoft/visualfsharp/issues/3869

**Comment by KevinRansom** [comment]
Closed dupe: https://github.com/Microsoft/visualfsharp/issues/3869
