### ISSUE TITLE
Property accessors are available in extended completion

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#4008]
<img width="606" alt="screen shot 2017-11-23 at 13 47 25" src="https://user-images.githubusercontent.com/3923587/33170222-9484819e-d058-11e7-8753-9dfcdbab324f.png">

**Comment by vasily-kirichenko** [comment]
![image](https://user-images.githubusercontent.com/873919/33233138-9316508c-d222-11e7-941d-51c33306d28c.png)

**Comment by vasily-kirichenko** [comment]
![image](https://user-images.githubusercontent.com/873919/33233494-b91031fe-d227-11e7-872a-25111a861219.png)

Maybe C# specific?

**Comment by vasily-kirichenko** [comment]
Reproduced on `System.Environment.CurrentDirectory`.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/4015
