### ISSUE TITLE
Can't build a computation expression from a SRTP'd value

### ISSUE THREAD

**Issue by drvink** [Microsoft/visualfsharp#401]
```fsharp
let inline silly< ^m, ^a, ^b when
    ^m : (member Return : ^a -> ^b)>
    (m : ^m) =
  m { return 0 }
```

I didn't expect it to work, but I couldn't resist trying. :)

**Comment by dsyme** [comment]
"ngen queue status" gives some info.

"ngen display" sure shows a lot of information and will indicate if FSHarp.Compiler.dll is NGEN'd

I think you have to run the 32-bit and 64-bit ngen.exe separately.

**Comment by drvink** [comment]
@dsyme I think you meant that for issue #400 :)

**Comment by dsyme** [comment]
Thanks, yes

**Comment by dsyme** [comment]
I'll have to close this as by-design :) You could you add a suggestion on http://fslang.uservoice.com
