### ISSUE TITLE
No namespace symbol uses when subsequent id isn't resolved in open expression

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#4011]
<img width="214" alt="screen shot 2017-11-24 at 18 16 35" src="https://user-images.githubusercontent.com/3923587/33216157-bd7de234-d143-11e7-8252-fdd96179ab84.png">

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/4012
