### ISSUE TITLE
Type check errors contain internal options warnings when --nowarn:75 is passed 

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#4030]
Warnings about internal options of the following form are returned in `FSharpCheckFileResults` and `FSharpCheckProjectResults` even when `--nowarn:75` is passed in `FSharpProjectOptions.OtherOptions`. These errors have error number 75.
```
commandLineArgs (0,1)-(0,1) parameter warning The command-line option 'times' is for test purposes only
```

In VS these warnings are ignored in the code below and after a quick search I don't see other places where these errors are shown to a user. I suppose it is a bug and these errors should not appear in the first place.
https://github.com/Microsoft/visualfsharp/blob/716b8e9998c1d764ba23dc37602e77b506dcfc64/vsintegration/src/FSharp.Editor/Diagnostics/DocumentDiagnosticAnalyzer.fs#L80-L84

**Comment by saul** [comment]
Errors with a 0 line number aren't ignored, they're reported separately in the ProjectDiagnosticAnalyzer.

**Comment by auduchinok** [comment]
@saul Am I right that you're talking about this code?
https://github.com/Microsoft/visualfsharp/blob/44fa027b308681a1b78a089e44fa1ab35ff77b41/vsintegration/src/FSharp.Editor/Diagnostics/ProjectDiagnosticAnalyzer.fs#L36-L39

As far as I can tell it is disabled by the following condition on a constant that currently is never set.
https://github.com/Microsoft/visualfsharp/blob/44fa027b308681a1b78a089e44fa1ab35ff77b41/vsintegration/src/FSharp.Editor/Diagnostics/ProjectDiagnosticAnalyzer.fs#L24

```
Eugene@DESKTOP-1ESHKDK  /c/Developer/visualfsharp (master)
$ grep -r PROJECT_ANALYSIS .
./vsintegration/src/FSharp.Editor/Diagnostics/ProjectDiagnosticAnalyzer.fs:#if PROJECT_ANALYSIS
./vsintegration/tests/unittests/ProjectDiagnosticAnalyzerTests.fs:#if PROJECT_ANALYSIS
```

**Comment by auduchinok** [comment]
@dsyme Thank you for the history of it, it makes sense for me now.
