### ISSUE TITLE
Record Label Inferences do not work in Sub-Module

### ISSUE THREAD

**Issue by EBrown8534** [Microsoft/visualfsharp#4035]
If you define a module with a type inside, and do not open the module, when you instance a type from that module you either have to include the fully-qualified name, or declare the object as having the fully-qualified type.

#### Repro steps

```fsharp
    module Thing =
        type SomeType = { A : string; B : int }
    let someType = { Thing.SomeType.A = "Test"; B = 5 }
    // The above errors at "B":
    // Error : FS0039 : The record label 'B' is not defined.	
    let someType : Thing.SomeType = { A = "Test"; B = 5 }
    let someType = { Thing.SomeType.A = "Test"; Thing.SomeType.B = 5 }
    // Both of the above mitigate the issue
    open Thing
    let someType = { A = "Test"; B = 5 }
    // The above also mitigates the issue, though the `open` is required.
```
#### Expected behavior

I would expect it to not error on the `B` label.

#### Actual behavior

It errors on the `B` label, with: "FS0039 : The record label 'B' is not defined."

#### Known workarounds

Define the object with the full type-name, or fully-qualify the type on all record labels.

#### Related information 

* Windows 10 Pro
* Stable
* .NET 4.6.1
* Visual Studio 2017 15.4.0
* Minor / Convenience

**Comment by charlesroddie** [comment]
The current behavior seems reasonable to me.

**Comment by dsyme** [comment]
@EBrown8534 It's currently by spec, but please open an fslang-suggestion.

thanks
don
