### ISSUE TITLE
tcConfigB.primaryAssembly is set three times during incremental builder creation

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#4039]
The first time:
https://github.com/Microsoft/visualfsharp/blob/3c07e576cb96f4d8324d3394caa1a96d735f684c/src/fsharp/vs/IncrementalBuild.fs#L1747-L1751

The second time right after the first time:
https://github.com/Microsoft/visualfsharp/blob/3c07e576cb96f4d8324d3394caa1a96d735f684c/src/fsharp/vs/IncrementalBuild.fs#L1753-L1754

And once again:
https://github.com/Microsoft/visualfsharp/blob/3c07e576cb96f4d8324d3394caa1a96d735f684c/src/fsharp/vs/IncrementalBuild.fs#L1758-L1761

Was there any specific reason of doing it several times? (e.g. if for some reason several profiles were passed in args, to use the first target profile provided and to override what was set during args parsing)
Is it just old code bits that weren't removed for some reason? If yes, I'll open a PR removing the first and the last times setting it.

**Comment by dsyme** [comment]
> Was there any specific reason of doing it several times? 

I don't think so.  By all means propose a PR and we can review carefully
