### ISSUE TITLE
Publish fresh FSharp.Compiler.Tools package

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#4044]
![image](https://user-images.githubusercontent.com/873919/33481353-2c036308-d6a5-11e7-8416-337ac3d4836c.png)

**Comment by cartermp** [comment]
cc @dsyme

**Comment by dsyme** [comment]
@cartermp Yes, we'll do it on next integration to fsharp/fsharp

**Comment by dsyme** [comment]
Integrating here: https://github.com/fsharp/fsharp/pull/801

**Comment by cartermp** [comment]
Closing as this was completed
