### ISSUE TITLE
Complete the migration from VSTS to be purely github-based

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#4057]
#4047 is the work for this.  The bulk of this work is to move localization support from our internal copy of this repository to GitHub.

**Comment by brettfo** [comment]
This is now done for the branches `master` and `dev15.6`.  It's not worth back-porting this to `dev15.5` as we're unlikely to release from there again.

**Comment by cartermp** [comment]
Yeeeee


On Tue, Dec 5, 2017, at 12:52, Brett V. Forsgren wrote:
> Closed #4057[1].


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].> 

Links:

  1. https://github.com/Microsoft/visualfsharp/issues/4057
  2. https://github.com/Microsoft/visualfsharp/issues/4057#event-1373512951
