### ISSUE TITLE
[Tooling RFC Update required] Package management endpoint

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#4062]
See #4042 and https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1027-fsi-references.md

A pluggable extension point for a package manager (NuGet and Paket, realistically) needs to be added to F# Interactive.  This work will move us towards unblocking fully F# Interactive support on .NET Core.

**Comment by dsyme** [comment]
I'll close this. We do have to update the RFC but lets do this as a natural part of getting #4042 over the line
