### ISSUE TITLE
Tooltip does not show enum filed values defined in a referenced C# project

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#4065]
![image](https://user-images.githubusercontent.com/873919/33650807-944e3230-da74-11e7-94be-142fbfffa664.png)

**Comment by cartermp** [comment]
Is there a project you can share? This works for a simple C# class library for me in VS 15.5:

![enums](https://user-images.githubusercontent.com/6309070/33677476-c2011050-da6d-11e7-9cb1-7b5283abf7b7.PNG)

**Comment by vasily-kirichenko** [comment]
It's reproduced for enums that have `byte` as underlined type only:
```csharp
public enum IntEnum : int
    {
        Case1 = 0,
        Case2 = 1
    }

    public enum Int16Enum : short
    {
        Case1 = 0,
        Case2 = 1
    }

    public enum ByteEnum : byte
    {
        Case1 = 0,
        Case2 = 1
    }

    public enum Int64Enum : long
    {
        Case1 = 0,
        Case2 = 1
    }
```
![image](https://user-images.githubusercontent.com/873919/33794472-e1ecf984-dcdd-11e7-8dd7-295be7c6ea39.png)

![image](https://user-images.githubusercontent.com/873919/33794469-d5020d90-dcdd-11e7-8c04-a9dfe1ec7fa4.png)

![image](https://user-images.githubusercontent.com/873919/33794474-ecb3f08e-dcdd-11e7-9d20-72650bd7ce9d.png)

![image](https://user-images.githubusercontent.com/873919/33794475-f4e79710-dcdd-11e7-8f7d-05c89ab26f27.png)
