### ISSUE TITLE
VF# solution doesn't load

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#4067]
@brettfo It looks like the xliff merge is the root cause:

![fail](https://user-images.githubusercontent.com/6309070/33676920-eb2da86e-da6b-11e7-892e-6f96b22b5889.PNG)

And this is latest master:

```
commit bc9f2a16183285e6c7aef3c5e91d8155bc474127 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Merge: cf48f76a 76e1d09f
Author: Brett V. Forsgren <brettfo@microsoft.com>
Date:   Tue Dec 5 10:37:50 2017 -0800

    Merge pull request #4051 from brettfo/publish-branches

    change nightly publishing branches to be from GitHub
```

When doing these sorts of infra merges, can we make sure the solution loads/builds in VS prior to a merge?

**Comment by vasily-kirichenko** [comment]
I'm sure this is the third time it's broken in the same way.

**Comment by brettfo** [comment]
> When doing these sorts of infra merges, can we make sure the solution loads/builds in VS prior to a merge?

The solution loads; since the `XliffTasks` package is new; you need to re-run `build.cmd` to restore it first.

**Comment by cartermp** [comment]
Got it - re-running `build` did the trick. Thanks!
