### ISSUE TITLE
National characters in string literals are treated as the same if source file encoding is not utf

### ISSUE THREAD

**Issue by ogvolkov** [Microsoft/visualfsharp#407]
If source file encoding is not UTF-8, and it contains string literals with national characters, all such characters are replaced with Unicode replacement character in the resulting assembly, leading to weird issues in string comparison and regular expressions. The problem also applies to fsi.

For example, the following two distinct Cyrillic characters are considered equal if the encoding of the input file is Windows 1251:

    module Test
    printfn "%b" ("а" = "б")

The code above returns true if source encoding is cp1251, and false if it is utf-8.

While having input files not in UTF-8 may not be considered "normal", the outcomes are quite disasterous and very misleading. As an example, C# compiler does the right thing regardless of the source file encoding.

The F# version having the issue is 3.1 (12.0.30110.0)

**Comment by latkin** [comment]
AFAIK there is no support for non-UTF-8 source files in F#. The 3.0 language spec states:

> All input files are currently assumed to be encoded as UTF-8

If someone contributed fixes in this area we would probably be open to considering them, but it's not something we see as particularly high priority.

**Comment by dsyme** [comment]
I'm closing this as it is by-design. Please add an entry to http://fslang.uservoice.com to cover the suggestion
