### ISSUE TITLE
Prepare PR's for the next release of the F# SDK

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#4072]
/cc @dsyme @PatrickMcDonald @saul @mjmckp @0x53a @OnurGumus @liboz @jack-pappas @manofstick 

VS 2017.6 will include an version number FSharp.Core revision and so we are able to add new API's to it.

[This list of PR's need attention:](https://github.com/Microsoft/visualfsharp/pulls?q=is%3Apr+is%3Aopen+label%3A%22Candidate+for+F%23+4.3%22)

Please review, comment, fix merge conflicts, or let me know to consider them for the next update.

If the changes are approved and green by January then they will be in.  Any that go green after that will be subject to our ability to negotiate with ship room.

==================================================================

**[WIP, FS-1042] Implement transpose on Seq, List and Array** https://github.com/Microsoft/visualfsharp/pull/4020

**[FS-1041] Add IReadOnlyCollection/List/Dictionary implementations to FSharp.Core collections**  
https://github.com/Microsoft/visualfsharp/pull/4014
**Add NativePtr.toByRef** 
https://github.com/Microsoft/visualfsharp/pull/3691

**[RFC Needed] F# 4.x: Add ToFSharpFunc overloads for Func<...>, especially for .NET Core**
https://github.com/Microsoft/visualfsharp/pull/3013

**[FS-1028] - Implement Async.StartImmediateAsTask**
https://github.com/Microsoft/visualfsharp/pull/2534

**[FS-1041] Add System.Collections.ICollection implementations to F# set/map**
https://github.com/Microsoft/visualfsharp/pull/2085

==================================================================

**Comment by cartermp** [comment]
@KevinRansom A number of these PRs are _language features_ and not additions to FSharp.Core.  As per our conversation yesterday, we are revving the _F# SDK_, not the _F# language_.  The following PRs are cut out of this by that definition:

* #1517 
* #2382 
* #2671 
* #3967 
* #3968

**Comment by dsyme** [comment]
@cartermp I've removed those from the list

**Comment by cartermp** [comment]
Closing as #3013  and #2085 did not make the cut
