### ISSUE TITLE
Replace Embed property with EmbeddedFiles item group in Microsoft.FSharp.Targets

### ISSUE THREAD

**Issue by tmat** [Microsoft/visualfsharp#4075]
We need to unify on ```EmbeddedFiles``` item group accross C#, VB and F#. The former two use ```EmbeddedFiles``` item group while F# uses ```Embed``` property.

Replace

```
Embed="$(Embed)"
```

with

```
Embed="@(EmbeddedFiles)"
```

**Comment by tmat** [comment]
@KevinRansom

**Comment by dsyme** [comment]
@tmat Is this a breaking change?

**Comment by tmat** [comment]
@dsyme Yes.  You can make it non-breaking if you replace it with ```Embed="$(Embed);@(EmbeddedFiles)"```.
