### ISSUE TITLE
StackOverflow in fsc without LCID param

### ISSUE THREAD

**Issue by nwolverson** [Microsoft/visualfsharp#408]
I had a F# project which would compile in VS but not with command line msbuild. (fsproj had previously been created/edited by VS and XS so may be nontypical).

Getting fsc failing with StackOverflow exception when not passing `LCID` param, but passing if I give `LCID=1033`.

The project in question references a type provider - project here https://github.com/nwolverson/signalrprovider/tree/1f11fe879743d058d4a86485926fd12ff78f7188 

    C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe -o:obj\Release\SignalRFunScriptClient.dll --debug:pdbonly --noframework --define:TRACE --doc:bin\Release\SignalRFunScriptClient.XML --optimize+ -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\FSharp.Core.dll" -r:C:\Users\Nicholas\git\srtptest\signalrprovider\demo\packages\FunScript.1.1.49\lib\net40\FunScript.dll -r:C:\Users\Nicholas\git\srtptest\signalrprovider\demo\packages\FunScript.1.1.49\lib\net40\FunScript.Interop.dll -r:C:\Users\Nicholas\git\srtptest\signalrprovider\demo\packages\FunScript.TypeScript.Binding.jquery.1.1.0.37\lib\net40\FunScript.TypeScript.Binding.jquery.dll -r:C:\Users\Nicholas\git\srtptest\signalrprovider\demo\packages\FunScript.TypeScript.Binding.lib.1.1.0.37\lib\net40\FunScript.TypeScript.Binding.lib.dll -r:C:\Users\Nicholas\git\srtptest\signalrprovider\demo\packages\FunScript.TypeScript.Binding.signalr.1.1.0.37\lib\net40\FunScript.TypeScript.Binding.signalr.dll -r:C:\Users\Nicholas\git\srtptest\signalrprovider\demo\packages\FunScript.TypeScript.Binding.underscore.1.1.0.37\lib\net40\FunScript.TypeScript.Binding.underscore.dll -r:C:\Users\Nicholas\git\srtptest\signalrprovider\demo\packages\Microsoft.AspNet.SignalR.Core.2.1.0\lib\net45\Microsoft.AspNet.SignalR.Core.dll -r:C:\Users\Nicholas\git\srtptest\signalrprovider\demo\packages\Microsoft.Owin.2.1.0\lib\net45\Microsoft.Owin.dll -r:C:\Users\Nicholas\git\srtptest\signalrprovider\demo\packages\Microsoft.Owin.Security.2.1.0\lib\net45\Microsoft.Owin.Security.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" -r:C:\Users\Nicholas\git\srtptest\signalrprovider\demo\packages\Newtonsoft.Json.6.0.3\lib\net45\Newtonsoft.Json.dll -r:C:\Users\Nicholas\git\srtptest\signalrprovider\demo\packages\Owin.1.0\lib\net40\Owin.dll -r:C:\Users\Nicholas\git\srtptest\signalrprovider\build\SignalRProvider.dll -r:C:\Users\Nicholas\git\srtptest\signalrprovider\build\SignalRProviderRuntime.dll -r:C:\Users\Nicholas\git\srtptest\signalrprovider\demo\SignalRServer\bin\Release\SignalRServer.dll -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Numerics.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.Linq.dll" --target:library --warn:3 --warnaserror:76 --fullpaths --flaterrors --subsystemversion:6.00 --highentropyva+ "C:\Users\Nicholas\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.fs" SignalRClient.fs  (TaskId:91)
    Microsoft (R) F# Compiler version 12.0.30815.0 (TaskId:91)
    Copyright (c) Microsoft Corporation. All Rights Reserved. (TaskId:91)
    (TaskId:91)
    Process is terminated due to StackOverflowException. (TaskId:91)

**Comment by enricosada** [comment]
I cannot build the commit nwolverson/signalrprovider@1f11fe879743d058d4a86485926fd12ff78f7188  I tried to add a `RestorePackages()` to fake, but i get missing nuget, etc. 
Same inside visual studio, `demo\SignalRProviderTest.sln` doesn't build.

i tried with master branch nwolverson/signalrprovider@1f11fe879743d058d4a86485926fd12ff78f7188 and i can repro

- build bat
- move to demo dir
- fsc -> stackoverflow exception :x:

**Comment by latkin** [comment]
Has anyone investigated where the SO occurs?  Is it in the type provider itself? A minimal repro would be useful here.

**Comment by nwolverson** [comment]
I'm sorry, this is a SO in my type provider, an `AssemblyResolve` handler on a new `AppDomain` is recursively loading `FSharp.Core.Resources`, which I guess is only being loaded if the culture is set to other than `en-US` - and my system culture is `en-UK`.

(For reference loaded from a generic equality comparison inside `FSharpType.IsRecord`)

I was thrown by the fact that VS and msbuild behave differently on building my project/solution, in that VS passes in the `LCID` parameter to specify US locale - I still don't understand this difference.

**Comment by enricosada** [comment]
@nwolverson you closed the issue by mistake? 
I can repro with tour version, but i think is fixed with new version. 
I'll try to bisect the error

**Comment by nwolverson** [comment]
@enricosada I closed the issue because I don't think there was a bug here, there was a bug in my type provider only surfacing when compiler invoked with non-US locale as described in my previous comment - for which I pushed change https://github.com/nwolverson/signalrprovider/commit/4909e031c4b63650f261383af17101ffcdad6c41
