### ISSUE TITLE
Rename unused symbol with "_" applied to function results with uncompilable code

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#4080]
![1](https://user-images.githubusercontent.com/873919/33777389-a8abca0c-dc55-11e7-98f4-895a9458e5d4.gif)

**Comment by cartermp** [comment]
Interesting - was this in a script file? I notice that the analyzer does trigger in a Program.fs nor inside of a module, but it will trigger in a script.

**Comment by vasily-kirichenko** [comment]
yes this is in a script. I don’t think we filter symbols in the fixer in any way.

**Comment by cartermp** [comment]
Yep, we don't.

**Comment by vasily-kirichenko** [comment]
Yes, been there a minute ago. There is no `IsValue` property :( There is `IsModuleValue` or something, but it does not cover class ctor let bindings and local vars.

**Comment by cartermp** [comment]
Might require some additions to name resolution then 😢
