### ISSUE TITLE
Complition suggests a lot of symbols on function name at declaration position

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#4081]
![image](https://user-images.githubusercontent.com/873919/33777457-f4750322-dc55-11e7-8f1d-194d9f64557b.png)

**Comment by cartermp** [comment]
Interesting - was this in a script file?  I notice that the analyzer does trigger in a `Program.fs` nor inside of a module, but it will trigger in a script.

**Comment by cartermp** [comment]
Can repro everywhere

**Comment by vasily-kirichenko** [comment]
Fixed via https://github.com/Microsoft/visualfsharp/pull/5083
