### ISSUE TITLE
VS 2017 15.5.0 - Multitargeting just plain doesn't work

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/visualfsharp#4084]
To reproduce, simply create a console app, edit the fsproj and switch from `TargetFramework`to `TargetFrameworks`. Here is a video demo:

https://youtu.be/jxrtAIvMPzE

**Comment by ctaggart** [comment]
IntelliSense is also not working with TargetFrameworks. Essentially, TargetFrameworks does not work in F#.

**Comment by cartermp** [comment]
In general, multitargeting with F# is completely hosed.  We haven't estimated the extent of the work, but I suspect it will be complicated given the space of things that can go wrong and the large amount of work that had to go into it for C#/VB tooling (and even today, there's no experience for multitargeting in the UI, forcing you to use some of the weirdo MSBuild syntax to express dependencies for different targets under whatever conditions are relevant to you).

I don't recommend multitargeting today unless you _must_ target something that .NET Standard doesn't cover today.

**Comment by ctaggart** [comment]
Thanks for the confirmation. I noticed.

Unity only support net46 and does not yet support netstandard. We have common code that we want to share in a library for Unity and for a server side web app. The web app, we want to deploy on dotnet core. Most likely, Unity will ship netstandard support in the first release of 2018 and then we'll be in a good position again.

When you multitarget, the Visual Studio UI gives you a selectbox to switch between the target frameworks:

### C#
![image](https://user-images.githubusercontent.com/80104/33919870-bc94e3c2-df99-11e7-9549-e8fbe47377dd.png)

### F#
![image](https://user-images.githubusercontent.com/80104/33919887-d2b13b60-df99-11e7-84da-459e7298f800.png)

**Comment by eiriktsarpalis** [comment]
+1 on this. Would really like to see this issue addressed.

**Comment by ctaggart** [comment]
C# in 15.5 simply runs and debugs the first one listed in TargetFrameworks. I learned this the hard way yesterday when trying to debug SourceLink. I only have the netcore 2 sdk installed, not netcore 1 sdk on this laptop. I got some obscure runtime error until I changed `netcoreapp2.0` [to be first](https://github.com/ctaggart/SourceLink/commit/a3f6cb8f45a5b76e271624f1c6b5303da2b6e182#diff-e04acac7da9dfc7330d784abc8ed32f9R5). My recommendation for a short term fix is to simply use the first framework listed for debugging just like C# does.

**Comment by jackfoxy** [comment]
Handy repo to develop/test with https://github.com/jackfoxy/multitargetpaket
This now works with Ionide. I would really like to see VS catch up on this.

**Comment by noelmcgrath** [comment]
any update when this will be available?

**Comment by cartermp** [comment]
We're closing in on the (quite huge) amount of work to complete file ordering with folder support and all current UI gestures for .NET Core SDK projects shipping in 15.6. Once that's locked down, we'll be looking at this and trying to get it fixed for 15.7.

**Comment by dmitry-a-morozov** [comment]
Suggested workaround: Have a single target defined for debug and use multi-targeting for release/deploy. 
```xml
    <TargetFramework Condition="'$(Configuration)'=='Debug'">net461</TargetFramework>
    <TargetFrameworks Condition="'$(Configuration)'=='Release'">netstandard2.0;net461</TargetFrameworks>
```

**Comment by paulostradioti** [comment]
Hi all,

Have this issue been resolved? It seems that the problem persists in Visual Studio 2022 and it only hits breakpoints in the first target framework.

cc @cartermp, @dsyme 
Thank you, 
Paulo
