### ISSUE TITLE
[ASP.NET] Update the F# web templates to add support for the HTTPS middleware

### ISSUE THREAD

**Issue by javiercn** [Microsoft/visualfsharp#4086]
As per our recent discussions, I've file a bug here and a tracking bug on our repo to update the F# web templates. See https://github.com/aspnet/templating/issues/185

Let me know if you need more information.

**Comment by cartermp** [comment]
I'll take a look at this later today.

**Comment by cartermp** [comment]
Done in https://github.com/aspnet/templating/pull/190 and https://github.com/aspnet/templating/pull/219
