### ISSUE TITLE
Type inference failure with JsonProvider

### ISSUE THREAD

**Issue by NullEntity** [Microsoft/visualfsharp#4089]
Type inference fails in some cases when using JsonProvider. I have not tested this with other type providers.

#### Repro steps
Execute the following snippet:
```
open FSharp.Data
type Foos = JsonProvider<"""[{"property": "value"}]""">
let a = Seq.map (fun x -> x.Property) (Foos.GetSamples())
```

#### Expected behavior

Type of parameter x should be inferred as `Foos.Foo`.

#### Actual behavior

The compiler gives the following error:
```
 error FS0072: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.
```

#### Known workarounds
When the erroring line is written with the forward pipe operator then the type of x is correctly inferred.
```
let a = Foos.GetSamples() |> Seq.map (fun x -> x.Property) 
```

#### Related information 
Tested with VS 2017 and F# 4.1

**Comment by tldrlol** [comment]
Alternatively, explicitly specifying the type is another workaround.

`(fun (x:Foos.Root) -> x.Property)` works too.

The weird part is how the VS tooling is able to infer the correct type of `x`, as can be seen by mousing over it. And yet it fails during actual compilation.

**Comment by dsyme** [comment]
This is by design, it's how F# type inference works, with or without the use of a type provider.  

There's an issue somewhere about the fact that VS uses the final results of type inference in the tooltip displays
