### ISSUE TITLE
Memory is not released after switching between build configurations

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#4091]
1. Open VFT solution, wait until CPU is idle.
2. Switch to Release configuration, wait until CPU is idle.
3. Switch back to Debug, wait, wait, wait.

Result: devenv.exe is about 2.5GB, no features works.

**Comment by dsyme** [comment]
Closing as I believe this has been addressed by the improvements to memory usage and caching in VS
