### ISSUE TITLE
No record field completion

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#4098]
```fsharp
module DataCentricPrograms

open System.Drawing

type Rect =
    { Left: float32
      Top: float32
      Width: float32
      Height: float32 }

let toRectangleF(original) =
    RectangleF(original.Left, original.Top, original.<caret>)
```

**Comment by vasily-kirichenko** [comment]
It does work in an expression

![image](https://user-images.githubusercontent.com/873919/33805037-c6bbc5f6-ddc2-11e7-80fd-6ac107b62fb0.png)

**Comment by vasily-kirichenko** [comment]
![1](https://user-images.githubusercontent.com/873919/33805079-79bd3432-ddc3-11e7-90af-65aaf92afdff.gif)

**Comment by vasily-kirichenko** [comment]
so it works on odd arguments and does not work - on even ones o_O

**Comment by vasily-kirichenko** [comment]
Looks like it's related to the fact that it has three constructors

![image](https://user-images.githubusercontent.com/873919/33805119-3a51c88e-ddc4-11e7-8042-c0fbae7d9c35.png)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/4105

**Comment by charlesroddie** [comment]
"-How do we tell whether she is made of wood? -Build a bridge out of her. -Ah, but can you not also make bridges out of stone?"

Questionable inference as Sir Bedevere points out!

**Comment by vasily-kirichenko** [comment]
@charlesroddie ?

**Comment by realvictorprm** [comment]
This was hilarious

Am 10.12.2017 14:03 schrieb "Vasily Kirichenko" <notifications@github.com>:
