### ISSUE TITLE
FSI, wrong version description

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#410]
vs 2015 RC:

The fsi panel (same in fsi.exe):

```
Microsoft (R) F# 3.0 Interactive - versione 14.0.22810.0
```

is it correct `3.0` instead of `4.0`?

**Comment by latkin** [comment]
I don't see that on my system.  FSI banner is:

    Microsoft (R) F# Interactive version 14.0.22810.0
    Copyright (c) Microsoft Corporation. All Rights Reserved.

FSC banner is

    Microsoft (R) F# Compiler version 14.0.22810.0
    Copyright (c) Microsoft Corporation. All Rights Reserved.

Maybe an issue with the localized translation?

**Comment by enricosada** [comment]
fsi
```
C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0>fsc
Compilatore Microsoft (R) F# versione 14.0.22810.0
Copyright (c) Microsoft Corporation. Tutti i diritti riservati.
```

fsc
```
Microsoft (R) F# 3.0 Interactive - versione 14.0.22810.0
Copyright (c) Microsoft Corporation. Tutti i diritti riservati.
```

yes, localization issue

```xml
 <data name="fsiProductName" xml:space="preserve">
    <value>Microsoft (R) F# 3.0 Interactive - versione {0}</value>
  </data>
```

in both `Fsi.resources.dll` and `FsiAnyCPU.resources.dll` ( `C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\it` )

**Comment by enricosada** [comment]
i cannot find the `ita` localization in resource file, it's not in this repo right?
if translation is inside the repo, fix  typos is easy ( see NuGet/NuGet.CommandLine@a34490ab0ec6cde0549df367c101c9b01394b8b5 )

**Comment by latkin** [comment]
Localized resources are not part of the public repo, we'll have to track this internally

**Comment by enricosada** [comment]
i checked the `it` fsi resources (decompiled from dll), the only one i found is

### fsiConsoleProblem

lang | text
--- | ---
| en | Try selecting Tools-&gt;Options-&gt;F# Interactive for Visual Studio and enter '--fsi-server-no-unicode |
| it | Provare a scegliere Strumenti-&gt;Opzioni-&gt;F# Interactive per Visual Studio e immettere '--fsi-server-no-unicode' |

the path `Tools->Options->F# Interactive for Visual Studio` does not exists, is `Tools->Options->F# Tools->F# Interactive`

another trivial :smile:

**Comment by KevinRansom** [comment]
@enricosada if you are interested our localization team are planning on doing a linguistics review to make sure the terms are the correct ones,  Send me your email and I can forward your email to them if you would like to participate.

my email alias is kevinr @ the company I work for .com

Kevin

**Comment by latkin** [comment]
I don't think we fixed this one before RTM.

**Comment by enricosada** [comment]
nope, i can repro with rtm version of vs 2015

**Comment by KevinRansom** [comment]
Fixed
