### ISSUE TITLE
Intellisense adds "....Module" when conflicting type and module appears together

### ISSUE THREAD

**Issue by ChangHaiBin** [Microsoft/visualfsharp#4101]
My goal is to create a "Person" type and a "Person" module that I can call functions easily.

However, having the type and module of the exact same name may not be a good idea. It may be a better idea to have a "person" type and a "Person" module for the functions, 
similar to how there is a "seq", "list" type, but the functions are in "Seq", "List", etc.

#### Repro steps

We start with the following two files, "Example.fs" and "Program.fs"

![workingcode](https://user-images.githubusercontent.com/12854096/33804334-8b890fe6-dddd-11e7-9614-73e79e9f6606.png)

The code above compiles correctly. The compiler correctly identifies that "Person.getName" is from the module "Person", not the type "Person".

If we delete "Person" from "let extractName = Person.getName bob", then we expect an error.

However, when I hover my mouse above the error, I see the following suggestion:

![intellisenseerror](https://user-images.githubusercontent.com/12854096/33804183-9506c87c-ddda-11e7-896a-71585c833dd3.png)

#### Expected behavior

Expected intellisense to suggest 
"open Example.Person"

#### Actual behavior

Intellisense suggested
"open Example.PersonModule"

Selecting this Intellisense suggestion will not solve the "getName" error.

#### Known workarounds

Similar to how the type for IEnumerable is called "seq", but the functions are located in "Seq", e.g. Seq.map, Seq.sum

similarly, there is a "list" type, but the functions are located in "List", e.g. List.map, List.sum

So, I can just define the type to be "person", and the functions located in "Person"

___________________

Also, there is also a blog post on fsharpforfunandprofit about organizing functions:

https://fsharpforfunandprofit.com/posts/recipe-part3/

#### Related information 

IDE used: Visual Studio Community 2017

Thank you very much for your help.

**Comment by vasily-kirichenko** [comment]
It works OK if the attribute explicitly applied:

![image](https://user-images.githubusercontent.com/873919/33804566-dc9816fe-ddb8-11e7-859c-36a08d580fcc.png)

**Comment by vasily-kirichenko** [comment]
So, with explicit attribute it compiles to
```csharp
[CompilationMapping(SourceConstructFlags.Module), CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)]
public static class PersonModule
{
	public static string getName(M.Person person)
	{
		return person.Name@;
	}
}
```
and without one to
```fsharp
[CompilationMapping(SourceConstructFlags.Module)]
public static class PersonModule
{
	public static string getName(M.Person person)
	{
		return person.Name@;
	}
}
```
So... We have inconsistent code generation: if there is a type with the same name, `Module` suffix is appended implicitly, but the attribute is not added. As a consequent, we cannot distinguish if `Module` is auto generated or it's just a normal module name.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/4102
