### ISSUE TITLE
VS2015 rc - no f# templates

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#411]
After fresh install of visual studio 2015 rc (web+sl+xam+github) i see only xamarin f# project templates

![image](https://cloud.githubusercontent.com/assets/147243/7457058/ea786750-f289-11e4-8293-0dcef47485d5.png)

This computer had installed vs 2013 premium ( works ok after installation )

VS2015 info:

```
Microsoft Visual Studio Community 2015 RC
Versione 14.0.22823.1 D14REL
Microsoft .NET Framework
Versione 4.6.00057

Edizione installata: Community

Visual Basic 2015 RC   00269-30000-00001-AA562
Microsoft Visual Basic 2015 RC

Visual C# 2015 RC   00269-30000-00001-AA562
Microsoft Visual C# 2015 RC

Visual C++ 2015 RC   00269-30000-00001-AA562
Microsoft Visual C++ 2015 RC

Visual F# 2015 RC   00269-30000-00001-AA562
Microsoft Visual F# 2015 RC

ASP.NET and Web Tools RC   14.0.20417.0
ASP.NET and Web Tools RC

ASP.NET Web Frameworks and Tools 2013   5.2.30411.0
For additional information, visit http://www.asp.net/

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

Gestione pacchetti NuGet   3.0.0
Gestione pacchetti NuGet in Visual Studio. Per ulteriori informazioni su NuGet, visitare il sito Web http://docs.nuget.org/.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Pacchetto di Strumenti Application Insights per Visual Studio   1.0
Strumenti Application Insights per Visual Studio

SQL Server Data Tools   14.0.50325.0
Microsoft SQL Server Data Tools

Strumenti comuni di Azure   1.4
Fornisce servizi comuni da usare con Servizi mobili di Azure e gli strumenti di Microsoft Azure.

Strumenti di Servizi Mobili di Microsoft Azure   1.4
Strumenti di Servizi Mobili di Microsoft Azure

Xamarin   3.11.450.0 (2ab5145)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   5.1.0.115 (d23da369e436488f38c8ab8fe8a9ae7d9ea5256b)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   8.10.0.0 (7741cc495ab0baf04ff0405d0604bc27f0ecae2e)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified

Xamarin.TestCloud.Integration   1.0
Early preview of Xamarin Test Cloud integration
```

**Comment by enricosada** [comment]
@latkin if you need system info or something else, just ask

**Comment by latkin** [comment]
You are using Italian OS, correct?

**Comment by enricosada** [comment]
win7 pro italian, i'll send you the complete system info asap.
btw, what is the path of the project templates zip files?

**Comment by KevinRansom** [comment]
I fixed the bug Friday.

**Comment by StefanBelo** [comment]
How to fixed this problem. I installed VS 2015 Community Update 1 and all F# templates are missing now. I cannot even add F# source file to existing project.

**Comment by enricosada** [comment]
@StefanBelo thats a closed issue for visual studio 2015 RC ( release candidate ).
can you open a new issue? i think previous discussion in this issue there are from a really different codebase and are useless to diagnose your problem

**Comment by parmigianig** [comment]
Hi. i have this same issue now in version 14.0.25123.00 Update 2 of Visual Studio Professional 2015.
all project templates for f# (except android and ios projects) are missing. is this related to Xamarin recent integration? 

> 
> Microsoft Visual Studio Professional 2015
> Version 14.0.25123.00 Update 2
> Microsoft .NET Framework
> Version 4.6.01055
> 
> Installed Version: Professional
> 
> Visual Basic 2015   00325-60003-35761-AA731
> Microsoft Visual Basic 2015
> 
> Visual C# 2015   00325-60003-35761-AA731
> Microsoft Visual C# 2015
> 
> Visual C++ 2015   00325-60003-35761-AA731
> Microsoft Visual C++ 2015
> 
> Visual F# 2015   00325-60003-35761-AA731
> Microsoft Visual F# 2015
> 
> Windows Phone SDK 8.0 - ENU   00325-60003-35761-AA731
> Windows Phone SDK 8.0 - ENU
> 
> Application Insights Tools for Visual Studio Package   5.205.60510.1
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
> ASP.NET and Web Tools 2015 (RC1 Update 1)
> 
> ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
> For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563
> 
> ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
> For additional information, visit http://www.asp.net/
> 
> Azure App Service Tools v2.7.1   14.0.11112.0
> Azure App Service Tools v2.7.1
> 
> CodeMaid   10.1.93
> CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.
> 
> Common Azure Tools   1.7
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> GitHub.VisualStudio   1.0
> A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> JetBrains ReSharper Ultimate 2015.2   Build 103.0.20150818.200216
> JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2016 JetBrains, Inc.
> 
> Microsoft Azure Mobile Services Tools   1.4
> Microsoft Azure Mobile Services Tools
> 
> MoveTypeToFile   1.0
> MoveTypeToFile
> 
> NuGet Package Manager   3.4.3
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> PreEmptive Analytics Visualizer   1.2
> Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
> 
> SlowCheetah - XML config transforms    1.0
> This package enables you to transform your app.config or any other XML file based on the build configuration. It also adds additional tooling to help you create XML transforms.
> 
> SQL Server Data Tools   14.0.60311.1
> Microsoft SQL Server Data Tools
> 
> TypeScript   1.8.30.0
> TypeScript tools for Visual Studio
> 
> Visual F# Power Tools   2.4.1
> A collection of additional commands for F# in Visual Studio
> 
> Visual Studio Tools for Universal Windows Apps   14.0.25208.00
> The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.
> 
> WhereAmI 2015   1.0
> WhereAmI? (for VS2015)
> 
> Xamarin   4.0.3.214 (0dd817c)
> 
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin.Android   6.0.3.5 (a94a03b)
> Visual Studio plugin to enable development for Xamarin.Android.
> 
> Xamarin.iOS   9.6.1.8 (3a25bf1)
> Visual Studio extension to enable development for Xamarin.iOS.
