### ISSUE TITLE
Send to (interfactive/F# Interactive) 

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#412]
Trivial. vs2015, the italian version, dont know if is the same issue in the english version

![image](https://cloud.githubusercontent.com/assets/147243/7457647/6abe2c2a-f28e-11e4-94e0-6c934ce8efbb.png)

translated, one is to  `run in interactive`, the other is `run debug in F# interactive` . 
Better use only `interactive` (Esegui debug in interattivo), less confusion

**Comment by latkin** [comment]
The wording was inconsistent for a time but this was fixed before RTM. It should be "Execute in interactive" / "Debug in interactive", no "F#" in either.
