### ISSUE TITLE
Wrong tab/spaces default

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#413]
the default Tools -> Options -> Text Editor -> F# -> Tabs is `Keep tabs` instead of `Insert spaces` 

Fresh vs 2015 install, 2013 premium was installed. 
I did not choose to import config from older version at vs 2015 bootstrap
Others f# configs ( General, Scroll Bars ) are ok

vs 2015

![image](https://cloud.githubusercontent.com/assets/147243/7458224/074ec866-f293-11e4-8474-891586084937.png)

vs 2013

![image](https://cloud.githubusercontent.com/assets/147243/7458239/2d5b0a24-f293-11e4-81a8-a608d6ea4ee2.png)

**Comment by latkin** [comment]
Same as #199, let's keep using that one for discussion.  We need a consistent repro.
