### ISSUE TITLE
Function is no longer tail recursive after removing unnecessary argument

### ISSUE THREAD

**Issue by nikonthethird** [Microsoft/visualfsharp#4141]
I was messing around with implementing `List.foldBack` myself tailrecursively. I noticed that when applying a certain optimization (`fun arg -> (stuff) arg` should be equivalent to just `(stuff)`), suddenly my code was no longer tail recursive and I received a `StackOverflowException`.

#### Repro steps

```fsharp
let flip f b a = f a b

let foldBackTailRec f =
    let rec inner = function
    | [] -> (<|)
    | head :: tail -> fun cont -> (f head |> (>>) >> inner tail) cont // (A) With lambda.
    flip inner id

let foldBackNotTailRec f =
    let rec inner = function
    | [] -> (<|)
    | head :: tail -> f head |> (>>) >> inner tail // (B) Without lambda.
    flip inner id

let run foldBack name =
    foldBack (-) [1 .. 1000000] 0
    |> printfn "%s: %d (should be -500000)" name

run List.foldBack "List.foldBack"
run foldBackTailRec "Tail recursive"
run foldBackNotTailRec "Not tail recursive" // StackOverflowException.


```

#### Expected behavior

The optimization should work.

The line marked (A) could be equally written as `fun cont -> inner tail (f head >> cont)`.
Here it is obvious that the call to `inner` is indeed a tail-call.
It is possible to re-write this line like above, such that the continuation is given as the last argument.
Therefore, it should be possible to get rid of the argument like in the line marked (B), and the behaviour
should be the same.

#### Actual behavior

The code fails with a `StackOverflowException`.

#### Known workarounds

Do not use partial application in this case.

#### Related information 

* Windows 10
* F# 4.1
* F# Runtime 4.4.1.0
* .NET Framework 4.6.1

#### Further information

You can use this version to get a stack trace showing the calls pile up.

```fsharp
open System
open System.IO

let flip f b a = f a b

let foldBack f =
    let rec inner list =
        File.WriteAllText ("StackTrace.txt", Environment.StackTrace)
        match list with
        | [] -> (<|)
        | head :: tail -> f head |> (>>) >> inner tail
    flip inner id

ignore (foldBack (-) [1 .. 10] 0)
```

**Comment by dsyme** [comment]
@nikonthethird I don't think either `` (f head |> (>>) >> inner tail) cont`` or the other one is a guaranteed tailcall.  It might drop out to be a tailcall due to optimizations, but it's not guaranteed.
