### ISSUE TITLE
F# 4.0 VS extension says VS2014 instead of VS2015

### ISSUE THREAD

**Issue by ovatsus** [Microsoft/visualfsharp#415]
Out of the box VS20015 RC:

![image](https://cloud.githubusercontent.com/assets/738761/7474102/229f3a02-f337-11e4-802c-deb9f65d9a49.png)

**Comment by KevinRansom** [comment]
@ovatsus good eyes, I don't know how many times I have seen that without noticing it.  There is some internal deployment files to update so I will take care of it.

Kevin

**Comment by enricosada** [comment]
@KevinRansom as a note, there is no Italian translation. 

I dont care, i am only testing the italian version for next f# release

![image](https://cloud.githubusercontent.com/assets/147243/7478329/57fca6a8-f35a-11e4-83e2-3c8d6ae7d0a8.png)

No logo either, but that's really less than trivial :lipstick: :lipstick::lipstick:, should i open an issue or is a fast fix i can do (not something internal or vNext) ?

**Comment by KevinRansom** [comment]
@enricosada  Is the F# in the product localized, or just the component name.  Please raise a separate issue for this.

**Comment by enricosada** [comment]
F# extension is localized, the extension description not, see the screenshot below.

![image](https://cloud.githubusercontent.com/assets/147243/7478741/dad2f72e-f35c-11e4-8a95-342d1620d562.png)

**Comment by KevinRansom** [comment]
That's much better, because I know I have tested RD with Localized builds, but sometimes other people change stuff and we never even see the change.

Thanks for raising this

**Comment by KevinRansom** [comment]
The fix has been in for a while now:

![untitled](https://cloud.githubusercontent.com/assets/5175830/8625803/ce59a94e-26f5-11e5-807c-56f934d707fb.jpg)
