### ISSUE TITLE
"Unexpected false" - cannot debug VF# tools

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#4155]
Using latest master, f5 into a debug hive, create a new F# .NET Standard library, and then hit enter in the editor.  The Roslyn FatalError.cs file is brought into the editor and looks like this:

![image](https://user-images.githubusercontent.com/6309070/34282752-c6d5270e-e67c-11e7-8af1-c923610634cf.png)

Exception details:
```
System.ExecutionEngineException
  HResult=0x80131506
  Message=Exception of type 'System.ExecutionEngineException' was thrown.

Inner Exception 1:
InvalidOperationException: Unexpected false
```

**Comment by dsyme** [comment]
Roslyn's use of FatalError is really frustrating. What's the stack here?

**Comment by cartermp** [comment]
I can no longer reproduce this on latest master installed into VS 15.6 Preview 5.
