### ISSUE TITLE
VS 2017 15.5 F# can't set breakpoint when TargetFramework net45

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/visualfsharp#4159]
This is very similar to #4084 in that I can't set breakpoints at all in a project. I have an F# .NET Core project that is an exe and a couple of library projects. All of them are set to `<TargetFramework>net45</TargetFramework>`.

I have VS 2017 15.5.2 installed. It is a commercial project that I'm consulting for.  They target Unity, which Unity now supports net46, so I bumped the version. After bumping the version, I was able to set breakpoints. As far as I'm concerned, you can close this as won't fix, but I thought I should get it documented. May be it will become a known issue. It would probably be okay to support only net46 and above.

**Comment by cartermp** [comment]
Was this before switching from `TargetFrameworks` to `TargetFramework`?  The following works for me:

1. New .NET Core app
2. Change TFM to `net45`
3. Set breakpoint in `Program.fs`
4. Run and observe that it breaks at the breakpoint

**Comment by ctaggart** [comment]
Thanks for testing. I am unable to reproduce it with a simple test case. I also just tried to rollback some changes in the project and was not able to reproduce. I don't know, but troubleshooting it is not worth it. I observed it was only on the referenced library projects that I was unable to set the breakpoint.
