### ISSUE TITLE
Extension manifest for VS/VWD and WD are not localized

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#416]
raised by @enricosada in issue: #415 "F# 4.0 VS extension says VS2014 instead of VS2015 #415"

**Comment by enricosada** [comment]
![image](https://cloud.githubusercontent.com/assets/147243/7483668/16936e82-f381-11e4-9ca7-40b670b9021a.png)

**Comment by KevinRansom** [comment]
The template vsix text isn't localized either.  I will take care of that too.

**Comment by KevinRansom** [comment]
Nope, just checked.  The Templates extension.vsixlangpacks are localized.

**Comment by latkin** [comment]
@KevinRansom here's another one, did this get fixed in 4.0 or no?

**Comment by KevinRansom** [comment]
This is handled differently in Dev15
