### ISSUE TITLE
"The result of this expression is implicitly ignored" worning message should include type name of the ignored value

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#4163]
![image](https://user-images.githubusercontent.com/873919/34318853-642501b2-e7e2-11e7-9548-e654a9c720bf.png)

Currently it's impossible to say what's being ignored.

**Comment by dsyme** [comment]
Agreed this would be a good improvement

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/4198
