### ISSUE TITLE
'Move file up/down' keybindings should be scoped to solution explorer

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#417]
We have an internal bug tracking this, wanted to make it public.

Our [current keybindings](https://github.com/Microsoft/visualfsharp/blob/fsharp4/vsintegration/src/vs/FsPkgs/FSharp.Project/FS/MenusAndCommands.vsct#L177-L178) for the "move file up", "move file down" actions are globally-scoped.  This means we hijack `Alt-Up`, `Alt-Down` in some places where we don't need to.

In particular, the Find and Replace dialog also uses these keys, and is getting broken by us.

Fix should be simple - scope our keybindings to Solution Explorer only.

**Comment by ricksladkey** [comment]
This is great!  Thanks a lot.
