### ISSUE TITLE
Visual Studio Fsproj Multi-Target: conditional nuget references not working as expected

### ISSUE THREAD

**Issue by eiriktsarpalis** [Microsoft/visualfsharp#4174]
I am trying to set up a multi-target F# project with the following package configuration:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0; net45</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
    <PackageReference Include="FSharp.Core" Version="4.2.3" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)'=='net45'">
    <PackageReference Include="FSharp.Core" Version="3.1.2" />
  </ItemGroup>
</Project>
```

The loaded project however does not produce the expected output:
![image](https://user-images.githubusercontent.com/2813363/34468208-e4916f64-eefb-11e7-97f6-b72e35c224f8.png)

If I copy and paste the identical configuration in a C# project I get the following result:

![image](https://user-images.githubusercontent.com/2813363/34468212-fb21316a-eefb-11e7-98ad-7834c8f6a109.png)

#### Repro steps

Load the solution found in [this commit](https://github.com/eiriktsarpalis/Repro/tree/507d50a7d51b0a29d79a23f82ca2b53dd0095c59)

**Comment by eiriktsarpalis** [comment]
I should mention I'm using the 15.5.2 release

**Comment by dhwed** [comment]
The FSharp.Core version is set by the Microsoft.FSharp.NetSdk.targets file [found here](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.targets).

So, you're going to want to instead do something like this:
```xml
<PropertyGroup>
  <FSharpCoreImplicitPackageVersion Condition="'$(TargetFramework)'=='net45'">3.1.2</FSharpCoreImplicitPackageVersion>
</PropertyGroup>
```

**Comment by eiriktsarpalis** [comment]
I made a mistake in the reproducing commit. Fixing it made the issue go away. Sorry for the confusion.
