### ISSUE TITLE
Description not available for completion items in .NET Core

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/visualfsharp#4178]
Completion message for most items gives a "Description not available" message.

#### Repro steps

1. Create a new .NET Core F# project

2. In the editor type `pr` to bring up the completion menu.

3. Use the arrow keys to move up and down the list, observe that all items description says "description not available"

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

#### Expected behavior

A description is provided. This is working correctly in non .NET Core projects.

#### Actual behavior

The first use of the menu gives the Description not available message.

#### Known workarounds

Creating a new project, or closing and reopening the project will allow them to be displayed correctly

#### Related information 

Win10
@brettfo notes that it is present in 15.5
Reproducible in both 15.6 and 15.6stg builds

**Comment by cartermp** [comment]
I cannot produce this in VS 15.6 Preview 4:

![works](https://user-images.githubusercontent.com/6309070/36187814-9e8242b4-10fc-11e8-8593-642e56baa2f9.gif)

Closing for now - please re-open if you observe this again.
