### ISSUE TITLE
Incorrect pattern matching warning when using comparison

### ISSUE THREAD

**Issue by shishkin-pavel** [Microsoft/visualfsharp#4188]
```
match x.y with
| z when z < someValue -> 0
| z when z = someValue -> 1
| z when z > someValue -> 2
```

results in "Incomplete pattern matches on this expression." warning even if no custom comparison/equality defined on `someValue`'s type

**Comment by PatrickMcDonald** [comment]
`let someValue = nan` will cause a `MatchFailureException`

**Comment by dsyme** [comment]
This is by design.  Even if there wasn't a specific case, F# doesn't analyze the completeness of "when" qualifiers
