### ISSUE TITLE
Visual F# Tools are not localized for: PLK,PTB,TRK

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#419]
The internal process is missing these languages.  I will need to fix it.

**Comment by enricosada** [comment]
no klingon? }}>:-(

![](http://i.giphy.com/i4KuBQLnxAuju.gif)

**Comment by KevinRansom** [comment]
We don't currently have a contract with any Klingon linguists to do this work.  But I will raise it, see if it can become an official VS language.

**Comment by veikkoeeva** [comment]
:)

**Comment by latkin** [comment]
@KevinRansom did this get fixed for 4.0? Or do we need to look at it for Update 1?

**Comment by KevinRansom** [comment]
Fixed.
