### ISSUE TITLE
Indavertent revert of #3203

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#4200]
Tracking comment https://github.com/Microsoft/visualfsharp/pull/3203#issuecomment-356688291 in case it gets lost:

> it seems this change was inadvertently reversed in f52362a. And indeed I am again experiencing the issue.

**Comment by dsyme** [comment]
cc @Tarmil

**Comment by dsyme** [comment]
@Tarmil Could you resubmit your fix please (revert the revert :) )

**Comment by Tarmil** [comment]
I did it as #4202.

**Comment by dsyme** [comment]
Thanks, merged
