### ISSUE TITLE
Copy recursive record types

### ISSUE THREAD

**Issue by plainionist** [Microsoft/visualfsharp#4201]
Pls refer to the following stackoverflow thread:

https://stackoverflow.com/questions/47869011/copy-recursive-f-record-types

could this be a "compiler bug" or "missing feature"?

I have tried it in VisualStudio 2017 (15.3).

**Comment by cartermp** [comment]
I don't believe this is a compiler bug nor missing feature, as in your original code, you're attempting to use a value which may not be initialized. And indeed at runtime, it is not. Conversely, if you move the `children` definition above the `parent`, then every value needed to construct a `parent` has been initialized.

```fsharp
// Compiles and runs just fine
let create name kids =
    let rec makeChild kid = { kid with Parent = parent |> Some }
    and adult = createAdult name 42
    and children = kids |> List.map makeChild
    and parent = 
        { adult with Children = children }
    parent

// Fails at runtime
let createBad name kids =
    let rec makeChild kid = { kid with Parent = parent |> Some }
    and adult = createAdult name 42
    and parent = 
        { adult with Children = children } // Warning on 'children'
    and children = kids |> List.map makeChild
    parent
```

That said, I think you can generally make things easier on yourself by not using recursively-defined values.  Something along the lines of this (untested)

```fsharp
let makeChild parent kid = { kid with Parent = parent |> Some }

let create name kids =
    let adult = createAdult name 42
    let children = kids |> List.map (makeChild adult)
 
   { adult with Children = children }
```

Is cleaner overall. But in general, what you're attempting to accomplish must necessarily be a three-step process, where you initialize one, initialize the other, then update references to values. Either that, or simple have a one-way reference relationship (e.g., Parent has children, or children has parent, but not both).

**Comment by plainionist** [comment]
sometimes one cannot see the forest for the trees :(
I published the repro here https://github.com/plainionist/DevNull/tree/master/src/FSharpCopyRecordRecursive

and of course it works like a charm

thx a lot!!

**Comment by plainionist** [comment]
we have overlooked one aspect :( 
the proposed solution does NOT work. The last line here

```F#
let makeChild parent kid = { kid with Parent = parent |> Some }

let create name kids =
    let adult = createAdult name 42
    let children = kids |> List.map (makeChild adult)
 
   { adult with Children = children }
```
returns a new instance of a parent which has children correctly updated BUT the children do NOT reference this new instance of the parent. Hence the bidirectional reference is broken and the copy is not complete.

Pls refer to the repro: https://github.com/plainionist/DevNull/blob/master/src/FSharpCopyRecordRecursive/Program.fs

Only option I could found is to manually "copy" the records with recursive definitions.

Did I overlook s.th. else or is recursive "with" really not supported?

**Comment by plainionist** [comment]
@dsyme : can u pls reopen the issue in case my last comment is correct? thx

**Comment by dsyme** [comment]
@plainionist Bi-directional update is not supported, you'll need to use a mutable data structure to get this effect, patching the parent after copy

**Comment by plainionist** [comment]
@dsyme: thx for ur answer.
I have improved my repro: https://github.com/plainionist/DevNull/blob/master/src/FSharpCopyRecordRecursive/Program.fs

meanwhile I have two working approaches (without mutable - I don't want to have mutable types in my domain model)

1. manual copy: recursive let with manually creating new record and manually copy each member one by one

2. use "with" key word to copy the structures only uni-directional and then use one generic manual deep copy function to "fix" the backward links

``
