### ISSUE TITLE
SQM Debug assert when running ide tests

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#421]
I always get this debug assert dialog

![image](https://cloud.githubusercontent.com/assets/147243/7494486/2fb6305c-f408-11e4-8fe9-2cd79f94e543.png)

when running test from visual studio test explorer, it's ok? 
It is rather annoying

**Comment by latkin** [comment]
Yeah that's really annoying, it should be fixed.

I think should be simple conditional compile [here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/vsintegration/src/vs/FsPkgs/FSharp.Project/Common.Source.CSharp/Project/ProjectNode.cs#L3568-L3575), i.e.
```csharp
#if !OPEN_BUILD
 // ... do SQM stuff ...
#endif
```
Looks like `OPEN_BUILD` definition will need to be added to `src/FSharpSource.Setting.targets`, too.

**Comment by latkin** [comment]
Ping for anyone looking for up-for-grabs

**Comment by raymens** [comment]
I'm interested.

Is there any condition you'd like in the definition for adding it to the `src/FSharpSource.Setting.targets` file? As there doesn't seem to be one in `src/FSharpSource.targets`.
