### ISSUE TITLE
AccessViolationException with seq { } when using yield! with multiple collected sequences (Release)

### ISSUE THREAD

**Issue by Julien-Pires** [Microsoft/visualfsharp#4220]
Following method throws an AccessViolationException. The problem occurrs only in release mode, if you run this method in debug everything works fine. The exception is thrown while enumerating the `seq { }`.

```F#
let getBaseType (node : TypeBlockSyntax) =
        let types = seq {
            yield! node.Implements |> Seq.collect (fun c -> c.Types)
            yield! node.Inherits |> Seq.collect (fun c -> c.Types) }
        types
        |> Seq.map (fun c -> c.ToString())
        |> Seq.toList
```

#### Repro steps

1. Switch to `Release`
2. Open the TestExplorer
3. Debug the method `Analyze should return base types when type has some`

You can find the source here: https://github.com/Julien-Pires/Markify. 

The method getBaseType can be found in Markify.Services.Roslyn.VisualBasic > DefinitionFactory.fs > StructureDefinitionFactory.

#### Expected behavior

Seq enumeration works without exception.

#### Known workarounds

I've found multiple workarounds to the problem:

- Enumerate the result of `Seq.collect` before` yield!`

```F#
let types = seq {
   yield! node.Implements |> Seq.collect (fun c -> c.Types) |> Seq.toList
   yield! node.Inherits |> Seq.collect (fun c -> c.Types) |> Seq.toList }
```

- Not use ` seq { }`

```F#
let types =
    Seq.append (node.Implements |> Seq.collect (fun c -> c.Types)) (node.Inherits |> Seq.collect (fun c -> c.Types))
```

- Compile in debug

#### Related information 

* Windows 10
* Visual Studio 2017
* F# Runtime 4.4.1.0
* .NET Runtime 4.7

**Comment by dsyme** [comment]
@Julien-Pires Could you try to trim down the problem to a minimal repro please, per CONTRIBUTING.md?  It makes it much easier for us to investigate and fix, thanks

**Comment by Julien-Pires** [comment]
Sorry for not providing a more simple project for repro. I've created a simple example that you will find attached. You must compile and execute in release, I can reproduce all the times.

[SeqAccessViolation.zip](https://github.com/Microsoft/visualfsharp/files/1731661/SeqAccessViolation.zip)

**Comment by dsyme** [comment]
This stems from the fact that `SeparatedSyntaxList` in the repro is a value type implementing collection semantics, https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Syntax/SeparatedSyntaxList.cs#L13
