### ISSUE TITLE
Improve warning for ignored values in sequence expressions

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#4228]
// stupid things to make the sample compile
    let div _ _ = 1  
    let subView _ _ = [1; 2]

    // elmish view
    let view model dispatch =
       [
           yield! subView model dispatch
           div [] [] // <- warning
           div [] [] // <- warning
       ]

This code gives famous the famous "The result of this expression is implicitly ignored" message and suggests to bind to a let binding. This is wrong advice and not helpful for newcomers in elmish apps. 

Instead we should improve the warning when we are inside of list comprehsions to something more useful.

**Comment by isaacabraham** [comment]
Because they should have yielded out the result?

**Comment by isaacabraham** [comment]
Maybe rename this to something less about elmish and more about yields in list comprehensions etc.?

**Comment by forki** [comment]
,yes they should yield.
And no this is something that especially is seen in elmish view code. I
think it's good to keep that reference and to think about it in that case

Am 20.01.2018 12:18 schrieb "Isaac Abraham" <notifications@github.com>:

Maybe rename this to something less about elmish and more about yields in
list comprehensions etc.?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/visualfsharp/issues/4228#issuecomment-359164111>,
or mute the thread

**Comment by isaacabraham** [comment]
But it has more applications than simply elmish. People use list comprehensions elsewhere, too.

**Comment by forki** [comment]
Another aspect here is that we often see people go over from a simple list with couple of react elements to something with an if or match. Then they need to use yield and now the whole list is basically this case here

**Comment by forki** [comment]
another common case:

    let view model dispatch =
       [
           let x = true
           if x then
               div [] [] <- warning
           else
               div [] [] <- warning
       ]



interestingly the following doesn't compile:

    let view model dispatch =
       [
           if true then
               div [] []
           else
               div [] []
       ]

**Comment by forki** [comment]
yet another important case:


    let view model dispatch =
       [   
            div [] [
               match y with
               | 1 -> yield! subView model dispatch
               | _ -> subView model dispatch // <- warning
            ]
       ]

**Comment by forki** [comment]
see https://github.com/Microsoft/visualfsharp/pull/4245
