### ISSUE TITLE
Type inference knows less than intellisense

### ISSUE THREAD

**Issue by rojepp** [Microsoft/visualfsharp#424]
![inference3](https://cloud.githubusercontent.com/assets/445888/7510535/570d5320-f49d-11e4-97b0-b273173ebcec.gif)

Following a discussion on (twitter)[https://twitter.com/Cynede/status/596212402129149952]. Why is it that type inference won't resolve the type in the screen cap above but completion knows the type? Is this a bug?

**Comment by enricosada** [comment]
from the awesome [fsharpforfunandprofit troubleshooting](http://fsharpforfunandprofit.com/troubleshooting-fsharp/)

> The reason is that the F# compiler is currently a one-pass compiler, and so type information present later in the program cannot be used if it hasn't been parsed yet

### FS0072: Lookup on object of indeterminate type
> In some cases though, judicious rearrangement of the code can help. For example, the example below looks like it should work. It's obvious to a human that the List.map function is being applied to a list of strings, so why does x.Length cause an error?

```fsharp
List.map (fun x -> x.Length) ["hello"; "world"] // Error FS0072      
```

> The reason is that the F# compiler is currently a one-pass compiler, and so type information present later in the program cannot be used if it hasn't been parsed yet.
Yes, you can always explicitly annotate:

```fsharp
List.map (fun x:string -> x.Length) ["hello"; "world"] // OK
```

>But another, more elegant way that will often fix the problem is to rearrange things so the known types come first, and the compiler can digest them before it moves to the next clause.

```fsharp
["hello"; "world"] |> List.map (fun x -> x.Length)   // OK
```

>It's good practice to avoid explicit type annotations, so this approach is best, if it is feasible.

**Comment by rojepp** [comment]
Thanks @enricosada. I know about all this. The question was specifically since completion knows the type of a, then the compiler should be able to know it too? If it did, there would probably a lot less moving code around to satisfy type inference.

**Comment by enricosada** [comment]
ah, sry @rojepp didnt understood the issue, my bad

**Comment by TeaDrivenDev** [comment]
I'm seeing a case of that here even when piping in the input sequence.

**Comment by pezipink** [comment]
Note - this is not new, it has been around since I can remember and appears in various forms.

**Comment by Heather** [comment]
As I wrote in twitter you just should use your pipes... I don't think it's a bug since it was provided as is

``` fsharp
let xs = ["a"; "b"]
let ms = Seq.map (fun x -> x.ToLower()) xs
let ms = Seq.map (fun x -> x + x) xs
```

First method will not compile, second method feels very unsafe because it will be really solved very later, it works for some basic operations common for most of types... What I wonted to point on original post is not much related this behaviour but mostly about community love to pipe operator

> Working in a language without the |> operator feels so… Archaic.  Ugly.   Painful. Temporary variables? 
( 8 RTs 10 Likes)

**Comment by rojepp** [comment]
It's not new, and possibly not a bug. That completion knows what the type is indicates it may be regarded as a bug. Regardless, it would be awesome if type inference could cover this scenario.

**Comment by Heather** [comment]
@rojepp agreed, as more F# is Haskell, as better it is!

**Comment by dsyme** [comment]
This would currently be regarded as a usability "glitch" - though I agree it trips people up.

Basically, the VF# Tools language service (and FSharp.Compiler.Service too) produces tooltips and completions based on the overall inferred types (from the whole file) rather than the partially inferred types (left-to-right up to the point of completion).  This is OK for tooltips (you really want to see as much inferred information as possible) but not really right for completions.

Since this is long-term known behaviour, I suppose the right place to track this is as a user voice request for the Visual F# Tools (though equally I think it's good to have discussions like this here from time to time to raise the visibility of the issues)

**Comment by rojepp** [comment]
[Done](http://fslang.uservoice.com/forums/245727-f-language/suggestions/7866168-improve-type-inference).

**Comment by dsyme** [comment]
Cool, closing this out here then

**Comment by Heather** [comment]
@rojepp thank yo for pushing it
@dsyme for me personally this + letrec will improve look&feel a lot...

**Comment by latkin** [comment]
Hooray, for once the F# IDE is doing too much :tada:

**Comment by fsoikin** [comment]
@Heather, can you please elaborate on "letrec" for me? F# does already have "let rec" (as in, `let rec f x = f (x+1)`), and it does exactly what Scheme's letrec does, which is the only other letrec I was able to find. 

Did you mean something else?

**Comment by Heather** [comment]
@fsoikin haskell `let` for example, http://docs.racket-lang.org/reference/let.html

**Comment by fsoikin** [comment]
@Heather, that link was for Racket, not Haskell. Racket's `letrec` is generally same as Scheme's, which, as I mentioned before, F# does have in the form of `let rec ... and ... and ...`.

Racket (example from the linked page):
```
(letrec ([is-even? (lambda (n)
                       (or (zero? n)
                           (is-odd? (sub1 n))))]
           [is-odd? (lambda (n)
                      (and (not (zero? n))
                           (is-even? (sub1 n))))])
```

F#:
```
let rec isEven x = x = 0 || isOdd (x-1)
and isOdd x = x <> 0 && isEven (x-1)
```

Or am I missing something?

**Comment by Heather** [comment]
@fsoikin Haskell `let` is formally `letrec`, e.g. works as like `letrec` in scheme
``` haskell
let a = b + 1
    b = 1
in show a
```

btw `let` `in` syntax in F# is also broken

**Comment by fsoikin** [comment]
Yes, F# syntax does exactly the same, only you have to add `rec` and `and` between definitions:

```
let rec a = b + 1
and b = 1
in printfn "%d" a
```

What's broken about it?

**Comment by Heather** [comment]
@forki there are two things, first is that this code makes no sense, e.g. this `in` is meaningless, and I personally dislike `and` splitter

**Comment by fsoikin** [comment]
So your issue is not that a feature is absent, but that you dislike the particular syntax that the feature has? 

And consequently, your request would be not to add a new feature, but to change syntax of an existing one?

**Comment by Heather** [comment]
@fsoikin I don't want to change actual syntax, there was request about it on uservoice but I can't find it for now. At least `in` part could be dropped or variables inside `in` block should not be visible from outside it.
