### ISSUE TITLE
Consider to remove all localized error messages

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#4243]
This is not intended as trolling. Seriously.

We should revisit the idea to have localized compiler error messages. At least in german case they are usually not very helpful.

* You can't google with localized errors
* You can't ask on stackoverflow with localized errors
* The message are really really hard to understand since established english terms like "assembly binding redirect" are translated as well to something noone has ever heard of.
* Contributors have now much more pain to maintain all these languages, when they actually just want to patch the english message.

I know MS employees /VF# team might see this differently - but they don't have to use the localized versions and don't see the pain.

**Comment by auduchinok** [comment]
The problem is not in F# compiler/FCS only, I was never able to (quickly/easily) understand what were localized .NET exceptions about and have even forgotten how bad it was after switching to English as an OS language.
I'd be happy if all .NET tooling used English language only so it'd be possible to get help online.

**Comment by cartermp** [comment]
This is about compliance with accessibility requirements. The recent switch to bring the localized files to the repo was done for three reasons:

* Allow someone to patch one of these strings when they previously had no ability to do so
* Significantly reduce our build times (4 hrs -> 90 mins) and allow us to remove the copy of this repo that we had to maintain in VSTS, thus making it far easier for us to get something critical into VS in a short time span
* Be available for a pilot program run by Bing to offer better machine translation on OSS assets.

Until our policy for accessibility changes and does not mandate localized resources, we won't be changing anything.

**Comment by forki** [comment]
Yeah. I feared that. For english speaking people "accessibility" means
machine assisted translation into foreign languages.

Ok. Thanks anyway. At least I tried to raise some awareness.

Am 23.01.2018 17:15 schrieb "Phillip Carter" <notifications@github.com>:

**Comment by KevinRansom** [comment]
@ forki
The option you need is already in the product:

use:   fsc --preferreduilang:us-EN

in projects add <OtherFlags>$(OtherFlags);--preferreduilang:us-EN</OtherFlags>

There is a bug, it doesn't seem to set it for FSI, and that needs to be fixed.

````
fsc.exe" --preferreduilang:de-DE
Microsoft (R) F# Compiler version 10.1.0 for F# 4.1
Copyright (c) Microsoft Corporation. Alle Rechte vorbehalten.

error FS0207: Keine Eingaben angegeben.

fsc.exe" --preferreduilang:us-EN
Microsoft (R) F# Compiler version 10.1.0 for F# 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

error FS0207: No inputs specified

````

Kevin

**Comment by forki** [comment]
Thanks! Does this work for fsi and FCS as well? If so we can close it and defer to downstream.

**Comment by cartermp** [comment]
It looks like this isn't listed as an option in the [F# Compiler Options](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/compiler-options) docs page. I created an issue for that here: https://github.com/dotnet/docs/issues/4183

I'll probably add it to the table by the end of the day unless someone gets to it first
