### ISSUE TITLE
FSI does not respect target runtime of a project.

### ISSUE THREAD

**Issue by toburger** [Microsoft/visualfsharp#425]
Wouldn't it be advisable if FSI respects the configuration of the target F# runtime, if a script file is defined inside an F# project?
![](http://i.imgur.com/Zk2Wj5K.png)
The editor gives a warning about a deprecated construct in F# 4.0 and allows to define and run new F# 4.0 methods.
![](http://i.imgur.com/ci8kaTW.png)

My concern is, that legacy projects are used often in teams with mixed versions of Visual Studio. When trying to run a script with F# 4.0 exclusive features in VS 2013 it gives an error, because F# 4.0 isn't available.

I'm not sure if it could cause at worst a different runtime behaviour of my code between running/testing in interactive (4.0) and running the compiled code (3.1)?

**Comment by latkin** [comment]
There are certainly lots of knobs like this that would be useful for developers to control.  For now, though, the design of F# Interactive in VS is pretty simple doesn't allow for anything like this.  You can add a feature request at [UserVoice](http://visualstudio.uservoice.com/forums/121579-visual-studio/category/30935-languages-f-tools).

F# Interactive persists for the life of the VS process, there is no per-project or per-solution configurability. The backing fsi.exe process naturally loads up a single .NET version and a single FSharp.Core version, there is no way to switch at runtime.  Each version of VS uses the latest fsi from the newest F# language version.

**Comment by latkin** [comment]
Some related ideas that have been tossed around (each has drawbacks and complications):
- Allow multiple F# interactive windows
- Allow for the backing fsi.exe process to be specified by the user (e.g. specify path to older 3.1 fsi, or to your own custom-built one, etc)
- Support syncing of other project properties with F# Interactive (e.g. #defines, compile flags, etc)
