### ISSUE TITLE
Master is red

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#4256]
01:20:07   D:\j\w\debug_windows_nta76b1b03\src\fsharp\service\service.fs(994,89): error FS0039: The field, constructor or member 'EnclosingType' is not defined. [D:\j\w\debug_windows_nta76b1b03\src\fsharp\FSharp.Compiler.Private\FSharp.Compiler.Private.fsproj]
01:20:07 

/cc @KevinRansom

**Comment by nosami** [comment]
Strange. The PR wasn't red.

**Comment by auduchinok** [comment]
The `EnclosingType` change was introduced in an earlier PR https://github.com/Microsoft/visualfsharp/pull/4034 it could be if the last PR wasn't rebased before merging.

**Comment by forki** [comment]
If you merge 2 green PRs there is still a chance they conflict without
merge errors.

Am 24.01.2018 13:28 schrieb "Eugene Auduchinok" <notifications@github.com>:

**Comment by nosami** [comment]
@auduchinok, @forki  OK. Thanks - willl fix

**Comment by auduchinok** [comment]
@forki Yeah, that's exactly what I was talking about.
