### ISSUE TITLE
F# compiler should emit 'final' flag for implemented interface methods for consistency with C#

### ISSUE THREAD

**Issue by axel-habermaier** [Microsoft/visualfsharp#426]
This is a minor issue affecting both VS2013 and VS2015. Consider the following code:

```F#
namespace NN

type I =
    abstract member Q : unit -> unit

type X () =
    interface I with
        member this.Q () = ()
```

Interface implementations in F# are like explicit interface implementations in C# - except that the F# compiler emits slightly different code for the example above than the C# compiler would. In particular, ``X.Q`` is emitted as

```IL
.method private hidebysig newslot virtual // C# would also emit the 'final' flag here
		instance void 'NN-I-Q' () cil managed 
	{
		.override method instance void NN.I::Q()
		// Method begins at RVA 0x205c
		// Code size 2 (0x2)
		.maxstack 8

		IL_0000: nop
		IL_0001: ret
	} // end of method X::'NN-I-Q'
```

Note how the F# compiler -- in contrast to what the C# compiler would have done -- does not mark the method as ``final``. Now, since the method is ``private``, there shouldn't be any noticeable difference. However, this minor discrepancy might confuse some tools.

In particular, I stumbled across this issue while trying to create a class derived from ``X`` in C#. Resharper offers me to override ``NN-I-Q`` using its [Alt+Insert -> Overriding members] feature (the code it goes on to generate is invalid, of course). Clearly, this is a Resharper bug, but it's not happening with explicit interface implementations implemented in C#. So this example shows how C#-centric tools might be affected by the F# compiler not adhering to the patterns used by the C# compiler.

I realize this issue is not very important, but since there are no backwards compatibility considerations and the fix should be relatively simple, I hope that you consider fixing this issue anyway.

**Comment by dsyme** [comment]
This seems a reasonable thing to address

**Comment by latkin** [comment]
Is there a bug filed with ReSharper on this?

After chat with Roslyn devs, consensus was that current F# behavior is 100% correct, and outside of "documentation" purposes, adding `final` provides only theoretical benefit.  Explicit interface implementations can't be overridden anyways, and interface methods must always be invoked with `callvirt` instruction, so there is no practical optimization to be performed.

So a change here would be solely for the sake of consistency with C#, and compatibility with whatever tools rely on those patterns (which is fine, just wanted to provide more context).

**Comment by dsyme** [comment]
I'm going to close this as won't fix.  Adjusting the flags carries risk, and as @latkin mentions the F# behavior is correct.  A bug should be filed with ReSharper.
