### ISSUE TITLE
Odd random vertical line in Visual Studio

### ISSUE THREAD

**Issue by wanton7** [Microsoft/visualfsharp#4266]
While using F# in visual studio odd dotted vertical line appears.

#### Repro steps

Only happens when scrolling down. If i go to bottom of text in screen and use arrow down key then it sometimes appears. Always in same scroll positions and doesn't happen when scrolling to up.

#### Expected behavior

No vertical line like this

#### Actual behavior

Odd vertical line

#### Known workarounds

No workarounds

#### Related information 

* Operating system
Windows 10 (64bit)
* .NET Runtime, CoreCLR or Mono Version
CoreClr 2.1.4
* Editing Tools (e.g. Visual Studio Version)
Visual Studio 2017 15.5.4
* Indications of severity
Not severe

![oddline](https://user-images.githubusercontent.com/1009930/35390671-e6c1a69a-01e4-11e8-9c53-f67b16dc99b6.png)
![oddline2](https://user-images.githubusercontent.com/1009930/35391221-b5aa59ce-01e6-11e8-94da-b4aca9b2f21d.png)![oddline3](https://user-images.githubusercontent.com/1009930/35391220-b573b77a-01e6-11e8-8ac0-3f90a8b7cd18.png)
![oddline4](https://user-images.githubusercontent.com/1009930/35391219-b555be50-01e6-11e8-9c29-48a990dc1354.png)
![oddline5](https://user-images.githubusercontent.com/1009930/35391218-b4f027e8-01e6-11e8-8535-29ea5eff24f4.png)

**Comment by cartermp** [comment]
I've noticed this as well. It's the Structured Guidelines feature (relevant: toggling it on/off with this PR: #4227).

There may be a bug in what we report to Roslyn (a range that spans the whole file), but there may also be a bug in how Roslyn chooses to show it because it only comes up when scrolling through large files for me as well.

@CyrusNajmabadi would you have an idea about what this could be?

**Comment by CyrusNajmabadi** [comment]
No clue.  We just report the spans you report to us to the editor.  I think Amadeus (not sure about alias) may know about the editor side of this.  If not, try @olegtk

**Comment by olegtk** [comment]
@gundermanc might know

**Comment by gundermanc** [comment]
Hi all, is there a repro file?

**Comment by cartermp** [comment]
Ooof, this is where it gets tricky. In VF#, I've noticed it `service.fs` when scrolling around ... but I do not recall a specific area. @wanton7 is your example shareable?

**Comment by wanton7** [comment]
@cartermp I can share a file where it happens to me if you scroll down with arrow key at end of configFiles list.
[Program.zip](https://github.com/Microsoft/visualfsharp/files/1665494/Program.zip)

**Comment by gundermanc** [comment]
Hi all, it looks like this is an editor issue where the layout changed event is invalidating spans of text in text view lines that are not visible.

In the structure guides rendering code, if we fail to find a text view line corresponding to the start or end point of the adornment span, we assume the point should be on the start or end line respectively.

In some cases when scrolling down, it's possible for the structure tag in question to be off the bottom of the screen, but still within the invalidated span of text such that the adornment is included in the drawn set of adornments, but both the start and end lines fail to resolve, so we choose the top and bottom lines for the start and end points, and end up with a top to bottom adornment.

I think I have a trivial fix. Do we know which milestone we're targeting yet?

**Comment by gundermanc** [comment]
Ported to DEVDIV WIT: https://devdiv.visualstudio.com/DevDiv/_workitems?id=557472

**Comment by cartermp** [comment]
@gundermanc Thanks for looking into this! Since 15.6 is in escrow and this isn't a critical issue, I think 15.7 is a good target.

**Comment by gundermanc** [comment]
Proposed fix: https://devdiv.visualstudio.com/DevDiv/Editor/_git/VS-Platform/pullrequest/103484

**Comment by gundermanc** [comment]
Alright, the Editor fix is in for Visual Studio 15.7 and I have resolved the DEVDIV issue 103484 to @cartermp for final validation.

Thanks for reporting this!

**Comment by cartermp** [comment]
Thanks a bunch @gundermanc! I'll close this out here and validate the fix on a 15.7 build.
