### ISSUE TITLE
TargetFrameworks no intellisense

### ISSUE THREAD

**Issue by noelmcgrath** [Microsoft/visualfsharp#4267]
No intellisense in Visual Studio 2017 15.5.4

#### Repro steps

Create f# console app(.net core)
Open fsproj
Change `<TargetFramework>net47</TargetFramework>` to `<TargetFrameworks>net47</TargetFrameworks>`
Note the s
Save file
Go the Program.fs
Type array.

#### Expected behavior

Intellisense would work and would get .map etc

#### Actual behavior
No Intellisense 

#### Known workarounds
n\a

**Comment by auduchinok** [comment]
Duplicate of https://github.com/Microsoft/visualfsharp/issues/4084?

**Comment by cartermp** [comment]
Yep, a duplicate.
