### ISSUE TITLE
Rename doesn't rename referenced function in Visual Studio

### ISSUE THREAD

**Issue by wanton7** [Microsoft/visualfsharp#4276]
Rename doesn't rename referenced function in Visual Studio

#### Repro steps

```fsharp
module DataAccess

module Sql =
    open System

    let rec private containsClause (value : string) (str : string)  =
        let checkLeft idx =
            idx < 0 || Char.IsWhiteSpace(str.[idx]) || str.[idx] = ';' || str.[idx] = '/'
        let checkRight idx =
            idx = str.Length || Char.IsWhiteSpace(str.[idx]) || str.[idx] = '/'
        let rec impl idx value (str : string) =
            match str.IndexOf(value, idx, StringComparison.OrdinalIgnoreCase) with
            | idx when idx < 0 ->
                Ok str
            | idx when checkLeft (idx - 1) && checkRight (idx + value.Length) ->
                Error ("SQL query script contains illegal clause " + value)
            | idx -> impl (idx + value.Length) value str
        
        impl 0 value str

    let private validateClauses keywords (sql : string) =
        keywords |> Seq.fold (fun s k -> s |> Result.bind (containsClause k)) (Ok sql)

    let validateQuery =
        validateClauses ["UPDATE";"DELETE";"MERGE";"INSERT";"CREATE";"ALTER";"DROP"]

let foo = Sql.validateQuery "foobar"
```

Copy & paste code and try to rename validateQuery in foo with F2.

#### Expected behavior

validateQuery in Sql module should get renamed

#### Actual behavior

Renaming doesn't work

#### Known workarounds

Jump to actual function with F12 and rename it there

#### Related information 

* Operating system
Windows 10 (64bit)
* .NET Runtime, CoreCLR or Mono Version
CoreCLR 2.1.4
* Editing Tools (e.g. Visual Studio Version)
Visual Studio 2017 15.5.4
* Indications of severity
Not severe

**Comment by cartermp** [comment]
@wanton7 So this is weird. The text buffer seen in VS is **VERY** slow to update, but the rename actually does commit:

![rename-buffer-slow](https://user-images.githubusercontent.com/6309070/35537279-83bc6c70-04fe-11e8-9f31-d70435dc6df5.gif)

This is with 15.6 Preview 3.

@Pilchie any idea why it's so slow?

**Comment by cartermp** [comment]
@wanton7 with Preview 4 I can still confirm that renameworks. I'll close this out for now, but please do re-open if you see it again.
