### ISSUE TITLE
Where's the FSharp.Core changelog?

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#4278]
This may be a stupid question, but I can't find any updated changelog for the FSharp.Core nuget package. I noticed 4.3 is out and was wondering what's new from 4.2 in order to determine whether to upgrade.

**Comment by cmeeren** [comment]
Haha, just googled my own issue now that 4.5 has been released. Is there seriously no FSharp.Core changelog?

**Comment by abelbraaksma** [comment]
I miss it too. Sometimes things get mentioned in VS updates 'what's changed' pages, but often that list is incomplete at best. Also, changes in compiler are hard to find, but they are there. I recently stumbled on a change in SRTP which allowed class names in the restriction. It's not mentioned anywhere (except that it's been added to the docs).

I would certainly welcome a change log on the compiler, language service and Core lib.

**Comment by cartermp** [comment]
Sorry, I hadn't seen this issue.

Changelogs are [captured as RFCs](https://github.com/fsharp/fslang-design). When there is a new release, relevant RFCs are merged and organized appropriately.

Though bug fixes are not. We can consider a bugfix-level changelog. @KevinRansom / @dsyme / @TIHan / @brettfo ?

**Comment by abelbraaksma** [comment]
@cartermp, Since many small new features are implemented as bugfixes rather than through the RFC process, that seems reasonable. And it's _especially_ bugfixes that I would be interested in, a place to look if your favorite (read that as: production blocking) bug is (partially) resolved would be of tremendous help. Even an incomplete list would already be beneficial, I think.

I've sometimes went over existing bugs, following the relevant PR's, trying to find out which made it into which VS version or RTM version of FSharp.Core or the language services, but that is an arduous task and often leads to a dead end.

Visual studio does something like this: in the "What's new" it lists the relevant user-reported bugs that were addressed in a given release. Perhaps we could collect our list there too?

**Comment by cartermp** [comment]
@abelbraaksma Could you give an example of this?

> Since many small new features are implemented as bugfixes rather than through the RFC process, that seems reasonable

I'm not aware of smaller new features being added alongside bug fixes. New features are captured via an RFC, and behavioral changes have been captured in the Visual Studio release notes. I think it's worth putting those behavioral changes in a changelog as well, but it's not clear where that changelog ought to live, either. My guess is somewhere under the **fsharp** org on GitHub.

**Comment by dsyme** [comment]
> Since many small new features are implemented as bugfixes rather than through the RFC process

All design-changes should be in an RFC, lete us know if that's not the case

**Comment by cartermp** [comment]
@abelbraaksma None of these are FSharp.Core changes. One is a tooling change (which are captured in VS release notes), one is a compiler error change (also captured there), and the other is also a tooling change _proposal_ (and one that we won't be taking any time soon).

This issue is for FSharp.Core. I see value in there being a changelog for this, but the question is where that changelog lies.

**Comment by cmeeren** [comment]
> Changelogs are [captured as RFCs](https://github.com/fsharp/fslang-design). When there is a new release, relevant RFCs are merged and organized appropriately.

Most of the "F# 4.5 candidate RFCs" are just marked as "approved in principle", so that list does not seem to me to be actively maintained (even apart from the fact that they're listed as "candidates"). I suppose someone goes through them after the fact and edits the RFCs to reflect what has actually been implemented, and how it actually turned out?

In any case, to be frank, when a new F# version comes out, I don't really want to dig up and read through a bunch of design documents to find out what's changed. I just want a list of new features and how to use them (and a list of bug fixes). This can appear on the .NET blog for all I care, or another post on an MS-owned domain. (By all means though, do link to the RFCs from the changelog if they contain useful information.)

C# manages to communicate new features very clearly. I think an F# changelog could help push F# adoption - it would be one less thing implying that F# is the "lesser child".

(Thanks for the great work on the language, though! 😁👍  I'd just like to know what it was.)

**Comment by cartermp** [comment]
@cmeeren Every RFC that is implemented is in a folder that corresponds to a version. You can see everything going into F# 4.5 in the FSharp-4.5 and FSharp.Core-4.5.0.0 folders. Unreleased features and/or in-progress features are in the RFCs folder.

We also do capture release notes for all changes to the language and FSharp.Core in the Visual Studio release notes. For example: https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#fsharp

Each of the changes that make their way into the binary/package for FSharp.Core are documented in these release notes when they are shipped.

I think the question is if we should publish changes to FSharp.Core separately from what we already do. And perhaps the same to the language and/or compiler.

**Comment by cmeeren** [comment]
> @cmeeren Every RFC that is implemented is in a folder that corresponds to a version. You can see everything going into F# 4.5 in the FSharp-4.5 and FSharp.Core-4.5.0.0 folders. Unreleased features and/or in-progress features are in the RFCs folder.

Ah, I see. I followed the link in the readme called "Open F# Language RFCs (including candidates for F# 4.5)". Thanks for the clarification.

**Comment by abelbraaksma** [comment]
@cartermp yes, I always read those release notes trying find out wether it's worthwhile to go through an update process for  all instances. Often the list is empty, even when clearly bug fixes made it through. However, I think that list, while helpful,  is often incomplete when it is available. I've had several discussions here only to find out that something was already implemented or was planned for version X. An example is the SRTP change mentioned nowhere. I know release management is difficult, and I wasn't aware of the folders. Perhaps we can link there from the Release Notes of VS?

**Comment by cmeeren** [comment]
> Perhaps we can link there from the Release Notes of VS?

I also suggest clearly linking there from the readme in this repo too, since this is where the "project page" link from the FSharp.Core points.

**Comment by cartermp** [comment]
I've gone through and applied milestones on issues where they were released back until 15.6. Not sure if I'll do so for 15.5 and before, but this should cover any relatively recent concerns.

**Comment by cartermp** [comment]
Closing this in favor of #5489
