### ISSUE TITLE
Error when using --debug:portable with fc.exe: 'System.Collections.Immutable, 1.2.0.0"

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#4287]
Running 

    fsc --debug:portable --optimize- a.fs

from a Visual Studio command prompt gives me this.  This is the product fsc.exe for .NET Framework.

![image](https://user-images.githubusercontent.com/7204669/35588379-7b93b0e6-05ce-11e8-9150-5f7a9f09dca1.png)

**Comment by dsyme** [comment]
C:\GitHub\dsyme\visualfsharp>where fsc.exe

C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\fsc.exe

**Comment by dsyme** [comment]
Visual Studio is up-to-date, but the fsc.exe.config installed on my machine looks very old and doesn't match what's in our repo:

![image](https://user-images.githubusercontent.com/7204669/35588528-ed9ab446-05ce-11e8-92d5-23212bf33f4d.png)

```
C:\GitHub\dsyme\visualfsharp>more "C:\Program Files (x86)\Microsoft SDKs\F#\4.1\
Framework\v4.0\fsc.exe.config"
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <legacyUnhandledExceptionPolicy enabled="true" />
    <gcServer enabled="true"/>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity
          name="FSharp.Core"
          publicKeyToken="b03f5f7f11d50a3a"
          culture="neutral"/>
        <bindingRedirect
          oldVersion="2.0.0.0-4.4.1.0"
          newVersion="4.4.1.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by dsyme** [comment]
If someone could check a fresh install of VS that would be useful.

@brettfo Could it be that installing update to VS isn't updating those config files?

**Comment by brettfo** [comment]
Clean install on my box shows the correct contents and the command in the original issue appeared to work.  That config file is placed via [this line](https://github.com/Microsoft/visualfsharp/blob/5d88640df70e27d5116f9c32fa10cce489a34836/setup/FSharp.SDK/component-groups/Compiler_Redist.wxs#L90) and looking at [the schema](http://wixtoolset.org/documentation/manual/v3/xsd/wix/file.html) for that file I don't see anything specific to file overwriting on install, which means I have no idea if that means the file is always overwritten or never.

Adding @KevinRansom to see if he has any ideas.

**Comment by dsyme** [comment]
@brettfo It's possible I manually clobbered this file on my machine, I don't know if that makes a difference or not

**Comment by 0x53A** [comment]
Wix (msi) only overwrites files based on versions or dates.

So if you modified (or overwrote) it manually, msi won't touch it anymore.

(ref http://www.syntevo.com/blog/?p=3508)

> ... Will be treated by MSI as user data and hence the creation and modification times define whether a file will be overwritten by an update: if the modification time is newer than the creation time, MSI will not overwrite the file when updating. 

I don't want to rant too much, so I won't provide my opinion on this, but the way I solved it for our setup was to add an explicit ``RemoveFile`` for everything:

```
                <Component Directory="APPLICATIONFOLDER" Permanent="no" MultiInstance="yes" Guid="29ddef58-c617-4b38-abf3-3c12fa07c372" Id="CWjasTAWsYcdUFuj7aJMS0OIMCB.i2em3xhB640jR61A">
                    <File Id="fileuG0U7a7rAladAh0.zPv9bJ7qQxS9vMpAh3Hz_YmvfLo" Name="SomeFile.dll" Source="SomeFile.dll" />
                    <RemoveFile Id='removeFileuG0U7a7rAladAh0.zPv9bJ7qQxS9vMpAh3Hz_YmvfLo' On='install' Name='SomeFile.dll'/>
                </Component>
```

**Comment by dsyme** [comment]
Ok, thanks, that's helpful to know. Our dev notes still contain instructions on how to clobber the F# netfx install on a machine, so other people might get hit by this. I presume a repair would fix things.

**Comment by 0x53A** [comment]
>  I presume a repair would fix things

I'm not sure, but I don't think so
