### ISSUE TITLE
Align with C# Span support  / Missing safety for stackallocated types

### ISSUE THREAD

**Issue by realvictorprm** [Microsoft/visualfsharp#4288]
F# currently lacks full support for stackallocated types like Span and other types found in the System.Memory package. C# already supports all safety features like disallowing the return of a span type.

----

This is meant to be a collection of what needs to be done and what's the plan of Microsoft so a future contributor or maybe even me could start implementing this compatibility feature. 

----

I won't discuss why we need this expect telling that we can only benefit from it.

PS: currently on mobile. Will link C# Span details later.

**Comment by realvictorprm** [comment]
@cartermp @dsyme Could we discuss the plan of Microsoft here in the compiler office hours?

**Comment by dsyme** [comment]
Yes, of course. Would be helpful if you could draft a RFC first, if possible.

**Comment by zpodlovics** [comment]
It seems that the CoreCLR/CoreFX team figured out how to represent byref<T> fields:

"ByReference<T> is meant to be used to represent "ref T" fields. It is working around lack of first class support for byref fields in C# and IL. The JIT and type loader has special handling for it that turns it into a thin wrapper around ref T." [1].

[1] https://github.com/dotnet/coreclr/blob/6c12105bb8cc1821ba5d5c3d36aad609a44308e0/src/mscorlib/src/System/ByReference.cs

The current Span implementation use ref struct and readonly ref struct types.

**Comment by dsyme** [comment]
Initial draft of support for `Span` is here: https://github.com/Microsoft/visualfsharp/pull/4888

This is based on 5 hours work. A fair bit more work is needed, but not vastly more.

**Comment by dsyme** [comment]
I will close this as it is covered by RFC https://github.com/fsharp/fslang-design/blob/master/RFCs/FS-1053-span.md
