### ISSUE TITLE
Visual Studio 2015 RC provides only F# 3.0 runtime

### ISSUE THREAD

**Issue by Matthias247** [Microsoft/visualfsharp#429]
If I open my F# project in VS2015RC it tells me it is using F# 3.0 runtime in the project properties:
![](http://abload.de/img/fsharperrmuo6m.png)

I can't choose any other version that that (dropdown box contains only that single entry).  
The compiler call it makes for my project is

    C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\fsc.exe -g --debug:full --noframework --define:DEBUG --define:TRACE --optimize- --tailcalls- -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\FSharp.Core.dll" ...

So I guess it uses the F# 4 compiler but the F# 3 libraries?

It's the german version - if that matters.

In VS2013 community which I have installed in parallel the only choice for me is  "4.3.1.0", and the dropdown box is greyed out.

**Comment by forki** [comment]
Side issue: please fix the german translation. It's completely wrong. Should be runtime like in english.

**Comment by dsyme** [comment]
Could you share the contents of your .fsproj file?  Have you hand-edited it? thanks

**Comment by Matthias247** [comment]
Here it is: https://gist.github.com/Matthias247/616a1bea739f2b9915bf  
I have stripped the source file list since this is currently a closed project.

I haven't hand-editited the project files before. It was created with Visual Studio 2013 before (I think either premium or professional), and I have now loaded it with VS2015 Community

**Comment by latkin** [comment]
This is by design. Your project targets .NET 4.0, and 4.3.0.0 is the latest runtime that targets the same. It was a bug that 4.3.1.0 or 4.4.0.0 were previously shown, as they target .NET 4.5.

See #157.

**Comment by Matthias247** [comment]
Thanks @latkin, that explains it. When I select .NET 4.5 then I can choose between all 3 F# runtime versions, so it is correct. What's not correct is then the behavior on the VS2013 side, which shows `4.3.1.0` for all .NET framework versions.

**Comment by latkin** [comment]
Ok, this seems to be understood well enough.  Yes, it's a bug in VS 2013, though we likely won't go back and publish a patch.

**Comment by forki** [comment]
Could you please still look for the translation? "Ziellaufzeit" is not even a word.

**Comment by enricosada** [comment]
@forki ask @KevinRansom maybe you can help to review german translation. i am trying to do the same for italian

**Comment by forki** [comment]
Yep. I'd be open for that.
