### ISSUE TITLE
Nightly releases for 15.6 (Preview)

### ISSUE THREAD

**Issue by irium** [Microsoft/visualfsharp#4294]
Is there MyGet feed of nightly releases for VS 15.6 (currently preview)?

The only info here is https://dotnet.myget.org/feed/fsharp/package/vsix/VisualFSharp
which is for VS 15.4 (stable).

**Comment by BillHally** [comment]
Previews can be manually downloaded from:

https://dotnet.myget.org/feed/fsharp-preview/package/vsix/VisualFSharp

And the feed to add to Visual Studio is:

https://dotnet.myget.org/F/fsharp-preview/vsix

**Comment by cartermp** [comment]
Closing as @BillHally is correct here

**Comment by irium** [comment]
Thanks a lot! @cartermp it might be worth mentioning this in the " README.md?

**Comment by cartermp** [comment]
Added!
