### ISSUE TITLE
In anticipation of spring cleaning

### ISSUE THREAD

**Issue by ncave** [Microsoft/visualfsharp#4312]
Now that netstandard 2.0 has been out for a while, is there a plan or a timeline on when all the older projects in this repo (i.e. the ones with project.json, or older versions of VS) will be migrated?
Mainly with a goal to lower the bar on contributing, by not requiring so many different dotnet framework versions installed?

**Comment by cartermp** [comment]
Current projects with associated issues for this are here: https://github.com/Microsoft/visualfsharp/projects/1

The main issues are removing project.json from the build and removing the last of machine state dependencies by no longer requiring an MSBuild installation.

We're currently 100% booked up in getting the 15.6 release out the door with some critical changes coming in fast (multitargeting support, the long list of file ordering behaviors, ASP.NET Core templates wired up in VS, validating the large number of changes between 15.5 and 15.6).

Additionally, the remaining in-flight work for FSI and Type Providers on .NET Core will probably take precedence over OSS build improvements for now. @KevinRansom are there things here that OSS contributors could hack on if given some pointers?

**Comment by ncave** [comment]
@cartermp Thanks for the detailed outline.

**Comment by dsyme** [comment]
closing discussion
