### ISSUE TITLE
Missing Publish option for F# dotnet core console applications

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#4332]
In Visual Studio Professional 2017 Version 15.5.6 the “Publish” option is missing for F# dotnet core console applications.  The option is neither available from the projects context menu nor from Build menu,
The option is available for C# dotnet core console applications.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/195889/missing-publish-option-for-f-dotnet-core-console-a.html
VSTS ticketId: 564517_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by chuchu** [comment]
Here are two screenshots. The first one shows the context menu of a c# project and the second one is n f# project.

![publish](https://user-images.githubusercontent.com/521666/36085885-e5ba2fd0-0fc0-11e8-975e-5da712f1c1f7.jpg)

![nopublish](https://user-images.githubusercontent.com/521666/36085887-ea59f9da-0fc0-11e8-9394-dede8ac3d004.jpg)

**Comment by cartermp** [comment]
@TIHan @Pilchie Is the GUI gesture controlled in the project system?

**Comment by dsyme** [comment]
cc @davkean, @BillHiebert who might know about what enables these (based on the fact they are recent contributors to https://github.com/dotnet/project-system :) )

**Comment by TIHan** [comment]
I think we found where it was: http://vstfdevdiv:8080/DevDiv2/DevDiv/_versionControl?path=%24%2FDevDiv%2FOffcycle%2FWPT%2FWebToolsExtensions%2FMain/src/ManagedPublish/PublishProviders/Console/Provider/PublishProvider.cs

In WebToolsExtension. It should be as simple as adding "FSharp" string to the `AppliesTo`.

**Comment by davkean** [comment]
That capability string is a sign that we need to add a new capability for this...

**Comment by vijayrkn** [comment]
Currently Publish specifically checks for capability - (CSharp|VB)&CPS.  That is the reason it doesn't show up for fsharp projects.

Talked to @BillHiebert and we could enable Publish based on the presence of 'ManagedPublish' capability.

**Comment by davkean** [comment]
Don't combine capabilities; `Managed` and `Publish` already exist - so that would be `Managed & Publish` capability. However, `Managed` is overloaded because C++ uses it, let's come up with a new replacement for `Managed` (we need it for other reasons) and you can combine it with `Publish`.

**Comment by cartermp** [comment]
Tagging this as external until we get a bug filed in the appropriate place

**Comment by vijayrkn** [comment]
Sure, What ever capability name we decide we can add that.

**Comment by vijayrkn** [comment]
@cartermp - This would be a VS feature request.

**Comment by davkean** [comment]
Two bugs; 

- change the provider's capability string
- opt into said capability here: https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.Managed/ProjectSystem/DesignTimeTargets/Microsoft.Managed.DesignTime.targets#L70

**Comment by cartermp** [comment]
@davkean @vijayrkn where should these be filed under?

**Comment by davkean** [comment]
First against us on project-system, second aganst web in VSTS. We're discussing internally the naming of "Managed"  as we speak.

**Comment by cartermp** [comment]
Closing as this is external - bug files on project system and @TIHan is filing a bug against Web.

**Comment by chuchu** [comment]
Just a question, why is this related to Web? I thought this "publish" command is equivalent to the "dotnet publish" console command which "Packs the application and its dependencies into a folder for deployment to a hosting system."
This is independet from web or console or whatever. Isn't it?

**Comment by cartermp** [comment]
@chuchu VS tooling implementation is such that it is under the web tooling repository (which is internal and closed-source).

**Comment by chuchu** [comment]
@cartermp Ok, thanks for clarification.

**Comment by davkean** [comment]
We've decided internally to use ".NET" capability as a replacement of CSharpOrVisualBasicOrFSharp usage.
