### ISSUE TITLE
PInvoke fails when marshalling as UnmanagedType.LPUTF8Str

### ISSUE THREAD

**Issue by BillHally** [Microsoft/visualfsharp#4359]
## Description

.Net 4.7 and .Net Core 1.1 added the new value [LPUTF8Str](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedtype?view=netframework-4.7.1#System_Runtime_InteropServices_UnmanagedType_LPUTF8Str) to the type `System.Runtime.InteropServices.UnmanagedType`. However, when this value is passed to a `MarshalAs` attribute used in a DllImport statement and the code is compiled by `fsc`, the value is replaced by 0, which results in an exception being thrown at runtime when the imported function is used.

*Note: this issue doesn't affect code run by `fsi` - it only affects code compiled by `fsc`*

## Repro Steps

The following is a minimal repro:

1. Save the following code to a file named "Test.fs":
    ```fsharp
    module Test

    open System.Runtime.InteropServices

    [<DllImport("Kernel32")>]
    extern int lstrlen([<MarshalAs(UnmanagedType.LPUTF8Str)>]string s)

    [<EntryPoint>]
    let main __ =
        let s = "abc"
        printfn "%d" (lstrlen(s))
        0
    ```
2. Compile and run it:
    ```
    > fsc --platform:x86 Test.fs; ./Test.exe
    Microsoft (R) F# Compiler version 4.1
    Copyright (c) Microsoft Corporation. All Rights Reserved.

    Unhandled Exception: System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #1': Invalid managed/unmanaged type combination.
       at Test.lstrlen(String s)
       at Test.main(String[] __)
    ```

## Expected

The correct value of UnmanagedType is stored in the assembly, and it runs correctly.

## Actual

The value `0` is stored in the assembly, and it crashes when executed.

## Severity

It fails at runtime rather than compile time which isn't great. However, it's not hard to work around.

## Version

OS: Windows 10
fsc.exe: 2017.11.21.3 (FileVersion) 4.4.1.0 (ProductVersion)  
.Net Framework: 4.7.1
Visual Studio: 15.5.5

## Likely Cause

If `ilxgen.fs` doesn't recognise an `UnmanagedType` value, it defaults to [ILNativeType.Empty](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/IlxGen.fs#L4973).

## Workaround

It can be worked around by marshalling as byte arrays, and converting to/from UTF8 before/after marshalling as appropriate.

**Comment by dsyme** [comment]
Fixed by https://github.com/Microsoft/visualfsharp/pull/4360 - thanks for the contribution!
