### ISSUE TITLE
Compiler doesn't produce pdb files with DebugType=full and latest SDK

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#4364]
Consider an SDK-based project targeting net451 with full DebugType switch. After some recent update I found that no pdb file is produced when I compile the project. No relevant changes has been made to the project so I think it may be something to do with the compiler bundled in the SDK.

A part of the project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net451</TargetFramework>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    <RootNamespace>JetBrains.ReSharper.Plugins.FSharp.Common</RootNamespace>
    <AssemblyName>JetBrains.ReSharper.Plugins.FSharp.Common</AssemblyName>
    <DebugType>full</DebugType>
  </PropertyGroup>

<ItemGroup>
    <PackageReference Include="FSharp.Core" Version="4.1.18" />
    ...
  </ItemGroup>

... 
```

Rebuild log: https://gist.github.com/auduchinok/a3ff17dbb830d78d44eb28a24a36250d
`$ dotnet build` log: https://gist.github.com/auduchinok/3ec2ab25e65f8c34c4e4ac071b99e37e

**Comment by KevinRansom** [comment]
@auduchinok this is fixed here: https://github.com/Microsoft/visualfsharp/pull/4366

**Comment by auduchinok** [comment]
@KevinRansom Yeah, I've seen it. Thank you!
