### ISSUE TITLE
Unable to use git blame (annotate) in latest master + VS 15.6 Preview 5

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#4378]
![image](https://user-images.githubusercontent.com/6309070/36568263-2d64e10c-17de-11e8-875f-26b4a2c61e33.png)

**Note:** I had to upgrade my Git for Windows install separately due to [GitHub deprecating TLS v1 and v1.1](https://githubengineering.com/crypto-removal-notice/). I did not do so with VS, so it may possibly be related to that.

@jaredpar since you so kindly reminded us over mail to update git clients, think this might be related to that?

**Comment by jaredpar** [comment]
What VS are you on? I know that some updates were required to compensate for the GitHub changes.

**Comment by cartermp** [comment]
This was with Preview 5. Looks like it's fixed with Preview 6.
