### ISSUE TITLE
Exception thrown in Project.fs when debugging latest master in VS 15.6 Preview 5

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#4379]
![image](https://user-images.githubusercontent.com/6309070/36568208-f7e9cd4e-17dd-11e8-8b4a-8d7ea616797d.png)

[This code](https://github.com/Microsoft/visualfsharp/blame/master/vsintegration/src/FSharp.ProjectSystem.FSharp/Project.fs#L312) that throws the exception is 3+ years old. Is it relevant anymore? cc @enricosada  @dsyme

**Comment by dsyme** [comment]
@cartermp No it's not relevant any more (though check the options pages after you delete it...)

**Comment by dsyme** [comment]
@cartermp Though note I have no idea if the exception is really a problem or not - it's an MDA assistant - maybe it's just a warning

**Comment by cartermp** [comment]
Looks like debugging with that line removed causes VS.Shell.15 PDBs to not load

![image](https://user-images.githubusercontent.com/6309070/36569331-42dfd4c0-17e2-11e8-9f38-712e97c737b2.png)

**Comment by dsyme** [comment]
@cartermp What's the call stack?

**Comment by cartermp** [comment]
Closing as I havent seen this recently
