### ISSUE TITLE
Strange implementation for currying

### ISSUE THREAD

**Issue by ElemarJR** [Microsoft/visualfsharp#438]
Consider this code: 

````fsharp
module Heracles
 
type Point3(x: double, y: double, z: double) = 
    new(x: double, y: double) = Point3(x, y, 0.0)
    new() = Point3(0.0, 0.0, 0.0)
    member d.X = x
    member d.Y = y
    member d.Z = z
 
let distanceBetween (origin: Point3) (destiny: Point3) =
    let dx = origin.X - destiny.X
    let dy = origin.Y - destiny.Y
    let dz = origin.Z - destiny.Z
    sqrt(dx * dx + dy * dy + dz * dz)
 
type Point3 with
    member x.DistanceTo = distanceBetween x
````

Examining the CIL, I saw that compiler generated something like that:

````
.class public auto ansi abstract sealed Heracles
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 07 00 00 00 00 00
	)
	// Nested Types
	.class nested public auto ansi serializable Point3
		extends [mscorlib]System.Object
	{
		.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
			01 00 03 00 00 00 00 00
		)
		// Fields
		.field assembly float64 z
		.field assembly float64 y
		.field assembly float64 x

		// Methods
		.method public specialname rtspecialname 
			instance void .ctor (
				float64 x,
				float64 y,
				float64 z
			) cil managed 
		{
			// Method begins at RVA 0x2098
			// Code size 31 (0x1f)
			.maxstack 8

			IL_0000: ldarg.0
			IL_0001: callvirt instance void [mscorlib]System.Object::.ctor()
			IL_0006: ldarg.0
			IL_0007: pop
			IL_0008: nop
			IL_0009: ldarg.0
			IL_000a: ldarg.1
			IL_000b: stfld float64 Heracles/Point3::x
			IL_0010: ldarg.0
			IL_0011: ldarg.2
			IL_0012: stfld float64 Heracles/Point3::y
			IL_0017: ldarg.0
			IL_0018: ldarg.3
			IL_0019: stfld float64 Heracles/Point3::z
			IL_001e: ret
		} // end of method Point3::.ctor

		.method public specialname rtspecialname 
			instance void .ctor (
				float64 x,
				float64 y
			) cil managed 
		{
			// Method begins at RVA 0x20b8
			// Code size 19 (0x13)
			.maxstack 8

			IL_0000: nop
			IL_0001: ldarg.0
			IL_0002: ldarg.1
			IL_0003: ldarg.2
			IL_0004: ldc.r8 0.0
			IL_000d: callvirt instance void Heracles/Point3::.ctor(float64, float64, float64)
			IL_0012: ret
		} // end of method Point3::.ctor

		.method public specialname rtspecialname 
			instance void .ctor () cil managed 
		{
			// Method begins at RVA 0x20cc
			// Code size 35 (0x23)
			.maxstack 8

			IL_0000: nop
			IL_0001: ldarg.0
			IL_0002: ldc.r8 0.0
			IL_000b: ldc.r8 0.0
			IL_0014: ldc.r8 0.0
			IL_001d: callvirt instance void Heracles/Point3::.ctor(float64, float64, float64)
			IL_0022: ret
		} // end of method Point3::.ctor

		.method public hidebysig specialname 
			instance float64 get_X () cil managed 
		{
			// Method begins at RVA 0x20f0
			// Code size 8 (0x8)
			.maxstack 8

			IL_0000: nop
			IL_0001: ldarg.0
			IL_0002: ldfld float64 Heracles/Point3::x
			IL_0007: ret
		} // end of method Point3::get_X

		.method public hidebysig specialname 
			instance float64 get_Y () cil managed 
		{
			// Method begins at RVA 0x20fc
			// Code size 8 (0x8)
			.maxstack 8

			IL_0000: nop
			IL_0001: ldarg.0
			IL_0002: ldfld float64 Heracles/Point3::y
			IL_0007: ret
		} // end of method Point3::get_Y

		.method public hidebysig specialname 
			instance float64 get_Z () cil managed 
		{
			// Method begins at RVA 0x2108
			// Code size 8 (0x8)
			.maxstack 8

			IL_0000: nop
			IL_0001: ldarg.0
			IL_0002: ldfld float64 Heracles/Point3::z
			IL_0007: ret
		} // end of method Point3::get_Z

		.method public hidebysig specialname 
			instance class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<class Heracles/Point3, float64> get_DistanceTo () cil managed 
		{
			// Method begins at RVA 0x2114
			// Code size 8 (0x8)
			.maxstack 8

			IL_0000: nop
			IL_0001: ldarg.0
			IL_0002: newobj instance void Heracles/get_DistanceTo@18::.ctor(class Heracles/Point3)
			IL_0007: ret
		} // end of method Point3::get_DistanceTo

		// Properties
		.property instance float64 X()
		{
			.get instance float64 Heracles/Point3::get_X()
		}
		.property instance float64 Y()
		{
			.get instance float64 Heracles/Point3::get_Y()
		}
		.property instance float64 Z()
		{
			.get instance float64 Heracles/Point3::get_Z()
		}
		.property instance class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<class Heracles/Point3, float64> DistanceTo()
		{
			.get instance class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<class Heracles/Point3, float64> Heracles/Point3::get_DistanceTo()
		}

	} // end of class Point3

	.class nested assembly auto ansi serializable beforefieldinit get_DistanceTo@18
		extends class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<class Heracles/Point3, float64>
	{
		// Fields
		.field public class Heracles/Point3 x

		// Methods
		.method assembly specialname rtspecialname 
			instance void .ctor (
				class Heracles/Point3 x
			) cil managed 
		{
			// Method begins at RVA 0x2120
			// Code size 14 (0xe)
			.maxstack 8

			IL_0000: ldarg.0
			IL_0001: call instance void class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<class Heracles/Point3, float64>::.ctor()
			IL_0006: ldarg.0
			IL_0007: ldarg.1
			IL_0008: stfld class Heracles/Point3 Heracles/get_DistanceTo@18::x
			IL_000d: ret
		} // end of method get_DistanceTo@18::.ctor

		.method public strict virtual 
			instance float64 Invoke (
				class Heracles/Point3 destiny
			) cil managed 
		{
			// Method begins at RVA 0x2130
			// Code size 14 (0xe)
			.maxstack 8

			IL_0000: nop
			IL_0001: ldarg.0
			IL_0002: ldfld class Heracles/Point3 Heracles/get_DistanceTo@18::x
			IL_0007: ldarg.1
			IL_0008: call float64 Heracles::distanceBetween(class Heracles/Point3, class Heracles/Point3)
			IL_000d: ret
		} // end of method get_DistanceTo@18::Invoke

	} // end of class get_DistanceTo@18


	// Methods
	.method public static 
		float64 distanceBetween (
			class Heracles/Point3 origin,
			class Heracles/Point3 destiny
		) cil managed 
	{
		.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationArgumentCountsAttribute::.ctor(int32[]) = (
			01 00 02 00 00 00 01 00 00 00 01 00 00 00 00 00
		)
		// Method begins at RVA 0x2050
		// Code size 60 (0x3c)
		.maxstack 5
		.locals init (
			[0] float64 dx,
			[1] float64 dy,
			[2] float64 dz
		)

		IL_0000: nop
		IL_0001: ldarg.0
		IL_0002: ldfld float64 Heracles/Point3::x
		IL_0007: ldarg.1
		IL_0008: ldfld float64 Heracles/Point3::x
		IL_000d: sub
		IL_000e: stloc.0
		IL_000f: ldarg.0
		IL_0010: ldfld float64 Heracles/Point3::y
		IL_0015: ldarg.1
		IL_0016: ldfld float64 Heracles/Point3::y
		IL_001b: sub
		IL_001c: stloc.1
		IL_001d: ldarg.0
		IL_001e: ldfld float64 Heracles/Point3::z
		IL_0023: ldarg.1
		IL_0024: ldfld float64 Heracles/Point3::z
		IL_0029: sub
		IL_002a: stloc.2
		IL_002b: ldloc.0
		IL_002c: ldloc.0
		IL_002d: mul
		IL_002e: ldloc.1
		IL_002f: ldloc.1
		IL_0030: mul
		IL_0031: add
		IL_0032: ldloc.2
		IL_0033: ldloc.2
		IL_0034: mul
		IL_0035: add
		IL_0036: call float64 [mscorlib]System.Math::Sqrt(float64)
		IL_003b: ret
	} // end of method Heracles::distanceBetween

} // end of class Heracles
````

What's the reason for get_DistanceTo@18?! Is really necessary to create a new object everty time that I use DistanceTo?

**Comment by rodrigovidal** [comment]
If you use the function with both parameters the result is different. 

```
type Point3(x: double, y: double, z: double) = 
    new(x: double, y: double) = Point3(x, y, 0.0)
    new() = Point3(0.0, 0.0, 0.0)
    member d.X = x
    member d.Y = y
    member d.Z = z

let distanceBetween (origin: Point3) (destiny: Point3) =
    let dx = origin.X - destiny.X
    let dy = origin.Y - destiny.Y
    let dz = origin.Z - destiny.Z
    sqrt(dx * dx + dy * dy + dz * dz)

type Point3 with
    member x.DistanceTo(v) = distanceBetween x v
```
https://gist.github.com/rodrigovidal/81682b15dd75f15e0941

I think that the same "optimization" should apply.

**Comment by latkin** [comment]
`DistanceTo` is declared as a property, which will be re-evaluated on each invocation.  Per the code, the property returns a new partially-applied function each time, and that means allocating a new closure each time.

@rodrigovidal's solution looks like the best option to me.  Instead of the property returning a closure, it calls the function.

If you really want to use partial application, then you will need to cache the partially-applied function in an instance field, then re-use it.  Options below for use as a property or as a method:

```fsharp
type Point3(x: double, y: double, z: double) as this = 
    // create 1 partial application per instance
    let distToThis = Point3.distanceBetween this

    new(x: double, y: double) = Point3(x, y, 0.0)
    new() = Point3(0.0, 0.0, 0.0)
    member d.X = x
    member d.Y = y
    member d.Z = z

    // return the cached partial application
    member d.DistanceToAsProp = distToThis

    // invoke the cached partial application
    member d.DistanceToAsMeth(v) = distToThis v

    static member distanceBetween (origin : Point3) (destiny : Point3) =
        let dx = origin.X - destiny.X
        let dy = origin.Y - destiny.Y
        let dz = origin.Z - destiny.Z
        sqrt(dx * dx + dy * dy + dz * dz)
```

**Comment by ElemarJR** [comment]
Sorry, @latkin but I don't agree with you. It's really hard to differentiate properties and methods here.  The use will be the same. But I accept your argument. 

Compiler generates the type and knows that is readonly. There is no reason to not create the caching automatically

**Comment by rodrigovidal** [comment]
@latkin Don't you think that the compiler should cache the closure for me? Is there a reason for not to?

**Comment by giggio** [comment]
I don't think the compiler should optimize in this case. It is doing exactly what you asked for. It could try to be smart about it, but the meaning of the code could be different, and end up breaking behavior on badly designed code.

**Comment by ElemarJR** [comment]
Sorry @giggio. It's not the case. I am using partial application in the correct way. Compiler is using more resources than necessary to deliver what I asked.

**Comment by ElemarJR** [comment]
@giggio In a "declarative mindset"  I expect that compiler produces the best code to deliver what I asked.

**Comment by giggio** [comment]
I get it. But it is still a property, and a getter, and that is the expected behavior. If the getter has side effects, and you cache it, you loose the side effects. I know that that is usually wrong, but it is difficult for the compiler to infer that it is safe to optimize in this situation.

**Comment by latkin** [comment]
The compiler is indeed producing the best (and only possible) code to deliver what you asked: a property that returns a new partially-applied function.

What if the compiler automatically cached this in a backing field without you asking? That means every instance of your type now requires allocation of an additional partial application closure, which you probably didn't expect and can't control (I thought my type only had 3 fields and some methods! Why are all these FSharpFuncs on the heap?!). This small vector type now carries around a bunch of extra baggage all the time, no matter how you use it.  If this were a value type, such an optimization would be disastrous to performance, and invalid in the case of zero-init values. Maybe the cached value is lazily-created... well that means the internal state is now mutable and internal locking is required to keep it thread safe. More perf-harming codegen you didn't expect.

Instead, the compiler just gives you what you asked for, and doesn't make potentially harmful assumptions.

F# does support automatic backing fields for properties, using the `member val` syntax (i.e. when you opt-in).  I should have mentioned this in my earlier reply, apologies. See the [MSDN page](https://msdn.microsoft.com/en-us/library/dd483467.aspx) on F# Properties, particularly this passage:

> Note that the expression that initializes an automatically implemented property is only evaluated upon initialization, and not every time the property is accessed. This behavior is in contrast to the behavior of an explicitly implemented property. What this effectively means is that the code to initialize these properties is added to the constructor of a class

Usage would look like this:

```fsharp
type Point3(x: double, y: double, z: double) as this = 
    member d.X = x
    member d.Y = y
    member d.Z = z

    // compiler automatically generates backing field
    member val DistanceToAsAutoProp = Point3.distanceBetween this

    static member distanceBetween (origin : Point3) (destiny : Point3) =
        let dx = origin.X - destiny.X
        let dy = origin.Y - destiny.Y
        let dz = origin.Z - destiny.Z
        sqrt(dx * dx + dy * dy + dz * dz)
```

I am not suggesting that this stuff is "obvious" or "easy," I'm just trying to explain what's happening and why. In fact I totally agree it's quite easy to get these distinctions mixed up sometimes.

In raw .NET there are data, and there are functions (methods), and these are completely distinct.  In F# (or functional-style C#), this distinction fades away, and often functions *are* data.  Mapping functions-as-data back to raw .NET is a tricky business and different approaches yield different tradeoffs.

For the most part the F# compiler will try to do the safest/best thing to achieve what you asked, and provides enough flexibility to do something else if needed.

**Comment by ElemarJR** [comment]
@giggio there is no side effects, never. Type of returned object is generated by the compiler and it's always readonly. There is no inference here. :)

**Comment by giggio** [comment]
@elemarjr In this specific situation it is. But it could not be. Plus what @latkin said. :)

**Comment by ElemarJR** [comment]
I got it. Thanks @latkin. I've been thinking about  the implications and I accept your arguments. 

While using f# I will have to make distinction between function and partially-applied functions. Conceptually  I do not see this distinction.

**Comment by latkin** [comment]
I guess this basically boils down to an argument that the compiler should automatically [memoize](http://en.wikipedia.org/wiki/Memoization) all provably side-effect-free functions.  That's an interesting idea.  In many situations it will result in better performance.  But it carries a heavy memory burden, and will therefore result in worse performance in equally many situations.  The realities of .NET interop (value types, exceptions, nulls, reflection, serialization, etc) unfortunately make this even more complex and impractical.  F# isn't quite so bleeding edge experimental :smile: 

Some interesting links on automatic memoization:
- [As it pertains to Haskell](http://stackoverflow.com/q/5749039/1366219)
- [Attempt to do it in Python](http://www.pgbovine.net/projects/pubs/guo_issta11_camera_ready.pdf)

**Comment by ElemarJR** [comment]
@latkin I don't think that is the case of memoization. But, compile-time optimization.

If every call for a property getter returns a conceptually equal result, so I can improve the emitted code. Don't you think?

What's the risk of generate CIL that just calls distanceBetween, like expressed in @rodrigovidal's code?
