### ISSUE TITLE
AddObsoleteAttribute on ProvidedStaticParameter

### ISSUE THREAD

**Issue by dmitry-a-morozov** [Microsoft/visualfsharp#439]
It would be nice to have ```AddObsoleteAttribute``` on ```ProvidedStaticParameter``` too.

**Comment by dsyme** [comment]
Yes. Ideally add as a suggestion on http://fslang.uservoice.com (which I'd consider approved subject to discussion), and submit a PR here. Won't make F# 4.0 though - vNext

**Comment by dsyme** [comment]
Closing as its a design issue
