### ISSUE TITLE
F# compiler/tools type provider generated types cache misses

### ISSUE THREAD

**Issue by dmitry-a-morozov** [Microsoft/visualfsharp#440]
Instantiation function is called 3 times within short period of time (~ 1 sec) for type provider generated types for now obvious reason.

I created repro project 
https://github.com/dmitry-a-morozov/Sandbox/tree/2902ed84c434b2b555f888312f5aa254d2b33197/TPCacheMisses

To repro take following steps
  1. Open TPCacheMisses.sln
  2. Compile type provider
  3. Start TPCacheMisses project (with or w/o debugger)
  4. Open Test.fsx to trigger types generation
  5. Observe assertion pop-up

https://github.com/dmitry-a-morozov/Sandbox/tree/66f55ff410262382373b134c7252c174f49adcca/TPCacheMisses

**Comment by dsyme** [comment]
Can you implement a cache for the generation in the type provider?  e.g. https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/FSharp.Data.TypeProviders/TypeProviders.fs#L33

**Comment by dmitry-a-morozov** [comment]
Of course I do that. 
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/master/src/SqlClient/ProvidedTypesCache.fs
But I thought F# compiler can be a little smarter. 
Seems like cache miss to me.

BTW, isn't types cache suppose to be thread-safe?

**Comment by dsyme** [comment]
Closing old discussion

**Comment by dmitry-a-morozov** [comment]
Agree. As a matter of fact I think I have a good solution for this problem. Better than on one in FSharp.Data. 
https://github.com/fsharp/FSharp.Data/blob/2.3.1/src/CommonProviderImplementation/Helpers.fs#L295
Maybe I will write a blog post on that.
