### ISSUE TITLE
.NET Core and .NET Standard projects (new project file format) don't have file context options in solution explorer

### ISSUE THREAD

**Issue by SirUppyPancakes** [Microsoft/visualfsharp#4416]
.NET Core and .NET Standard projects, which both use the newer project file format, are missing the right-click context items normally expected in an F# project (Add Above, Add Below, Move Up, Move Down, etc). The project file must be manually edited to enforce the necessary file-order/folder dependencies.

**Reproduction:**

1. Create a new blank solution.
2. Add a bunch of F# projects to it of various types (Console, Core, Standard, PCL, Library, etc.).
3. Notice the context items missing from the Core/Standard projects, and any other projects I would expect, that use the new project file format.

**Workaround:**

Manually edit the project file for these functions.

**Comment by cartermp** [comment]
These have all been implemented for the 15.6 release. You can try it out as a preview today, or the official release which should be soon.
