### ISSUE TITLE
`Add new item...\Source file` closes all the files below added file

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#4418]
#### Repro steps

1. Add 3 F# source files
2. Open them all
3. Right click on the first one and add new source file below

#### Expected behavior

All the opened files remain open

#### Actual behavior

All the files below the added file are being closed

#### Known workarounds

No

#### Related information 

* Windows 10.0.16299.248 Pro x64 English Singapore
* .NET Core 2.0
* Visual Studio 15.5.7, 15.6.0 Preview 6
* Medium

**Comment by cartermp** [comment]
cc @TIHan

**Comment by cartermp** [comment]
I believe @TIHan fixed this a while back, as it no longer reproduces.
