### ISSUE TITLE
Not possible to specify a type alias to "outer" scoped type with same name

### ISSUE THREAD

**Issue by matthid** [Microsoft/visualfsharp#4426]
#### Description

I tried to use type-aliases to introduce an source-code-backwards-compatible API change. And the compiler didn't accept the alias as I'd expect.

Does this work as designed or is this a bug?

#### Repro steps

Consider you have an API looking like:

```fsharp
module M =
    type R = { A : string; B: int }
```

Now you want to refactor `R` to be in the namespace and have a type alias for `R` (for backwards compat).
This doesn't work:
```fsharp
type R = { A : string; B: int }
module M =
    [<System.Obsolete("Use R instead of M.R")>]
    type R = R
```

as it breaks the following client code:

```fsharp
    let f (p:M.R) =
        { p with B = 2 }
```

#### Expected behavior

No compiler error.

#### Actual behavior

 `error FS0001: This expression was expected to have type    'M.R'    but here has type    'R'`

#### Known workarounds

```fsharp
namespace Version2
type R = { A : string; B: int }
namespace Version2
module M =
    [<System.Obsolete("Use Version2.R")>]
    type R = Version2.R

namespace Program
open Version2 // Replace with Version2

module Program =
    let f (p:M.R) =
        { p with B = 2 }
```

#### Related information 

Full code sample to easily reproduce:

`dotnet new console -lang f#`

```fsharp
namespace Version1
module M =
    type R = { A : string; B: int }
    
namespace Version2
type R = { A : string; B: int }
module M =
    [<System.Obsolete("Use R instead of M.R")>]
    type R = R

namespace Program
open Version1 // Replace with Version2

module Program =
    let f (p:M.R) =
        { p with B = 2 }

    [<EntryPoint>]
    let main argv = 0
```

```
$ dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by matthid** [comment]
Apparently the problem is that the compiler is creating a new DU with a single case instead of a type-alias.
It seems like there is no way to reference the "outer" `R`:

![image](https://user-images.githubusercontent.com/1866463/36938996-57007be0-1f2a-11e8-81f3-bfb882822f64.png)

**Comment by realvictorprm** [comment]
Then it's like I supposed, well this is a bug?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-03 21:32 GMT+01:00 Matthias Dittrich <notifications@github.com>:

**Comment by matthid** [comment]
The following works and seems to be a workaround:

```fsharp
namespace Version2
type R = { A : string; B: int }
namespace Version2
module M =
    [<System.Obsolete("Use R instead of M.R")>]
    type R = Version2.R

namespace Program
open Version2

module Program =
    let f (p:M.R) =
        { p with B = 2 }
```

**Comment by dsyme** [comment]
This is by design for name resolution. There are other workarounds such as
```
namespace rec N

type R = { A : string; B: int }
module M =
    [<System.Obsolete("Use R instead of M.R")>]
    type R = N.R
```
thanks

**Comment by matthid** [comment]
@dsyme Do you care to elaborate? Usually the language prefers a type alias over a single cased DU. Is there a special reason for this exception?

**Comment by matthid** [comment]
I can see the following in the spec (8.5):

![image](https://user-images.githubusercontent.com/1866463/37242935-ae87bdd2-2471-11e8-9510-4f3e2391e856.png)

Which indicates that this is a bug. Is there another place in the spec which refers to this exception?

**Comment by matthid** [comment]
Ok now I get it. Basically DUs can be defined recursively without rec:

```
type Test =
    | Test of string
    | Expr of Test * Test
```

Therefore the outer `R` in the above case is no longer in scope.
