### ISSUE TITLE
FSharp.Compiler.Tools 10.0.1 "License Info" link is dead

### ISSUE THREAD

**Issue by JanWosnitza** [Microsoft/visualfsharp#4434]
#### Repro steps
1. Navigate to https://www.nuget.org/packages/FSharp.Compiler.Tools/10.0.1
2. Click on the "License Info" link

OR

1. Search for FSharp.Compiler.Tools in VS's NuGet window
2. Click on the "License" link

#### Expected behavior

The link should lead to https://github.com/fsharp/fsharp/blob/master/License.txt

#### Actual behavior

The link sends you to https://github.com/fsharp/fsharp/blob/master/LICENSE which results in a 404 error.

#### Known workarounds

Click on "Project Site" instead and select License.txt on GitHub.

**Comment by cartermp** [comment]
@dsyme or @forki could you update the link for the package? https://github.com/fsharp/fsharp/blob/master/License.txt

**Comment by dsyme** [comment]
Fixed
