### ISSUE TITLE
Flaky Ubuntu16.04 Release_fcs Build  build

### ISSUE THREAD

**Issue by AviAvni** [Microsoft/visualfsharp#4484]
The Ubuntu16.04 Release_fcs Build build is fail because of nuget restoring package
See https://github.com/Microsoft/visualfsharp/pull/4429
Workaround: use dotnetbot to retrigger the build

**Comment by forki** [comment]
Yes I saw this as well in basically all my recent pull requests. This is a contributor pain and should be addressed. There are two ways to solve this problem.
a) add automatic retry to the restore process
b) you know b)
