### ISSUE TITLE
Unused Opens Diagnostic analyser is very slow in large files

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#4488]
The unused opens diagnostic analyzer is implemented in a way that is not sufficiently performant, particularly for large files.

When using 15.6, you will see long delays before error lists red squigglies are updated.  

When using 15.7 previews, you will see either long delays before error lists/red-squigglies, or just unnecessary CPU load, depending on whether https://github.com/Microsoft/visualfsharp/pull/4369 has been fixed

### Repro

1. Open FSharp.sln. Go to IlxGen.fs. 
2. Make an edit. Wait for red squigglies. 
3. Repeat, measuring update time

### Possible Cause

From quick profiling it looks to me like some of the code here may be quadratic or worse 

![image](https://user-images.githubusercontent.com/7204669/37259468-a52859c8-257e-11e8-92ec-0b1f1400ddf4.png)

https://github.com/Microsoft/visualfsharp/blob/52391ed77b1f185d9d51b2e022961e44600f8ae0/src/fsharp/service/ServiceAnalysis.fs#L96

### Workaround

It should be possible for us to make this performant. But until then when using large files (> 500 lines?) I'd say it's best to turn this analyzer off by default until we get to the bottom of this.  

![image](https://user-images.githubusercontent.com/7204669/37259428-0d6ab0ae-257e-11e8-8574-e9244e42d278.png)

**Comment by auduchinok** [comment]
@dsyme I think it would be better to fix performance (rather than disabling thee feature) the way @vasily-kirichenko suggested in https://github.com/fsharp/FSharp.Compiler.Service/issues/830.

**Comment by vasily-kirichenko** [comment]
@auduchinok :))))))))

**Comment by dsyme** [comment]
@auduchinok Yes, though in 15.6 we should disable the feature since it is locked down. The feature should never have been enabled in such a state.

In 15.7/master we will fix it, of course.
