### ISSUE TITLE
No Intellisense for ctors of TP generated types

### ISSUE THREAD

**Issue by dmitry-a-morozov** [Microsoft/visualfsharp#449]
I believe this was an issue since VS 2012 F# 3.0. It's applicable to VS 2013 + F# 3.1, VS 2015 + F 4.0.
As example a library I work on FSharp.Data.SqlClient (ver 1.6.2 as of now) contains SqlCommandProvider. Types generated by this provider have 2 overloaded constructors. Neither this or any information on parameters shows up in VS Intellisense.
Another example is CsvProvider from FSharp.Data (ver 2.2.2 as of now) has single ctor with one parameter `row` of type `IEnumerable<_>`. This information is not available in Intellisense .

**Comment by jackfoxy** [comment]
I must say this bug does inhibit the usefulness of type providers. It's a case of "out of sight, out of mind".

**Comment by dmitry-a-morozov** [comment]
The problem appears only on top level erased typed. Nested types have Intellisense show up for constructors.
