### ISSUE TITLE
fsi.CommandLineArgs behavior different when fsi invoked with 8.3 short path

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#45]
Opened at codeplex by latkin

Say I have a script that just prints out its arguments:
```fsharp
printfn "Args are: %A" fsi.CommandLineArgs
```
If I invoke this script via FSI using a full long path, it works as expected:  
C:\Users\latkin> Source\Repos\visualfsharp\Debug\net40\bin\fsi.exe --exec test.fsx 1 2
Args are: [|"test.fsx"; "1"; "2"|]
But if I invoke with the 8.3 short path, it goes wrong:
C:\Users\latkin> Source\Repos\visual~1\Debug\net40\bin\fsi.exe --exec test.fsx 1 2
Args are: [|"Source\Repos\visual~1\Debug\net40\bin\fsi.exe"; "--exec"; "test.fsx"; "1"; "2"|]
This repros 100%, on 2 different machines, both debug and release, for open source output. It does not repro with official VS bits. 

I spent some time debugging, and it’s not a problem with the command line arg parser. In the repro case, the InteractiveSession instance is being re-initialized a second time after CommandLineArgs is set, thus reverting back to its default value of  Environment.GetCommandLineArgs(). I verified the dynamically generated IL for both cases is exactly the same. 

Output with debug tracing:
C:\Users\latkin> Source\Repos\visualfsharp\Debug\net40\bin\fsi.exe --exec test.fsx 1 2
Initializing to Environment.GetCommandLineArgs
Just set fsi.CommandLineArgs to [|"test.fsx"; "1"; "2"|]
Args are: [|"test.fsx"; "1"; "2"|]

C:\Users\latkin> Source\Repos\visual~1\Debug\net40\bin\fsi.exe --exec test.fsx 1 2
Initializing to Environment.GetCommandLineArgs
Just set fsi.CommandLineArgs to [|"test.fsx"; "1"; "2"|]
Initializing to Environment.GetCommandLineArgs
Args are: [|"Source\Repos\visual~1\Debug\net40\bin\fsi.exe"; "--exec"; "test.fsx"; "1"; "2"|]
Fsi.fs 
![dwyi2nv](https://cloud.githubusercontent.com/assets/5175830/5791084/3b0e6270-9e6e-11e4-8726-db66c58d8a8d.png)
fsiaux.fs 
![c0pqjba](https://cloud.githubusercontent.com/assets/5175830/5791080/0375e19e-9e6e-11e4-95ff-8c9617178d80.png) 

> comments
> vladima wrote Apr 7, 2014 at 3:44 PM [x] 
> Seems that FSharp.Compiler.Interactive.Settings.dll was loaded twice and thus 2 instances of InteractiveSession were created.
> * During fsi initialization FSharp.Compiler.Interactive.Settings.dll is loaded in Load context from .. visual~1/fsharp/Debug/net40/bin/ 
> * When executing dynamically generated code FSharp.Compiler.Interactive.Settings is requested to be loaded to the LoadFrom context. During lookup it will be resolved in …/visualfsharp/fsharp/Debug/net40/bin/FSharp.Compiler.Interactive.Settings.dll. Here comes the juicy part (from FUSLOGW):

> LOG: Attempting download of new URL file:///...visualfsharp/fsharp/Debug/net40/bin/FSharp.Compiler.Interactive.Settings.dll.
> LOG: Assembly download was successful. Attempting setup of file: …\visualfsharp\fsharp\Debug\net40\bin\FSharp.Compiler.Interactive.Settings.dll
> LOG: Entering run-from-source setup phase.
> LOG: Assembly Name is: FSharp.Compiler.Interactive.Settings, Version=4.3.1.9055, Culture=neutral, PublicKeyToken=f536804aa0eb945b
> LOG: Re-apply policy for where-ref bind.
> LOG: Post-policy reference: FSharp.Compiler.Interactive.Settings, Version=4.3.1.9055, Culture=neutral, PublicKeyToken=f536804aa0eb945b
> LOG: GAC Lookup was unsuccessful.
> LOG: Where-ref bind Codebase does not match what is found in default context. Keep the result in LoadFrom context.
> LOG: Binding succeeds. Returns assembly from …\visualfsharp\fsharp\Debug\net40\bin\FSharp.Compiler.Interactive.Settings.dll.
> LOG: Assembly is loaded in LoadFrom load context.
> WRN: The same assembly was loaded into multiple contexts of an application domain:
> WRN: Context: Default | Domain ID: 1 | Assembly Name: FSharp.Compiler.Interactive.Settings, Version=4.3.1.9055, Culture=neutral, PublicKeyToken=f536804aa0eb945b
> WRN: Context: LoadFrom | Domain ID: 1 | Assembly Name: FSharp.Compiler.Interactive.Settings, Version=4.3.1.9055, Culture=neutral, PublicKeyToken=f536804aa0eb945b
> WRN: This might lead to runtime failures.

>>vladima wrote Apr 7, 2014 at 3:45 PM [x] 

>>seems that workaround is simple: given that problem appears when ApplicationBase has 8.3 shape we can create a helper domain with an updated value of ApplicationBase and run all fsi code in it.

>> Smth like:
```fsharp
 [<EntryPoint>]
 [<STAThread()>] 
 let MainMain argv = 
ignore argv

let appDomainSetup = System.AppDomain.CurrentDomain.SetupInformation
appDomainSetup.ApplicationBase <- Path.GetFullPath(appDomainSetup.ApplicationBase)
let helperDomain = AppDomain.CreateDomain("helper-domain", null, appDomainSetup)
helperDomain.DoCallBack(fun() ->
    let argv = System.Environment.GetCommandLineArgs()
…
```

>>>srivatsn wrote Apr 9, 2014 at 10:16 AM [x] 

>>>@vladima, if you've investigated this, we would welcome a pull request :)
>>>vladima wrote Apr 9, 2014 at 10:52 AM [x] 
>>>already done :)

>>>>KevinRansom wrote Jun 2, 2014 at 6:41 PM [x] 
>>>>This is a bug in the CLR, the pr is a neat work around, Howe er we would prefer the correct.fix.
>>>> ** Closed by KevinRansom 06/02/2014 6:41PM

>>>>>forki wrote Jun 3, 2014 at 1:46 AM [x] 
>>>>>I'd argue that a fix which works around a CLR bug is valuable since it might take a while to get the CLR changed. How is the process now? Can we track the CLR bug issue somehow? 

>>>>>>latkin wrote Jun 5, 2014 at 9:46 AM [x] 
>>>>>>I agree proposed workaround is not ideal and real CLR fix is preferred. That being said, the issue still exists, so it would be good to leave this open until we have a fix or resolution to offer - either a workaround in F#, or a patch from CLR team.

**Comment by latkin** [comment]
Just chatted with @KevinRansom about this. We believe current status is that .NET fixed the underlying bug, but this was really obscure anyways and would never come up in real-world scenarios for F# users, so it's not worth worrying about.  Closing...
