### ISSUE TITLE
Ctrl+ Enter takes indent from wrong line.

### ISSUE THREAD

**Issue by realparadyne** [Microsoft/visualfsharp#450]
In VS2015 RC and the F# editor, using Ctrl+Enter to insert a line above the current one, the indent position is incorrectly taken from the line above instead of the line the cursor was on.  This worked correctly in VS2013 and still works correctly in VS2015RC when editing C#.

**Comment by latkin** [comment]
Can you provide details (w/ sample code or screenshot) of the old behavior and the new behavior?

I am seeing the same behavior in 2013 and 2015, where the cursor matches indentation of the previous line (below screencast is with 2013):

![newline](https://cloud.githubusercontent.com/assets/5943573/7689649/b9daa228-fd62-11e4-8832-c9c514de70bf.gif)

**Comment by enricosada** [comment]
shouldn't the `CTRL-ENTER` after `"foo"` move the cursor at the same indentation ( column 4 ) of `printfn "foo"` instead of `let test` ( column 0 ) ? 
the idea is to add a new line is the same block ( c# behaviour )

![insert_line_before](https://cloud.githubusercontent.com/assets/147243/7699744/72c5ccb0-fe1a-11e4-976f-fa7d645e18f5.gif)

**Comment by latkin** [comment]
@enricosada I'm not claiming current behavior is perfect, but if hasn't changed from 2013 to 2015 then this is less a bug than a small feature request.

Cleaning up behavior would probably not be too hard post-VS 2015 - VS command to handle is `Edit.LineOpenAbove`.

**Comment by enricosada** [comment]
yes @latkin , i was trying to repro the regression, but my vs 2013 (clean, no development or vspowertools) has the same behaviour of 2015.

i wrote about the c# behaviour to understand what @realparadyne was saying. 

The c# behaviour is a nice improvement ( i didn't know the `CTRL-ENTER` , resharper use the keybinding :smile: ) , i'll add an issue later

**Comment by realparadyne** [comment]
I'm going to have to apologise!  I tested it right before posting and the VS2013 behaviour seemed better but having just retested it now you are correct and it is the same (though the c# behaviour is still better).  Sorry for the mistake.
