### ISSUE TITLE
False warnings in Error List: "The referenced component 'MyProject' could not be found.", followed by false errors.

### ISSUE THREAD

**Issue by BentTranberg** [Microsoft/visualfsharp#4506]
After updating to VS 2017 15.6.1, these mysterious warnings have started to appear in the Error List pane from time to time when I do successful builds in my solutions.

"The referenced component 'MyProject' could not be found."

First there's just the warnings. Then when trying to recompile one or more times, the warnings will eventually be accompanied with various errors.

![image](https://user-images.githubusercontent.com/15068882/37343974-51dc539a-26c9-11e8-9b8a-dc97949c7268.png)

Note that this shows up although the Error List is filtered on "Build Only".

It happens rather frequently, and with solutions with .NET Framework 4.5.2 and 4.6.1. (I don't have anything else.)

These warnings ~~and errors~~ do not show up in the Build Output. The status bar says the build is successful, as it should. Edit: Some errors do show up in the build output, and there is actual compiler errors, but they are false. Restarting VS is the best option to get rid of them quickly.

I am beginning to suspect it only happens when C# projects references F# projects, but haven't done any intensive research on that.

It happens in several solutions, and on several machines.

#### Repro steps

Rather random behavior. ~~I don't have a repro yet.~~ Repro posted below somewhere.

#### Known workarounds

~~None discovered yet.~~
I think deleting .vs and bin and obj folders will help.

#### Related information 

* Operating system - Windows 10, updated.
* .NET Runtime - .NET Framework 4.5.2 and 4.6.1
* VS 2017 15.6.1
* Severity - very annoying. ~~I prefer to roll back if possible.~~ ~~edit1: The found workaround makes this problem considerably less important for me.~~ edit2: The number of actual compiler errors caused by this has increased in frequency, so now it's really annoying.

**Comment by BentTranberg** [comment]
So I just reported, and then there's a change of course.

The FS0084 that you see in the screenshot above, was the only one of the warnings and errors that also appeared when filtering on "IntelliSense Only".

I restarted VS hoping that would clear the false messages. It didn't. Then I looked in the Build Output, and noticed FS0084 was present there, but none of the other messages.

Then I decided I would run anyway, and it actually worked. The Build Output is flawless. But the Error List is back to displaying false warnings only.

![image](https://user-images.githubusercontent.com/15068882/37345731-d7debf38-26cd-11e8-90e6-b2d7d86d5fc8.png)

I deleted .vs in the solution root, and all bin and obj folders. This seems to have got rid of the problem, but whether it's permanent I don't know yet.

**Comment by cartermp** [comment]
@BentTranberg Very strange. Do you have a sample solution you could share, or some info about the project types? There's an issue with phantom errror messages in 15.6 for .NET Core SDK-based projects if you have a P2P reference, but they will go away if the file is closed and re-opened (#3952), but I'm not sure if this is what you have.

**Comment by BentTranberg** [comment]
All the warnings are from C# projects of various types - WPF, WinForms, .NET Framework Library. All the projects that aren't found are F# Framework Library. Solutions are either Framework 4.5.2 or 4.6.1.

I tried only deleting the .vs folder in one case, and that was sufficient to get rid of the problem.

**Comment by cartermp** [comment]
Good to know. We'll keep this open for a bit to see if anyone else comes across. If you don't repro again and nobody else mentions they're seeing it, we'll close the issue.

**Comment by BentTranberg** [comment]
Just now had a case where deleting the .vs folder earlier did not help permanently. Warnings appeared after some hours work. Nevertheless deleting .vs, bin and obj folders still diminishes the problem greatly. Haven't yet tried to delete only bin and obj, and leave .vs, but will try that next time.

I can't afford to do research on this, but will report findings when stuff happens.

**Comment by BentTranberg** [comment]
It's getting more annoying, so I thought it worthwhile now to produce a repro. I get warnings and errors immediately when I open and compile this.

[TdNet5.bughunt.zip](https://github.com/Microsoft/visualfsharp/files/1811532/TdNet5.bughunt.zip)

To produce a repro, I first tried to remove projects that didn't relate to the projects in the warnings. That didn't work - warnings and errors disappeared after some pruning. Then instead I removed pretty much all source from all projects, and references to commercial libraries, but left all references to free NuGet packages. I stopped there and haven't attempted to reduce it further.

**Comment by BentTranberg** [comment]
Updated to VS 15.6.2, and the problem is still present.

**Comment by BentTranberg** [comment]
@cartermp, I updated to VS 15.6.3, and the problem seems to be gone. I have worked several hours today and yesterday without sign of it. At 15.6.2 it typically showed up several times in an hour.

Suggest we close this. Also remove the "needs repro", since I've uploaded a zip with repro above.

**Comment by cartermp** [comment]
Agh, sorry @BentTranberg - I've been a bit swamped in preparing for travels in the next two weeks. I'll close this for now, and please do ping to re-open if you see it again.
