### ISSUE TITLE
List.truncate and Array.truncate diverge from Seq.truncate wrt negative inputs

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#453]
```fsharp
[1..5] |> Seq.truncate -1  // empty seq
[1..5] |> List.truncate -1  // throws
[| 1..5 |] |> Array.truncate -1 // throws
```

`Seq.truncate` was the original implementation, so IMO the new APIs `List.truncate` and `Array.truncate` should match that behavior, i.e. on negative input, return empty collections.

Credit to @imfrancisd for noticing this and pointing it out in #451.

**Comment by PatrickMcDonald** [comment]
I've no idea how I invented that new requirement, the mind boggles.  Great catch

**Comment by imfrancisd** [comment]
Thank you! :-)

I thought I was the only one.
