### ISSUE TITLE
Intellisense and Error Highlighting in VisualF# takes more than 5 seconds to appear/change

### ISSUE THREAD

**Issue by realvictorprm** [Microsoft/visualfsharp#4532]
With the latest stable Visual Studio I'm running into bad editor performance with the Visual F# solution projects.

This doesn't include solution load time nor build time. They improved much compared to months ago + building got very easy and responsive.

Consider I'm working either in FSharp.Editor or in the Fsharp Compiler, if I apply changes which would cause or solve an error I have to wait 'felt much'/ more than 5 seconds till something happens. 
If I trigger intellisense I have to wait a bit around 2 or more seconds.

I already disabled the unused open analyser, did I miss something else?

----

If this is still the case is there anything we can do about for this repository? If it wouldn't take so much time my productivity would increase much (linear with the reduced build time and wait time for error & intellisense feedback).

**Comment by dsyme** [comment]
@realvictorprm 

1. Turn off "Unused opens".  
2. And/or turn off "In-memory cross project references"

See #4488

**Comment by cartermp** [comment]
The inconsistently long delays (i.e., sometimes or often more than 2 sec) are fixed with the 15.7 perf improvements.
