### ISSUE TITLE
Format selection script.fsx, cursor goes to end of file

### ISSUE THREAD

**Issue by philderbeast** [Microsoft/visualfsharp#455]
In Visual Studio 2015 CTP, open an fsharp *.fsx script file and choose Edit|Advanced|Format Selection. If the code is reformatted then the cursor jumps to the end of the file after the reformatting. I would have expected the cursor to stay on the same line.

I tested this with the banana pyjamas loop in the following file at rev d3d937ed12c8d091f984870a9b7ee3c4295cbee4 ...

https://github.com/BlockScope/ExpertFSharp/blob/master/04Imperative/Script.fsx

**Comment by latkin** [comment]
Source formatting is implemented by the Visual F# Power Tools extension, it's not actually part of the base Visual F# tools.  You can open an issue for this at https://github.com/fsprojects/VisualFSharpPowerTools
