### ISSUE TITLE
Create a new legacy F# project on VS2017.7 with developer build (dev15.8) fails

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#4550]
Using developer build of F# dev15.8 branch.

Create new legacy F# projects yields:

![image](https://user-images.githubusercontent.com/5175830/37496742-8c693f92-2871-11e8-99ef-a5f3b830a1c4.png)

Expected to be able to create a new F# project fine.

**Comment by KevinRansom** [comment]
The extra 4.3.1 was put in to address that.  Once developers are on dev15.8 that will no longer be necessary.

**Comment by cartermp** [comment]
Closing as this will be in 15.8 P3
