### ISSUE TITLE
Backtick methods / types don't show up in intellisense.

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#456]
If you create a type which is backticked and contains spaces etc. in it, intellisense does not show it e.g.

```fsharp
type Foo =
| ``Frodo``
| ``Bar is the best!``
```

![backtick](https://cloud.githubusercontent.com/assets/1781813/7688723/dda0c232-fd9e-11e4-9c71-e2b100f65ee0.png)

**Comment by latkin** [comment]
Same as https://github.com/Microsoft/visualfsharp/issues/97?

**Comment by isaacabraham** [comment]
Doh. Searched for backtick in the titles. Sorry.
