### ISSUE TITLE
FSharpFunc.FromConverter disappeared from FSharp.Core in VS 15.6, but still shows in IntelliSense, existing projects in 4.4.0 or 4.4.3 do not compile

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#4569]
The function `Core.FSharpFunc.FromConverter` is a part of FSharp.Core, and [is still available according to the documentation](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/fsharpfunc.fromconverter%5B%27t,%27u%5D-method-%5Bfsharp%5D), however, when compiling in the public release of 15.6.2 Visual Studio + F# (no Preview), this throws the error that it doesn't exist.

At the same time, the function appears available according to the editor environment.
 
### Repro steps

Repro code;

```fsharp
module TestConverter =
    open System

    type private Wrappers<'X> private () =

        static member Wrap1<'T1>(f: Converter<'T1,'X>) :
            'T1 -> 'X =
            Core.FSharpFunc.FromConverter f
```

### Expected behavior

The above code should compile as it used to do.

### Actual behavior

The code doesn't compile. Note that:

* The IntelliSense shows the member as available:
![image](https://user-images.githubusercontent.com/16015770/37568215-40b1557c-2ad2-11e8-8c9a-c87581ee462e.png)

* This compiled just fine in Visual Studio 15.5.x (my build server still compiles this, which wasn't updated)

### Known workarounds

I don't know of a workaround, while a similar issue appears to exist for NetStandard 2.0, that post actually explains that it _is_ available in FSharp.Core, but not in NetStandard and that no suitable workaround exists for cross-targeting.

### Related information 

I noticed it happening after the most recent update to 15.6.2, but it is possible it happened already on earlier versions of 15.6 of Visual Studio.

I tried searching for changes regarding this function, but couldn't find it. This suggests it may have gotten hidden by some other means at a higher level perhaps?

Tested with:

* FSharp.Core 4.4.0.0, 4.4.1.0, 4.4.3.0
* .NET 4.6, 4.7
* Visual Studio 15.6.2 Professional edition
* (update issue) Every Preview edition since, incl 15.7.0 Preview 1

**Comment by cartermp** [comment]
@dsyme It shows you as having last touched the code for the type, though it was just for signature file alignment and it doesn't look like anything changed there. Any ideas?

**Comment by abelbraaksma** [comment]
FWIW, I tested it on the latest Preview editions, incl. 15.6.0 Preview 7. Error is the same and it also happens in FSI, same error there.

**Comment by abelbraaksma** [comment]
@cartermp, @dsyme, What is odd is that the signature is still there in the `FSharp.Core.dll` library as a public method. In fact, it is still the same library from 2016, so nothing changed in the core library, it's just that the compiler doesn't find it.

![image](https://user-images.githubusercontent.com/16015770/37591395-afbf709a-2b6b-11e8-94d3-0fe31fe88b7e.png)

That explains perhaps why it appears in IntelliSense, yet somehow the compiler can't find it. Which could mean that other functions/methods in public libraries or the Core lib may also have become hidden.

Shouldn't the surface area tests capture this? Or aren't they testing the signature lookup resolution? If not, perhaps we should update those tests to include compiler method resolution as well, to prevent this from happening.

**Comment by dsyme** [comment]
I can repro this. This is likely because of the 15.3 normalization of ``FSharpFunc<A,B>`` to be equal to function type ``A -> B`` (same issue as tuple types `.Item1` etc.).  Annoying there is no test for FuncConverter in FSharp.Core.UnitTests....

The method will still be visible to C# code, which is how it's mostly used.

**Comment by abelbraaksma** [comment]
Thanks!

**Comment by bizmonger** [comment]
I'm experiencing the same issue on my Xamarin Android project (FSharp.Core 4.6.2)

FromConverter and ToConverter are not exposed.
The only methos that's exposed is  InvokeFast.

**Comment by KevinRansom** [comment]
@bizmonger 

I just fetched the fsharp.core package from nuget these are the public signatures for the net45 .dll.  The netstandard1.6 version of the .dll does not have those APIs because netstandard1.6 does not support System.Converter.
````
[Serializable, AbstractClass, CompilationMapping(SourceConstructFlags.ObjectType)]
public abstract class FSharpFunc<T, TResult>
{
    // Methods
    [DebuggerHidden]
    public FSharpFunc();
    public static FSharpFunc<T, TResult> FromConverter(Converter<T, TResult> converter);
    public abstract override TResult Invoke(T func);
    public static V InvokeFast<V>(FSharpFunc<T, FSharpFunc<TResult, V>> func, T arg1, TResult arg2);
    public static W InvokeFast<V, W>(FSharpFunc<T, FSharpFunc<TResult, FSharpFunc<V, W>>> func, T arg1, TResult arg2, V arg3);
    public static X InvokeFast<V, W, X>(FSharpFunc<T, FSharpFunc<TResult, FSharpFunc<V, FSharpFunc<W, X>>>> func, T arg1, TResult arg2, V arg3, W arg4);
    public static Y InvokeFast<V, W, X, Y>(FSharpFunc<T, FSharpFunc<TResult, FSharpFunc<V, FSharpFunc<W, FSharpFunc<X, Y>>>>> func, T arg1, TResult arg2, V arg3, W arg4, X arg5);
    public static implicit operator Converter<T, TResult>(FSharpFunc<T, TResult> func);
    internal static implicit operator Func<T, TResult>(FSharpFunc<T, TResult> func);
    public static implicit operator FSharpFunc<T, TResult>(Converter<T, TResult> converter);
    internal static implicit operator FSharpFunc<T, TResult>(Func<T, TResult> converter);
    public static Converter<T, TResult> ToConverter(FSharpFunc<T, TResult> func);
}
````

**Comment by Alxandr** [comment]
So there is no way to create a `FSharpFunc` on .NET core?

**Comment by cartermp** [comment]
@Alxandr If you wait for .NET Core 3 then there will be.

**Comment by Alxandr** [comment]
I figured out I could just subclass fsharpfunc. Made one that takes a system.func, plus an extension method.
