### ISSUE TITLE
Razor services crash in VS2017 15.6.2

### ISSUE THREAD

**Issue by Liminiens** [Microsoft/visualfsharp#4570]
It seems like that some part of razor services in visual studio stops working when any of .cshtml files is opened in fsproj project.

#### Repro steps

1. dotnet new mvc --lang F#
2. Open generated project in VS
3. VS internal error window appears:
![devenv_2018-03-18_21-07-02](https://user-images.githubusercontent.com/10695322/37569238-57a94eec-2af0-11e8-850f-6d3894e69b1a.png)

![2018-03-18_21-16-29](https://user-images.githubusercontent.com/10695322/37569326-b622a36e-2af1-11e8-9c26-bffb816b3bb4.gif)

Generated project:
[Repro.zip](https://github.com/Microsoft/visualfsharp/files/1822993/Repro.zip)

#### Expected behavior

There is razor-specific code highlighting, intellisence in cshtml, etc.

#### Actual behavior

Internal error in VS

Activity log:
[ActivityLog.txt](https://github.com/Microsoft/visualfsharp/files/1823001/ActivityLog.txt)

The important part is this, I think:

```xml
  <entry>
    <record>1864</record>
    <time>2018/03/18 13:10:08.823</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   
at Microsoft.VisualStudio.Html.Package.CBM.CBMWorkItemDispatcher`1.Dispatch(ITextBuffer textBuffer, Func`1 toExecute, Action`1 callback)&#x000D;&#x000A;   
at Microsoft.VisualStudio.Html.Package.Razor.RazorImportsProvider.Microsoft.Html.Editor.ContainedLanguage.Razor.Def.IRazorImportsProvider.GetImportsAsync(ITextBuffer textBuffer, Func`1 toExecute, Action`1 callback)&#x000D;&#x000A;  
 at Microsoft.VisualStudio.Web.Razor.Implementation.Shims.RazorCodeGenerator.DispatchGetRazorNamespacesWorkItem()&#x000D;&#x000A;   
at Microsoft.VisualStudio.Web.Razor.Implementation.Shims.RazorCodeGenerator.&lt;.ctor&gt;b__24_0()&#x000D;&#x000A;   
at Microsoft.Web.Editor.Utility.GuardedOperations.InvokeExtensionPoint(Object errorSource, Action action)
</description>
  </entry>
```

#### Known workarounds

No workarounds

#### Related information 
OS:

> Microsoft Windows [Version 10.0.16299.309]

VS Info:

> Microsoft Visual Studio Enterprise 2017
> Version 15.6.2
> VisualStudio.15.Release/15.6.2+27428.2005
> Microsoft .NET Framework
> Version 4.7.02556
> 
> Installed Version: Enterprise
> 
> Architecture Diagrams and Analysis Tools   00369-90000-00000-AA906
> Microsoft Architecture Diagrams and Analysis Tools
> 
> Visual C++ 2017   00369-90000-00000-AA906
> Microsoft Visual C++ 2017
> 
> Visual F# Tools 10.1 for F# 4.1   00369-90000-00000-AA906
> Microsoft Visual F# Tools 10.1 for F# 4.1
> 
> Application Insights Tools for Visual Studio Package   8.11.10212.1
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2017   15.0.40301.0
> ASP.NET and Web Tools 2017
> 
> ASP.NET Core Razor Language Services   1.0
> Provides languages services for ASP.NET Core Razor.
> 
> ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
> For additional information, visit https://www.asp.net/
> 
> Azure App Service Tools v3.0.0   15.0.40215.0
> Azure App Service Tools v3.0.0
> 
> Azure Functions and Web Jobs Tools   15.0.40215.0
> Azure Functions and Web Jobs Tools
> 
> C# Tools   2.7.0-beta3-62707-11. Commit Hash: 75dfc9b33ed624dff3985c7435c902c3c58c0e5c
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Common Azure Tools   1.10
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2
> 
> Microsoft Continuous Delivery Tools for Visual Studio   0.3
> Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Visual C++ Wizards   1.0
> Microsoft Visual C++ Wizards
> 
> Microsoft Visual Studio Tools for Containers   1.1
> Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.
> 
> Microsoft Visual Studio VC Package   1.0
> Microsoft Visual Studio VC Package
> 
> Node.js Tools   1.4.11027.3
> Adds support for developing and debugging Node.js apps in Visual Studio
> 
> NuGet Package Manager   4.6.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> ProjectServicesPackage Extension   1.0
> ProjectServicesPackage Visual Studio Extension Detailed Info
> 
> Snapshot Debugging Extension   1.0
> Snapshot Debugging Visual Studio Extension Detailed Info
> 
> SQL Server Data Tools   15.1.61801.210
> Microsoft SQL Server Data Tools
> 
> TypeScript Tools   15.6.20202.3
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Basic Tools   2.7.0-beta3-62707-11. Commit Hash: 75dfc9b33ed624dff3985c7435c902c3c58c0e5c
> Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Visual C++ for Linux Development   1.0.8
> Visual C++ for Linux Development
> 
> Visual Studio Code Debug Adapter Host Package   1.0
> Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
> 
> Visual Studio Tools for CMake   1.0
> Visual Studio Tools for CMake

dotnet sdk version:

> 2.1.101

**Comment by cartermp** [comment]
Calling upon @eilon to see if this should be routed over to ASP.NET side of things since the stack trace is in the web editor.

I wouldn't expect to see anything representing a full Razor experience (e.g., `@model` support and IntelliSense for that) given that Razor for ASP.NET Core is effectively C# only, but the error dialog should definitely not be popping up.

**Comment by Eilon** [comment]
This looks like "old" Razor to me, from MVC 5.x, as opposed to Razor in ASP.NET Core) but I'm adding @rynowak and @jodavis who can confirm. Then we can figure out where this bug goes.

**Comment by rynowak** [comment]
This is actually similar to an issue I've been looking of late. The editor decides to open the file as System.Web Razor, but then the contained language service decides to create a dotnet Core contained language implementation.

**Comment by Eilon** [comment]
Thanks @rynowak . Any idea where the investigation should go? Presumably this is the wrong repo here, but I'm not sure where is correct.

**Comment by Eilon** [comment]
@rynowak who can move the bug there?

**Comment by rynowak** [comment]
Logged internal TFS issue 587514

**Comment by cartermp** [comment]
Thanks @rynowak

**Comment by Spongman** [comment]
I'm seeing the same intermittent error, razor, c#, vs2019 v16.3.2:

````
System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.VisualStudio.Web.Interop.IVsClientBuildManagerService.DispatchUserWorkItem(IVsClientBuildManagerEventSink sink)
   at Microsoft.WebTools.Languages.Html.VS.CBM.CBMWorkItemDispatcher`1.Dispatch(ITextBuffer textBuffer, Func`1 toExecute, Action`1 callback)
   at Microsoft.WebTools.Languages.Html.VS.Razor.RazorImportsProvider.Microsoft.WebTools.Languages.Html.Editor.ContainedLanguage.Razor.Def.IRazorImportsProvider.GetImportsAsync(ITextBuffer textBuffer, Func`1 toExecute, Action`1 callback)
   at Microsoft.WebTools.Languages.Razor.V3.RazorCodeGenerator.DispatchGetRazorNamespacesWorkItem()
   at Microsoft.WebTools.Languages.Razor.V3.RazorCodeGenerator.&lt;&gt;c__DisplayClass24_0.&lt;InitializeAsync&gt;b__1()
   at Microsoft.WebTools.Languages.Shared.Editor.Utility.GuardedOperations.InvokeExtensionPoint(Object errorSource, Action action)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
````

**Comment by abelbraaksma** [comment]
@spongman, you probably want to report that to the c# team, or report a vs bug.
