### ISSUE TITLE
No framework templates for F# after installing F# desktop support

### ISSUE THREAD

**Issue by cocogorilla** [Microsoft/visualfsharp#4571]
See title.  Latest everything vs 2017 as of date of post.  Uninstalled F# desktop support, Reinstalled F# desktop support.  Only .NET Core and .NET Standard templates are available.  .NET Framework templates are not available.

Yes, .NET 4.5-4.7.1 are installed with SDK.

Do I have to install VS 2015 and run it alongside VS 2017 in order to access a simple F# class library targeting .net 4.6?

**Comment by cartermp** [comment]
@brettfo can you take a look? I’m not aware of any changes to the desktop templates component for 15.6.* nor any setup engine bugs

**Comment by cartermp** [comment]
Also as a workaround for now @cocogorilla you can retarget a netstandard project file to net46 to have it specifically target .NET Framework.

**Comment by cocogorilla** [comment]
Sorry guys, we can delete this issue.  I think I spent an hour being an idiot.  To be honest, I was looking for a framework folder in the dialog and totally confused that all I saw was core and standard.  However I realize now those are sub categories... if I select the parent category "Visual F#" then the framework templates do appear.

Again, sorry for being an idiot.  It happens sometimes.

**Comment by realvictorprm** [comment]
It's all fine @cocogorilla 👍

**Comment by cartermp** [comment]
No worries!

**Comment by brettfo** [comment]
I've been hit by this, too.  It might be worth talking about placing the framework templates in their own category to make them easier to find.  Thoughts @cartermp and @KevinRansom?

**Comment by cartermp** [comment]
I think that’s a splendid idea. How about “Windows Desktop” as a
trial name?

On Mon, Mar 19, 2018, at 09:33, Brett V. Forsgren wrote:
> I've been hit by this, too.  It might be worth talking about placing
> the framework templates in their own category to make them easier to
> find.  Thoughts @cartermp[1] and @KevinRansom[2]?> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[3], or mute the thread[4].> 


Links:

  1. https://github.com/cartermp
  2. https://github.com/kevinransom
  3. https://github.com/Microsoft/visualfsharp/issues/4571#issuecomment-374276895

**Comment by KevinRansom** [comment]
C# uses "Windows Classic Desktop" as the category name.

**Comment by brettfo** [comment]
I've filed #4578 to track this.
