### ISSUE TITLE
Recent Visual Studio editions 15.6.2+ start spinning 90% CPU forever, on large projects with lots of errors

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#4574]
I left my Visual Studio open during the night and when I got back, the whole machine was sluggish. I saw this in the task manager, slowly going up further (and spiking from 60-90%):

![image](https://user-images.githubusercontent.com/16015770/37590368-586f73ec-2b68-11e8-82ac-a2029f06724b.png)

With previous versions, memory used to be an issue, but this is the first time I saw the processor spinning.

### Repro steps

Not sure how to repro consistently since I try to prevent this behavior, but it happened during a large refactoring session, where approx. 50 files showed perhaps thousands of errors and several hundreds other files and a dozen or so projects in the same solution compiled fine.

I also couldn't open the debugger to find out what was spinning, or hook up a profiler, the system was too sluggish for that.

### Expected behavior

When in rest, the developer environment should be in rest.

### Actual behavior

CPU spinning / overload.

### Known workarounds

For a few years my modus operandi has been to work for a few hours on a large project and then restart Visual Studio. That used to be necessary because of memory congestion. This is the first time I see it happen with CPU congestion. 

### Related information 

In the past I have seen many occasions where the CPU took 100% of a single processor and VS became sluggish or completely unresponsive. It is possible that recent changes allowed for better multi-threading behavior. 

It seems reasonable that whatever kept a single thread running forever in the past, now runs in its own range of threads, leaving the system more responsive than before, but it doesn't finish its task.

The good news is that it was still somewhat responsive and I could close it, even though it took two minutes or so to quit, showing the unload-screen for a long time:

![image](https://user-images.githubusercontent.com/16015770/37590734-723f21d6-2b69-11e8-8de4-c25fa2adb789.png)

* Windows 7, all recent updates and .NET versions available
* Visual Studio 15.6.2 Professional, possible also other 15.6.x versions or previews
* I'm not sure, but my guess is the large amount of errors has something to do with it: I had the same project open in a compilable state in a different instance, and that didn't start spinning with high CPU

_PS: I would appreciate any suggestions on how to give more info on this, or to create a memory dump, or whatever, so that we can at least find out what method is looping. Also, if anybody else has seen this behavior, pointers / suggestions are welcome._

**Comment by cartermp** [comment]
You can take a memory dump in Task Manager (right-click on the devenv.exe process and select "Create Dump File"), which will then save the file in AppData (the location is shown in the UI).

You'll probably need to upload it to a file share, though, since it will be quite large.

My suspicion is that you're in a "loop of death" where FCS data is getting flushed -> added -> flushed -> added forever and ever. A good course of action would be:

1. Turn off in-memory cross-project references
2. Turn off the unused opens analyzer (perf fix for it is only in nightlies)
3. Set the project cache size to be far lower (it used to be 3 in VS 2015)

If that doesn't help, then the answer is, "we need to do the hardcore perf work in the language service necessary to support this scenario".

**Comment by abelbraaksma** [comment]
@cartermp , thanks. I have these settings, which means cache-size was at your suggested setting, I'll try by removing that checkmark:

![image](https://user-images.githubusercontent.com/16015770/37608330-89a72bd0-2b9a-11e8-949f-8e690af793e7.png)

Not sure how to turn off the unused-opens analyzer (that used to be an option in FSharp Powertools, I believe), but it is certainly on (unused opens are grey).

**Comment by majocha** [comment]
@abelbraaksma unused opens setting is under Text Editor > F# > Code Fixes

**Comment by abelbraaksma** [comment]
@majocha, thanks, but that looks to me like automatic code fixes, I never thought that was the analyzer: 

![image](https://user-images.githubusercontent.com/16015770/37611999-37022c5e-2ba4-11e8-96c1-736830a6a7fd.png)

**Comment by cartermp** [comment]
@abelbraaksm The 1st, 3rd, and 4th all analyze code; though it's only when a document is changed so turning these off is less likely to be a cause and more of a, "Let's see if more advanced features are related at all" kind of thing.

**Comment by abelbraaksma** [comment]
@cartermp, I have turned the 3rd (unused open statements) off. The others are essentially too valuable while coding, especially the one for unused values. That analyzer saved my world several times ;).

I've kept the new settings for a while and left VS open. While after some time it gets slower and slower in the editor, VS as a whole doesn't spin like crazy anymore. Maybe it was a fluke.

Though it keeps being necessary to open/close VS after a couple of hours work. But it has been like that since VS2017 came around anyway. It is generally much faster than VS2015, but in my experience, after some time, typing and syntax coloring starts to get sluggish. 

It's essentially fastest (searching is instant, typing and coloring is fast, compiling is fast)  right after an upgrade, which suggests that temp files or an ever growing browse file (don't know where/what it is in F#, but in C++ that used to be a thing you needed to remove every now and then). Project > Clean doesn't erase these files I think (at least, it doesn't speed anything up). The performance drop is large: for instance, compiling a large project takes, say 30 seconds, but after a few weeks it takes 2 minutes. Same for searching: from almost instant, to dozens of seconds after a while. Restarting VS doesn't solve this.

I'd be grateful if someone can tell me what files the setup cleans, so I can do this maintenance by hand.

**Comment by cartermp** [comment]
Unfortunately, I don't really know why it would slow down dramatically like that after a few weeks. I'm not aware of something like a large number of temp files affecting F# performance all-up. This would suggest that the way we read info off disk is getting affected for you, especially since build times are dropping by a lot. @dsyme @KevinRansom any thoughts?

**Comment by KevinRansom** [comment]
@abelbraaksma I have no idea why VS should be fast after an update and then degrade over time.   Does updating the nightly, have the same affect, or is it just a full VS update where you see this effect?

**Comment by dsyme** [comment]
@abelbraaksma I'm closing this since we don't have a specific repro, please reopen a new issue if you have repro steps, thanks

**Comment by abelbraaksma** [comment]
@dsyme I agree. It's difficult to repro something like this. While I continue to have performance troubles, there's another issue I raised,  with a repro, that has more detail to it. Let's keep this one closed.
