### ISSUE TITLE
VS 2017 15.6.x build fails (while 15.5.7 succeeds) when FSharpLint.MSBuild.targets exists in the fsproj

### ISSUE THREAD

**Issue by nethatix** [Microsoft/visualfsharp#4585]
Visual Studio 2017 tools bundled with the version of **15.6.x** lost the ability to build fsproj with the target 
**FSharpLint.MSBuild.targets**. Tools bundled with the version of **15.5.7 build ok**.

15.6.x Build Error:

> error : TypeLoadException: Could not load type 'Microsoft.FSharp.Control.CommonExtensions+SubscribeToObservable@1693' from assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

Note the attached reduced solution shows the error but it appears to produce successful dll output. That is not the case with our projects. They fail with the above error. 

_A side by side installed visual studio version of 15.5.7 in the same machine builds fine._
[testsln.zip](https://github.com/Microsoft/visualfsharp/files/1828933/testsln.zip)

#### Repro steps

I've attached a minimum project to demonstrate this error when re-building the sln with the 15.6.x version with the output error.

```
1>------ Build started: Project: test, Configuration: Debug Any CPU ------
1>	C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\fsc.exe -o:obj\Debug\test.dll -g --debug:full --noframework --define:DEBUG --define:TRACE --doc:bin\Debug\Test.XML --optimize- --tailcalls- -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\mscorlib.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Core.dll" -r:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.dll" -r:D:\temp\test\packages\System.ValueTuple.4.4.0\lib\net461\System.ValueTuple.dll --target:library --warn:3 --warnaserror:76 --vserrors --utf8output --fullpaths --flaterrors --subsystemversion:6.00 --highentropyva+ "C:\Users\Mario\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.fs" AssemblyInfo.fs test.fs 
1>	test -> D:\temp\test\bin\Debug\test.dll
1>D:\temp\test\test.fsproj: error : TypeLoadException: Could not load type 'Microsoft.FSharp.Control.CommonExtensions+SubscribeToObservable@1693' from assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
1>   at FSharpLint.MSBuild.AppDomain.LintRunner.add_Failure(FailureEventHandler handler)
1>   at <StartupCode$FSharpLint-MSBuild>.$FSharpLintTask.Lint@26.Invoke(FailureEventHandler eventDelegate)
1>   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.CreateEvent@341.System-IObservable`1-Subscribe(IObserver`1 r)
1>   at FSharpLint.MSBuild.Proxy.Lint()
1>   at FSharpLint.MSBuild.FSharpLintTask.Execute()
1>
1>Done building project "test.fsproj" -- FAILED.
1>
1>Build FAILED.

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

* Operating system: Windows 10 (latest)
* .NET Runtime 4.6.1
* Editing Tools 15.6.x

**Comment by cartermp** [comment]
@nethatix Sorry for no reply here, do you still see this? My guess is that the tool has not been updated to account for newer FSharp.Core versions, but it's a hunch.

**Comment by nethatix** [comment]
@cartermp Indeed. It has been resolved!
