### ISSUE TITLE
Resx files are not working for fsharp project

### ISSUE THREAD

**Issue by nguerrera** [Microsoft/visualfsharp#4591]
_From @Lanayx on February 28, 2018 15:1_

## Steps to reproduce
1. Create empty F# console project (.NET Core)
2. Add `type Test = Test of string`
3. Add Resources folder
4. Add Resource `Test.en.resx` to Resources folder
5. Build project

## Expected  behavior
VS build works
`dotnet build` works

## Actual behavior
VS build works
`dotnet build` doesn't work. 
resources.cs file with fsharp content is created and CS compiler errors are shown

## Environment data
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

_Copied from original issue: dotnet/cli#8697_

**Comment by nguerrera** [comment]
_From @livarcocc on February 28, 2018 17:49_

This is not currently supported in MSBuild core, but is supported in full MSBuild.

I believe this issue is a duplicate of https://github.com/Microsoft/msbuild/issues/2272.

**Comment by nguerrera** [comment]
_From @Lanayx on February 28, 2018 19:7_

Looks like the issue is only with F#, if I do the same thing in C#, it works fine. The main problem is that MyProject.resources.cs file is generated for both cases and C# compiler is used for both cases, while .fs file and F# compiler should be used for F# project.

**Comment by nguerrera** [comment]
_From @livarcocc on February 28, 2018 19:38_

@KevinRansom can you take a look?

@nguerrera just corrected me. We do support resx files. MSBuild just doesn't support non-string assets in it. But that does not look like the issue here.

**Comment by nguerrera** [comment]
_From @Lanayx on February 28, 2018 19:39_

Just checked Visual Basic, it has exactly the same issue. Only C# version works fine.

**Comment by nguerrera** [comment]
_From @peterhuene on March 15, 2018 1:16_

I see this working in master:

```
$ mkdir repro && cd repro
```
```
$ dotnet new console -lang f#
```
```
$ cat <<EOF > Program.fs
open System
open System.Resources

[<EntryPoint>]
let main argv =
    Console.WriteLine(ResourceManager("repro.Strings", System.Reflection.Assembly.GetCallingAssembly()).GetObject("HelloWorld"))
    0
EOF
```
```
$ cat <<EOF > Strings.resx
<?xml version="1.0" encoding="utf-8"?>
<root>
  <data name="HelloWorld" xml:space="preserve">
    <value>Hello World!</value>
  </data>
</root>
EOF
```
```
$ dotnet run
Hello World!
```

I don't think the F# SDK currently supports strongly-typed resources (hence the manual use of `ResourceManager` above).

**Comment by nguerrera** [comment]
_From @Lanayx on March 15, 2018 3:55_

It was supported when I created the issue if building from VS.

**Comment by nguerrera** [comment]
_From @livarcocc on March 15, 2018 4:10_

@KevinRansom to comment.

**Comment by nguerrera** [comment]
This is a duplicate of https://github.com/dotnet/sdk/issues/1748

It is now fixed. The fix will be in 2.1.102 which will ship very soon and be delivered with a VS 15.6.x update.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nguerrera** [comment]
_From @Lanayx on March 21, 2018 7:12_

Tried the latest 15.6.3 update (dotnet version 2.1.102) - the error is different:
```
Error writing code fragment: System.Exception: Language name must be F#
   at Microsoft.FSharp.Build.WriteCodeFragment.Microsoft-Build-Framework-ITask-Execute()
Build FAILED.
```
But the result is the same, it still doesn't work... Please reopen the issue.

**Comment by nguerrera** [comment]
_From @livarcocc on March 21, 2018 16:7_

@nguerrera can you please take a look and if necessary re-activate the SDK issue?

**Comment by brettfo** [comment]
I originally tried to add this to MSBuild in Microsoft/MSBuild#2585 but was told to do it in the F# sources.

Speaking with @KevinRansom we can add a fallback to generate C# from our task when necessary.
