### ISSUE TITLE
Ctrl+ Enter should use same indentation of block, not of line above

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#460]
f# behaviour: same indentation of line above

![fsharp](https://cloud.githubusercontent.com/assets/5943573/7689649/b9daa228-fd62-11e4-8832-c9c514de70bf.gif)

c# behaviour: indentation of same block

![csharp](https://cloud.githubusercontent.com/assets/147243/7699744/72c5ccb0-fe1a-11e4-976f-fa7d645e18f5.gif)

from @latkin 
> VS command to handle is Edit.LineOpenAbove

**Comment by Happypig375** [comment]
Still not fixed in VS2019. Why was this closed?
