### ISSUE TITLE
Find In Files blocks the enviroment

### ISSUE THREAD

**Issue by Tbd19** [Microsoft/visualfsharp#4605]
I have a .NET web solution with only one project. The project uses the Telerik scripts(256 + 134 + 836 files) and styles (153 + 19*14 files). (The files are all minified version)

Every time I try to find a text in all the files (No type file is provided) and Visual Studio is looking into the scripts/styles file and get stuck on one of the files. After that the only way to continue working is End task of VS.

If the text I want to look is complicated and exists only in the cs files then the VS does not gets stuck. But If I look for a text that exists also in the scripts or the styles then the VS gets stuck.

I should also mention that I also have as extension Resharper and the Break or Ctrl+Break does not work.

**Comment by ScottHutchinson** [comment]
There is nothing in your description to suggest that this is an issue specific to F#, so you might have posted this in the wrong place. It sounds more like a problem with Visual Studio, in which case you could report it in VS using Help...Send Feedback...Report a Problem. It would also be very helpful if you could reproduce the problem without any Telerik or Resharper extensions installed.

**Comment by Tbd19** [comment]
Sorry I assumed this is VS git

**Comment by cartermp** [comment]
@Tbd19 no worries! As @ScottHutchinson mentioned, you can use the Report a Problem tool in VS. There is also an option to take a memory dump, which I'd recommend because it will collect diagnostic information that can help with debugging.
