### ISSUE TITLE
Compiler emits FS0988 warning with a reference to non existing location in source file

### ISSUE THREAD

**Issue by mstyura** [Microsoft/visualfsharp#461]
Description: In some cases compiler emits `FS0988 (Main module of program is empty: nothing will happen when it is run)` warning and gives a reference to non existing code location. In "wrong" cases location is always `(1, 81)`, even if there is no such location in source file.

Repro Steps: 
Compile the following file

``` fsharp
namespace MyNamespace1

module MyModule1 =
    let irrelevant = 10
```

Expected: 
Compiler emits warning `FS0988` pointing at the end of the last module in file `MyModule1`

Actual: 
Compiler emits warning `FS0988` pointing at location `(1, 81)`

Severity: Cosmetic - for this particular warning it is just a matter of taste to have a correct source code location, but might be useful when navigation to warning/error location is used in some editors.

Version: 12514308c79453bac38dea11e0e3c549619a79dc

Likely Cause: [build.fs#L3054](https://github.com/Microsoft/visualfsharp/blob/12514308c79453bac38dea11e0e3c549619a79dc/src/fsharp/build.fs#L3054)

Workaround: no workaround

**Comment by enricosada** [comment]
nice bug report @mstyura !

**Comment by aloisdg** [comment]
I got this one in a F# dotnet core project. Is there a known workaround since last year?

**Comment by forki** [comment]
fixed in https://github.com/Microsoft/visualfsharp/pull/1852
