### ISSUE TITLE
Newly added signature file items are given "None" as action

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#4610]
1. Create new F# Library for .NET Standard
2. Right click add signature file `Library.fsi`

### Expected

The item is added to the project file as:

    <Compile Include="Library.fsi" />
    <Compile Include="Library.fs" />

### Actual
You get this:

    <None Include="Library.fsi" />
    <Compile Include="Library.fs" />

**Comment by cartermp** [comment]
@TIHan was this something you had mentioned a while back?

**Comment by TIHan** [comment]
Yes, we resolved this in 15.7 already. https://github.com/dotnet/project-system/pull/3208
