### ISSUE TITLE
Values of private mutable variables are lost if modified from a base class constructor

### ISSUE THREAD

**Issue by bbenoist** [Microsoft/visualfsharp#463]
Hi,

I am suffering an issue which prevents me from using F# on a .NET plugin for a third-party software.

To plug my code into a third-party library, I need to inherit a specific base class. This base class forces me to implement a method which will be directly called from its constructor :scream: .

The third-party code:
```csharp
namespace ThirdPartyLib
{
    public abstract class ThirdPartyBaseClass
    {
        protected ThirdPartyBaseClass()
        {
            CalledFromConstructor();
        }

        protected abstract void CalledFromConstructor();
    }
}
```

A C# plugin:
```csharp
namespace MyCSLib
{
    using ThirdPartyLib;

    public class MyCSClass : ThirdPartyBaseClass
    {
        private bool _myValue = false;

        protected override void CalledFromConstructor()
        {
            _myValue = true;
        }

        public bool MyValue
        {
            get { return _myValue; }
        }
    }
}
```

A F# plugin:
```fsharp
namespace MyLib

open ThirdPartyLib

type MyClass() = 
    inherit ThirdPartyBaseClass()

    let mutable myValuePrivate = false

    override x.CalledFromConstructor() = myValuePrivate <- true

    member x.MyValue with get() = myValuePrivate
```

The problem here is that while the C# code keeps the modified value of `myValuePrivate`, the F# one equals to false when accessed with `MyValue`.

Here is a corresponding unit test:

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using MyCSLib;
using MyLib;

namespace ThirdPartyApp
{
    [TestClass]
    public class UnitTest
    {
        [TestMethod]
        public void TestFSharp()
        {
            var myClass = new MyClass();
            Assert.IsTrue(myClass.MyValue);
        }

        [TestMethod]
        public void TestCSharp()
        {
            var myCSClass = new MyCSClass();
            Assert.IsTrue(myCSClass.MyValue);
        }
    }
}
```

Does someone know why both plugin implementations are not reacting the same way?

A VS2013 solution demonstrating the problem can be cloned from https://github.com/bbenoist/fs-private-inheritance-bug . Feel free to submit your solution as a PR.

**Comment by bbenoist** [comment]
After reading "[Explicit Fields: The val Keyword (F#)](https://msdn.microsoft.com/en-us/library/dd469494.aspx)", I found a fix (https://github.com/bbenoist/fs-private-inheritance-bug/pull/1) by using the `val` keyword instead of `let` in the F# code:

```fsharp
namespace MyLib

open ThirdPartyLib

type MyClass() = 
    inherit ThirdPartyBaseClass()

    [<DefaultValue(false)>] val mutable myValuePrivate : bool

    override x.CalledFromConstructor() = x.myValuePrivate <- true

    member x.MyValue with get() = x.myValuePrivate
```

What's wrong with the version using the `let` instruction?

**Comment by FunctionalFirst** [comment]
The `let` binding is part of the primary constructor. That is, this F#
````f#
type A() =
    inherit B()
    let x = 1
````
is logically equivalent to this C#
````c#
class A : B {
    int x;
    public A() : base() {
        x = 1;
    }
}
````

**Comment by latkin** [comment]
Calling virtual methods from constructors is a notorious anti-pattern, for exactly this reason.  Many static analysis tools will warn you not to do it, see https://msdn.microsoft.com/en-us/library/ms182331.aspx and http://stackoverflow.com/questions/119506/virtual-member-call-in-a-constructor.

In C#, field initialization is done *before* invoking the base ctor, so in this particular problem is avoided.  F# and VB do the opposite - the base ctor is invoked first, *then* fields are initialized.  There are advantages to both approaches.  In F#/VB is it safe and legal to access base class members when initializing a derived class:

```csharp
    public abstract class ThirdPartyBaseClass
    {
        protected int baseField = 42;
        public int BaseProp { get { return baseField; } }
    }
```
```fsharp
type MyClass() = 
    inherit ThirdPartyBaseClass()
    let myValuePrivate = base.BaseProp + 10
    member __.MyValue = myValuePrivate

let x = MyClass()
printfn "%A" x.MyValue  // prints 52 as expected
```

Since C# runs initializers before calling base ctor, it is illegal to access base members during field initialization:

```csharp
    public class DerivedClass : ThirdPartyBaseClass
    {
        // error: keyword 'base' is not available in the current context
        private int myValuePrivate = base.BaseProp + 10;
        public int MyValue { get { return myValuePrivate; } }
    }
```

**Comment by bbenoist** [comment]
@FunctionalFirst @latkin 
Thank you for the explanations! I now clearly see what was the problem with my understanding.

@latkin 
> Calling virtual methods from constructors is a notorious anti-pattern, for exactly this reason. Many static analysis tools will warn you not to do it, see https://msdn.microsoft.com/en-us/library/ms182331.aspx and http://stackoverflow.com/questions/119506/virtual-member-call-in-a-constructor.

I totally agree but am unfortunately not responsible of the proprietary .NET software which executes my code. Thus, I have to deal with their poor design choices.

> In C#, field initialization is done before invoking the base ctor, so in this particular case the problem you are seeing is avoided. F# and VB do the opposite - the base ctor is invoked first, then fields are initialized. There are advantages to both approaches. In F#/VB is it safe and legal to access base class members when initializing a derived class.

I was not aware of such differences, thanks for the info.
