### ISSUE TITLE
method calls on structs almost always make a spurious copy

### ISSUE THREAD

**Issue by kulibali** [Microsoft/visualfsharp#464]
The F# compiler (both 3 and 4) boxes structs when calling struct methods in almost every case.  This results in unnecessary copying overhead, and if the struct method mutates its data, the changes are lost.

The following sample code demonstrates 6 scenarios:

- *test1*: calling a tupled method on a variable makes a copy of the struct and calls the method on the copy (it doesn't even actually box it, just makes a spurious copy)
- *test2*: calling a curried method on a variable does the same as in test1
- *test3*: calling a tupled method on an array element does NOT box the array element, but calls the method with a pointer to the element.  This behavior is what I would expect, and matches what C# does.
- *test4*: calling a curried method on an array element boxes the array element and calls the method on the boxed copy.
- *test5*: upcasting a struct to an interface variable boxes the struct.  This behavior is what I would expect.
- *test6*: upcasting the struct within a member access expression also boxes the struct.  This is different from what C# does -- it calls the interface method on the original struct.

So in 4 out of 6 cases, the F# compiler makes a spurious copy of the struct.

    type IFoo =
        abstract member Step3 : int -> unit

    type Foo =
        struct
            val mutable LastFrame : int
            val mutable Lifetime  : float32

            member this.Step1 (dt:float32) =
                this.Lifetime <- this.Lifetime + dt

            member this.Step2 (frame:int) (dt:float32) =
                this.LastFrame <- frame
                this.Lifetime <- this.Lifetime + dt

            interface IFoo with
                member this.Step3 frame = this.LastFrame <- frame
        end

    type Seg(n:int) =
        class
            let foos = Array.zeroCreate<Foo> n

            member __.Foos = foos
        end

    let test1() =
        let foo = Foo()
        let dt = 0.1f
    
        let lt1 = foo.Lifetime + dt
        foo.Step1 dt // tupled method call boxes foo -- wrong
        let lt2 = foo.Lifetime

        let res = (abs (lt1 - lt2)) < 0.01f
        printfn "test1 lifetime is %A, should be %A: %A" lt2 lt1 (if res then "ok" else "ERROR")

    let test2() =
        let foo = Foo()
        let dt = 0.1f
    
        let lt1 = foo.Lifetime + dt
        foo.Step2 1 dt // curried method call boxes foo -- wrong
        let lt2 = foo.Lifetime

        let res = (abs (lt1 - lt2)) < 0.01f
        printfn "test2 lifetime is %A, should be %A: %A" lt2 lt1 (if res then "ok" else "ERROR")

    let test3() =
        let cap = 10
        let seg = Seg(cap)

        for frame = 1 to 2 do
            for i = 0 to cap - 1 do
                let dt = ((float32 i) + 1.0f) / 10.0f
            
                let lt1 = seg.Foos.[i].Lifetime + dt
                seg.Foos.[i].Step1 dt  // tupled method call does NOT box the array element -- right
                let lt2 = seg.Foos.[i].Lifetime

                let res = (abs (lt1 - lt2)) < 0.01f
                printfn "test3 lifetime is %A, should be %A: %A" lt2 lt1 (if res then "ok" else "ERROR")

    let test4() =
        let cap = 10
        let seg = Seg(cap)

        for frame = 1 to 2 do
            for i = 0 to cap - 1 do
                let dt = ((float32 i) + 1.0f) / 10.0f
            
                let lt1 = seg.Foos.[i].Lifetime + dt
                seg.Foos.[i].Step2 frame dt  // curried method call boxes the array element -- wrong
                let lt2 = seg.Foos.[i].Lifetime

                let res = (abs (lt1 - lt2)) < 0.01f
                printfn "test4 lifetime is %A, should be %A: %A" lt2 lt1 (if res then "ok" else "ERROR")

    let test5() =
        let mutable foo = Foo()
        foo.LastFrame <- 1

        let f1 = foo.LastFrame
        let ifoo = foo :> IFoo // boxes foo, same as C# -- right
        ifoo.Step3 2
        let f2 = foo.LastFrame

        printfn "test5 frame is %A, should be %A: %A" f2 f1 (if f2 = f1 then "ok" else "ERROR")

    let test6() =
        let mutable foo = Foo()
        foo.LastFrame <- 1

        let f1 = 2    
        (foo :> IFoo).Step3 2 // boxes foo; in C#, this does NOT box foo -- wrong
        let f2 = foo.LastFrame

        printfn "test6 frame is %A, should be %A: %A" f2 f1 (if f2 = f1 then "ok" else "ERROR")

    [<EntryPoint>]
    let main argv = 
        test1()
        test2()
        test3()
        test4()
        test5()
        test6()

        0 // return an integer exit code

**Comment by kulibali** [comment]
Here is the IL for `test` in debug mode:

Here is the IL for *test1* in debug mode:

	.locals init (
		[0] valuetype Program/Foo foo,
		[1] valuetype Program/Foo,
		[2] float32 dt,
		[3] float32 lt1,
		[4] valuetype Program/Foo,
        ...
	)

	IL_0000: nop
	IL_0001: ldloca.s 1
	IL_0003: initobj Program/Foo
	IL_0009: ldloc.1
	IL_000a: stloc.0
	IL_000b: ldc.r4 0.1
	IL_0010: stloc.2
	IL_0011: ldloca.s foo
	IL_0013: ldfld float32 Program/Foo::Lifetime
	IL_0018: ldloc.2
	IL_0019: add
	IL_001a: stloc.3
	IL_001b: ldloc.0
	IL_001c: stloc.s 4
	IL_001e: ldloca.s 4
	IL_0020: ldloc.2
	IL_0021: call instance void Program/Foo::Step1(float32)

This copies `foo` to a temporary and calls the method on it.

**Comment by kulibali** [comment]
Here is the IL for `test1` in release mode:

	.locals init (
		[0] valuetype Program/TestBox/Foo foo,
		[1] valuetype Program/TestBox/Foo,
		[2] float32 lt1,
		[3] valuetype Program/TestBox/Foo,
		[4] valuetype Program/TestBox/Foo&,
		[5] float32 lt2,
		[6] bool res,
		[7] class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<float32, class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<float32, class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<string, class [FSharp.Core]Microsoft.FSharp.Core.Unit>>>,
		[8] class [FSharp.Core]Microsoft.FSharp.Core.PrintfFormat`4<class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<float32, class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<float32, class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<string, class [FSharp.Core]Microsoft.FSharp.Core.Unit>>>, class [mscorlib]System.IO.TextWriter, class [FSharp.Core]Microsoft.FSharp.Core.Unit, class [FSharp.Core]Microsoft.FSharp.Core.Unit>
	)

	IL_0000: nop
	IL_0001: ldloca.s 1
	IL_0003: initobj Program/TestBox/Foo
	IL_0009: ldloc.1
	IL_000a: stloc.0
	IL_000b: ldloca.s foo
	IL_000d: ldfld float32 Program/TestBox/Foo::Lifetime
	IL_0012: ldc.r4 0.1
	IL_0017: add
	IL_0018: stloc.2
	IL_0019: ldloca.s 3
	IL_001b: initobj Program/TestBox/Foo
	IL_0021: ldloc.3
	IL_0022: stloc.1
	IL_0023: ldloca.s 1
	IL_0025: stloc.s 4
	IL_0027: ldloc.s 4
	IL_0029: ldloc.s 4
	IL_002b: ldfld float32 Program/TestBox/Foo::Lifetime
	IL_0030: ldc.r4 0.1
	IL_0035: add
	IL_0036: stfld float32 Program/TestBox/Foo::Lifetime
	IL_003b: ldloca.s foo
	IL_003d: ldfld float32 Program/TestBox/Foo::Lifetime
	IL_0042: stloc.s lt2
	IL_0044: ldloc.2
	IL_0045: ldloc.s lt2
	IL_0047: sub
	IL_0048: call float32 [mscorlib]System.Math::Abs(float32)

Now the call to `Step1` has been "optimized" out, I assume since the updated value of the temporary is not used anywhere.  However, I wanted to mutate `foo`, and this did not happen.

**Comment by dsyme** [comment]
Hi @kulibali 

If you turn on "--warn:5" you will see these warnings:

``
a.fs(33,5): warning FS0052: The value has been copied to ensure the original is not mutated by this operation

a.fs(45,5): warning FS0052: The value has been copied to ensure the original is not mutated by this operation

a.fs(77,13): warning FS0052: The value has been copied to ensure the original is not mutated by this operation
``

This warning is off by default.

For example, in test1() the value "foo" is, from the F# perspective, immutable, so a copy is made when operations that (might) mutate are performed.  If you change to use

``
let test1() =
    let mutable foo = Foo()
   ...
``

then the warnings go away.  Basically, if you are going to use mutable structs, you need to mark more locals and record fields as mutable.

For this one:
``
 (foo :> IFoo).Step3 2 
``

the F# specification is that a boxing operation occurs (there is no special case to indicate otherwise in the F# language spec).   You can get the effect of a "mutating interface call on a struct" via this sort of thing:

``
let test7() =
    let mutable foo = (new Foo() :> IFoo)
    foo.Step3 2 
``

Though unless I've missed something I think it's fair to add that F# doesn't allow you to view a mutable struct location through the lens of both IFoo and Foo types.

Cheers
don

**Comment by latkin** [comment]
@dsyme I think there is confusion because immutable bindings can have mutable fields for classes and records, but for structs this is no longer the case? Can you provide some clarity on why?

```fsharp
type MyClass(x : int) =
    member val X = x with get,set
    member __.Mutate(n) = __.X <- n

let c = MyClass(1)
c.Mutate(2)  // c.X is mutated

type MyRec =
    { mutable X : int }
    member __.Mutate(n) = __.X <- n

let r = { X = 1 }
r.Mutate(2)  // r.X is mutated

type MyStruct =
    struct
        val mutable X : int
        member __.Mutate(n) = __.X <- n
    end

let s = MyStruct(X = 1)
s.Mutate(2)  // s.X is *not* mutated
```

**Comment by dsyme** [comment]
This now belongs in a stackoverflow question (there's probably one on it already?)

See section 6.9.4 of the F# language spec - "6.9.4	Taking the Address of an Elaborated Expression" and the side note "Unless a value is held in arrays or locations marked mutable, or a value type is known to be immutable to the F# compiler, F# inserts copies to ensure that inadvertent mutation does not occur."

(FWIW it's not properly clear from the first bullet in that section that taking the address of a module-bound or class-bound "let mutable x" is elaborated to a byref to that location, I'll make a note to adjust that. We have lots of updates to make for the F# 4.0 spec in any case!)

**Comment by latkin** [comment]
This felt confusing/inconsistent to me at first but after some lunchtime chats w/ roslyn compiler people a while ago I understand it better. C# `readonly` values behave the same way.

The explanation that made sense to me was that the readonly/immutable designation applies to the memory directly associated with the binding. For ref types that's just the pointer, but for val types it includes the fields, as well.
