### ISSUE TITLE
F12 go-to-definition goes to wrong location when type is defined with "and" instead of "type"

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#4640]
When you define a type with `and`, and it contains a discriminated union, going to the definition of that type will end up inside the DU `of X`, instead of the definition itself. Replace `and` for `type` and it goes well.

![wrong go-to-definition](https://user-images.githubusercontent.com/16015770/38046702-a12da50e-32c0-11e8-891c-407714863a9a.gif)

### Repro steps

You can see the wrong behavior with this code:

```f#
/// Types defined with "and" fail to go to the correct definition
module JumpingTest =
    type Three = Three of int 
    and Foo = Zed of Three 
    and Bar = Foo of Foo
```

Hit F12 on `Foo` in `of Foo` (or any other place you use the class, it doesn't matter), and you end up at `of Foo`, Same for `Three`.

### Expected behavior

It should go to the definition of `Foo` or `Three` instead.

### Actual behavior

It goes to a usage of `Foo`, in particular, a usage inside a DU. When there's multiple such usages there's no telling where you will end up. In large files, F12 is golden when it works, but pretty confusing when it doesn't.

### Known workarounds

Done't use `and`, but there are scenario's where that's simply not possible.

### Related information 

Seen on any recent (15.6+) version of Visual Studio. Seen it before as well, but didn't report it earlier and I can't remember when it started, or whether it was always like that.

This *worked correctly in Visual Studio 2015, i.e. 14.x* (just reconfirmed, it doesn't happen there).

**Comment by vasily-kirichenko** [comment]
It's fixed in https://github.com/Microsoft/visualfsharp/pull/5050

**Comment by vasily-kirichenko** [comment]
Ive not checked though. Is this bug specific or it’s just about navigating to recursive type declaration?

**Comment by abelbraaksma** [comment]
@vasily-kirichenko I'm not sure it's related to recursion. It happens with the example snippet always and that's not recursive of itself.

**Comment by vasily-kirichenko** [comment]
OK

**Comment by vasily-kirichenko** [comment]
@abelbraaksma It's fixed in master:

![_1](https://user-images.githubusercontent.com/873919/41413027-88c621b4-6fea-11e8-89a4-8657415564c5.gif)

**Comment by cartermp** [comment]
Closing and labeling for posterity

**Comment by abelbraaksma** [comment]
Great work, thanks!
