### ISSUE TITLE
Errors are no longer listed in the order in which the compiler finds them (regression?)

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#4642]
Since a short while (15.6, 15.5?) the errors listed in the Error List window in Visual Studio 2017 are in some odd undefined order. 

The order in the Output window is correct (first in declaration order comes first).

This is particularly confusing and becomes time-consuming when working on large solutions with large refactorings, where first-in-declaration-order is the usual way to go to fix errors.

### Repro steps

Always reproducible, most visible when you have a lot of errors in multiple files:

* Create a project with at least three files
* Make sure you have an error in each file
* The order will not be first-encountered-to-last-encountered

### Expected behavior

Errors should be displayed in first-to-last order, that's also how this used to work. This has the benefit of (often) fixing the following errors by taking care of the first one in the list.

### Actual behavior

Some undefined order. It is not the opposite order, nor alphabetical by description, nor numerical by error code, nor by severity.

As a consequence, "Next error" and "Previous error" make little sense with respect to the overview in the error list.

Note that within any one file the errors appear in line-number order.

### Known workarounds

Use the Output window instead. This works, but it not as neat as working from the cleaner Error List.

### Related information 

Seen at least from 15.6, possibly a little earlier. Can't remember for certain how it was from 15.3 and before, but I do not have the ability to test it. In Visual Studio 2015 this was definitely not the case, they appeared in order (as far as I can remember).

**Comment by cartermp** [comment]
@abelbraaksma I have tried the following with 15.8 Preview 5:

**File2.fs**

```fsharp
module File2

let f1 () = x
```

**File1.fs**

```fsharp
module File1

let f2 x = (x, 12)
```

**Program.fs**

```fsharp
// Learn more about F# at http://fsharp.org

open System
open File2
open File1

let f3 x y = f1 x |> f2 y

[<EntryPoint>]
let main argv =
    printfn "Hello World from F#!"

    f3 1 2 |> ignore
    0 // return an integer exit code
```

The error list is as follows:

|Code|Description|Project|Line|
|-----|------------|-------|-----|
|FS0039|	The value or constructor 'x' is not defined.	|ConsoleApp20	C:\Users\phillip\source\repos\ConsoleApp20\ConsoleApp20\File2.fs|3|
|FS0001|	(elided for formatting)|ConsoleApp20	C:\Users\phillip\source\repos\ConsoleApp20\ConsoleApp20\Program.fs|7|
|FS0001	|(elided for formatting)|ConsoleApp20	C:\Users\phillip\source\repos\ConsoleApp20\ConsoleApp20\Program.fs|13|

This would appear to be in order. Have you still seen this in your project?

**Comment by cartermp** [comment]
Closing this out. @abelbraaksma I cannot repro this with the release VS 15.8.x. Please do report back if you see it with that release.

**Comment by abelbraaksma** [comment]
> @cartermp added the needs repro label on Aug 13

It's been a while, but I've added a repro in the newly created issue #5958. I believe it happens with any project, but it's a repro nonetheless ;). This issue should remain closed, I guess, let's continue in the new one, with new info.
