### ISSUE TITLE
Active recognizers / active patterns are shown twice in IntelliSense, once with, once without "|" around them

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#4651]
Whenever an active recognizer appears in the IntelliSense dropdown box, they are included twice, once as `X` and once as `|X|_|` (or `|X|` or `|X|Y|Z|`, whichever applies). 

![image](https://user-images.githubusercontent.com/16015770/38157401-dfc34ad6-3486-11e8-9bcc-1475d4db8d4c.png)

### Repro steps

Happens with any active pattern.

### Expected behavior

Should appear once. Or, if the context sensitive help is aware of the context, it should appear without `|` (pipe) syntax when inside a `match x with` or a `function` expression, and with them when in any other context.

### Actual behavior

See screenshot.

### Known workarounds

Just ignore the double appearance.

### Related information 

As can be seen in the screenshot, it doesn't seem to happen to *all* active recognizers. However, it happens most of the time that I know off.

Visual Studio 2017 15.6.x.

**Comment by cartermp** [comment]
Additionally, taking the option which _isn't_ an active recognizer will result in uncompilable code.

<img width="440" alt="screen shot 2018-03-31 at 12 08 59 pm" src="https://user-images.githubusercontent.com/6309070/38165103-516fa832-34dc-11e8-92f6-f5c0ae1a8324.png">

**Comment by abelbraaksma** [comment]
@cartermp: indeed. Except in the case where you want to use it as a function. In your case, if you were to write (through the dropdown or by hand) ``` let foo ``|StartsWith|_|`` x y ``` would return an option value.

I.e., occasionally this can come in handy: ```["Phillip"; "John"] |> List.choose (``|StartsWith|_|`` "Ph") ``` would compile and return a list of one item. But I think this abuse of active recognizers is used rarely (though I'm guilty of doing it every now and then).

**Comment by vasily-kirichenko** [comment]
This is fixed in https://github.com/Microsoft/visualfsharp/pull/4831
