### ISSUE TITLE
FCS: namespaces and types considered equal when name equals

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#4658]
<img width="368" alt="screen shot 2018-04-01 at 17 42 16" src="https://user-images.githubusercontent.com/3923587/38174320-0d67c70c-35d4-11e8-928f-71753c52f93c.png">

Looks like the problem is in implementation of `ItemsAreEffectivelyEqual` as it also makes the `JetBrains.Util` considered unused unless the other `Util` is commented out.

**Comment by auduchinok** [comment]
OK, entities are indeed considered equal by `NameResolution.tyconRefDefnEq`.
One of the `Util` namespaces is defined in a C# project in the same solution and the other is a part of the `ReSharper.SDK`.

<img width="604" alt="screen shot 2018-04-01 at 20 51 12" src="https://user-images.githubusercontent.com/3923587/38175972-7642c2da-35ee-11e8-9255-ba5626729b37.png">

```
(1,0-1,0) startup IsSynthetic=False -> System.IO.FileNotFoundException: Could not find file 'C:\Developer\fsharp-support\rider-fsharp\build\riderRD-LATEST-TRUNK-SNAPSHOT\bin\startup'.
File name: 'C:\Developer\fsharp-support\rider-fsharp\build\riderRD-LATEST-TRUNK-SNAPSHOT\bin\startup'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at Microsoft.FSharp.Compiler.Range.range.get_DebugCode()
```

**Comment by auduchinok** [comment]
I found that the `tyconRefEq` check fails but due to ranges and name equality namespaces and types from assemblies considered equal.

<img width="213" alt="screen shot 2018-04-01 at 23 35 18" src="https://user-images.githubusercontent.com/3923587/38177941-0a051d0c-3611-11e8-83eb-97cefea7496f.png">

<img width="237" alt="screen shot 2018-04-01 at 23 35 31" src="https://user-images.githubusercontent.com/3923587/38177942-0a22b39e-3611-11e8-8bc1-a69362bd62f0.png">

Adding a check for startup range fixes it for namespaces and types/constructors. I'll look into values equality as well and check if anything could be broken due to this change.

```fsharp
let tyconRefDefnEq g (eref1:EntityRef) (eref2: EntityRef) =
    tyconRefEq g eref1 eref2 
    // Signature items considered equal to implementation items
    || ((eref1.DefinitionRange = eref2.DefinitionRange || eref1.SigRange = eref2.SigRange) &&
        eref1.LogicalName = eref2.LogicalName && eref1.DefinitionRange <> Range.rangeStartup)
```

**Comment by dsyme** [comment]
> What would be a better way to check that a symbol is from an assembly and we should not try comparing declaration ranges?

@auduchinok The symbol equality imlpementation has kind of grown over time and it's a good time to look at what we're trying to achieve i suppose

* We currently implement two notions of equality - .Equals and .EffectivelySameAs
* We can't use object equality because we don't create unique objects for symbols
* We struggle to use object equality of underlying symbols because we want to treat symbols from signature files as the same as corresponding symbols from implementation files, without carrying around the complex maps that can allow us to check this exactly. This motivated the original use of the DefinititionRange hack
* For many purposes, the user expects the symbol for, say, a constructor ``C()`` to be the same as both the constructor and the symbol for the type `C` in `type C()` .  This sort of thing motivated EffectivelySameAs.

But I'm not happy with the state of play as it leads to bugs like the one you spotted.  I think your fix for that is OK but perhaps there is just another way to approach this.

**Comment by dsyme** [comment]
> I'll look into values equality as well 

I suppose we don't get any Val from IL assemblies so this shouldn't be a problem (for IL members and properties we generally check members have the same assembly and metadata token)

**Comment by auduchinok** [comment]
> * We can't use object equality because we don't create unique objects for symbols
> * We struggle to use object equality of underlying symbols because we want to treat symbols from signature files as the same as corresponding symbols from implementation files, without carrying around the complex maps that can allow us to check this exactly. This motivated the original use of the DefinititionRange hack

Yes, I understood that.

> * We currently implement two notions of equality - .Equals and .EffectivelySameAs
> * For many purposes, the user expects the symbol for, say, a constructor C() to be the same as both the constructor and the symbol for the type C in type C() . This sort of thing motivated EffectivelySameAs.

I was speaking about `EffectivelySameAs`. I agree on expecting some symbols to be interchangeable in some contexts from user's point of view, however I'd expect FCS to not treat different symbols as same ones. I think this it's the tooling/clients who should decide whether some symbols should be treated as same ones. If we want to keep this logic inside FCS and don't make clients implement it, I think additional options may be added to APIs like `EffectivelySameAs` or `GetUsesOfSymbolInFile`. The options object could be a record with fields similar to `TypeNameResolutionFlag` union in the name resolution.

**Comment by dsyme** [comment]
> > I think your fix for that is OK but perhaps there is just another way to approach this.

> @dsyme Could you elaborate please?

Nothing specific - really asking for advice along the lines of "maybe we need to rethink this whole thing"...
