### ISSUE TITLE
Type inference fails with active recognizers, even with type annotations

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#4679]
Trying syntax such as `Choice1 foo` works, but `Choice1 <| foo` or `foo |> Choice1` doesn't, regardless of whether a specific type annotation is available, type inference fails.

### Repro steps

This fails:

```f#
let (|X|Y|) x =
    match x with
    | 1 -> 1 |> X
    | _ -> Y
```

And this, with type annotation

```f#
let (|X|Y|) x: Choice<int, unit> =
    match x with
    | 1 -> 1 |> X
    | _ -> Y
```

And this:

```f#
let (|X|Y|) x =
    match x with
    | 1 -> X <| 1
    | _ -> Y
```

But this works:

```f#
let (|X|Y|) x =
    match x with
    | 1 -> X 1
    | _ -> Y
```

### Expected behavior

All examples above should all compile without error, and even if type discovery fails, the one with type annotation should work. But `|>` and `<|` should typically _help_ type inference, not prevent it from succeeding.

### Actual behavior

Only postfix expressions compile properly, the rest gives the following error:

![image](https://user-images.githubusercontent.com/16015770/38311881-8471824a-3820-11e8-81d0-41aa7cae5718.png)

In text:

> error FS0001: This expression was expected to have type int -> Choice<int,unit> but here has type Choice<unit,'a>

### Known workarounds

Only use postfix syntax for function calls, where the function is a choice-operand.

### Related information 

Seen in VS2017 15.6 and up, and VS2015.

**Comment by dsyme** [comment]
This is by design for F# 3.x and 4.x. We don't support first-class uses of active pattern result labels.  We added first-class uses of union cases in F# 3.x.  We could do the same for active pattern result labels, but please track it via a language suggestion.

**Comment by abelbraaksma** [comment]
@dsyme, thanks, I wasn't aware of this distinction (and got just too accustomed to the "everything is a function" adage). Let me close this. I'll go through the language suggestion, unless someone already proposed it.
