### ISSUE TITLE
Semicolon in F# member declaration is not recognized as end of expression

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#4680]
Code is below, but due to indentation issues it will probably be easier to understand the problem by referring to attached screenshots.

```fsharp
type Name = Name of string 
    with override x.ToString() = let value (Name s) = s
                                 value x
```

(here the 'value x' line is indented to begin directly below the 'let')
is acceptable but the equivalent code

```fsharo
type Name = Name of string 
    with override x.ToString() = let value (Name s) = s; value x
```

results in a compiler error.

Problem observed on VS Community 15.6.4

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/227841/semicolon-in-f-member-declaration-is-not-recognize.html
VSTS ticketId: 594506_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
(Edited to add the F# formatting to the code samples)

**Comment by duncanmak** [comment]
One way to make this work is to change it to:

```F#
> type Name = Name of string 
-     with override x.ToString() = let value (Name s) = s in value x
- ;;
type Name =
  | Name of string
  with
    override ToString : unit -> string
  end

> 
```

**Comment by dsyme** [comment]
This is by design - `;` has never been end-of-expression, you have to use `in`
