### ISSUE TITLE
QuickInfo colors are incorrect for `UnionCase` and `Interface`.

### ISSUE THREAD

**Issue by brettfo** [Microsoft/visualfsharp#4685]
As mentioned in #4644 the colors we used to use for `UnionCase` and `Interface` aren't among the standard colors of [PredefinedClassificationTypeNames](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.standardclassification.predefinedclassificationtypenames?view=visualstudiosdk-2017), but there may be some additional pre-defined color names that we can use here; it's just a string.

![image](https://user-images.githubusercontent.com/926281/38338033-acaa7c66-381c-11e8-9fad-133a41deee91.png)

**Comment by majocha** [comment]
Previously we used Roslyn's Enum tag
https://github.com/Microsoft/visualfsharp/blob/0d569e4f4aaafc6f9fd19f6b48a8090fb1aee14f/vsintegration/src/FSharp.Editor/Common/RoslynHelpers.fs#L50-L55
for those.


Tracing it through [Roslyn code](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Classification/ClassificationTypeNames.cs,24):
`        public const string EnumName = "enum name";`

this string probably should work with the new API.
