### ISSUE TITLE
Description tooltip in Intellisense often empty.

### ISSUE THREAD

**Issue by majocha** [Microsoft/visualfsharp#4714]
![image](https://user-images.githubusercontent.com/1760221/38642213-b302fc7e-3dd9-11e8-8b9e-0dfa82b7c7d6.png)

#### Repro steps

Trigger autocompletion and go through the list with arrow keys. After a few correctly displayed descriptions empty tooltips start to show up.

#### Related information 

Recent nightlies and master. Hard to tell exactly when it broke.
This works fine in the released version.

**Comment by cartermp** [comment]
I've noticed this is self-built VSIXs over time. Not sure what the root cause is, since I recall seeing it months ago.

**Comment by irium** [comment]
Also seeing this for about a month.

**Comment by majocha** [comment]
Here, we cache declarations with 10 second expiration:
https://github.com/Microsoft/visualfsharp/blob/d4920e014b2a0f7f8313d6fcfaea099433161c76/vsintegration/src/FSharp.Editor/Completion/CompletionProvider.fs#L186-L189


We should do it for the duration of the intellisense session instead. The problem is, Roslyn doesn't expose the completion session. From the calls of FSharpCompletionProvider  methods we can deduct when a new session starts and when it commits, but there is no indication of a cancelled one.

So, one solution would be to keep the backing data of the last intellisense session until it commits or, in the worse case, until a new one starts.

Another solution is to go lower level, handle [IIntellisenseSession.Dismissed](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.iintellisensesession.dismissed?view=visualstudiosdk-2017) to explicitly clear our cache in the right moment.

**Comment by dsyme** [comment]
@majocha 

> From the calls of FSharpCompletionProvider methods we can deduct when a new session starts and when it commits, but there is no indication of a cancelled one.

What's the right way to deduce when the session starts?  Is it whenever `ShouldTriggerCompletion` returns true? Or each time `ProvideCompletions` is called?

**Comment by BentTranberg** [comment]
Although closed now, let me just say I've seen this in release versions for a long time.
