### ISSUE TITLE
Instance property name collides with nested class name

### ISSUE THREAD

**Issue by dmitry-a-morozov** [Microsoft/visualfsharp#4729]
I have generative type provider that emits following definitions
```csharp
public class MyClass
{
    class MyNestedClass
    {
        const string Path = "c:\test";
    }
    public MyNestedClass MyNestedClass { get; set; }
}
```
In type provider consuming project when trying to reference `MyClass.MyNestedClass.Path` I get an error: `Property `Property 'MyNestedClass' is not static.`

- I used C# for pseudo code because I need nested class to show the use case
- I'm aware that this C# code fails to compile because of name collision between class name  `MyNestedClass` and property name `MyNestedClass` but it's perfectly legal as type provider output
- I understand why C# compiler makes this code illegal but why this restriction exists in F#?

I tried to search F# language spec but could not find anything.

**Comment by dsyme** [comment]
@dmitry-a-morozov Yes, the name resolution will stop at `MyClass.MyNestedClass` being a reference to a property.  Once name resolution reaches a member or value, we commit to that interpretation.

**Comment by dsyme** [comment]
> @dmitry-a-morozov Yes, the name resolution will stop at MyClass.MyNestedClass being a reference to a property. Once name resolution reaches a member or value, we commit to that interpretation.

Looking further... I can see the case for saying that name resolution should not commit to something which is going to fail (referencing an instance property as a static property) if alternatives are available.  I wouldn't be opposed to a language addition/change here to allow this.  @forki is good on the name resolution code and might help you find the right place to make the adjustment

**Comment by dmitry-a-morozov** [comment]
Right. It should not resolve to static property `MyClass.MyNestedClass` because it doesn't exist.

**Comment by dsyme** [comment]
> Right. It should not resolve to static property MyClass.MyNestedClass because it doesn't exist.

Well, right now it resolves to the property, then decides to give an error because it's static, just like we'd give an error if it had the wrong type.

If we make a change here we'd need to be really careful to be consistent.

**Comment by dmitry-a-morozov** [comment]
Would it be helpful to explain a use case where I need this ?

**Comment by dsyme** [comment]
> Would it be helpful to explain a use case where I need this ?

Sure :)  BTW it should go to fslang-suggestions in any case

**Comment by dsyme** [comment]
Closing as it goes to fslang-suggestions
