### ISSUE TITLE
C# method with params argument does not have expected signature

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#474]
I have a C# method on a class that looks like this: -

```csharp
class Foo {
    public void Bar(int a, string b, params bool [] things) { }
}
```
If I bind that method to a value it ends up with a signature of

```fsharp
int -> string -> unit
```

I would have expected it to have a signature of

```fsharp
int -> string -> bool[] -> unit
```

**Comment by dsyme** [comment]
Hi Isaac,  

I think you mean ``int * string -> unit`` and ``int * string * bool[] -> unit``?

In any case by design, it's how the method overload resolution process works for first-class uses of methods.  I don't think it's something we could realistically change at this point.

Cheers
Don

**Comment by isaacabraham** [comment]
Yes, sorry, that was what I meant. So I suppose the way to work around this is to manually create something like ```let x = fun (a,b,c) -> object.Bar(a,b,c)``` or similar.

Thanks for the clarification.
