### ISSUE TITLE
VS 2017 very slow

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#4742]
Visual studio 2017 on the new project format is very slow.

Text input seems to sometimes lag by about 5 seconds.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/231792/vs-2017-very-slow.html
VSTS ticketId: 598176_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
Tracking here instead: #4258

Since there isn't a single root cause, but rather a large set of issues
