### ISSUE TITLE
Visual Studio Editing is sluggish

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#4743]
Hi there,

I'm using VS2017, updated to v15.6.2. I use the IDE for a .NET Core F# project.

Typical process for me is to open a file, do some editing, navigate to a particular type to check/modify something, check and fix any syntax errors, then build the project.

After a short while,
1. VS2017 has grabbed more than 2GB of memory, which does not get freed up. This after perhaps 3 build operations, with maybe 4 files open (+- 200 lines per file)
2. Editing becomes terribly sluggish, navigation is impossible even to a type in the same file. CPU runs at 85-100% for protracted periods

Bouncing VS helps, but the problem returns soon after.

I ran processmon.exe to see what was going on, and saw that VS is repeatedly scanning ../Microsoft SDKs/NugetPackages folder. Is there **any** way to stop this? Making the folder hidden did not help.

Please help by posting a How-To article, the editing experience is terrible, I've had the same problem with VS Code and have had to resort to using Atom to edit my project, keeping VS2017 open only to build and debug.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/224130/visual-studio-editing-is-sluggish.html
VSTS ticketId: 590977_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
Tracking here instead: #4258

Since there isn't a single root cause, but rather a large set of issues
