### ISSUE TITLE
F# Templates Missing

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#4744]
I'm missing the F# project templates in Visual Studio, version 15.6.4, today.  Is there some good resource that documents how to fix this?  I tried using the installer to remove F# support and add it back again, but that didn't work.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/221912/f-templates-missing-2.html
VSTS ticketId: 588869_
_These are the original issue comments:_

shawnmartin70 on 3/23/2018, 09:35 AM (26 days ago): <p>I have now also tried the repair process and that did not correct the problem.</p>

Brett V. Forsgren on 3/27/2018, 04:46 PM (21 days ago): <p>Can you provide a screenshot of the issue?  Installing VS on a fresh machine installs templates for me.  I've attached screenshots of my installer and new project dialog.</p><p><img src="https://developercommunity.visualstudio.com/storage/temp/26090-fs-templates.png"></p><p><img src="https://developercommunity.visualstudio.com/storage/temp/26101-fs-templates2.png"></p>

Brett V. Forsgren on 3/30/2018, 11:49 AM (19 days ago): <p>Can you look at the screenshots I posted above and see if that works for you?</p>

_These are the original issue solutions:_

shawnmartin70 solved on 4/10/2018, 00:26 PM (8 days ago), 0 votes: 
<p>Brett,</p>
<p>I'm sorry about the late reply. I went on vacation. Anyway, I inadvertently resolved the issue: in the process of trying to use a netstandard 2.0 library I was forced to install .NET 4.7.1 (previously I had 4.7 installed) and after that Visual Studio would not open my existing F# projects any more (previously, existing F# projects would open, but the templates weren't showing for new ones). So, when failing to open an F# project VS prompted to install F# language support and after letting it do so everything worked.</p>
<p>So, I'm wondering if this is all because I upgraded to VS 15.6 without having .NET 4.7.1?</p>
<p>Thank you,</p>
<p>Shawn</p>

**Comment by cartermp** [comment]
Closing as this appears to have been resolved
