### ISSUE TITLE
no F# templates in VS2015RC

### ISSUE THREAD

**Issue by tommes** [Microsoft/visualfsharp#475]
I have no F#-templates in my 2015RC. Might be related to the install-sequence. Here is what i did:
Win 8.1 running with VS2013 (update 4)
- installed 2015RC side by side - I didn't check the F# templates here
- uninstalled VS2013
![image](https://cloud.githubusercontent.com/assets/1334132/7866308/f8acd5de-056e-11e5-9c1e-b8c67a916e6d.png)

I've tried to repair/uninstall/reinstall VS2015, no dice.

On the other side, in a Win10 installation without previous VS2013, all is fine.
![image](https://cloud.githubusercontent.com/assets/1334132/7866378/5bac1d02-056f-11e5-813b-0b6bd371ddfd.png)

**Comment by enricosada** [comment]
Duplicate of #411 ?

**Comment by latkin** [comment]
Thanks for logging the issue.  Would be great if someone can try to repro.

**Comment by tommes** [comment]
as suggested on twitter, I've tried to install the vsix which fails:
![image](https://cloud.githubusercontent.com/assets/1334132/7869766/33401614-0585-11e5-9646-b38eea7ae997.png)
Log: 
28.05.2015 22:00:30 - Microsoft VSIX Installer
28.05.2015 22:00:30 - -------------------------------------------
28.05.2015 22:00:30 - Initializing Install...
28.05.2015 22:00:31 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: This VSIX does not apply to any product installed on this machine. The problem could be that the VSIX manifest's format is not recognized, or that the manifest has been corrupted. ---> System.InvalidOperationException: Fehler im XML-Dokument (3,18). ---> System.Xml.Schema.XmlSchemaValidationException: Das _locID-Attribut wurde nicht deklariert.
   bei System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(XmlSchemaValidationException e, XmlSeverityType severity)
   bei System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(String code, String arg)
   bei System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String lName, String ns, XmlValueGetter attributeValueGetter, String attributeStringValue, XmlSchemaInfo schemaInfo)
   bei System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(String localName, String namespaceUri, XmlValueGetter attributeValue, XmlSchemaInfo schemaInfo)
   bei System.Xml.XsdValidatingReader.ValidateAttributes()
   bei System.Xml.XsdValidatingReader.ProcessElementEvent()
   bei System.Xml.XsdValidatingReader.ProcessReaderEvent()
   bei System.Xml.XsdValidatingReader.Read()
   bei System.Xml.XmlReader.ReadStartElement()
   bei Microsoft.VisualStudio.ExtensionManager.Implementation.XmlSerializationReaderVsixLanguagePack.Read2_VsixLanguagePack(Boolean isNullable, Boolean checkType)
   bei Microsoft.VisualStudio.ExtensionManager.Implementation.XmlSerializationReaderVsixLanguagePack.Read3_VsixLanguagePack()
   bei Microsoft.VisualStudio.ExtensionManager.Implementation.VsixLanguagePackSerializer.Deserialize(XmlSerializationReader reader)
   bei System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   bei Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadVSIXLanguagePackManifest(XmlReader vsixManifestReader)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadVSIXLanguagePackManifest(XmlReader vsixManifestReader)
   bei Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.LocalizeExtension(XmlReader langPackManifestReader, String localeRelativeRoot)
   bei Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream, String localeRelativeRoot, Boolean localize)
   bei Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream vsixStream, CultureInfo preferredCulture)
   bei Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   bei VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   bei VSIXInstaller.App.InitializeInstall()
   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()


Maybe a localization issue?

**Comment by tommes** [comment]
This commit did the trick:
https://github.com/Microsoft/visualfsharp/commit/74bbb0795fd5cb1fdd09b0f17099c670590816be
I've edited the vsix using 7zip and put the content of the file  vsintegration/src/deployment/VsProDeployTemplates/extension.vsixlangpack into VsProDeployTemplates.vsix\de\extension.vsixlangpack - after that install succeeded.
