### ISSUE TITLE
Do not allow unbox null to value types

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#4758]
Unboxing `null` to a value type:

```fsharp
unbox<int> null
```
causes NRE at runtime:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at <StartupCode$FSI_0003>.$FSI_0003.main@()
```
The generated code is
```csharp
internal static class $_
    {
        [DebuggerBrowsable(DebuggerBrowsableState.Never), DebuggerNonUserCode, CompilerGenerated]
        internal static int init@;

        static $_()
        {
            int arg_06_0 = (int)null;
        }
    }
```
Compare with C#:
```csharp
class T {
  int X => (int) null;
}
```
It raises a compile time error:

![image](https://user-images.githubusercontent.com/873919/38995155-fb222404-43f0-11e8-8173-45bf59a7dc7c.png)

I suggest to generate the same error.

**Comment by vasily-kirichenko** [comment]
It should raise an error for struct records and struct DUs too, of cause.

**Comment by ForNeVeR** [comment]
Please don't forget that there's `Nullable<T>`: a **value type** itself, but you could `unbox null` into it.

```fsharp
open System
let x : Nullable<int> = unbox null // ok
```

**Comment by smoothdeveloper** [comment]
@ForNeVeR I think it is related to implicit cast operator, I don't think we'd like that to apply implicitly in F# which doesn't allow implicit casts AFAIK.

**Comment by dsyme** [comment]
This is per spec (add a language suggestion?)

* The type of `unbox` is `obj -> 'T` where `T` is unconstrained - the output can be a reference or value type, nullable or not-nullable.

* The type of the `null` literal is a fresh type inference variable `T` constrained with the `nullable` constraint. 

Anyway, you can certainly pass a `null` literal where `obj` is expected. 

The language suggestion might be to track special knowledge that we know a value to be exactly `null` and add a special set of rules when we know these things will fail.  But such knowledge would only be very local and lost at any boundary, and of not much practical use.

**Comment by vasily-kirichenko** [comment]
@dsyme I understand it. But the C# team decided to do this check, and being worse than that does not look great :) However, it's a small thing and better be forgotten.
