### ISSUE TITLE
F# go to definition spotty

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#4789]
**Action:**
Mouse over type name in project referencing another project in solution and select go to definition. This works.

But within the same project, if the active fs file is in a folder, and the targeted type is in a file in another folder, results in &quot;Cannot navigate to symbol under the carat.&quot;

Both are in modules without namespaces.

**Versions:**
15.6.6 and 15.7.0 preview 4

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/239657/f-go-to-definition-spotty.html
VSTS ticketId: 605984_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by abelbraaksma** [comment]
Perhaps worth adding that often the wrong location is selected, especially with DU types when they have the same name as the case. Also, from context menu it is slow, up to 20 seconds, but select it from the tooltips, it's immediate.

**Comment by cartermp** [comment]
Closing this out as no concrete repro was produced, and I can verify that project-to-project Go to Definition works (including now with recursive types).
