### ISSUE TITLE
Disallow whitespace in unit literal to conform to language spec

### ISSUE THREAD

**Issue by moonPtr** [Microsoft/visualfsharp#4793]
According to §4.3 of the spec found at http://fsharp.org/specs/language-spec/4.0/FSharpSpec-4.0-latest.pdf,
the unit literal () may not contain any white space; however, to fsc/fsi (                    ) is a valid unit literal, and so is this monstrosity: 
![code_2018-04-27_22-47-35](https://user-images.githubusercontent.com/32428601/39384409-04091438-4a6d-11e8-8d3a-2d5c68516e31.png)

**Comment by abelbraaksma** [comment]
Closed why? You don't consider it a big anymore? Personally I think, even if it is a bug, it would probably be a breaking change, so we should retrospectively fix the spec instead.

**Comment by moonPtr** [comment]
Closed because I opened this late night and felt kinda dumb about it the next day
Guess I'll reopen because allowing newlines in unit literals definitely should be disallowed

**Comment by KevinRansom** [comment]
@dsyme spec change required I would think.

**Comment by dsyme** [comment]
Yes, we will just clarify the spec for this. The unit literal is just the LPAREN then RPAREN tokens ignoring whitespace tokens
