### ISSUE TITLE
Scripts and .NET Standard 2.0 - Editor shows reference error in F# code while code is correct and runs

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/visualfsharp#4797]
When adding references for a script file, I encounter an error that pops up in the editor, but it is possible to run the code in FSI?

See attachment.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/241500/editor-shows-reference-error-in-f-code-while-code.html
VSTS ticketId: 607352_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by cartermp** [comment]
This is an issue (based on info in the VSTS report) where references to .NET Standard components in an F# script file will produce an error in a script file, but execute in F# interactive.

**Comment by cartermp** [comment]
Related to #3309 but not the same issue

**Comment by cartermp** [comment]
Closing this out in favor of #2407, which is the main issue tracking .NET Core (and Standard) support for FSI and scripting.
