### ISSUE TITLE
F# IntelliSense doesn't respect the EditorBrowsable attribute

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#48]
Opened by ovatsus at CodePlex

EditorBrowsable(EditorBrowsableState.Never) doesn't work for F#. We can use CompilerMessageAttribute("message", IsHidden=true), but it's not exactly the same as it will also generate a warning message when that member is used. It also doesn't apply to C#, so that means we always have to have 2 attributes to achieve the same thing when working on libraries intended for use by both C# and F#

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2206

/cc @ovantus
