### ISSUE TITLE
Another VS2015 RC with no F# template

### ISSUE THREAD

**Issue by Sehnsucht-Fr** [Microsoft/visualfsharp#480]
I downloaded VS2015 Community RC (english via ISO)  and "custom installed" with no "optional feature" at all
Everything seemed fine until I clicked on "New Project" where F# template or not even listed
![capture d ecran 96](https://cloud.githubusercontent.com/assets/12448828/7925337/bdd17dcc-08c3-11e5-85c0-e325666c1c8c.png)

# Additional information :
running fsi.exe or fsc.exe with the "Developer Command prompt for VS2015" works fine ; both are version "14.0.22810.0" (in the contrary with "cmd.exe" both are "not found")
I'm using Windows 8.1 Profesionnal and my region settings is French (France)
Inside Tools -> Extension and Updates there is a "Visual F# 4.0" installed as shown
![capture d ecran 97](https://cloud.githubusercontent.com/assets/12448828/7925542/1fed74d2-08c6-11e5-8ddc-450ac2e08e0f.png)

# Here are the "About" information :
>Microsoft Visual Studio Community 2015 RC
>Version 14.0.22823.1 D14REL
>Microsoft .NET Framework
>Version 4.6.00057
>
>Installed Version: Community
>
>Visual Basic 2015 RC   00269-30000-00001-AA124
>Microsoft Visual Basic 2015 RC
>
>Visual C# 2015 RC   00269-30000-00001-AA124
>Microsoft Visual C# 2015 RC
>
>Visual C++ 2015 RC   00269-30000-00001-AA124
>Microsoft Visual C++ 2015 RC
>
>Visual F# 2015 RC   00269-30000-00001-AA124
>Microsoft Visual F# 2015 RC
>
>Application Insights Tools for Visual Studio Package   1.0
>Application Insights Tools for Visual Studio
>
>Common Azure Tools   1.4
>Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
>
>GenerateUnitTest   1.0
>Generates unit test code for methods in classes under test.
>
>Microsoft Azure Mobile Services Tools   1.4
>Microsoft Azure Mobile Services Tools
>
>NuGet Package Manager   3.0.0
>NuGet Package Manager in Visual Studio. For more information about NuGet, visit >http://docs.nuget.org/.

I also saw the other similar subject but didn't understood if it were applicable to my problem

**Comment by KevinRansom** [comment]
@Sehnsucht-Fr 

Hi, this is fixed in the soon to be released product, unfortunately the localized vsix has an invalid format.  And the templates do not load on Localized Visual Studios.  So this is the same as the existing issue.

For example: https://github.com/Microsoft/visualfsharp/issues/475

**Comment by Sehnsucht-Fr** [comment]
Except it's not a localized visual studio as stated at beginning of previous post ; it's an english/neutral visual studio on a localized os/system.

**Comment by xenocons** [comment]
hello, as a temporary work around, try installing the latest F# build from https://github.com/Microsoft/visualfsharp/releases/tag/V4.0.Preview-06.03.2015, I had a similar issue and this seemed to resolve it (might be a false positive as I also repaired VS2015RC before)

**Comment by Sehnsucht-Fr** [comment]
Thank you xenocons ; I was nearly ready to only use notepad++ and the command line but I just installed that preview and finally got them !
