### ISSUE TITLE
Installing MSBuild tools for VS2017 fails to find reference FSharp.Core 4.4.0.0

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#4801]
After installing the MSBuild Tools for VS2017 RTM, and running it on a project configured for FSharp.Core 4.4.0.0, it doesn't find that reference.

### Repro steps

1. On a clean Windows Server (mine was previously configured for VS 2015 build tools)
2. Install MS Build 2017 tools (from: https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017), select F# in the components (it is not selected by default).
3. Compile a Visual Studio *.sln file that is configured for FSharp.Core 4.4.0.0

![image](https://user-images.githubusercontent.com/16015770/39406527-19408a9c-4bb8-11e8-9e05-9f1627bc81db.png)

### Expected behavior

Should find the FSharp.Core 4.4.0.0 reference and compile successfully.

### Actual behavior

Did not compile, it shows an error in the build log as follows:

> [ResolveAssemblyReference] C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(2052, 5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

The full log of the resolving assembly is a few dozen of lookups that all fail with "file does not exist", like these:

```text
[ResolveAssemblyReference] For SearchPath "{TargetFrameworkDirectory}".
[ResolveAssemblyReference] Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\FSharp.Core.winmd", but it didn't exist.
[ResolveAssemblyReference] Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\FSharp.Core.dll", but it didn't exist.
[ResolveAssemblyReference] Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\FSharp.Core.exe", but it didn't exist.
[ResolveAssemblyReference] Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\FSharp.Core.winmd", but it didn't exist.
[ResolveAssemblyReference] Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\FSharp.Core.dll", but it didn't exist.
[ResolveAssemblyReference] Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Facades\FSharp.Core.exe", but it didn't exist.
```

Of interest are lines like these, which suggest it finds an older version, but not the 4.4.0.0 one:

```text
 Considered "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\PublicAssemblies\FSharp.Core.winmd", but it didn't exist.
[ResolveAssemblyReference]         Considered "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\PublicAssemblies\FSharp.Core.dll",
			but its name "FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
			didn't match the expected name "FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
```

### Known workarounds

None yet, though I will try to install the compiler tools from #2553, or otherwise install the FSharp.Core 4.4.0.0 manually. The odd thing is, before I installed the VS2017 Build Tools, these projects just compiled.

### Related information 

* MS Windows Server 2016
* with MS Build Tools 2017, v. 15.6.7
* Installed: .NET 4.5, 4.6.x and 4.7.x (not 4.7.2, which is not RTM yet for build tools)
* Indications of severity: I think this is quite severe, as it looks like F# 4.0 may not be build if you install the MS Build tools + F#, which I think would be a regression?

Perhaps of note, the `fsproj` file contains this:

```xml
<Reference Include="FSharp.Core, Version=$(TargetFSharpCoreVersion), Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
```

Where `TargetFSharpCoreVersion` is set to 4.4.0.0. This seems to be the F# 4.0 way of doing things, and I remember vaguely reading somewhere that the suggested way of doing this now is to use NuGet or Paket.

 I am attempting that currently as a workaround, but _so far it yields the same error_. It looks as if the MSBuild task is configured to look in the system locations, not in the packages dir. And FSharp.Core is nowhere to be found. I will attempt to change the MSBuild task by hand.

I also read this (#4517) to use `AutoGenerateBindingRedirect` in each fsproj file, but that has no effect, still the same error.

**Comment by abelbraaksma** [comment]
Some observations and a workaround:

* Tried `AutoGenerateBindingRedirect` in all projects, had no effect
* Tried previous plus `DisableImplicitFSharpCoreReference` in all projects, had no effect
* Tried referencing FSharp.Core.dll 4.4.0.0 through NuGet, had no effect (this one was most surprising to me)
* Tried reinstalling MSBuild 15.6.7, had no effect
* Checked presence of correct version of FSharp.Core.dll 4.4.0.0, it was available on several locations, including the proper version in `C:\Windows\System32\config\systemprofile\.nuget\packages\fsharp.core\4.0.0.1\` and the local-to-solution NuGet package folder.

I then noticed this structure in the Program Files x86 dir:

![image](https://user-images.githubusercontent.com/16015770/39407862-45bc62de-4bcd-11e8-8cd4-5a86802530cd.png)

This hinted to the absence of F# 4.0 libraries. So I googled for F# 4.0 build tools and [found this link](https://www.microsoft.com/en-us/download/details.aspx?id=48179), after which the same directory looked like this:

![image](https://user-images.githubusercontent.com/16015770/39407871-6f677790-4bcd-11e8-8f40-1367de508716.png)

Running the builds again now worked as expected.

What strikes me as odd, though, is that a few hours ago, prior to installing the MSBuild 2017 tools, everything just worked with FSharp.Core 4.4.0.0. After installing the tools, it stopped working. I don't know whether that directory was removed by the installer, or that the previous tools used a different assembly resolving algorithm. Be as it may, after installing MSBuild 2017, things break.

**Comment by dsyme** [comment]
I'm very surprised that referencing the nuget package didn't work.  That's certainly how we'd recommend you reference FSharp.Core from now on.

**Comment by dsyme** [comment]
Note we would expect to find the FSHarp.Core 4.4.0.0 reference assembly at

     C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.0.0

I don't know which specific component installs that however, @brettfo may know

**Comment by cartermp** [comment]
As an aside, I've rarely observed MSBuild 15 working for F# 4.0, so much so that I've adopted a mantra of "always use F# 4.1 with MSBuild 15". Not sure if we even deploy this binary. We should if we don't. And it's a bit troubling that it couldn't resolve from a NuGet package.

**Comment by abelbraaksma** [comment]
@cartermp, I think we don't, it wasn't installed after I installed msbuild with F# selected. In fact, I think it makes sense to install previous core assemblies, or make it at least optional. It would certainly help the out of the box experience.

Yes, the nuget failing for 4.4.0.0 is rather odd.

**Comment by dsyme** [comment]
Note the nuget you want is this one: https://www.nuget.org/packages/FSharp.Core/4.0.0.1

**Comment by abelbraaksma** [comment]
@dsyme, yes, that's the one linked in my project that didn't compile when only msbuild is installed.

**Comment by cartermp** [comment]
Closing this one out, as VS 2017 15.9.x has MSBuild and FSharp.Core deployed side-by-side, and the binary should always be found in this case. Additionally, with the move out of a machine-deployed binary and NuGet, the question of how to acquire MSBuild is now answered by NuGet uniformly.

**Comment by KevinRansom** [comment]
I believe this was a bug, where we deployed fsharp.core 4.4.3.0 into the location we expected to find 4.4.0.0.
Anyway it was fixed a long time ago.
