### ISSUE TITLE
Question: Is the F# tokenizer slow?

### ISSUE THREAD

**Issue by matthid** [Microsoft/visualfsharp#4808]
While trying to improve start times from FAKE and profiling the application, I noticed that the tokenizer alone takes 300ms for the 1200 lines script file.

#### Repro steps

measure and tokenize https://github.com/fsharp/FAKE/blob/master/build.fsx 

#### Question:

Is there potential in improving that time or was this already optimized by someone? Does somebody already know some "quick gains" in that area?

**Comment by dsyme** [comment]
> Is the F# tokenizer slow? 

It is more resource intensive than most tokenizers because of the indentation-aware lexing rules. But it is fast enough to use in the IDE.

> Is there potential in improving that time 

Yes... there always is

> was this already optimized by someone? 

Yes...

> Does somebody already know some "quick gains" in that area?

Not really....  You just have to profile, improve, profile, improve.

**Comment by dsyme** [comment]
Closing but by all means please work on the performance of this.
