### ISSUE TITLE
Type Provider with optional parameter with type option - wrong signature in tooltip

### ISSUE THREAD

**Issue by radekm** [Microsoft/visualfsharp#481]
I used FSharp.TypeProviders.StarterPack to create the following provider:

``` fsharp
namespace Samples

open System.Reflection
open FSharp.Core.CompilerServices
open FSharp.Quotations
open ProviderImplementation.ProvidedTypes

[<TypeProvider>]
type public SampleProvider() as this =
    inherit TypeProviderForNamespaces()

    let thisAssembly = Assembly.GetExecutingAssembly()
    let rootNamespace = "Samples"
    let baseTy = typeof<obj>

    let sampleType = ProvidedTypeDefinition(thisAssembly, rootNamespace, "SampleType", Some baseTy)
    let optParam = ProvidedParameter("x", typeof<option<string>>, optionalValue = null)
    let m = ProvidedMethod("Foo", [optParam], typeof<unit>)
    do
        m.IsStaticMethod <- true
        m.InvokeCode <- fun qs ->
            <@@
                printfn "Hi from SampleType %A"
                    %%(Expr.Coerce(qs.Head, typeof<obj>))
            @@>
    do sampleType.AddMember(m)

    do this.AddNamespace(rootNamespace, [sampleType])

[<TypeProviderAssembly>]
do ()
```

The provider provides type `Samples.SampleType` with static method `Foo`. The tooltip with a signature for this method shows that the method has a single optional parameter `x` with type `string`:

![tooltip](https://cloud.githubusercontent.com/assets/518912/7930282/5fe9cb44-0907-11e5-968f-ce33ed2895e5.png)

But if you enter a string then you see error that the type is `Option<string>`

![error](https://cloud.githubusercontent.com/assets/518912/7930296/85f750fe-0907-11e5-8a29-9e499a5180b4.png)

So I think that the tooltip with the signature should contain `?x : Option<string>` instead of `?x : string`.

BTW why do the names `Unit` and `Option` start with uppercase letter?

**Comment by dmitry-a-morozov** [comment]
Also it would be nice if F# compiler will allow visually distinguish between F# optional parameters and .NET parameters with default value. Ideally it will show parameters with default values the same way Visual C# tools do e.g. ?x: Option<string> = None or ?x: int = 42

**Comment by dsyme** [comment]
> So I think that the tooltip with the signature should contain ?x : Option<string> instead of ?x : string.


Closing this old issue - it is by design to show "string" in ``?x : string``
