### ISSUE TITLE
FSharp.Core assembly versions questions

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#4840]
We currently have package references to FSharp.Core pinned to `4.1.*` versions and according binding redirects for FSharp.Core to `4.4.1.0`. The 4.1.19 package has a different assembly version, namely `4.4.3.0`, which as it looks like wasn't stated anywhere. Why does FSharp.Core 4.1.19 package use assembly version 4.4.3.0 instead of 4.4.1.0?

Recent FCS nuget packages have 4.1.18 as dependency but FSharp.Compiler.Service.fsproj has it also pinned to `4.1.*` which resolves to `4.1.19` from `dotnet-core` feed defined in https://github.com/Microsoft/visualfsharp/blob/4d75decc7b1e71879c305539c7b8af0f15041a04/NuGet.Config#L14 and, thus, built against `4.4.3.0` assembly. However, net45 assembly in FCS NuGet package references `4.4.1.0`. Why does the assembly from NuGet reference a different assembly version?

**Comment by KevinRansom** [comment]
@auduchinok 

There was a long compiler thread for this somewhere, but the short answer is.

The FSharp.Core 4.1 package train, packages the FSharp.Core along with all of the portable FSharp.Core versions.  It is for users who built projects on the old OSS project scaffolding and want to update to the most recent FSharp.Core without rearchitecting their projects.

The FSharp.Core 4.2 + package train has just the desktop and netstandard FSharp.Core, it is for new projects.

Shortly we will move to 4.5, and the language/core version numbers will be aligned once more, and hopefully we can keep them aligned.

**Comment by auduchinok** [comment]
@KevinRansom Thank you. I remember the long discussion, yes, I guess I've just missed the moment when we updated the assembly version in `4.1.*` packages which could be a surprising thing to discover for people who previously used binding redirects to `4.4.1.0` just fine.
Anyway, if people used `4.1.*` packages without pinning/locking a particular version they'd already face problems and there's not much sense to change it once again few months later.
