### ISSUE TITLE
Breakpoints are all inactive on a asp.net core app created from the template

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#4847]
VS 15.7, vanilla ASP.NET Core app:

![image](https://user-images.githubusercontent.com/873919/39714394-98217738-5232-11e8-830f-dcac12080e7c.png)

**Comment by vasily-kirichenko** [comment]
It's started working after terminating the debug session and restarting it again:

![image](https://user-images.githubusercontent.com/873919/39714460-cf520f42-5232-11e8-92e9-27b04e7fe002.png)

**Comment by vasily-kirichenko** [comment]
So, the scenario is:
* create a project
* hit F5 without opening any file
* breakpoints are inactive
* terminate the debug session
* hit F5 again (having the controller file open)
* debugging works

**Comment by cartermp** [comment]
Spoke with @vasily-kirichenko and it seems to have been after dirtying the editor by executing the unused opens code fix in a debug session

**Comment by vasily-kirichenko** [comment]
Yes, sorry for this.
