### ISSUE TITLE
Visual Studio 15.7 ASP.NET Core template

### ISSUE THREAD

**Issue by AviAvni** [Microsoft/visualfsharp#4855]
Can't create F# asp.net core project

![image](https://user-images.githubusercontent.com/1097246/39745176-318e465e-52af-11e8-9fb7-020d5b6416ff.png)

**Comment by vasily-kirichenko** [comment]
It works for me:

![image](https://user-images.githubusercontent.com/873919/39745842-2c1e2426-52b1-11e8-97cd-7c6e7243642d.png)

I had 15.6 installed, then installed 15.7 and removed 15.6. Everything works.

**Comment by AviAvni** [comment]
@vasily-kirichenko I did upgradefrom 15.6 to 15.7

**Comment by forki** [comment]
please try reinstall

2018-05-08 10:34 GMT+02:00 Avi Avni <notifications@github.com>:

**Comment by AviAvni** [comment]
I did repair not work also uninstall and install still the same issue

**Comment by vijayrkn** [comment]
@philhenning

**Comment by phenning** [comment]
@AviAvni, @vasily-kirichenko

It seems like there may be a version of the 2.0 F# templates being found that do not have an associated VS host file.

A few things to check:
1. From a normal command prompt, what does "where dotnet.exe" return?
2. Which SDKs versions are installed in the sdk folder where dotnet.exe was found?

Additionally, could you please check the following folder where  the VS Version matches the installed build:
%userprofile%\.templateengine\vs-2017.3\15.7.*

From that folder:
1. Could you please share the templatecache.json file.
2. Open the settings.json file in the same folder and list out the name of all the NuGet packages from the "Places" that contain "microsoft.dotnet.web.projecttemplate". You may not want to include the full paths in your response, as they may include your login name.

**Comment by AviAvni** [comment]
first 
![image](https://user-images.githubusercontent.com/1097246/39775081-730086be-5305-11e8-86eb-6cf72e1e3381.png)

second
templatecache.json
[templatecache.log](https://github.com/Microsoft/visualfsharp/files/1985172/templatecache.log)

settings.json
```
{
      "ParentMountPointId": "00000000-0000-0000-0000-000000000000",
      "MountPointFactoryId": "94e92610-cf4c-4f6d-aeb6-9e42dde1899d",
      "MountPointId": "a9e64809-c82f-4a03-bd09-06fed07b3d5a",
      "Place": "C:\\Users\\XXX\\.templateengine\\vs-2017.3\\15.7.27703.1-10d0add7\\packages\\microsoft.dotnet.web.projecttemplates.1.x.1.0.0-beta2-20170629-269.nupkg"
},
{
      "ParentMountPointId": "00000000-0000-0000-0000-000000000000",
      "MountPointFactoryId": "94e92610-cf4c-4f6d-aeb6-9e42dde1899d",
      "MountPointId": "d2436d12-aab6-4387-95cc-bef1628e4e26",
      "Place": "C:\\Users\\XXX\\.templateengine\\vs-2017.3\\15.7.27703.1-10d0add7\\packages\\microsoft.dotnet.web.projecttemplates.2.0.2.0.8.nupkg"
},
{
      "ParentMountPointId": "00000000-0000-0000-0000-000000000000",
      "MountPointFactoryId": "94e92610-cf4c-4f6d-aeb6-9e42dde1899d",
      "MountPointId": "9930ffd4-8936-4200-b00c-e35a76f12434",
      "Place": "C:\\Users\\XXX\\.templateengine\\vs-2017.3\\15.7.27703.1-10d0add7\\packages\\microsoft.dotnet.web.projecttemplates.2.0.1.0.0-beta2-20171004-309.nupkg"
}
```

I hope this help
@phenning

**Comment by phenning** [comment]
That confirms what I thought. You need to uninstall the 2.2.0-preview 1 SDK. After you do that, based on the other SDKs you have installed, you should see the F# templates in Visual Studio.

For more information:

https://github.com/dotnet/announcements/issues/57

**Comment by AviAvni** [comment]
thank you very much it fixed this issue
