### ISSUE TITLE
Open new Code Lens PR

### ISSUE THREAD

**Issue by realvictorprm** [Microsoft/visualfsharp#4868]
I haven't had enough time yet (or hung up on a different very interesting task) to open a new PR yet.
With this I'm tracking the task to open the PR and post if here if I'm running into a particular problem.

**Comment by realvictorprm** [comment]
sorry that I didn't take care of this yet :(

**Comment by KevinRansom** [comment]
@realvictorprm 

can you get us a pr labelling it as experimental, and with an off by default switch.

Thanks

Kevin

**Comment by realvictorprm** [comment]
@KevinRansom this time for master?

**Comment by cartermp** [comment]
Master is the branch now, yes.

**Comment by realvictorprm** [comment]
Thanks

Phillip Carter <notifications@github.com> schrieb am So., 13. Mai 2018,
17:50:

**Comment by cartermp** [comment]
Closing old issue, as CodeLens is now in for 15.8
