### ISSUE TITLE
.NET Core project template has "Generate tail calls" on by default in Debug configuration

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#4873]
![image](https://user-images.githubusercontent.com/873919/39868474-759f81aa-5462-11e8-9dc9-1251acf271fe.png)

**Comment by vasily-kirichenko** [comment]
The Full framework template has it turned off:

![image](https://user-images.githubusercontent.com/873919/39868701-6e3801a2-5463-11e8-9927-daede58315d0.png)

**Comment by dsyme** [comment]
@vasily-kirichenko Thanks, yes, either the template is wrong or the default settings in the .NET SDK are wrong.

**Comment by cartermp** [comment]
@KevinRansom would know more but I suspect this is it: https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.props#L40

**Comment by KevinRansom** [comment]
the props file is indeed the issue.  I can update it.

**Comment by cartermp** [comment]
#4876

**Comment by dsyme** [comment]
Fixed
