### ISSUE TITLE
`ignore ()` still creates a local variable

### ISSUE THREAD

**Issue by ChrSteinert** [Microsoft/visualfsharp#4884]
Implicitly ignoring a return value raises a warning, so we are trained to use `ignore (x)`. Alas, it seems that `ignore` does create overhead that is unexpected and unwanted.

#### Repro steps

Compile the following F# in a project that calls `test ()` somewhere with `dotnet build -c Release`:

```F#
let test () =
    let list = ResizeArray ()
    list.Contains "asd" |> ignore
    list.Contains "qwe"
    ()
```

#### Expected behavior

I would expect, that lines 2 and 3 of the functions body would emitt pretty much the same IL and none of the lines creates a local variable.

#### Actual behavior

I get the folloing IL in dnSpy:

```
.method public static 
	void test () cil managed 
{
	// Header Size: 12 bytes
	// Code Size: 32 (0x20) bytes
	// LocalVarSig Token: 0x11000003 RID: 3
	.maxstack 4
	.locals init (
		[0] class [System.Collections]System.Collections.Generic.List`1<string> list,
		[1] bool
	)

	/* 0x0000025C 730400000A   */ IL_0000: newobj    instance void class [System.Collections]System.Collections.Generic.List`1<string>::.ctor()
	/* 0x00000261 0A           */ IL_0005: stloc.0
	/* 0x00000262 06           */ IL_0006: ldloc.0
	/* 0x00000263 7201000070   */ IL_0007: ldstr     "asd"
	/* 0x00000268 6F0500000A   */ IL_000C: callvirt  instance bool class [System.Collections]System.Collections.Generic.List`1<string>::Contains(!0)
	/* 0x0000026D 0B           */ IL_0011: stloc.1
	/* 0x0000026E 06           */ IL_0012: ldloc.0
	/* 0x0000026F 7209000070   */ IL_0013: ldstr     "qwe"
	/* 0x00000274 6F0500000A   */ IL_0018: callvirt  instance bool class [System.Collections]System.Collections.Generic.List`1<string>::Contains(!0)
	/* 0x00000279 26           */ IL_001D: pop
	/* 0x0000027A 00           */ IL_001E: nop
	/* 0x0000027B 2A           */ IL_001F: ret
} // end of method Program::test
```

We can already see, that we have two local variables for this function. The list is expected, but the bool is not - neither is it needed. The call to `List<>.Contains` with the ignore spans from `0x263` to `0x26E`, and includes storing the return of the `List<>.Contains` call into the local variable. 
The line creating a compiler warning, without `ignore` (`0x26F` and `0x274`) does not store the result. I would assume that the `pop` at `0x279` simply discards the value.

I just looked at the in the end generated asm. At asm level, the two statements look to be perfeclty similar. So I would assume, that RyuJIT does some optimizations on top of the IL to make the likes equal in the end. Therefore I would say the impact is minimal to nothing.

![image](https://user-images.githubusercontent.com/9868229/39919786-0f9fa6f6-5515-11e8-92fe-b1c56e6618b1.png)

#### Known workarounds

Do not use `ignore`.

#### Related information 

Provide any related information 

* Win 10
* .NET Core 2.0.7
* fsc 10.1.0

**Comment by zpodlovics** [comment]
@ChrSteinert 

Last time I checked the ignore was compiled as a static function, that receive an argument. The following example will not create a local bool variable. You can use this as a workaround:

```fsharp
let test () =
    let list = ResizeArray ()
    let _ = list.Contains "zzz"
    ()
```

**Comment by dsyme** [comment]
Closing re comment

**Comment by kerams** [comment]
The assembly _can_ be different when `ignore` creates a value type local, for which JIT generates zeroing instructions.

https://sharplab.io/#v2:DYLgZgzgNALiCGEC2AfYBTGACCBLAJugKJhjoDG2AFAJRYC8AsAFBZtYDKAnhDOkgDoAIvD4AVXEnQCAcgHsA7ixYZsfXlloMW7HAWKkK1OigB8WXAHMAdnIBO6Zc1VZ1MAEya6TVuzyESMkovHXZaIA

The question is whether trying to fix this is worth the risks.
