### ISSUE TITLE
C#-style extension method on constrained type is used on types that don't match the constraint

### ISSUE THREAD

**Issue by Tarmil** [Microsoft/visualfsharp#489]
I have a C#-style extension method that applies to a constrained type `'a when 'a :> ThisType` (aka `#ThisType`). The compiler wrongly tries to invoke it on types that do not match the constraint:
```fsharp
open System.Runtime.CompilerServices

type ThisType() = class end

[<Extension>]
type ThisTypeExtensions =
    [<Extension>]
    static member SomeMethod<'a when 'a :> ThisType>(this: 'a, x, y, z) = x + y + z

let x = "test"
let y = x.SomeMethod(1, 2, 3)
// Expected: error FS0039: The field, constructor or member "SomeMethod" is not defined
// Got: error FS0193: The type 'string' is not compatible with the type 'ThisType'
```

In the above case it is fairly benign, because `x.SomeMethod(1, 2, 3)` is not a valid call anyway, so all we get is the wrong error message. However if `x` does have a valid method called `SomeMethod`, then overloading-related errors can arise and make it impossible to call this valid method:

```fsharp
open System.Runtime.CompilerServices

type ThisType() = class end

[<Extension>]
type ThisTypeExtensions =
    [<Extension>]
    static member SomeMethod<'a when 'a :> ThisType>(this: 'a, x, y, z) = x + y + z

type OtherType() =
    member this.SomeMethod (x: int) (y: int) = x + y

let x = new OtherType()
let y = x.SomeMethod 1 2
// Expected: successful call to OtherType.SomeMethod : int -> int -> int, giving y = 3
// Got: error FS0816: One or more of the overloads of this method has curried arguments.
//                    Consider redesigning these members to take arguments in tupled form.
```

**Comment by dsyme** [comment]
I don't think it's a bug - if you read the method overloading resolution rules in the F# language spec carefully (I know it's not easy), curried overloaded methods are rejected. So I don't yet see the specific case where there's a divergence from the specification.  This might be a language improvement suggestion to go to http://fslang.uservoice.com?

**Comment by Tarmil** [comment]
The problem is that there is no overload. The extension method doesn't apply to the type `OtherType`, only to `'a when 'a :> ThisType`; so it shouldn't even be considered when resolving the call.
