### ISSUE TITLE
F# compiler referenced assembly version is impacted by imported assemblies. 

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#4900]
Whilst working through the issues associated with:  #4850 I came across this.

When building VisualFSharp.UnitTests.dll we pass in a reference to Microsoft.Build.Framework.dll with the version # 15.0.0.0.

However, the build also references a bunch of VS dlls which transitively reference Microsoft.Build.Framework version # 15.1.0.0.

The F# Compiler emits the reference as 15.1.0.0 which seems wrong.

I introduced this when doing the coreclr port of the compiler.
https://github.com/Microsoft/visualfsharp/blob/master/src/absil/il.fs#L368

I remember adding this because we were generating metadata references to many different versions of System.Runtime.dll, due to the pick and mix nature of the dotnet framework at that time.

I'm not sure what the right behavior should be.  However, it seems that at least referencing the version of the dll passed in directly to the compiler, is preferable or at least more explainable.

The C# compiler uses the version of the passed in .dll, and relies on the build tools to generate binding redirects.

The C# compiler also has logic that produces build errors when the compiler uses the type from a referenced assembly that is higher than the version passed in on the command line.

I think it would make sense to go back to the old behavior, and see if we can make the build behavior match C#.

@dsyme does the above make sense.

**Comment by matthid** [comment]
Yes we basically discovered and discussed this in the related issue. Reality is these issues always come back.

But to understand the current situation better: What is the actual impact this time? What is the problem with the higher version number this time?

**Comment by KevinRansom** [comment]
@matthid.

We know (with a conviction that defies argument that the lower assembly version is the one we want to ship with the compiler, an api was removed in a later release that we still depend on).  We know that code path isn't accessed via the IDE which can survive with the higher version of the build assemblies.  Indeed must survive since VS has binding redirects that force us up to it.

In both examples, ours and the linked issues I consider the builds to be broken,  it doesn't stop me from wanting it to "work" without slamming in binding redirects that redirect downwards.  Indeed, making sure the build works correctly without automagically pulling in the higher versions required some tap-dancing.

At least in C# this scenario is mitigated by the compiler issuing an error complaining about the brokenness if you try to use a type gathered from the transitive dependency, ensuring that the developer has to deal with broken transitive references.  We do not do this.  Even then the scenario is still broken, if we use an API that requires the higher version assembly.

Its a judgement call which is the right fix, although the C# approach offers a little more control to the developer.  In short I think C# handles the brokenness better than we do, by surfacing an error in code that will obviously break. And in using the reference passed in.

**Comment by matthid** [comment]
> with a conviction that defies argument that the lower assembly version is the one we want to ship with the compiler, an api was removed in a later release that we still depend on

So issue is you want to release the compiler build against a specific version? But why what would it mean if the compiler was referencing a later version (what is the impact)?

> Its a judgement call which is the right fix, although the C# approach offers a little more control to the developer. In short I think C# handles the brokenness better than we do, by surfacing an error in code that will obviously break. And in using the reference passed in.

If the C# compiler really errors out if you use an API only available in the higher version it should just as well error out if you use an API no longer available in the higher version.

Also, historically (or technically) the full .net runtime loads multiple versions of an assembly just fine. I guess that is the real reason for the C# compiler behavior (it errors if you mix them but is happy otherwise). Problems only appear of you mix stuff or assume that only a single version is loaded (which you can achieve by using assembly redirects). I guess the F# compiler just never fully supported this (historic) behavior.

**Comment by dsyme** [comment]
I discussed this with Kevin and the plan we came up with was:

> One approach would be to pass in an "ILAssemblYRef --> ILAssemblyRef option" normalizing function into ilwrite.fs, which gets called each time an ILAssemblyRef is emitted.   The implementation of the normalizing function would be passed in from fsc.fs.  There's actually already a function to normalize ILScopeRef (basically the same thing) see https://github.com/Microsoft/visualfsharp/blob/707e712c23a3c804b567f3a1c09cb90ccf061dd8/src/fsharp/CompileOptions.fs#L1369 
> 
> I think this is the right solution. It may slow down ilwrite.fs a little so you might want to move your hash table hack from il.fs to the implementation of the normalizing function.
> 
> Note that we have that code because we do assembly ref normalization when static linking, but not in normal compilation. In static linking we do this normalization as a separate phase, a mapping rewrite over ILModuleDef that rewrites all ILScopeRef.  I'm not terribly keen to have such a rewrite phase added.  So adding it as a callback to ilwrite.fs avoids a complete extra rewrite phase. 
> 
> I guess you would add the normalizing callback to cenv in ilwrite.fs and call it here https://github.com/Microsoft/visualfsharp/blob/master/src/absil/ilwrite.fs#L718
