### ISSUE TITLE
The latest version of FSharp.Core 4.3.4 NuGet package contains unsigned FSharp.Core.dll

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#4911]
As I understand, the 4.3.4 package was re-uploaded 20th April:

![image](https://user-images.githubusercontent.com/873919/40050337-cfa7f9ee-583f-11e8-868e-16a6c6f403aa.png)

And now it contains unsigned FSharp.Code.dll

![image](https://user-images.githubusercontent.com/873919/40050366-eed01fea-583f-11e8-93f8-c41b2905f0fc.png)

Which causes the following error on Windows Server 2012R2:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.
SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
   --- End of inner exception stack trace ---
   at Program.main(String[] args)
```

**Comment by vasily-kirichenko** [comment]
A work around:

```cmd
reg DELETE "HKLM\Software\Microsoft\StrongName\Verification" /f
reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f
reg DELETE "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification" /f
reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f
```

**Comment by isaacabraham** [comment]
What I don't understand is why there are *four* different dates:

1. The date shown in the NuGet website screenshot i.e. sometime in February 2018.
2. The File Explorer date of 19th April.
3. Another one with Date Modified of 25th April.
4. Yet another one with Date Modified 10th May.

This would *suggest* (and I might be completely wrong here) that this wasn't a one-off but actually happened several times?

**Comment by vasily-kirichenko** [comment]
I strongly suspect the 4.3.4 version of the package has been uploaded several times, with different FSharp.Core.dll inside. It must not be done, ever. Packages must be immutable. 

@dsyme

**Comment by forki** [comment]
time to implement hashes in paket.lock

**Comment by khellang** [comment]
I just downloaded the `fsharp.core.4.3.4.nupkg` package from the NuGet gallery and opened it with 7zip (which shouldn't modify any dates).

This is what it looks like:

The NuGet gallery says `2018-02-12T18:45:53Z`

![image](https://user-images.githubusercontent.com/582487/40053315-1499effc-5841-11e8-974c-0f546d0a422e.png)
![image](https://user-images.githubusercontent.com/582487/40053321-1f9683a2-5841-11e8-98e2-dea8f6746067.png)

![image](https://user-images.githubusercontent.com/582487/40053407-69f59870-5841-11e8-96f3-aeb0169f84c2.png)

As you can see, it shows the same File Version as the "good" example above (`2018.2.9.3`).

**Comment by vasily-kirichenko** [comment]
@khellang what if you create a project and perform `paket update --force` and then explore the package in `packages` dir?

**Comment by davkean** [comment]
I've confirmed the same thing:

![image](https://user-images.githubusercontent.com/1103906/40054329-cf531a26-5887-11e8-8e5b-0916db55a5c1.png)

```
> sn -vf fsharp.core.4.3.4\lib\net45\FSharp.Core.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'C:\Temp\FSharp\fsharp.core.4.3.4\lib\net45\FSharp.Core.dll' is valid

```

**Comment by forki** [comment]
so the question is: where does this package come from?

**Comment by vasily-kirichenko** [comment]
![image](https://user-images.githubusercontent.com/873919/40054532-d3dd5140-584d-11e8-90bd-2d3cd56a04a9.png)

**Comment by vasily-kirichenko** [comment]
@forki yes :(

**Comment by vasily-kirichenko** [comment]
I've remembered. I've put FSharp.Core.xxx there to test @dsyme async stack traces on prod. Wow. Sorry, guys :(

**Comment by forki** [comment]
lol

still: we should put hashes into lock files...

**Comment by vasily-kirichenko** [comment]
Yes, I agree. I'm for SHA-256.

**Comment by baronfel** [comment]
I could try to revive my old PR, again. Maybe the mono/netcore inconsistencies I saw in the past have worked themselves out
