### ISSUE TITLE
Completion performance for multitargeted projects is slow

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#4914]
With SDK-style projects, if you multi-target, the experience is subpar due to very slow completion. With #4889 this is alleviated for a time, but after a while it will still invalidate caches and rebuild chunks of the world. The language service itself needs to properly understand the additional context that multitargeting requires.

Although this is not a regression, it is still quite a bad experience for people who multitarget. We recommend sticking to a single target if you don't require multitargeting.

**Comment by TIHan** [comment]
This should help it even more: https://github.com/Microsoft/visualfsharp/pull/4918

We will still type check multiple times, once per TFM, but that is what Roslyn does.

I tested this myself and now multi-targeting is much much better. Especially in Area51's case.

**Comment by TIHan** [comment]
This is now resolved.
