### ISSUE TITLE
Signing build failures in 'prodcon/fsharp/master/' - '20180517.01'

### ISSUE THREAD

**Issue by jcagme** [Microsoft/visualfsharp#4932]
There were a set of failures during this build. Here is a summary of these:
* https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1696168
  - **Agent:** DDMBLDW150
  - **Error log:** signtool : error : Zip Container 'net40\bin\VisualFSharpFull.vsix' has part 'FSharp.Data.TypeProviders.dll' which is not listed in the sign or external list...

@mmitche, @brettfo

**Comment by jcagme** [comment]
This was opened in core-eng so I just moved it from there to here manually since I cannot cut/paste across github accounts

**Comment by brettfo** [comment]
The linked build is using the deprecated build definition `FSharp-Signed-Through-Dev15.6`, but should instead use `FSharp-Signed`.

That being said I have a fix available that I'm testing now.  I'll report back once it's ready.
