### ISSUE TITLE
DocBug at MSDN: captured let-bindings in code quotations

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#494]
I'm not sure if this is the correct place to report this, but I couldn't find a better one...

The first example at https://msdn.microsoft.com/en-us/library/dd233212.aspx makes it look like this quotation

    let a = 2
    <@ a + 1 @>

will be represented with 'a' as a variable. But it looks to me like that is just a side effect of the fact that let bindings in modules are compiled into properties, and normal let bindings are always replaced with their values. My experimentation can be found here: http://stackoverflow.com/questions/30744024/when-are-let-bindings-in-code-quotations-replaced-with-their-values?noredirect=1#comment49544058_30744024

**Comment by latkin** [comment]
@billchi-ms, doc bugs are your domain.

The docs are perfectly correct.  The suggestion is that they elaborate a bit more on expected behavior? Or use a less "misleading" example?

**Comment by 0x53A** [comment]
Yes to both. While the example is technically correct, it only works in that specific context. (So it is a DocRequestForClarification, not a DocBug)

E.g. 

    let a = 2

    [<EntryPoint>]
    let main argv = 

        // exprCall has type unit.
        let exprCall = <@ a + 1 @>
        println exprCall
        0 // return an integer exit code


produces the expected output, 

    [<EntryPoint>]
    let main argv = 
        let a = 2
        // exprCall has type unit.
        let exprCall = <@ a + 1 @>
        println exprCall
        0 // return an integer exit code

does not. From a language-user perspective, this is really confusing. (It becomes clearer if you realize that the first `let a = 2` get compiled into a property of the implicit `Program` module)

I would love it if you could add the detailed description of Tomas Petricek (http://stackoverflow.com/a/30758268/1872399) to the msdn doc.

**Comment by billchi-ms** [comment]
Thanks for details!  As I told Lincoln on another thread, I can update this, but I won't get to it for 2-3 weeks with other stuff on my plate.  I know that sounds lame, and while this may only be a little effort, I need to focus on other stuff.

Thanks,
Bill

**Comment by dsyme** [comment]
Please fix this issue at https://github.com/Microsoft/visualfsharpdocs
