### ISSUE TITLE
FSharp.Core still referenced even with --noframework

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/visualfsharp#495]
Is there any way to not reference an `FSharp.Core.dll` when referencing another assembly that contains all the `FSharp.Core.dll` types? 

In the current scenario https://github.com/ctaggart/Paket/issues/1, I'm trying to wrap `paket.exe` with a PowerShell assembly. `paket.exe` has the `FSharp.Core.dll` merge in already. I'd like to build `Paket.PowerShell.dll` without a `FSharp.Core.dll` reference and only a reference to the `paket.exe`.

![image](https://cloud.githubusercontent.com/assets/80104/8075735/ae759f62-0ef8-11e5-9676-3ef64fd51f39.png)

I guess I should try writing `Paket.PowerShell.dll` in C# for troubleshooting. :(

**Comment by dsyme** [comment]
Hi @ctaggart - no, there's no way to do this.  

Best regards
don

**Comment by ctaggart** [comment]
Thanks @dsyme. That saves me a few hours of trying to make it work. I'll figure out another solution.
