### ISSUE TITLE
"IncrementalBuild object has already been disposed!" assertion

### ISSUE THREAD

**Issue by TIHan** [Microsoft/visualfsharp#4952]
I was testing out the latest master with a debug build and I got an assertion, `IncrementalBuild object has already been disposed!`. This came from IncrementalBuild.fs. I managed to have it occur fairly easily, just by using F# in VS normally; compiling and looking at code. I have been testing my NewFoom project which is entirely .NET Standard. Sometimes I get an assertion in CompileOps.fs, on `CheckDisposed` too, I believe they are related.

Not sure what might be causing this, but I think it was introduced when I added this commit: https://github.com/Microsoft/visualfsharp/commit/a1f2f807a6f302d4af77e440b69012e1c7c1f563 - not 100% sure though

**Comment by cartermp** [comment]
Yes, I've seen this a few times months and months ago. I don't believe that it was due to the recent work here, but agreed that it's good to get a repro

**Comment by cartermp** [comment]
This is an older issue that I haven't seen lately. Since much in the tools and compiler has changed since then, I'll close this out. We should file a new one with a repro when we see it.
