### ISSUE TITLE
Unacceptable completion performance on a project that has ProvidedTypes.fs(i) included

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#4961]
15.7.1

1. `git clone https://github.com/fsprojects/FSharp.Data.SqlClient.git`
2. `cd FSharp.Data.SqlClient`
3. `build Build`
4. Open `SqlClient.sln`
5. Open `DesignTime.fs` file
6. Go to line 347, for example
7. Add an empty line
8. Type "L" character
9. Wait for completion
10. It takes about 5 seconds to get the completion, devenv.exe consumes a lot of CPU
11. Delete the "L", repeat
12. Completion takes the same long time to appear

![untitled](https://user-images.githubusercontent.com/873919/40327291-02e71488-5d4b-11e8-9474-faac5d2fd2c5.gif)

Looking at the reactor logs:

* `DesignTime.fs` is checked instantly 
* Background checking blocks the reactor thread for more than 3 seconds

I think something wrong with caching background check results: the huge ProvidedTypes.fs seems to be rechecked every time on any `ParseOnCheckFileInProject` call.

```
Reactor: 77,745.864 BAD-BG-SLICE: >3s <-- background step, took 3982.1349ms
```

**Comment by vasily-kirichenko** [comment]
It turns out the problem is not caused by `ProvidedTypes.fs`. I've created a minimal repro: https://github.com/vasily-kirichenko/SlowTypecheckRepro

![_1](https://user-images.githubusercontent.com/873919/40357322-7c9e4a84-5dc4-11e8-909f-9af55324eaea.gif)

**Comment by forki** [comment]
can you please upload the repro?

**Comment by forki** [comment]
just saw you already created a git. never mind

**Comment by smoothdeveloper** [comment]
Maybe amount of overloads in some types of this assembly?

![image](https://user-images.githubusercontent.com/87944/40357709-ec55f9f6-5d71-11e8-87a6-7b98f17795fe.png)

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper maybe. 

Does anybody remember a packages with a type with LOTS of overloads?

**Comment by forki** [comment]
Yes overload resolution is sloooooow

Vasily Kirichenko <notifications@github.com> schrieb am Di., 22. Mai 2018,
12:53:

**Comment by vasily-kirichenko** [comment]
![image](https://user-images.githubusercontent.com/873919/40358524-2ee275dc-5dc8-11e8-9e2b-e953958e58d4.png)

**Comment by vasily-kirichenko** [comment]
![image](https://user-images.githubusercontent.com/873919/40359088-261b8f9a-5dca-11e8-972e-f3e552388674.png)

**Comment by vasily-kirichenko** [comment]
![image](https://user-images.githubusercontent.com/873919/40360722-b6849734-5dcf-11e8-93c6-f4b2080356dc.png)

**Comment by vasily-kirichenko** [comment]
Why `Visit` is non optional:

![image](https://user-images.githubusercontent.com/873919/40360834-0cd78d4e-5dd0-11e8-9def-6cd9a916ca5e.png)

even though it's virtual, not abstract:

![image](https://user-images.githubusercontent.com/873919/40360865-2332b514-5dd0-11e8-8402-320848c48dbf.png)

**Comment by forki** [comment]
can you see what part of isexactmatch is slowest?
from very quick review I can see that CompiledSigOfMeth is called with same arg in IsExactMatch and in IsPartialMatch

**Comment by forki** [comment]
and in IsTyparKindMatch

**Comment by vasily-kirichenko** [comment]
Yes, I've optimized away the double call of CompiledSigOfMeth. But I think the problem is that all _virtual_ methods are checked (> 1000), because for abstract classes all methods are marked as required to implement:

https://github.com/Microsoft/visualfsharp/blob/4eed66b39d0db4c3c2d63bf11e98f4ea3f30be4c/src/fsharp/MethodOverrides.fs#L461-L478

**Comment by vasily-kirichenko** [comment]
What if filter dispatch slots by minfo.IsAbstract = true?

**Comment by forki** [comment]
https://github.com/Microsoft/visualfsharp/pull/4970

**Comment by vasily-kirichenko** [comment]
With https://github.com/Microsoft/visualfsharp/pull/4971

![_1](https://user-images.githubusercontent.com/873919/40362512-621dabc6-5dd5-11e8-896c-e54be1b135f8.gif)

**Comment by vasily-kirichenko** [comment]
Found this https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/MethodOverrides.fs#L320
This is iteration over `dispatchSlots`, which is done inside `List.iter` over the same `dispatchSlots`, so for 1K overloads, `IsExactMatch` was called up to 1M times :(

**Comment by forki** [comment]
Looks like they are doing something like a discriminated union - just without DUs in the language.

**Comment by vasily-kirichenko** [comment]
Fixed via https://github.com/Microsoft/visualfsharp/pull/4971

**Comment by abelbraaksma** [comment]
I do have a project with an often used create method with over 300 overloads (use case interoperability with c# for otherwise inlined methods). Can I help with testing something? I do have issues with performance in general and completion, quickinfo and colouring specifically. It may be related.

**Comment by vasily-kirichenko** [comment]
@abelbraaksma just install the nightly vsix and try https://blogs.msdn.microsoft.com/dotnet/2017/03/14/announcing-nightly-releases-for-the-visual-f-tools/
