### ISSUE TITLE
Members hidden from IntelliSense still show up in tooltips

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#50]
opened by ovatsus at CodePlex

When we have a member like this: 
```fsharp
 [<EditorBrowsableAttribute(EditorBrowsableState.Never)>] 
 [<CompilerMessageAttribute("This method is intended for use in generated code only.", 10001, IsHidden=true, IsError=false)>] 
 member x._Print = x.XElement.ToString() 
```
 It doesn't show up on IntelliSense, but it still does show up on the tooltip: 

![e420bdd2-cccc-11e3-98d9-10f3bf7f73f4](https://cloud.githubusercontent.com/assets/5175830/5791899/2077786c-9eae-11e4-97e5-8bfe003d599e.png)

 If someone can point where this code is located I can take a shot at submiting a PR with a fix

**Comment by forki** [comment]
@ovatsus - could you please test/review #73? Thanks

**Comment by ovatsus** [comment]
Sure, I'll try test it soon

**Comment by ovatsus** [comment]
Coming a bit late, but tested it and it works as expected
