### ISSUE TITLE
Q: chunkBySize types 

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#500]
for my property based test I tried:

    let chunkBySize<'a when 'a : equality> (xs : 'a []) size  =
        let s = xs |> Seq.chunkBySize size
        let l = xs |> List.ofArray |> List.chunkBySize size
        let a = xs |> Array.chunkBySize size
        Seq.toArray s = a && List.toArray l = a

    [<Test>]
    let ``chunkBySize is consistent`` () =
        Check.QuickThrowOnFailure chunkBySize<int>
        Check.QuickThrowOnFailure chunkBySize<string>
        Check.QuickThrowOnFailure chunkBySize<float>

and I get a compile error. 

I think my test is wrong, but I noticed a type inconsistency:

List.chunkBySize is returning `'a list list`
Array.chunkBySize is returning `'a [] []`
but Seq.chunkBySize is returning `Seq<'a []>`

is this good?

**Comment by latkin** [comment]
This was discussed a bit: https://github.com/Microsoft/visualfsharp/pull/261#issuecomment-75662898

Also led to: https://github.com/Microsoft/visualfsharp/pull/272

**Comment by forki** [comment]
so my question is: should I ignore it (and close this issue)?

/cc @PatrickMcDonald

**Comment by latkin** [comment]
Yes, the signatures are by design.
