### ISSUE TITLE
Completion inside double quoted function name at declaration site

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5006]
![image](https://user-images.githubusercontent.com/873919/40544838-3e9f17e8-6032-11e8-80d8-4b003a125eff.png)

**Comment by abelbraaksma** [comment]
This doesn't happen only on declaration site. Whenever backticks are involved auto completion behaves erratic. It often adds extra backticks too, see #4602

**Comment by abelbraaksma** [comment]
> But on declarations it shouldn't pop up at all

Looks like declarations always show completion. I don't think that makes sense. In fact:

* Completion should not fire for declarations of members or let-bindings 
![image](https://user-images.githubusercontent.com/16015770/40570651-42b192ec-608d-11e8-8650-21ab2c7e1758.png)

* It should fire when typing argument names
![image](https://user-images.githubusercontent.com/16015770/40570707-cc8bd8c4-608d-11e8-8a39-586df356c4f4.png)

* It shouldn't fire when declaring generic type arguments
![image](https://user-images.githubusercontent.com/16015770/40570697-a67b4c50-608d-11e8-9154-fccfb60e97ba.png)

* It shouldn't fire when typing compiler directives (it doesn't)
* It shouldn't fire when typing namespace, module or type declarations
![image](https://user-images.githubusercontent.com/16015770/40570661-5737ccb8-608d-11e8-99b1-6e8c4f779e73.png)

Other improvements are:

* don't double-fire like in this OP, that is, in backticked names, it presently fires on individual words within the name, which, if you aren't careful, often leads to accidentally inserted auto-completion remnants.
* if it finds a correct backticked name, don't double the backticks (#4602)
* don't list the internal names of active patterns (see one of the screenshots above), they are hardly ever useful

Nice-to-have would be some sense of context. If the completion "knows" it is in a type-specification location, don't list anything but types, if it is in a match expression, don't show keywords or variables etc etc.

At the moment I find myself more often than not hitting Esc. Auto-completion is a wonderful thing, but it should work with you, not against you ;).

**Comment by vasily-kirichenko** [comment]
> don't list the internal names of active patterns (see one of the screenshots above), they are hardly ever useful (this was reported somewhere but I can't find it back)

APs are valid to call as functions, so their presence in the completion list is valid. However, they should be put to the very end of the list.

**Comment by vasily-kirichenko** [comment]
> Nice-to-have would be some sense of context.
There _is_ such a thing as completion context. For example, at attribute application site the list contains only attributes, modules and namespaces.

**Comment by vasily-kirichenko** [comment]
> Completion should not fire for declarations of members or let-bindings

Fixed in master.

> It should not fire when typing argument names

Fixed in master.

> It shouldn't fire when declaring generic type arguments

On your screenshot you miss `'` before `T`, hence the completion. There is no completion on `'T`.

> It shouldn't fire when typing namespace, module or type declarations

Cannot reproduce on master.

**Comment by vasily-kirichenko** [comment]
I've removed active pattern (as values) from completion https://github.com/Microsoft/visualfsharp/pull/4831#issuecomment-396376630

**Comment by abelbraaksma** [comment]
Great work! Did you also get a chance to look at the quoted names? It's your original issue. Also, when you have a quoted name with special characters like dash, dot, comma, colon,  space etc, you currently automatically select the first name from the dropdown list. I think it's best that for quoted names it doesn't fire at all our takes the whole quoted name into consideration (as opposed to only the last part)

**Comment by cartermp** [comment]
Can't reproduce the issue in the OP anymore with VS 2019 GA:

* with ``` `` ``` and typing
* with ``` ``foo`` ``` (typing out a known identifier with double ticks enclosing the whole decl
* with auto completion
* with forced completion (ctrl+space)
