### ISSUE TITLE
Property based testing revealed inconsistency in chunkBySize

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#501]
I wrote the following test:

    type Result<'a> = 
    | Success of 'a
    | Error of string

    let run f = 
        try
            Success(f())
        with
        | exn -> Error exn.Message

    let chunkBySize<'a when 'a : equality> (xs : 'a []) size =
        let s = run (fun () -> xs |> Seq.chunkBySize size |> Seq.map Seq.toArray |> Seq.toArray)
        let l = run (fun () -> xs |> List.ofArray |> List.chunkBySize size |> Seq.map Seq.toArray |> Seq.toArray)
        let a = run (fun () ->  xs |> Array.chunkBySize size |> Seq.map Seq.toArray |> Seq.toArray)
        s = a && l = a

    [<Test>]
    let ``chunkBySize is consistent`` () =
        Check.QuickThrowOnFailure chunkBySize<int>
        Check.QuickThrowOnFailure chunkBySize<string>
        Check.QuickThrowOnFailure chunkBySize<float>

which returned:
    
    Test 'FSharp.Core.PropertyTests.CollectionModulesConsistency.chunkBySize is consistent' failed: System.Exception : Falsifiable, after 10 tests (16 shrinks) (StdGen (1102101551,296021308)):
    [|0; 0; 0; 0; |]
    3
    	at <StartupCode$FsCheck>.$Runner.get_throwingRunner@349-1.Invoke(String message)
    	at <StartupCode$FsCheck>.$Runner.get_throwingRunner@339.FsCheck-IRunner-OnFinished(String , TestResult )
    	at FsCheck.Runner.check[a](Config config, a p)
    	at FsCheck.Check.QuickThrowOnFailure[Testable](Testable property)
    	D:\code\visualfsharp\src\fsharp\FSharp.Core.PropertyTests\CollectionModulesConsistency.fs(102,0): at FSharp.Core.PropertyTests.CollectionModulesConsistency.chunkBySize is consistent()
So it seems this one revealed inconsistent behaviour between List, Seq and Array (which still might be OK)

so I investigated the case and created this test:

    [<Test>]
    let ``chunkBySize of zeros`` () =
        let a = Seq.chunkBySize 3 [|0;0;0;0|]
        let b = List.chunkBySize 3 [0;0;0;0]
        let c = Array.chunkBySize 3 [|0;0;0;0|] 
    
        Assert.AreEqual(a = b && a = c) // false after converting to Array

which prints:

    seq [[|0; 0; 0|]; [|0|]]
    [[0; 0; 0]; [0]]
    [|[|0; 0; 0|]; null|]

so where is this null coming from.

**Comment by latkin** [comment]
Nice find!

**Comment by PatrickMcDonald** [comment]
:+1:  :disappointed:

**Comment by forki** [comment]
@PatrickMcDonald any ideas why this null is introduced?

**Comment by PatrickMcDonald** [comment]
I'm looking at it now, my first guess is that it could be some integer arithmetic bug.  `Array.chunkBySize 4 [|1..5|]` seems to work okay, so its definitely a very edgy case

**Comment by forki** [comment]
Yes. I'm pretty sure only random testing could have found this one

**Comment by forki** [comment]
[|0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0|]
   5

is another one

**Comment by FunctionalFirst** [comment]
From [here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/FSharp.Core/array.fs#L587)
````F#
if len % chunkCount <> 0 then
````
Shouldn't that be `chunkSize`?

**Comment by PatrickMcDonald** [comment]
@FunctionalFirst Indeed it should!

**Comment by PatrickMcDonald** [comment]
@forki This is definitely the incontrovertible evidence property based testing in visualfsharp needed! :dancer:

**Comment by dsyme** [comment]
:)
