### ISSUE TITLE
Getting FSharp.Core reference twice, yellow triangle of horror

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#5014]
If you have an existing .NET Framework project with old-style FSharp.Core references and you update it to have a new style NuGet reference, you will get two references to `FSharp.Core`. Sometimes these show up double, sometimes once, usually with the yellow triangle:

![image](https://user-images.githubusercontent.com/16015770/40575631-b919110c-60e8-11e8-93ee-42bcfb3b1eb6.png)

### Repro steps

Take a project that has a reference to FSharp.Core 4.0 old-style and add a NuGet reference. The old reference will not be replaced.

### Expected behavior

Should not happen in the first place, or otherwise expected a clear error when trying to add it, warnings / errors during build.

### Actual behavior

No warnings or errors, just the triangle of horror.

Source of fsproj shows this:

```xml
<Reference Include="FSharp.Core">
  <HintPath>..\..\_Solutions\packages\FSharp.Core.4.0.0.1\lib\net40\FSharp.Core.dll</HintPath>
</Reference>
<Reference Include="FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
  <Private>True</Private>
</Reference>
```

### Known workarounds

Edit the fsproj file by hand and remove the offending reference.

### Related information 

At least in VS 2017 15.7 Preview 6 (as single reference, but double in source) and 15.7.2 RTM (as double reference, see screenshot.).

I saw an earlier post on this triangle-issue, it may or may not be the same, but I hit this a few times recently. See PR of @KevinRansom #4990.

**On two projects it had the added effect of always being considered dirty, so on build, your source gets always rebuild, and on any change elsewhere, those bad projects will be rebuild internally leading to a sluggish editing experience**.

**Comment by cartermp** [comment]
@abelbraaksma I don't think this is related to #4990, as that was a targets file update for .NET SDK targets. The "yellow triangle of horror" was for .NET SDK-based projects.

Which reference is the one that is a bad reference after the action you took?

**Comment by abelbraaksma** [comment]
> Which reference is the one that is a bad reference after the action you took?

Ehm, @cartermp, I dunno, they are both the same (see screenshot). 

> Manually adding two references to two different dlls with the same name in the same project is not usually a good thing to do.

@KevinRansom: I wholeheartedly agree and I can't remember having done that.

> When updating the project to use nuget referencing you will need to eliminate the existing non nuget reference.

@KevinRansom, hmm, that sounds logical, but apparently it wasn't, at least not for me. I thought NuGet could update references? I'll be more careful. I believe that earlier it didn't even show the FSharp.Core twice (as in the screenshot), but did have the yellow triangle. There are no warnings when building, I find it very peculiar. If there's a conflict with libraries, I usually see a warning or error in the build log.

**Comment by cartermp** [comment]
@abelbraaksma I cannot reproduce this in VS 15.7:

* new .NET Framework console app
* Manage NuGet packages
* FSharp.Core 4.2.3
* Update to 4.5.2

In both cases, the FSharp.Core reference is replaced appropriately. Do you still see this?

**Comment by KevinRansom** [comment]
@abelbraaksma.

do you still see this, I think the issue was merely a failure to delete the existing FSharp.Core reference when manually editing the project to support nuget, which will likely result in two references.
I don't think that the VS nuget package manager recognizes this as a reference over which it has control.

````
<Reference Include="FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
  <Private>True</Private>
</Reference>
````

**Comment by abelbraaksma** [comment]
@KevinRansom, @cartermp, I haven't seen it in a while, but I've also fixed the original issue by editing the fsproj files, so while I'm not sure the root cause was fixed, I think it is save to close this.
