### ISSUE TITLE
Set VisualFSharpFull as default startup project

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#5027]
Today, the legacy FSharp.LanguageService project is the default project. This is clearly wrong.

I tried setting this as the default, inspired by https://github.com/dotnet/project-system/pull/3589

However, I don't think it's going to be as easy for us. Things I tried:

1. Setting [VisualFSharpFull](https://github.com/Microsoft/visualfsharp/blob/master/VisualFSharp.sln#L120) as the first project defined in the solution file
2. Doing (1) and making its solution folder the first one defined in the[ folder section of the solution file](https://github.com/Microsoft/visualfsharp/blob/master/VisualFSharp.sln#L576)
3. Doing (1) and (2) and removing what looks like the [unnecessary goop](https://github.com/Microsoft/visualfsharp/blob/master/VisualFSharp.sln#L9) the FSI projects define

No matter what I do, **FSharp.VS.FSI** ends up being the default (including after wiping the .vs folder on my machine).

Halp @davkean and @Pilchie

**Comment by Pilchie** [comment]
Could be an issue in the legacy F# project system?
