### ISSUE TITLE
Property based testing reveald possible inconsistency in exists2

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#504]
I created a property-based test:

    let exists2<'a when 'a : equality> (xs : 'a []) (xs2 : 'a []) f =    
        let s = runAndCheckErrorType (fun () -> Seq.exists2 f xs xs2)
        let l = runAndCheckErrorType (fun () -> List.exists2 f (List.ofSeq xs) (List.ofSeq xs2))
        let a = runAndCheckErrorType (fun () -> Array.exists2 f (Array.ofSeq xs) (Array.ofSeq xs2))
        s = a && l = a
    
    [<Test>]
    let ``exists2 is consistent`` () =
        Check.QuickThrowOnFailure exists2<int>
        Check.QuickThrowOnFailure exists2<string>
        Check.QuickThrowOnFailure exists2<NormalFloat>

and it fails with:

    Test 'FSharp.Core.PropertyTests.CollectionModulesConsistency.exists2 is consistent' failed: System.Exception : Falsifiable, after 1 test (0 shrinks) (StdGen (557866357,296021561)):
    [|0|]
    [||]
    <fun:Invoke@3253>
    	at <StartupCode$FsCheck>.$Runner.get_throwingRunner@349-1.Invoke(String message)
    	at <StartupCode$FsCheck>.$Runner.get_throwingRunner@339.FsCheck-IRunner-OnFinished(String , TestResult )
    	at FsCheck.Runner.check[a](Config config, a p)
    	at FsCheck.Check.QuickThrowOnFailure[Testable](Testable property)
    	D:\code\visualfsharp\src\fsharp\FSharp.Core.PropertyTests\CollectionModulesConsistency.fs(220,0): at FSharp.Core.PropertyTests.CollectionModulesConsistency.exists2 is consistent()

so I created a manual test:

    [<Test>]
    let ``exists2 is inconsistent`` () =
        let s = Seq.exists2 id [||] [|0|]
        let a = Array.exists2 id [||] [|0|]
        Assert.AreEqual(s,a)

this test fails since `Array.exists2` throws `System.ArgumentException : The arrays have different lengths`.

I'd assume `Seq.exists2` would throw the same error, but instead it returns false.

**Comment by forki** [comment]
please close it if this is expected. I know there are cases where Seq is expected to have different behaviour.

**Comment by PatrickMcDonald** [comment]
This was a design decision made I guess early in F# development, that List and Array in these cases would throw exceptions for unequal lengths and Seq doesn't (presumable to allow one of the seqs to be an infinite list)

See also map2, zip, etc.

**Comment by forki** [comment]
ok, then I will restrict the test for equal lengths.
