### ISSUE TITLE
Long format string causes bogus error in editor FS0001

### ISSUE THREAD

**Issue by asik** [Microsoft/visualfsharp#5041]
If you remove one character from the string, the bogus error message disappears.
```

let a username password = 
    sprintf """aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa%s%s""" username password
```

>     Error FS0001 This expression was expected to have type
>     ''a -> 'b -> 'c'
>     but here has type
>     'string'

Expected behavior:

should not have this error in the editor.

Visual Studio 15.7.2
Visual F# Tools 10.1 for F# 4.1 - 15.7.0.0.

Possibly related (?) Seems to be a different limit. Coloring re-appears only after several more characters are deleted from the string.
https://github.com/Microsoft/visualfsharp/issues/4268

**Comment by cartermp** [comment]
Looks like this is the same cause as #4268; i.e., compiler ranges are too small to support this. Closing as a duplicate, and this further motivates the PR #4476 which makes them considerably longer.
