### ISSUE TITLE
DivideByInt is defined as 'T -> int -> 'T, but List.average (etc) expects ('T * int) -> 'T

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#5057]
I was struggling a bit with getting my type to support `DivideByInt` to allow it to be used with `Lis.average` and the like. The documentation on [`List.average`](https://msdn.microsoft.com/visualfsharpdocs/conceptual/list.average%5b%5et%5d-function-%5bfsharp%5d) links to [`LanguagePrimitives.DivideByInt`](https://msdn.microsoft.com/visualfsharpdocs/conceptual/languageprimitives.dividebyint%5b%5et%5d-function-%5bfsharp%5d), which is not the expected type.

### Repro steps

Try ([from SO](https://stackoverflow.com/questions/46443198/how-to-implement-dividebyint))

```f#
type Pair = Pair of int * int with
    static member DivideByInt pair int = pair
```

### Actual/expected behavior

The above type should be allowed to be used with `List.average`, but it isn't. The typeinfo in the error only says that it expects `DivideByInt` without further information.

### Known workarounds

Use a tuple instead of curried arguments. Though this is different from what the internal types seem to use for `float`. 

Fix:

```f#
type Pair = Pair of int * int with
    static member DivideByInt(pair, int) = pair
```

### Related information 

Not really important, but note that the documentation also states that `DivideByInt` is implemented for `double`, but it isn't, the type does not support this, instead it uses compiler magic (I think) to get the method from `LanguagePrimitives`, perhaps using SRTP.

Perhaps the error and/or tooltip could be expanded to include the signature, and/or the docs could be updated?

**Comment by dsyme** [comment]
This is by design, or at least just a doc bug (please reenter on the new doc sit?)

You definitely have to use an explicit pair of uncurried arguments

**Comment by abelbraaksma** [comment]
Yes, i didn't mean to suggest it be differently implemented. I should've reported it on the doc git. I'll move it there.
