### ISSUE TITLE
Property based testing revealed inconsistency in Seq.item vs. Array.item

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#506]
`Seq.item 0 [||]` gives 

    System.ArgumentException : The input sequence has an insufficient number of elements.

and `List.item 0 []` gives similar (except for message):

    System.ArgumentException : The index was outside the range of elements in the list.

but `Array.item 0 [||]` gives 

    System.IndexOutOfRangeException : Der Index war außerhalb des Arraybereichs.

so even the type of the last error is different.

**Comment by PatrickMcDonald** [comment]
The use of IndexOutOfRangeException instead of ArgumentException was discussed in the [pull request on CodePlex](http://visualfsharp.codeplex.com/SourceControl/network/forks/mexx24/visualfsharp/contribution/7097#!/tab/comments)
