### ISSUE TITLE
DocBug at MSDN: not all keywords reserved for future use are listed

### ISSUE THREAD

**Issue by mexx** [Microsoft/visualfsharp#507]
At [Keywords](https://msdn.microsoft.com/en-us/library/dd233249.aspx) MSDN page there is a section about tokens that are reserved as keywords for future expansion of the F# language.

The table do not contain some of the keywords defined in both language specifications [F# 3.0](http://fsharp.org/specs/language-spec/3.0/FSharpSpec-3.0-final.pdf) and [F# 3.1](http://fsharp.org/specs/language-spec/3.1/FSharpSpec-3.1-working.docx)
* fori
* measure
* params
* recursive

There are some entries in the table not reserved in the language specification:
* event
* external

Those also do not produce "The identifier '%s' is reserved for future use by F#" warning.

**Comment by latkin** [comment]
@billchi-ms, doc bug for you

**Comment by enricosada** [comment]
added #761 because also `const` is here, but not in the [tests suite](https://github.com/Microsoft/visualfsharp/blob/a3dc921d93d1d68d3bc5861a2ee33dcc75c5cd5d/tests/fsharpqa/Source/Conformance/LexicalAnalysis/IdentifiersAndKeywords/E_ReservedIdentKeywords.fs)

**Comment by dsyme** [comment]
const can be used like this. I'm actually not sure it's documented anywhere.

```
[<Literal>]
let x = "data"
[<Literal>]
let y = "MarketDepth.htm"

type MarketDepth = HtmlProvider<const (x + "/" + y)>
```

**Comment by dsyme** [comment]
Please fix this issue at https://github.com/Microsoft/visualfsharpdocs
