### ISSUE TITLE
In state machines, too many variables are represented in the closure

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#5073]
I'm looking at `Microsoft.FSharp.Compiler.NameResolution.ResolveCompletionsInTypeForItem` in `FSharp.Compiler.Private.dll` using ILSpy.

The constructor is taking 23 arguments, but all the calls to it pass null to most of the arguments, the first ones are related to legit closure state, but some *may* look like symbols being erronously identified as closed over.

For example, `suppressedMethNames` is one of those parameters, but by the look of `ResolveCompletionsInTypeForItem`, it should (conceptually) just behave like a local variable; it makes sense to have it as part of the sequence builder state, but not as a constructor parameter.

Does the number of constructor parameter of a sequence builder constructor have performance implications?

Is there special consideration taken to reduce number of parameters and the state of the sequence builder to the minimum?

Is it possible to have more information about how IlxGen.GenSequenceExpr works? maybe that code should have some comments about design/implementation choices.

code for `Microsoft.FSharp.Compiler.NameResolution.ResolveCompletionsInTypeForItem`:
https://github.com/Microsoft/visualfsharp/blob/4cf7aaed221a79e3aa16c11b932527cc9c2f0e1d/src/fsharp/NameResolution.fs#L4061-L4228

Given the generated code and potential impact of having many members in the sequence builder, it might be better for clients to try to scope sequence expressions to smaller areas, which is not done in this specific code.

Sorry if I'm being too curious.

**Comment by dsyme** [comment]
We minimize the state for classes, for example, see the section on class representations in the F# spec (roughly speaking, if it's captured by a method it becomes a field).

However remember that for a `seq { ...} ` and `async { ... }`the execution is on-demand, nothing executes immediately and everything executes each time you do `GetEnumerator` and iterate.  

We could in theory make some things local to the state machine but it would be fairly difficult work.

**Comment by smoothdeveloper** [comment]
> We minimize the state for classes, for example, see the section on class representations in the F# spec (roughly speaking, if it's captured by a method it becomes a field).

I'm not sure which part of the spec you are refering to here, what keyword or section is it?

**6.3.11 Sequence Expression** explains how the calls to Seq module are mapped
**6.9.10 Evaluating Function Applications** explains how partial application will generate a closure over local values

I believe the aspect I'm discussing is a compiler implementation detail and might not be relevant to the spec.

BTW, the 4.1 spec has the TOC navigation broken, while it works in 4.0 version of the document.

> nothing executes immediately and everything executes each time you do GetEnumerator and iterate.

I understand, although the cost of constructor with large amount of arguments is paid any time you get a seq expression, even without iterating.

I don't know how the actual assembly generated code differs comparing between passing explicit values to a constructor and just assigning the defaults fields (the values we pass are the default ones whenever that constructor is called), nor if the amount of parameters has a significant impact, we end up having a bunch of `ldnull` at call site.

> We could in theory make some things local to the MoveNext in the state machine and not in the closure for the state machine state itself

Beside that, it seems that with some extra escape analysis, some of the things could be made local altogether, in the code I pointed `tc` parameter seems extraneous, `tinst` is closed over in a local lambda, but both never escape beyond a single iteration.

Also, there might be room for improvement regarding deconstructed tuples (and potentially other constructs), a 2 value tuple and both values are being passed to the constructor (same `tc` and `tinst` I'm talking above), we should only pass the tuple in this case, in case it is actually needed / escaping more than a single iteration.

Anyways, I'm just lurking around and trying to get some information about how the state machine is generated, there is potential codegen optimization to perform for optimized builds if we find a wizard to tackle that, thanks for the pointers!

**Comment by smoothdeveloper** [comment]
This is a small sample to play with:

```fsharp
type Foo = Foo | Bar
let getTuple foo = match foo with | Foo -> 1,2 | Bar -> 3,4
let seq1 () =
  seq {
     let a,b = getTuple Foo
     yield! [a;b]
  }
let seq2 foo =
  seq {
    match foo with
    | Foo ->
      let a,b = getTuple foo
      yield! [a;b]
    | Bar ->
      let c,d = getTuple foo
      yield! [c;d] 
  }
```

**Comment by dsyme** [comment]
Section 8.6.1.3:

> •	Value definitions that declared in classes are represented in compiled code as follows: 
> •	If a value definition is not mutable, and is not used in any function or member, then the value is represented as a local value in the object constructor.
> •	If a value definition is mutable, or used in any function or member, then the value is represented as an instance field in the corresponding CLI type.
> •	Function definitions are represented in compiled code as private members of the corresponding CLI type.


> Beside that, it seems that with some extra escape analysis, some of the things could be made local altogether, in the code I pointed tc parameter seems extraneous, tinst is closed over in a local lambda, but both never escape beyond a single iteration.

It's a good investigation. I think this is the most promising lead so far.

**Comment by smoothdeveloper** [comment]
@dsyme update from your branch #5097:

`ResolveCompletionsInTypeForItem` sequence builder constructor is down to 14 parameters from 24:

before
```csharp
(NameResolver ncenv
, NameResolutionEnv nenv
, Range.range m
, AccessibilityLogic.AccessorDomain ad
, bool statics
, Tast.TType typ
, Item item
, TcGlobals.TcGlobals g
, Import.ImportMap amap
, Tuple<Tast.EntityRef, FSharpList<Tast.TType>> patternInput
, FSharpList<Tast.TType> tinst
, Tast.EntityRef tc
, FSharpList<Infos.PropInfo> pinfosIncludingUnseen
, FSharpList<string> pinfoMethNames
, FSharpList<string> einfoMethNames
, Set<string, IComparer<string>> suppressedMethNames
, FSharpList<Infos.PropInfo> pinfos
, FSharpFunc<Infos.MethInfo, bool> minfoFilter
, FSharpList<Item> pinfoItems
, FSharpList<Infos.MethInfo> minfos
, Item v
, IEnumerator<Item> @enum
, int pc
, Item current)
```

after:
```csharp
(NameResolver ncenv
, NameResolutionEnv nenv
, Range.range m
, AccessibilityLogic.AccessorDomain ad
, bool statics
, Tast.TType ty
, Item item
, TcGlobals.TcGlobals g
, Import.ImportMap amap
, FSharpFunc<Infos.MethInfo, bool> minfoFilter
, FSharpList<Item> pinfoItems
, IEnumerator<Item> @enum
, int pc
, Item current)
```

removed:
```csharp
//, Tuple<Tast.EntityRef, FSharpList<Tast.TType>> patternInput
//, FSharpList<Tast.TType> tinst
//, Tast.EntityRef tc
//, FSharpList<Infos.PropInfo> pinfosIncludingUnseen
//, FSharpList<string> pinfoMethNames
//, FSharpList<string> einfoMethNames
//, Set<string, IComparer<string>> suppressedMethNames
//, FSharpList<Infos.PropInfo> pinfos
//, FSharpList<Infos.MethInfo> minfos
//, Item v
```

From cursory look, all the remaining items being held look correct as they span several `yield` or need closure over.

I'm very happy that sequence expression won't carry unecessary state anymore in the future, thanks a lot for getting to the core of the issue to fix it, it would have taken me much longer to even get on the good track...

**Comment by realvictorprm** [comment]
Pretty cool stuff happening here :) Thanks from me too!

**Comment by cartermp** [comment]
Closing as #5097 is merged.
