### ISSUE TITLE
Incorrect auto-completions when property has same name as a module/namespace in complex expression

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#51]
Ovatsus opened this at CodePlex

On this line: 
[https://github.com/fsharp/FSharp.Data/blob/a28caf225e4165acc0088ee2d24c470b139586f7/tests/FSharp.Data.Tests/JsonProvider.fs#L595](https://github.com/fsharp/FSharp.Data/blob/a28caf225e4165acc0088ee2d24c470b139586f7/tests/FSharp.Data.Tests/JsonProvider.fs#L595) 

InteliSense instead of showing the actual fields (ApprovedBy, Author, ..., SubredditId, Ups) shows fields related to SI units that I have no idea where they are coming from: 

![bdb19b00-ce69-11e3-94f8-6a4dd907172e](https://cloud.githubusercontent.com/assets/5175830/5791938/2695a09c-9eaf-11e4-93b1-fce98dfc8f90.png)

![3436284e-ce6b-11e3-8683-7c43661627f6](https://cloud.githubusercontent.com/assets/5175830/5791928/dafa6758-9eae-11e4-882a-aa4909e616d4.png)

Both compilation and fsi evaluation is fine, though 

For more details see  https://github.com/fsharp/FSharp.Data/issues/591

**Comment by dsyme** [comment]
This is a really old issue without a simple repro. The intellisense implementation has changed enough since this that I think we can close it and wait for it to be re-reported with a simpler repro
