### ISSUE TITLE
Discussion: to alleviate contributor pain with fsharpqa, make output files an artifact of CI part 2 

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#5111]
FSharp QA tests are notoriously hard to run locally (need to be familiar with perl and the test runner, long tu run etc.) and people most often just rely on CI to run those and fix them.

Given the poor output of those test results in jenkins and in order to shorten the feedback loop to allow contributors to fix their code, please allow downloading the test output as an artifact of the build.

**Comment by dsyme** [comment]
@smoothdeveloper Using this works well for me:

    .\build net40 test-net40-fsharpqa

For code generation tests this leaves the new .il files scattered around

**Comment by smoothdeveloper** [comment]
#5160 brings a small tool and few additions to the fsharpqa test documentation that solves this issue.
