### ISSUE TITLE
Completion on lambda parameter name

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5113]
![image](https://user-images.githubusercontent.com/873919/41031608-ba701fce-6989-11e8-9dd0-5026584709f7.png)

Completion should not appear at this point.

**Comment by smoothdeveloper** [comment]
it should appear but propose names matching the type names being passed in, or even binding patterns.

**Comment by cartermp** [comment]
@smoothdeveloper there are not names to offer when using partial application

```fsharp
module Beef =
    let hoopty =
        fun x y z -> x + y + z
```

I agree with @vasily-kirichenko that it's best to just not offer completion at that point. We can perhaps figure out ways to intelligently figure out named on a case-by-case basis, but I think it's more worthwhile to clean out all the places where we offer completion when we shouldn't be.

**Comment by vasily-kirichenko** [comment]
@smoothdeveloper 
> it should appear but propose names matching the type names being passed in, or even binding patterns.

It should appear _on the parameter name_??

**Comment by vasily-kirichenko** [comment]
Sorry, that's fixed in master, Rider is not updated yet.

**Comment by smoothdeveloper** [comment]
> @smoothdeveloper there are not names to offer when using partial application

When there is no name, we can fallback to type name, if you pass a `Doot` it would propose `doot`.

**Comment by smoothdeveloper** [comment]
@cartermp, see if that makes any sense:

![vs lambda completion typename](https://user-images.githubusercontent.com/87944/41055148-4ee7ad4e-6975-11e8-9e2b-f6fab5b10420.gif)

you could propose httpFunc based on the type of parameters (this is assuming the type is resolved, it generally is at the point you write the lambda, for example when you pipe to `veggies |> Seq.filter (fun <|>` you know that you have an object of type `Vegetable` so you propose `vegetable`.

**Comment by smoothdeveloper** [comment]
Notice also how the completion helps me pick `Exists` or `IsReadOnly` as expression in the lambda in that screen capture above, because the return value of this should be a boolean.

**Comment by cartermp** [comment]
The type is not resolved at that point. `next` could be anything as I am typing it. Only a post-hoc code fix to rename this could do what you are after.

**Comment by smoothdeveloper** [comment]
I'm seeing it as doable in this case:
```fsharp
let files = [FileInfo("some/path");FileInfo("some/path")]
files |> Seq.filter (fun <|>)
```

there you know you get handled a `FileInfo`, and that the lambda needs to return a `bool`.

**Comment by smoothdeveloper** [comment]
the lambda could even be proposed in autocomplete earlier 


```fsharp
let files = [FileInfo("some/path");FileInfo("some/path")]
files |> Seq.filter <|>
```

it would list first any function that takes FileInfo as last argument and return a bool, or propose creation of adhoc lambda `(fun fileInfo -> )` and put the cursor before the closing paren.
