### ISSUE TITLE
Using F# (FSharp.Core 4.3.4) Type Provider with .NET Core 2.1

### ISSUE THREAD

**Issue by AmosHason** [Microsoft/visualfsharp#5115]
We've just upgraded from .NET Core 2.0 to .NET Core 2.1. We're able to build and publish our project using Visual Studio 2017, but we're unable to do so using the CLI of .NET Core. The SDK version is 2.1.300, and this is what we get while running "dotnet publish":

error FS3053 : The type provider 'ExcelProvider.ExcelProvider+ExcelProvider' reported an error : The type provider constructor has thrown an exception: Exception has been thrown by the target of an invocation.
FSC : warning FS3005: Referenced assembly 'C:\Users\XXX\.nuget\packages\excelprovider\0.8.2\lib\ExcelProvider.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found

Is F# by any means incompatible with .NET Core 2.1? I know that .NET Core 2.1 has just been released last week, but I couldn't find anywhere a statement about F# being supported by .NET Core 2.1. The closest thing I found is an MSDN blog post which states that "starting with the release of .NET Core 2.0 and .NET Standard 2.0, all of the changes we have made for F# support in .NET Core 2.0 will be in-box with the .NET Core SDK and .NET Core CLI".

**Comment by dsyme** [comment]
> Is F# by any means incompatible with .NET Core 2.1? I know that .NET Core 2.1 has just been released last week, but I couldn't find anywhere a statement about F# being supported by .NET Core 2.1. The closest thing I found is an MSDN blog post which states that "starting with the release of .NET Core 2.0 and .NET Standard 2.0, all of the changes we have made for F# support in .NET Core 2.0 will be in-box with the .NET Core SDK and .NET Core CLI".


The ExcelProvider has not yet been updated to be able to run as part of the .NET Core toolchain.  Best to log an issue on the ExcelProvider site, until then use `msbuild` over your new project files instead of `dotnet`

**Comment by cartermp** [comment]
F# is fully supported on .NET Core 2.1. Closing as external.
