### ISSUE TITLE
FSI window should introduce a separate content type

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#512]
There was a bug in Paket.VisualStudio which caused strange colors in the fsi:

![image](https://cloud.githubusercontent.com/assets/57396/8351413/75352dbc-1b2d-11e5-856c-b81ffdeb150a.png)

see discussion in https://twitter.com/isaac_abraham/status/613731961136394240

This was fixed in https://github.com/fsprojects/Paket.VisualStudio/pull/61.

But the amazing @dungpa decided to turn the bug into a nice feature and created syntax highlighting for the fsi. See https://twitter.com/dungpa/status/613957668621950976

Now we think the fsi window should somehow introduce their own content type since otherwise the new VisualF#PowerTools feature will colorize all text windows.

**Comment by latkin** [comment]
@forki @dungpa sounds like a good idea, can you send a PR?

**Comment by dungpa** [comment]
How do you define `ContentType` in `vsintegration`? I couldn't find the definition of `F#` content type by a quick glance at the code base.

**Comment by latkin** [comment]
@dungpa not sure off the top of my head, sorry. It's possible it's defined internally.

**Comment by dungpa** [comment]
@latkin If you find a clue to do it here, please let me know. It shouldn't be too difficult to patch this.
