### ISSUE TITLE
No outlining and guidelines until file changed

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5135]
This is on current master:

![untitled](https://user-images.githubusercontent.com/873919/41120554-8bf063e6-6a9e-11e8-8325-74670bcf5a5d.gif)

**Comment by cartermp** [comment]
Can you provide repro steps? Is this upon opening a file? Is this after toggling the option?

**Comment by vasily-kirichenko** [comment]
@cartermp 
* open https://github.com/fsprojects/FSharp.TypeProviders.SDK
* open `ProvidedTypes.fs`
* close VS
* open VS

**Comment by majocha** [comment]
This happens to files opened on solution load #4622

**Comment by cartermp** [comment]
Aha, this is indeed a dupe of #4622

**Comment by majocha** [comment]
I can't repro this on current nightly. If I reopen the solution structure shows up quite fast in ProvidedTypes.fs.

**Comment by vasily-kirichenko** [comment]
@majocha I've just tested it on master - reproduced in ~80% runs.

**Comment by majocha** [comment]
@vasily-kirichenko yeah, the issue I've seen was also showing up most of the time but not always.
