### ISSUE TITLE
[15.8 Preview 2] Opening TextEditor->F#->Advanced crashes VS

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#5137]
![image](https://user-images.githubusercontent.com/4236651/41124650-e89b9b20-6aa2-11e8-97a8-a6d451d8994d.png)

![image](https://user-images.githubusercontent.com/4236651/41124813-68f9ecc2-6aa3-11e8-9940-48e2d645fb0b.png)

You should have gotten two watsons by now :)

According to the source, it should be mutable:

https://github.com/Microsoft/visualfsharp/blob/ae4e8e24723035f36c359d75db9e8bb762fafeaa/vsintegration/src/FSharp.Editor/Options/EditorOptions.fs#L48-L51

According to the disassembler, it isn't:

![image](https://user-images.githubusercontent.com/4236651/41126107-ba83dc94-6aa6-11e8-842c-93f00f33a3bb.png)

![image](https://user-images.githubusercontent.com/4236651/41126121-c89e5fe8-6aa6-11e8-8711-ad93a62a9063.png)

**Comment by cartermp** [comment]
This was wiped out when CodeLens was added. It's been fixed in #4941
