### ISSUE TITLE
Gettting a StackOverflowException on using `Seq.append` with `Seq.singleton`, but not in a rewrite with `yield/yield!`

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#5139]
This is a follow-up to the discussion in #5077 (no need to go over that to understand the issue here), and the discussion on [StackOverflow.com on the same](https://stackoverflow.com/questions/50748589/accidental-recursion-blowing-up-the-stack-with-seq-append).

In short, using `Seq.append` for state inside a `Seq.fold` (which is probably not required) blows up with a `StackOverflowException`. Since neither of these functions are presently defined recursively, I think this is an error in the library somehow.

### Repro steps

The following code is perhaps more idiomatic with Result.bind, but leaving it like this for clarity:

```f#
module Result =
    let unwindSeq (sourceSeq) =
        sourceSeq
        |> Seq.fold (fun state res -> 
            match state with
            | Error e -> Error e
            | Ok innerResult ->
                match res with
                | Ok suc -> 
                   // this causes SOE. Deep stack can be seen when run with smaller numbers
                    Seq.singleton suc
                    |> Seq.append innerResult
                    |> Ok
                | Error e -> Error e) (Ok Seq.empty)
```

Call it like this, for instance, will lead to a StackOverflowException:

```f#
Seq.init 1000000 Result.Ok     // throws StackOverflow
|> Result.unwindSeq
|> printfn "%A" 
```

### Expected behavior

There is no recursion, no `rec` defined anywhere. The code may be sub-optimal, but should finish in due time without exception.

### Actual behavior

In Debug build it takes a while, but then an SOE is thrown. In Release build the SOE is almost immediate. The Visual Studio debugger does not show any usable stacktrace when that happens in either build, so I don't know what part of FSharp.Core is causing this.

### Known workarounds

Surprisingly, using sequence CE's solves the issue, and performs significantly faster. So the question is, how does `Seq.singleton >> Seq.append` end up being so different?

This is a version of above function that can run with 10x as many items, finish in reasonable time and will **not** throw a StackOverflowExc:

```f#
module Result =
    let unwindSeq (sourceSeq) =
        sourceSeq
        |> Seq.fold (fun state res -> 
            match state with
            | Error e -> Error e
            | Ok innerResult ->
                match res with
                | Ok suc -> 
                    // this succeeds normally, no recursion appears
                    seq {
                        yield! innerResult
                        yield suc
                    } |> Ok
                | Error e -> Error e) (Ok Seq.empty)
```

### Related information 

SOE seen in both FSharp.Core 4.0 and 4.1 versions (FSharp.Core.dll 4.4.3.0, or 4.3.4.0 as it is called in NuGet, confusingly).

The example here may seem contrived, but this is a problem in production code where the stack is already under stress and the SOE comes up with as a little as a few thousand items in 64 bit builds.

**Comment by dsyme** [comment]
TBH I expect we won't fix this - there are places where things happen on the stack and very large chains of `Seq.append` mixed with other things aren't guaranteed not to consume stack when iterated.  I'd rather people just avoided explicit uses of Seq.append and learned to write and trust `seq { ... }` state machines (and I'm not at all surprised they are faster...)

**Comment by abelbraaksma** [comment]
@dsyme, tx for explaining, but I'm still wondering:

* Why isn't `Seq.append` itself implemented as `seq { yield! first; yield! next }`? If it is faster, and doesn't consume the stack, that seems a reasonable approach, no?
* While I understand that you can't anticipate every situation, I think people kind of expect that library functions are stable and won't blow up, and are generally a prime example of the best F# can offer, that is, with appropriate tail-recursion and tail-call optimization where necessary. In other words, if this is blowing up, isn't it perhaps a sign of a bug in the compiler, or other parts of the library than ` Seq.append` itself?

**Comment by abelbraaksma** [comment]
> since code like this is nearly always really bad code in any case and should be done another way 

That we can definitely agree on! :)

> I get an SO with all your versions.

You mean even with the `seq { yield... }` version? That one doesn't blow up for me, at least not last time.

I'll run them again and give you the command line (I didn't use FSI though, I just compiled and ran the program with default Release and Debug settings).

**Comment by dsyme** [comment]
> You mean even with the seq { yield... } version? That one doesn't blow up for me, at least not last time.

Yes

    debug\net40\bin\fsc a.fs && a.exe

**Comment by abelbraaksma** [comment]
>  Could you give exact command line used, runtime used etc. for a version that doesn't. 

@dsyme The `seq{..}` versions works for me in FSI with --optimize. I have these settings:

![image](https://user-images.githubusercontent.com/16015770/41172452-31ab888c-6b54-11e8-8462-3b1b39dc4a79.png)

* Windows 7, up-to-date
* VS2017 15.7.2, or VS2017 15.8.2 Preview

This version doesn't blow up:

```f#
module Result =
    let unwindSeq (sourceSeq) =
        sourceSeq
        |> Seq.fold (fun state res -> 
            match state with
            | Error e -> Error e
            | Ok innerResult ->
                match res with
                | Ok suc -> 
                    seq {
                        yield suc
                        yield! innerResult
                    } |> Ok
                | Error e -> Error e) (Ok Seq.empty)

```

I run it with this (with extra iterate of the result):

```f#
Seq.init 1000000 Result.Ok
|> Result.unwindSeq
|> fun x -> match x with Ok a -> Seq.iter ignore a; x
|> printfn "%A" 
```

And with "Send to Interactive" command.

When I replace it with this, I get the SOE:

```f#
module Result =
    let unwindSeq (sourceSeq) =
        sourceSeq
        |> Seq.fold (fun state res -> 
            match state with
            | Error e -> Error e
            | Ok innerResult ->
                match res with
                | Ok suc -> 
                    // this throws SOE
                    Seq.singleton suc
                    |> Seq.append innerResult
                    |> Ok
                | Error e -> Error e) (Ok Seq.empty)

```

**Comment by abelbraaksma** [comment]
And when I run it without `--optimize`, it still succeeds using `seq`, but not with `Seq.append`....

**Comment by abelbraaksma** [comment]
Oh crap, I see the difference. My test had:

```f#
seq {
    yield! innerResult
    yield suc
}
```

While the original post had:

```f#
seq {
    yield suc
    yield! innerResult
}
```
And **that** makes all the difference here! Using this last version I have the same as you have: SOE.

**Comment by abelbraaksma** [comment]
I'll close this, I understand now why it is _by design_, and I see the complexity and the little benefit of changing that.

**Comment by Xyncgas** [comment]
> TBH I expect we won't fix this - there are places where things happen on the stack and very large chains of `Seq.append` mixed with other things aren't guaranteed not to consume stack when iterated. I'd rather people just avoided explicit uses of Seq.append and learned to write and trust `seq { ... }` state machines (and I'm not at all surprised they are faster...)

What did you mean by trust seq{...} expression, how can you

**Comment by abelbraaksma** [comment]
>  seq{...} expression, how can you

He means to use `seq{..}` and not to use `Seq.append` in cases I described here. See my penultimate comment on an example what can throw SO and what doesn't.
