### ISSUE TITLE
There are two settings to turn on structure guidelines

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5191]
![image](https://user-images.githubusercontent.com/873919/41346748-34546f12-6f10-11e8-99b7-fdead7a753f6.png)

![image](https://user-images.githubusercontent.com/873919/41346702-14481b38-6f10-11e8-9b1a-f91e072e95e2.png)

**Comment by cartermp** [comment]
This is a bit by design, as the first setting is global for all languages. There may be a situation where someone wants it in C# but not F#. Additionally, C# has their own (more intricate) settings for block structure guidelines. Not sure if we'll change this.

**Comment by cartermp** [comment]
This is by design, as it should be configurable on a per-language basis. If the global configuration is removed, then things won't be different for us.
