### ISSUE TITLE
The .. operator in sequence expressions is slow

### ISSUE THREAD

**Issue by tpetricek** [Microsoft/visualfsharp#520]
I was doing some performance tweaks in Deedle and I noticed that writing `seq { for x in 1 .. 100 -> ... }` is fairly slow. I wrote a fairly simple implementation (http://fssnip.net/rJ) that seems to be doing the same thing, but is a lot faster: 

    // The following takes about 350-400ms on my machine
    seq { for x in 0L .. 5000000L -> 0 } |> Seq.length
    seq { for x in 0. .. 5000000. -> 0 } |> Seq.length
    seq { for x in 0L .. 10L .. 50000000L -> 0 } |> Seq.length
    seq { for x in 0. .. 10. .. 50000000. -> 0 } |> Seq.length

    // The following takes about 75ms on my machine
    seq { for x in range 0L 5000000L -> 0 } |> Seq.length
    seq { for x in range 0. 5000000. -> 0 } |> Seq.length
    seq { for x in rangeStep 0L 10L 50000000L -> 0 } |> Seq.length
    seq { for x in rangeStep 0. 10. 50000000. -> 0 } |> Seq.length

I guess the default F# implementation is the `..` operator [from here](https://github.com/Microsoft/visualfsharp/blob/fsharp4/src/fsharp/FSharp.Core/prim-types.fs#L5901), which seems to be doing _a lot_ of stuff.

<strike>AFAIK, the only thing that does not work correctly in my implementation is that doing `rangeStep 0 10 25` does not correctly stop at the end (because it is checking for equality at the end), but that can be quite easily added.</strike> [fixed] Are there any other things that I'm missing?

**Comment by forki** [comment]
how about writing fscheck tests, that show that the experienced behaviour is equal. you could fork https://github.com/Microsoft/visualfsharp/pull/502 where we already have infrastructure in place.

**Comment by tpetricek** [comment]
FsCheck will also find that my code does not work for `seq { for x in Int32.MinValue .. Int32.MinValue+1 -> x }` (and that it does not throw the right exceptions). 

But I'm curious if there is anything fundamental I'm missing, before I try to replacing the current implementation with a new one.

**Comment by forki** [comment]
related: https://github.com/Microsoft/visualfsharp/issues/377

**Comment by tpetricek** [comment]
BTW: I realized that my answer above might sound like I'm dismissing the idea to write FsCheck tests. That's not at all what I was thinking - I just accepted that so fast that I thought that's not even a question - and it made me think about `MinValue` and `nan` already :).

I was mainly curious if some of the interfaces etc. that are used there need to be there because of some compiler black magic.

**Comment by latkin** [comment]
Looks like new impl doesn't throw various exceptions on error cases, but that is pretty simple to add.

After a bit of testing, here are a few cases that are currently not working.  There are lots of corners in floating point that need to be considered, and overflow/underflow need to be detected.  `char` needs to be supported, too.

```fsharp
open System

let inline testSeq first second r = 
    match r with
    | Some(r) ->
        (seq { for x in first .. r .. second -> x },
         seq { for x in rangeStep first r second -> x })
    | None ->
        (seq { for x in first .. second -> x },
         seq { for x in range first second -> x } )


testSeq 1 10 (Some(Int32.MaxValue))  // new impl overflows, underflows
testSeq 1 10 (Some(-1))              // old impl returns 0-length seq, new impl underflows and gives huge seq
testSeq 3 1 None                     // old impl gives empty seq for a .. b with a < b
testSeq 1. 2. (Some(0.7))            // new impl gives out-of-region final value of 2.4
testSeq 1. 2. (Some(Double.Epsilon)) // old: [1.0] new: [1.0, 1.0, 1.0, 1.0, ... infinity]
testSeq 1. 2. (Some(Double.NaN))     // old impl detects NaN and throws, new impl doesn't
testSeq 1. 2. (Some(Double.PositiveInfinity)) // old: length-1 nan seq new: infinite nan seq
testSeq 1. 2. (Some(Double.NegativeInfinity)) // old: length-1 nan seq new: empty seq
// testSeq 'a' 'z' None              // does not compile with new impl
```

**Comment by dsyme** [comment]
Closing old discussion/perf-bug
