### ISSUE TITLE
German Language pack menu option for FSharp Interactive is not localized.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#5204]
German Language pack menu option for FSharp Interactive is not localized.

Probably the others are not localized too.

![image](https://user-images.githubusercontent.com/5175830/41444278-e3db40dc-6ff6-11e8-973c-d9ecae2e3c1f.png)

**Comment by KevinRansom** [comment]
More info:

In F# the translation of Interactive is Interactive.

     Google says it is Interaktive.  C# seems to have it as Interaktiv.

````
      <trans-unit id="fsiConsoleProblem">
        <source>A problem occurred starting the F# Interactive process. This may be due to a known problem with background process console support for Unicode-enabled applications on some Windows systems. Try selecting Tools-&gt;Options-&gt;F# Interactive for Visual Studio and enter '--fsi-server-no-unicode'.</source>
        <target state="translated">Beim Starten des F# Interactive-Prozesses ist ein Fehler aufgetreten. Ursache hierfür kann ein bekanntes Problem mit der Hintergrundprozess-Konsolenunterstützung für Unicode-aktivierte Anwendungen unter manchen Windows-Systemen sein. Wählen Sie "Tools" -&gt; "Optionen" -&gt; "F# Interactive für Visual Studio" aus, und geben Sie "--fsi-server-no-unicode" ein.</target>
        <note />
      </trans-unit>

````

And yet here the same word has a 'k;
````
      <trans-unit id="shadowCopyReferences">
        <source>Prevents references from being locked by the F# Interactive process</source>
        <target state="translated">Verhindert, dass Verweise vom interaktiven Prozess F# gesperrt werden</target>
        <note />
      </trans-unit>
````
I guess we should at least get the translators to confirm the spellings.

**Comment by forki** [comment]
It's really really really bad to translate names. Would you translate
"IntelliSense"? Or let's go a step further and translate "Microsoft" to
"Winzigweich" everywhere.

Proper fix is to revert the C# translation.

(if you insist to translate here, then please go with "F# interaktiv" - but
honestly: please don't)

Kevin Ransom (msft) <notifications@github.com> schrieb am Fr., 15. Juni
2018, 02:32:

**Comment by KevinRansom** [comment]
@forki, 

I have no expertise in this issue, I will merely notify the translation drivers about it and we can see where they land.  My intuition, is that you are correct about the names and they will end up doing a pass to ensure that the names are consistently 'not translated' unless agreements require them to be.


Kevin

**Comment by realvictorprm** [comment]
I'm biased here because I think translations are still important. Sure people think everyone can speak English in Germany but I can tell it's definitely not the case.

**Comment by KevinRansom** [comment]
@forki, @realvictorprm .

It turns out that for localization of terms the correct answer is: "It depends" and there is quite a lot of effort put into to decide for new terms whether to localize it or not.  I have asked for a write up to post here from our Localization expert.  So ... it's likely that in our case for Germany, F# is correct, and C# Interactive should be fixed.  However, it should at least be consistent ... and so the Turkish translations, actually have it both English and Turkish, indicating that it wasn't correctly identified as a Turkish term.

Anyway the translation folk have a bug to review the Term and ensure that it is appropriately English or translated, depending on the target language.

Anyway ... I was amused how hard detailed, a simple observation like this could get.

**Comment by KevinRansom** [comment]
Our localization contact, just got back to us with this explanation:
-------------------------------------------------------------------------

There have been questions about untranslated strings in our open source projects from our multilingual contributors. Although strings may appear in the repo as untranslated, it is not uncommon in some markets to not translate a given term. This means you cannot reference other languages on whether something should be translated. 

Microsoft cares about language quality and terminology. Our language specialists work in each local language market to research the best translation for a given term. A term is a
•	Product, services, feature names (Azure Service Names, e.g. Data Lake) 
•	Technical concepts (flow run)
•	Marketing terms (Extended Plus Support, Immersion Labs) 
•	Keywords and high-visible terms (temporal table, plot) 
•	Difficult concepts (rolling average) 
•	Terms which represent a Microsoft version of a generic term (cloud)

Translations that do not differ from general language usage and can be found in a regular dictionary are generally not considered terms. 

All approved terms are available publicly in the Microsoft Language portal where you can search by language and product. It is important to note that projects should be consistent with Microsoft-wide guidelines as well as with related projects. For example, F# should remain consistent with Visual Studio as a whole, so we might align with a term already in place for C#.

The localization team works with the development team to identify new terms or novel uses of old terms and mines new products, but not all terms are caught during this routine term mining. If a new term is identified, then Microsoft will have this evaluated, researched, and input to the Microsoft Language Portal.

Microsoft listens to community feedback on terms in the open source projects via the Issues submitted as well as feedback submitted through https://docs.microsoft.com. (If you add “localization” to the title, we’ll find it quickly. ) Our multilingual contributors living and working in a local market provide valuable feedback on how technical language is being actively used. There may be stylistic preferences between individuals and not all suggestions will be implemented, again for consistency with existing Microsoft products or standards. The Microsoft Language portal provides Style Guides for each language, which offers guidelines on language style and usage. If you are a MSDN subscriber, you can also download all the User Interface Translations as well.

However, there should usually be consistency within a language. A large, existing project like F# has had many of different translators over the years. Translators generally only work on new or updated strings and never see previously translated strings, even if they are nearby in the same resource file in the code project. The community can help by letting us know if they find an inconsistency via GitHub issues by logging an Issue with “localization” in the title.
