### ISSUE TITLE
AsyncActivation load failure from FAKE 5 and FSharp.Core 4.5

### ISSUE THREAD

**Issue by theimowski** [Microsoft/visualfsharp#5207]
I'm working on updating SAFE Template to FAKE 5 https://github.com/SAFE-Stack/SAFE-template/pull/101

While testing azure support I encountered following error:

```
---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target          Duration
------          --------
Clean           00:00:00.0017947
InstallClient   00:00:09.1332439
Build           00:00:28.0601001
Bundle          00:00:07.1811521
ArmTemplate     00:00:00.0100319   (Could not load type 'Microsoft.FSharp.Control.AsyncActivation`1' from assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.)
AppService      00:00:00           (skipped)
Total:          00:00:44.5082644
Status:         Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'ArmTemplate' failed.
-> One or more errors occurred. (Could not load type 'Microsoft.FSharp.Control.AsyncActivation`1' from assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.)
-> TypeLoadException: Could not load type 'Microsoft.FSharp.Control.AsyncActivation`1' from assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

#### Repro steps

1. https://github.com/SAFE-Stack/SAFE-template/pull/101
2. build template using `build.cmd`
3. install template locally with `dotnet new -i nupkg/{name}.nupkg`
4. create new project from template with azure support: `dotnet new SAFE --deploy azure`
5. `fake run build.fsx --target appservice -e subscriptionId={azure-sub-id} -e clientId={azure-client-id}`

#### Related information 

* Windows 10
* dotnet sdk 2.1.300

**Comment by dsyme** [comment]
Given this error:

```
-> TypeLoadException: Could not load type 'Microsoft.FSharp.Control.AsyncActivation`1' from assembly 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```
I'm 99.9% certain that you have an FSharp.Core mismatch. One of your components was built with FSharp.Core 4.5.0.0 but at runtime you are using FSharp.Core 4.4.3.0.

**Comment by dsyme** [comment]
(If they are involved it could be that Azure Functions only supports FSharp.Core 4.4.3.0, I'm not an expert at that.)

**Comment by matthid** [comment]
The problem seems to be that fake still runs with fsharp.core 4.3.4 nuget package (https://github.com/fsharp/FAKE/blob/release/next/paket.lock#L3109).
Sorry I didn't realize that people were already using 4.5 here, thanks @dsyme

**Comment by matthid** [comment]
We can track this now in https://github.com/fsharp/FAKE/issues/2001

**Comment by Thorium** [comment]
I guess there is no working solution for this yet.

**Comment by cartermp** [comment]
@Thorium This is likely because one of the dependencies (likely FSFormatting) is pinning a different version. More FSharp.Core exceptionalism at play here, unfortunately. You'll probably need to upgrade FSharp.Formatting to the latest release to use it with FAKE 5/.NET Core: https://www.nuget.org/packages/FSharp.Formatting/

**Comment by Thorium** [comment]
Thanks. As a workaround from Fake 4 build.fsx, I ran dotnet.exe calling custom generate.fsx with the new FSharp.Formatting, and it did work.
