### ISSUE TITLE
Data loss in Seq.windowed?

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#521]
While preparing the final parts of https://github.com/Microsoft/visualfsharp/pull/502 my property-based tests found a strange edge case. I wonder if this is expected:

    Seq.windowed 2 [0] |> Seq.toArray

returns `[||]`

I mean it's strange that the requested window size is greater than the original list, but I would expect to get either `[|0|]` or an exception.

**Comment by theimowski** [comment]
`Seq.windowed 2` is similiar to `Seq.pairwise`, in case of `Seq.pairwise` type system would force the output to be a tuple, in case of `Seq.windowed` type system can't do that. 
I'd expect the result to be an array of 2-elems arrays - so the result of the above seems ok for me

**Comment by forki** [comment]
thanks

**Comment by forki** [comment]
Ok I added another test which compares pairwise and windowed 2.
