### ISSUE TITLE
GenericEqualityER breaks if assigned

### ISSUE THREAD

**Issue by iainnicol** [Microsoft/visualfsharp#522]
``` f#
open Microsoft.FSharp.Core.LanguagePrimitives

type Age = | Years of double

[<EntryPoint>]
let main argv = 
    let noAge = Years nan
    printfn "GenericEqualityER nan nan? %b" (GenericEqualityER nan nan) // true (good)
    printfn "GenericEqualityER noAge noAge? %b" (GenericEqualityER noAge noAge) // true (good)
    let isEq = LanguagePrimitives.GenericEqualityER
    printfn "isEq nan nan? %b" (isEq nan nan) // true (good)
    printfn "isEq noAge noAge? %b" (isEq noAge noAge) // false (bad)
    0
```

This seems to affect F# v3.x as shipped with VS 2013 Update 3, as well as F# v4.0 prerelease as shipped with the VS 2015 RC.

**Comment by latkin** [comment]
Nice find, thanks for reporting this.

What's especially distressing is that compiling with optimizations leads to a different result (the expected result).

**Comment by dsyme** [comment]
Yes, definitely an inconsistency that we'd prefer to iron out. Is there a manifestation of this that doesn't require calls to an alias of something in Microsoft.FSharp.Core.LanguagePrimitives? I see that the only place we call GenericEqualityER is in generated calls in augmentations.

**Comment by iainnicol** [comment]
Not that I've come across. I only stumbled on the known manifestation because I was using this semi-private (?) API in some property based tests.

**Comment by manofstick** [comment]
Per my last linkage; I don't think that is true now. I deleted the reference, but it still seems to be shown here; but please ignore.

**Comment by dsyme** [comment]
I'm closing this as won't fix.  It's an inconsistency that we'd prefer to iron out but there is no known manifestation of this that doesn't require calls to an alias of something in Microsoft.FSharp.Core.LanguagePrimitives.  The cost/risk of a fix is too high to justify (unless a very simple and safe fix is found)
