### ISSUE TITLE
Opening current namespace doesn't grey out

### ISSUE THREAD

**Issue by BentTranberg** [Microsoft/visualfsharp#5228]
Opening the current namespace doesn't cause the open to become greyed out.

```
namespace Something

module SomeModule =

    open Something  //  <--- Why isn't this greyed out?
    // big chunks of code follow
```

I tried to create a simple repro in a flash, but did not succeed. For some reason my modules with big chunks of code has this problem, but creating a tiny app with a module and a few lines will not reproduce the problem.

This is of course nowhere near being a critical issue. However, it's annoying that needless opens aren't flagged.

I'm thinking that opening the current module perhaps is a special case, so maybe special action has to be taken to grey it out. But then again, it is greyed out in a simple test case. Why the difference? I know that greying out doesn't always work well, but it wasn't greyed out anywhere I tried it in my solution, except for the test above.

VS 15.7.4

**Comment by BentTranberg** [comment]
When I try to reproduce this error today, I get an error saying "The namespace or module 'Something' is not defined." Has the compiler changed behavior, or is it me not managing to recreate the issue? Can the issue be closed?

VS 15.9.7, FSharp.Core 4.6.2

**Comment by cartermp** [comment]
Not sure when this was adjusted, but I think the error is correct here since it's already in scope. But the message could probably be a bit clearer.
