### ISSUE TITLE
"Step into (F11)" doesn't seem to work in Visual Studio when debugging through F# Interactive

### ISSUE THREAD

**Issue by jorgedfbranco** [Microsoft/visualfsharp#523]
I was experimenting with the new F# Interactive debugging feature in Visual Studio 2015 RC and found out that "Step into" (as well as the other buttons next to it) doesn't seem to work correctly. Instead of stopping on the next line, they simply resume program execution (as if I had clicked on "Continue", instead).

This behavior is not observed when debugging a standard F# executable, which seems to work fine.

**Comment by latkin** [comment]
F# interactive generates optimized code by default, which leads to a fairly poor debugging experience.  You might just be seeing that.

If you check the F# Interactive options, is the top script debugging setting marked "true"?  "true" will enable debug-friendly options for F# interactive (you'll need to reset the session, though).

![image](https://cloud.githubusercontent.com/assets/5943573/8528447/e13f8cd0-23c7-11e5-8811-16fe7fe9d55b.png)

**Comment by jorgedfbranco** [comment]
My current settings are:

![image](https://cloud.githubusercontent.com/assets/677887/8532166/3fdad5ea-2424-11e5-9339-68d5507bda63.png)

I've tried also removing the "--optimize", as it could be changing in strange ways the generated code but it was of no avail. The previously described behavior still persists.

**Comment by latkin** [comment]
Then this is likely just some kind of code pattern that has poor sequence-point generation.

Can you share your code and the exact debugging steps you tried?

**Comment by jorgedfbranco** [comment]
Sure:

![image](https://cloud.githubusercontent.com/assets/677887/8532303/1975eeca-2425-11e5-8503-20d3ce2076fb.png)

Added x() definition to the FSI (ALT + ENTER), then started F# Interactive debugging session, then executed x(). The debugging session starts and stops in the breakpoint. I then:
![image](https://cloud.githubusercontent.com/assets/677887/8532400/c0f17ab6-2425-11e5-86b1-0537b5951aed.png)

It just resumes execution and doesn't stop on the next line.

**Comment by latkin** [comment]
Hmm, I don't repro with the latest builds here.

![debug](https://cloud.githubusercontent.com/assets/5943573/8532692/e9199032-23e4-11e5-86a2-430ae23fd611.gif)

Do you have "Enable Just My Code" enabled in the debugger?

**Comment by jorgedfbranco** [comment]
Yes, I had. I disabled it and now it works perfectly! That was it.

**Comment by exercitusvir** [comment]
This is unrelated to the issue, but that GIF video is really impressive. Lincoln, may I know how you created that?

**Comment by latkin** [comment]
Screen2Gif - http://screentogif.codeplex.com/

**Comment by 21c-HK** [comment]
Thank you! I especially like how smooth the rendering is.
