### ISSUE TITLE
Publish new FSharp.Core patch version to include XML doc bug fix

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#5231]
The current FSharp.Core version includes a bug in the XML docs that was fixed here: https://github.com/Microsoft/visualfsharp/commit/ee2edd15a55b3a62866004377b054eff41bb05fa

This prevents us from onboarding onto the docs.microsoft.com/dotnet/api API reference.

**Comment by zpodlovics** [comment]
@cartermp When the new F# 4.5 (Span support) will be pushed to .NET Core SDK? Any chance to LTS 2.1.x or at least non-LTS 2.2.x series?

**Comment by cartermp** [comment]
Closing as it has been published.

@zpodlovics It will be in the august update to .NET Core, LTS train.

**Comment by cartermp** [comment]
This actually need to be re-opened because FSharp.Core was published from the dev15.8 branch, not the master branch where the XML doc fix lies. We'll hopefully target VS 15.9 for this.

**Comment by cartermp** [comment]
This is already published now in 4.5.2
