### ISSUE TITLE
Unexpected compiler error: internal error: impossible: the flags parameter value is come from enums MethodAttributes and FieldAttributes must have access flag

### ISSUE THREAD

**Issue by rafd123** [Microsoft/visualfsharp#5233]
An internal compiler error occurs when inheriting from certain classes within the `Standford.NLP.Core.NLP` NuGet package.

#### Repro steps

Provide the steps required to reproduce the problem

1. Clone https://github.com/rafd123/InternalErrorImpossible.git

2. Compile the solution.

#### Expected behavior

Should compile.

#### Actual behavior

Compile fails with an internal error:

```
FS0192 internal error: impossible: the flags parameter value is come from enums MethodAttributes and FieldAttributes must have access flag
```

#### Known workarounds

Install version 10.0.2 of the `FSharp.Compiler.Tools` NuGet package. Doing so allows the solution to compile, however IntelliSense still reports the error.

#### Related information 

Provide any related information 

* Windows 10 April 2018 Update - Version 1803 (OS Build 17134.112)
* Visual Studio Professional 2017 (version 15.7.4)
* Microsoft Visual F# Tools 10.1 for F# 4.1 (15.7.0.0 Commit Hash: 173513e369ffb7a1c4d5dccf83696d9aac2ab2d0)

**Comment by rafd123** [comment]
I suspect that [this block of code](https://github.com/fsharp/FSharp.Compiler.Service/blob/79e77bbf75666d980ee105f3e305ba7803f834dd/src/absil/il.fs#L1542-L1549) should be handling `0x00000000` (which maps to `MethodAttributes.PrivateScope`) once the `0x00000007` mask (which maps to `MethodAttributes.MemberAccessMask`) is applied; see https://referencesource.microsoft.com/#mscorlib/system/reflection/methodattributes.cs,23).

**Comment by cartermp** [comment]
cc @dsyme and @AviAvni this seems like a regression

**Comment by cartermp** [comment]
This is now in and fixed. Thanks for the report @rafd123!

**Comment by rafd123** [comment]
Cheers!
