### ISSUE TITLE
Implicit restore doesn't restore enough

### ISSUE THREAD

**Issue by 0x53A** [Microsoft/visualfsharp#5241]
__EDIT: running ``dotnet restore`` on the console fixed it.__

The following behavior is on my work pc with VS2017.7.3.
I can't try it on my home pc with VS 2018.8pre because I currently don't have internet there. 😱 

Would appreciate guidance on whether this is a known fixed bug (can't currently test on 15.7.4 or 15.8.x), whether you can reproduce it, and if there are any workarounds.

1) Clone https://github.com/haf/expecto, checkout master.

Notice that nuget shows warnings
![grafik](https://user-images.githubusercontent.com/4236651/41988880-c7b26e2a-7a3d-11e8-996a-29221b3de5ad.png)
and almost nothing works.

Colorization is just the basic one, no class-coloring (I guess DateTime should be blue), no tooltips, no intellisense:
![grafik](https://user-images.githubusercontent.com/4236651/41989369-5c7fb192-7a3f-11e8-8958-dfe19b846e1b.png)

2) I added explicit references to System.ValueTuple (https://github.com/0x53A/expecto/tree/valuetuple), which removed the NuGet warnings, but didn't bring the tooling back to life.

3) New Project -> F# -> Class Library (.NET Standard)

Everything works
![grafik](https://user-images.githubusercontent.com/4236651/41989570-05802376-7a40-11e8-854c-78864fdbdbbf.png)

-------------------------------------------

VS and .NET SDK:

![grafik](https://user-images.githubusercontent.com/4236651/41989413-8893d8ee-7a3f-11e8-9f99-2f4f53097447.png)

```
C:\Repos\expecto>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.301\

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by 0x53A** [comment]
grr, running ``dotnet restore`` on the console fixed it.

I'll still leave it open, as the implicit restore _should_ work.

**Comment by cartermp** [comment]
Closing this as external, since this isn't a VS tooling issue. I'd suggest opening this on [dotnet/project-system](https://github.com/dotnet/project-system), which is where implicit restore at design time is handled.

**Comment by 0x53A** [comment]
Expecto uses paket, so it seems like I've hit the scenario you described here: https://github.com/fsprojects/Paket/issues/3270#issuecomment-400781633

**Comment by 0x53A** [comment]
I don't have a repro, which is why I haven't opened another issue, but I've hit a similar issue again. Vanilla nuget, no paket.

Open project, I get basic features, but no extended features.
Restart VS, everything works.

**Comment by 0x53A** [comment]
https://github.com/dotnet/project-system/issues/3788
