### ISSUE TITLE
F# .net core project referencing F# .net standard project, the error list window shows some errors.

### ISSUE THREAD

**Issue by YunWeiaa** [Microsoft/visualfsharp#5244]
#### Repro steps

1. Create a new F# .net core console app project;
2. Add a new F# .net standard classlib project；
3. Set reference from F# console app to F# netstandard classlibrary;
4. Add line similar to: Say.hello "Lily"
#### Expected behavior

No errors in error list

#### Actual behavior

There is a red squiggly, and the Error List shows some errors as below, but build and run succeeded.
 
![f 1](https://user-images.githubusercontent.com/33921754/42033727-675c1192-7b10-11e8-8c52-1559c15dc744.PNG)

#### Known workarounds

Close solution and reopen, the red squiggly and errors disappear.
#### Related information 
VS 15.8.0 Preview 5
Dotnet --info
![dot](https://user-images.githubusercontent.com/33921754/42033807-a85bffe0-7b10-11e8-80d0-92fbaa0e5201.PNG)

**Comment by TIHan** [comment]
I can confirm this. It looks like we may not be kicking off any updates when a project gets referenced. I will look into this.

**Comment by TIHan** [comment]
I think I know what's happening now. We aren't updating command line args when the project gets referenced.

**Comment by TIHan** [comment]
Hmm, the command line args are updated correctly. Something else is going on.
