### ISSUE TITLE
Requesting Quick Info hangs VS

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#5254]
Please provide a succinct description of the issue.

#### Repro steps

In an .fsx script in VS 2017.7.4, when I hit CTRL K + I when the caret is over a function, VS hangs completely - no redraws occur, nothing. The only option is to restart it.

**Comment by forki** [comment]
Please add a concrete script where it happens.

Isaac Abraham <notifications@github.com> schrieb am Fr., 29. Juni 2018,
13:03:

**Comment by majocha** [comment]
Yep, happens not just in scripts. BTW CTRL K, I opens quick info, not IntelliSense. I think I've seen this bug and it had been fixed at some point before.

**Comment by majocha** [comment]
duplicate #4710, I think a fix for this has been merged?

**Comment by majocha** [comment]
Fixed in #5257

**Comment by isaacabraham** [comment]
![foo](https://user-images.githubusercontent.com/1781813/42112695-965470fe-7be0-11e8-88ac-9b652e725155.gif)

CPU doesn't go to 100% - just seems to be around 5%, doesn't ever come back out, but it is doing something because somehow my PC grinds to a half. In fact I had to restart it whilst making this video because the first time I did it my PC completely locked up.

**Comment by majocha** [comment]
Wow, this is new. You don't hit any kay combinations in the video above? Just typing 'x', completion shows up, and bang?
It looks like it dies the moment the doc tooltip shows up for 'x'.

**Comment by isaacabraham** [comment]
No, I hit CTRL K + I to get quick info. It was just coincidence that intellisense was showing, you can ignore that.

**Comment by majocha** [comment]
Ahh, OK 😆 I've already edited some comments. This one we got just fixed.
