### ISSUE TITLE
15.8 preview 3 Core App template references outdated FSharp.Core package

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5268]
1. Create a new .net core app having .net core sdk 2.1 installed 
2. Look at referenced packages

![image](https://user-images.githubusercontent.com/873919/42132157-193577da-7d1b-11e8-9221-8d04bf4de72f.png)

Expected result: FSharp.Core 4.5.0 is referenced
Actual result: FSharp.Core 4.3.4 is referenced

**Comment by cartermp** [comment]
This is by design. .NET Core in Preview 3 does not have the update compiler for F# 4.5, so we won't be referencing FSharp.Core 4.5 until the SDK that ships with VS has the right compiler bits.
