### ISSUE TITLE
Failed to port a Span example from C#

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5271]
https://www.codemag.com/Article/1807051/Introducing-.NET-Core-2.1-Flagship-Types-Span-T-and-Memory-T

```csharp
public static int StringParseSum(string data)
{
    ReadOnlySpan<char> span = data;
    int sum = 0;
    while (true)
    {
        int index = span.IndexOf(',');
        if (index == -1)
        {
            sum += int.Parse(span);
            break;
        }
        sum += int.Parse(span.Slice(0, index));
        span = span.Slice(index + 1); // skip ','
    }    
    return sum;
}
```
```fsharp
let stringParseSum (data: string) =
    let mutable span: ReadOnlySpan<char> = data.AsSpan()
    let mutable sum = 0
    let mutable break' = false
    while not break' do
        let index = span.IndexOf(',')
        if index = -1 then
            sum <- sum + Int32.Parse(span)
            break' <- true
        sum <- sum + Int32.Parse(span.Slice(0, index))
        span <- span.Slice(index + 1)
    sum
```
![image](https://user-images.githubusercontent.com/873919/42125838-e9305346-7c86-11e8-9c99-cd8df04e73b1.png)

**Comment by majocha** [comment]
Ref instead of mutable works here.
```
let sum = ref 0
```

**Comment by vasily-kirichenko** [comment]
Yes, it works, but I think mutable should work as well.

**Comment by majocha** [comment]
True.
Another oddity:
![image](https://user-images.githubusercontent.com/1760221/42126750-f656c536-7c8c-11e8-887b-54b039dd433e.png)

**Comment by zpodlovics** [comment]
Span supposed to use in performance critical code on code paths without heap allocation, unfortunately ref not a value type and will allocate on heap (unless optimized out by the compiler, if this optimization exists, but even if there is no guarantee):

```fsharp
typeof<ref<int>>.IsValueType;;
val it : bool = false
```

**Comment by TIHan** [comment]
In latest master, the code compiles fine. It may be that preview 3 doesn't include any of the ref fixes that we did.

**Comment by cartermp** [comment]
Yes, Preview 3 definitely doesn't have the bug fixes. I _think_ Preview 4 should have them, but Preview 5most definitely will.
