### ISSUE TITLE
DEVGUIDE.md missing a step

### ISSUE THREAD

**Issue by ScottHutchinson** [Microsoft/visualfsharp#5272]
The DEVGUIDE.md instructions assume that the contributor has already got the visualfsharp repo on their machine.

Should the instructions say to first clone the **master** branch of the visualfsharp repo?

Should the instructions say when to clone a branch other than the master branch?

Thanks

**Comment by smoothdeveloper** [comment]
It would make sense to add that explicit step, I guess a PR would be welcomed.

I think most external contributions are supposed to happen on master branch and the maintainers manage later integration in specific release branches, I don't think we need to mention other branches.

**Comment by ScottHutchinson** [comment]
#5276 should resolve this issue.

**Comment by cartermp** [comment]
merged
