### ISSUE TITLE
No XML Doc for inref/outref in tooltip

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5279]
![image](https://user-images.githubusercontent.com/873919/42133839-0773198a-7d39-11e8-8709-408865207d8a.png)

However the sources contains XML Doc comments (no idea why `<summary>` tag is used though):

https://github.com/Microsoft/visualfsharp/blob/62068b73d6fdd11b47b516dda7023e0f92f78d8d/src/fsharp/FSharp.Core/prim-types.fsi#L846-L850

**Comment by vasily-kirichenko** [comment]
However, if a locally built FSharp.Core is referenced, like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <!--<ItemGroup>
    <PackageReference Update="FSharp.Core" Version="4.5.0" />
  </ItemGroup>-->

  <ItemGroup>
    <Reference Include="FSharp.Core">
      <HintPath>c:\git\visualfsharp\debug\net40\bin\FSharp.Core.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
```

 the XML Doc is there:

![image](https://user-images.githubusercontent.com/873919/42133869-b1cc3e7a-7d39-11e8-9798-677a65bcfccf.png)

**Comment by TIHan** [comment]
I believe it's the version of FSharp.Core that you are using in the preview.

**Comment by cartermp** [comment]
The XML docs are present in the editor with 4.5.2.

<img width="611" alt="screen shot 2018-08-12 at 11 04 49" src="https://user-images.githubusercontent.com/6309070/44004905-8e204dd4-9e1f-11e8-9369-ba06f68122b6.png">
<img width="545" alt="screen shot 2018-08-12 at 11 04 41" src="https://user-images.githubusercontent.com/6309070/44004906-90f73626-9e1f-11e8-9e26-6c6271a7ba77.png">
