### ISSUE TITLE
Compiler does not catch typing error in pattern matching when using literals

### ISSUE THREAD

**Issue by blumu** [Microsoft/visualfsharp#528]
When literals are used in pattern matching there is no check that the subsequent expression/pattern argument list is empty, e.g.
```fsharp
module Color =
    let [<Literal>] Yellow = "Yellow"

let isRed inp = 
    match inp with
    | Color.Yellow arg ->   // should get an error here
        failwith "Don't know this color"
```
nor that the right arrow in the pattern match is not missing, e.g.
```fsharp
let isRed = function
    | Color.Red ->
        true
    | Color.Yellow               /// Notice the missing -> here
        you can insert what you want here like booleans false "strings" _and numbers 42. Yes it still compiles
    | _ -> 
        failwith "Don't know this color"
```
As a side effect the match on Color.Yellow never holds.

For reference when using discriminated unions instead of literals you get the expected behavior:
```fsharp
module Color =
    type Y = | Yellow | Green

let isRed inp = 
    match inp with
    | Color.Yellow arg -> // we do get an error here
        failwith "Don't know this color"
```

**Comment by dsyme** [comment]
Fix is now ready for this

**Comment by blumu** [comment]
Thank you! I confirm that it works with branch fix-528. I now get the expected error:

    D:\sources\visualfsharp\Release\net40\bin>fsc c:\Users\wiblum\Documents\test.fs
    Microsoft (R) F# Compiler version (private)
    Copyright (c) Microsoft Corporation. All Rights Reserved.

    c:\Users\wiblum\Documents\test.fs(6,7): error FS3190: This literal pattern does not take arguments

**Comment by dsyme** [comment]
Reopening until the pull request is committed :) thx
