### ISSUE TITLE
Byref analysis on record of functions FS0412 and FS0437

### ISSUE THREAD

**Issue by marklam** [Microsoft/visualfsharp#5281]
Errors FS0412 (A type instantiation involves a byref type. This is not permitted by the rules of Common IL) and FS0437 (A type would store a byref typed value. This is not permitted by Common IL) are reported if a record contains a function with a byref argument. 
Using a type alias for the function type works

#### Repro steps

```f#
open System
open System.Buffers.Binary

module X = 
    type Nope = {
        Funcn : ReadOnlySpan<byte> -> int
        }

    type FuncType = ReadOnlySpan<byte> -> int
    type Works = {
        Funcn : FuncType
        }

    let f = BinaryPrimitives.ReadInt32BigEndian
    let works = { Works.Funcn = f }
    let nope =  { Nope.Funcn = f }
```

#### Expected behavior

Both `Nope` and `Works` behave the same

#### Actual behavior

`Nope` produces FS0412 and FS0437

#### Known workarounds

Create a type alias like `FuncType`

#### Related information 

.net standard 2.0
VisualStudio.15.Preview/15.8.0-pre.3.0+27825.0
Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: ac667ab00ebb5ef25ca1611ded25254b799877e0.

**Comment by TIHan** [comment]
Yes, it should give an error on the type abbreviation. I suspect the check didn't strip type equations.

**Comment by cartermp** [comment]
Milestone is 16.0 for now, but if we can get a quick fix in for 15.8 then I'll retarget

**Comment by TIHan** [comment]
I'll look at this tomorrow.

**Comment by TIHan** [comment]
I have a fix for this coming. It was pretty trivial.

**Comment by cartermp** [comment]
Closing as completed.
