### ISSUE TITLE
TypeChecker.fs file is too large to view or link all lines on github.com

### ISSUE THREAD

**Issue by ScottHutchinson** [Microsoft/visualfsharp#5283]
On github.com, in the default (formatted) viewer, it is not possible to view more than the first 9,323 lines of the file https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/TypeChecker.fs, which contains 17,343 lines. And even more importantly, it is not possible to share a link to any line past line #9,323. As indicated in the message below, the only workaround is to make the file shorter. Therefore, I propose splitting the TypeChecker.fs file into at least two smaller files.

From Github staff:

Hey Scott,

You should see a notice at the top of the file that says:

This file has been truncated, but you can view the full file.

For performance reasons, we can't display the entire file when it's this large. The only workaround would be to make your files shorter.

I hope this helps to clarify things!

Best,
Shawna

This link does not work, because the web page will not display more than about 9,400 lines. I could not find any information about why this does not work or how to make it work better. Please help. Thanks.

https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/TypeChecker.fs#L10539

**Comment by ScottHutchinson** [comment]
Another exchange with Github support:
-----------------------------------------------------------------------------------------------------------------
Shawna,

Thank you for your response.

I cannot see that notice anywhere. I'm using the Chrome browser. 

Although this file is larger than I would wish (and I did not create it), I have worked with code files with over 70,000 lines. So this one is nowhere near the maximum number of lines you can find in the wild.

I think github could easily come up with a better way to deal with this issue. For instance, if you must limit the number of lines displayed, then you could provide an API for selecting a range of lines to display.
-----------------------------------------------------------------------------------------------------------------
Hi Scott,

Thanks for your reply.

> I cannot see that notice anywhere. I'm using the Chrome browser.

It seems there is a bug on our end which is the reason that notice isn't being shown to you. Sorry about that.

Our engineers are looking into that. We'll also go ahead and pass your feedback along to the team!

Apologies once again for the trouble here.

Cheers,
John 
GitHub Support

**Comment by jwosty** [comment]
This would be good. Shorter code = cleaner code

**Comment by cartermp** [comment]
I don't think the file will be trimmed any time soon. There actually is a benefit to this (I agree it'd be good for it to be shorter), which is that we do dogfood the IDE experience with larger files and feel the same pains that others encounter if they also have huge files.
