### ISSUE TITLE
Can't pipe byref into function, but can apply it directly

### ISSUE THREAD

**Issue by marklam** [Microsoft/visualfsharp#5286]
Passing a byref argument using the forward-pipe doesn't work, get "error FS0412: A type instantiation involves a byref type. This is not permitted by the rules of Common IL."

#### Repro steps

```f#
open System.Buffers.Binary

module X = 
    let thisIsOK s  = BinaryPrimitives.ReadInt32BigEndian s
    let thisIsNot s = s |> BinaryPrimitives.ReadInt32BigEndian
```

#### Expected behavior

The forward-pipe should work the same as directly supplying the parameter to the function

#### Actual behavior

The compiler complains 

#### Known workarounds

Not using the forward-pipe

#### Related information 

.net standard 2.0
VisualStudio.15.Preview/15.8.0-pre.3.0+27825.0
Visual F# Tools 10.2 for F# 4.5 15.8.0.0. Commit Hash: ac667ab00ebb5ef25ca1611ded25254b799877e0

**Comment by TIHan** [comment]
This is intended. Because `|>` is a generic function, the rules state you can't have a `byref<_>` as a generic, ex: `callSomething<byref<int>>`.
