### ISSUE TITLE
Referencing a library compiled with --standalone interferes with array indexing

### ISSUE THREAD

**Issue by kasperhj** [Microsoft/visualfsharp#529]
Suppose `Lebowski.fs` contains
```
module Lebowski
type Name = FirstName of string
```
and is compiled with `fsc --standalone --target:library Lebowski.fs`.

If `Rat.fs` contains
```
module Something
type Something() =
    let a = [|0;0;0;|]
    let b = a.[0]
```
and is compiled with `fsc --target:library -r:Lebowski.dll Rat.fs` the following error occurs.

> Rat.fs(4,13): error FS0001: This expression was expected to have type
>     'a [] * int
> but here has type
>     int []

So it seems that simply referencing a library compiled with `--standalone` messes up the ability to do array indexing the the referencing assembly.

Everything is find if `--standalone` is removed.

**Comment by dsyme** [comment]
@kasperhj The recommendation is simply not to ever try to reference libraries compiled with --standalone from further F# compilations.  The kind of scenario where --standalone makes sense for DLLs is where the DLL is a plugin to some other system (but is not used as further input to the F# compiler)

**Comment by dsyme** [comment]
Closing this out for now.
