### ISSUE TITLE
FSharp.Core 4.3.4 is not found

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5295]
VS 15.8 pre 3
master
Ctrl+F5
New F# .net 4.6.1 console app
This:

![image](https://user-images.githubusercontent.com/873919/42336060-18aee274-808b-11e8-8f48-bf31d97ceb49.png)

**Comment by vasily-kirichenko** [comment]
![image](https://user-images.githubusercontent.com/873919/42336144-6d60d318-808b-11e8-9a30-7a915c579f6b.png)

**Comment by vasily-kirichenko** [comment]
![image](https://user-images.githubusercontent.com/873919/42336279-e48cf822-808b-11e8-8500-1423085908d6.png)

**Comment by vasily-kirichenko** [comment]
Looks like master is completely broken.

**Comment by vasily-kirichenko** [comment]
It's not reproduced on VS 15.7

**Comment by dsyme** [comment]
I think this is the usual thing that you have to use master with the latest official VS release (currently 15.7)

Does the dev15.8 branch work with 15.8 pre 3?

**Comment by vasily-kirichenko** [comment]
I see, thanks. I've not checked dev15.8.
