### ISSUE TITLE
The type 'string' is not compatible with the type 'seq<'a>'

### ISSUE THREAD

**Issue by bangjunyoung** [Microsoft/visualfsharp#530]
I have no idea why the following code doesn't compile with F# 4.0 on VS2015 RC:

![The type 'string' is not compatible with the type 'seq<'a>'](https://cloud.githubusercontent.com/assets/3378580/8632953/b80e5dbc-27ed-11e5-93ae-d1a90c3d9e40.PNG)

That's quite strange since there's no error if I run the same code in F# Interactive. Is it a compiler bug or am I missing something?

```fsharp
module Number

let digitNames = ["zero"; "one"; "two"; "three"; "four"
                  "five"; "six"; "seven"; "eight"; "nine"]

let toWord (number:seq<char>) =
    number
    |> Seq.map (fun n -> digitNames.[int n - 48])
    |> String.concat " "

let toWord' (number:string) =
    number
    |> Seq.map (fun n -> digitNames.[int n - 48]) // Error: The type 'string' is not compatible with the type 'seq<'a>'
    |> String.concat " "

let toWord'' (number:string) =
    (number :> seq<char>)  // Error: The type 'string' is not compatible with the type 'seq<'a>'
    |> Seq.map (fun n -> digitNames.[int n - 48])
    |> String.concat " "
```

**Comment by dsyme** [comment]
You must be developing a portable library I think.  For strange reason, the profile 7/78/259 System.Runtime.dll binary doesn't record System.String as implementing ``IEnumerable<char>``.  I checked this by looking at:

    ildasm "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.
NETCore\v4.5\System.Runtime.dll"

Likewise the Profile7 facade DLL doesn't implement this:

    ildasm "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.
NETPortable\v4.5\Profile\Profile7\System.Runtime.dll"

Later "4.6" profiles do implement this. AFAIK it's not possible to the get the Visual F# Tools to target the 4.6 portable profiles (Profile31, 32, 44, 84, 151, 157)

You can workaround this by using ``seq { for c in "F#" -> c }`` which uses the F# rule that strings have a "GetEnumerator()" method.

**Comment by dsyme** [comment]
Closing this as it's not strictly speaking a bug - the portable profiles are what they are.
