### ISSUE TITLE
[Documentation] Why are there two versions of the CoC?

### ISSUE THREAD

**Issue by jwosty** [Microsoft/visualfsharp#5321]
Theres the [CoC](https://github.com/Microsoft/visualfsharp/wiki/Code-of-Conduct) in the wiki page, but there's also another one (with some differences) at [/code](https://github.com/Microsoft/visualfsharp/blob/4bcffb74d68b5c6249f43c247bd88e257f84fbb6/code). Which one is the correct one? Should they be synced? Should one be deleted?

Side note -- should `code` be named `code.md`, so that Github knows it's a Markdown file? Currently it just displays it as normal text.

**Comment by smoothdeveloper** [comment]
`code_of_conduct.md`?

**Comment by jwosty** [comment]
@smoothdeveloper yeah that one makes more sense to me -- better to be more descriptive than less when naming things.

**Comment by jwosty** [comment]
Hold on, just noticed that there's also [/CODE_OF_CONDUCT.md](https://github.com/Microsoft/visualfsharp/blob/6c6de72d154a550732dd1ce818f64ad75fee843c/CODE_OF_CONDUCT.md). So sounds like /code could just be deleted then. PR incoming

**Comment by cartermp** [comment]
Thanks @jwosty - I also removed the duplicate in the wiki and pointed to the official doc that is in our repository root.
