### ISSUE TITLE
Core.printfn signature changed (?) / problem at assembly boundary

### ISSUE THREAD

**Issue by urbanhop** [Microsoft/visualfsharp#5329]
With version 4.5. I suddenly get an error when aliasing printn inside an assembly:

    let pf = printfn // inside assembly, in myutils.fs

worked until 4.5, while now using it like
    
      pf "hello" // in mylab.fsx

raises

        System.InvalidCastException: Unable to cast object of type 'clo@1504[System.IO.TextWriter,Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Core.Unit]' to type 'Microsoft.FSharp.Core.FSharpFunc`2[Microsoft.FSharp.Core.FSharpFunc`2[Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Core.PrintfImpl+PrintfEnv`3[System.IO.TextWriter,Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Core.Unit]],Microsoft.FSharp.Core.Unit]'.
        at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
        at Microsoft.FSharp.Core.PrintfImpl.PrintfBuilder`3.Build[T](String s)
        at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
        at Microsoft.FSharp.Core.PrintfImpl.Cache`4.Get(PrintfFormat`4 key)
        at Microsoft.FSharp.Core.PrintfModule.PrintFormatToTextWriterThen[TResult,T](FSharpFunc`2 continuation, TextWriter textWriter, PrintfFormat`4 format)
        at <StartupCode$FSI_0002>.$FSI_0002.main@()

Trying it typed:

      let pf :  (Printf.TextWriterFormat<'a> -> 'a) = printfn // inside assembly 

does not help. I believe that the export signature from the assembly changed and is incorrect now.

If I shall diagnose it any further let me know.

**Comment by cartermp** [comment]
@urbanhop Can you provide some more information?

* Visual Studio version
* F# tools version (nightlies or preview nightlies?)
* Project type (.NET Framework, .NET SDK?)
* F# compiler version (you can view this by looking at the output pane with the following setting enabled)

![image](https://user-images.githubusercontent.com/6309070/42604681-ded0a040-8528-11e8-8378-94f396a5e9fb.png)

Additionally, if you can supply a repro project, that would be very helpful.

When using VS 15.7.5 in a .NET Framework project with FSharp.Core 4.5.0 and F# compiler found in the build log as:

```
C:\Program Files (x86)\Microsoft SDKs\F#\10.1\Framework\v4.0\fsc.exe
```

I cannot reproduce this by placing `let pf = printfn` in an F# source file, `#load`ing that source file into an F# script file, and then executing the F# script in FSI.

**Comment by urbanhop** [comment]
thx for the fast + detailed response.

I nailed it down and prepared a repo: https://github.com/urbanhop/lab-printfn

The problem is related to FSI only, other assemblies reference the pf function well.
The problem might be to get FSI using FSharp.Core 4.5 only, in the repo sample, FSharp.Core.dll is loaded twice.

**Comment by cartermp** [comment]
@urbanhop sorry for the delay here, this fell off my radar somehow. I tested this out in VS 15.8 Preview 5 and cannot reproduce. I suspect this was more a quirk of having two references of FSharp.Core loaded by your script. On my machine, only 4.5.0 is loaded, so there isn't any confusion about where `printfn` is. I don't think things are intended to work if you have multiple versions loaded at the same time.
