### ISSUE TITLE
F# 4.0 contributor photo!

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#534]
We've had a recent tradition of tweeting/blogging a "ship photo" on important milestones.  F# 4.0 represents the biggest group of contributors ever to an F# release, so the ship photo needs to be the best ever!

F# 3.1.2 was the first RTM release to incorporate open source contributions.  We included those contributors in the photo, via their Twitter profile pics:

![image](https://cloud.githubusercontent.com/assets/5943573/8711716/4a8a6d0c-2b09-11e5-8f72-7f49e896cf41.png)

For 4.0, I figured we could plan ahead better and have some fun with it:

- Redmond people (@latkin, @KevinRansom, @vladima, @brettfo, @wschae) will take a photo together over here
- I'd request @dsyme organize a photo in Cambridge with @andrewjkennedy and Matthew Parkinson (can't find a GH for him) and post it here
- Everyone else who has an accepted PR*, post a photo here and we will include it! Feel free to get creative (include your `Cup<'t>`?). If we don't get a photo from you we'll be forced to use your GH or Twitter pic. :smile:

In case you haven't seen it, VS 2015/F# 4.0 will be RTMing next week on [Monday 7/20](http://blogs.msdn.com/b/somasegar/archive/2015/06/29/save-the-date-visual-studio-2015-rtm-on-july-20th.aspx), so this needs to be done by Sunday 7/19.

`*` /cc contributors w/ accepted PRs: @forki @PatrickMcDonald @enricosada @dungpa @mexx @rojepp @ReedCopsey @TIHan @braden @antofik @GeorgeHahn @mrange @jdh30 @soloman817 @mstyura @rodrigovidal @khmylov @ploeh @thinkbeforecoding @OkayX6 @zeux @ledbutter @simonhdickson @richardadalton @stephen-swensen @soimort @pirrmann @xepaul @jack-pappas @bogdangaliceanu

**Comment by thinkbeforecoding** [comment]
![jeremiechassaing](https://cloud.githubusercontent.com/assets/146717/8743841/b9d57e80-2c72-11e5-8edf-6dac802613ae.jpg)
Here it is... My profile pictures are usually space invaders, so not that useful for a group photo :D

**Comment by bogdangaliceanu** [comment]
![bogdan](https://cloud.githubusercontent.com/assets/7138276/8750963/fe6fc402-2cb2-11e5-85e4-736b665a4fa9.jpg)
Here I am in all my glory

**Comment by latkin** [comment]
Here are the Redmond contributors, sans @wschae who couldn't be there :cry:

![image](https://cloud.githubusercontent.com/assets/5943573/8758785/48b767f6-2c9d-11e5-9f8c-5d821a1855c9.png)

**Comment by stephen-swensen** [comment]
Here's mine!
![fsharp-portrait](https://cloud.githubusercontent.com/assets/1300508/8759337/e23ed644-2cbf-11e5-8ad3-96adf7b4bad8.jpg)

**Comment by pirrmann** [comment]
And mine!
![20150717_190156](https://cloud.githubusercontent.com/assets/1926632/8761699/39ac6d98-2d5f-11e5-8c74-2534585cde6b.jpg)

**Comment by OkayX6** [comment]
All our faces look so aggressive on screen because of Github auto-resize... :) !
Here's a random popeyed selfie...

![denis - bastille - day](https://cloud.githubusercontent.com/assets/1169339/8763699/87e2dcea-2daa-11e5-8fc7-35662561b2c8.jpg)

**Comment by ledbutter** [comment]
Avert your eyes!
![me](https://cloud.githubusercontent.com/assets/3759836/8764223/5eb27670-2d8f-11e5-87d9-a608aa903301.jpg)

**Comment by latkin** [comment]
Keep them coming!

**Comment by forki** [comment]
I like the one you already used for 3.1.2 release ;-)

**Comment by ploeh** [comment]
I'd be happy with the one on my Twitter profile <https://twitter.com/ploeh> ; I don't have anything better lying around anyway :)

**Comment by richardadalton** [comment]
My GitHub pic is is fine by me.

-----Original Message-----

**Comment by xepaul** [comment]
My GitHub pic is is fine by me.

**Comment by PatrickMcDonald** [comment]
![img_6406-portrait](https://cloud.githubusercontent.com/assets/1562597/8772118/f8e89a12-2ec0-11e5-97f1-4beb0a579c1a.jpg)

Here you go.

**Comment by latkin** [comment]
@forki 3.1.2 was your old twitter picture, don't have it any more :(

**Comment by forki** [comment]
![buddy_lueneburg_200](https://cloud.githubusercontent.com/assets/57396/8778873/88911d12-2f00-11e5-9584-9543e9f1ce77.jpg)

**Comment by latkin** [comment]
Ok here's everyone together. Order is roughly alphabetical by username. I'll upload full-res version at some point.

![image](https://cloud.githubusercontent.com/assets/5943573/8780960/3c38643c-2ec1-11e5-8e49-fdfa2a8629d5.png)

**Comment by latkin** [comment]
Full-res here, if anyone wants it: https://gist.github.com/latkin/45b176ba4ab789924968

3996x3996, about 28.5 MB
