### ISSUE TITLE
Keyword descriptions of let-bang and friends should be consistent and not specifically refer to asyncs

### ISSUE THREAD

**Issue by jwosty** [Microsoft/visualfsharp#5343]
*As discussed in https://github.com/Microsoft/visualfsharp/pull/4427#pullrequestreview-101251096*

Some computation-expression keyword descriptions are inconsistent with each other in how they are described, and this should be fixed. For example:

* [`let!`](https://github.com/Microsoft/visualfsharp/blob/32a93aa9da192ddd622d6a416748a4c00bd4f528/src/fsharp/FSComp.txt#L1373) says it's *"Used in asynchronous workflows ..."*
* [`use!`](https://github.com/Microsoft/visualfsharp/blob/32a93aa9da192ddd622d6a416748a4c00bd4f528/src/fsharp/FSComp.txt#L1401) says it's *"Used ... in asynchronous workflows and computation expressions ..."*
* [`return!`](https://github.com/Microsoft/visualfsharp/blob/32a93aa9da192ddd622d6a416748a4c00bd4f528/src/fsharp/FSComp.txt#L1391) says it's *"Used to indicate a computation expression ..."*
* [`yield!`](https://github.com/Microsoft/visualfsharp/blob/32a93aa9da192ddd622d6a416748a4c00bd4f528/src/fsharp/FSComp.txt#L1408) says it's *"Used in a computation expression ..."*
* and finally, [`match!`](https://github.com/Microsoft/visualfsharp/blob/32a93aa9da192ddd622d6a416748a4c00bd4f528/src/fsharp/FSComp.txt#L1375) says it's *"Used in computation expressions ..."*

All of these descriptions should be unified to either all say "Used in computation expressions", or "Used in a computation expression" (doesn't really matter which; just as long as they're consistent).

**Comment by cartermp** [comment]
100% agree, it should be unified on CEs.

**Comment by jwosty** [comment]
I can certainly take this one within the next couple of days

**Comment by chillitom** [comment]
It would be really cool if there was a way to document computation expression builder methods so that intellisense and compiler warnings would adapt for the context of the builder.

For example `let!` in an `async` builder might say "binds the result of an async computation" whilst `let!` in a `maybe` builder might say "binds the value of the option when Some otherwise causes the maybe computation expression to result in None". (Preferably with better wording).

Perhaps it could just pick up any doc comments from the associated builder methods if they exist.

**Comment by jwosty** [comment]
@chillitom now that's a thought that's worth exploring. I wonder if that's possible -- it would depend on what phase of the compiler in which the keyword descriptions are read. The helper function that does that is [keywordsWithDescription](https://github.com/Microsoft/visualfsharp/blob/bb33e27e87c31df468851fe0ebad9cfda94935cf/src/fsharp/lexhelp.fs#L365), and it's used by a few other things, so maybe it should be able to get this information dynamically from user code.

**Comment by cartermp** [comment]
This is now completed.
