### ISSUE TITLE
Mutable use bindings permitted by the F# compiler

### ISSUE THREAD

**Issue by eiriktsarpalis** [Microsoft/visualfsharp#535]
I just noticed that the F# compiler permits mutable use bindings:

``` fsharp
let disp msg = { new System.IDisposable with member __.Dispose () = printfn "%s" msg }

let test () =
    use mutable d = disp "foo"
    d <- disp "bar"
```

Running `test` will cause "bar" to be printed. This feels wrong and the sentiment was corroborated by the fact that C# explicitly prevents it:

``` csharp
using (MemoryStream m = new MemoryStream())
{
      m = null;
}
```

which produces the compiler error:

```
Error   1   Cannot assign to 'm' because it is a 'using variable'
```

I checked the F# spec, but couldn't find any explicit mention of mutable use bindings. 

Is this a compiler bug then?

**Comment by dsyme** [comment]
It's by spec but I'd be happy to emit a warning in this case.  Could you add an entry to http://fslang.uservoice.com?  I'll mark it as approved for a future edition of the language.

**Comment by eiriktsarpalis** [comment]
Done! http://fslang.uservoice.com/forums/245727-f-language/suggestions/8909788-disable-or-add-a-warning-to-mutable-use-bindings

**Comment by dsyme** [comment]
Closing this since it's now recoded on uservoice (and approved)

**Comment by dsyme** [comment]
@eiriktsarpalis An update on this: I believe mutable use bindings may be needed for F# in the case that the "disposable" type is a struct.  For example, a struct enumerator of a ``System.Collections.Generic.List<T>``
