### ISSUE TITLE
Extension method on byref can mutate an immutable value

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#5355]
Consider the following F# code:

```fsharp
open System
open System.Runtime.CompilerServices

[<Extension>]
type Ext() =
    [<Extension>]
    static member inline Change(dt: byref<DateTime>) = dt <- DateTime.Now

let f() =
    let dt = DateTime.Now
    printfn "%d" dt.Ticks
    
    let dtRef = &dt
    
    dtRef.Change()
    printfn "%d" dt.Ticks

    dtRef.Change()
    printfn "%d" dt.Ticks

    dtRef.Change()
    printfn "%d" dt.Ticks

[<EntryPoint>]
let main argv =
    f()
    0 // return an integer exit code
```

Executing with ctrl-f5:

```
636676140835468566
636676140835876165
636676140835877191
636676140835878063
```

**Comment by cartermp** [comment]
Note that this can also be done with reference types:

```fsharp
// Learn more about F# at http://fsharp.org

open System
open System.Runtime.CompilerServices

[<Extension>]
type Ext() =
    [<Extension>]
    static member inline Change(dt: byref<string>) = dt <-"Hoopty"

let f() =
    let dt = "beef"
    printfn "%s" dt
    
    let dtRef = &dt
    
    dtRef.Change()
    printfn "%s" dt

    dtRef.Change()
    printfn "%s" dt

    dtRef.Change()
    printfn "%s" dt

[<EntryPoint>]
let main argv =
    f()
    0 // return an integer exit code
```
Gives
```
beef
Hoopty
Hoopty
Hoopty
```

**Comment by TIHan** [comment]
Highly aware of this. Looking into it.

**Comment by zpodlovics** [comment]
I guess this is the same or similar problem as the ```this <- v``` whole structs replacement here:
https://github.com/fsharp/fslang-design/issues/287#issuecomment-388555482

Please do not disallow byref access to immutable/read-only structures, as it used for performance critical work.

**Comment by TIHan** [comment]
@zpodlovics it looks like it is similar, but those are referring to instance members.

I think I know what's happening in the compiler, but it needs more investigation. Basically on calls like this we lose information that it was a byref or a inref; it only compares if it was the destination type of the byref.

**Comment by TIHan** [comment]
I have a fix for this coming soon.

**Comment by TIHan** [comment]
Resolved.
