### ISSUE TITLE
Do we need to a .Net Core 2.0 version of FSharp.Core?

### ISSUE THREAD

**Issue by kunjee17** [Microsoft/visualfsharp#5372]
I was trying [Elmish.XamarinForms](https://github.com/kunjee17/functional-cat). In that I was trying to fetch data from web. And signature F# method was missing. I can't have `AsyncDownloadString` . While `System.Net.Web` is [working](https://github.com/kunjee17/functional-cat/blob/master/FunctionalCatApp/FunctionalCatApp.fs#L38) without any issue. It will just add one more step to convert task to async. 

While digging up and asking around, I found out this https://github.com/Microsoft/visualfsharp/blob/75fbda0e27cd9e8447852185bdf2e33fb965f017/src/FSharp.Profiles.props#L41

.Net Core 2.0 / .Net Standard 2.0 is very much near to full framework. (Skipping windows specific parts) . Shouldn't we also push to have complete FSharp.Core for full and 2.0 ?

Let me know if any further details are required.

**Comment by baronfel** [comment]
I do think there's value in shipping a `netstandard2.0` version of FSharp.Core, if only for the massive dependency tree trimming that would result from not being forced to use the `netstandard1.6` version. AFAIK the .Net Standard 2.0 is stable so irrespective of executables shipped I think the library makes sense.

**Comment by cartermp** [comment]
Note that if you target .NET Standard, there is no dependency tree trimming required for the `netstandard1.6` version. That's why there is a NuGet group in the package to prevent that. We'll eventually phase out the `netstandard1.6` version at the end of June 2019 as per the [support policy](https://www.microsoft.com/net/support/policy) for .NET Core 1.x and associated bits.

Though the original issue is for a `netcoreapp2.x` binary to additionally be shipped in the package. I don't think it's out goal to have a binary for each platform.

**Comment by kunjee17** [comment]
@cartermp Is it possible to provide things as separate nuget package? I remember there was a discussion going on to chop FSharp.Core in few packages. May be this way few more things can be supported. I totally understand the headache part of it, but just looking into possibility to have similar support of FSharp.Core in Full and NetCore version. Just like asp.net mvc is doing.

**Comment by zpodlovics** [comment]
@cartermp How the new ```Span<'T>``` supported version F# will work as a netstandard1.6 package ? How the CoreCLR/CoreFX/ASP.NET team solve the versioning problem (=provide compatibility as per support policy, but also have packages that could use the newer apis for example new ASP.NET packages that use Span internally / or even within the api) ?

**Comment by cartermp** [comment]
@kunjee17 I could see such a split working out, but I'm not sure if others here would be fine with that.

@zpodlovics Span is not a type that we depend on in FSharp.Core. We define the appropriate reference types and their algebraic relationship in FSharp.Core, which has no dependencies on .NET Core 2.1. Span/ReadonlySpan are .NET Core 2.1-only for the time being, with no immediate plans to make them available in a .NET Standard version.

**Comment by cartermp** [comment]
Closing old discussion.

We'll consider a future FSharp.Core that has a binary with Span (i.e., .NET Core 2.1 or higher),
