### ISSUE TITLE
Visual Studio F# error - FSharp.Core.sigdata

### ISSUE THREAD

**Issue by Overlord-Zurg** [Microsoft/visualfsharp#538]
I've installed the latest FSharp bundle, but now whenever I hit control-spacebar in Visual Studio, I get this error:

> Problem reading assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a': Error opening binary file 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\FSharp.Core\v4.0_4.3.1.0__b03f5f7f11d50a3a\FSharp.Core.dll': FSharp.Core.sigdata not found alongside FSharp.Core

Also, when I try to compile, I get:

> FSC: error FS1223: FSharp.Core.sigdata not found alongside FSharp.Core
> FSC: error FS0229: Error opening binary file 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\FSharp.Core\v4.0_4.3.1.0__b03f5f7f11d50a3a\FSharp.Core.dll': FSharp.Core.sigdata not found alongside FSharp.Core
> FSC: error FS3160: Problem reading assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a': Error opening binary file 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\FSharp.Core\v4.0_4.3.1.0__b03f5f7f11d50a3a\FSharp.Core.dll': FSharp.Core.sigdata not found alongside FSharp.Core
> Done building project "Library1.fsproj" -- FAILED.

**Edit 2**

On top of that, I get the following errors when I try to run fsi.exe:

    > Session termination detected. Press Enter to restart.
    
    
    
    unknown(1,1): error FS1223: FSharp.Core.sigdata not found alongside FSharp.Core
    
    
    unknown(1,1): error FS0229: Error opening binary file 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\FSharp.Core\v4.0_4.3.1.0__b03f5f7f11d50a3a\FSharp.Core.dll': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+StopProcessing' was thrown.
    
    
    unknown(1,1): error FS3160: Problem reading assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+StopProcessing' was thrown.

**Note: I can still run fsi.exe for F# 3.0. I'm only having this issue with 3.1 (C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0)**

Any idea how I can get back to functioning F#?

**Edit 3**

It appears that I am again able to compile my F# projects after numerous repair installs/system reboots of things. The issues with fsi.exe and Visual Studio Intellisense remain.

**Comment by latkin** [comment]
I'm a bit confused as to the current system state and what exactly is/is not working. Can you clarify?

What version of VS are you using (and are there any others also on the system)? What F# bundle version are you using?

**Comment by Overlord-Zurg** [comment]
Visual Studio 2013 Ultimate is what I am attempting to use. I may also have 2010 installed, not sure; I will double-check when I get home.

I believe the bundle I installed is:
http://www.microsoft.com/en-us/download/confirmation.aspx?id=44011

(I was attempting to install it to use the additional PCL templates that are included.)

The specific issues I'm trying to address are:

1. When I attempt to run "C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\Fsi.exe", it errors out with the FSharp.Core .opdata/.sigdata error described above. (The same thing occurs when trying to use F# Interactive in VS.)

2. If I attempt to trigger auto-completion help in VS, I get a popup with the same error.

**Comment by Overlord-Zurg** [comment]
Any suggestions on how I can resolve this? I'm pretty lost when it comes to issues with the GAC...

**Comment by dsyme** [comment]
You might look for a rogue FSharp.Core.dll somewhere on your system. Also try repair/reinstall.

**Comment by Overlord-Zurg** [comment]
Wow, THE Don Syme! Yes sir, I tried both of those things, but they had no impact. Ideally I would be able to do a full system wipe, but I'm not really organized enough to have that be feasible right now (or ever).

The problem is no longer urgent for me, since I can now use Visual Studio 2015 with F# 4.0.

**Comment by aggieben** [comment]
I am currently having this problem.

```
D:\Users\ben
λ gcm fsi

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     Fsi.exe                                            4.4.0.0    C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\Fsi.exe


D:\Users\ben
λ fsi

Microsoft (R) F# Interactive version 14.0.23413.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

>

unknown(1,1): error FS1223: FSharp.Core.sigdata not found alongside FSharp.Core


unknown(1,1): error FS0229: Error opening binary file 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\FSharp.Core\v4.0_4.4.0.0__b03f5f7f11d50a3a\FSharp.Core.dll': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+StopProcessing' was thrown.


unknown(1,1): error FS3160: Problem reading assembly 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a': Exception of type 'Microsoft.FSharp.Compiler.ErrorLogger+StopProcessing' was thrown.
D:\Users\ben
λ
```
