### ISSUE TITLE
Publish new FSharp.Compiler.Tools when preview 5 ships

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#5382]
@dsyme When preview 5 ships (very, very soon), the F# compiler will be implementing F# 4.5 fully. We should also publish an updated version of the FCT package to align with that.

**Comment by cartermp** [comment]
(ping me privately if you want the ship date, as this is closed information)

**Comment by cartermp** [comment]
@dsyme Preview 5 is out, so we should publish this (especially now that the binary compat issue is in).

**Comment by vasily-kirichenko** [comment]
Even RTM is out. Maybe someone other than @dsyme should have rights to publish the package?..

**Comment by vasily-kirichenko** [comment]
@forki if you tell me how to build it, I'll do that.

**Comment by forki** [comment]
so  seems we're back to beginning ....

Am Mi., 15. Aug. 2018 um 11:46 Uhr schrieb Vasily Kirichenko <
notifications@github.com>:

**Comment by vasily-kirichenko** [comment]
OK, simple `build` builds it, but the version does not seem correct:

![image](https://user-images.githubusercontent.com/873919/44143147-3ad2ca4e-a08b-11e8-86ac-35b741718001.png)

(I've built it from master, is it the right branch?)

**Comment by cartermp** [comment]
dev15.8 is still not merged into master: https://github.com/Microsoft/visualfsharp/pull/5508

Building out of the dev15.8 branch should do it.

**Comment by vasily-kirichenko** [comment]
@dsyme Pleeeease :)
