### ISSUE TITLE
Rename is bogus on generic parameters

### ISSUE THREAD

**Issue by asik** [Microsoft/visualfsharp#5389]
```
type Generic<'t> = {
    T : 't
}
```

After invoking rename (Ctrl+R,R) on `t` or `'t` and entering `a` or `'a` respectively, the result is invalid code:
```
type Generic<``'a``> = {
    T : ``'a``
}
```

The expected result is
```
type Generic<'a> = {
    T : 'a
}
```

Visual Studio 15.7.5

**Comment by cartermp** [comment]
FYI @Krzysztof-Cieslak although we handle the resulting symbol differently in VS, this will also give an incorrect result in Ionide. Any ideas if this is due to how you handle the result?

![ionide](https://user-images.githubusercontent.com/6309070/43281429-7ed5036a-90c8-11e8-8899-da59e0629081.gif)

**Comment by Krzysztof-Cieslak** [comment]
I think Ionide problem may be connected with some underlying behavior of VSCode, not with how we handle results in it.
