### ISSUE TITLE
fsi scripts do not respect [<EntryPoint>] attribute

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#539]
We have an fsharp.core.dll API exit(n) which wraps System.Environment.Exit(n).  This API is missing from portable library based versions of fsharp.core.
The necessary Support APIs do not exist in the current coreclr netfx:
- System.Environment.Exit(int)
- System.Environment.GetCommandLineArgs()

In some ways exit() is an imperative function who’s aim is to short circuit program execution and terminate quickly but cleanly.  I wonder why we originally chose to wrap it in fsharp.core, it seems reasonable to exclude it for coreclr.

It seems to me that exit and System.Environment.CommandLineArgs() are primarily useful to support scripting scenarios, that’s certainly seems to be where we use them most.

Internally we do also use System.Environment.GetCommandLineArgs() in FSI.fs, but it’s use there is a bit idiosyncratic, and is not strictly necessary.

``` [<EntryPoint>]
[<STAThread()>]
[<LoaderOptimization(LoaderOptimization.MultiDomainHost)>]     
let MainMain argv = 
    ignore argv
    let argv = System.Environment.GetCommandLineArgs()
```

For compiled apps, we don’t really need these API’s, since Main provides command line arguments and the integer value of the Main function is the exit code for the process.  However scripts are problematic.

.fsx scripts executed with –exec do not honor the `[<EntryPoint>]` attribute.  If it did script authors would be able shove that Attribute on the last binding in their script and get access to Command Line arguments and set the return value.

I propose that we ensure that for scripts that contain an `[<EntryPoint>]` attributed binding we hook up the command line args and set the exitcode based on the return value from the `[<EntryPoint>]` binding.

How does that sound?

Kevin

**Comment by dsyme** [comment]
So the general question here is "what modifications do we need to make to the F# scripting programming model if it is going to run on .NET Core"

I must say it seems very strange not to have "exit" or "GetCommandLineArgs" on .NET Core - it feels like .NET Core is kind of deficient if it can't do the basic process-related things that every Linux programmer expects to be able to do.  It really feels like these functions should exist (but exit can raise an exception if exit is not allowed and GetCommandLineArguments can always return something half sensical). Without them .NET Core is just kind of some incomplete model suitable for ASP.NET-like hosted scenarios only.

**Comment by KevinRansom** [comment]
The absence of the APIs caused me to look at what we do.  I do expect that eventually those APIs will be added.  However, neither of those APIs are necessary to write a correctly functioning CoreCLR console application.

In the Cambridge tests we can run them either as compiled programs or as fsi --exec scripts.

In the absence of these APIs we can get command line arguments for the script using:
    let args = fsi.CommandLineArgs

and when compiled to an exe using :+1: [<EntryPoint>]
let main argv = 
    printfn "%A" args
    0 // return an integer exit code

As far as returning an exit code when compiled to an .exe the value of the main function is the exit code.  When using a script there is no mechanism.

I am suggesting that we harmonize the script mechanism so that it supports the same mechanism is a console application.  Then we have a single model that works correctly and has less of a platform dependence.

I think this would be a good thing to do regardless of whether the coreclr adds these APIs.

Kevin

**Comment by cartermp** [comment]
@KevinRansom Is this something you're considering in the .NET Core FSI work you'll be doing?

**Comment by cartermp** [comment]
Closing old discussion as this is covered by a suggestion: https://github.com/fsharp/fslang-suggestions/issues/658
