### ISSUE TITLE
Generic arguments are locked to the first used type when curried and partially applied

### ISSUE THREAD

**Issue by Nhowka** [Microsoft/visualfsharp#5393]
I'm experimenting with some reflection features and tried to do a generic function that prints a string, the type full name, and the content. I was able to do this:

#### Repro steps

```fsharp
let printer(name, x:'a) = printfn "%s, %s, %A" name typeof<'a>.FullName x

let test t = printer("Test",t)
test 1 // Test, System.Int32, 1
test "2" // Test, System.String, "2"

let test2 name t = printer(name,t)
test2 "Test2" 3 // Test2, System.Int32, 3
test2 "Another test" "12" // Another test, System.String, "12"

let test3 = test2 "Partially applied"
test3 "4" // Partially applied, System.String, "4"
test3 12 // This expression was expected to have type     'string'     but here has type     'int'
```

#### Expected behavior

The partially applied function keeps the argument as generic

#### Actual behavior

The partially applied function gets locked to the first type used

#### Known workarounds

I couldn't make it work. Probably that is by design, but I would like to know if there is any.

**Comment by asik** [comment]
That's your workaround:

`let test3 x = test2 "not really partially applied anymore but works the same" x`

Type inference has some limitations when it comes to function values; in these cases, use syntactic functions instead. I don't really understand them but the rule of thumb of switching to syntactic functions and, if needed, specifying types explicitely, works well for me. I'll leave it to a real language expert to explain why things work this way.

**Comment by TIHan** [comment]
I'll leave it to @dsyme to explain this one. I'm having a hard time thinking why. I have some ideas but it's hard to make sense of it. But yea, it looks like value functions have a limitation on generics when you start calling them.

**Comment by dsyme** [comment]
Yes, this is known as the value restriction in F# type inference, see Chapter 5 of Expert F# 4.0 and other such guides
