### ISSUE TITLE
F#: Editor features (intellisense etc) don't work after deleting ".vs"

### ISSUE THREAD

**Issue by davkean** [Microsoft/visualfsharp#5395]
_From @0x53A on July 25, 2018 12:20_

![grafik](https://user-images.githubusercontent.com/4236651/43200249-3c8870b8-9015-11e8-902f-91e7c8c02112.png)

1) Create a new F# project ``Console App (.NET Core)``

2) Let VS do its thing, after a few seconds everything works. Do a build for good measure.  
![grafik](https://user-images.githubusercontent.com/4236651/43200303-69fd3308-9015-11e8-95ce-132f1d75c176.png)

3) Close VS and delete the ``.vs`` directory

4) reopen the solution: build works, but editor features don't  
![grafik](https://user-images.githubusercontent.com/4236651/43200356-9ba50ab6-9015-11e8-94c8-596e5b050883.png)

5) __Restart VS one more time, after that, everything works again__

_Copied from original issue: dotnet/project-system#3788_

**Comment by davkean** [comment]
_From @Pilchie on July 25, 2018 20:16_

@TIHan can you take a look at this?

**Comment by davkean** [comment]
_From @TIHan on July 25, 2018 20:25_

Yes, going to look at it now.

**Comment by davkean** [comment]
_From @Pilchie on July 25, 2018 21:26_

Leaving in 15.8 for investigations.

**Comment by davkean** [comment]
_From @TIHan on July 26, 2018 0:43_

I know what is happening now. F#'s language service is not being initialized unless a document has been opened. This means we miss out on all the workspace events that F#'s language service needs.

To be more specific, `FSharpPackage` doesn't get initialized until a F# document has been opened.

**Comment by davkean** [comment]
_From @TIHan on July 26, 2018 22:21_

I have a fix for this coming. It is a bug in the F# language service.

**Comment by TIHan** [comment]
This has been resolved.
