### ISSUE TITLE
Does F# tools in Visual Studio 2015 use Light Bulb?

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#540]

**Comment by latkin** [comment]
Light Bulb is more or less a replacement for "Smart Tags" (the little box that appears under bits of your code, or for spellcheck in MS Office). The light bulb idiom has become somewhat of a standard editor thing, so VS opted to move there rather than continue with smarttags.

The in-box F# tools never exposed any features using smarttags, so we do not use light bulbs now.  The Visual F# Power Tools do use smarttags, though, they might want to consider moving to light bulbs for VS 2015. /cc @dungpa  @vasily-kirichenko

**Comment by vasily-kirichenko** [comment]
@latkin If you point us at the API, we will move to Light Bulb :)

**Comment by isaacabraham** [comment]
@vasily-kirichenko at the moment power tools still even work with CTRL + . in 2015. I've not been able to find any way to stop lightbulb from claiming that shortcut.

**Comment by dungpa** [comment]
The new API is here https://msdn.microsoft.com/en-us/library/vstudio/dn903708(v=vs.140).aspx. The tricky part is to preserve behaviours for VS 2013 and VS 2012 without splitting the code base.

**Comment by vladima** [comment]
VFPT should already have machinery in-place to import components with a minimal required VS version, it is currently used in implementation of NavigateTo [here](https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic/NavigateToItem.fs#L33) and [here](https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/src/FSharpVSPowerTools.Logic.VS2013/NavigateToItemDisplay2.fs#L13). Bits that select the best supported component can be extracted and generalized.

**Comment by xperiandri** [comment]
My issues are here
https://github.com/fsprojects/VisualFSharpPowerTools/issues/1043
https://github.com/fsprojects/VisualFSharpPowerTools/issues/1041

**Comment by xperiandri** [comment]
Will this work for F#?
https://msdn.microsoft.com/en-us/library/dn903708.aspx

**Comment by vladima** [comment]
If by work you mean "is it possible to show lightbulb in F# text editor", then yes, it should work.

**Comment by xperiandri** [comment]
Could you @vladima or someone else explain me how to add Light Bulb support into VFPT in a right way in a Skype call? So I can quickly get started.

We need to update:
- implement interface
- rename
- generate record stub
- generate union pattern match cases
- generate references for FSI
So if I know how to update one of them I will do this for other

Explaining how to do [Use new Visual Studio 2015 UI to rename bindings (variables)](https://github.com/fsprojects/VisualFSharpPowerTools/issues/1041) would also be helpful

**Comment by vladima** [comment]
Information in the [instruction](https://msdn.microsoft.com/en-us/library/dn903708.aspx) you've mentioned before should be enough to make editor show lightbulb, I don't think I can add anything to it in general. I would suggest you to try it and get back with a list of specific questions (if there are any).

Regarding inline rename - this functionality is currently is not provided by the editor out of the box and was implemented by the Roslyn team. As a consequence it is accessible only for languages that use Roslyn API, namely C#, VB.NET and TypeScript.

**Comment by xperiandri** [comment]
@vladima I have built only one extension in my life recently and it extends Entity Framework Data Model designer.
All I know about extending Visual Studio is that it is done with MEF (I know MEF).
I need some advice what to read to get started in extending Visual Studio Editor. And how to expose version dependent behavior.

**Comment by vladima** [comment]
I would start with going through the instruction step-by-step. Also a few extra articles that can be helpful:
- [Inside the editor](https://msdn.microsoft.com/en-us/library/dd885240.aspx)
- [Extending the editor](https://msdn.microsoft.com/en-us/library/dd885242.aspx)

**Comment by xperiandri** [comment]
Thanks, I will have a look
