### ISSUE TITLE
Enable Snippets in F# and install a basic set with tools

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#542]
Implement snippets logic in F# tools and install a basic set of snippets with F# tools.
There is an [extension from one of MSFTs](https://visualstudiogallery.msdn.microsoft.com/d19080ad-d44c-46ae-b65c-55cede5f708b). But it is not opensourced and snippets does not appear in IntelliSense. So I can't just type a snippet name and press tab to expand.
Also it requires to do a lot of steps to enable snippets which can be done by F# tools installer.

**Comment by latkin** [comment]
Thanks for the suggestion!  We handle feature requests on UserVoice.  I would recommend adding votes/comments to this guy: http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2227602-add-code-snippet-support-for-f
