### ISSUE TITLE
Code Lense support

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#543]
What is necessary to do to implement Code Lens in F#?

**Comment by latkin** [comment]
At the moment CodeLens is an internal-only API, it's not part of the VS SDK that users or extension authors can plug into.  Off the top of my head I'm not really familiar with it at all, so I can't give an informed answer as to what's needed to integrate with it.

If you would like to see CodeLens for F#, please open a suggestion at http://visualstudio.uservoice.com/forums/121579-visual-studio/category/30935-languages-f-tools. I see there is one for C++ already: http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/4230372-codelens-for-c

**Comment by xperiandri** [comment]
Vote here
http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/8960266-codelens-for-f
http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/6518006-expose-an-api-to-be-able-to-extend-or-take-advanta
