### ISSUE TITLE
VS2015 RTM about box shows "Visual F# 2015 RC"

### ISSUE THREAD

**Issue by lasandell** [Microsoft/visualfsharp#545]
After installing Visual Studio 2015 RTM, the about box still shows "Visual F# 2015 RC".

![vs2015about](https://cloud.githubusercontent.com/assets/2034420/8784251/a38be472-2ee6-11e5-9ba0-f01b778df95f.png)

**Comment by latkin** [comment]
Thanks, nice catch.  Does it show the same in Control Panel add/remove programs?

**Comment by lasandell** [comment]
I actually don't have an uninstall entry for F# at all. Maybe that's only when you use the stand-alone installer?

**Comment by eriawan** [comment]
@latkin, 

I have tried to install VS 2015 editions on two VMs, including Enterprise and Professional on a clean VM of Windows 8.1 with Update (with no previous version of Visual Studio installed). And in VS 2015 Enterprise, the about box is also showing Visual F# 2015 RC:

![vs2015_enterprise_about](https://cloud.githubusercontent.com/assets/8773147/8841392/17b7e8a0-3117-11e5-8514-ef93062619fc.png)

The installation of Visual F# tools is included in a big composite of Visual Studio Enterprise 2015 or in Visual Studio Professional 2015.

My conclusion for now is there's no entry for standalone installation of Visual F# 4.0 tool in Control Panel after installation of Visual Studio 2015 (or entry of Visual F# 4.0 as separate component).

I'm not sure for other edition such as Community, though.

**Comment by bogdangaliceanu** [comment]
@eriawan Community shows RC as well

**Comment by lasandell** [comment]
If I install the [stand-alone Visual F# Tools](http://www.microsoft.com/en-us/download/details.aspx?id=48179&WT.mc_id=rss_alldownloads_devresources), then Programs and Features correctly shows an entry for "Microsoft Visual F# 4.0".  However, the installer still makes reference to the Visual Studio RC, which I do not have installed:

![image](https://cloud.githubusercontent.com/assets/2034420/8861385/ca656e2c-314f-11e5-832c-52bd69739cc4.png)

**Comment by veikkoeeva** [comment]
It looks like the F* guys came across this and maybe other things too. The issue: https://github.com/FStarLang/FStar/issues/308.

**Comment by latkin** [comment]
@veikkoeeva thanks for the pointer

**Comment by KevinRansom** [comment]
This is fixed in Update 1.
