### ISSUE TITLE
match! breaks structure guidelines and collapsible nodes

### ISSUE THREAD

**Issue by kerams** [Microsoft/visualfsharp#5456]
Structure guidelines and collapsible nodes below a `match!` are missing.

#### Repro steps

```fsharp
let blah = async {
    match! async { return Some 1 } with
    | Some _ -> ()
    | None ->
        if true then
            if true then
                if true then
                    () }
```

#### Expected behavior

Structure guidelines and collapsible nodes are present.

#### Actual behavior

![untitled](https://user-images.githubusercontent.com/5063478/43638988-00d8549a-971b-11e8-828f-8d220fbf0d05.png)

#### Known workarounds

None.

#### Related information 

Provide any related information 

VS 2017.8 Preview 5

**Comment by cartermp** [comment]
I have a fix for this, but cannot verify it due to https://github.com/Microsoft/visualfsharp/issues/5465

**Comment by cartermp** [comment]
Fixed
![image](https://user-images.githubusercontent.com/6309070/44175720-efe5f400-a09b-11e8-92b5-409735b1b1af.png)
