### ISSUE TITLE
Completion consumes enter key even when nothing is completed

### ISSUE THREAD

**Issue by ricksladkey** [Microsoft/visualfsharp#5488]
Although completion is an invaluable feature, many times I know what I want to type and I just type it without looking at the screen. I have repeatedly been surprised when I know I typed enter, but when I look the text is still on the same line and what I have typed is smashed up against the last word I typed before I typed enter.

After paying more attention to what is going on, I discovered that what is happening is completion recognized that I was starting to type a keyword, e.g. "then" and even though I typed all the letters "t", "h", "e", and "n", the completion consumed the enter key that I typed as though I was confirming, "yes, that is the keyword I want you to complete."

This is an irritation that I now have to look at the screen to see if my enter key "took effect" and put me on a new line, and if it didn't, type enter again, this time for real. Perhaps it seems like a small thing but it slows me down and interrupts my flow.

Completion should only consume the enter key when the word being completed is incomplete or ambiguous; it should not interfere if the user typed all the keys for the word being completed.

#### Repro steps

1. In any F# file, begin to type a condition expression `if true the`

2. Wait for the completion service to recognize that the word `then` is a valid completion for `the`

3. Type `n<Enter>`

4. Observe that the caret is still positioned at the end of the word `then`

#### Expected behavior

Typing `then<Enter>` should move the caret to the next line.

#### Actual behavior

Typing `then<Enter>` only sometimes moves the caret to the next line.

#### Known workarounds

Visual check the screen to see whether the enter "took effect", and if not, type it again.

#### Related information 

* Windows 7
* Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 173513e369ffb7a1c4d5dccf83696d9aac2ab2d0.
* .NET Runtime, CoreCLR or Mono Version
* Microsoft Visual Studio Community 2017 - Version 15.7.6 - VisualStudio.15.Release/15.7.6+27703.2047
* Microsoft .NET Framework - Version 4.7.02558

It is possible some users prefer the current behavior or have grown used to it. The C# Language Service allows this very behavior to be configured:

![image](https://user-images.githubusercontent.com/2680524/43939825-6c34d618-9c3a-11e8-9fee-aa623e6f3f89.png)

**Comment by cartermp** [comment]
This should be pretty straightforward to implement.

Basically, represent [this enum](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/EnterKeyRule.cs,106ae6852615e18b) in F# settings and wire it up [here](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/Completion/CompletionService.fs#L33).

**Comment by cartermp** [comment]
@ricksladkey #5530

**Comment by ricksladkey** [comment]
This was a sweet, sweet day when I realized this feature was in VS2019.  Thanks @cartermp!

![image](https://user-images.githubusercontent.com/2680524/58062402-465ef200-7b48-11e9-9b27-b17443241f07.png)

**Comment by cartermp** [comment]
No problem! I was scared for a second, saying that you hadn't seen the option at all 😅
