### ISSUE TITLE
IntelliSense - Quick Info not indicating statically resolved type parameters correctely

### ISSUE THREAD

**Issue by Calogyne** [Microsoft/visualfsharp#550]
Hi, I'm using Visual Studio Community 2015 with Visual F# 4.0

For example, the function

```fsharp
let inline printAsFloatingPoint number =
    printfn "%f" (float number);;

//val inline printAsFloatingPoint :
//number: ^a -> unit when  ^a : (static member op_Explicit :  ^a -> float)
````
would show 
![36qgsc6mbffb 15vodeicq](https://cloud.githubusercontent.com/assets/11813352/8829615/27717aa6-30ca-11e5-97b9-1d2ff3f0e1bb.png)
in Quick Info, where the type parameters are supposed to be `^ident`
Is this behavior by design or is it a bug? It confused me while I was learning about statically resolved types and inline functions.

**Comment by dsyme** [comment]
I believe this is deliberate (QuickInfo sometimes shows a simplified version of the signature - e.g. the "requires member op_Explicit" is deliberately simplified).

Cheers
don

**Comment by latkin** [comment]
Can you be explicit about what exact text you expect the quickinfo to display?  The current content is definitely intentionally simplified, but maybe there is a clearer/better way to represent statically resolved type args. I think we'd be open to a PR tweaking this in a sensible way.

**Comment by Calogyne** [comment]
I think the quickinfo should match the function signature exactly for better clarity, where: 1. inline functions are expected to differ from normal generic functions in some ways;  2. using `^` for statically resolved type args is specified in the documentation.

**Comment by dsyme** [comment]
I understand the POV. That said, the signature simplification was a design choice we already made in F# 2.0. It was a considerable improvement to usability that has not been the source of significant problems. So this is by design I'm afraid.

Feasibly there could be a VS option "show full detail of all type signatures in QuickInfo" but that would be a feature request?

best regards
don

**Comment by bender2k14** [comment]
For what it's worth, I was recently learning F# and static resolved type parameters and was very confused when I encountered this.  I thought I didn't correctly understand statically resolved type parameters or was failing to make use of them.
