### ISSUE TITLE
15.8 Internal MSBuild Error

### ISSUE THREAD

**Issue by asik** [Microsoft/visualfsharp#5504]
Upgrade from 15.7.6 to 15.8
Open solution 
Build (Rebuild, Clean/Rebuild, whatever)

1>------ Rebuild All started: Project: ****************, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: ********************, Configuration: Debug Any CPU ------
2>Unhandled Exception:MSB0001: Internal MSBuild Error: Already registered for build-time.
2>Error: MSB0001: Internal MSBuild Error: Already registered for build-time..

I emptied all VS cache folders and ran a repair install, no luck.
I could repro with a dummy solution with just an empty console app and 2 empty libraries, all on .NET Framework (not .NET Core or Standard). However after closing and reopening VS on that solution, I could no longer repro.
[ConsoleApplication2.zip](https://github.com/Microsoft/visualfsharp/files/2288142/ConsoleApplication2.zip)

I can always repro on our solution with 90+ projects (mix F#/C#, all .NET Framework).

Tools->Options->Projects and Solutions->Build and Run->
Reducing the number of parallel projects to 1 was a workaround.

Another weird thing I noticed is that in the Project Properties->Application, the Target Framework dropdown is empty:

![image](https://user-images.githubusercontent.com/1631157/44112109-3ba2eaee-9fd2-11e8-8364-1d3810b0db79.png)

Since this version seems completely broken and I need to work, I'm going to downgrade to the previous release using these instructions https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017 

EDIT: The problem is gone after reverting back to 15.7.6.

**Comment by cartermp** [comment]
For posterity

MSBuild issue: https://github.com/Microsoft/msbuild/issues/3610
Devcom issue: https://developercommunity.visualstudio.com/content/problem/311575/exceptionmsb0001-internal-msbuild-error-already-re.html

Labeling this as external unless we get confirmation that is an issue on our side.

**Comment by Savelenko** [comment]
I also came across this issue, on two different machines after upgrade to VS 15.8 on .NET Framework.

**Comment by 0x53A** [comment]
The linked MSBuild issue explicitly mentions ``old style fsproj``. Can you confirm whether new-sdk is affected before I update to 15.8?

**Comment by hejoco** [comment]
Experiencing same issue after upgrading to 15.8. My solution has one C# project and three F# projects. The error message always complains about the same F# project.

**Comment by cartermp** [comment]
After a thorough investigation with the MSBuild and Project System teams, we've identified the sources of the problem and a few possible fixes. The cheapest one we arrived at would involve changing the F# classic project system, so we'll be doing that (hence the label change). The issue arises when [this condition is met](https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.ProjectSystem.Base/Project/ProjectNode.cs#L3316).

We're currently working on a fix, but we'll need to assess the impact of that fix before pushing anything.

**Comment by BentTranberg** [comment]
I doubt the following is useful information, but just in case it is. Not a practical problem for me - just an observation.

I have set the number of concurrent builds to 1, as a workaround for this issue, which affects all my solutions on all machines. Mix of C#/F#/Framework/Standard/Core. It has worked flawlessly until now. When I tried to add a package with NuGet (not Paket), I got one set of these errors (they come in pairs) in spite of the workaround. Retrying solved it there and then.

**Comment by curdincaspar** [comment]
@cartermp What is the status of this?

**Comment by cartermp** [comment]
@curdincaspar There is a fix out at #5557, but @KevinRansom is currently fixing CI before that can be merged.

**Comment by cartermp** [comment]
Now that the fix is merged, users with the nightly builds can see it. We'll be striving for a servicing fix for 15.8 and also merging this into the 15.9 branch. We'll report back when we have more detailed information.

**Comment by KevinRansom** [comment]
Let's close when it's in 15.9 pls.

**Comment by cartermp** [comment]
This has been inserted and shipped in 15.8.5.
