### ISSUE TITLE
Visual Studio New template fails to create new .NET 4.0 F# project.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#5507]
With this dialog:
![image](https://user-images.githubusercontent.com/5175830/44117618-acb6bc24-9fc8-11e8-8aed-ae2d20d452bc.png)

This is by design the nuget template for F# targets has a minimum target framework of 4.5.

This should be addressed by suppressing the ability to target 4.0 frameworks in the framework selector for new F# projects.

![image](https://user-images.githubusercontent.com/5175830/44117811-31202bbc-9fc9-11e8-85d3-8ce2fe30702f.png)

**Comment by cartermp** [comment]
Kind of iffy on this one. .NET Framework 4.0 is officially unsupported, but enough people do target it that we may want to consider some kind of frozen template that works for the time being.

**Comment by KevinRansom** [comment]
Well we don't have an FSharp.Core.dll which is the real issue.

**Comment by cartermp** [comment]
Talked with @KevinRansom and the correct thing to do here is to make .NET Framework 4.5 a requirement for new projects, as this is the lowest FSharp.Core that we can actually build. For those who must create a new project targeting .NET Framework 4.0, manually adding the entries in the project file can accomplish their goal.

**Comment by cartermp** [comment]
Closing as #5509 addresses this.
