### ISSUE TITLE
Breakpoints do not work in (some?) large methods in VS2015 RTM

### ISSUE THREAD

**Issue by Rickasaurus** [Microsoft/visualfsharp#551]
I'm having trouble producing a small example. It's a VS2013 project that has been loaded in VS2015. It's effecting two large (~20 line) methods which aggregate my internal functional API into a nice C# friendly API. The project is 19 fs files each of which is at least a few pages in size.

Breakpoints anywhere within these methods do not set. They are both in classes with only one method, being classes so they can do some precomputation in the implicit constructor to save extra work.

Breakpoints within the let bindings of the constructor do work just fine, and other classes in the same file with small bodies work fine as well.  

I haven't been able to reproduce this in a smaller project, and was hoping there might be some way to see what is going on when I click on the margin to set a breakpoint.

Thanks.

**Comment by Rickasaurus** [comment]
Also, I should mention that I can set breakpoints just fine if I load this same project up in VS2013. I tested SP4 and SP5.

**Comment by Rickasaurus** [comment]
Here is one of the classes I mentioned:

```fsharp
    type ClassScorer (gsettings: SafeAlertSettings, settings: ClassSetting) = 
        let filePath = Path.GetDirectoryName(gsettings.FilePath)
        let parameterExtractor = new ParameterExtractor(filePath, settings.DataDerivation)
        let dataStructurer = new DataStructurer(filePath, settings.DataStructuring)
        let siCalculator = new ScoreCalculator(settings.FeatureParameters, gsettings.AdditionalFeatures, gsettings.Defaults.FeatureParameters.AdditionalFeatureWeights)
        let featureGroups = gsettings.GetAllFeatureGroups()
        let outputFilter = new OutputFilter(gsettings.Output)
        with member t.Score hit custDobsRx provDobsRx = 
                try
                    let sPair = dataStructurer.Structure hit custDobsRx provDobsRx

                    let cleanedFeatures = parameterExtractor.Extract(sPair.StructuredCust, sPair.StructuredProv, hit)
                    let record : ScoreRecord = 
                        { FilePath = filePath
                          Hit = hit
                          Params = cleanedFeatures 
                          StructuredCust = sPair.StructuredCust
                          StructuredProv = sPair.StructuredProv }

                    let rankingResults = siCalculator.ScoreFeatures record

                    let siComps = 
                        rankingResults.FeatureScores 
                        |> Map.map (fun k v -> v |> Seq.sumBy (fun fnv -> fnv.Value))
                        
                    let hit = { hit with PairScore = Some { SIComponents = siComps; SITotal = rankingResults.TotalScore } }

                    Success (ViewRecord.FromScan featureGroups hit sPair.StructuredCust sPair.StructuredProv rankingResults cleanedFeatures |> updateOutputClass outputFilter) 
                with ex -> Failure(hit, ex)
```

VS2015 will not let me set breakpoints anywhere within the Score function. I don't think it's related to the try ... with as another effected method is not of that form.

**Comment by Rickasaurus** [comment]
Also, this may be useful, the file is a namespace at the top level, and these classes are in an internal module. 

```fsharp
namespace MyProj.Stuff

... // Lots of open statements

module internal APIInternals = ...
```

**Comment by dsyme** [comment]
Will it deny breakpoints before debugging (that calls ValidateBreakpointLocation), or does it fail to set them properly once you start debugging? (validated by debugger wrt IL code)?

**Comment by Rickasaurus** [comment]
Yes, it won't let me set them at any time. This is true in both Release and Debug mode.

**Comment by dsyme** [comment]
@Rickasaurus  - 

Replace 

        with member t.Score hit custDobsRx provDobsRx = 

by 

        member t.Score hit custDobsRx provDobsRx = 

The use of "with" to start an augmentation is never needed for a class type (and I actually don't really ever recommend using "with member ...e" for record and union types, but rthat a separate matter).  It seems like setting breakpoints in "with" augmentations on class types is not supported (either in VS2013 or VS2015).  That's a bug but it will be easy to fix in ValidateBreakpointLocation

Please let us know if that solves your problem

thanks
don

**Comment by dsyme** [comment]
Minimal repro:

```
type ClassScorer(a:int) = 
    let x = 1
    with member t.Socre x = 
           let a = x + 1 // try to set a breakpoint on this line
           a, a
```

**Comment by Rickasaurus** [comment]
This fixes it! Thanks Don!

**Comment by latkin** [comment]
Marking up for grabs

**Comment by dungpa** [comment]
@latkin Is this supposed to be fixed (i.e. non-issue)?

**Comment by latkin** [comment]
@dsyme provided a workaround (omit the `with`), but it should be fixed so that breakpoints can be set without the workaround.

**Comment by latkin** [comment]
I think this is a parser bug - the assigned range for an ObjectModel declaration does not currently include it's augmentation's range, so ValidateBreakpointLocation "correctly" decides the requested BP is not within any known ranges.

This looks like an oversight, as the other `tyconDefn` cases do combine all the ranges together. Relevant code is [here](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/pars.fsy#L1438-L1449), this case should have a `unionRangeWithListBy` bit like the previous 2 cases.  Adding that fixes the bug in my testing.

Will send a PR...
