### ISSUE TITLE
Rename factor does not work on Record type name.

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#5520]
In 15.8, renaming the type of a Record does not change associated type annotations:

![rename](https://user-images.githubusercontent.com/1781813/44202591-b7522300-a14c-11e8-91b6-0eaaa82abef6.gif)

**Comment by cartermp** [comment]
@isaacabraham Is the file saved on disk? If so, then this is a dupe of #2204

**Comment by cartermp** [comment]
So long as files are saved on disk, rename updates everything for me on my 15.8 install.

**Comment by cartermp** [comment]
@isaacabraham can you confirm that this was for an unsaved file?

**Comment by cartermp** [comment]
Was it a script file? Renaming like this on a "naked" script that isn't in works for me.

**Comment by cartermp** [comment]
I just tested this with Open Folder > Create fsx file > Rename, and it works. Do you have something you can upload that reproduces?

**Comment by cartermp** [comment]
@isaacabraham Closing this as it's been open without a repro for quite some time. If you have a reproducible scenario please report back and we can re-open it.
