### ISSUE TITLE
What is the difference betwean Microsoft/visualfsharp and fsharp/fsharp/ repositories?

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#553]
What is the difference between [Microsoft/visualfsharp](https://github.com/Microsoft/visualfsharp/) and [fsharp/fsharp/](https://github.com/fsharp/fsharp/) repositories?
I am confused with this coexistence.

**Comment by latkin** [comment]
Hi @xperiandri, thanks for you interest! This is explained briefly in [README.md](https://github.com/Microsoft/visualfsharp/blob/fsharp4/README.md) in the root of repo.  More details are linked, in particular [here](https://github.com/Microsoft/visualfsharp/wiki/Code-Flow-to-Open-Edition).
