### ISSUE TITLE
Inconsistent behavior with method shadowing

### ISSUE THREAD

**Issue by runefs** [Microsoft/visualfsharp#5543]
### Description

I had an issue with method shadowing not being consistent with F#. So I tested it in REPL2  and found the particular issue is resolved however I found a different.

### Repro code

```fs
type a() =
    member x.Foo() = printf "Yeah from A!"

type b() = 
   inherit a()
   member x.Foo() = failwith "Nay from B!"

type c() =
  inherit a()
  member x.Foo() = printf "Yeah from C!"

let bb = b()
let cc = c()
(bb :> a).Foo()
bb.Foo() //should throw but instead calls a.Foo()
cc.Foo() // inconsistent with the above line. This actually calls c.Foo()
```

[code snippet](http://fable.io/repl2/#?code=C4TwDgpgBAhgFASigXgLACgNW1AthXAIwgCcoAPAOgDEB7WxFKMEgSwDtgAzKAIgE0IMABZQuJWrigBBAIS8Mi9KEhRCjZFCzYOw0q2CxE2vAWJkqdBkk1cYrADYB3A6N4A5GCDESpAIXklFWgAYw1tXX1DeARtfCJSChp6DWY2Th4BIVFxSSgAYUDMYocIQ0JCJnVY9FLDEJCmMJq4CqgALgA+WARk6wwKvuN0BqGEIA&html=DwCwLgtgNgfMBGB7AJgTzgeiWz5oyA)

### Expected and actual results

see code comments.

This was originally reported as a Fable issue but it was found that FSI have the same behavior. See [https://github.com/fable-compiler/Fable/issues/1525#issuecomment-414935175](this issue)

**Comment by smoothdeveloper** [comment]
The reason is that `B.Foo` is in fact `B.Foo<T>` and not a shadowing method.

With type annotation
```fsharp
type a() =
    member x.Foo() = printf "Yeah from A!"

type b() = 
   inherit a()
   member x.Foo () : unit = failwith "Nay from B!"

type c() =
  inherit a()
  member x.Foo() = printf "Yeah from C!"

let bb = b()
let cc = c()
(bb :> a).Foo()
bb.Foo()
cc.Foo()
```

**Comment by TIHan** [comment]
Closing as what @smoothdeveloper showed, it's not actually shadowing a method because it is a generic function due to `failwith`, so annotations are required.

**Comment by runefs** [comment]
As eric lippert would say "[Maybe there's something wrong with the universe but probably not](https://blogs.msdn.microsoft.com/ericlippert/2011/04/25/maybe-theres-something-wrong-with-the-universe-but-probably-not/)". Thanks for the explanation
