### ISSUE TITLE
running fsianycpu.exe fails with missing assembly

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#5544]
After updating my VS2017 to 15.8.1, if I launch fsianycpu.exe from the sdk folder (C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0)

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Compiler.Private, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Sample.Microsoft.FSharp.Compiler.Interactive.Main.MainMain(String[] argv)
```

I just want to confirm if this is a known issue and if there is a workaround?

**Comment by vasily-kirichenko** [comment]
Fresh windows + vs 15.8.1 installation: 

![image](https://user-images.githubusercontent.com/873919/44468565-2a1c3c00-a62e-11e8-854b-feb2fcb38f2f.png)

**Comment by smoothdeveloper** [comment]
It seems my `C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0` is spurious, @vasily-kirichenko pointed me to `c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp\` which works.
