### ISSUE TITLE
Multi-targeting broken with sdk 2.1.401 and mono 5.12

### ISSUE THREAD

**Issue by TheAngryByrd** [Microsoft/visualfsharp#5554]
Please provide a succinct description of the issue.

Multi-targeting seems broken with dotnet sdk 2.1.401 and mono 5.12.

```
/usr/local/share/dotnet/sdk/2.1.401/FSharp/Microsoft.FSharp.Targets(183,9): error MSB4062: The "FSharpEmbedResXSource" task could not be loaded from the assembly /usr/local/share/dotnet/sdk/2.1.401/FSharp/FSharp.Build.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

#### Repro steps

Provide the steps required to reproduce the problem

1. On mac or linux, install dotnet sdk 2.1.401 and mono 5.12

2. create a new project, `dotnet new console -lang F#`

3. see `dotnet build` works

4. Add a new target framework net472 `<TargetFrameworks>netcoreapp2.1;net472</TargetFrameworks>`

5. Ensure  dotnet sdk can find reference assemblies`export FrameworkPathOverride=$(dirname "$(which mono)")/../lib/mono/4.7.1-api/`

6. build fails with error message described above

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

[what.zip](https://github.com/Microsoft/visualfsharp/files/2318451/what.zip)

You can just run `./build.sh` and will demonstrate the issue

#### Expected behavior

Build passes

#### Actual behavior

Build fails

#### Known workarounds

Use an older sdk

#### Related information 

Provide any related information 

* Operating system 
MacOs (i suspect linux as well)
* Branch 
* .NET Runtime, CoreCLR or Mono Version 
dotnet sdk 2.1.401
mono 5.12
* Editing Tools (e.g. Visual Studio Version)
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
* Links to performance testing scripts
* Indications of severity

**Comment by cartermp** [comment]
@KevinRansom any idea?

Is this also related to #3925?

**Comment by brettfo** [comment]
Can you try to update your version of mono?  Using `dotnet` 2.1.401 and `mono` 5.14.0.177 I'm able to restore/build on Ubuntu 18 (I don't have a Mac to test on).

**Comment by KevinRansom** [comment]
@TheAngryByrd 

I am unable to repro this on my macbook.

I installed mono from here:       https://download.mono-project.com/archive/5.12.0/macos-10-universal/

If you can still repro this, could you please attach a zip file containing pp.out and diag.out retrieved as below:

dotnet build /pp >pp.out
dotnet build /t:rebuild /v:diag >diag.out


Thanks

Kevin
````
MacBook-Pro:foo kevinr$ ls /Library/Frameworks/Mono.framework/Versions
5.12.0	Current
MacBook-Pro:foo kevinr$ cat foo.fsproj 
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp2.1;net461</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
MacBook-Pro:foo kevinr$ dotnet restore
  Restore completed in 37.21 ms for /Users/kevinr/projects/foo/foo.fsproj.
MacBook-Pro:foo kevinr$ dotnet build
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 28.96 ms for /Users/kevinr/projects/foo/foo.fsproj.
  foo -> /Users/kevinr/projects/foo/bin/Debug/net461/foo.exe
  foo -> /Users/kevinr/projects/foo/bin/Debug/netcoreapp2.1/foo.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.21
MacBook-Pro:foo kevinr$ dotnet --version
2.1.401
MacBook-Pro:foo kevinr$ 

````

**Comment by TheAngryByrd** [comment]
Now I also cannot reproduce this 😞 .

**Comment by KevinRansom** [comment]
@TheAngryByrd, I hate it when that happens, you have my sympathies.

Kevin

**Comment by realvictorprm** [comment]
just seeing that on my machine. Weiiird :D
