### ISSUE TITLE
No FSharp.Core.xml

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5565]
![image](https://user-images.githubusercontent.com/873919/44722180-f67d5e00-aad4-11e8-9b64-022bb506a611.png)

VS 15.8.1

**Comment by cartermp** [comment]
Pretty sure this is just deployed for compat reasons, is that right @brettfo? The NuGet package that all new projects depend on contains the XML file.

**Comment by auduchinok** [comment]
@cartermp AFAIK it's the assembly that goes into script options created by FCS (and is used by fsi/fsc themselves BTW), so the XML file could be important there.

**Comment by dsyme** [comment]
> @cartermp IIRC it's the assembly that may go into script options created by FCS (and is used by fsi/fsc themselves BTW), so the XML file could be important there.

I checked and we are getting XML hints when editing F# script files, even without any F# projects loaded.   So unless there is a specific problem in the IDE I think we should close this.
