### ISSUE TITLE
Open references item is shown as a folder instead of references

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#559]
When references project item is closed it has icon of References.
But if it is open the icon changes to Folder icon.
This does not happen in any other project type!

<img width="209" alt="f references item opens as folder" src="https://cloud.githubusercontent.com/assets/2365592/8936570/b7ba882e-355b-11e5-97fe-dbda19945fe2.png">

**Comment by latkin** [comment]
Yes it would be nice to use the standard icon. Would welcome a fix for this, marked up for grabs.

**Comment by xperiandri** [comment]
As I understand it is a problem with icon index, isn't it?

**Comment by xperiandri** [comment]
How to fix this?
I forked this repository and opened Deployment.sln in VS 2015 from `visualfsharp\vsintegration\src` but all the F# stuff is not loaded 
![34](https://cloud.githubusercontent.com/assets/2365592/9252955/ec288c0c-41e3-11e5-839b-fc76221a6a1f.png)

**Comment by xperiandri** [comment]
I can't understand why it is so complex to prepare environment for any open source software.
I need to do 100500 steps to be able to open a solution and do 1 simple fix.

**Comment by xperiandri** [comment]
@latkin, could you point me to a right project within this repository related with this issue?

**Comment by dsyme** [comment]
@xperiandri Yes, the workflow to contribute to the Visual F# tools project system is painful - and I'm sure that's one reason why we get relatively few contributions to that component.  We need to make that much simpler.
