### ISSUE TITLE
Add a #n directive to fsi which loads nuget packages

### ISSUE THREAD

**Issue by toburger** [Microsoft/visualfsharp#56]
This was already discussed [here](https://visualfsharp.codeplex.com/workitem/42), but the issue was closed with the note that it is already under review on [UserVoice](http://fslang.uservoice.com/forums/245727-f-language/suggestions/5670137--package-directive-to-import-nuget-packages-in-f).
I would be very happy to get further information on the progress of this issue.

**Comment by dsyme** [comment]
As @latkin has labelled, I think this is still a discussion/feature-request item. I'm not sure what @latkin  and @KevinRansom want, but I personally think it is best to keep feature-requests off GitHub until a later stage (e.g. they are "approved" or a concrete design is available or an implementation pull request is available).  Equally, I may be wrong, especially if good labelling is used.  Ultimately it's up to the @latkin  and @KevinRansom  as current masters of the repo :)

**Comment by smoothdeveloper** [comment]
Relevant ticket: #1177

If this get implemented, as @dsyme described in [a comment](https://github.com/Microsoft/visualfsharp/issues/1177#issuecomment-220180588) it would better be based on custom handlers and some type of URI scheme so it can be extended.

**Comment by enricosada** [comment]
It's possibile to add to `fsi` as cli parameter the name/assembly of a resolver? Using an external assembly resolver, there is no need to add special use case inside fsi (paket, nuget, etc).
Or as internal fsi command `#resolver "path/to/resolver.dll`
So `#r "suave"` is resolved by custom resolver, who can for example download the nuget package or use it from paket.

**Comment by smoothdeveloper** [comment]
@enricosada yes with @dsyme idea we won't have special case for nuget, paket etc.

His idea:
```fsharp
#r "references:nuget-handler.dll"  // specially attributed DLL
#r "SomeNugetPackage"
```

But we can refine.

What your propose about command line argument is an important point and I agree having possibility to reference the handler from there, and maybe also having fsi scan a folder with additional handlers would be great!

**Comment by dsyme** [comment]
Closing as suggestion is tracked by https://github.com/fsharp/fslang-suggestions/issues/542
