### ISSUE TITLE
Comparing of F# files crushes Visual Studio 2015

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#560]
When I compare F# files from Changes page of Team Explorer and right after I close a comparison window Visual Studio crushes.

Dump and reproduction steps included on Connect
https://connect.microsoft.com/VisualStudio/feedback/details/1602452/comparing-of-f-files-crushes-visual-studio-2015

I disabled Navigation Bar, F# Power Tools and F# Outlining and this does not help.

**Comment by xperiandri** [comment]
Only I affected?

**Comment by xdaDaveShaw** [comment]
Is this the GIT or TFS Change page? They are different.

**Comment by xperiandri** [comment]
Git
Looks like I fixed the problem.
After reinstallation of Azure Tools 2.7 and ASP.NET and Web Tools 2015 from Remove Programs.

**Comment by xdaDaveShaw** [comment]
I can't repro on my clean VS2015 Ent installation.

**Comment by dsyme** [comment]
Closing since @xperiandri reports the issue fixed
