### ISSUE TITLE
Build fails on Windows 10

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#561]
I have a new PC with:

  * Windows 10 Enterprise german
  * VS 2015 RTM
  * VS 2015 SDK RTM

and the build fails with

![image](https://cloud.githubusercontent.com/assets/57396/8977649/50ebc0c2-369b-11e5-9717-ac18e3c08c03.png)

    C:\code\visualfsharp\vsintegration\src\vs\FsPkgs\FSharp.Project\FS\ProjectSys
tem.fsproj(138,7): 
    error MSB3073: Der Befehl ""C:\Program Files (x86)\Windows K
its\8.1\bin\x86\rc.exe" /fo obj\Release\net40\ProjectResources.rc.res ProjectRe
sources.rc" wurde mit dem Code 9009 beendet.

so something in WindowsKits\8.1 failed with code 9009

**Comment by forki** [comment]
I just read 9009 means `Command not found` which makes sense. I don't have Win 8.1

**Comment by dungpa** [comment]
Does it work if you install Windows SDK?

This
https://dev.windows.com/en-us/downloads/windows-10-sdk
or
https://msdn.microsoft.com/en-us/library/windows/desktop/bg162891.aspx

It seems to be mentioned implicitly at https://github.com/Microsoft/visualfsharp/wiki/Required-Software

**Comment by forki** [comment]
yes I'm already installing that and update the guide if it works

**Comment by forki** [comment]
after installing the new Win 10 SDK I get millions (really) errors like 

![image](https://cloud.githubusercontent.com/assets/57396/8978556/7cab8816-36a3-11e5-9633-3a58ccbe557b.png)

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/8979209/438fc588-36a8-11e5-8ab5-72cb7037ab66.png)

comes at the end

**Comment by forki** [comment]
so it can't find the fsharp.core 4.4.0.9055

**Comment by adamchester** [comment]
@forki you might have a command prompt / environment with the wrong variables/tools? That might be why it was looking for Win 8.1 SDK? I get different errors on a fresh windows 10 machine.

**Comment by forki** [comment]
no the issue with the Win 8.1 SDK is OK. I found that place in the fsproj and can work around it. But the WIN 10 SDK seems to have broken my build entirely.

**Comment by adamchester** [comment]
I now have lots of errors about it being unable to set registry keys, ending with similar errors to you. I am trying build from 2015 developer cmd prompt (run as administrator now).

**Comment by adamchester** [comment]
```
Microsoft (R) CLR Native Image Generator - Version 4.6.79.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
Administrator permissions are needed to use the selected options.  Use an administrator command prompt to complete these tasks.
```

**Comment by forki** [comment]
I'm trying from administrator powershell. That always worked on my other machines.

**Comment by adamchester** [comment]
I'm going to guess your powershell environment is missing one (or more) variables defined by the `Developer Command Prompt for VS2015`, because I had similar errors to you, and now they're gone.

**Comment by forki** [comment]
IMHO this should all be figured out during the build. FAKE does this and the appveyor-build here worked too.

**Comment by adamchester** [comment]
I agree it should.

To summarise for other people attempting (if they have similar issues to us):
 1. Install .NET Framework 2.5/3.5 via windows (e.g. run FsSrGen.exe and follow the prompts).
 2. Make sure VSSDK and Windows 10 SDK are installed (per guides).
 3. run `appveyor-build.cmd` from an Administrator `Developer Command Prompt for VS2015`.

**Comment by forki** [comment]
Ok will try from command prompt

**Comment by forki** [comment]
same issue from vs command promt

**Comment by latkin** [comment]
Thanks for scouting this, would be great to figure out what the blocker is.  FWIW I can build ok on my Win10 machine, but it's an 8.1 upgrade.

**Comment by forki** [comment]
it builds inside VS2015, but appveyor-build is still broken for me.

**Comment by forki** [comment]
I think the first strang thing is:

![image](https://cloud.githubusercontent.com/assets/57396/9001946/4e5e8c36-375e-11e5-986e-28c55896939f.png)

**Comment by isaacabraham** [comment]
Getting this here on a clean Win 10 machine. I have an 8.1-upgraded machine at home so will try on that and see if it still occurs there.
