### ISSUE TITLE
module global crashes VS 2017 15.8.1

### ISSUE THREAD

**Issue by mauriciomagni** [Microsoft/visualfsharp#5615]
In case you write down "module global" it crashes VS 2017 15.8.1

#### Repro steps

- Create a new .Net Core Console App
- Add a new item: File1.fs
- Replace in "File1" by "global"
- Hit Enter
- Wait a couple of seconds... Visual Studio should crash

#### Expected behavior

I now "module global" is not valid, my goal was to define "namespace global", because I forgot changing module by namespace it crashed VS.
Expected behavior: to signal the error, something like "module cannot be global"

#### Actual behavior

VS crashes

#### Known workarounds

Be sure to replace "module" by "namespace" before naming it "global"

#### Related information 

Operating system: Windows 10 Pro (10.0.17134)
Host (useful for support):
Version: 2.1.2
Commit: 811c3ce6c0
.NET Core SDKs installed:
2.1.4 [C:\Program Files\dotnet\sdk]
2.1.104 [C:\Program Files\dotnet\sdk]
2.1.200 [C:\Program Files\dotnet\sdk]
2.1.201 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
2.1.400 [C:\Program Files\dotnet\sdk]

Severity: Low

**Comment by cartermp** [comment]
This also reproduces with a non-SDK project.

**Comment by cartermp** [comment]
No `ActivityLog.xml` file dropped on my machine either.

**Comment by TIHan** [comment]
Has been fixed. Will be in dev15.9.
