### ISSUE TITLE
Suggestion: Use absolute urls when referencing issues on this repo

### ISSUE THREAD

**Issue by dungpa** [Microsoft/visualfsharp#564]
When a new commit is pushed to this repo, Lincoln often links to related issues by relative urls like this [#564](https://github.com/Microsoft/visualfsharp/issues/564).

However, it causes problems to fsharp/fsharp and FCS because when code transfering is done, a lot of issues there get closed automatically. It's wrong and difficult to track which issues have been closed mistakenly. Moreover, the relative urls also create bogus issue references on fsharp/fsharp and FCS, which makes it harder to examine issues in those repos.

An occurrence of this problem happened a few days ago when F# 4.0 code flows to FCS.

I suppose if we use absolute urls like this [ https://github.com/Microsoft/visualfsharp/issues/564](https://github.com/Microsoft/visualfsharp/issues/564) when referencing issues in pushed commits, above-mentioned issues no longer apply. 

Please help to give clean history to fsharp/fsharp and FCS. Thanks.

**Comment by latkin** [comment]
Good feedback, makes sense. We'll make sure to do that in the future!

**Comment by latkin** [comment]
I've started doing this with recently-merged cleanup PRs.  Note that GH still renders it as a short link:

![image](https://cloud.githubusercontent.com/assets/5943573/9069793/4afddbd8-3aa0-11e5-967d-7672cb6ad8ab.png)

But in the raw commit it's the full URL

![image](https://cloud.githubusercontent.com/assets/5943573/9069804/64f49888-3aa0-11e5-97b3-24c9e0480b9a.png)

**Comment by dungpa** [comment]
Confirm that it works fine (see https://github.com/fsharp/FSharp.Compiler.Service/commit/ae910eec18f00727834d8fa1c1254c5aaff06cb7). 

Thanks.
