### ISSUE TITLE
Adding Visual F# to VS 2015 RTM kills javascript langauge service (100% reproducable)

### ISSUE THREAD

**Issue by ReverseBlade** [Microsoft/visualfsharp#565]
I tried with fresh Windows 10 installation x64 two times.
1- Install Visual Studio 2015 RTM  (typical)
2- Install Windows 10 SDK
3- Install Visual F#
4 - Create a new Universal JavaScript Application
5 - Try to start it with debugging mode.

It won't start. Also you will notice no syntax highlighting in default.js

When we add Visual F# to Visual Studio, it some how  effects javascript language service. For instance adding a new javascript file, syntax highlighting will not work. Also create a new JavaScript Universal application, it will not start. It will say "unable to start debugging"

It is a blocker. Adding Visual F# simply kills entire javascript service

**Comment by ReverseBlade** [comment]
More thoroughly investigation I realized this is not an F# bug. If you add anything to visual studio, it causes this bug. Since Microsoft Connect doesn't work I don't have any place to report this bug unfortunately.

**Comment by latkin** [comment]
We'll forward this along to the appropriate internal team. Thanks for taking the time to investigate and log the bug!

**Comment by latkin** [comment]
I'm told this is the same as the issue tracked [here](https://social.msdn.microsoft.com/Forums/en-US/0e5115ca-83a7-4294-8740-289b3f453fca/rtm-known-issue-package-load-failure-when-creating-a-windows-app-project-with-javascript-or-hang?forum=Win10SDKToolsIssues). The JS team is working on getting out a fix as soon as they can, but in the meantime there is a workaround listed.

**Comment by ReverseBlade** [comment]
Thank you very much!

**Comment by ReverseBlade** [comment]
Unfortunately this doesn't fully fix the problem. After applying above fix javascript syntax highlighting starts working. However create a universal JS application  and try to start. It won't start debugging. Also right click to project properties, you get an error: There is no project properties provider for Persistence =  JavaScriptProjectPropertiesProvider.
