### ISSUE TITLE
Automatic cast is broken inside array expression

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5656]
```fsharp

type Base() = class end
type A() = inherit Base()
type B() = inherit Base()

let x : Base[] =
    [| 
       A()
       B() 
    |]

let y =
    [| 
       A() :> Base
       B() :> _ 
    |]

let y : Base[] =
    [| 
       A() :> Base
       B() :> _ 
    |]
```

![image](https://user-images.githubusercontent.com/873919/45620917-1c1fd680-ba87-11e8-9f4c-647eff105d1d.png)

JetBrains Rider 2018.2 EAP
Build #RD-182.4231.491, built on September 12, 2018
Rider EAP User
Expiration date: October 12, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by cartermp** [comment]
Same behavior for F# 4.0: https://repl.it/@cartermp/GlisteningBoilingQuagga

@dsyme is this by design? Error message would indicate as much.

**Comment by dsyme** [comment]
Yes this is by design if you follow through the spec of F# type inference.  If the known type is `Base[]` then a special rule is applied. You don't need the upcasts at all in this case.  But the above is the price we pay for that
