### ISSUE TITLE
The Visual F# team is growing

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#567]
Please welcome David Stephens (@NumberByColors / [@NumberByColors](https://twitter.com/NumberByColors))), who started today as a dedicated PM for Visual F#.  We are thrilled to have him join us, and very happy to see the team here in Redmond growing.

>Hey everyone! I’m David. I’m super excited to work with you all on F#. It’s been one of my favorite programming languages ever since I was introduced to it (and functional programming) in college. Looking forward to meeting more of you, soon!

You'll start seeing David pop up around here soon.

![daisykittywelcometothegroup-vi](https://cloud.githubusercontent.com/assets/5943573/9049529/ca56ca56-39f7-11e5-8036-f2cea86ae93d.gif)

**Comment by NumberByColors** [comment]
Thanks, @latkin!

**Comment by forki** [comment]
Wow. Very cool.

**Comment by jackfoxy** [comment]
Great!

**Comment by dsyme** [comment]
Welcome @NumberByColors!

**Comment by Overlord-Zurg** [comment]
Woooo! Welcome, @NumberByColors (even if I am jealous to learn that they're now teaching F# in college).

**Comment by manofstick** [comment]
Welcome @NumberByColors!

**Comment by CumpsD** [comment]
Welcome @NumberByColors :)

**Comment by enricosada** [comment]
Welcome @NumberByColors !

![2015-08-19 17 42 07](https://cloud.githubusercontent.com/assets/147243/9361185/93b065de-469a-11e5-8798-414a418a9b96.gif)
