### ISSUE TITLE
Match expression is evaluated twice if it returns a struct union

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#5689]
Potentially critical issue: If the expression (e.g. a function call) inside a `match ... with` returns a struct union (e.g. `ValueOption<_>`, `Result<_,_>` or a custom struct union), the expression is evaluated twice, including any side effects.

#### Repro steps

Repro solution: <s>Test.zip</s> [ConsoleApp1.zip](https://github.com/Microsoft/visualfsharp/files/2407805/ConsoleApp1.zip)

The repro solution consists of a console app with the following code, showing various examples and aspects of this bug:

```f#
open System


type CustomValueUnion = V

[<Struct>]
type CustomStructUnion = S

[<Struct>]
type CustomStructRecord =
  { A: CustomStructUnion }


[<EntryPoint>]
let main argv =

  match printfn "Option inlined"; Some () with
  | Some () -> ()
  | None -> ()

  let x = printfn "Option outside"; Some ()
  match x with
  | Some () -> ()
  | None -> ()

  match printfn "ValueOption inlined"; ValueSome () with
  | ValueSome () -> ()
  | ValueNone -> ()

  let x = printfn "ValueOption outside"; ValueSome ()
  match x with
  | ValueSome () -> ()
  | ValueNone -> ()

  match printfn "Result inlined"; Ok () with
  | Ok () -> ()
  | Error () -> ()

  let x = printfn "Result outside"; Ok ()
  match x with
  | Ok () -> ()
  | Error () -> ()

  match printfn "Custom value union inlined"; V with
  | V -> ()

  let x = printfn "Custom value union outside"; V
  match x with
  | V -> ()

  match printfn "Custom struct union inlined"; S with
  | S -> ()

  let x = printfn "Custom struct union outside"; S
  match x with
  | S -> ()

  match printfn "Custom struct union inlined with catch-all"; S with
  | _ -> ()

  match printfn "Custom struct record inlined"; { A = S } with
  | { A = S } -> ()


  printfn "Press Enter to exit..."
  Console.ReadLine() |> ignore
  0
```

#### Expected behavior

The message should only be printed once for each use of `match`.

#### Actual behavior

![image](https://user-images.githubusercontent.com/7766733/45916358-db4c0700-be64-11e8-9b5b-f6fbbbc550fe.png)

#### Known workarounds

Bind the expression to a named value and use that value in the `match` expression, like the example shows.

#### Related information 

* Visual Studio version: 15.8.5
* Visual F# tools 10.2 for F# 4.5, 15.8.0.0, commit hash 92247b88
* Severity: Assumed high

**Comment by zpodlovics** [comment]
Could you also attach the compiled binaries to check the generated code? Unfortunately I cannot reproduce it on .NET Core SDK 2.1.402-1 on Linux (Debug/Release).

Release:
```
Option inlined
Option outside
ValueOption inlined
ValueOption outside
Result inlined
Result outside
Custom value union inlined
Custom value union outside
Custom struct union inlined
Custom struct union outside
Custom struct union inlined with catch-all
Custom struct record inlined

```

Debug:

```
Option inlined
Option outside
ValueOption inlined
ValueOption outside
Result inlined
Result outside
Custom value union inlined
Custom value union outside
Custom struct union inlined
Custom struct union outside
Custom struct union inlined with catch-all
Custom struct record inlined

```

**Comment by cmeeren** [comment]
Here are the binaries.

[bin.zip](https://github.com/Microsoft/visualfsharp/files/2407802/bin.zip)

**Comment by cmeeren** [comment]
Here's a fresh repro solution with binaries; I had some troubles with the original one on another device.

[ConsoleApp1.zip](https://github.com/Microsoft/visualfsharp/files/2407805/ConsoleApp1.zip)

**Comment by cmeeren** [comment]
> it would be good to see the AST difference between the two compilation.

Your message was a bit unclear on whether this is something you want me to provide. If so, I have no idea how.

**Comment by zpodlovics** [comment]
In order to dig it deeper it would require to check the compiler internals (AST=Abstract Syntax Tree [1]). There is an ```--ast``` hidden option available [2] for fsc/fsharpc, but the output seems missing when enabled with ```<OptArgs>--ast</OptArgs>``` in a new style .net project...

[1] https://fsharp.github.io/FSharp.Compiler.Service/untypedtree.html
[2] https://github.com/Microsoft/visualfsharp/blob/fead0aac540485683f694524eadad79983ec28d9/src/fsharp/CompileOptions.fs#L882

**Comment by cmeeren** [comment]
I interpret this to mean that someone other than me has to look into this.

**Comment by TIHan** [comment]
Yes, this would classify as a very high priority.

I can't reproduce this in 15.8.5, but I can reproduce it in master. That means a recent change happened in master for this to occur.

**Comment by TIHan** [comment]
This PR caused the regression: https://github.com/Microsoft/visualfsharp/pull/5148

We will look into it.

**Comment by TIHan** [comment]
This has been resolved.
