### ISSUE TITLE
Unfixable FS0076 error from fsharpi when putting #r directive in .fs file

### ISSUE THREAD

**Issue by kg** [Microsoft/visualfsharp#569]
It appears to be impossible to actually put a `#r` directive in a .fs file, at least as far as `fsharpi` on linux is concerned. Test case:

``` fsharp
#if INTERACTIVE
#r "FParsec.dll"
#endif

module Test

let test =
  5
```

If I load this file with fsharpi It generates a FS0076:
`~/Desktop/test.fs(2,1): error FS0076: #r directives may only occur in F# script files (extensions .fsx or .fsscript). Either move this code to a script file, add a '-r' compiler option for this reference or delimit the directive with '#if INTERACTIVE'/'#endif'.`

Except as you can see, I followed those directions and it didn't fix it. I can't find any information about this on the web so this appears to be some sort of a bug in fsharpi. I've tried every permutation of this that I can think of and it just doesn't work. If you remove the `#r` directive, fsharpi happily loads and compiles the file.

The FS0076 guidance should be modified to remove the `#if INTERACTIVE` workaround if it's not intended to work. (I assume it's intended to work, though?)

Configuration details:
`fsharpi --help` prints `F# Interactive for F# 3.0 (Open Source Edition)`.
Installed mono and fsharp from the mono-project package sources using the official directions (`sudo apt-get install mono-complete fsharp`).

**Comment by dsyme** [comment]
The `#if INTERACTIVE` option is intended to allow you to put the #r in a block which is suitable for sending to F# interactive as user input, e.g. using Ctrl-Enter.  For example see this: https://github.com/fsharp/FSharp.Compiler.Service/blob/master/tests/service/ProjectAnalysisTests.fs#L1

However it doesn't mean the reference will be allowed when using the .fs file on the command line to F# interactive.  That's just not possible unless you use a .fsx.

So it works in some sense, it just doesn't achieve quite what you want.

**Comment by dsyme** [comment]
The error message could be improved - please submit a PR with a proposed improvement by editing https://github.com/Microsoft/visualfsharp/blob/275b832e9dd1a4bd64ed3accd218384b901be1d2/src/fsharp/FSStrings.resx#L1045

**Comment by kg** [comment]
OK, so this is intended to work in the scenario where you ctrl+a a ```.fs``` file and then send it to F# interactive, but not the scenario where you pass the ```.fs``` file as a command line argument to ```fsharpi```?

I'm not sure there's a reasonable way to express this logic in an error message. Would something like:
```#r directives may only occur in F# script files (extensions .fsx or .fsscript). Either move this code to a script file or replace this reference with the '-r' compiler option. If this directive is being executed as user input, you may delimit it with '#if INTERACTIVE'/'#endif'.``` work? If so, I'll try to revise the directive error messages in that resx file and submit a PR.

**Comment by dsyme** [comment]
That seems fine!

**Comment by dsyme** [comment]
@isaacabraham Please add this to your catalog of error message improvements? thanks

**Comment by forki** [comment]
PR at https://github.com/Microsoft/visualfsharp/pull/2635

**Comment by isaacabraham** [comment]
@forki Can this be closed?

**Comment by forki** [comment]
yep
