### ISSUE TITLE
Should F# lists implement ICollection?

### ISSUE THREAD

**Issue by eiriktsarpalis** [Microsoft/visualfsharp#570]
I just noticed that F# lists do not implement the `ICollection` interface. This means that it is currently impossible to quickly extract the length of a list of unknown type unless using some form of reflection and/or appealing to its IEnumerable implementation, which is far from an ideal solution. On closer inspection the same seems to be true with FSharpMap and FSharpSet. 

I was wondering if it would make sense to incorporate `ICollection` implementations for F# collections in future versions of F# core. I could provide a PR if this is agreeable to you.

**Comment by forki** [comment]
related #436

**Comment by dsyme** [comment]
Please add to fslang.uservoice.com with some code examples for what you're trying to do.  (I'm not a total fan of ICollection and wouldn't particularly encourage its use in user APIs but lets see how the discussion goes)

**Comment by isaacabraham** [comment]
Am I right in thinking that this is related to things like optimisations in LINQ? If you look at the source code in the standard LINQ library, many methods type check against ICollection (e.g. List etc.) where they can get the Count of a collection etc. which obviously from an IEnumerable perspective is a potentially expensive operation.

**Comment by eiriktsarpalis** [comment]
@dsyme I'm writing a piece of code that extracts all collections from a given object graph using FsPickler.  I currently use [this implementation](https://github.com/mbraceproject/MBrace.Core/blob/880e76f5b21b0d693961e5261dd176e770ced1da/src/MBrace.Runtime.Core/Utils/Reflection.fs#L77) to extract the count of F# collections. Given that these already implement IEnumerable I think it would make sense to also include ICollection, which is essentially an IEnumerable with length known a priori. 

I think Isaac makes a good point here, extracting the length from IEnumerable can be expensive, particularly when evaluating lists of value types. Many libraries like LINQ and Streams also benefit by checking against ICollection.

I should also point out that `ICollection` is different to `ICollection<T>`: they do not have a subtype relationship; `ICollection<T>` supports updates whereas `ICollection` does not. In that sense `ICollection` is perfectly compatible with immutable data structures whereas `ICollection<T>` is not. At the same time FSharpMap/FSharpSet implement `ICollection<T>` but not `ICollection` which certainly seems strange.

**Comment by eiriktsarpalis** [comment]
@dsyme done http://fslang.uservoice.com/forums/245727-f-language/suggestions/9183845-add-system-collections-icollection-implementations
