### ISSUE TITLE
Enable F# optional parameter usage from C#

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/visualfsharp#5701]
Optional parameters in F# are not usable in C# due to differences in how the languages emit them into IL. 

- F#: 
    - Parameters are tagged with the `OptionalArgumentAttribute` 
    - Default value is handled inside the callee method body. Callers always pass `null` for optional parameters.
- C#:
    - Parameters have the CLI `Optional` flag set 
    - Default value is specified on the parameter using the CLI metadata. The caller copies this value into their metadata and passes it explicitly when invoking the function.

Given the different ways in which they're emitted it means neither language can take advantage of each others optional parameter feature. Instead we're forced to do work arounds like the following when mixing F# and C#:

``` fsharp
type FSharpUtil() =

    // F# method I want to define and use everywhere
    member this.Method(?i: int) = 
        let i = defaultArg i 42
        Console.WriteLine(i)

    // Overload callable from C# / VB
    member this.Method() =
        this.Method(42)
```

I believe the C# calling F# optional parameters can be fixed quite easily though by making a small change to how they are emitted. In addition to what F# does today it could also:

1. Mark the parameter with the `Optional` CLI flag
1. Mark the parameter as having the default value of constant `null`

This will cause C# to act like F# whenever it encounters an optional parameter. Lacking a specific value C# will provide `null` for each optional parameter. Specific values still need to be passed using an `FSharpOption<T>` instead of `T` but that is already the case today. 

Here is an example of how `FSharpUtil.Method` would be emitted with the proposed changes:

``` il
.method public hidebysig 
	instance void Method (
		class [FSharp.Core]Microsoft.FSharp.Core.FSharpOption`1<int32> [opt] i
	) cil managed 
{
	.param [1] = null
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.OptionalArgumentAttribute::.ctor() = (
		01 00 00 00
	)
	// Method begins at RVA 0x205c
	// Code size 16 (0x10)
	.maxstack 4
	.locals init (
		[0] int32
	)

	IL_0000: ldarg.1
	IL_0001: ldc.i4.s 42
	IL_0003: call !!0 [FSharp.Core]Microsoft.FSharp.Core.Operators::DefaultArg<int32>(class [FSharp.Core]Microsoft.FSharp.Core.FSharpOption`1<!!0>, !!0)
	IL_0008: stloc.0
	IL_0009: ldloc.0
	IL_000a: call void [mscorlib]System.Console::WriteLine(int32)
	IL_000f: ret
} // end of method FSharpUtil::Method
```

The differences from the current IL is the use of `[opt]` on the definition of `i` and the `= null` addition to the `.param [1]` declaration.

Here are the relevant entries in the CLI for the parameter fields that C# use for optional metadata encoding.

```
II.22.33 Param : 0x08
The Param table has the following columns:
•Flags (a 2-byte bitmask of type ParamAttributes, §II.23.1.13)
•Sequence (a 2-byte constant)
•Name (an index into the String heap)

I I.23.1.13 Flags for params [ParamAt t ributes]
Flag Value Description
- In 0x0001 Param is [In]
- Out 0x0002 Param is [out]
- Optional 0x0010 Param is optional
- HasDefault 0x1000 Param has default value
- HasFieldMarshal 0x2000 Param has FieldMarshal
- Unused 0xcfe0 Reserved: shall be zero in a conforming implementation
```

**Comment by gsomix** [comment]
@jaredpar For interop purposes you can use explicit attributes in F# code. It acts like C# optional parameters both in F# and C# code.

https://github.com/fsharp/fslang-design/blob/master/FSharp-4.1/FS-1027-complete-optional-defaultparametervalue.md

**Comment by cartermp** [comment]
I think any way to have F# optional parameters (not with `Optional; DefaultParameterValue`) would be a dedicated suggestion here: https://github.com/fsharp/fslang-suggestions

Given that we do have a way to do this today, I think it's unlikely to happen though
