### ISSUE TITLE
need an explicit inline tail-recursion function keyword

### ISSUE THREAD

**Issue by greatim** [Microsoft/visualfsharp#5702]
for Span<'T>, it can't use in a closure,  but for-loop.
```
let test(ptr: Span<uint32>) =
    for x in ptr do 
        foo x
```
But,we can't break the loop ，so it must be usable in a tail-recursion function.
```
let test(ptr: Span<uint32>) =
      let rec loop idx =
          if idx <> ptr.Length then
              ptr.[idx] |> foo
              idx +1 |> loop
      loop 0
```

I suggestions use a tail-recursion function keyword(ie. tail, rec&, inline rec, etc.)，it sure convert to a for-loop inline, and only use in current scope.

```
let test(ptr: Span<uint32>) =
      let rec& loop idx =
          if idx <> ptr.Length then
              ptr.[idx] |> foo
              idx + 1 |> loop 
      loop 0
```

 

Others， it improve a lot performance。

**Comment by TIHan** [comment]
We can't allow it to ever be captured by a closure even if it would compile down correctly in some circumstances.

Another way to handle this is to make a non-local recursive function:
```fsharp
let foo x = ()

let rec testRec (ptr: Span<uint32>) (idx: int) =
    if idx <> ptr.Length then
        ptr.[idx] |> foo
        testRec ptr (idx + 1)

let test(ptr: Span<uint32>) =
      testRec ptr 0
```

You can't make a local function (yet) take a byref or span.

**Comment by TIHan** [comment]
Closing this as by-design.
