### ISSUE TITLE
Feature request: as-declaration in match-expression with multiple patterns per expression-body

### ISSUE THREAD

**Issue by tordenhunden** [Microsoft/visualfsharp#5709]
The following should compile and evaluate to "Some 1"

```
Microsoft (R) F# Interactive version 10.2.3 for F# 4.5
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> match Some 1 with | None as x | (Some _) as x -> x;;

  match Some 1 with | None as x | (Some _) as x -> x;;
  ----------------------------^

stdin(1,29): error FS0038: 'x' is bound twice in this pattern

> 
```

**Comment by tordenhunden** [comment]
One could argue that it is not a bug, and instead a feature not implemented. But it should be doable, since it can be transformed 

from

```
match Some 1 with 
| None as x
| (Some _) as x -> 
  x;;
```

to

```
match Some 1 with 
| None as x ->
  x
| (Some _) as x -> 
  x;;
```

Since the static type of x is the same in both cases.
I am convinced this works in the general case.

**Comment by tordenhunden** [comment]
Lets call it a feature request instead :-)

I wrongly assumed that it was possible in OCaml.

**Comment by cartermp** [comment]
@tordenhunden Can you file a suggestion here? https://github.com/fsharp/fslang-suggestions

Thanks!
