### ISSUE TITLE
navigation bar in signature file empty

### ISSUE THREAD

**Issue by jackfoxy** [Microsoft/visualfsharp#572]
nothing in navigation bar of signature files
 I'm on Win10, VS2015, but I'm pretty sure this is also a problem under 8.1, VS2013

**Comment by latkin** [comment]
Nav bar issues are kind of weird - we don't officially support the feature, yet it's in our codebase... We'd certainly be happy to see a PR for this.

**Comment by dsyme** [comment]
@vasily-kirichenko @saul Is this fixed in VS2017? thanks

**Comment by vasily-kirichenko** [comment]
Yes it's fixed in the new nav bar.

**Comment by cartermp** [comment]
Yup, fixed.
