### ISSUE TITLE
ComparisonIdentity.Structural.Compare for float/float32 says is NaN equal (i.e. 0) to everything!

### ISSUE THREAD

**Issue by manofstick** [Microsoft/visualfsharp#573]
Whilst creating regression tests for #513 I came across this case:

    let r = System.Random ()

    if not <| HashIdentity.Structural.Equals(r.NextDouble(),System.Double.NaN) then
        printfn "All numbers are not equal to NaN according to HashIdentity.Structural"
    
    if ComparisonIdentity.Structural.Compare(r.NextDouble(),System.Double.NaN) = 0 then
        printfn "But all numbers are equal to NaN according to ComparisonIdentity.Structural"

    printfn ""
    printfn "System.Collections.Generic.EqualityComparer.Default.Equals(x,NaN)=%b" (System.Collections.Generic.EqualityComparer.Default.Equals (r.NextDouble(),System.Double.NaN))
    printfn "HashIdentity.Structural.Equals(x,NaN)=%b" (HashIdentity.Structural.Equals (r.NextDouble(),System.Double.NaN))

    printfn ""
    printfn "System.Collections.Generic.Comparer.Default.Compare(x,NaN)=%d" (System.Collections.Generic.Comparer.Default.Compare (r.NextDouble(),System.Double.NaN))
    printfn "ComparisonIdentity.Structural.Compare(x,NaN)=%d" (ComparisonIdentity.Structural.Compare (r.NextDouble(),System.Double.NaN))

Has the following output

    All numbers are not equal to NaN according to HashIdentity.Structural
    But all numbers are equal to NaN according to ComparisonIdentity.Structural
    
    System.Collections.Generic.EqualityComparer.Default.Equals(x,NaN)=false
    HashIdentity.Structural.Equals(x,NaN)=false
    
    System.Collections.Generic.Comparer.Default.Compare(x,NaN)=1
    ComparisonIdentity.Structural.Compare(x,NaN)=0

**Comment by manofstick** [comment]
Manifestation of this issue (not that floats make good keys anyway, so kind of invalid, but still):

    let set1 = Set.ofArray [| 0.0; System.Double.NaN |]
    let set2 = Set.ofArray [| 0.0 |] 
    if set1.Equals set2 then printfn "set1.Equals set2 is true"

outputs: 

    set1.Equals set2 is true

(argh, I think I need a better baseline for my regression suite! I might branch off the OOB and fix these before I start delving any further...)

**Comment by manofstick** [comment]
Hmmm... Trying to debug this issue I rolled back to the latest checkin before my changes and used that. *When I used that FSharp.Core this problem didn't exist*. But creating a new project, and using the standard FSharp.Core it was an issue.

I am still using the Visual Studio 2015 RC; so maybe that's the issue?? I'll uninstall and put the proper one one soon...

**Comment by manofstick** [comment]
Argh, just seems to have been an issue with the RC... Anyway, all good.

**Comment by latkin** [comment]
Fixed by this https://github.com/Microsoft/visualfsharp/pull/373.  Yes make sure baseline for regression tests is tip of fsharp4 branch.
