### ISSUE TITLE
Unresolved symbols off by default in completion lists?

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#5735]
We've received a lot of feedback from people that including symbols from unopened namespaces in completion lists makes it feel noisy. I've been experimenting with turning it off by default to see how it felt, and I think I prefer it off by default as well. Still, it's valuable, and the instant something is off by default, the majority of people will not know about it.

Do people have any thoughts on this? Yay/nay?

edit: just came across the timeline today: https://twitter.com/isaac_abraham/status/1049552508350279680

**Comment by inosik** [comment]
We updated to VS 2017 just last week and I prefer this to be disabled, too. I also disabled it in Ionide as soon as the option to do that was added there.

I heavily rely on autocompletion even for symbols with short names and I feel like I'm constantly `open`ing namespaces I didn't intend to.

**Comment by saul** [comment]
Is this not default on for C#? A better metric for deciding as to whether it should be on by default or not is how many people turn this off. If a sizable amount turn it off, then change the default.

**Comment by cartermp** [comment]
@saul There is a ReSharper feature that will add it, but there is no default experience for this for the majority of C# developers.

Telemetry-wise, we actually don't have any information tracked about individual selections (nor about top-level menu items like "IntelliSense"). This exists for C#, VB, and global options that are implemented in Roslyn, but the relevant ones here are not tracked there. I don't think we track anything that we could use as a proxy, either. This sort of information could be added, but it's not likely to be trivial to do so, and would have to ship in a major update to VS. The next one where we could do this would be 16.0 Preview 1 or Preview 2, which also means the population of people we could measure would not be representative of most F# developers.

So I think this is going to have to be a "let's see what people think" decision. It's been on for a while, but it does populate the list with a _ton_ of symbols because the default set of references for a project includes a lot of symbols. I've seen feedback here, on Twitter, and Reddit indicating that it's too chatting and can result in including a symbol you didn't intend to type. But as mentioned, it's not without value as a feature.

**Comment by cartermp** [comment]
The PR to change the default to off has been merged as is in the nightly feed. It would be great to hear from folks if they think this as changed things, positivity or negatively. It's very easy to change back, and we have a lot of time to collect feedback leading up to VS 2019 RTW.
