### ISSUE TITLE
Weird bug causing crash with some usages of some struct types in Release on certain devices

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#5765]
I experience a very weird bug causing crashes in the Android version of a Xamarin.Forms app I am developing/maintaining. I cannot share the whole app code (at least not publicly), and I have so far not been able to produce a minimal repro, so I am writing this just to let you know that there is something weird going on with `Result<_,_>` and other struct unions in FSharp.Core >= 4.5.0 (as previously reported, see #5655), and in the hopes that perhaps someone might be able to get something out of this regardless.

#### Update: Repro solution

See https://github.com/Microsoft/visualfsharp/issues/5765#issuecomment-430137670

#### Repro constraints

In short, there's a bug that only occurs for certain operations in the app and only if all of the following is true:

* Release mode (works fine in debug; I have tried to make the configs as similar as possible to no avail)
* Only certain devices (it works fine on Motorola Moto G5S and all images I've tried in the Genymotion emulator, but App Center has reported crashes on Samsung Galaxy S7, S7 Edge, S8, S8+, Note8, A8, Sony Xperia XZ2, L1, Huawei Honor 10, P10, and I have personally reproduced this on two Samsung Galaxy devices)
* FSharp.Core >= 4.5.0 (<= 4.3.4 works fine)
* Using the built-in `Result` type

#### Workarounds that each will fix the problem on their own

* Downgrading to FSharp.Core <= 4.3.4
* Replacing all usages of `Result<_,_>` with `Choice<_,_>`
* Replacing all usages of the built-in `Result<_,_>` with a custom non-struct `Result<_,_>` type (this is what I ended up deploying as a fix)
* Commenting out the following two lines in a certain function - while they don't make much sense to anyone else, note that:
    * This is a pure function
    * `resp` and `err` are instances of simple F# types composed of records, unions, and primitives
    * Commenting out these lines fixes a single instance of the bug/crash (when signing in), but others might be present
    * When these lines aren't commented out, the app crashes even though the output of the function is only passed to `ignore`, indicating that something might be wrong with F#'s pattern matching

```f#
let getLogMsg : Action -> Msg = function
  ...
  | GetSignInMethodsCompleted (Ok resp) -> Some <| GetSignInMethodsSuccessful resp
  | GetSignInMethodsCompleted (Error err) -> Some <| GetSignInMethodsFailed err
  ...
```

#### Other weird stuff

* If I add the `[<Struct>]` attribute to the custom `Result<_,_>` type I used as a workaround, I experience other weird behavior: The app does not crash, but this simple change causes the behavior of the app to change. In particular, the `GetSignInMethodsCompleted` action (and by extension its `Result<_,_>` data) that is returned from the API call (whether real or mocked) does not seem to cause any visible change in the app; again, only in Release mode, so it's devilishly hard to debug. This weird behavior seems to have the same restrictions (devices, fixes, etc.) as the previously explained crash-causing bug.

* Possibly related: If I comment out the two lines mentioned above, allowing me to sign in to the app, a lot of the other HTTP API-based (real or mocked) UI changes in the app seem to intermittently "lag one step behind". For example, when clicking a green button that performs an API call and turns red when it receives a result, it doesn't turn red until I click it once more and another API call is performed. Again, the constraints for this bug are the same as for the previously explained bug (same devices, fixes, etc.).

#### General notes

This further indicates that there is something weird with `Result<_,_>` or struct unions in general that changed from 4.3.4 to 4.5.0, as reported in #5655. As I explain in that issue, I'm not saying the fault definitely lies with F#, but surely there would be no issue here if absolutely nothing changed with `Result<_,_>` or struct unions.

If anyone wants to take a look at the problematic APK, the Google Play ID is `com.infotech.checkboxapp` and the affected version is `2.5.0`.

Let me know if I can provide further helpful information.

#### Environment

* VS 15.8.6 and 15.8.7
* F# tools that came with VS, as well as nightlies

**Comment by dsyme** [comment]
@cmeeren Well that almost certainly feels like a bug in the Xamarin/Mono compilation stack, though it is possible it is a bug in F# code generation relating to structs and pointers.

I think we would need a definite repro of this which we can compare on diffrerent compilation stacks, i.e. a repro of a small code fragment that runs differently on-device v. Mono-linux v. Mono-arm v. Windows v. NETCore.

**Comment by cmeeren** [comment]
I understand. I'll see what I can cook up, but no promises on time frame since I have to borrow a colleage's personal phone to repro and each iteration requires release mode compilation, which takes a while.

**Comment by dsyme** [comment]
> I understand. I'll see what I can cook up, but no promises on time frame since I have to borrow a colleage's personal phone to repro and each iteration requires release mode compilation, which takes a while.

I can imagine that's very painful.  This is the first recent live codegen bug/issue I know of in the Xamarin --> device compilation stack for F#, it would be great to get to the bottom of it.

**Comment by cmeeren** [comment]
I managed to set aside a day and a half to reduce this as much as I could. Repro solution:

[BugTest.zip](https://github.com/Microsoft/visualfsharp/files/2481919/BugTest.zip)

In short, aside from the Android head project, this is the only code:


```f#
type App() =
  inherit Application()

  // Won't repro with Choice<_,_> or ValueOption, but will repro with a custom
  // struct union isomorphic to Result
  let handleResult = function
    // Changing the order of these cases won't repro unless the payloads are
    // also switched
    | Ok xs -> for _ in xs do ()  // unit here won't repro
    | Error _ -> ()  // catch-all here (_) won't repro

  do
    Application.Current.MainPage <- Page()
    async {
      // Simplifying this nested async expression won't repro
      let! x = async { return Error () }  // Can also return Ok []
      handleResult x  // Moving this out of async won't repro
    }
    |> Async.Start
    // Can also repro with StartImmediate, RunSynchronously, and StartAsTask
```

The changes indicated by the comments are verified using a Samsung Galaxy S7 Edge (SM-G935F). I expect the bug to be reproducible on the devices listed in the original post.

**Comment by dsyme** [comment]
Just to mention: 

> The Samsung Galaxy S7 Edge phone ... the main processor is a Snapdragon 820 or Exynos 8890 ... The snapdragon 820 is an ARMv8 processor, thus 64-bit.

**Comment by dsyme** [comment]
I can repro this on my Google Pixel

**Comment by dsyme** [comment]
@cmeeren See https://github.com/mono/mono/issues/11263.  It looks like this can be resolved - the bug has been fixed in Mono Xamarin already and there should also be a workaround where 

    <AndroidSupportedAbis>armeabi,armeabi-v7a,x86</AndroidSupportedAbis>

is used in Release mode as well

**Comment by cmeeren** [comment]
Great, thanks for seeing this through! 🙌
