### ISSUE TITLE
Implementing interface method returning byref<'t> cannot just throw

### ISSUE THREAD

**Issue by marklam** [Microsoft/visualfsharp#5776]
For an interface method with a `byref<'t>` return, it's not possible to provide an implementation that just throws an exception

#### Repro steps

```fsharp
open System

type Ii<'T> =
    abstract GetSpan : int -> ReadOnlySpan<'T>

[<Struct>]
type X(value : int) =
    interface Ii<int> with
        member __.GetSpan n = ReadOnlySpan()

[<Struct>]
type Y(value : int) =
    interface Ii<int> with
        member __.GetSpan n = failwith "Nope"
```
#### Expected behavior

Compiles

#### Actual behavior

The line
```fsharp
member __.GetSpan n = failwith "Nope"
```
reports the error 
`FS0412	A type instantiation involves a byref type. This is not permitted by the rules of Common IL.`

#### Known workarounds

Include an unreachable dummy return value
```fsharp
        member __.GetSpan n = failwith "Nope";  ReadOnlySpan()
```

#### Related information 

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 39fd7b8216d9242213577070d7892c148bb9994e.

**Comment by cartermp** [comment]
Thanks, that definitely looks like a bug.

**Comment by dsyme** [comment]
It's by design.  `failwith` is a generic function instantiated with the return type.    The same would apply to `Unchecked.defaultof<_>`.  Byrefs are just whacky wierd on .NET

You can record a language suggestion if you like

**Comment by cartermp** [comment]
We'll have to strongly consider doing work here. Since both `raise` and `failwith` are generic functions, you cannot throw an exception like you can in C#:

```csharp
    interface Ii<T>
    {
        int GetSpan(ReadOnlySpan<T> sp);
    }

    struct Y : Ii<int>
    {
        public int GetSpan(ReadOnlySpan<int> sp)
        {
            throw new Exception("Nope");
        }
    }
```

**Comment by dsyme** [comment]
Yes, it would make sense to do something here, though it is a bit of a corner case.  It's shame .NET generics have this limitation on byref instanatiations.

**Comment by marklam** [comment]
Could the 'something' also encompass the pipe operator? (like https://github.com/Microsoft/visualfsharp/issues/5286)

**Comment by dsyme** [comment]
> Could the 'something' also encompass the pipe operator? (like #5286)

No.  I'm very loathe to go down that long slippery slope since it's a bug farm.  

Anything we do here would be for `raise` and nothing else.  Not even for `failwith`.

**Comment by marklam** [comment]
> No. I'm very loathe to go down that long slippery slope since it's a bug farm.

Fair enough :-)

**Comment by cartermp** [comment]
@dsyme Do you still think a language suggestion is necessary, or should we just use this to track and update the RFC?

**Comment by dsyme** [comment]
> @dsyme Do you still think a language suggestion is necessary, or should we just use this to track and update the RFC?

We can use this to track I suppose, special casing `raise` is fine

**Comment by cartermp** [comment]
Filed: https://github.com/fsharp/fslang-suggestions/issues/872
