### ISSUE TITLE
FSharp.Core on nuget.org says it supports netstandard2.0, only supports netstandard1.6

### ISSUE THREAD

**Issue by deecewan** [Microsoft/visualfsharp#5782]
I'm trying to get a library to build using `netstandard2.0`. An upstream dependency (`NetBio.Core`) requires at least `netstandard2.0`, and I'm looking to compile on MacOS so `net4xx` isn't an option (as far as I know).

The below image shows the description on nuget - it says that there is support for `netstandard2.0`.

![image](https://user-images.githubusercontent.com/4755785/47086351-92695180-d25c-11e8-91b2-22cc11ca2d84.png)

However, both `nuget` and `paket` only receive `netstandard1.6`

![image](https://user-images.githubusercontent.com/4755785/47086432-cd6b8500-d25c-11e8-90ff-ef6fc57ebacf.png)

I may be missing something here, but I assume that this is why I can't call methods from another library that depends on `netstandard2.0` - I get the following

```
Method not found: Microsoft.FSharp.Core.FSharpFunc`2<string, string> .Texta.get_blue()
```

when trying to call `Texta.blue()`.

#### Related information 

Provide any related information 

* Operating system
	MacOS
* .NET Runtime, CoreCLR or Mono Version
```
mono --version
Mono JIT compiler version 5.14.0.177 (2018-04/f3a2216b65a Fri Aug  3 09:28:16 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/8b1520c8aae)
	GC:            sgen (concurrent by default)
```

**Comment by cartermp** [comment]
The actual binary targets `netstandard1.6`, but there is a `netstandard2.0` group so that you don't incur the large set of downloads on restore. Calling something from a .NET Standard 2.0 component is orthogonal to the actual target of the FSharp.Core binary - it's completely possible to call something from a component targeting .NET Standard 2.0 in F# today. I suspect the issue you're seeing is something else. Do you have a repro you can share?

**Comment by deecewan** [comment]
Hmmm. I have now found that to be the case - I don't think it's anything to do with FSharp.Core.

I've [opened a question on StackOverflow](https://stackoverflow.com/questions/52857726/failing-to-find-package-reference-method) with more context.

**Comment by cartermp** [comment]
@deecewan This may be an issue in how the Texta library is packaged. The [project file](https://github.com/deecewan/Texta/blob/master/src/Texta/Texta.fsproj) does not specify an FSharp.Core version, but the [nuspec does](https://github.com/deecewan/Texta/blob/master/Texta.nuspec). I recommend adding the following to both Texta and Forest libraries:

```xml
<PacakgeReference Update="FSharp.Core" Version="4.3.4"/>
```

This will ensure that your libraries target the lowest compatible FSharp.Core version correctly, overriding the SDK reference that applications use. This step is necessary for library authors.

**Comment by deecewan** [comment]
That was it! Thanks a lot 👍
