### ISSUE TITLE
Too long path in #r directive

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#579]
If a path in #r directive is to long F# interactive says `" '<path>\<assembly name>.dll' is not a valid assembly name"`. It doesn't matter if it is referenced by absolute or relative paths.

For example this long `C:\Users\Андрій\Dev\XperiAndri\D2L\Sources\packages\FSharp.Text.RegexProvider.0.0.7\lib\net40\FSharp.Text.RegexProvider.dll`

But if I move that assembly to a shorter path example `C:\Temp\FSharp.Text.RegexProvider.dll` it works fine.
The path `C:\Users\Андрій\FSharp.Text.RegexProvider.dll` also works so the problem is not in my user name `Андрій`. However Ukrainian (and also Byelorussian) letter i with code U+0456 in my user name can have impact on this issue.

**Comment by latkin** [comment]
At first glance I am guessing this is unrelated to length, and instead a matter of escape sequences.

`"C:\Temp\FSharp.Text.RegexProvider.dll"` contains no escape sequences, so parsed string is the same as in your code. (`\T` and `\F` are not escapes)

`"C:\Users\Андрій\Dev\XperiAndri\D2L\Sources\packages\FSharp.Text.RegexProvider.0.0.7\lib\net40\FSharp.Text.RegexProvider.dll"` does contain escape sequences (namely `\n`), so parsed string contains a newline.

Does it work if you use a verbatim string `@"c:\users\...\blah.dll"`?

**Comment by xperiandri** [comment]
Indeed.
I changed \net40 to \\net40 and it works now
