### ISSUE TITLE
"Optimize code" or fsc flag incorrect when <Optimize> element is missing

### ISSUE THREAD

**Issue by bentayloruk** [Microsoft/visualfsharp#580]
If the `<Optimize>` element is missing from an `fsproj` file project configuration `PropertyGroup`, `fsc` will compile with `--optimize+`, but the **Optimise code** checkbox in the project properties window will be *unchecked*, which should map to `--optimize-`.  This will cause confusion when you hit F5 and expect to be able to debug your code.

## Repro Steps

* Create a new F# console application.
* Remove the `<Optimize>false</Optimize>` element from the `fsproj` file `Debug|AnyCPU` `PropertyGroup`.
* Allow VS to reload the project.
* Open the project properties.
* Observe that **Optimize code** is unchecked.
* Build the project.
* Observe that the `fsc` compiler command line in the Output window has the flag `--optimize+`.
* Hit F5 and you'll be surprised by this dialogue:
![screen shot 2015-08-12 at 12 35 06](https://cloud.githubusercontent.com/assets/189409/9223054/b6a1fa50-40ee-11e5-9963-2ab941181d86.png)

## Expected

When the element is missing, the default should be correctly reflected in the **Optimize code** checkbox.  *The default appears to be `true`, which I'm guessing is the safest option.*

## Actual

The **Optimize code** checkbox is not checked to match the `--optimize+` usage.

## Severity

It's not really bad, but it wasted time for me as it was missing from an F# community template.  I have submitted a [fix PR for the template](https://github.com/fsprojects/FSharpCommunityTemplates/issues/97).  In the linked Issue you'll see another person had the same problem.

## Version

VS2015 and F#4.

## Likely Cause

*I forked cloned and had a sperlunk around the project.  It seems clear to me, that a default is used somewhere that is not reflected in the UI, or the default is not observed by the `fsc` cmd line builder.  However, I ran out of time before nailing down the lines in question.*

## Workaround

Option 1:  Edit the project and add the `<Optimize>` element.

Option 2:  Check the Project Properties **Optimize code** checkbox, save the solution, uncheck the box, save the solution (the element will now be in the proj file, set to `false`).

*Hope this helps!  Thanks for all your hard work F# people!*

**Comment by latkin** [comment]
@bentayloruk thanks for the detailed bug report!

**Comment by bentayloruk** [comment]
@latkin I got a bit carried away! :blush:

**Comment by enricosada** [comment]
really good bug report @bentayloruk , easy to fix with these detailed info

i checked the code in [fsc.fs](https://github.com/Microsoft/visualfsharp/blob/0f514efe25899ba59778b5bb522e2724aec44a3d/src/fsharp/FSharp.Build/Fsc.fs#L120-L121)

```fsharp
    let mutable optimize  : bool = true
    let mutable tailcalls : bool = true
```

the only other true is `tailcalls`, but the command line parameter is not added so difficult too discover the bug.
This option is enabled by default, source [MSDN](https://msdn.microsoft.com/en-us/library/dd233171.aspx).

```fsharp
        if optimize then
            builder.AppendSwitch("--optimize+")
        else
            builder.AppendSwitch("--optimize-")
        if not tailcalls then
            builder.AppendSwitch("--tailcalls-")
```

i think is should do the same for tailscalls too. if useless, ignore the commit @latkin
