### ISSUE TITLE
Performance issue when calling Async.RunSynchronously inside Async.Parallel

### ISSUE THREAD

**Issue by eiriktsarpalis** [Microsoft/visualfsharp#581]
I can reproduce the following performance issue in VS 2015: 

https://gist.github.com/eiriktsarpalis/17b5652d57974d0e3e5d

Not sure why this happens.

EDIT: it looks like this can be solved by increasing the minimum number of threads in the thread pool, however I'd still be interested to find out why `RunSynchronously` causes such dramatic performance degradation.

**Comment by radekm** [comment]
It seems that most of the time is spent in `ResultCell.TryWaitForResultSynchronously` in call `resHandle.WaitOne`.

**Comment by radekm** [comment]
I wonder whether the problem isn't caused by blocking thread pool threads by waiting.

**Comment by radekm** [comment]
I think that blocking threads by waiting for asynchronous operations should avoided - it may cause deadlock when thread pool runs out of threads (e.g. in your case by setting `System.Threading.ThreadPool.SetMaxThreads(20, 1000)`):

```fsharp
let run x = Async.RunSynchronously x

System.Threading.ThreadPool.SetMaxThreads(20, 1000) |> ignore

let runParallel (workflow : Async<'T>) =
    [| for i in 1 .. 100 -> workflow |] 
    |> Async.Parallel
    |> run

let a = async { return 42 }
let b = async { return run (async { return 42 })}

runParallel b
```

**Comment by latkin** [comment]
Can you comment on whether this affects older F#/VS versions, or repros differently for x86 vs x64/RyuJIT?

**Comment by radekm** [comment]
Times reported by this code

```
let run x = Async.RunSynchronously x

let runParallel (workflow : Async<'T>) =
    [| for i in 1 .. 100 -> workflow |] 
    |> Async.Parallel
    |> run

let b = async { return run (async { return 42 })}

let sw = System.Diagnostics.Stopwatch()

sw.Start()
runParallel b
printfn "time: %A" sw.Elapsed
System.Console.ReadLine()
```

on VS 2015, Windows 10:

- .NET Framework 4.5.2, x86: 00:01:37
- .NET Framework 4.5.2, x64: 00:01:35
- .NET Framework 4.6, x86: 00:01:36
- .NET Framework 4.6, x64: 00:01:37
- .NET Framework 4.6, x86, legacy JIT: 00:01:35
- .NET Framework 4.6, x64, legacy JIT: 00:01:36

What is actually interesting is that all threads cross the line (from `control.fs`)

```fsharp
let ok = resHandle.WaitOne(millisecondsTimeout= timeout,exitContext=true) 
```

almost always at the same time - after the last thread starts waiting.

**Comment by latkin** [comment]
I see the same perf compiling against F# 4.0, 3.1, 3.0. So at least not a recent regression.

**Comment by radekm** [comment]
> What is actually interesting is that all threads cross the line (from `control.fs`)

The reason is that `Async.Parallel` queues all operations at the beginning. If I change

```fsharp
                    tasks |> Array.iteri (fun i p ->
                        queueAsync
                                innerCTS.Token
                                // on success, record the result
                                (fun res -> recordSuccess i res)
                                // on exception...
                                (fun edi -> recordFailure (Choice1Of2 edi))
                                // on cancellation...
                                (fun cexn -> recordFailure (Choice2Of2 cexn))
                                p
                            |> unfake);
```

to queue only `Environment.ProcessorCount` operations

```fsharp
                    let rec queueBatch tasks =
                        let now, later =
                            if Array.length tasks <= Environment.ProcessorCount
                            then tasks, [| |]
                            else tasks |> Array.splitAt Environment.ProcessorCount
                        now |> Array.iteri (fun i p ->
                            queueAsync
                                    innerCTS.Token
                                    // on success, record the result
                                    (fun res -> recordSuccess i res)
                                    // on exception...
                                    (fun edi -> recordFailure (Choice1Of2 edi))
                                    // on cancellation...
                                    (fun cexn -> recordFailure (Choice2Of2 cexn))
                                    p
                                |> unfake);
                        if later |> Array.isEmpty |> not then
                            ThreadPool.QueueUserWorkItem(fun _ -> queueBatch later)
                            |> ignore

                    queueBatch tasks
```

then it takes less than two seconds (because waiting for results is interleaved with computing results and `ThreadPool` doesn't need to grow up to 100 threads to do some work - originally almost always 100 waiting operations were queued before any operation which computes some result).

**Comment by radekm** [comment]
Same behaviour but without `async`:

```fsharp
open System.Threading

let queue f =
    ThreadPool.QueueUserWorkItem(fun _ -> f () |> ignore) |> ignore

let work () =
    let ev = new ManualResetEvent(false)       
    queue (ev.Set)
    ev.WaitOne() |> ignore

do
    let n = 100
    let finished = new CountdownEvent(1)

    seq { 1 .. n }
    |> Seq.iter (fun _ ->        
        finished.AddCount()
        queue (fun () ->
            work ()
            finished.Signal()))

    finished.Signal() |> ignore

    // Wait until work is done - usually until `ThreadPool` grows to `n + 1` threads.
    finished.Wait()
```

**Comment by radekm** [comment]
Maybe this issue could be solved if `RunSynchronously` could use current thread (especially if it is already a thread from `ThreadPool`) instead of blocking it and queuing work to another thread in `ThreadPool` (or do we have to start with an empty stack?).

**Comment by eiriktsarpalis** [comment]
I should point out that the issue does not occur if implementing an `Async.RunSynchronously` on top of `Task.Result`:
```fsharp
let run' (x : Async<'T>) =
    let tcs = new TaskCompletionSource<'T>()
    Async.StartWithContinuations(x, tcs.SetResult, tcs.SetException, fun _ -> tcs.SetCanceled ())
    tcs.Task.Result

let runParallel (workflow : Async<'T>) =
    [| for i in 1 .. 100 -> workflow |] 
    |> Async.Parallel
    |> run

let a = async { return 42 }
let b = async { return run (async { return 42 })}
let c = async { return run' (async { return 42 })}

runParallel a // Real: 00:00:00.031, CPU: 00:00:00.015, GC gen0: 0, gen1: 0, gen2: 0
runParallel b // Real: 00:01:24.086, CPU: 00:00:00.000, GC gen0: 0, gen1: 0, gen2: 0
runParallel c // Real: 00:00:00.003, CPU: 00:00:00.015, GC gen0: 0, gen1: 0, gen2: 0
```

**Comment by eulerfx** [comment]
I see similar numbers. However, using the following alternative to `Async.Parallel` it is much better:

```fsharp
open System
open System.Threading
open System.Threading.Tasks

[<AutoOpen>]
module AsyncEx =
  
  type Async with

      /// Creates an async computation which runs the provided sequence of computations and completes
      /// when all computations in the sequence complete. Up to parallelism computations will
      /// be in-flight at any given point in time. Error or cancellation of any computation in
      /// the sequence causes the resulting computation to error or cancel, respectively.
      static member ParallelIgnore (parallelism:int) (xs:seq<Async<_>>) = async {                
        let sm = new SemaphoreSlim(parallelism)
        let cde = new CountdownEvent(1)
        let tcs = new TaskCompletionSource<unit>()
        let inline tryComplete () =
          if cde.Signal() then
            tcs.SetResult(())
        let inline ok _ =
          sm.Release() |> ignore
          tryComplete ()                
        let inline err (ex:exn) =
          tcs.TrySetException ex |> ignore
          sm.Release() |> ignore                        
        let inline cnc (ex:OperationCanceledException) =      
          tcs.TrySetCanceled() |> ignore
          sm.Release() |> ignore
        try
          use en = xs.GetEnumerator()
          while not (tcs.Task.IsCompleted) && en.MoveNext() do
            sm.Wait()
            cde.AddCount(1)
            Async.StartWithContinuations(en.Current, ok, err, cnc)                              
          tryComplete ()
          do! tcs.Task |> Async.AwaitTask
        finally      
          cde.Dispose()    
          sm.Dispose() }




let run x = Async.RunSynchronously x

let runParallel (workflow : Async<'T>) =
    [| for i in 1 .. 100 -> workflow |] 
    |> Async.ParallelIgnore 10
    |> run

let a = async { return 42 }
let b = async { return run (async { return 42 })}

runParallel a // Real: 00:00:00.031, CPU: 00:00:00.015, GC gen0: 0, gen1: 0, gen2: 0
runParallel b // Real: 00:00:00.023, CPU: 00:00:00.031, GC gen0: 0, gen1: 0, gen2: 0
```

**Comment by radekm** [comment]
IMO the number of parallel computations should be controlled by `ThreadPool` by its hill climbing heuristics (especially in this case when tasks are very short).

**Comment by letrec** [comment]
Relying on ThreadPool makes sense only if computations are CPU bound, which is not always the case.

**Comment by eulerfx** [comment]
@radekm  Good point, using on ThreadPool alone for this would be ideal, but some issues are that it is global to the process, and sometimes, particularly IO bound workflows, as alluded by @letrec, are better tuned using explicit parallelism as above. A more adaptive approach uses a controller to set the degree of parallelism. It would be great if in the future, Async parameterized the scheduler like MBrace or Hopac.

**Comment by eiriktsarpalis** [comment]
@eulerfx @radekm @latkin I think this is clearly not an issue with Async.Parallel, but rather a performance bug in Async.RunSynchronously, which uses ManualResetEvent for awaiting. Here is the relevant code:

https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/control.fs#L1208

Writing an improved Async.RunSynchronously (for example, something like [this](http://fssnip.net/sl)) would do much to fix a serious performance bug in a pattern that is all too common in async-heavy projects.

**Comment by palladin** [comment]
@eulerfx Regarding your comment about Async scheduler parameterization, I'm experimenting with Algebraic Effects and specifically with applications to concurrency, for inspiration you can check http://kcsrk.info/ocaml/multicore/2015/05/20/effects-multicore/ .

**Comment by eulerfx** [comment]
@palladin cool! gadts would be nice :)

**Comment by dsyme** [comment]
> It would be great if in the future, Async parameterized the scheduler like MBrace or Hopac.

I believe we would accept a well-thought-out design proposal and implementation that implements this.  The interaction with task schedulers is the most significant consideration.

Likewise, an Async design extension that allowed localized async storage or the propogation of extra state through the call chain would also be of interest. For example this might remove the need for "local" single-machine cloud workflows in MBrace.

Strangely neither of these are listed on http://fslang.uservoice.com (though that can easily be fixed - please go ahead :) )

**Comment by eulerfx** [comment]
added http://fslang.uservoice.com/forums/245727-f-language/suggestions/9688323-support-custom-scheduler-in-async

**Comment by palladin** [comment]
@eulerfx I'm experimenting with OCaml but for a very early sneak peak https://github.com/palladin/Eff

**Comment by eulerfx** [comment]
@palladin cool, this sent me on a bit of a rabbit hole, will check out in depth later.

**Comment by jack-pappas** [comment]
This issue brings up an interesting aspect of F# ``async`` -- it's implemented using [``ManualResetEvent``](https://msdn.microsoft.com/en-us/library/system.threading.manualresetevent%28v=vs.110%29.aspx) instead of [``ManualResetEventSlim``](https://msdn.microsoft.com/en-us/library/system.threading.manualreseteventslim%28v=vs.110%29.aspx). The latter wasn't introduced until .NET 4.0 and the ``async`` implementation has been around for a while so I'm not surprised it's still using the older mechanism.

The main difference between the two is that ``ManualResetEvent`` uses [functionality](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682655%28v=vs.85%29.aspx) provided by the OS, while ``ManualResetEventSlim`` tries to avoid the system call overhead by spin-waiting for a short time before falling back to the ``ManualResetEvent`` behavior.

If anyone has some time to experiment, it'd be interesting to see whether modifying the ``async`` implementation to use ``ManualResetEventSlim`` improves the performance of this case. If I remember correctly, @vasily-kirichenko tweeted a few months back about a performance comparison he'd done between hopac and ``async`` that looked like it'd be another good test case for this.

**Comment by eiriktsarpalis** [comment]
@jack-pappas I ran some further tests incorporating `ManualResetEventSlim` only to discover that `ManualResetEvent` is not at fault here. First of all, the numbers that I gave in my [earlier post](https://github.com/Microsoft/visualfsharp/issues/581#issuecomment-135969183) are wrong in the sense that the performance of `runParallel c` is such only when run immediately after `runParallel b`. In fact, any  implementation of `run : Async<'T> -> 'T` be it using `ManualResetEvent`, `Task` or `ManualResetEventSlim` demonstrate the same performance bottleneck once tested in an isolated setting. 

I can thus say conclusively that this behaviour occurs solely because of the ThreadPool's conservative allocation of additional worker threads. This is essentially a pathological manifestation of a known performance issue, which can be solved by increasing the minimum number of threads, as indicated in my first post.

**Comment by palladin** [comment]
Unfortunately the only solution is to set a large number of threads in ThreadPool.SetMinThreads

**Comment by radekm** [comment]
> which can be solved by increasing the minimum number of threads, as indicated in my first post.

Maybe `RunSynchronously` should do computation in the current thread (especially if it is already a thread from `ThreadPool`)?

**Comment by dsyme** [comment]
@radekm - IIRC the decision to run the computation passed to RunSynchronously in the thread pool was deliberate, to ensures the SynchronizationContext for the computation is null rather than the event handler of the (blocked) GUI thread.

**Comment by radekm** [comment]
@dsyme In that case the current thread could be still used if `Thread.CurrentThread.IsThreadPoolThread` is true. IMO the only disadvantage of using the current thread is that the computation doesn't start with empty stack.

**Comment by dsyme** [comment]
@radekm Yes, that sounds correct.  I wasn't actually aware of that flag.  Please feel free to send a PR+tests for that

**Comment by radekm** [comment]
Ok, I'll do that this week.
