### ISSUE TITLE
Web applications cannot be published to Azure from Publish Wizard

### ISSUE THREAD

**Issue by OnurGumus** [Microsoft/visualfsharp#5829]
Recently I noticed that when we create a VS 2017 .NET Core Web application project for F#
publishing to azure won't work.

The reasons is publish adds the following to the project file  : 
`  <UserSecretsId>3b2b079e-6201-411f-aa7d-....</UserSecretsId>`

Which in turn causes the compiler give : 

`Program.fs(23,9): error FS0433: A function labeled with the 'EntryPointAttribute' attribute must be the last declaration in the last file in the compilation sequence.`

#### Repro steps

1. Create an Empty .NET Core Web project with F#
2. Right click to Project and Publish it to Azure

It will take long time. Cancel it and try to build the projects

This issue didn't exist in June (I always keep VS up to date). But now happens with 15.8.8.

**Comment by OnurGumus** [comment]
Adding   `<GenerateUserSecretsAttribute>false</GenerateUserSecretsAttribute>` works around the issue.

**Comment by cartermp** [comment]
Linking duplicate #5549

This will be fixed in ASP.NET 2.2: https://github.com/aspnet/Configuration/pull/872
