### ISSUE TITLE
Should private DU constructors be private to the type or the type's parent scope?

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#5855]
The following code compiles:

```f#
type A = private A of string

let x = A ""

let f (A x) = x
```

The following does not:

```f#
module M =
  type A = private A of string

let x = A ""

let f (A x) = x
```

Is this intended? I was sure a DU's private constructors were private to the type, not to the type's parent scope, but apparently I remember incorrectly. Is it possible to have a DU constructor that is private to the type?

**Comment by FunctionalFirst** [comment]
Secton 10.5 of the spec, _Accessibility Annotations_, calls this a "type representation" and states the following:

> `private` on a type, module, or type representation in a module means “private to the module.”

**Comment by cmeeren** [comment]
Yes, but it's an accessibility modifier on a DU case (i.e. constructor), not the DU itself.

**Comment by FunctionalFirst** [comment]
No, it's an accessibility modifier for the type's representation, i.e., all cases, not just the case immediately following the modifier.

**Comment by cmeeren** [comment]
Ah, I see. Thanks!

**Comment by cartermp** [comment]
Thanks @FunctionalFirst, this is indeed by design.
