### ISSUE TITLE
Development size of the repository requires multiple GB's space

### ISSUE THREAD

**Issue by realvictorprm** [Microsoft/visualfsharp#5857]
The visualfsharp repository requires multiple GB's of space for development which isn't very contributor friendly. On my PC it requires for example up to 4 GB's of space. It would be good to reduce the required space to less than 1 GB.

**Comment by cartermp** [comment]
I don't think there's much we can do about this if you also want to do VS tooling development. We've reduced our dependencies down to almost the bare minimum to build .NET applications within Visual Studio. You can trim this down a bit by using `FSharp.sln` and not installing the Visual Studio SDK, but that's only going to trim a few 100 MB.
