### ISSUE TITLE
Show completion list after a character is typed is buggy and not respected

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#5859]
This setting:

![image](https://user-images.githubusercontent.com/6309070/47930559-89e25f00-de89-11e8-92f9-dc63284782ad.png)

Is always set to unchecked on my machine, even if I re-check it. But if I explicitly leave it unchecked, I still get completions when hitting backspace.

**Comment by majocha** [comment]
Hi @cartermp, I think I got a fix for the setting not saving.
OTOH is `ShowAfterCharIsDeleted` being used anywhere? [repo search](https://github.com/Microsoft/visualfsharp/search?q=ShowAfterCharIsDeleted&unscoped_q=ShowAfterCharIsDeleted) shows nothing. Find all references confirms that.

**Comment by cartermp** [comment]
Fully fixed after #5863 and #5865, thanks @majocha!

After playing with it a bit, I think I actually prefer the behavior with it turned off.
