### ISSUE TITLE
Add support in LeafExpressionConverter.QuotationToLambdaExpression for PropertySet

### ISSUE THREAD

**Issue by stakx** [Microsoft/visualfsharp#5864]
This is a request to enhance `LeafExpressionConverter.QuotationToLambdaExpression` such that it can translate `PropertySet` `Expr`s to LINQ expression trees.

`LeafExpressionConverter.QuotationToLambdaExpression` cannot currently convert `PropertySet` expressions to a LINQ expression tree, even though the construct would appear to be supported by the latter and the translation would presumably be straightforward. (I assume it would be quite similar to [the translation for `PropertyGet`](https://github.com/Microsoft/visualfsharp/blob/46b758f1142011029d5cd61959c64bf6e3acdb66/src/fsharp/FSharp.Core/Linq.fs#L459-L470).)

Having this capability would be nice e.g. for libraries such as [Moq](https://github.com/moq/moq4) which heavily rely on LINQ expression trees, but are currently limited by the Roslyn compilers which do not allow assignment statements in lambda functions that are to be converted to LINQ `Expression`s; see e.g. https://github.com/dotnet/csharplang/issues/158.)

#### Repro steps

Run the following program:

```fsharp
open Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter

type INamed =
    abstract member Name: string with get, set

[<EntryPoint>]
let main argv =
    <@ fun (n: INamed) -> n.Name <- "Bork" @>
    |> QuotationToLambdaExpression
    |> ignore
    0
```

#### Expected behavior

I would expect the program to succeed. `QuotationToLambdaExpression` should convert the shown code quotation to a LINQ expression tree roughly equivalent to what the following C# code would produce:

```csharp
interface INamed
{
    string Name { get; set; }
}

var n = Expression.Parameter(typeof(INamed), "n");

_ = Expression.Lambda(
        Expression.Assign(
            Expression.Property(n, typeof(INamed).GetProperty(nameof(INamed.Name))),
            Expression.Constant("Bork")),
        n);
```

#### Actual behavior

The function fails with:

```
System.NotSupportedException: Could not convert the following F# Quotation to a LINQ Expression Tree
--------
PropertySet (Some (f), Name, [Value ("Bork")])
-------------

   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.ConvExprToLinqInContext(ConvEnv env, FSharpExpr inp)
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.ConvExprToLinqInContext(ConvEnv env, FSharpExpr inp)
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.QuotationToLambdaExpression[T](FSharpExpr`1 e)
   at Program.main(String[] argv) in Program.fs:line 8
```

#### Related information 

* Visual Studio 15.8.8+28010.2048
* Visual F# Tools 10.2 for F# 4.5 (commit hash: 55a3dc3231c95c77f81ee53f7d29152029da7408)
* .NET Runtime: Tried on .NET Core 2.1

**Comment by cartermp** [comment]
@stakx Can you open an issue over here? https://github.com/fsharp/fslang-suggestions Thanks
