### ISSUE TITLE
FSharpType.IsUnion returns false for unions with private constructors

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Microsoft/visualfsharp#5876]
Is this intended?

```
Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> type Foo1 = Code of string
- type Foo2 = private Code of string
- 
- open FSharp.Reflection
- FSharpType.IsUnion(typeof<Foo1>) |> printfn "%b"
- FSharpType.IsUnion(typeof<Foo2>) |> printfn "%b";;
true
false
type Foo1 = | Code of string
type Foo2 = private | Code of string
val it : unit = ()
```

I also got the same result when compiling an F# with dotnet SDK 2.1.401 (FSharp.Core 4.5.2).

**Comment by alfonsogarciacaro** [comment]
This evals to true, so maybe it works according to specs but it's a bit unexpected:

```FSharpType.IsUnion(typeof<Foo2>, System.Reflection.BindingFlags.NonPublic)```

**Comment by alfonsogarciacaro** [comment]
I'm noticing that most of the reflection methods need the `BindingFlags.NonPublic` flag for unions with private constructors (also for records). I guess it's intended so I'll close the issue. Sorry for noise, blame @forki ;)

**Comment by forki** [comment]
Yes always blame on Remmidemmi track...

Am Mi., 7. Nov. 2018, 16:51 hat Alfonso Garcia-Caro <
notifications@github.com> geschrieben:

**Comment by pbachmann** [comment]
@alfonsogarciacaro 
Don't apologise for making this noise! You pointed me to the fix and so I didn't need to raise this as an issue myself. ie.

`if FSharpType.IsUnion(typ, true) then`

People like me have a much happier life because of the hard work of people like you.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for your words @pbachmann Happy to make you happy!
