### ISSUE TITLE
How to contribute to F# 4.0 update 1

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#590]
The next release of Visual F# will be a minor update to F# 4.0.  It will most likely be delivered with Visual Studio 2015 Update 1, though we are also considering releasing it completely standalone as we have done in the past with 3.1.1 and 3.1.2.

If you want to contribute toward this release, take a look at the [F# 4.0 Update 1](https://github.com/Microsoft/visualfsharp/milestones/F%23%204.0%20Update%201) milestone.  Issues and PRs that we'd like to include are listed there.

Motivated contributors are requested to start with this list if they are looking for issues to tackle.  We remain open to all high-quality contributions, but for the time being we'll prioritize those which match well with the Update 1 plans.

Please send all PRs to the `master` branch, as outlined in https://github.com/Microsoft/visualfsharp/issues/563

**Comment by forki** [comment]
So PRs to those issues should go against OOB branch and other stuff against master?

**Comment by latkin** [comment]
Correct, though I need to merge OOB into master first (will do that today).

**Comment by latkin** [comment]
Just merged OOB into master, so now master is open for vNext stuff (beyond just updates).

@forki I take it back, all contributions should go against `master`, per https://github.com/Microsoft/visualfsharp/issues/563. We will port stuff back into OOB as appropriate.

**Comment by forki** [comment]
Yes that's much better. master as a real master branch and target for all pull requests. That's how most projects do it. Nice to see it here, too.

**Comment by xperiandri** [comment]
Will you update environment setup process?
So that it will not require to do 100500 steps but just download a repository and run some cmd file if needed to make environment ready.

**Comment by xperiandri** [comment]
Is F# source building simplified since previous year like Roslyn? Can I just download it and build?

**Comment by isaacabraham** [comment]
@xperiandri I would direct you to #1100 which I raised earlier today.
