### ISSUE TITLE
Symbols are not updated on-the-fly between F# projects

### ISSUE THREAD

**Issue by cmeeren** [Microsoft/visualfsharp#5901]
I frequently (at least a couple of times per week) experience a bug where symbols are not updated on-the-fly between F# projects. Let's say project A has a reference to project B. If I make changes in B, they are not visible in A until I have compiled B, even though both A and B are F# projects.

Again, things mostly work, and I have no reliable repro, but I get this error fairly frequently.

Is this a known bug? Can I do more to help without having a reliable repro?

#### Related information 

* Windows 10 1803
* VS  15.8.9
* VF# nightlies 15.8.20181108.1

**Comment by cartermp** [comment]
Which kinds of F# projects are these - .NET SDK style? Also if you back off of nightlies do you observe this?

We've been making a few changes to P2P referencing to account for changes in coordination with Roslyn for VS 2019, and those are in master (#5818). I wouldn't be surprised if that affects nightlies.

**Comment by cmeeren** [comment]
.NET SDK style, yes. I can try to turn off nightlies, but if I don't see the error it will be a while before I can say with any kind of certainty that it had helped.

**Comment by cartermp** [comment]
Makes sense. If, with 15.9 and no nightlies, you can still see it, then we definitely have a bug. But given the churn in this space for the forthcoming 16.0 Preview 1 release later this year, I think nightlies may be a bit unstable in this regard. Hopefully you don't see it with nightlies off!

**Comment by cmeeren** [comment]
Thanks. I'll turn the nightlies off and let you know as soon as I see the bug. Still on 15.8 though, is that interesting or should I wait until 15.9 is out?

**Comment by cartermp** [comment]
15.9 is already out, so I recommend updating to that (if anything for the additional bug fixes around `byref`s).

**Comment by cmeeren** [comment]
I'll do that then, hadn't gotten the yellow icon yet. Hopefully you won't hear anything from me!

**Comment by cmeeren** [comment]
I experienced the bug the last couple of days (VS 15.9, no nightlies), but deleted the solution's `.vs` folder and now it seems fine again.

**Comment by cartermp** [comment]
The `.vs` folder is (among other things) a cache that the VS project system uses. Are the projects in your solution using the .NET SDK-style format?

**Comment by cmeeren** [comment]
Yes they are.

(I know the `.vs` folder contains a cache, by the way, which is why I wanted to try deleting it. But I figured I'd post a comment anyway, since it still doesn't explain why the behavior occurred in the first place.)

**Comment by cartermp** [comment]
Gotcha. In this case I don't think it's an F# tools issue, since the .NET SDK-style projects used by F# are a separate codebase. We don't store anything in the `.vs` folder either. This sort of thing used to be a lot worse but the fact that it still happens means there's a bit more to suss out.

Could you file a bug on the dotnet/project-system repository?

**Comment by cmeeren** [comment]
https://github.com/dotnet/project-system/issues/4452
