### ISSUE TITLE
.NET runtime optimization service failed to compile fsc.exe, message in windows event log

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#5909]
After upgrading to VS 15.9.0, I found the following error in the event log of Windows:

> .NET Runtime Optimization Service (clr_optimization_v4.0.30319_64) - 1>Failed to compile: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsc.exe . Error code = 0x80131f07 

### Repro steps

Not sure about repro, though I can probably run the optimization service again if I know how to do that by hand, to see if this was a one-time error or repeatable.

### Expected behavior

No errors expected.

### Actual behavior

As above. Though I am not sure about the impact. I have had performance issues in the past and perhaps this is a sign that points in the right direction, but I don't know exactly what the optimization service is supposed to do.

### Known workarounds

None that I know of. Except that I can use Visual Studio and F# normally without problems.

### Related information 

* Operating system: Windows 7 (I also have Win10, but I didn't see it there)
* VS 2017 Pro udate to 15.9.0.

**Comment by cartermp** [comment]
@abelbraaksma Have you seen this since updating? What about on other machines? The tool isn't a part of VS or the F# tools (nor is it NGEN that's running) so I doubt this is a problem with F# itself. Still, I'll keep this open and tag as external.

**Comment by abelbraaksma** [comment]
@cartermp, what I understand from the _.NET Runtime Optimization Service_ is that it runs periodically or in the background to update and/or precompile assemblies ([source](https://answers.microsoft.com/en-us/windows/forum/windows_8-performance/what-is-net-runtime-optimization-service-and-why/1f8779db-4dab-4f8c-aa86-dfd2ac176fd7))

Looking back at that date, it appears that I have dozen such messages, including the likes of this:

> .NET Runtime Optimization Service (clr_optimization_v4.0.30319_32) - Failed to compile C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\TestExplorer\System.ValueTuple.dll because of the following error: The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047).

However, they seem to be limited to the update on that particular date (15 November, on my machine). A later update of Visual Studio on 3 December caused only 4 such errors.

I don't know how to ascertain that compiling succeeds, since I don't have success messages or logs, but I think I can assume that it precompiles any touched assemblies and if it was re-occurring, it would have such errors again and again.

There's not really anything conclusive we can get from this, I think, unless perhaps that something fishy was going on on that particular date (perhaps a memory issue, or hard-disk issue). Also, if the assemblies really couldn't be compiled, as the message suggests, I doubt I would be able to use Visual Studio, or F# at all. Perhaps just a fluke?

**Comment by cartermp** [comment]
Sounds good, I'll close this out.
