### ISSUE TITLE
Type providers usage of FSharpCoreAssemblyVersion is resulting in large LOH allocations and UI delays inside of VS

### ISSUE THREAD

**Issue by davkean** [Microsoft/visualfsharp#5930]
Trace: https://developercommunity.visualstudio.com/content/problem/379653/vs-slow-typing-and-hang-1.html.

GC Rollup By Generation
--

Gen | Count | MaxPause | MaxPeak MB | Max AllocMB/sec | TotalPause | TotalAlloc MB | Alloc MB/MSec GC | Survived MB/MSec GC | MeanPause | Induced
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ALL | 305 | 13,100.2 | 2,515.3 | 9,389.575 | 23,078.5 | 2,845.1 | 0.1 | 13.147 | 75.7 | 1
0 | 187 | 20.6 | 2,481.5 | 4,736.269 | 1,031.3 | 1,109.3 | 0.4 | 0.050 | 5.5 | 0
1 | 108 | 13,100.2 | 2,509.7 | 9,389.575 | 14,950.0 | 1,486.1 | 5.3 | 0.199 | 138.4 | 0
2 | 10 | 728.8 | 2,515.3 | 14.396 | 7,097.2 | 249.7 | 2.5 | 20,674.062 | 709.7 | 1

Type Providers usage of FSharpCoreAssemblyVersion in the above trace is causing 250 MB of LOH allocations:

![image](https://user-images.githubusercontent.com/1103906/48748752-04a1db80-eccc-11e8-9921-af80ba5bc755.png)

**Comment by davkean** [comment]
This is very similar to https://github.com/Microsoft/visualfsharp/issues/5931 I think, in that this is probably reading FSharp.Core.dll?

**Comment by baronfel** [comment]
did some manual counts by debugging some tests in the TPSDK, and the big hit seems to be the `ILModuleReader` constructor. When we load mscorlib and FSharp.Core in order to read the FSharp.Core assembly version, the sizes/counts of the byte[] and strings in memory balloon wildly.

Some numbers:
```
Stage		Byte[]	Size		String[]	Size		String	Size
Pre-mscorlib	431	130872	        411		24360	        6180	953048
Post-mscorlib	438	959528	        414		24728	        6284	958320 
// some bad stuff happens because my debugger broke, so I restarted 
// the magnitude still shows the effect though
Pre-f# core	1590	9508648         340	        18760	        16453	1559816
Post-f# core	1609	11844312	345		19208	        16534	1563992
```
Sizes are in bytes, but the effect seems to be apparent.  

This _should_ be a one-time hit because these module readers are held in a cache, but /shrug to that.

**Comment by cartermp** [comment]
Note that this also takes up notable CPU time:

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/6309070/50877214-bc2aa400-1385-11e9-8454-ac35c8e43584.png">

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/6309070/50877249-f005c980-1385-11e9-975e-02a9c76965d2.png">

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/6309070/50877318-2ba09380-1386-11e9-8576-1ea5255ec7a8.png">

**Comment by dsyme** [comment]
That piece of code in the TPSDK doing byte array comparison has already been fixed https://github.com/fsprojects/FSharp.TypeProviders.SDK/pull/284/files#diff-7c540ae6a67f14c48d0403e7b021fc86R6646, we just need to update the various type providers to use this.

There are still too many ILModuleReader being created (we can save them in a time cache) but the aove should fix most things.

**Comment by cartermp** [comment]
Okay. I'll create an issue on the TPSDK since this ultimately a concern over there.
