### ISSUE TITLE
Huge allocation in PrettyNaming.splitAroundQuotations

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#5939]
Editing a file containing an XmlProvider declaration, for about 20 seconds:

![image](https://user-images.githubusercontent.com/873919/48760812-209b8200-ecb8-11e8-8277-8468a20c6505.png)

![image](https://user-images.githubusercontent.com/873919/48760839-390b9c80-ecb8-11e8-9c4d-b79621a33cad.png)

![image](https://user-images.githubusercontent.com/873919/48760920-6b1cfe80-ecb8-11e8-82bc-a42301a375c2.png)

AFAIK, the problem is here:

https://github.com/Microsoft/visualfsharp/blob/44c7e10ca432d8f245a6d8f8e0ec19ca8c72edaf/src/fsharp/PrettyNaming.fs#L585

As a result, there were several seconds freezes in Rider while typing.

**Comment by cartermp** [comment]
#5599 reduces `split` allocations by an order of magnitude, but I'm not sure if this went into a given VS release and corresponding FCS release. You can verify if this helps rider by using a build of FCS from this repo.

**Comment by vasily-kirichenko** [comment]
@cartermp thank you! I'm closing this issue.
