### ISSUE TITLE
fsc failing with error fso192 when generating doc for parameter of type coming from type provider

### ISSUE THREAD

**Issue by michalmalecki** [Microsoft/visualfsharp#595]
Environment:
Fsc 4.31
Visual Studio 2013
Windows 7
Repro:
Add CSV file to F# command line project and configure CSV type provider
create a simple function 
let hello foo =
()

where foo is of type generated by type provider
add doc to this function by adding ///

compile project
Expected: builds fine
Actual:
fails with  fso192 internal error"impossible"

Workaround - remove doc for that function (may be weak for public api)

**Comment by latkin** [comment]
Thanks for the issue report.  Can you provide a complete, self-contained repro project?

I am unable to repro on my box.

foo.csv
```
Name,Age
Joe,10
Sally,15
Sue,20
Homer,25
```

program.fs
```fsharp
open FSharp.Data

type People = CsvProvider< "./foo.csv" >

/// my foo function doc
let foo (p : People.Row) =
    printfn "Person: %s %d" p.Name p.Age

People.Load(@"D:\source\foo.csv").Rows |> Seq.iter foo
```

Builds/runs ok:

```
D:\source
> & 'C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\Fsc.exe' .\test.fs -r FSharp.Data.dll
Microsoft (R) F# Compiler version 12.0.30815.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

D:\source
> .\test.exe
Person: Joe 10
Person: Sally 15
Person: Sue 20
Person: Homer 25
```

**Comment by michalmalecki** [comment]
Hi,
sorry for not providing this in the first place! You need to add 
--doc:foo.XML
in your fc call to force generation of the documentation, and in effect catastrophic failure.

So the full command:
"C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\Fsc.exe" .\program.fs -r FSharp.Data.dll --doc:foo.XML

**Comment by panesofglass** [comment]
_That_ explains the weird API doc failures with FSharp.Formatting, I bet! Thanks for finding this!

**Comment by dsyme** [comment]
This was fixed a long time ago
