### ISSUE TITLE
SRTP resolution is order-dependent in unintuitive, subtle ways

### ISSUE THREAD

**Issue by drvink** [Microsoft/visualfsharp#596]
When attempting to write groups of overloads, a surprising behavior manifests. In the following code, the compiler obsessively chooses the `string` overload for `invoke`; attempts at fixing the problem result in it choosing the `seq` overload instead. You will never get what you want: an `uncons` that is dispatched appropriately on type.

```fsharp
#light "off"

open System

type Uncons = class
  static member _resolve = Unchecked.defaultof<Uncons>

  static member inline Uncons (x : 'F) =
    ((^F) : (static member Uncons : ^F -> ^R) x)

  static member Uncons (s : string) =
    if String.IsNullOrEmpty s then None else
    Some (s.[0], if s.Length > 1 then s.[1..] else "")

  static member Uncons (s : seq<_>) =
    if Seq.isEmpty s then None else
    Some (Seq.head s, Seq.skip 1 s)

  static member Uncons (s : _ list) =
    match s with
    | [] -> None
    | x::xs -> Some (x, xs)

  static member inline invoke x =
    let inline call (a : ^a, b : ^b) =
      ((^a or ^b) : (static member Uncons : _ -> _) b) in
    call (Uncons._resolve, x)
end

let inline uncons x = Uncons.invoke x
```

However, there is a solution, and it is absurd:

```fsharp
#light "off"

open System

type Uncons = class
  static member _resolve = Unchecked.defaultof<Uncons>

  static member inline invoke x =
    let inline call (a : ^a, b : ^b) =
      ((^a or ^b) : (static member Uncons : _ -> _) b) in
    call (Uncons._resolve, x)
end

let inline uncons x = Uncons.invoke x

type Uncons with
  static member inline Uncons (x : 'F) =
    ((^F) : (static member Uncons : ^F -> ^R) x)

  static member Uncons (s : string) =
    if String.IsNullOrEmpty s then None else
    Some (s.[0], if s.Length > 1 then s.[1..] else "")

  static member Uncons (s : seq<_>) =
    if Seq.isEmpty s then None else
    Some (Seq.head s, Seq.skip 1 s)

  static member Uncons (s : _ list) =
    match s with
    | [] -> None
    | x::xs -> Some (x, xs)
end
```

Splitting the definition of the type fixes the problem. This is so bizarre that it seems more like the result of some aspect of the compiler's implementation rather than an intentional design decision. Either way, it really ought to be documented somewhere.

It's tempting to say that something ought to be fixed or corrected here, but that should probably take place as part of some greater conversation on the overloading/SRTP story. (Perhaps we can start that here? There doesn't seem to be a better venue for discussing language design/RFC-ish issues; UV certainly isn't the place, since its commenting is so weak.)

**Comment by radekm** [comment]
It seems that it also works if you annotate `x` with `^X`:

```fsharp
#light "off"

open System

type Uncons = class
  static member _resolve = Unchecked.defaultof<Uncons>

  static member inline Uncons (x : 'F) =
    ((^F) : (static member Uncons : ^F -> ^R) x)

  static member Uncons (s : string) =
    if String.IsNullOrEmpty s then None else
    Some (s.[0], if s.Length > 1 then s.[1..] else "")

  static member Uncons (s : seq<_>) =
    if Seq.isEmpty s then None else
    Some (Seq.head s, Seq.skip 1 s)

  static member Uncons (s : _ list) =
    match s with
    | [] -> None
    | x::xs -> Some (x, xs)

  static member inline invoke (x : ^X) =
    let inline call (a : ^a, b : ^b) =
      ((^a or ^b) : (static member Uncons : _ -> _) b) in
    call (Uncons._resolve, x)
end

let inline uncons (x : ^X) = Uncons.invoke x

let x = uncons [1; 2]
let y = uncons "dog"
```

**Comment by drvink** [comment]
I could have sworn I tried that. Indeed, that works, and appears to work for overloads defined on user-provided types as well. (Though this doesn't change the weirdness shown in the first post, nor the fact that the behavior as-is is surprising.)

**Comment by latkin** [comment]
Thanks for the issue report. Given the provided workaround, is there a concrete request besides "better documentation for statically resolved type arguments"?

**Comment by exercitusvir** [comment]
I think this shows another problem that I wanted to create an issue for. The F# compiler automatically infers generic type parameters that are indicated with ' to SRTP. I don't think it should do that. It should be explicit that a type parameter is a SRTP. But currently, the F# compiler even prohibits using ^ in the declaration. E.g. `<^T>` is not allowed. You have to type `<'T>`, which will be inferred to `<^T>`.

**Comment by drvink** [comment]
@exercitusvir You actually can write it, but you have to write `< ^T>` (note the space), since the lexer consumes `<^` as one token...tripped me up initially too.

@latkin No, that'll do for now; you can close this issue. Sorry for the noise.
