### ISSUE TITLE
Test Explorer does not discover unit tests in VS 2019 Preview build

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#5966]
(sorry OSS folks, you don't have access to this yet)

1. Build the solution in the IDE
2. Ensure that the NUnit test runner package is installed

VS 15.9.2:

![image](https://user-images.githubusercontent.com/6309070/49252162-255ae700-f3d8-11e8-89a1-1e015a6ed212.png)

VS 16.0 P1 internal build:

![image](https://user-images.githubusercontent.com/6309070/49252188-33106c80-f3d8-11e8-9a88-7b435ee02961.png)

Log in dev16: 
`[11/29/2018 12:54:24 PM Warning] No test is available in C:\repos\visualfsharp\vsintegration\src\FSharp.Editor\bin\Debug\FSharp.Editor.dll C:\repos\visualfsharp\vsintegration\src\FSharp.LanguageService\bin\Debug\FSharp.LanguageService.dll C:\repos\visualfsharp\vsintegration\src\FSharp.ProjectSystem.FSharp\bin\Debug\FSharp.ProjectSystem.FSharp.dll C:\repos\visualfsharp\vsintegration\src\FSharp.VS.FSI\bin\Debug\FSharp.VS.FSI.dll C:\repos\visualfsharp\vsintegration\tests\GetTypesVSUnitTests\bin\Debug\GetTypesVSUnitTests.dll C:\repos\visualfsharp\vsintegration\tests\Salsa\bin\Debug\VisualFSharp.Salsa.dll C:\repos\visualfsharp\vsintegration\tests\UnitTests\bin\Debug\VisualFSharp.UnitTests.dll C:\repos\visualfsharp\vsintegration\Utils\LanguageServiceProfiling\bin\Debug\LanguageServiceProfiling.exe. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.`

**Comment by cartermp** [comment]
We'll have to determine if this is on our side of on the test runner side.

**Comment by cartermp** [comment]
Can't repro today. Must just be some preview weirdness.

**Comment by cartermp** [comment]
Just for posterity:

* Tests cannot be run in VS 2019 preview yet because we are trying to load a dev15 .dll
* Tests cannot be run in VS 2017, when working out of the dev16 branch, due to failing to load a P2P reference

So if we're doing any dev16 work we cannot run unit tests locally 😢

**Comment by cartermp** [comment]
Re-opening due to internal ticket report

**Comment by cartermp** [comment]
So with File | New project for:

* MSTest
* NUnut
* xUnit

It all works. You just need to build the solution first.
![image](https://user-images.githubusercontent.com/6309070/49611943-12a45d00-f958-11e8-985d-266fe40b2a8d.png)

**Comment by cartermp** [comment]
I cannot reproduce this anymore.

**Comment by alex-piccione** [comment]
Not sure is the same issue or different.
In my case I noticed that VS cannot "discover" tests.
I have a VS solution with the main projects created in C# .Net 4.7.
The solution has also test projects (NUnit 3).
I add test projects in dotnet Core and change the Target Framework to "net47".
Right click in the test "run test" does not have any effect.
"Run All" in the Test View find all the test and after that I can select the test in the Tests Window and run it again. "Run test" context menu voice still doesn't work from the code. 
I don't have ReSharper.
It happens with VS 2019 preview 2.
It works in VS 2017 15.9.6.

**Comment by cartermp** [comment]
@alex-piccione Just for clarity, is this with C# projects or F# ones?

There are some new features for tests that are based on Roslyn syntax trees, so they won't work for F#. But the Test Runner should be able to discover and run tests provided that you build the .dll(s) and have the appropriate NuGet package runner installed into the test project(s).
