### ISSUE TITLE
Lookup on object of Action<T> is broken

### ISSUE THREAD

**Issue by Szer** [Microsoft/visualfsharp#5969]
Somehow compiler cannot get member of successfully inferred type:
![image](https://user-images.githubusercontent.com/10308233/49288049-aab1ca80-f4b0-11e8-898f-f22fad2c5e22.png)

#### Repro steps

Provide the steps required to reproduce the problem

1. Create project file:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
```

2. Create `Program.fs`
```fsharp
module WebApplication2

open Microsoft.AspNetCore
open Microsoft.AspNetCore.Hosting
open Microsoft.Extensions.DependencyInjection

type Foo() = 
    member val Bar = "" with get, set

type Startup private () =
    member __.ConfigureServices(services: IServiceCollection) =

        services.Configure<Foo>(fun foo -> printfn "%s" foo.Bar) 
        |> ignore

[<EntryPoint>]
let main args =
    WebHost
        .CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .Build()
        .Run()
    0
```

3. `dotnet build`

These two files in attach:
[WebApplication2.zip](https://github.com/Microsoft/visualfsharp/files/2633108/WebApplication2.zip)

#### Expected behavior

It should compile

#### Actual behavior

Compiler actually inferred `foo` type in lambda correctly, but fails to access type properties

#### Known workarounds

1. Add type annotation
2. Explicitly wrap lambda in Action<T> ctor

#### Related information 

Provide any related information 

* Win 10
* .NET Core 2.1.500
* Visual Studio 15.9.3

**Comment by Szer** [comment]
@abelbraaksma If I just create C# library with this method
![photo_2018-11-30_15-06-59](https://user-images.githubusercontent.com/10308233/49294775-f4a4ab80-f4c4-11e8-8f2d-a9a62e10bb63.jpg)
and call it like this (with same class definition)
![photo_2018-11-30_17-25-56](https://user-images.githubusercontent.com/10308233/49295669-5fef7d00-f4c7-11e8-830a-2435e07d1d9c.jpg)

It works OK. So there is something else beside being `Foo` a class

**Comment by abelbraaksma** [comment]
I spoke too soon, you're right. Though I'm unsure whether both examples are fully interchangeable, and it's a common nuisance I have that with class members type inference often fails. But with the syntax you use, it ought to work correctly, I agree.

**Comment by cartermp** [comment]
Definitely feels like a bug in the compiler if it works for a generic action you define yourself.

**Comment by dsyme** [comment]
It's by design. For overloaded methods, the type is propagated into lambdas if all method overloads accept a lambda.  However in this case the overloads take string and Action, and the type is not pre-inferred.  Just add the type annotation.
