### ISSUE TITLE
Invalid range when parsing generated yacc files.

### ISSUE THREAD

**Issue by brettfo** [Microsoft/visualfsharp#5976]
REPRO:
0.  (This was discovered while working on #5482 and may be dependent on that.)
1.  Set a conditional break point in the [`range` constructor](https://github.com/Microsoft/visualfsharp/blob/a7acf9f4198550f697945ba36c8321e96541eeab/src/fsharp/range.fs#L156) with the condition `el > 100000000` (end line greater than 100 million).
2.  Debug.

RESULT:
An expression from the generated `pars.fs` has an ending line of 134 million.  This eventually leads to bad PDBs being generated because a sequence point can't be properly set.

Possibly related to #4476.

**Comment by auduchinok** [comment]
@brettfo The ranges were incorrect before #4476.

**Comment by cartermp** [comment]
@brettfo Does this still reproduce now that #4476 is in?

**Comment by brettfo** [comment]
Fixed in #6383.
