### ISSUE TITLE
Cannot use attribute on inferred binding type

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#5982]
According to F# 4.1 spec, 13.1 Custom Attributes, the following attribute placement is possible
```fsharp
let foo a: [<SomeAttribute>] = a + 5
```
but it cannot be parsed with neither F# 4.1 nor F# 4.5 FCS/fsi. Specifying binding return type explicitly makes it parseable.

```
let foo: [<Attr>] = 12

  let foo: [<Attr>] = 12
  ------------------^

stdin(3,19): error FS0010: Unexpected symbol '=' in binding

let foo: [<Attr>] int = 12
val foo : int = 12
```

**Comment by majocha** [comment]
This also compile
```f#
let foo a: [<SomeAttribute>] _ = a + 5
```

**Comment by dsyme** [comment]
Yes this is by design, the spec needs clarification
