### ISSUE TITLE
Where did the .NET Framework and other F# templates go in Visual Studio > Create New Project?

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#5987]
In one of my systems, I see the following list of templates (both systems are updated to 15.9.3):

![image](https://user-images.githubusercontent.com/16015770/49593709-7dfc2800-f974-11e8-8d0e-b15800d2a069.png)

### Repro steps

Not sure how to repro. I know they disappeared sometime ago and at the time it was "by design" I believe, but then the issue was resolved and the templates were restored, renamed etc. I can see this on my laptop, but not on my workstation.

The only difference being that on the Workstation I also have a Preview edition installed that is a little behind with updating.

### Expected behavior

All templates should be there, this is how it looks on my laptop, for instance (though, .NET Core DLL is missing here...). Or at least, I would expect that after a fresh update, they magically appear again.

![image](https://user-images.githubusercontent.com/16015770/49594129-7e48f300-f975-11e8-9cf8-40780a86f2b8.png)

### Actual behavior

Some templates, mainly the so-called "legacy" templates, are gone.

### Known workarounds

I don't know if this is caused by the many installations I have had and that something went amiss along the lines. What I do know is that running Setup doesn't fix this. Maybe someone knows of a workaround, or what files I can replace from one system to another to restore this issue.

Meanwhile, the simplest way I know as a workaround is to take an existing project and copy it, rename it and then work from there.

### Related information 

VS 2017 15.9.3, on Windows 7 (where it fails) and Windows 10 (where it doesn't fail)

**Comment by cartermp** [comment]
Have you selected "F# Desktop templates" from the VS installer (individual components tab or the list of components under the .NET Desktop workload)

**Comment by abelbraaksma** [comment]
@cartermp, I basically just hit Update in the installer. I can click Modify and check if that option is enabled

**Comment by abelbraaksma** [comment]
Perhaps if that option wasn't there in earlier installers, it is cleared by default?

**Comment by abelbraaksma** [comment]
@cartermp, do you mean "F# Desktop language support"? 

I'm not sure what the difference is between "language support" and "desktop language support" (and the mouseover doesn't really give a clue), but I've selected the missing F# bit and see if that turns things around.

**Comment by cartermp** [comment]
Sorry, yes that is what I mean.

**Comment by abelbraaksma** [comment]
Apart from templates, do you know what the one installs more than the other? Previously I wasn't aware of this extra option (but that's what you get when you only hit the Update button, hoping to get all the exciting new bits automagically ;)

**Comment by cartermp** [comment]
F# desktop language support is just the older templates.

**Comment by abelbraaksma** [comment]
@cartermp, aha, I see now. Well, I ran the update and they appear properly now, thanks!

![image](https://user-images.githubusercontent.com/16015770/49601715-e3f1ab00-f986-11e8-8c23-a7a0d19fc6c2.png)

Maybe not entirely intuitive, especially since on systems that used to have such templates, apparently they disappear if you go from update to update, which may be what most users do. Though I don't know if there's a good alternative (I assume it is not preselected so that users that only want .NET Core aren't bugged by redundant templates).

**Comment by cartermp** [comment]
It is not preselected, but an update _should_ respect your previous selections. If not, I recommending filing a bug on the installer with the feedback tool in the upper-right corner of the installer. They'll want to know if a previously-selected component got unselected as a result of an update.

**Comment by abelbraaksma** [comment]
> They'll want to know if a previously-selected component got unselected as a result of an update.

My guess is that in earlier 15.x versions, this option wasn't there, but the templates were installed as part of the normal installation and that later this was split. Hence, to keep the templates, I would have had to select the new option, which clearly until today I didn't.

Most likely, my other dev system, which was installed much later, already had that option selected.

**Comment by abelbraaksma** [comment]
I'll keep an eye out to whether it will get unselected at some point, though I think this was just a "human error"  (mine ;))
