### ISSUE TITLE
How can I update an existing project to target FSharp.Core 4.5? Project Properties do no list it

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#5988]
Since Visual Studio 15.8, F# 4.5 has been around, but I fail to be able to update existing projects. 

### Repro steps

Take an existing project (like the one attached: [FSharpBug#5988.zip](https://github.com/Microsoft/visualfsharp/files/2653871/FSharpBug.5988.zip)) and attempt to target FSharp.Core 4.5. You'll see the following:

![image](https://user-images.githubusercontent.com/16015770/49595928-755a2080-f979-11e8-8fea-ae6c09135b79.png)

Other projects might even disable changing the target F# Core completely:

![image](https://user-images.githubusercontent.com/16015770/49595704-dd5c3700-f978-11e8-9c05-1c3ef7ac61f8.png)

### Expected behavior

FSharp.Core 4.5 should be selectable from the dropdown. It isn't. It doesn't seem to matter if I change to .NET Framework 4.7.1. Or perhaps I misunderstood and recent versions of FSharp.Core are no longer supported with legacy .NET Frameworks and require .NET Core?

### Actual behavior

No possibility to update.

### Known workarounds

Probably possible by doing it manually, by updating the `fsproj` files, but I haven't tried it yet. That's what I did with previous cases, I've been hit by the "greyed out" option before.

### Related information 

Attached is a solution that exhibits this behavior on my machine (VS 2017 15.9.3). I would be interested in knowing whether this is something local, or whether others can repro this behavior as well.

**Comment by cartermp** [comment]
This by design. Since FSharp.Core is a NuGet package, starting with 4.5.x we deploy via that mechanism as of VS 15.8.

See #4977

**Comment by abelbraaksma** [comment]
Thanks, I must have read that, and forgot.
