### ISSUE TITLE
Record fields cannot usefully be marked as Obsolete

### ISSUE THREAD

**Issue by SteveGilham** [Microsoft/visualfsharp#5996]
If any field of a record is marked with the `[<Obsolete>]` attribute then all uses of that type trigger the compiler warning

#### Repro steps

Run this

```
open System

type R =
  {  Wanted : String
     [<Obsolete("Use 'Wanted' instead")>]
     Unwanted : String }
  static member Create () =
    { Wanted = String.Empty
      Unwanted = String.Empty }

let UseR s =
  let r1 = R.Create()
  printfn "%A" r1
  let r2 = { R.Create() with Wanted = s }
  printfn "%A" r2
  let r3 = { R.Create() with Unwanted = s }
  printfn "%A" r3

UseR "is this wanted?"
```

#### Expected behavior

An unavoidable `warning FS0044` message ideally for line 9, though it's acceptable to be on 8 as the start of the expression; and another warning for line 16 (a deprecated use), and nothing more.

#### Actual behavior

```
      { Wanted = String.Empty
  ----^

stdin(8,5): warning FS0044: This construct is deprecated. Use 'Wanted' instead


      { Wanted = String.Empty
  ----^

stdin(8,5): warning FS0044: This construct is deprecated. Use 'Wanted' instead

    let r2 = { R.Create() with Wanted = s }
  -----------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin(14,12): warning FS0044: This construct is deprecated. Use 'Wanted' instead


    let r3 = { R.Create() with Unwanted = s }
  -----------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin(16,12): warning FS0044: This construct is deprecated. Use 'Wanted' instead


    let r3 = { R.Create() with Unwanted = s }
  -----------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

stdin(16,12): warning FS0044: This construct is deprecated. Use 'Wanted' instead
```
In each case there is one more `warning FS0044` for each source line than expected from just the textual source.

#### Known workarounds

None useful

#### Related information 

Provide any related information 

Windows 10 Home
Using the F# interactive window in Visual Studio 
```
Microsoft Visual Studio Community 2017 
Version 15.9.3
VisualStudio.15.Release/15.9.3+28307.145
Microsoft .NET Framework
Version 4.7.03056

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5
```

**Comment by cartermp** [comment]
I believe this is by design. Because a record is, conceptually, a value that is an aggregate of other values, marking one as obsolete would poison the rest. You cannot construct a "partial record" in F#. You may want to consider a Discriminated Union if you want consumers to choose between a particular case:

```fsharp
open System

type Foo =
    | [<Obsolete>] Bar of int
    | Baz of int

let b1 = Bar(12) // Obsolete warning
let b2 = Baz(12) // No warning
```

**Comment by SteveGilham** [comment]
That's very much like the old joke about the motorist lost out in the countryside asking directions and being told "I wouldn't start from here if I were you."

Given an existing record type, though, as things stand, there is no way to gently move from, say, a stringly-typed value for a particular domain item to a strongly-typed one, without either a major semantic version step, or adding a new and nigh-redundant type with inter-conversions or duplicated consumer APIs.

To take a practical example, consider the sorts of record [used by the FAKE build system to group together parameters](https://fake.build/apidocs/v5/fake-dotnet-dotnet-options.html).  In this particular case it could be something as as simple as transitioning from a `String option` to a `String seq` for the custom parameters, with the rationale of offering to automate the task of composing the items into the command line with appropriate escaping and what have you in a consistent manner.  The current behaviour denies the possibility of limiting the change by just deprecating the old field (but retaining it with a warning for backwards compatibility), and inserting a new one, and using the latter if not in its default empty state, else taking the old one as-is.

**Comment by cartermp** [comment]
I think the best recourse is to file a suggestion here: https://github.com/fsharp/fslang-suggestions

As it stands, this is by design, though the general idea of "partial records" could warrant general design thought.
