### ISSUE TITLE
Visual Studio Installer places unnecessary FSharp.Core in VS: PublicAssemblies folder

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#6014]
This causes a problem within the WPF designer.  The only real function this file adds is to add FSharp.Core.dll to the Extensions node of the Assembly Reference dialog in VS.

The correct way to reference F# is Via a nuget package.

We should remove this file.

**Comment by cmeeren** [comment]
Was this intended to be closed in #6039? (GH didn't seem to pick up on closing both issues referenced in that PR)

**Comment by cartermp** [comment]
Thanks @cmeeren, this should be closed.

**Comment by cmeeren** [comment]
Great! Is it fixed in a current release of VS, or in VS16? If a current release, must the dll be removed manually if it was installed before this fix?

**Comment by cartermp** [comment]
This should be in VS 2019 GA.

**Comment by cartermp** [comment]
You shouldn't have to remove a dll manually for VS 2019 - regular updates should take care of it.
