### ISSUE TITLE
Improve test suite runner

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#603]
I'd like to discuss how to improve the test suite runner.

My goals:
- remove dependency from perl and bat files
- make it cross platform ( both `tests/fsharp` and `tests/fsharpqa` suites should run in fsharp repo )
- use a modern test framework (nunit, xunit), runnable inside visual studio (less friction)

I have done some work in pr #90 but is rejected, so what's next?
I know is low priority, but it's really a friction for developers outside ms and is a good area for community contribution ( less work for ms team ).

There is a bit of discussion already in pr #90 and in the old [codeplex discussion](https://visualfsharp.codeplex.com/discussions/541792)

As i said in [my comment](https://github.com/Microsoft/visualfsharp/pull/90#issuecomment-133067993) i dont want the complete rewrite of the test suite, or change tests, but improve current status.

My only additional feedback:
I like to contribute with bugfix and small features, and now without rtm lockdown we can iterate a bit on bigger problems.
That mean little improvement or partial solutions, not low quality commits.
I know ms team need to allocate resource, roadmap, etc, but if we can discuss together and let community influence a bit the direction on not critical issues, is easier to improve the status of repo.

Maybe an open and scheduled chat session once in a while ( weekly? ) on gitter/slack with active contributors and a list of arguments, can help move forward the big questions, because a github issue become big very fast, and after a bit is dead, waiting a decision and but no actionable results (ci, asp.net vnext, the project system, tooling or infrastructure in general). We can wait for ms team decision when an issue has priority, but that take longer, and you lose lot of possibile help from contributors

**Comment by panesofglass** [comment]
I'm sad #90 was closed.

**Comment by panesofglass** [comment]
@enricosada do you think you could start submitting chunks of #90 as smaller, separate PRs? For example, add what's necessary to run NUnit and perhaps a placeholder test. Once that's accepted, push up some converted tests, removing the older ones so that we don't have duplicates. Thoughts?

**Comment by panesofglass** [comment]
@enricosada another possibility might be to migrate the tests in https://github.com/fsharp/fsharp and then merge that back into this repo at some later point in the future. That might at least allow those willing to help with tests some place in which to do so.

**Comment by enricosada** [comment]
the pr got accepted in master branch :fireworks: :fireworks: , fsharp test suite can be run with old runner or new runner now, just set `FSHARP_TEST_SUITE_USE_NUNIT_RUNNER` env var.

```batch
set FSHARP_TEST_SUITE_USE_NUNIT_RUNNER=1
RunTests.cmd debug fsharp "core/access,Smoke" 
```

TODO:

fsharp:

- [ ] apply feedback of #90 pr review ( thx @dsyme, @jack-pappas, @forki 
- [ ] upgrade to final nunit 3
- [ ] check tags of each test (can be done inside visualstudio) and apply nunit categoryattributes (remove the need for `fsharp/tests/test.lst` )
- [ ] xplat after merge inside fsharp repo
- [ ] create a test for each category, and replace usage of single-run inside tests with the code ot the category ( `FSI`, `FSC` ) executed previously

If someone want to help, also fsharpqa can be done like this (lot of .fs code can be reused, like exec, fsc, etc), and is a lot smaller because the test runner flow is simple

1. read `env.lst` file, compile `SOURCE` with `SCFLAGS`
2. read source files header comments, parse `//<Expects status=success></Expects>`, run and assert

nunit suite need to programmatically create tests based on a directory attribute (like fsharp new nunit runner) and call a function ( written based on `tests\fsharpqa\Source\run.pl`)

**Comment by dsyme** [comment]
@enricosada We should probably update the TODO list on this - can you post a new TODO list below with the next steps? thanks

**Comment by dsyme** [comment]
Closing as most of the test suite runner work has been done now - thanks @enricosada for driving this along at the outset

**Comment by realvictorprm** [comment]
@dsyme can we still work on removing perl dependencies?
