### ISSUE TITLE
New build has changed workflows quite a bit and somethings are slower

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#6037]
With the old repo build there were reasonable options for workflows

- build proto
- build net40
- build coreclr
- build vs
- build net40 debug etc.

These workflows were optimized towards specific tasks, "working on the desktop compiler, working on the coreclr compiler and working on ide code, with debug specializations.

The new build uses multi-targeting, and so builds usually build both desktop and coreclr compilers.  In the VS IDE it builds both net46 and netcoreapp … targets in the background.

We will need to figure out what workflows we will need moving forward, and how to achieve them.

Right now, working on the desktop compiler is now much slower, because it builds the desktop compiler + the coreclr compiler.

**Comment by cartermp** [comment]
Should be helped by #6040

**Comment by cartermp** [comment]
This is currently not fixable unless/until we move to a single TFM for the compiler.
