### ISSUE TITLE
CI-Build links on wiki page "Using CI Builds" are broken

### ISSUE THREAD

**Issue by ronaldschlenker** [Microsoft/visualfsharp#6041]
On this [this](https://github.com/Microsoft/visualfsharp/wiki/Using-CI-Builds) page, there are several links to CI build artifacts that are broken.

Broken links are the ones pointing to: "https://ci2.dot.net/job/Microsoft_visualfsharp/job/master/..."

Please update the page and repair or remove the broken links.

**Comment by cartermp** [comment]
@brettfo What should the links for this be now that we're using [public ADO](https://dnceng.visualstudio.com/public/_build?definitionId=106)?

**Comment by cartermp** [comment]
Closing this for now - I don't think there's a way to get a CI build from the ADO CI. I've updated the page to state that this is not possible.
