### ISSUE TITLE
wrong ProductVersion using AssemblyInformationalVersion, AssemblyFileVersion and AssemblyVersion attributes

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#605]
ProductVersion number should be set using the following fallback sequence (as msdn doc and c# compiler behaviour):

1. AssemblyInformationalVersionAttribute
2. AssemblyFileVersionAttribute
3. AssemblyVersionAttribute

repro: 
- create both a f# Library and c# ClassLibrary 
- set version attributes in both c# and f#

    ```fsharp
    [<assembly: AssemblyVersion("1.2.0.0")>]
    [<assembly: AssemblyFileVersion("1.3.0.0")>] 
    ```
- build and check version

![image](https://cloud.githubusercontent.com/assets/147243/9499591/7b279b8c-4c20-11e5-955a-44536fb76eb9.png)

expected `1.3.0.0`, actual `1.2.0.0`

this issue was reported by @haf in fsharp/fsharp#289.
I fixed only the warning message with Microsoft/visualfsharp#298 

This bug report got lost in the migration openrepo -> codeplex -> github.

**Comment by enricosada** [comment]
I have fix in  https://github.com/enricosada/fsharp/tree/product_version i'll try to rebase/clean it and send a pr

**Comment by KevinRansom** [comment]
Great, thanks for getting on top of this mate.

**Comment by dsyme** [comment]
@enricosada What's the status of this fix? Is it all good to go?  Thanks

**Comment by enricosada** [comment]
@dsyme yes, https://github.com/Microsoft/visualfsharp/pull/618#issuecomment-160994581 ready to review

**Comment by haf** [comment]
Sorry, but how does this fix https://github.com/fsharp/fsharp/issues/289? I can't find any reference to A-Informational-V attributes in it and my code has been throwing these sorts of warnings for years now.

**Comment by enricosada** [comment]
@haf in https://github.com/Microsoft/visualfsharp/pull/618/files#diff-d58c6e25aebd2ff64de33a050b0228ccR963

can you repro with latest compiler?

**Comment by haf** [comment]
https://github.com/Microsoft/visualfsharp/pull/618/files#diff-c1c59f2c3f2ed83115462d37e87f6635R60 is wrong I think; having a version like `1.2.3-beta` is what the informational version is for, no?

**Comment by piers7** [comment]
Why on earth would F# want to replicate the C# behavior so exactly as to replicate the unnecessary and confusing warning (which can't be disabled: https://github.com/Microsoft/visualfsharp/issues/3139 )?
