### ISSUE TITLE
Warning Message "The 'FSharpProjectPackage' did not load correctly"

### ISSUE THREAD

**Issue by ricardozimmer** [Microsoft/visualfsharp#6053]
Please provide a succinct description of the issue.

1. Update VS Community 2017 (Version 15.9.4) with Visual Fsharp Tools Version 15.9.2018.12.24.1 generates a few error messages. The error info ex: in activity log;
<entry>
    <record>675</record>
    <time>2018/12/26 12:58:06.973</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [FSharpProjectPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;FSharp.ProjectSystem.FSharp, Version=15.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)&#x000D;&#x000A;System.IO.FileLoadException: Could not load file or assembly &apos;FSharp.ProjectSystem.FSharp, Version=15.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)&#x000D;&#x000A;File name: &apos;FSharp.ProjectSystem.FSharp, Version=15.9.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; ---&gt; System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)&#x000D;&#x000A;The Zone of the assembly that failed was:&#x000D;&#x000A;MyComputer&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(String assemblyName, String typeName)&#x000D;&#x000A;   at System.AppDomain.CreateInstance(String assemblyName, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)&#x000D;&#x000A;The Zone of the assembly that failed was:&#x000D;&#x000A;MyComputer</description>
    <guid>{91A04A73-4F2C-4E7C-AD38-C1A68E7DA05C}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>

#### Actual behavior
Package does not load
#### Known workarounds
None
#### Related information 

* Operating system Windows 10
* .NET 4.7
* Community V 15.9.4
[ActivityLog.zip](https://github.com/Microsoft/visualfsharp/files/2710324/ActivityLog.zip)

**Comment by cartermp** [comment]
@ricardozimmer Does this repro without the nightly installed?

**Comment by TeaDrivenDev** [comment]
I get this on VS 15.9.4 and 15.9.5 on different machines only with 20181224.1. On the first start of VS after installation, F# projects cannot be loaded and F# files not opened. On subsequent VS restarts, the error messages persist, and while F# files can be opened again, there is no syntax highlighting whatsoever. Uninstalled, installed 20181217.1 again, which works without any problems immediately.

**Comment by cartermp** [comment]
It will have come from one of the following:

https://github.com/Microsoft/visualfsharp/pull/5841 (unlikely)
https://github.com/Microsoft/visualfsharp/pull/5985
https://github.com/Microsoft/visualfsharp/pull/6046
https://github.com/Microsoft/visualfsharp/pull/6040
https://github.com/Microsoft/visualfsharp/pull/6039 (highly unlikely)
https://github.com/Microsoft/visualfsharp/pull/6027 (highly unlikely)
https://github.com/Microsoft/visualfsharp/pull/5951 (highly unlikely)

**Comment by cartermp** [comment]
cc @KevinRansom and @brettfo any ideas?

**Comment by ricardozimmer** [comment]
@cartermp Unisntalling nightly works fine.

**Comment by irium** [comment]
I also have this issue with nighties on VS 15.9.5 Pro
Works good on stock Visual F# 15.8.20181029.1

**Comment by lessismore1** [comment]
VS Enterpris 2017 (Version 15.9.4) with Visual Fsharp Tools Version 15.9 nighlty build generates a same error message. The last nightly build that works is VisualFSharp.15.8.20181217.1.

Something happend between 15.8 and 15.9 ?

**Comment by vslynko** [comment]
I have upgraded all projects in my solution from Legacy project system to the modern one. And still have same problem. The Tag on this issue might be wrong.

**Comment by KevinRansom** [comment]
@ricardozimmer 

We have uncovered a signing issue that is impacting our build, @brettfo is working on fixing it.  Allthough it has proved particularly resistant to fixing.  Given that this error is also due to an invalidly signed assembly this may be due to the same underlying fault.

The reason we didn't catch this, is likely because we are often dogfooding unsigned previews of visual studio and in order to run those we have validation turned off.

Sorry.

**Comment by gchernis** [comment]
Looks good this AM

**Comment by gchernis** [comment]
I verified that a signed version of FSharp.ProjectSystem.FSharp.dll from \AppData\Local\Microsoft\VisualStudio\15.0_fc294f60\Extensions\<Something>\FSharp.ProjectSystem.FSharp.dll is dated today, Feb 20, 2019

**Comment by gchernis** [comment]
ProcessExplorer shows that it loads as part of opening a solution.  The per-project error is no longer there.

**Comment by cartermp** [comment]
Yes, can confirm that latest nightlies now work. I believe the recent signing changes we made into master and dev16.0 addressed this problem.
