### ISSUE TITLE
Different errors on new constraint for delegate in SRTP

### ISSUE THREAD

**Issue by Liminiens** [Microsoft/visualfsharp#6054]
#### Repro steps

1. Define this delegate in C#
`public delegate string CsharpDelegate(string a);`

2. Define this delegate in F#
`type FsharpDelegate = delegate of string -> string`

3. Define this function
```
let inline test fn =
    (^TTarget: (new: (string -> string) -> ^TTarget)(fn))
```
4. Try to use it for delegates above
```
let (func: CsharpDelegate) = test <| fun (x: string) -> ""
let (func: FsharpDelegate) = test <| fun (x: string) -> ""
```

#### Expected behavior

Error is the same (?)

#### Actual behavior

For `CsharpDelegate` the error is:

```
FS0001 The object constructor '.ctor' takes 2 argument(s) but is here given 1. The required signature is 'CsharpDelegate(object: obj, method: nativeint) : CsharpDelegate'.
```

For `FsharpDelegate` the error is:

```
FS0001 The type 'FsharpDelegate' does not support the operator '.ctor'
```

#### Related information 

* .NET Core 2.2.100

**Comment by dsyme** [comment]
I don't think the fact there are different errors here is too much of a surprise.  However in general I believe we simply do not support the use of the `new` constraint with delegate types in any case
