### ISSUE TITLE
Missing IL instruction (conv.r.un)

### ISSUE THREAD

**Issue by TIHan** [Microsoft/visualfsharp#6060]
Been digging into our IL reader and we apparently do not read this instruction:
```
conv.r.un | Convert unsigned integer to floating-point, pushing F on stack.
```
Fixing it should be straight forward as we need to add a new case to `ILInstr` called `| AI_conv_un of ILBasicType`

**Comment by dsyme** [comment]
I believe this would only be a real issue if we used this in an instrinsic in FSharp.Core.  Is there some missing or incorrect case in our intrinsics here we should be using this?

**Comment by TIHan** [comment]
It's an issue if we read method bodies from other assemblies that use it, right? I'm assuming we read method bodies so that we can do static linking and such?

**Comment by dsyme** [comment]
> It's an issue if we read method bodies from other assemblies that use it, right? I'm assuming we read method bodies so that we can do static linking and such?

Yes.  It might be that neither C# nor F# ever emit this.  I suspect that must be the case.

**Comment by dsyme** [comment]
We do handle it, here: 
```
          0x76,   AI_conv DT_R  
```
This is the table that maps back and forth.  The definitions like
```
let i_conv_u8       = 0x6e 
```
and
```
let i_conv_r_un     = 0x76 
```
are not used and can be either removed or the 0x76 changed to use the name

**Comment by dsyme** [comment]
I suspect this can be closed (but it's always great to double check! 👍  )

**Comment by TIHan** [comment]
Ah, ok it looks like we do then. Wasn't sure since I didn't see the `_un` :)
