### ISSUE TITLE
F# Not Available on Gentoo

### ISSUE THREAD

**Issue by beetleb** [Microsoft/visualfsharp#6067]
I'm sorry if this is the wrong place to report this.

The [Linux F# page](https://fsharp.org/use/linux/) implies F# is available on Gentoo. It was removed in March of 2018 and is not even in the dotnet overlay. As it stands, there is no known good way to install F# on Gentoo. That page needs to be updated.

Thanks.

**Comment by cartermp** [comment]
Closing as external.

**Comment by beetleb** [comment]
I tried editing that page (it's a Wiki), but did not have permissions, and did not know who to contact. For people viewing this issue, I'll [crosslink](https://github.com/gentoo/dotnet/issues/382) to the one on the Gentoo dotnet overlay. 

Overall, though, I hope they can put slightly better instructions for, say, people who want to build it in user directories (e.g. without sudo access). As I mentioned in the cross linked page, following Option 2 from that page gave me issues (e.g. no mention of msbuild, which does not come with mono). Updating the page to mention .NET core would be great as well.

**Comment by voronoipotato** [comment]
If you go to fsharp.org you can join the slack and that makes it very easy to talk to the team that manages those pages.

**Comment by baronfel** [comment]
Also the site itself is open source and available https://github.com/fsharp/fsfoundation, please raise an issue there to help us work through it/track the problem.
