### ISSUE TITLE
FSharMap.ComputeHashCode() throws OverflowException

### ISSUE THREAD

**Issue by jmanty** [Microsoft/visualfsharp#6068]
Hash function for  F# map ([ComputeHashCode](https://github.com/Microsoft/visualfsharp/blob/9b55eccd1bc83ed123c5ae08c577be5646861830/src/fsharp/FSharp.Core/map.fs#L555)) ends by taking the absolute value of the combined hash values of the map's contents. If the combined hash value is Int32.MinValue, getting the absolute value fails with System.OverflowException.

#### Repro steps

Run following code `hash <| Map.add 1073740877 1 Map.empty`

#### Expected behavior

A hash code is returned.

#### Actual behavior

System.OverflowException is thrown.

**Comment by syeerzy** [comment]
Hashcode could lower than zero, I don't think the abs operator is necessary.

**Comment by dsyme** [comment]
agreed
