### ISSUE TITLE
F# incorrectly handles non-exception derived exceptions

### ISSUE THREAD

**Issue by jaredpar** [Microsoft/visualfsharp#607]
Consider the following code: 

``` fsharp
let main argv = 
    try
        Console.WriteLine("hello world")
    with
        | _ -> Console.WriteLine("oops")
``` 

This code will be emitted as roughly the following:

``` csharp 
try
{
    Console.WriteLine("hello world");
}
catch (object arg_10_0)
{
    Exception Exception = (Exception)arg_10_0;
    Console.WriteLine("oops");
}
```

Notice that F# is setting the catch block type to `object` and not `Exception`.  The local if caught is always unconditionally cast to `Exception` though (irrespective of the contents of the `with` block`).  

This behavior seems incorrect.  The code spit seems to account for F# catching non-exception derived exception values.  The code spit for such a scenario is broken though as it will end up in an `InvalidCastException` being thrown.  Even though in the case where F# code explicitly catches only Exception derived exceptions F# still emits the catch block local as `object`.  

The compiler code in question appears to be [here in ILXGen.fs](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/IlxGen.fs#L2904).

**Comment by latkin** [comment]
Yes, codegen should either be changed to catch `Exception` directly, or to properly validate the type before casting from `Object` to `Exception`

**Comment by dsyme** [comment]
IIRC we came across this in preparing F# 2.0 and decided to leave it as it was. Are there any cases of languages allowing non-Exception-typed exceptions to be raised?

**Comment by dsyme** [comment]
I'll close this: I don't know of any cases where non-Exception-typed exceptions are raised by a CIL language, and without that I don't think we'd make a change here?
