### ISSUE TITLE
No autocomplete or tooltips in XAML designers in F# projects in VS 2015

### ISSUE THREAD

**Issue by NumberByColors** [Microsoft/visualfsharp#609]
Open an F# project with XAML code in VS 2013. Edit some of the XAML code and mouse-around: notice the autocomplete and tooltips.

Now try the same thing in VS 2015: no autocomplete, no tooltips. Red squiggles for malformed XAML tags still seem to work.

This change is caused by the XAML language service moving to use Roslyn Workspaces in VS 2015.

**Comment by Art** [comment]
Thanks for this issue. I'm planning to VS15, wondering what the issues are.

**Comment by ArtemyB** [comment]
So are there any solutions of this problem? I haven't found such question anywhere else, so does everybody has it?

**Comment by neolem** [comment]
@ArtemyB yes, the auto complete, intellisense on XAML files doesn't seem to be working on VS 2015.

**Comment by ArtemyB** [comment]
@neolem and what about solutions? Do you know how to fix this problem?

**Comment by wastaz** [comment]
Im using the latest VS and I have disabled resharper. Still no intellisense or anything at all in xaml files. :( 
Too bad really, I was looking forward to writing Xamarin.Forms apps in 100% F#.

**Comment by Krzysztof-Cieslak** [comment]
Was told, it's fixed in VS 2015 Update 3. If anyone can confirm it, we can close this issue.

**Comment by dsyme** [comment]
If someone could confirm that would be very useful

**Comment by kerams** [comment]
It indeed appears to work under Update 3.

**Comment by dsyme** [comment]
Wow.  What unexpected good news :) So ok, I'll close this.
