### ISSUE TITLE
Should we allow type abbreviations for anonymous records?

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#6105]
Consider the following code:

```fsharp
type R = {| IntVal: int; StringVal: string |}
let f (r: R) = r.IntVal, r.StringVal
```

This is actually _more_ typing than if I just used a regular Record type definition:

```fsharp
type R = { IntVal: int; StringVal: string }
let f (r: R) = r.IntVal, r.StringVal
```

Which is pretty weird.

**Comment by cartermp** [comment]
So this is actually useful, since if you use this combined with manipulating data with the copy-and-update syntax, you can effectively have more flexible named records:

```fsharp
type Person = {| Name: string; Age: int |}

// Person list -> {| Name: string; Age: int, NetWorth: int |} list
let createNewPeopleWithNetWorth (people: Person list) =
    people |> List.map (fun p -> {| p with NetWorth=(p.Age + 500) |})
```

Given that this can actually be useful, I'll close this out. Wild.

**Comment by majocha** [comment]
You can also do anonymous copy and update from a named record which is neat.

So giving anonymous record a name seems like a good moment to remove the pipes:
```type Person = { Name: string; Age: int }``` works, too.
Should this be enforced? I have no idea.
