### ISSUE TITLE
Better Documentation as a whole package for newcomers

### ISSUE THREAD

**Issue by jnoortheen** [Microsoft/visualfsharp#6179]
I am a newbie in F# with strong Python background, trying to do some real-world projects to get a good feel of F#. 
When I started learning F#, it wasn't a smooth experience. The reason I think are the scattered learning resources and there was no clear path to learn all the basic language constructs. 

I have tried some sites suggested in https://fsharp.org/learn.html and they are cluttered and assume that the learner is from C# ecosystem. The books are outdated(using VS and not .NET Core). Other modern languages have great documentation in its main website itself. It gears up the great learning feel. 
For example
 - [Rust](https://doc.rust-lang.org/book/)
 - [ReasonML](https://reasonml.github.io/docs/en/what-and-why)
 - [Nim](https://nim-lang.org/documentation.html)
 & even [Python](https://docs.python.org/3/)

everything in one place up-to-date and serves as a reference whenever needed during the initial phases of learning curve.

Here I really like the docs of ReasonML which clearly have organized all the topics. I think many people have felt the same and off-putting to learn F#. 
Is it possible to clearup the current documentation of the site? I will be more than happy to work on new pages and would translate from ReasonML for F#. But I am no expert in F# as I mentioned before.

**Comment by cartermp** [comment]
Thanks for the feedback! The fsharp.org site is actually the site of the F# Software Foundation, and although it's currently undergoing a redesign, it is not something we at Microsoft control or produce content for. 

Documentation on getting started with F# is available officially here: https://docs.microsoft.com/en-us/dotnet/fsharp/

Those docs are all linked to the backing GitHub repository, so if you find specific issues or have suggestions the feedback tool will create an issue for you.

**Comment by jnoortheen** [comment]
Thanks for the clarification. I am recreating the issue there.
