### ISSUE TITLE
dotnet-fsi doesn't allow the use of up-arrow or moving the cursor without --readline

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#6185]
1. Install a build of .NET Core that comes with `dotnet fsi` ([link](https://github.com/dotnet/core-sdk#installers-and-binaries))
2. Launch it
3. Attempt to move the cursor around

This fails with `dotnet fsi`. However, it works fine with `fsharpi` from Mono:

![fsharpi-move-cursor](https://user-images.githubusercontent.com/6309070/52222951-8d56ff00-2859-11e9-9fbf-15f50646bcf1.gif)

**Comment by zpodlovics** [comment]
@cartermp Please also try the dotnet fsi with --readline+

https://github.com/Microsoft/visualfsharp/issues/2407#issuecomment-416043233

**Comment by cartermp** [comment]
Thanks @zpodlovics this actually solves this problem and #6185, and lets ctrl+D work if you hit it twice (#6188).

**Comment by sasmithjr** [comment]
`--readline+` also fixes an issue where the up arrow on macOS is broken.
