### ISSUE TITLE
Triple-quoted string with empty end line breaks indentation?

### ISSUE THREAD

**Issue by amazingant** [Microsoft/visualfsharp#621]
Using Visual Studio 2015, in a new script window, the following gives compiler errors, and fails to run when sent to FSI via Alt+Enter:

```FSharp
let test =
    sprintf """
Multi-line sprintf?
%s
""" "test"
```

Adding any whitespace to the beginning of the last line fixes it, such as:

```FSharp
let test =
    sprintf """
Multi-line sprintf?
%s
 """ "test"
```

Removing indentation entirely also fixes it:

```FSharp
sprintf """
Multi-line sprintf?
%s
""" "test"
```

**Comment by dsyme** [comment]
@amazingant   THe indentation error is related to the "test" token following the triple-quoted string.  This works:

```
let test =
    sprintf """
Multi-line sprintf?
%s
"""    "test"
```

I agree it is an oddity but I'm not immediately inclined to categorize this as a bug - more of a design suggestion.

**Comment by amazingant** [comment]
Say I was pre-computing an error message for a possible outcome, and I bind the result of `sprintf`to a value temporarily. Even with your modified indentation, this still doesn't work:

```FSharp
let test =
    let f = sprintf """
Multi-line sprintf?
%s
"""    "test"
    f
```
After the line where the triple-quoted string ends, no amount of additional whitespace seems to let me bind more values in the same scope level.

**Comment by PatrickMcDonald** [comment]
@amazingant The following works for me:

```
let test =
    let f = sprintf """
Multi-line sprintf?
%s
"""          "test"
    f
```

**Comment by amazingant** [comment]
@PatrickMcDonald I suppose I should have guessed that two full indentation levels wasn't enough, I needed that ninth space to make the compiler happy. :)
