### ISSUE TITLE
Anonymous record types not working with generic reference/value type constraints

### ISSUE THREAD

**Issue by chadunit** [Microsoft/visualfsharp#6214]
Attempting to use an anonymous record type (non-struct) with a generic type having `when 'a : not struct` constraint produces `error FS0001: A generic construct requires that the type '{|R : int|}' have reference semantics, but it does not, i.e. it is a struct`.

A struct anonymous record type with `when 'a : struct` constraint produces `error FS0073 : internal error : tcrefOfAppTy (Failure) error FS0192 : internal error : tcrefOfAppTy`

Wondering if these are expected to work -- hopefully yes so they work with serializers/ORMs that happen to use the constraints -- but if not then they will probably need better error messages.

#### Repro steps

```
type Class<'a>() = class end
type RefClass<'a when 'a : not struct>() = class end
type StructClass<'a when 'a : struct>() = class end

//
// OK
//
let cAnon = Class< {| C: int |} >()

//
// error FS0001: A generic construct requires that the type '{|R : int|}'
// have reference semantics, but it does not, i.e. it is a struct
//
let rAnon = RefClass< {| R: int |} >()

//
// error FS0073 : internal error : tcrefOfAppTy (Failure)
// error FS0192 : internal error : tcrefOfAppTy
//
let sAnon = StructClass< struct {| S: int |} >() 
```

#### Related information 

Visual Studio Enterprise 2019 Preview - Version 16.0.0 Preview 2.2
Visual F# Tools 10.4 for F# 4.6 - 16.0.0.0
dotnet 2.2.200-preview-009799

**Comment by cartermp** [comment]
Thanks @chadunit, yes this is definitely a bug. Doesn't look like the constraint checking was implemented here. It's not mentioned in the [spec](https://github.com/fsharp/fslang-design/blob/master/FSharp-4.6/FS-1030-anonymous-records.md), but I'm interpreting this as an oversight because anonymous records should be _effectively_ records without names, and this is clearly supported with record types.

**Comment by TIHan** [comment]
This is bug; though I think it should be pretty easy to fix.

**Comment by cartermp** [comment]
I actually can't reproduce the struct case using dev16 bits:

![image](https://user-images.githubusercontent.com/6309070/52506471-886cb500-2ba3-11e9-9eac-0bdb86373172.png)

But the reference type constraint fails:

![image](https://user-images.githubusercontent.com/6309070/52506517-b05c1880-2ba3-11e9-80ce-faecefdc6946.png)

**Comment by TIHan** [comment]
The struct case was probably fixed when we did this: https://github.com/Microsoft/visualfsharp/pull/6078
