### ISSUE TITLE
dotnet-fsi cannot find HttpClient type despite the namespace being opened

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#6215]
Using latest build:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/6309070/52536941-bd007e00-2d15-11e9-8cd1-301ab989ed85.png">

I can reference the namespace (yay!) but the type is not loaded.

**Comment by cartermp** [comment]
Using latest build:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/6309070/52536941-bd007e00-2d15-11e9-8cd1-301ab989ed85.png">

I can reference the namespace (yay!) but the type is not loaded.

**Comment by cartermp** [comment]
Just to be clear on expectations, since this can be used in both in a .NET Core application and a .NET Standard library, it should work in FSI

**Comment by jjsullivan5196** [comment]
@cartermp I tried to replicate your issue with the 3.0 sdk on linux and did get the same result, but strangely if you manually reference System.Net.Http.dll it seems to just work. Script included

`#r "System.Net.Http.dll"
open System.Net.Http

let asyncRequest (url: string) =
  let client = new HttpClient()
  let response = client.GetAsync(url).Result
  response.Content.ReadAsStringAsync().Result

let json = asyncRequest "https://httpbin.org/anything/hello" 
printfn "%s" json
`
If you run this with dotnet fsi it just works, however, there seems to be more things missing despite this example working. For instance, I can't reference System.Uri, and seemingly valid uses of async workflows with HttpClient also don't work like this one:

`#r "System.Net.Http.dll"
open System.Net.Http

let asyncRequest (url: string) =
  async {
    let client = new HttpClient()
    let! response = client.GetAsync(url)
    let! body = response.Content.ReadAsStringAsync()
    return body
  }

let json = "https://httpbin.org/anything/hello" |> asyncRequest |> Async.RunSynchronously
printfn "%s" json
`
This throws the following type error and exits:

`httptest.fsx(7,21): error FS0001: This expression was expected to have type
    'Async<'a>'    
but here has type
    'System.Threading.Tasks.Task<HttpResponseMessage>'`

I guess I wouldn't say this is overall just resolved, but for the meanwhile there's a bit more working now.

**Comment by cartermp** [comment]
@jjsullivan5196 Thanks for more detail here, it's also good to see `#r "foo.dll"` working without too much hassle in finding the correct assembly. Perhaps there's something off about not knowing the type forwarding, since FSI knows we can open the namespace but can't bind to the right type when it evaluates the expression.

Your second example actually won't compile in normal F#. To make it work, you'll need to use `Async.AwaitTask`:

```fsharp
let asyncRequest (url: string) =
  async {
    let client = new HttpClient()
    let! response = client.GetAsync(url) |> Async.AwaitTask
    let! body = response.Content.ReadAsStringAsync() |> Async.AwaitTask
    return body
  }
```

**Comment by jjsullivan5196** [comment]
@cartermp Thanks for the clarification, guess I was looking at some outdated documentation. If I come across anything else I report back.

**Comment by KevinRansom** [comment]
````
> open System.Net.Http;;
> let client=HttpClient();;

  let client=HttpClient();;
  -----------^^^^^^^^^^^^

stdin(2,12): warning FS0760: It is recommended that objects supporting the IDisposable interface are created using the syntax 'new Type(args)', rather than 'Type(args)' or 'Type' as a function value representing the constructor, to indicate that resources may be owned by the generated value

val client : HttpClient

>
````

**Comment by baronfel** [comment]
Can we whitelist HttpClient for the disposable warning in general, since it's widely-regarded as one of the [worst things you can do](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) when using an HttpClient to new-and-dispose in rapid succession?

**Comment by KevinRansom** [comment]
@baronfel it's just telling you to use the keyword new, to remind you of your responsibility to dispose it, when you are ready to.

````
> let client=new HttpClient();;
val client : HttpClient
````
Personally, I think the reminder is poor design in all cases.  However, it is accepted as a thing.

**Comment by baronfel** [comment]
Ah yes, of course you're right. I slid right past the syntax in your example. But hurrah for the dependency working now! Great work on this so far :)
