### ISSUE TITLE
Building VF# from scratch does not work on german OS

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#6216]
![image](https://user-images.githubusercontent.com/57396/52499978-1618c680-2bdd-11e9-9fa9-c63fe51feda1.png)

I didn't build the project for a long time. Did something important change?

    build.cmd debug

**Comment by auduchinok** [comment]
@forki I think I've had something similar and `git clean -dfx` helped me.

**Comment by forki** [comment]
I did tthat before the build

**Comment by KevinRansom** [comment]
@forki , which branch?, how recent was the last commit? and what were the git clean arguments you used, and what build arguments did you use.

Thanks

Kevin

**Comment by forki** [comment]
master
git clean-xdf
build.cmd debug

**Comment by KevinRansom** [comment]
Can you attach the build logs:
- visualfsharp\artifacts\log\Debug\fsharp.proj.build.binlog
- visualfsharp\artifacts\log\Debug\fsharp.projrestore.binlog

to see if we can figure it out from there.

Thx

**Comment by forki** [comment]
I cloned from scratch after reboot.
all is well now. I guess it's as @auduchinok said - something wasn't properly cleaned. thanks guys
