### ISSUE TITLE
Regression: using System.IO.Compression from F# Interactive (missing DLL in deployed bits)

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#6220]
We have a setup bug which means that when using  `fsi.exe` (or `fsiAnuCpu.exe`) from the installed product then `System.IO.Compression` is no longer usable. (we need to double check this is a problem in dev16.0)

The problem is when running this code:
```fsharp
#r "System.IO.Compression"
open System.IO.Compression
let f (ms) = new ZipArchive(ms, ZipArchiveMode.Read)
```

For freshly built bits I get:
```
error FS0193: Could not load file or assembly 'file:///C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.IO.Compression.dll' or one of its dependencies. The system cannot find the file specified.
```

Here's the status

1. This **works** for `fsi.exe and `fsiAnyCpu.exe` in the latest VS 15.9.6 (from `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\fsi.exe`)

2. This **works** for `build vs` then running `artifacts\bin\fsiAnyCPU\Debug\net46\fsiAnyCpu.exe`  and `artifacts\bin\fsi\Debug\net46\fsi.exe`.  So basically it's our deployment of these bits that is screwed up, not the bits themselves.

3. This **fails** when I use `build vs` (thus installing VisualFSharpFull.vsix into the RoslynDev hive), and then I run the exact same `fsi.exe` or `fsiAnyCpu.exe` installed into the VS package directory 

   (you can run this directly from VS, and the directory is something like `C:\USERS\DSYME\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D5B059C1ROSLYNDEV\EXTENSIONS\MICROSOFT.VISUALFSHARPTOOLS\VISUAL F# TOOLS\42.42.42.42\`.  )

Now, it looks to me that the problem is that under `artifacts\bin\fsiAnyCPU\Debug\net46` we have som extra DLLs we are not deploying, e.g.  compare the build:
```
15/05/2018  12:29           358,536 System.Collections.Immutable.dll
05/11/2016  04:55            35,016 System.Data.Common.dll
05/11/2016  04:55           104,816 System.Data.SqlClient.dll
05/11/2016  04:55            37,256 System.Diagnostics.Process.dll
05/11/2016  04:55            27,544 System.Diagnostics.TraceSource.dll
05/11/2016  04:56           111,984 System.IO.Compression.dll
05/11/2016  04:56            22,896 System.Net.Security.dll
15/05/2018  12:29           584,848 System.Reflection.Metadata.dll
05/11/2016  04:56            28,936 System.Reflection.TypeExtensions.dll
05/11/2016  04:57            33,256 System.Runtime.InteropServices.RuntimeInformation.dll
05/11/2016  04:57            24,792 System.Security.Claims.dll
05/11/2016  04:57            39,872 System.Security.Cryptography.Algorithms.dll
05/11/2016  04:57            23,480 System.Security.Cryptography.Encoding.dll
05/11/2016  04:57            22,816 System.Security.Cryptography.Primitives.dll
05/11/2016  04:57            38,872 System.Security.Cryptography.X509Certificates.dll
10/02/2017  10:28           182,504 System.Threading.Tasks.Dataflow.dll
01/11/2018  18:14            22,240 System.Threading.Thread.dll
05/11/2016  04:57            22,256 System.Threading.ThreadPool.dll
19/07/2017  09:01            79,208 System.ValueTuple.dll
```
to the installation:
```
09/02/2019  15:04           358,536 System.Collections.Immutable.dll
09/02/2019  15:04           584,848 System.Reflection.Metadata.dll
09/02/2019  15:04            79,208 System.ValueTuple.dll
```

In short, it looks like we should now be deploying `System.IO.Compression.dll` with the product, and likely these other DLLs as well.  Sure enough copying over this DLL fixes the problem:
```
C:\GitHub\dsyme\Tensorflow_FSharp>copy C:\GitHub\dsyme\visualfsharp2\artifacts\bin\fsiAnyCPU\Debug\net46\System.IO.Compression.dll "C:\USERS\DSYME\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_D5B059C1ROSLYNDEV\EXTENSIONS\MICROSOFT.VISUALFSHARPTOOLS\VISUAL F# TOOLS\42.42.42.42\"
```
I assume this regression was caused by some version change to `System.IO.Compression.dll`, I'm not sure.

#### Repro steps

Provide the steps required to reproduce the problem

1. Step A

2. Step B

If possible attach a zip file with the repro case. This often makes it easier for others to reproduce.
The zip file should ideally represent the situation just before the call/step that is problematic.

#### Expected behavior

Provide a description of the expected behaviour.

#### Actual behavior

Provide a description of the actual behaviour observed. 

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Editing Tools (e.g. Visual Studio Version)
* Links to F# RFCs or entries on https://github.com/fsharp/fslang-suggestions
* Links to performance testing scripts
* Indications of severity

**Comment by dsyme** [comment]
re `#r "System.IO.Compression"` - 

No not the GAC - or not only - but it is a search. We still use the default resolution rules we've always used for Desktop. Based on [the code](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/MSBuildReferenceResolver.fs#L291) we do this:

1. check existing DLL references, then
2. ask MSBuild to resolve, 
   1. use an explicit "raw" filename if given, then
   2. search explicit `#I` include directories, then
   3. search the `fsi.exe` implementation directory (the `FSharp.Core` directory), then
   4. search the target framework directory, then
   5. search AssemblyFoldersEx and AssemblyFolders, then
   6. search the GAC next
   7. search the .NET Framework implementation assemblies, e.g. the `Windows\...\Framework64` directory

This has, I think, basically all been removed from .NET Core F# Interactive but I'm not 100% certain if it's all gone - certainly MSBuild is no longer called but maybe SimulatedMSBuildReferenceResolver s being used.

**Comment by dsyme** [comment]
Note that it could be this is only a setup bug on master branch. SOme things have changed in the dev16.0 branch that might mean this isn't a problem - e.g. FSI.EXE now targets .NET 4.7.2. (In master it's targeting .NET 4.6.1 but running on .NET 4.7.1.)  That could easily be enough to cause this problem.

**Comment by cartermp** [comment]
This does not appear to be an issue in dev16 Preview 3 (internal build, real stuff should be out soon)
![image](https://user-images.githubusercontent.com/6309070/52542170-fa82fc80-2d51-11e9-9f77-5546986e5a7c.png)

**Comment by dsyme** [comment]
Cool.  Could you show me a dir of `artifacts\bin\fsiAnyCPU\Debug\net46` after a `build vs debug` please?  That should show the extra DLLs the build system has decided might in theory be needed alongside `fsiAnyCpu.exe`.  We should be wary whenever these DLLs are not part of our deploy set

**Comment by cartermp** [comment]
There is no `net46` folder with dev16 - it's `net472`. But the output is this:

```
FSharp.Compiler.Interactive.Settings.dll
FSharp.Compiler.Interactive.Settings.pdb
FSharp.Compiler.Interactive.Settings.xml
FSharp.Compiler.Private.dll
FSharp.Compiler.Private.pdb
FSharp.Compiler.Private.xml
FSharp.Compiler.Server.Shared.dll
FSharp.Compiler.Server.Shared.pdb
FSharp.Compiler.Server.Shared.xml
FSharp.Core.dll
FSharp.Core.pdb
FSharp.Core.xml
Microsoft.Build.Framework.dll
Microsoft.Build.Tasks.Core.dll
Microsoft.Build.Utilities.Core.dll
Microsoft.Build.dll
Microsoft.VisualStudio.Setup.Configuration.Interop.dll
System.Collections.Immutable.dll
System.Data.SqlClient.dll
System.Reflection.Metadata.dll
System.Reflection.TypeExtensions.dll
System.Threading.Tasks.Dataflow.dll
cs
de
en
es
fr
fsiAnyCpu.exe
fsiAnyCpu.exe.config
fsiAnyCpu.pdb
fsiAnyCpu.xml
it
ja
ko
pl
pt-BR
ru
tr
zh-Hans
zh-Hant
```

**Comment by cartermp** [comment]
Closing as this is a temporary problem if you build lastest master and use that with VS 2017 15.6.x
