### ISSUE TITLE
Unspecified generic overload preferred over default optional parameter?

### ISSUE THREAD

**Issue by chadunit** [Microsoft/visualfsharp#6234]
Given two overloads of MyMethod, one with optional param and the other generic:

```fsharp
type MyClass() =
  member this.MyMethod(s:string, [<Optional; DefaultParameterValue(true)>] b:bool) = printfn "non-generic called"
  member this.MyMethod<'a>(s:string) = printfn "generic called"

MyClass().MyMethod("") // prints "generic called"
```

When calling without specifying either the type or the optional param, it appears that the generic method gets called, with the type parameter apparently defaulted to System.Object.

Same thing when calling from F# into an equivalent C# class. 

However, C# itself calls the non-generic method:

```csharp
public class MyClass
{
  public void MyMethod(string s, bool b = true) { Console.WriteLine("non-generic called"); }
  public void MyMethod<T>(string s) { Console.WriteLine("generic called"); }
}

new MyClass().MyMethod(""); // prints "non-generic called"
```

Is this expected for F# to prefer a generic call when no generic type parameter was provided (in contrast to C#)? 

Any way to make it to prefer the non-generic? ~I found [RequiresExplicitTypeArgumentsAttribute](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/core.requiresexplicittypeargumentsattribute-class-%5bfsharp%5d) which looks like it would fit the bill but appears to be F# specific~ (edit: actually this attribute doesn't help the compiler choose the other method, it still chooses the generic method and just adds a compiler error), anything to help with the C# interop scenario? 

(This issue arose in the [Chain ORM](https://github.com/docevaad/Chain/issues/262) where the author agreed to provide some F#-friendly overloads to get around C# implicit conversions, only to run into this instead.)

#### Related information 

VS 2017 15.9.6
Visual F# Tools nightly 15.8.20181217.1
FSharp.Core 4.5.2
dotnet 2.2.200-preview-009799

**Comment by cartermp** [comment]
I can't speak towards this being expected or not (I suspect it is due to a general tendency to pick a more generic option in F#), but given that changing this would be a breaking change, I doubt we'd adjust it.

**Comment by Grauenwolf** [comment]
Would it be possible to move RequiresExplicitTypeArgumentsAttribute into .NET Standard? 

That would support interoperability without having to drag along the whole F# runtime.

**Comment by Grauenwolf** [comment]
> given that changing this would be a breaking change, I doubt we'd adjust it.

Understandable, but it wouldn't hurt to verify that this isn't a new behavior. It wouldn't be the first time a breaking change was accidentally introduced in a .NET compiler.

**Comment by Grauenwolf** [comment]
Quick question. If I created a new internal class named RequiresExplicitTypeArgumentsAttribute in my library, would the F# compiler honor it?

**Comment by chadunit** [comment]
I just tried `RequiresExplicitTypeArguments` in a test project and it doesn't actually do what I expected. The compiler still chooses the generic method and produces `error FS0685: The generic function 'MyMethod' must be given explicit type argument(s)`.

**Comment by Grauenwolf** [comment]
Well that sucks. This is turning out to be trickier than I expected.

**Comment by cartermp** [comment]
This is the behavior at least as of F# 4.1 (when support for `DefaultParameterValue` was added):

```                                                                                                                                                                                     
Microsoft (R) F# Interactive version 4.1
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> open System
- open System.Runtime.InteropServices;;
>
- type MyClass() =
-   member this.MyMethod(s:string, o:obj, [<Optional; DefaultParameterValue(null:obj)>] o2:obj) =
-     printfn "non-generic called"
-   member this.MyMethod<'a when 'a : not struct>(s:string, o:obj) =
-     printfn "generic called";;
type MyClass =
  class
    new : unit -> MyClass
    member MyMethod : s:string * o:obj -> unit
    member MyMethod : s:string * o:obj * o2:obj -> unit
  end

> MyClass().MyMethod("", Object());;
generic called
val it : unit = ()

>
```

In general, overload resolution in F# and C# are not identical ([a few issues here to demonstrate](https://github.com/Microsoft/visualfsharp/issues?q=is%3Aissue+label%3A%22Resolution-By+Design%22+is%3Aclosed+overload)), and I doubt anything would be done about this given that it's existed at least since F# 4.1 (and perhaps even since F# 4.0).

**Comment by chadunit** [comment]
Out of curiosity I believe this is the relevant definition in the [spec](https://fsharp.org/specs/language-spec/) if I'm reading it correctly (it's complex!):

> * 14\.4 Method Application Resolution
>   * 7\. Choose a unique M possible according to the following rules:
>     * If a unique applicable M possible exists, choose that method. Otherwise, choose the unique best M possible by applying the following criteria, in order:
>     ...
>     **4\) Prefer candidates that do not have ImplicitlySuppliedFormalArgs .**
>     ...
>     8\) Prefer candidates that are not generic over candidates that are generic—that is, prefer candidates that have empty ActualArgTypes .

If multiple candidates make it to (8) then non-generic is preferred, but the optional overload already got rejected earlier at (4).

Given the historical issues I wonder if this is worth a mention in the [component design guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/component-design-guidelines)? There are notes in there to use overloads to play nice with .NET and it might be a good idea to caveat that with possible resolution discrepancies.

Also, does there exist (or has there been any consideration for) a "reverse" document -- guidance on how to make a C# library F#-friendly?

**Comment by cartermp** [comment]
I think documenting in the CDG makes sense, yes.
