### ISSUE TITLE
No symbol uses for enclosing types

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#6240]
Consider nested types:
```csharp
public class A
{
  public class B
  {
    public static void M() { }
  }
}
```

When a nested type is used in F#, name resolution doesn't notify about its enclosing type use, so the type isn't available in features like Find Usages.
```fsharp
let b = A.B()
A.B.M()
```

**Comment by auduchinok** [comment]
Ah, it seems to be fixed in #5297. I'll check.

**Comment by cartermp** [comment]
@auduchinok have you had a chance to check?

**Comment by auduchinok** [comment]
@cartermp Sorry, not yet. I'll check it soon when migrating our plugin to FCS from master or dev16.0.

**Comment by auduchinok** [comment]
@cartermp I can confirm it's fixed in `dev16.1` branch.
