### ISSUE TITLE
Type inference issue in point-free function composition

### ISSUE THREAD

**Issue by eiriktsarpalis** [Microsoft/visualfsharp#625]
I came across the following issue when writing this snippet:
```fsharp
open System
open System.Threading
open System.Threading.Tasks

type Async with

    static member RunSynchronously2(workflow : Async<'T>, ?timeout : int, ?cancellationToken : CancellationToken) =
        let tcs = new TaskCompletionSource<'T>()
        match timeout with
        | Some 0 -> raise <| new TimeoutException()
        | Some t when t < 0 -> invalidArg "timeout" "must be positive."
        | Some t -> let timer = new Timer((fun _ -> ignore <| tcs.TrySetException(new TimeoutException())), null, t, Timeout.Infinite) in ()
        | None -> ()

        let start _ = Async.StartWithContinuations(workflow, 
                                                    ignore << tcs.TrySetResult,
                                                    ignore << tcs.TrySetException,
                                                    ignore << tcs.TrySetCanceled << ignore,
                                                    ?cancellationToken = cancellationToken)

        if not <| ThreadPool.QueueUserWorkItem(new WaitCallback(start)) then invalidOp "Could not queue to thread pool." 
        try tcs.Task.Result 
        with :? AggregateException as e when e.InnerExceptions.Count = 1 -> raise e.InnerExceptions.[0]
```
Type checking this piece of code produces the following error message:
```
test.fsx(18,85): error FS0001: Type mismatch. Expecting a
    OperationCanceledException -> CancellationToken    
but given a
    OperationCanceledException -> unit    
The type 'CancellationToken' does not match the type 'unit'
```
The offending line is
```fsharp
ignore << tcs.TrySetCanceled << ignore,
```
which if replaced with an explicit lambda declaration
```fsharp
(fun _ -> ignore <| tcs.TrySetCanceled()),
```
will make the error message go away.

A few observations:
* This is reproducible in both F# 3.1 and F# 4.0.
* Intellisense does not produce any error messages.
* The erroneously inferred `CancellationToken` return type does not appear anywhere in the offending lambda, but it does occur as a follow-up optional argument. Removing the optional argument will not make the error go away.

**Comment by dsyme** [comment]
The lack of error message from intellisense is curious and is a bug.

The inference question itself appears related to the resolution of tcs.TrySetCanceled as a first-class method use and whether the input argument type is known to be of type unit or not.  We'd need a smaller repro of that (that said I suspect it would be resolved as by-design rather than making a change to inference)

**Comment by eiriktsarpalis** [comment]
@dsyme Here's a minimal reproduction
```fsharp
type Foo =
    static member A() = true
    static member A(x:int) = false // comment out method overload to fix error

type Bar =
    static member Test(f : int -> unit) = ()

Bar.Test(ignore << Foo.A << ignore) // fails type check
Bar.Test(ignore >> Foo.A >> ignore) // passes type check
```
Curiously, intellisense will produce the error in this minimal counterexample.

**Comment by eiriktsarpalis** [comment]
Ok, so things are starting to become weird. Here's the absolute minimal counterexample I could create:
```fsharp
let test (f : int -> unit) = ()

let tcs = new System.Threading.Tasks.TaskCompletionSource<int>()
test (ignore << tcs.TrySetCanceled << ignore) // type error
test (ignore >> tcs.TrySetCanceled >> ignore) // ok
```
I could not reproduce the problem with any type other than TaskCompletionSource. Intellisense indicates that `TaskCompletionSource.TrySetCanceled` does not come with a method overload, which could have been the root cause of this issue. However when looking up the documentation at msdn I discovered [this](https://msdn.microsoft.com/en-us/library/dn823326(v=vs.110).aspx).

So clearly there does exist a method overload. However, when I try to do the following:
```fsharp
let tcs = new System.Threading.Tasks.TaskCompletionSource<int>()

tcs.TrySetCanceled(new System.Threading.CancellationToken())
```
Intellisense complains with error message
```
Error		The member or object constructor 'TrySetCanceled' takes 0 argument(s) but is here given 1. The required signature is 'System.Threading.Tasks.TaskCompletionSource.TrySetCanceled() : bool'.
```
but the F# compiler works fine. I'm not entirely sure what is at fault here.

**Comment by eiriktsarpalis** [comment]
Ultimately this seems to be some kind of tooling failure, since compilation also fails in C# code:
```csharp
        public static void Test()
        {
            var tcs = new System.Threading.Tasks.TaskCompletionSource<int>();
            return tcs.TrySetCanceled(new System.Threading.CancellationToken());
        }
```
with error
```
Error	CS1501	No overload for method 'TrySetCanceled' takes 1 arguments	ClassLibrary1	C:\Users\eirik\Documents\Visual Studio 2015\Projects\ClassLibrary1\Class1.cs	14
```

**Comment by latkin** [comment]
I don't think there is any issue here.  What version of .NET are you targeting?

If your project targets .NET 4.5.2 or earlier, the `TrySetCanceled(CancellationToken)` overload does not exist (well, it's internal), so type inference encounters no ambiguities and everything works. Intellisense shows 1 overload (correct) and no squiggles (correct), compiler issues no error (correct).

If your project targets .NET 4.6, the new overload exists. Moving left to right, type inference picks the new 1-arg overload over the 0-arg overload (per spec), which causes the final `<< ignore` to mismatch. Both overloads are shown in intellisense (correct), squiggles appear (correct), and the compiler issues an error (correct).

![image](https://cloud.githubusercontent.com/assets/5943573/9771600/1a425768-56ec-11e5-9925-69855276d350.png)
![image](https://cloud.githubusercontent.com/assets/5943573/9771613/322df97c-56ec-11e5-8ea1-323b23ef5816.png)

**Comment by latkin** [comment]
This could definitely be very confusing if there was a mismatch between the .NET version targeted by the editor/project, and perhaps the .NET version targeted by FSI (if that's how you were testing) or quickie command-line FSC tests.

**Comment by eiriktsarpalis** [comment]
Interesting, I was in fact primarily using VS 2013 in a machine that does have VS 2015 installed. So it seems like the confusion arises from the fact that FSI always runs on top of net46. I just tested on a machine without VS 2015 and the problem does not appear.

Closing this since it's a non-issue, but it might be worth discussing the possibility of specifying target frameworks in future releases of FSI.

**Comment by latkin** [comment]
@eiriktsarpalis There could definitely be better tooling for specifying this.  Strictly speaking you can control it today, by setting framework references explicitly in the initial command line. Of course that's nonobvious and not user friendly, but in a pinch it works:

![image](https://cloud.githubusercontent.com/assets/5943573/9775303/facaba08-5702-11e5-8643-cb8df023a9b9.png)

The set of default references you get in an FSI session does not include specific version numbers, so I guess it resolves to the highest compatible version by default.

**Comment by eiriktsarpalis** [comment]
:+1:

**Comment by eiriktsarpalis** [comment]
@latkin Incidentally, I noticed that VS2015 intellisense in .fsx files always targets net45 and there doesn't seem to be a way to change this. Clearly, it should be net46 by default?

**Comment by latkin** [comment]
Probably another weird interaction with how the language service finds dependencies. Could definitely be some edge cases there.
