### ISSUE TITLE
Multiple #load directives with scripts cause UI delays

### ISSUE THREAD

**Issue by cartermp** [microsoft/visualfsharp#6250]
Thanks to @kevmal for the repro as per our discussion in the FSSF slack during office hour.

Repro project: https://github.com/kevmal/vs2019slow

Steps:

1. Got to Script.fsx
2. Type some code

See this (from @kevmal)
![image](https://user-images.githubusercontent.com/6309070/53041488-fe410e00-3438-11e9-8883-10312f3c8dfe.png)

**Comment by cartermp** [comment]
@TIHan and I could not reproduce UI delays on his machine with Preview 4 bits. @kevmal, we'll let you know when Preview 4 ships and we'll see if this still happens. The diff between Preview 3 and Preview 4 does contain some additional performance work, so hopefully that addresses it.

**Comment by kevmal** [comment]
Noticing the same issues with Preview 4 just with my day-to-day use. I updated the repro to hopefully make the lag more obvious. I can load the solution in 2017, continuously type and have zero lag. With 2019 and steady typing it constantly freezes. The repro still doesn't seem as bad as my general experience, I just can't even use 2019.

![2019slow](https://user-images.githubusercontent.com/7281367/53581506-ebb28d00-3b3a-11e9-8150-72587a359a6f.gif)

**Comment by cartermp** [comment]
@heejaechang FYI - I believe we turned on F# scripts for the F# Misc Files workspace starting with Preview 3; I can reproduce on Preview 4/RC. I can get a trace to see what's going on here, I suspect things are getting re-evaluated on each keystroke.

**Comment by cartermp** [comment]
I also managed to get VS to deadlock when invoking rename in a script, but I can't reproduce that. Not sure if it's related.

**Comment by cartermp** [comment]
Tracking this as a regression that we should attempt to service for 16.0. F# scripts are now using @heejaechang's work here: https://github.com/dotnet/roslyn/pull/31134

So it's unclear if the regression lies in our side or on the Roslyn side of things.

@jinujoseph @Pilchie for FYI

**Comment by heejaechang** [comment]
@cartermp trace will be best way to figure out what is going on? regardless whether F#'s script now uses Roslyn MiscWorkspace or not, we need to figure out what feature is causing the wait dialog box.

**Comment by dsyme** [comment]
One thing to consider: start by checking how often `ComputeSingleFileOptions` in FSharp.Editor.dll is being called and doing its work, and checking whether it is returning options with a new Stamp each time.

**Comment by dsyme** [comment]
The new stamp gets set here: https://github.com/Microsoft/visualfsharp/blob/master/vsintegration/src/FSharp.Editor/LanguageService/ProjectSitesAndFiles.fs#L298

If a new set of options with a new stamp is getting created on each call then that's a problem.

Viewing the trace from the background reactor should reveal a lot - run `devenv.exe` under debugger and see the `Output` window.

    devenv.exe /debugexe devenv.exe /RootSuffix RoslynDev

**Comment by dsyme** [comment]
Oh the code will have changed in dev16

**Comment by dsyme** [comment]
In the new code, it certainly looks like as as soon as a file stamp changes the whole project options are nuked and a new project options created with a new stamp

This will mean the whole underlying builder is re-created on each file edit, 

 
 
 
 https://github.com/Microsoft/visualfsharp/blob/dev16.0/vsintegration/src/FSharp.Editor/LanguageService/FSharpProjectOptionsManager.fs#L157

This definitely looks wrong. 

Separately I'm skeptical about the use of an agent in this code - a simple lock should normally suffice to protect mutable state 
 https://github.com/Microsoft/visualfsharp/blob/dev16.0/vsintegration/src/FSharp.Editor/LanguageService/FSharpProjectOptionsManager.fs#L252

**Comment by cartermp** [comment]
@heejaechang Looks like this one will be on us based on @dsyme's findings, we'll let you know if there's an issue after this gets resolved on the F# side of things.

**Comment by TIHan** [comment]
@dsyme, we should probably be using a lock instead of an agent. I think the reason I chose an agent is simply because I didn't feel comfortable using a lock; not a great reason I know. It should be very easy to switch over though.

**Comment by dsyme** [comment]
> @dsyme, we should probably be using a lock instead of an agent. I think the reason I chose an agent is simply because I didn't feel comfortable using a lock; not a great reason I know. It should be very easy to switch over though.

Yup understood.  It only matters because getting the options is so frequent and the thread switch which normally happens with agents may be a cost we don't want.

**Comment by kevmal** [comment]
Definitely better but I still can't use 2019 where 2017 is fine. Not sure if this helps but with `devenv.exe /debugexe devenv.exe /RootSuffix RoslynDev` here's what I get (cleared the output window and reproduced lag within ~5 seconds)

[2019 dbg output.txt](https://github.com/microsoft/visualfsharp/files/3158638/2019.dbg.output.txt)

Around line ~286 of the output it completely stops and makes me wait. 

```
devenv.exe Information: 0 : Reactor: 39,728.190 BAD-OP: > 1s <-- SignatureHelpProvider.ParseAndCheckFileInProject, took 2229.0885 ms
devenv.exe Information: 0 : Reactor: 39,728.190 pausing 10 milliseconds
devenv.exe Information: 0 : Reactor: 39,728.191 pausing 10 milliseconds
devenv.exe Information: 0 : Reactor: 39,728.191 --> Unknown.GetProjectOptionsFromScript (E:\profile\Projects\bleh\Fury.Core\Fury.FSI\stochvol2.fsx), remaining 0
devenv.exe Information: 0 : FCS: SignatureHelpProvider.parseFile (E:\profile\Projects\bleh\Fury.Core\Fury.FSI\stochvol2.fsx)
devenv.exe Information: 0 : Reactor: 39,728.213 enqueue SignatureHelpProvider.CheckOneFile.Fragment (E:\profile\Projects\bleh\Fury.Core\Fury.FSI\stochvol2.fsx), length 0
```
from there this cycle more or less repeats

```
Exception thrown at 0x7780C762 (KernelBase.dll) in devenv.exe: 0xE0434352 (parameters: 0x8013153B, 0x00000000, 0x00000000, 0x00000000, 0x74830000).
devenv.exe Information: 0 : Reactor: 39,729.022 <-- Unknown.GetProjectOptionsFromScript, took 142.9207 ms
devenv.exe Information: 0 : Reactor: 39,729.023 pausing 10 milliseconds
devenv.exe Information: 0 : Reactor: 39,729.023 enqueue Unknown.GetProjectOptionsFromScript (E:\profile\Projects\bleh\Fury.Core\Fury.FSI\stochvol2.fsx), length 0
devenv.exe Information: 0 : Reactor: 39,729.024 --> Unknown.GetProjectOptionsFromScript (E:\profile\Projects\bleh\Fury.Core\Fury.FSI\stochvol2.fsx), remaining 0
```

up till things get a bit better around line 376 starting with a bunch of 
```
Exception thrown at 0x7780C762 (KernelBase.dll) in devenv.exe: 0xE0434352 (parameters: 0x8013153B, 0x00000000, 0x00000000, 0x00000000, 0x74830000).
```

**Comment by kevmal** [comment]
@cartermp The original repro seems to still stand (VS 16.0.3). 

Just typing quickly `let f a b = a + b` and enter it freezed. 
From debug output:

```
devenv.exe Information: 0 : Reactor: 36,419.874 <-- DocumentDiagnosticAnalyzer.CheckFileInProject, took 4.2767 ms
devenv.exe Information: 0 : Reactor: 36,419.874 pausing 10 milliseconds
devenv.exe Information: 0 : FCS: DocumentDiagnosticAnalyzer.CheckFileInProject.CacheMiss (E:\profile\Projects\bleh\vs2019slow\vs2019slow\vs2019slow\Script.fsx)
devenv.exe Information: 0 : Reactor: 36,419.875 enqueue DocumentDiagnosticAnalyzer.CheckFileInProject (E:\profile\Projects\bleh\vs2019slow\vs2019slow\vs2019slow\Script.fsx), length 0
devenv.exe Information: 0 : Reactor: 36,419.875 --> DocumentDiagnosticAnalyzer.CheckFileInProject (E:\profile\Projects\bleh\vs2019slow\vs2019slow\vs2019slow\Script.fsx), remaining 0
Exception thrown at 0x7780C762 (KernelBase.dll) in devenv.exe: 0xE0434352 (parameters: 0x8013153B, 0x00000000, 0x00000000, 0x00000000, 0x74830000).
Exception thrown at 0x7780C762 (KernelBase.dll) in devenv.exe: 0xE0434352 (parameters: 0x8013153B, 0x00000000, 0x00000000, 0x00000000, 0x74830000).
devenv.exe Information: 0 : Reactor: 36,419.885 enqueue Unknown.GetProjectOptionsFromScript (E:\profile\Projects\bleh\vs2019slow\vs2019slow\vs2019slow\Script.fsx), length 0
```
All I see is the please wait message and then finally
```
The thread 0xdfe4 has exited with code 0 (0x0).
The thread 0x9768 has exited with code 0 (0x0).
The thread 0x3970 has exited with code 0 (0x0).
devenv.exe Information: 0 : Reactor: 36,436.947 BAD-OP: >10s <-- DocumentDiagnosticAnalyzer.CheckFileInProject, took 17071.7833 ms
````

Adding new lines to the source is when it gets particularly bad.

**Comment by cartermp** [comment]
Re-opening. @TIHan can you take a look?

**Comment by TIHan** [comment]
Looking at it now; the 1.7seconds for a check on that is incredibly long. Thank you @kevmal for the diagnostic reports.

**Comment by TIHan** [comment]
I figured how to make the behavior better. The cancellation didn't get thrown before it tried to parse the load closures.
