### ISSUE TITLE
[Docs] Add example of DefaultParameterValue accepting the 'default' value of a valuetype

### ISSUE THREAD

**Issue by NinoFloris** [Microsoft/visualfsharp#6251]
@cartermp had to look it up in the issue again today https://github.com/Microsoft/visualfsharp/pull/1812, for creating an API with a default CancellationToken parameter. 

I keep forgetting you can use a `new` expression inside the `DefaultParameterValue` constructor. Unchecked.defaultof feels very natural to me, but doesn't work (yet), until that time can we add an example to the docs for a default valuetype value?

https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/parameters-and-arguments#optional-parameters

**Comment by cartermp** [comment]
@NinoFloris just to clarify, are you looking for an example like this?

```fsharp
open System.Threading
open System.Runtime.InteropServices
type C = 
    static member Foo([<Optional; DefaultParameterValue(CancellationToken())>] ct: CancellationToken) =
        printfn "%A" ct
```

**Comment by NinoFloris** [comment]
Yes exactly that ❤️

**Comment by cartermp** [comment]
Gotcha, PR out here: https://github.com/dotnet/docs/pull/10586

I'll close this issue - we can figure out if there's a better way to word this on the docs PR.

**Comment by NinoFloris** [comment]
Now that I see the docs process, it would probably help if I submit that PR myself next time. Seems like no extra work at all. Thanks anyway for now :)
