### ISSUE TITLE
Extension methods named Run can cause computation expressions to fail to compile

### ISSUE THREAD

**Issue by mattstermiller** [Microsoft/visualfsharp#6268]
Defining an extension method with the `[<Extension>]` attribute named Run that has one generic parameter or a tupled parameter where the first is generic with a constraint will cause computation expressions to fail compilation with various errors as though the computation expression builder's definition of Run ceased to exist.

There is no problem if the Run extension's parameter is not generic or if it is generic with no constraints.

It is unknown if other Builder method names are affected, although Combine and Delay seem to be unaffected.

#### Repro steps

Consider the following code:
```open System.Runtime.CompilerServices

type MyClass() =
    member val Prop = 0

[<Extension>]
type CompletelyUnrelatedExtensions =
    // these are fine
    [<Extension>] static member Run (x: int, y) = x + y
    [<Extension>] static member Run (x: MyClass, y) = x
    [<Extension>] static member Run (x: int) = x
    
    // produces error "None of the types 'AsyncBuilder, Async<'a>' support the operator '+'"
    //[<Extension>] static member Run (x, y) = x + y
    
    // produces error "The type 'AsyncBuilder' is not compatible with the type 'MyClass'."
    //[<Extension>] static member Run (x: #MyClass, y) = x
    
    // produces error "The member or object constructor 'Run' takes 0 argument(s) but is here given 1."
    //[<Extension>] static member Run (x) = x
    
let f () = async {
    do! Async.Sleep 100
    ()
}
f () |> Async.RunSynchronously
```

If any of the commented extensions are uncommented, the compiler will throw errors at the `async { ... }` computation expression. Note that the presence of the first three extensions does not affect the outcome in any way.

For convenience, this code sample has been shared on Repl.it where it can be run: https://repl.it/repls/LoyalRawVoxel.

#### Expected behavior

Extension methods named Run that are not type-compatible with a computation expression should not affect the compilation of the computation expression.

#### Actual behavior

Unrelated extension methods named Run cause code that worked flawlessly before to suddenly stop compiling.

#### Known workarounds

* Don't include the interfering extension methods in the scope of the affected computation expression
* Rename the extension method
* Change the type of the first parameter on the extension method to be non-generic
* Change the extension method to use curried parameters

#### Related information 

None.

**Comment by dsyme** [comment]
> Extension methods named Run that are not type-compatible with a computation expression should not affect the compilation of the computation expression.

My understanding is that this is expected behavior - the presence of a "Run" method matters to the syntactic desugaring of computation expressions

**Comment by dsyme** [comment]
From 6.3.10 of the F# 4.1 spec: 
```
If the inferred type of b has one or more of the Run, Delay, or Quote methods when builder-expr is
checked, the translation involves those methods. For example, when all three methods exist, the
same expression translates to:
68
let b = builder-expr in b.Run (<@ b.Delay(fun () -> {| cexpr |}C) >@)
```

Does that make sense?

**Comment by mattstermiller** [comment]
@dsyme The spec makes sense, the behavior I am observing does not. I worded the desired behavior poorly. Let me put it this way:

Extension methods named Run that are not type-compatible with a computation expression should not prevent the compiler from selecting the type-compatible Run method(s) on the computation builder itself.

Just the fact that importing a namespace with an unrelated extension method named Run can cause all computation expressions to no longer compile makes no sense at all.

**Comment by dsyme** [comment]
Well, extension methods can interfere with type inference, especially ones as generic as above.  So although it is not intuitive it is per spec.
