### ISSUE TITLE
Cannot use VisualFSharp.sln with Preview 4 bits

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#6269]
"Error occurred while restoring NuGet packages: The operation failed as details for project FSharp.Core could not be loaded."

![image](https://user-images.githubusercontent.com/6309070/53207753-7817f980-35e9-11e9-9252-10517e20ff58.png)

![image](https://user-images.githubusercontent.com/6309070/53207772-8108cb00-35e9-11e9-9509-8bc37b5e8d18.png)

The F# language service does not appear to be kicked off; all files are plaintext.

**Comment by cartermp** [comment]
Can't reproduce this on @KevinRansom's machine. ¯\_(ツ)_/¯

**Comment by cartermp** [comment]
Can't reproduce on my machine anymore. Ergh

**Comment by abelbraaksma** [comment]
@cartermp I've seen this once when I noticed that the native cache wasn't fully build yet, which can take hours with big updates. It shouldn't matter (Fusion should just resolve to unjitted assemblies and then JIT on demand should kick in), but it could explain why it once reproed and then not anymore.
