### ISSUE TITLE
[VS 2015] FSI process targeting net46 but fsx intellisense targeting net45

### ISSUE THREAD

**Issue by eiriktsarpalis** [Microsoft/visualfsharp#627]
The discrepancy is evident when running the following snippet from any fsx file within VS2015:
```fsharp
let tcs = new System.Threading.Tasks.TaskCompletionSource<int>()
tcs.TrySetCanceled(new System.Threading.CancellationToken())
```
This behavior does not happen in F# projects that have been set to target net46. 

If anything, intellisense in script files should be forced to target net46. A nice improvement to the tooling would be to make it possible to specify a common target framework for fsi/fsx intellisense from the configuration panel.

(see also #625)

**Comment by dsyme** [comment]
This is definitely a discrepancy in intellisense v. FSI.EXE that should be fixed.

**Comment by ImaginaryDevelopment** [comment]
How can we tell, or how is it determined what FSharpCore, what .net framework, and any other important criteria for diagnosing issues in .fsx files and f# interactive are contributing to a bug? I have a decent amount of code that works wonderfully via FSI but the intellisense and autocompletetion is very erratic on functioning. I would like to think the project a .fsx lives in has no effect on the editor, nor the fsi.
