### ISSUE TITLE
Is the FCS Dependency on System.Data.SqlClient intended?

### ISSUE THREAD

**Issue by baronfel** [Microsoft/visualfsharp#6273]
@nojaf on the Foundation Slack noted that between versions 25 and 26 of FCS a new nuget dependency on System.Data.SqlClient appeared. From what we can see, the reason was to include the System.Data dll in the set of default references for FSI, is this the core reasoning? There's some worry about Fable and other FCS consumers now requiring the System.Data.SqlClient dependency and if that might be untenable for them, so I wanted to ask the question and at least get an answer on record.

It looks like it was introduced as part of #5923, if that helps narrow it down.

**Comment by dsyme** [comment]
No it's not particularly intended.  I don't really know where it came from to be honest.  I don't think it's the default references

https://github.com/Microsoft/visualfsharp/pull/5923/files#diff-a2fc4429830a9bc94312ff5d413e3f1aR644

**Comment by cartermp** [comment]
@dsyme It is the default references for non-.NET Framework. But if it's not a part of the shared framework then it shouldn't be included.

We need to re-evaluate this default set, see #6215

**Comment by baronfel** [comment]
I just ran a quick test using `fsharpi` on mono 5.18, and `open System.Data.SqlClient;;` works out of the box there. This suggests to me that the dll is already included in the reference set on .Net Framework, and also should be included in the default set on .Net Core, so that scripts are more portable.

**Comment by cartermp** [comment]
Gotcha, though things are also a bit different for framework. Given that the package is for working with Windows, perhaps it doesn't make sense to include for .NET Core/.NET Standard.

**Comment by dsyme** [comment]
> @dsyme It is the default references for non-.NET Framework. But if it's not a part of the shared framework then it shouldn't be included.

I don't know why that would mean it gets included as a dependency of the compiler bits.  The default references for scripting aren't read from the _compilation_ directory, they are read from wherever we read the framework/reference assemblies from.

So we should just remove this dependency, it is not needed for the compiler bits.

**Comment by dsyme** [comment]
@baronfel My understanding is that you can just remove this as a dependency of the compiler bits in the FCS repository.

**Comment by KevinRansom** [comment]
If I remember correctly, it was added to get some tests that pass on desktop, to also pass on coreclr, that may not not be what we actually want, so I shall take a look.

I doubt if just removing the reference will work in the FCS repo because of:  
https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/CompileOps.fs#L1857

I will take a look and see what is actually broken without this.  We may want it to not work anyway.

**Comment by dsyme** [comment]
Oh I see, yes, well, that line was added by me I think - it was nothing particularly thought out, and certainly wasn't intended to added a hard dependency for the compiler bits.

**Comment by KevinRansom** [comment]
Blame blames me ....  lol.

It was I think in the middle of a huge batch of let's get stuff working.  So I think it makes sense to actually analyze what's broken, and see what we intend to happen, and how best to resolve the issue.

As it is, it certainly doesn't crash on Linus, but our bar for that may be higher.  Anyway, I have a PR to see what breaks.

https://github.com/Microsoft/visualfsharp/pull/6274

**Comment by cartermp** [comment]
@dsyme this is where we get the default set of references for FSI though - so if we need this, it's needed in the compiler unless we can factor it out. Or am I misunderstanding something?

**Comment by cartermp** [comment]
Removed in #6274 - tests pass without it. We should think a bit more about what else to include separately.

**Comment by KevinRansom** [comment]
@baronfel thanks for noticing and following up on this.

Good eyes :-)
