### ISSUE TITLE
All documentation for Core Library is missing

### ISSUE THREAD

**Issue by voronoipotato** [Microsoft/visualfsharp#6287]
I guess this is our life now. Gonna start printing out docs on paper in case of emergency. 

#### Repro steps

1. navigate to https://docs.microsoft.com/en-us/dotnet/fsharp/

2. Click "F# Core Library References

3. Attempt to google.

#### Expected behavior

I can find or read the documentation. 

#### Actual behavior

I cannot find or read the documentation.

#### Known workarounds
None, I've tried crying a lot but it doesn't seem to help.

#### Related information 
The error is a "500 error". I spoke to ~Reed~ @cartermp , he's already sent an email out about this so perhaps this issue is redundant. Please read the _drama_ as humor and not any attempts to undermine people's hard work.

**Comment by ReedCopsey** [comment]
Correction - I think @cartermp sent out (or is involved in) the email chain about this...

**Comment by KevinRansom** [comment]
@voronoipotato,
sobbing is good, and cursing.  They don't solve the underlying problem, but it makes me feel happier.

Kevin

**Comment by voronoipotato** [comment]
Yes, Sorry @cartermp it was in a chatroom and I didn't carefully read who posted what. I'll try to be more careful about attribution in the future.

**Comment by cartermp** [comment]
No worries - email is out, we'll see what's up relatively soon

**Comment by cartermp** [comment]
Live again, looks like it was intermittent.
