### ISSUE TITLE
Intellisense does not appear if there is an error inside lambda

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#629]
VS 2013, VFPT 3.1.2

![1](https://cloud.githubusercontent.com/assets/873919/9810110/a3c19806-5876-11e5-89e1-cce913c0dfab.gif)

the code

``` fsharp
let foo (f: unit -> unit) = f()

let foo(): unit =
    foo <| fun _ ->
        ["a"]
        |> List.map (fun x -> x.)
```

**Comment by mpetruska** [comment]
I could reproduce the same problem in Visual Studio 2015 Community Edition. Started to investigate the problem.

**Comment by vasily-kirichenko** [comment]
@mpetruska :+1:

**Comment by mpetruska** [comment]
As of now there's a partial fix in PR #848.

**Comment by vasily-kirichenko** [comment]
Current status (VS 2017 RC):

![image](https://cloud.githubusercontent.com/assets/873919/20462802/2b2b9fa4-af37-11e6-93ae-e959b356e9cd.png)

![image](https://cloud.githubusercontent.com/assets/873919/20462804/37c1a218-af37-11e6-964d-2e748369622d.png)

**Comment by forki** [comment]
@liboz do you remember why you did this?
