### ISSUE TITLE
Error reading metadata

### ISSUE THREAD

**Issue by gmpl** [Microsoft/visualfsharp#631]
Possible related to [this similar issue](https://github.com/Microsoft/visualfsharp/issues/592)

Here's a small reproduction:

. Create a new library project
. Paste this code:

    namespace Library1

    type Class1() =
      static member inline ($) (r:'R, _) = fun (x:'T) -> ((^R) : (static member method2: ^T -> ^R) x)
      static member inline method1 x = Unchecked.defaultof<'r> $ Class1()

. Compile, then reference the dll

    #r @"Library1.dll" ;;

    unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 3 in table 'ivals' of assembly 'Library1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.

    unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 4 in table 'ivals' of assembly 'Library1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using.

    --> Referenced 'Library1.dll'

This was working fine before, in all F# versions, even in a beta (or may be it was a pre-release) version of F# 4.0 I tested some months ago was working fine, but now it doesn't and I have a project that is throwing many warnings like this when used from another project. Still they work fine but apart from the warnings the compile time increased, probably related to this.

**Comment by dsyme** [comment]
FWIW this commit into F# 4.0 changed a debug-mode assertion into a warning https://github.com/Microsoft/visualfsharp/commit/e5cdef919d43fc527ca412688af21d10f36f063a#diff-c357695ff5c54532cf4bebc7af8ac2aa

The warning can be safely ignored for now but the extra information you've given will help us fix the underlying problem.

**Comment by dsyme** [comment]
Fixed by https://github.com/Microsoft/visualfsharp/issues/674
