### ISSUE TITLE
Problem when resolving references to Office Interop classes in VS 2015

### ISSUE THREAD

**Issue by MpDzik** [Microsoft/visualfsharp#632]
I encountered a strange problem when compiling one of my projects after migrating it to Visual Studio 2015. I suspect that this is a bug in the F# compiler, but I'm not sure.

My VS solution consists of:

- An F# assembly with interface definitions (`MyAddIn.Interfaces`)
- An F# assembly with interface implementations (`MyAddIn.Implementatons`)
- A Microsoft Excel add-in project (`MyAddIn`) implemented in C#, which uses `MyAddIn.Interfaces` and `MyAddIn.Implementations`
- A C# assembly with helper classes (`OfficeHelpers`)
- some other unrelated projects

I can successfully build `MyAddIn.Interfaces`. When I build `MyAddIn.Implementations` the dependent project `MyAddIn.Interfaces` gets also built and I get a few strange warnings, however, this seems to be a [known bug](https://github.com/Microsoft/visualfsharp/issues/592) in the F# compiler.

    FSC: warning FS3186: An error occurred while reading the F# metadata 
    node at position 0 in table 'itypars' of assembly 'MyAddIn.Implementations, 
    Version=2.0.2.0, Culture=neutral, PublicKeyToken=null'. The node had no 
    matching declaration. Please report this warning. You may need to recompile 
    the F# assembly you are using.

Now when I try to compile `MyAddIn` project, I get the following error

    error CS7069: Reference to type 'Worksheet' claims it is defined in 'OfficeHelpers',
    but it could not be found.

This error comes up for each interface which uses Microsoft Excel Interop classes (such as `Microsoft.Office.Interop.Excel.Worksheet`). I have no idea why the compiler is looking for these classes in `OfficeHelpers` assembly (it does not contain any class named `Worksheet`).

The solution works perfectly fine in VS 2012 and VS 2013. No errors or warnings.

**Comment by eriawan** [comment]
@MpDzik have you tried to rebuild your C# addon project with NO PIA and without NO PIA?
I have once stumbled this before, even in VS 2013.
First, at the MS Office DLL, go to properties and look at "Embed interop types" and see if it's set to true. 
Just like this: 
![embed interop type] 
(http://blogs.microsoft.co.il/sasha/wp-content/uploads/sites/210/2013/12/embedinteroptypes.png)

Also don't forget to check the MyAddin.Implementation project too, whether the DLL is referenced or not.

Let me know if it works :smile:

**Comment by MpDzik** [comment]
@eriawan thanks for your answer. I was able to fix this problem by setting "Embed interop types" to `false` on the `OfficeHelpers` project. I guess that the compiler was trying to reference the Office types embedded in the assembly. Thank you very much for your help!
