### ISSUE TITLE
Metadata not shown for F# dlls when using dotnet cli to build

### ISSUE THREAD

**Issue by livarcocc** [Microsoft/visualfsharp#6327]
_From @mika-s on March 9, 2019 16:22_

This is similar to [this](https://github.com/Microsoft/visualfsharp/issues/5657) issue, but for the dotnet cli tool rather than when compiling with Visual Studio 2017.

Version 2.2.104 is the latest stable version as of this date, so this issue is filed for that particular version.

## Steps to reproduce

1. Create a folder and make a file called global.json in it. Add the following content to it and save:

```json
{
  "sdk": {
    "version": "2.2.104"
  }
}
```

This forces dotnet to use version 2.2.104 in case the preview version (3.0) is installed. Run `dotnet --version` to verify.

2. In the created folder, create a new solution with `dotnet new sln -o FSharpMetadata`.

3. `cd FSharpMetadata`

4. `dotnet new console -lang F# -o testproj`

5. `dotnet sln add testproj`

6. Open testproj.fsproj with an editor and add the following to the `PropertyGroup` element.

```xml
    <Authors>My author</Authors>
    <AssemblyName>testproj</AssemblyName>
    <RunPostBuildEvent>0</RunPostBuildEvent>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
```

7. `dotnet build`

8. `dotnet run --project testproj`

9. Go to `FSharpMetadata\testproj\bin\Debug\netcoreapp2.2`, right click on testproj.dll and choose Properties. Go to the Details tab.

## Expected  behavior

1. *2.2.104* is shown in the console.

2. FSharpMetadata folder created, with FSharpMetadata.sln in it.

3. New working folder is *FSharpMetadata*.

4. testproj folder created, with testproj.fsproj in it, as well as a few other files.

5. testproj is added to the sln file.

6. testproj.fsproj should look like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <Authors>My author</Authors>
    <AssemblyName>testproj</AssemblyName>
    <RunPostBuildEvent>0</RunPostBuildEvent>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
```

7. The project is build. testproj.dll is created.

8.  *Hello World from F#!* is shown in the console. This is to test that building works.

9. File description has content (e.g. testproj), File version has content (e.g. 1.0.0.0), Product name has content (e.g. testproj), Product version has content (1.0.0), Original filename has content (e.g. testproj.dll).

## Actual behavior

As expected, except for 9). Only Type, Size and Date modified have values. It looks like the screenshots that I posted when I made VS issue. See [here](https://developercommunity.visualstudio.com/content/problem/336722/metadata-not-shown-for-f-dlls-for-net-core.html).

If you try to run the repro, but change language to C#, you will get proper metadata for the dll.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.104\

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  1.0.0-preview2-003121 [C:\Program Files\dotnet\sdk]
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

## For searchability

AttributeInfo

_Copied from original issue: dotnet/cli#10957_

**Comment by livarcocc** [comment]
@KevinRansom is this a particular issue with f#? Can you investigate first?

**Comment by livarcocc** [comment]
Moving to the fsharp repo for traction.

**Comment by KevinRansom** [comment]
@livarcocc, this is a known issue with the coreclr implementation of the F# compiler.  The SDK is doing the correct thing, and works fine when using the desktop compiler, I.e. when built using msbuild myproj.fsproj.

The issue is that the Coreclr F# compiler does not embedded native resources which is where these attributes are surfaced, so that explorer can examine them.
