### ISSUE TITLE
Wsdl type provider doesn't work on clean install of Windows 10

### ISSUE THREAD

**Issue by rojepp** [Microsoft/visualfsharp#637]
Following the tutorial at https://msdn.microsoft.com/en-us/library/hh156503.aspx, I'm in trouble early on:
<img width="1074" alt="screenshot 2015-09-19 22 55 52" src="https://cloud.githubusercontent.com/assets/445888/9978126/c8589e42-5f21-11e5-91d4-56fbf4ae12fb.png">

> The type provider 'Microsoft.FSharp.Data.TypeProviders.DesignTime.DataProviders' reported an error: The .NET SDK 4.0 or 4.5 tools could not be found	ConsoleApplication2	c:\users\robert\documents\visual studio 2015\Projects\ConsoleApplication2\ConsoleApplication2\Program.fs	8

This is related to finding sdk locations in https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Data.TypeProviders/Util.fs#L105

I imagine the Sql TP has the same problems for the same reason (finding SqlMetal.exe), but I haven't tested it.

**Comment by piers7** [comment]
As far as I can see, the version of the type providers that ships with VS 2017.3 still doesn't have this fix in it. I had the same error, and I looked at the IL for the Wsdl Provider (in C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers) it looks to me like the original 'two locations' strategy, not the fixed version from PR 638 that checks for the SDK in more locations. Maybe I'm just referencing the wrong dll, but this is the only one I could find (and the one that appears in VS 2017's Add Reference dialog, on my new laptop)

Assembly I'm looking in:
// Type: Microsoft.FSharp.Data.TypeProviders.Utility.Util
// Assembly: FSharp.Data.TypeProviders, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// MVID: 5011D889-858F-C49F-A745-038389D81150
// Assembly location: C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers\FSharp.Data.TypeProviders.dll

I reference nuget FSharp.Data.TypeProviders, 5.0.0.2, the problem goes away, which makes me strongly suspect that this fix has never made it's way into an OOB release, and anyone struggling with this should probably reference the nuget instead.

**Comment by dsyme** [comment]
> I reference nuget FSharp.Data.TypeProviders, 5.0.0.2, the problem goes away, which makes me strongly suspect that this fix has never made it's way into an OOB release, and anyone struggling with this should probably reference the nuget instead.

Yes, you should use the nuget package from now on.  The version shipped with Visual Studio is legacy for backwards compat.

**Comment by dsyme** [comment]
> I reference nuget FSharp.Data.TypeProviders, 5.0.0.2, the problem goes away

Yes, you should reference the nuget package from now on
