### ISSUE TITLE
No intellisense for parameters of TP method with static parameters

### ISSUE THREAD

**Issue by dmitry-a-morozov** [Microsoft/visualfsharp#640]
![image](https://cloud.githubusercontent.com/assets/3004037/10060942/ad2932b8-6209-11e5-90f6-84c4225c52c8.png)

**Comment by dsyme** [comment]
Yes, well, this should indeed be fixed. I'm aiming to take a look at it.

**Comment by dmitry-a-morozov** [comment]
#642 and https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/63
are also very important for TP usability. 
#641 can be skipped but would be nice to get fixed.

**Comment by dsyme** [comment]
Hi @dmitry-a-morozov 

I'm working on a fix here: https://github.com/Microsoft/visualfsharp/pull/705.  I haven't added testing but maybe you get a chance to try it out

**Comment by dsyme** [comment]
(Actually that's probably the fix to https://github.com/Microsoft/visualfsharp/issues/642 not this one, but we should fix them at the same time in any case)

**Comment by dmitry-a-morozov** [comment]
@dsyme How do I go about testing https://github.com/Microsoft/visualfsharp/pull/705?

**Comment by dsyme** [comment]
I worked on this fix a bit more, see #705

**Comment by dsyme** [comment]
Fixed, see link above
