### ISSUE TITLE
Obscure error message when generated statically parameterized method is not yet applied

### ISSUE THREAD

**Issue by dmitry-a-morozov** [Microsoft/visualfsharp#641]
This is not very intuitive error message:

The type provider 'FirstProvider.TP+MyTypeProvider' reported an error in the context of provided type 'ExampleTypeProvider.ExampleType', member 'ExampleMethWithStaticParam'. The error: **ProvidedMethod: no invoker for ExampleMethWithStaticParam on type ExampleTypeProvider.ExampleType**  

![image](https://cloud.githubusercontent.com/assets/3004037/10082736/15d933ac-62b0-11e5-97a3-59f33b77298c.png)

**Comment by panesofglass** [comment]
:+1:

**Comment by dsyme** [comment]
My understanding is that this was fixed in #703
