### ISSUE TITLE
Overload resolution problem

### ISSUE THREAD

**Issue by kevmal** [Microsoft/visualfsharp#6419]
Using trill there seems to be an issue selecting the right overload for the `Select` extension method
![image](https://user-images.githubusercontent.com/7281367/55434947-f99e6800-5555-11e9-8547-bdecd69cdfa9.png)

```fsharp
open Microsoft.StreamProcessing
open System
open System.Linq.Expressions

type Record(a : int) = 
    member x.A = a

let f (x : IStreamable<int64, Record>) : IStreamable<int64,int> = x.Select(fun x -> x.A) //Error
let g (x : IStreamable<int64, Record>) = Microsoft.StreamProcessing.Streamable.Select(x, (fun x -> x.A)) //Error
let h (x : IStreamable<int64, Record>) = Microsoft.StreamProcessing.Streamable.Select<int64, Record, int>(x, (fun x -> x.A)) //Error
let k (x : IStreamable<int64, Record>) = x.Select(selector = (fun x -> x.A)) //Okay
```

The errors in  the first three attempts are on `x.A` with `Error	FS0072	Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved.`

Usually a simple type annotation on `x` would solve the problem but this is an ideal use case of anonymous records and having to add the full type annotation would be horrendous. Luckily in this particular case using a named parameter works.

#### Repro steps

Add `Trill` nuget package and use the code above, or clone https://github.com/kevmal/overloaderr

#### Known workarounds

- Named argument (specifically for this case)
- Type annotation which kills the whole anonymous record experience
- add helpers:
```fsharp
type Bleh() =
    static member Select(v : Expression<Func<'a,'b>>) = fun (x : IStreamable<_,_>) -> x.Select(v)
let l (x : IStreamable<int64, Record>) = x |> Bleh.Select (fun x -> x.A) //Okay
```

**Comment by dsyme** [comment]
I think this will need to be recorded as a language design suggestion at https://github.com/fsharp/fslang-suggestions/, rather than a bug.  There are complicated overload sets that definitely cause problems, looking at the above overloads I can see why they might be a problem in each of the three cases

I'd really like to see some F# Trill code - besides the above do you have any available to share?

**Comment by kevmal** [comment]
I don't have anything too exciting at the moment. But I have the fsx file I created reading through the [query writing guide](https://github.com/Microsoft/Trill/blob/master/Documentation/TrillQueryWritingGuide.pdf):

https://gist.github.com/kevmal/d5382e8d2b0059a179341805be2fc2d3

**Comment by dsyme** [comment]
OK cool. Put a blog post up when you have a decent starter intro done?

**Comment by kevmal** [comment]
Sure, I'll look into it.
