### ISSUE TITLE
No intellisense for method static parameters. 

### ISSUE THREAD

**Issue by dmitry-a-morozov** [Microsoft/visualfsharp#642]
Note this is diff from Issue #640. 
This came up as part of my work on FSharp.Data.SqlClient V2
I made nice progress on adding statically parameterized ```CreateCommand``` method on SqlClient type provider (formerly SqlProgrammability) 

Usage examples in unit tests:
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/44aaaaf61a725a3b30139d1aee61555fbcbe0595/src/SqlClient.Tests/CreateCommand.fs

In script
https://github.com/fsprojects/FSharp.Data.SqlClient/blob/44aaaaf61a725a3b30139d1aee61555fbcbe0595/src/SqlClient.Tests/CreateCommand.fsx

But end-user experience is sub-optimal because lack of intellisense for static parameters.
Below is comparison between current version of SqlCommandProvider and new SqlClient.CreateCommand. They both have more or less same set of static params

![image](https://cloud.githubusercontent.com/assets/3004037/10088154/8e715232-62cd-11e5-828c-f518a06efc04.png)

Issues #640, #641  and https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/63 combined makes me think that "TP statically parameterized methods" feature is really nice but not yet ready for prime time.

**Comment by panesofglass** [comment]
:+1:

**Comment by dsyme** [comment]
Fixed, see link above
