### ISSUE TITLE
We should support the current version of ASP by shipping ASP MVC templates.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#643]
Title says it all.

PR's are on CodePlex:
* https://visualfsharp.codeplex.com/SourceControl/network/forks/jackfoxy/visualfsharp/contribution/7679
* https://visualfsharp.codeplex.com/SourceControl/network/forks/riles01/multiprojecttemplates/contribution/7655
* https://visualfsharp.codeplex.com/SourceControl/network/forks/riles01/webtemplates/contribution/7650

Kevin should do what is necessary to make this happen.

**Comment by panesofglass** [comment]
:+1:  Thank you!

**Comment by zhengbli** [comment]
This would be awesome!

**Comment by dsyme** [comment]
Closing old discussion
