### ISSUE TITLE
fold, foldi for Array2D 

### ISSUE THREAD

**Issue by ruffianeo** [Microsoft/visualfsharp#645]
... with folde signatures: 
fold: 'U -> 'T
foldi: 'U -> int -> int -> 'T (the same as usual, state first, then x,y then the value at x,y.

It seems they were forgotten and there is no obvious reason, why those functions should not exist for Array2D.

See e.g. 
http://stackoverflow.com/questions/29873646/why-does-array2d-not-have-a-fold-operation

**Comment by cloudRoutine** [comment]
http://fslang.uservoice.com/forums/245727-f-language/suggestions/7334486-normalize-collections-api-for-array2d-module

**Comment by dsyme** [comment]
Closing this since it's now on User Voice
