### ISSUE TITLE
Q: Only build compiler on Windows

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharp#6463]
I always used "build.cmd debug" in order to only build the compiler and fsi bits. The build script changed and I can't find a corresponding option. Note: I don't want to build any tooling.

What's the process now?

/cc @brettfo

**Comment by dsyme** [comment]
I think it's 

    dotnet build FSharp.sln

Though you have to build the proto compiler first via

    build.cmd -bootstrap

**Comment by dsyme** [comment]
At least that's what `DEVGUIDE.md` says

**Comment by forki** [comment]
what`s `build.cmd` without parameters doing? seems to have worked on my machine and VS 2019 was colored. so maybe that's the new way!?

**Comment by dsyme** [comment]
> what's build.cmd without parameters doing? seems to have worked on my machine and VS 2019 was colored. so maybe that's the new way!?

AFAIK it shouldn't install into the default hive, but rather into `devenv /RootSuffix RoslynDev`. @brettfo can confirm or check the code.

**Comment by brettfo** [comment]
Correct, it uses the RoslynDev hive as specified [here](https://github.com/Microsoft/visualfsharp/blob/c370f8eb55c149c3b9ef00ca4bbe4472e5277f27/vsintegration/Vsix/Directory.Build.props#L7).

**Comment by forki** [comment]
So the new process is:

0) git clean -xdf
1) build.cmd -bootstrap
2) dotnet build FSharp.sln
3) open vs 2019 

Is that correct? Or is it enough to just do build.cmd -bootstrap?

**Comment by cartermp** [comment]
> open vs 2019

Only if you're a VS user 😛

But yes, that should be correct. If it fails then @brettfo would know more.

**Comment by brettfo** [comment]
You should`*` be able to do the following:

1. `git clean -xdf`
2. `Build.cmd` (`-bootstrap` is auto-detected, so it's only needed if you explicitly want to rebuild it)
3. Open FSharp.sln in VS

`*` I say **should** because it's untested on windows, but that's essentially what happens during the Linux build.

**Comment by forki** [comment]
thanks!
