### ISSUE TITLE
[16.1 Preview 1 - Known issue] .NET SDK F# projects do not load correctly

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#6476]
A bug that has been fixed a while ago causes F# projects not to load correctly if they are using the .NET SDK.

Unfortunately, due to the very tight schedule for 16.1 Preview 1, the fix is not going out in Preview 1. It will be available starting with Preview 2.

**Comment by klettier** [comment]
Sadly I have just done the upgrade and it breaks everything in Fsharp project

**Comment by cartermp** [comment]
@klettier I recommend using 16..0.x until 16.1 Preview 2 is available (if you prefer using previews)

**Comment by cartermp** [comment]
This is resolved in Preview 2.
