### ISSUE TITLE
./fcs/build.cmd fails

### ISSUE THREAD

**Issue by auduchinok** [Microsoft/visualfsharp#6493]
After fetching and cleaning everything with git:
```
$ ./fcs/build.cmd


    Directory: C:\Developer\vft-rebase\fcs


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        4/11/2019  11:53 AM                .paket
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At C:\Developer\vft-rebase\fcs\download-paket.ps1:6 char:5
+     Invoke-WebRequest -Uri $paketurl -OutFile "$paketpath"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
Downloading `paket.exe` and restore targets manually from GitHub makes build pass.

**Comment by forki** [comment]
This is very likely due to the new changes that replaced paket's bootstrapper with a script. My assumption is that this script does not work with proxies. /cc @brettfo

**Comment by forki** [comment]
maybe it just needs to do this:

 
            ServicePointManager.SecurityProtocol = 
                SecurityProtocolType.Tls12
                | SecurityProtocolType.Tls11
                | SecurityProtocolType.Tls
                | SecurityProtocolType.Ssl3;

**Comment by forki** [comment]
@auduchinok can you please try https://github.com/Microsoft/visualfsharp/pull/6494?

**Comment by auduchinok** [comment]
@forki Yes, it works in that branch.

**Comment by forki** [comment]
Not sure how the corresponding bash version would look like or if it is
even needed over there. I'll leave that as an exercise to the reader.

Eugene Auduchinok <notifications@github.com> schrieb am Do., 11. Apr. 2019,
13:06:
