### ISSUE TITLE
Just to note this feature is used in a few places

### ISSUE THREAD

**Issue by 7sharp9** [Microsoft/visualfsharp#6497]
https://github.com/Microsoft/visualfsharp/blob/4394ee7d14653bfcd7d6a52868e4ca277bbc4f8f/src/fsharp/fsc.fs#L1928

Just to note this feature is used in a few places, the quotation compiler, I think the pickler that Eirik wrote might also use it, and Falanx too has a beta feature using this API.

**Comment by enricosada** [comment]
@7sharp9 maybe send a PR to remove that comment?
probably if someone go ahead and remove that code because read that comment, will not search in issues.

**Comment by dsyme** [comment]
> Just to note this feature is used in a few places, the quotation compiler, I think the pickler that Eirik wrote might also use it, and Falanx too has a beta feature using this API.

FWIW I consider this an experimental part of FCS that may be removed in the future - it was added by Eirik for MBrace but they used a very different implementation path in the end.

**Comment by 7sharp9** [comment]
Its used in Eiriks quotation compiler too from this entry point: https://github.com/eiriktsarpalis/QuotationCompiler/blob/master/src/QuotationCompiler/QuotationCompiler.fs#L129

**Comment by dsyme** [comment]
Ah yes that was salvaged from that MBrace work.

Still, it's always been a bit out-of-scope for FCS, and no current use case in actively maintained F# IDE, documentation or script evaluation tooling, which are the three things that tends to keep FCS honest.

**Comment by 7sharp9** [comment]
Im think Fantomas might also use that endpoint too.

**Comment by cartermp** [comment]
Fantomas does not use this: https://github.com/fsprojects/fantomas/search?q=main1OfAst&unscoped_q=main1OfAst

I'll close this discussion; we don't have active plans to remove this
