### ISSUE TITLE
Cannot consume a [<CLIEvent>] in C# from F# module

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/visualfsharp#65]
Creating a ``[<CLIEvent>]`` within a module does not get exposed to C# the same as when they are on a class (either static or instance level): -

    // On a module
    module Foo =
        let private onBoo = new Event<string>()
        [<CLIEvent>]
        let Boo = onBoo.Publish

    // On a class, instance level
    type Bar() =
        let onBoo = new Event<string>()
        [<CLIEvent>]
        member __.Boo = onBoo.Publish 

    // On a class, static
    type Blah() =
        static member onBoo = new Event<string>()
        [<CLIEvent>]
        static member Boo = Blah.onBoo.Publish 

The last two can be consumed from C#, but the first one cannot: -

    Foo.Boo += (o, e) => { }; // gives three compiler errors, see below
    Blah.Boo += (o, e) => { }; // compiles
    new Bar().Boo += (o, e) => { }; // compiles

Errors are: -

    Cannot convert lambda expression to type 'Microsoft.FSharp.Control.IEvent<Microsoft.FSharp.Control.FSharpHandler<string>,string>' because it is not a delegate type
    Operator '+=' cannot be applied to operands of type 'Microsoft.FSharp.Control.IEvent<Microsoft.FSharp.Control.FSharpHandler<string>,string>' and 'lambda expression'
    Property or indexer 'Foo.Boo' cannot be assigned to -- it is read only

Indeed VS2013 in C# shows it as a property rather than an event in the intellisense.

**Comment by dsyme** [comment]
Hi @isaacabraham  - This is by design - CLIEvent only applies to property members, see See 8.13.10 of http://fsharp.org/specs/language-spec/.  Perhaps add a suggestion at http://fslang.uservoice.com to suggest that the attribute also applies to module values?

**Comment by isaacabraham** [comment]
@dsyme yes, will do - it would certainly be a useful feature for when a module alone would suffice.

It might be worth mentioning this somewhere because I've spoken with a few people that thought that this was the expected behaviour :-)

**Comment by dsyme** [comment]
I suppose our belief was that "global" static events were very rare in library design.  Perhaps not.

In any case please add a link to the user voice entry once you add it.

**Comment by isaacabraham** [comment]
Sometimes it's handy if you have a module with some functionality, which are exposed nicely in C# - events round off the story nicely. To be honest, I'd not mind either way - either a compiler warning or error, or to allow it.

Linked to UV request: http://fslang.uservoice.com/forums/245727-f-language/suggestions/6984621-support-for-clievent-on-modules
