### ISSUE TITLE
Seq.cast's non-generic IEnumerable implementation doesn't throw even when the cast is to the wrong type

### ISSUE THREAD

**Issue by kbattocchi** [Microsoft/visualfsharp#650]
This throws

    let strings = [1] |> Seq.cast<string>
    for s in strings do ()
but this doesn't

    let strings = [1] |> Seq.cast<string> :> System.Collections.IEnumerable
    for s in strings do ()

This can lead to other confusing behavior:

    let sum = [1] |> Seq.cast<string> |> Seq.cast<int> |> Seq.sum // doesn't throw!

**Comment by dsyme** [comment]
This was fixed by #651
