### ISSUE TITLE
Value restriction. The value 'partialTest' has been inferred to have generic type ...

### ISSUE THREAD

**Issue by TIHan** [Microsoft/visualfsharp#6509]
Code doesn't compile.

#### Repro steps

1. Put this code at a module level:
```fsharp
open System.Collections

let findCustomer (id:int) = ()

let test (f: int -> 'a) (id: int) (principle: IEnumerable)
    = Some (fun () -> f id)

let partialTest = test findCustomer
```

#### Expected behavior

It should compile and give a proper signature.

#### Actual behavior

It does not compile.
```
Value restriction. The value 'partialTest' has been inferred to have generic type
    val partialTest : (int -> '_a -> (unit -> unit) option) when '_a :> IEnumerable    
Either make the arguments to 'partialTest' explicit or, if you do not intend for it to be generic, add a type annotation. (using built-in F# compiler)
```

#### Known workarounds

Make `partialTest` generic, `let partialTest<'a> = ...`

#### Related information 

This compiles at the module level:
```fsharp
let findCustomer (id:int) = ()

let test (f: int -> 'a) (id: int) (principle: string)
    = Some (fun () -> f id)

let partialTest = test findCustomer
```

**Comment by TIHan** [comment]
It could be intended design, but I'm sure users would expect this to work since the one using `string` does. Therefore, I'm deeming this as a bug until said otherwise.

**Comment by dsyme** [comment]
Yes this is by design - `IEnumerable` is not sealed where `string` is, and this causes the value restriction to trigger

**Comment by NinoFloris** [comment]
@dsyme but there's no flexible type being used here? Why is IEnumerable suddenly being inferred as flexible instead of concretely being IEnumerable?

**Comment by TIHan** [comment]
I guess my head is exploding, I'm not sure why a sealed type in this case would cause a value restriction. But this would explain when using a record or DU worked.
