### ISSUE TITLE
In F# interactive, generic structs wrongly have an extra dummy field

### ISSUE THREAD

**Issue by kbattocchi** [Microsoft/visualfsharp#654]
Given the definition:

```fsharp
[<Struct>]
type S<'t> = // at least one type parameter
    val x : string // at least one instance field
```

then in F# interactive `S<_>` will spuriously have a private instance field `__dummy` of type int:

```fsharp
typeof<S<_>>.GetField("__dummy", enum 0xffffffff)  // not null!
```

This is due to the wrong logic being applied on line [6310](https://github.com/Microsoft/visualfsharp/blob/bf1b709520d05c577739672a1e1a86fe14b17800/src/fsharp/IlxGen.fs#L6310) of IlxGen.fs, which is checking for the presence of any instance field rather than the opposite.

Note that there is some very similar (but not identical) logic which is applied to determine size and packing behavior at line [6623] (https://github.com/Microsoft/visualfsharp/blob/bf1b709520d05c577739672a1e1a86fe14b17800/src/fsharp/IlxGen.fs#L6623) - it's not clear to me whether the condition here is actually correct, inverted, or wrong in a different way (e.g. here it doesn't only apply to F# interactive because the check for workAroundReflectionEmitBugs is following an `||`).

**Comment by dsyme** [comment]
Thanks, good catch
