### ISSUE TITLE
"Only functions can be marked 'inline'" maybe wrongly detected

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#657]
I was trying to define those two inline functions:

```fsharp
let inline isNull = function | null -> true | _ -> false
let inline isNotNull = not << isNull
```

which both give `Only functions can be marked 'inline'` (VS2015).

it seems the detection to validate inline rely on the fact that the function expressions are partially applied and don't have parameters.

Not sure if it's considered a bug, I believe those are functions and should be inlineable without ambiguity.

**Comment by dsyme** [comment]
This is by design, is the message says you have to declare a function explicitly.  Changing this would be a feature request, please add to http://fslang.uservoice.com/.
