### ISSUE TITLE
Visual Studio doesn't have Editor settings for the F# Editor

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#6577]
Visual Studio doesn't have Editor settings for the F# Editor

![image](https://user-images.githubusercontent.com/5175830/56403574-c119b200-6216-11e9-9fed-a5e5e97a4b0a.png)

**Comment by cartermp** [comment]
Which build/release?

**Comment by KevinRansom** [comment]
The staging branch --- 2019 - D16.1 Stg
Everywhere else, is correct.

**Comment by cartermp** [comment]
Okay, we'll need to prioritize this so we can get it through in preview 3 or 4

**Comment by cartermp** [comment]
Doesn't reproduce on latest d16.1 stage (which corresponds with Preview 3).
