### ISSUE TITLE
Fsi fails to augment a type constructor

### ISSUE THREAD

**Issue by geandbe** [Microsoft/visualfsharp#659]
The following script

    type AugmentMe = val _i : int
    type AugmentMe with member i.I = i._i
    type AugmentMe with new(i) = { _i = i }
    printfn "AugmentMe instance: %i" (AugmentMe(42).I) 

when interpreted by `fsi` at once works as expected.

When being interpreted in new `fsi` session line by line, last two lines produce the following diagnostic messages:

    warning FS0073: internal error: pop on empty stack during code generation, methodName = AugmentMe..ctor
    error FS0039: The value or constructor 'AugmentMe' is not defined

so apparently in the second case type augmentation with constructor has failed.

The artifact can be observed both in F# 4.0 and F# 3.1.

**Comment by dsyme** [comment]
Already fixed by https://github.com/Microsoft/visualfsharp/pull/704
