### ISSUE TITLE
Computation Expression Yield Error 

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#662]
Given two computation expressions
```
type record = { id:int;elms:int list}        
    
type recordBuilder1 () =
    member __.Yield (()) = { id=0;elms=[] }
    [<CustomOperation("set_id")>]
    member  __.set_id (r:record, n):record = { r with id = n}   

        
type recordBuilder2 () =
    member __.Yield () = { id=0;elms=[] }
    [<CustomOperation("set_id")>]
    member __.set_id (r:record, n) = { r with id = n}  
```
with FSI output 
```
type record =
  {id: int;
   elms: int list;}
type recordBuilder1 =
  class
    new : unit -> recordBuilder1
    member Yield : unit -> record
    member set_id : r:record * n:int -> record
  end
type recordBuilder2 =
  class
    new : unit -> recordBuilder2
    member Yield : unit -> record
    member set_id : r:record * n:int -> record
  end
```
It seems like they should have identical functionality, however 
```
let mkrecord1 = recordBuilder1()
let mkrecord2 = recordBuilder2()

let m1 = mkrecord1 { set_id 222 }
let m2 = mkrecord2 { set_id 222 } // <- compiler error 
```
`Error: The member or object constructor 'Yield' takes 0 argument(s) but is here given 1. The required signature is 'member recordBuilder2.Yield : unit -> record'.`

This made no sense to me, so I compiled and checked with ILSpy and found 
```
		[CompilationMapping(SourceConstructFlags.ObjectType)]
		[Serializable]
		public class recordBuilder1
		{
			public recordBuilder1() : this()
			{
			}

			public Cexprs.record Yield(Unit _arg1)
			{
				return new Cexprs.record(0, FSharpList<int>.Empty);
			}

			[CustomOperation("set_id")]
			public Cexprs.record set_id(Cexprs.record r, int n)
			{
				return new Cexprs.record(n, r.elms@);
			}
		}

		[CompilationMapping(SourceConstructFlags.ObjectType)]
		[Serializable]
		public class recordBuilder2
		{
			public recordBuilder2() : this()
			{
			}

			public Cexprs.record Yield()
			{
				return new Cexprs.record(0, FSharpList<int>.Empty);
			}

			[CustomOperation("set_id")]
			public Cexprs.record set_id(Cexprs.record r, int n)
			{
				return new Cexprs.record(n, r.elms@);
			}
		}
```

Which allows something like -
```
type recordBuilder1 () =
    member __.Yield () = { id=0;elms=[] }
    member __.Yield (()) = { id=0;elms=[] }
    [<CustomOperation("set_id")>]
    member  __.set_id (r:record, n):record = { r with id = n}   
> 

type recordBuilder1 =
  class
    new : unit -> recordBuilder1
    member Yield : unit -> record
    member Yield : unit -> record
    member set_id : r:record * n:int -> record
  end
```
to be valid code

**Comment by kbattocchi** [comment]
I'm not sure this is a bug; if you look at how custom operations are desugared the compiler ends up calling `Yield` with the set of in-scope local variables as a tuple, and in the case where there are no variables this is naturally an explicit 0-tuple (that is, `Yield` must be a method capable of taking a real value of type `unit`, rather than a normal method taking 0 arguments).  I think that in a well-formed query builder it should basically always be the case that `Yield` is generic (so that it can properly handle whatever number of locals the user has brought into scope).

**Comment by cloudRoutine** [comment]
Ah so that's what it is, it seemed like an error based on the method overloading rule about type signatures. Since it's an explicit 0-tuple wouldn't it aid clarity to show `Tuple` or `Tuple<unit>`  instead of `unit` twice? Since the signatures are materially different in terms of the types it seems like the signatures should express this.

**Comment by panesofglass** [comment]
Agree about the signatures. I wish GitHub had some way to bookmark threads, as this is extremely valuable to remember.

**Comment by kbattocchi** [comment]
@cloudRoutine I've created a new issue because I do think that there's an underlying problem here, but it's not directly related to Yield or computation expressions.

**Comment by cloudRoutine** [comment]
True, and that's the issue I really care about.
