### ISSUE TITLE
No F# templates in VS2013

### ISSUE THREAD

**Issue by GerjanOnline** [Microsoft/visualfsharp#665]
I do not have the F# templates in my Visual Studio 2013

![image](https://cloud.githubusercontent.com/assets/1153419/10249267/a2886ae6-6924-11e5-9a3d-6ba0d0165571.png)

How can I get these (back)?

Hopefully without doing a repair or uninstall + install that will take ~ 4 hours

I am using:
Visual Studio 2013 Ultimate Update 5
Windows 7 Pro 64bit

**Comment by dsyme** [comment]
Have you tried installing or reinstalling the Visual F# Tools 3.1.2?  If that doesn't work try a full reinstall.

I will close this as this repo is up to F# 4.0.

**Comment by GerjanOnline** [comment]
Repairing Visual F# Tools 3.1.2 (http://www.microsoft.com/en-us/download/details.aspx?id=44011) fixed it!

Thank you
