### ISSUE TITLE
ctrl-d should quit fsi

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharp#667]
I spent some time this weekend feeling out F# development *without* Visual Studio, and fsi was used for some functional prototyping via Powershell.

It's intuitive for someone with a *nix background to use `^D` to exit something like a repl session, and I think that supporting things like this will go a long way towards attracting primarily *nix developers to the language and environment.

**Comment by eriawan** [comment]
@cartermp 

I think this is a feature request or additional feature suggestion. You should go to F# uservoice (http://fslang.uservoice.com) and create new feedback there.

**Comment by dsyme** [comment]
Yes, it's a feature request, though for this case I'd say you could also just send a PR for discussion.  

Closing as it's not actually a bug (and we generally track suggestions via fslang.uservoice.com rather than issues).
