### ISSUE TITLE
Unclear error message when using the C# lambda operator

### ISSUE THREAD

**Issue by aspnetde** [microsoft/visualfsharp#6678]
#### Repro steps

I accidentally wrote something like this:

```
let x (y:int -> int) (z:int) = y <| z
let y a:int = a

let result = x (fun x -> x * 2) 5
let result2 = x (foo => y foo)fs
```
This results in:

![image](https://user-images.githubusercontent.com/1322584/57147459-e5a18c80-6dc7-11e9-9a40-1eaf0948709e.png)

#### Expected behavior

Maybe the error message could be a bit more clear.

* macOS
* Mono 5.18.1.3
* .NET COre 2.2.106
* VS4Mac 8.0.5 (build 9)

**Comment by sebhofer** [comment]
But that has nothing to do with the `=>` operator, does it? Just writing `x foo y` (or anything involving `foo`) yields the same error message. What message would you expecte?

**Comment by cartermp** [comment]
@aspnetde Do you have some thoughts on what would be more helpful here? From an error perspective, `=>` also doesn't make sense, but it's not mentioned.

**Comment by aspnetde** [comment]
This issue has been [brought to you](https://twitter.com/sforkmann/status/1124300317238222850) by @forki :-) – maybe he has an idea.

I for one don't have a clue about how all this is connected etcetera so I don't think I can be of much help here. (Thought: If it was possible to detect the shape of that C# lambda expression it would be helpful to give a hint about exactly that.)

**Comment by cartermp** [comment]
I don't think we'd be able to really do this, since detection of similar C# "shapes" isn't something we'd ever want to do in the compiler. Though it could be slightly confusing, I think this error message is about as clear as we could get here, especially since `foo` isn't defined anywhere.
