### ISSUE TITLE
Paket sln broken in VS 2019

### ISSUE THREAD

**Issue by forki** [microsoft/visualfsharp#6689]
https://user-images.githubusercontent.com/57396/57126853-b9b5e500-6d8e-11e9-958a-f65b79925614.png

I can't build anymore inside of VS 2019. Building from cmd line is fine. This is rather critical for me since I need to support paket ecosystem

**Comment by cartermp** [comment]
I think this is expected, as it's using `FSharp.Compiler.Tools` and probably getting some collision since that package uses older bits that have not been tested nor expected to work with VS 2019.

**Comment by forki** [comment]
I don't think we should close it. I consider it a bug in VS that it can't work with older FCT. The build works fine in cmd and former VS worked as well. We should not need to update FCT. The whole point of the FCT was to allow users to pin the compiler version

**Comment by cartermp** [comment]
We don't support nor test against the package (nor have we ever). That is akin to having some arbitrary older F# compiler work with an arbitrary newer VS version, which we also neither support nor test.

**Comment by baronfel** [comment]
It is going to start being a problem now with 2019 uptake increasing. It highlights the need to get a merged and updated FCT to unblock folks, or else have then reevaluate the need for it. As I understand it, the last remaining need (aside from the version-pinning that @forki mentioned) is to allow use of old, unuodated TPs, right?

**Comment by forki** [comment]
@cartermp it's really unfortunate since this is very common and IMHO important use case.

**Comment by cartermp** [comment]
I don't think the use of FCT is particularly common, nor important. Perhaps it was more useful years ago when there was no .NET SDK and VS had a very slow update cadence that prohibited the use of a more up to date compiler.
