### ISSUE TITLE
Use BenchmarkDotNet for task perf project

### ISSUE THREAD

**Issue by cartermp** [microsoft/visualfsharp#6718]
See here: https://github.com/microsoft/visualfsharp/pull/6634#issuecomment-491852691

The perf suite in `tests\fsharp\perf\tasks` needs to use BenchmarkDotNet to account for any variance in runs, preferably with a README that has the last run stored. It should compare:

* C# `async` runs as the baseline
* F# `async` equivalent
* F# `async`calling C# code with `AwaitTask`
* Ply equivalent
* Eventually, `task` CE in #6634 

It should also use `MemoryDiagnoser` so we can see the memory usage of each case.

**Comment by dsyme** [comment]
If you work on this please submit to the "tasks" branch in https://github.com/dsyme/visualfsharp

**Comment by dsyme** [comment]
I'm switching it over to use BenchmarkDotNet now

**Comment by dsyme** [comment]
Closing as all except Ply has been done in "tasks" branch
