### ISSUE TITLE
Port NUnit based tests to Core CLR

### ISSUE THREAD

**Issue by PatrickMcDonald** [Microsoft/visualfsharp#690]
coreclr status:  https://github.com/Microsoft/visualfsharp/wiki/F%23-for-CoreCLR---Status

I can start looking at this task for the CoreCLR project

**Comment by KevinRansom** [comment]
Thank you, that would be awesome.  You will have to make the tests build on coreclr first. Which is going to be an interesting challenge.  Good luck.

**Comment by PatrickMcDonald** [comment]
Have reached first hurdle well before looking at actually compiling on coreclr.  I can't get the project to compile against Profile47 using xUnit.net. Is this surprising or expected?

xUnit.net seems to support portable-net45+win8+wp8+wpa81, whereas Profile47 includes Silverlight 5

The workaround for a similar issue with FsCheck was to exclude those tests for 47, but I have a feeling that won't fly this time.

**Comment by PatrickMcDonald** [comment]
Also, @KevinRansom, I hope your comment yesterday wasn't intended to be encouraging, because it wasn't ;)

**Comment by enricosada** [comment]
xunit require .net desktop > 4.5 , we cannot use it for .net 2.0

**Comment by forki** [comment]
why is this change of framework needed?

**Comment by enricosada** [comment]
see #688 ,

> 8. Port the Nunit tests to XUnit 2.0. (*XUnit is what Roslyn and .NetCore use*).

**Comment by forki** [comment]
but that's only a fact not a real reason. 
AFAIK NUnit is also working on coreclr support.

**Comment by enricosada** [comment]
yes, not ready yet but maybe we can meawhile upgrade nunit 2.1 -> 3.0, and wait for dnx support

ref nunit/nunit#575

in the last bet5, there is support for coreclr (need build from sourcecode) see [Release-Notes nunit-300-beta-5](https://github.com/nunit/nunit/wiki/Release-Notes#nunit-300-beta-5---october-16-2015)

> The NUnit framework may now be built for the .NET Core framework. Note that this is only available through building the source code. A binary will be available in the next release

Ihmo is better to stay on nunit, upgrade to 3.0 in main branch, port fsharp/fsharpqa to use nunit runner, and wait for full compatibility of nunit.
If nunit drop a target profile, we can anyway stub methods, and run with nunit 2.x, easier than xunit -> nunit migration

**Comment by KevinRansom** [comment]
@forki Where possible we will use the same tooling as dotnet and coreclr OSS projects.  This allows us to leverage work they do.

**Comment by rprouse** [comment]
NUnit has a new PR nunit/nunit#915 that adds .NET core support. We still need to test on various platforms and get 3.0 out, but we are close :+1:

**Comment by forki** [comment]
Yes reusing other people's work is a good idea. But here we should be
careful if that's really helpful. Changing test frameworks comes with lots
of trouble (but keeping outdated ones too ;-) ).

When nunit allows us to keep working with it, then I personally would not
want to change. Especially xunit2 has been a nightmare for me in the past.

**Comment by radekm** [comment]
Does xUnit.net 2 work with Mono?

**Comment by forki** [comment]
Yes latest mono versions should support latest xunit2.

**Comment by KevinRansom** [comment]
@PatrickMcDonald It's worth investigating the coreclr implementation of nunit.  I doubt that converting the specific test framework will be anywhere near as hard as making the tests work on coreclr.  But nunit is perfectly decent framework.  The main goal is really to get this stuff working cross platform on coreclr anyway.

**Comment by ctaggart** [comment]
The NUnit support for CoreCLR already got merged to master. There is not a build with it in the NuGet Gallery yet. I just created this PR for them to add CI builds to the AppVeyor NuGet feed https://github.com/nunit/nunit/pull/932. 

Until that happens, it is available in my feed: https://ci.appveyor.com/nuget/ctaggart-nunit
Build history: https://ci.appveyor.com/project/ctaggart/nunit/history

**Comment by PatrickMcDonald** [comment]
NUnit is now 3.0 RC, from the [release notes](https://github.com/nunit/nunit/wiki/Release-Notes):

> NOTE: The `nunit3-console` runner cannot run tests that reference the portable build. You may run such tests using NUnitLite or a platform-specific runner.

Does this mean that running CoreCLR unit tests will not be supported in NUnit 3.0 without writing a custom console app?

**Comment by rprouse** [comment]
@PatrickMcDonald, the `nunit3-console` is a standard desktop app, so it does not run the DNX code. We plan on releasing runners for various platforms, but we are doing so out of band of the normal release. We are concentrating on getting 3.0 out the door then will be looking to creating runners for other platforms. The Xamarin runners are already done and at simple console runner shouldn't take too long.

In the meantime, you can reference NUnitLite making the tests themselves self-executable. All you need to do is add a couple of lines of code to Main and your tests are a console runner and tests all wrapped into one assembly.

**Comment by dsyme** [comment]
Closing old discussion
