### ISSUE TITLE
Explicit field declaration generating property in F# classes

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#7]
Opened by: [eiriktsarpalis](https://www.codeplex.com/site/users/view/eiriktsarpalis)

The definition
````fsharp
type Foo =
    val foo : string
````
currently generates the following code (decompiled):
````csharp
    public class Foo
    {
        internal string foo@;
        [CompilationMapping(SourceConstructFlags.Field, 0)]
        public string foo
        {
            get
            {
                return this.foo@;
            }
        }
    }
````
Is this correct behaviour? It does not seem to be recorded in the documentation (http://msdn.microsoft.com/en-us/library/dd469494.aspx) or the language spec. 

 I should note that this goes away as soon as I add the mutable keyword in the declaration. This might be intentional, since fields are always supposed to be mutable. But this feels wrong, particularly in the context of F# where the mutable keyword comes with a declaration of intention.

>comments
>dsyme wrote Today at 2:16 AM [x] 
>Yes, this is correct. We should make it clearer in the spec.

**Comment by dsyme** [comment]
Please fix this issue at https://github.com/Microsoft/visualfsharpdocs
