### ISSUE TITLE
error FS0193: internal error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by rojepp** [Microsoft/visualfsharp#706]
_From @fwaris on October 28, 2015 18:36_

The error can be reproduced by running the following two lines (need sql server installed):

#r @"C:\Program Files (x86)\Microsoft SQL Server\120\SDK\Assemblies\Microsoft.AnalysisServices.DLL"
let s = new Microsoft.AnalysisServices.Server()

Basically the 'printing' system cannot handle the layout for "s" above.

The workaround for now is to add a custom printer:
fsi.AddPrintTransformer(fun (s:Microsoft.AnalysisServices.Server)-> box "Server")

I tried to trace through the fsi print layout code but since I am not familiar with it, I could not spot the place with the NRE is being raised.

_Copied from original issue: fsharp/fsharp#509_

**Comment by rojepp** [comment]
_From @fwaris on October 28, 2015 18:44_

I have been able to find that the following line (sformat.fs line 543) is the issue because the value "text" is null:

                        let layout = Leaf(jl,(text :> obj),jr) 
                        let textWidth = text.Length

What I am not sure about is why this is so and where the fix should go.

**Comment by rojepp** [comment]
@fwaris I tried to reproduce, but I didn't have that assembly on my computer.  From eye-balling the code, it looks like the only way to get a null in `text` here is if `Microsoft.AnalysisServices.Server.ToString()` returns null, but that seems way too weird. What gets returned if you call `s.ToString()`? Could any of the other vars be null here?

**Comment by rojepp** [comment]
Hah, `s.ToString()` does return null. Sweet. :)

```fsharp
#r @"C:\Program Files (x86)\Microsoft SQL Server\120\SDK\Assemblies\Microsoft.AnalysisServices.DLL"
let s = (new Microsoft.AnalysisServices.Server()).ToString()

// FIS: val s : string = null
```
I guess a null check should go in https://github.com/fsharp/fsharp/blob/master/src/utils/sformat.fs#L1197 ? It should be fine to return the empty string when ToString() returns null?

**Comment by rojepp** [comment]
Could you move the issue to https://github.com/Microsoft/visualfsharp and submit a fix there? It will flow here eventually.

**Comment by rojepp** [comment]
_From @dsyme on October 28, 2015 20:30_

Yes please - thanks @fwaris

**Comment by rojepp** [comment]
@fwaris Will you do this? If not, let me know. Thanks.

**Comment by fwaris** [comment]
thanks! Sorry switch to new email reader (android version of Outlook) kept me from seeing the notifications until now.
