### ISSUE TITLE
support portable pdb files

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/visualfsharp#718]
Portable pdb files are designed specifically for .NET. The [spec is now 1.0](https://github.com/dotnet/roslyn/blob/master/docs/specs/PortablePdb-Metadata.md) and an implementation ships with Roslyn for Visual Studio 2015 Update 1. The new format is cross platform and several times smaller, making it practical to include in the `nupkg`s #294. This should take care of the [CoreCLR status](https://github.com/Microsoft/visualfsharp/wiki/F%23-for-CoreCLR---Status) issue of `Enable CoreCLR debugging of F#`. 

`Microsoft.DiaSymReader.PortablePdb` exists to provide compatibility to the existing Windows debugging tools that build on top of that COM API.
![image](https://cloud.githubusercontent.com/assets/80104/11043080/cdcb632a-86cf-11e5-816a-e46472999d3e.png)

I am advocating that the old PDB support be dropped to makes things simpler and easier to maintain.

**Comment by enricosada** [comment]
No need to deprecate pdb, just add the portable pdb, the user can choose using a compiler flag.
After portable pdb works, can be the default for new projects ( in project templates )

Btw yes, i think portable pdb is not a coreclr only issue, should be send to master, and merged in coreclr later, so we can use it with desktop clr ( .net 4.0 )

**Comment by Alxandr** [comment]
I agree with @ctaggart  that the old PDBs should be deprecated/dropped.

**Comment by dsyme** [comment]
I expect we won't drop for a while, as the compiler will still need to be used for .NET Framework compilation on back-target .NET implementations (4.0-4.6) for several years to come.  There may be a "compat" compiler that is used to achieve this.

But getting the new format implemented would be wonderful.

**Comment by ctaggart** [comment]
I don't think the new pdb format is tied to a .NET Framework version. There is a Microsoft.DiaSymReader.PortablePdb that is [being worked on](https://github.com/dotnet/roslyn/issues/3#issuecomment-155236754) to allow existing Windows debuggers to work with the new format. It would be good to define the test cases for switching.

**Comment by KevinRansom** [comment]
Portable pubs will be generated by the coreclr version of the compiler.  It is the next but one thing on my list.

**Comment by ctaggart** [comment]
Awesome! Looking forward to it. I am going to try to get SourceLink working with them this month.

**Comment by dsyme** [comment]
This has been implemented
