### ISSUE TITLE
SqlDataConnection Suppresses SQLMetal Warnings

### ISSUE THREAD

**Issue by xenocons** [Microsoft/visualfsharp#720]
Hello,

Feature request perhaps, but SqlDataConnection (in Microsoft.FSharp.Data.TypeProviders) suppresses SQLMetal warnings, as such, sometimes stuff is missing from the generated types, to rebug, one needs to run SqlMetal Manually and look for the errors, ideally these type of warnings should be surfaced at compile time.

e.g output of SQLMetal:
```
Warning : SQM1019: Unable to extract stored procedure 'Alerts' from SqlServer because its result set contains columns with the same name 'XXyyyId'.
```

**Comment by dsyme** [comment]
Please move this bug to http://github.com/fsprojects/FSharp.Data.TypeProviders
