### ISSUE TITLE
F# Open Standup:  Monday 11/16/2005 --- 10:00 AM pt 10:30 AM pt

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#721]
Hi,

So for the longest time we have wanted to do an open stand-up for those of us working on the Visual FSharp Tools, nothing mentioned will be NDA so if you are an MVP as well as a contributor and know NDA stuff please don’t discuss it in an open forum.  Let’s try out Skype see how it works out for us.

It is primarily for those who are contributing to, or are interested in contributing to the Visual F# tools open source project.  If you are in that group please join us on this Skype for business meeting, phone in should work if you don't have access to Skype for business.

**Agenda**
It’s a standup … no agenda … A few brief words about what you are working on, what interesting issues have cropped up and what you will to work on next.  If the time doesn’t work for you, then post an issue with your stand-up progress, we will review it.

Be kind, be brief, be present

Thanks

Kevin
.........................................................................................................................................
[Join Skype Meeting](https://meet.lync.com/microsoft/kevinr/ZFRDD3HV)
This is an online meeting for Skype for Business, the professional meetings and communications app formerly known as Lync.

Join by Phone
Toll-free number: +1 (866) 639-0588 
Toll number: +1 (252) 563-4478 
Find a local number 

Conference ID: 630930 

Help   

Welcome to Skype for Business Online Meetings!  Please note, all participants using the Join by Phone option must dial the full number for access to the call! 
[!OC([1033])!]
.........................................................................................................................................

**Comment by NatElkins** [comment]
Are there any plans to record this and post it somewhere?

**Comment by KevinRansom** [comment]
@NatElkins We have no plans to record it, or even to post notes.  The intent is to allow developers actively working on features to share their progress and insights.

**Comment by enricosada** [comment]
Great @KevinRansom !

**Comment by vasily-kirichenko** [comment]
Will join.

**Comment by enricosada** [comment]
thx guys.

@vasily-kirichenko if you want we can chat later (not today) about vs extension and how to move forward the repo, vb -> f# , i'd like to help

some info url https://github.com/Microsoft/VisualStudio-SharedProject/issues/3

**Comment by KevinRansom** [comment]
Roslyn is just about to check-in a project system based on CPS.  We should consider whether we want to follow suit.
