### ISSUE TITLE
Wrong intellisense

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#725]
![image](https://cloud.githubusercontent.com/assets/873919/11181258/d99b776a-8c71-11e5-8a8c-552db7ce42a5.png)

![1](https://cloud.githubusercontent.com/assets/873919/11181327/2f70a822-8c72-11e5-8bc7-9872bcc14f2d.gif)

VS 2013 Update 5

**Comment by KevinRansom** [comment]
Nice find ... thank you.

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2429
