### ISSUE TITLE
No Visual F# project template installed

### ISSUE THREAD

**Issue by EdouardM** [Microsoft/visualfsharp#728]
Hello, 

I selected visual f# in the components to be installed. 

When I open Visual Studio Community 2015 Blend I don't have any project template for F# in the "Installed" Section. See below:
![no_fsharp_template](https://cloud.githubusercontent.com/assets/7335389/11193005/87677f10-8ca4-11e5-8482-cdf91edc1a08.png)

**Comment by KevinRansom** [comment]
Blend does not support Visual F# Tools.  However, If you open Visual Studio that supports F# just fine.

**Comment by EdouardM** [comment]
Hi Kevin, 

Thank you for your answer. 

I am not sure I understand you. I tried to open one example project found in the "online" section. 
I chose one F# project and the  .fsproj file was not recognized. It looks like I don't have Visual F# installed whereas it is checked when I review my install of Visual Studio (see my last screen shot)
