### ISSUE TITLE
F# Open Standup: Monday 11/23/2015 --- 10:00 AM pt 10:30 AM pt

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#729]
Welcome to the F# Open Standup,

It is primarily for those who are contributing to, or are interested in contributing to the Visual F# tools open source project. If you are in that group please join us on this Skype for business meeting, phone in should work if you don't have access to Skype for business.

Agenda
It’s a standup … no agenda … A few brief words about what you are working on, what interesting issues have cropped up and what you will to work on next. If the time doesn’t work for you, then post an issue with your stand-up progress, we will review it.

Thanks

Kevin
.........................................................................................................................................
 Join Skype Meeting      
This is an online meeting for Skype for Business, the professional meetings and communications app formerly known as Lync.

Join by Phone
Toll-free number: +1 (866) 639-0588 
Toll number: +1 (252) 563-4478 
Find a local number 

Conference ID: 630930 

Help   

Welcome to Skype for Business Online Meetings!  Please note, all participants using the Join by Phone option must dial the full number for access to the call! 
[!OC([1033])!]
.........................................................................................................................................

**Comment by enricosada** [comment]
link?

**Comment by NumberByColors** [comment]
https://meet.lync.com/microsoft/kevinr/HJC6769M
