### ISSUE TITLE
FSI 14.0.23020.0 reports wrong script source line number for exception thrown

### ISSUE THREAD

**Issue by geandbe** [Microsoft/visualfsharp#734]
Executing snippet below under FSI 14.0.23020.0

```F#
let func (text:string) =
    let a = 1/0
    for i in 0..2..text.Length do
            printfn "%c" (text.Chars(i))

func "aabb"
```

reports

```
System.DivideByZeroException: Attempted to divide by zero.
   at FSI_0002.func(String text) in C:\Users\gene\AppData\Local\Temp\2\~vsA9B1.fsx:line 2
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in C:\Users\gene\AppData\Local\Temp\2\~vsA9B1.fsx:line 6
Stopped due to error
```

as expected. Now if we substitute line 2 by

    let a = 1/1

and execute the snippet again, FSI reports

```
a
b
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FSI_0002.func(String text) in C:\Users\gene\AppData\Local\Temp\2\~vsA9B1.fsx:line 2
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in C:\Users\gene\AppData\Local\Temp\2\~vsA9B1.fsx:line 6
Stopped due to error
```

which is apparently off, source of exception should be line 4. 

Running the same snippet by FSI 12.0.30815.0 correctly reports the source of exception as line 4.

**Comment by dsyme** [comment]
This is something to do with either .NET or F# optimized code.  Could you try running with --optimize- as an F# Interactive flag?

**Comment by geandbe** [comment]
Don,  the observed behavior is agnostic of --optimize flag.

**Comment by dsyme** [comment]
OK.  Feels a lot like something that is out of our control though...

**Comment by dsyme** [comment]
I think we will resolve this as external - I believe the same problem would repro in C#.  An issue could be added to the .NET Core repo though I suspect it might be by-design.  We can be reopened if proved wrong :)
