### ISSUE TITLE
Computation expression name is not colored in the "preview" mode until it's clicked

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#735]
![1](https://cloud.githubusercontent.com/assets/873919/11319599/691a8830-908d-11e5-8308-82242d6d9a40.gif)

**Comment by dsyme** [comment]
Almost a feature :)

**Comment by enricosada** [comment]
:smile:

**Comment by dsyme** [comment]
While I see the problem and it is a bug, I'm going to close this as "won't fix", at least until we find some more major ramification of the problem.

**Comment by enricosada** [comment]
@dsyme it's a trivial bug, but it's a bug

**Comment by vasily-kirichenko** [comment]
:(

**Comment by 7sharp9** [comment]
Instead of closing it, why not just label it as `minor` and `up-for-grabs`?

**Comment by dsyme** [comment]
OK, reopening

**Comment by abelbraaksma** [comment]
Perhaps related, and making this but a trifle more relevant: if the computation expression name is function / constructor call, it is not colored as a computation expression name at all.

Example code to repro:

    type MaybeBuilder1() =
        member __.Bind(x, f) = match x with None -> None | Some a -> f a
        member __.Return(x) = Some x

    type MaybeBuilder2(rt) =
        member __.Bind(x, f) = match x with None -> rt, None | Some a -> rt, f (a)
        member __.Return(x) = rt, Some x


    [<AutoOpen>]
    module TBuilders = 

        let may = MaybeBuilder1
        let may2 = MaybeBuilder2
        let may2a = new MaybeBuilder2(42)

        let test1 = 
            may() {
                return 1
            }

        let test2 = 
            may2(42) {
                return "test"
            }

        let test2a = 
            may2a {
                return "test"
            }

![coloring of builders](https://cloud.githubusercontent.com/assets/16015770/11561206/16a4acce-99c6-11e5-8944-125bc401a671.png)

**Comment by vasily-kirichenko** [comment]
An addition to this: F# files do not "previewable" in VS 2017, so we cannot even verify if this bug is still reproducible (however, as we use Roslyn API for syntax highlighting in VS 2017, it's likely to be fixed).

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/pull/2417

**Comment by vasily-kirichenko** [comment]
This bug has never reproduced in VS 2017.
