### ISSUE TITLE
Change ALT+Enter to CTRL+Enter when sending to the FSI

### ISSUE THREAD

**Issue by jamessdixon** [Microsoft/visualfsharp#736]
The Python Tools for Visual Studio and R Tools for Visual Studio are both going to use CTRL+Enter when sending code to the REPL.  I want to say that C# REPL in C#7 is also going to use CTRL + ENTER.   Does it make sense to keep consistent across all of the languages in Visual Studio?

**Comment by dsyme** [comment]
Closing inactive discussion
