### ISSUE TITLE
Query expression is generating the wrong type when grouping on tuples

### ISSUE THREAD

**Issue by chkeita** [Microsoft/visualfsharp#741]
The expected type of the grouping in the follwing expression is 

``` F#
IGrouping<int,(int * bool * string)>
```

 but here we get 

``` F#
IGrouping<int,(string * int * bool)>
```

Looks like the type of the tuple is getting rotated

``` F#
query {
    for (i,b,s) in query{ yield (1,true,"test")} do
    groupBy i into g
    select g
};;
//val it :
//  System.Linq.IQueryable<System.Linq.IGrouping<int,(string * int * bool)>> =
//  <seq>
```

**Comment by enricosada** [comment]
can that be related to #277 ?

**Comment by dsyme** [comment]
Yes, see #277 for explanation, you will have to iterate the groups and re-select

**Comment by kcheick** [comment]
Is there a rule to know how the tuple is supposed to be reconstructed
the reordering does not seem to be consistent with different number of elements in the tuple
```F#
query {
    for (i,b,s,b2) in query{ yield (1,true,"test", 0.5)} do
    groupBy i into g
    select g
} 

//val it :
//  val it :
//  System.Linq.IQueryable<System.Linq.IGrouping<int, (string * int * float * bool)>>
//= <seq>

```
This exemple is just for illustration but there are situation where i want to group on tuple with the same type and it makes it hard to know what the value represents. Is there any guidance for dealing with these cases ?

**Comment by dsyme** [comment]
I believe it is reverse-alphabetical order.  Not exactly obvious nor intended, though I'm not sure how to make progress on changing this while respecting backwards compat. Any ideas?

**Comment by cartermp** [comment]
This discussion is quite old. @dsyme should this be a bug?

**Comment by dsyme** [comment]
I think we can close it, it's just an oddity
