### ISSUE TITLE
Issues do not use the published labelling scheme yet.  We need to make it so.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#752]

**Comment by enricosada** [comment]
for others like me who didnt see the readme change, it's the roslyn label list https://github.com/dotnet/roslyn/wiki/Labels-used-for-issues

**Comment by enricosada** [comment]
let's use more the label ![](https://cloud.githubusercontent.com/assets/20570/11489952/e06cc1ee-9788-11e5-9b78-4dc77357a435.png) :smile:
