### ISSUE TITLE
Large, single-file sources of F# get the line number and debug-stepping totally wrong

### ISSUE THREAD

**Issue by abelbraaksma** [Microsoft/visualfsharp#758]
If your source file is sufficiently large (essentially, over 2^16 or 64k lines long) the line number used when source stepping, or the curlies that you on syntax errors, are reported on totally wrong lines (essentially, current line minus 2<sup>16</sup>).

This may not happen often in practice, but if it happens, it is highly confusing. I suggest to either raise a compile error "source file to large, maximum of 65535 lines reached, consider splitting your source in multiple source files" or to allow a integer instead of a short for the line number counter. I don't think it is a limitation of .NET or Visual Studio, large auto-generated source files in C# do not exhibit this problem.

A practical issue with this is specifically autogenerated files, for instance, we use a Dynamics CRM mapping which generates a single file of 350k lines for the entity mappings using Microsoft tooling. Converting that to F# is currently not an option.

Since the auto-created function names use line numbers to identify them, this has the effect that line numbers on such functions point to the wrong location. I have not tried whether this could confuse the compiler in creating such names.

This was also [reported on StackOverflow with a screenshot](http://stackoverflow.com/questions/33794570/the-mystery-of-blind-source-stepping-or-how-f-behaves-erratically-on-large-sou).

See how the debugger stops at a blank line, how the selection is wrong, and how the code-coverage tools report non-existing lines as hit:

![b4afq](https://cloud.githubusercontent.com/assets/16015770/11570310/e27d6cca-99f6-11e5-89c2-26d87b3f921a.png)

A by-product of this behavior is that setting a breakpoint with F9 will actually set it on the non-existing line, as if no breakpoint was set on the actual code.

Note, surprisingly, `__LINE__` stores the correct line information.

---

PS: previously, and in some comments, this entry also showed an example that, next to the wrong line numbers being reported, also crashed Visual Studio. I have now moved that into a separate bug entry: #779.

**Comment by dsyme** [comment]
Yes, this is indeed a limitation with the implementation of the ``range` type in range.fs, which stores location information in a limited range of bits.  But looking at the above it seems your very large file is generated  C# code?  Or is it F# code?

**Comment by abelbraaksma** [comment]
Hi Don, thanks for your answer. I have added a repro to the original report as while reproing I found a related bug that kinda changes the bug report as a whole. As such I updated the text a bit.

The screenshot above is from an FSharp project, with FSharp code in it. That one didn't crash the FSharp compiler, at least not all the time. I will try to create a non-crashing repro as well.

If this is a limitation of F#, I think at the very least it would be a good thing if the compiler, upon finding too many lines, issues a warning, or an error. And of course, it shouldn't crash Visual Studio and everything in it ;).

**Comment by abelbraaksma** [comment]
[FSharpBug758-repro1.zip](https://github.com/Microsoft/visualfsharp/files/56915/FSharpBug758-repro1.zip)

This repro shows F# behavior on large files by printing line information from `__LINE__`, the internal function decoration mechanism and from .NET's `StackFrame`. It can also be observed that Lint thinks this file module is 12931 lines long, while in fact is is 144004 lines long (but that's probably out of scope for this bug report).

![fsharp-bug-758-1](https://cloud.githubusercontent.com/assets/16015770/11688583/c68b613e-9e8d-11e5-8f5e-6a20e4dc575d.PNG)

If you run it in Debug or Release mode (code is different for both versions because the F# compiler's optimization inlines differently when optimizations are on), you'll get output that looks something like this:

    [... snip...]
    Real line  62000, decorated: 62000, stack: 62000 (fu@62000-434)
    Real line  63000, decorated: 63000, stack: 63000 (fu@63000-441)
    Real line  64000, decorated: 64000, stack: 64000 (fu@64000-448)
    Real line  65000, decorated: 65000, stack: 65000 (fu@65000-455)
    Real line  66000, decorated:   464, stack:   464 (fu@464-462)
    Real line  67000, decorated:  1464, stack:  1464 (fu@1464-469)
    Real line  68000, decorated:  2464, stack:  2464 (fu@2464-476)
    Real line  69000, decorated:  3464, stack:  3464 (fu@3464-483)
    [... snip ...]

As you can see, the line numbering (as Don already confirmed) starts from zero (464) again. Between the parentheses is the decorated name of the current function.

Another observation: the repro in the zip _does not allow you to set any breakpoint other than the first few lines_. Change the first `fu`-line from line 1000 to line 771, and selecting a breakpoint works again, everywhere (albeit on the wrong physical offset). There seems to be some relation to the size of the file, but I couldn't quite understand what was happening, because sometimes increased sizes still allowed breakpoints.

**Comment by cartermp** [comment]
Fixed in #4476

**Comment by abelbraaksma** [comment]
Fantastic! Thanks!
