### ISSUE TITLE
F# compiler bug in release mode in VS2015 Update 1

### ISSUE THREAD

**Issue by richardcallen** [Microsoft/visualfsharp#759]
In F# compound loops where the sequences are defined locally, in release mode only, F# generates a compile-time error saying that the name of the sequence being looped over is not found, generating error FS0971: Undefined value. Bizarrely this seems to be the case only when the outer loop is over the elements of a set.
I am using Visual Studio 2015 Update 1 RTM - 14.0.24720.00

I have managed to repro this in a few simple lines of code. Please see below.

**Comment by richardcallen** [comment]
Code for the repro is below. The upload of zip files does not seem to be working.
// Learn more about F# at http://fsharp.org
// See the 'F# Tutorial' project for more help.

module Stuff = 

    /// Does not compile in release build
    let f() =
        let currencies = set [ 1 ; 2 ; 3 ]
        let expiries = [ 3 ; 4 ]
        for ccy in currencies do
            for expiry in expiries do
                printfn "Done"

    /// Does compile in release build
    let f2() =
        let currencies = [ 1 ; 2 ; 3 ]
        let expiries = [ 3 ; 4 ]
        for ccy in currencies do
            for expiry in expiries do
                printfn "Done"
[<EntryPoint>]
let main argv = 
    Stuff.f()
    Stuff.f2()
    0 // return an integer exit code

**Comment by mjmckp** [comment]
Replacing 'set' with 'seq' above also causes the compile error.

**Comment by dsyme** [comment]
This is the same as the bug fixed by https://github.com/Microsoft/visualfsharp/pull/756.  Let's use this as the tracking issue for the problem.

**Comment by KevinRansom** [comment]
Fix merged:  
commit:
https://github.com/Microsoft/visualfsharp/commit/c1e0bc806f00db5da90cc996871afae9bee047e6
PR:
https://github.com/Microsoft/visualfsharp/issues/759

**Comment by KevinRansom** [comment]
Thank you for reporting this.  The fix is in, it will be in the next release of Visual F#.

**Comment by dsyme** [comment]
f you _do_ need to get your code to compile and you are using Update 1, it appears sufficient to place something benign prior to any loop where this problem is occurring, like this:

```
// do something that doesn't get optimized away
let workaround() = null |> ignore  

let configure () =
 let aSequence = Microsoft.FSharp.Core.Operators.(..) 3 4
 let aString = new string('a',3)
 workaround()
 for _ in aSequence do
   System.Console.WriteLine(aString)

configure ()

```

That said I really hope a fix is made available as soon as possible.

Obviously these calls should be removed as soon as a fix release is made available.
