### ISSUE TITLE
const reserved keyword warning message

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#761]
both `fori` and `const` are reserved keyword, but the warning message is different ( [SO question](http://stackoverflow.com/questions/32834580/what-is-f-const-keyword) )

```fsharp
> let fori = 3;;

  let fori = 3;;
  ----^^^^

stdin(115,5): warning FS0046: The identifier 'fori' is reserved for future use by F#
```

instead

```fsharp
> let const = 3;;

  let const = 3;;
  ----^^^^^

stdin(116,5): error FS0010: Unexpected keyword 'const' in binding
```

there is an use on `const` i dont know about, or is only reserved? /cc @dsyme

**Comment by dsyme** [comment]
See comment here https://github.com/Microsoft/visualfsharp/issues/507#issuecomment-161983644
