### ISSUE TITLE
Appveyor Error running tests\Upload-Results.ps1

### ISSUE THREAD

**Issue by WilliamBerryiii** [Microsoft/visualfsharp#767]
The appveyor build is throwing errors 'fileName' is null when calling Upload-Results.ps1.  Please see example from lines 3900+ here: https://ci.appveyor.com/project/KevinRansom/visualfsharp-radou/build/0.0.1.1126

**Comment by WilliamBerryiii** [comment]
Additionally, If this information is  important ... should the build fail if the data is not uploaded.

**Comment by enricosada** [comment]
duplicate of #754
