### ISSUE TITLE
Mutable field of struct is not changed as expected by struct member

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#77]
Originally reported on [CodePlex](https://visualfsharp.codeplex.com/workitem/207) by [Greatim](https://www.codeplex.com/site/users/view/greatim)
```fsharp
[<Struct>]
type TestStruct =
    val mutable _x:int
    new(x) = {_x = x}
    member this.Set(x) = this._x <- x

member this.X with get() = this._x;
let a = TestStruct(2)
let c() =
    a.Set 10
    a.X
c();;
```
the value of "c( )" is 2!! Why the value of "a.X" didn't change，bug this code compile well?

**Comment by vladima** [comment]
1. Title of the bug is not related to the bug itself
2. As I see this behavior is expected, immutable `let` binding defensive copy triggered creation of the copy. If  mutation of the struct is expected - define `let` binding as `mutable`

**Comment by latkin** [comment]
The title was incorrectly copied form Codeplex, I've updated it.

**Comment by dsyme** [comment]
Yes, this is by design. You would have to use "let mutable a = TestStruct(2)"
