### ISSUE TITLE
FSharp Class Library (package) option missing from VS2015 with ASP.NET 5 RC1

### ISSUE THREAD

**Issue by bluemmc** [Microsoft/visualfsharp#770]
Apparently, there is a new and better way to create VS 2015 class library projects that is introduced with ASP.NET 5 but not limited to web projects. This new project type is called a "Class Library (package)" and works better with NuGet, TFS merges, cross-platform etc. It would be good if F# tooling support this project type.

**Comment by dsyme** [comment]
Closing as this is subsumed by .NET Core tooling in geneal
