### ISSUE TITLE
Wrong warning on non compilable source

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#777]
![image](https://cloud.githubusercontent.com/assets/873919/11678952/95c2ddb4-9e5d-11e5-8c9a-fc065fb49235.png)

I don't think the compiler should emit such warning if a type contains fields of unknown type (because of missing open statement of typo).

``` fsharp
namespace Monitor.Web.Alarms

[<RequireQualifiedAccess>]
type AlarmStatus =
    | Alert
    | OK
    | NoData
    | Warn
    | Silenced

type AlarmId = Guid

type AlarmOverview =
    { Id: AlarmId
      Name: string
      Status: AlarmStatus
      Updated: DateTime }
```

**Comment by dsyme** [comment]
Doesn't repro on master (unless I'm mistaken)
