### ISSUE TITLE
Improve first use experience

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#78]
This was first posted on [codeplex](https://visualfsharp.codeplex.com/workitem/187) by [Tomasp](https://www.codeplex.com/site/users/view/tomasp)

When you clone the repo for the first time, there is a couple of things that make the first experience annoying:
*I downloaded the code and tried opening "fsharp.sln" to look at it - this does not work (the projects fail to load in VS 2013), because you first need to build the proto compiler (which generates some targets file that is referenced from the projects). This is pretty bad first-open experience!

* Next, I tried to follow the DEVGUIDE. Now, "gacutil" in step 1 is not usually in your PATH - but I knew that so I opened VS Command Prompt (Windows search returned command prompt for VS 2012 though!) and I ran the "gacutil" command. This failed because I need Admin rights (which is not mentioned in the DEVGUIDE), so I had to reopen the prompt in admin mod.

* I tried running the "msbuild" command next, which failed (with confusing error involving resource manifests - it actually looks like a real error in the code!) This was because I used wrong MSBUILD version (the one from VS Command Prompt 2012).

I guess you should be able to open "fsharp.sln" when you get the code (even if you do not want to build anything). The MSBUILD issues can be expected - but the error should be better (or the guide should be more clear about this).

>comments
>latkin wrote Dec 17, 2014 at 4:09 PM [x] 

>I have a pending update internally which will remove the need for GACing the old FSharp.Core version. This will help a lot - no more need for admin on first build. 

>We can update DEVGUIDE to point to  https://visualfsharp.codeplex.com/wikipage?title=Required%20Software which lists MSBuild 12.0 as a requirement and provides a download link. VS is linked, too, but 2013 is not explicitly stated as the version. Certainly this could be polished. 

>I don't have a good answer for the proto targets. Making that "just work" first time with no user action will require nontrivial refactoring of how the repo is set up.

**Comment by tpetricek** [comment]
cc @tpetricek

**Comment by latkin** [comment]
@tpetricek do you feel this has improved any? The following is in place:

- `gacutil` is no longer needed on first build of proto
- `README` [links](https://github.com/Microsoft/visualfsharp#development-and-testing) directly to [Required Software page](https://github.com/Microsoft/visualfsharp/wiki/Required-Software), which lists VS 2013 (and thus msbuild 12.0) as requirements

You still need to build proto before you open the sln though.
