### ISSUE TITLE
We read some settings from the devenv.exe.config file --- devenv.exe.config is not user mutable

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#786]
We need an alternate mechanism to enable these features:

	// App.config keys for determining whether not-shipping features are turned on or off
	// Edit devenv.exe.config and place these at the end.
	// <appSettings>
	// <add key="fsharp-regions-enabled" value="true" />
	// <add key="fsharp-navigationbar-enabled" value="true" />
	// <add key="fsharp-standalone-file-intellisense-enabled" value="false" />
	// </appSettings>

Because of this design the powertools who used this feature correctly, happened to cause VS update 1 to do bad things to people who use Dev 15 and the PowerTools.

**Comment by dungpa** [comment]
I think these settings should be exposed via F# Editor options in Visual Studio. Ideally they are turned off by default. In doing so, we should be able to improve these features gradually.

We're looking forward to removing these settings from VFPT. Doing it in VFPT was a bad idea since we haven't been able to fix bugs when users report them.

**Comment by KevinRansom** [comment]
Editor options is a good idea.  I had thought registry to enable you to continue to turn them on, but we could certainly add options, instead.

**Comment by abelbraaksma** [comment]
Would it be possible to have all options disabled when you open VS in safe mode? This might help in case such new features cause startup issues with VS. Or at least some other way to override the settings from the commandline or otherwise, regardless of what's selected under F# Editor Options.

**Comment by dsyme** [comment]
I think these features should be taken out of VFT (fully disabled) and added to VFPT.  They would end up much higher quality that way

**Comment by dsyme** [comment]
I don't think we would accept bug fixes to these features directly into VFT on grounds of stability

**Comment by otawfik-ms** [comment]
As part of #913, these keys/opposite functionality would be removed, and we would depend on Roslyn's infrastructure for that. Work is done on `roslyn `branch:
https://github.com/Microsoft/visualfsharp/tree/roslyn
