### ISSUE TITLE
Visual Studio tooling for F# DNX for more important projects then I thought - in fact key for F# viability

### ISSUE THREAD

**Issue by bluemmc** [Microsoft/visualfsharp#788]
I have looked at ASP.NET 5/vnext (RC1) and the changes it introduce goes far beyond just a new web project version.

A key change is new type of (package) project based on DNX that completely changes how tooling,  Visual studio integration and the compilation/execution environment works. These package projects works for non-web projects as well and my impression is that they will (in time) replace the old project types as the package projects has many benefits and works far better then the old project types. Right now only C# package projects can be created but VB package projects are coming. 

At my company we are doing new developments using DNX package projects already and I will be unable to introduce F# (as I am trying to do) if Visual Studio does not have F# support for this new project type. 

The existing "fsharp-dnx" project plans to help with F# DNX support but will not offer any support for using Visual Studio (projects will NOT be compatible with Visual Studio). It is also limited and will also not allow C# projects that depends on F# projects (as I need in order to introduce F# in our organisation). 

Hence, there are missing pieces that I do not think anyone is addressing. Sooner or later, without Visual Studio support for DNX package projects in F# (and combining such projects with C# projects) the future of F# seems in question. -At least for anyone using Visual Studio with new package projects.

**Comment by KevinRansom** [comment]
We are doing the best we can to keep up with the very fast moving .Net landscape.  Right now we are in the process of porting the compilers to coreclr.  You can checkout the coreclr branch for progress.  Right now the compiler and Fsi can both run and do work on Linux with coreclr.  Additional tooling will come as we get the bandwidth to implement.  There are several other OSS projects addressing specific cross platform and aspects vnext d# tooling needs.

**Comment by KevinRansom** [comment]
It is also the perfect time to get involved in addressing the shortfall.  We welcome contributions from fellow OSS developers addressing tooling shortfalls.

**Comment by KevinRansom** [comment]
@bluemmc could you outline what support is missing.  We have a branch coreclr where we are building the compiler and FSI to run on coreclr, which is obviously a precursor to supporting asp v.next.  We are also adding to dotnet cli support for F#, which is clearly an additional step.

What would you suggest be the steps after that?  And are there any that you would be interested in piloting, or is your observation more in the shape of a feature request?

Thanks

Kevin

**Comment by bluemmc** [comment]
Typical user scenario that I think should be supported is to add a package F# project with some business logic to a package based C# solution, so the C# code in one project can call into F# code in another project or the reverse (This solution might be related to ASP.NET 5 but can also be a console application, server application, desktop application etc - just something that use the new DNX packages).

For this I guess the following is needed:
1) Basic support for F# DNX package project outside visual studio - addressed by "fsharp-dnx" project. Check!
2) CoreClr support for F# - addressed also already. Check!

3) Support outside visual studio for F# DNX package project that depend on other C#/F# projects in same solution. Do not think this is addressed by "fsharp-dnx" project which maybe only supports nuget dependencies but I am not sure ?
4) Visual studio support for creating (and building/debugging etc.) a F# DNX package project - missing feature and not addressed by any project I know of.
5) Visual studio support for adding a reference to the F# package project from a C# package project without giving an error. - missing feature and not addressed by any project I know of.
6) Visual studio support for adding a reference to a C# package project from the F# package project. - missing feature and not addressed by any project I know of.

PS: I am just beginning with F# so I am not a good candidate (have unfortunately, no time for the next 7 months anyway).

**Comment by dsyme** [comment]
Closing old discussion
