### ISSUE TITLE
Parsing of generics within pattern match rules fails

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#79]
This was opened on [CodePlex](https://visualfsharp.codeplex.com/workitem/54) by [ranma42](https://www.codeplex.com/site/users/view/ranma42)

From my understanding, all the three test{1,2,3} functions should be legitimate, but they result in the following errors:
F# Compiler for F# 3.1 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License
/Users/ranma42/Code/sharp/datalog/test-match.fs(10,12): error FS0010: Unexpected identifier in pattern. Expected infix operator, quote symbol or other token.
/Users/ranma42/Code/sharp/datalog/test-match.fs(14,14): error FS0010: Unexpected type application  in pattern matching. Expected '->' or other token.
/Users/ranma42/Code/sharp/datalog/test-match.fs(18,16): error FS0010: Unexpected identifier in pattern. Expected infix operator, quote symbol or other token.
/Users/ranma42/Code/sharp/datalog/test-match.fs(18,8): error FS0583: Unmatched '('
I hit this issue while trying to pattern match on a provided type as in
```fsharp
let inline (|ParseRegex|_|) regex str =
  if (^T : (static member IsMatch : string -> bool) (str)) then
    Some (^T : (member Match : string -> 'U) (regex,str))
  else
    None
let parse str =
  match str with
    | ParseRegex RegexTyped<"test">.I m -> printfn "match %A" m
    | _ -> printfn "mismatch"
```
but I found out that I could not match in most (all?) cases where the rule includes a <...> syntax. 

Is this a limitation of the parser?

file attachments
 
test-match.fs

>comments
>latkin wrote Jun 20, 2014 at 6:45 AM [x] 
>The example from the attached file captures the issue nicely (easier to understand than the regex example):
>Basically, why does this work:
```fsharp
let (|Is|_|) v x =
  if v = x then
    Some x
  else
    None

>let intNone = Option<int>.None

>let test1 = function
  | Is intNone x -> "None"
  | _ -> "Not none"
```
>but this doesn't
```fsharp
let test2 = function
  | Is (Option<int>.None) x -> "None" // invalid argument to parameterized pattern label
  | _ -> "Not none"
```

>>latkin wrote Jun 20, 2014 at 6:54 AM
>>Interesting, I get the above typecheck error in the IDE, but when I try to actually compile as source, >>I get parse error same as original report.
>>TestLibrary.fs(10,17): error FS0010: Unexpected identifier in pattern. Expected infix operator, quote symbol or other token.
>>TestLibrary.fs(10,8): error FS0583: Unmatched '('

**Comment by dsyme** [comment]
This is expected - the F# language has never accepted type parameters in pattern position like this

Please add an entry at http://fslang.uservoice.com to suggest lifting this limitation?

Thanks!
Don
