### ISSUE TITLE
Documentation of F# 4.0 and later is not available on MSDN Library of Visual Studio 2015

### ISSUE THREAD

**Issue by eriawan** [Microsoft/visualfsharp#790]
Hi,

After I read the CHANGE.MD of F# 4.0, I have tried to reach documentation of F# 4.0 on MSDN Library of Visual F# on Visual Studio 2015:
https://msdn.microsoft.com/en-us/library/dd233154(v=vs.140).aspx

But I've puzzled by the fact that the page contain this info:

![vs2015_fsharp_msdnlibrary_20151212](https://cloud.githubusercontent.com/assets/8773147/11762414/c8af16d6-a117-11e5-903a-5d537a158328.png)

As attached, the page has "subtitled" and categorized as part of Visual Studio 2015, but in the documentation it says the documentation is for Visual F# 3.1. I also find out that there's no page in MSDN Library that describe "What's new" on Visual F# 4.0.

I also have installed the "offline" help documentation for Visual Studio 2015 Update 1, and I can't find it either! :frowning:

**Comment by dsyme** [comment]
Please see Visual F# doc project at https://github.com/Microsoft/visualfsharpdocs where people are adding support for F# 4.0 constructs to the docs

**Comment by eriawan** [comment]
@dsyme 

Thanks for closing this issue! :smile:  Apologize that I should close this issue, I almost forgot.
I also jump in to adding the necessary doc to the F# doc repo.

:+1: for opening doc participation to public, kudos for all of F# team members!
