### ISSUE TITLE
With C# Interactive introduction in 2015 Update 1 Interactive tool windows look inconsistent

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/visualfsharp#793]
<img width="1057" alt="interactive windows" src="https://cloud.githubusercontent.com/assets/2365592/11768564/ba24bcf2-a1d9-11e5-9e54-9ef15c877286.png">

As you can see on a screenshot C# and PowerShell interactive behave more like editors and there even work [Viasfora](http://viasfora.com/) features like Rainbow Brackets.
But F# Interactive looks more like a Command Windows.

Will you update F# Interactive to provide common functionality and look?

**Comment by abelbraaksma** [comment]
> Will you update F# Interactive to provide common functionality and look?

You may be interested in knowing that some effort has been put forth in enabling IntelliSense in FSI: http://alekseyv-dev.blogspot.nl/2015/10/implementing-f-interactive-intellisense.html, though I am not sure whether it will be added to the vNext (it's on github, so you can experiment with it).

**Comment by xperiandri** [comment]
Thanks for telling me about this extension. I already installed it and glad that @vasily-kirichenko crated it.
As I understand from a look of Interactive tool windows F# just uses old one window and C# and PS modern one. I guess so.

**Comment by enricosada** [comment]
F# interactive is fsi console output.
There is a new control for interactive windows used by nodejs, python, and roslyn, i tried to import the codebase with #733 ( from python/nodejs ), but because visualfsharp support only vs 2015 we can directly use this control ( python/nodejs support older version of visual studio, and clone the source of this control ).
If someone want to try that, there is an example of usage inside PTVS or nodejstools repository

**Comment by xperiandri** [comment]
Could you explain what do you propose to do?

**Comment by KevinRansom** [comment]
Yes ... 

I agree the FSI window for VB and C# have a different experience from F#.  The debugger window expression evaluators for F# doesn't even support F# syntax, e.g. use an F# array or the pipe operator in a debugger expression,  and neither does the immediate Window.  So .. it is fair to say that the "consistency" of F# is not that high.  

Whether FSI should support colouring and intellisense is a long runner matter of debate.  I have heard @dsyme say many times that, allowing a developer to type into the FSI window was a mistake.  Personally I would be okay with it, however, If I am using FSI in VS, it's never ... ever to type code into the FSI window. When using FSI in VS I only ever use a script file and send commands to the FSI window.  An FSI script file, has syntax coloring, intelli-sense and the VF# power tools support it too.

If a community member can provide a high quality submission that enables these features, then we would certainly consider it for inclusion.

Just as a heads up -- Roslyn handles the CSI intellisense and code colouring in-process in Visual Studio.and so the "experimental" intallisense feature built-into fsi.exe is not the correct place to start.  the VS-FSI window should use the same services as are currently used for FSX files to achieve this.

Hope this helps

Kevin

**Comment by dsyme** [comment]
Closing this old discussion
