### ISSUE TITLE
Bugs in provided methods with static parameters

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#795]
The TP:

```fsharp
[<TypeProvider>]
type Provider1 (_config: TypeProviderConfig) as self =
    inherit TypeProviderForNamespaces()
    let ns = "TypeProviderSandbox"
    let asm = Assembly.GetExecutingAssembly()
    let rootType = ProvidedTypeDefinition(asm, ns, "Provider1", Some typeof<obj>, HideObjectMethods = true)
    let cache = new MemoryCache("HexProvider")
    let rootParams = [ProvidedStaticParameter("GeneratingMethodName", typeof<string>)]
    do rootType.DefineStaticParameters(rootParams, fun typeName args ->
        lazy
            let rootTy = ProvidedTypeDefinition(asm, ns, typeName, Some typeof<obj>, HideObjectMethods = true)
            let innerTy = ProvidedTypeDefinition("InnerType", Some typeof<obj>, HideObjectMethods = true)
            let methodName = args.[0] :?> string
            if methodName.Length < 3 then failwith "Method name must be at least three letters long"
            let m = ProvidedMethod(methodName, [], innerTy, IsStaticMethod = true)
            let methodParams = [ProvidedStaticParameter("WhatToReturn", typeof<string>)]
            m.DefineStaticParameters(methodParams, fun methodName methodArgs ->
                let valueProp =
                    match methodArgs.[0] :?> string with
                    | "now" -> ProvidedProperty("Value", typeof<DateTime>, IsStatic = false, GetterCode = fun _ -> <@@ DateTime.Now @@>)
                    | "year" -> ProvidedProperty("Value", typeof<int>, IsStatic = false, GetterCode = fun _ -> <@@ DateTime.Now.Year @@>)
                    | _ -> failwithf "WhatToReturn must be either 'now' or 'year'"
                
                innerTy.AddMember valueProp
                let m2 = ProvidedMethod(methodName, [], innerTy, IsStaticMethod = true, InvokeCode = fun _ -> <@@ obj() @@>)
                rootTy.AddMember m2
                m2
            )
            
            rootTy.AddMember innerTy
            rootTy.AddMember m
            rootTy
        |> cache.GetOrAdd typeName)

    do self.AddNamespace(ns, [rootType])
       self.Disposing.Add <| fun _ -> cache.Dispose()

[<assembly:TypeProviderAssembly>]
do ()
```
* Root type accept a string static parameter and generates a static method with the same name, which returns an inner generated type `InnerType`.
* The method accepts another string static parameter and adds a property `Value` to `InnerType`. The return type and value of this property depends on the static parameter value: "now" => DateTime, DateTime.Now, "year" => int, DateTime.Now.Year. If the argument has other value, then an exception is raised. 

Issues:

* If a unexpected string is passed to the provided method's static parameter, then VS shows generic error instead of our exception's `Message`: "The type provider 'TypeProviderSandbox.Provider1' reported an error: Exception has been thrown by the target of an invocation."
![image](https://cloud.githubusercontent.com/assets/873919/11820606/6ac869bc-a376-11e5-955b-ffc0c50629c3.png)
Compare it with error which is shown if we pass wrong string to the type static parameter:
![image](https://cloud.githubusercontent.com/assets/873919/11821162/3cc6199e-a379-11e5-8e33-10995c4c4a3b.png)

* VS and FSI cache `Value` property and does not change it according to its static parameter:

![1](https://cloud.githubusercontent.com/assets/873919/11820997/6967f22a-a378-11e5-98e4-f179d755d17e.gif)

(resetting FSI helps, but VS is stuck with `int` as return type for `Value`, until a file is reopened)

**Comment by vasily-kirichenko** [comment]
(the bug is not caused by the cache, removing it does not solve the problem)

**Comment by dmitry-a-morozov** [comment]
I guess this the same as
https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/63

**Comment by dsyme** [comment]
The first part of this (the bad error message) was fixed some timme ago

The second part (the property caching) is by design - the line

                innerTy.AddMember valueProp

ends up adding two properties with the same name to ``innerTy`` and returns a different method in two cases associated with that property.  Instead a different ``innerTy`` should be provided for each of the two cases, where the name of ``innerTy`` incorporates ``methodName``
