### ISSUE TITLE
Unary negation applied to derived class instance gives compile time error

### ISSUE THREAD

**Issue by JeffreySax** [Microsoft/visualfsharp#799]
Applying the unary negation operator to an instance of a derived class when only the base class defines the operation results in a compile time error. This is in contrast with binary operators, where the operator definition from the base class is picked up correctly.

The same problem arises with elementary functions (sin, cos...).

    type Base(x : int) =
        member self.X = x
        static member (~-) (a : Base) = Base(-a.X)
        static member (+) (a : Base, b : Base) = Base(a.X + b.X)
        static member Cos(a : Base) = Base(2*a.X)

    type Derived(x : int) =
        inherit Base(x)

    let a = Base(1)
    let minusa = -a // OK
    let cosa = cos a // OK
    let twoa = a + a // OK
    let b = Derived(1)
    let minusb = -b // Compile error
    let cosb = cos b // Compile error
    let twob = b + b // OK

**Comment by mexx** [comment]
What would be your expectations especially in regard to the types of the expressions?

The reason for the compile error is that the unary operators are defined to retain the type of input for the result.

The binary operators on the other hand allow the operands and the result be of different types.

As far as I can read out of the language specs, any operator should allow the result type to be different from the input type(s). @dsyme did I got the idea right?

We could relax the result type of unary operators to be different easily as it's backwards compatible.

**Comment by mexx** [comment]
Btw. the unary operator `sqrt` is already defined in the relaxed way.

```
type Base(x : int) =
    member self.X = x
    static member Sqrt(a : Base) = Base(a.X)
type Derived(x : int) =
    inherit Base(x)

let a = Base(1)
let sqrta = sqrt a // OK
let b = Derived(1)
let sqrtb = sqrt b // OK
```

**Comment by dsyme** [comment]
Yes, the signatures of unary negation and ``cos`` and ``sin`` are all one type parameter, e.g.

``sin : T -> T``

etc.  This is the underlying problem.  ``sqrt`` is ``T -> U``.

This is really a request for a language or core-library design change.  Per CONTRIBUTING.md these should go to http://fslang.uservoice.com.  I've recorded this suggestion: http://fslang.uservoice.com/forums/245727-f-language/suggestions/11356425-optionally-relax-signatures-of-x-sin-x-cos-x-to

The awkward workaround is to upcast as follows:

```
type A(x : int) =
    member self.X = x
    static member (~-) (a : A) = A(-a.X)
    static member Cos(a : A) = A(2*a.X)

type B(x : int) =
    inherit A(x)

let a = A(1)
let b = B(1)
let minusb = -(b :> A) 
let cosb = cos (b :> A)
```

**Comment by dsyme** [comment]
Closing as this is recorded at http://fslang.uservoice.com
