### ISSUE TITLE
Intellisense tooltips for custom operators

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#80]
This was opened on [CodePlex](https://visualfsharp.codeplex.com/workitem/57) by [simtali](https://www.codeplex.com/site/users/view/simtali)

In F# 3.1 (VS2013) Intellisense tooltips don't appear for custom operators that use ".", except when it's the first character. Of the operators below, tooltips work only for the last one.

``` fsharp
let (>>.) x y = ()
1 >>. 2

let (>.>) x y = ()
1 >.> 2

let (.>>) x y = ()
1 .>> 2
```

I emailed fsbugs. Based on their response they experience slightly different behavior:

Thanks for the bug report, I can repro the issue. The tooltips appear only for those parts of the operator to the right of the dot. Using your example and putting the dot in the middle, I get a tooltip for the rightmost >, but not the dot or the leftmost >. If the dot is on the left, then I get tooltips for the two > characters.

> comments
> latkin wrote May 23, 2014 at 3:48 PM [x] 
> Interesting, I had actually reproed with an operator based on <, and oddly enough that behaves differently... Using your exact code (with >) I get the exact same repro as you. Below gives the modified repro quoted in the bug:
> 
> ``` fsharp
> let (<<.) x y = ()
> 1 <<. 2
> 
> let (<.<) x y = ()
> 1 <.< 2
> 
> let (.<<) x y = ()
> 1 .<< 2
> ```

**Comment by vasily-kirichenko** [comment]
I cannot reproduce either of the cases on current master:

![image](https://cloud.githubusercontent.com/assets/873919/21768358/62969f1e-d68a-11e6-965a-9f667d3e4d64.png)

![image](https://cloud.githubusercontent.com/assets/873919/21768392/85866bd0-d68a-11e6-8b88-6f311ee841cc.png)

![image](https://cloud.githubusercontent.com/assets/873919/21768396/8c946170-d68a-11e6-8498-59681e00c869.png)

/cc @simtali
