### ISSUE TITLE
ParamArrayAttribute affects type inference

### ISSUE THREAD

**Issue by JeffreySax** [Microsoft/visualfsharp#800]
The presence of a ParamArray attribute on an array parameter causes type inference to be more restrictive. Consider the following code:

    type Base(x : int) =
        member self.X = x
        static member count1<'a> (x : 'a array) = x.Length
        static member count2<'a> ([<System.ParamArray>]x : 'a array) = x.Length
    type Derived(x : int) = inherit Base(x)

    let a = Base(1)
    let b = Derived(1)

    let n1 = Base.count1<Base> [| a; b |] // OK
    let n2 = Base.count2<Base> [| a; b |] // Compiler error

The functions `count1` and `count2` are identical, except for the `ParamArray` attribute on the parameter. The call to `count1` compiles, while the call to `count2` does not.

**Comment by mexx** [comment]
Just to add more curiosity, the intended usage of `count2` does work.
```
let n3 = Base.count2<Base> (a, b)     // OK
```

Another observation, the type annotation `<Base>` is required in any case.
```
let n4 = Base.count1       [| a; b |] // Compiler error
let n5 = Base.count2       [| a; b |] // Compiler error
let n6 = Base.count2       (a, b)     // Compiler error
```

**Comment by JeffreySax** [comment]
According to the [documentation](https://msdn.microsoft.com/en-us/library/system.paramarrayattribute(v=vs.110).aspx):

> When the method is called, a parameter array permits arguments 
> to a method to be specified in either of two ways:
> * As a single expression of a type that is implicitly convertible 
> to the parameter array type. The parameter array functions
> as a value parameter.
> * As zero or more arguments, where each argument is an expression
> of a type that is implictly convertible to the type of the parameter array element.

The first way works fine if no "advanced" type inference is required, i.e. the first element of the array is exactly of the expected type. Otherwise, we see the same pattern as in #801:

    let d1 = Base.count2<Base> [| a; a |] // OK
    let d2 = Base.count2<Base> [| a; b |] // b expected to have type Base
    let d3 = Base.count2<Base> [| b; a |] // No overloads match
    let d4 = Base.count2<Base> [| b; b |] // No overloads match

**Comment by enricosada** [comment]
i think

```fsharp
let d2 = Base.count2<Base> [| a; b |] //error
```

it's the same as 

```fsharp
let xs = [| a; b |]
let d2 = Base.count2<Base> xs //error
```

And that's it by design, you are creating an array `[| a; b |]` with different types, not using `ParamArray` syntax like

```fsharp
let n3 = Base.count2<Base> (a, b)     // OK
```

**Comment by mexx** [comment]
@enricosada it have to be interpreted like this, but why than the version of `count1` works? It can also be interpreted like this.

**Comment by enricosada** [comment]
sry @mexx i misunderstood the issue

**Comment by dsyme** [comment]
Like #801 this is by design.  The use of ``ParamArray`` effectively makes the method overloaded.  This means that the array expression is pressed without a known type. Again you can insert explicit upcasts:

```
type A(x : int) =
    member self.X = x
    static member count1<'a> (x : 'a array) = x.Length
    static member count2<'a> ([<System.ParamArray>]x : 'a array) = x.Length
type B(x : int) = inherit A(x)

let a = A(1)
let b = B(1)

let n1 = A.count1<A> [| a; b |] // OK
let n2 = A.count2<A> [| a; (b :> A) |]
```
