### ISSUE TITLE
dotnet cli ( http://dotnet.github.io )

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#805]
ref: http://dotnet.github.io/getting-started/

ref dotnet/cli#45

i was checking [fsharp-dnx](https://github.com/fsprojects/fsharp-dnx/), an amazing work by @Alxandr, to help him with [aspnet/dnx](http://github.com) and f#. It's (was) really important as project, i didnt understood how pervasive dnx/dnu/dnvm was in coreclr. but it works also in .net desktop ( didnt know that )

In [jabbr](https://jabbr.net/#/rooms/AspNetvNext) @davidfowl mentioned they are moving away from dnx to [dotnet cli](https://github.com/dotnet/cli)

Is someone from the F# team is working on f# support? @davidfowl mentioned someone is working on it, and i'd like to help. Or at least understand the roadmap if possibile to not duplicate work.
/cc @dsyme @KevinRansom @NumberByColors @otawfik-ms 

An additional value added is also project.json + xproj, who use the new project system, it already work ok with f# in fsharp-dnx , much better than current situation with fsproj. 
For example a base asp.net mvc works ok [https://github.com/fsprojects/fsharp-dnx/tree/master/sample/HelloMvc], it's the same project used by c#, only with f# compilation.
Require updates in vs extensions, but it's ok.
I'll add another issue about xproj and project.json

**Comment by enricosada** [comment]
ok i added a first try here dotnet/cli#538

to compile a f# project, add 
```json
"compilerName": "fsc"
 ```

to project.json

**Comment by KevinRansom** [comment]
It's actually what I start work on today, and I expect it to be done quickly.

**Comment by enricosada** [comment]
@KevinRansom well if you want there is a pr ready with implementation there dotnet/cli#45

**Comment by enricosada** [comment]
dotnet/cli it's a really good codebase, nice to work with ( docs/build script/code )
Now that is f# compilation is working with `dotnet`, i'd like to use `dotnet compile` to explore usage of project.json + xproj with visual studio. 
With fsharp-dnx was really good already

**Comment by KevinRansom** [comment]
So does that run the desktop compiler, or the coreclr one?

**Comment by enricosada** [comment]
Like c# . Run in coreclr and execute fsc.exe in path. Dotnet cli bundle csc.exe in netcore. If you add coreclr fsc.exe should compile coreclr f#It's a real good idea because like that can run also desktop fsc with net451 framework target i think ( like old dnx/dnu )

Inviato da Outlook Mobile




On Thu, Dec 17, 2015 at 10:21 AM -0800, "Kevin Ransom (msft)" <notifications@github.com> wrote:





So does that run the desktop compiler, or the coreclr one?

---

**Comment by davidfowl** [comment]
What compiler you use has no bearing on what the target runs on. Csc is embedded in the CLI itself and is never loaded from the path.

There's a model for bringing in tools like this via packages as well (what we're doing for dotnet test) that might be interesting to look at.

**Comment by enricosada** [comment]
I'd like something to separate build dependencies from project deps ( i'll write about that use case in dotnet cli repo )
But is really nice like that. It replace msbuild for good, use PATH and nuget ref. Compile to exe. With native is supported. Work good in Shell and cmd ( no need for developer vs 2015 cmd ). Lots of goodies, nice work!

Inviato da Outlook Mobile




On Thu, Dec 17, 2015 at 11:02 AM -0800, "David Fowler" <notifications@github.com> wrote:





What compiler you use has no bearing on what the target runs on. Csc is embedded in the CLI itself and is never loaded from the path.

There's a model for bringing in tools like this via packages as well (what we're doing for dotnet test) that might be interesting to look at.

---

**Comment by enricosada** [comment]
@davidfowl if i add csc in PATH before dotnet cli bin, it's not going to use that csc?
Is nice that csc is bundled, but an easy way to change csc.exe ( or fsc ) is good to have for testing, performance testing, regressione etc. 
Dotnet cli bundle csc ( good ) and i hope fsc too ( latest stable! Fast release! )

**Comment by davidfowl** [comment]
Nope the one in the box wins over the path.

**Comment by enricosada** [comment]
Well good anyway, less surprises. 
I'll check the other way with nuget, to test new version

**Comment by dsyme** [comment]
Closing, this is old discussion
