### ISSUE TITLE
No F# templates in VS Community 2015 

### ISSUE THREAD

**Issue by StefanBelo** [Microsoft/visualfsharp#808]
After installing Update 1 for VS Community 2015 all F# templates are missing in File/New project. On existing F# project Visual F# templates group is missing when adding a new item/file.

**Comment by KevinRansom** [comment]
Some simple diagnostics to help me try to figure out what is going on?

Do you have any add-ons installed?
Have you tried repair?
If you run vs setup is the F# option checked?

Can you attach the most recent: 
<user>\AppData\Local\Temp\dd_FSharp_Bundle_*.log

**Comment by KevinRansom** [comment]
Can you try installing F# from here and let me know how it goes? :  https://github.com/Microsoft/visualfsharp/releases/tag/V4.0.Update2.Preview-12.16.2015
These are the latest signed bits.

install fsharp_bundle.exe
If you use a language other than English also 
install fsharp_bundlelp.exe

Thanks

Kevin

**Comment by StefanBelo** [comment]
Thank you Kevin, for all your help. Just to summarize it:

After installing Update 1 for VS 2015 Community, the installation failed with two errors. At that time I googled it, and found similar complains for failed installation from other users. VS was actually not usable, F# project templates were not presented and Extensions and Updates was not able to open and when starting up VS there were 5-6 error messages saying some components were not loaded.

I tried to reinstall VS 3 times finally got it running without error messages at start up, but F# project templates were still missing, and for my asp.net project there was no support for Publish. I decided to reset Windows 10 installation, I did not install clean installation and was running from windows 7, 8, 8.1 to 10 for years.

Clean Windows 10 installation and VS.

I have just checked VS and all is ok, will check asp.net project Publish in a moment as other VS updates are still running. F# project templates are presented, will install websharper and Visual F# Power Tools, later.

**Comment by MaxWilson** [comment]
Just wanted to say: I installed Kevin's preview and it didn't fix the issue for me.

I'm going to work around it for now by just manually editing my .fsproj.

**Comment by MaxWilson** [comment]
Logs attached.




[dd_vsupdate_KB3022398_20160107113943_210_FSharpVS.zip](https://github.com/Microsoft/visualfsharp/files/86605/dd_vsupdate_KB3022398_20160107113943_210_FSharpVS.zip)

**Comment by dsyme** [comment]
Close old issue
