### ISSUE TITLE
Code security attributes are lost when closures are lifted out of annotated classes

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#81]
Originally opened at [CodePlex](https://visualfsharp.codeplex.com/workitem/62) by [latkin](https://www.codeplex.com/site/users/view/latkin)

[from fsbugs] 

From: "Anton Tayanovskyy"  anton.tayanovskyy@gmail.com 
Date: Jul 11, 2013 5:18 PM 
Subject: F# and Level 2 Security 
To: fsharp-opensource@googlegroups.com 
Cc: 

 <snip> 
 Having worked with it for past couple of days there appears to be a 
 serious issue with F#. .NET security policy expects you to annotate 
 types/methods with [<SecuritySafeCritical>] if they reference or call 
 "SecurityCritical" code, which happens to be most of the code out 
 there on NuGet because this is what it defaults to. Now, in F# this 
 works ok until you start using closures. You cannot do:

``` fsharp
[<SecuritySafeCritical>]
module M =
   let foo () =
       getSomeCriticalThings ()
       |> Seq.collect (fun x -> ..)
```

This fails to please SecAnnotate.exe because F# compiler lifts the closure (fun x -> ..) to a separate type, which is now NOT annotated with [<SecuritySafeCritical>], defaults to Transparent, but references some critical code, which is an error. It sounds like a minor restriction but it cost me many hours altering code to avoid closures and satisfy SecAnnotate constraints. Maybe F# could propagate security attributes to closure types it creates? Is there another simple way around this that I am missing? 
Thanks, 
 --A

**Comment by dsyme** [comment]
I'm going to close this.  Code Access Security is not present in .NET Core, and has become less and less important for .NET Framework over the years, see https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/porting.md#code-access-security-cas. It is also possible to write transparent code in F#, which usually suffices, and it is possible to write other CAS code if you just carefully avoid the use of come language constructs.
