### ISSUE TITLE
string "cast" doesn't compile on a generic type object

### ISSUE THREAD

**Issue by manofstick** [Microsoft/visualfsharp#810]
Don't think I can find this one in the list of existing issues...

    type T1<'a>(a:'a) =
        override __.ToString () = a.ToString()

    type T2<'a>(a:'a) =
        override __.ToString () = string a

T1 is fine. T2 comes up with

    error FS0670: This code is not sufficiently generic. The type variable  ^a could not be generalized because it would escape its scope.

Which then got me looking at what the compiler was doing, and I see that it was doing some static type stuff:

    let inline string (x: ^T) = 
            anyToString "" x
            // since we have static optimization conditionals for ints below, we need to special-case Enums.
            // This way we'll print their symbolic value, as opposed to their integral one (Eg., "A", rather than "1")
            when ^T struct = anyToString "" x
            when ^T : float      = (# "" x : float      #).ToString("g",CultureInfo.InvariantCulture)
            when ^T : float32    = (# "" x : float32    #).ToString("g",CultureInfo.InvariantCulture)
            ...

And then I had a look the IL it was actually generating for types like "float", because my memory was telling me that it was doing a check for IFormattable etc. and low and behold it was (i.e. it was just inlining the 'anyToString' function). So my money is on the compiler hitting the first static condition, i.e. the "when ^T struct ..." and just forgetting about all the rest. Making the use of the static type inline function pointless, in which case this could just be a normal inline function, and my original code would compile!

So that's one possible solution.

Anyway, simple work around for me (I just use my original 'T1' version) but I think as a minimum all the type specific should be deleted from "prim-types.fs" because they are misleading. (and if static types can be discriminated via interface [not sure if they can?] then you could make a value type friendly version without the boxing/type checking... otherwise just remove the static typed function altogether...)

**Comment by dsyme** [comment]
Hi @manofstick 

AFAICS this is by design - it's just the way using "string" works according to the current signature, which we won't be changing.  If you see a repro that doesn't involve using the inlined "string" function please reactivate.

The difference can also be seen here:

```
> let f x = string x;;

val f : x:obj -> string

> let f x = x.ToString();;

val f : x:'a -> string
```

thanks
don
