### ISSUE TITLE
Failing tests in cambridge suite ( disabled now )

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#813]
cambridge suite ( `tests/fsharp` )

- [ ] core/load-script
- [ ] core/members/basics 
- [ ] typeProviders/negTests
- [ ] core/printing

These are disabled now with `NO_CI` tag

## core/load-script

the bat was false positive, now is disabled in both nunit and bat runner

## core/members/basics

the bat was false positive. 
all `FSI*` permutation of this test fails, because the bat execute fsi < a.fsi b.fs but fsi understand fsi b.fs (load file, not stdin redirect)

see https://github.com/Microsoft/visualfsharp/pull/737#issuecomment-160159281 for detailed info

## typeProviders/negTests

dont know why

## core/printing

works only in en-US culture. 

fails on bat runner too because output differ, it's culture related. 
the error messages are in italian, in the base file are in english

Problem is, i cant change current user culture of fsc. 
I'll add an issue because some test are disabled in fsharpq if culture is not en-US (same problem i think, error messages translate make output diff fail )

**Comment by dsyme** [comment]
It's very important that these tests get re-enabled especially members/basics, core/prnging and typeProviders/negTests.  They are crucial coverage of areas very poorly covered elsewhere

@enricosada if could you look into re-enabling these that would be great

**Comment by enricosada** [comment]
i think i can reenable `core/printing` after my #858 (because right now fails for non english contributors, like me, so it's annoying ). Or we need to skip known failures for non us language by tag.

others tests i tried a fast check, but i dont understand why.

@KevinRansom i see #829 fixed `core/load-script` in coreclr branch, that's in master too? i can remove it from list?

**Comment by dsyme** [comment]
I will close this in favour of https://github.com/Microsoft/visualfsharp/issues/915
