### ISSUE TITLE
Failing tests in fsharpqa suite ( now disabled )

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#814]
Some tests in `Conformance\LexicalAnalysis\StringsAndCharacters` fails.

These are disabled with `NO_CI` tag in [tests/fsharpqa/Source/Conformance/LexicalAnalysis/StringsAndCharacters/env.lst](https://github.com/Microsoft/visualfsharp/blob/2d413fb940aa1677688454c50b8ec05cd3b6f78f/tests/fsharpqa/Source/Conformance/LexicalAnalysis/StringsAndCharacters/env.lst#L32)

**Comment by dsyme** [comment]
Closing this old test issue
