### ISSUE TITLE
add `fsc --preferreduilang`

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#815]
like roslyn csc, it's not because is roslyn, i think is useful

ref https://msdn.microsoft.com/en-us/library/hh506932.aspx

```
--preferreduilang              Specifica il nome del linguaggio di output preferito.
```

example

```
fsc.exe --preferreduilang:ja-JP
```

from docs:
You can use the /preferreduilang compiler option to specify the language that you want the C# compiler to use for error messages and other command-line output. If the language pack for the language is not installed, the language setting of the operating system is used instead, and no error is reported.
## implementation:

if set, change thread current culture, at beginning of fsc main
### use case 1, nice for tests

some tests do a diff of output against a base.
That doesnt works because if i run with a different user culture than en-US ( for me is italian ), the error message for example doesnt match
### use case 2, change language inside ides

i have windows user culture italian, but i want the ui in english ( easier to google ).
That is not easy now

**Comment by enricosada** [comment]
this can be an upforgrab, it's really easy to implement

**Comment by KevinRansom** [comment]
Agreed, this would be a nice addition.

**Comment by KevinRansom** [comment]
Everything is up for grab unless it's assigned to someone.  Regardless, however, this is probably not as straightforward as you think.

**Comment by mexx** [comment]
@KevinRansom I think you get it wrong, this option do not change anything in the compiled assemblies. It's only for the output of the compiler. The behavior is clearly defined in the `from docs:` section of initial description by Enrico.

**Comment by enricosada** [comment]
> What to do about existing behavior?

existing behaviour is the default, the system language ( `CultureInfo.CurrentUICulture` )

> What should the defaults be?

as doc, the default is system language, like current behaviour. So if not specified, nothing need to be done

> What to do in a multi-module app where differ some assemblies are compiled with the switch, one way and others differently configured

as @mexx said, this doesnt affect compiled assemblies, **only compiler** error message and output, are localized, **not the compiled libraries** output

> What if the OS picks a different language, how would it interact with CurrentUI language

i dont understand that question, it's only the current culture for printf changed.


for example roslyn use the Property [Culture](https://github.com/dotnet/roslyn/blob/03d11f2a56cf60c5a16b0b4aa60f3c37384bbb2c/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L843-L849) when print diagnostic info ( warnings/errors/log ).

 ```csharp
protected virtual CultureInfo Culture
{
    get
    {
        return Arguments.PreferredUILang ?? CultureInfo.CurrentUICulture;
    }
}
```

**Comment by enricosada** [comment]
@KevinRansom about `up-for-grab` label

> Everything is up for grab unless it's assigned to someone

Yes, unassigned mean everyone can contribute (that's the default). 
But [up-for-grab](http://up-for-grabs.net/#/) mean also easy to implement, standalone, clearly documented. A good and easy first work for a new contributor.

> We're looking for projects who can take the time out to help mentor developers as they get started with open source.

>What sort of tasks are a good fit?

>Tasks should take no longer than a few nights' worth of work
Tasks should stand alone - avoid core functionality on which other tasks depend
Tasks should be well described with pointers to help the implementer

**Comment by cartermp** [comment]
This is now enabled in #3285
