### ISSUE TITLE
add support for response file to fsc

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#816]
like roslyn. it's not because is roslyn, i think is useful

add `@file` argument to `fsc`

ref https://msdn.microsoft.com/en-us/library/8a1fs1tb.aspx

Long story short: 

A file that lists compiler options or source code files to compile, instead of pass compiler arguments.

Goodies:

- Response files can have comments that begin with the # symbol.
- Combine multiple options. @file1.rsp @file2.rsp
- command line arguments can override previously listed options in response files.
- options in a response file will override options listed previously on the command line or in other response files

it's nice to have a base configuration, and two files, for example debug, test or perf as additional
more easy to track in source control ( it's a text file ) instead of concat argument list in script

**Comment by mexx** [comment]
:+1:

**Comment by KevinRansom** [comment]
Yes, this is a long time missing feature from F#, I have been figuring I would add it at some point, however, nothing fails to work because it is missing, so it has seemed like a very low priority feature to me.
If we do this, we should also consider adding response files for FSI.

I would certainly eagerly consider accepting a PR for this feature.

**Comment by enricosada** [comment]
i'll try to add it, it's really useful for dotnet cli development.

About this feature, `@` is really wierd, it's like a special case of source file.
Should we use `@` or a normal (short) argument like `--rsp` for consistency ? /cc @dsyme 

I'll start with `@`, is not difficult to change after it's done

**Comment by smoothdeveloper** [comment]
I've encountered response files in the past and it was always using `@` prefix, though I don't remember which compiler it was.

https://gcc.gnu.org/wiki/Response_Files

I'd vouch to keep the same convention as others compilers, especially if roslyn uses the same.

**Comment by enricosada** [comment]
ah nice @smoothdeveloper , good that is a shared command line option, thx for feedback

llvm too http://llvm.org/docs/CommandLine.html#response-files nice.

no more open questions so :smile:

**Comment by dsyme** [comment]
Fixed in https://github.com/Microsoft/visualfsharp/issues/831
