### ISSUE TITLE
coreclr compiler require default.win32manifest for exe

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#825]
To compile `--target:exe` a win32manifest is required

It's possible to add it from command line argument `--win32manifest`:

```
--win32manifest:the\path\to\default.win32manifest
```

This issue is used to track the status of this temporary requirement.

A default.win32manifest is bundled with `Microsoft.FSharp.Compiler.netcore` nuget package

What is needed on osx/linux?

**Comment by KevinRansom** [comment]
Sure, it is something I was hoping to get to this week.

**Comment by KevinRansom** [comment]
However, you can always make your cli driver program provide this argument.

**Comment by enricosada** [comment]
@KevinRansom i do that :smile: 

ref https://github.com/enricosada/cli/commit/c1a015bbed402f5035fbf0425432c2d1b11f2e48

but that work also for osx/linux?

**Comment by KevinRansom** [comment]
Yes it will work on other platforms.

**Comment by enricosada** [comment]
leave it open @KevinRansom pls, i use that to track that issue in dotnet cli.

**Comment by KevinRansom** [comment]
+

**Comment by KevinRansom** [comment]
Actually I pressed the wrong button when commenting :-(  sorry.

**Comment by KevinRansom** [comment]
Committed.

**Comment by enricosada** [comment]
nice, i'll remove workaround in dotnet/cli#538 after i upgrade compiler nuget :smile:
