### ISSUE TITLE
VFT: solution explorer / linked files / no option to remove linked file / delete deletes the physical file

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#828]
In Visual Studio projects, user can add a linked file (a pointer to a file which is located outside the project folder hierarchy).

In a C# project when I right click on such item I can't pick `Delete` but `Remove` is shown instead.

In a F# project, `Delete` is shown and it actually deletes the physical file instead of just removing the link from the project file.

I'd expect `Delete` to not delete the actual file if it's a linked file, and possibly to have identical behaviour as in C# projects (show `Remove` instead of `Delete`).

**Comment by saul** [comment]
This can be closed. F# and C# both show "Delete" and "Exclude from project" on both linked files/normal files.
