### ISSUE TITLE
add dotnet cli support

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#834]
ref dotnet/cli#586 ( F# support )

I didnt know about dotnet cli, so first a summary:

The `dotnet` cli is an **xplat**  way to get **dependencies/compile/package/run .NET** projects ( not only c# ).
The dotnet cli **runs on coreclr** (xplat), but can **also compile/build for desktop clr**.
There are options to compile to il ( default ) and to native ( ``--native`` ). Lots of stuff.
As i said, xplat, it runs and is supported on: Windows, Ubuntu, OSX and docker
It's not a language service for ides, it only compile .NET programs and some helpers ( restore, test, pack, repl )
It's designed to work cross language ( it's called `dotnet` ).

The actual dotnet cli roadmap ( dotnet/cli#45 ) has only C# in P0, and F# + VB in P1. 
It's ok, it's a new bootstrap ( really ), but as community we can help alot to make F# support happen asap.
the base is from aspnet/dnx, but it's a lot easier, more clean, extendible and is normal .net workflow now ( compile to .exe )

info https://dotnet.github.io/getting-started/

### Current status on common dotnet commands who need f# support:

ref dotnet/cli#586

| Command  | Issue | Status | TODO | Descr |
|----------|-------|--------|-------|-------|
|  new     | dotnet/cli#647 | TODO, now generate c# .cs file only  | write the .fs hello world + configure project.json to use fsc ( like a basic scaffold ). current code can be adapted to write f#, it currently write c#  | Initialize a basic .NET project |
|  compile | dotnet/cli#539 | WIP, pr dotnet/cli#538 add compilation of library, console app  | remove workaround, use latest version of fsc, test it! | Compiles a .NET project |
|  repl    | dotnet/cli#648 | TODO   |  call fsi   | Launch an interactive session (read, eval, print, loop) |

### The others common commands who doesnt need special f# support, because these works cross language 

| Command  | Descr |
|----------|-------|
|  run     | Compiles and immediately executes a .NET project |
|  restore | Restore dependencies specified in the .NET project |
|  publish | Publishes a .NET project for deployment (including the runtime) |
|  pack    | Creates a NuGet package |

### Other stuffs i think we need

lots of other command in dotnet cli roadmap ( dotnet/cli#45 ), check what's need f# support
For example aspnet vNext will use dotnet cli instead of aspnet/dnx, so aspnet should work

| Task | TODO |
|--------|----------|
| Docs on http://dotnet.github.io/docs/ | Add `Learn F#` near `Learn C#`, to quickstart to F# |
| Docs on http://dotnet.github.io/docs/ | The website use c# to explain .NET ( garbace collection etc). add f# examples near c# in the website, like msdn? |
| user experience | check what workflows are important, restore+compile+run |
| demo | make it easier to demo f# on dotnet cli |

I think is better a **public** wiki page :smile:

## My feedback about dotnet cli, if someone care about it :smile:

First, i think it's a really good new beginning, instead of msbuild, now there is `dotnet` cli + `project.json`. 
`project.json` file is used a configuration file ( source file, defines, etc), not the main entry point like in msbuild.

**dotnet cli is the entry point**, each command ( like `dotnet-compile-fsc` ) is a separated exe and use command line argument. 
Some command may read `project.json` as a configuration file, but after that call others command or exe passing command line arguments.
If you want you can call that exe directly, without project.json.

It's a lot easier than previous aspnet/dnx attempt, compilation to disk, exe and command line
args ( `dotnet pack arg0` call `dotnet-pack.exe arg0` , like git cli )
so for example `dotnet compile` ( `dotnet-compile.exe` ) parse source files and call `dotnet-compile-csc` 
( or `dotnet-compile-fsc`, dependes on `compilerName` property in project.json )

A msbuild wrapper exists and it's used by visual studio ( .xproj ), but it only execute `dotnet cli` and read files
 list from `project.json` for visual studio extension. 
As a note, the project system of xproj is cross language. 
That's really important because  that fix lot of issue with current F# project system, and make F# on par with C# for project system
without effort ( folders, add files like .html etc, etc ).

Others ide who support project.json and dotnet cli, should allow compilation without effort ( like in vs, language service is another issue )

**I added this issue to add visibility to dotnet cli and f# support effort**.

I think it's really a good codebase to start with ( easy to clone and build, run, code, xplat ), no legacy, fast feedback, no dependencies, no visual studio required, no msbuild, very few moving parts.

Other stuffs i think are important for f# ecosystem but not part of this issue, but are going to change

- **paket** , it's `dotnet restore`, maybe is possible to do `dotnet-restore-packet` instead of call dnu restore
- ides, check ides ( like vs, ionide, vim ) language services. vs has .xproj wrapper, others can use same dotnet plugin and maintain only f# language service. A shared (vs+others) language service based on dotnet cli functionality (reference, sources, etc) ?
- mono, mono support story?
- open source repo, what's the story? actually dotnet cli **bundle** visualfsharp repo fsc.
- FSharp.Core nuget package ( everything is a nuget package now), open vs microsoft because each project add FSharp.Core as nuget reference ( so should specify the name ).
- FSharp.Core nuget package ( everything is a nuget package now), can we use one single FSharp.Core for all targets ( .net desktop and coreclr ) pls, otherwise is annoying specify two different FSharp.Core for different targets, is not needed with nuget.
- NETStandardLibrary and NETStandardPlatform, or how nuget is changing to fix desktop/coreclr/mono/pcl problems

A real thx to @Alxandr for https://github.com/fsprojects/fsharp-dnx/ because has made lots of things working and helped me a lot on dotnet cli support

**Comment by GerjanOnline** [comment]
Just a question since I couldnt find it: do you have any idea how `dotnet` commands picks its "drivers"? (not sure if you can state it this way)

So its probably mostly "configuration based" by looking at `project.json` but what about commands where you do not want or have a config file:
`dotnet new` => how does it know I want a new F# project?
`dotnet repl` => how does it know I want to launch FSI instead of the C# REPL?

Do they pick the defaults (which is I think C#) and you can override it with a switch/flag?

**Comment by lambdakris** [comment]
@enricosada Nice! I was aware of dotnet-cli, but gathering the info together like this really helps understand the current state, relationships, and what needs to be done. It also seems really relevent for the [getfsharp.org](getfsharp.org) effort begun by @swlaschin and especially to the discussion of the [OOBE](https://github.com/swlaschin/getfsharp.org/issues/6). As an aside, I've been following your work on the unit tests and dotnet-cli support and just wanted to commend you on really exemplary work...so thanks!

**Comment by enricosada** [comment]
@GerjanOnline usually the first work is a verb, so `dotnet compile` execute `dotnet-compile.exe` ( like git)
for fsc, `dotnet-compile` call `dotnet-compile-{CompilerName}.exe` => `dotnet-compile-csc` or `dotnet-compile-frank` if compilerName property is "frank"

about repl and new, these need arguments ( --lang ) or do like `dotnet compile`.
i think repl do that for `dotnet repl csi` -> the `dotnet-repl.exe` call `dotnet-repl-csi.exe`

Default are c# atm, so `dotnet repl` = `dotnet repl csi`

`new` doesnt call another exe or understand `--lang`

**It's ok i think, dotnet is a new project, need help to support new lang**, there is lots of todo for shared commands too ( publish etc )

**Comment by GerjanOnline** [comment]
Thanks for you explanation @enricosada! Makes sense

**Comment by iainnicol** [comment]
As you say, Paket is only tangentially related to the bulk of this issue, because it's not tied to F#.  But FYI I'm prototyping paket support.  Namely that's implementing `dotnet-restore-paket`, plus some dark magic overrides to make it invokable as `dotnet restore`.

**Comment by dsyme** [comment]
Closing this old discussion
