### ISSUE TITLE
Feedback required  ---  Proposal for FSC command line support on coreclr compiler for platform support

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#837]
# Proposal for FSC command line support on coreclr compiler for platform support

FSharp compiler has always done 'MAGIC' for referenced, we have a goal to ship a single compiler that can run on all platforms and target all platforms.  We may not get there but if a developer can build and package a Windows Desktop App on a MAC or a Unix APP on Mac or Windows that will be huge.

The compiler as is will work fine with the dotnet cli tool when targeting coreclr, however, we need to ensure that the fsc.exe cli is still usable and relevent for the existing Windows and Mono usage scenarios.  We also need to smooth out references under FSI on coreclr where the BCL is partitioned in a much more fine grained way - writing an F# script that directly references each framework assembly, so I propose that the --targetprofile  scheme described below is also supported by the FSI command.

The existing msbuild magic will not work on the coreclr or for building Windows apps on linux I am proposing using nuget combined with --targetprofile below to fill those gaps by referencing 
nuget packages with the reference assemblies for specific profiles and platforms.  This will also enable us to support a wider number of portable profiles via nuget, if the need arises.

Having the compiler understand the nuget protocol is not ideal, but it will allow us to have the fsc command line reference packages of assemblies with a single instruction.
This proposal applies to command line processing
# Goal: 
1.  Be able to build all targets on all platforms.  Obviously desktop will require Windows to run.  But it will be possible to build and deploy on all platforms.  Linux, Mac, and other coreclr targets.
2.  Be extensible to any new build target platform without requiring extensive modification.
3.  Support simple IDE target platform selection.
4.  Enable FSI to #r nuget packages
5.  dotnetcli will be able to specify the switch using project.json files.
6.  project json files will be able to reference these packages
7.  we will not depend on nuget.exe for nuget support.

```
--targetplatform:platformId

    lookuptable platformID --> nugetpackageID  ?? Should this be a convention FSharp.Platform.__targetplatform__ or a textfile that is read at runtime.  My preference a convention.

reserved:           // provided for compatability with legacy build scripts __ will only work on desktop windows __
    mscorlib        // Will respect --simpleresolution --noframework
    netcore

new:
    net461 ---      Windows Desktop 4.61    --- FSharp.Platform.net461
    net46 ---       Windows Desktop 4.6     --- FSharp.Platform.net46
    net452 ---      Windows Desktop 4.52    --- FSharp.Platform.net452
    net451 ---      Windows Desktop 4.61    --- FSharp.Platform.net451
    net45 ---       Windows Desktop 4.5   --- FSharp.Platform.net45

    profile7 ---      Portable Profile 7        --- FSharp.Platform.profile7
    profile47 ---    Portable Profile 47      --- FSharp.Platform.profile47
    profile78 ---    Portable Profile 78      --- FSharp.Platform.profile78
    profile259 ---  Portable Profile 259    --- FSharp.Platform.profile259
    profileN ---     Portable Profile N        --- FSharp.Platform.profileN        ???? If we decide to add more
                                                                                   ???? profile support
    coreclr ---       CrossPlat corclr          --- FSharp.Runtime.coreclr
```

Specification of these will automagically select --noframework and --simpleresolution. All lib assemblies in packages will be automagically referenced.

Todo:
    1.  Rip out more msbuild codepath from coreclr build (Mostly done but I foolishly tried to deal with it in the original port to coreclr)
    2.  Build sample profiles for Desktop 45, profile7 and crossplat coreclr
    3.  Implement nuget support for profiles
    4.  Extend #r support to include profile support.

**Comment by forki** [comment]
From all I learned about it I think putting nuget into the compiler is a really bad idea. Good luck with keeping up with all the craziness.

**Comment by forki** [comment]
I personally think that putting nuget into the compiler would be a big mistake. It has way to many changing parts and would be really hard to keep up with all the changes.

**Comment by forki** [comment]
Of course having #n in fsx files would be nice, but I always thought it should call another (customizable) tool.

**Comment by smoothdeveloper** [comment]
Regarding Nuget, I'm iffy on fsc/fsi understanding nuget, in other environments I've never seen the compiler dealing with package repository directly (ruby has gem, ghc has cabal, rust has cargo, etc.).

It seems for F# we could expect users to have paket installed (it could be shipped as part of dotnet or fsharp like ruby installer ships gem, etc.).

Now that I've started to use paket, it's not too painful to pull all dependencies, we could have a paket command to generate a `packages/load-all-dependencies.fsx` to `#load` which has all the assemblies from all dependencies.

As a .net developer, paket solves most of the pain of dealing with nuget published refereneces, it took me very short time to pick it up while nuget has always been kind of nebulous and painful at times (inconsistent versions / targets in several packages.config files, default to folder named with version, etc.).

Regarding the main point of this issue (cross compile / support many targets), it seems to me having a first release of fsc/fsi with a "hardcoded" set of platform would be good enough so the development stays focused on the internals while keeping in mind that it would be made extensible by descriptors on file system in the future.

My rationale is that I assume most of the hardwork happens in the compiler's internals to deal with all those targets properly while the end user extensibility is not a top priority (as long as list of targets support most runtimes).

**Comment by enricosada** [comment]
I am totally :-1:  to do complex resolution in the compiler or bundle nuget experience.

the compiler should accept path of references as part of command line arguments, no clue about how these files are created ( packet, nuget restore, downloaded from internet, file copy etc ).

It's seems better at the beginning, but it's easier to create a wrapper command line to translate arguments.

> Enable FSI to #r nuget packages

I think is easier on `#r package` to call `packet download package` or `nuget download package`

> Support simple IDE target platform selection

project json support multiple targets in the `framework` property, and build each one, in parallel.

**Comment by KevinRansom** [comment]
I was originally thinking of creating a new compiler driver perhaps fl.exe until it occurred to me that fsc and fsi are not the compiler, the compiler is really fsharp.compiler.dll, FSC and FSI are the compiler driver.  

I am very keen on shipping a single compiler that runs on the corecl and targets desktop windows profiles with a minimal transformation of project files for existing tooling as well as coreclr profiles and can do so on MAC, Linux and Windows clients.

The cli tool is a tacit recognition of this state of affairs and resolves the issue  for coreclr by creating a set of command line drivers that rely on project.json and nuget.  Of course the desktop C# compiler uses a lot less magic than the F# desktop compiler and so the C# command line driver transfers easier to Linux and mac.

I have noticed that the FSC command line experience is almost unusable as a command line tool when using --simpleresolution --noframework.  This proposal is an attempt to make it usable as a command line tool.  I would welcome suggestions for how to make it usable.

Or perhaps you think we should ship two compilers, a windows only compiler with the current set of switches for building windows apps, and a coreclr based compiler for building coreclr based apps?

Thoughts?

**Comment by dsyme** [comment]
In F# 2.0 I argued for something along these lines. I think it makes a lot of sense, on the assumption that the whole notion of platform identifier is stable enough.

As Kevin mentions, in the forthcoming CoreCLR world, it seems that F# scripts are going to need something like

    #r "coreclr"

    #r "net461"

that indicates what platform the script actually targets.  I think this declaration needs to be in the script file itself since the editor tooling will need to inspect it to get the references right.   In truth we already need this today as it's not clear which .NET 4.x is targeted by a script - the editor tooling defaults to the latest .NET but that's not always what you want.

**Comment by smoothdeveloper** [comment]
what about

```fsharp
#platform "coreclr"
```

and keeping this optional (use most recent runtime by default, or rather same runtime as what fsi/fsc is bound to), we really want the simple / portable scripts to look as slick as possible.

**Comment by dsyme** [comment]
> #platform "coreclr"

I'd be fine with that. I don't mind ``#r`` and it may be cheaper that way (since support for various ``#`` directives is baked into a few different places and tools).

> and keeping this optional (use most recent runtime by default, or rather same runtime as what fsi/fsc is bound to)

Yes, assuming that would be the case..

**Comment by iainnicol** [comment]
Small question.  Why doesn't the `coreclr` platform need a version number?  `net46` for example has one.  Or to rephrase, if I do `--targetPlatform=coreclr`, will that automatically reference (a fixed version of) packages like NETStandard.Library or Microsoft.NETCore.Platforms?

**Comment by enricosada** [comment]
i think if we depends on nuget for dependencies ( sry ), the [new nuget platform docs](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md) can help the discussion ( and make someone crazy ) 

for example, `#platform  "netstandard,1.4" make more sense maybe

And we should make fsi and fsc two separate discussions, because #r ( or #n ) it's complicated if you dont use paths.

for example csi (csharp interactive)

>Note: The Interactive Window doesn't currently support #r'ing NuGet packages. As a temporary workaround, reference the NuGet DLL

**Comment by dsyme** [comment]
Can we close this now?

**Comment by dsyme** [comment]
Can we close this now?
