### ISSUE TITLE
Debug ranges wrong in for loop with non-int32 counters

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#84]
This was originally opened on [CodePlex](https://visualfsharp.codeplex.com/workitem/65) by [latkin](https://www.codeplex.com/site/users/view/latkin)

If I define a simple for loop with a signed-integer counter, debug behavior is as expected: 

 But if I change the counter to something besides a normal signed int (e.g. an unsigned int, shown below), line #2 takes 2 debug steps to pass through: 

![pic1](https://cloud.githubusercontent.com/assets/5175830/5844987/4dd61a4a-a16d-11e4-9ff4-e48ffd0db801.png) -> ![pic2](https://cloud.githubusercontent.com/assets/5175830/5844989/51d796a0-a16d-11e4-8ff1-e55bd7389b24.png)
 
vs 
![pic3](https://cloud.githubusercontent.com/assets/5175830/5845000/622697a4-a16d-11e4-88c4-fa5cdb7a5616.png) -> ![pic4](https://cloud.githubusercontent.com/assets/5175830/5845002/678f70da-a16d-11e4-8a7f-6440291a2adf.png) --> ![pic5](https://cloud.githubusercontent.com/assets/5175830/5845008/6d41409e-a16d-11e4-99ed-8abac6a8b75c.png)

From peeking at the IL, looks like first example is compiled as normal ‘for’ loop as in C#, but second example is implemented with an IEnumerable<uint> and various plumbing to work with it.

>comments
>latkin wrote Jun 2, 2014 at 1:45 PM
>Possibly we could generate the same optimized loop code for all integer types

**Comment by dsyme** [comment]
Fixed by above PR
