### ISSUE TITLE
Build failure in fsharp-vsintegration-build debug

### ISSUE THREAD

**Issue by mpetruska** [Microsoft/visualfsharp#840]
Description:
`msbuild vsintegration\fsharp-vsintegration-build.proj` (debug) fails with FS3180 warnings

Repro Steps:
Go through the steps of the [devguide](https://github.com/Microsoft/visualfsharp/blob/master/DEVGUIDE.md) "3. Full Steps Before Running Tests" (debug).

Expected:
The build succeeds.

Actual:
The build fails.

Severity: medium?

Version: Microsoft/visualfsharp:master fd4d36f1f35a8c4a4d2bfa5d81f23f59382f91e3

Likely Cause:
Warnings are generated in tast.fs lines [38](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/tast.fs#L38) and [43](https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/tast.fs#L43) because /warnon:3180 is explicitly set for debug in [FSharpSource.settings.target](https://github.com/Microsoft/visualfsharp/blob/master/src/FSharpSource.Settings.targets#L29).
Strange that it is set only for debug builds...

**Comment by dsyme** [comment]
Fixed

**Comment by enricosada** [comment]
:+1: @mpetruska
