### ISSUE TITLE
Changing target F# runtime incorrectly updates assembly binding redirects

### ISSUE THREAD

**Issue by TeaDrivenDev** [Microsoft/visualfsharp#844]
I have a project (of type "Windows Application") created with VS 2013 targeting F# 3.1; the `<runtime>` section in `app.config` looks like this:

```
<runtime>
  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
      <assemblyIdentity name="System.Net.Http.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.2.22.0" newVersion="4.2.22.0" />
    </dependentAssembly>
  </assemblyBinding>
  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
      <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
    </dependentAssembly>
  </assemblyBinding>
</runtime>
```

Changing the target F# runtime to 4.0 in VS 2015 adds binding redirects to FSharp.Core 4.4.0.0, but also keeps the existing one to 4.3.1.0:

```
<runtime>
  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
      <assemblyIdentity name="System.Net.Http.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.2.22.0" newVersion="4.2.22.0" />
    </dependentAssembly>
    <dependentAssembly>
      <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="2.0.0.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="2.3.0.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="2.3.5.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="4.0.0.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="4.3.0.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="3.3.1.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="2.3.5.1" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="3.78.3.1" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="3.259.3.1" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="4.3.1.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="3.47.4.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="3.78.4.0" newVersion="4.4.0.0" />
      <bindingRedirect oldVersion="3.259.4.0" newVersion="4.4.0.0" />
    </dependentAssembly>
  </assemblyBinding>
  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
      <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
      <bindingRedirect oldVersion="0.0.0.0-4.3.1.0" newVersion="4.3.1.0" />
    </dependentAssembly>
  </assemblyBinding>
</runtime>
```

The odd thing is that for another F# project in the same solution, the same change leads to a correct update of its binding redirects, both when set to "Class Library" and "Windows Application".

**Comment by abelbraaksma** [comment]
I can confirm that this indeed happens. My current way of dealing with assembly redirects is to write them by hand and track them through DVCS (i.e., whenever an automated process updates them, I revert them). Not ideal. Would be better if VS recognizes that a single line like the following suffices and that it doesn't add specific lines, which clutters:

    <bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.0.0" />

Like you, I have not managed to create a true repro: it happens often, but when I repeat the steps, or try it in a clean project, next time it doesn't happen again (though I assume there must be some deterministic way of reproing).

**Comment by enricosada** [comment]
maybe in   https://github.com/Microsoft/visualfsharp/blob/a3dc921d93d1d68d3bc5861a2ee33dcc75c5cd5d/vsintegration/src/vs/FsPkgs/FSharp.Project/FS/AppConfigHelper.fs#L354

```fsharp
//TargetMin,  targetMax,    redirects
"4.3.1.0",    "4.4.1.0",    ["3.3.1.0";    "2.3.5.1";   "3.78.3.1";   "3.259.3.1"; "4.3.1.0"]
```

the function only check newVersion, if exists doesnt delete it, only add missing

```fsharp
redirects |> Seq.iter(fun r -> if r <> targetFSharpCoreVersion then createRedirect fsharpCoreDependentAssemblyElement (r, targetFSharpCoreVersion))
```

i dont see a check for `..` in that code

**Comment by enricosada** [comment]
btw 

```fsharp
                    Seq.where(fun (min, max, _) -> targetFSharpCoreVersion >= min && targetFSharpCoreVersion <= max)
```

how that work with strings like "3.259.41.0", "3.259.41.0"

**Comment by dsyme** [comment]
This is a very old bug report.  I checked what happens on VS2017 today and the AutoGenerateBindingRedirects means the final config file contains the right settings
