### ISSUE TITLE
"dotnet compile" on Linux can't find mscorlib

### ISSUE THREAD

**Issue by iainnicol** [Microsoft/visualfsharp#845]
On Linux, I'm struggling to compile trivial F# examples, using the .NET Core F# compiler.  To clarify, I'm not attempting to compile the compiler itself.

For example, I `cd` to `test/FSharpTestProjects/TestLibrary` in the dotnet cli repo.
I run `dotnet restore` then `dotnet compile`.  It gives me the truncated error message:

```
~/dotnet/cli/test/FSharpTestProjects/TestLibrary/unknown(1,1): error FS0078: Unable to find the file 'mscorlib.dll' in any of
```

 I'm not 100% certain the problem is Linux specific, but previously I was able to get similar steps working on Windows.

@enricosada, have you attempted to run dotnet compile on LInux?  I was under the impression @KevinRansom added support so that fsc.exe should work on Linux.

**Comment by KevinRansom** [comment]
Yeah I'm sorry about that.

on the windows desktop there was a ton of magic dealing with assembly resolution including (shudders) referencing msbuild, none of which is appropriate for cross platform development.    we are still in the process of figuring out what that should look like on the coreclr based fsc and fsi tools.

Currently fsc.exe requires the Command line switches 
--targetprofile:netcore --noframework --simpleresolution

and a -r: with the full path to each assembly referenced by the application.

The dotnet cli tool should create a better command line experience around this for project json based apps.  And we are trying to get consensus about the appropriate resolution mechanism for FSI and FSC.

Do take a look at the dotnet cli tool and see if that will simplify your life for now.

Kevin

**Comment by iainnicol** [comment]
Hi.  Thanks for the detailed info.  I'll take a look at what the dotnet cli is doing compared to your recommendation.

**Comment by cbowdon** [comment]
FWIW I've experienced the same error on OSX too.

- dotnet new --lang F#
- Setup project.json to target net46
- dotnet restore
- dotnet compile

    path/to/my/project/unknown(1,1): error FS0078: Unable to find the file 'mscorlib.dll' in any of
    <empty list of locations that it searched for>

Building and running traditional projects/scripts works just fine, only dotnet cli gives this error. Let me know if there's any more detail I could helpfully provide.

**Comment by enricosada** [comment]
@cbowdon can you add the project.json? Without source files list, it's not needed, i pretty much much need frameworks and dependencies

You added `net46` to framework list or replaced the `netstandardapp` ?

**Comment by cbowdon** [comment]
Replaced:
````json
    "frameworks": {
        "net46": {
            "dependencies": {
                "FSharp.Core": "4.0.0.1"
            },
            "frameworkAssemblies": {
            }
        }
    }
````
(global dependencies empty)

dotnet version:
````
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
````

Using the LKG F# from your handy page.

**Comment by KevinRansom** [comment]
I don't think this is any longer the case.
