### ISSUE TITLE
Invalid behavior in the Visual Studio debugger for F# when using DebuggerTypeProxy attribute with certain types

### ISSUE THREAD

**Issue by GregRos** [Microsoft/visualfsharp#846]
**Version:** Visual Studio 2015, .NET Framework 4.5.2, F# 4.0

The issue does not appear in Visual Studio 2013.

Consuming the following C# class from F# causes the F# debugger to behave strangely.

```
[DebuggerTypeProxy(typeof(Test<>.Proxy))]
public class Test<T> {

    public Test(T value) {
        ShouldBeHidden = value;
    }

    class Proxy {
        Proxy(Test<T> t) {}

        public int ShouldBeVisible {
            get;
        } = -1;
    }

    public T ShouldBeHidden { get; }
}
```

In the C# debugger, viewing an instance of the type works as expected.
Code: `var t = new Test<int>(456)`
![image](https://cloud.githubusercontent.com/assets/1788329/12066320/8c1303d2-afee-11e5-8c9c-65497fe34a78.png)

However, in the F# debugger, this occurs instead:
Code: `let sd = ConsoleApplication1.Test(456)`
![image](https://cloud.githubusercontent.com/assets/1788329/12066309/6ac1ccb8-afee-11e5-92d4-f0c28b77e66b.png)

Note that the number the debugger displays has nothing to do with the actual number.

**Comment by saul** [comment]
I can't reproduce this on Roslyn master with the latest F# nightlies:

![image](https://cloud.githubusercontent.com/assets/64654/25247558/1147e42e-2603-11e7-897c-d3c8fea85331.png)

Can close as fixed. @cartermp

**Comment by cartermp** [comment]
Yup, and this should be live in VS 2017 Update 3.  Thanks @saul!
