### ISSUE TITLE
Type Inference broken on VS2015 Update1

### ISSUE THREAD

**Issue by gmpl** [Microsoft/visualfsharp#855]
Hi.
I would need to investigate further to give a small repro of the issue, but before doing that I can tell you right now that I have a script that works perfectly in VS2015 (FSharp.Core.dll 4.40.23020.0) and it fails in VS2015 Update1 (FSharp.Core.dll 4.40.23413.0).
I will to invest some hours, may be days to come up with a small repro but before doing that, can you tell me if there is already a known issue between those versions? Or point me to a specific change that might have affected type inference?

Thanks

**Comment by enricosada** [comment]
can you paste the lines without smaller repro? maybe it's easier.
type inference on what? class, members, overload resolution, param array?

**Comment by gmpl** [comment]
It uses static constraints and overload resolution, it's a Monad Transformer [sample code from F#+](https://github.com/gmpl/FSharpPlus/blob/master/FSharpPlus/Samples/MonadTransformers.fsx) I know you will not be interested in supporting this kind of stuff but it's a breaking change and it might have impacted other code as well. Indeed I have more cases in that project related to the Lenses library.
In the script I'm linking, by adding a type annotation the issue is solved, but that was never needed before.

**Comment by enricosada** [comment]
thx @gmpl , i think usually @dsyme help with these :smile: , too complicated for me

**Comment by gmpl** [comment]
Thanks for your interest @enricosada anyway this issue at the moment is more a question that an issue.
I'm not 100% sure the problem is related to those different .dll versions, if I find the problem is something else I will close the issue but in principle would like to know if anybody is aware of a change between those versions that might have affected type inference.

**Comment by dsyme** [comment]
@gmpl - The changelog is here: https://github.com/Microsoft/visualfsharp/blob/master/CHANGELOG.md

It's possible one of the bug fixes related to escaping type variables is related to what you're seeing.  A minimized repro would be very helpful of course :) 

Thx

**Comment by dsyme** [comment]
Closing until a repo is given (per CONTRIBUTING.md)

**Comment by gmpl** [comment]
Thanks @dsyme and I agree to close it, at least until I have more information.
