### ISSUE TITLE
Private methods on Record types cause transtive dependencies on referenced assemblies

### ISSUE THREAD

**Issue by colinbull** [Microsoft/visualfsharp#86]
Originally from http://stackoverflow.com/questions/27188097/f-compiler-requires-project-reference-but-method-is-private
Given the following program containing two libraries (Library & SubLibrary) and a console application. 

In the ConsoleApp/Program.fs 

```
open Library

[<EntryPoint>]
let main argv = 
    printfn "%A" argv

    let banana = { Value = 42 }
    0
```

in Library/Library1.fs

```
namespace Library

open SubLibrary

type Banana = 
    { Value : int}

    member private x.TakeWidget (w: Widget) =
    { x with Value = w.Value }
```

and in SubLibrary/Library1.fs

```
namespace SubLibrary

type Widget = { Value: int }
```

the problem is that when we try and compile the application we get the following error, 

```
Error   6   The type referenced through 'SubLibrary.Widget' is defined in an assembly that is not referenced. 
You must add a reference to assembly 'SubLibrary'.  c:\temp\ConsoleApplication1\ConsoleApplication1\Program.fs  7   18  ConsoleApplication1
```

Now I wouldn't expect this as the member `TakeWidget` is set to private and the Widget type isn't exposed anywhere outside of the.
However if I change the Banana type to become a class

```
open SubLibrary

type Banana(v:int) =
    member val Value = v with get, set

    member private x.TakeWidget (w: Widget) =
        x.Value <- w.Value
```

then things work as expected. Looking at the IL it appears to be generating identical _internal_ methods for both the class and record versions. 

```
.method assembly hidebysig instance void 
        TakeWidget(class [SubLibrary]SubLibrary.Widget w) cil managed
{
  // Code size       15 (0xf)
  .maxstack  8
  IL_0000:  nop
  IL_0001:  ldarg.0
  IL_0002:  ldarg.1
  IL_0003:  call       instance int32 [SubLibrary]SubLibrary.Widget::get_Value()
  IL_0008:  callvirt   instance void Library.Banana::set_Value(int32)
  IL_000d:  nop
  IL_000e:  ret
 } // end of method Banana::TakeWidget
```

After having a quick look at the F# 3.0 language spec, nothing immediately jumps out at me as to why this is the behavior. Hence why I'm raising this as an issue. (Apologies if it is in there).

**Comment by dsyme** [comment]
I've checked this with the following repro steps and it appears fixed (no errors on compilation):

```
C:\GitHub\dsyme\visualfsharp>fsc /target:library lib1.fs
C:\GitHub\dsyme\visualfsharp>fsc /target:library lib2.fs /r:lib1.dll
C:\GitHub\dsyme\visualfsharp>fsc app.fs /r:lib2.dll
```
