### ISSUE TITLE
can't use `for i in view do` within async {} when view is a System.Data.DataView.

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#869]
Consider this code in a .fsx:

```fsharp
#r "System.Data"
#r "System.Data.DataSetExtensions"

open System.Data
let datatable = new DataTable()

let view =
  datatable
    .AsEnumerable()
    .AsDataView()

for r in view do
  ()

let filterWorkflow =
  async {
    for r in view do
      ()
  }
```

it fails to compile with following message when doing so within an `async` computation expression while it works fine outside of it.

```
The type 'DataView' is not compatible with the type 'seq<'a>'. 2. . Type constraint mismatch. The type DataView is not compatible with type seq<'a>. The type 'DataView' is not compatible with the type 'seq<'a>'.
```

The code seems legit to me. 

`System.Data.DataView` implements a large amount of interfaces and somehow the compiler fails to pick up that it implements `IEnumerable` when used within `async`.

It seems that `IEnumerable` is done with implicit implementation in the C# code for `DataView` while other interfaces are defined via explicit interface implementation.

I don't know why this type of resolution would differ within a computation expression but it seems to be what is failing here.

**Comment by enricosada** [comment]
@smoothdeveloper i think the problem is `IEnumerable` vs `IEnumerable<T>` 

the async expect a `seq<'t>`, an `IEnumerable<T>`.

if you try

```fsharp

let viewTyped = view |> Seq.cast<DataRowView>;;

let filterWorkflow =
  async {
    for r in viewTyped do
      ()
  }
```

that works.

the error is correct

```
The type 'DataView' is not compatible with the type 'seq<'a>'
```

because `DataView` implement lots of interface, but not generic

**Comment by smoothdeveloper** [comment]
@enricosada thanks for update.

Do you know why the same code works outside of `async`?

As a user, it's strange that the same code outside the `async` computation can't be just moved within it.

**Comment by enricosada** [comment]
Because the for inside async it's not a special instruction, but a function of a computed expression

https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/control.fsi#L533

```fsharp
member For: sequence:seq<'T> * body:('T -> Async<unit>) -> Async<unit>
```

The enumerable ( not generic ) it's a corner case in modern .net, better without. 
It's always possible to make it typed with `Seq.cast`

**Comment by enricosada** [comment]
My feedback it's to try to improve error messages. 
For example add some suggestion about 

```
seq<'t> expected, found IEnumerable, it's missing a Seq.cast?
```

We can improve a lot learning from elm-lang

**Comment by smoothdeveloper** [comment]
@enricosada thanks, explanation makes sense alas the language fails at principle of least surprise on this (code outside the CE assumed to work inside of it).

The current error message is still good as soon as one is aware of this type of distinction.

I guess we can close that issue.

**Comment by dsyme** [comment]
These old .NET v1.0 APIs supporting just IEnumerable are becoming rarer and rarer, and I doubt there are any in Core CLR libraries for example.

So one far off day we may be able to get rid of the special language rules for these types (which are much the same as C# language rules).
