### ISSUE TITLE
Passing a function as an argument to an active pattern doesn't work...

### ISSUE THREAD

**Issue by kolektiv** [Microsoft/visualfsharp#870]
Specifically, if I define an active pattern like this:
```fsharp
let (|Partial|_|) f c =
    read f c
```
where the read function takes a function in to c (some data structure). C may be None, in which case None is returned, etc. so a classic simple partial active pattern.

If I use that like this:
```fsharp
let f =
    fun x -> x.SomeProperty

let test =
    function | Partial f p -> ...
             | _ -> ...
```

...everything is fine. If I wish to use the function inline however, it will merely complain about an unexpected identifier at "fun":
```fsharp
let test =
    function | Partial (fun x -> x.SomeProperty) p -> ... // Nope.
             | _ -> ...
```
I'm not sure if this is a bug, by design, parser edge case, etc. Would it be expected that this would work, or are there obvious reasons why it can't?

**Comment by dsyme** [comment]
This is by design, see the F# Language Specification where the grammar for patterns doesn't include all expression forms.

Language suggestions go to http://fslang.uservoice.com.  Language design Q&A is mostly on stackoverflow.com.
