### ISSUE TITLE
intellisense trips when parent expression is incomplete

### ISSUE THREAD

**Issue by smoothdeveloper** [Microsoft/visualfsharp#875]
Consider this code:

``` fsharp
type Foo = {id:int}
let foos = [{id=1};{id=2}]
sprintf "%i" (foos |> Seq.find (fun f -> f.
```

when I try to complete at the last `.` of the last line, I don't get any intellisense.

the completion works in this case:

``` fsharp
foos |> Seq.find (fun f -> f.
```

Since the expression is put within open paren, I'd expect the completion context to not be affected by the state of whole expression (which is invalid until I finish typing the code).

**Comment by dsyme** [comment]
@vasily-kirichenko @cartermp  If you get a chance could you try this in the VS2017 bits please? Just to update the status, thanks

**Comment by cartermp** [comment]
This looks fixed in vs2017:

![looks-good](https://cloud.githubusercontent.com/assets/6309070/22563278/d150a988-e934-11e6-94ad-2ca3e033ed1f.PNG)

There's an argument for the case that `id` should be the first item in the completion list, but the bug as-stated seems fixed to me.

**Comment by smoothdeveloper** [comment]
@cartermp this is great!
