### ISSUE TITLE
It's review time!

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#877]
Why don't you tell my Managers how you think I have done over the last 6 months or so ...

When providing feedback consider all three of the following ways of having impact on the community, product, and project results:
* Key individual accomplishments that contributed to community, product, and project results
* Results that build on the work, ideas, or effort of others
* Contributions to the success of others
* What have I done well?
* What have I done poorly?
* Do I share enough? accomplish enough? Am I respectful?, disrespectful? Am I open enough, do you feel involved?
* What's my code like?
* Please provide specific examples:

Please email @jaredpar with your feedback.

Thanks

Kevin

**Comment by manofstick** [comment]
@jaredpar 

OK; I'll bite.

I'm creator of #513, a bit of a rambling pull request, but one that performs a valid and valuable result (IMnsHO!) (also #549, #577 & #594 - they were basically spin offs from #513, and maintainter of [FSharp.Quotations.Evaluator](https://github.com/fsprojects/FSharp.Quotations.Evaluator))

Anyway, my gripe relates to #513 where there was lack of communication after @latkin left. I would of appreciated (and still would?!?!) some updated timeframe as to when (if!?!?!?) this work is going to be merged.

It definitely deterred me from spending time working of further improvements (although, to be fair, my 2 daughters also deter me from work as well - probably more so!)

I don't mean this to cause grief to @KevinRansom, as I can see he has been busy getting the coreclr support across the line, but just me being selfish banging on for what's most important to me!

**Comment by enricosada** [comment]
@manofstick i think we should mail @jaredpar directly ( the mail is the profile )

**Comment by dsyme** [comment]
closing old discussion :)
