### ISSUE TITLE
error FS0193: internal error: Method not found: 'FileSystem Shim.get_FileSystem()'.  running tests

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#883]
If you see an error like this: when running AppVeyor it is because the version of fsharp.compiler.dll is loaded from the GAC rather than the LKG directory.

````
C:\Microsoft>"C:\Microsoft\visualfsharp\tests\..\lkg\FSharp-14.0.23413.0\bin\Fsi.exe" --exec --nologo "C:\Microsoft\visualfsh
arp\tests\\Convert-NUnit2Args-to-NUnit3Where.fsx" -- "Smoke" "ReqPP,NOOPEN,NO_CI,Expensive"


error FS0193: internal error: Method not found: 'FileSystem Shim.get_FileSystem()'.
```

When we created the LKG we used a preview of the compiler that had some of Don's recent reformatting PR's in it, rather than the DEV15 RTM version, it had a bug fix we wanted to use.

I think the solution is to for us to downgrade the LKG to the RTM version of the compiler:

Kevin

**Comment by KevinRansom** [comment]
It would appear that I have installed a preview on my machine with the refactored code.  So be careful using the previews.

**Comment by KevinRansom** [comment]
The sooner we have an entirely coreclr based LKG the sooner I will like it.

**Comment by dsyme** [comment]
> It would appear that I have installed a preview on my machine with the refactored code. So be careful using the previews.

I think this is because of this line in appveyor-build.cmd:

    call vsintegration\update-vsintegration.cmd release

As noted in DEVGUIDE.md this clobbers the installed F# SDK on the machine under ``c:\Program Files`` and is thus highly invasive on the VS installation.  I don't think this should be necessary to run tests.

I'm going to submit a PR to remove this line and see if CI testing still passes.

**Comment by dsyme** [comment]
See @enricosada's comment  https://github.com/Microsoft/visualfsharp/pull/904#issuecomment-175637484 The 

    call vsintegration\update-vsintegration.cmd release

was added to support testing of portable templates, and it's possible that command needs to be run prior to a full test run.  However that currently means that anyone following the DEVGUIDE.md instructions will trash the F# installation on their machine irrevocably.

I think we should remove this line from the Appveyor and Jenkins CI for now (by pulling [this PR](https://github.com/Microsoft/visualfsharp/pull/904)) and add instructions in TESTGUIDE.md that it may be needed prior to some specific tests.

**Comment by KevinRansom** [comment]
@dsyme I would prefer a better solution than just removing the line and not running all of the tests.  I expect it's quite easily solvable using msbuild and binding redirect magic.  

It's just a matter of someone figuring out the magic.

**Comment by enricosada** [comment]
@KevinRansom i think it's not needed for ci build in appveyor-build.cmd

the only vs test we run are [the unit test](https://github.com/Microsoft/visualfsharp/blob/95fb299ab8588b112246f986148de9da8dbc9a4b/appveyor-build.cmd#L290-L293),  no need for portable lib and update-vsintegration.cmd (i think)

```
if '%TEST_VS%' == '1' (
%_msbuildexe% vsintegration\fsharp-vsintegration-unittests-build.proj /p:Configuration=Release
@if ERRORLEVEL 1 echo Error: VS integration unit tests build failed && goto :failure
)
```
.

The others vs test are not run, see [appveyor-build.cmd@350](https://github.com/Microsoft/visualfsharp/blob/95fb299ab8588b112246f986148de9da8dbc9a4b/appveyor-build.cmd#L350) 

```
rem tests for TEST_VS are not executed
```

**Comment by dsyme** [comment]
@KevinRansom I agree we need to get to the point where we can safely run all tests in CI and on people's dev machines (though preferably without overwriting the installed VS bits under Program Files)

**Comment by otawfik-ms** [comment]
Closing this since #904 was already pulled.
