### ISSUE TITLE
Inconsistent execution of `do` statements in F# modules

### ISSUE THREAD

**Issue by eiriktsarpalis** [Microsoft/visualfsharp#890]
Consider the following module definition that is part of a compiled assembly:
```fsharp
module Test

    do printfn "Test"

    let x = 42

    let f n = x + n
```
In this example, the print side-effect will never fire, even if we call the `Test.f` function. If we change the definition to the following:
```fsharp
module Test

    do printfn "Test"

    let x = [42]

    let f n = n :: x
```
Then the side-effect will trigger as expected. Even stranger,
```fsharp
module Test

    do printfn "Test"

    let private x = [42]

    let f n = if n = 42 then x else [n]
```
only fire after `Test.f 42` is called for the first time. 

While this behaviour is to be expected given the code generated by the F# compiler in modules, it definitely has the smell of a bug. My initial expectation was that the side-effect should always fire on first  consumption of the module regardless of its constitution.

**Comment by dsyme** [comment]
This is covered in the F# Language Spec section on initialization, could you review that and reopen if you continue to see an issue? Thanks

**Comment by eiriktsarpalis** [comment]
Thanks. TBH I still find this to be rather counterintuitive behaviour, which can be a source of bugs. I actually discovered this precisely because of a slight change of my code that caused things to fail.

**Comment by dsyme** [comment]
Out of interest, could you explain the nature of the static initialization that you were performing where this come up, that is the overall pattern being used (e.g. "registering things into a global table" or "initializing another library" etc.)

thanks

**Comment by eiriktsarpalis** [comment]
It was initializing state for Vagabond in a module that wasn't defining any values. My expectation was that  the static initializer was guaranteed to run before *any* use of that particular file.

**Comment by eiriktsarpalis** [comment]
Actually a lot of my code depends on this. It only incidentally happens to work because none of the modules were like the one above.
