### ISSUE TITLE
Create perf test suite inside a `bench` directory

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#898]
There are lots of performance improvements suggested by community, but sometimes it's not clear how to make a good benchmark/
The reason is: i found a possible bottleneck in code (or i think can be improved), now what? Let's make it easier to validate the idea.

Another reason is: When the pull request is committed, the perf test is often lost.

I think we should save the benchmarks inside a `bench` directory, to:
- make it easier to create an experiment, using a similar perf test (for example i want to improve a function who use a collection, i'll find something similar in `bench/fsharp.core/collections` maybe )
- promote good tests as stable perf tests, so it's possibile to have a perf bench with a baseline
- find regressions of most used fsharp.core functions or compiler behaviour on sample projects
- create a shared knowledge and guidelines around perf testing
  - memory pressure
  - how to show time results
  - how to show memory, il, asssembly
  - how to choose good inputs (for example empty array, small, big)
  - expected perf of functions characterized by similar growth rates ( big O )
- in the future, create an automated and stable benchmark server

`bench` can be divided in:
- compiler: for example compile time of a small/medium/large project, etc
- fsharp.core: for example collection functions, inline, etc

It's also possible to choose a modern bench framework ( for example https://github.com/PerfDotNet/BenchmarkDotNet or Microsoft.Xunit.Performance or Nunit ) to make it easier to run it (xplat) and show results (il/memory/graph) without common issues

**Comment by cloudRoutine** [comment]
I think this is a fantastic idea, one I hope will become a more common practice among F# OSS projects. Once a solid workflow with some conventions has been established I think it'd be a great addition to [the project scaffold](https://github.com/fsprojects/ProjectScaffold)

**Comment by dsyme** [comment]
I recommend we create this outside this repo, to avoid PR pileup here.  For example in github.com/fsprojects.

**Comment by enricosada** [comment]
ok about the separate repo for the runner, this repo alredy do lot of things, easier fsproject

I think the repo should have a xplat script (fsx or fake) parametrized to run all/specific test with different compilers:

compiler parameter:

- compiler from nuget (baseline)
- build and use fsc from a specific repo/commit (like a pr, master)
- fsc at specific path (local testing)

test source:

- from specific path, a test.fs ( local development )
- from gist ( to use it in pr testing )

so a test it's a dsl like

```fsharp
perf {
    let! fscFromNuget = Compiler.getFromNuget("1.0.2");
    let! fscFromCommit = Compiler.build ("http://.../repo.git", "sha1") ("buildscript", "path/of/built/fsc.exe")
    let! fscFromPath = Compiler.fromPath @"d:\example\fsc.exe"

    let! script = TestScript.fromPath @"d:\perfimprovement\array_map_test.fs"

    //or TestScript.FromGist

    do! PerfTest.run script [ fscFromNuget; fscFromCommit; fscFromPath ] 
}
```

Runner can be nunit/xnunit.
Graph libraries of fslab :smile: 

Good tests can be added to a stable suite inside repo


I think it's better to have perf test in the same repo, but this repo already does lot of stuff.

pro in same repo:

- test is committed inside pr, so easy to test
- test is merged when pr is merged, so it's easy to have an history
- test works always ( a test cannot execute on an older version who doesnt support the function )
- run all perf test is: clone -> build -> run perf script

cons:

- this repo is already big
- more difficult to parametrize on fsharp.core, compiler
- more difficult to evolve

**Comment by dsyme** [comment]
Closing old discussion (the idea is a good one, just no need to track it with an issue)
