### ISSUE TITLE
Internal error in FSI: FS0192: binding null type in envBindTypeRef

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#9]
Opened by: [swlaschin2](https://www.codeplex.com/site/users/view/swlaschin2)

I can reproduce this error in FSI in VS2012 , VS2013 and in tryFsharp.org
* In VS2012 and VS2013 
error FS0192: internal error: binding null type in envBindTypeRef
* In tryFsharp.org (as of 2014-12-09) 
error FS0193: internal error: Error 0x2115.
Here is a minimal example that causes the error:
````fsharp
// fails to compile
// error FS0192: internal error: binding null type in envBindTypeRef
let ``1,`` x = 
    [||] |> Array.fold (+) ","
````
But minor variants of the code do compile! 
````fsharp
// remove comma from function name and it compiles, so the function name is involved?        
let ``1`` x = 
    [||] |> Array.fold (+) ","
// change fold to map and it compiles, so something to do with fold as well?        
let ``1,`` x = 
    [||] |> Array.map ((+) "")
````
Not sure if it is related to: https://github.com/Microsoft/visualfsharp/issues/10

**Comment by forki** [comment]
Mini-repro:

run fsi with:

    module ``Generic IKEv1, AuthIP, and IKEv2`` =
      [<Literal>]
      let Category = "Generic IKEv1, AuthIP, and IKEv2";;
