### ISSUE TITLE
Indexer inference bug with types that are cyclic

### ISSUE THREAD

**Issue by TIHan** [Microsoft/visualfsharp#900]
I haven't tried on the latest F# master yet, but encountered this bug.

```fsharp
type Test () =
    let test2 = Test2 ()

    member this.Truth : int = 
        let xs = test2.IntArray
        xs.[0]

and Test2 () =

    member this.IntArray = [|0|]
```
```
Error FS0752: The operator 'expr.[idx]' has been used on an object of indeterminate type based on information prior to this program point. Consider adding further type constraints (FS0752) 
```
This is referring to `xs.[0]`.

It also fails like this:
```fsharp
type Test () =
    let test2 = Test2 ()

    member this.IntArray = test2.IntArray

    member this.Truth : int = 
        let xs = this.IntArray
        xs.[0]

and Test2 () =

    member this.IntArray = [|0|]
```

To fix it, you can be explicit with the type:
```fsharp
type Test () =
    let test2 = Test2 ()

    member this.Truth : int = 
        let (xs: int []) = test2.IntArray
        xs.[0]

and Test2 () =

    member this.IntArray = [|0|]
```
or re-order
```
type Test2 () =

    member this.IntArray = [|0|]

type Test () =
    let test2 = Test2 ()

    member this.Truth : int = 
        let xs = test2.IntArray
        xs.[0]
```

I'm thinking this is an inference bug that is specific to the indexer.

**Comment by dsyme** [comment]
This looks by design by me.  The type of test2.IntArray is not known in order to resolve the use of dot notation, so type annotations are needed

**Comment by TIHan** [comment]
Ok I guess. We had someone who spent a great deal of time figuring out what I described. The intellisense was showing the type as `int []` and he was unable to index into it; so it was mis-leading.

**Comment by dsyme** [comment]
Ah yes, that's a somewhat separate tooling issue (I think there is an issue - or several issues - recorded for this)
