### ISSUE TITLE
Remove Seq.rev

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharp#902]
If's awful. We can make it obsolete in the next release and remove in the release after next.

**Comment by kolektiv** [comment]
Seconded. The presence of this implies that such an action makes sense for a sequence - I don't think it does. At the very least this should come with some well documented XML doc warnings that it could explode in surprising ways.

**Comment by enricosada** [comment]
:+1: xml document warning only, sometimes it's useful. 
It's like other functions who consume the whole input sequence before return output

**Comment by vasily-kirichenko** [comment]
If you consume entire sequence, convert it to an array first. It's very explicit and safe.

**Comment by dsyme** [comment]
Per CONTRIBUTING.md, please take design change suggestions for the core library through fslang.uservoice.com. 

Adding a rule to FSharpLint may be the best first course of action.

**Comment by dsyme** [comment]
Closing as it's a design issue

**Comment by forki** [comment]
https://fslang.uservoice.com/forums/245727-f-language/suggestions/11602140-remove-seq-rev-from-fsharp-core-again

**Comment by eiriktsarpalis** [comment]
I try to think of `Seq.rev` as a `Seq.toArray` in disguise. I think that its type signature `seq<'T> -> seq<'T>` is confusing because people might assume it is not an eager combinator. Perhaps explicitly changing it to `seq<'T> -> 'T []` would inform its users of the risks involved.

**Comment by enricosada** [comment]
> At the very least this should come with some well documented XML doc warnings that it could explode in surprising ways.

we can add a `<remarks>Consume the whole input sequence before yielding the first element</remarks>` in [src/fsharp/FSharp.Core/seq.fsi xmldoc](https://github.com/Microsoft/visualfsharp/blob/1bbc36038bc7c63e9b5dbd3fa1a59b3c474141a1/src/fsharp/FSharp.Core/seq.fsi#L956-L959)

**Comment by forki** [comment]
Changing it to return an array is still breaking and not really better than https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Core/seq.fs#L1832

**Comment by forki** [comment]
Regardless of the decision about the UV - the XML comment change would be a good thing.

**Comment by enricosada** [comment]
easier do it thank discuss :smile: 
if there are other similar functions (consume whole input), i can add these in the pr, just comment it

**Comment by isaacabraham** [comment]
I have a slightly different view on this. Yes, it should be clear that calling rev has to traverse the entire sequence, so comments that warn of this are a good thing. It's unfortunate that going from seq -> seq also means the type system can't help us here. But is removing the method entirely really necessary? Either warnings or going from seq to array explicitly would be a big help whilst still leaving the method there for discoverability.

Flame away...

**Comment by vasily-kirichenko** [comment]
About adding a FsLint rule or compiler warning, I thinks both ideas are rather strange.

**Comment by enricosada** [comment]
ObsoleteAttribute it's a warning in practice, but we need to wait @dsyme decision

Lint rule and xmldoc can help meanwhile
