### ISSUE TITLE
Open build is broken for FSharp.Core targeting .NET 3.5

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#914]
I believe the recent PR to optimize generic comparison broke the net20 build of FSharp.Core.

A handful of errors matching
`src\fsharp\FSharp.Core\prim-types.fs(1333,31): error FS0043: The type 'Tuple<'a,'b>' does not have 'null' as a proper value`
`src\fsharp\FSharp.Core\prim-types.fs(4170,63): error FS0066: This upcast is unnecessary - the types are identical`

I know that net20 version is freeze-dried in terms of what actually ships with VS, but if it is no longer supported for open build, either, then we should:

  - Remove it from DEVGUIDE
  - Remove all of the .NET 2 compat code in FSharp.Core

Otherwise the open net20 build should be fixed.

**Comment by KevinRansom** [comment]
@latkin .  A ton of stuff is broken.  For a bunch of reasons.  Most of which equate to I should have pulled fewer PR's.  Hopefully I can get stuff fixed back up before too long.

**Comment by latkin** [comment]
@KevinRansom no worries, just getting stuff logged so it's not forgotten

**Comment by dsyme** [comment]
OK, the net20 instructions removed from DEVGUIDE.md in #933
