### ISSUE TITLE
Various codegen tests failing

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#918]
I'm seeing the following failures on master. Have not dug in to see what the delta is.

```
Optimizations\GenericComparison	#  (Compare07.fs - NetFx40)
Optimizations\GenericComparison	#  (Compare10.fs - NetFx40)
Optimizations\GenericComparison	#  (Equals06.fs - NetFx40)
Optimizations\GenericComparison	#  (Equals09.fs - NetFx40)
Optimizations\GenericComparison	#  (Hash09.fs - NetFx40)
Optimizations\GenericComparison	#  (Hash12.fs - NetFx40)
```

**Comment by manofstick** [comment]
I dare say that would be #513 - that was slurped in relatively recently? Lots of stuff around equality gets inlined, so it could end up with different codegen? But I see green on master build? Are you doing something extra?

**Comment by dsyme** [comment]
@manofstick Not all tests are run by CI. I'm going to track all current test failures on master with bug https://github.com/Microsoft/visualfsharp/issues/915 and close this.

**Comment by dsyme** [comment]
@manofstick Please see https://github.com/Microsoft/visualfsharp/pull/944#issue-132021537 and take a careful look at the tailcalls that have been removed.
