### ISSUE TITLE
For tupled functions it's possible to break/step before the arguments have correct debug display 

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#92]
Migrated from fsharp/fsharp#369 

From @DavidKarlas 

> Bug reported in XS also reproducible in VS as debugger bug I came to conclusion it's compiler bug... > See comment 3 for more details.
> see https://bugzilla.xamarin.com/show_bug.cgi?id=21537

**Comment by enricosada** [comment]
From @7sharp9

Given the following program:
```fsharp
[<EntryPoint>]
let main argv = 

    let combineTwoTupledStrings (one, two)=
        sprintf "First:%s Second:%s" one two

    printfn "%s" <| combineTwoTupledStrings ("hello", "everyone")
```
When a break point is placed on on the line: `sprintf "First:%s Second:%s" one
two` 

The value `one` is incorrectly shown as `null`
The value `two` is incorrectly shown as `Unknown Identifiew`
The locals display does not include `two`

![screenshot showing 'one'](https://bugzilla.xamarin.com/attachment.cgi?id=7469)
![screenshot showing 'two'](https://bugzilla.xamarin.com/attachment.cgi?id=7470)

**Comment by enricosada** [comment]
From Ram Chandra

I have checked this issue and I am getting the same behavior.

Steps I followed:

1. Create a "F# console application on XS".
2. Replace the code of "Program.fs" in file with following code 
    ```fsharp
    [<EntryPoint>]
    let main argv = 

        let combineTwoTupledStrings (one, two)=
            sprintf "First:%s Second:%s" one two

        printfn "%s" <| combineTwoTupledStrings ("hello", "everyone")
        0
    ```
3. Place a breakpoint on following line :
    ```sprintf "First:%s Second:%s" one two``
4.  Debug the application.

When I hover the cursor over the value of `one`, I observed that the suggestion
popup display it `null` and the values of `two` is incorrectly shown as `Unknown
Identifier`. I have checked the same on 'Local' debug window and I am getting
the same behavior.

[Screencast](http://www.screencast.com/t/inFTI0GJipX)

Environment Info:
```
Mac OS X 10.9.3
Xamarin Studio: 5.2 (build 384)

Build Information
Release ID: 502000384
Git revision: 09e06441e39ea272ddda63758fd53013157f7e45
Build date: 2014-07-16 11:15:54-04
Xamarin addins: 2d11dd4dad5b35ca83f24d70e965792a47be8291
```

**Comment by enricosada** [comment]
From @DavidKarlas:

This is compiler bug not debugger. You can confirm this by compering results in
VisualStudio(it's same behaviour).

Problem is that this method in C# looks like this:
```csharp
public override string Invoke (Tuple<string, string> tupledArg)
{
  string one = tupledArg.get_Item1 ();
  string two = tupledArg.get_Item2 ();
  FSharpFunc<string, FSharpFunc<string, string>> clo =
ExtraTopLevelOperators.PrintFormatToString<FSharpFunc<string,
FSharpFunc<string, string>>> (new PrintfFormat<FSharpFunc<string,
FSharpFunc<string, string>>, Unit, string, string, Tuple<string, string>>
("First:%s Second:%s"));
  return FSharpFunc<string, string>.InvokeFast<string> (new
Program.combineTwoTupledStrings@5-1 (clo), one, two);
}
```

And .mdb(or .pdb) method information look like this:
```xml
<method token="0x6000007" signature="System.String
Program/combineTwoTupledStrings@5::Invoke(System.Tuple`2&lt;System.String,System.String&gt;)">
  <sequencepoints>
  <entry il="0x0" row="5" col="9" file_ref="1" />
  </sequencepoints>
  <locals>
  <entry name="one" il_index="0" scope_ref="2" />
  <entry name="two" il_index="1" scope_ref="3" />
  </locals>
  <scopes>
  <entry index="0" start="0x0" end="0x2d" />
  <entry index="1" start="0x0" end="0x2d" />
  <entry index="2" start="0x7" end="0x2d" />
  </scopes>
</method>
```
So when debugger step into this method `string one = tupledArg.get_Item1 ();` is
not called yet and variable `two` is not visible yet because it's part of scope
3 which starts at `ILoffset 0x7`... So doing few steps results into entering into
scope 3 and both variables being set...

What compiler should do is set sequence point to `IL 0xE` or something like
that(so after both variables are set) instead of `0x0`...

Pasting also IL output:
```il
.method public strict virtual 
  instance string Invoke (
    class [mscorlib]System.Tuple`2<string, string> tupledArg
  ) cil managed 
{
  // Method begins at RVA 0x20f0
  // Code size 45 (0x2d)
  .maxstack 7
  .locals init (
    [0] string,
    [1] string,
    [2] class [FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<string, class
[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<string, string>>
  )

  IL_0000: ldarg.1
  IL_0001: call instance !0 class [mscorlib]System.Tuple`2<string,
string>::get_Item1()
  IL_0006: stloc.0
  IL_0007: ldarg.1
  IL_0008: call instance !1 class [mscorlib]System.Tuple`2<string,
string>::get_Item2()
  IL_000d: stloc.1
  IL_000e: ldstr "First:%s Second:%s"
  IL_0013: newobj instance void class
[FSharp.Core]Microsoft.FSharp.Core.PrintfFormat`5<class
[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<string, class
[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<string, string>>, class
[FSharp.Core]Microsoft.FSharp.Core.Unit, string, string, class
[mscorlib]System.Tuple`2<string, string>>ctor(string)
  IL_0018: call !!0
[FSharp.Core]Microsoft.FSharp.Core.ExtraTopLevelOperators::PrintFormatToString<class
[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<string, class
[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<string, string>>>(class
[FSharp.Core]Microsoft.FSharp.Core.PrintfFormat`4<!!0, class
[FSharp.Core]Microsoft.FSharp.Core.Unit, string, string>)
  IL_001d: stloc.2
  IL_001e: nop
  IL_001f: ldloc.2
  IL_0020: newobj instance void
Program/'combineTwoTupledStrings@5-1'::.ctor(class
[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<string, class
[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<string, string>>)
  IL_0025: ldloc.0
  IL_0026: ldloc.1
  IL_0027: call !!0 class
[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<string,
string>::InvokeFast<string>(class
[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!0, class
[FSharp.Core]Microsoft.FSharp.Core.FSharpFunc`2<!1, !!0>>, !0, !1)
  IL_002c: ret
}
```

**Comment by latkin** [comment]
This is definitely a debug range bug, but as I mentioned on Codeplex, if you continue single-stepping (through invisible code) the locals do populate correctly (at least in VS, have not looked at XS)

**Comment by dsyme** [comment]
Fixed
