### ISSUE TITLE
Regression in parameter info

### ISSUE THREAD

**Issue by dsyme** [Microsoft/visualfsharp#928]
There is a regression in parameter info when pressing "," .  It is probably due to an off-by-one error in comma location calculation in my PR #853.  Strangely it is not caught by existing unittests.

In both the examples below things work correctly with a vanilla install of Visual Studio 2015.  

Example 1: 

    let SomeFunction (a:int,b:int,c:int) = 1
    let x = SomeFunction (3,4,)   <- no parameter info when pressing "," here

Example 2:

    module Testing = 
        let SomeFunction(arg1,arg2,arg3) = 1

    let cfg40 = Testing.SomeFunction (abc,def, )   <- no parameter info when pressing "," here.

Interestingly when pressing ctrl-space just between ``def`` and the second comma, the latest bits show "arg3" while the VS2015 bits show "arg2".  That seems to indicate an off-by-one error.

**Comment by otawfik-ms** [comment]
Can this be closed?

**Comment by dsyme** [comment]
Yes, thanks!
