### ISSUE TITLE
Bogus mutation error related to type inference

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#934]
``` fsharp
type A<'t>(i : IEnumerator<'t>) = class end

type B<'t>(i) =
    inherit A<'t>(i)
    let x = i.Current
    let y = i.MoveNext() // error FS0256: A value must be mutable in order to mutate the contents or take the address of a value type, e.g. 'let mutable x = ...'

type B2<'t>(i : IEnumerator<'t>) =
    inherit A<'t>(i)
    let x = i.Current
    let y = i.MoveNext() // ok
```

See above, F# 4.0 compiler.

The only difference between `B` and `B2` is the type annotation in the ctor. The compiler successfully infers `IEnumerator` for `i` without the annotation (b/c it's passed to base ctor), but issues a bogus error if the annotation is missing.

**Comment by dsyme** [comment]
This is by design - the type of ``i`` is still a (constrained) variable type at the point where the method is invoked.
