### ISSUE TITLE
FSC allows bogus inheritance where FSI issues error

### ISSUE THREAD

**Issue by latkin** [Microsoft/visualfsharp#935]
``` fsharp
type A(i : int) = class end

type B = class inherit A end
```

In FSI I get an error that's not super clear but at least reminds me I'm doing something suspicious with omitting constructors: `error FS0193: Parent does not have a default constructor. The default constructor must be explicitly defined.`

FSC compiles this code without errors or warnings, though. There is no way to create an instance of `B`, but the code is verifiable.

Since `B` is fairly nonsensical it seems right to have an error.

**Comment by dsyme** [comment]
This by-design according to the F# language spec.  As you say the code is verifiable - there is no requirement to define a constructor on a class type in F#.

**Comment by dsyme** [comment]
(RefEmit seems to impose a limitation that a constructor of some kind is needed)
