### ISSUE TITLE
System.numerics.vectors package does not install properly

### ISSUE THREAD

**Issue by jackmott** [Microsoft/visualfsharp#939]
Visual Studio 2015 Update 1, using Nuget to install the System.numerics.vectors library results in an incomplete installation that must be repaired by hand.  The package works correctly on C# projects suggesting it may be a specific F# issue in visual studio.

Specifically this line should be added to the project file but is completely missing:

``` xml
 <Reference Include="System.Numerics.Vectors, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Numerics.Vectors.4.1.0\lib\net46\System.Numerics.Vectors.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

Internet sleuthing suggests others have been experiencing this for a few months, and that issue was reported to corefx team who closed it because they felt it wasn't their problem: https://github.com/dotnet/corefx/issues/3103

**Comment by forki** [comment]
Sounds like this issue belongs into NuGet repo.

Does it install properly using paket?

**Comment by jackmott** [comment]
Just gave paket a try. It looks like that works. I'll move this to Nuget.

**Comment by jackmott** [comment]
See this issue on nugets repot:
https://github.com/NuGet/Home/issues/1510

**Comment by forki** [comment]
Wow how can they close it?

**Comment by dsyme** [comment]
Closing as issue is in Nuget repository
