### ISSUE TITLE
MailboxProcessor.Receive() does not terminate when cancelled

### ISSUE THREAD

**Issue by dlbeer** [Microsoft/visualfsharp#940]
If a mailbox processor started with a cancellation token invokes `Receive()` with no timeout, cancellation of the token does not cause it to terminate.

In the following code example, the message "Terminated" is never printed:

``` fsharp
open System.Threading
let c = new CancellationTokenSource()
let m = MailboxProcessor.Start((fun inbox -> async {
    try
        printfn "Started"
        while true do
            let! s = inbox.Receive()
            printfn "Received %s" s
    finally
        printfn "Terminated"
  }), c.Token)

Thread.Sleep 100
c.Cancel()
Thread.Sleep 1000
```

Some changes that do cause the agent to terminate are:
- Making a dummy post to the mailbox after cancelling the token.
- Ensuring the token is cancelled before `Receive()` is invoked.
- Passing any timeout value >= 0 to `Receive()`.

I haven't investigated in-depth, but the last point suggests that the problem is in `Mailbox.waitOneNoTimeout()` in control.fs, as this method of waiting is only used when the timeout is unspecified. I note that other asynchronous primitives contain code to register actions with their given cancellation tokens, whereas this function does not.

This bug is present in the F# open-source repository as of commit 9f24461f0d1097235b75a09d473f375e707fad0a (8 Feb 2016), but it appears to have always been there.

**Comment by stmax82** [comment]
This seems to have been fixed in FSharp.Core 4.3.1.. it prints "Started" + "Terminated". Previous versions (4.2.3) only prints "Started".

**Comment by dsyme** [comment]
@stmax82 thanks!
