### ISSUE TITLE
Replace lkg fslex/fsyacc with FsLexYacc nuget package

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#959]
Use https://github.com/fsprojects/FsLexYacc nuget package instead of lkg fslex/fsyacc binaries.

Replace `utils/prim-{parsing,lexing}.{fs,fsi}` with the source `{Lexing,Parsing}.{fs,fsi}` in `FsLexYacc` (source should be in an additional nuget package).
The sources are used instead of depends `FsLexYacc.Runtime.dll` assembly.

**Comment by KevinRansom** [comment]
Done
