### ISSUE TITLE
Erratic performance issues with F# Interactive and compiled

### ISSUE THREAD

**Issue by mrakgr** [Microsoft/visualfsharp#965]
The discussion over this is now sharded across three different places: [Reddit thread](https://www.reddit.com/r/fsharp/comments/44j3vk/some_performance_testing_and_questions/), [SO page](http://stackoverflow.com/questions/35313448/is-f-interactive-supposed-to-be-much-slower-than-compiled/35325663#35325663), the [other Fsharp Github](https://github.com/fsharp/fsharp/issues/542) - but I will do my best to recount it here.

I've been using F# nearly six months for now, mostly writing performance intensive GPU applications, yet ironically I've never bothered benchmarking F# itself. A while ago, I did so and found some strange things in how FSI is acting. From [this benchmark](http://pastebin.com/2CuQQ4ne), I get roughly the following timings (Windows 10, VS2015, i5-4960k):

FSI (--optimize, script debugging on)
* reduce array = 50005284 - Time = 201
* for loop array = 50005284 - Time = 447
* Array.sum = 50005284 - Time = 173

FSI (--optimize, script debugging off)
* reduce array = 50006181 - Time = 134
* for loop array = 50006181 - Time = 253
* Array.sum = 50006181 - Time = 329

As one would expect the reduce function and the iterative loop is faster without the overhead from debugging, but strangely enough the Array.sum is much slower which makes very little sense.

Compiled (full optimizations, no debugging)
* reduce array = 50009709 - Time = 134
* for loop array = 50009709 - Time = 71
* Array.sum = 50009709 - Time = 78

The time it takes to sum 100M int elements in the [0,2) range is much faster for the compiled and other users have failed to reproduce the error.

There is also a very [similar benchmark](http://pastebin.com/E4d0gw04) that uncovered some more puzzling phenomena for me:

FSI (--optimize, script debugging on)
* reduce sequence of list, result 450015000, time 2261 ms
* reduce array, result 450015000, time 604 ms
* for loop array, result 450015000, time 580 ms
* reduce list, result 450015000, time 605 ms

FSI (--optimize, script debugging off)
* reduce sequence of list, result 450015000, time 1947 ms
* reduce array, result 450015000, time 402 ms
* for loop array, result 450015000, time 135 ms
* reduce list, result 450015000, time 405 ms

Compiled (full optimizations, no debugging):
* reduce sequence of list, result 450015000, time 2553 ms
* reduce array, result 450015000, time 403 ms
* for loop array, result 450015000, time 134 ms
* reduce list, result 450015000, time 405 ms

Reducing a sequence of list is slower in compiled that in interactive for some reason. An interesting thing happens when I try running the above with `fsi.exe` directly from the command line instead of `fsianycpu.exe` which is linked to the VS IDE.

* C:\Users\Marko\Documents\Visual Studio 2015\Projects\GVGAI-Fsharp\GVGAI-Fsharp>fsi -O --exec fs.fsx
* Total iterations: 300000000, Outer: 10000, Inner: 30000
* reduce sequence of list, result 450015000, time 1814 ms
* reduce array, result 450015000, time 407 ms
* for loop array, result 450015000, time 101 ms
* reduce list, result 450015000, time 404 ms

Hmmm, previously I consistently got 78ms with the for loop array. I only changed the entry a little...

Yeah, it seems that in the benchmark, removing the EntryPoint causes the for loop to be executed 20ms slower.

It might be tempting to blame this on background processes, but the performance from run to run is very consistent. `fsi.exe` is really quite a bit faster than `fsianycpu.exe` even though they are supposed to be even.

At any rate, removing the `-O` switch seems to be doing nothing, and the way performance acts for these benchmarks is very unintuitive, so much that I suspecting compiler bugs, though it might not turn out to be a big deal.

Also, in the test above, the compilation can be uneven, sometimes I get it to compile with 78ms for the for loop which happened when I started a fresh project just for this, but then it went to 134ms again.

If this is worth investigating further, I am willing to disassemble this thing to get to the bottom of this. In the future, these ms differences will get translated into hours when running some of the stuff that I wrote. I already had cases when one day the same thing will run consistently in 4s and the other in 3s. Back then I wrote it off as the GPU being too hot or maybe not being hot enough, but now I am thinking the issue is linked to the above.

Would it be possible to get assembly code from FSI somehow? I know there is a tool named ILDASM for binaries.

**Comment by drvink** [comment]
You can use [dnSpy](https://github.com/0xd4d/dnSpy) to save dynamic/in-memory modules while attached to a process, then use ildasm or other tools on the dumped assembly.

**Comment by mrakgr** [comment]
@drvink Loading .exe files is simple enough, but I have no idea how to load stuff from inside F# Interactive. Any advice?

**Comment by drvink** [comment]
I meant to reply when I saw your comment but forgot, sorry! I should have explained it better.

FSI adds types to an in-memory assembly for each evaluation you perform. Assemblies live in modules (in the Windows API sense--think `HINSTANCE`). If you attach to the `fsi.exe` or `fsiAnyCpu.exe` process from dnSpy and break into the debugger, then bring up the modules pane from the debug menu, you'll see all the modules mapped into the FSI process. Scroll to the one called `FSI-ASSEMBLY` and hit enter on it. Expand the `FSI-ASSEMBLY` module in the assembly explorer and then expand the empty namespace (`-`). The `FSI_nnnn` types are the ones generated by your evaluations!

File:Save Module will save the module to disk, and then you can fool with it with whatever tools you want.

**Comment by mrakgr** [comment]
Thanks for the reply. Actually, just now I realized that there is an attach to process option in Debug. I did not see it until now. Whops.

After your last post I decided to study IL assembly and am going through the Expert IL 2.0 Assembler book. I'll have an update to this issue in a few days.

**Comment by drvink** [comment]
There's also (Msiler)[https://visualstudiogallery.msdn.microsoft.com/60fc53d4-e414-461b-a27c-3d5d2a53f637], which is convenient for just viewing IL.

**Comment by mrakgr** [comment]
Done with the book and am trying out dnSpy. I am not sure I would have figured how to load the modules without your explanation above, though now I have a different problem. When I use `fsi.exe` I can see the modules properly and the evaluations they produce, but `fsianycpu.exe` which is the default in VS crashes the dnSpy along with the Interactive session. I am thinking of opening an issue on the dnSpy Github. Any ideas?

**Comment by drvink** [comment]
I've had it crash a few times on `fsiAnyCpu.exe`, but it seems to be more stable on `fsi.exe` (32-bit FSI). You can change which one gets used by F# Interactive in the VS options under `F# Tools`.

**Comment by mrakgr** [comment]
For this particular issue, I need to compare 32 and 64-bit versions, so I'll try to build dnSpy and take a look at the issue myself though I am not sure I'll be able to do much, but thanks anyway.

**Comment by mrakgr** [comment]
I am going through the examples step by step. The reason why Array.sum with script debugging off is slower is easy enough to guess.
            // loop start (head: IL_0162)
                /* 0x000004FD FE0C0500     */ IL_013D: ldloc     5
                /* 0x00000501 2803000006   */ IL_0141: call      int32[] FSI_0002::get_numsArray()
                /* 0x00000506 FE0C0600     */ IL_0146: ldloc     6
                /* 0x0000050A A31B000001   */ IL_014A: ldelem    [mscorlib]System.Int32
                /* 0x0000050F D6           */ IL_014F: add.ovf
                /* 0x00000510 FE0E0500     */ IL_0150: stloc     5
                /* 0x00000514 FE0C0600     */ IL_0154: ldloc     6
                /* 0x00000518 2001000000   */ IL_0158: ldc.i4    1
                /* 0x0000051D 58           */ IL_015D: add
                /* 0x0000051E FE0E0600     */ IL_015E: stloc     6

                /* 0x00000522 FE0C0600     */ IL_0162: ldloc     6
                /* 0x00000526 2803000006   */ IL_0166: call      int32[] FSI_0002::get_numsArray()
                /* 0x0000052B 8E           */ IL_016B: ldlen
                /* 0x0000052C 69           */ IL_016C: conv.i4
                /* 0x0000052D 3FCBFFFFFF   */ IL_016D: blt       IL_013D
            // end loop 
Here is the script debugging on version.
            // loop start (head: IL_017E)
                /* 0x0000072E FE0C0A00     */ IL_015A: ldloc     10
                /* 0x00000732 FE0C0900     */ IL_015E: ldloc     9
                /* 0x00000736 FE0C0B00     */ IL_0162: ldloc     11
                /* 0x0000073A A31B000001   */ IL_0166: ldelem    [mscorlib]System.Int32
                /* 0x0000073F D6           */ IL_016B: add.ovf
                /* 0x00000740 FE0E0A00     */ IL_016C: stloc     10
                /* 0x00000744 FE0C0B00     */ IL_0170: ldloc     11
                /* 0x00000748 2001000000   */ IL_0174: ldc.i4    1
                /* 0x0000074D 58           */ IL_0179: add
                /* 0x0000074E FE0E0B00     */ IL_017A: stloc     11

                /* 0x00000752 FE0C0B00     */ IL_017E: ldloc     11
                /* 0x00000756 FE0C0900     */ IL_0182: ldloc     9
                /* 0x0000075A 8E           */ IL_0186: ldlen
                /* 0x0000075B 69           */ IL_0187: conv.i4
                /* 0x0000075C 3FCDFFFFFF   */ IL_0188: blt       IL_015A
            // end loop 
In the first version (with script debugging off) Array.sum has extra function calls to get the array while in the on version above, the array is stored in local variables.

That explanation seems convincing to me at first glance, but it does not explain the for loop sums.
            // loop start (head: IL_00C4)
                /* 0x0000045F FE0C0400     */ IL_009F: ldloc     4
                /* 0x00000463 2803000006   */ IL_00A3: call      int32[] FSI_0002::get_numsArray()
                /* 0x00000468 FE0C0500     */ IL_00A8: ldloc     5
                /* 0x0000046C A31B000001   */ IL_00AC: ldelem    [mscorlib]System.Int32
                /* 0x00000471 58           */ IL_00B1: add
                /* 0x00000472 FE0E0400     */ IL_00B2: stloc     4
                /* 0x00000476 FE0C0500     */ IL_00B6: ldloc     5
                /* 0x0000047A 2001000000   */ IL_00BA: ldc.i4    1
                /* 0x0000047F 58           */ IL_00BF: add
                /* 0x00000480 FE0E0500     */ IL_00C0: stloc     5

                /* 0x00000484 FE0C0500     */ IL_00C4: ldloc     5
                /* 0x00000488 2803000006   */ IL_00C8: call      int32[] FSI_0002::get_numsArray()
                /* 0x0000048D 8E           */ IL_00CD: ldlen
                /* 0x0000048E 69           */ IL_00CE: conv.i4
                /* 0x0000048F 3FCBFFFFFF   */ IL_00CF: blt       IL_009F
            // end loop 
The above is with script debugging on (the slower variant).
            // loop start (head: IL_00CE)
                /* 0x0000067D FE0C0600     */ IL_00A9: ldloc     6
                /* 0x00000681 2803000006   */ IL_00AD: call      int32[] FSI_0002::get_numsArray()
                /* 0x00000686 FE0C0700     */ IL_00B2: ldloc     7
                /* 0x0000068A A31B000001   */ IL_00B6: ldelem    [mscorlib]System.Int32
                /* 0x0000068F 58           */ IL_00BB: add
                /* 0x00000690 FE0E0600     */ IL_00BC: stloc     6
                /* 0x00000694 FE0C0700     */ IL_00C0: ldloc     7
                /* 0x00000698 2001000000   */ IL_00C4: ldc.i4    1
                /* 0x0000069D 58           */ IL_00C9: add
                /* 0x0000069E FE0E0700     */ IL_00CA: stloc     7

                /* 0x000006A2 FE0C0700     */ IL_00CE: ldloc     7
                /* 0x000006A6 2803000006   */ IL_00D2: call      int32[] FSI_0002::get_numsArray()
                /* 0x000006AB 8E           */ IL_00D7: ldlen
                /* 0x000006AC 69           */ IL_00D8: conv.i4
                /* 0x000006AD 3FCBFFFFFF   */ IL_00D9: blt       IL_00A9
            // end loop 

I am not sure what to think of this. The two blocks seem pretty much the same apart from local variables referenced. I'll compare the above with the compiled version in the following post.

**Comment by mrakgr** [comment]
The compiled version is pretty much the same as the script with script debugging off version. Not what I expected at all given the large speed discrepancies. Whatever the case, it seems the performance differences are not due to generated IL at least in the case of the first benchmark.

So...I guess the difference is due to the JIT compiler acting differently with scripting and binaries then?
