### ISSUE TITLE
Add jenkins build by branch and os

### ISSUE THREAD

**Issue by enricosada** [Microsoft/visualfsharp#967]
Current jenkins ci builds `master` branch in `Debug` and `Release` configuration in `Windows`.
Like http://dotnet-ci.cloudapp.net/job/Microsoft_visualfsharp/job/release_windows_nt/

Others useful build configuration:

- OS: Windows/Macosx/Linux, because are needed by xplat (coreclr)
- branch: `master`, `coreclr`, `vs2015` are active branches built by appveyor

Proposed name in jenkins `branch_conf_osname` . Actual is `conf_osname`

ref [dotnet jenkins new new branch model](https://github.com/dotnet/cli/pull/1386#issue-133290544)

/cc @otawfik-ms @TyOverby

**Comment by otawfik-ms** [comment]
Branch is now included in the job as specified (example: 963)
I'll keep this open, because we still need to update the front page README.md when we have at least one jenkins build for every branch.
