### ISSUE TITLE
In a struct constructor, providing the name of the first argument causes a parse error.

### ISSUE THREAD

**Issue by mrakgr** [Microsoft/visualfsharp#971]
type Test =
        struct
        val queue : string
        val position : int * int
        new (queue, position) = {queue=queue;position=position}
        end

    Test(queue="asdf",position=(1,2))
To make the above work, I need to remove `queue=` on the first line. This seems like a bug to me.

**Comment by dsyme** [comment]
Strangely this is by design: the overloads are ambiguous between ``Test()`` and ``Test(queue,position)`` where in the first case the named arguments get assigned to the properties (this happens even though they are immutable).  Renaming the properties works correctly:

```
type Test =
    struct
      val x : string
      val y : int * int
      new (queue, position) = {x=queue;y=position}
    end

Test(queue="asdf",position=(1,2))
```

**Comment by mrakgr** [comment]
I am not sure I understand the explanation why this is not an error, but if this is by design then I guess it is fine. Maybe a more informative error message would be good?

**Comment by 0x53A** [comment]
@mrakgr In C#, you can set properties after calling a ctor with

    var x = new A(arg1, arg2) {prop1="val", prop2=2};

In F#, the equivalent code would be 

    type A(arg1, arg2) = ...
    let x = A(arg1, arg2, prop1="val", prop2=2)

**Comment by mrakgr** [comment]
Ah, I see. I do not have any C# experience as you guessed. It makes more sense now.
