### ISSUE TITLE
Installing F# SDK Tools to VS Experimental Instance 

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#975]
https://github.com/Microsoft/visualfsharp/blob/master/DEVGUIDE.md#4-optional-install-the-visual-f-ide-tools-and-clobber-the-f-sdk-on-the-machine

Instead of clobbering the machine wide installation of F# is it possible to install the VSIX and update the vsintegration in an experimental instance instead to remove the need to repair VS to go back to the release version of the SDK?

**Comment by cloudRoutine** [comment]
Or at the very least anything to avoid 
> Repairing Visual Studio 2015 is currently the only way to revert this step

as this can take several hours at worst

**Comment by dsyme** [comment]
This is a duplicate of https://github.com/Microsoft/visualfsharp/issues/232
