### ISSUE TITLE
VSIntegration is not updating FSI correctly

### ISSUE THREAD

**Issue by cloudRoutine** [Microsoft/visualfsharp#976]
After following [the instructions to use a WIP F# SDK](https://github.com/Microsoft/visualfsharp/blob/master/DEVGUIDE.md#4-optional-install-the-visual-f-ide-tools-and-clobber-the-f-sdk-on-the-machine)
the version of FSI in VS has not been correctly updated

![](http://i.imgur.com/x7LLNxd.png)

As you can see in the screenshot the VS language integration is working properly as there's no compiler error thrown on the definition of a struct record and the built version of FSI supports defining struct records, but this version of FSI is not what's being loaded in VS.

**Comment by KevinRansom** [comment]
The whole debugging and trying out an OSS build of F# from Visual Studio is quite unsatisfactory.  We should spend some time figuring out a better approach, I agree.
