### ISSUE TITLE
class extern method is different from module extern method.

### ISSUE THREAD

**Issue by sayurin** [Microsoft/visualfsharp#978]
Following code will be compile error.
```fsharp
open System.Runtime.InteropServices

module M =
    [<DllImport "Kernel32.dll">]
    extern bool GetExitCodeProcess(nativeint hProcess, uint32& lpExitCode);

type T() =
    [<DllImport "Kernel32.dll">]
    static extern bool GetExitCodeProcess(nativeint hProcess, uint32& lpExitCode);
    do
        let mutable exitCode = 0u
        M.GetExitCodeProcess(1234n, &exitCode) |> ignore  // ok
        GetExitCodeProcess(1234n, &exitCode) |> ignore    // error FS0412 and error FS0421
```

>  error FS0412: A type instantiation involves a byref type. This is not permitted by the rules of Common IL.
> error FS0421: The address of the variable 'exitCode' cannot be used at this point

class extern method did not work if the method has two or more parameters and an out parameter like `GetExitCodeProcess`. Its signature is like this.
```c
BOOL WINAPI GetExitCodeProcess(
  _In_  HANDLE  hProcess,
  _Out_ LPDWORD lpExitCode
);
```

In contrast, if the method has single parameter (like `time`), it works.
```F#
module M =
    [<DllImport "libc.so">]
    extern uint32 time(uint32& timer);

type T() =
    [<DllImport "libc.so">]
    static extern uint32 time(uint32& timer);
    do
        let mutable timer = 0u
        M.time(&timer) |> ignore  // ok
        time(&timer) |> ignore    // ok
```

**Comment by dsyme** [comment]
Class extern methods are not yet supported, see http://fslang.uservoice.com/forums/245727-f-language/suggestions/6343373-allow-defining-extern-methods-in-a-class
