### ISSUE TITLE
Creating overloads in a module with CompiledName fails if it's also the F# name of one of the functions

### ISSUE THREAD

**Issue by Tarmil** [Microsoft/visualfsharp#979]
Sorry if the title is confusing, the issue needs some explaining.

It is possible to compile module functions into .NET overloads using `[<CompiledName>]`:

```fsharp
module Logger =
    [<CompiledName "Log">]
    let LogMessage (msg: string) = Console.WriteLine msg

    [<CompiledName "Log">]
    let LogException (exn: exn) = Console.WriteLine (exn.ToString())
```

This is very convenient to create an API that is friendly for both F# and C# users. However, it fails if the overloaded name (here, `Log`) is also used as the F# name of one of the overloaded functions:

```fsharp
module Logger =
    [<CompiledName "Log">] // Or omit this attribute, the result is the same
    let Log (msg: string) = Console.WriteLine msg

    [<CompiledName "Log">]
    let LogException (exn: exn) = Console.WriteLine (exn.ToString())
    // Error: Duplicate definition of value 'LogException'
```

I think it should be possible to relax this.

**Comment by dsyme** [comment]
Please add to http://fslang.uservoice.com and put a link here 

I'll close this per CONTRIBUTING.md

thanks!
don
