### ISSUE TITLE
More Option functions

### ISSUE THREAD

**Issue by ploeh** [Microsoft/visualfsharp#980]
In the F# User Voice forum, there's [a suggestion to add various functions to the `Option` module](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6672880-add-a-option-getordefault-method-as-a-curryable-al). These include:

- `Option.getOrDefault : 'a -> 'a option -> 'a`
- `Option.map2: ('a -> 'b -> 'c) -> 'a option -> 'b option -> 'c option`
- `Option.map3: ('a -> 'b -> 'c -> 'd) -> 'a option -> 'b option -> 'c option -> 'd option`

I often find that I need better building blocks for option values, and while they're easy enough to define, I think it would make the F# language more productive if these fundamental functions were already present.

I'll be happy to write the tests and implementation and send a pull request for this, but I'm opening this issue first, in order to gauge the interest.

If there's interest, I'll get started on some pull requests, but if there's no interest, please close this issue and [the User Voice suggestion](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6672880-add-a-option-getordefault-method-as-a-curryable-al).

**Comment by smoothdeveloper** [comment]
Please consider reviewing @vasily-kirichenko answer in this user voice, there seems to be many other existing resources to draw from, should we prepare a RFC so we can discuss naming / signatures to greater extent?

Definitely agree that having more extensive support over `Option` in the core library makes lots of sense.

**Comment by dsyme** [comment]
Closing as this will go via UserVoice per CONTRIBUTING.md

**Comment by ploeh** [comment]
@dsyme, could you please advise how to move forward with these suggestions?

The [User Voice suggestion](https://fslang.uservoice.com/forums/245727-f-language/suggestions/6672880-add-a-option-getordefault-method-as-a-curryable-al) that I already linked to has been inactive for more than a year. In order to get the ball rolling, I wanted to restart the discussion.

The problems with User Voice are:

- The User Voice UI doesn't support code formatting. That makes it suboptimal to discuss code.
- You don't get any notifications when there are new comments (at least, I don't).

A GitHub issue solves these problems.

Per CONTRIBUTING.md I could have sent a pull request, since there already _is_ a User Voice suggestion. I did, however, consider that suggestion poorly specified, which is the reason I wanted to restart the discussion.

I am, as written above, offering to implement the `Option` features, but now I don't know how to proceed... Please advise.

**Comment by dsyme** [comment]
@ploeh I will mark the UV item as approved-in-principle which means we can open an RFC on it and have a really proper discussion about the Option module.

However the best way to help would then be to [volunteer to help do facilitation work on setting up RFCs for approved UV items, per my tweet here](https://twitter.com/dsyme/status/702537556387373057) :)  Basically I'd give you access to FSharpLangDesign to set up about 20-40 RFCs, one for each approved-in-principle issue, and then we as a community can get to work on the details and discussions.

**Comment by ploeh** [comment]
@dsyme I'll be happy to help to the best of my abilities. The process isn't entirely clear to me, though. Should I just take one of the documents at https://github.com/fsharp/FSharpLangDesign/tree/master/RFCs (e.g. https://github.com/fsharp/FSharpLangDesign/blob/master/RFCs/FS-1007-xxx.md), rename it in fill in the blanks?

If so, I'll be happy to do so.

**Comment by enricosada** [comment]
wait a bit @ploeh , i already done that for this issue :smile: 
https://github.com/fsharp/FSharpLangDesign/issues/60

@ploeh i'll push the RFC and a template RFC

**Comment by dsyme** [comment]
@ploeh  @enricosada Yes, basically, feel free to send a PR creating the RFC for any approved-in-principle issue.  First in first served.  If you want to grab the token then send one doing nothing but renaming the file, and then fill in the further details.
