### ISSUE TITLE
Structs with mutable properties inside containers can't be mutated

### ISSUE THREAD

**Issue by mrakgr** [Microsoft/visualfsharp#982]
type X =
        struct
        val mutable x : int
        val mutable y : int
        end

    let t = ResizeArray([|X();X();X()|])

    t.[0].x <- 5

The above example gives an error, though with plain arrays it works. Having the above work would be handy in ensuring [data locality](http://gameprogrammingpatterns.com/data-locality.html) in games. I am working on one and am forced to use an oversized plain array with a separate counter as a mutable variable for length. It could be done with reference types, but I am worried they would fragment the memory. Of course, in the game, the struct used for NPC state is significantly larger than 8 bytes.

I've run into this problem before in a different context and there structs could not be mutated through Item set.

Would making the above example work be doable?

**Comment by dsyme** [comment]
This is fundamental to the design of ResizeArray and in fact to the lack of byref returns in .NET IL.  The F# work for this to happen is covered by : https://fslang.uservoice.com/forums/245727-f-language/suggestions/11125137-expand-support-for-byref-to-match-c-7
