### ISSUE TITLE
Visual Studio vNext preview F# fails when installed to non-default location

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharp#987]
When a non default install path is selected for VS vNext, Visual Studio installs into the new path, and a few F# dll’s are installed into the default install location.  These files were previously installed in the Gac and when we moved them out of the GAC into PrivateAssebmlies, we specified the target path for installation incorrectly.

The list of files looks like:
![untitled](https://cloud.githubusercontent.com/assets/5175830/13367438/824af492-dc97-11e5-99c0-147b3af72c5b.jpg)

**Comment by otawfik-ms** [comment]
@KevinRansom  Fixed in VS Preview 4.
