### ISSUE TITLE
Running fsc.exe on OS X and Linux gives access error

### ISSUE THREAD

**Issue by NumberByColors** [Microsoft/visualfsharp#997]
How to repro:

- `dotnet new --lang f#` to install the F# compiler and core library
- On a Mac or Linux, run `/usr/local/share/dotnet/bin/corerun /usr/local/share/dotnet/bin/fsc.exe <required args> <Program.fs>` where `<required args>` includes references to the necessary libraries, and `<Program.fs>` is the program to compile. A single-line Hello World program has been verified to repro.

The error is:

```
Access to the path '/usr/local/share/dotnet/bin' is denied.
```

This issue was first discovered in [Issue #1405](https://github.com/dotnet/cli/issues/1405) in the dotnet CLI repo.

**Comment by NumberByColors** [comment]
@KevinRansom FYI your fix worked on my machine (replacing those F# files in /usr/local/share/dotnet/bin).

**Comment by thinkbeforecoding** [comment]
Can you give more info on the fix ?

**Comment by enricosada** [comment]
the development version of fsc works, the bundled with .net cli is old and contains the bug.
Build the repo or use built binaries https://github.com/enricosada/fsharp-dotnet-cli-samples/wiki/Status

**Comment by ctaggart** [comment]
@thinkbeforecoding You can try the docker image I created, but I'm dealing with another `Access to the path is denied` exception when using it from OS X, but not Linux. https://github.com/dotnet/corefx/issues/7091

**Comment by ctaggart** [comment]
@NumberByColors I think you can close this issue. It it has been fixed in more recent builds.
